### ISSUE TITLE
Drush 7 not finding Drupal 7 install.inc

### ISSUE THREAD

**Issue by brylie** [drush-ops/drush#1025]
When using drush 7 in a Drupal 7 codebase, I get the following error:

```
Drush command terminated abnormally due to an unrecoverable error.
[error]Error: require_once(): Failed opening required '/home/user/public_html/core/includes/install.inc'
```

A [stop-gap solution](http://drupal.stackexchange.com/questions/137432/failed-opening-install-inc-when-upgrading-drupal-7-x-core-with-drush-7-x/138433?iemail=1&noredirect=1#138433) has been suggested on stack exchange.

Is drush failing to detect the proper Drupal version here?

**Comment by jaypan** [comment]
Still seeing this in current drush

**Comment by doxigo** [comment]
As you can drush is trying to locate install.inc in /core/includes/ which is D8 structure not D7.

For now you can fix this issue by modifying [drush_directory]/commands/core/core.drush.inc file on line 1120 and remove /core/ from it.

**Comment by weitzman** [comment]
There are two instances of install.inc in core.drush.inc and they both have a constant in place which should be correct if Drush recognizes your site as Drupal 7. They are `include_once DRUSH_DRUPAL_CORE . '/includes/install.inc';`. Please verify that you have latest Drush and that core.drush.inc has this constant and that its value is `''` for D7.
