### ISSUE TITLE
PHP Fatal error when trying to download projects

### ISSUE THREAD

**Issue by imperator99** [drush-ops/drush#1026]
Using Drush 7.0-alpha7 on Drupal 7.34, I am getting the following error when I try to download a project (specifically, menu_import - but I have tried with other projects and get the same error):

<pre>PHP Fatal error:  Call to a member function selectReleaseBasedOnStrategy() on a non-object in /Applications/DevDesktop/drush/vendor/drush/drush/commands/pm/download.pm.inc on line 111

Fatal error: Call to a member function selectReleaseBasedOnStrategy() on a non-object in /Applications/DevDesktop/drush/vendor/drush/drush/commands/pm/download.pm.inc on line 111
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Call to a member function selectReleaseBasedOnStrategy() on a
non-object in
/Applications/DevDesktop/drush/vendor/drush/drush/commands/pm/download.pm.inc,
line 111</pre>

I have tried to debug it myself but I don't know enough about Drush (and PHP more generally) to get very far. It does appear that the minor version for the project isn't being discovered, so when Drush tries to perform the request the <code>selectReleaseBasedOnStrategy()</code> function fails as <code>$version</code> is null.

**Comment by luksak** [comment]
Still getting this error. I am using Dev Desktop as well but installed Drush via composer. Here is the error message:

```
Fatal error: Call to a member function selectReleaseBasedOnStrategy() on a non-object in /.composer/vendor/drush/drush/commands/pm/download.pm.inc on line 111
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Call to a member function selectReleaseBasedOnStrategy() on a
non-object in
/.composer/vendor/drush/drush/commands/pm/download.pm.inc,
line 111
```

**Comment by luksak** [comment]
Any news on this?

**Comment by luksak** [comment]
I filed several bug reports because of different issues for Acquia Dev Desktop. I didn't get one single reply. I also don't understand why this issue is closed. This bug obviously still exists.

**Comment by weitzman** [comment]
Its closed because there are no steps to reproduce using master branch. Also the bug must exist without Dev Desktop to be open here.

**Comment by luksak** [comment]
Ok. Do you know if anyone at Acquia is aware of this bug?
