### ISSUE TITLE
Drush doesn't pick up on modules it downloaded in 8.x

### ISSUE THREAD

**Issue by brianV** [drush-ops/drush#104]
drush dl downloads the project to the correct folder in d8, but drush en doesn't find it.

    brian@brian-MS-7599:~/Workspace/drupal$ drush dl devel 
    Project devel (8.x-1.x-dev) downloaded to modules/devel. [success] 
    Project devel contains 3 modules: devel_generate, devel_node_access, devel.   
    brian@brian-MS-7599:~/Workspace/drupal$ drush en devel
    devel was not found. [warning] 
    The following projects provide some or all of the extensions not found: [ok] 
    devel 
    Would you like to download them? (y/n): y 
    Install location modules/devel already exists. Do you want to overwrite it? (y/n): y 
    Project devel (8.x-1.x-dev) downloaded to modules/devel. [success] 
    Project devel contains 3 modules: devel_generate, devel_node_access, devel. devel was not found. [warning] 
    The following projects provide some or all of the extensions not found: [ok] devel     
    Would you like to download them? (y/n):

**Comment by bradjones1** [comment]
I can vouch for the original bug report. Drush will download the module (or, in my case, theme) to the proper directory in the present install, however when it goes to enable the module it doesn't discover the just-downloaded files. If you ctrl-C out of the operation and then do a drush en -y just-downloaded, it works as expected.

**Comment by jonhattan** [comment]
@bradjones1 It seems you're suffering #5. The issues reported in the other comments above are already fixed.
