### ISSUE TITLE
Refresh status before update

### ISSUE THREAD

**Issue by barryvdh** [drush-ops/drush#1048]
I maintain multiple Drupal websites, so when an update comes out, I want to patch all of the sites quickly. Drush helps with this very good :)

But many sites are set to check every 24 hour for updates. So when I run the `drush pm-update` command, the data is not always refreshed. I can run `pm refresh` first, but isn't it more logical that data get's refresh automatically when updating? Or perhaps add a `--refresh` flag so it will be refresh first?

**Comment by greg-1-anderson** [comment]
`pm-*` commands are maintenance only; closing.
