### ISSUE TITLE
`drush cr` in fresh Drupal 8 install results in Missing $settings['hash_salt'] in settings.php

### ISSUE THREAD

**Issue by shrop** [drush-ops/drush#1050]
`drush cr` in fresh Drupal 8 install results in Missing $settings['hash_salt'] in settings.php

Below is the full trace after the errors. I have tried a few installs of Drupal 8.0.0-beta3 and continue to get the same results. I am running php 5.5.

exception 'RuntimeException' with message 'Missing $settings['hash_salt'] in settings.php.' in /Users/shrop/Projects/www/core/lib/Drupal/Core/Site/Settings.php:130                   [error]
Stack trace:
#0 /Users/shrop/Projects/www/core/lib/Drupal/Core/PhpStorage/PhpStorageFactory.php(47): Drupal\Core\Site\Settings::getHashSalt()
#1 /Users/shrop/Projects/www/core/includes/utility.inc(35): Drupal\Core\PhpStorage\PhpStorageFactory::get('service_contain...')
#2 /Users/shrop/bin/drush/commands/core/cache.drush.inc(278): drupal_rebuild(Object(Composer\Autoload\ClassLoader), Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: drush_cache_rebuild()
#4 /Users/shrop/bin/drush/includes/command.inc(359): call_user_func_array('drush_cache_reb...', Array)
#5 /Users/shrop/bin/drush/includes/command.inc(210): _drush_invoke_hooks(Array, Array)
#6 [internal function]: drush_command()
#7 /Users/shrop/bin/drush/includes/command.inc(178): call_user_func_array('drush_command', Array)
#8 /Users/shrop/bin/drush/lib/Drush/Boot/DrupalBoot.php(46): drush_dispatch(Array)
#9 /Users/shrop/bin/drush/drush.php(76): Drush\Boot\DrupalBoot->bootstrap_and_dispatch()
#10 /Users/shrop/bin/drush/drush.php(16): drush_main()
#11 {main}

**Comment by torstenzenk** [comment]
Having a hash salt string within settings.php and using the latest drush-master und D8-beta9 i get this error when i se drush cr:
exception 'RuntimeException' with message 'Missing $settings['hash_salt'] in settings.php.' in                                                           [error]
/mysite/core/lib/Drupal/Core/Site/Settings.php:130
Stack trace:
#0 /mysite/core/lib/Drupal/Core/PhpStorage/PhpStorageFactory.php(47): Drupal\Core\Site\Settings::getHashSalt()
#1 /mysite/core/includes/utility.inc(53): Drupal\Core\PhpStorage\PhpStorageFactory::get('service_contain...')
#2 /home/me/.composer/vendor/drush/drush/commands/core/cache.drush.inc(282): drupal_rebuild(Object(Composer\Autoload\ClassLoader),
Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: drush_cache_rebuild()
#4 /home/me/.composer/vendor/drush/drush/includes/command.inc(368): call_user_func_array('drush_cache_reb...', Array)
#5 /home/me/.composer/vendor/drush/drush/includes/command.inc(219): _drush_invoke_hooks(Array, Array)
#6 [internal function]: drush_command()
#7 /home/me/.composer/vendor/drush/drush/includes/command.inc(187): call_user_func_array('drush_command', Array)
#8 /home/me/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(62): drush_dispatch(Array)
#9 /home/me/.composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#10 /home/me/.composer/vendor/drush/drush/drush.php(11): drush_main()
#11 {main}
Are there any solutions or recommendations on this issue?

**Comment by kenorb** [comment]
Just add:

    $settings['hash_salt'] = 'CHANGE_THIS';

into `settings.php` or `settings.local.php`

**Comment by ferdly** [comment]
Here is a really good article that explains the good advice by @kenorb: [Drupal Easy](https://www.drupaleasy.com/quicktips/getting-drupal-8-pantheon-site-up-running-locally-acquia-dev-desktop) -- specifically from a Pantheon POV

**Comment by therobyouknow** [comment]
@kenorb thank you that worked: for https://github.com/drush-ops/drush/issues/1050#issuecomment-203484066

> Just add:
> 
> `$settings['hash_salt'] = 'CHANGE_THIS';`
> 
> into your settings.php or settings.local.php file.
> 

I then ran drush cr when in mysite.dev/web and the command completed without the error. I can also visit the mysql.dev and now longer get unexpected error please try later error.

Thank you.

**Comment by cleverington** [comment]
Can confirm it works and is pretty much needed for Pantheon -> Acquia DevDesktop on Windows

I had to drop-tables and re-import and _then_ cache-rebuild though.

**Comment by charlieartist** [comment]
@cleverington I had to make that change running Drupal 8.3.x and DevDesktop, as well, although I believe it would have been the same for other local dev environments. Luckily, though, I didn't need to drop the DB and reimport.

**Comment by carnnia** [comment]
in drupal 8.4.2 multi-site with drush installed locally via composer:
while in /var/www/public/d8/sites/carnnia.local 
../../vendor/bin/drush status  gives 
 Drupal Settings File   :  MISSING
i think it is trying to look in default directory for settings.php

**Comment by greg-1-anderson** [comment]
@carnnia Your problem above is unrelated to the things discussed in this closed issue. Please open a new issue, and compare behavior of Drush 8.1.15 with Drush 9.0.0-beta9 with your site.

**Comment by loopy3025** [comment]
I can confirm that this error also triggers sometimes when Drupal can't find the settings file. It happened to me when I wasn't referencing settings.local.php from my settings.php correctly. It is somewhat different in drupal 8 than drupal 7.

**Comment by paul94010** [comment]
I am now having this problem with Drupal 8.5.1 and Drush 9.2.1.   I don't understand where the hash salt comes from.   It is not on any settings.php files in any version of Drupal 8 that I am running.  Who supplies it and when in the process.   And maybe a bigger question is "why this added complexity".

**Comment by pimduijst** [comment]
I am having this issue as well on a clean D8.5.1 install with Drush 9.2.3. Maybe the most strange thing is that I do have a $settings['hash_salt'] value set...

**Comment by amritms** [comment]
Same here, Fresh drupal 8.5.1 install via composer with drush 9.2.3. I have long hash value in $settings['hash_salt']

**Comment by davidjguru** [comment]
Well, I'm having the same issue with a multisite instalation after launch drush cr  :-/ 
I can confirm that I have hash_salt registered in all occurrences of settings.php
So, what's the problem? What settings are Drush Lookin' for...?
**drush status**
 Drupal version : 8.5.3                                                   
 Site URI       : default                                                 
 PHP binary     : /usr/bin/php7.2                                         
 PHP config     : /tmp/LCIcHO                                             
 PHP OS         : Linux                                                   
 Drush script   : /usr/local/bin/drush                                    
 Drush version  : 9.3.0                                                   
 Drush temp     : /tmp                                                    
 Drush configs  : /var/www/html/dp_multisite/vendor/drush/drush/drush.yml 
 Drupal root    : /var/www/html/dp_multisite                              
 Site path      : sites/default

**Comment by davidjguru** [comment]
Ok, that's my fault xD ...When you're using drush cr in a multisite installation, you have to launch the order within a project folder. Drush cr goes to look for the specific database related with the project and if you are in the global multisite folder, there is no database there xD. Ok. 
Launching the drush cr within a project folder, everything is ok. The message goes out.

**Comment by ryanblackmore** [comment]
I've installed Drupal 8 with composer, arranged my sites/ folder for multisite and immediately encountered this problem. Drush gives the missing salt error even within when ran in a site folder. However, Drush will work by using the --uri= argument:
`$ drush --uri=example.com cr`

**Comment by venkatadapa** [comment]
Add below line of code in either settings.php or settings.local.php, This was solved the same error for me. Basically we need to set some hash salt for more security and it will be used in string encryption like password.  
  $settings['hash_salt'] = 'SOMESTRING';

**Comment by brightbold** [comment]
Another reason you might get this error: if you're in a Lando container (Pantheon recipe in my case) and you accidentally typed `drush cr` instead of `lando drush cr`.

**Comment by carnnia** [comment]
i don't have this issue when i setup a d8 site using /sites/default. 
but when trying to setup multi-site:
sites/site1.local
sites/site2.local
...
if i copy sites/default to sites/site1.local after site install, then the issue with the hash_salt happens.
if i create sites/site1.local and go through the installation procees then:
 /var/www/my-dev-work/web/sites/site1.local   drush cr
 [success] Cache rebuild complete.

**Comment by tarekdj** [comment]
If your are in a multisite context execute the drush command inside the proper site folder.

**Comment by Salah-1** [comment]
Similar to @carnnia 
I was getting the error [Missing $settings['hash_salt'] in settings.php line 146] when i do drush commands such as cache clear or site-install.
**Solution**:
Is to copy the sites.php and then remove settings.php in /defaults folder if you have it.

cp sites/example.sites.php  sites/YOUR-NEW-SITE/sites.php (read the core/INSTALL.txt)
Hope it helps someone
I know its not related to the main issue discussed but people are landing here from google search like me.

**Comment by oprogramador** [comment]
For me it also fails.

- I cloned the Drupal repo (http://git.drupal.org/project/drupal.git with the d99b12fb9e7a6c07db49bb2eba0d465f88cd9fc7 commit)
- I run `composer install`
- I run `composre require drush/drush`
- I added the following code to `sites/default/default.settings.php` after `$databases = [];` (removing `$settings['hash_salt'] = '';`):
```
$databases['default']['default'] = [
  'database' => 'foo',
  'username' => 'user',
  'password' => 'pass',
  'host' => 'localhost',
  'port' => '3306',
  'driver' => 'mysql',
  'prefix' => '',
  'collation' => 'utf8mb4_general_ci',
];
$settings['hash_salt'] = 'ZDE0YjYxZDI2MDNkZWNjNTY0YzZiMDc0';
```
- I have the following error for `drush cr`:
```
⟩ ./vendor/bin/drush cr

In Settings.php line 196:
                                                   
  Missing $settings['hash_salt'] in settings.php.  
```
- my environment:
```
⟩ ./vendor/bin/drush status
 Drupal version : 9.2.0-dev                                               
 Site URI       : http://default                                          
 PHP binary     : /usr/bin/php7.4                                         
 PHP config     : /etc/php/7.4/cli/php.ini                                
 PHP OS         : Linux                                                   
 Drush script   : /home/pierre/fooproject/vendor/dr 
                  ush/drush/drush                                         
 Drush version  : 10.3.6                                                  
 Drush temp     : /tmp                                                    
 Drush configs  : /home/pierre/fooproject/vendor/dr 
                  ush/drush/drush.yml                                     
 Drupal root    : /home/pierre/fooproject           
 Site path      : sites/default
 ```

**Comment by oprogramador** [comment]
for me, `drush cr` worked after `cp sites/default/default.settings.php sites/default/settings.php`

**Comment by greg-1-anderson** [comment]
Folks, please be sure that your `$settings['hash_salt']` is set to a random unguessable string. If you skip this step, your one-time-login links will not be secure.

**Comment by rhyoharianja** [comment]
Sorry, may be this reply pass for 1 year. but, i ever face same issue $settings['hash_salt'] even I've been set in settings.php or settings.local.php. But, I found and fix the problem with server user : group access. Coz, when I run drush cr with different user group then settings.php or with simple sentence "permission denied". 
How to fix : use same user / group on execute drush command with settings.php access level or in the other mean make settings.php can be access / read by drush command

**Comment by Sandra-headscape** [comment]
also make sure you're not using `require_once` or `include_once` as that might also cause it to not populate the settings from a sub file (as I learned  😅  while migrating to d10/drush 12.1)

**Comment by Sandra-headscape** [comment]
also make sure you're not using `require_once` or `include_once` as that might also cause it to not populate the settings from a sub file (as I learned  😅  while migrating to d10/drush 12.1)
