### ISSUE TITLE
Requesting feature to back up config prior to uninstall

### ISSUE THREAD

**Issue by amyq** [drush-ops/drush#1052]
Moving this request from an internal discussion (SI-423) to this ticket, per Moshe's request. The relevant part:

> The most actionable thing ... is the desire for a feature will backs up your config before uninstall. Extra nice would be an option to re-enable the module, and then import the old config back into the site. I think that I could add this to core Drush. Then someone could make a UI for it.
> 
> I asked on IRC - this module/feature does not exist yet.

**Comment by weitzman** [comment]
We got on OK without this
