### ISSUE TITLE
datestamp added by drush make should be date of commit

### ISSUE THREAD

**Issue by lkmorlan** [drush-ops/drush#1059]
drush make adds a datestamp line to the info file based on the date that drush make ran. It would be more useful if it instead used the date of the commit. This would be particularly helpful when checking out a -dev version because on the "Available updates" page, it would show the date of the -dev version.

**Comment by danepowell** [comment]
This would also be good because currently the datestamp changes every time you run drush make. This plays havoc if you are trying diff the output with an existing build or push it into a git repo.

**Comment by danepowell** [comment]
note, I am aware of the "no-gitinfofile" switch, but I need to keep the version in the info file in order to resolve versioned dependencies between modules. I just want to see the datestamp pinned or removed altogether.

**Comment by danepowell** [comment]
I'm working on a fix for this here, but haven't had time to test it:
https://github.com/danepowell/drush/tree/feature/git-datestamp

**Comment by CashWilliams** [comment]
@jhedstrom are you ok with this approach before we continue pursuing it?

**Comment by danepowell** [comment]
Maybe just opening a PR is the best way to get visibility on this: #1190

**Comment by danepowell** [comment]
PR was merged, I think this can be closed. Thanks!

**Comment by lkmorlan** [comment]
Thank you!
