### ISSUE TITLE
Drush master does not update a drupal 8 install

### ISSUE THREAD

**Issue by gabooh** [drush-ops/drush#1062]
I have a drupal 8 beta 3 install. And an up to date drush master install.
I want to update it to latest beta, beta4.

I do drush pm-refresh then drush pm-releases which says :

    Project  Release      Date         Status      
    drupal   8.0.0-beta4  2014-Dec-17  Supported   
    drupal   8.0.x-dev    2014-Dec-17  Development 
    drupal   8.0.0-beta2  2014-Oct-15  Security

But drush up does not perform the update :

    Update information last refreshed: jeu, 12/18/2014 - 16:25
    Name    Installed Version  Proposed version  Message                
    Drupal  8.0.0-dev          8.0.0-dev         Mise à jour disponible 
        
    No code updates available.

Is it confused by the version names ?

**Comment by jonhattan** [comment]
Fixed in 87e048ae98e47421ed53eb4a621e0668bf3d3d47

**Comment by gabooh** [comment]
It works now, thanks :)
