### ISSUE TITLE
`drush watchdog-show` multiple severity levels

### ISSUE THREAD

**Issue by echernyavskiy** [drush-ops/drush#1069]
This issue is to propose support for specifying multiple watchdog severity levels on the command line when issuing `drush ws` along with support for negating a particular severity level:

```
drush ws --severity=notice,warning,error
drush ws --severity=~debug,~info
drush ws --severity=-debug
```

Negation would be supported via both "-" and "~".

The use case for this issue comes from the desire to be able to sprinkle watchdog log statements across the codebase in case there's a need for a step-by-step paper trail of things happening, but at the same time support the capability for drush to only display the relevant messages when we don't care about "debug".

Would such functionality be welcomed?

**Comment by jasonellington** [comment]
This is awesome, was it never added? :(

**Comment by greg-1-anderson** [comment]
Looks like this was never added.  However, Drush now uses [filter-via-dot-access-data](https://github.com/consolidation/filter-via-dot-access-data) to allow flexible filtering based on arbitrary table columns. For example:
```
drush watchdog-show --filter='severity~=#(Notice|Info)#
```
In that example, `~=` means "match by regular expression", and the regular expression matches on "Notice or Info".  You could also use `--filter='severity*=o'` to show any row whose severity contains an "o" (`*=` means "contains").

If someone had an idea for a shorthand for a comma-separated list of values, a PR in filter-via-dot-access-data would be welcome. Another idea is that `--severity` is already being converted into a `--filter` equivalent; severity with a value containing a comma could be automatically converted into the equivalent filter regex.

**Comment by YurkinPark** [comment]
Still need in this stuff. `--filter` works illegal in cases of severity: it fetches last `10` messages and apply filter for them (in case you have not provided `--count` with more value). `--severity` apply its filter value exact during query to DB.
