### ISSUE TITLE
pm-updatestatus always throws errors for custom modules

### ISSUE THREAD

**Issue by pfrenssen** [drush-ops/drush#1073]
I'm using a cron job to periodically check all Drupal sites on a server for security updates and notify the maintenance team about them:

```
locatedrupal | xargs -i{} sh -c 'RESULT=`drush --root={} ups --security-only --pipe`; if [ -n "$RESULT" ] ; then echo -e "\n{}" ; echo "$RESULT" ; fi
```

The problem is that the following error occurs for custom modules, and this causes notifications to be sent.

> No release history was found for the requested project

I don't want to suppress any errors, and the `--lock` option does not help in this case, since the errors are thrown before the locks are checked in `drush_pm_updatestatus()`:

```
function drush_pm_updatestatus() {
  ...
  $update_info = $update_status->getStatus($projects, $check_disabled);
```

`StatusInfoDrush::getStatus()` then optionally filters out disabled modules, and instantiates a `\Drush\UpdateService\Project` object for each module. In the constructor of this object the error is thrown for all projects without release history.

Looking at how this is made, wouldn't it be better if `\Drush\UpdateService\Project` would throw exceptions rather than directly logging errors? At least exceptions we can catch if the errors are expected such as in this case.

**Comment by jonhattan** [comment]
I'd like to properly fix this

**Comment by greg-1-anderson** [comment]
`pm-*` commands are maintenance only; closing.
