### ISSUE TITLE
Attempt to use global httpserver installation

### ISSUE THREAD

**Issue by orlitzky** [drush-ops/drush#1074]
The `drush-runserver` command attempts install and use a snapshot of the `httpserver` program in the drush `lib/` directory. It may be the case that the user has `httpserver` installed globally, under e.g. `/usr/share/php`, just like we might find `PEAR-Console_Table` there.

Would it be possible to check whether or not `httpserver.php` can be `require`d before attempting to download a new copy? Something like,

```php
try {
  include('httpserver/httpserver.php');
}
catch {
  // Do the whole download and install thing
}
```
```

**Comment by weitzman** [comment]
Dont think we will amke that change on drush6 branch. drush7 works with its own dependencies and composer autoloader.

**Comment by orlitzky** [comment]
Will it be possible to install drush-7.x __without__ composer? I maintain the drush Gentoo package, and our current install method is a glorified `cp -r` which works great with drush-6.x. Requiring an autoloader is fine, as long as it doesn't depend solely on the autoloader that composer generates, because that won't exist if drush is installed through our package manager.

**Comment by weitzman** [comment]
I'm not aware of a way to do that. You'd have to generate an autoload.php via some other means.

**Comment by orlitzky** [comment]
Well that's sad! Anyone using a distribution package manager is going to be unable to use drush7. If an autoload.php is required for drush to work, it should come with drush. It's not like there's an easy way for us to generate one. The only way is to actually *install* the package using composer, which is the one thing we can't do.
