### ISSUE TITLE
Can't rebuild cache with drush 7 in D8

### ISSUE THREAD

**Issue by edxxu** [drush-ops/drush#1075]
I am using Drush 7, and after upgrading drupal core from beta3 to beta4, i can't rebuild cache with drush.  the following is the error code:
<em class="placeholder">Warning</em>: Missing argument 3 for Drupal\Core\Site\Settings::initialize(), called in /home/edxxu/drush/commands/core/cache.drush.inc on line 269 and defined in <em class="placeholder">Drupal\Core\Site\Settings::initialize()</em> (line <em class="placeholder">99</em> of <em class="placeholder">/var/www/drupal8/public_html/core/lib/Drupal/Core/Site/Settings.php</em>).PHP Fatal error:  Call to a member function get() on a non-object in /var/www/drupal8/public_html/core/lib/Drupal.php on line 575
PHP Stack trace:
PHP   1. {main}() /home/edxxu/drush/drush.php:0
PHP   2. drush_main() /home/edxxu/drush/drush.php:16
PHP   3. Drush\Boot\DrupalBoot->bootstrap_and_dispatch() /home/edxxu/drush/drush.php:76
PHP   4. drush_dispatch() /home/edxxu/drush/lib/Drush/Boot/DrupalBoot.php:46
PHP   5. call_user_func_array() /home/edxxu/drush/includes/command.inc:178
PHP   6. drush_command() /home/edxxu/drush/includes/command.inc:178
PHP   7. _drush_invoke_hooks() /home/edxxu/drush/includes/command.inc:210
PHP   8. call_user_func_array() /home/edxxu/drush/includes/command.inc:359
PHP   9. drush_cache_rebuild() /home/edxxu/drush/includes/command.inc:359
PHP  10. Drupal\Core\Site\Settings::initialize() /home/edxxu/drush/commands/core/cache.drush.inc:269
PHP  11. _drupal_error_handler() /home/edxxu/drush/commands/core/cache.drush.inc:107
PHP  12. _drupal_error_handler_real() /var/www/drupal8/public_html/core/includes/bootstrap.inc:867
PHP  13. _drupal_log_error() /var/www/drupal8/public_html/core/includes/errors.inc:77
PHP  14. Drupal::theme() /var/www/drupal8/public_html/core/includes/errors.inc:128
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Call to a member function get() on a non-object in
/var/www/drupal8/public_html/core/lib/Drupal.php, line 575

**Comment by joaogarin** [comment]
Hello,

I am having this issue with latest beta of drupal (beta7) and latest of drush from github. Is this suposed to be fixed?

Error is the following : 

Missing argument 3 for Drupal\Core\Site\Settings::initialize(), called in /Users/joaogarin/drush/commands/core/cache.drush.inc on line 269
