### ISSUE TITLE
Can't install drush 7 via latest composer 

### ISSUE THREAD

**Issue by edxxu** [drush-ops/drush#1077]
My composer version is 1.0-dev (095dc6129550de93cd98170c8e6c6ccd4558e983) 2014-12-29 20:29:13. And i tried to install drush 7 through "composer global require drush/drush:dev-master" command, there is no error while installing, but when i type "drush" command, the output is ": No such file or directory". So i delete vender folder under .composer folder, and tried to install drush 6 through "composer global require drush/drush:6.*" command, it works well.

**Comment by RobLoach** [comment]
Set this up in [Dockie](http://github.com/robloach/dockie) with [the following](https://github.com/RobLoach/Dockie/blob/master/dockie/Dockerfile#L78):

``` bash
composer global require drush/drush:~7.0.0@alpha
drush --version
```
Also important to load `~/.composer/vendor/bin` into your PATH so that Composer binaries can be found.

**Comment by edxxu** [comment]
@RobLoach Thanks, it works now.
