### ISSUE TITLE
pm-update backup directory error

### ISSUE THREAD

**Issue by goodwillhinton** [drush-ops/drush#1078]
I am attempted to update a contrib module  with "drush pm-update" and am getting the following error message:
>Backup directory /home/xxx/public_html/backup found. It's a security risk to store backups inside the Drupal tree. Drush now uses by default              [error]
~/drush-backups. You need to move /home/xxx/public_html/backup out of the Drupal tree to proceed. Note: if you know what you're doing you can explicitly
set --backup-dir to /home/xxx/public_html/backup and continue.

I have tried setting the --backup-dir to a directory in in /home/xxx but I keep getting error messages. Any suggestions on how to resolve this problem? Thx.

**Comment by jonhattan** [comment]
you want to remove `/home/xxx/public_html/backup`
