### ISSUE TITLE
pear install drush/drush installs outdated v6.2

### ISSUE THREAD

**Issue by yamlfd** [drush-ops/drush#1079]
Why is this not always installing the latest version? When can I install 6.5 this way?

**Comment by greg-1-anderson** [comment]
It doesn't look like anyone is maintaining the pear install any longer.  The recommended way to install Drush 6 is composer.  Read the installation instructions for the master branch for Drush; they contain information on how to install Drush 6 as well.

**Comment by greg-1-anderson** [comment]
I should not have closed this.  We need to figure out if Pear is supported or not.  If someone is still building packages, then a new one should get pushed out.  If not, we should update the README in the 6.x branch.  I don't think we can just point it to Read The Docs, but perhaps we can copy in the composer installation instructions.

**Comment by yamlfd** [comment]
I have no idea what is required to get the pear download, but it would be great if it works, too.

**Comment by weitzman** [comment]
Let's remove the PEAR instructions from 6.x branch and call it dead. Pear releases are not automated like Packagist releases. Folks who run 6.x and don't like Composer are welcome to do a Manual install.

**Comment by greg-1-anderson** [comment]
I updated the README for the 6.x branch to remove the instructions for PEAR, and replace them with the instructions for Composer.

**Comment by FiableDotBiz** [comment]
It's not completely finished: the "pear" method is still the one recommended on
https://github.com/drush-ops/drush/tree/6.x-fulltest
section "NSTALL - PEAR".
It's a pity this method doesn't work any more. It's quite complicated to install Drush now.
Moreover, it would be a good idea to explain in a few words what "Composer" is, since you ask us to install it.
