### ISSUE TITLE
Running 'drush field-info' and select any of the options returns error

### ISSUE THREAD

**Issue by tadityar** [drush-ops/drush#1080]
using 'field-info' command returns an error
if 'types' is selected the error is : Fatal error: Call to undefined function field_info_field_types() in /usr/local/bin/drush/commands/core/field.drush.inc on line 316

if 'fields' is selected the error is : Fatal error: Call to undefined function field_info_fields() in /usr/local/bin/drush/commands/core/field.drush.inc on line 301

**Comment by weitzman** [comment]
Dupe of #1194
