### ISSUE TITLE
How can Unish test a contrib module without downloading it as part of the test?

### ISSUE THREAD

**Issue by TravisCarden** [drush-ops/drush#1083]
I'm trying to write Unish tests for my contrib module, and I can't figure out how to correctly get my module included in the sandbox site such that I can enable it. Devel module currently runs a `drush dl` inside the test to get itself from Drupal.org, with the understated `@todo` comment, "It is not ideal to download yourself in your own tests." Obviously having to push code to d.o to test it renders the whole process worthless for test-driven development. Has this problem been solved?

**Comment by weitzman** [comment]
Just pushed a commit which fixes this for devel - http://cgit.drupalcode.org/devel/commit/?id=cc910acc703c170e3354acef988b27fb4c9b5f99

**Comment by TravisCarden** [comment]
Perfect! Thanks so much!!
