### ISSUE TITLE
Pending update for webform not being reported correctly in drush 7 pm-updatestatus

### ISSUE THREAD

**Issue by mariagwyn** [drush-ops/drush#1084]
Ran:
```drush7 pm-updatestatus```

The following was returned for webform:
``` Webform (webform)                        6.x-3.19           6.x-3.19          SECURITY UPDATE available```

It finds that a security update is available, but gets the numbers wrong, it should be 6.x-3.21.  As a result, it does not update the code.

**Comment by mariagwyn** [comment]
Same issue with og_menu:
```OG Menu (og_menu)                                6.x-2.4            6.x-2.4           SECURITY UPDATE available```
Should be version 6.x-2.6

**Comment by weitzman** [comment]
I can confirm the problem with webform module. Here is its --format=yaml - http://pastie.org/9820219

**Comment by jonhattan** [comment]
Fixed. This was the case for any project without a recommended release. The cause was a variable initialized to NULL.
