### ISSUE TITLE
archive-restore - option to specify host for GRANT

### ISSUE THREAD

**Issue by dasginganinja** [drush-ops/drush#1089]
I'd like to use Drush to restore archives created by archive-dump but ran into an issue due to our server setup. We have separate web and database servers and it appears that Drush uses the host from the mysql-url as the host in the GRANT for access to the database.  Due to the web server being a different IP than that of the database server we needed to mend the archive-restore command to give us a specific host to be allowed from.

I found [this issue over at Drupal.org](https://www.drupal.org/node/2026731) that referenced this same thing and was just trying to see if there was some ground or interest in a patch for this functionality.  We have manually patched our versions of drush for our specific application but feel this would be a great feature for archive-restore.

Thanks!

**Comment by weitzman** [comment]
Sure, a PR would be welcome. Please start with master branch.

**Comment by dasginganinja** [comment]
I was not sure if I should be writing this functionality in `Drush\Sql\SqlBase` or if it was specific enough for MySQL to go in `Drush\Sql\Sqlmysql`. 

I do see that `Drush\Sql\SqlBase` has a `su` method. This modifies the username / password from the $db_spec.  

For the time being I have chosen the latter method for the time being as just a patch for functionality. Once we know what direction this should go I will go back in and update the archive-dump command information as well to reflect the new option if that is the case.  Here's my example just for the time being. https://github.com/dasginganinja/drush/commit/9a2b7474816430dd3a49c72d79217c772b41fa8e

I would just like to make sure that we are heading a correct direction before I go too far.  Thanks!

**Comment by weitzman** [comment]
That looks reasonable to me. You'll want to declare the new option in whichever commands need it.

**Comment by weitzman** [comment]
Any progress?

**Comment by weitzman** [comment]
We made a few changes in this area. Also, this issue has become inactive.
