### ISSUE TITLE
Specify next updatedb for module or execute all for specific module

### ISSUE THREAD

**Issue by davidbarratt** [drush-ops/drush#1096]
I know this has been brought up [before](https://www.drupal.org/node/779676), but the issue is pretty old so I thought I'd bring it up again.

I've run into this problem several times, where modules like [Metatag](https://www.drupal.org/project/metatag) will have huge updates that [takes hours](https://www.drupal.org/node/2168939). Since you can't specify the order of the modules updated though, if you have several modules you are upgrading during a code deployment, things can break until the large update is complete. It would be really beneficial if you could just specify the order of the modules. Then you can have the faster ones go first and the slower ones go last.

I noticed that `updatedb` actually executes a function for each update:
https://github.com/drush-ops/drush/blob/master/commands/core/drupal/update.inc#L36

because of this, I would think it would be possible to either specify an option, or create a new command that would allow the user to specify the order of the modules?

The way I'm thinking this would work, is that when you specify `--manual` or something like that, you'd get an option list. For each module, there would be 1-2 entries. The first would be the next update, the second would be all updates for that module. Obviously if there's only a single update for a module then there only needs to be a single option for that module. This gives site maintainers the ability to order the updates without the danger of executing them out of order.

**Comment by weitzman** [comment]
[Drupal core provides a dependency system for ordering update functions](https://api.drupal.org/api/drupal/modules!system!system.api.php/function/hook_update_dependencies/7). Drush core is not going to implement its own manual ordering system but folks are welcome to experiment in Contrib. If you can't easily reuse parts of updatedb, then refactoring PRs are welcome.

**Comment by davidbarratt** [comment]
@weitzman 

thanks! that hook looks really helpful.
