### ISSUE TITLE
Quiet option for run server

### ISSUE THREAD

**Issue by mikeyp** [drush-ops/drush#1098]
I'm working on some better logging extensions for use with runserver and I need a way to quiet the default request logging from the PHP built in server. It logs to stderr by default and I can redirect that if needed, but that's all wrapped in drush_shell_proc_open() which doesn't expose any option for ignoring output or redirecting it. 

Where would you recommend adding this option? I'm not sure if I should submit a patch for drush_shell_proc_open to allow callers to express how they want to output directed?

**Comment by weitzman** [comment]
Related to #673
