### ISSUE TITLE
PEAR install: make drush look for php.ini in the script path as well as in the installation path

### ISSUE THREAD

**Issue by James-Oakley** [drush-ops/drush#110]
Please reference Drupal.org support issue: https://drupal.org/node/1671896

When Drush is installed through PEAR, the $SCRIPT_PATH variable in bin/drush is hard-coded to a directory such as /usr/local/lib/php/drush.

When $conf_dir is being formed, it only looks in $SELF_PATH. However the Drush documentation suggests that custom php.ini files should go in the lib/drush folder, not the bin folder. This is also in line with Linux directory-naming convention - custom ini files should not go in an application's bin.

I have written a patch that I apply whenever I install or update Drush using PEAR. This patch may not be the correct solution for the central Drush repository, but it's a starting point. Any changes to the way the PEAR installer modifies the Drush code need to be non-breaking for existing installations, who may well have their php.ini file in the lib directory.

**Comment by damienmckenna** [comment]
I suspect this won't be fixed as the PEAR installer no longer works.

**Comment by jonhattan** [comment]
yeah, PEAR no longer supported.
