### ISSUE TITLE
Cache problem stops pm-enable work correctly in some scenarios

### ISSUE THREAD

**Issue by damienmckenna** [drush-ops/drush#1101]
There have been several reports that in certain scenarios the installation of some modules fails when they're being loaded via Drush:

* https://www.drupal.org/node/2254377 - Message
* https://www.drupal.org/node/2261005 - Paranoia
* https://www.drupal.org/node/2311711 - Date Repeat Entity

This is despite the fact that since 2012 Drush has directly used [module_enable()](https://api.drupal.org/api/drupal/includes%21module.inc/function/module_enable/7) to enable the module rather than trying to do anything custom.

Might there be a caching problem that's stopping the .module file from being loaded?

**Comment by weitzman** [comment]
I looked at the first link and I suspect that it is a bug that was recently fixed in Drush. Try to reproduce with 6.5.0. It would be good if we had clear steps to reproduce with a virgin drupal site.

**Comment by greg-1-anderson** [comment]
Adding to Drush7 just in case there is something that needs to be done here.

**Comment by weitzman** [comment]
NO feedback.
