### ISSUE TITLE
Error during cache rebuild in Drupal 8

### ISSUE THREAD

**Issue by subhojit777** [drush-ops/drush#1103]
I am doing `drush cr` in my Drupal 8 instance and I am geting this error:

> <em class="placeholder">Warning</em>: Missing argument 3 for Drupal\Core\Site\Settings::initialize(), called in /home/username/.composer/vendor/drush/drush/commands/core/cache.drush.inc on line 262 and defined in <em class="placeholder">Drupal\Core\Site\Settings::initialize()</em> (line <em class="placeholder">112</em> of <em class="placeholder">/var/www/drupal8/core/lib/Drupal/Core/Site/Settings.php</em>).PHP Fatal error:  Call to a member function get() on a non-object in /var/www/drupal8/core/lib/Drupal.php on line 594
Drush command terminated abnormally due to an unrecoverable error.                                                                                             [error]
Error: Call to a member function get() on a non-object in /var/www/drupal8/core/lib/Drupal.php, line 594

I have latest codebase of Drupal 8 and and Drush version is 7.0-dev. I dont get error during `drush cc all` in Drupal 7 instances.

**Comment by weitzman** [comment]
Your Drush is too old. Since D8 is changing all the time, you have to upgrade to latest Drush often.
