### ISSUE TITLE
Drupal 8 root check means we can't move/rename some core files anymore

### ISSUE THREAD

**Issue by stefanruijsenaars** [drush-ops/drush#1105]
As of (https://github.com/drush-ops/drush/commit/9da9a52acd22c15d1510dc76b2eebd32512d1c5c), Drush does the following check to validate a correct drupal installation:

```php
function drush_valid_drupal_root($path) {
  if (!empty($path) && is_dir($path) && file_exists($path . '/index.php')) {
    // Drupal 8 root. Additional check for the presence of core/composer.json to
    // grant it is not a Drupal 7 site with a base folder named "core".
    $candidate = 'core/includes/common.inc';
    if (file_exists($path . '/' . $candidate) && file_exists($path . '/core/misc/drupal.js') && file_exists($path . '/core/core.services.yml')) {
      return $candidate;
    }
```

This means that we will break a couple of drush installs with a cryptic "no root found" error in case we rename/move any of:

* core/core.services.yml
* core/includes/common.inc
* core/misc/drupal.js

The first 2 are unlikely to change but **core/misc/drupal.js** we are looking to move to **core/assets/js/drupal.js** as per this issue: https://www.drupal.org/node/1663622

**Comment by theodoreb** [comment]
What's the reason for the drupal.js check in the first place?

**Comment by ruijse** [comment]
You're right, we probably don't need that check. In addition to **core/includes/common.inc** we used to just check for **composer.json** in the root (which is admittedly not very drupal specific), but now that we check for **core/core.services.yml**, further checks may not be needed.

From https://github.com/drush-ops/drush/commit/9da9a52acd22c15d1510dc76b2eebd32512d1c5c

```// Extra checks to insure that the candidate is in fact part of a Drupal root,
// and not some other non-Drupal directory
function _drush_valid_drupal_root_extra_checks($path, $candidate) {
 // We also require that there must be a file misc/drupal.js in a sibling
 // folder of the candidate file.```

**Comment by ruijse** [comment]
I have posted a pull request to remove drupal.js from the root check over at https://github.com/drush-ops/drush/pull/1106

**Comment by greg-1-anderson** [comment]
So, we have a basic problem that there is no official way to detect a Drupal 8 root directory, so we try to do the best we can by checking for "fingerprint" files, especially those that contain the name "drupal".  We want to avoid false positives and false negatives to the greatest extent possible.  We also want to avoid parsing text files during the bootstrap, if possible.

If anyone could provide of a good, stable and reliable way to detect the Drupal root, then we could improve this code.

**Comment by stefanruijsenaars** [comment]
So I guess we'll have to keep looking for drupal.js in either the old location or the new location then! I have updated the pull request to reflect this, as there isn't really any other way to detect the drupal root with certainty without parsing text files.

**Comment by greg-1-anderson** [comment]
PR was merged.

**Comment by RobLoach** [comment]
Another possible solution would be to check `core/composer.json`'s `type` being `drupal-core`.

**Comment by greg-1-anderson** [comment]
Yes, I agree that it would be cleaner to check the type in core/composer.json; in general, I think that checking file contents is more likely to produce a stable result vis-a-vis the type and version of the site found (currently only variants of Drupal supported).  However, we also want to avoid file parsing during bootstrap for performance reasons.

If someone could demonstrate that a file-content check could be done with negligible impact to the bootstrap performance, then I think we could consider it.
