### ISSUE TITLE
drush sql-sanitize ignores db prefix

### ISSUE THREAD

**Issue by SteffenBxyz** [drush-ops/drush#1107]
Hi i wanted to sanitize all passwords in my local dev with:

aegir:/data/disk/o1/static/bag-pna/sites/eonbagpna.aegir.local# drush -v sql-sanitize -y 
Do you really want to sanitize the current database? (y/n): y
Initialized Drupal 7.34 root directory at /data/disk/o1/static/bag-pna                                                                                        [notice]
Initialized Drupal site eonbagpna.aegir.local at sites/eonbagpna.aegir.local                                                                                  [notice]

The following post-sync operations will be done on the destination:
  * Reset passwords and email addresses in user table

Calling system(mysql --database='eonbagpnaaegirlo' --host='localhost' --port='3306' --user='eonbagpnaaegirlo' --password='YidS9kPeeN'  < /tmp/phpW47C0Z);
ERROR 1146 (42S02) at line 1: Table 'eonbagpnaaegirlo.users' doesn't exist
Command dispatch complete                             

Theres a prefix in settings.php which is ignored by sql-sanitize command.

 $databases['default']['default'] = array(
    'driver' => "mysql",
    'database' => "eonbagpnaaegirlo",
    'username' => "eonbagpnaaegirlo",
    'password' => "**********",
    'host' => "localhost",
    'port' => "3306",
    'prefix' => '40000030_',
   );

![auswahl_651](https://cloud.githubusercontent.com/assets/5519671/5820993/2d4f7004-a0c9-11e4-8be3-948cdeeb09a8.png)

**Comment by weitzman** [comment]
Just fixed on master branch
