### ISSUE TITLE
Make should generate YAML file

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#1110]
When writing a makefile via --lock, --lock-update, or make-generate command, make should be able to generate YAML in addition to its current ini format.

**Comment by ergonlogic** [comment]
I'm not sure whether this is a valid approach, but I was thinking of converting the rendering of makefiles to use the output-format engine. I believe that this'd largely involve moving the ini-generating code into a new 'ini' output format. We'd probably want a validate hook to only allow 'yaml' and 'ini' as output formats for make-related commands, and remove 'ini' as an engine for most other commands.

I consider the 'ini'-style a largely legacy feature, that we should consider deprecating, and eventually removing. Isolating it in an engine should facilitate that. In addition, this'd probably be a step towards supporting other makefile formats, such as json, which'd be neat.

**Comment by dreftymac** [comment]
+1

https://github.com/dreftymac/stackoverflow.questions.1715811

**Comment by weitzman** [comment]
We could consider deprecating ini format here so that all we do is generate yaml. we just put make-convert command in drush so folks using ini can convert and then use all our tools in drush7 (i.e. generate-make, make-update, etc.)

**Comment by miloskroulik** [comment]
I'm looking forward to this! Convert command would be nice!

**Comment by weitzman** [comment]
make-convert is in. now the options that write ini need to learn to write yaml.

**Comment by ergonlogic** [comment]
This is in now. I've added a `--format` option to the various commands that generate makefile. As per previous comments, we default to generating YAML.

**Comment by weitzman** [comment]
Nice! I think this issue can be closed?

**Comment by ergonlogic** [comment]
Sure
