### ISSUE TITLE
Add a --security-only option to make's --lock-update feature

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#1111]
When generating an updated makefile, it would be great if make only updated when a security release is pending. This is how `pm-updatestatus --security-only` works.

This requires smartening the ReleaseInfo engine to support --security-only. Once thats done, we can change pm-updatetstatus to use this feature instead of doing its own implementation in pm_project_filter().

**Comment by jonhattan** [comment]
One option I think of is to filter out non-security releases when parsing the xml at https://github.com/drush-ops/drush/blob/master/lib/Drush/UpdateService/Project.php#L187. I'm not sure if that will work for `pm-updatestatus`. I'll give it a try.

**Comment by jonhattan** [comment]
I've been working on a separate new command: make-update. The purpose of this command is to improve and replace `--lock-update`. It uses the update_status engine to generate an updated makefile.

Found it at https://github.com/jonhattan/drush/compare/make-update

Code is still a rough outline of the idea. Most of the options are not implemented yet (`--build`, `--only-updates`). `make` code may need some (major?) changes to enable the `--build` option. Other options (`--security-only`) need also some refactoring in the `update_status` engine and `pm-updatestatus` commands.

**Comment by weitzman** [comment]
@jhedstrom  - any early comments about this proposal?

@jonhattan  - I think we should be consistent with updatestatus and write the latest stable release when a security update is available. the current code looks like it writes the security release, and not any ones after that. Not a big deal though.

**Comment by jonhattan** [comment]
Created PR #1142 to better discuss `make-update` implementation.

@weitzman - now selecting the latest stable release. For some reason I understood you wanted the latest security release.
