### ISSUE TITLE
(documentation) drush rsync has no convenient way of migrating 'private' files

### ISSUE THREAD

**Issue by dman-coders** [drush-ops/drush#1113]
It's taken me this long for it to become an issue, but I thought I'd notice it because it tripped up a deployment today.

Usually a quick

  drush sql-sync @original @copy
  drush rsync @original:%files @copy:%files

sets me up with a handy update of any site.

BUT, on a site that has started utilizing private files, stuff got left out.

One work-around that works enough today was making up my own paths:

  drush rsync @original:%site/private @copy:%site/private

- but that is only reflecting my naming convention, and has no "smarts" like the %files path_alias does.

* suggestion: the file_private_path variable should be exposed in the default site-alias path_alias array (at least with --show-optional) , such that we can run:

  drush rsync @original:%files @copy:%files
  drush rsync @original:%private_files @copy:%private_files

*i know* I can do this manually on my sites by adding stuff randomly to the path_aliases, but with aegir managing my site-aliases, that's not so cute, and it becomes a special case. I'd suggest making this - at least a common site-alias key - a convention going forwards.

**Comment by jonhattan** [comment]
`%private` is available. Find all magic paths with `drush @site php-eval "return _core_path_aliases()"`

**Comment by dman-coders** [comment]
Groovy. Thanks for the info! So I guess it's more of a documentation thing. I could not find it mentioned in the rsync help.

**Comment by greg-1-anderson** [comment]
A documentation PR for this would be welcome.

**Comment by nerdcorenet** [comment]
I'm a bit stumped by this:

I can see %private is set properly in the output of _core_path_aliases()

$ drush ev "return _core_path_aliases()"
array(
  '%root' => '/var/www/drupal7',
  '%site' => 'sites/example',
  '%modules' => 'sites/example/modules',
  '%themes' => 'sites/example/themes',
  '%files' => 'sites/example/files',
  '%private' => '/var/www/drupal_private/example',
  '%temp' => '/tmp',
)

But when I try to execute the `drush rsync` command using "%private" the directory is all kinds of wrong:

$ drush rsync @example.remote:%private/ @self:%private
You will destroy data from /var/www/drupal7/sites/all/modules/contrib/private and replace with data from remote-host:/data/www/d7/sites/all/modules/contrib/private/

Why does _core_path_aliases() return the correct value for %private but drush rsync does not?

**Comment by greg-1-anderson** [comment]
Do you have a module named "private" enabled?

**Comment by nerdcorenet** [comment]
Apparently I do: https://www.drupal.org/project/private

**Comment by greg-1-anderson** [comment]
Seems that %modulename is actually %projectname, and uses the filesystem rather than the database, and takes precedence over other shortcuts.  This is not convenient.

I am guessing that this shortcut is used less often than others, and Drush would do well to change here, maybe to %project:projectname, or just kill the feature.  Proposals / PRs welcome.

**Comment by t0xicCode** [comment]
I'd say switch to `%project:projectnam`e if we don't want to completely kill the feature, but I don't remember ever using a % alias to refer to a particular project/module.

**Comment by weitzman** [comment]
%projectname is used by drupal-directory (dd) command.

**Comment by greg-1-anderson** [comment]
It's no good if the shortcut is too long, either.  I was thinking we might try the following:

* Move %projectname to the end of the list, so %private files has priority over %private project.
* Add %:projectname or %.projectname as a way to disambiguate project names from the other shortcuts.

If we don't like the alphabet soup, we could do something similar with %project:projectname or %project.projectname, with a fallback to %projectname when there are no conflicts. That way, scripts can be sure to get a project directory if that's what they want. Conflicts are uncommon, so it seems not too bad in interactive mode to get the wrong answer, as long as the common aliases (like the private files directory) take precedence.

**Comment by t0xicCode** [comment]
Something like @greg-1-anderson proposed sounds good. Using `:` rather than `.` makes more sense in my mind, but that's really just my personal preference.
