### ISSUE TITLE
Drush 7 Stable Release planning

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#1123]
I'd like to make a push to release a stable version of Drush 7.  Let's use this issue for planning.  Edit this text to summarize the Drush 7 stable plan; comment below to discuss criteria, policy, etc.

## Drush 7 Stable branch and commit policies

We will work in the master branch for most of the Drush 7 Stable work.

The Drush 7 branch will not support Drupal 8.  Shortly before we are ready to release 7.0.0 (perhaps at the RC1 release), we will make a 7.x branch, and remove Drupal 8 support from it.  At this time, we will also update the version of the master branch to 8.0-dev.

## Critieria for Beta Release

* Issues that break backwards compatibility or make substantial changes to Drush should be resolved before beta, on a best-effort basis.
* Issues that cause usability issues with Drush (significant regressions from Drush 6, etc.), that one would not expect to exist in a stable release must be fixed.
* As many "easy" or "opportunistic" issues as possible should also be resolved. During this period, maintainers will be putting even more attention in the queue than usual; this is a good opportunity for other contributors to get their PRs reviewed. A lot of these issues can be resolved w/out being tagged as a Drush 7 stable issue just by bringing them to the top of the queue with new discussion &/or code changes so that they receive attention and get committed during this cycle.

## Criteria for RC Release

We will continue to allow changes that break backwards compatibility up to the 7.0.0 stable release.  We will make a best-effort attempt to identify and fix issues that break backwards compatibility prior to the RC tag, though.

## Drush 7 Stable Tags

* The [Drush7 milestone](https://github.com/drush-ops/drush/milestones/Drush7) should be placed on all issues under consideration for the D7 stable release.
* *badcamp* tag. We resolved most of these at Badcamp, but we should also review these to see which should be part of the Drush 7 stable effort.

We may in the future add additional tags to indicate “blockers”, or issue priority; for now, though, we will just use our best judgement and existing available tags to organize the issues.

## Schedule

TBD. "When it's ready." I'd like to make a soft-goal of getting a beta release out sometime around 20 Feb, but of course this will vary depending on how much we find that we want to fix, and how much progress we make on these issues.

**Comment by weitzman** [comment]
1. Yes, Drush7 need not support Drupal 8.
1. Yes, lets keep using master until sometime after 7.0.0 tag when an API break is needed.
1. I'd remove the backward compat rationale around beta1. I'm OK with breaking backward compat anytime before release of 7.0.0
1. I just created a [Drush7 milestone](https://github.com/drush-ops/drush/milestones/Drush7). Seems like most projects use a milestone for this sort of planning. I opted not to have a different milestone for each beta - seems unnecessary.

**Comment by greg-1-anderson** [comment]
Thanks for the Drush 7 milestone.  I updated the summary based on your comments.  Let's make a best effort to identify and fix issues that break backwards compatibility before beta, but we will allow these sorts of changes right up to the end.

**Comment by ergonlogic** [comment]
A label identifying any issues that break backwards compatibility might be helpful, or should these perhaps just be added to the milestone?

**Comment by greg-1-anderson** [comment]
At the moment we are not specifically sorting Drush 7 issues by any criteria; anything under consideration for Drush 7 is being added to the milestone.  If we decide not to fix something, we'll just remove the milestone from the issue.

**Comment by greg-1-anderson** [comment]
There was a request in #1106 for a new Drush 7.x release.  I think that enough stuff has gotten merged in since 7.0.0-alpha8 that this is a good idea.  Is there anything anyone else wants to get in first?  I think we should just push this out, and then work towards a beta1 release.

I am now using [ZenHub pipelines](https://www.zenhub.io/) to organize the Drush7 beta release.  This is a chrome extension; it costs money to use with private repositories, but is free for public repos.  After you install it, you can visit the [Drush 7 pipeline](https://github.com/drush-ops/drush/milestones/Drush7#boards?milestone=1).  (That link will just show you the issues tagged Drush 7 if you have not installed the ZenHub extension.)

Right now "New Issues" are things I haven't investigated, or things that are just "nice to have" for Drush 7.  (These should probably be split into a separate pipeline if there gets to be a lot of them.)  The "backlog" is the todo for Drush 7 queue, and I have also made a "For Beta" pipeline with candidate blockers for a beta release.  I also made "Output format" and "Drush make" pipelines, just for organizational purposes.

These are all "soft" / "unofficial" categorizations; if we really want to formally identify blockers, we should use a label.  At the moment, it seems like the seriousness of the remaining issues is for the most part pretty low, which makes me think that we should be ready for a beta release pretty soon.

**Comment by stefanruijsenaars** [comment]
Just wondering if we could release an alpha9? see http://drupal.org/node/2422915

**Comment by weitzman** [comment]
As of today, the drupal's test bot no longer depends on Drush. This is
great! We are free to tag when desired.

**Comment by greg-1-anderson** [comment]
Sounds good to me.  We should establish some simple tagging policies.

1. I will get a +1 from all maintainers that are paying attention prior to tagging beta1, rc1, and 7.0.0 stable.

2. For other releases, I'll make tags at my discretion, every week or two, depending on need (when enough new fixes have gone in).  Folks can post here to request a release, or to note that they just need a little bit more time to finish up x or y before the next tag.

If that sounds good, then I'll clean up a bit more and tag alpha9 this afternoon.  I'll shoot for Tuesday afternoon-ish, on weeks where there's enough progress to warrant a release.

**Comment by greg-1-anderson** [comment]
We will make new Drush 7 releases in concert with Drupal 8 releases, at least through Drupal 8.0 stable.

Drupal 8 release announcements are made in the [Core Drupal Group](https://groups.drupal.org/core).  Releases are currently happening on the 4th Wednesday of the month, although previously they were on the 3rd Wednesday.

There was a [Drupal 8 Beta 7 release yesterday](https://groups.drupal.org/node/456108), so we should make a Drush tag to go with it shortly.

**Comment by weitzman** [comment]
[Drush7 alpha9](https://github.com/drush-ops/drush/releases/tag/7.0.0-alpha9) has been released. This is recommended for use with Drupal 8 - beta 7.

**Comment by greg-1-anderson** [comment]
It would be good to make a beta release of Drush 7, to get more people using it.

Which issues do we need to fix before we do this?  Are there any testing gaps that need to be closed?

**Comment by weitzman** [comment]
Actually, I just forgot that we discussed moving to beta. Lets do that for the next release. Or maybe even RC1

**Comment by greg-1-anderson** [comment]
Maybe we should do beta1 in a couple of weeks, and then do RC1 at the same time as Drupal 8 beta 8 (~25 March), if nothing serious comes up before then.
