### ISSUE TITLE
drush_confirm spews to stdout regardless of requested format and DRUSH_AFFIRMATIVE

### ISSUE THREAD

**Issue by psynaptic** [drush-ops/drush#1126]
We have a custom command that uses `--format=json` to return machine-readable output. It also requires confirmation because it's a destructive operation. In automated scripts we're passing `--yes --format=json` but the confirm prompt message is printed to stdout, which obviously causes a parse error on the consumer.

I've worked around the issue by short circuiting in the drush command:

```
$machine_readable = drush_get_context('DRUSH_AFFIRMATIVE') && $format === 'json';
if (!$machine_readable) {
  $confirm = drush_confirm($prompt, $args);
  if (!$confirm) {
    return drush_log(dt('Operation aborted.'), 'warning');
  }
}
```

I was wondering, since `drush_confirm()` calls `drush_print_prompt()` which in turn calls `drush_print()` which has an optional `$handle` argument, whether `drush_confirm()` would benefit from taking and passing down the `$handle` argument. This would make it possible for the caller to specify where they want the output to go.

**Comment by greg-1-anderson** [comment]
Did you try making json your pipe output, and then call your command with --pipe?  Haven't tried this yet, but it should give you the behavior that you want.

I don't like the idea of passing $handle to drush_confirm(); however, I think it might make sense to change the way that drush_confirm() behaves when DRUSH_AFFIRMATIVE is set.  Do folks think it would make sense to hide the output, even when not in --pipe mode, or is it useful to see the message scroll by?  Maybe we hide the output if --format is specified, and show it if the command was called without it?

**Comment by psynaptic** [comment]
I did try `--pipe` but didn't actually print the output using `drush_print_pipe()` so, of course, I wasn't seeing any output to stdout. I have since removed my workaround and everything works as expected. It was simply my lack of understanding about how to use the `--pipe` feature. Thanks for putting me on the right track.

It might be beneficial to hide the confirmation message output from stdout when DRUSH_AFFIRMATIVE and/or format is set, but as long as you control the drush command code you can just use the `--pipe` feature as intended.

How about sending the confirmation message output to stderr instead? That would still keep the same visual behaviour for a human user and allow scripts to get to the machine-readable output easily (as most will read the stdout and stderr as separate streams).

**Comment by psynaptic** [comment]
To be explicit about how I handled this:

```
    if (drush_get_context('DRUSH_PIPE')) {
      drush_print_pipe(drush_format($records, NULL, $format));
    }
    else {
      drush_print_format($records, NULL);
    }
```

So when using, for example `--format=json --yes --pipe`, only the machine-readable output is printed to stdout.

**Comment by greg-1-anderson** [comment]
Are you still using Drush 5?  In Drush 6 and later, you should return, not print your output.  I was going to put in a URL to some slides here, but drush.org is gone, and the output format docs are broken (http://docs.drush.org/en/master/output-formats/).  Read `drush docs-output-formats` (just type that command from the command line), and also try creating a sample Drush command using the [drushify](https://drupal.org/project/drushify) tool for more info.

Emitting drush_confirm output to stderr iff in --yes or --no mode is a good idea.

**Comment by psynaptic** [comment]
I read the docs on output formats earlier today but to be honest I didn't really understand what it was trying to tell me. It seems to imply that using `--pipe` is "equivalent" to using, for example, `--format=json`, but I'm sure that is not true since that's how this whole issue came about.

We're using both drush5 and drush6 in production (both for automated scripts and human users), although I think we're mostly using drush6 now (but there are still certain things we need to use a specific version for). I wouldn't be against making these commands specifically require drush6, but compatibility with both versions is ideal.

**Comment by weitzman** [comment]
Emitting drush_confirm output to stderr iff in --yes or --no mode is a good idea.

This is the only todo here, AFAICT. At some point we should rethink the output format docs since we can't do dynamic stuff at readthedocs.

**Comment by psynaptic** [comment]
Perhaps also constraining this to only apply to `machine-parsable` output format engines would be best.

**Comment by greg-1-anderson** [comment]
We should commit #673 before starting here.

When we make this output go to stderr, we should fix backend invoke to process stdout and stderr separately, so that stderr does not get merged in to stdout.  We should do this with the Symfony Process component.

**Comment by greg-1-anderson** [comment]
The stdout / stderr split was made in Drush 9. We won't be fixing this in Drush 8.
