### ISSUE TITLE
Postgres Passwords

### ISSUE THREAD

**Issue by dpi** [drush-ops/drush#1129]
Drush will not connect to a Postgres Drupal site if the password contains weird characters, such as ":"

I came across this issue when 1Password created an obscure password that was accepted initially, but failed when Drush attempted to connect to the site after installation.

Tested with Drupal 7 and 8.

This issue does not occur with a MariaDB database (tested with Drupal 8).

**Drush says**

    Command pm-update needs a higher bootstrap level to run - you will need to invoke drush from a more functional     [error]
     Drupal environment to run this command.
     The drush command 'up' could not be executed.                                                                      [error]
     Drush was not able to start (bootstrap) the Drupal database.                                                       [error]
     Hint: This may occur when Drush is trying to:
      * bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working database setup by specifying the URI to use with the --uri parameter on the command line. See `drush topic docs-aliases` for details.
      * connect the database through a socket. The socket file may be wrong or the php-cli may have no access to it in a jailed shell. See http://drupal.org/node/1428638 for details.

# Drush Site Install

1. site-install will accept urlencoded passwords which contained the character
2. Password will be stored plaintext in settings.php
3. Drush will not connect after installation.
4. Site operates normally when navigating UI.

# UI/Browser Install

1. If a site install was completed through UI, the password will be accepted
2. Password will be stored plaintext in settings.php (same as Drush)
3. Drush will not connect after installation.
4. Site operates normally when navigating UI.

**Comment by tstoeckler** [comment]
@dpi just opened a pull request that should fix this. Can you review/test?
