### ISSUE TITLE
file_get_contents(), when behind a proxy with auth, fails (windows)

### ISSUE THREAD

**Issue by ChristopheMayet** [drush-ops/drush#1139]
Hi,

I had a problem with downloading/upgrading modules with drush, via `drush up xxxxxxx` or `drush dl xxxxxxx` command.
There is no problem to download and fetch xml project informations but it fails when drush has to download the project itself.
Below, the message printed (with `--debug` option) :
`Unable to download admin_menu to  from http://ftp.drupal.org/files/projects/xxxxxxx`

I digged into this and I found that the culprit was [`@file_get_contents()`](https://github.com/drush-ops/drush/blob/92be6690f939b810c49c54bf5938efa07fd7d30d/includes/drush.inc#L827), in `_drush_download_file()` function.

I have my local environment variables _HTTP_PROXY_ and _HTTPS_PROXY_ setted, proxy access properly configured in the _settings.php_ of my Drupal website, curl or wget (in drush operations) work well.
But nothing in Drush seems to rely on those configurations for such operation, AFAIK.

My workaround (quick and dirty style) was to set a `stream_context_set_default`, in which I set proxy settings before the main execution of drush, like this :

``` php
$auth = base64_encode("PROXY_USER:PROXY_PASSWORD");
stream_context_set_default(
    array(
        'http' => array(
            'proxy' => "tcp://PROXY_IP:PROXY_PORT",
            'request_fulluri' => true,
            'header' => "Proxy-Authorization: Basic $auth"
        )
    )
);
...
exit(drush_main());
```

I don't know if it's a common error, but I haven't find any references of this problem (Anyone else experiencing the same ?).

PS : There's obviously a prettier way to write that, that is just to demonstrate the problem and the solution in order to be easy to understand.

FI, my working environment :
- OS : Windows 7
- Server type : Wamp
- Apache : 2.4.10
- Php : 5.6.1
- Cygwin binaries for window (curl, wget, etc.)
- Drush version : latest under master branch
- Drupal version : 7.34
- php.ini : allow_url_fopen = On

**Comment by weitzman** [comment]
See #4040
