### ISSUE TITLE
Concurrent drush execution intermittently throws errors

### ISSUE THREAD

**Issue by Fabio-E-Questionmark** [drush-ops/drush#1141]
Hello.

Our deployment strategy concurrently runs multiple Drush commands (using the same user) in a multi-threaded environment.

This works fine and helped to significantly improve performances, however, we are experiencing the following error (thrown intermittently):
Drush must have a writable cache directory; please insure that one of the following 
locations is writable...

The cache directory actually exists and appears to be writable.
Also, some Drush processes actually used it as cache data appears to be in it.

By looking at the drush_directory_cache function, the theory is that if a process calls "is_writable" exactly at the same time the directory is getting created, then is_writable returns FALSE and this causes drush_directory_cache to throw an error (if no other paths are available).

If this is true, I think the cleanest way to fix this issue would be to use semaphores to guarantee a mutually exclusive access.

Would you think this would fix the problem / would you consider to accept a pull request with such a fix?
Also my question is, can you think about other potential problems caused by running concurrent Drush commands with the same user?

Thanks in advance for the support and for this great tool!

Fabio

**Comment by greg-1-anderson** [comment]
The call to is_writable() in drush_directory_cache() happens on the base directory; if this is a problem, it would only happen once, at the beginning, and then should be fine thereafter.  Perhaps you are having trouble with drush_make_dir(), but it calls @mkdir() before checking is_writable(), so I'm not sure how this could fail.  However, you are seeing an error, so there is probably one in there somewhere.

I think that the first thing to do would be to write a unit test that called drush_mkdir() or drush_directory_cache() repeatedly, in a concurrent or multithreaded environment, to demonstrate the failure.  Then, submit a PR that fixes the problem.  This would definitely be welcome, but I think isolation is necessary prior to the fix.

**Comment by Fabio-E-Questionmark** [comment]
I could not prove that a specific function cannot be run simultaneously.
However, by running drush commands such as "cc" simultaneously with 4 process it's fairly easy to reproduce warnings and errors.

Warnings are thrown by:
- opendir (in filesystem:653 - drush_scan_directory)
- rmdir (in filesystem:141 - drush_delete_dir)
Errors are then thrown by:
- drush_mkdir (Unable to create !dir)

Unfortunately, by looking at the specific error it seems the issue isn't limited to the Drush cache, for instance most of the opendir are related to folders inside sites/all/modules/... :
opendir(sites/all/modules/Community/ctools/views_content,sites/all/modules/Community/ctools/views_content): The process cannot access the file because it is being used by another process. (code: 32) filesystem.inc:653

I'm under the impression that we need some strategy to lock files and directories the process is working on...

**Comment by greg-1-anderson** [comment]
We have to be careful with locking; if we lock too much, then we have disabled concurency.  There are some options, such as `drush cc` that we should not try to support with concurrency (at least not on the same site).

If the concurrency problem seems to be limited to Drush's basic handling of its cache files, etc., maybe the best thing to do is to add a new global option that concurrency can set that alters how temporary and cache directories should be named.  Again, though, we would want to be careful here as well, as we ideally would use the same commandfile cache for all of the processes, and separate only the temporary files.

Could get complicated, but it would be good to have some help in this area.  We've been talking about removing the concurrency feature from Drush, which is something we might have to do if the current maintainers don't have time to make the existing code work right for common scenarios.

**Comment by Fabio-E-Questionmark** [comment]
I understand that locking too much might substantially disable concurrency (or at least represents a limitation to it) but on the other hand it seems to be the safest option to support it. Eventually, to me this sounds like a better option than dropping concurrency support.

Altering cache and temp folder names seems to be a reasonable (and relatively cheap) approach, however, I'm worried by the fact that one of the errors was caused by attempting to access a folder under sites/all/modules/... What I can't figure out is why a command would even try to write files and directories under sites/all? Is this the issue you referred to when considering not to support concurrency for commands such as drush cc? Or do you see other issues?

**Comment by greg-1-anderson** [comment]
In general, you should expect that Drupal should be able to handle multiple concurrent requests, because that's what happens when multiple users hit the site simultaneously through the web browser.  However, I would not expect Drupal to necessarily be able to concurrently clear the cache simultaneously on the same Drupal site.  There's no good reason you'd want to do this, but if you did, you might have problems.  `drush @site1,@site2 cc` should work concurrently, though, if the problems in Drush are worked out.

A PR that attempted to fix concurrency through locking would be welcome.  Again, try to use as localized locks as possible.  Try not to lock the Drupal bootstrap; this can take the majority of the time for some requests, so concurrent execution could become nearly serial if this was necessary.  At that point, we'd have to question whether it was worth keeping the feature, if that's what was necessary to make it work. Maybe it would be still for some commands.

**Comment by Fabio-E-Questionmark** [comment]
Hi Greg.

This is my summary after having tested Drush concurrent execution.

Installed websites: 5
Command run: vget
Concurrent processes: 5 (one for each website)
PHP version: 5.6
Drupal version: 7.34
Drush version: 6.2.0

Attempt 1:

2 processes out of 5 did not terminate. They simply seem deadlocked.
3 processes terminated with the expected result but with many warnings:
 ![drush-concurrent-execution-warnings](https://cloud.githubusercontent.com/assets/6928689/6691626/9ab89d88-ccbf-11e4-8115-83d75babd8e5.jpg)

Attempt 2-N:

Attempts varied in:
-	number of deadlocked processes (arranging from 0 to 4)
-	warnings produced by processes (arranging from none to a huge list of warnings all very similar to the ones shown above)

In a nutshell, Drush concurrent execution doesn't seem to be reliable.


Additional information:

Every warning seems to be produced during the Drush bootstrap process, more specifically when Drush scans the whole available codebase after every bootstrap stage (e.g. looking for available commands, ... - @greg-1-anderson please correct me if I'm wrong).

I have re-run the test several times after having hacked Drush and locked the bootstrap process so that only 1 process at a time is bootstrapping Drush.
Results:
No process deadlocked.
No warnings raised.
I've also been trying to lock more specific functions in filesystem.inc but that didn't seem to solve the issue.

The issue seems to be confined to the bootstrap process.
Also, deadlocks have to happen during that phase.

I could not really identify what causes processes to deadlock or warnings.

The bad news (as @greg-1-anderson anticipated) is that by looking at the CPU usage while processes are executed, it’s easy to notice that their execution has become almost serial.
At any time, basically only 1 process was consuming CPU resources.

**Comment by weitzman** [comment]
I think that concurrency has complicated our codebase for not much benefit and should be removed. See #975

**Comment by greg-1-anderson** [comment]
@msonnabaum have any opinions here? @juampy72?

I sort of hate to see it go, but I don't see these issues as being easily solvable.  Maybe we should remove for 7.0-rc1 (planned for [next Wednesday](http://www.mosheweitzman.me/post/113968700703/in-order-to-better-support-the-fearless-drupalists)).

**Comment by Fabio-E-Questionmark** [comment]
This might be obvious, but I want to make it 100% clear:
This thread is not related at all to the Drush concurrency feature.
All my tests were about running "drush -l site1 vget ..." "drush -l site2 vget ..." ... in parallel.

**Comment by weitzman** [comment]
Oh, thats helpful, @Fabio-E-Questionmark. Sorry I got us off track there. Further discussion bout Drush's --concurrency feature should happen in #975.

I don't know of a reason why the directory reads that we do doing bootstrap would deadlock like that. Are you using a network filesystem or something like that? Is this Linux? One way to avoid scanning global locations is to use the --local option. But your problems are reported on Drupal directories so not sure that will help.

**Comment by Fabio-E-Questionmark** [comment]
I believe I have just found the issue.

Thanks @weitzman, your last 2 questions really put me on the right track!

Tests were on *Windows*. But the actual issue was that "sites/modules" is a *symbolic link* pointing to somewhere else on the file system.
After removing the link and copying the actual modules folder to sites/all/modules I could not replicate the issue anymore.
No deadlocks, no warnings.

I'm not sure whether this is a Windows issue or a PHP / symbolic links issue, but this has clearly fixed the problem. It would be interesting to repeat the test on Linux using symbolic links though...

So, I can eventually come back to my original concern, which is only related to the Drush cache directory.

Considering the parallel execution of the following 4 commands:

drush -l test1 vget
drush -l test2 cc all
drush -l test3 another-command
drush -l test4 yet-another-command

My concern is that while cc is destroying the Drush cache, other commands are attempting to read it.

The "immediate" solution I see here, is to use the process ID to construct the Drush cache directory name. Perhaps not an elegant solution, but cheap and safe IMO.

Any thought?

Many thanks to everyone for the support!

Fabio

**Comment by greg-1-anderson** [comment]
It might be a good idea, as you suggest, to set the TEMP environment variable to a separate path for each Drush process you launch.  I would -not- use the process ID to make this directory name, or every single command would have to rebuild all of the Drush caches every single time, which would be really slow.  Instead, you should cycle through them, from 1 - N, where N > the number of processes you will ever have.  The challenge you have if you do this is to insure that all of these directories are deleted on `drush cc drush`; otherwise, they may keep stale information.  You could avoid this problem by putting them all inside of Drush's temp directory, so that drush cc drush erases them all.  This is the main cause of concern you have, though, so my next question is, is this actually a problem that you are experiencing?

Typical scenario:

Process 1:  `drush cc drush` => `rm -rf /tmp/foo`
Process 2: Does /tmp/foo exist?  No?  Rebuild it.

This generally should be safe, unless process 3 comes along and does a `drush cc drush` in the middle of process 2's rebuild, which might cause problems.  Drupal might have problems with this as well.

I think the solution here is to lock your cc commands, so that no two are ever running at the same time.  This might be a useful feature for Drush to have as well; a PR would be welcome here.

**Comment by Fabio-E-Questionmark** [comment]
We felt like the safest (and cheapest) option here was to use the CACHE_PREFIX environment variable to make sure concurrent processes use different cache folders. It worked smoothly.
Thanks for your help!

**Comment by ttk** [comment]
I had the same issue described in the original post and I solved it using the CACHE_PREFIX.  I want to mention that CACHE_PREFIX is a bit of a misnomer, as it's not really a prefix, but the path the custom cache root directory, which must already exist (will not be created by drush).  Here's the script I use to run drush command on multiple sites in parallel:

```
#!/usr/bin/php
<?php

// Usage: drushall.php @alias1 @alias2 <drush commands>
// Dependencies: php; parallel (apt-get install parallel php5-cli)

$all_sites = array('alias1','alias2','alias3'); // List of valid site aliases
$cache_root = getenv("HOME") . '/.drush/cache';
$columns = 158; //getenv("COLUMNS");  // Format output with specified columns

//////////////

array_shift($argv); // Pop off the script name

$sites = array();

while(count($argv)) {
  $a = $argv[0];
  if($a[0] != '@') break;
  else {
    $alias = substr($a, 1);
    if($alias == 'all') $sites = $all_sites;  // @all means all sites
    else if(in_array($alias,$all_sites)) $sites[] = $alias;
    array_shift($argv);
  }
}

if(empty($sites)) $sites = $all_sites;  // If no alias specified, do them all

// Create cache dirs
foreach($sites as $site) {
  $cache_dir = $cache_root .  "_$site";
  error_log($cache_dir);
  if(!file_exists($cache_dir))  mkdir($cache_dir);
}

// Compose the command
$args = array_map(function($value) {
  return escapeshellarg($value);
},$argv);

$args = implode(" ",$args);

$cmd = 'echo -n "' . implode(':',$sites) . '" | parallel -d ":" -j20 COLUMNS=' . $columns . ' "echo "{}:";  CACHE_PREFIX=' . $cache_root . '_{} drush @{} ' . $args . '"';

//echo $cmd;
system($cmd);  // Execute it! Full speed!
```

Enjoy!
