### ISSUE TITLE
drush sql-dump returns success even if database is not available when --gzip is specified

### ISSUE THREAD

**Issue by dmitrybezer** [drush-ops/drush#1148]
How to reproduce:
go to the docroot of a site whose database is not available and run
`drush sql-dump ; echo $?`

`mysqldump: Got error: 2003: Can't connect to MySQL server on '127.0.0.1' (111) when trying to connect
Database dump failed                                                                  [error]
1`
So we are good here. Now append --gzip:

`drush sql-dump --gzip ; echo $?`
`mysqldump: Got error: 2003: Can't connect to MySQL server on '127.0.0.1' (111) when trying to connect
+:?T0`
Note: it outputs something, there is no "Database dump failed" message and the return value is 0.

Seems like the problem is in SqlBase.php file - appending `| gzip -f` to the command line makes it always return 0 so drush fails to notice the error.

**Comment by weitzman** [comment]
Per http://stackoverflow.com/questions/1550933/catching-error-codes-in-a-shell-pipe, it looks like we need to create a tmp file and gzip that. Dump files can be very large, but whatever. Patches welcome.

**Comment by weitzman** [comment]
sql-sync always does a gzip now so i think this will happen more.

**Comment by weitzman** [comment]
I'm a little hesitant to use a temp file and then gzip that. dump files are huge and disk space is sometimes an issue. also performance degrades slightly by having to write the large file.

**Comment by greg-1-anderson** [comment]
This was fixed in Drush 9. We are unlikely to address in Drush 8, although I suppose a backport would be welcome if someone felt strongly enough to make one.
