### ISSUE TITLE
Drush 7.0-dev + Drupal8-beta backup_migrate do not work

### ISSUE THREAD

**Issue by vibrasphere** [drush-ops/drush#1149]
Do not work when trying to run **drush bb** or **drush bam-backup**

    $ drush bam-backup

    Fatal error: Call to undefined function variable_get() in C:\xampp\htdocs\d8\modules\backup_migrate\includes\destinations.inc on line 25
    Drush command terminated abnormally due to an unrecoverable error.

    Error: Call to undefined function variable_get() in C:\xampp\htdocs\d8\modules\backup_migrate\includes\destinations.inc, line 25

**Comment by jonhattan** [comment]
That's bam fault.

**Comment by vibrasphere** [comment]
So to who this bam belongs to? Where do I report this?

**Comment by jonhattan** [comment]
https://www.drupal.org/project/issues/backup_migrate
