### ISSUE TITLE
Drush7 pm-updatestatus defaults to the 'recommended' version even if there is a 'other' release

### ISSUE THREAD

**Issue by mariagwyn** [drush-ops/drush#1157]
Summary: drush7 defaults to the 'recommended' version even if there is a 'other' release within the same major version family.

Media:
Media is downgrading using the recommended version which is below the deployed version.
```drush6 upc --pipe
media 7.x-2.0-alpha3+46-dev 7.x-2.0-alpha4 Update-available```
```drush7 pm-updatestatus
Media (media) 7.x-2.0-alpha3+46-dev  7.x-1.4 SECURITY UPDATE available```

Recommended: 7.x-1.4
Other: 7.x-2.0-alpha4

Linkt and Favicon are upgrading using the recommended version.

Linkit:
```drush6 upc --pipe
linkit 7.x-2.5 7.x-2.7 SECURITY-UPDATE-available```
```drush7 pm-updatestatus
Linkit (linkit) 7.x-2.5 7.x-3.3 SECURITY UPDATE available```

Recommended: 7.x-3.3
Other: 7.x-2.7

Favicon:
```drush6 upc --pipe
favicon 7.x-1.0-rc1 7.x-1.0-rc2 SECURITY-UPDATE-available```
```drush7 pm-updatestatus
favicon     7.x-1.0-rc1        7.x-2.1```

Recommended: 7.x-2.1
Other: 7.x-1.0-rc2

**Comment by acquiacat** [comment]
Helpful or not, here is some follow-up info:

favicon 7.x-1.0-rc1
favicon 7.x-1.0-rc2 (Security Release)
favicon 7.x-2.1
media 7.x-2.0-alpha3+46-dev
media 7.x-2.0-alpha4 (Security Release)
media 7.x-1.4 (Security Release)
linkit 7.x-2.5
linkit 7.x-2.6
linkit 7.x-2.7 (Security Release)
linkit 7.x-3.3 (Security Release)

**Comment by mariagwyn** [comment]
Same issue with Webform:
drush6 --uri=default upc --pipe
webform 7.x-3.20 7.x-3.22 SECURITY-UPDATE-available
drush7 --uri=default pm-updatestatus
 Webform (webform)                                7.x-3.20           7.x-4.4           SECURITY UPDATE available

**Comment by mariagwyn** [comment]
Attempted to run Webform update with specific version number:
```
drush7 pm-updatecode webform-7.x-3.23
Update information last refreshed: March 19, 2015
 Name               Installed Version  Proposed version  Message
 Webform (webform)  7.x-3.21           7.x-3.21          Specified version available
```
Note that it did not pick up the specified version.

**Comment by mariagwyn** [comment]
And add 'Print' module to the list.

**Comment by jonhattan** [comment]
@mariagwyn @acquiacat please check it is fixed now.

**Comment by mariagwyn** [comment]
I am still testing (having issues getting Drush 7 working on local sites), but I can confirm that Media is now correctly reporting.  I will check others and reopen if I see an issue.

Thanks @jonhattan.
