### ISSUE TITLE
drush sql-cli prints the select statement when running from cron

### ISSUE THREAD

**Issue by kbemelmans** [drush-ops/drush#1160]
I made a bash script that runs one query and echos the result. This will be used by a zabbix server to monitor the logged in users:

    #!/bin/bash
    cd $HOME/httpdocs
    drush sql-query "select count(DISTINCT(u.name)) from sessions s \
    LEFT JOIN users u ON s.uid=u.uid \
    LEFT JOIN users_roles ur ON u.uid=ur.uid \
    LEFT JOIN role r ON ur.rid = r.rid \
    WHERE unix_timestamp() - timestamp < 300 AND s.uid > 0 AND r.name IS NULL;"

When I run this from bash, this works fine and echo's the resulting number.
But when I run this from cron, the select statement gets also echo'd:

    	count(DISTINCT(u.name))
    0

Is this a bug in drush or is this just normal behaviour? I have no idea where to look to debug this, so I'm just posting this here hoping someone can explain this for me.

I'm use the latest development version (Updating drush/drush dev-master (a1d4c30 => a639912))

**Comment by greg-1-anderson** [comment]
Seems unlikely that this would be Drush, with only a portion of the complete query being echoed.

Add --debug to the drush sql-query command in your script, and run it from cron.  Inspect the copious output, and see what comes before and after the echo'ed 'count' line.  This should help isolate the cause.
