### ISSUE TITLE
Allow config-import to work with partial sets of config

### ISSUE THREAD

**Issue by jhedstrom** [drush-ops/drush#1163]
The config UI allows one to import individual configs. The current `config-import` command only works with entire config sets. It would be nice to have an option to import only configs found in a target directory (if one tries this now, the import command will delete all configs not present).

This alternatively could be an option to the `config-edit` command to take a source file (thus skipping the interactive editing part) and make it the active config for that object.

**Comment by weitzman** [comment]
Yeah, this would be useful.

**Comment by jhedstrom** [comment]
Let's track further discussion in the PR #1170.
