### ISSUE TITLE
Set default timezone

### ISSUE THREAD

**Issue by ergonlogic** [drush-ops/drush#1166]
A number of my colleagues work on OSX, whose PHP implementation doesn't appear to set date.timezone. It should be pretty harmless to add `date_default_timezone_set()` somewhere early in our bootstrap to avoid lots of warnings like:

```
date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.
```

I've begun sometimes adding `date_default_timezone_set()` in hook_drush_init() in some of my contrib projects. This is pretty trivial, so I'm going to go ahead and add this unless there are objections. Any suggestions as to where?

**Comment by greg-1-anderson** [comment]
Shouldn't we just rely on folks to set [date.timezone](http://php.net/manual/en/function.date-default-timezone-set.php) in their cli php.ini instead?

c.f. http://php.net/manual/en/function.date-default-timezone-set.php

I suppose it would be okay with me if we set this to UTC somewhere early in Drush's bootstrap, but only if we first confirm that the ini value is not set.  If we do this, maybe we should put in at least one Drush warning about how to fix it the right way (trade one Drush warning in return for many many Drupal warnings?).

**Comment by shelane** [comment]
When you don't have control of the server php.ini file and the server is located in a different time zone and 99% of your users are in a specific time zone, being able to set a default for a user or even in just a drush command when creating the user would be nice.

**Comment by Berdir** [comment]
I believe this became a bigger issue with 8.8 as we deprecated drupal_get_user_timezone() and instead ensure that we set the correct timezone on the request and user-change events in https://www.drupal.org/project/drupal/issues/3009377.

For example https://www.drupal.org/project/drupal/issues/3087606 become a more common issue, when before it only affected sites with per-user timezones (which are rare I think) and now it can also happen if caches are invalidated and rebuilt with drush in the wrong timezone. And similar problems could appear with any other code that is invoked by drush.

I don't know enough about drush's internals to say what the best fix is, and since \Drupal\system\TimeZoneResolver::getTimeZone() was explicitly made protected and not an API, I think one of two things should be done:

a) Explicitly call \Drupal\Core\Session\AccountProxy::setAccount() even if no user was provided (with `new AnonymousUserSession()`), to trigger the set user event
b) call `date_default_timezone_set($config->get('timezone.default'));` yourself

**Comment by weitzman** [comment]
Do any of the CLI scripts that ship with Drupal deal with this issue? Or do they similarly corrupt things? 

Could core use a different listener thats not a request listener. Like a kernel event that happens for both CLI and web requests?

Those two options look pretty much equivalent. I guess a) is slightly preferable. The question is where to put it. We can do it in full bootstrap code but thats not called for some commands like cache:rebuild.

**Comment by IgorKvyatkovskyi** [comment]
I got this issue when I use `drush updb` command

I guess this issue has an influence for all custom drush commands

For example `drush advancedqueue:queue:process` from module `advancedqueue`

As for me in full bootstrap code will be better.

**Comment by jantoine1** [comment]
I'm running into this issue with the Ultimate Cron module as it calculates the cron_last_run value differently based on the method of execution. If run through Drupal's UI, cron_last_run is calculated using Drupal's default timezone. If run through Drush, cron_last_run is calculated using UTC.

**Comment by greg-1-anderson** [comment]
@jantoine1 Did you try configuring your php.ini as [describe above](https://github.com/drush-ops/drush/issues/1166#issuecomment-74182276)?

**Comment by jantoine1** [comment]
@greg-1-anderson Similarly to that solution, I actually ended up calling date_default_timezone_set() in a settings.local.php file placed in my web/sites/default directory. This might be more accessible to those who can't edit their php.ini file.

**Comment by DieterHolvoet** [comment]
Having the same problem. I think calling <code> date_default_timezone_set()</code> manually is more a workaround than a fix.

> Could core use a different listener thats not a request listener. Like a kernel event that happens for both CLI and web requests?

Not an expert, but there doesn't seem to be one: https://api.drupal.org/api/drupal/vendor%21symfony%21http-kernel%21KernelEvents.php/class/KernelEvents/8.4.x

> Those two options look pretty much equivalent. I guess a) is slightly preferable. The question is where to put it. We can do it in full bootstrap code but thats not called for some commands like cache:rebuild.

Not sure if it's possible to get Drupal configuration without bootstrapping. Setting a default account in the full bootstrap phase would fix this issue in most cases, so it's worth it in my eyes. I can't think of a situation in which correct timezone information would be critical during `drush cache:rebuild` anyway.
