### ISSUE TITLE
Inline comments in .make file?

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#1167]
It's possible to make inline comments in .make files?

I've tried something like:

    defaults[projects][subdir] = contrib ; Specify directory for contrib modules.

but my sub-folder was created as `contrib ; Specify directory for contrib modules`.

Does it mean the inline comments are not supported or it's a bug?

**Comment by ergonlogic** [comment]
Inline comments are no supported for ini-style makefiles, though they should work in YAML.
