### ISSUE TITLE
Use drush_set_error in queue run

### ISSUE THREAD

**Issue by bjeavons** [drush-ops/drush#1168]
I'm using jenkins to call drush queue-run but a build won't fail unless I throw an exception from worker callback which also keeps the queued item from being deleted. If drush_queue_run() could support an error return state from the worker it could call drush_set_error while also allowing the item to be deleted.

**Comment by bjeavons** [comment]
PR #1169 is for 6.x. For master I'm not sure yet how to trigger an error within the queue class or if should be within the drush_queue_run().

**Comment by weitzman** [comment]
In master, you can throw an exception in your queue class and it will be caught as an error by the drush invoke code that runs the command.

**Comment by greggles** [comment]
Thanks for the insight, Moshe. That makes it sound like PR #1169 could be accepted to Drush 6.x without the need to port to another branch.

Any thoughts on that proposal?

**Comment by weitzman** [comment]
Closing this in favor of #1169
