### ISSUE TITLE
example.bashrc doesn't work when drush is symlinked

### ISSUE THREAD

**Issue by jhedstrom** [drush-ops/drush#1171]
Commit 55deaf2 seems to have broken the example when drush is symlinked on OSX.

**Comment by jhedstrom** [comment]
Possible fix in #1171. Needed to use regex and double brackets.

**Comment by greg-1-anderson** [comment]
Existing commit works on my OSX system with a simlink--but I like the way yours looks better anyway, so we should commit this if it works in multiple platforms.  I just need to remember to test this a couple of places.  I seem to remember that some systems don't support the "[[ ]]" syntax, but I don't quite remember where the problem with this is.

What is the failure you are seeing with the current code?
