### ISSUE TITLE
drush sqlq triggers Warning: Using a password on the command line interface can be insecure.

### ISSUE THREAD

**Issue by idefix6** [drush-ops/drush#1175]
The new mysql version show a warning message if the password is provided as parameter (as this can be seen with ps auxw | grep mysql).
Therefor if you execute:
<code>
drush sqlq "SELECT users.uid, users.name, users.status, users.mail, field_data_field_name_first.field_name_first_value as first_name, field_data_field_name_last.field_name_last_value FROM users LEFT OUTER JOIN field_data_field_name_first ON field_data_field_name_first.entity_id=users.uid LEFT OUTER JOIN field_data_field_name_last ON field_data_field_name_last.entity_id=users.uid where users.status=1"
</code>
You always get the message on stderr:
Warning: Using a password on the command line interface can be insecure.

For the new mysql version a new approach is foreseen. Create a new login path with:
<code>
mysql_config_editor set --login-path=drush-path --host=localhost --user=restore --password
</code>
And then connect with:
<code>
mysql --login-path=drush-path
</code>

Does anybody know, how is could be solved for drush?

Thanks
Matthias

**Comment by greg-1-anderson** [comment]
This has been discussed extensively in #365.  While this issue is important, no one has come forward with a PR yet.  Perhaps this will be easier now that sql-sync has been refactored; previous attempts broke the old implementation.

**Comment by greg-1-anderson** [comment]
Looks like this is already solved in the master branch of Drush.

**Comment by idefix6** [comment]
Thanks, can confirm that version for master (tested with 56909d5221a785670034efe6fea664a5fb6db933ESC) solved the problem.
