### ISSUE TITLE
Cant start Drush, tried many ways to solve this problem, still nothing!!!

### ISSUE THREAD

**Issue by MichaelRoma** [drush-ops/drush#1180]
After installing getting this message:
"Unable to load autoload.php. Drush now requires Composer in order to install its dependencies and autoload classes. Please see README.md"
Tried many ways, nothing. I am using macbook with Mac Os X 10.10 Yosemite
Michael

**Comment by greg-1-anderson** [comment]
Try `composer install`.  The installation instructions moved out of the README; they can be found at README.md -> General Instructions -> [Installation](http://docs.drush.org/en/master/install/).

**Comment by MichaelRoma** [comment]
After "composer install" what do next?
Michael

**Comment by ergonlogic** [comment]
Please read the documentation that @greg-1-anderson linked to.

As a note about asking for help, saying "Tried many ways, nothing." is not very helpful. We, as maintainers, don't know what issue(s) you're facing, or what attempts you've made to resolve it. Please ensure that you've carefully read and followed the installation documentation. Then document which step is failing for you, and the entire error output that you are receiving. Without this, we are not in a position to help.

Finally, this issue has been closed, and it is generally bad form to comment on closed issues. Please follow the instructions above, and start a new issue if you still have trouble.
