### ISSUE TITLE
Ability to non-interactively download latest supported release for branch

### ISSUE THREAD

**Issue by AohRveTPV** [drush-ops/drush#1182]
There seems to currently be no way to non-interactively download the latest supported release for a branch that is not recommended.

For instance, the Coder module currently has no 7.x recommended release.  There is no (non-interactive) way to specify that you would like to download the latest supported release from 7.x-2.x, whatever minor version it may have.

Some possible syntaxes:
```
# Specify a project major version.
drush pm-download --yes coder-7.x-2

# Give option to download supported release for the indicated branch.
drush pm-download --yes --supported coder-7.x-2.x
```

**Comment by ergonlogic** [comment]
Have you tried '--yes'?

**Comment by AohRveTPV** [comment]
```
$ drush dl --yes coder
There are no stable releases for project coder.                                                                    [warning]
Choose one of the available releases for coder:
 [0]  :  Cancel                                               
 [1]  :  7.x-2.4      -  2015-Jan-14  -  Supported
 [2]  :  7.x-2.x-dev  -  2015-Jan-14  -  Development          
 [3]  :  7.x-1.x-dev  -  2013-Sep-30  -  Development          
 [4]  :  7.x-1.2      -  2012-Nov-11  -  Supported
Cancelled
Aborting.
```

I do not see a way to specify "latest 7.x-2.x stable release" (option 1 from the interactive menu).

I could do `drush pm-download --yes coder-7.x-2.4`, but 7.x-2.4 will not always be the latest 7.x-2.x release.

**Comment by AohRveTPV** [comment]
Sorry, the example commands in my original post should have included '--yes'.  Updating to add.

**Comment by ergonlogic** [comment]
These work for me. What version of Drush are you using?

    $ drush dl --yes coder
    Project coder (7.x-1.2) downloaded to /home/vagrant/coder.                                                                                [success]
    Project coder contains 3 modules: coder_upgrade, coder_review, coder.
    $ drush dl --yes coder-7.x-2.x
    Install location /home/vagrant/coder already exists. Do you want to overwrite it? (y/n): y
    Project coder (7.x-2.x-dev) downloaded to /home/vagrant/coder.                                                                            [success]
    Project coder contains 6 modules: drupalcs, bad, bad2, coder_upgrade, coder_review, coder.

**Comment by AohRveTPV** [comment]
I was on Git master but had not recently pulled, sorry.  After pulling, I have the same behavior as you show.

However, there still seems to be no way to download the latest release for Coder 7.x-2.x.

**Comment by AohRveTPV** [comment]
Sorry, by "latest release" I meant "latest other release" and not "latest development release".  I will clarify my initial comment.

**Comment by ergonlogic** [comment]
Well, the problem here is that, while the 2.4 release is supported, it isn't recommended. I don't know whether the select list will always put the 2.x release at the top, but the below appears to work, for now:

    $ drush dl --yes coder --select --choice=1
    Choose one of the available releases for coder:
     [0]  :  Cancel                                      
     [1]  :  7.x-2.4      -  2015-Jan-14  -  Supported   
     [2]  :  7.x-2.x-dev  -  2015-Jan-14  -  Development 
     [3]  :  7.x-1.x-dev  -  2013-Sep-30  -  Development 
     [4]  :  7.x-1.2      -  2012-Nov-11  -  Supported
    Install location /home/vagrant/coder already exists. Do you want to overwrite it? (y/n): y
    Project coder (7.x-2.4) downloaded to /home/vagrant/coder.                                                                                [success]
    Project coder contains 6 modules: drupalcs, bad, bad2, coder_upgrade, coder_review, coder.

For un-attended installs, I'd highly recommend using 'drush make' instead, as it easily supports pinning a project to a specific major version.

**Comment by greg-1-anderson** [comment]
There was a big controversial discussion about this back on the drupal.org issue queue some time ago.  The eventual conclusion is that, if a module has no recommended release, then we want Drush to prompt you, rather than just giving a warning and returning a stable-but-unsupported version.

--choice=1 is the recommended workaround for scripts -- or just use `drush make`, as @ergonlogic says above.

**Comment by AohRveTPV** [comment]
> --choice=1 is the recommended workaround for scripts

In general this will not work reliably because other releases may be added/removed, changing the choices.

> There was a big controversial discussion about this back on the drupal.org issue queue some time ago. The eventual conclusion was that, if a module has no recommended release, then we want Drush to prompt you, rather than just giving a warning and returning a stable-but-unsupported version.

Drush already automatically downloads non-recommended, supported releases without prompting:

```
$ drush dl coder
Project coder (7.x-1.2) downloaded to /var/www/drupal7/sites/all/modules/coder.                                [success]
Project coder contains 3 modules: coder_review, coder_upgrade, coder.
```

I am just requesting the ability to specify *which* non-recommended, supported release to download.  I would like a reliable command that downloads, for instance, the latest 7.x-2.x release.

> For un-attended installs, I'd highly recommend using 'drush make' instead, as it easily supports pinning a project to a specific major version.

I appreciate the suggestion, but creating a makefile in order to download the desired version of a module would seem to be a heavyweight or complex solution to a problem that could be solved with a single command-line option.  In my use case I am not building a site from scratch, I am merely trying to download a module as part of a larger script.  It does not seem like a reasonable solution to me to within a script create an entire makefile and run it, and expect readers of the script to learn the syntax of Drush make files just to understand it.

What would be wrong with these possibilities for downloading a specific supported release branch:
```
drush pm-download --supported coder-7.x-2.x
drush pm-download --major=2 coder
```

I could develop a patch.

**Comment by AohRveTPV** [comment]
This syntax would seem to make the most sense to me:
```
# Download latest 7.x stable release from preferred branch.
drush pm-download coder

# Download latest 7.x-2.x stable release.
drush pm-download coder-7.x-2.x

# Download latest 7.x-2.x development release.
drush pm-download coder-7.x-2.x-dev
```

But unfortunately the second command would currently download the development release.

**Comment by greg-1-anderson** [comment]
Yes, what you said makes sense.

This usecase is actually very similar to #1174, so rather than re-open this issue, I'm just going to send you over there.

**Comment by greg-1-anderson** [comment]
Yes, as you said, 7.x-2.x currently means 'dev'; we allow changes that break behavior across major versions of Drush, but I think this one might be too big, as people have been used to this meaning 'dev' for a long time now.  Not out of the question, but not my first choice.

**Comment by AohRveTPV** [comment]
Thanks.  Trying to find time to try adding a --stable option.
