### ISSUE TITLE
Various places call drush_copy_dir with wrong argument (TRUE instead of FILE_EXISTS_OVERWRITE)

### ISSUE THREAD

**Issue by hefox** [drush-ops/drush#1184]
In https://www.drupal.org/node/1539076, drush_copy_dir's argument was changed, but various places call it with TRUE which bypasses the overwrite handling.

To see this in action, have two conflicting make files, one that defines a project with a version, the other that gets the project from git. Instead of deleting the overwritten pm downloaded, the project is merged. Our issue is that both definitions applied the same patch so patch was unable to be applied because it already was.

**Comment by weitzman** [comment]
Lets see if @jonhattan can review this.
