### ISSUE TITLE
drush config-export fails on beta 6

### ISSUE THREAD

**Issue by derheap** [drush-ops/drush#1187]
When I try do export a config from Drupal 8 beta 6 Drush fails with the following error:

$ drush cex

PHP Fatal error:  Call to undefined method Drupal::hasContainer() in /usr/local/bin/drush/lib/Drush/Boot/bootstrap.inc on line 824
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/drush/drush.php:0
PHP   2. drush_main() /usr/local/bin/drush/drush.php:11
PHP   3. Drush\Boot\DrupalBoot->bootstrap_and_dispatch() /usr/local/bin/drush/drush.php:74
PHP   4. drush_bootstrap_to_phase() /usr/local/bin/drush/lib/Drush/Boot/DrupalBoot.php:35
PHP   5. drush_bootstrap() /usr/local/bin/drush/lib/Drush/Boot/bootstrap.inc:308
PHP   6. _drush_bootstrap_drupal_configuration() /usr/local/bin/drush/lib/Drush/Boot/bootstrap.inc:186
PHP   7. drupal8_bootstrap() /usr/local/bin/drush/lib/Drush/Boot/bootstrap.inc:630

Fatal error: Call to undefined method Drupal::hasContainer() in /usr/local/bin/drush/lib/Drush/Boot/bootstrap.inc on line 824

**Comment by PLPeeters** [comment]
I fixed this by replacing the following line (line 824) in `/usr/local/bin/drush/lib/Drush/Boot/bootstrap.inc`:

~~~
return \Drupal::hasContainer() ? DRUPAL_BOOTSTRAP_CODE : DRUPAL_BOOTSTRAP_CONFIGURATION;
~~~

with

~~~ 
return \Drupal::getContainer() !== NULL ? DRUPAL_BOOTSTRAP_CODE : DRUPAL_BOOTSTRAP_CONFIGURATION;
~~~

**Comment by greg-1-anderson** [comment]
`drush cex` with \Drupal::hasContainer() is working for me, with a fairly recent D8 build--newer than beta 6.

This recently changed in the other direction (FROM getContainer TO hasContainer):

```
$ git show 13d75443
commit 13d754433d33f29f96edbf4bbf4a4dc335f66450
Author: Tim Plunkett <junk@plnktt.com>
Date:   Thu Feb 5 12:54:58 2015 -0800

    Use \Drupal::hasContainer() instead of checking if \Drupal::getContainer() === NULL

diff --git a/lib/Drush/Boot/bootstrap.inc b/lib/Drush/Boot/bootstrap.inc
index 956c753..49df7bf 100644
--- a/lib/Drush/Boot/bootstrap.inc
+++ b/lib/Drush/Boot/bootstrap.inc
@@ -821,5 +821,5 @@ function drupal8_bootstrap($phase = NULL) {
     $boot_level = $phase;
   }
 
-  return \Drupal::getContainer() ? DRUPAL_BOOTSTRAP_CODE : DRUPAL_BOOTSTRAP_CONFIGURATION;
+  return \Drupal::hasContainer() ? DRUPAL_BOOTSTRAP_CODE : DRUPAL_BOOTSTRAP_CONFIGURATION;
 }
```

The only thing we really support right now is using the head of Drush master with the head of Drupal 8.0.x.  We should probably start publishing recommended Drush tags to use with corresponding Drupal 8 beta releases.  Try Drush 7.0.0-alpha8 with Drupal 8.0-beta6.
