### ISSUE TITLE
Add themes installed in a profile to the commandfiles

### ISSUE THREAD

**Issue by DuaelFr** [drush-ops/drush#1192]
Some themes, like Omega, implements drush commands to ease themers' life.
It works well while the theme is installed under `sites/*/themes` but when it's into `profiles/*/themes` it is not added to the commandfiles list. That make these drush commands unusable even after having cleared the drush cache many times.

I suppose the problem comes from the `_drush_find_commandfiles()` function because in the `DRUSH_BOOTSTRAP_DRUPAL_FULL` case we only consider enabled modules and not enabled themes.

Steps to reproduce:

1. Install drupal 7.x using the standard profile
1. Download omega-7.x-4.x-dev into profiles/standard/themes
1. Enable omega
1. Clear drush's cache
1. Try to run `drush omega-wizard`

If you do the same but you put Omega into sites/all/themes, the drush command will run without any problem.

**Comment by ellioseven** [comment]
I'm having the same issue with omega in a profile

**Comment by jonraedeke** [comment]
Exact same issue. Thanks for posting. I hope someone has a solution. This is a problem when using a distro like Acquia COD. 

After I run `drush cc drush`, I see the omega commands in `drush help --filter=omega`. After I try `drush owiz`, I get `The drush command 'owiz' could not be found.` and the omega commands are no longer listed in the drush help.

**Comment by weitzman** [comment]
What version of Drush are folks using?

**Comment by jonraedeke** [comment]
7.0-alpha7

**Comment by DuaelFr** [comment]
7.0-dev

**Comment by weitzman** [comment]
Drush commandfile searching doesn't treat themes nicely at all. See http://api.drush.org/api/drush/lib%21Drush%21Boot%21command.inc/function/_drush_find_commandfiles/master

**Comment by ellioseven** [comment]
We managed to fix this by downgrading our version from 7 to 6.5-dev

**Comment by jonraedeke** [comment]
6.5.0 doesn't work for me

**Comment by jonraedeke** [comment]
I worked around this by copying the Omega theme from the profile to sites/all/themes. This overrides the profile version and allows me to work with the Omega drush commands. Obviously, not ideal.

**Comment by greg-1-anderson** [comment]
Commandfile searching moved here:

https://github.com/drush-ops/drush/blob/master/lib/Drush/Boot/DrupalBoot.php#L92

This is altered slightly by #1258, but the situation is not improved.

Seems like we could include `$searchpath[] = "profiles/$profile/themes";` in the 'not going to reach full bootstrap' case, and use drush_get_themes() to duplicate the process currently done for modules.  I do notice, though, that drush_get_themes() calls `system_rebuild_theme_data()` (or `\Drupal::service('theme_handler')->rebuildThemeData()`) every time; maybe this code was left this way for performance reasons?  If so, it seems like it wouldn't be too bad to just add `$searchpath[] = "profiles/$profile/themes";` as an unconditional commandfile searchpath.  That way, commandfiles in themes for the installed profile would always be available.

**Comment by greg-1-anderson** [comment]
I just took some non-scientific, inadequate sample-size, Drupal-7-only, but probably approximately-accurate-anyway time measurements.  On one particular site:
```
drush ev 'drush_get_themes();' - about 1.1s on average
drush ev 'drush_get_modules();' - about 1.4s on average
drush ev 'drush_get_themes(); drush_get_modules();' - about 1.5s on average
```
Might as well do the right thing with themes, eh?

**Comment by greg-1-anderson** [comment]
Actually, the problem is that there is no 'drush_theme_list()' function.  I made a start in the above PR, but the D8 version still needs to have the correct method filled in.

**Comment by weitzman** [comment]
Lets just continue discussion in the PR #1260
