### ISSUE TITLE
Drush needs a higher bootstrap level to run... on Archlinux

### ISSUE THREAD

**Issue by bavramor** [drush-ops/drush#1193]
Hi mates,

I am using Archlinux as OS. I found a lot of anwers for my issue in context of Mamp, but not in context to Archlinux. This is what i try to fix this issue:
- drush sqlc works !
- open_basedir =/srv/http/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/:/home/foo/data/Webdesign/Webseiten/:/usr/lib/drush/:/etc/drush/:/usr/share/drush/
- my ~/.drush/php.ini
  :

open_basedir =
safe_mode=
disable_functions=
disable_classes=
magic_quotes_gpc=

I can execute the command „drush dl mymodule“, but when i execute „drush en mymodul“ this issue comes:

Command pm-enable needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.                                                    [error]
The drush command 'en admin_menu' could not be executed.                                                                                                                                                  [error]
Drush was not able to start (bootstrap) the Drupal database.                                                                                                                                              [error]
Hint: This may occur when Drush is trying to:
- bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working database setup by specifying the URI to use with the --uri
  parameter on the command line. See `drush topic docs-aliases` for details.
- connect the database through a socket. The socket file may be wrong or the php-cli may have no access to it in a jailed shell. See http://drupal.org/node/1428638 for details.

Drush was attempting to connect to: 
 Drupal version         :  7.34  
 Site URI               :  http://default  
 Database driver        :  mysql  
 Database username      :  root  
 Database name          :  drupal_bootstrap_db  
 Default theme          :  garland  
 Administration theme   :  garland  
 PHP executable         :  /usr/bin/php  
 PHP configuration      :  /home/bavramor/.drush/php.ini /home/bavramor/.drush/php.ini 
 PHP OS                 :  Linux  
 Drush version          :  6.4.0  
 Drush configuration    :  
 Drush alias files      :  /etc/drush/example.aliases.drushrc.php  
 Drupal root            :  /home/bavramor/data/Webdesign/Webseiten/drupal-bootstrap  
 Site path              :  sites/default  
 File directory path    :  sites/default/files        

Please help me

**Comment by frederickjh** [comment]
Were you in the Drupal webroot when you ran the drush command?  Drupal webroot is where <b>index.php</b> lives and the <b>sites</b> folder.  If you were not then Drush does not know which Drupal site you want it to work on. You can also create site aliases and then run commands on Drupal sites that you are not currently on.

**Comment by dtolj** [comment]
@bavramor I have the same problem on Linux. I looked at the jailedshell issue but no luck. @frederickjh I am running drush commend from my webroot. Running drush dl <module> works but any local commands which interact with the database fails.
My website is running fine however and this issue in only happening in prod, in staging I don't have any drush issues.

Here is the output when i run 'drush pm-list'
NOTE that is doesn't even display Database information.

Drush was attempting to connect to:
 Drupal version         :  7.32
 Site URI               :  http://default
 PHP executable         :  /usr/bin/php
 PHP configuration      :  /etc/php.ini
 PHP OS                 :  Linux
 Drush script           :  /root/.composer/vendor/drush/drush/drush.php
 Drush version          :  7.0.0
 Drush temp directory   :  /tmp
 Drush configuration    :
 Drush alias files      :  /root/.drush/otn.aliases.drushrc.php
 Drupal root            :  /var/www/html/otn
 Site path              :  sites/default

**Comment by frederickjh** [comment]
Hi @dtolj!

My guess is drush cannot access the database that drupal lives in using the settings in the sites/default/settings.php file.

Do you get a mysql prompt when you run
`drush sql-cli`
If you do then you can type exit to get out of it. If not then I would try see what settings you need to get a mysql prompt on the command line without drush using the mysql program.

Can you run 
`drush --debug pm-list'
and then give us the output?

Also run 
`drush core-config`
and
`drush core-status`
they should tell us a lot about what drush knows and does not know.
Greetings,
Frederick

**Comment by dtolj** [comment]
The problem was due to PHP 5.3.3, I have upgraded to 5.4 and problem was solved.
