### ISSUE TITLE
Allow to override or disable the watchdog-show message length

### ISSUE THREAD

**Issue by marcvangend** [drush-ops/drush#1197]
Drush watchdog-show truncates messages at 188 characters. This value is hard-coded and there is no way to override it. Can we have an option to override the message length or disable truncating completely?

Once trunctation is made optional, I would expect that the --full option would really show the full message.

**Comment by lokapujya** [comment]
try this, I think it might show the full message:
drush @d8 --extended

**Comment by marcvangend** [comment]
Thanks, that works. And if you really need to know everything:

     drush ws --extended --full
