### ISSUE TITLE
Documentation: Installing drush 6.5 on Windows using zip file

### ISSUE THREAD

**Issue by pkiff** [drush-ops/drush#1198]
Are there any instructions or troubleshooting advice for installing drush 6.5 using the zip file in Windows?

Theoretically, can I just unzip this into C:/drush and then run the .bat file? And that zip is supposed to already include the various libraries and rsync and msys/cygwin (or whatever) without requiring additional downloads?

(I've already successfully installed 6.0 using the MSI installer, but ran into issues with sql-dump and sql-sync that I hope can be resolved using 6.5.).

**Comment by greg-1-anderson** [comment]
If you have already used the MSI installer, then you should be able to just replace your older Drush files with a newer set of Drush files (e.g. via unzipping an archive from github).
