### ISSUE TITLE
Drush 7.0-dev only updates enabled modules in multisite environment (boa aegir) - this changes prior functioning

### ISSUE THREAD

**Issue by EdNett** [drush-ops/drush#1199]
Drush used to update all the modules and themes - even those that are not enabled, and this was good for a multisite (aegir) environment when site admins will want the secure, bug-fixed latest release of a module or theme. Now with drush 7.0-dev, drush will only update enabled modules and themes. Is there a flag to the up command in 7.0-dev, or is there a new command to update all modules and themes? Is this really the new INTENDED behavior of drush 7?  This issue relates to issue # 1045.

**Comment by EdNett** [comment]
This new behavior occurs whether or not the "Check for updates to disabled modules and themes" flag in the update module is set.  Shouldn't the update behavior follow this setting?

**Comment by EdNett** [comment]
This issue appears to have been fixed with 7.0-dev dated feb 27 2015, or:
Downloading drush mini-7-27-02-2015. Thank you.

**Comment by EdNett** [comment]
With the recent drush 7 dev updates to march 7th drush 7 dev, the "faulty" behavior is happening once again.

I request an "official" answer as to whether or not this is an error. In an aegir multisite environment, with the update core module enables and set to check update status of disabled modules and themes, are we supposed to be able to update a disabled module via drush on the command line, like we have been able to for years?

Thanks for an answer - this is a bug until / or unless you have decided to change your policy.

**Comment by greg-1-anderson** [comment]
@jonhattan?
