### ISSUE TITLE
Running `drush cache-rebuild` makes site unusable (D8)

### ISSUE THREAD

**Issue by alerque** [drush-ops/drush#1201]
Using the latest alpha of Drush (7.0.0-alpha8) on the latest Drupal Core 8.0.x-dev (Feb 24), the `cache-rebuild` command completely borks the site into an unusable condition. Specifically the following PHP error starts getting thrown:

> Fatal error: Class 'Drupal\toolbar\PageCache\AllowToolbarPath' not found in /srv/http/sites/default/files/php/service_container/service_container_prod/6d4e334e2db7ddf6f918486747d7bab960f83fdf0ce5abb72a793ca73044424f.php on line 7264

Running `cr` again changes the hash involved but the error remains. Deleting the `sites/default/files/php` directory allows the site to run again, but drush is still hosed.

> Fatal error: Class 'Drupal\toolbar\PageCache\AllowToolbarPath' not found in /srv/http/sites/default/files/php/service_container/service_container_prod/6d4e334e2db7ddf6f918486747d7bab960f83fdf0ce5abb72a793ca73044424f.php on line 7264

**Comment by weitzman** [comment]
Try latest Drush release (alpha9) with latest drupal beta (8.0.0-beta7). Otherwise, using dev snapshots for both usually works. These combinations are working for me now.
