### ISSUE TITLE
Drush @alias rap on a d7 installation gives me error: "Unable to load class Drush\Role\Role"

### ISSUE THREAD

**Issue by rodrigoaguilera** [drush-ops/drush#1205]
Without alias works fine.

I'm using latest dev for drush 7

**Comment by weitzman** [comment]
Is it a remote alias? Do you have latest on the remote side as well?

**Comment by rodrigoaguilera** [comment]
No, is a local alias with "uri" and "root"
Is something else required?

Thanks

**Comment by weitzman** [comment]
I can reproduce this. Might be related to recent bootstrap change so assigning to @greg-1-anderson
