### ISSUE TITLE
Autoenabling modules from make file

### ISSUE THREAD

**Issue by gephaest** [drush-ops/drush#1206]
Is It possible to download and enable modules from my make file? I don't want to copying manually list of modules from make file to a command ``drush en [modules]``. It's hard for automating.

Thanks.

**Comment by weitzman** [comment]
Not possible. Write a script which runs make and then site-install or
pm-enable.

**Comment by gephaest** [comment]
This is planned in future or not?

**Comment by weitzman** [comment]
Not planned. We provide base level commands, and we expect you to folks to use scripts to glue together workflows.
