### ISSUE TITLE
have 'drush download' use the standard modules folder structure of a given subsite

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#1208]
If I do:

drush @foo dl bar

then bar is downloaded to sites/all/modules

I can use --destination to specify an explicit folder, but what I would like to happen is for the use of @foo to mean the project is downloaded to sites/foo-folder/modules.

Rationale: less typing, and drush also knows to download to a /contrib folder if that is present.

**Comment by greg-1-anderson** [comment]
If you have both sites/all and sites/foo, how would Drush know which one to use?

I think this was rejected in the past, but I can't recall why.  There's probably an issue on drupal.org somewhere.

I think it might be fine to use sites/foo instead of sites/all iff the former exists and has modules, and the later does not.

**Comment by joachim-n** [comment]
> If you have both sites/all and sites/foo, how would Drush know which one to use?

If I say 'drush dl bar' then I mean sites/all; if I say 'drush @foo dl bar' then I mean sites/foo.

It's true that this wouldn't work when the dl command is automatically invoked by a pm-enable if I want it in sites/all, but I can live with that :)

Alternatively, the @foo that gives the folder destination could be specified as an option rather than as the first parameter?

**Comment by greg-1-anderson** [comment]
Some people who use 'drush @foo dl bar' are going to expect it to be downloaded to sites/all/modules, as it always has.

**Comment by jonhattan** [comment]
You can enforce the site dir by using `drush @foo dl bar --use-site-dir`.

We should maintain the current functioning, where people expect that `drush @foo dl bar`, run from any location in the filesystem means: "download bar to sites/all in the drupal root addressed by @foo".

**Comment by joachim-n** [comment]
> drush @foo dl bar, run from any location in the filesystem means: "download bar to sites/all in the drupal root addressed by @foo".

But that isn't what happens. Having that happen is what this feature request was about.

**Comment by jonhattan** [comment]
Sorry I think you understood it wrong. This is current functioning, and the one I think it's fine:

```
$ cd /tmp
$ drush @d7 dl date
Project date (7.x-2.8) downloaded to /var/www/d7/docroot/sites/all/modules/date.
$ drush @d7 dl date --use-site-dir
Project date (7.x-2.8) downloaded to /var/www/d7/docroot/sites/default/modules/date.
```
