### ISSUE TITLE
Drush 7 Alpha 8 not compatible with D8 beta 7. Can we have a new alpha release of Drush 7?

### ISSUE THREAD

**Issue by paul-mckibben** [drush-ops/drush#1209]
Apparently, the fix for https://www.drupal.org/node/2363341, which is in the new Drupal 8 beta 7, requires a corresponding drush update. Alpha 8 does not have the update, but I see that the latest code in master is working. Can we have a new alpha release with this fix? This will help in managing our vagrant environment.

**Comment by greg-1-anderson** [comment]
Moshe and I just discussed making Drush releases at the same time as Drupal releases; since Drupal 8 beta 7 came out yesterday, it seems that we are due.

I'll try to fix some of the recent regressions today, so that we can make a release.

**Comment by greg-1-anderson** [comment]
I think this should happen soon.  Release planning discussion is happening at #1123.

**Comment by greg-1-anderson** [comment]
Alpha 9 released. https://github.com/drush-ops/drush/releases/tag/7.0.0-alpha9
