### ISSUE TITLE
Drush runserver has trouble executing actions on Drupal 8.

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#1211]
As an experiment, I was trying to reproduce this issue, using today's 8.0.x-dev (close to 8.0-beta7):

https://www.drupal.org/node/2442255

After navigating to Home >> Administration >> Configuration >> People >> Account Settings >> Manage Fields, and selecting "Text (Formatted)" and giving it a label, when I click "Save and continue" I get:
```
The requested resource /admin/config/people/accounts/fields/user.user.field_weakness/storage?bundle=user&destinations%5B0%5D%5Broute_name%5D=entity.field_config.user_field_edit_form&destinations%5B0%5D%5Broute_parameters%5D%5Bbundle%5D=user&destinations%5B0%5D%5Broute_parameters%5D%5Bfield_config%5D=user.user.field_weakness&destinations%5B1%5D%5Broute_name%5D=entity.user.field_ui_fields&destinations%5B1%5D%5Broute_parameters%5D%5Bbundle%5D=user&destinations%5B1%5D%5Broute_parameters%5D%5Bfield_config%5D=user.user.field_weakness&destinations%5B2%5D=/admin/config/people/accounts/fields/add-field%3Fq%3Dadmin/config/people/accounts/fields/add-field was not found on this server.
```

The field is added successfully.  If there is an error, then it is correctly reported w/out throwing an error similar to the above.

Maybe this is just a general Drupal 8 bug?  I'm not sure, because I think I've seen this before on runserver, but not when running with an actual web server.  I'll try to reproduce tomorrow, and if the problem is not unique to runserver, I will close this.

**Comment by greg-1-anderson** [comment]
Confirmed: this problem DOES happen with `drush runserver` using sqlite OR mysql databases, but DOES NOT happen with a regular webserver using mysql.

**Comment by greg-1-anderson** [comment]
Okay, progress!

This issue does **NOT** happen when calling the php built-in webserver directly with the patch provided in https://www.drupal.org/node/1543858

This should be fixable now.

**Comment by pendashteh** [comment]
Use **Drupal Console** to run the built-in server:

`drupal server`

[https://hechoendrupal.gitbooks.io/drupal-console/content/en/commands/server.html](https://hechoendrupal.gitbooks.io/drupal-console/content/en/commands/server.html)

This worked for me running D8 using SQLite with PHP built-in server when using `PHP -s` directly would not work.

**Comment by weitzman** [comment]
drush runserver works every day for me on Drupal 8.

**Comment by adal2404-Real** [comment]
> Use **Drupal Console** to run the built-in server:
> 
> `drupal server`
> 
> https://hechoendrupal.gitbooks.io/drupal-console/content/en/commands/server.html
> 
> This worked for me running D8 using SQLite with PHP built-in server when using `PHP -S` directly would not work.

Thanks, this worked for me too, just cd to drupal project and run php like that link or set  working directory to drupal project after run it.
