### ISSUE TITLE
Problem with special characters in SQLSRV driver

### ISSUE THREAD

**Issue by david-garcia-garcia** [drush-ops/drush#1212]
In SQL\SQLsqlsrv.php when creating the command line based sentence to open database connection, if any of the parameters (username or password) have special characters in them (such as an ampersand) the command will fail.

We can either escape special characters (with ^) or close them inside quotes.

return ' -S ' . $host . ' -d ' . $database . ' -U ' . $this->db_spec['username'] . ' -P ' . '"' . $this->db_spec['password'] . '"';

**Comment by weitzman** [comment]
See the escaping pattern used at bottom of http://api.drush.org/api/drush/lib%21Drush%21Sql%21Sqlmysql.php/function/Sqlmysql%3A%3Acreds/master. The key line is $this->params_to_options($parameters);

**Comment by david-garcia-garcia** [comment]
I updated the pull request.
