### ISSUE TITLE
Broken link on drupal.org redirect page

### ISSUE THREAD

**Issue by kenahoo** [drush-ops/drush#1217]
On https://www.drupal.org/node/add/project-issue/drush , the user is told to "report bugs on our Github project".  But the link for "our Github project" is broken, it's missing the http://, so the user gets a 404.

**Comment by weitzman** [comment]
I think that message comes from the drupal.org codebase. I dont see that I can change it by editing the Drush project on drupal.org. I think someone needs to pursue this at http://drupal.org/project/issues/webmasters
