### ISSUE TITLE
Proposal for commands to merge configuration changes between two sites.

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#1219]
After talking with @weitzman and @davidstrauss, and trying some experimental merges manually, I have come up with the following proposal for configuration management commands.

## Problem Statement
Sometimes, site developers make configuration changes on dev / staging that they wish to deploy to live; however, the site administrators may have, at the same time, made configuration changes of their own on the production server.  It then becomes necessary to merge the prod configuration into the dev configuration.

## Proposed Solution
`config-merge` and `config-push` commands.  No code exists yet; this is just a proposal.  The code seems easy enough to write, though.

### Configuration Merge

`$ drush @dev config-merge @live label`

The `label` defaults to `staging`, just as it does in the `drush cex` and `drush cim` commands.  The command will fail if @dev is not under git revision control.  If it is, then the following operations will be done:

1. A new branch `live-config` in the git repository for @dev is created to hold configuration from @live.  If this branch already exists, it will be re-used.
1. `drush @live cex label` is executed via drush_invoke_process().
1. Copy the exported configuration from @live to @dev, probably via rsync
1. Commit the new changes to the branch prepared for @live.  Exit with "nothing to do" if there are no changes to be committed.
1. Run `drush @dev cex label`
1. Commit this exported configuration. (QUESTION: Create a temp branch `dev-config`, or just use the current branch?)
1. `git checkout live-config && git rebase dev-config`
1. At this point, the `dev-config` branch may be deleted, if it is a temp branch.
1. If there are MERGE CONFLICTS: prompt the user and run 3-way diff tool.

At this point, there are a lot of different situations that can arise.  There might be merge conflicts, or there might not.  There might be changes from @live, or @dev, or none.  The developer will need to test before anything else is done.  In order to test, it will be necessary to run `drush @dev cim label`, but this cannot be done until the merge is successfully completed.  Maybe config-merge just advises the user to run this command, but does not attempt to run it.

Similarly, configuration deployment might be done in a number of different ways, depending on the developer's workflow.  The config-merge command therefore should not attempt to do any deployment.

It should be okay to run config-merge over and over again, with or without running `drush config-push` in between, and with or without changes to the @dev and @live sites, without causing any problems (e.g. accidental "removals" in the diff that should not be there) with the 3-way merge.

### Configuration Push

We could potentially provide a simple "config-push" example deployment plan.  It is not required that the developer use "config-push" in order to use "config-merge" iteratively; if another deployment mechanism is in place, then this command may be ignored.

`$ drush @dev config-push @live label`

Again, `label` defaults to `staging`.

1. Determine the name of the branch that config-merge would use with the @live site. Fail if it does not exist.
1. rsync the configuration data from the branch prepared for @live to the @live site
1. `drush @live cim label`

ASSUMES that the user has done the 3-way merge first, so overwrites target config. There should be a strong warning (like sql-sync and rsync) that data is about to be overwritten.

This command is optional, but users who are new to config-merge might wonder how to deploy back to production without it.  `drush @live config-merge @dev label` would work, in a pinch, but switching branches on the production site would probably be a bad idea, and of course running a GUI mergetool on the remote system might be inconvenient as well.

Perhaps gitlib could be used to do some of these operations without actually switching the branch, which might have some benefit (e.g. when merging with a remote production target); however, the main purpose of the `config-merge` operation is to run `git mergetool`, and this command requires that the appropriate branch be checked out in the working set.

**Comment by weitzman** [comment]
This looks really strong. Thanks for working through this.

config-merge
==============
1) What is the basis for the new branch? Do we branch off of whatever the dev has checked out at the time? Also, what is the benefit of reusing this branch?

2) Use tempdir as we do in drush_config_import(): `drush_invoke_process('@live', 'config-export', array(), array('destination' => drush_tempdir()))`

3) %config-staging path is available: `drush_invoke_process('@self', 'core-rsync', array(@live:%config-staging, @dev:%config-staging)`

9) After successful merge and test, we are left with good code on `live-config` branch. This has to merged into master or whatever the devs are using, no? Not sure if this should be part of the config-merge or not.

config-push
==============
At least at Acquia, we have assumed that config deployment always happens as part of a code deploy, and not separately. But I can see the utility of this for cowboy workflows.

**Comment by greg-1-anderson** [comment]
1) The impetus for reusing the live-config branch was to keep track of the common base commit for the 3-way merge.  Sometimes, when doing merge-diffing in a vcs workflow, you can get situations where you have false removal sections in your diff.

I should draw a picture -- but imagine the following workflow.

PHASE I:

A developer makes config changes to dev and live; call them changeset D1 and L1, respectively.

The developer then runs config-merge.  Dev now has D1 + L1, and live has L1.

PHASE 2:

Without deploying, the developer makes more config changes to dev and live; these are D2 and L2.

Dev now has D1 + L1 + D2, and live has L1 + L2.

The developer then runs config-merge.  If we re-use the same branch from phase 1, then the base commit that was made before D1 was committed.  If we just make a new branch, and we don't have some other magic way to know which base commit to use, then there is a danger that we might use a base commit AFTER the D1 commit was made.  If we use a base commit after D1, then the 3-way merge will show the live branch backing out the D1 commit.  If there are no conflicts, this might even happen silently, without the developer seeing the removal in the diff.

Is that clear?  I can whip out a graphics program and draw a diagram if it would help visualize the situation.

There are other options besides re-using a branch to solve this problem, though.  For example, if we had some way of knowing which commit was used to deploy to live, then we could use this as the base commit.  We might allow the user to specify the base commit with an optional parameter, for example.  Furthermore, we could provide a sample policy file that did pattern matching on the available git tags, and used the most recent matching tag as the "deployed to live" commit.  Devs could then customize the matching code to align with their deployment policy (if they tag the most recent deployment, anyway).

We could also assume that the developer never commits the development configuration until it is time to deploy to live.  If we instructed developers to use this workflow, and they very strictly never committed development configuration prior to a deployment to live, then we could use any recent commit (from the latest deployment to live or later), and D1 would never be included, so it would never be removed by iterative use of config-merge.

It is important to note that re-using the live-config branch is **not** a guaranteed solution to this problem; it will have a *tendency* to help the developer get the right base commit, but depending on the exact workflow used, there would be a danger that a dev would accidentally back out a development config change before it is deployed to live.  This could be very very bad, e.g. if someone made a quick minor dev config change before a deployment, and accidentally silently backed out the big config change everyone had been working with all week.

Subtle interactions like this are critical to the correct operation of this command.  It is critical that we correctly identify the base commit when running config-merge.  If we always use a good base commit, then everyone will love this command. If we occasionally choose the wrong one, it will cause a lot of heartache.

I am leaning towards "only commit config (to main branch) during deploy" -- which is to say, fix it by policy -- but this is very vulnerable to user error when folks don't understand.

Maybe the real danger here is the "pull live config via rsync" step.  Maybe if we require that live config be deployed via git, and we used git push / git pull to bring the live config back to the dev machine, it would be safer.  I need to analyze this more, but off the top of my head, it seems like it would be okay.  However, I don't like the commit-from-live workflow.  This is mitigated by the fact that at least the commit would be happening via Drush, and not via the webserver.

Feedback on this appreciated.

2) & 3) Great tips, thanks.

9) I thought it was best to not try to make assumptions about what the dev wanted to use with the successfully-merged branch, and let them manually put it where it needs to go.  One thing we might consider doing automatically is `drush @dev cim` after a successful merge, as the dev will always want to import the configuration for testing.

I am on the fence about config-push.  There are a lot of different ways that a dev might do deployment.  Pulling config info into the 'live-config' branch via rsync seems safe (that is, this operation can be done without touching whatever assumptions are made in the developer's deployment workflow, as long as you can ssh / rsync from live), but as you mention, an out-of-band deploy is not guaranteed to be compatible.  If a dev used config-push, and did not remember to merge the live-config branch into the main branch, then the next code deploy would overwrite the cowboy config.

Maybe we should just omit config-push, and advocate code + config as a standard deployment process.

**Comment by weitzman** [comment]
I'm a bit green with 3 way merge, so some of that is over my head. In general, I'm in favor of simpler solutions to start. So, proving a ref for the 3 way via a param sounds good to me. Acquia customers can discover the ref an [API call](http://cloudapi.acquia.com/#GET__sites__site_envs__env-instance_route). Your tag search heuristic sounds useful as well. I'm curious how the proposal changes if we rely on this base commit param.

**Comment by beejeebus** [comment]
great to see this proposal. i'll be pointing people at DrupalSouth to this during my CMI talk :-)

i like the idea of a 'tracking branch' for configuratoin changes against @prod as the source of changes to pull back to @dev.

essentially, encouraging the practice of creating such a branch for each deploy, and 'automatically' applying commits to this branch from live @prod events. this is one of the use cases that led to the [config_log module](https://www.drupal.org/project/config_log). a drush command or worker process can read out the config_log changes and turn them in to commits.

**Comment by davidstrauss** [comment]
@weitzman Supporting three-way merge properly was something @greg-1-anderson and I agreed on easily when we discussed approaches. The only question was whether the three-way computation should happen in git or by calling a tree-way merge tool or library directly.

The case for merging in git is (1) familiar conflict resolution tools, (2) merge ancestry visibility in git's tools after the merge, (3) branch and tag history providing automatic "base" detection, and (4) a rich set of GUI tools and web services related to git.

The case for merging outside of git is (a) avoiding creation of a ghost branch or tag that serves as the merge source, (b) canonicalization of the "base," "theirs," and "ours" prior to merging (cleaner diffs), (c) the possibility of YAML semantic awareness for things like diff computation, (d) higher-level conflict detection (like a View referencing a field that got removed), and (e) the option to provide our own pluggable conflict resolution.

That said, I think git is the right option. I think the likelihood that we (as a community) will do (c) thorough (e) well enough to justify avoiding git's tools is low.

Here's a nice discussion of why three-way merging is important:
http://blog.trumpi.co.za/the-secrets-of-understanding-3-way-merges/

**Comment by greg-1-anderson** [comment]
The proposal does not change much if we assume a --base option to specify the base commit.  I have copied the original proposal below; new parts are in italics, removed steps are in strikethrough.

1. *The base commit can be specified via the --base option.  If the base commit is not provided, then Drush calls a 'find base commit' hook.  After the base commit is determined, drush calls 'base commit alter', to allow policy files to confirm that the starting conditions are valid.  We can provide sample policies for different environments, to help folks customize to match their workflow.  We then check out the base revision (detached HEAD), and from there, make a new temporary branch `live-config` to work with.*  ~~A new branch live-config in the git repository for @dev is created to hold configuration from @live. If this branch already exists, it will be re-used.~~
1. drush @live cex label is executed via drush_invoke_process().
1. Copy the exported configuration from @live to @dev, probably via rsync
1. Commit the new changes to the branch prepared for @live. Exit with "nothing to do" if there are no changes to be committed.
1. Run drush @dev cex label
1. Commit this exported configuration into a temporary branch `dev-config`.
1. `git checkout live-config && git rebase dev-config`
1. Delete the dev-config branch.  *Delete the live-config branch*
1. If there are MERGE CONFLICTS: prompt the user and run 3-way diff tool.

It wouldn't be hard to introduce the concept of a tracking branch either.  We could add an option, --tracking-branch, that allowed the user to specify it explicitly.  The 'find' and 'alter' hooks could be provided with both the tracking branch and base commit, so the policy file could decide whether it wanted to use a base commit with temporary branches, or a "follow-along" tracking branch.  A policy branch that used a tag search would also be feasibly (this would just be another way of finding the base commit).

If the config-merge command could not find a base commit OR a tracking branch, then it could run under the presumption that there have been NO commits of dev or live config since the last deploy from dev to live.  We could print out a big scary warning to advise the user that they might lose configuration data from the 'dev' side if this is not the case.

The config_log module is interesting.  Again, I don't like the idea of requiring commits  on production, but I wonder if the diff + config log might help us to detect when config is being undesirably backed out due to a poorly-chosen base commit.  So, the pattern is that you see `-` lines in the diff, but these do not correspond with any changes in the commit log.  Or, if you are running the config_log module, then you could find the base commit by finding some commit that was made on live that is already merged into the branch that dev is on.  This presupposes that you can detect commits that were added by config_log.  Right now this is seeming too complicated to me, but perhaps a policy file could attempt to figure this out.

I am still wondering if there is some magic we can do to reliably find the base commit *just* by running code on @dev and @live without requiring any commits to be pushed from @live.  My issue with committing from production is that, in the unlikely case of a compromised site, if the production side can't push to the repository, than you know that you don't need to audit the commit log for unauthorized content.  Maybe folks who think that this concern is more paranoid than necessary could use a policy file that pushed commits from live to dev, and then used git to reliably find the base commit between the two branches.

**Comment by greg-1-anderson** [comment]
@davidstrauss I read your post after I put mine up.  I think at the end of the day I (still) agree with you--the benefits of committing from live outweigh the risks.  I can't help hoping for a magic silver bullet to find the base commit, but I don't think anything is going to come up.

Note also that `git mergetool` already supports a pluggable merge tool, so you can strike (e).  (3) is the poison pill that makes the non-git case hard.

Also, I'd like to clarify that I think that git on dev should always be relied on; by "non-git case" I mean without requiring access to git on the production side.

**Comment by greg-1-anderson** [comment]
I just discussed all of this with @joshkoenig, and it seems that the best assumption is:

- Production-side config changes typically will not be committed on live
- All commits are available on the dev side (dev has fetched anything needed)
- If your deployment workflow is rational, then it should be easy for the dev to tell the tool what the last deployed hash is.  Making a tag on every deploy is a good policy to help here.

So, I think that the tool as proposed is workable / usable, and I won't agonize too much over finding the right base commit.  We can still support the idea of a policy file that will find the most recent deployment tag, or whatever, for folks who want to use it, but for the most part, we will assume that the provided base commit is the right one to use.

**Comment by weitzman** [comment]
Sounds to me like we are all on the same page. Perhaps we should detail a couple user sequences which exercise config-merge and specify expected outcome. These could become Drush integration tests. Or feel free to just start building the command.

**Comment by weitzman** [comment]
For anyone who skipped it, @davidstrauss linked to a [very instructive overview of 3-way merge](http://blog.trumpi.co.za/the-secrets-of-understanding-3-way-merges)

**Comment by greg-1-anderson** [comment]
Please see the shiny new PR.

**Comment by greg-1-anderson** [comment]
There is another important use-case to consider, in addition to the production configuration workflow.  Imagine a team building a new site with a shared staging server.  Maybe the site builders set up the configuration directly on the staging server, which can push to git.  In that instance, developers might want to use `drush config-merge` to pull changes from the site builders into their local dev machines, so they can test the change and merge into master.

The reason to use git here instead of rsync is that if you use git, then the base commit is tracked for you automatically, and you no longer need to worry about getting the wrong base commit and consequentially backing out changes.

The latest code in the PR supports both git and rsync for transporting config changes.

**Comment by greg-1-anderson** [comment]
It suddenly struck me this morning that git already has a solution for keeping track of where the base commit is in a 3-way merge that is being done in situations where the remote end cannot push directly to the repository where the merge is being done.  In fact, you might even say that git was designed for this situation, since it is a distributed tool that makes no assumptions about how distributed workers exchange patches.

When you can't push and pull code, git allows you to bundle all of your changes into a formatted diff via the `git format-patch` command.  Once the recipient has the formatted diff, it can be re-applied with `git am`.

I am going to update the PR to use `format patch` and `am` iff there is a git repository on production.  If for some reason production is deployed without the .git directory, then the raw files will continue to be rsync'ed over, as they are in the most recent PR.

I'll fix up the issues in the review comments today as well.

**Comment by greg-1-anderson** [comment]
The latest commit in the PR now used `git format-patch` by default when transferring files via rsync.  The old mechanism is still supported.

Format-patch works wonderfully vis-a-vis keeping track of the base commit, but it introduces a new problem.  Under the current algorithm, I export the current configuration on the remote machine, commit it, and make a patch based on the last commit.  If you -only- commit on the remote site using `drush config-merge`, then this works; however, if you export and commit manually, then those commits from production are lost.  Also, if you have two devs running `drush config-merge`, then one will not get any of the changes already pulled over by the other.  This is only an issue if the devs are not promptly merging their merges back into the master branch, but it still could be an issue.

I'm going to try to get git to tell me the history of branches that the dev-side feature branch was created from.  If I send this list over to the staging / production server, it could probably find the closest common branch, and find the base commit from there.  If using format-patch, it would not hurt to include too many commits, as git will ignore any that have already been merged in.  Once this feature is added, the format-patch case should work a lot better.

**Comment by weitzman** [comment]
config-merge was committed so closing this. feel free top reopen as needed.
