### ISSUE TITLE
cache-clear option for role-add/remove-perm doesn't work

### ISSUE THREAD

**Issue by PLPeeters** [drush-ops/drush#1221]
The `cache-clear` argument for the `role-add-perm` and `role-remove-perm` commands doesn't do anything. The documentation isn't really clear on how it works though, so I may be doing it wrong. Here's an example command I used:

    drush rap --cache-clear=0 administrator 'add case entity'

I also tried with `1` instead of `0` (since that seems to be the default value); same thing.

I'd need this to quickly set all my permissions automatically through a script. The script is really slow at the moment, because it clears the cache after setting each permission.

**Comment by weitzman** [comment]
What version of Drupal and Drush?

**Comment by PLPeeters** [comment]
Both the latests versions. While quickly looking through the code, I noticed there aren't any checks before firing the cache clear, so it "makes sense" for it to be broken. Maybe it's supposed to be checked somewhere other than where I looked though, so I could just have missed it.

**Comment by weitzman** [comment]
So you are using Drupal 8 and Drush7?

**Comment by PLPeeters** [comment]
Yep.
