### ISSUE TITLE
Allow specifying the temporary dir to use as an option

### ISSUE THREAD

**Issue by ergonlogic** [drush-ops/drush#1234]
In [drush_find_tmp()](http://api.drush.org/api/drush/includes%21filesystem.inc/function/drush_find_tmp/master), we already allow this to be set by an ENV var. But it'd be nice to allow this to be set in, for example, a `.drushrc.php`.

**Comment by greg-1-anderson** [comment]
A global option might be okay, but as a workaround, you could always use [putenv](http://php.net/manual/en/function.putenv.php) in your drushrc.php file.

**Comment by ergonlogic** [comment]
Yep, this is all I have in mind: https://github.com/drush-ops/drush/compare/dev/1234

**Comment by greg-1-anderson** [comment]
If we did this, we'd probably want to use 'propagate-cli-value' => TRUE, or maybe 'never-propagate'.  I don't think you'd want to use the value from a local drushrc.php file with a remote command.

**Comment by ergonlogic** [comment]
I was wondering about those parameters... Presumably we'd want it to propagate to local sub-processes, but not remote ones. It's nor clear to me which, if any, of these would allow for that.

**Comment by greg-1-anderson** [comment]
We have local-context-only, but this only works for variables that are cached in contexts.  So, you could follow the example of 'debug' et. al. and cache the value of your option in _drush_preflight_global_options(), or modify backend invoke to have a local-only flag for options.

Or just use [putenv](http://php.net/manual/en/function.putenv.php).  :)

**Comment by weitzman** [comment]
Can you describe the use case? FYI, 

1. Env variables can now be passed along to remote calls by setting name/value in a site alias
1. Dunno if you are working around #64. If so, lets fix it instead.

**Comment by weitzman** [comment]
#64 is now fixed. Please reopen if this is still needed.

**Comment by greg-1-anderson** [comment]
Also related to #1239.

**Comment by ergonlogic** [comment]
I'll try putenv. FWIW, my use case isn't addressed by the other issues. I'm running 'drush make' in a Vagrant VM, where the destination is mounted from the host via NFS. This causes a significant delay, since the final move of the complete code base from the temp dir to its final destination crosses file system boundaries. I'm thinking of putting the temp dir inside the mount to avoid this.
