### ISSUE TITLE
composer.json and composer.lock are out of sync

### ISSUE THREAD

**Issue by mpdonadio** [drush-ops/drush#1246]
I just did a fresh ```git clone https://github.com/drush-ops/drush.git``` then a ```composer install```, and got this warning:

> Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

Not sure which is correct (the .json or the .lock), or I would provide a pull request.

**Comment by greg-1-anderson** [comment]
Drush uses ~ versions for a number of components, so this message will happen periodically for folks, whenever our dependencies release new versions after our most recent commit of composer.lock.

It might be useful if we had some mechanism to remind us to run `composer update` and commit the composer.lock file periodically.  We could add a unit test that failed whenever composer.lock was out of date.  This seems overly heavy-handed and annoying, but of yet, I haven't thought of anything else that would be a more reasonable reminder.

On the flip side, we could remove all of the ~ versions, and declare only specific version numbers for our dependencies.  This would prevent Drush end-users from seeing this message, but would make it more likely that folks would be running with out-of-date dependencies.

Not sure what is best here.

**Comment by thewilkybarkid** [comment]
@greg-1-anderson That's not the case, Composer gives you this message when something has changed in the .json file (by comparing it with the hash in the .lock file). Executing `composer update --lock` will fix it.

**Comment by greg-1-anderson** [comment]
Ah, my mistake; thanks for the clarification.

I updated composer.lock and pushed it to the master branch.

**Comment by sraul2015** [comment]
I  was facing similar problem, executing below command fixed it. thanks a lot

composer update --lock

**Comment by mlabwa1** [comment]
composer update --lock worked great for me. Thanks

**Comment by nguyendangkhoa221192** [comment]
@thewilkybarkid Thanks a lot.

**Comment by greatestukonu** [comment]
how do i type that code update lock

**Comment by azril16** [comment]
wow ini sangat membantu terima kasih bro :+1:

**Comment by kennblvnp** [comment]
@greatestukonu  composer update --lock

**Comment by crazychengmm** [comment]
I rename the lock file,it would not generate again. I think it's same problem.

**Comment by abadurrahman** [comment]
no working
