### ISSUE TITLE
Cannot call ftp destination

### ISSUE THREAD

**Issue by hasinduatukorale** [drush-ops/drush#1248]
Hi,

I'm able to see the destinations by using the 'bam-destinations' command and below is my script to get an entire site backup from a ftp destination (ID of this destination is 'ftp_destination')

drush archive-dump default http://www.mysite.com/ --destination=ftp_destination

For some reason it's not uploading in to the ftp location but just creates a backup called 'ftp_destination' in my local PC.

Thanks

**Comment by weitzman** [comment]
please take this up in the bam issue queue. we dont support non-local destinations at this time.
