### ISSUE TITLE
segmentation fault when make with yaml 

### ISSUE THREAD

**Issue by lussoluca** [drush-ops/drush#1249]
Using the latest drush 7 dev version I get a segmentation fault when I try to build a site with drush make. It seem that there is a problem with the yaml length because if I split the file in more included files all works correctly.

**Comment by weitzman** [comment]
I think this has been reported before. If the error is in the parser (likely), you would want to ask the Symfony folks about this. Thats who makes our YAML component.

**Comment by lussoluca** [comment]
Hi Moshe and thanks for your reply,
I've done a little investigation and the problem is in the PCRE
implementation: in /commands/make/make.utilities.inc::571 we try to parse
the YAML file as INI and in /lib/Drush/Make/Parser/ParserIni.php::41 the
preg_match_all fails to parse big YAML file and throws the "Segmentation
fault" exception. Can we switch the test in _make_determine_format (YAML
first and then INI)? Or we need a clever way to determine if a file is in
YAML or INI format.

Thanks

Luca

On Thu, Mar 12, 2015 at 6:39 PM, Moshe Weitzman <notifications@github.com>
wrote:

> I think this has been reported before. If the error is in the parser
> (likely), you would want to ask the Symfony folks about this. Thats who
> makes our YAML component.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drush-ops/drush/issues/1249#issuecomment-78542082>.
>



-- 
Lusso Luca

**Comment by weitzman** [comment]
See #1386
