### ISSUE TITLE
$kernel->terminate() is not called

### ISSUE THREAD

**Issue by dawehner** [drush-ops/drush#1252]
For various reasons drush should call <code>$kernel->terminate</code>when drush is done with its processing.

One example is https://www.drupal.org/node/356399 which would require drush to rebuild the router.

**Comment by dawehner** [comment]
I'm trying to solve that, but its a bit tricky, because the $kernel is currently just a local static variable.

**Comment by Berdir** [comment]
I noticed that too, we should move that to a function or something.

+1 to this, because it will also allow to rely on terminate() for things like sending out an aggregated cache tag invalidation list instead of doing it immediately in an cache tag invalidation listener.

**Comment by greg-1-anderson** [comment]
This should be easier now that #1242 has landed.

**Comment by greg-1-anderson** [comment]
Fixed by #1259
