### ISSUE TITLE
sql-sync --create-db make SUPER privilege mandatory to the destination user

### ISSUE THREAD

**Issue by drzraf** [drush-ops/drush#1262]
--create-db make a:
DROP DATABASE destination
CREATE DATABASE destination
GRANT ALL PRIVILEGES ON destination.* TO destination_user

The later pose an issue, since:
- destination_user may have be created and does NOT have the SUPER privileges
- GRANT ALL should not be needed is  destination_user already has ALL to destination
- SUPER pose a security risk
- there are other way to clean the destination database, like DROP x, y, z... which does not need the SUPER privilege

In my case, I have the following log from:
```
drush -vv sql-sync @src @dst --create-db --sanitize
Calling system(echo "DROP DATABASE IF EXISTS...  GRANT ALL PRIVILEGES ON dst_db ... )
ERROR 1044 (42000) at line 1: Access denied for user
...
```
Also note that the mysql error return is ignored by the drush sql-sync command.

Could we please have an option to avoid this call to "GRANT"? and/or an alternative way to do the table cleanup without going through a DROP/CREATE DATABASE?

**Comment by weitzman** [comment]
we have improved this recently. please retry with master branch or 6.x
branch.

**Comment by weitzman** [comment]
Please post here either way after you test master.
