### ISSUE TITLE
sql-sync --sanitize should modify file_(directory|public)_path variable

### ISSUE THREAD

**Issue by drzraf** [drush-ops/drush#1274]
One of the few annoying (as in "could imply dataloss") things left in a @dev Drupal sync'ed from @prod is that those variable don't get altered.
Thus even if you changed symlink (in case both -prod and -dev, or -v1 and -v2 are on the same host), you may change files where you don't expect to.

For the very same reason --sanitization applies to emails and password, it would be nice that it applies to file*paths to.
I'd at least hope this:
```
str_replace($old-hostname, $new-hostname, file_public_path, &$ok)
if($ok) continue with the next variable
else ... use /tmp/ ?
```

**Comment by weitzman** [comment]
Sanitize is a security tool. What you describe is non-security. Core Drush will not take this on. I suggest you look into sites.php mappings as an alternative to db futzing.
