### ISSUE TITLE
create ~/.drush/cache files/directory using getenv(SUDO_USER) if exists

### ISSUE THREAD

**Issue by drzraf** [drush-ops/drush#1275]
... so that later run using the regular user owner of $HOME won't failed with a directory permission problem.
In most configuration `sudo` preserve HOME, but mkdir & co will use root/the-user-passed-to-u to create file and directory. 

Actually I don't have more hint on how to do it well other than a simple chown(SUDO_UID)
(setuid(SUDO_UID) can't then be followed by setuid(UID) if UID > SUDO_UID)

Similar issue:
https://www.drupal.org/node/1528976

**Comment by greg-1-anderson** [comment]
Check to see if your problem is fixed by #64, recently committed to the master branch.

If not, please consider an alternate solution; we don't sudo in Drush, or assume we are called by root.
