### ISSUE TITLE
drush cache-rebuild can store the wrong theme path in D8

### ISSUE THREAD

**Issue by tanc** [drush-ops/drush#1276]
I have a slightly unusual set up where I'm running Vagrant but use drush from the host system (port forwarding mysql so drush talks to the vagrant db). I noticed that I was getting a lot of warnings whilst developing a Twig based theme in Drupal 8. I tracked it down to a cache issue, where clearing caches using the UI in D8 was fine, the correct Vagrant based path was stored. When I clear caches with drush it stores the host's file path to the theme instead which throws the warning. For example, when rebuilding caches with drush cr I get this error:

Warning: include_once(/Users/tanc/Documents/Sites/vagrant_54/sites/l.gcp-main.dev/web/core/themes/seven/seven.theme): failed to open stream: No such file or directory in Drupal\Core\Extension\Extension::load() (line 145 of core/lib/Drupal/Core/Extension/Extension.php).

But clearing cache using the D8 performance admin page works fine and stores the correct serialised array in the database containing the correct value for 'root' to the D8 site (and therefore the theme). The correct value in my case is: /vagrant_sites/l.gcp-main.dev/web

The theme itself loads fine either way and I think the warning is only thrown when twig_init runs.

It would be good to try and fix this so drush cr works as expected. Whether this is a drush issue or a Drupal 8 issue I don't entirely know so I thought I'd post here first.

**Comment by weitzman** [comment]
I haven't done this before, but I think you want to setup a site alias with
a 'remote-host' that points at the ssh daemon inside vagrant and the 'root'
should be  /vagrant_sites/l.gcp-main.dev/web. Then you run commands using
that alias like `drush @gcp cc all`

**Comment by tanc** [comment]
Thanks Moshe, I've done that before with vagrant but I was hoping there might be a different solution. Feel free to close this issue for now. I think I'll try investigating a bit further into the D8 code to understand why the themes function just fine but why that particular file path is cached wrongly when using drush cr. There might be a way to resolve it within core.

**Comment by hyip** [comment]
I'd say that drush seems better than the other ways as mentioned _[here](https://www.drupal.org/documentation/clearing-rebuilding-cache)_
