### ISSUE TITLE
Unable to find a matching SQL Class. Drush cannot find your database connection details when using remote database

### ISSUE THREAD

**Issue by nkgokul** [drush-ops/drush#1277]
I have fresh Drupal 8 instance where the DB is hosted on a different server. I get the following error when I try to execute any drush command that uses database connection.

Drush Version   :  7.0-dev 
Drupal : Drupal 8 Beta 7

**Comment by weitzman** [comment]
In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.

**Comment by nkgokul** [comment]
Sorry for the inconvenience. Point noted. I have asked the question on http://drupal.stackexchange.com/questions/152586/drush-is-not-working-with-remote-database
