### ISSUE TITLE
Add option to run specific updates

### ISSUE THREAD

**Issue by ivanjaros** [drush-ops/drush#1284]
It would be nice to be able to run only a specific updates. Sometimes it is helpful to run each update one by one and observe the changes or when you are working in multidev environment and an already run update hook has changed and you want to run it again.

The already existing updb command would be just extended with --module and --id or something like that.

**Comment by weitzman** [comment]
Won't fix. Thats circumventing Drupal's dependency system and we cant support that code - too much room for error. See #1096 and the links there.
