### ISSUE TITLE
Comments that start with "#" in makefiles will make drush ignore the line underneath it

### ISSUE THREAD

**Issue by stefanruijsenaars** [drush-ops/drush#1286]
Drush should probably either throw an error or accept those comments as if they started with ";".

Ignoring the line underneath it is no good as it may lead to all sorts of unexpected behavior (wrong versions downloaded, no patch applied).

**Comment by ergonlogic** [comment]
Hash marks are not supported as comments in INI files http://en.wikipedia.org/wiki/INI_file#Comments. Just use semi-colons.
