### ISSUE TITLE
drupal 8 : "drush archive-restore" remove o+w permission on sites/default/files/php

### ISSUE THREAD

**Issue by adraoo** [drush-ops/drush#1287]
When the /php folder is not present, a "drush cr" recreate it with ugo+w permission. When a user browses the website then apache creates the /php/twig subfolder (owned by www-data:www-data) and the website has all the needed files to works properly.

Problem: restoring the website with "drush archive-restore" remove the o+w permission on /php and subfolders then apache is not able anymore to update the /php/twig subfolder.

**Comment by weitzman** [comment]
archive-restore only sets up a codebase. you must then set permissions as needed.

**Comment by adraoo** [comment]
The documentation says:
> archive-dump: Backup your code, files, and database into a single file.
> archive-restore: Expand a site archive into a Drupal web site.

The archive-restore command should not change the permission of any folder, but it does. My configuration is xubuntu 12.04 and drush installed via composer, running on virtualbox. I checked the permissions in the archive and they are correct so it is the archive-restore command who changes them.

As apache is not able anymore to update the /php/twig subfolder the result is a "Fatal error", either immediately or after the first "drush cr" (Class TwigTemplate not found in /core/lib/Drupal/Core/Template/TwigEnvironment.php).
