### ISSUE TITLE
Make a new drush release so Drupal 8.0.0-beta9 can be installed

### ISSUE THREAD

**Issue by pwolanin** [drush-ops/drush#1288]
Due to https://www.drupal.org/node/2347625#comment-9685871

and other changes, the most recent drush release off master fails with the latest Drupal 8.

Please make a new release.

**Comment by weitzman** [comment]
Now done, per http://www.mosheweitzman.me/post/113968700703/in-order-to-better-support-the-fearless-drupalist. See https://github.com/drush-ops/drush/releases/tag/7.0.0-rc1
