### ISSUE TITLE
Drush up errors with "pm-updatestatus failed" 

### ISSUE THREAD

**Issue by chadpeppers** [drush-ops/drush#1294]
drush up on any site that I try to run fails.  I tested it on another co-workers and his fails as well.

drush up
pm-updatestatus failed

I can run any other drush command like drush cc all or even run drush pm-updatestatus but it fails.  Added a debug statement in the code and get this:

````
array(3) {
    'DRUSH_COMMAND_INSUFFICIENT_BOOTSTRAP' =>
    array(1) {
      [0] =>
      string(156) "Command pm-updatestatus needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command."
    }
    'DRUSH_COMMAND_NOT_EXECUTABLE' =>
    array(1) {
      [0] =>
      string(58) "The drush command 'pm-updatestatus' could not be executed."
    }
    'DRUSH_DRUPAL_DB_ERROR' =>
    array(1) {
      [0] =>
      string(1802) "Drush was not able to start (bootstrap) the Drupal database.
Hint: This may occur when Drush is trying to:
 * bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working database setup by specifying the URI to use with the --uri parameter on the command line. See `drush topic docs-aliases` for details.
 * connect the database through a socket. The socket file may be wrong or the php-cli may have no access to it in a jailed shel"...
    }
  }
  'self' =>
  array(3) {
    'root' =>
    string(51) "/Users/cpeppers/Sites/drupal/directlinkadmin/htdocs"
    'uri' =>
    string(36) "http://directlinkadmin.localhost.com"
    'path-aliases' =>
    array(1) {
      '%root' =>
      string(51) "/Users/cpeppers/Sites/drupal/directlinkadmin/htdocs"
    }
  }
  'context' =>
  array(4) {
    'php' =>
    string(12) "/usr/bin/php"
    'backend' =>
    string(1) "2"
    'root' =>
    string(51) "/Users/cpeppers/Sites/drupal/directlinkadmin/htdocs"
    'uri' =>
    string(36) "http://directlinkadmin.localhost.com"
  }
  'site' =>
  string(4) "self"
}
`````

**Comment by jonhattan** [comment]
It is `pm-updatestatus` that fails or any command?. From your debug it seems drupal is not bootstrapping at all.

**Comment by chadpeppers** [comment]
Let me clarify more I do not feel I put enough info.  This is in the latest version 7 and works fine whenever I check out 6.6.  Basically I can do most anything using drush besides update.  I can use drush cc and I can even execute drush pm-updatestatus but for some reason when I run drush up it fails with the error stated.

**Comment by andrew-pardue** [comment]
Just wanted to chime in and say i'm having the same issue. I have Drush installed with composer and currently running Drush 7.0-dev. Any commands that subsequently call `pm-updatestatus` fail.
For example running:
`drush up drupal --debug`
will fail when it reaches `pm-updatestatus`
most of the other commands seem to run fine, including directly calling `pm-updatestatus`.
Details:

    OSX Yosemite - 10.10.2
    MAMP 2.2
    PHP 5.5.3
    Database driver                 :  mysql
    Database hostname               :  localhost
    Database port                   :
    Database username               :  root
    Database name                   :  mysitedb
    Database                        :  Connected
    Drupal bootstrap                :  Successful
    Drupal user                     :
    Default theme                   :  my-drupal-site
    Administration theme            :  seven
    PHP configuration               :  /Applications/MAMP/bin/php/php5.5.3/conf/php.ini
    PHP OS                          :  Darwin
    Drush version                   :  7.0-dev
    Drush temp directory            :  /tmp
    Drush configuration             :
    Drush alias files               :
    Drupal root                     :  /Users/username/Documents/Webapps/my-drupal-site
    Site path                       :  sites/default
    File directory path             :  sites/default/files
    Private file directory path     :  /tmp
    Temporary file directory path   :  /tmp

**Comment by weitzman** [comment]
The log in the OP suggests an error in the function drush_valid_db_credentials() during the redispatch to pm-updatestatus. Perhaps one of you can debug that function and find exactly why Drush thinks it cant connect to your DB.

**Comment by stephenplatz** [comment]
I just started having the same issue as andrew-pardue, what's strange is that it happened suddenly, I was able to use pm-update without issues, then it started throwing the pm-updatestatus failure error. The result of `drush up -vd --no-core --security-only`

```
Starting Drush preflight. [0.01 sec, 2.28 MB]                                                                                                                                   [preflight]
Cache HIT cid: 7.0-dev-commandfiles-0-f369f27f0dcbfc6811d2d6233c9a9226 [0.02 sec, 2.35 MB]                                                                                          [debug]
Bootstrap to phase 0. [0.13 sec, 7.55 MB]                                                                                                                                       [bootstrap]
Bootstrap to phase 6. [0.13 sec, 7.55 MB]                                                                                                                                       [bootstrap]
Drush bootstrap phase : _drush_bootstrap_drupal_root() [0.13 sec, 7.56 MB]                                                                                                      [bootstrap]
Initialized Drupal 7.20 root directory at /Users/steve/Sites/tostan.local [0.14 sec, 7.97 MB]                                                                                      [notice]
Cache HIT cid: 7.0-dev-commandfiles-1-b4b4d2dff979e18de464aa0088542400 [0.14 sec, 5.53 MB]                                                                                          [debug]
Drush bootstrap phase : _drush_bootstrap_drupal_site() [0.14 sec, 5.54 MB]                                                                                                      [bootstrap]
Initialized Drupal site default at sites/default [0.14 sec, 5.54 MB]                                                                                                               [notice]
Cache HIT cid: 7.0-dev-commandfiles-2-9518eda12b48158193bd617384d95a7d [0.15 sec, 5.54 MB]                                                                                          [debug]
Drush bootstrap phase : _drush_bootstrap_drupal_configuration() [0.15 sec, 5.54 MB]                                                                                             [bootstrap]
sql-query: SELECT 1; [0.15 sec, 5.68 MB]                                                                                                                                        [status]
Executing: mysql --defaults-extra-file=/private/tmp/drush_jnQGCB --database=tostan --host=localhost --silent  < /private/tmp/drush_RpSdfj
  1
Drush bootstrap phase : _drush_bootstrap_drupal_database() [0.17 sec, 5.68 MB]                                                                                                  [bootstrap]
Successfully connected to the Drupal database. [0.17 sec, 6.25 MB]                                                                                                              [bootstrap]
Drush bootstrap phase : _drush_bootstrap_drupal_full() [0.17 sec, 6.25 MB]                                                                                                      [bootstrap]
Cache HIT cid: 7.0-dev-install_profile-66ecfeb9791a023150773849f1550c5d [0.35 sec, 38.18 MB]                                                                                        [debug]
Cache HIT cid: 7.0-dev-install_profile-66ecfeb9791a023150773849f1550c5d [0.35 sec, 38.18 MB]                                                                                        [debug]
Cache HIT cid: 7.0-dev-commandfiles-5-a5623f8133444e2bf229aa7563c182b7 [0.35 sec, 38.21 MB]                                                                                         [debug]
Drush bootstrap phase : _drush_bootstrap_drupal_login() [0.36 sec, 38.89 MB]                                                                                                    [bootstrap]
Found command: pm-update (commandfile=pm) [0.36 sec, 38.91 MB]                                                                                                                  [bootstrap]
Calling hook drush_pm_update [0.49 sec, 41.87 MB]                                                                                                                                   [debug]
Loading release_info engine. [0.49 sec, 41.92 MB]                                                                                                                                  [notice]
Loading version_control engine. [0.49 sec, 41.96 MB]                                                                                                                               [notice]
Loading package_handler engine. [0.5 sec, 41.98 MB]                                                                                                                                [notice]
Executing: wget --version
Executing: curl --version
Loading update_status engine. [0.51 sec, 42.01 MB]                                                                                                                                 [notice]
Including /Users/steve/.composer/vendor/drush/drush/commands/pm/updatecode.pm.inc [0.51 sec, 42.09 MB]                                                                          [bootstrap]
Calling hook drush_pm_updatecode_validate [0.51 sec, 42.2 MB]                                                                                                                       [debug]
Returned from hook drush_pm_updatecode_validate [0.51 sec, 42.2 MB]                                                                                                                 [debug]
Calling hook drush_pm_updatecode [0.51 sec, 42.22 MB]                                                                                                                               [debug]
Cache MISS cid: 7.0-dev-alias-path--bfdd02173f788b641b3b281330181827 [0.52 sec, 42.24 MB]                                                                                           [debug]
Undefined index: drush-script backend.inc:761 [0.52 sec, 42.25 MB]                                                                                                                 [notice]
Backend invoke: /usr/local/php5/bin/php /Users/steve/.composer/vendor/drush/drush/drush.php --php=/usr/local/php5/bin/php  --backend=2 --verbose --debug                          [command]
--root=/Users/steve/Sites/tostan.local --uri=http://default  pm-updatestatus   --security-only 2>&1 [0.52 sec, 42.25 MB]
/usr/local/php5/bin/php /Users/steve/.composer/vendor/drush/drush/drush.php --php=/usr/local/php5/bin/php  --backend=2 --verbose --debug --root=/Users/steve/Sites/tostan.local    [notice]
--uri=http://default  pm-updatestatus   --security-only 2>&1 [0.52 sec, 42.26 MB]
pm-updatestatus failed. [0.85 sec, 42.29 MB]                                                                                                                                    [error]
Returned from hook drush_pm_updatecode [0.85 sec, 42.26 MB]                                                                                                                         [debug]
Changes made in drush_pm_updatecode have been rolled back. [0.85 sec, 42.26 MB]                                                                                                  [rollback]
Command dispatch complete [0.85 sec, 42.22 MB]                                                                                                                                     [notice]
Returned from hook drush_pm_update [0.85 sec, 42.17 MB]                                                                                                                             [debug]
Command dispatch complete [0.85 sec, 42.13 MB]                                                                                                                                     [notice]
 Timer  Cum (sec)  Count  Avg (msec) 
 page   0.702      1      701.52
```

I suspect that something has been cached that is messing things up.

**Comment by fmann** [comment]
I experienced this issue today too. Restarting MySQL made the problem disappear.

**Comment by atwixtor** [comment]
I'm still having this problem after restarting MySQL and clearing all caches. I can run it all by itself and it works, but if I run drush up <project> it fails.

**Comment by sukk1e** [comment]
Not sure if you guys have the same problem as me. I was using drupal 7 with drush 7 dev and the reason why it failed was due to release information and the fix that worked for me was this commit.
https://github.com/arnested/drush/commit/dce7283dd12f2548441535d3c06499111cc9a41a

**Comment by chadpeppers** [comment]
I agree with sukk1e the issue I was having is because I was using the drush 7 version.  If you are using drupal 7 download the drush 6.x version

**Comment by atwixtor** [comment]
@sukk1e I checked that file for the commit you say resolved the issue, and I have that commit in my drush 7 dev build, and still encountering problems.

**Comment by sukk1e** [comment]
@atwixtor 
hmm, and the drush pm-updatestatus doesn't provide any information? When I did that I gotten errors like
Call to a member function getInfo() on a non-object in /usr/share/drush/lib/Drush/UpdateService/StatusInfoDrush.php

**Comment by atwixtor** [comment]
Great, now that it's been a few days since I had those problems, I can no longer recreate them. drush pm-updatestatus never gave me trouble, it was running drush up that did. Now everything including drush up seems to be working OK. Really not sure what fixed it though, I didn't change anything.

**Comment by 4aficiona2** [comment]
Restarting MySQL DB worked out for me. Thanks for the advice @fmann !

**Comment by dwisusanto** [comment]
Restarting MySQL worked. Thanks for the advice @fmann !

**Comment by atwixtor** [comment]
This is still happening on drush 8.1-dev... Restarting MySQL did not help this time around (shutting down the MAMP servers, quitting MAMP, then re-opening and starting the Apache and MySQL servers again). Restarting the computer did not help either.

**Comment by AndyRead** [comment]
I've been using drush 8.0-dev plenty recently including 'drush up' with no problems.  Then today suddenly I started to get the 'pm-updatestatus failed' message, even though I could run 'drush pm-updatestatus' on its own without any problem.
After restarting mysql as suggested here it's sorted itself out and 'drush up' works fine.

**Comment by alexrayu** [comment]
Upgraded to the latest version yesterday. `drush up -y` does not work any more.

**Comment by cjwills** [comment]
I eventually figured out why this is happening in my case.  `drush up` is running `drush pm-updatestatus` as a subcommand, and on my system this would try to execute drush.phar directly which would use the default php which doesn't work.

By putting a ~/bin/php that points to php-5.6 in the PATH before the default system php I was able to make this work (dreamhost server)

**Comment by jenlampton** [comment]
A client of mine was having the same issue with Drush 8.0.1 and Drupal 7. Restarting mysql did not help, but adding an alias for drush, and an export for DRUSH_PHP to the .bash_profile did the trick.

**Comment by kaicyee** [comment]
I'm having the same issue but I'm using Acquia Devdesktop for the PC. I wonder if @cjwills can clarify as to where to put this update code?

**Comment by cjwills** [comment]
I have zero knowledge of Devdesktop, but you need to make sure that the 'php' command runs the correct version of php.

**Comment by kaicyee** [comment]
Well, help a brother out. Where should this edit be made: "...By putting a ~/bin/php that points to php-5.6 in the PATH before the default system php I was able to make this work"? On the Drush program or on the server?

**Comment by gh640** [comment]
Restarting MySQL worked for me, too. @fmann , thank you.

**Comment by vrwired** [comment]
my issue turned out to be something with drush aliases file, removing allowed to update. Will need check how my aliases added a 2nd db which @weitzman mentioned as potential issue.

**Comment by DocDJ** [comment]
Having the same problem:
navigate root of Drupal folders in public_html 
 (drush pm-update fails with "pm-updatestatus failed"). 
Restarting MySQL did not help.
Drupal 7.51, drush 8.1.2 on Windows 10 Pro. PHP 7.0.7, MySQL 5.6

**Comment by sschuchlenz** [comment]
I had the same problem and on my side, it was the fact that on the particular server, `phpbrew` is in use to manage php versions. I switched to `php-5.6.23` temporarily and updating works flawlessly (drupal 7 with drush 8).

YMMV though ;)

**Comment by shirazd** [comment]
This was happening for me on the latest stable Drush as of writing (8.1.10). I needed to restart my mysql.

**Comment by michalsen** [comment]
D7 w/ drush 8.1.15 on Acquia devdesktop
restarting Apache/MySQL fixed issue

**Comment by scottybrookie** [comment]
I had the same problem and the fix was embarrassingly simple:  I had a directory at the Drupal root level that didn't belong there.  I removed it and the "pm-updatestatus failed" error went away.

**Comment by JPustkuchen** [comment]
For me the reason was a PHP issue with a module (entityreference_prepopulate 7.x-1.7). Updating to the latest dev fixed it. I don't know why the error wasn't even shown with -d or -vvv
