### ISSUE TITLE
Drush latest (HEAD) doesn't work properly on MAMP

### ISSUE THREAD

**Issue by daften** [drush-ops/drush#1301]
The only thing that fixes it is making a symlink from /tmp/mysql.sock to the actual socket. This is with drush installed through brew. I've only noticed after updating to the latest MAMP version. My PATH is setup correctly for MAMP.

This is most likely not a drush issue, but I can't find an answer anywhere and am hoping additional direction can be given here. This is also for reference for other people who have the same problem.

**Comment by C13L0** [comment]
This is an issue with the new MAMP update. I was able to resolve this by going to Applications ▸ MAMP ▸ bin ▸ php ▸ php5.6.6 ▸ conf ▸ php.ini and adding the following:
pdo_mysql.default_socket = /Applications/MAMP/tmp/mysql/mysql.sock

Make sure and restart the server. Credit goes to Blackice2999 https://www.drupal.org/node/726970#comment-9774567

Here is a screenshot of before/after
![bash2015-03-30](https://cloud.githubusercontent.com/assets/3138019/6904248/7d484fae-d6ed-11e4-949a-22f199c3a50a.png)

**Comment by damienmckenna** [comment]
The details provided by C13L0 will resolve the problem - it's not Drush's fault, it's MAMP. Again.

**Comment by daften** [comment]
Thanks very much for the updates! I hate the overwrites of the settings files, for pHP at least the option to take a backup is there, but apparently not for MySQL.
As usual for people that helped me, they get the promise of free beers (but decent ones) :)

Again thanks!

**Comment by daften** [comment]
It was fixed in MAMP 3.2.x
