### ISSUE TITLE
Drush updb command not working with Drush dev and 7.0.0-rc1, Drupal dev and Beta 9

### ISSUE THREAD

**Issue by jeqq** [drush-ops/drush#1302]
I'm trying to run updates with `drush  updb` and it fails with this error:

<pre>PHP Fatal error:  Call to undefined function batch_get() in /home/andrei/.composer/vendor/drush/drush/commands/core/drupal/batch.inc on line 82
PHP Stack trace:
PHP   1. {main}() /home/andrei/.composer/vendor/drush/drush/drush.php:0
PHP   2. drush_main() /home/andrei/.composer/vendor/drush/drush/drush.php:11
PHP   3. Drush\Boot\BaseBoot->bootstrap_and_dispatch() /home/andrei/.composer/vendor/drush/drush/drush.php:70
PHP   4. drush_dispatch() /home/andrei/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php:62
PHP   5. call_user_func_array:{/home/andrei/.composer/vendor/drush/drush/includes/command.inc:187}() /home/andrei/.composer/vendor/drush/drush/includes/command.inc:187
PHP   6. drush_command() /home/andrei/.composer/vendor/drush/drush/includes/command.inc:187
PHP   7. _drush_invoke_hooks() /home/andrei/.composer/vendor/drush/drush/includes/command.inc:219
PHP   8. call_user_func_array:{/home/andrei/.composer/vendor/drush/drush/includes/command.inc:368}() /home/andrei/.composer/vendor/drush/drush/includes/command.inc:368
PHP   9. drush_core_updatedb_batch_process() /home/andrei/.composer/vendor/drush/drush/includes/command.inc:368
PHP  10. _update_batch_command() /home/andrei/.composer/vendor/drush/drush/commands/core/core.drush.inc:1177
PHP  11. drush_batch_command() /home/andrei/.composer/vendor/drush/drush/commands/core/drupal/update.inc:148
PHP  12. _drush_batch_command() /home/andrei/.composer/vendor/drush/drush/includes/batch.inc:90
Drush command terminated abnormally due to an unrecoverable error.                         [error]
Error: Call to undefined function batch_get() in
/home/andrei/.composer/vendor/drush/drush/commands/core/drupal/batch.inc, line 82
The external command could not be executed due to an application error.</pre>

Tested with Drush 7 dev and 7.0.0-rc1, Drupal 8 dev and Beta 9.

**Comment by weitzman** [comment]
Do you have pending updates? Which module?

**Comment by jeqq** [comment]
I test with <a href="https://www.drupal.org/project/multiversion">Multiversion</a> module.

**Comment by weitzman** [comment]
@helmo  - this is surely caused by the recent updb bootstrap level change. Are you available to debug this?

**Comment by helmo** [comment]
I'll look into this tomorrow.

ref: #1223 or #961

**Comment by weitzman** [comment]
Thanks @helmo. I'll add that it is possible that update.php is broken in Drupal 8 itself. Would be good to test with Drupal UI to verify that only Drush is broken. See https://www.drupal.org/node/2447573

**Comment by Berdir** [comment]
Pretty sure that the UI works, I've used that after seeing that drush was broken.

batch_get() still exists, in form.inc, since 2007 apparently, so I think this is caused by drush change, not a core change. The most recent commit that git log -S with batch_get or form.inc finds is 7 month old.

**Comment by jeqq** [comment]
Drupal UI works, I'm using it while Drush is broken :)

**Comment by helmo** [comment]
Weird, on a clean D8-dev install I get 6 pending db updates .... 
But that does let me confirm the 'undefined function batch_get()' error.

Extra weird that we have all this batch API code in a file called form.inc ... but anyway.

Changing back the bootstraplevel to DRUSH_BOOTSTRAP_DRUPAL_FULL resolves this case.
However then #1223 fails again :(

Changing it to the bootstrap level in between (DRUSH_BOOTSTRAP_DRUPAL_DATABASE) still gives an error, about missing functions.

It is solved by bootstrapping to _FULL inside the _update_batch_command() function, which is in commands/core/drupal/update.inc.

**Comment by helmo** [comment]
Please review my PR in #1306
