### ISSUE TITLE
Drush with remote alias with a prefix COLUMNS=### breaks remote execution

### ISSUE THREAD

**Issue by jurgenhaas** [drush-ops/drush#1305]
I'm using the latest dev release of drush 7 and when I'm calling ```drush @pweb.default status -v``` there is the following output:

```
Loaded alias @pweb.default from file /etc/drush/pweb.aliases.drushrc.php
Begin redispatch via drush_invoke_process(). 
Calling proc_open(ssh -o PasswordAuthentication=no pweb 'COLUMNS=163 drush  --verbose --uri=www.paragon-es.de --root=/var/www/live/htdocs  core-status 2>&1' 2>&1);
```

The command being executed is ```COLUMNS=163 drush ...```which doesn't seem to make sense, does it?

**Comment by greg-1-anderson** [comment]
What shell are you running on the remote end?  Drush currently expects, and only really supports bash.

With bash:
```
$ FOO=bar bash -c 'echo $FOO'
bar
```
This also works, though:
```
$ env FOO=bar bash -c 'echo $FOO'
bar
```
It's not that we **can't** support anything other than bash, it's just a little difficult to get enough test coverage for a lot of different shells.  If you can suggest something that works in your environment, and is does not cause problems for the supported shell, then we can switch to a more compatible construct.

**Comment by greg-1-anderson** [comment]
If you explicitly set your COLUMNS environment variable to 80 (the default), then Drush will not pass COLUMNS to remote commands.  Setting COLUMNS in '#env-vars' in your site alias does not work, though.

**Comment by jurgenhaas** [comment]
Thanks @greg-1-anderson I can confirm that a locally set COLUMN = 80 solves the problem, but as I'm using the fish shell instead of bash, that ain't gonna work because fisi is automatically setting this variable when ever you open a terminal or resize it later on.

I'm wondering if that got introduces recently. It seemed to have been working before but I haven't looked deeper into the commits yet.

Wouldn't it be better to pass the columns as an option to drush rather than setting an environment variable remotely?

**Comment by greg-1-anderson** [comment]
We don't pass COLUMNS as an option because we evaluate the terminal width in the `drush` bash script, that the drush script does not parse options.  (We evalute terminal width in the drush script because it is done differently in drush.bat.)

I think it's been doing this (passing COLUMNS in backend invoke) for a really long time, but I did not check which commit it was introduced in.

Does `env COLUMNS=...` work for you in fish?

**Comment by jurgenhaas** [comment]
Ah, got it. Thanks. Yes, ```env COLUMNS=...``` does work in the fish environment.

So, I've changed line 483 in drush/includes/environment.inc to this:

```
$prefix .= ' env ' . drush_escapeshellarg($key, $os) . '=' . drush_escapeshellarg($value, $os);
```

and that is fixing the problem.

**Comment by greg-1-anderson** [comment]
Not sure that change is appropriate for instances where there are multiple environment variables.  If you submit a working PR, then we can work on getting this change in.

**Comment by greg-1-anderson** [comment]
Also, I will add that I am working under the assumption that 'env' is always going to be in everyone's $PATH.  If that's not the case, then this change might be an issue for some.

**Comment by jurgenhaas** [comment]
'env' seems to be supporting both, adding multiple key/value pairs for one command or chaining 'env' processes. However, not chaining seems the better approach, so I'm going to use that in the PR.

Regarding your concern about 'env' being in the $PATH or not, the same concern should then apply to the 'which' and 'tput' commands, that are also used in the script.
