### ISSUE TITLE
Message is not correct when enabling a module with downloadable depencies

### ISSUE THREAD

**Issue by youri2015** [drush-ops/drush#1312]
When I install a module i get the following messages:
1. better_watchdog_ui was not found.                                                  [warning]
2. The following projects provide some or all of the extensions not found:                          [ok]
3. better_watchdog_ui
4 Would you like to download them? (y/n): y
5 Project better_watchdog_ui (7.x-2.0) downloaded to  D:\wamp\www\whaymeat/sites/all/modules/better_watchdog_ui.                           [success]
6 Project better_watchdog_ui contains 3 modules: better_watchdog_ui_rules, better_watchdog_ui_entity, better_watchdog_ui.
7 The following extensions will be enabled: better_watchdog_ui, better_watchdog_ui_entity
8 Do you really want to continue? (y/n): y
9 better_watchdog_ui was enabled successfully.                                 [ok]
10 better_watchdog_ui_entity was enabled successfully.                     [ok]

In step  8  drush is asking would you to like to enabled all 3 modules. My answer is yes but only module is actually enabled. I think the correct message should: the following extensions will be available en downloaded. module1, module2. Do you want to enable the module1.

**Comment by greg-1-anderson** [comment]
The `pm-*` commands are maintenance only; closing. For a discussion on continuing maintenance of pm, see https://github.com/drush-ops/drush/issues/1581#issuecomment-405138494
