### ISSUE TITLE
drush core-requirements does not output descriptions in render arrays

### ISSUE THREAD

**Issue by pfrenssen** [drush-ops/drush#1314]
In [issue #2296929: Clean up system_install() SafeMarkup::set() use](https://www.drupal.org/node/2296929#comment-9764547) it was discovered by [herved](https://www.drupal.org/u/herved) that `drush rq` does not output descriptions that are rendered with render arrays correctly. Instead it shows `Array`.

This is because the `concatenate-columns` option is used to format the table. This treats the input data as strings and simply concatenates them.

The table formatter actually expects all input data to be raw strings. To make it possible to use arrays and objects in the input data we could provide a callback function that preprocesses the data of particular columns before trying to format it. This would solve it in a generic way.

**Comment by AdamPS** [comment]
Thanks @weitzman I think this is now fixed and ready to close.
