### ISSUE TITLE
sql-sanitize --sanitize-password is no-op

### ISSUE THREAD

**Issue by drzraf** [drush-ops/drush#1318]
Using drush 7 master,
And php 5.6.6-2
```
I run drush @td6  sql-sanitize --sanitize-email --sanitize-password
```
on a Drupal 6 database.

The command returns 0 but no password is actually reset.

There are multiple bugs here:

1)
This is the main issue:
```php
drush_get_option(array('sanitize-password', 'destination-sanitize-password'), 'password');
```
returns true.
But I didn't pass value to the --password argument, I thus expected to reset passwords to "password", and not to (boolean)True. Either it's a bug in drush_get_option() either in sql_drush_sql_sync_sanitize()
But digging a bit further, it's probably an issue in drush_context_names() (since this initialize the array used later to fetch argument's value (or absent value) from.

2) This True value given to $newpassword, is then used in the test copied below:
```php
if ($newpassword != 'no' && $newpassword !== 0)
```
what evaluates to
```php
if(true != 'no' && true !== 0) 
```
what evaluates to
```php
false && true
```
(since in the PHP world true is not (so) different from 'no')
At least this PHP bug^Wbehavior avoided reseting passwords with "true" (but was it expected?)

3) the script should not return 0 when it didn't actually succeeded happens (if no sanitization happened we can expect that a failure happened somewhere)

**Comment by weitzman** [comment]
I think the core problem here is that --sanitize-password was never intended to be used without a value since you can just omit the option to get 'password'. I have marked is and --sanitize-email as required so now you can't use them without a value.
