### ISSUE TITLE
drush pm-update but leave an index file

### ISSUE THREAD

**Issue by drubage** [drush-ops/drush#1320]
We have set up some useful scripts that use drush and other command line functions to update several drupal sites on the same server using a single management site. When we drush pm-update drush will make a backup of the entire root directory of the site while it is working. It leaves behind the folder where it downloads Drupal and the sites folder. On our server this results in the directories and files being visible as there is no index file during this time (this is something we can fix but many servers might be configured this way). Also, because the owner of the files from drush updates is always root we need to chown the files/folders to the right account after drush is done. On a big update, however, this can take several minutes and during that time the site will be in 500 error mode (as the .htaccess file has the wrong ownership). We have overcome this issue with a custom 500 error page that shows a "This website is currently undergoing maintenance. It should back up within a few minutes. Thank you for your patience!" message so this is not as big of a deal.

What we'd like to be able to do is copy an index.html file in the site root and then run drush updates but have it leave the index.html file in the root so that we can display that same useful error message to our users "This website is currently undergoing maintenance. It should back up within a few minutes. Thank you for your patience!". After the drush updates are done we remove that file.

Is this possible? Like can we tell drush not to backup that index.html file when it updates Drupal? Or are we not doing the drush updates properly? Seems like they will always break a website while they are running.

Thanks!

-Drew

**Comment by greg-1-anderson** [comment]
We neither recommend nor support running pm-update / pm-updatecode on a live site.  You should update a dev or staging site, test thoroughly, and then use some other mechanism (e.g. rsync or git pull) to get your files on the live site.  Once the files are in place, run updatedb.  Of course, you will need some solution to keep your site from showing errors during this process, but you are completely in control of this, so it shouldn't be an issue.

**Comment by drubage** [comment]
Wow okay. How does Acquia update the many sites across its system? They don't do any 'testing' that the updates worked on a dev site that would be up to the client but they are constantly keeping all the contributed modules updated?

So bottom line when pm-update runs it's going to zip up and backup the entire root directory there's no way to have it exclude one index.html file, sound right?

**Comment by greg-1-anderson** [comment]
Right, we do not support what you are requesting.  There is another open request to run pm-updatecode without moving files out of the way, which might by coincidence work for your use case; however, that does not change the fact that your use case is not supported.  I also regret to say that no one has had time to work on said pm-update improvement in the years that the request has been open.

I can't speak for what Aquia does, but at Pantheon, it is possible to update your dev site, after which you can push your code up from dev to test and live.  I'm sure that Aquia does do testing before they deploy code to clients, and I am sure that they do not use drush pm-updatecode to deploy, either.

**Comment by drubage** [comment]
I find it hard to believe a company would offer automatic updates that you would need to manually perform. Too bad nobody has worked on this most important feature of drush that we totally love!

**Comment by drubage** [comment]
Also updating your dev site and then pushing to live would mean you could lose valuable content posted in the interim like comments and webform results. You could shut down the sites for the update period but that could be many minutes of downtime and on high traffic revenue generating site this could be significant.

**Comment by greg-1-anderson** [comment]
When you push from dev to live, you only push code, not the database.  After you push the code, then run updatedb on the database for the live site.  You only need to take the site down during the update db, which is a much smaller window than you get running pm-updatecode on your live site.

Remember, sometimes an update can break your site.  You can't downgrade after you run updatedb; you have to restore from backup.  You really don't want to be running this sort of experiment on your live site until you have tested thoroughly on a dev site.  This really is how folks to Drupal deployments.

**Comment by drubage** [comment]
Ok gotcha I see what you mean. I agree it would be ideal to update a dev site and then a live site but if you are managing hundreds of sites some with small budgets it is more difficult to do it that way.

**Comment by greg-1-anderson** [comment]
If your hundreds of sites are all running the same code, and their configuration is similar enough, perhaps you could test updates on one site and then deploy the code across multiple live sites.  You'd have to be very confident of your testing, as this is not super-safe -- but it is more safe than running pm-updatecode on the live sites directly.

Managing hundreds of dissimilar sites is, in fact, difficult to do on a small budget.

**Comment by drubage** [comment]
They are on some similar code and some not similar code, it's all kinds of projects. We have built a pretty awesome tool that updates and checks these websites and it works great except for during the pm-update part when the sites go down for a few minutes. Thanks for all your feedback I understand what you are saying, too bad that Drupal is so hard to update. Obviously Wordpress is much easier with push-button updates that rarely break sites (although Wordpress brings its own set of problems also).

**Comment by drubage** [comment]
Sorry one more question of clarification. On this point...

at Pantheon, it is possible to update your dev site, after which you can push your code up from dev to test and live.

Are you saying at Pantheon customers are required to update their Drupal modules themselves you guys don't manage that for customers?

**Comment by greg-1-anderson** [comment]
Yep.  Customers are responsible for testing the upgrade path for the contrib modules they select for their sites.  Pantheon tests Drupal core upgrades before making them available to customers, but neither Pantheon nor drupal.org guarantees that a core security update will work with all available contrib modules -- although it's rare for there to ever be a problem with core updates.  Contrib updates... depends on the quality of the contrib module.

https://pantheon.io/docs/articles/local/drush-command-line-utility/

https://pantheon.io/docs/articles/drupal/updating-modules-through-drupal/

**Comment by greg-1-anderson** [comment]
Note also that often, the direct customer for Pantheon is a web shop, whereas the owner of the website is a customer of the web shop.  Companies with important websites usually pay someone to make sure that it stays working and updated.
