### ISSUE TITLE
Drush was not able to start (bootstrap) the Drupal database.

### ISSUE THREAD

**Issue by AndyD328** [drush-ops/drush#1325]
Thank you for Drush and for all your work on it, you 'make life better'!
----
If I have an alias file that 'includes' settings.php then database connections fail. 
If I remove the alias file completely ( or the include from the alias file ) then database operations work as expected.
File operations are unaffected either way.

This worked with the include until very recently - and using the include was used to save duplicating the database connection information. 

I have tried reverting to an older commit of Drush 7 ( the oldest I have tried is 27cbe36061a9e3ac0b2bbb5ce94f33c06c4db313 as I'm pretty sure it was working at that point ).

As reverting hasn't worked it seems the problem might not be drush at all but php related. Can you give me any pointers to where to look and how to debug this. Or a better way of not duplicating connection information in multiple files?

Thank you in advance.

**Comment by weitzman** [comment]
You rarely need to put db info in an alias. Drush will look up your connection info as needed. Thats usually more secure as well.

**Comment by AndyD328** [comment]
Wow. So you don't, problem solved, code simplified, security increased! Thanks heaps Moshe

**Comment by dwaghmare** [comment]
in your settings.php 
put
``
'host' => php_sapi_name() == 'cli' ? '127.0.0.1' : 'localhost',
``
instead of
``
'host' => 'localhost',
``
That should solve your issue :+1:
