### ISSUE TITLE
'drush ard' follows symlinks

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#1329]
I have a symlink in the root of my drupal site which points back to the root folder itself. This is for use with multisite, so I get http://site.local/ and http://site.local/subfolder as two different sites on the codebase.

Drush ard follows this, and creates an GIANT archive -- a fairly modest site created a 9GB archive, and was probably interrupted in some way as the tarball won't unarchive.

Listing its contents shows this sort of thing:

-rw-r--r--  0 joachim staff    1777 18 Mar 19:20 joachim-accounts/dev/dev/dev/dev/dev/dev/dev/dev/dev/dev/dev/dev/dev/dev/dev/dev/dev/dev/dev/dev/modules/field/modules/text/text.js

**Comment by pmatias** [comment]
Hi @joachim-n!
Can you show us the complete drush command you are trying to execute?
Also, Can you post your current dir structure? (starting from the root folder itself)

And also, if you haven't seen this yet, http://drushcommands.com/drush-6x/archive/archive-dump has a lot of information that may be handy ;)

**Comment by joachim-n** [comment]
It was just 'drush ard' with presumably an output file given -- sorry it was a while ago, so I don't remember.

The directory structure is that I have symlinks from the Drupal root back to itself. In other words, they are the product of doing this while standing in the Drupal root:

  ln -s . subsite

**Comment by weitzman** [comment]
Lets consolidate at #221
