### ISSUE TITLE
drush update problem - drush upc results in memory exhaustion 

### ISSUE THREAD

**Issue by karl07** [drush-ops/drush#1330]
ran into a problem today when updating a d7-site. "drush upc" just didn't do the job. finally just used "drush up" which managed to update core and contrib modules. the output of --debug still contained the messages that seemed to prevent "drush upc" from finishing it's job, or - to be precise - that seemed to make drush restore the old version of d7 and contribs. here the respective part of --debug output (sorry if my words are not precise, i am not really a tec-guy).

Successfully logged into Drupal as Gast (uid=0) [25.46 sec, 33.83 MB][bootstrap]
Found command: cache-clear (commandfile=cache) [25.46 sec, 33.83 MB] [bootstrap]
Calling hook drush_cache_command_clear [26.65 sec, 34.63 MB]             [debug]
Calling drush_cache_clear_both() [26.65 sec, 34.67 MB]                   [debug]
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /Library/WebServer/Documents/eugr/eugr150408/sites/all/modules/views/views.module on line 415

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /Library/WebServer/Documents/eugr/eugr150408/sites/all/modules/views/views.module on line 415
The external command could not be executed due to an application     [error]
error. [31.33 sec, 38.89 MB]
Illegal string offset 'site' backend.inc:1012 [31.33 sec, 40.28 MB]  [warning]
The command could not be executed successfully (returned: Bootstrap  [error]
to phase 0. [0.01 sec, 1.88 MB]                           
[bootstrap]
Drush bootstrap phase : _drush_bootstrap_drush() [0.01 sec, 1.99 MB]
[bootstrap]
Loading drushrc "/Users/mediamarkt/.drush/drushrc.php" into         
[bootstrap]
"home.drush" scope. [0.01 sec, 2 MB]
Cache HIT cid: 6.3.0-commandfiles-0-1dc0937d996349649ecbbcaedffbff7a 
   [debug]
[0.03 sec, 2.01 MB]
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted
(tried to allocate 72 bytes) in
/Library/WebServer/Documents/eugr/eugr150408/sites/all/modules/views/views.module
on line 415

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried
to allocate 72 bytes) in
/Library/WebServer/Documents/eugr/eugr150408/sites/all/modules/views/views.module
on line 415
, code: 255) [31.34 sec, 38.9 MB]
Finished performing updates. [31.34 sec, 41.1 MB]                    [ok]
Returned from hook drush_core_updatedb [31.34 sec, 41.1 MB]              [debug]
Command dispatch complete [31.34 sec, 41.06 MB]                         [notice]
 Timer  Cum (sec)  Count  Avg (msec) 
 page   11.034     1      11034.41
Peak memory usage was 43.39 MB [31.34 sec, 41.06 MB]                    [memory]
Cache MISS cid: 6.3.0-alias-path--6d5f13e5abea974f344f6342460ceabd       [debug]
[31.34 sec, 41.06 MB]
Returned from hook drush_pm_post_pm_update [31.41 sec, 38.88 MB]         [debug]
Command dispatch complete [31.41 sec, 38.82 MB]                         [notice]
 Timer  Cum (sec)  Count  Avg (msec) 
 page   31.247     1      31246.73
Peak memory usage was 42.22 MB [31.41 sec, 38.82 MB]                    [memory]

**Comment by weitzman** [comment]
Not a drush bug.

**Comment by karl07** [comment]
thought it could be useful to let you know. 
good to see how fast you looked at it. thx for your work, moshe.
