### ISSUE TITLE
Provide post update hook

### ISSUE THREAD

**Issue by yamlfd** [drush-ops/drush#1338]
For robots.txt module I need the ability to delete the root robots.txt file after every Core updade. I'm looking for a hook that is called by drush post core update where I can run some code like a file delete.

Any idea how this could be archived? It suxxx so much that I need to manually delete the file after every update.

**Comment by jonhattan** [comment]
There's a hook, called after each project update.
http://api.drush.org/api/drush/drush.api.php/function/hook_pm_post_update/master

**Comment by yamlfd** [comment]
Does this hook fire after a core update if the module has not bern updated?
