### ISSUE TITLE
drush site-install breaks if minimal.profile is not present

### ISSUE THREAD

**Issue by marcvangend** [drush-ops/drush#1344]
There is a patch in the Drupal 8 issue queue which works fine from within Drupal, but breaks `drush site-install`: [Do not use SERVER_NAME as default value for the site name](https://www.drupal.org/node/2473709) (especially comment # 12 and below).

As far as I can see, this is a drush bug. Maybe it can be fixed in Drush before that patch goes into core (assuming that it will).

**Comment by greg-1-anderson** [comment]
Casual inspection of the code does not reveal the source of this dependency; I'll have to trace through it and see why Drush si is behaving differently than the GUI installation.  I don't see a dependency on the minimal installation profile in any .info.yml file in Core, so this is a bit of an oddity.

**Comment by marcvangend** [comment]
Thanks for looking into this Greg. I did some more tests to figure out exactly when this problem occurs. TL;DR: It seems to be caused by the `$settings['install_profile']` variable in settings.php.

Long version:

First, I tried to install Drupal with a completely clean codebase (except for the patch from https://www.drupal.org/node/2473709 of course), specifying the database credentials in the command:

    $ drush si standard --db-url=mysql://dbuser:password@localhost:3306/drupal8

That worked.
Second, I re-installed with the standard profile, using the db credentials from settings.php:

    $ drush si

No problems there.
Next, I re-installed with the minimal profile, again using the db credentials from settings.php:

    $ drush si minimal

Again no errors.
Finally, I tried to re-install with the standard profile, which failed:

    $ drush si 
      You are about to DROP all tables in your 'drupalcore' database. Do you want to continue? (y/n): y
      Starting Drupal installation. This takes a while. Consider using the --notify global option.            [ok]
      exception 'Drupal\Core\Installer\Exception\InstallerException' with message 'Required modules: Required [error]
      modules not found.
      
      The following modules are required but were not found. Move them into the appropriate modules
      subdirectory, such as <em>/modules</em>. Missing modules: <span class="admin-missing">Minimal</span>' in
      /home/marc/http/public/drupalcore/core/includes/install.core.inc:2268

In an attempt to figure out where this reference to Minimal was stored, I deleted all config files with `rm -rf sites/default/files/*`, dropped all tables in the database and tried again. The error still occurred. Then I deleted the following line from settings.php:

    $settings['install_profile'] = 'minimal';

After that line was removed, `drush si` worked perfectly again. It seems to me that drush at some point reads the $settings['install_profile'] from settings.php and tries to load minimal.profile.

**Comment by greg-1-anderson** [comment]
Yeah, that does make sense.  In my test site, I have never installed the 'minimal' profile, so my settings.php says `$settings['install_profile'] = 'standard';`.  So, this problem apparently is limited to re-installs after installing the 'minimal' profile.

**Comment by marcvangend** [comment]
Exactly. So I guess the real question is: Why does Drush try to load the .profile file of the previously used install profile? I would expect that that file is not necessary at all to perform the installation. The fact that is does work when you simply remove that line from settings.php, seems to confirm that.

**Comment by greg-1-anderson** [comment]
Drush does not care about or want `$settings['install_profile']` to be set at installation time.  This value is saved so that Drush can search for Drush commands only inside the active installation profile, ignoring the others.  If this value happens to exist, and is wrong at `drush si` time, then it causes problems.

The solution is to insure that this value is correct before firing off the install.

**Comment by greg-1-anderson** [comment]
It actually appears that it is Drupal that is writing this value into settings.php.  There's a comment about it in default.settings.php.

**Comment by greg-1-anderson** [comment]
I made a PR to correct this situation.  Please let me know if it works for you.

**Comment by marcvangend** [comment]
Yes, that solves the problem, thank you!

Interesting to see (as you wrote in https://www.drupal.org/node/2473709#comment-9849547) that this problem already existed, and is not caused by our patch. That thought didn't even cross my mind :-)
