### ISSUE TITLE
Add deprecation warnings for changes to drush aliases

### ISSUE THREAD

**Issue by minorOffense** [drush-ops/drush#1346]
Since you're deprecating "parent" adding some warning would be useful. Right now everything just keeps going as if nothing has changed but remote commands start failing.

Only if you read the example file do you get any indication that the API has changed.

**Comment by greg-1-anderson** [comment]
There is already a deprecation warning; however, it is only visible in --debug mode.  See #1279.

I presume that you intended to say "... remote commands will start failing," as presently, 'parent' is still supported in Drush.

The discussion on the future of site aliases et. al. is at #975.

**Comment by minorOffense** [comment]
Should we not include a visible warning in 6.x so people know before they upgrade to 7?

I'll bring that up in the linked issues. Thanks!

**Comment by greg-1-anderson** [comment]
'parent' is supported in 6 and 7, and will be removed in 8.
