### ISSUE TITLE
Wrong contrib project version made with yml make file while making D7 codebase

### ISSUE THREAD

**Issue by henrijs** [drush-ops/drush#1348]
In MYSITE.make.yml i have line(s) for views, version 3.10, views 3.1 gets downloaded.

Does not matter if I use

`  views: 3.10`

syntax or

`  views:`
`    version: 3.10`

syntax.

**Comment by jonhattan** [comment]
I think you want to use `version: '3.10'` to avoid the parser to get it as a number.

**Comment by jonhattan** [comment]
Duplicate of #1470
