### ISSUE TITLE
drush dl downloads to sites/all instead of site specific dir when doing helpful auto-dependency download

### ISSUE THREAD

**Issue by joakimf** [drush-ops/drush#135]
Drush Version   :  6.0 (ubuntu 12.04 server)
in a multisite environment (aegir)

When running:
  drush dl
files are downloaded into the current site
ex.
  path/to/sites/my.site/themes/adaptivetheme

But if you run:
  drush en
and if files do not exist, they will be downloaded to sites/all...
ex.
  path/to/sites/all/themes/adaptivetheme

**Comment by jonhattan** [comment]
So you're asking to autodownload missing dependencies to the same folder that the dependent project is placed? This may get tricky if you try to enable a module/theme located sites/all and another from the site dir and both has the same missing dependency.

If you want' to always use the site directory, you can leverage dl's `--use-site-dir` option. For it to take effect when autodownloading missing dependencies, put it in your alias or drushrc file.
