### ISSUE TITLE
drush pml does not see custom module

### ISSUE THREAD

**Issue by PVasili** [drush-ops/drush#1352]
The name of my theme: *my_name* and name of module: *my_name*.
After **drush pml** I do not see my module named *my_name* :(

**Comment by greg-1-anderson** [comment]
By Drupal naming conventions, it is illegal to have a module and a theme with the same name.

**Comment by andypost** [comment]
Yep, please file core issue about ability for hook collisions in themes and modules!
D8 still have separate storage for modules and themes

**Comment by jonhattan** [comment]
FYI running drush in --debug mode shows a message in this case.
