### ISSUE TITLE
'drush rln' crash with missing module's release notes

### ISSUE THREAD

**Issue by emanuk** [drush-ops/drush#1353]
Hello,

It seems that 'drush rln' can't deal when there is a problem with getting the release notes of a module.

Examples:

Drush version:  6.3-dev
<pre>
  $ drush rln environment_indicator-7.x-2.6
  PHP Fatal error:  Call to a member function asXML() on a non-object in /drush-6.x/commands/pm/release_info/updatexml.inc on line 211

  Fatal error: Call to a member function asXML() on a non-object in /drush-6.x/commands/pm/release_info/updatexml.inc on line 211
  Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                     [error]
  Error: Call to a member function asXML() on a non-object in /drush-6.x/commands/pm/release_info/updatexml.inc, line 211
</pre>
Drush version:  7.0-dev
<pre>
  $ drush7 rln environment_indicator-7.x-2.6
  PHP Fatal error:  Call to a member function asXML() on a non-object in /drush7/lib/Drush/UpdateService/Project.php on line 607
 
  Fatal error: Call to a member function asXML() on a non-object in /drush7/lib/Drush/UpdateService/Project.php on line 607
  Drush command terminated abnormally due to an unrecoverable error.                                           [error]
  Error: Call to a member function asXML() on a non-object in
  /drush7/lib/Drush/UpdateService/Project.php, line 607
</pre>

Here's a basic workaround for Drush 7:

<pre>
  diff --git a/lib/Drush/UpdateService/Project.php b/lib/Drush/UpdateService/Project.php
  index 54d000a..626e1cf 100644
  --- a/lib/Drush/UpdateService/Project.php
  +++ b/lib/Drush/UpdateService/Project.php
  @@ -603,7 +603,16 @@ class Project {
         $last_updated = $xml->xpath('//div[@class="last-updated"]');
         $last_updated = $last_updated[0]->asXML();
         $notes = $xml->xpath('//div[contains(@class,"field-name-body")]');
  -      $notes = $notes[0]->asXML();
  +      # Check if $notes[0] is set, quick workaround.
  +      # If the release notes is not available we get: 
  +      # Fatal error: Call to a member function asXML() on a non-object (...)
  +      # We use 'continue' instead of 'break' in the case that we check the release notes
  +      # for more than one module.
  +      if (isset($notes[0])) {
  +        $notes = $notes[0]->asXML();
  +      } else {
  +        continue;
  +      }
   
         // Build the notes header.
         $header = array();
</pre>

**Comment by jonhattan** [comment]
backported to 7.x
