### ISSUE TITLE
drush datestamp in .info are not compatible with the latest recommended release

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#1359]
Not sure if the problem lay in how drush handles the release datestamp or how Update module deals with that.

I've a constant problem when on Available updates page Drupal show me that different 7.x-1.x-dev version is recommended, however at the end, it's the exact same version.

I'm guessing that dates added by drush are different than release dates. I think currently drush takes the datestamp from the latest commit (as suggested [here](https://github.com/drush-ops/drush/issues/1059)), but probably it's a not good approach.

Is there anything that can be fixed in drush that it could better handle datestamps preventing Update module showing the warning that I need to install another version (despite it's the same latest dev)?

Here is my [full description of the problem](https://www.drupal.org/node/2480135).

**Comment by weitzman** [comment]
The full description link is broken.

Maybe you want to install the module without using Drush and see how the datestamp is different? That would help debug this.

**Comment by kenorb** [comment]
I've fixed the link. I'll try to check if the datestamp is the main problem.

**Comment by kenorb** [comment]
First test (testing `drush dl`):

    $ drush -y qd
    # Ctrl-Z, fg
    $ cd quick-drupal-*/drupal/
    $ drush -y dl yql_views_query --dev
    $ drush -y en yql_views_query
    $ tail sites/all/modules/yql_views_query/*.info
    ; Information added by drupal.org packaging script on 2013-10-26
    version = "7.x-1.x-dev"
    datestamp = "1382797741"
    $ drush pm-updatestatus
    # Nothing to show (no updates needed).

Second test (testing `drush make` on the same instance)

    $ drush --no-core -y make <(printf "core = 7.x\nprojects[yql_views_query] = 1.x-dev")
    $ tail sites/all/modules/yql_views_query/*.info
    ; Information added by drupal.org packaging script on 2013-10-26
    version = "7.x-1.x-dev"
    datestamp = "1382797741"
    $ drush pm-updatestatus
    # Nothing to show (no updates needed).

Third test (testing `drush make` and git method):

    $ drush --no-core -y make <(printf "core = 7.x\nprojects[yql_views_query] = 1.x-dev\nprojects[yql_views_query][download][type] = git\nprojects[yql_views_query][download][branch] = 7.x-1.x")
    $ tail sites/all/modules/yql_views_query/*.info
    ; Information added by drush on 2012-09-04
    version = "7.x-1.x-dev"
    project = "yql_views_query"
    datestamp = "1346775212"
    $ drush pm-updatestatus
     Name                                       Installed Version  Proposed version  Message 
     YQL Views Query Backend (yql_views_query)  7.x-1.x-dev        7.x-1.x-dev       Update available

The timestamp is already changed back, despite I'm downloading the same version, but using different method ('drush' instead of 'drupal.org packaging script').

**Comment by weitzman** [comment]
This sounds like #1190. Please make sure you are running with latest Drush (i.e. dev-master) when reporting bugs.
