### ISSUE TITLE
Remove test.drush.inc

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#1362]
Drush attempts to offer an alternative Simpletest runner, mimicking what Drupal's scripts/run-tests.sh offers. Alas hardly anyone keeps it up to date and it has fallen behind for Drupal 8 (can't run phpunit based tests). I propose to remove this script in Drush 7. Others who care can maintain it in Contrib or on Github. Note that run-tests.sh also returns results in junit xml.

Objections?

**Comment by greg-1-anderson** [comment]
No objection here.  I think it is better to have just one way to run the tests.  I think that the Drupal Simpletests are already too fragile--maintaining a parallel runner does not improve the situation, and adds uncertainty.

**Comment by amateescu** [comment]
+1 for removing it.

**Comment by arildm** [comment]
Any chance we can restore `test-clean`? It was helpful.

**Comment by weitzman** [comment]
Sorry, no. Use scripts/run-tests.sh in drupal.

**Comment by EugenMayer** [comment]
that means, i cannot use drush 7.x to run simpletests under drupal6, right?

**Comment by philippelabat** [comment]
Sadly, run-tests.sh does not let you export test result using --xml='path'. Which makes it that much harder to get a proper CI analysis.

**Comment by stefgosselin** [comment]
@philippelabat -  I hit the same wall as you, but came to realise run-tests.sh does support xml exports, it is just not documented in the script arguments.

See line 145 of run-tests.sh
