### ISSUE TITLE
Drush not creating/deleting entity tables in multisite

### ISSUE THREAD

**Issue by AlterEgo7** [drush-ops/drush#1365]
I am working with Drupal8-beta7 and drush 7.0.0-rc1 and have setup multisite configuration through sites.php. Uninstalling a module through drush does not delete the entity tables and installing it does not create them. (Un)installing through the Drupal GUI works well.

**Comment by weitzman** [comment]
Maybe we have to do something special like we did at https://github.com/drush-ops/drush/pull/1204. What module are you installing?

Probably unrelated to multisite

**Comment by AlterEgo7** [comment]
I am installing a custom module that creates 2 entities.

**Comment by weitzman** [comment]
Please share the code or make a test module that illustrates the problem

**Comment by weitzman** [comment]
Config entities must declare enforced dependencies in order to get their entities deleted. Thats a Drupal core requirement. if these are content entities, it would be nice to know what Drush is doing wrong (if anything)
