### ISSUE TITLE
Drush php-eval running just on 1 core

### ISSUE THREAD

**Issue by Vacilando** [drush-ops/drush#1366]
I run very long processes using "drush php-eval" and I notice only one of the 4 CPU cores is busy. 

Any idea whether is this a limitation of drush or PHP CLI or the fact I am running php-eval?

**Comment by weitzman** [comment]
Thats how PHP works. You have to write your eval php to use multi-thread if you want that. See https://www.lullabot.com/blog/article/importing-huge-databases-faster

**Comment by Vacilando** [comment]
Thought so - thanks for the confirmation, Moshe. Will try to code around the limitation.
