### ISSUE TITLE
Dynamic remote web root in aliases

### ISSUE THREAD

**Issue by pjcdawkins** [drush-ops/drush#1370]
I wonder how I could make it possible, in a site alias, to have a dynamic 'root', based on an environment variable?

At the moment Drush escapes (quotes) the `--root` option.

```php
$aliases['myalias'] = [
  'remote-user' => '<user>',
  'remote-host' => '<host>',
  'root' => '$WEB_ROOT',
];
```

currently:
```shell
ssh -o PasswordAuthentication=no <user>@<host> \
 'COLUMNS=120 drush  --verbose --root='\''$WEB_ROOT'\''  core-status 2>&1' 2>&1
```

desired:
```shell
ssh -o PasswordAuthentication=no <user>@<host> \
 'COLUMNS=120 drush  --verbose --root="$WEB_ROOT"  core-status 2>&1' 2>&1
```

**Comment by ergonlogic** [comment]
The alias is PHP. So why not pick up the env var there?

**Comment by pjcdawkins** [comment]
The env var is present on the remote environment, not the local one

**Comment by weitzman** [comment]
In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.
