### ISSUE TITLE
Major-release update via "drush pm-update"?

### ISSUE THREAD

**Issue by danmbox** [drush-ops/drush#1374]
Hi, is there a way to upgrade modules to newer major releases using drush? E.g.

$ drush pm-update zen
> Update status information on all installed and enabled Drupal projects:
>  Name                           Installed   Proposed    Status                                             
> Drupal                         7.36        7.37        Update available
> ...
> Zen (zen)                      7.x-3.3     7.x-3.3     Up to date
> No code updates available.                                                                      [ok]

... but actually there ARE newer releases available:
> $ drush pm-releases zen
> ------- RELEASES FOR 'ZEN' PROJECT -------
> Release         Date         Status
> 7.x-6.x-dev     2015-May-08  Supported, Development
> 7.x-5.x-dev     2015-Mar-10  Development
> 7.x-5.4         2013-Aug-21  Security
> 7.x-3.3         2014-Apr-30  Supported, Security, Installed
> 7.x-5.5         2014-Apr-30  Supported, Recommended, Security
> 7.x-3.x-dev     2014-Apr-30  Development

**Comment by weitzman** [comment]
pm-updatecode updates within same major version. if you want to upgrade to a new major like 7.6 in your example, download it into place with pm-download

**Comment by danmbox** [comment]
... overwriting the existing module installation? Maybe first disable, pm-uninstall, then rm -rf, and only then pm-download

**Comment by weitzman** [comment]
That method works if you are OK with losing any data and config associated with the module. Otherwise, move old one aside and put new files into same place.
