### ISSUE TITLE
sql-drop does not work on PGSQL

### ISSUE THREAD

**Issue by tstoeckler** [drush-ops/drush#1376]
`Sqlpgsql::listTables()` contains some code to remove the first line of output the query returns. However, the output starts with the list of tables directly. Thus, removing the first line, leads to a table being left in the database, which then lets a subsequent `site-install` fail.

I don't know why that line was introduced originally or if there are version differences, etc. but removing that line definitely fixes the issue for me.

**Comment by Haza** [comment]
+1 

I just had the same issue.

![capture_85fc3f1](https://cloud.githubusercontent.com/assets/204144/8526082/abb1028c-2404-11e5-84eb-273c7ab5b2eb.png)

The $table only contains the list of all the tables, so we don't need to remove anything.

**Comment by SebCorbin** [comment]
:+1:

**Comment by dmromanov** [comment]
@tstoeckler Will you create a PR?

**Comment by tstoeckler** [comment]
@dmromanov See https://github.com/drush-ops/drush/pull/1377

**Comment by dmromanov** [comment]
@tstoeckler Thank you.

**Comment by dmromanov** [comment]
@weitzman Already fixed.
