### ISSUE TITLE
sql-create and sql-sync from remote server ignore --db-su

### ISSUE THREAD

**Issue by chuxau** [drush-ops/drush#1383]
Hi,

I have been trying to migrate a site between hosts, and been sending drush commands from the source host (with ssh keys configured appropriately and working)

I have repeatedly come across a challenge where --db-su (maybe) and --db-su-pw are being ignored by drush when trying to operate on the remote hosts DB.  The operations just fail. 

I had to enable the mysql logs on the remote host to eventually discover what was going wrong: drush was attempting to login into mysql with the db-su but with no password.  So, perhaps it does pick up db-su and just ignores db-su-pw .. Makes no difference if db-su/db-su-pw is entered on the command line or in a drush aliases file 

Eventually the only thing that has worked was to create a ~/.my.cnf on the remote host (for the db-su user) and in that file enter the mysql credentials .. 

This issue is also captured in [this gist](https://gist.github.com/jalama/bf3713481b1657f90f1c) ..

**Comment by weitzman** [comment]
Which version of Drush? Try with latest Drush7 or Drush8 please. Please post full output with --verbose.

**Comment by weitzman** [comment]
FYI, the handling for db-su is in \Drush\Sql\SqlBase::su
