### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages. (symfony/var-dumper)

### ISSUE THREAD

**Issue by davidtrainer** [drush-ops/drush#1384]
`composer require drush/drush:6.*` successfully installs drush 6.6.0, but when I run `composer require drush/drush:dev-master` I get the following:

```
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: symfony/var-dumper[v2.6.3, v2.6.7].
    - Can only install one of: symfony/var-dumper[v2.6.7, v2.6.3].
    - drush/drush dev-master requires symfony/var-dumper 2.6.3 -> satisfiable by symfony/var-dumper[v2.6.3].
    - Installation request for drush/drush dev-master -> satisfiable by drush/drush[dev-master].
    - Installation request for symfony/var-dumper == 2.6.7.0 -> satisfiable by symfony/var-dumper[v2.6.7].


Installation failed, deleting ./composer.json.
```

Per #938 I have run composer self-update, deleted composer.lock and composer.json, and tried both with and without the global keyword. Each have given me the same result.

**Comment by greg-1-anderson** [comment]
I could not reproduce this using just Drush; however, I can see how it would be very easy to get into this situation if you ever installed Drush with any other component that directly or indirectly required symfony/var-dumper.

To rectify this situation, I changed Drush's requirement for symfony/var-dumper to require any version >=2.6.3, but less than 3.0.  This update has already reached packagist:

https://packagist.org/packages/drush/drush
