### ISSUE TITLE
drush 7.x in Drupal 8 permissions

### ISSUE THREAD

**Issue by staminna** [drush-ops/drush#1385]
$ drush status
opendir(//dev/fd/6): failed to open dir: Not a directory filesystem.inc:660                                                                                                                   [warning]
opendir(//dev/fd/7): failed to open dir: Not a directory filesystem.inc:660                                                                                                                   [warning]
opendir(//dev/fd/8): failed to open dir: Not a directory filesystem.inc:660                                                                                                                   [warning]
opendir(//etc/cups/certs): failed to open dir: Permission denied filesystem.inc:660                                                                                                           [warning]
opendir(//Library/Application Support/Apple/ParentalControls/Users): failed to open dir: Permission denied filesystem.inc:660                                                                 [warning]
opendir(//Library/Application Support/Apple/Remote Desktop/Client): failed to open dir: Permission denied filesystem.inc:660                                                                  [warning]
opendir(//Library/Application Support/ApplePushService): failed to open dir: Permission denied filesystem.inc:660                                                                             [warning]
opendir(//Library/Application Support/com.apple.TCC): failed to open dir: Permission denied filesystem.inc:660                                                                                [warning]
opendir(//Library/Caches/com.apple.iconservices.store): failed to open dir: Permission denied filesystem.inc:660

On the status report: Info File system	Writable (public download method)
I have installed using composer, maybe previous install settings have been left behind.
Works well in any Drupal 7 install. Drush version                   :  7.0-dev

**Comment by weitzman** [comment]
In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.
