### ISSUE TITLE
Drush drupal-directory returns wrong result

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#1390]
$ drush dd sites
    /var/www/d7/sites/defaults

I suppose we should apply more intelligent replacement in [sitealias.inc#L2041](https://github.com/drush-ops/drush/blob/master/includes/sitealias.inc#L2041)

**Comment by weitzman** [comment]
What are you expecting? If you don't have a module or theme names 'sites', I don't see how this example is supported.

If you are looking for the sites subdir thats active for a request, try `drush st --fields=site`

**Comment by Chi-teck** [comment]
Yes, I was expecting to get _sites_ path to pass it as parameter to _cd_ command. However _sites/defaults_ is very confusing result.

I suppose it should return "Target 'sites' not found."  as it does in other cases.

    $ drush dd example
    Target 'example' not found.
