### ISSUE TITLE
Drush Make post-run command or hook

### ISSUE THREAD

**Issue by jacobbednarz** [drush-ops/drush#1393]
Something that would be handy to do after a successful `drush make` run is the ability to hook in and perform arbitrary commands or execute scripts. I.e. once a module is downloaded, clean up the packaging script data that appears in an `.info` file.

If you think this is an idea worth pursuing, I'm happy to have a crack at it and get some feedback on the implementation.

**Comment by ergonlogic** [comment]
Drush already provides hooks for all commands: https://github.com/drush-ops/drush/blob/master/drush.api.php#L16. So, in the case you describe, all you should need is to implement drush_hook_post_make().

**Comment by jacobbednarz** [comment]
Awesome! Thanks for the pointer.
