### ISSUE TITLE
Unable to install drush 7 with composer

### ISSUE THREAD

**Issue by swaroopkundeti** [drush-ops/drush#1395]
server1# composer global require drush/drush:7.*
Changed current directory to /root/.composer
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package drush/drush could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

**Comment by greg-1-anderson** [comment]
Worked just fine for me just now.  We recently created the 7.x branch, and renamed the master branch from 7.x to 8.x; maybe there was something in your Composer cache that was out of sync with these changes.  Try again, and see if it has cleared up.

**Comment by greg-1-anderson** [comment]
Presumed working; closing.
