### ISSUE TITLE
Drush make-generate writes version number, which doesn't work with drush make

### ISSUE THREAD

**Issue by miloskroulik** [drush-ops/drush#1397]
When I build makefile from my installation, generated versions of historical dev version don't work with drush make.

For example, generated line was:

`projects[auto_entitylabel][version] = "7.x-1.3+1-dev"`

When I try to build makefile with this line, I get:

`Could not locate auto_entitylabel version 7.x-1x-dev.`

However, if I modify it to:
````
projects[auto_entitylabel][version] = "1.x-dev"
projects[auto_entitylabel][download][type] = "git"
projects[auto_entitylabel][download][url] = "http://git.drupal.org/project/auto_entitylabel.git"
projects[auto_entitylabel][download][revision] = "d4624c120c6ea672663d6f4c6f081fff121545a5"
````
it works without any problem. Would it be possible to resolve GIT commits and generate makefiles in correct format? I am using latest version of Drush 6.x

In the meantime, is the only workaround using --working-copy on subsequent builds to preserve GIT info?

**Comment by ergonlogic** [comment]
This appears to work without the extra git info:

    projects[auto_entitylabel][version] = "1.x-dev"

That appears to be the generated output we'd want. The dev builds don't inject the git commit hash into the .info file, so that data isn't available to make-generate.

**Comment by ergonlogic** [comment]
Currently, the generated makefile looks like:

    projects[auto_entitylabel][version] = "1.3+1-dev"

So presumably make-generate should look for a '+' in the version string, and strip it down to "MAJOR.x-dev". Would this overly aggressive? Are there any other legitimate uses to a '+' in a version string?
