### ISSUE TITLE
Feature: Add support for dumping database stored routines

### ISSUE THREAD

**Issue by com2** [drush-ops/drush#1404]
In contributed stored MySQL functions might be part of the database and this is not included in drush sql-dump because mysqldump by default does not include routines. Please add the switch --routines in the command line and they will be included too. I know that core Drupal might never use them, but contributed modules like CiviCRM count on drush making a full dump of the database including the functions. 

https://drive.google.com/file/d/0BzgXit0d3IkrZDA4S1ZaX3podms/view?usp=sharing

**Comment by weitzman** [comment]
See #178
