### ISSUE TITLE
Localize.drupal.org URL is incorrect

### ISSUE THREAD

**Issue by scubafly** [drush-ops/drush#1408]
Hi,

The Localize URL that is hardcoded into Drush (https://github.com/drush-ops/drush/blob/master/commands/make/make.drush.inc#L12) seems to be incorrect, according to https://www.drupal.org/node/2484343#comment-9959915

This causes quite lot of problems, because it makes all our builds fail miserably.

**Comment by weitzman** [comment]
Did something change in d.o. infrastructure? It has been localize.drupal.org since forever. Just curious. I am happy to change it to ftp.drupal.org.

**Comment by rolfvandekrol** [comment]
Looks like an infra change indeed. Not sure. Gábor Hojtsy says it should be ftp.drupal.org, and since he knows everything there is to know about translating Drupal, he's probably right. :smile:

**Comment by weitzman** [comment]
Lets consolidate discussion to the PR - #1394.
