### ISSUE TITLE
installing new drush for ubuntu

### ISSUE THREAD

**Issue by sam452** [drush-ops/drush#1411]
I'm anxious to try out the new version 7.0 and have an older version in my /user/bin/. Pardon my git inadequacies as looking around I found this

composer global require drush/drush:dev-master
which as expected installed version 5. 

Would someone be kind as to point me to how I should tailor the composer command to pull the branch containing the 7.0? thx, sam

**Comment by greg-1-anderson** [comment]
'dev-master' should install version 8; if you are getting something else, you should double-check your $PATH, and make sure that ~/.composer/vendor/bin appears before any other directory that may contain an older version of Drush.

Instructions are here: http://docs.drush.org/en/master/install/
