### ISSUE TITLE
Permission to use drush logo in Dash/Zeal docset

### ISSUE THREAD

**Issue by mikebell** [drush-ops/drush#1415]
Hi,

I'm nearly finished writing a tool (https://github.com/mikebell/drush-docset) to build a drush docset for the offline documentation application Dash (https://kapeli.com/dash) and Zeal (http://zealdocs.org).

As part of publishing the docset I'd like permission to include the drush logo as an icon. The icon would be visible for anyone who has the docset installed.

Would this be possible?

**Comment by weitzman** [comment]
Yes, thats no problem at all. Thanks for helping promote out docs.
