### ISSUE TITLE
Drush 8.0-dev does not support Drupal

### ISSUE THREAD

**Issue by boabjohn** [drush-ops/drush#1416]
Hi guys,
Just trying to get up to the bleeding edge and found that my Drupal 8 beta4 will not run with Composer-installed Drush 8.0-dev, the intriguing error above being my only clue.
Drush 8.0-dev is running fine in D7 installs, but the D8 is not to its liking.
Google did not provide many clues on this one..sorry for jumping in to the git queue.

**Comment by weitzman** [comment]
We dont support old betas of Drupal8. You have to downgrade your drush or upgrade your drupal.

In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.
