### ISSUE TITLE
Make the Drush Make tests more stable

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#1431]
It's always a bother to have our unit tests periodically failing because some md5 checksum no longer matches.  It would be really helpful if these tests could be rewritten to either:

a) Not use md5 in assertEquals(), and instead use some other measure to evaluate whether the build was "successful" or not

or

b) Only include fake "stub" modules in any test makefile, so that we do not have our test results changing based on ordinary development / evolution of external components that are not Drush dependencies.

**Comment by jhedstrom** [comment]
Anything currently relying on an md5 checksum should be checking out a very specific version of something. I haven't seen checksum failures in some time. What does periodically happen is the removal of a project from github (or a tag, etc). I'd love to be in a place where  the tests do not rely on any external downloads.

**Comment by greg-1-anderson** [comment]
Make is maintenance only; closing.
