### ISSUE TITLE
Starter guide for using new Boris console

### ISSUE THREAD

**Issue by sam452** [drush-ops/drush#1433]
I was thrilled to see that a REPL like Boris was built into drush. I'm anxious to use it but saw no command that would seem appropriate. Searching the issues I blindly copied what you've done before: drush @site x-generate-module but the failure was expected. Reading the Boris page it seems that if drush had it installed I didn't need to pull down its dependencies? I'm probably overlooking something obvious but a nudge in the right direction would be appreciated, thx, sam

**Comment by weitzman** [comment]
the command is core-cli
