### ISSUE TITLE
locale_parse_js_file

### ISSUE THREAD

**Issue by nkorovin** [drush-ops/drush#1436]

**Comment by weitzman** [comment]
too terse

**Comment by nkorovin** [comment]
Failed opening required 'sites/all/modules/sheetnode/socialcalc.inc' (include_path='.;C:\php\pear;includes/ZendGdata-1.12.13/library') in Z:\home\edukakmogu.my\www\sites\all\modules\sheetnode\sheetnode.module on line 311

**Comment by nkorovin** [comment]
I can not understand how to fix the error, such as simple, but I still do not know. I beg your pardon

**Comment by weitzman** [comment]
This is the Drush project. Your error relates to the sheetnode module which is different.

**Comment by nkorovin** [comment]
Excuse me, learning to live new
