### ISSUE TITLE
File names using word "aliases" adds ghost aliases

### ISSUE THREAD

**Issue by ccharlton** [drush-ops/drush#1444]
I was testing custom Shell Aliases in a file called `~/.drush/sitealiases.drushrc.php` and by naming the file with the word "_aliases_" Drush thought I had a new set of custom Site Aliases and was listing a ghost group called `@shellaliases`.
Renaming the file fixed the issue (I used `sa.drushrc.php`), but I figured I'd report the problem. It's trivial for sure, but something I noticed recently.

**Comment by frederickjh** [comment]
Actually this is a feature of site aliases. By putting <b>aliases</b> instead of <b>alias</b> in the name you are creating a group of aliases the group alias can be used to perform actions on all aliases in the group.
[example.aliases.drushrc.php](https://raw.githubusercontent.com/drush-ops/drush/master/examples/example.aliases.drushrc.php) states:
> There are several ways to create alias files.
>
>   + Put each alias in a separate file called ALIASNAME.alias.drushrc.php
>   + Put multiple aliases in a single file called aliases.drushrc.php
>   + Put groups of aliases into files called <b>GROUPNAME.aliases.drushrc.php</b>

. . .
> Alias groups (aliases stored together in files called
> GROUPNAME.aliases.drushrc.php, as mentioned above) also
> create an implicit namespace that is named after the group
> name.
>
> For example:
>
> @code
> \# File: mysite.aliases.drushrc.php
> $aliases['dev'] = array(
>   'root' => '/path/to/drupal',
>   'uri' => 'dev.mydrupalsite.com',
> );
> $aliases['live'] = array(
>   'root' => '/other/path/to/drupal',
>   'uri' => 'mydrupalsite.com',
> );
> @endcode
>
> Then the following special aliases are defined:
> - @mysite: An alias named after the groupname may be used to reference all of
>   the aliases in the group (e.g., `drush @mydrupalsite status`).
> - @mysite.dev: A copy of @dev.
> - @mysite.live: A copy of @live.
>
> Thus, aliases defined in an alias group file may be referred to
> either by their simple (short) name, or by their full namespace-qualified
> name.

Considering that this is a feature of Drush site aliases this issue can be safely closed.

**Comment by ccharlton** [comment]
I've familiar with _groupaliases_, and my file didn't have the dot ("*.aliases"), so as long the file naming isn't strict by design then this issue can be closed. If the period in the group's filename _should_ be a requirement then we'll want to reopen.

**Comment by frederickjh** [comment]
Sorry, somehow I missed the missing dot / period. That does sound like bug.  It should default to a normal alias file. On the other side I find it confusing to use the word aliases in an alias file ;)

**Comment by ccharlton** [comment]
Agreed, my file naming wasn't ideal but still exposed a small bug in Drush Aliases.

**Comment by greg-1-anderson** [comment]
Yes, Drush should be insisting on the extra "dot" in the filename.

**Comment by greg-1-anderson** [comment]
The Drush 8 implementation of aliases will not be getting much attention moving forward. There is a new implementation in Drush 9.
