### ISSUE TITLE
The drush command 'migrate-manifest' could not be found.

### ISSUE THREAD

**Issue by davidcsonka** [drush-ops/drush#1451]
Attempting to do a D7 to D8 migration, using instructions found in these articles: http://www.metaltoad.com/blog/migrating-content-drupal-8

Using Drush version 8.0-dev. Migrate and Migrate Drupal modules are enabled.  

Running: 
drush migrate-manifest manifest.yml --legacy-db-url=mysql://my_user:my_pass@localhost/my_db

Gives me the following error:
The drush command 'migrate-manifest manifest.yml' could not be found.  Run `drush   [error]
cache-clear drush` to clear the commandfile cache if you have installed new
extensions.

Am I missing something here? Based on those blog posts with instructions, I got the impression a basic D7 to D8 migration could be done using the latest version of Drush.

**Comment by neclimdul** [comment]
Yeah, caused me trouble too.

remove in 98809b0

added to migrate_plus here: https://www.drupal.org/node/2506583

**Comment by davidcsonka** [comment]
Thank you for the help, using the sandbox migrate_plus module you linked to solved that issue for me. +1
