### ISSUE TITLE
Automated Testing of Updatedb

### ISSUE THREAD

**Issue by generalconsensus** [drush-ops/drush#1453]
In order to make our infrastructure more agile we are investing more in automated tests -- via Behat and the https://github.com/jhedstrom/drupalextension repo.

In order to keep my sanity I am preferring that drush export only JSON so that I can do systematic matching against the responses I get from Drush.

While it was very easy to modify an existing drush contrib command (features) to make a command only export in JSON -- the same can not be said of drush updb. 

```php

    'outputformat' => array(
      'default' => 'key-value',
      'pipe-format' => 'json',
      'simplify-single' => TRUE,
      'table-metadata' => array(
        'list-separator' => ' ',
      ),
      'output-data-type' => 'format-list',
    ),
```

I do realize that the current direction of the project does a lot to support this -- and of which I am very grateful. 

Can you suggest anyway to make this functionality happen -- I would be glad to do the work but I believe that attention is focused on making this happen [first](https://github.com/drush-ops/drush/pull/673) before [this](https://github.com/drush-ops/drush/issues/1126)

**Comment by weitzman** [comment]
If you want a list of pending updates, use the update-status command. Otherwise, I'm not sure what data you are trying to get out.

**Comment by weitzman** [comment]
Closing until the request is clarified.

**Comment by generalconsensus** [comment]
@weitzman Sorry for the delay in answering your original request: 

The point of this is take the following default output and make it just JSON

![image of normal updb]
(https://www.evernote.com/l/AFMS8yQ9zM9KUoJaozI82CZyTj8xilx-zT0B/image.png)

**Comment by weitzman** [comment]
`drush updatedb-status --format=json`

**Comment by generalconsensus** [comment]
Yes, but actionable -- the updatedb-status command only lists any pending database updates, but does not trigger the update itself. Indulge me for a moment to suggest the following as a backend behat test:

Given I run drush "updb" "--format=json"
Then I should see that the update works correctly

If this makes sense, I would be glad to send up a PR

**Comment by weitzman** [comment]
Oh. The usual way you test to see if the update completed successfully is to examine the exit code from updatedb call. If it is zero, it was successful. Thats the unix standard.

If you really want more info, call `updatedb --backend` and you will get a JSON packet in return thats wrapped in some standard delimiters. Once you get JSON out of it you get log files, errors, etc.
