### ISSUE TITLE
Handling recoverable fatal errors

### ISSUE THREAD

**Issue by mdeletter** [drush-ops/drush#1459]
Why is there a difference between handling recoverable fatal errors (E_RECOVERABLE_ERROR) in Drush versus Drupal (7.x)?

Drupal is treating recoverable fatal errors the same as fatal errors and the execution of the script is stopped. See [_drupal_error_handler](https://api.drupal.org/api/drupal/includes!errors.inc/function/_drupal_error_handler_real/7) and [_drupal_log_error](https://api.drupal.org/api/drupal/includes!errors.inc/function/_drupal_log_error/7) 

Inside the Drush (version 6.x,7.x), the same error is logged (as a notice ??) and even more scary: the execution of the script continues. See drush_error_handler in drush/includes/environment.inc

Thanks for the information!

**Comment by mdeletter** [comment]
See #1465 for the solution.

**Comment by weitzman** [comment]
Lets use #1465
