### ISSUE TITLE
drush_policy_core_rsync_validate() function not working.

### ISSUE THREAD

**Issue by awochna** [drush-ops/drush#1463]
The following are two examples in my `policy.drush.inc` file:

    /**
     * Implements drush_hook_COMMAND_validate().
     *
     * Prevent catastrophic sql sync to production.
     */
    function drush_policy_sql_sync_validate($source = NULL, $destination = NULL) {
      if (preg_match("/@prod/", $destination)) {
        return drush_set_error('POLICY_DENY', dt('Per /etc/drush/commands/policy.drush.inc, you may not overwrite the production database!'));
      }
    }
    
    /**
     * Implements drush_hook_COMMAND_validate().
     *
     * Prevent catastrophic rsync to production.
     */
    function drush_policy_core_rsync_validate($source = NULL, $destinaton = NULL) {
      if (preg_match("/@prod/", $destination)) {
        return drush_set_error('POLICY_DENY', dt('Per /etc/drush/commands/policy.drush.inc, you may not overwrite the production file set!'));
      }
    }

The first policy works as designed. `drush -s sql-sync @test.site @prod.site` results in an error telling me I can't overwrite the production database.

The second policy does not work. `drush -s rsync @test.site @prod.site` results in printing the system call the command would use, instead of an error telling me that I can't overwrite the production file set.

I have tried naming the function `drush_policy_rsync_validate()` as well with no change in effect.

**Comment by greg-1-anderson** [comment]
This worked for me in Drush 8 (master branch):
```
/**
 * Implements drush_hook_COMMAND_validate().
 *
 * We can also limit rsync operations to production sites.
 */
function drush_policy_core_rsync_validate($source = NULL, $destination = NULL) {
  if (preg_match("/^@prod/", $destination)) {
    return drush_set_error('POLICY_DENY', dt('Per examples/policy.drush.inc, you may never rsync to the production site.' . $destination));
  }
}
```
I added this to the example policy file on the master branch.
