### ISSUE TITLE
Versions of modules

### ISSUE THREAD

**Issue by tnanek** [drush-ops/drush#1466]
I am quite confused at my current situation and was hoping someone could assist, its more than one module, just trying to simplify it here.

I'm currently in the site specific folder.

> $ drush cc drush
> 'drush' cache was cleared
> $ drush ups mailchimp
> ...
>  Name  Installed Version  Proposed version  Message                   
>  MailChimp (mailchimp)  7.x-3.2            7.x-3.4           SECURITY UPDATE available
> (Installed: 7.x-3.2)
> (Proposed: 7.x-3.4)
> $ grep version modules/mailchimp/mailchimp.info
> version = "7.x-3.4"

**Comment by jonhattan** [comment]
It is likely that you have more than one copy of mailchimp installed. Check the install directory of the copy that Drupal prefers with `drush pm-info mailchimp`.

**Comment by tnanek** [comment]
Confirming that was the issue, thanks @jonhattan.
