### ISSUE TITLE
Segmentation fault when using site-install with Drupal 8 on PHP 7.0.0 Alpha 2

### ISSUE THREAD

**Issue by geerlingguy** [drush-ops/drush#1467]
When I tried installing a Drupal 8 HEAD site via Drush (master branch, as of today), I got a `Segmentation fault` after a couple seconds, and nothing else.

Database tables are created, and most of the filesystem changes (like setting up a `settings.php` file and the lik) are done, but it doesn't complete, and when I try loading the not-quite-installed site, I get a 404, and the site is in some strange state.

```
$ drush si standard -y \
  --site-name="Test Me" \
  --account-name=admin \
  --account-pass=admin \
  --db-url=mysql://drupal:drupal@localhost/drupal
You are about to create a /var/www/drupal/sites/default/settings.php file and DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                 [ok]
Segmentation fault
```

If I use Drupal 8 HEAD's web UI to install the site, it installs fine. Additionally, if I run either PHP 5.5 or 5.6, Drush `site-install` works fine.

I don't have much more time to debug today, but steps for testing are basically outlined on this page: https://github.com/geerlingguy/drupal-vm/wiki/PHP-7-on-Drupal-VM#redhatcentos-7 (just don't set `install_site` to `false` if you want Vagrant to bail out; otherwise, follow the directions for CentOS, then `vagrant ssh` in, and run the above site install command inside `/var/www/drupal` to see for yourself).

**Comment by weitzman** [comment]
If anyone gets details here, it would be much appreciated.

**Comment by geerlingguy** [comment]
I think I may be able to reproduce this with a source build of PHP 5.6.10 as well, but we'll see. I'm testing multiple versions of PHP on a Raspberry Pi and will try to get more information/debug info if possible.

**Comment by geerlingguy** [comment]
Debug output on a fresh Raspberry Pi running Debian 7 and PHP 7.0.0-alpha2:

```
# drush site-install standard -y --site-name="Drupal Pi" --account-name=admin --account-pass=admin --db-url=mysql://drupal:supersecure@localhost/drupal --debug
Starting Drush preflight. [0.02 sec, 1.83 MB]                                                                [preflight]
Cache HIT cid: 8.0-dev-commandfiles-0-fc1cd62fa8fc4a79c6471dedc94a852f [0.04 sec, 1.92 MB]                       [debug]
Bootstrap to phase 0. [0.31 sec, 4.15 MB]                                                                    [bootstrap]
Bootstrap to phase 1. [0.32 sec, 4.15 MB]                                                                    [bootstrap]
Drush bootstrap phase : bootstrap_drupal_root() [0.34 sec, 4.45 MB]                                          [bootstrap]
Initialized Drupal 8.0.0-dev root directory at /var/www/drupal [0.35 sec, 4.45 MB]                              [notice]
Find command files for phase 1 (max=1) [0.35 sec, 3.8 MB]                                                        [debug]
Cache HIT cid: 8.0-dev-commandfiles-1-8b12b5889cef410748dab3200b18bda1 [0.36 sec, 3.81 MB]                       [debug]
Found command: site-install (commandfile=site_install) [0.36 sec, 3.85 MB]                                   [bootstrap]
Calling hook drush_core_site_install_validate [0.5 sec, 4.57 MB]                                                 [debug]
Returned from hook drush_core_site_install_validate [0.5 sec, 4.57 MB]                                           [debug]
Calling hook drush_core_pre_site_install [0.5 sec, 4.59 MB]                                                      [debug]
Cache MISS cid: 8.0-dev-alias-path--b2128d00007d0d10071fff4a8b200722 [0.51 sec, 4.63 MB]                         [debug]
sql-query: SELECT 1; [0.52 sec, 4.63 MB]                                                                     [status]
Executing: mysql --defaults-extra-file=/tmp/drush_kr7kVo --database=drupal --host=localhost --silent  < /tmp/drush_WJEFJM > /dev/null
You are about to create a /var/www/drupal/sites/default/settings.php file and DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y
Sites directory /var/www/drupal/sites/default already exists - proceeding. [0.55 sec, 4.63 MB]                  [notice]
Calling copy(sites/default/default.settings.php, /var/www/drupal/sites/default/settings.php) [0.55 sec, 4.63     [debug]
MB]
Drush bootstrap phase : bootstrap_drupal_site() [0.58 sec, 5 MB]                                             [bootstrap]
Initialized Drupal site default at sites/default [0.58 sec, 5 MB]                                               [notice]
Find command files for phase 2 (max=) [0.6 sec, 4.31 MB]                                                         [debug]
Cache MISS cid: 8.0-dev-install_profile-66ecfeb9791a023150773849f1550c5d [0.6 sec, 4.31 MB]                      [debug]
Cache HIT cid: 8.0-dev-commandfiles-2-50dd6edc39e3ab92adfb6fe5265f6291 [0.6 sec, 4.31 MB]                        [debug]
sql-query: SELECT 1; [0.6 sec, 4.37 MB]                                                                      [status]
Executing: mysql --defaults-extra-file=/tmp/drush_CIc13Q --database=drupal --host=localhost --silent  < /tmp/drush_cubg07 > /dev/null
sql-query: SHOW TABLES; [0.64 sec, 4.37 MB]                                                                  [status]
Executing: mysql --defaults-extra-file=/tmp/drush_usFyXn --database=drupal --host=localhost --silent  < /tmp/drush_CN9KwC
Returned from hook drush_core_pre_site_install [0.67 sec, 4.37 MB]                                               [debug]
Calling hook drush_core_site_install [0.67 sec, 4.38 MB]                                                         [debug]
Starting Drupal installation. This takes a while. Consider using the --notify global option. [0.69 sec, 4.65 [ok]
MB]
Calling install_drupal(Object, Array) [0.69 sec, 4.65 MB]                                                        [debug]
Segmentation fault
```

Interestingly, database tables are created, and enough of the install completes that Drupal loads a page and allows login. I don't know what exactly didn't complete at that point though. I'm trying to see if I can dig deeper into the segfault.

**Comment by weitzman** [comment]
check the PHP error log. Certainly looks like Drupal related. Note a few
minor PHP7 bugs listed at https://www.drupal.org/node/2454439

**Comment by geerlingguy** [comment]
K, here's some more debug info after attempting install via web GUI on the Pi (this worked on Drupal VM, so not sure why it's not working on the Pi):

FPM log:

```
/var/log# cat php-fpm.log 
[06-Jul-2015 19:27:09] NOTICE: fpm is running, pid 14440
[06-Jul-2015 19:27:09] NOTICE: ready to handle connections
[06-Jul-2015 19:30:11] WARNING: [pool www] child 14443 exited on signal 11 (SIGSEGV) after 181.935722 seconds from start
[06-Jul-2015 19:30:11] NOTICE: [pool www] child 14497 started
```

And the error from Nginx (just reporting that fpm died):

```
2015/07/06 19:30:11 [error] 14411#0: *9 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.0.1.36, server: 10.0.1.49, request: "POST /core/install.php?langcode=en&profile=standard HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "10.0.1.49", referrer: "http://10.0.1.49/core/install.php?langcode=en&profile=standard"
```

I'm trying to get more debug info, but it seems PHP just bails without extra error reporting, and I don't have xdebug running with PHP 7 to find more info.

But it _does_ seem PHP 7/Drupal 8 related, at least on the Pi. Can close this ticket if you'd like, but it seems like I am still unable to install Drupal 8 on PHP 7 (alpha 2) regardless, definitely with drush, and possibly also with Drupal's UI :(

**Comment by geerlingguy** [comment]
Hmm, simply refreshing the web UI page where the install bailed on segfault picks back up where it left off and completes the rest of the installation process.

**Comment by weitzman** [comment]
Memory exhaustion? Check php.ini memory_limit. Just a guess.

**Comment by geerlingguy** [comment]
Could be it... but I have 128MB set, and confirmed that it's correct via `phpinfo()`... afaict, D8 supposedly only _requires_ 64MB, though more is recommended. If I get some time, I'll also test installing minimal profile instead of standard profile. Fewer core modules to potentially break things.

**Comment by geerlingguy** [comment]
FYI, I rebuilt a Pi 2 fresh this morning with PHP 7.0.0 beta1, and there were no segmentation faults. Not only that, things are noticably—and measurably—faster across the board (see https://github.com/geerlingguy/drupal-pi/wiki).

**Comment by geerlingguy** [comment]
So... unceremoniously closing this issue, as it seems to have been related to a bug that's been fixed in PHP core.
