### ISSUE TITLE
Drush make and (php 5.3.5) Unable to patch caption_filter with 1432092-button-and-image.patch.

### ISSUE THREAD

**Issue by joejoseph00** [drush-ops/drush#147]
Steps to reproduce:
Install any version of Drush (5.4 through 6.0)
PHP 5.3.5

and then try to run a drush make as follows: 
http://wiki.drupalwxt.org/concepts/drush-make/

The following error message occurs: 
Unable to patch caption_filter with 1432092-button-and-image.patch.

For some reason this doesn't work on PHP 5.3.5 (at least not in my environment) using any version of drush I tried (5.4, 5.5, 5.6, 5.7, 5.8 , 5.9, 6.0 ).

YET it does work with PHP 5.3.3 and drush 5.7

So it appears to be a problem with PHP 5.3.5 , but I don't know what other versions of PHP might be affected.  

If someone has some debug suggestions/techniques I could run them and provide more information here.

**Comment by greg-1-anderson** [comment]
Drush 7 is EOL as well; I would recommend upgrading to Drush 8.

**Comment by joejoseph00** [comment]
Yes I have been using Drush 8 lately, it works as well as Drush 7, I haven't noticed any issues yet.
