### ISSUE TITLE
YAML makefile quotes gotcha

### ISSUE THREAD

**Issue by danepowell** [drush-ops/drush#1470]
If you create a makefile with a line like this, you would expect to get version 1.0 of visitor_actions.
````
package:
  visitor_actions: 1.0
````
Instead, you will actually get 1.1 every time.

I'm guessing what's happening here is that the YAML parser is casting this version to an integer and dropping the trailing 0, so drush make downloads the latest version instead.

One of two things should be done to fix this: either tweak the parser to treat version numbers as strings (no idea if that's possible or not), or change the documentation (for instance [here](http://www.drush.org/en/master/make/)) to always put version numbers in quotes.

**Comment by danepowell** [comment]
I'm not sure if there's a way to force the YAML parser to cast certain attributes to strings - a documentation fix seems easier. See associated pull request.

**Comment by davereid** [comment]
I would agree a docs fix is probably best.

**Comment by jonhattan** [comment]
For the record, here's how to cast a float to a string in yaml:

```
projects:
  visitor_actions: !str 1.0
```
