### ISSUE TITLE
Drush @sites not working when realpaths of symlinks not ending with site-alias

### ISSUE THREAD

**Issue by alexanderschimpf-de** [drush-ops/drush#1472]
I think there is bug in _drush_find_local_sites_in_sites_folder (located in Includes/sitealias.inc): lines 1417-1419 intend to detect whether a symlink points outside the drupal root directory or not. But the if-condition (line 1419) should always evaluate to true ($real_root should never evaluate to FALSE), because $real_root will be always $a_drupal_root. The problem ist, that in order to get the real root, drush_locate_root is applied to $filename, which actually is prefixed by $a_drupal_root. Probably drush_locate_root should be applied to $real_sitedir here!?
Despite that bug the sites alias should work, when symlinks point to paths that are suffixed by the site-alias, and won't work, if not.

Alex

**Comment by leymannx** [comment]
Recently found out that a sites/$site/settings.php file needs to be existent to get @sites working correctly. It MUST NOT be a symlink.

**Comment by greg-1-anderson** [comment]
Drush 8 is maintenance only, and Drush 9 does not support `@sites`. Closing.
