### ISSUE TITLE
updb should show $sandbox['message'] instead of repeating the function name

### ISSUE THREAD

**Issue by rudiedirkx** [drush-ops/drush#1475]
In `drush_update_do_one()` this is the message shown after every batch cycle (sometimes 1, sometimes many per update hook):

    $context['message'] = 'Performed update: ' . $function;

If you see those 20, you still don't know anything. Drupal invented `$sandbox['message']` for this, to show messages during 1 update hook's batch operations.

I propose:

```
if ($context['finished'] == 1 || empty($context['sandbox']['message'])) {
  $context['message'] = 'Performed update: ' . $function;
}
else {
  $context['message'] = $context['sandbox']['message'];
}
```

`drupal_set_message()` isn't displayed consistently after/during every batch operation, so sometimes you see none and then suddenly 6, so it's not as useful. Only `$context['message']` is consistent.

**Comment by weitzman** [comment]
No time to investigate. Notice some attempt at logging in _drush_log_update_sql()

**Comment by rudiedirkx** [comment]
In my Drush (6.2.0) `_drush_log_update_sql()` is only used in `update_6.inc`, and it doesn't use `'message'` like `update.php` UI does. Maybe I misunderstand.

I'll make a pull request soon, so you can see the diff.

**Comment by weitzman** [comment]
I see some attempt to show these messages at https://github.com/drush-ops/drush/blob/master/commands/core/drupal/update_7.inc#L77. Needs debugging.

Also, please submit a PR against the master branch, not 6.2.0

**Comment by rudiedirkx** [comment]
I see now that `update.php` doesn't use `$sandbox['message']` either... Only the return value, but only at the very end, after all updates. Not useful for big batches.

Drush does that too (since 7.0 I think), so at least it's consistent, and slightly better than `update.php`. I haven't tested with 7.x or 8.x, so I don't know if it actually works. It wants me to install composer and read stuff. Maybe later.

**Comment by jhedstrom** [comment]
I think this is related to #1509. Digging into that one now.

**Comment by weitzman** [comment]
Seems like message is not used by Druapl or Drush so this issue is a Wont Fix.

**Comment by rudiedirkx** [comment]
Yeah, I don't know where I got that. Sorry for the confusion.

It would be awesome if something like this existed though. Drush updates with big sandboxes with 100+ iterations can be very spooky, because you don't know what happened until the very end, which you can't see coming. Repeating `Performed update: my_update_7011` 100+ times isn't very useful...

**Comment by weitzman** [comment]
See #1484

**Comment by rudiedirkx** [comment]
Excellent! Thanks.
