### ISSUE TITLE
Can't install module geophp using drush make file. It uses geoPHP instead of geophp.

### ISSUE THREAD

**Issue by dpastov** [drush-ops/drush#1483]
I can't install module using drush make. As far as I see, drush reads somewhere name of module with upper case (geoPHP, instead of geophp).

Here is real example that does not work.

1) Here is my 'make file':
```
; Drush make - drupal informations
core = 7.x
api = 2
; Contrib Modules
projects[geophp][version] = 1.7
```
2) How I run the 'make file'
```
drush make test.make -y --no-core --no-patch-txt
```
3) Result of srunning make file (notice, it says geoPHP, but not geophp):
```
Make new site in the current directory? (y/n): y
Beginning to build test.make.                                                                                                    [ok]
No release history was found for the requested project (geoPHP).  
```

*END*

However it works fine if I use command from terminal:
```
dursh dl geophp
```

Is it something related to drush or to drupal config?

**Comment by jonhattan** [comment]
It doesn't uppercase, it shows the project human name. Perhaps you have stale caches. Try `drush cc drush`
