### ISSUE TITLE
aliases.drushrc.php running twice

### ISSUE THREAD

**Issue by guaka** [drush-ops/drush#1485]
```
$ drush site-alias
@none
```

But I have about 100 aliases set up.

```
$ drush @example.com pml
... long list of modules ...
```

My `~/.drush/aliases.drushrc.php` looks like

```
<?php

require_once '~/REPO1/scripts/aliases.drushrc.php';
require_once '~/REPO2/scripts/aliases.drushrc.php';
```

And those `aliases.drushrc.php` work fine...

**Comment by weitzman** [comment]
What is @none? Is that your way of saying 'no output'?

Can you put a die('here') at top of aliases.drushrc.php to see if that file is getting loaded? What version of Drush? We recently made an alias path change in master branch.

**Comment by guaka** [comment]
It's executed. Twice, actually! I added `echo sizeof($aliases) . "\n";` to `aliases.drushrc.php`.
I guess my code is probably doing something wrong here when executed twice. Looking into that now.
Still weird it's executed twice...

![screen shot 2015-07-09 at 15 00 44](https://cloud.githubusercontent.com/assets/54728/8595780/4df9d620-264b-11e5-81f4-84ccca4bc277.png)
(Switched to `sh`, fastest way to reduce information in screenshot.)

**Comment by guaka** [comment]
Ah! It's because I used `require_once`. Switched to `include`.

Fixed the problem for me, so this issue could be closed, but I don't think `aliases.drushrc.php` should be running twice...

**Comment by weitzman** [comment]
I am seeing two executions as well. I think this is particular to the sa command. Not sure if it is worth fixing. Ping @greg-1-anderson

**Comment by greg-1-anderson** [comment]
Drush 8 is maintenance only, and we have a new alias manager implementation in Drush 9. Closing
