### ISSUE TITLE
sql-sync on remote host with a different source db is silently failing

### ISSUE THREAD

**Issue by jurgenhaas** [drush-ops/drush#1492]
My sites do have two different databases defines in the settings.php and when syncing those to a different site with sql-sny, that works as long as both sites are on the same host.

I'm using the following two commands to copy the default and the secondary database from @live to @dev:

```
drush -y sql-sync @live @dev
drush -y sql-sync @live @dev --source-database=secondary --target-database=devsecondary
```

My problem is that if the @live host is remote, then the sync for the default database works fine but the sync for the secondary database seems to be working but the dev database remains empty.

Any idea what could be causing this? Tested with Drush 6.5, 7.0 and 7.0-dev

**Comment by weitzman** [comment]
No idea. I think you have to verify if each step is working (the dump, the rsync, the import). Use --verbose to see the commands running.

**Comment by jurgenhaas** [comment]
Found it.

I'm calling ```drush -y sql-sync @live @dev --source-database=secondary --target-database=devsecondary```

That does those two steps (among others):

```
drush sql-dump @live --source-database=secondary --target-database=devsecondary
drush sql-query @dev --source-database=secondary --target-database=devsecondary --file=data.sql
```

The correct syntay would be to replace source-database and target-database as follows:

```
drush sql-dump @live --database=secondary
drush sql-query @dev --database=devsecondary --file=data.sql
```

**Comment by weitzman** [comment]
It would be great if you could post the full output with --verbose. Also, please assure that you are using drush7 on both sides of the sql-sync.

It looks like we lost some of the handling of source- and target- in the new sql-sync. I'd like to handle this in sql-sync and get rid of framework handling like drush_get_merged_prefixed_options(), etc. Any objection, @greg-1-anderson?

**Comment by greg-1-anderson** [comment]
For most Drush commands, drush_get_option() will correctly fetch the best prioritized option from the available contexts.  The thing about sql-sync is that there are options in the @source and @destination option, and we wanted to be able to override any of these either with --source-foo or --foo for the source, or --target-foo or --foo for the target.  The framework handling functions like drush_get_merged_prefixed_options () were introduced to reduce the amount of branching in the sql-sync implementation, which, in its original form, started out with a lot of nesting and a lot of conditionals.

I have no objection to simplifying and eliminating these helper functions now that sql-sync itself is simpler; it would be great if the end result did not cause too much additional branching (plethora of 'if' statements) in the sql-sync body.

**Comment by jurgenhaas** [comment]
@weitzman unfortunately I faced that problem in a production environment and had to switch back to drush 6.x to keep the ongoing deployment processes working. Sorry, therefore can't provide the full output from drush 7 anymore.
