### ISSUE TITLE
user-login to a remote host does not pass along a cli override of --uri option

### ISSUE THREAD

**Issue by ian-rose** [drush-ops/drush#1493]
I have an `example.aliases.drushrc.php` file with contents of:

```php
<?php
$aliases['prod'] = array(
  'parent' => '@parent',
  'site' => 'example',
  'env' => 'prod',
  'root' => '/path/to/drupal',
  'remote-host' => 'server.tld',
  'remote-user' => 'example',
  'uri' => 'www.example.com',
);
```

When I run `drush @example.prod uli` the command returns `http://www.example.com/user/reset/1/[token]/login`.

When I run `drush @example.prod uli -l edit.example.com` I expect to get `http://edit.example.com/user/reset/1/[token]/login`, but instead the command returns `http://www.example.com/user/reset/1/[token]/login`

I believe this is an issue, as command-line arguments should override any defaults defined in an alias.

**Comment by weitzman** [comment]
This is an edge case when you are calling uli on a remote host and have specified a custom uri. We dont pass aong that uri in our redispatch. See https://github.com/drush-ops/drush/blob/8.0.0-beta12/commands/user/user.drush.inc#L378. Ping @greg-1-anderson for ideas on how to fix. Not urgent.

**Comment by ian-rose** [comment]
I tested with the following alias configuration on a local environment and am still seeing drush not prioritize the `--uri` flag over the alias's `uri` definition:

```php
<?php
$aliases['local'] = array(
  'parent' => '@parent',
  'site' => 'example',
  'env' => 'local',
  'root' => '/path/to/drupal',
  'uri' => 'local.example.com',
);
```

This issue appears to apply to both remote hosts and local sites.

**Comment by weitzman** [comment]
@ian-rose - what version of drupal and drush are you using?

**Comment by weitzman** [comment]
I tried to reproduce the problem and was not able. Here is my alias and command. I got back an URL that 127.0.0.1 domain, not mm domain:

```
~/c/h/drush (master<)$ dr sa @d7
$aliases["d7"] = array (
  'root' => '/Users/moshe.weitzman/htd/d7',
  'uri' => 'http://mm/d7',
  'path-aliases' => 
  array (
    '%dump-dir' => '/Users/moshe.weitzman/sqldump',
  ),
);
```

`dr @d7 --uri=127.0.0.1/d7 uli`

**Comment by ian-rose** [comment]
I was using a (outdated) 6.x version. I pulled the latest 6.x and tested on that and 7.x, and am no longer seeing the issue on local environments.

updating++

**Comment by weitzman** [comment]
We still have this problem with a remote-host.

**Comment by blazindrop** [comment]
Confirmed still an issue for remote-host

**Comment by blazindrop** [comment]
I have a fix working locally; PR coming soon

**Comment by weitzman** [comment]
Lets keep further discussion in the PR
