### ISSUE TITLE
drush_preflight_prepare() makes assumptions about Composer

### ISSUE THREAD

**Issue by djotto** [drush-ops/drush#1494]
From `drush_preflight_prepare()`:

    $local_vendor_path = DRUSH_BASE_PATH . '/vendor/autoload.php';
    $global_vendor_path = DRUSH_BASE_PATH . '/../../../vendor/autoload.php';

    // Check for a local composer install or a global composer install. Vendor dirs are in different spots).
    if (file_exists($local_vendor_path)) {
        $vendor_path = $local_vendor_path;
    }
    elseif (file_exists($global_vendor_path)) {
        $vendor_path = $global_vendor_path;
    }
    else {
        $msg = "Unable to load autoload.php. Drush now requires Composer in order to install its dependencies and autoload classes. Please see README.md\n";
        fwrite(STDERR, $msg);
        return FALSE;
    }

But the vendor directory is configurable (see [Composer documentation](https://getcomposer.org/doc/06-config.md#vendor-dir)), and this check fails on otherwise-functioning systems.

**Comment by weitzman** [comment]
The current code [is based on PHPUnit](https://github.com/sebastianbergmann/phpunit/blob/master/phpunit). I'm not sure how other prepackaged apps handle this. Shell out to `composer` to discover the path? Honor an environment variable?

**Comment by weitzman** [comment]
Please reopen if anyone has troubles here and/or a a proposed way forward.
