### ISSUE TITLE
What happened to drush_sql_dump_file()?

### ISSUE THREAD

**Issue by markcarver** [drush-ops/drush#1495]
I understand that the SQL command got a major overhaul, but what is the "equivalent" replacement of this function?

It wasn't deprecated or documented that it was to be removed... it was just removed by https://github.com/drush-ops/drush/commit/c714484880e02b0e4b2a131ee03b118ea7f54d9b#diff-31ada6b624724696f3cbb93fb59fdde8 but without any sort of indication (diff of other code that used it) on how to replace it.

**Comment by weitzman** [comment]
The feature is gone. sql-sync does not keep around transferred dump files any more.
