### ISSUE TITLE
Drush make http://example.com/example.make fails

### ISSUE THREAD

**Issue by helmo** [drush-ops/drush#1497]
The examples mention ` drush make http://example.com/example.make example                               Build the remote example.make makefile in the example directory.             
     `

However you then get:
```
You need to specify an API version of two in your makefile:                                                                        [warning]
api = 2
Beginning to build http://cgit.drupalcode.org/provision/tree/provision-tests/makes/drupal7.make.                                   [ok]
No core project specified.                          
```

It appears that no attempts are made to download the file.

**Comment by ergonlogic** [comment]
You need to specify a plain or raw output git URL. Try: http://cgit.drupalcode.org/provision/plain/provision-tests/makes/drupal7.make

**Comment by helmo** [comment]
Yes, thanks that was it.
