### ISSUE TITLE
Can't upgrade Drush to 7 or 8

### ISSUE THREAD

**Issue by kevinquillen** [drush-ops/drush#1500]
Trying to upgrade from 6.5 to 7 in Homebrew, and I get this error:

```
brew upgrade drush
==> Upgrading 1 outdated package, with result:
homebrew/php/drush 7.0.0
==> Upgrading homebrew/php/drush
drush: Missing PHP53, PHP54, PHP55, PHP56, PHP70 from homebrew-php. Please install one of them before continuing
composer: Missing PHP53, PHP54, PHP55, PHP56, PHP70 from homebrew-php. Please install one of them before continuing
Error: Unsatisified requirements failed this build.
```

I run everything in my VMs (including PHP), so how can I update Drush?

I could just SSH into the box and use Drush that way, but shouldn't you be able to do it remotely without needing different versions of PHP?

When I run php -v in my terminal (non VM):

```
PHP 5.5.14 (cli) (built: Sep  9 2014 19:09:25) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
```

So it would seem like I meet the requirements, no?

**Comment by weitzman** [comment]
This is a homebrew issue, not a Drush issue. 

In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.
