### ISSUE TITLE
Drush make: patch option '--no-backup-if-mismatch' not available on FreeBSD

### ISSUE THREAD

**Issue by henkiejan** [drush-ops/drush#1502]
drush.project.inc,  r. 279:
if ($patched = drush_shell_exec("patch %s --no-backup-if-mismatch -d %s < %s", $patch_level, $project_directory, $filename)) {

Unfortunately FreeBSD's patch has no option  '--no-backup-if-mismatch', and patch will therefore fail

**Comment by drupol** [comment]
Same issue on my FreeBSD workstation.

**Comment by Techwolf12** [comment]
Same here. Also with other drupal related/used things: https://github.com/cweagans/composer-patches/pull/184

**Comment by greg-1-anderson** [comment]
Make is maintenance only; closing.
