### ISSUE TITLE
Drush uses --defaults-extra-file which is overrided by users .my.cnf

### ISSUE THREAD

**Issue by jkolkka** [drush-ops/drush#1505]
Drush uses --defaults-extra-file when connecting to database for storing username&password. If current user has .my.cnf in his/her home folder it will override --defaults-extra-file.

Example:
settings.php found in sites/default
```
$databases = array (
  'default' =>
  array (
    'default' =>
    array (
      'database' => 'dev_base',
      'username' => 'dev_user',
      'password' => 'dev_password',
      'host' => 'localhost',
      'port' => '',
      'driver' => 'mysql',
      'prefix' => '',
    ),
  ),
);
```
~/.my.cnf
```
[client]
user="my_user"
password="my_password"
```

When connecting to MySQL drush will create tmp file with following context:
```
#This file was written by Drush's Sqlmysql.inc.
[client]
user="dev_user"
password="dev_password"
```
And it uses it like:
`mysql --defaults-extra-file=<previously created tmp file> --database=dev_base --host=localhost --silent`

Because .my.cnf overrides --defaults-extra-file previous command will try to connect with user my_user and if my_user doesn't have permissions to access database drush will fail to connect to database.

**Comment by weitzman** [comment]
Honoring my.cnf is by design. If you dont want it, delete that file.

**Comment by minerva-atrix** [comment]
This is not a good enough answer.  Scripts on the server setups I have already use .my.cnf for doing a lot of tasks.  Drupal's database is on another machine.  Drush needs a way to disable this functionality and it's bad it was ever added.  It's been very disruptive see:
https://www.drupal.org/project/drush/issues/2852233
https://github.com/drush-ops/drush/issues/2750
https://github.com/drush-ops/drush/issues/2183
