### ISSUE TITLE
state-set changes the data type

### ISSUE THREAD

**Issue by anavarre** [drush-ops/drush#1507]
```
$ drush @site.env sget system.cron_last
1437683548
$ drush @site.env sqlq "SELECT name,value FROM key_value WHERE name = 'system.cron_last';"
system.cron_last	i:1437683548;
$ drush @site.env sset system.cron_last 1437683550 && drush @site.env sget system.cron_last
"1437683550"
$ drush @site.env sqlq "SELECT name,value FROM key_value WHERE name = 'system.cron_last';"
system.cron_last	s:10:"1437683550";
```

I don't think this is expected so filing an issue to see if there's any way we can preserve the data type.

**Comment by weitzman** [comment]
See --format option on state-set

**Comment by anavarre** [comment]
```
Options:
 --format=<yaml>    Format to parse the object. Use "string" for string (default), and "yaml" for YAML.
```

So, if I understand things correctly we could pass either `--format=yaml` or `--format=string`. But there doesn't seem to be an option to pass `--format=integer` - And even if there was this option, shouldn't it respect the expected data type regardless?

**Comment by weitzman** [comment]
This command may need more work, but the idea is that this works like vset. Looks at 4th example at http://www.drushcommands.com/drush-6x/variable/variable-set

**Comment by weitzman** [comment]
Once this is sorted, we need better Examples docs in state-set and config-set (and maybe vset)

**Comment by weitzman** [comment]
This command doesn't do nearly what it needs to do around data types. Assigning to me. Stand by.

**Comment by anavarre** [comment]
Thanks for the quick fix!

The `--format=integer` parameter works as advertised.

```
$ drush @site.env sget system.cron_last
1437766029
$ drush @site.env sset system.cron_last 1437766039 --format=integer
$ drush @site.env sget system.cron_last
1437766039
$ drush @site.env sqlq "SELECT name,value FROM key_value WHERE name = 'system.cron_last';"
system.cron_last	i:1437762217;
```

On the contrary `--format=auto` doesn't do what it says in the docs: `Use "auto" to detect format from value (default)`

```
$ drush @site.env sset system.cron_last 1437762227 --format=auto
$ drush @site.env sget system.cron_last
"1437762227"
$ drush @site.env sqlq "SELECT name,value FROM key_value WHERE name = 'system.cron_last';"
system.cron_last	s:10:"1437762227";
```

Should I open a new issue for this?

**Comment by anavarre** [comment]
Fantastic, it just works. Thanks again!
