### ISSUE TITLE
Drush on an already existing project

### ISSUE THREAD

**Issue by anabrownee** [drush-ops/drush#1510]
First, I apologise for this question, it'll probably look dead simple to a lot of you, but I am quite new at this and can't seem to figure it out.

I am working on a project that requires that I import a lot of data from a wordpress site. For that I want to you wordpress migrate. This module recommends me to use drush to transfer the data.

After having had quite a lot of problem installing it (thank you windows) I finally managed it. Now I'd like to use drush on one of the project that's in my wamp\www file.

How do I do that? I've been looking but it doesnt look like anyone else had that issue.

I tried the commands from this: https://www.drupal.org/node/1958170
but it says : 
"Command variable-set needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.
Command variable- set requires Drupal core versu=ion 6 or 7 to run."

I am working with drush 7 and I am hoping to use it on a drupal 7-*...

Please help!!!!!

**Comment by weitzman** [comment]
In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.
