### ISSUE TITLE
--search-depth option is confusing when used with --alias-path

### ISSUE THREAD

**Issue by deviantintegral** [drush-ops/drush#1512]
`Control the depth that drush will search for alias files.`

For example, if I run `drush --alias-path=/ --search-depth=1`, I expected drush to not look in any subdirectories for paths. However, search-depth is only used by `_drush_find_local_sites_at_root`, and not when running drush outside of a Drupal directory context.

I'm not sure if this is a docs issue or a bug, but either way it's a problem when drush hangs looking for alias files in a large directory and you can't even pull up drush help.

This comes up as an issue for upgrades from previous versions of drush that didn't recurse looking for aliases. Many developers I work with use something like https://github.com/Lullabot/trusty32-lamp/blob/master/aliases.drushrc.php#L3 to store aliases outside of a drupal site for local installs, which breaks rather horribly on master!

**Comment by greg-1-anderson** [comment]
Drush currently uses `drush_get_option('search-depth', $search_depth) + 1` inside `drush_scan_directory() when looking for alias paths.  I'm not sure that is right (maybe `drush_get_option('search-depth', $search_depth + 1)` was meant?)  You could try --search-depth=0, and see if that works better for you; if it does, perhaps we should fix Drush.  I get the feeling this option has not gotten much use.

I'm not sure I am strongly in favor of supporting the use-case shown above.  Couldn't you at least add '$options['alias-path'][] = $dir . '/drush-aliases';`, or something like that, maybe wrapped inside of an is_dir() test?  That would be much more discriminating, and a better solution than fine-tuning the handling of the --search-depth option, IMHO.

**Comment by deviantintegral** [comment]
Yeah, I came to the same conclusion about a subdirectory and that is working nicely for me.

`--search-depth=0` still hangs drush when using an alias path with a large subtree. I'm not against the current implementation of the recursion - but search-depth still doesn't make sense. Perhaps it should just be removed entirely?

Or, perhaps there just needs to be better promotion of "things that will break in Drush 8" that I missed when switching branches. It's not like this is an API change, but many of our projects will need to have internal docs and example drushrc files updated.

**Comment by weitzman** [comment]
Related: #1537

**Comment by greg-1-anderson** [comment]
Sorry this is confusing; not likely to get better in Drush 8. Drush 9 is much more efficient about alias file searching.
