### ISSUE TITLE
Option for views-dev command to revert changes done to configuration

### ISSUE THREAD

**Issue by rodrigoaguilera** [drush-ops/drush#1517]
My use case is that I'm exporting all site configuration to yaml in d8 and in my development enviroment after I'm finished doing changes I want to export all the config to files disabling all the modules and configuration made for development.

with drush views-dev I can go one way but not the other so the views-dev configuration doesn't get exported with the rest.

**Comment by weitzman** [comment]
You want config to vary by environment. Thats being discussed at #1430
