### ISSUE TITLE
Option to set custom home / cache directory

### ISSUE THREAD

**Issue by danepowell** [drush-ops/drush#1518]
It would be nice to have a runtime option to set the home directory that Drush uses. This is currently hardcoded to `~/.drush`.

Drush is increasingly being pulled in as a Composer dependency and run on CI systems such as Jenkins and TravisCI. In these cases, you want it to be as self-contained as possible, for instance in a `vendor` subdirectory. That way, you can cache the `vendor` directory between builds, and prevent different projects from interfering with each other's configurations. By using `~/.drush` globally, Drush is breaking this compartmentalization.

**Comment by weitzman** [comment]
It actually isn't hard coded. You can set the environment variable HOME=/wherever/you/want and Drush will honor that. So set that in your CI and you'll be good. Our Unish test suite actually does this in order to compartmentalize our own tests - see unish_init() and drush_server_home() functions.
