### ISSUE TITLE
Site installation is not working in Windows 10

### ISSUE THREAD

**Issue by ivanjaros** [drush-ops/drush#1524]
I have the latest drush( via composer) and I am running Windows 10.
When I try to install a new site with drush it just hangs. It will print the initial message about beginning the installation but then nothing.

**Comment by ivanjaros** [comment]
OK, so I have been able to install the site. After the installation is complete I am importing a default set of content(5 entity types, 100 entities with fields, 10 terms) and running cron.

On Windows 7 it toke about 4:15. Now it takes 17:30 minutes. I used the verbose switch and the "Executing: mysql ..." was displayed the most of the time.

**Comment by weitzman** [comment]
Something is wrong in your networking to the mysql server. Try changing from 127.0.0.1 to localhost or vice versa in your settings.php.

**Comment by weitzman** [comment]
or maybe you are using a domain for mysql and that domain is slow for dns lookup.

**Comment by ivanjaros** [comment]
I have used the debug switch and this is what I got:
```
Starting Drupal installation. This takes a while. Consider using the --notify global option.           [ok]
[4.67 sec, 5.49 MB]
Calling install_drupal(Object, Array) [4.68 sec, 5.49 MB]                                           [debug]
Installation complete.  User name: system  User password: system [814.2 sec, 69.01 MB]                 [ok]
Returned from hook drush_core_site_install [814.2 sec, 69.01 MB]                                    [debug]
```
See the seconds!

**Comment by weitzman** [comment]
Not a Drush issue. 

In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.

**Comment by ivanjaros** [comment]
The issue was in xdebug. I have disabled it and all is fine.
