### ISSUE TITLE
Windows 10 - 240 seconds max execution time error in CLI

### ISSUE THREAD

**Issue by ivanjaros** [drush-ops/drush#1525]
For some reason I am getting the maximum execution time error in CLI for 240 seconds on Windows 10 and XAMPP which is really strange. I have this value set to 160 seconds so this makes it that much stranger. I am not setting this variable in any script.

**Comment by weitzman** [comment]
try php.ini. otherwise, dunno. drush does not set this.

**Comment by ivanjaros** [comment]
It looks like every time xdebug is enabled drush takes a significantly longer to perform its tasks.
