### ISSUE TITLE
drush rsync with remote-host but different username does not work

### ISSUE THREAD

**Issue by Schnitzel** [drush-ops/drush#1528]
I've got some situations like that:

Local Server Hostname: backend.zh2.single.amazee.io
Local User: sitename_com_dev
Files folder: /var/www/sitename_com_dev/public_html/sites/default/files
File Permission of files folder: 700

Remote Server Hostname: backend.zh2.single.amazee.io
Remote User: sitename_com_prod
File Permission: 700
Files folder: /var/www/sitename_com_prod/public_html/sites/default/files
File Permission of files folder: 700

The site aliases is setup like that:
```
$aliases["prod"] = array (
  'remote-host' => 'backend.zh2.single.amazee.io',
  'remote-user' => 'sitename_prod',
);
```

Now I'm trying to run an rsync:
```
sitename_com_dev@backend.zh2.single.amazee.io:~/public_html$ drush rsync @prod:%files default:%files
```

But it fails because it tries to run an rsync like that:
```
Calling system(rsync -e 'ssh' -akzv --exclude=".git" --exclude=".gitignore" --exclude=".hg" --exclude=".hgignore" --exclude=".hgrags" --exclude=".bzr" --exclude=".bzrignore" --exclude=".bzrtags" --exclude=".svn" --stats --progress -d /var/www/sitename_com_prod/public_html/sites/default/files/ /var/www/sitename_com_dev/public_html/sites/default/files);
```
The error:
`rsync: change_dir "/var/www/sitename_com_prod/public_html/sites/default/files" failed: Permission denied (13)`

the problems comes from https://github.com/drush-ops/drush/blob/master/includes/sitealias.inc#L1939 which determines that if the remote hostname is the same as the local hostname it assumes that an rsync can be made without a remote hostname in there, which in a case of a different username will fail.

**Comment by jonhattan** [comment]
I think drush_is_local_host() is correct here. This avoids undesired ssh connections when you're using the same alias definition in local and remote (so you want remote-host in local but it is useless in the remote env).

IMO a better fix is to add a condition like `drush_get_username() !=  $site_alias_settings['remote-user']`

**Comment by jonhattan** [comment]
@greg-1-anderson I wonder if the check for username matching should be another condition in the if statement (proposed in #1636), or maybe it should be done in `drush_is_local_host()`.

Also I've found we have `drush_sitealias_is_remote_site()` and several places where we are checking directly if remote-host key is present (for example `drush_sitealias_local_site_path()`). I'm feeling like it needs a refactoring.

**Comment by greg-1-anderson** [comment]
The plan is to get rid of all occurrences of drush_is_local_host, and force people to "local-ize" their alias in an alias alter hook with logic that is appropriate for their specific situation.

**Comment by greg-1-anderson** [comment]
This should be re-evaluated once #1650 is merged.  This might just fix this problem; please provide feedback if it does not.

**Comment by greg-1-anderson** [comment]
Also, regarding the [comments on refactoring](https://github.com/drush-ops/drush/issues/1528#issuecomment-143470090) above, I agree, but hope to take care of this in a more drastic way with [drush-ops/drush-aliases](https://github.com/drush-ops/drush-aliases), so let's focus only on behavior changes for now.

**Comment by weitzman** [comment]
#1650 has been merged. Can we close this issue?

**Comment by Schnitzel** [comment]
yes, closed
