### ISSUE TITLE
drush uli --browser flag not working + hardcode in drushrc.php?

### ISSUE THREAD

**Issue by jessehs** [drush-ops/drush#153]
I use (Mac) Safari as my default browser. However, I use Chrome for a lot of development due to the feature of having multiple user sessions simultaneously.

I'm trying to use the command `drush uli 1234` to launch a login link in the browser. This launches Safari, as expected. I'm trying to launch Chrome, though, which I can't figure out how to do. I've tried every permutation of `drush uli --browser="chrome"`, `drush uli --browser="Google\ Chrome"`, etc. I've even tried `--browser=safari`, `--browser=`Safari.app`, etc., and that prevents Safari from launching. So it seems this flag might be broken for Macs?

The issue is two-part: 
1, How do I figure out how to reference browsers?
2. Can I/how do I hard-code this into my .drushrc file?

I'm running the 7.x-5.x branch

**Comment by paullew** [comment]
To specify the browser in Mac OS X, pass the browser name to "open -a"

For example:
drush uli  --browser="open -a Google\ Chrome"
drush uli  --browser="open -a Safari"
drush uli  --browser="open -a Firefox"

**Comment by pandaPowder** [comment]
Finally! That is great news! Thanks.

**Comment by golddragon007** [comment]
In drush 9+ if you want to block all the browser openings you need a file here: `~/drush/drush.yml` with a content of this:
```
command:
  user:
    login:
      options:
        browser: 0
```

On linux to open with chrome or firefox or anything else:
```
drush uli --browser=firefox
drush uli --browser=google-chrome
```
It needs to be in path or you need to refer to it with full path.
