### ISSUE TITLE
"drush cc block" crashes on drupal 8.0 beta 14  

### ISSUE THREAD

**Issue by torenware** [drush-ops/drush#1531]
Running "drush cc block" (master) causes an exception.  This is likely due to a change in Drupal 8.0.x; I think that the block cache no longer exists in current builds:

<pre>
drush cc block
exception 'Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException' with message 'You have requested a non-existent service       [error]
"cache.block".' in /var/www/drupal/core/vendor/symfony/dependency-injection/Container.php:318
Stack trace:
#0 /var/www/drupal/core/lib/Drupal.php(282): Symfony\Component\DependencyInjection\Container->get('cache.block')
#1 /usr/local/share/drush/commands/core/drupal/cache_8.inc(79): Drupal::cache('block')
#2 /usr/local/share/drush/includes/drush.inc(718): drush_cache_clear_block()
#3 /usr/local/share/drush/includes/drush.inc(705): drush_call_user_func_array('drush_cache_cle...', Array)
#4 /usr/local/share/drush/commands/core/cache.drush.inc(143): drush_op('drush_cache_cle...')
#5 [internal function]: drush_cache_command_clear('block')
#6 /usr/local/share/drush/includes/command.inc(359): call_user_func_array('drush_cache_com...', Array)
#7 /usr/local/share/drush/includes/command.inc(210): _drush_invoke_hooks(Array, Array)
#8 [internal function]: drush_command('block')
#9 /usr/local/share/drush/includes/command.inc(178): call_user_func_array('drush_command', Array)
#10 /usr/local/share/drush/lib/Drush/Boot/BaseBoot.php(62): drush_dispatch(Array)
#11 /usr/local/share/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#12 /usr/local/share/drush/drush.php(11): drush_main()
#13 {main}
</pre>

As near as I can tell, the error message is correct; there in fact *is no* cache.block service.  So drush should probably not try to clear it.

**Comment by weitzman** [comment]
Fixed in c4b888362b7f202fa77f53670286561129d68d45
