### ISSUE TITLE
Unable to load autoload.php

### ISSUE THREAD

**Issue by jenlampton** [drush-ops/drush#1538]
I've installed three versions drush 7, and all three new versions throw the following error message:

`Unable to load autoload.php. Drush now requires Composer in order to install its dependencies and autoload classes. Please see README.md`

I've consulted the README.md file as instructed, but there is no information there as to why autolpad.php may be required but is not found, and what I might need to do if I encounter this error. (And yes, Composer is installed on my machine).

I'll comment back here if I am able to resolve the problem with some suggested updates to the error message in Drush (or the README.md file) but if anyone has any instructions as to where I should actually be looking for a solution to that problem, I'd appreciate some help :)

**Comment by weitzman** [comment]
Unlike old Drush, you now have to install via the composer tool. If you did a git clone of Drush, your next step is to run `composer install`. See docs.drush.org/en/master/install/. Ping me if you get stuck.

**Comment by jenlampton** [comment]
Thanks! I finally got it installed :)

**Comment by shrop** [comment]
In case anyone runs into this, I had this issue after installing drush like this:

`$ COMPOSER_HOME=/opt/drush COMPOSER_BIN_DIR=/usr/local/bin COMPOSER_VENDOR_DIR=/opt/drush/7 composer require drush/drush:7.*`

I had to `$ cd /opt/drush/7/drush/drush` and then run `$ composer update`.

Not sure why, but that removed the message: "Unable to load autoload.php. Drush now requires Composer in order to install its dependencies and autoload classes. Please see README.md"

**Comment by kosli** [comment]
thanks @shrop, this also solved it for me. (site-wide installation, as root it worked, but not for the specific vhost user)

**Comment by nehajyoti04** [comment]
I get this  on vagrant provision

TASK [geerlingguy.drush : Run drush to finish setting it up.] ******************
fatal: [my_site]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush"], "delta": "0:00:00.065354", "end": "2016-11-15 16:57:34.534011", "failed": true, "rc": 1, "start": "2016-11-15 16:57:34.468657", "stderr": "Unable to load autoload.php. Run composer install to fetch dependencies and write this file (http://docs.drush.org/en/master/install-alternative/). Or if you prefer, use the drush.phar which already has dependencies included (http://docs.drush.org/en/master/install).", "stdout": "", "stdout_lines": [], "warnings": []}

Please help!!

**Comment by niteshsyngenta11** [comment]
**sudo ansible-galaxy install -r provisioning/requirements.yml --force** will fix up the issue of Unable to load autoload.php.

**Comment by wturrell** [comment]
Several people using ansible by the looks of it.  Here's how I got it working for a Drupal 7 migration, installing on Debian 9, using the [geerlingguy.drush](https://galaxy.ansible.com/geerlingguy/drush/) role: 

Playbook:

Variables:
```
drush_install_from_source: yes
drush_source_install_version: "7.x"
drush_composer_update: yes

```
Note by default composer runs in `/usr/local/share/drush`, if you screw things up you might need to wipe that directory.

**Comment by josuevalrob** [comment]
What about Drupal 8?

**Comment by greg-1-anderson** [comment]
Drush 7 is end-of-life, and should be avoided.

- For Drupal 7, you should use Drush 8.
- For Drupal 8, you should use Drush 9.

If you are building your Drupal site with Composer, then a site-local Drush is recommended. (`cd` to your Drupal project directory and use `composer require` to install Drush.)

Global installs of Drush 8 and Drush 9 still works, but is not recommended. Drush 8 with Drupal 8 still works, but is not recommended. You must use Drush 8 with Drupal 8 if you are using `pm-update` / `pm-download`, as these commands do not exist in Drush 9. Switching to Composer-managed sites is recommended.
