### ISSUE TITLE
How to install drush on an offline environment?

### ISSUE THREAD

**Issue by hanoii** [drush-ops/drush#1540]
I am trying to figure out the best way, if at all possible, to install drush on a server which its outbound internet connection is filtered. I could manage to install composer offline, but then each module that it tries to download will fail.

Is there a recommended/documented way of doing, any feasable workaround?

Thanks,
Ariel.=

**Comment by DuaelFr** [comment]
I suppose you could install drush using composer on a connected environment then copy the entire .composer directory to the offline env and set it's PATH properly.

**Comment by greg-1-anderson** [comment]
Please use [Drupal Answers](http://drupal.stackexchange.com/questions/tagged/drush) for support requests.
