### ISSUE TITLE
Drush fails to install correctly

### ISSUE THREAD

**Issue by TMWagner** [drush-ops/drush#1545]
I've referenced several different documentation sources for installing Drush on my new Macbook. The most complete, step-by-step I found is located at https://drupalize.me/videos/installing-drush-composer?p=1156

Regardless what I do, I am blocked by a mysterious message:
*env: sh\r: No such file or directory*

This would suggest that some script is being read with Windows type garbage inserted at line end. 
1. I didn't use Windows
2. I didn't create any scripts. 

Where is this coming from and why is it so hard to install Drush now?  Over the years, I've installed many times, and never had this grief!

**Comment by danepowell** [comment]
Could this be related to #418

**Comment by weitzman** [comment]
In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.

**Comment by TMWagner** [comment]
Actually, this IS Github, is it not?  According to my browser window it is
![image](https://cloud.githubusercontent.com/assets/5316689/9505653/7eb771c8-4bf8-11e5-917f-b522c09bf98d.png)
