### ISSUE TITLE
Drush 7 no longer correctly searches top-level drupal/drush directory contents

### ISSUE THREAD

**Issue by apotek** [drush-ops/drush#1546]
A bug was introduced in going from version 6 to 7 of drush. Drush 6 used to support having drush commands and alias files and configuration in a sibling directory to the docroot directory, ie drupal/drush.

In moving from 6 to 7, a commit removed an essential slash from the search path setup during drush  bootstrap.

The following two pull requests (one for master, one for 7.x) fixes this.

https://github.com/drush-ops/drush/pull/1542 (merged to master)
https://github.com/drush-ops/drush/pull/1541 (not yet merged to 7.x)

**Comment by kwidholm-tm** [comment]
~~#1541 (not yet merged to 7.x)~~

Looks like we can close this issue.

**Comment by apotek** [comment]
~~#1541 (not yet merged to 7.x)~~

Looks like we can close this issue.
