### ISSUE TITLE
Remote host shows wrong drush version

### ISSUE THREAD

**Issue by patkai** [drush-ops/drush#1548]
Both my local and the remote server have drush 7.0, drush --version shows them correctly. But when I set up an alias and run from local ```drush @my_alias status``` I get the error message:

```Drush 6.7-dev does not support Drupal 8. See http://drupal.org/project/drush for more information```

**Comment by weitzman** [comment]
Please post the full output of that command. Also post the output of `drush sa @my_alias`

**Comment by patkai** [comment]
OK, thanks! 

On local (MacOSX):
```drush --version```

```Drush Version   :  7.0-dev```

Also on remote (Linux) the same version info:
````
drush status
 PHP executable         :  /usr/bin/php                                 
 PHP configuration      :  /etc/php5/cli/php.ini                        
 PHP OS                 :  Linux                                        
 Drush script           :  /root/.composer/vendor/drush/drush/drush.php 
 Drush version          :  7.0-dev                                      
 Drush temp directory   :  /tmp                                         
 Drush configuration    :                                               
 Drush alias files      :
```

Again on local:
```
drush sa @stagi
$aliases["stagi"] = array (
  'remote-user' => 'root',
  'remote-host' => 'abc.xyz.fi',
  'uri' => 'abc.xyz.fi',
  'root' => '/var/www/d8/current',
);
```

```
drush @stagi status
Drush 6.7-dev does not support Drupal 8. See http://drupal.org/project/drush for more information. [error]
```

I don't recall to have or see any other version of drush.

**Comment by weitzman** [comment]
Not sure why it mentions 6.7-dev, but the message is otherwise correct. You can't run Drush7 on Drupal 8 sites. You need to use Drush8, which is in beta. Use ,aster branch or a beta release. You need drush8 on both sides.
