### ISSUE TITLE
Drush Migrations

### ISSUE THREAD

**Issue by hollyfox** [drush-ops/drush#1549]
I bench-marked numerous migrations between the UI and drush 6.0 and drush consistently was about twice the length of time to complete the migrations. Additionally, once drush echoes the completion feedback, it does not release the cli for quite a while afterwards. Looking at Workbench to determine what is going on reveals that it is doing a statistics query after the migration that takes considerable time. I am not sure why it processes the node slower though.

For now, I am going back to the ui.

**Comment by weitzman** [comment]
Not a Drush issue. One does xhprof in order to find slowdowns in your site or toolchain.

**Comment by hollyfox** [comment]
Same site, different migrate engines.
