### ISSUE TITLE
Duplicate drush_log when no Drupal site found.

### ISSUE THREAD

**Issue by jenlampton** [drush-ops/drush#1550]
When trying to clear the cache and no Drupal site is found, multiple drush_log messages are printed.  The first is correct:
`No Drupal site found, only 'drush' cache was cleared.`
The second is incorrect:
`'all' cache was cleared.`

I think this problem can easily be solved with an else statement. Thought this might be a good issue to learn how to contribute :)

**Comment by jonhattan** [comment]
Fixed in #1551

@jenlampton you can add "Fixes #1550" or similar to a commit message in the PR, so github automatically closes this issue. See https://help.github.com/articles/closing-issues-via-commit-messages/
