### ISSUE TITLE
Cannot install site, AccountInterface not found

### ISSUE THREAD

**Issue by ivanjaros** [drush-ops/drush#1552]
I am trying to set up a virtual machine for development and I am getting fatal error when I run site installation:

PHP Fatal error:  Class 'Drupal\Core\Session\AccountInterface' not found in /var/www/html/core/includes/bootstrap.inc on line 64
Drush command terminated abnormally due to an unrecoverable error.                              [error]
Error: Class 'Drupal\Core\Session\AccountInterface' not found in
/var/www/html/core/includes/bootstrap.inc, line 64

The machine is Ubuntu Server 14.04 32bit with Apache2 and PHP 5.6.11 and Drupal 8b14.

**Comment by dwaghmare** [comment]
Hi @ivanjaros 
I'm using Drupal 8 beta 12 with Drush 6
If I do 
``
drush status
``
out side of drupal 8 docroot it gives status about drush
but if I do that in docroot of  drupal8 it simply gives an below error.
Fatal error: Class 'Drupal\Core\Session\AccountInterface' not found

I have installed latest drush using composer on windows system. 
Not sure if I'm missing something.

**Comment by dwaghmare** [comment]
Ok got ride of it..
best way is 
Try doing 
``
  composer self-update
``
inside your drush folder

If it wont help try
``
  composer global require drush/drush:7.*
`` 
Then do
``
  composer install
``

**Comment by ivanjaros** [comment]
Will try. I used the apt package for drush.

**Comment by jonhattan** [comment]
Use Drush 8 for Drupal 8. Stated in the install instructions.
