### ISSUE TITLE
drush make --lock= (make-generate) strips core from version of core downloads.

### ISSUE THREAD

**Issue by eeisenhart** [drush-ops/drush#1553]
Using drush 7,  with a makefile like this:

    api = 2
    core = 7.x
    projects[panopoly][type] = core

Running `drush make --no-build test.make --lock=test-lock.make` results in an output file with `projects[panopoly][version] = "1.25"`.

But attempting to build with that will result in a "Could not locate panopoly version 1.25" error.

Manually editing the generated lock makefile so that version is "7.x-1.25" fixes the problem.

If I put `projects[panopoly][version] = "7.x-1.25"` in the original test.make makefile, it still sets version=1.25 in the output makefile.

**Comment by ergonlogic** [comment]
I think `projects[panopoly][version] = "1.25"` should be valid in a makefile, since specifying `core = 7.x` is required anyway. So I don't think the problem is with the `make-generate` code that the `--lock` calls.

**Comment by ergonlogic** [comment]
I've tracked this down to `make_prepare_request()`, where we find the following line:

    $request['version'] = $type == 'core' ? $project['version'] : $project['core'] . '-' . $project['version'];

Here we're making an assumption that `projects[...][type] = 'core'` is going to be Drupal core, Pressflow, or some other straight drop-in, rather than a distribution.

**Comment by ergonlogic** [comment]
This is essentially a chicken and egg problem. We need to know the project type ('project_core' or 'project_distribution') before making the request that'll provide this info.

Two obvious approaches present themselves:

(1) Add a `distribution` project type that Drush Make will recognize as a `core`; or
(2) Pull down the project XML, and check the `project_type` when `projects[...][type] = 'core'`.

I'm leaning towards (2), since only a very local change is required. Since we have (at most) one core per makefile, the additional overhead here would be minimal.

To do (1) properly, we'd probably have to figure out how to get make-generate to recognize that a site was built on a distribution.

**Comment by ergonlogic** [comment]
@jhedstrom & @weitzman I can bang out (2) in a half-hour. However (1) is probably the "right" way to fix this. Suggestions?

**Comment by jhedstrom** [comment]
@ergonlogic the approach in 2 sounds reasonable for the time being if it fixes the immediate problem. We can always do a follow-up if adding `distribution` has additional benefits.

**Comment by jonhattan** [comment]
@ergonlogic the problem is at `make_generate_from_makefile()` rather than `make_prepare_request()`. See https://github.com/drush-ops/drush/blob/master/commands/make/generate.contents.make.inc#L101

**Comment by jonhattan** [comment]
AFAICS lines 101-103 are unneccesary: `$project['download']['full_version']` always contains the proper version string for Drupal core (7.38) or a distro (7.x-y.z).

**Comment by ergonlogic** [comment]
Those lines strip the core version off of all projects, for readability. Otherwise *all* projects' versions will have the core prefix.

That said, the simplest fix would probably be to skip projects of type 'core' here.

**Comment by ergonlogic** [comment]
While I still think a 'bare' version should be valid for distributions, I think that should probably be part of a more comprehensive addition of 'distribution' as a project type.

As such, I went with the simplest solution that resolves this issue. Assuming tests pass, I'd like to back-port this to Drush 7.x and 6.x. Unless there are objections.

**Comment by ergonlogic** [comment]
Since [tests passed](https://travis-ci.org/drush-ops/drush/builds/75985008), I'm going to back-port this trivial patch to 6.x and 7.x.

**Comment by ergonlogic** [comment]
Cherry-picked into 7.x. The '--lock' functionality doesn't exist in Drush 6.x.
