### ISSUE TITLE
Can't Install Drush because of psy/psysh

### ISSUE THREAD

**Issue by ajankowski** [drush-ops/drush#1554]
It looks like Boris has been replaced with PsySH in [75306527](https://travis-ci.org/drush-ops/drush/builds/75306527).

Now if I try to install I get the following output:

Alberts-MacBook-Pro:d8 albertski$ composer global require drush/drush:dev-master
Changed current directory to /Users/albertski/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for drush/drush dev-master -> satisfiable by drush/drush[dev-master].
    - Conclusion: remove symfony/var-dumper v2.6.3
    - Conclusion: don't install symfony/var-dumper v2.6.3
    - drush/drush dev-master requires psy/psysh ~0.5 -> satisfiable by psy/psysh[v0.5.0, v0.5.1, v0.5.2].
    - psy/psysh v0.5.0 requires symfony/var-dumper ~2.7|~3.0 -> satisfiable by symfony/var-dumper[v2.7.0, v2.7.1, v2.7.2, v2.7.3].
    - psy/psysh v0.5.1 requires symfony/var-dumper ~2.7|~3.0 -> satisfiable by symfony/var-dumper[v2.7.0, v2.7.1, v2.7.2, v2.7.3].
    - psy/psysh v0.5.2 requires symfony/var-dumper ~2.7|~3.0 -> satisfiable by symfony/var-dumper[v2.7.0, v2.7.1, v2.7.2, v2.7.3].
    - Can only install one of: symfony/var-dumper[v2.7.0, v2.6.3].
    - Can only install one of: symfony/var-dumper[v2.7.1, v2.6.3].
    - Can only install one of: symfony/var-dumper[v2.7.2, v2.6.3].
    - Can only install one of: symfony/var-dumper[v2.7.3, v2.6.3].
    - Installation request for symfony/var-dumper == 2.6.3.0 -> satisfiable by symfony/var-dumper[v2.6.3].

**Comment by weitzman** [comment]
Works for me, without the 'global' part. Maybe it conflicts with something else you have installed globally.

**Comment by ajankowski** [comment]
Sorry you are correct. Turns out even though symfony/var-dumper wasn't in my composer.json file, it was in my composer.lock file.

I just renamed the my lock file to composer.lock.old (just in case I need to refer to it in the future) and it worked.

**Comment by geerlingguy** [comment]
I've been hitting this from time to time as well, no clue why, but on first install (with command `composer install --prefer-source --no-interaction`), psy is not installed. Then if I run it again, I get:

```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing psy/psysh (v0.5.2)
    Downloading: 100%         

    Skipped installation of bin bin/psysh for package psy/psysh: name conflicts with an existing file
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
Generating autoload files
```

And then Drush works correctly.

**Comment by geerlingguy** [comment]
Hit this again today, randomly. Same thing as above fixed it. The weird thing was, I was provisioning a set of 8 webservers, and 7 worked, one did not. Identical base box and configuration. Must be a ghost in the wires.
