### ISSUE TITLE
Batch API: Divergence from Drupal (7, at least)

### ISSUE THREAD

**Issue by adam-vessey** [drush-ops/drush#1559]
[Drush's batch implementation has a check for memory](https://github.com/drush-ops/drush/blob/982e79684c23bd13737f9383c2701f5b3b13c9c2/commands/core/drupal/batch.inc#L180-L186), while [Drupal has a check for time](http://cgit.drupalcode.org/drupal/tree/includes/batch.inc?h=7.x#n314).

This discrepancy can lead to issues in code expecting to be in a new PHP instance. For example: Using `timer_start()`/`timer_read()` (which use global vars) and so on in a batch operation which takes multiple iterations to complete, expecting to have the timer reset between iterations.

My first instinct is that the default should be based on the time in order to keep the same assumptions, but to make an option to have the memory check taken into effect (instead?), to allow whatever particular batches to save on the bootstrapping overhead.

**Comment by jonhattan** [comment]
php cli has no time limit constraints, this is why we check for memory instead of time.

OTOH, Drupal doesn't perform a page request for each iteration. It will try to perform as much iterations as possible within the same page request.

So, AFAICS, the the only difference is that drush will run more iterations within the same process than the web-based drupal equivalent.

**Comment by adam-vessey** [comment]
> OTOH, Drupal doesn't perform a page request for each iteration. It will try to perform as much iterations as possible within the same page request.

As many iterations within its one second, yes, before the new request... Note that it's one second, not near the default PHP `max_execution_time` of 30, which might be expected if it were due to constraints. (UI responsiveness maybe? dunno)

If one writes a batch operation which tries to do more per iteration (say querying for a chunk of records and transforming as many as possible in some fraction of `max_execution_time`) and uses timers (which happen to use global variables) to control the iteration of their batch operation, one gets into a heap of trouble... Changing from time to memory means any other cases when an operation may be using time to control execution would similarly have to be made to base their decision on memory.

IMHO, the processing of "progressive" batches shouldn't be concerned with resource constraints--they're explicitly meant to iterate more frequently, based on the web code. I could see possibly forcing non-progressive batches (which seem to be intended to run all-at-once) to iterate when they near constraints, but that would likely violate other assumptions which are made about them.

**Comment by jonhattan** [comment]
Sorry It is likely that we won't change our implementation. It is advantageous in most of the cases.

Perhaps you can add a check to not use those timers if running from drush, you may use `function_exists('drush_main')` for that. Other option could be to give unique names to the timers based on $context.

/me invokes @weitzman

**Comment by weitzman** [comment]
Agreed.
