### ISSUE TITLE
drush make --gitsubmodule support

### ISSUE THREAD

**Issue by mfrieling** [drush-ops/drush#1569]
`drush dl` has the option `--gitsubmodule` to register the downloaded module as git submodule.

It would be a good feature to have this option as well in `drush make`, but there it should be configurable:

``` bash
# Register all git based modules as submodules to the root level repository,
# e. g. the profile
drush make --gitsubmodule distro.make.yml

# Register only those git based modules as submodules which are cloned
# from the Drupal Git server
drush make --gitsubmodule=drupal distro.make.yml

# Register only those git based modules as submodules which are cloned
# from gitlab.com
drush make --gitsubmodule=gitlab.com distro.make.yml

# Register only those git based modules as submodules which are cloned
# from the Drupal Git server, github.com and your own/companies Git server
drush make --gitsubmodule=drupal,github.com,git.mydomain.com distro.make.yml
```

Basically it's the exact hostname of teh Git server or the keyword `drupal` for git.drupal.org.

A second option could be `--gitinit` to init a new Git repository at the Drupal root, making the cloned profle repository a Git submodule as well. This could run directly after downloading and eventually patching Drupal core:

``` bash
git init
git add --all
git commit -m "Drupal {version} site created"
```

**Comment by greg-1-anderson** [comment]
Make is maintenance only; closing.
