### ISSUE TITLE
Show informative messages for config-import

### ISSUE THREAD

**Issue by karmazzin** [drush-ops/drush#1570]
Related with this #807. I would like to raise the issue.
> That message comes from a drupal_set_message() \Drupal\config\Form\ConfigSync::buildForm which is a really odd place to do validation. I think this needs fixing in drupal.

Exception is thrown from `ConfigImporter::validate`, no `ConfigSync::buildForm`. But for show informative messages we need get error messages from `ConfigImporter::getErrors`

**Comment by karmazzin** [comment]
Before 
![image](https://cloud.githubusercontent.com/assets/2082480/9485614/b9ca0bb0-4bc4-11e5-8d25-44d951ca00ea.png)

After 
![image](https://cloud.githubusercontent.com/assets/2082480/9485616/ca418748-4bc4-11e5-9862-50dd6e161047.png)

**Comment by weitzman** [comment]
Fixed
