### ISSUE TITLE
PHP7 - Uninstalling module results in TypeError

### ISSUE THREAD

**Issue by joshuataylor** [drush-ops/drush#1578]
Using PHP7, uninstall a module, which results in:

```
TypeError: Argument 1 passed to Drush\Log\DrushLog::__construct() must implement interface Drupal\Core\Logger\LogMessageParserInterface, none given, called in /home/josh/.composer/vendor/drush/drush/commands/core/drupal/environment.inc on line 227 in Drush\Log\DrushLog->__construct() (line 35 of /home/josh/.composer/vendor/drush/drush/lib/Drush/Log/DrushLog.php).
```

**Comment by davereid** [comment]
Confirmed started seeing this failure on all our PHP 7 Travis module test runs.

**Comment by jonhattan** [comment]
I guess this is due to this change I did recently: 670decb0e38670e51dd61a01631188d27e9c5bb4

It seems the failure is not only on pm-uninstall. In @davereid's case, it fails also when enabling a module (simpletest) https://travis-ci.org/drupal-media/crop/jobs/77858247#L221
