### ISSUE TITLE
Provide config-export ability from remote sites

### ISSUE THREAD

**Issue by mrf** [drush-ops/drush#1580]
I found myself this morning really wanting to get the latest config from a staging site down to my local machine without using the UI.

Before I start on this, would this be a feature that Drush would be interested in having? Any tips / ideas on what an implementation would look like here?

**Comment by weitzman** [comment]
untested,  but might just work: `drush @example config-export && drush rsync @example:%config-staging @self:%config-staging`

**Comment by weitzman** [comment]
FYI, we added config-pull command that implements the above suggestion.
