### ISSUE TITLE
env: drush8: No such file or directory

### ISSUE THREAD

**Issue by cjokinen** [drush-ops/drush#1591]
I have a new install of Linux and Drush and I get the error noted in the subject right after this line when running -vd

Calling proc_open(ssh -o PasswordAuthentication=no [site]@staging-5808.prod.hosting.acquia.com 'env COLUMNS=173 drush8  --verbose --debug --root=/var/www/html/[site]/docroot --uri=[site].prod.acquia-sites.com  core-status 2>&1' 2>&1);

I can run drush status locally without issue....ideas?

**Comment by weitzman** [comment]
you are trying to run a program called `drush8` which is not found. if you are on acquia cloud, that is a known issue.

**Comment by cjokinen** [comment]
No, but my alias file has this in it

if (!isset($drush_major_version)) {
  $drush_version_components = explode('.', DRUSH_VERSION);
  $drush_major_version = $drush_version_components[0];
}


So I guess this is what may be requesting that.

**Comment by cjokinen** [comment]
yes did a test and set the variable 

$drush_major_version = ''; 

which sets it and skips that code. It now runs correctly.
