### ISSUE TITLE
PHP Fatal error:  Class 'Drupal\Core\ContentNegotiation' not found

### ISSUE THREAD

**Issue by huijing** [drush-ops/drush#1597]
The error occurred when I ran `drush pm-update` on Drupal 8 Beta 14 to upgrade to Beta 15. The terminal output is as follows. This issue does not appear to have any significant implications from a functionality perspective. Drush version used is 8.0-dev.

    Project drupal was updated successfully. Installed version is now 8.0.0-beta15.
    Backups were saved into the directory                                [ok]
    /Users/huijing/drush-backups/drupal8/20150906061232/drupal.
    The following updates are pending:

    system module :
      8002 -   Removes the system.filter configuration.
      8003 -   Change the index on the {router} table.
      8004 -   Add a (id, default_langcode, langcode) composite index to entities.
      8005 -   Place local actions and tasks blocks in every theme.

    block_content module :
      8001 -   Add 'revision_translation_affected' field to 'block_content' entities.

    node module :
      8001 -   Add 'revision_translation_affected' field to 'node' entities.
      8002 -   Remove obsolete indexes from the node schema.
      8003 -   Promote 'status' and 'uid' fields to entity keys.

    views module :
      8001 -   Update views field plugins.

    Do you wish to run all pending updates? (y/n): y
    Performing system_update_8002                                        [ok]
    Performing node_update_8001                                          [ok]
    Performing system_update_8003                                        [ok]
    Performing system_update_8004                                        [ok]
    Performing node_update_8002                                          [ok]
    Performing views_update_8001                                         [ok]
    Performing node_update_8003                                          [ok]
    Performing block_content_update_8001                                 [ok]
    Performing system_update_8005                                        [ok]
    Cache rebuild complete.                                              [ok]
    Finished performing updates.                                         [ok]
    PHP Fatal error:  Class 'Drupal\Core\ContentNegotiation' not found in /Users/huijing/Sites/drupal8.dev/sites/default/files/php/service_container/service_container_prod_ea32c1db/23f1dc7affe14d8f38dc8fa6237453e184f2f1d6dcf062466ca1fc6f60ff10e6.php on line 4257

    Fatal error: Class 'Drupal\Core\ContentNegotiation' not found in /Users/huijing/Sites/drupal8.dev/sites/default/files/php/service_container/service_container_prod_ea32c1db/23f1dc7affe14d8f38dc8fa6237453e184f2f1d6dcf062466ca1fc6f60ff10e6.php on line 4257
    Drush command terminated abnormally due to an unrecoverable error.   [error]
    Error: Class 'Drupal\Core\ContentNegotiation' not found in
    /Users/huijing/Sites/drupal8.dev/sites/default/files/php/service_container/service_container_prod_ea32c1db/23f1dc7affe14d8f38dc8fa6237453e184f2f1d6dcf062466ca1fc6f60ff10e6.php,
    line 4257

**Comment by jonhattan** [comment]
This seems a spurious error, due to [Remove ContentNegotiation and embed functionality in the middleware](https://www.drupal.org/node/2506533). The `http_negotiation.format_negotiator` service has been removed and the service container needs to be recompiled. I don't understand why the cache rebuild didn't do it though.

**Comment by sebastianwestberg** [comment]
Same thing happened to me. No visible errors on the site though, everything seems to work.

**Comment by jalama** [comment]
+1 on getting the error updating beta14 -> beta15, I'm working on the CLI side on automation stuff so using sqlite.

`git status` and `drush st`, indicating the update happened as expected:

 Drupal version                  :  8.0.0-beta15                                                                                                  
 Site URI                        :  127.0.0.1:8888                                                                                                
 Database driver                 :  sqlite                                                                                                        
 Database name                   :  Users/<user>/.drupdates/builds/drupal/drupal.sqlite                                                         
 Drupal bootstrap                :  Successful                                                                                                    
 Drupal user                     :  Anonymous                                                                                                     
 Default theme                   :  stark                                                                                                         
 Administration theme            :  seven                                                                                                         
 PHP executable                  :  /usr/bin/php                                                                                                  
 PHP configuration               :                                                                                                                
 PHP OS                          :  Darwin                                                                                                        
 Drush script                    :  /Users/<user>/.composer/vendor/drush/drush/drush.php                                                        
 Drush version                   :  8.0-dev                                                                                                       
 Drush temp directory            :  /tmp                                                                                                          
 Drush configuration             :  /Users/<user>/.drupdates/builds/drupal/drush/drushrc.php                                                    
 Drush alias files               :  /Users/<user>/.drush/pantheon.aliases.drushrc.php /Users/<user>/.drush/test.aliases.drushrc.php           
 Install profile                 :  minimal                                                                                                       
 Drupal root                     :  /Users/jdtaylor/.drupdates/builds/drupal                                                                      
 Site path                       :  sites/default                                                                                                 
 File directory path             :  sites/default/files                                                                                           
 Temporary file directory path   :  /tmp                                                                                                          
 Staging config path             :  sites/default/files/config_DPibyttQ9YXkz3hemrPD_X8mLXCpsNeHTQ4aom5MpRZGyEieJV73POTsOq6YE4yeXuZyqIjpTQ/staging

**Comment by christianmgrupp** [comment]
The error is also occurring going from beta 13 to beta 15. The site generally seems to be working otherwise.

**Comment by AndyLicht** [comment]
I get the same error, after that i can not create views, contenttypes or content.
I'm using postgres.

**Comment by weitzman** [comment]
Not a Drush issue. These are the troubles one has to fix (sometimes by hand) when adopting a Drupal 8 beta. We have no resources to support it here.
