### ISSUE TITLE
Drush can select a NAME.drush.inc which isn't part of a NAME module

### ISSUE THREAD

**Issue by phil-s** [drush-ops/drush#1598]
My particular use-case is an ugly "historical reasons" situation, but it would be nice if Drush handled it.

If you have a module `FOO` which contains a file `FOO.drush.inc`, and you also have *another* file named `FOO.drush.inc` elsewhere in the searchable paths, then Drush *may or may not* select the file inside the `FOO` module when determining which `drush FOO*` commands are available.

It would seem like a good idea if Drush reliably picked a path which was a child of that module's path, whenever that was an option?

**Comment by greg-1-anderson** [comment]
Yeah, I agree with you.  The reason this is hard is that some of the common "other locations" (e.g. all the global locations) are searched before Drush even knows where the module paths are.  In fact, Drush loads some of these before it even knows if its going to bootstrap far enough for there to be modules.

Any ideas on how to resolve this problem would be welcome.

**Comment by phil-s** [comment]
I would imagine that if Drush remembers an array of potential include file paths for each module (rather than clobbering a single value each time it sees a match), then the decision for any given module can at least be deferred as long as possible.

> Drush loads some of these before it even knows if its going to bootstrap far enough for there to be modules

That's certainly a tricky one. My initial thought is that conflicts here should either be an error, or else cause all such files to be loaded. Notifying the user would seem sensible in either case (with perhaps some command line option(s) to facilitate user choice).

Once Drush knows which modules are enabled, and where they live, presumably we could filter the remaining unprocessed arrays appropriately. (Or again, potentially load all the files unless instructed otherwise?)

**Comment by greg-1-anderson** [comment]
Drush loads commandfiles early, in case they have hooks that affect the bootstrap.

Maybe we need two kinds of commandfiles.

**Comment by phil-s** [comment]
(following up my previous comment)

I've realised that "load them all" wouldn't be a sane default option, as the more likely scenario is probably that conflicting filenames have similar/identical contents.

Offhand it seems sensible to require the user to configure the behaviour in these situations. Some kind of conf file syntax to tell Drush what to do with any conflicts -- whenever conflicting filenames are seen, it would consult the config to see what to do with each file.

The config could then be an array of (only) those files, keyed by file paths, with the value indicating what to do for each one: 'ignore', or 'load'.

If the appropriate config didn't exist, Drush could prompt the user to create it as and when required.

**Comment by greg-1-anderson** [comment]
Drush presumes that any two commandfiles with the same name do in fact contain the same content, and will only load one of them.  Currently, though, it's first-one-wins; we would prefer to have it be best-one-wins, but our problem is that we want to load them as soon as we see them in case we need something inside.

**Comment by phil-s** [comment]
If we need to load a file before Drush is capable of knowing which one is best, I don't see any option other than requiring the user to configure the behaviour? Any "best guess" approach runs the risk of Drush silently getting it wrong (and perhaps inconsistently so -- in my case sometimes a command worked, and sometimes it didn't, because which of the two files was loaded was variable).

**Comment by greg-1-anderson** [comment]
We don't need to load a file to know it's best; I think that Drush should always favor the commandfile in the module directory in the case of duplicates.  I don't know that we need to solve this problem, though, because --local mode with #1595 provides an unambiguous answer to your question.  Of course, the downside here is that --local solves the problem by disabling all global commandfile locations, but you can always add some of them back in with a site-specific drushrc.php file.  So, I don't think anyone is going to spend effort on fixing the bootstrap to make it easier to mix global and local commandfiles, since we are moving away from that model.
