### ISSUE TITLE
List unused modules' directories

### ISSUE THREAD

**Issue by OnkelTem** [drush-ops/drush#1599]
## Drush list-unused command

Let me share a new utility command `list-unused` which lists directories of unused modules: 
https://github.com/OnkelTem/drush-list-unused

**Warning: while this software is itself safe, it is untested and may produce incorrect results, so please use it with caution, double check before trying any real file operations.**

## Usage

**List directories**
```
drush list-unused
```
sample output:
```
...
sites/all/modules/git_deploy
sites/all/modules/gmap
sites/all/modules/gridbuilder
sites/all/modules/hacked
sites/all/modules/hierarchical_select
sites/all/modules/i18n
sites/all/modules/imce
...
```
**Delete directories**
In theory it can be done like so:
```
drush list-unused | while IFS= read -r line; do rm -rf "$line"; done
```
But I myself haven't tried it and can't think why you may need this. Instead use the output to feed your deployment system. For example I use it to create exclude list for ```rsync``` when deploying a website. 

## Motivation

When you finish developing a website, you may end up with tens of disabled/never installed modules under ```sites/*/modules``` which you probably don't want to keep for production usage. It would be nice to have a ```drush``` command to just delete those modules or at least to enumerate their directories. Unfortunately out of the box ```drush``` can only help you in figuring out the disabled/not installed module *names*, not their location:
```
drush pm-list --no-core --pipe --type=module --status='not installed'
```
and the sample output:
```
...
i18n_block
i18n_contact
i18n_field
i18n
i18n_menu
i18n_node
i18n_forum
...
```
— i.e. no paths. Also, it lists submodules just the same way it lists modules.

## Approach

Had we 1-to-1 relation between directories and projects, the task wouldn't ever worth to mention. But Drupal architecture allows projects to have several modules in it, share one directory among different modules, have random nesting and even modules location. In such circumstances there is no probably 100%-working solution for the task of fnding unused locations (paths). That said, we have to make at least this one assumption about projects locations to get things done:

* submodules which are the part of their projects were not moved outside the containing project directory

Hopefully, in real life such a heresy is rare at least.

Now when the stage has been set, the idea is pretty simple: get the list of disabled modules' paths from the database and filter it out by two criteria:

1. a path should not be a part of *some enabled* module's path
2. a path should not be a part of *parent disabled* module's path

1st rule basically means that we ignore disabled submodules if their parents are enabled. This is needed to not break the integrity of projects containing several submodules. Example: ```i18n``` with lots of submodules. Had we counted a disabled submodule (like ```i18n_block```) as unused, we would break ```i18n``` project integrity.

2st rule is needed to fold up disabled submodules' dirs to their parents. I.e. all those ```i18n_block```, ```i18n_contact```, ```i18n_field``` and etc should fold up to their parent - ```i18n```.

## Testing

Please report any troubles and share ideas on enhancing/fixing this utility.

**Comment by echernyavskiy** [comment]
@OnkelTem, smoke tested this command just now - looks good to me. Great idea too!

Looking at the list of unused modules in one of my Drupal installations though makes me think that providing an option to only list parent module paths would be useful, e.g.

    ...
    sites/all/modules/contributed/custom_search
    sites/all/modules/contributed/custom_search/modules/custom_search_blocks
    sites/all/modules/contributed/custom_search/modules/custom_search_i18n
    sites/all/modules/contributed/custom_search/modules/custom_search_taxonomy
    ...

with such option on becomes

    ...
    sites/all/modules/contributed/custom_search
    ...

Such output could then safely be piped to, say

    while IFS= read -r line; do rm -rf "$line"; done

**Comment by OnkelTem** [comment]
@echernyavskiy 

But doesn't it already print only parent modules? As this should be the default (and the only) behavior:

> 2. a path should not be a part of parent disabled module's path

**Comment by jonhattan** [comment]
With some drush-fu you can concatenate commands and get really near:

`ls -d $(drush pm-info --format=list --fields=path $(drush pm-list --no-core --status='disabled,not installed' --pipe))`

The problem, as stated above, is that it includes the path of submodules that may have a parent or sibling module enabled. The command  in #766 may help to tune this (part of drush_extras).

---

OTOH, drush already has a nice api to get the unused projects really easy:

`drush php-eval 'array_map(function($project) {print $project["path"]."\n";}, array_filter(drush_get_projects(), function($project) { return !$project["status"];}));'`

So, `rm -rf $( /* above command here */ )`.

**Comment by OnkelTem** [comment]
@jonhattan 

> OTOH, drush already has a nice api to get the unused projects really easy:

Your drush-fu is of 80lvl, comrade! And I wish I knew about ```drush_get_projects()``` before as it looks very promising.
I have an issue with your expression as it lists only a part of projects. For example:
```
drush list-unused | wc -l
235
```
```
drush php-eval 'array_map(function($project) {print $project["path"]."\n";}, array_filter(drush_get_projects(), function($project) { return !$project["status"];}));' | wc -l
50
```
Where are the rest 185 projects? :)

**Comment by jonhattan** [comment]
So you have 235 unused **projects**? Is this a reliable number?

There's no pager-like restriction involved in `drush_get_projects()`. Perhaps my improvised eval code has any failure, but drush_get_projects() is trustworthy.

**Comment by jonhattan** [comment]
@OnkelTem I've tested your extension and definitely it is not accurate. It shows several subdirectories.

I've created two patches for drush_extras to allow `pm-projectinfo` to show the path of disabled projects. Once/If accepted, this will do the job:

`ls -ld $(drush @d7 pm-projectinfo --status=disabled --fields=path --format=list)`

Patches:
 * https://www.drupal.org/node/2565101
 * https://www.drupal.org/node/2565095

/cc @greg-1-anderson

**Comment by OnkelTem** [comment]
@jonhattan 
> I've tested your extension and definitely it is not accurate. It shows several subdirectories.

Would you be more specific - what exactly goes wrong?

**Comment by OnkelTem** [comment]
@jonhattan 
> So you have 235 unused projects? Is this a reliable number?
Affirmative. I use single code-base for many projects.

> drush_get_projects() is trustworthy.
I've just checked and it sure enough it returns 59 projects.

> ls -ld $(drush @d7 pm-projectinfo --status=disabled --fields=path --format=list)
I've applied the patches and tried this command — anticipated 50 directories out from 235.

**Comment by OnkelTem** [comment]
I've rewritten the code so that it is now searching for parent projects recursively up to the 'sites' directory: 
https://github.com/OnkelTem/drush-list-unused/commit/2d5951a7bdfc146d0e0baf2f1f89e58613d60655

**Comment by greg-1-anderson** [comment]
@jonhattan: I made a new release of Drush Extras containing your contributions.  Thanks! https://www.drupal.org/node/2565309

**Comment by jonhattan** [comment]
Thanks @greg-1-anderson!

@OnkelTem output for both commands https://gist.github.com/jonhattan/d3165603256174ac199f. Anyway your command won't be part to Drush. If you find something innacurate in `drush_get_project()` (or `pm-projectinfo`) we can continue here or in another issue until it's fixed.

###### Summarizing

To obtain a list of the unused projects (projects with all of its modules/themes disabled), you can use command `pm-projectinfo`, part of [drush_extras](https://www.drupal.org/project/drush_extras).

`drush pm-projectinfo --status=disabled --fields=path --format=list`

For convenience, you can define a shell alias in `drushrc.php`. For example:

`$options['shell-aliases']['list-disabled-projects'] = 'pm-projectinfo --status=disabled --fields=path --format=list'``

Now you can issue `drush list-disabled-projects`.

Finally, to operate on the command result from the shell:

`ls -d $(drush list-disabled-projects)`

*Replace `ls -d` with a command of your choice* :)

**Comment by jonhattan** [comment]
Ok, one important thing to note here is that drush_get_projects() and thus `pm-projectinfo` command, ignores projects cloned from git, if git_deploy module is not enabled. Reason is that the repository doesn't hold the project name and version (this is added to .info files by drupal.org's packaging script) and drush can't figure it out.

**Comment by OnkelTem** [comment]
@jonhattan Then let ```list-unused``` be a separate command, as this allows to stay practical and usable,  what I can't say about ```pm-projectinfo``` (via ```drush_get_projects()```). 

When I played with ```pm-projectinfo``` yesterday I noticed how slow it is. Also I got a bunch of different warnings. And now to get the lions share of modules just to get listed — ```git_deploy``` must enter the  game which is slow like hell. And yet this probably a theoretically correct approach, just do what ```list-unused``` does seems to be much better.

**Comment by greg-1-anderson** [comment]
@OnkelTem: Thank you for writing a useful Drush extension.  To help folks find it on GitHub, you should add a composer.json file so that it shows up in http://packages.drush.org.  Find some other project by browsing there, and use its composer.json as a guide. Then, if you submit your project on packagist.org, it will show up on packages.drush.org.

**Comment by OnkelTem** [comment]
@greg-1-anderson Thanks. Yeah, I definitely should become acquainted with composer workflow.
