### ISSUE TITLE
Drush pm-update (up) rollbacks changes if fetching updates fails

### ISSUE THREAD

**Issue by rodrigoaguilera** [drush-ops/drush#160]
bug from the do issue queue
https://drupal.org/node/1196972

When running "drush up drupal," drush says that the upgrade completed successfully, but no update actually occurs. Instead the initial backup is restored instead. Here's the output:

Do you really want to continue? (y/n): y
Project drupal was updated successfully. Installed version is now 7.2.
Backups were saved into the directory [ok]
/home/xxx/drush-backups/xxx/20110622192752/drupal.
Backups were restored successfully. [ok]

Subsequent checking shows that the Drupal version is still set at 7.0. This behavior occurs on ANY module update as well.

**Comment by ahebrank** [comment]
Just had this problem (rollback after every `drush up` update attempt).  The cause (in my case) for posterity, since there were no Drush errors or watchdog notices: I had a custom module with a typo in the .info metadata.
