### ISSUE TITLE
Group exports/imports (e.g. content types)

### ISSUE THREAD

**Issue by anavarre** [drush-ops/drush#1601]
Drush's `config-export` and `config-import` commands might be improved by supporting group exports/imports. E.g. content types, image styles, etc. Basically, all configuration you might want to make portable and have to export/import manually by making sure you won't miss a required dependency (field, field storage, form display, etc..).

The ideal implementation would make it so we'd have a flag to pass, say `--type`, and by passing `$ drush config-export --type=article` we'd then get a tarball with all files we need that we could then import on any site of our choice with `$ drush config-import --type=article`

If there are UUID considerations, then maybe `devel` would be a dependency so that it generates new UUIDs on the fly.

I didn't put much thought into the above suggestions, but what matters is that we determine if a) it's a good job for Drush to implement this and b) if this needs to live in the config-export/import commands or a totally new command that would support CMI's individual export/import of config.

**Comment by weitzman** [comment]
I would expect [Features](https://www.drupal.org/project/features) to implement this sort of thing. If they can't or its awkward to do there, then lets re-open this.

**Comment by anavarre** [comment]
Just want to report that Features for D8 does things pretty elegantly and it's a good workaround to solve this annoying but common use case. +1 to the D8 version not needing to be installed on the prod site.

Thanks for the heads up.

**Comment by amjad1233** [comment]
@anavarre I heard that feature shouldn't be used. As per the maintiner of Features module explained here https://youtu.be/x2kYZhgUSU0?t=2144.
