### ISSUE TITLE
drush qd not working against 8.0.x

### ISSUE THREAD

**Issue by mohankumargupta** [drush-ops/drush#1605]
I decided to run a travis CI test that was working about 3 months ago, and it failed.

https://travis-ci.org/mohankumargupta/mentionsdrupal8module

The error I got is:

Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: syntax error, unexpected 'CLASS' (T_CLASS), expecting
identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in
/home/travis/build/mohankumargupta/mentionsdrupal8module/web/mydrupal/drupal-8.0.x/core/lib/Drupal/Core/Extension/ModuleInstaller.php,
line 226
The command "drush qd mydrupal --core=drupal-8.0.x --dev --no-cache --yes --profile=standard --no-server --account-mail='a@b.com' --account-name=admin --account-pass=password --site-name=boo" failed and exited with 255 during .

Any suggestions? Is it drush or is it drupal?

**Comment by weitzman** [comment]
Can't reproduce this with todays Drupal and Drush.

**Comment by mohankumargupta** [comment]
Got it.

I updated my travis.yml to PHP 5.5

RTFM!
