### ISSUE TITLE
Unable to bootstrap drupal when using prefix with different databases

### ISSUE THREAD

**Issue by andreasbergqvist** [drush-ops/drush#1606]
I have a database setup with multiple sites sharing a database with user spefific tables.

It looks like
db1_shared (database that contains users and permission tables)
db2_site1 (database containing all drupal table exept users and permissions)
db3_site2 (database containing all drupal table exept users and permissions)

In my settings.php file for the two sites i setup prefixes as:
    
    'prefix' => array (
        'default' => '',
        'role' => 'db1_shared .',
        'role_permission' => 'db1_shared .',
        'sessions' => 'db1_shared .',
        'users' => 'db1_shared .',
    ),

When I run `drush status` I don't get "Drupal bootstrap : Successful". And I can't run any other drush commands that needs database connection.

If I test adding the tables from the shared table to my site database and remove the prefix setting it works.

Is it correct that drush won't work with different databases prefixed?

Note that the sites works in the web browser.

**Comment by andreasbergqvist** [comment]
After digging in to the code I noticed that it stopped when checking if the `blocked_ips` table existed in the selected database. I had moved this table to the shared database. This is not possible with drush as it seems.

**Comment by Niremizov** [comment]
This issue was very helpfull for me! Thx. I had preffix configuration like this:

```
'prefix' => array (
    'default' => 'db0_default',
    'role' => 'db1_shared .',
    'role_permission' => 'db1_shared .',
    'sessions' => 'db1_shared .',
    'users' => 'db1_shared .',
),
```

And drush 8 could not bootstrap normally. After i have look at yours 'default' index value, I have changed prefix as this:

```
'prefix' => array (
    'default' => '',
    'role' => 'db1_shared .',
    'role_permission' => 'db1_shared .',
    'sessions' => 'db1_shared .',
    'users' => 'db1_shared .',
),
```
So i left default index value empty - and it's began to work!
