### ISSUE TITLE
Remove calls to deprecated conf_path()

### ISSUE THREAD

**Issue by iant-tui** [drush-ops/drush#1607]
conf_path() is due to be removed before Drupal 8.0.0 (see https://www.drupal.org/node/2457469 ), but doing so breaks drush. We need to remove calls to this function.

**Comment by cilefen** [comment]
It seems like if many usages of conf_path were changed to drush_conf_path, and drush_conf_path made aware of anything it needs to know for 8, that may work.

**Comment by weitzman** [comment]
Yeah, I suggest that drush_conf_path() be added to the three commands/core/drupal/environment*.inc files. Then when you use drush_conf_path(), you should add this line right above it - `drush_include_engine('drupal', 'environment');`

**Comment by iant-tui** [comment]
How are you getting on cliefen? Is this ready for review?

**Comment by cilefen** [comment]
@iant-tui See #1611

**Comment by iant-tui** [comment]
Can I help with this in any way? It is a blocker to conf_path() being removed, and if we don't do that before RC1 (announced as 7th Oct) we'll need to support it until Drupal 9.

**Comment by cilefen** [comment]
@iant-tui, in #1611, @weitzman suggested re-implementing conf_path in the bootstrap classes. You could try that.

**Comment by weitzman** [comment]
Sorry I got delayed. You can help by making a PR.

**Comment by iant-tui** [comment]
I take it you haven't written any code for this yet then. Are we basically suggesting copying D8's current conf_path() function into the bootstrap class?

**Comment by weitzman** [comment]
Correct I have not started. I have not investigated the best way to implement this. There may be a better way than just copying the code - I dont yet know.

**Comment by cilefen** [comment]
@weitzman Can you give me a hint on a way to test the changes, like a command that will definitely error or fail if the changes don't work?

**Comment by weitzman** [comment]
Full bootstrap would fail if this code broke so I think we have sufficient implicit testing already.

**Comment by weitzman** [comment]
Coded up a fix at #1607. Will merge when tests are green.

**Comment by cilefen** [comment]
The PR is #1631

**Comment by paul-m** [comment]
Actually removing conf_path() from Drupal is blocked by this issue.

https://www.drupal.org/node/2573443
