### ISSUE TITLE
Convert alias files to .yaml

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#1609]
c.f. #975

I started to break out Drush alias handling in a separate project.  I put sample alias files there:

https://github.com/drush-ops/drush-aliases/tree/master/examples

I have more code that I have not pushed to that repository yet; I ran into an issue with command-specific options that I think may warrant some rework in the current code base prior to refactoring.  Another issue with a separate project is what to do with drush_log.  Currently, I am just trying to write the API to return simple result codes, so it does not need to log.  If that works out, then we wouldn't need to worry about DI-ing a logger.

Feedback would be appreciated.  We could start off with the refactor just as part of Drush, but if it does go into a separate project, then we'd have the opportunity to handle `drush @alias foo ...` redispatching in the Drush launcher instead of in drush.php -- although that is a separate issue (which depends on this issue).

**Comment by weitzman** [comment]
Great to kick this off ...

1. Maybe there should only be one type of alias file - the plural. We create a group alias if the count is in there is more than one. Just thinking aloud. 
1. Drupal core depends on "psr/log": "~1.0". It's tiny. I'd be fine with depending on that. We can convert existing code over time. Or drush_log() wraps the psr/log stuff. Not sure if this is a complete solution to your issue.

**Comment by greg-1-anderson** [comment]
Aegir wanted separation of `name.alias.drushrc.php` from `group.aliases.drushrc.php` because they have so many aliases, they did not want to have Drush load a large compound alias file unless it is referenced.  By having different filenames for these, we know that we do not have to try to load any "aliases" files unless none of the "name" files match.

I am wondering now, though, if this is effective.  If you had a mix of both kinds of alias files, you'd still take the hit any time anyone accidentally tried to use a non-existent alias.  If you have tons of small aliases, you can just choose not to make any large "aliases" files.

The other reason to have two different formats is to avoid having a variable schema.  If we had just the plural form of the file, then we'd either always have two extra levels of nesting, or we'd have to dynamically switch to the plural schema when we saw a top-level 'sites' element.

Undecided on the trade-offs here.  For my part, I always use the plural syntax, so I would not personally mind if we dropped the singular.  It might be good if we could get some feedback from folks who actually use the feature here.

**Comment by weitzman** [comment]
Not much feedback. IMO we should drop singular format. Nice thinking splitting into a separate repo.

**Comment by ergonlogic** [comment]
The last time I tested the plural aliases format in Aegir, it incurred a huge performance overhead. We store all kinds of data in alias files, and use backend_invoke rather heavily too. The main problem, iirc, was that the use of plural aliases required loading all `aliases.drushrc.php` files.

Also, since we use aliases as a backend data-store, we write and re-write these aliases regularly. This'd be greatly complicated if we couldn't do so reasonably atomically.

**Comment by weitzman** [comment]
Aegir could implement the alter hook and scan a directory of single file aliases, or it could just declare from iterate over DB records or whatever you want.

**Comment by greg-1-anderson** [comment]
The advantage of the single-alias variant for Aegir is that Drush loads *only* the named alias file if it exists, and will not load the multiple alias variants in those instances.

The alter hook only fires after Drush has already found a matching alias record; at the moment, we do not have an "alias load" hook.

**Comment by greg-1-anderson** [comment]
Look, this is done! 😄
