### ISSUE TITLE
Setting GREP_OPTIONS='--color=always' causes errors

### ISSUE THREAD

**Issue by ShawnConn** [drush-ops/drush#1610]
I had the `$GREP_OPTIONS` set to "--color=always"  and that appears to break Drush.

```bash
$ ./drush --version
PHP:  parse error, expecting `']'' in Unknown on line 7
 Drush Version   :  8.0-dev
```

It looks to occur for both the master & 7.x branches. I'd troubleshoot further, but the origin of the parse error is ambiguous to me.

**Comment by lokapujya** [comment]
try: alias grep='grep --color=auto'

**Comment by orlitzky** [comment]
I used to set that too, and ran into problems everywhere. The consensus was that it's bad news and will be removed later. From `man grep`:

```
GREP_OPTIONS
              This variable specifies default options to be placed in front of
              any  explicit  options.   As  this  causes problems when writing
              portable scripts, this feature  will  be  removed  in  a  future
              release  of  grep,  and grep warns if it is used.  Please use an
              alias or script instead.
```

**Comment by ShawnConn** [comment]
Thanks @lokapujya, that's the route I went with to get around the problem.
