### ISSUE TITLE
Don't check drupal.org for projects that specify a 'download' parameter in makefiles

### ISSUE THREAD

**Issue by ergonlogic** [drush-ops/drush#1614]
Specifically, when a module isn't hosted on drupal.org, we need to specify ```projects[...][type] = "module"```. Otherwise, we'll get an error about not being able to find the project on d.o, when Drush tries to look up the project type. Since we filter out default or null values, when generating makefiles, ```drush make --lock``` is broken by this behaviour.

**Comment by ergonlogic** [comment]
I'm pretty sure the logic in ```make_project_needs_release_info()``` is flawed. It's described as:

```
 * If the location of the project is not customized (uses d.o), and
 * one of the following is true, then release information is required:
 *
 * - $project['type'] has not been specified
 * - $project['download'] has not been specified
```

I think both the criteria have to be true, for this to make sense. That is, we proceed to set ```projects[...][download][type] = 'pm'``` if ```make_project_needs_release_info()``` returns TRUE. So neither ```$project['type']``` nor ```$project['download']``` should be set is we're going to poll d.o for the release info.

**Comment by jhedstrom** [comment]
Yeah, both `download` and `type` need to be specified, otherwise drush won't know if it's a module, theme, or install profile, so that docblock appears to be in error.

**Comment by ergonlogic** [comment]
I always thought that 'module' was the default project type, regardless of whether it was hosted on d.o. Is there reason *not* to have modules be the default? They outnumber profiles and themes combined by an order of magnitude. It's also has the virtue of being trivial to implement.

**Comment by jonhattan** [comment]
The current implementation of `make_project_needs_release_info()` is there to support cases as the ones in `tests/makefiles/git-simple.make` and `tests/makefiles/git-simple-8.make`. Those and other cases, including some assumptions of drush make, come from the old drush_make. I don't think we have done any deprecation or backward incompatible change never. Perhaps Drush 8 is the time.

Btw time back I did some changes in [make-fixes](https://github.com/drush-ops/drush/commits/make-fixes). I think some of them have been introduced later, but I wonder if some of them are still relevant for this topic.

**Comment by ergonlogic** [comment]
@jonhattan points out that he'd already introduced a similar (but better) fix in e90bd93. does anyone object to my cherry-picking that into master? This very minor change should also be backwards compatible with existing makefiles, and so I'd like to back-port it to Drush 7.x and 6.x.

**Comment by jhedstrom** [comment]
Defaulting type to 'module' sounds great to me.

**Comment by ergonlogic** [comment]
This required a bit of re-factoring of the code to determine a project's core vs. contrib status, in 3c7761b. Tests are passing again. Closing.

**Comment by ergonlogic** [comment]
Sorry, I forgot to back-port this to 7.x. I've cherry-picked the two commits into 7.x now. I'll close once the test run is green.

**Comment by ergonlogic** [comment]
Tests are green.
