### ISSUE TITLE
PHP Warning breaks drush shell script.

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#1616]
I can't use `drush` command, as my PHP showing me some warnings, e.g.:

	$ drush status
	PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php56/5.6.8/lib/php/extensions/no-debug-non-zts-20131226/memcached.so' - dlopen(/usr/local/Cellar/php56/5.6.8/lib/php/extensions/no-debug-non-zts-20131226/memcached.so, 9): image not found in Unknown on line 0
	~/.composer/vendor/bin/drush: line 129: [: too many arguments

Affected code:

	PHP_MINOR_VERSION="`\"$php\" -r 'print PHP_MINOR_VERSION;'`"
	if [ $PHP_MINOR_VERSION -le 3 ] ; then

Running: `php -r 'print PHP_MINOR_VERSION;'` shows `6`, but along with memcached warnings, so I believe we need to find a better way of checking PHP version.

I've tried: `php -d error_reporting=-1 -r 'print PHP_MINOR_VERSION;'`, but it didn't help.

**Comment by greg-1-anderson** [comment]
The right solution here would be to fix your php.ini so that it does not reference the extensions that are not available!

However, when I forced this situation, so my php emitted warnings, I did not have a problem.  I am running with #1595; try with that PR, it might solve your problem.

**Comment by kenorb** [comment]
Similar happened on different server:

	-sh-4.1$ drush sql-dump --ordered-dump --gzip
	+ drush sql-dump --ordered-dump --gzip
	PHP Warning:  Module 'memcache' already loaded in Unknown on line 0
	sh: -c: line 0: syntax error near unexpected token `|'
	sh: -c: line 0: `| gzip'
	Database dump failed                  

when I ran it outside of public_html/, but when repeated in public_html/ then it worked.
Unfortunately I couldn't correct php.ini to see if that would work, as I don't have sudo access.

Drush: v6.2.0

But the error seems different, as it doesn't showing the line.
