### ISSUE TITLE
Remote makefile fails to complete build

### ISSUE THREAD

**Issue by ergonlogic** [drush-ops/drush#1621]
It looks like `drush make` will sometimes build differently depending on whether the makefile is remote. For example, [this makefile](https://raw.githubusercontent.com/devekko/aegirproject.com/872739b2d03890fdd08fdc3f4b6cf1f38497361b/rune-build.make)  works properly if downloaded and run locally, but `drush make` fails to download `bootstrap` when passed the remote URL.

**Comment by greg-1-anderson** [comment]
Make is maintenance only; closing.
