### ISSUE TITLE
Themes get the wrong project type now

### ISSUE THREAD

**Issue by daften** [drush-ops/drush#1627]
Due to the changes in commits fcaf417c7a78c9619f949178fb93304b4fa0fe7c and e8125d083afe9087ced958a1356bb361116793e4, e.g. when the project type for themes is not explicitly defined, it is not autodetected anymore and the theme is placed in the modules folder. This seems like a breaking bug to me :)

**Comment by danepowell** [comment]
Yeah, unfortunately I can't find any pull requests or issues associated with those commits, so it's hard for me to guess their intention. However, they definitely had the side effect of breaking project type auto-detection.

#1684 fixes this by partially reverting those commits. It doesn't seem to have any side effects, but like I said, without any documentation on what those commits were supposed to fix in the first place, it's hard to know for sure.

**Comment by daften** [comment]
Thanks, I haven't verified completely, but the code changes look good. I can always reopen if necessary.

Thanks again ;)
