### ISSUE TITLE
Any plans to update drush in apt repositories?

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#1628]
Currently in apt repositories there is quite old drush version:

    $ sudo apt-cache madison drush
     drush |   5.10.0-2 | http://archive.ubuntu.com/ubuntu/ vivid/universe amd64 Packages

Which has many bugs and doesn't support yml files.

Are there any plans to update this release to the next stable version? I understand I could use composer, but for simplicity of my VM provisioning I wanted to investigate apt approach (`sudo apt-get install drush`).

**Comment by greg-1-anderson** [comment]
The maintainers of the Drush apt packages manage them in the Debian repository, so the version that is ultimately exposed to Ubuntu is usually extremely old.  I think there are -- or were at one time -- some more recent "bleeding edge" repositories that you could reference in order to get more recent versions of Drush.  I don't know if these are maintained any more, or if including them would have adverse effects on other software selection done in your VM setup.

I would recommend using Composer here; it's only a couple of extra lines.  You might be interested in my [move-in](https://github.com/greg-1-anderson/utiliscripts/blob/master/move-in) script, which installs Composer and uses it to install Drush.  I use this script to make new systems configured to my liking; it runs with and without a GUI, on Linux and MacOS.  Would also work for VM setup. I'd recommend extracting what you need rather than tracking the script in my repo.

**Comment by kenorb** [comment]
Thanks, I've tried composer, but I've some [issues](http://superuser.com/q/977692/87805) with it.

On [`composer update`](https://github.com/mycognitive/drupal-sandbox/blob/371b65b55e3cb2f11c6aff834b3069785b7bb12a/scripts/provision.sh#L34), it's just installing `drush` in `/vagrant/vendor/drush` which is a bit weird.

**Comment by greg-1-anderson** [comment]
If Drush 5.x is sufficient to your needs, then apt-get is going to be the easiest route.  If you want to keep up do date with Drush, I'd recommend using composer.

I answered your composer question in the superuser question you linked to.

**Comment by jonhattan** [comment]
If you're after a system-wide installation (ie, for all users of the system), here's how to do it: https://github.com/drush-ops/drush/issues/644#issuecomment-122588151

**Comment by kenorb** [comment]
Too much complications such as creating dirs, linking, modifying system variables, etc.

For now I've specified dirs inside JSON file:

	{
	    "config": {
	        "vendor-dir": "/var/lib/vendor",
	        "bin-dir": "/usr/local/bin"
	    },
	    "require": {
	        "drush/drush": "dev-master"
	    }
	}

which works pretty simple. So lib stuff automatically goes to `/var/lib/vendor`, then binaries into `/usr/local/bin`, so it's basically the same place where `composer` got installed at the first time.

**Comment by jonhattan** [comment]
I wasn't aware of those options!

So here's a oneliner:
```
COMPOSER_HOME=/opt/drush COMPOSER_BIN_DIR=/usr/local/bin COMPOSER_VENDOR_DIR=/opt/drush/7 composer require drush/drush:7
```

COMPOSER_HOME is where the `.composer` folder is placed.

Note that the vendor-bin option adds any binary found in drush or its dependencies (psysh, boris,..) to `/usr/local/bin`. Not desirable in some environments.

Also, this oneliner can't manage the case when you want several versions of drush, as my snippet in https://github.com/drush-ops/drush/issues/644#issuecomment-122588151 does.

**Comment by kenorb** [comment]
@jonhattan Thanks, this would work for me as well, as I don't have to hardcode the paths in my `composer.json`. So Vagrant can install drush somewhere else, and Travis CI can do, and they can share the same config.

**Comment by kenorb** [comment]
I'll try contacting maintainer then:

	$ apt-get changelog drush | head
	Get:1 Changelog for drush (http://packages.debian.org/changelogs/pool/main/d/drush/drush_5.4-1/changelog) [7,699 B]
	drush (5.4-1) unstable; urgency=low

	  * New upstream release
	  * Update to standards 3.9.3, no change
	  * Fix Vcs-* urls

	 -- Antoine Beaupré <anarcat@debian.org>  Fri, 15 Jun 2012 17:27:17 -0300

**Comment by kenorb** [comment]
I've contacted Antoine Beaupré, however he orphaned the `drush` Debian package as per [Debian Bug #798500](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=798500).

As per Antoine advice:

> The first step to update the package will be to fix the issues with the
new Composer deployment that Drush uses. It looks like Composer is now
in Debian, but I am not sure how to package composer tools in Debian
now.

> Maybe the Debian PHP team could help: https://wiki.debian.org/Teams/DebianPHPGroup

> Once there's a package to be uploaded (or even before, actually), the
package adoption procedure should be followed here: https://www.debian.org/doc/manuals/developers-reference/ch05.en.html#adopting

Jan commented the current situation:

> Upstream has basically rewrote the whole distribution
mechanism to depend on Composer, which made it very hard to package new
versions, as composer isn't itself packaged in Debian (or wasn't, last i
checked).

--

The homepage for the package is at: https://tracker.debian.org/pkg/drush

The git repository for the Debian package: http://git.debian.org/git/collab-maint/drush.git

**Comment by greg-1-anderson** [comment]
Maybe it would be easier to package the Drush phar in Debian.

**Comment by kenorb** [comment]
**drush will be removed from Debian**

As per Antoine Beaupré e-mail to [debian-bugs](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1419737.html):

> In #823767, I have requested from the FTP-masters that Drush be removed
> from Debian. In the ~9 months since it was orphaned, no one stepped up
> to start maintaining the Drush package, let alone update it to a current
> version. There was some movement on the Ubuntu side of things (also in
> CC), but it seems it didn't end up going anywhere.
> 
> It seems clear to me no one is available to do that task and having an
> outdated version of Drush in Debian is hurting both projects for no good
> reason. At least that is the constant feedback I receive, both privately
> and through the above bug reports.
> 
> So unless someone steps up *now* to tell the FTP-masters to stop, it
> will be removed as soon as they take a look at bug #823767.
> 
> Thanks for your attention, and sorry for the wide {B,}CC.
> 
> A.
> 
> --
> Le pouvoir n'est pas à conquérir, il est à détruire
>                         - Jean-François Brient, de la servitude moderne

**Comment by greg-1-anderson** [comment]
This is probably for the best. It's hard for the distros to keep up with composer-packaged projects anyway.

**Comment by colans** [comment]
There's an open issue for fixing this over at #2177 .
