### ISSUE TITLE
Support for GitHub to checkout and update projects.

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#1630]
Is there any way of using GitHub as a handler for downloading the modules.

Normally you would do:

    drush -y dl views --dev

Where by default we're using `git_drupalorg` as `--package-handler` if I'm looking on the correct parameter.

Is there any way to change the default repository and use GitHub instead?

So I would expect something like:

    drush -y dl org/repo --dev --package-handler=github

which I would expect to download the project from GitHub.

I know I can use `yml`/`make` files, but I'm checking for possibility to do it from the command-line. So if there is the existing option (`git_drupalorg`):

> Use git.drupal.org to checkout and update projects. 

I would expect different handlers to be present.

--

Update: Now I see there are only two package handlers in [`commands/pm/package_handler`](https://github.com/drush-ops/drush/tree/master/commands/pm/package_handler).

Would it be possible/accepted to provide additional one for GitHub?

**Comment by weitzman** [comment]
I'm not sure what this buys you beyond what you get by using `git clone` or `composer require` directly. The secret sauce of dl is that it understands Drupal's update XML. Thats gone once you do releases on Github. I think it is fine for projects to choose that, but they no longer benefit from dl.

**Comment by kenorb** [comment]
This will buy some time and simplicity when developing modules which are on GitHub.

Normal (drush) way to download and enable two modules is simple one-liner:

    drush -y dl booking_timeslots postcodeanywhere --dev

which would work for Drupal repos only, and automatically download repos into contrib/ dir.

Standard git way would be in 4 steps (to download and enable two modules):

    cd sites/all/modules/contrib
    git clone -b 7.x-1.x git@github.com:mycognitive/booking_timeslots.git
    git clone -b 7.x-1.x git@github.com:mycognitive/postcodeanywhere.git
    drush -y en booking_timeslots postcodeanywhere

Having GitHub handler it would go like (just example):

    drush -y en mycognitive/booking_timeslots mycognitive/postcodeanywhere --dev --package-handler=github

as a simple one-liner. The question is then, where `--dev` should point to, either to master or 7.x-1.x.

This helps people who're not familiar with git syntax (like cloning the right branch).

Just to give some idea, maybe somebody would be interested in doing it (it's just writing few functions). Or Drupal team would decide in future to migrate to GitHub instead, so it would be helpful.

**Comment by kenorb** [comment]
Related: https://www.drupal.org/project/git_deploy and:

    drush pm-download --package-handler=git_drupalorg --gitinfofile
