### ISSUE TITLE
`drush --uri http://example.com pm-updatecode` doesn't work

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#1632]
Not sure if I'm missing anything here, but when I run the command from the example ([usage.md](https://github.com/drush-ops/drush/blob/master/docs/usage.md#options))

> drush --uri http://example.com pm-updatecode

it's giving me the error:

	docroot$ drush --uri http://localhost pm-updatecode
	The drush command 'http://localhost pm-updatecode' could not be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new extensions.
	vagrant@vagrant:/vagrant/docroot$ drush cache-clear drush
	'drush' cache was cleared.             
	$ drush status
	 Drupal version                  :  7.39                                           
	 Site URI                        :  http://default                                 
	 Database driver                 :  sqlite                                         
	 Database name                   :  .db.sqlite                                     
	 Drupal bootstrap                :  Successful  
	 Drush version                   :  8.0-dev                                        

I've tested on another Drupal instance, the same thing.

I am using this command right? Or something changed recently?

**Comment by kenorb** [comment]
I think the example should be:

    drush --uri http://example.com pm-updatecode

as described in `drush topic core-global-options`.

**Comment by greg-1-anderson** [comment]
Merged. Thanks.
