### ISSUE TITLE
Ability to change $base_url via drush (in order to work with runserver)

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#1634]
It would be nice to have ability to override `$base_url` from `drush` in similar way as it's done via `--variables` to override `$conf` in settings file.

For example this works:

```
$ drush --variables="foo=bar" eval 'global $conf; print_r($conf);' | grep foo
    [foo] => bar
```

but it's limited only for `$conf`.

I've tried to use `-l` which seems work, but it's not for `runserver`.

I've described my scenario [here](http://drupal.stackexchange.com/q/175660/1908), but I was a bit lost which settings controls that.

This should be useful for performing [quick Drupal installations](http://drupal.stackexchange.com/q/134761/1908) or running a lightweight http server on multiple addresses (`drush rs 0.0.0.0:8080`).

By default the address is calculated dynamically based on the address which I access the server and when using a lightweight http server sometimes it doesn't work as expected with no possibility to change base_url when using default configuration of Drupal.

Normally I would expect this example to work:

```
drush --uri=http://example.com:8080 rs --default-server=0.0.0.0:8080
```

and it works at some point:

```
$ drush --uri=http://example.com:8080 eval 'global $base_url; echo $base_url;'
http://example.com:8080
```

but not with the `runserver` command I guess.

I've also tested the following option in `sites/default/drushrc.php`:

```
<?php
$options['uri'] = "http://example.com";
```

which works for all commands except `runserver` (where it's ignored based on what I see in the HTML source). However after few more tests I'm actually not quite sure about this.

So I believe this is hardcoded in [`runserver.drush.inc`](https://github.com/drush-ops/drush/blob/b4c0683922ab08ef81c9f7553f58ab845ea6972e/commands/runserver/runserver.drush.inc#L95).

Let me know if that make sense, or I'm missing something.

If it's not clear, I'll try to send more details soon, when I'll figure it out what's the exact issue.

**Comment by dpi** [comment]
I dont think this is possible as of [Remove the option to specify a base_url from within settings.php](https://www.drupal.org/node/2528988)

**Comment by fuzzy76** [comment]
I would also like this functionality (so I would not have to edit my /etc/hosts file every time I spin up a quick testsite - I don't like using the default site).

The problem with --uri is not that it is hardcoded, but the server is run as a separate process (launched with exec), and not "inside" the drush context. The problem is passing the info on to the actual server.

Would it be possible to overwrite the hostname for the request in the router file?

**Comment by grugnog** [comment]
I [think](https://github.com/drush-ops/drush/blob/b4c0683922ab08ef81c9f7553f58ab845ea6972e/commands/runserver/runserver-prepend.php#L3) this is already what we do for Drupal 7 - I am not clear what the equivalent is for Drupal 8 (or if this kind of smoke and mirrors is even possible).

**Comment by weitzman** [comment]
Stale
