### ISSUE TITLE
Certain types of YAML files can silently crash Drush Make

### ISSUE THREAD

**Issue by danepowell** [drush-ops/drush#1638]
This bug may not sound bad, but it's absolutely insidious and can cause a _lot_ of grief.

The symptom is that you are using Drush Make on a YAML make file on a daily basis, when without warning Drush Make starts to fail because of a (perfectly valid) change to the make file. The YAML file can be completely valid and well-formatted.

In my case, I determined that the crash would occur when the total number of characters in patch filenames reached some limit (but only when the patches are indexed by URL, rather than using shorthand format). I'm sure there are other ways to trigger it, however, and they are all equally confounding to debug.

I found that the crash actually occurs in the INI file parser, called by _make_determine_format(). I didn't debug any further than that- it's not surprising to me that a malformed INI file (i.e. a YML file) could crash the parser, although I wish it didn't fail silently. Rather, this seems like a complete abuse of the parser, and a better method should be used to determine file type.

I'm pretty sure that #1386 will solve this, but I think it should be backported to 7.x, since silently choking on perfectly valid files is definitely a bug.

**Comment by greg-1-anderson** [comment]
Seems to me that `make` would be better off if it inspected the first few lines of the makefile itself, and made its own determination of format before sending all of the data to the parser.  Safer that way.

**Comment by danepowell** [comment]
Ah, looks like I'm late to the party, this has already been backported (#1608), so this can be closed. Now if we can just get another stable 7.x release...
