### ISSUE TITLE
Drush runserver HTTP server doesn't support callbacks with dot in the URL

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#1641]
I've the following testing URLs (which exists in Drupal 7):

    /taxonomy/autocomplete/foo_bar
    /taxonomy/autocomplete/foo.bar

These Drupal URLs normally works in Apache by giving the error:

> Taxonomy field foo.bar not found.

When testing using `drush rs`, the second URL doesn't work properly and it gives the following error:

> Not Found

> The requested resource /taxonomy/autocomplete/aa.00 was not found on this server.

Log entry:

> `[Tue Sep 29 15:56:11 2015] 127.0.0.1:54729 [404]: /pca/retrievebyid/25764183.00 - No such file or directory`

I've found this when implementing [PCA](https://github.com/mycognitive/postcodeanywhere) and [this callback](http://services.postcodeanywhere.co.uk/PostcodeAnywhere/Interactive/RetrieveById/1.3/json.ws?key=DJ95-ZP12-FW89-EN99&Id=23747212.00&PreferredLanguage=English&CallbackFunction=TestCallBack).

So my local menu callback (`pca/retrievebyid/1234.00`) doesn't accepts the Id argument, because it's never gets passed into Drupal, as it consist dot (`.`). So for some reason drush is giving 404 page.

The easiest way to reproduce the problem is by running: `drush qd`.

I'm using `drush rs` for testing purposes.

I believe the error is could be somewhere in [runserver_parse_uri()](https://github.com/drush-ops/drush/blob/b4c0683922ab08ef81c9f7553f58ab845ea6972e/commands/runserver/runserver.drush.inc#L186), but I'm not sure exactly how the URLs are handled.

**Comment by MartijnBraam** [comment]
The issue that paths containing a dot aren't working is because the built-in php server assumes that all files containing a dot are an file in the filesystem. If a router script is passed to `php -S` then this behavior is bypassed and the all the urls start working.

I think this can be fixed by using the `d8-rs-router.php` for drupal 7

**Comment by kenorb** [comment]
It also fails for Advanced Help module which scans for the help files and generates the appropriate callbacks.

So going into: `/help/commerce_paypoint_advanced/README.md`
generates `Not Found` page as well.

Related: #752

**Comment by kenorb** [comment]
The solution is to start the server in docroot as:

    php -S localhost:8888 .ht.router.php

Where `.ht.router.php` file can be found at: [Add a startup configuration for the built-in PHP server that supports clean URLs](https://www.drupal.org/node/1543858)

Works for both Drupal 7 & 8.

**Comment by weitzman** [comment]
Got fixed by #2033
