### ISSUE TITLE
Consider back-porting "Drush Finder" script to 7.x branch

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#1644]
I think that we should backport #1595 to the 7.x branch and make a 7.1 release, either with the Drush release that will come out with Drupal 8.0.0-RC1 (~ 7 Oct), or for BADCamp.

The use-case here is for folks who want to use Drush 7.x stable as their "global" Drush, and run Drush 8.x on their Drupal 8 sites.  Having the Drush Finder script in the stable branch of Drush would facilitate this.

This might not be terribly necessary if Drush 8 stable were to come out soon, but I suspect that the RC1 -> 8.0.0 stable period may stretch out for several months.  Also, regardless of how long the road from RC1 to stable is, I think it is important that we start teaching people about site-local Drush during this period.

This change should not have much affect on folks who do not use or know about the new capability of the finder script, so I think it should be pretty safe to backport.  I'll roll a PR if this sounds like a good idea.

**Comment by weitzman** [comment]
I really don't think this change is appropriate for a stable release. It *should* be transparent, but my spidey senses are tingling. 

FWIW, Acquia is going to default to Drush8 soon. We'd rather have one version that works for D6/D7/D8 than try to encourage D8 folks to use their own Drush and Composer workflow.

**Comment by greg-1-anderson** [comment]
Okay.  The D8 composer workflow should get a lot better with today's Drupal-8.0.0-beta16 release.
