### ISSUE TITLE
Drush broken since conf_path() has been removed from Core

### ISSUE THREAD

**Issue by DuaelFr** [drush-ops/drush#1651]
See [#2573443 Remove conf_path() from core](https://www.drupal.org/node/2573443) commited 4 hours ago.

**Comment by weitzman** [comment]
Please update your drush to newest dev-master. We fixed this in #1631

**Comment by DuaelFr** [comment]
Arg I ran composer global update before reporting (I am laready on dev-master) but I had to re-require it to have that last update... Sorry :/
