### ISSUE TITLE
Drush commands related to db fail when using aliases but succeed with --db-url

### ISSUE THREAD

**Issue by WebmasterMFO** [drush-ops/drush#1656]
Hello,

I am using Drush 6.3.0 on a shared hosting.

**Drush does not seems to work with dabatase connection parameters when they are declared in aliases although it does connect when I append them to the command using -db--url**

I have tried several commands such as sql-connect, sql-dump, in two different ways: 

* appending --db-url parameters with my db credentials, 
**both commands work**

* using an alias. Here, I am trying both methods to specify db connection parameters:
   * with 'db-url' as part of the connection key array
   * with 'databases' array as part of the connection array

**They both make the commands fail, although I am using the same credentials**

I have to specify the db connection parameters since the database I am working on is on a different server than Drupal.

**Comment by weitzman** [comment]
I'm not sure if this is a bug, but we cant look into it until you verify on a supported version of drush - ideally the master branch.
