### ISSUE TITLE
Document that --uri should be a full URL

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#1668]
Now that [D8 does not support setting base_url in settings.php](https://www.drupal.org/node/2529168), its imperative that folks pass --uri=http://example.com using config or site alias. Otherwise, commands like browse and user-login will return bad urls. ping to @greg-1-anderson who may know what docs need to be updated.

**Comment by greg-1-anderson** [comment]
Touched up the documentation pages that mention uri.
