### ISSUE TITLE
drush en might not run the locale_modules_installed() batch

### ISSUE THREAD

**Issue by YesCT** [drush-ops/drush#1670]
while reproducing a bug in https://www.drupal.org/node/2580575#comment-10419447
noticed that doing the steps with drush did not reproduce the bug, but doing manual manual did.

@alexpott thought maybe drush module install and locale_modules_installed() might be broken
and guessed it is that drush en book does not run the batch locale_modules_installed() creates

**Comment by weitzman** [comment]
Who does run that batch?

**Comment by vijaycs85** [comment]
@weitzman it's part of hook_modules_installed in locale module. This hook is invoked in Drupal\Core\Extension\ModuleInstaller::install()

```php
    // If any modules were newly installed, invoke hook_modules_installed().
    if (!empty($modules_installed)) {
      \Drupal::service('router.builder')->setRebuildNeeded();
      $this->moduleHandler->invokeAll('modules_installed', array($modules_installed));
    }
```


I just tested this in my local. Looks like it's just the matter of running batch as part of drush command doesn't work.

**Comment by vijaycs85** [comment]
replacing `batch_process()` with `drush_backend_batch_process` throws error:

```shell
drush cget system.site name && drush pb && drush cget system.site name --verbose
'system.site:name': 'My site name - 1481998626'

Command batch-process needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal [error]
environment to run this command.
The drush command 'batch-process 88 88' could not be executed.                                                            [error]
Drush was not able to start (bootstrap) the Drupal database.                                                              [error]
Hint: This may occur when Drush is trying to:
 * bootstrap a site that has not been installed or does not have a configured database. In this case you can select
another site with a working database setup by specifying the URI to use with the --uri parameter on the command line. See
`drush topic docs-aliases` for details.
 * connect the database through a socket. The socket file may be wrong or the php-cli may have no access to it in a jailed
shell. See http://drupal.org/node/1428638 for details.
```

**Comment by weitzman** [comment]
That error looks unrelated. Drush pb?

I see that batch_set() is called in locale_modules_installed(). I assume it is form API that actually calls batch_process() when the Modules page is submitted. So yes, we should add a drush_backend_process() call so various pm operations - I'm not sure which ones. Would be great to get input from @jonhattan here.

**Comment by vijaycs85** [comment]
@weitzman pb is a simple drush command I created to test this issue. The Drupal\Core\Form\FormSubmitter::doSubmitForm() handles the batch_process. So, we might need to handle globally, instead of just pm commands?

**Comment by weitzman** [comment]
Maybe we could run any pending batches after the main command callback has fired but that feels pretty wrong to me. Dont they sometimes have custom argument, options, etc? Lets have commands do batch processing as needed for now.

**Comment by jonhattan** [comment]
So this is also a bug in Drupal 7, where the same mechanism is used.

**Comment by jonhattan** [comment]
@weitzman batches don't have args and options. We just use that for the respawn of our batch-process command.

For Drupal 6, we do a submission of the modules form in `drush_module_enable()`. I think we can just do `drush_backend_batch_process()` for Drupal 7, 8. Anyway this should wait until 8.0.1

**Comment by weitzman** [comment]
This got done https://github.com/drush-ops/drush/blob/5b7ebf84f9e644a647035cebc1969c5a99bd8936/src/Drupal/Commands/pm/PmCommands.php#L98
https://github.com/weitzman/drush/blob/5b7ebf84f9e644a647035cebc1969c5a99bd8936/src/Drupal/Commands/pm/PmCommands.php#L98
