### ISSUE TITLE
#1595 broke Drush on Windows

### ISSUE THREAD

**Issue by mikeker** [drush-ops/drush#1672]
```
while (!empty($c) && ($c != "/")) {
```
results in an endless loop as PHP on Windows return "c:\" (or similar) at the root directory. PR coming shortly.

**Comment by mikeker** [comment]
#1595 because GitHub doesn't provide automated references if you mention an issue in the title...

**Comment by mikeker** [comment]
#1673 is the first step.

**Comment by weitzman** [comment]
FYI, when we committed the finder/launcher split we said that WIndows folks would temporarily need to use drush.bat, and skip the finder entirely.
