### ISSUE TITLE
Drush did not allow to upgrade to Drupal 8.0.0-rc1- after manuel update did not work and give same error that when try to update =>

### ISSUE THREAD

**Issue by orfils** [drush-ops/drush#1675]
root@ns315737:/srv/drupal8/portaladuc8# drush cache-rebuild all
PHP Fatal error:  Call to undefined function conf_path() in /root/.composer/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php on line 388
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                                                [error]
Error: Call to undefined function conf_path() in /root/.composer/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php, line 388
root@ns315737:/srv/drupal8/portaladuc8# drush --version
 Drush Version   :  8.0-dev

**Comment by weitzman** [comment]
You need to be running Drush8-rc1 - released this morning.

**Comment by orfils** [comment]
Yes it was done but the problem was I am guess with drush version and drush work now on installed drupal 8-rc1 version after update  drush to the last-last version =>

=> root@ns315737:~# /usr/local/bin/composer self-update
Updating to version 7a9eb02190d334513e99a479510f87eed18cf958.
    Downloading: 100%         
Use composer self-update --rollback to return to version 833ce984264204e7d6576ab082660105c7d8f04c

and then

=> root@ns315737:~# composer global require drush/drush:dev-master
Changed current directory to /root/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Writing lock file
Generating autoload files

and then when use drush it works =>
root@ns315737:/srv/drupal8/portaladuc8# drush cache-rebuild all
Cache rebuild complete.  

Thanks
