### ISSUE TITLE
Drush 8.0.0-rc1 won't bootstrap

### ISSUE THREAD

**Issue by danepowell** [drush-ops/drush#1683]
I recently upgraded from Drush 7 to Drush 8.0.0-rc1. It works fine on Drupal 8 sites, but is failing to find a valid Drupal installation (and consequently failing to bootstrap) on a Drupal 7 site. For instance, `drush cc all` (while in the docroot) leads to the error message "No Drupal site found, only 'drush' cache was cleared."

If I provide the path to the docroot (`drush --root=/path/to/docroot cc all`) it works fine.

**Comment by weitzman** [comment]
Perhaps you are using site-set command? In any case, I think you'll have to debug this and report back as it is working locally.

**Comment by danepowell** [comment]
Not sure what was causing this, but upgrading both the global and package drush versions from 8.0.0-rc1 to dev-master fixed the problem. My guess is that b9e2b1c7560cb5863572560bc6158398823cff91 was the fix.
