### ISSUE TITLE
Install multisite on fresh D8 fail if DRUPAL/sites/sites.php does't exist

### ISSUE THREAD

**Issue by GuilleW** [drush-ops/drush#1686]
Hello,

I try to install D8 from drush on Debian server, it fails with *"Unable to find a matching SQL Class"*. However, it's not the real issue.

### Drush 8 installation:
```shell
composer global require drush/drush:8.0.0-rc1
```
OK

### Drupal 8 installation:
```shell
drush dl drupal-8-dev --yes --destination=/var/www --drupal-project-rename=drupal-8.x
```
OK

### Install website
I create folder "DRUPAL/sites/d8.domain.tld" with a working settings.php (got it from previous D8 install with interface)
Now, i try to install a multisite website:
```shell
drush --root=/var/www/drupal-8.x --uri=d8.domain.tld -y si
```
ERROR
```shell
exception 'Drush\Sql\SqlException' with message 'Unable to find a matching SQL Class. Drush cannot find your database connection details.' in /root/.composer/vendor/drush/drush/commands/sql/sql.drush.inc:597      [error]
Stack trace:
#0 /root/.composer/vendor/drush/drush/commands/core/site_install.drush.inc(107): drush_sql_get_class()
#1 [internal function]: drush_core_pre_site_install()
#2 /root/.composer/vendor/drush/drush/includes/command.inc(364): call_user_func_array('drush_core_pre_...', Array)
#3 /root/.composer/vendor/drush/drush/includes/command.inc(215): _drush_invoke_hooks(Array, Array)
#4 [internal function]: drush_command()
#5 /root/.composer/vendor/drush/drush/includes/command.inc(183): call_user_func_array('drush_command', Array)
#6 /root/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(62): drush_dispatch(Array)
#7 /root/.composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 /root/.composer/vendor/drush/drush/drush.php(11): drush_main()
#9 {main}
```

### FIX
Create an empty files "sites.php" in "DRUPAL/sites/"
Now it works !
Nothing about SQL...

I know Drupal 8 creates this file when using web interface install (with comments inside).
Can Drush creates this file on site install...?

**Comment by weitzman** [comment]
We already create a sites.php in drush_core_pre_site_install(). Perhaps you can debug and see why it is not working for you.

**Comment by GuilleW** [comment]
> We already create a sites.php in drush_core_pre_site_install() 

Indeed, but sites.php is created later.
The problem occurs at the first line inside this function: drush_sql_get_class()
```php
function drush_core_pre_site_install($profile = NULL) {
  $sql = drush_sql_get_class();
```

These commands work:
```shell
drush --root=/var/www/drupal-8.x --uri=d8.domain.tld -y si --db-url=mysql://root:pass@localhost:port/dbname
# with empty sites/sites.php and sites/d8.domain.tld/settings.php with correct MySQL driver
drush --root=/var/www/drupal-8.x --uri=d8.domain.tld -y si 
```

If I remove sites/sites.php and run 
```shell
# with sites/d8.domain.tld/settings.php with correct MySQL driver
drush --root=/var/www/drupal-8.x --uri=d8.domain.tld -y si 
```
I got exception in first post.

Digging...

**Comment by GuilleW** [comment]
I found that:
```
/var/www/drupal-8.x/core/lib/Drupal/Core/Database/Database.php(271): self::$databaseInfo  <<<---- [[[ IS EMPTY ]]]
/root/.composer/vendor/drush/drush/lib/Drush/Sql/Sql8.php(12): Database::getConnectionInfo($database)
/root/.composer/vendor/drush/drush/commands/sql/sql.drush.inc(591): $sqlVersion->get_db_spec()
/root/.composer/vendor/drush/drush/commands/core/site_install.drush.inc(107): drush_sql_get_class()
```

The problem is not in Drush itself...
For some reason *Drupal/Core/Database/Database.php* doesn't load my *settings.php* if *sites/sites.php* doesn't exist (I stopped digging here, so I don't know why).

**Comment by GuilleW** [comment]
I just move $sitesfile and add a touch(), and it works.

```php
function drush_core_pre_site_install($profile = NULL) {
  $sitesfile = "sites/sites.php";
  touch($sitesfile);
  $sql = drush_sql_get_class();
```

**Comment by weitzman** [comment]
We dont want unconditionally create a sitesfile like that. By copying settings.php, you did half of a manual install of your site. The ogther half is sites.php. You need to do none or both. sites.php is a new requirement for Drupal 8 when using Drupal's multisite feature.

**Comment by drzraf** [comment]
I'm getting the exact the same behavior than OP
At the very least, `--debug` should give information about which directory `drush_conf_path()` is trying before failing-back on the `default`
The `sites.php` requirements is hard to find and is not ensured in a meaningful manner.

**Comment by weitzman** [comment]
--debug does say what site_path is in use, as does `drush status`

**Comment by drzraf** [comment]
Yes it does as:
> Initialized Drupal site blahfoobar at sites/default [0.13 sec, 9.32 MB]

But when such a message arises, it's pretty hard to understand why it chose "default" rather than  "sites/blahfoobar".
* Was "blahfoobar" unreadable?
* Was "blahfoobar/settings.php" unreadable?
* Was "blahfoobar/settings.php" not containing a correct $db definition?
* Was the (D8-mandatory)"sites.php" absent?

Having `drush_conf_path()` showing how it iterates over its recognized possibility could help tracking down such an issue.

**Comment by weitzman** [comment]
PRs welcome on this..
