### ISSUE TITLE
Please provide a command to enable a dev version of a module

### ISSUE THREAD

**Issue by kopeboy** [drush-ops/drush#1691]
Usually you would type 'drush en MODULE -y'
but then you have to annotate separately the modules for which you need a dev (or specific) version because the required command is first 'drush dl ...' and THEN 'drush en ..'.

And since some modules may require other modules' specific versions too, you end up with a long list of convoluted instructions on your notes, instead of a single paragraph to copy-paste to kickstart your site :)

Can't we have 'drush en MODULE-2.x-dev -y'?
Thanks

**Comment by weitzman** [comment]
So your issue is that pm-download and pm-enable are separate commands? We have reserved the pm-install command name for this feature when it arrives. But no code has been written for it (that I know of) Be warned - its more complicated than it looks. See http://drupal.org/node/112692.

**Comment by jonhattan** [comment]
It is feasible, but adds more complexity I'm not sure if worth it.

One case to consider: how should we proceed when you have MODULE-1.1 available (downloaded or even enabled) and perform `drush en MODULE-2.x-dev -y`?

**Comment by greg-1-anderson** [comment]
The pm-install case is most compelling for projects that have only a single module. Once you start having multiple modules per project, it becomes more difficult. See the issue @weitzman linked to.
