### ISSUE TITLE
drush 8 on windows

### ISSUE THREAD

**Issue by MrPhilbert** [drush-ops/drush#1696]
The install instructions for drush 8 on windows need corrections.

They say to add the drush/drush folder to your system path. This is not needed as long as drush is installed in the composer/vender bin directory and that directory is in your system path.

Also, when executing the "drush" command from git bash, it will try to open drush.launcher (which windows does not know what to do with). Instead, type drush.php and you'll get access to drush. If you would like to just enter "drush" instead go to you your home directory (user directory) and create or open .bashrc and add "alias drush="drush.php"" without the outside quotes. Next time you open git bash and type drush, all your drush options will be available.

**Comment by kenorb** [comment]
I can confirm that.

I've added `~/AppData/Roaming/Composer/vendor/bin` to my `PATH`.

- `drush`, `drush.bat` points to `drush.launcher` (popup: Windows can't open this file)
- `drush.php` just points to shell script

The only binary which works correctly is `drush.php.bat`.

**Comment by greg-1-anderson** [comment]
What is `drush.php.bat`?  Did you mean `drush.bat` or `drush.php` or something else?

We do not really sanction calling `drush.php` directly; while it still has the shebang at the top that makes this possible, we might remove that in #1693  to support a drush phar.

**Comment by kenorb** [comment]
I've `drush.php.bat` and other corresponding batch files for each script, if they're not coming from drush, then maybe there were created by Composer during the install?


	C:\Users\925309\AppData\Roaming\Composer\vendor\bin>ls -la
	total 18
	drwxr-xr-x 1 925309 1049089   0 Oct 20 14:45 .
	drwxr-xr-x 1 925309 1049089   0 Oct 20 14:01 ..
	-rwxr-xr-x 1 925309 1049089 132 Oct 20 13:57 drush
	-rw-r--r-- 1 925309 1049089  77 Oct 20 13:57 drush.bat
	-rwxr-xr-x 1 925309 1049089 144 Oct 20 13:57 drush.complete.sh
	-rw-r--r-- 1 925309 1049089  89 Oct 20 13:57 drush.complete.sh.bat
	-rwxr-xr-x 1 925309 1049089 141 Oct 20 13:57 drush.launcher
	-rw-r--r-- 1 925309 1049089  85 Oct 20 13:57 drush.launcher.bat
	-rwxr-xr-x 1 925309 1049089 136 Oct 20 13:57 drush.php
	-rw-r--r-- 1 925309 1049089  81 Oct 20 13:57 drush.php.bat
	-rwxr-xr-x 1 925309 1049089 134 Oct 20 13:56 psysh
	-rw-r--r-- 1 925309 1049089  79 Oct 20 13:56 psysh.bat

	C:\Users\925309\AppData\Roaming\Composer\vendor\bin>type drush.php.bat
	@ECHO OFF
	SET BIN_TARGET=%~dp0/../drush/drush/drush.php
	php "%BIN_TARGET%" %*

**Comment by kenorb** [comment]
The other interesting thing which I've found, that `drush.bat` which is in `bin/` isn't the same as one from Drush package.

	925309@UK868678  /c/Users/925309/AppData/Roaming/Composer/vendor
	$ find . -name drush.bat -ls
	562949953702214    1 -rw-r--r--   1 925309   1049089        77 Oct 20 13:57 ./bin/drush.bat
	562949953701942    4 -rw-r--r--   1 925309   1049089       759 Oct 20 13:57 ./drush/drush/drush.bat
	562949953702074    1 -rw-r--r--   1 925309   1049089       193 Oct 20 13:57 ./drush/drush/misc/windrush_build/assets/drush.bat

So the original Drush is in `./drush/drush/drush.bat`, and `./bin/drush.bat` is the Composer one.

	$ cat $(where drush.bat)
	@ECHO OFF
	SET BIN_TARGET=%~dp0/../drush/drush/drush
	php "%BIN_TARGET%" %*

Not sure if this is expected install behavior.

**Comment by weitzman** [comment]
The install instructions now recommend using drush.phar which avoids composer entirely. Well Windows users first are discouraged from using Windows but then they could use drush.phar. See http://docs.drush.org/en/master/install-alternative/#windows - suggestions welcome.

**Comment by weitzman** [comment]
Woops - reopening for feedback.

**Comment by ivanjaros** [comment]
I am using composer as well. No point in fiddling with phar.
Also in Windows drush will throw 'site' error on D7 site when running updb at this moment(8.0.1).
