### ISSUE TITLE
Hostname in "GRANT ALL PRIVILEGES" is incorrect if mysql is located on remote host

### ISSUE THREAD

**Issue by zaporylie** [drush-ops/drush#1702]
I have tried to install drupal 8 using drush on remote mysql server (in private network). If database and user already exists, everything works just fine. Problem is when drush should also create both user and database. Lets say I have drupal on localhost and mysql on remote host called "mysql_db"

````
drush si --db-url=mysql://test_user:test_password@mysql_db/test_database --db-su=root --db-su-pw=root_password
````

> SQLSTATE[28000] [1045] Access denied

That command will connect to mysql using db-su credentials, create test_database and mysql user (test_user:test_password). And it's all good (works perfect on localhost)! Problem is in [this line](https://github.com/drush-ops/drush/blob/c129ea6ce51f6387d244f57debd04335b9c07dc1/lib/Drush/Sql/Sqlmysql.php#L65). test_user has privileges to connect to mysql_db only from mysql_db (which is not going to happen).

**Comment by weitzman** [comment]
Thanks for the clear bug report. There might be a duplicate somewhere but I can't find it. Would you suggest to simply remove the @host part of the user specification? That way the specified user could connect from any host. I dont know what else to specify for the host part that would be reliable (an ip address or domain name).

**Comment by zaporylie** [comment]
I couldn't find any existing issue touching that problem as well. 

I thought that '%' instead of fixed host would be the simplest way to fix it. Of course it's not perfect since it makes database connection less secure but it's definitely not something we should be worried about since:
- it fixes existing bug
- can be changed at any time by anyone with root access
- remote access can be limited on mysql level

Let me know if you'd like me to create a Pull Request. Or I'll make it anyway - in worst case that will be entrypoint.
