### ISSUE TITLE
Drush si creating a new sites directory instead of using sites/default: how to debug?

### ISSUE THREAD

**Issue by alberto56** [drush-ops/drush#1703]
Hi, this problem started last night: now, drush si -y is creating a new directory with the name of user, instead of using sites/default. How would I go about debugging this?

    [myusername@myserver test]$ drush dl
    Project drupal (7.41) downloaded to /opt/myusername/test/drupal-7.41.                                                                                      [success]
    Project drupal contains:                                                                                                                                        [success]
     - 3 profiles: testing, standard, minimal
     - 4 themes: stark, garland, seven, bartik
     - 47 modules: contextual, update, openid, help, tracker, book, field_ui, dblog, trigger, locale, comment, text, options, list, field_sql_storage, number,
    field, overlay, toolbar, user, color, dashboard, rdf, path, forum, contact, file, simpletest, block, syslog, profile, filter, menu, system, search, taxonomy,
    statistics, translation, php, node, aggregator, blog, shortcut, image, poll, drupal_system_listing_compatible_test, drupal_system_listing_incompatible_test

    [myusername@myserver test]$ drush version
     Drush Version   :  6.5.0 

    [myusername@myserver test]$ cd drupal-7.41/
    [myusername@myserver drupal-7.41]$ echo 'create database testdb'|mysql -uroot -pHIDDENPASSWORD
    [myusername@myserver drupal-7.41]$ drush si -y --db-url=mysql://root:HIDDENPASSWORD@localhost/testdb
    You are about to create a sites/default/files directory and create a sites/default/settings.php file and DROP all tables in your 'testdb' database. Do you want to continue? (y/n): y
    No tables to drop.                                                                                                                                              [ok]
    Starting Drupal installation. This takes a few seconds ...                                                                                                      [ok]
    Installation complete.  User name: admin  User password: HIDDENPASSWORD                                                                                         [ok]
    [myusername@myserver drupal-7.41]$ drush si -y
    You are about to create a sites/myusername/files directory and create a sites/myusername/settings.php file and DROP all tables in your 'testdb' database. Do you want to continue? (y/n): y

Notice at the end it is not using sites/default, but sites/myusername

**Comment by weitzman** [comment]
I suspect that a config file is setting the sites-subdir option to myusername. Looks for a drushrc.php file in one of the 6 locations mentioned in https://github.com/drush-ops/drush/blob/6.x/examples/example.drushrc.php

**Comment by alberto56** [comment]
Thanks! Actually it turns out this was caused by #159, which is not integrated into drush 65.
