### ISSUE TITLE
Add a config-validate command

### ISSUE THREAD

**Issue by cweagans** [drush-ops/drush#1704]
We've already run into a couple of instances where a stray config file got committed in a PR, nobody noticed it, and it broke configuration import due to a missing dependency or something. It would be awesome if we could run `drush config-validate [config dir]` to run some sanity checks on the config in our CI process and locally on dev workstations.

It would be *really* cool if this could work without a working Drupal install at all so that we could run it before `drush si`. This way, the tests can fail early without installing Drupal and attempting to import the config. For that, maybe have an argument to specify a directory where config is exported to (the actual path to the dir, rather than the name configured in settings.php)?

I might work on this over the weekend if nobody beats me to it.

**Comment by greg-1-anderson** [comment]
I think that the config-import should fail if this happens, although Drush currently does not do a good job at reporting this error.  I think it would be a good idea to have a config-validate command, and perhaps the right thing for Drush to do is to use the same API prior to config-import.

I'm not sure that this stuff will work without an installed Drupal site, though. Perhaps the best you can do for CI is to fail right after the site-install. It would be cool if validation could be done without a site, but if it can't, I don't think it would be good to attempt to do our own validation with duplicate code.

**Comment by weitzman** [comment]
I can't really envision this command. Please reopen when some prototype code arises,
