### ISSUE TITLE
Could config-get --include-overridden

### ISSUE THREAD

**Issue by anavarre** [drush-ops/drush#1710]
Gábor raised a good point in https://www.drupal.org/node/2408549#comment-10491456

What if we use the `--include-overridden` parameter but we have config variants based on time of day, role of user, organic group being viewed, etc? Is there any way to make the parameter more context-aware somehow?

Similarly, if we have several levels of overrides (e.g. one in `setting.local.php` and one at the very last line of `settings.php`) could/should that be taken into account?

**Comment by weitzman** [comment]
The Drupal API only allows you to get the value with overrides applied or the "storage value" which is raw, without overrides. Not much else that Drush can do. If you want a value for a certain time of day or organic group, you have to setup your Request so we have the right context set when we call `$config->get();` (with override) or `$config->read($config_name);` (raw). 

And no, Drush cannot distinguish between an ovderride set in settings.local.php versus one set in settings.php
