### ISSUE TITLE
Global drush 8.x causes sql-cli to hang at "proc_open(...)"

### ISSUE THREAD

**Issue by Shaun-Dychko** [drush-ops/drush#1712]
`drush sql-cli` hangs on Mac OS X with MAMP (PHP 5.6.10). Other drush commands work fine, such as `drush sql-connect` and `drush sql-query`, so connection to the DB works. `drush sql-cli` also works with these same Drupal 7 sites hosted on different linux servers, one of which has the exact same version of drush, so I suspect the issue is with my Macbook, but I'm flummoxed. I ran `drush --debug sql-cli` and it gets to the line
```
Calling proc_open(mysql <various arguments>...
```
This is the case both with drush 7.0.0 and with drush 6.6.0. There aren't any error messages in the PHP log. Any pointers on how I could troubleshoot? I also moved ~/.drush in case something there was getting in the way.

**Comment by Shaun-Dychko** [comment]
Oh, an interesting observation: if I remove ~/.composer/vendor/bin from my PATH and execute drush using ../vendor/drush/drush/drush from the site root, then `drush sql-cli` works! There's an issue with having drush 8.x installed globally with composer not handing off properly to the version installed locally with the site for this particular `sql-cli` command.

**Comment by weitzman** [comment]
I can reproduce this if I force the drush_startup() to go through the passthru() code branch. Assigning to @greg-1-anderson

**Comment by greg-1-anderson** [comment]
Maybe passthru doesn't do the right things with STDIN or tty setup or something.  Might need proc_open in startup.inc to fix.

**Comment by weitzman** [comment]
fixed in 75aa74f
