### ISSUE TITLE
Downloading Drupal.org modules doesn't work

### ISSUE THREAD

**Issue by ZeiP** [drush-ops/drush#1713]
Downloading Drupal.org modules doesn't seem to work with Drush any more, apparently because of a requirement for compression by the updates.drupal.org server. A quick workaround to partly fix this is available at http://zeip.eu/~zeip/drush.patch – if Drupal.org doesn't revert their conf it's obviously necessary to also figure out the correct wget command options.

**Comment by thewilkybarkid** [comment]
Output appears like:

```
simplexml_load_file(): I/O warning : failed to load external entity "" Project.php:72               [warning]
Failed to get available update data from https://updates.drupal.org/release-history/admin_menu/7.x  [error]
```

**Comment by PieterDC** [comment]
This issue got linked from https://www.drupal.org/node/2602264 "A lot 7.x module history requests return 404 Page not found".

**Comment by ZeiP** [comment]
Yeah, apparently there's also another error causing some release histories (at least) to return a 404 error even if the request has the correct headers. That issue (and quite possible also this one) is related to this: https://www.drupal.org/node/2602264

**Comment by alexpott** [comment]
Once you have the error on a particular project you need to run "drush cc drush" to clear any cached responses.

**Comment by bartfeenstra** [comment]
Using `curl --compressed` directly proves Drush cannot fully work around this.

**Comment by alexpott** [comment]
I agree - I don't think that we should fix this in Drush

**Comment by thewilkybarkid** [comment]
@alexpott A change that could be made though is to fallback to cached copies where possible (and emit a warning), rather than just breaking. This would allow builds that aren't updating/adding anything to happen.

(I haven't checked whether copies are cached, but I'm guessing not.)

**Comment by anthony-o** [comment]
Or make Drush support gzip encoding and send correct headers ? `wget https://updates.drupal.org/release-history/linkit/7.x --header="accept-encoding: gzip" -O - | gunzip -c` works (as said in https://www.drupal.org/node/2602264)

**Comment by jordandukart** [comment]
As per https://www.drupal.org/node/2602264 one of their servers lost an NFS mount, works again.

**Comment by ZeiP** [comment]
I think using compression for downloads should still be considered, even if the D.org issue is now fixed. Perhaps this issue should be reopened and the title changed?

**Comment by PieterDC** [comment]
Please don't reopen the ticket with a changed title.
Please do create a new issue to consider using compression for downloads, attach the patch you already have and reference this issue.

**Comment by weitzman** [comment]
Please make a new PR if you want that. But be warned ...

I dont think it matters much, considering that update XML is pretty small, and Drush caches it. I know that some CI systems rebuild from scratch all the time but most offer the option to cache directories.

**Comment by kenorb** [comment]
404s could be related to this: https://www.drupal.org/node/2602570
