### ISSUE TITLE
Incorporate database backup into 'drush up drupal'

### ISSUE THREAD

**Issue by AlexShapka** [drush-ops/drush#1714]
Hi,

I only could find http://drupal.stackexchange.com/questions/4228/does-drush-up-do-a-database-backup-dump about the subject matter and decided to ask drush developers what's the rationale not to include the database backup in `drush up drupal` command. They always run `drush sql-dump` before updating core anyway, so why not make it easy for lot's of drush users by including the database backup into the document root backup that `drush up drupal` takes before executing the actual upgrade?

And if there is some serious reason not to include the database backup, then could anyone point out how I could check if there is a Drupal core update/upgrade before running actual upgrade to decide to take or not the database dump. I've filed a support request on http://drupal.stackexchange.com/questions/178798/make-drush-to-dump-database-conditionally/178814#178814, but nobody seems to have good solution for this.

**Comment by weitzman** [comment]
See Stackexchange

**Comment by AlexShapka** [comment]
Thanks Moshe. Is there any chance to eventually get database backup included in `drush up drupal`

**Comment by weitzman** [comment]
No. 

> The Unix philosophy emphasizes building short, simple, clear, modular, and extensible code that can be easily maintained and repurposed by developers other than its creators. The Unix philosophy favors composability as opposed to monolithic design.

- https://en.wikipedia.org/wiki/Unix_philosophy
