### ISSUE TITLE
hook_update_projects_alter() support for pm-statusupdate

### ISSUE THREAD

**Issue by akamustang** [drush-ops/drush#1715]
I remove modules that I don't want to check updates for with hook_update_projects_alter(), but pm-statusupdate still tries to check their update history.

**Comment by weitzman** [comment]
Try using --lock to exclude modules or --update-backend=drupal.

**Comment by jonhattan** [comment]
@akamustang please test #1792. Patch file is https://patch-diff.githubusercontent.com/raw/drush-ops/drush/pull/1792.patch

**Comment by greg-1-anderson** [comment]
Tracking in #1792
