### ISSUE TITLE
drush builds without composer

### ISSUE THREAD

**Issue by sint** [drush-ops/drush#1718]
There is no way to setup Drush >7 on a server level by any package management system. Please support servers! I run a couple of servers with only one Drupal system on a single server. Developers demand Drush and i don't want to research every drush update by hand to copy files again and again and again.

This is what Linux is superior to other systems. There is a package management!

**Comment by weitzman** [comment]
Packages are not maintained by Drush core team.

**Comment by sint** [comment]
That's it? I know that packages within Linux are not maintained by Drush. The Problem is not about external Packages. The Problem is that you guys force people to use composer now. Drush above 7 is not working if you just download the tar file from your website.

**Comment by colans** [comment]
@sint : There's a lot of interest is bringing the Debian package back from the dead.  If you'd like to help there, it would be appreciated.  See #2177 .

**Comment by sint** [comment]
@colans thanks allot for this hint. I wasn't around for 2 weeks to respond earlier.

Its kinda interesting to see that people still requesting PHP Software to be installed with Linux package managers instead of composer. It seems like people don't get the beauty and benefits of composer. But i do understand them, i don't get it too.

I had a long debate with the composer guys about their concept of having a package manager without a independent layer of maintainers, their concept of dynamic linking and the lack final builds in composer driven development of PHP software. It contradicts the Linux world which has somewhat ages of experience with it to prevent security disasters or other kind of chaos from happening. The Composer community will stay like it is and the way i see it, it will go down the road into chaos like NPM did.

http://www.haneycodes.net/npm-left-pad-have-we-forgotten-how-to-program/

Because of this situation i don't feel motivated to get into another debate about rescuing a Linux Distribution from loosing PHP software or hacking composer into its current package manager. Gentoo dropped support of Drush and other PHP software and i am not surprised if this happens to Debian as well.

At the end i would love to quote a member of the Composer community:

Well to be completely honest, I only see one problem with (Link into Gentoo Wiki) and that is people. Clinging to their old ways.

https://github.com/composer/composer/issues/4950

There is no need to care! People working with Linux Package Managers are bearded, old rotting people and we will die out soon anyway.
