### ISSUE TITLE
Feature to add command for entity dump

### ISSUE THREAD

**Issue by IRuslan** [drush-ops/drush#1727]
# Motivation
Our team is using drush during 6 years of intensive Drupal development.
From my point of view, one of the missed most needed commands, is ability to dump an object of any entity type. It's handy to debug on remove enviroments. It's similar to Devel tab for node, but for cli and any entity type.

# Solution
What I want is actually to add command similar to user-info command, but with support of 2 arguments: entity type and entity id.
A command callback will make entity_load() with appropriate arguments and output resulted object.

# Further steps
I am really insterested in to provide such feature via pull request, but I want to get advice from experienced Drush maintainers about next points.
1. Will such command be useful for all?
2. Is there any similar funcitonality already?
3. What is the recommended way to output objects into cli? An object will have nested fields, etc. Is there something more friendly than var_dump/print_r?

**Comment by greg-1-anderson** [comment]
1. I'll let @weitzman comment on whether this is useful to have here, or maybe in the devel module.
2. Not that I know of. I frequently use 'drush ev' for this sort of thing.
3. Use the Drush output format system.

The output format system allows you to declare which output formats make sense for your command's output data.  When using the output format system, you do not print any data yourself; instead, you return an array that contains your data.  Typecast objects to arrays for this purpose. This allows folks to decide how they want to see the data, e.g. yaml, json, var_export, etc.

**Comment by IRuslan** [comment]
> Not that I know of. I frequently use 'drush ev' for this sort of thing.

I'm too. But it's pretty anoying to write each time something like
```
drush ev 'var_dump(entity_load("type", "id"))'
```
instead of
```
drush edump type id
```

**Comment by greg-1-anderson** [comment]
Maybe https://www.drupal.org/project/drush_entity is useful.

**Comment by weitzman** [comment]
There is a need for drush entity integration for create/view/edit/delete. I'd like to see such commands mature outside of Drush core. There is relevant code in https://github.com/drush-ops/behat-drush-endpoint/blob/master/behat.d7.drush.inc, migrate module, etc.
