### ISSUE TITLE
Provide strorage filters hook

### ISSUE THREAD

**Issue by anotherjames** [drush-ops/drush#1728]
drush_config_get_storage_filters() uses the new skip-modules parameter, which is great, but as alluded to in the function's doxygen, it could be extended with a hook: https://github.com/drush-ops/drush/blob/master/commands/core/config.drush.inc#L513

Why not just add that hook? :-)

I was thinking of using it to allow specifying a list of specific configuration to be excluded from exports/imports (or possibly the reverse, to only include a specific subset of configuration). A module could be made to allow this to be configured, so that (for example), site administrators could choose certain configuration to be protected in a production environment. The existing config override system may not be suitable for this, as it doesn't allow configuring those overrides within the UI. 

Anyway, that's just a half-thought out idea, but given the idea of this hook is documented, why not just allow it so other modules can implement better ideas?

**Comment by greg-1-anderson** [comment]
The biggest weakness with storage filters currently is that they are not in core, and therefore are bypassed if anyone uses the Drupal admin API to import or export configuration. At BADCamp, I talked with @alexpott about moving filters into core. His thought was that filtering configuration is not a robust solution. It would be better if the configuration for multiple environments could exist together in the configuration exports, and the per-environment data could be selected at access time. This presumes that each site would know what environment it was.

I am not sure which way this will actually start evolving in core, though, so I think that it would be premature to start expanding the behavior of filters in Drush core.

**Comment by weitzman** [comment]
Soirage filters are long removed. See config_split module for Drupal, and its dependencies.
