### ISSUE TITLE
Support for project namespaces

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#1731]
My use case is described in [here](http://drupal.stackexchange.com/q/179393/1908).

Basically I would like to `drush` to recognise the new format introduced in Drupal v7.40, so it can download appropriate projects.

For example:

### Drupal 7

    dependencies[] = project:module (>=version)

### Drupal 8

    dependencies
      - project:module (>=version)

Related:

- [Project namespaces can now be added for module dependencies](https://www.drupal.org/node/2299747)
- [#2205271: Project namespace for dependencies](https://www.drupal.org/node/2205271)

--

### Problem

Currently `drush` fails when specifying sub-modules, for example:

    dependencies[] = date
    dependencies[] = date_views
    dependencies[] = hierarchical_select
    dependencies[] = hs_taxonomy
    dependencies[] = hs_taxonomy_views

fails with:

> No release history was found for the requested project (hs_taxonomy_views).
> No release history was found for the requested project (hs_taxonomy).
> No release history was found for the requested project (date_views).

when enabling modules or installing the site using `quick-drupal`, like:

    drush qd --yes --core=drupal-7 testsite booking_timeslots

**Comment by greg-1-anderson** [comment]
I saw the discussion on project:module, but missed the fact that this is supported now. Drush should definitely support this.

**Comment by kenorb** [comment]
I've updated [`.info`](https://github.com/mycognitive/booking_timeslots/commit/f1d83a2555b12fd530375d13dee5810b4380ef44) file, but it [fails](https://travis-ci.org/mycognitive/booking_timeslots/builds/88640615) (I'm installing the latest `drush:dev-master`), unless I'm missed anything.

**Comment by weitzman** [comment]
Drush does not yet support it, but one day it will. Thats what @greg-1-anderson meant. Help wanted.

**Comment by andypost** [comment]
this still broken for install profiles in core https://www.drupal.org/node/2855026
