### ISSUE TITLE
drush dd can't find modules outside of Drupal root?

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#1733]
I've the following scenario.

I've downloaded Coder module in the following way:

    drush -y dl coder --destination=~/.drush

in order to check my code styling without need of running Drupal core.

However when I'm trying to determine the folder of that module, it's not recognised by `drush`:

    $ drush dd coder
    Target 'coder' not found.

despite `drush coder` command works using that module.

In `drush help dd` I can read:

> Return the filesystem path for modules/themes and other key folders.

which doesn't apply to Drupal root folder only.

Is it something to be improved or it's expected behaviour?

**Comment by weitzman** [comment]
Coder is not a module as recognized by drupal (not in the system_list()) so dd cant find it. By design.
