### ISSUE TITLE
Merge registry_rebuild functionality

### ISSUE THREAD

**Issue by damienmckenna** [drush-ops/drush#1744]
The registry rebuild functionality should be merged into the main module.

https://www.drupal.org/project/registry_rebuild

**Comment by weitzman** [comment]
Core drush doesn't have a registry-rebuild AFAIK. Are you saying it should move *into* Drush? See https://www.drupal.org/node/1447272

**Comment by damienmckenna** [comment]
I've clarified the request, sorry, was in a hurry.

The problem can occur when either a module is moved or a module decides to relocate files that contain classes, as happened with the EntityCache v7.x-1.5 release (https://www.drupal.org/node/2604054), and has happened with many other modules in the past.

**Comment by weitzman** [comment]
I'm going to keep this as Won't Fix for Drush core. We've lived with this in Contrib for over 4 years.

**Comment by damienmckenna** [comment]
FYI catch has reopened the core issue to port D8's rebuild script to D7: https://www.drupal.org/node/2097189

**Comment by albertvolkman** [comment]
We've lived with Views in Contrib for more than that, just saying ;-)

**Comment by damienmckenna** [comment]
And look what happened to Views :-P
