### ISSUE TITLE
Criteria for having functionality added to Drush core?

### ISSUE THREAD

**Issue by damienmckenna** [drush-ops/drush#1746]
Can you please document the criteria used to determine whether something is added to Drush core vs left as a contrib module elsewhere? There are plenty of features in Drush that many people never use, while other features which are often used are left as separate downloads. Some guidance around this would be helpful. Thanks.

**Comment by weitzman** [comment]
Its a balance of competing interests. Some criteria:

* Value of the feature to those who use it
* How broadly used will it be
* Are there alternatives to it living in Drush core?
* Does feature have excellent user experience (i.e. low complexity)
* How maintainable is the code? Does it have an owner?
* Code quality
* Full support for Drush features like remote aliases, argument completion, ...
* Excellent documentation
