### ISSUE TITLE
Stop looking in Drush folder for site aliases, config, and scripts

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#1748]
We do useless scans into Drush itself for aliases and config. Lets remote the ability to put files there for Drush9. It wont easily work with a .phar anyway.

**Comment by greg-1-anderson** [comment]
I sometimes see folks customizing their Drush installs by putting stuff here, and it makes me cringe. We don't use this facility ourselves, and any use of this feature is abusive. I agree we should take it out.

**Comment by jhedstrom** [comment]
Is it too late for Drush 8?

**Comment by greg-1-anderson** [comment]
I second the vote for taking this out in D8.

**Comment by weitzman** [comment]
Personally, I think there isn't a need to surprise folks at the last minute on this. Do you have any specific reason to need this?

**Comment by greg-1-anderson** [comment]
Nope. It can wait for D9 as far as I am concerned. It's just the wrong place to put custom stuff philosophically. You are probably right that this change might surprise some or make them not upgrade to D8, so I guess I don't care that much.

**Comment by weitzman** [comment]
Also stop searching inside Drush for scripts.
