### ISSUE TITLE
More PsySH hotness

### ISSUE THREAD

**Issue by bobthecow** [drush-ops/drush#1754]
You should check out @grota's [drush-psysh](https://github.com/grota/drush-psysh). It proxies drush commands inside the REPL, which is super rad :)

**Comment by weitzman** [comment]
Psysh is in core drush already

**Comment by bobthecow** [comment]
Yep. But I'm talking about incorporating features of drush-psysh that core doesn't yet have :)

**Comment by weitzman** [comment]
I don't see what you refer to. Please be specific about what you think core
is missing.

**Comment by bobthecow** [comment]
> It proxies drush commands inside the REPL, which is super rad.

**Comment by bobthecow** [comment]
So, for example, you can run `cache-clear`, or `role-list`, or really any other drush command, while inside a REPL session.

**Comment by weitzman** [comment]
thats kinda neat. @damiankloip is our de facto psysh maintainer so lets get his opinion.

**Comment by damiankloip** [comment]
I did see that project, indeed has some awesome stuff in! We could easily bring this into drush core - the creation of the commands for the shell.

We would not want to use that project in it's entirety as it has it's own command file, and install command. We already have commands and dependencies.

So, in a nutshell, yes!

**Comment by damiankloip** [comment]
OK, added a modified version of drush-psysh as that was not working with this version of drush, but a few fixes later and it's working pretty well! https://github.com/drush-ops/drush/pull/1768
