### ISSUE TITLE
Add pm-projectinfo into Drush core

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#1757]
I would like to add [pm-projectinfo from drush extras](http://cgit.drupalcode.org/drush_extras/tree/pm_extras.drush.inc) into Drush core.

This was discussed before, and pm-projectinfo was relegated to Drush extras due to lack of demand. However, I'd like to be able to rely on it being available in Drush core in the composer-generate command. This is more convenient in the remote case.

**Comment by greg-1-anderson** [comment]
My workaround is:
```
$values = drush_invoke_process($site_alias, "php-eval", array("return drush_get_projects(drush_get_extensions())"), array(), FALSE);
```

**Comment by greg-1-anderson** [comment]
So, I'd still prefer to see this in core, for completeness. The workarounds are inelegant. You can just close this if it is still not desired, though, as my workaround is functional.

**Comment by weitzman** [comment]
I'm ambivalent. If @jonhattan approves, lets bring it into Drush (after removing pm_extras_drush_help())

**Comment by jonhattan** [comment]
I definitely think `pm-projectinfo` is useful. In #1599 I show how to use it to list/remove unused projects:

`ls -d $(drush pm-projectinfo --status=disabled --fields=path --format=list)`
