### ISSUE TITLE
Failing unit test: pmEnDisUnListInfoTest.php

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#1758]
Results are strange. Here is the output of pm-list --status=enabled for the site under test in the failing unit test:
```
 Package      Name                                              Type    Version          
 Core         Internal Dynamic Page Cache (dynamic_page_cache)  Module  8.0.0-rc3+10-dev 
 Core         Internal Page Cache (page_cache)                  Module  8.0.0-rc3+10-dev 
 Core         System (system)                                   Module  8.0.0-rc3+10-dev 
 Core         Update Manager (update)                           Module  8.0.0-rc3+10-dev 
 Core         User (user)                                       Module  8.0.0-rc3+10-dev 
 Development  Devel (devel)                                     Module  8.x-1.x-dev      
 Field types  File (file)                                       Module  8.0.0-rc3+10-dev 
```
Looks like a minimal install?  A site I install via `drush qd` has a more normal-looking (standard profile install) list of enabled modules.

**Comment by greg-1-anderson** [comment]
The other thing I wanted to mention is that this started happening with a documentation commit, so it seems to be caused by a change in Drupal, not a change in Drush.

**Comment by jonhattan** [comment]
@greg-1-anderson the output of `pm-list` is correct. It corresponds with the `testing` profile.

Tests are failing because classy --the theme enabled by testing profile-- is now a hidden theme. Ref https://www.drupal.org/node/2574975

**Comment by greg-1-anderson** [comment]
Oh, my test was bad, because I forgot that we use the testing profile. Thanks!
