### ISSUE TITLE
make with custom themes in info file fails

### ISSUE THREAD

**Issue by fuzzy76** [drush-ops/drush#1759]
At some point ```projects[zen][version] = "5.4"``` was enough for downloading the zen theme (as it should according to the example.make file). But with the latest drush, the theme is downloaded to sites/all/modules instead of sites/all/themes unless you add a type key.

**Comment by daften** [comment]
See #1627 
Didn't commit #1684 fix this?

**Comment by daften** [comment]
Apparently, part of the revert commit was reverted again in this commit : https://github.com/danepowell/drush/commit/4066da0a020faeb3224fd658de1d41b26f4552e5

It should be noted exactly why this is done, because the commit message doesn't explain enough IMO.

And this is a breaking change that has happened twice now, can this at least be documented properly? :)

**Comment by ergonlogic** [comment]
Can someone provide a sample makefile that illustrates this behaviour on Drush's master branch?

**Comment by fuzzy76** [comment]
I don't have a server with a newer Drush available right now, but dropping the line in my original post into any make-file (like https://github.com/drush-ops/drush/blob/master/examples/example.make ) should show the behaviour.

**Comment by ergonlogic** [comment]
example.make doesn't build properly because of an invalid patch and git branch. But removing those so that it does build, then adding `projects[zen][version] = "5.4"` does indeed show that it was downloaded to `sites/all/modules/contrib/`. Here's a simpler makefile illustrating the behaviour:

    core = 7.x
    api = 2

    projects[] = drupal
    projects[zen][version] = "5.4"
    defaults[projects][subdir] = "contrib"

**Comment by ergonlogic** [comment]
Adding `projects[zen][type] = "theme"` puts it in the correct place. The defaults must not be getting overridden by the data retrieved from update.drupal.org.
