### ISSUE TITLE
drush dl module gives error touch(): Utime failed: Operation not permitted filesystem.inc:273 

### ISSUE THREAD

**Issue by therobyouknow** [drush-ops/drush#1762]
When I download a module using drush, e.g.:
drush dl webform
I get:
touch(): Utime failed: Operation not permitted filesystem.inc:273 

My setup:
puphpet.com-based Vagrant provisioned Ubuntu 14.04 LTS 64bit box. puphpet manifest from 25th October.
Host machine Mac OS X El Capitan 10.11.1
VirtualBox 5.0.8 r103449
Vagrant 1.7.4

Shared folder between host and VM

Versions of drush where problem seen: 5.10 and 7.1.0

Things I tried to stop the error appearing - I ensured that the filesystem permissions were writable for user, group and other:
I edited the puphpet/vagrant/Vagrantfile-local
line: group: sync_group, owner: sync_owner, mount_options: ['dmode=775', 'fmode=774']
to:
group: sync_group, owner: sync_owner, mount_options: ['dmode=777', 'fmode=777']

AND

edited puppet/modules/rvm/manifests/rvmrc.pp
line: $umask = 'u=rwx,g=rwx,o=rx',
to
$umask = 'u=rwx,g=rwx,o=rwx',

and deleted my VM and rebuilt it with these changes
but still no luck, didn't work

So I reverted to the original setup and then tried the following:

I also inserted some debug output into includes/filesystem.inc in drush to see what user it is running as and what file it is trying to touch, here is the result (there are many, all for the files in webform), but here is one:

***WHOAMI ?
vagrant*** dest
/var/www/d7.dev/sites/all/modules/webform/css/webform-admin.css
touch(): Utime failed: Operation not permitted filesystem.inc:279                                                                                                             [warning]

So drush is running as vagrant and it is trying to touch /var/www/d7.dev/sites/all/modules/webform/css/webform-admin.css

this file has the following ownership/group:
-rw-rw-r-- 1 www-data www-data 4497 Nov 10 11:25 /var/www/d7.dev/sites/all/modules/webform/css/webform-admin.css

So the file belongs to www-data whose group is www-data

but vagrant user also belongs to www-data :- 

$ groups vagrant
vagrant : vagrant adm cdrom sudo dip www-data plugdev lpadmin sambashare rvm www-user

I also created my own php file, touch.php : 

<?php
touch("/var/www/d7.dev/sites/all/modules/webform/components/pagebreak.inc");
?>

and ran that (as vagrant, on one of the same webform files)

php -f touch.php

and got no error.

Please advise.

**Comment by therobyouknow** [comment]
Update: Problem has gone away for now
Downloaded puphpet manifest and build VM from scratch
Not sure what the difference is between this and my earlier manifest is, the diff in beyond compare doesn't show anything strikingly different.

**Comment by weitzman** [comment]
In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.
