### ISSUE TITLE
[7.x] Modules in included makefiles do not override the "parent" makefile

### ISSUE THREAD

**Issue by kienanstewart** [drush-ops/drush#1769]
In a case similar to [#1268](https://github.com/drush-ops/drush/issues/1268), specifications to modules included in later makefiles do not override the ones from previous makefiles.

Makefile1

>  projects[webform][version] = 3
>  include Makefile2

Makefile2

> projects[webform][version] = 4

The makefile generation will end up with webform = 3.x

I would expect later includes to override previous entries.

**Comment by ergonlogic** [comment]
Actually, no, this works as expected. The makefile that contains includes should be thought of as a wrapper around the includes. The order they're defined in the makefile is irrelevant.
