### ISSUE TITLE
There was a problem enabling x,y,z.

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#1773]
I'm trying to enable module which has around 35 modules in dependencies in .info file, however I'm having the error instead:

> `drush -vd en news_features`
> There was a problem enabling                                                                                                                                                                                                 
better_exposed_filters,caption_filter,community_content,news_features,entityform_block,flexslider,flexslider_fields,flexslider_views,image_field_caption,lightbox2,service_links,socialfeed,socialmedia,social_media_custom,communityconnect,views_content,widgets,xautoload.

Most of the modules I'm expecting to be already downloaded.

Adding debugging flag didn't help much. How do I check what went wrong? Is there any potential circular dependency which trigger such error?

How do I know exactly which extension caused that? As it's listing me over 30?

I'm using drush 8.0-dev

**Comment by weitzman** [comment]
Run with --debug and you should see what caused the problem. You need to make sure that all modules are present before enabling. The auto-download feature of pm-download is not reliable. Its a best-effort convenience thing.

**Comment by weitzman** [comment]
I mean, please post the --debug here.

**Comment by kenorb** [comment]
As far as I remember, debug didn't show me which module it was. Can't reproduce it now, sorry, so closing.
