### ISSUE TITLE
Difficulties to upgrade drush 7 to 8

### ISSUE THREAD

**Issue by webmasterpf** [drush-ops/drush#1777]
Hi,

After doing what doc says about upgrading with composer, I get 2 differents locations for drush, and the 7 one is using to manage websites.Here are my values:
`~$ drush status
 PHP executable         :  /usr/bin/php
 PHP configuration      :  /etc/php5/cli/php.ini
 PHP OS                 :  Linux
 Drush script           :  /home/webmaster/.composer/vendor/drush/drush/drush.php
 Drush version          :  7.1.0
 Drush temp directory   :  /tmp
 Drush configuration    :
 Drush alias files      :  /home/webmaster/.drush/aliases.drushrc.php

webmaster@vm-server1:~$ php drush.phar core-status
 PHP configuration      :  /etc/php5/cli/php.ini
 PHP OS                 :  Linux
 Drush script           :  /home/webmaster/drush.phar
 Drush version          :  8.0.0-rc4
 Drush temp directory   :  /tmp
 Drush configuration    :
 Drush alias files      :  /home/webmaster/.drush/aliases.drushrc.php
`
this don't change after doing:

`~$ chmod +x /home/webmaster/drush.phar
webmaster@vm-server1:~$ sudo mv /home/webmaster/drush.phar /usr/local/bin/drush
`
So what can I do to fix this ? Because I need Drush 8 to manage D6 ,7 and 8 websites.

Thanks

**Comment by weitzman** [comment]
composer global remove drush-ops/drush

**Comment by webmasterpf** [comment]
seem not to work..

``
$ composer global remove drush-ops/drush
Changed current directory to /home/webmaster/.composer
drush-ops/drush is not required in your composer.json and has not been removed
Package "drush-ops/drush" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

``

**Comment by webmasterpf** [comment]
great :)
```$ drush @d6 status
 Drupal version                  :  6.37
 Site URI                        :  http://default
 Database driver                 :  mysql
 Database hostname               :  localhost
 Database port                   :
 Database username               :  root
 Database name                   :  drupal6_def
 Drupal bootstrap                :  Successful
 Drupal user                     :
 Default theme                   :  garland
 Administration theme            :  garland
 PHP configuration               :  /etc/php5/cli/php.ini
 PHP OS                          :  Linux
 Drush script                    :  /usr/local/bin/drush
 Drush version                   :  8.0.0-rc4
 Drush temp directory            :  /tmp
 Drush configuration             :
 Drush alias files               :  /home/webmaster/.drush/aliases.drushrc.php
 Install profile                 :  default
 Drupal root                     :  /var/www/drupal6
 Site path                       :  sites/default
 File directory path             :  sites/default/files
 Temporary file directory path   :  /tmp
``

**Comment by webmasterpf** [comment]
since I did the upgrade I can't use this :
``$ drush @d6 @sites en webform_protected_downloads -y
ï»¿The drush command '@sites en webform_protected_downloads' could not be found.  Run `drush cache-clear drush` to clear the commandfile cache if  [error]
you have installed new extensions.
``
does it change with drush 8 ?
thanks

**Comment by greg-1-anderson** [comment]
Please do not install Drush -- or any other PHP commandline tool -- using `composer global require`. Please use [cgr](https://github.com/consolidation/cgr) instead. See [Fixing the Composer Global command](https://pantheon.io/blog/fixing-composer-global-command).

**Comment by webmasterpf** [comment]
I'm using cgr as discribed from my reinstall. I will test later.
Thanks
