### ISSUE TITLE
Split '--lock' option into 'make-lock' command

### ISSUE THREAD

**Issue by ergonlogic** [drush-ops/drush#1778]
I only ever use the `--lock` option along with `--no-build` to generate lockfiles. This could be simplified by simply splitting out a 'make-lock' command. Then `--no-build` would be pretty much redundant, and could presumably be removed. `--lock` could then just invoke 'make-lock'.

**Comment by ergonlogic** [comment]
Current behaviour is preserved, but I believe the '--no-build' should probably be dropped.

**Comment by weitzman** [comment]
So lets drop it. OK with you, @jhedstrom ?

**Comment by jhedstrom** [comment]
I'm fine to drop it.
