### ISSUE TITLE
Allow extra arguments to mysqldump in sql-dump command

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#178]
--tab=path, -T path

     Produce tab-separated text-format data files. For each dumped table, mysqldump creates a tbl_name.sql file that contains the CREATE TABLE statement that creates the table, and the server writes a tbl_name.txt file that contains its data. The option value is the directory in which to write the files.

See:
http://dev.mysql.com/doc/refman/5.1/en/mysqldump.html#option_mysqldump_tab
http://stackoverflow.com/a/6300583/55075

**Comment by com2** [comment]
I would like this too, but it would be nice when some arguments / switches could be added by default. I think of the the missing --routines switch. When you work frequently with CiviCRM you need to include stored functions / routines in your dump. With mysqldump you would think that everything is safely backed up until you discover that without this switch the stored functions are missing!
