### ISSUE TITLE
Remove WinRS support

### ISSUE THREAD

**Issue by dmsmidt** [drush-ops/drush#1788]
I would like some guidance for Drush in a setup where the host is running Linux and the Target is running Windows. Maybe this will result in a feature request.

In my aliases file I have the following (simplified, ssh-options and path-aliases can probably be ignored):

```php
$aliases['windows'] = array(  
  'root' => 'C:\Websites\SomeSite',  
  'uri' => 'http://www.somesite.com',  
  'os' => 'Windows',  
  'remote-host' => '124.123.123.123',  
  'remote-user' => 'Windows\\User',  
  'ssh-options' => '-oHostKeyAlgorithms=+ssh-dss -oPubKeyAcceptedKeyTypes=+dsa', 
  'path-aliases' => array(
    '%files' => '/cygdrive/c/Websites/SomeSite/sites/default/files/',
  ),
);
```

I got `ssh` access and rsync working. But the `sql-sync` and `status` commands do not work.
Because the `os` option is set to `Windows` Drush tries to use the `winrs` program for some command (the ones that don't work), but this program is not available under Linux as far as I know.

Any ideas on how to make this work? 
If I were to remove the `os` options I guess the mentioned commands would work because in our case the target Windows machine has the programs needed.
But the `root` path is not processed correctly without this setting.

**Comment by weitzman** [comment]
This is untested. I think Drush should remove winrs and expect that there is an SSH daemon. Any thoughts, @hansfn, @mikeker and others?

**Comment by dmsmidt** [comment]
WinRS was introduced here I think: https://www.drupal.org/node/1149880

I never use a Windows to Windows workflow, but for those people I think it is helpful.
Removing winrs makes maintenance of Drush easier, of course.

Couldn't we force SSH or WinRS usage instead of WinRS with an extra option next to `os` or something? Or would this overcomplicate things.

Or we could split the `os` option into: `host_os` and `remote_os` and switch depending on the `host_os` setting. But I guess it is not so neat to put host config in the config array about a certain machine.

Last thought, make the remote commands also read the @self alias config and check the `os`:
```php
$aliases['self']['os'] = 'linux';
````
And switch ssh/winrs usage based on that. But then again, we could automatically detect the host OS.

**Comment by weitzman** [comment]
Repurposing this issue to remove WinRS support as this issue is the only time its ever been mentioned!
