### ISSUE TITLE
install doc error - files.drush.org does not exist

### ISSUE THREAD

**Issue by bradbulger** [drush-ops/drush#1797]
on http://docs.drush.org/en/master/install/

"Install/Upgrade a global Drush

# Download latest stable release using the code below or browse to github.com/drush-ops/drush/releases.
wget http://files.drush.org/drush.phar

[etc]"

files.drush.org does not exist

**Comment by weitzman** [comment]
http://files.drush.org/drush.phar is working for me. Its mapped to an S3 bucket. Can you paste your verbose log with error message.

Also don't use https.

**Comment by bradbulger** [comment]
some kind of transient DNS failure, i guess. 5 minutes ago i was getting this result:

$ wget http://files.drush.org/drush.phar
--2015-11-20 14:09:05--  http://files.drush.org/drush.phar
Resolving files.drush.org (files.drush.org)... failed: Name or service not known.
wget: unable to resolve host address ‘files.drush.org’
$ whois files.drush.org
NOT FOUND

Now it sees that amazon machine:

$ nslookup files.drush.org
Server:		127.0.1.1
Address:	127.0.1.1#53

Non-authoritative answer:
files.drush.org	canonical name = files.drush.org.s3.amazonaws.com.
files.drush.org.s3.amazonaws.com	canonical name = s3-1-w.amazonaws.com.
Name:	s3-1-w.amazonaws.com
Address: 54.231.98.200
