### ISSUE TITLE
bash completion/prompt broken

### ISSUE THREAD

**Issue by dehnhard** [drush-ops/drush#1799]
[[See this comment for fix](https://github.com/drush-ops/drush/issues/1799#issuecomment-160104122)]

I installed drush 8.0.0 according the officially documented steps (with downloading phar, ... , drush init).
drush works, but not the completion. Instead every prompt shows:

bash: __drush_ps1: command not found
bash: __git_ps1: command not found
[root@mail ~]# 

This is on a practically fresh minimal CentOS7 install. It did work on a previous installation (8.0.0RC4 I think) with the composer based install on a similar system.

**Comment by dehnhard** [comment]
I found the cause and workarounds.

"bash: __drush_ps1: command not found" is caused by absense of the file https://github.com/drush-ops/drush/blob/master/drush.complete.sh 
That file is installed to /etc/bash_completion.d/drush by "composer install". "drush init" doesn't install this file, it probably should install it into .drush and source it from ./drush/drush.bashrc. I guess nobody noticed it, because a developer has most likely run a "composer install" previously on his machine.

To replicate this problem you need a clean system without a previous drush installation.

To work around this problem, download that file manually and source it from your drush.bashrc.

The "bash: __git_ps1: command not found" is also caused by a missing bash completion file. I just hadn't git installed. That git is needed should be mentioned in the installation instructions, but even better would be if an absent git could be silently ignored. There are use cases when you want drush but no git.

**Comment by weitzman** [comment]
Nice sleuthing.

[drush.complete.sh is already sourced from drush.bashrc](https://github.com/drush-ops/drush/blob/8.0.0/examples/example.bashrc#L134-L139). However, the strategy there won't work if your Drush is a phar. A bash script like drush.bashrc doesn't understand how to reach inside a phar. Lets mull over best next step for phar users. Ping @greg-1-anderson

**Comment by weitzman** [comment]
Oh, now I see what you are saying. The init command can copy to ~/.drush/drush.complete.sh. I'll implement that now.

drush,prompt.sh already guards against the __git_ps1 not being available so i'd love to know which line is causing that.

**Comment by weitzman** [comment]
Reopning to see if this fixed init for @dehnhard and also to find out why lack of git is throwing an error.

**Comment by dehnhard** [comment]
Thanks for the fast responses.

I am unsure how to test the changes without taking much time to learn the build process.
Can you advice me about an easy way to get the newest drush.phar onto my composer-less system?

From looking at the code I guess the file still needs to get sourced from the .drush directory?

The git error is coming from the prompt.
You can test it by 
`unset -f __git_ps1` which removes the git completion funtion and results in the 'command not found' on every prompt.
`unset PROMPT_COMMAND` shows that by removing the error message disappears and with
`. /path/to/drush.prompt.sh` it reappears.

So maybe the mentioned guards against absent git are buggy?

**Comment by weitzman** [comment]
@dehnhard - the guard is visible at https://github.com/drush-ops/drush/blob/8.0.0/examples/example.prompt.sh#L15. Maybe those `type` calls are wrong? Not too familiar with `type` myself.

So now drush.complete.sh is sourced by both drush.bashrc and by .bashrc directly. Should we remove the one in drush.bashrc since it can't work for phar users? ping @greg-1-anderson?

**Comment by greg-1-anderson** [comment]
`type -t` is supposed to work like this:
```
$ type -t __drush_ps1
function
```
Without the `-t`, it prints out the entire definition.  It works for aliases, functions, and executable programs, e.g.:
```
$ type -t cat
file
$ type cat
cat is /bin/cat
```
Type is a built-in, so you can't exec it.
```
$ type type
type is a shell builtin
```
Anyway, the code here does need some work to ensure that `drush init` sets things up correctly, and everything still works with the drush.phar.  I don't think we should necessarily remove the part of drush.bashrc that sources drush.complete.sh (no point in breaking folks who are used to it working this way), but we should make sure that it does not cause any problems if it is sourced twice.  I don't expect that should ever be a problem; drush.complete.sh isn't something you'd ever want to customize.

**Comment by dehnhard** [comment]
According to http://stackoverflow.com/a/85903 I'd suggest
````bash
if [ -n "$(type -t __git_ps1)" ] && [ "$(type -t __git_ps1)" = function ] && [ "$(type -t __drush_ps1)" ] && [ "$(type -t __drush_ps1)" = function ]; then
````

**Comment by weitzman** [comment]
Thanks @dehnhard. That code guards properly. Yet once I fixed the guard, I lost my prompt! 

What is happenning for me is that my bash completion is sourced later during .bashrc by the lines below. So __git_ps1 is not available when this prompt file is sourced. 

This is proving difficult to get right. Should we move the include of all the drush files to the end of .bashrc? Perhaps @greg-1-anderson did not do that in order to avoid overrriding something that a user configured later in .bashrc?

    if [ -f `brew --prefix`/etc/bash_completion ]; then
      . `brew --prefix`/etc/bash_completion
    fi

**Comment by dehnhard** [comment]
I thought about .bashrc a bit. 
I do not like it when a program changes a config file, that is in the responsibility of the user, but I see that it does makes sense here.

What about questioning the user? Someting like:
````
drush bash completion installed. You can activate it by calling 'xy.sh'.
Do you want this line added to your .bashrc, so that it's always active? (Y/n)
````
Then unexperienced users can type YES, experienced users can decide themself and someone who has customized his .bashrc is alerted to check it. 
Then it's also not a problem to put that line at the end of the file.

Some more observations:
- Are the files in .drush overwritten by a second call of `drush init`? I tend towards that they should, but with a warning inside the file that this happens.
- The line in .bashrc should only be added if it does not already exist. 
- Have you noticed that the .drush/drush.php generated by `drush init` consists only of empty lines?

**Comment by weitzman** [comment]
Good idea to do a user confirmation and then append to .bashrc. Will implement that now.

1. The files in .drush are not overwritten. 
1. If the file is already in ~/.drush dir, we dont add any corresponding line to .bashrc.
1. I can't reproduce this. Its a straight copy() so quite unusual to end up with an empty file.

**Comment by dehnhard** [comment]
re 1: Ok. So no update management. I guess it may be overkill and won't be a big problem until someone decides to put incompatible or required changes into these config files. 
But I need to remember to delete .drush before running init when getting a new phar file.

re 2: Ok

re 3: I can reproduce it on the system which has only the phar file but no composer - by removing .drush and running `drush init`. Another case of not able to reach into the phar? To be precise the file contains `<?php` at the top and then 312 empty lines, which looks like the correct size of that file, just without the content.

**Comment by weitzman** [comment]
I jus retried using the very latest phar and cant reproduce the 312 blank lines issue. That does sound like a problem reaching into the phar but it looks like php was successful reading the number of lines which is just strange. We suppress errors in these copies with code like this: `@copy($example_bashrc, $drush_bashrc);`. I'm not sure why @greg-1-anderson chose that. One limitation of a phar is that it is hard for end user to modify it. If it were easier I would ask you to remove that @ character and retry.

**Comment by greg-1-anderson** [comment]
Error checking is good; I don't know why it is `@copy`; seems like it should be `copy` everywhere.

Regarding re-install, perhaps a --force option would be handy?

Also, regarding code like this, see https://github.com/drupal-composer/drupal-project/pull/77.  The [Robo filesystemstack](http://robo.li/tasks/FileSystem/#filesystemstack) allows fs operations to be chained together. Seems like we should be using libraries like this (or maybe something similar in Symfony?) rather than maintaining our own. The catch-22 here is that what I am envisioning is having a class like filesystemstack that we could just instantiate and set modes on, like --simulated and --force.  This would reduce the tedium of error checking, and make the code easier to read by eliminating branching. This is a catch-22 because I'd like to re-use a library like Robo (sans its cli parser), but the existing candidates don't support all of the features we'd likely want. I think contribution of enhancements to external solutions over maintenance of internally maintained libraries is a direction we should be moving. See also how the aforementioned PR in drupal-project can simply start using objects, such as \Drupal:version, due to the Composer autoloader. Folks are going to want to use things like this that are easy to start using. The procedural Drush libraries are only available to Drush extensions; I think it's really important to start living in a Composer ecosystem.

Sorry to take a hard-right-turn in the middle of this issue, but I thought this might be a good place to experiment.  We can put in obvious enhancements with existing techniques, if desired.

**Comment by dehnhard** [comment]
@greg-1-anderson You are welcome to discuss technical details here. 
For myself I think it is the best to give feedback in the role of the user who wants to run drush (.phar) on the shell (which coincidentally is part of the work I am doing this week :-).
Spoken from that role, I'd say that I wouldn't care much if there is a `--force` option or not. My main interest is that the installation instructions are leading me to a functional installation. If that means to call `drush --force init` if it's an update, then it's just important that it's documented.
Additionally I am just glad that there is an easier install path than the git/source code/composer based one.

**Comment by dehnhard** [comment]
@weitzman Just an idea: With a patch file against the latest phar release file, I could easily update my phar and test it. Thats with the assumption that a developer can easily create such a patch, of course.

**Comment by weitzman** [comment]
Alas you can't patch a phar.

I removed the error suppression so if you grab a new drush-unstable.phar
you might see why that file ends up with blank lines.

**Comment by dehnhard** [comment]
From where do I grab that?

**Comment by dehnhard** [comment]
Never mind. [Found it](https://files.drush.org/drush-unstable.phar) in the [docs](http://www.drush.org/en/master/install-alternative/) (hint: the link contains a certificate error...)

No error messages though. I got curious, googled a way to extract a phar and found out, that example-drushrc.phar is already empty. Seems to happen in the build process?

The `bash: __git_ps1: command not found` problem is fixed now.

**Comment by neubreed** [comment]
Hi Guys

I recently followed the instructions for installing drush from this page http://docs.drush.org/en/master/install/ which resulted me getting an error that ultimately brought me here .. How do I get rid of this error / uninstall / fix this problem?

**Comment by dehnhard** [comment]
@neubreed to summarize and describe how to fix:

- You need a phar including the fixes above. Until there is a new release after 8.0.0 you can use `https://files.drush.org/drush-unstable.phar`
- To get the new configs you can remove your `~/.drush` directory and run `drush init` with the new phar.
- On entering a new bash, it disappears.

Alternative quick fix without a new phar: Remove the prompt by removing the line
`. /root/.drush/drush.prompt.sh` in your `~/.bashrc`. Error should be gone in a new login shell.

**Comment by dehnhard** [comment]
Closing as original issue is fixed. Moved remaining side issue to #1813.

**Comment by weitzman** [comment]
Drush 8.0.1 has been released and has a fix for these issues and #1813.

**Comment by DrCord** [comment]
I am still getting this issue on Drush 8.0.2

**Comment by cassiel74** [comment]
Still getting on Drush 9, debian box here.

**Comment by calbasi** [comment]
I have this issue just for root user, on Drush 8.1.16
