### ISSUE TITLE
sql-sync doesn't pass --ssh-options through to the core-rsync command

### ISSUE THREAD

**Issue by minorOffense** [drush-ops/drush#1803]
When running the following command in drush 7

``` shell
drush sql-sync @prod @self --ssh-options="-o User=mwinstone"
```

The initial SSH connection is made properly with the SSH options provided. However, once the sql dump is created on the server, when the transfer is attempted, the specified SSH options are lost and another user account is used instead

```
Please enter vagrant@prod.example.com's password: 
```

The SSH options should persist throughout the transaction.

**Comment by weitzman** [comment]
I'm not sure I ever fixed this request, but even if I did I just reverted my fix. We can't support passing global options like this to rsync at this time. Instead, add options like `ssh-options` to your site alias. See

**Comment by minorOffense** [comment]
You had fixed it. And looks like you unfixed it ;-)

What did you want me to see? Your last message got cut off.

**Comment by weitzman** [comment]
Oops - that was just a stray word. I've removed it ... Sorry to unfix this but it caused a worse problem - #1858. Until we have a better workaround, add ssh-options to a site alias (usually on the machine starting the sql-sync - depends on your params)

**Comment by weitzman** [comment]
Dupe of #842

**Comment by minorOffense** [comment]
Drush 9 doesn't appear to have this problem so I'll close it.
