### ISSUE TITLE
make-generate does not output yaml

### ISSUE THREAD

**Issue by lmakarov** [drush-ops/drush#1807]
make-generate outputs using the old .info file format by default. It also does not honor the `--format` flag.

```
docker@cli:/var/www/docroot$ drush --version
 Drush Version   :  8.0.0

docker@cli:/var/www/docroot$ drush make-generate
; This file was auto-generated by drush make
core = 8.x
api = 2

; Core
projects[drupal][version] = "8.0.0"


docker@cli:/var/www/docroot$ drush make-generate --format=yaml
; This file was auto-generated by drush make
core = 8.x
api = 2

; Core
projects[drupal][version] = "8.0.0"
```

**Comment by ergonlogic** [comment]
Hmm, tests passed locally, despite the move to yaml by default. 'MakeGenerate' tests rightly failed on travis. I'll fix the tests.

**Comment by ergonlogic** [comment]
Oops, I just realized that I had only run makeTest locally, figuring that any 'generate' functionality would be part of that suite. testGenerateMake is the one failing on Travis.

**Comment by ergonlogic** [comment]
Okay, finally got tests passing.
