### ISSUE TITLE
Allow site-install to install from tar.gz or zip Drupal archive

### ISSUE THREAD

**Issue by anavarre** [drush-ops/drush#1809]
Say you wish to install a specific version of Drupal that you've downloaded locally. Being able to pass a command similar to `--from=/path/to/archive.tar.gz` would allow not only to specify what version to install but also to rely on a local archive rather than having to perform a remote download. All this in a one-liner and no need for drush make.

Quickly scanning through https://github.com/drush-ops/drush/blob/master/commands/core/site_install.drush.inc I didn't see such feature.

**Comment by greg-1-anderson** [comment]
The site-install command always operates on an already-extracted set of Drupal files.

For a command that will extract files and a backed-up database, and restore a site, see archive-restore.

For a command that will download, extract and install a Drupal site, see core-quick-drupal.

This sort of enhancement might make sense as part of core-quick-drupal, but I don't think that we'd want to alter the bootstrap level of site-install to less than DRUSH_BOOTSTRAP_DRUPAL, which would be what would be required to add this feature.

**Comment by anavarre** [comment]
I understand it would probably be a better fit for `core-quick-drupal` but currently only the `--core` parameter could hold a custom path it seems. I don't really care if this should extract from a tarball or, say, use the files from a local checkout. My only concern is to have to download an archive always which I would like to avoid if at all possible since I'm installing/wiping/reinstalling D8 HEAD several times a day.

I have a test project in which I [git pull from HEAD](https://github.com/anavarre/drupal-8-tools/blob/master/provisioning/functions.sh#L60) and then use [site-install](https://github.com/anavarre/drupal-8-tools/blob/master/provisioning/functions.sh#L212) for that purpose and was thinking about using Drush even more extensively.

Let me please know if you think it's still not reasonable with that context and use case?

**Comment by greg-1-anderson** [comment]
If you just want to re-install your Drupal 8 site, you can run site-install on the already-extracted files. If you want to make sure that the files are in a clean state first, you could check them in to a local git repository, and `git reset --hard` them before re-installing.

If you have to install from a fresh extraction of a tarball, a three-line bash script (tar, cd, site-install) could give you the functionality you want.

Note that core-quick-drupal has a --use-existing option, which makes it act very much like site-install, but will also call drush runserver and open a web browser at the end.

**Comment by anavarre** [comment]
Okay, this is already what I'm doing with bash scripting, then. Thanks.
