### ISSUE TITLE
Create drush config-status command

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#1811]
I am looking for a way to display overridden configuration. It is something similar to `drush fl` in Drupal 7. At the moment it is possible with `drush cex` or `drush cim` commands but you have to cancel the export / import actions each time. So that's not convenient. Perhaps we can just add some options to `drush config-list` command.

**Comment by Chi-teck** [comment]
Well `drush cex -n` fit my needs.

**Comment by greg-1-anderson** [comment]
I think a config status command is still a good idea.

**Comment by weitzman** [comment]
I think its a good idea as well. The code would like similar to the way pm-updatecode embeds a call to pm-updatestatus and updatedb embeds updatedb-status. This could also bring a confirmation to config-pull in the same way that the confirm happens after pm-updatestatus call

**Comment by danepowell** [comment]
Note that `drush cex -n` does not work on read-only file systems (such as Acquia Cloud). So we do need some other way of generating a list of overridden configuration.

I was thinking either a "dry-run" option for cex that does not try to write to the file system, or a separate config-status command. It sounds like folks would prefer config-status so I might try to whip that up.

**Comment by weitzman** [comment]
For read-only, I suggest the --destination option of config-export or use [config-pull](https://drushcommands.com/drush-8x/config/config-pull/) to bring the config local where you can commit it, etc. [This command was built with Acquia Cloud in mind](https://docs.acquia.com/acquia-cloud/develop/config-d8).

**Comment by danepowell** [comment]
I made a mistake during testing, I think `drush cex -n` runs fine on Acquia Cloud if all you want is a list of configuration changes. Regardless though, a config-status command would be nice. PR imminent.

**Comment by weitzman** [comment]
Lets talk in the PR
