### ISSUE TITLE
example/example.drushrc.php in phar file contain as much empty lines as it contains non-empty lines in the sources

### ISSUE THREAD

**Issue by dehnhard** [drush-ops/drush#1813]
As described up to this [comment here](https://github.com/drush-ops/drush/issues/1799#issuecomment-159997045), it seems to happen while building the phar.

Seems to also effect example/example.aliases.drushrc.php, but no other php files.

**Comment by weitzman** [comment]
Fixed by removing the compactors from box.json. Stripping comments is a bad idea for Drush.

I just created an 8.0.1 branch and will soon cherry pick the init fixes along with other bug fixes. fyi to @drush-ops/maintainers.
