### ISSUE TITLE
.bash_profile has to be resourced every time to run Drush

### ISSUE THREAD

**Issue by 4Digits** [drush-ops/drush#1815]
I installed Drush 8.0.0 for Drupal 8 on Linux Mint 17.1 via Composer.

I added Composer's directory to ```.bash_profile```:

```export PATH="$HOME/.composer/vendor/bin:$PATH"```

The problem is that every time I want to run Drush now, I have to resource <code>.bash_profile</code> like so: <code>source ~/.bash_profile</code>, otherwise I get an error:

```The program 'drush' is currently not installed. You can install it by typing:
    sudo apt-get install drush```

Any idea how to keep it sourced?

**Comment by weitzman** [comment]
Try putting your code into ~/.bashrc. Thats what our `drush init` command does. Otherwise, study bash startup files for Linux Mint.
