### ISSUE TITLE
Add commands for working with interface translations (locale)

### ISSUE THREAD

**Issue by tstoeckler** [drush-ops/drush#1817]
Drush currently does not have any way to work with translations. It is often an important part of the deployment process to update translations, i.e. just like doing a `drush config-import` as part of the deployment to have the latest config on the site you also want to have the latest translations.

**Comment by tstoeckler** [comment]
So this initial version basically replicates the _Available translation updates_ screen in Drupal 8 core. Interface Translation module sadly does not provide a proper API, so I basically re-implemented what happens in the respective form submission handlers. See the respective `@see` entries for the actual code I used. The `locale-check` and `locale-update` commands do work, however this does not yet contain commands for exporting and importing single PO files, which would also be useful. That feature is also available in Drupal 7 so we could provide that there, as well.

The translation update functionality is handled by the contrib [Localization update](https://www.drupal.org/project/l10n_update) module, so probably is not eligible for Drush core.

**Comment by tstoeckler** [comment]
Here's a screenshot:
![drush-locale](https://cloud.githubusercontent.com/assets/3929504/11466735/79de5630-9743-11e5-91c9-ceddeeec8050.png)

Also pinging @penyaskito because we talked about this yesterday...

**Comment by weitzman** [comment]
@tstoeckler will merge the PR (#1818) when he has a chance. no need to keep this issue open.
