### ISSUE TITLE
Bash autocompletion not working

### ISSUE THREAD

**Issue by subhojit777** [drush-ops/drush#1819]
I followed the installation steps as given here http://docs.drush.org/en/master/install. I have this line in `~/.bashrc`:
```
if [ -f ~/.drush_bashrc ] ; then
	. ~/.drush_bashrc
fi
```

The part inside `~/.drush_bashrc` that does the autocompletion is:
```
# Get the directory that Drush is stored in.
d="$(dirname "$d")"
# If we have found drush.complete.sh, then source it.
if [ -f "$d/drush.complete.sh" ] ; then
  . "$d/drush.complete.sh"
fi
```

I have Drush bin file here `/usr/local/bin/drush`. This is just a binary executable file and does not contains the `drush.complete.sh`, due to this the autocompletion is not working.

P.S. Earlier the Drush documentation had installation steps using Composer, then the autocompletion worked properly. With the new installation steps it is failing.

**Comment by weitzman** [comment]
This code has changed recently. Please update to drush 8.0.1 and then run `drush init` to copy files to ~/.drush append two lines in .bashrc file for you. Please post here if still not working.

**Comment by subhojit777** [comment]
Thank you so much! That worked :+1:
