### ISSUE TITLE
Drush version 6.* not working due offline pear.php.net

### ISSUE THREAD

**Issue by mdeletter** [drush-ops/drush#1827]
Hi,
Just to let you know, Drush version 6.* isn't working at this moment because pear.php.net is offline.
Drush tries (internally) to download a dependency on Console_Table directly from http://pear.php.net/ (wich is offline at the moment).
See https://github.com/drush-ops/drush/blob/6.x/includes/environment.inc#L150

Hopefully this helps other people to fix failing builds on Travis CI for example.

**Comment by generalredneck** [comment]
:+1:

**Comment by leolandotan** [comment]
:+1:

**Comment by greg-1-anderson** [comment]
Drush 6 is no longer supported.  This leaves us the question: should we make another release on the 6.x line, just to provide a way to get the Console Table without using Pear, or should we trust folks will all move up to Drush 7?

Note that Drush 7 still works on PHP 5.3, so in most cases, updates should be fairly straightforward. Should we consider a Drush 7 phar, to give a non-Composer option for those who are not ready to go up to PHP 5.4?

**Comment by ergonlogic** [comment]
Did I miss the EOL announcement for Drush 6? I think at least one more 6.x release is in order.

+1 for a Drush 7 phar.

**Comment by greg-1-anderson** [comment]
Drush 6 is still being tested, but there are not many changes getting backported on that branch. I tend to think that we should do at least one more.

**Comment by generalredneck** [comment]
My solution for this was to upgrade to Drush 7. In our case, I think there was just an old dependency in a module written long long ago, in a galaxy far far away that hadn't heard of drush 7 yet.

**Comment by greg-1-anderson** [comment]
I submitted a PR against the 6.x branch to download the Console Table from GitHub rather than from Pear.

**Comment by greg-1-anderson** [comment]
The 6.x dev release, at least, should be working again. We should make a new stable release on this branch as well.

**Comment by cafuego** [comment]
@generalredneck Note that drush 7 doesn't contain the test-run command, so if you use simpletest you'll need to now use the bundled drupal scripts/run-tests.sh php script. *that* in turn doesn't return an error status when a test fails, so you'll also want patch Drupal 7 with https://www.drupal.org/node/2189345#comment-10622516

**Comment by weitzman** [comment]
OK, making a release now. [There are only 11 commits since last release (5/25)](https://github.com/drush-ops/drush/compare/6.6.0...6.x). I'm going to also mark Drush 6 as EOL.

**Comment by weitzman** [comment]
Released [Drush 6.7.0](https://github.com/drush-ops/drush/releases/tag/6.7.0). 

A phar for Drush7 isn't worth it IMO. You would have to find all the right commits to cherry-pick, and deal with conflicts. i think Drush 7 is an ignorable release much like PHP 5.4. Just skip it.

**Comment by btopro** [comment]
thanks @weitzman !

**Comment by AndreBaumeier** [comment]
phar for Drush 7 still can be very useful for people having to deal with machines running old versions of php.. and please let's not start the discussion on why and that everyone should switch.

**Comment by greg-1-anderson** [comment]
Folks stuck on PHP 5.3 must stick with Drush 6 or Drush 7.

**Comment by greg-1-anderson** [comment]
We do still have the issue that it would be nontrivial to produce a phar for Drush 7. This might be too much of an effort for someone not familiar with Drush, but I don't see @weitzman or myself having time to do it either.
