### ISSUE TITLE
MySQL connection problems with drush 7 and up

### ISSUE THREAD

**Issue by horvan** [drush-ops/drush#1830]
Hi there,

I have seen a seldom bug in drush 7 and up

reproduce:

*Just set up  two servers lets calll it @dev and @prod  
*The two machines are a home for Ubuntu lts and just have a lamp package on it normal my-sql 5.5-server.

While drush sql-sync with drush 6.1 on both servers works like a charm drush 7 and up to drush -master produces a

 >mysql error 1045 28000-access-denied message.

sql-connect shows the right connection details on both serves so it seems there is a bug that forces drush not to use this credentials to connect mysql.

# sql-cli doesn't work so it seems the sql-cli function is where the issue comes from 

I've double checked it as well in my aliases.drushrc.php and in the settings.php file.

It seems I am not the only one with this problem because I have seen many similar questions on drupal@stackexchange as well. I can send over my settings.php and my aliases.drushrc.php if you like. 

Again I'll use drush 6.x for now bbecause 7.x and up seem to have problesms to sync data or even bootsrap drupal correctly.

**Comment by weitzman** [comment]
we added support for a my.cnf file. we will take creds from there is yhou have one. search both servers for one. mysql is not very clear about where those can live.
