### ISSUE TITLE
Drush 6.6 hangs if pear site is down and we can't download Console_Table

### ISSUE THREAD

**Issue by alberto56** [drush-ops/drush#1831]
I have Drush 6.6 installed (it seems to be the latest version which supports PHP 5.3) via Puppet, and since yesterday, building new VMs has started failling at the line:

    drush dl some_module
    
Logging into my box and using the Drush `--debug` option, it turns out that http://download.pear.php.net/package/Console_Table-1.1.3.tgz and https://pear.php.net has an invalid certificate.

(This error will only occur if Console_Table does not already exist in /path/to/drush/drush/libs/)

I manually added a copy of Console_Table-1.1.3 to my VM and got drush to run.

However, I'm wondering if we could have an alternate path to fetch Console_Table-1.1.3 in case http://download.pear.php.net is not available.

**Comment by weitzman** [comment]
Worked around PEAR failure - https://github.com/drush-ops/drush/releases/tag/6.7.0
