### ISSUE TITLE
Drush loads duplicate copies of template.php - throws PHP fatal

### ISSUE THREAD

**Issue by jenlampton** [drush-ops/drush#1833]
I've found that clearing caches from the Drupal UI on a local site works fine, but when attempting to clear the caches using `drush cc all` I get an error about a my `preprocess_html` function being declared twice in template.php.  I've checked and double checked, but the function is only declared once.  The first line reference is to the function definition, but the second is to an arbitrary closing `}`. I can only assume that Drush is somehow loading a duplicate copy of template.php, and since the `preprocess_html` function is the first one in the file, that's why it fatal's there.

I am running Drush 6.3.0 Drupal 7 on Mac OSX using MAMP.  I have looked into these similar issues with Drush, Mac, & MAMP but none of the fixes here recommended fix my problem.
https://www.drupal.org/node/644126
https://www.drupal.org/node/1296594

Any advice greatly appreciated.

**Comment by weitzman** [comment]
Drush 6 is ancient, and no longer supported (as of this morning). Any chance you can upgrade to 8.0.1? Drupal 6 is still supported there.

**Comment by jenlampton** [comment]
It took me 2 full days to get Drush 7 installed, and that still doesn't work properly on all sites. It looks like Drush 8 also still requires composer? Is there an installer coming soon?  Maybe I'll just wait for that.

**Comment by weitzman** [comment]
drush8 no longer requires Composer. See
http://docs.drush.org/en/master/install/. There is just one file to
download.

**Comment by jenlampton** [comment]
I read that, but this is what I see when I try to use it...
![screen shot 2015-12-02 at 12 54 51 pm](https://cloud.githubusercontent.com/assets/397895/11543915/07676d8c-98f4-11e5-9dbe-1bcb2badba8a.png)

**Comment by jenlampton** [comment]
Today it only took me about an hour, but I was able to `composer update` both drush7 and drush8 to get them working the drush.phar is still not working though. 
![screen shot 2015-12-02 at 4 36 05 pm](https://cloud.githubusercontent.com/assets/397895/11548595/ef36bd66-9912-11e5-9650-36fde998cce3.png)

**Comment by jenlampton** [comment]
Well, I found an existing bug report, but it was closed with no solution. https://github.com/drush-ops/drush/issues/657
