### ISSUE TITLE
New global composer install method doesn't work

### ISSUE THREAD

**Issue by karlshea** [drush-ops/drush#1834]
http://docs.drush.org/en/master/install-alternative/#install-a-global-drush-via-composer

Please revert to the old documentation that did work.

After running 

```
COMPOSER_HOME=/opt/drush COMPOSER_BIN_DIR=/usr/local/bin COMPOSER_VENDOR_DIR=/opt/drush/7 composer require drush/drush:7
```

Trying to run drush gives the error "Unable to load autoload.php. Drush now requires Composer in order to install its dependencies and autoload classes. Please see README.md"

**Comment by weitzman** [comment]
ping @greg-1-anderson and @jonhattan since that onliner was intoduced in #1628.

**Comment by gerzenstl** [comment]
I was able to solve that error by installing the drush dependencies specified by composer using:
```
COMPOSER_HOME=/opt/drush COMPOSER_BIN_DIR=/usr/local/bin COMPOSER_VENDOR_DIR=/opt/drush/7 composer require drush/drush:7.* && cd /opt/drush/7/drush/drush/ && composer update --no-interaction && composer install --no-interaction
```

Let me know if you think this solution is valid, I could add a PR to update the documentation.

**Comment by weitzman** [comment]
Can anyone verify that the proposed line works properly?

**Comment by greg-1-anderson** [comment]
These instructions have been removed. `composer global` is deprecated.
