### ISSUE TITLE
Error using Drush on Windows 7 using Cgwin & Composer for Installation - The system cannot find the path specified

### ISSUE THREAD

**Issue by agilis1** [drush-ops/drush#1839]
I am using Windows 7 64, with WAMPServer64, with Cygwin and composer installed.

- C:\cygwin64
- C:\wamp
- C:\Users\dev\AppData\Roaming\Composer

I have followed all the steps required to complete a successful install of Drush. Everything seems to work correctly as far as I can tell. Here's the output of a drupal status command.

Drupal version                  :  7.32
 Site URI                        :  http://default
 Database driver                 :  mysql
 Database hostname               :  localhost
 Database port                   :
 Database username               :  db
 Database name                   :  db
 Drupal bootstrap                :  Successful
 Drupal user                     :
 Default theme                   :  theme548
 Administration theme            :  garland
 PHP executable                  :  /cygdrive/c/wamp/bin/php/php5.5.12/php
 PHP configuration               :  C:\wamp\bin\php\php5.5.12\php.ini
 PHP OS                          :  WINNT
 Drush script                    :  C:\Users\dev\AppData\Roaming\Composer\vendor\drush\drush\d
                                    rush.php
 Drush version                   :  7.1.0
 Drush temp directory            :  C:\cygwin64\tmp
 Drush configuration             :
 Drush alias files               :
 Install profile                 :  standard
 Drupal root                     :  C:\wamp\www\projects\dev\Mirror
 Site path                       :  sites/default
 File directory path             :  sites/default/files
 Private file directory path     :  sites/default/files/private
 Temporary file directory path   :  /tmp

However, when I execute the following command, I receive an error.

Initialized Drupal 7.32 root directory at                   [notice]
C:\wamp\www\projects\dev\Mirror
Initialized Drupal site default at sites/default            [notice]
Executing: mysql --defaults-extra-file="C:\\cygwin64\\tmp\\dru2DAB.tmp" --database=db --host=localhost --silent  < "C:\\cygwin64\\tmp\\dru2DAA.tmp"
Executing: mysql --defaults-extra-file="C:\\cygwin64\\tmp\\dru2E29.tmp" --database=db --host=localhost --silent  < "C:\\cygwin64\\tmp\\dru2E28.tmp"
Loading release_info engine.                                [notice]
Loading version_control engine.                             [notice]
Loading package_handler engine.                             [notice]
Executing: wget --version
Loading update_status engine.                               [notice]
/cygdrive/c/wamp/bin/php/php5.5.12/php                      [notice]
"C:\\Users\\dev\\AppData\\Roaming\\Composer\\vendor\\drush\\drush\\drush.php"
--php=/cygdrive/c/wamp/bin/php/php5.5.12/php  --backend=2
--verbose
--root="C:\\wamp\\www\\projects\\dev\\Mirror"
--uri=http://default  pm-updatestatus drupal 2>&1
Illegal string offset 'site' backend.inc:1030            [warning]
The command could not be executed successfully (returned:[error]
The system cannot find the path specified.
, code: 1)
pm-updatestatus failed.                                  [error]
Command dispatch complete                                   [notice]
Command dispatch complete                                   [notice]

The specific error being returned:

Illegal string offset 'site' backend.inc:1030            [warning]
The command could not be executed successfully (returned:[error]
The system cannot find the path specified.
, code: 1)

Sometimes "The system cannot find the path specified." is not displayed.

I cannot seem to track down this issue and I do not know enough about Drush to fix this error.

From within the site directory, `drush cc all` (Clearing all the Drupal site cache) works correctly as well as `drush pm-updatestatus`

Please help.

**Comment by jeremygrajales** [comment]
Which drush command did you execute to receive this error?

**Comment by agilis1** [comment]
The command I am trying to execute was 'drush up drupal'

**Comment by FatalMojo** [comment]
The problem is with

**PHP executable : /cygdrive/c/wamp/bin/php/php5.5.12/php**

create the following system variable

**DRUSH_PHP=c:/wamp/bin/php/php5.5.12/php.exe**

that should fix you up.

**Comment by fmeirelesfon** [comment]
Hi, I recently stumbled upon the same issue and I would like to trace the origin of the problem. Here's what I have so far:

- I'm running drush on a Windows environment using Git Bash;
- Running the command `drush config-import --source=sites/default/config/sync --verbose` results in the following output:

```
Import the listed configuration changes? (y/n): y
"C:\\ProgramData\\Drush\\bin\\drush"  --backend=2 --verbose --root="C:\\MAMP\\htdocs\\clone\\web" --uri=http://default          [notice]
cache-rebuild 2>&1
The filename, directory name, or volume label syntax is incorrect.
Illegal string offset 'site' backend.inc:1037                                                                                [warning]
[error]mand could not be executed successfully (returned: The filename, directory name, or volume label syntax is incorrect.
, code: 1)
```

- The `illegal string offset` is expected, I already opened pull request #1982;
- The `The filename, directory name, or volume label syntax is incorrect.` is puzzling, specially considering that executing the given command without backend works just fine `"C:\\ProgramData\\Drush\\bin\\drush" --verbose --root="C:\\MAMP\\htdocs\\clone\\web" --uri=http://default cache-rebuild`:

```
Cache rebuild complete.                                                                                                      [ok]
Command dispatch complete                                                                                                       [notice]
```

**Comment by mstrelan** [comment]
I was able to fix this by creating a .bashrc file in my home directory for sh.exe which aliased the drush command to invoke it via PHP.

```
alias drush='php /c/path/to/drush/vendor/drush/drush/drush.php'
```

As far as I could tell, before this, drush couldn't decide if I was on Windows or Unix. I guess running through sh.exe it should detect Unix, but it seemed to treat it as Windows.

**Comment by Zythyr** [comment]
@mstrelan 

Your method doesn't work for me. Below is the line that I put into my ~/.bashrc file:

`alias drush='php /cygdrive/c/Users/dev/AppData/Roaming/Composer/vendor/drush/drush/drush.php'`

Below is the error I get:

```
dev@DEV-PC /cygdrive/c/xampp/htdocs/www/img_test1
$ drush
Could not open input file: /cygdrive/c/Users/dev/AppData/Roaming/Composer/vendor/drush/drush/drush.php
```

**Comment by weitzman** [comment]
You can't alias `drush` and include `php` in the value.

The most robust way to fix this is to adjust your PATH so the right PHP appears first. [See this SO answer](http://stackoverflow.com/questions/4145667/how-to-override-the-path-of-php-to-use-the-mamp-path/10653443#10653443).

**Comment by Zythyr** [comment]
@weitzman 

I am confused. My configuration is: Cygwin64 on Windows 10, Drush 8.0.5, XAMPP with PHP 5.6.19. 

My issue is that Drush is giving me error when I run the command: `drush -d pm-update`. Below is part of the debug output: 
```
Backend invoke:                                                        [command]
"C:\\Users\\dev\\AppData\\Roaming\\Composer\\vendor\\drush\\drush\\drush"
 --backend=2 --verbose --debug
--root="C:\\xampp\\htdocs\\www\\my_drupal_6_site" --uri=http://www
pm-updatestatus 2>&1 [7.21 sec, 16.15 MB]
"C:\\Users\\dev\\AppData\\Roaming\\Composer\\vendor\\drush\\drush\\drush"   [n     otice]
 --backend=2 --verbose --debug
--root="C:\\xampp\\htdocs\\www\\my_drupal_6_site" --uri=http://www
pm-updatestatus 2>&1 [7.21 sec, 16.16 MB]
The command could not be executed successfully (returned: The        [error]
filename, directory name, or volume label syntax is incorrect.
, code: 1) [7.32 sec, 16.16 MB]
pm-updatestatus failed. [7.32 sec, 16.15 MB]                         [error]
Returned from hook drush_pm_updatecode [7.32 sec, 16.15 MB]              [debug]
Changes made in drush_pm_updatecode have been rolled back. [7.32 sec,    [debug]
```


Why do I need to export my PHP path? I only have one version of PHP installed: 
```
dev@DEV-PC ~
$ which php
/cygdrive/c/xampp/php/php
```
It seems Drush is already refering to the correct PHP path. See output below:

```
dev@DEV-PC /cygdrive/c/xampp/htdocs/www/my_drupal_6_site
$ drush status
 Drupal version         :  6.16
 Site URI               :  http://www
 Database driver        :  mysql
 Database hostname      :  localhost
 Database port          :
 Database username      :  drupal
 Database name          :  my_drupal_6_site
 PHP configuration      :  C:\xampp\php\php.ini
 PHP OS                 :  WINNT
 Drush script           :  C:\Users\dev\AppData\Roaming\Composer\vendor\drush
                           \drush\drush
 Drush version          :  8.0.5
 Drush temp directory   :  C:\cygwin64\tmp
 Drush configuration    :
 Drush alias files      :
 Drupal root            :  C:\xampp\htdocs\www\my_drupal_6_site
 Drupal Settings File   :  sites/default/settings.php
 Site path              :  sites/default
```

**Comment by parkerjgit** [comment]
I see this is closed 29 days ago, but I am having the same unresolved problem as Zythyr. I'm using GitBash and wamp, but 'drush status' and debug output from 'drush up drupal' are otherwise the same.

**Comment by wolfborg** [comment]
I know this closed over a year ago but just updating Drush seemed to work for resolving this issue for me. Tried all your solutions first and nothing worked, wanted to tear my hair out, but really I probably should've tried updating first.
