### ISSUE TITLE
Drush gives both a success note and an error, and UI shows no change

### ISSUE THREAD

**Issue by Benosika** [drush-ops/drush#1847]
I have a Drupal 8.0.0 site and Drush master-branch. When I ran "drush up" I was informed that the update has been made successfully and Drupal version is now 8.0.1 ... I ran "drush cr" and went happy into the UI "Knowing" that the update took place woohoo, but than I SADLY realized that the program is still 8.0.0 ... I.E It seems that the drush update didn't take effect.

Than, I looked at the Drush process again and saw the error I missed... It's confusing me, If Drush both gave an error ("Unable to decompress" "druB89E.tmp.gz"), and made the update "Successfully", than who's right? Which side has the justice?, Did I had a partial update and now something is messed up? Would you suggest to me to try to fix this error or to cancel the whole process somehow (partial downgrade)?

Since I'm just starting to learn coding, I don't really know how to treat this case and what steps to take with it. Any advice?

![dup1](https://cloud.githubusercontent.com/assets/13021900/11669289/9c2cf346-9e04-11e5-8945-87494ac6cce1.PNG)
![dup2](https://cloud.githubusercontent.com/assets/13021900/11669290/9c2dbf9c-9e04-11e5-9ad0-78b1aeb2e616.PNG)

**Comment by Benosika** [comment]
Will thank you dearly for your help!

**Comment by weitzman** [comment]
Some comments were deleted here.

**Comment by Benosika** [comment]
I just deleted a comment that said "Thank you dearly for your help" because I didn't want to get "shouts" as I got in Stackoverflow when I did that. Why did you close this issue Moshe? Ben,

**Comment by weitzman** [comment]
Fixed up some error handling so you don't get a success message in this case. I think you are safely still on 8.0.0. I would figure out why your decompress is not working. Make sure that you have the program `gzip` on your PATH in Windows.

**Comment by Benosika** [comment]
Hello! I've added, the following Path value to the Path EV in my Windows 10 home (64), after a semicolon... C:\Program Files (x86)\GnuWin32\bin

I've also restarted cmd but still I get a similar error. :\

**Comment by weitzman** [comment]
You can add --verbose to the command and you will see the exact params for `gzip` that are used. try to run that exact command in your shell.

**Comment by Benosika** [comment]
C:\wamp\www\benia>drush up --verbose
Executing: mysql --defaults-extra-file="C:\\Users\\Beni\\AppData\\Local\\Temp\\dru6EFA.tmp" --database=benia --host=localhost --port=3306 --silent  < "C:\\Users\\Beni\\AppData\\Local\\Temp\\dru6EF9.tmp"
Executing: mysql --defaults-extra-file="C:\\Users\\Beni\\AppData\\Local\\Temp\\dru6F0C.tmp" --database=benia --host=localhost --port=3306 --silent  < "C:\\Users\\Beni\\AppData\\Local\\Temp\\dru6F0B.tmp"
Loading release_info engine.                                                                                               [notice]
Loading version_control engine.                                                                                            [notice]
Loading package_handler engine.                                                                                            [notice]
Executing: wget --version
Executing: curl --version
Loading update_status engine.                                                                                              [notice]
php.exe "C:\\drush-master\\drush.php" --php=php.exe  --backend=2 --verbose --root="C:\\wamp\\www\\benia"                   [notice]
--uri=http://default  pm-updatestatus 2>&1
Update information last refreshed: Tue, 12/08/2015 - 07:18
 Name    Installed Version  Proposed version  Message
 Drupal  8.0.0              8.0.1             Update available


Code updates will be made to drupal core.
WARNING:  Updating core will discard any modifications made to Drupal core files, most noteworthy among these are .htaccess and robots.txt.  If you have made any modifications to these files, please back them up before updating so that you can re-create your modifications in the updated version of the file.
Note: Updating core can potentially break your site. It is NOT recommended to update production sites without prior testing.

Do you really want to continue? (y/n): y
Executing: svn info "C:\\wamp\\www\\benia/drupal-8.0.1"
Executing: bzr root "C:\\wamp\\www\\benia/drupal-8.0.1"
C:\Users\Beni/.drush/cache/download/http---ftp.drupal.org-files-projects-drupal-8.0.1.tar.gz retrieved from cache.         [notice]
Downloading drupal-8.0.1.tar.gz was successful.                                                                            [notice]
Md5 checksum of drupal-8.0.1.tar.gz verified.                                                                              [notice]
Executing: gzip --decompress "C:\\Users\\Beni\\AppData\\Local\\Temp\\drush_tmp_1449779221_5669e01590898\\dru581.tmp.gz"
Executing: bsdtar.exe  -xvf dru581.tmp
Unable to untar C:\Users\Beni\AppData\Local\Temp\drush_tmp_1449779221_5669e01590898\dru581.tmp.                             [error]
Project drupal was updated successfully. Installed version is now 8.0.1.
Backups were saved into the directory C:\Users\Beni/drush-backups/benia/20151210202620/drupal.                                 [ok]
Rolling back update of Drupal core code ...                                                                                [notice]
Executing: svn info drupal-8.0.1
Executing: bzr root drupal-8.0.1
Backups were restored successfully.                                                                                            [ok]
Command dispatch complete                                                                                                  [notice]
Command dispatch complete                                                                                                  [notice]

C:\wamp\www\benia>

**Comment by weitzman** [comment]
Error happens after `bsdtar.exe -xvf dru581.tmp`. Make sure that bsdtar is in your path. This would be fixed by #1371

**Comment by Benosika** [comment]
I must say Moshe, I think demanding from Windows users to install about 6 programs and configure a EV Path value for each one is very time demanding (I am not complaining for a moment and it might be even clearer in a second).

I haven't yet to try Git for Windows... It may be my last option before installing a combined Ubuntu-Win10 environment... Can it shorten the drush-master installation process in Windows 10 home?

**Comment by weitzman** [comment]
[I recently revised the install instructions to point to Dev Desktop](http://docs.drush.org/en/master/install-alternative/#windows) instead of asking folks to setup all those programs.

**Comment by weitzman** [comment]
Yes - set the environment variable TEMP to whatever you wish. 

For folks who land here and are wondering abut Drush9, the env variable is named DRUSH_PATHS_CACHE_DIRECTORY as per #3592

**Comment by staminna** [comment]
I sucessfully set the TEMP env. variable to C:\PGM\TEMP although when I try to download
```
λ drush vget temp

ds_extras_field_template: 1
file_temporary_maximum_age: '0'
file_temporary_path: tmp
temp: 'C:\PGM\TEMP\'

λ drush dl media

Unable to untar C:\Users\domijor\AppData\Local\Temp\1\drush_tmp_1537961244_5bab6d1c6db44\medE808.tmp.                                                                                              [error]
```

Drush does not have write access to my temporary directory. I also changed the Windows environment TMP and TEMP directories, but the issue remains the same. I can't change permissions inside a corporate environment.
