### ISSUE TITLE
Drush 7 sql-sync fails on Windows

### ISSUE THREAD

**Issue by jeremygrajales** [drush-ops/drush#1850]
I ran into this issue when working on a Windows target. And it appears to be related to gzip.
I receive this error when running
```
drush sql-sync @remote @local
```
Everything runs fine until sql-sync starts copying the dump file from remote. Here's the error.
```
Copying dump file from Source to Destination.                                                                           
Starting to import dump file onto Destination database.                                                             
Failed to gunzip input file.                                                                                             [error]
Query failed.                                                                                                            [error]
```
This appears to be related to https://github.com/drush-ops/drush/blob/7.x/lib/Drush/Sql/SqlBase.php#L146

Based on the source, the command executed is "gunzip" which doesn't exist on my Windows OS.
I have gunzip through cygwin. But this is just a shell script that runs:
```
gzip -d
```
Windows won't read this shell script and execute gzip -d appropriately. So, I'll get the dump file transferred, but sql-sync fails to unzip the dump file after that. I can fix this by adding
```
'source-command-specific' => array (
			'sql-sync' => array (
				'gzip' => FALSE,
			)
		)
```
to my @remote alias. This causes the remote not to use gzip like sql-sync requires here https://github.com/drush-ops/drush/blob/7.x/commands/sql/sqlsync.drush.inc#L209
And causes the script to skip https://github.com/drush-ops/drush/blob/7.x/lib/Drush/Sql/SqlBase.php#L145 altogether (and therefore skipping the gunzip command).

I could also just create a gunzip.bat for my Windows box that does the same thing as the shell script.  Then I wouldn't have to edit the alias. But I just wanted to know if this was an existing issue or if there were Windows+Drush installation tips that others may know about that I couldn't find on the web. Remote is a AWS Linux OS. And Local is Windows 8.1.

Maybe others have been getting around this by using sql-dump + rsync instead of sql-sync.
And I know drush support for Windows is eh... But this seems like a minor flaw with sql-sync. I could be wrong?

Could it possibly be better to use
```
drush_shell_exec('gzip -d %s', $input_file)
```
instead of
```
drush_shell_exec('gunzip %s', $input_file)
```
at https://github.com/drush-ops/drush/blob/7.x/lib/Drush/Sql/SqlBase.php#L146

**Comment by jeremygrajales** [comment]
This is kind of a duplicate of https://github.com/drush-ops/drush/issues/1435?_pjax=%23js-repo-pjax-container but hopefully more constructive.

**Comment by weitzman** [comment]
Nice debugging! using `gzip -d` seems like a good fix to me. /cc @jonhattan

**Comment by mlochd** [comment]
Great stuff Jeremy! Had been looking for a solution to this for a while. Now it works great with Acquia-Dev.
