### ISSUE TITLE
Updating composer failed

### ISSUE THREAD

**Issue by Benosika** [drush-ops/drush#1851]
Hi, my Composer.JSON file is at c:\drush-master, so at Powershell I navigated and ran:

C:\drush-master> composer global update

Than I got:

Changed current directory to C:/Users/Beni/AppData/Roaming/Composer
Composer could not find a composer.json file in C:\Users\Beni\AppData\Roaming\Composer

---

Why should CMD change the directions to C:/Users/Beni/AppData/Roaming/Composer ? I have no such path in my Path variable...

**Comment by jeremygrajales** [comment]
This is not exactly a Drush issue.
See https://getcomposer.org/doc/03-cli.md#global
This explains the "Changed current directory" message.

Maybe try
```
composer update
```
instead...

**Comment by weitzman** [comment]
The install instructions no longer require using Cmoposer. Just download and rename/move. Please retry that way.

**Comment by Benosika** [comment]
Hi, I think I'm going to move to Ubuntu.
