### ISSUE TITLE
Multi-Site Setup: Clear Cache from a specific Site

### ISSUE THREAD

**Issue by jepster** [drush-ops/drush#1852]
Hi,

my Drupal 8 multi-site setup is located at **/Users/jepster/Sites/d8**. The several sites are configured in the **sites.php** file and each site has it's folder in **/sites/**. The Drupal 8 multi-site configuration works. My operating system is Mac OSX Yosemite.

Now I want to flush with drush only the cache from a specific site. I've tried it in my drush alias file at **~/.drush/d8.aliases.drushrc.php**. It looks like this:

```php
<?php
$root = '/Users/jepster/Sites/d8';
$aliases['pbt'] = array(
        'root' => $root,
        'uri' => 'http://db-pbt:8888'
);
$aliases['d8'] = array(
        'root' => $root,
        'uri' => 'http://db:8888'
);
```

But either I've insert the command

> drush @pbt status

or 

> drush @d8 status

the file directory path is always

> File directory path             :  sites/default/files 

How can I setup my drush alias file to handle different database connection for each site in the multi-site setup?

Thanks in front.

**Comment by weitzman** [comment]
In status, look for the item toward the bottom called Site path. That should be different for each alias. if it isn't, I'm not sure what to try next.

**Comment by jepster** [comment]
No, it's not different. Twice the same:

*Site path                       :  sites/default*

If I change the 'root' key like so:

$aliases['pbt'] = array(
	'root' => $root . '/sites/pbt',
	'uri' => 'http://db-pbt:8888'
);

Then I'm getting no site path at all via drush status.

Any help would be appreciated.

**Comment by weitzman** [comment]
Perhaps there is a problem in the sites.php In any case, I dont think we can successfully debug this here. The problem is specific to your setup. Sorry.

**Comment by jepster** [comment]
Only one more answer please: I've renamed the "default" folder in my "sites" directory. Then Drush is reporting:

Could not find a Drupal settings.php file at sites/default/settings.php.  

Does Drush expect a settings.php file in the "default"-folder, with any specific multi site configuration?
