### ISSUE TITLE
drush make fails to deploy

### ISSUE THREAD

**Issue by drzraf** [drush-ops/drush#1853]
If base-path is non-writable, and base-path/sites is non-writable _but_ base-path/sites/all is a symlink to a writable directory, then copying a build containing only sites/all/\* files should succeed. It currently does not.
Workaround, creates a /tmp/blah/sites/ tree, and symlink  /tmp/blah/sites/all to the destination directory (as in the original base-path) then it will works, but that's suboptimal.
The fact that intermediary (below all/) directories are not writable should not keep drush make to succeed.

**Comment by greg-1-anderson** [comment]
Make is maintenance only; closing.
