### ISSUE TITLE
Add pm-uninstall option to automatically uninstall dependent modules

### ISSUE THREAD

**Issue by colans** [drush-ops/drush#1854]
For Drupal 8, there's no more "drush pm-disable" command to turn off modules & such (say for development sites).  They now need to be uninstalled.  But in Drupal 7-, "dis" automatically uninstalled dependent modules as well.  There's no such functionality in pm-uninstall to do the same sort of thing in Drupal 8.

We should add a pm-uninstall option that takes care of this, something like "--remove-dependents".

**Comment by danepowell** [comment]
The current situation is also somewhat unintuitive, in that the dependency chain of the module arguments isn't even taken into consideration--the modules are just uninstalled in the order they are passed. So if you are uninstalling modules with dependencies on each other, you have to be very careful in what order you pass them as argument to `pmu`. This is especially painful in situations where you may not know _a priori_ what the dependencies are.

**Comment by danepowell** [comment]
See #2566, I think this is actually a regression introduced by #925
