### ISSUE TITLE
can't fetch git@ repository

### ISSUE THREAD

**Issue by drzraf** [drush-ops/drush#1855]
Fetching authenticated (private) repository does not work in 8.x (does in 7.x)
Sample :

```
projects[myblog][type] = "theme"
projects[myblog][download][type] = "git"
projects[myblog][download][url] = "git@gitlab.com:xxx/yyy.git"
projects[myblog][download][branch] = "master"
projects[myblog][options][working-copy] = TRUE
```

See also : https://drupal.stackexchange.com/questions/3821/ and issue #23 
The `git` command usually handles this well, either.
Hypothesis : the SSH\* variable (including those for ssh-agent) are not passed correctly (would the environment be reset by drush ??)

Side note: it's quite difficult to debug since even using -v -d, nothing from the git commands appears.

**Comment by jhedstrom** [comment]
Looking at `make_download_git()`, running with `--debug` should output some indication of where the command is failing.

**Comment by drzraf** [comment]
unless -d and --debug act differently, I can say that -d didn't provided
the (expected) increased debug output.

**Comment by drzraf** [comment]
@weitzman I failed to see the relation between 45136cc and this issue.

**Comment by jhedstrom** [comment]
@drzraf is `make_download_git()` being called at all?

**Comment by drzraf** [comment]
I'm now using drush-7 which works.
If you can't reproduce, please let me know.

**Comment by greg-1-anderson** [comment]
Make is maintenance only; closing.
