### ISSUE TITLE
Drush make fails for relative paths to make file (8.0.1)

### ISSUE THREAD

**Issue by googletorp** [drush-ops/drush#1856]
Usually when working with drush to make, I go to the place where I have a make file (usually in the root of an install profile) and run the following command

`drush make --no-core --working-copy --contrib-destination=. drush-make.make`

where `drush-make.make` is the name of the drush make file. This have worked since drush 4.x I think, but with the newest version of drush (8.0.1 right now), I get an error instead:

`file_get_contents(drush-make.make): failed to open stream: No such file or directory make.utilities.inc:527`

If i instead specify the full system path to the make file, the above command works as expected. So probably somewhere the context of where the command is being run, isn't used like it has been done.

I have tested this on Mac OS 10.10 and Ubuntu LTS 14.04

**Comment by googletorp** [comment]
This was actually entirely my fault, had some drush include files in the drupal site folder (probably messed up with composer at some point) which messed up running make.

**Comment by thamas** [comment]
Just updated Drush to 8.1.2 (via composer) on OSX and have the same issue. Relative path does not work but absolute path works. And I do not have any drush include files in my site directory…

(I use Drush with MAMP–it was configured earlier and works, and have Acquia DevDesktop installed on my system too.)
