### ISSUE TITLE
"use-site-dir" option for drush make projects

### ISSUE THREAD

**Issue by drzraf** [drush-ops/drush#1857]
When using drush makefiles, downloading/git-cloning inside the site-specific directory is useful (eg, a theme).
But AFAICT drush make does not provide such an option.
(Using a value for ``subdir`` like ``../../www.my.domain`` could do the trick (I didn't test) but that's suboptimal.)

**Comment by jonhattan** [comment]
`projects[views][contrib_destination] = "sites/sitedir";` will install views to `sites/sitedir/modules/views`

**Comment by drzraf** [comment]
Thank you for the tip.
May I suggest that it gets documented. Currently, it's not.

**Comment by drzraf** [comment]
referencing PR drush-ops/drush#582 and WhiteHouse/buildmanager#8
