### ISSUE TITLE
Fatal error: Maximum function nesting level of '200' reached with qd and -l parameter.

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#1860]
The error happens for the following command:

    $ drush -vy -l http://localhost:8080 qd --server=http://localhost:8080 --no-server --watchdog --core=drupal-7 testsite

See: https://travis-ci.org/drupal-modules/rules_forms/jobs/97044631

Cherry-picked backtrace:

      0.6511    9749832   5. call_user_func_array:{~/.composer/vendor/drush/drush/includes/command.inc:183}('drush_command', array (0 => 'testsite')) ~/.composer/vendor/drush/drush/includes/command.inc:183
      1.5475    8062456  10. drush_invoke($command = 'site-install', $arguments = array (0 => NULL)) ~/.composer/vendor/drush/drush/commands/core/core.drush.inc:976
      1.7984   11044704  13. drush_command(NULL) ~/.composer/vendor/drush/drush/includes/command.inc:183
      1.8001   11084792  16. drush_core_pre_site_install($profile = NULL) ~/.composer/vendor/drush/drush/includes/command.inc:364
      1.8417   11204728  17. drush_mkdir($path = NULL, $required = ???) ~/.composer/vendor/drush/drush/commands/core/site_install.drush.inc:149
      1.8417   11204856  18. drush_mkdir($path = '', $required = ???) ~/.composer/vendor/drush/drush/includes/filesystem.inc:361
      1.8417   11204984  19. drush_mkdir($path = '', $required = ???) ~/.composer/vendor/drush/drush/includes/filesystem.inc:361
      1.8426   11359136 200. drush_mkdir($path = '', $required = ???) ~/.composer/vendor/drush/drush/includes/filesystem.inc:361

This happened because I had the following variable set: `DRUSH="drush -vy -l $URL"`, and replaced all `drush` commands with `$DRUSH`, therefore I end up with unexpected errors. So possibly `drush` `-l` parameter conflicts with `qd` command.

**Comment by weitzman** [comment]
No, it doesn't conflct. No idea what $URL is. Regardless, this configuration is not supported. Use drushrc files or aliases to set configuration.
