### ISSUE TITLE
sqlite db file created in the wrong folder

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#1861]
Here is my test case:

I'm in `~/empty` folder which is empty, then I run:

    drush -vy qd --root=$HOME/drupal-7 --core=drupal-7 testsite

which seems to work, however the db file is created in the wrong place.

Here is key message which appeared during the installation:

> You are about to create a `/Users/kenorb/drupal-7/sites/default/settings.php` file and CREATE the '`Users/kenorb/testsite.sqlite`' database. Do you want to continue? (y/n): y

which should show `/Users` instead of `Users`.

As results, my Drupal root folder contain `Users` folder with db file in it, so the full path is: `/Users/kenorb/drupal-7/Users/kenorb/testsite.sqlite` which it isn't right, secondly my db file is exposed being within the Drupal root directory.

**Comment by weitzman** [comment]
Fixed both issues. Thanks for reporting.
