### ISSUE TITLE
cron documentation inconsistency

### ISSUE THREAD

**Issue by com2** [drush-ops/drush#1865]
I followed the drush global installation instructions (http://docs.drush.org/en/master/install/) and thought that from then on drush can be called from cron smoothly. Apparently the only way to use drush in a crontab is then to follow the instructions "Running Drupal cron tasks from Drush" (http://docs.drush.org/en/master/cron) 

These instructions however are inconsistent with each other. Installation instructions establish the global drush path as /usr/local/drush, while the cron instructions give an example with another path /usr/local/bin/drush/drush. Ignorant user this can be a cause for at least some delay and irritation. Would be better when both use the same path.

**Comment by weitzman** [comment]
Fixed in 45136cc5950e483033cdcac4751b085f44d8da24
