### ISSUE TITLE
drush 8.x ups / pm-updatestatus doesn't show theme updates with drush backend

### ISSUE THREAD

**Issue by bricas** [drush-ops/drush#1867]
With the drupal backend:

```
$ drush ups --format=csv --pipe --update-backend=drupal
bootstrap,7.x-3.0,7.x-3.3,Update available
```

With the drush backend:

```
$ drush ups --format=csv --pipe --update-backend=drush
(no output)
```

**Comment by jonhattan** [comment]
Unable to reproduce. @bricas is the bootstrap theme disabled in your test?

**Comment by bricas** [comment]
Yes, I believe the bootstrap theme was installed, but disabled because it was used by a sub-theme.

**Comment by weitzman** [comment]
@jonhattan will make the final decision, but I'm OK leaving this as a known limitation of the drush backend. In general, future work is focused on Composer based code assembly/update rather than pm-updatestatus.

**Comment by greg-1-anderson** [comment]
`pm-*` commands are in maintenance only.
