### ISSUE TITLE
Drush pm-update doesn't complete

### ISSUE THREAD

**Issue by safetypins** [drush-ops/drush#1868]
I recently updated drush to 8.0.1, but I am now unable to smoothly update modules in a Drupal 7 installation. When attempting to updates, I get a "Destination directory exists" and when drush attempts to roll-back the update, that fails silently and the module directory is then missing.

Here's the full error message:
    Note: A backup of your project will be stored to backups directory if it is not managed by a supported version control system.
    Note: If you have made any modifications to any file that belongs to one of these projects, you will have to migrate those modifications after updating.
    Do you really want to continue with the update process? (y/n): y
    Destination directory /Volumes/.../sites/all/modules/stable/mollom already exists.                                                    [error]
    Updating project mollom failed. Attempting to roll back to previously installed version.                                                                                  [error]

This project is managed by a VCS, and of course I'm doing this in a development environment, but I can't seem to find any other information about this error.

**Comment by AdamPS** [comment]
I think you have the same problem as #1056.  I'm surprised more people aren't seeing this.

**Comment by greg-1-anderson** [comment]
Drush `pm-*` commands are maintenance only; closing
