### ISSUE TITLE
drush make option to force a modification of .info files when cloning from Git even if repository isn't hosted on Drupal.org

### ISSUE THREAD

**Issue by bircher** [drush-ops/drush#187]
https://drupal.org/node/2005070 by Danylo Dragan

Currently drush make doesn't modify .info files when cloning from Git if repository isn't hosted on Drupal.org.

For the purposes of custom continuous integration scenarios it's necessary to be able to force a modification of .info files when cloning from Git even if repository isn't hosted on Drupal.org.

**Comment by ergonlogic** [comment]
The referenced pull request was merged. So I'm closing this.
