### ISSUE TITLE
DRUSH_PHP

### ISSUE THREAD

**Issue by com2** [drush-ops/drush#1871]
In drupal documentation (https://www.drupal.org/node/1302418) I find reference to this environment variable that would allow drush to run under an alternative PHP version. The example alias does not work. What is the modern equivalent of DRUSH_PHP or why is the documented alias not working for me.

**Comment by weitzman** [comment]
Docs on drupal.org are not supported. See docs.drush.org

That variable is only supported when using Composer built Drush, not drush.phar. It is now recommended to adjust your path for right PHP before calling drush.
