### ISSUE TITLE
Drush regression with themes' commands

### ISSUE THREAD

**Issue by DuaelFr** [drush-ops/drush#1878]
Some themes (eg Omega) defines drush commands to help themers to do their job.

With Drush 7, these commands were runnable even when the theme was not installed.
With Drush 8, they are runnable only if the theme is installed and set by default. Even if it's one of its subthemes that's set by default, the commands won't run.

Steps to reproduce:
1. Download and install Drupal 7
2. $ composer require drush/drush:8.*
3. $ drush cc drush
4. $ drush omega-guard
Command omega-guard needs the following module(s) enabled to run : omega
5. $ rm -rf composer.* vendor
6. $ composer require drush/drush:7.*
7. $ drush cc drush
8. $ drush omega-guard
Work as expected

**Comment by weitzman** [comment]
Modern Drush is more careful to only allow access to commandfiles that belong to enabled themes and modules. In this case you have to manually incude the Omega directory using the --include option, Then your commands will be available.

**Comment by DuaelFr** [comment]
Thank you for your answer!
Could we just pass the module/theme machine name to --include instead of the full path to be able to create scripts that works in all cases? It'd be a lot better for TX and DX don't you think? :)

**Comment by weitzman** [comment]
Neither Drupal nor Drush knows anything about disabled/uninstalled modules and themes. You will have to script this outside of Drush.

**Comment by DuaelFr** [comment]
How can drush list these commands in its drush help then?
Currently, these commands are appearing in the drush help but cannot be run without using the --include option. Is it a bug?

**Comment by weitzman** [comment]
The help listing is a special case. For performance, we don't do a full bootstrap so we don't yet know what extensions are enabled. So we should help for commands that are not actually runnable. Its arguably a bug and arguably a command discovery feature.

Hopefully you get an error message telling you to enable a Omega extension when you try to run it. If not, we have a bug thats been fixed and broken a couple times over the years.

I think we could exclude non-runnable commands without too much performance penalty. I dont know of an open issue for that but it comes up periodically.

**Comment by DuaelFr** [comment]
A last though. In Drupal 8 it makes sense to not take in consideration disabled themes as base themes have to be enabled for the site to work. The thing is that in Drupal 7 they don't have to be enabled at all. It wouldn't be a big deal if they just had to be enabled but the problem also occurs when they are enabled but not set as the default theme. Would it be possible to automatically include all the enabled themes, even if they are not the default one?

**Comment by weitzman** [comment]
Please help test #1879 if possible. Should implement your last request.
