### ISSUE TITLE
I am not sure I understood the documentation right - Drush master-branch for Win10

### ISSUE THREAD

**Issue by Benosika** [drush-ops/drush#1881]
Please give me your help, I feel a bit bitter and confused, and it would set me straight with this issue...

After I installed Git for Windows (GFW) I didn't install Cygwin or anything else actually since I understand that GFW is the most general\basic\broad unix-emulator for windows anyway.

It's important for me to use GFW and not Ubuntu since I encounter many problems with (at least) the current LTS version of Ubuntu and it's not lazyness; These are mainly driver\language\keyboard-syncronization\compatibility problems that are not that fast to solve, and I don't have the resources to that easily at least in the coming year.

My questions:

1. Can GFW be less stable than Ubuntu or at least more problematic in such cases?

2. Should I install anything else besides GFW?

3. What would be the best, most fast, most "efficient" command to all the Drush master-branch "dependencies" to run it smoothly? These "dependencies" include (If I didn't miss anything): Linux Zip, Tar, Tar.gz, composer.

4. What except WAMP's PHP\mySQL will require a manual Path Variable setting?

**Comment by weitzman** [comment]
Welcome to Drush. I kindly ask that you ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a>. This Github project is for contributing code or reporting bugs.

**Comment by weitzman** [comment]
One last note is that the install docs for Windows now recommend using cquia Dev Desktop for Windows. That's easier than setting up all the dependencies. See http://docs.drush.org/en/master/install-alternative/#windows

**Comment by Benosika** [comment]
Hello Moshe, I used Drush 7.0 in WIndows10 now without any problem. All the problems I encounter are in relation only to Drush master-branch.

When I requested similar type of help, my thread was closed down at Drupal Answers (Image attached)... A thing that make my feeling even more bitter.

I did not know Acuia Dev Desktop is a free software. I will use it... But please, with great plea, if you have some spare time, please answer shortly, and in the most simple words you can on the questions I asked. Just that me, and those who will come after me (and especially for a case Acquia dev desktop will no longer be free software - If that would happen), will have a better, general understanding\more clear lines of these environments\emulators for installing Drush master-branch on Win10...

![selection_001](https://cloud.githubusercontent.com/assets/13021900/11959300/331b41ec-a8d5-11e5-9732-44580c4f2402.png)

**Comment by weitzman** [comment]
The response on Drupal Answers explains the problem with your question. Rephrase so that the answer is a fact, not an opinion. That is, "What programs does Drush 8 depend on for Windows.".

Also, if you follow links at http://docs.drush.org/en/master/install-alternative/#windows you actually see a list of dependencies on windows.

**Comment by Benosika** [comment]
I wanted to know if there is a complete list of Drush-master-branch--only Linux UNIX based programmes... I just want the list I started to include the two 4-5 more programs I missed... Just to have a foundation to go on from in the future; THe Git for windows list (which I haven't seen then) seems very long... About 70 programs... I guess only 10 of them uses for Drush master-branch... Anyway, supplemented with this knowledge I'll read it again...

I must say I became kind of anxious the moment I saw "Acuiqa" Because that moment I was saying to myself "Are they really suggest me a payable solution as a first-line option?" That's of course, when I didn't no it's free software.

I also didn't feel very good when I saw that the current versions of Drupal VM or Vlad support only Drush 6.0\6.6.0 or 7.0.0 ...

I'll be happy to detail more of the instructions of this is possible... I want to share my ideas both as a student for programming and as one who took some courses in Psychology and have some experience in Psychology of reading of texts, and knowledge accessibility.
