### ISSUE TITLE
Shallow clones do not include .git directory in working copies

### ISSUE THREAD

**Issue by achton** [drush-ops/drush#1891]
When using the `--shallow-clone` command, I would expect to be able to continue working with the cloned git repo for each project (e.g. run `git fetch --unshallow`). It seems that Drush Make is removing the **.git** directory when I use this command.

Here is my Drush make file for testing:

```
core: 8.x
api: 2
projects:
  drupal:
    type: core
    download:
      tag: 8.0.1
```

And here is the command I run:

```
$ drush make --verbose test.make.yml tmp --shallow-clone --no-cache --no-clean
```

When running this, I have no .git folder available in `tmp/`. The temporary folder also does not contain it.

If I run the git command that Drush informs me is run (`git clone http://git.drupal.org/project/drupal.git tmp --verbose --progress --depth=1 --branch=8.0.1`), I see the **.git** folder.

Also, if I use `--working-copy` instead, things work as I expect.

This is using Drush 8.0.1 and also latest drush-unstable.phar. I'm using Git 2.5.0.

**Comment by jhedstrom** [comment]
Drush Make always removes the `.git` directory unless `--working-copy` is specified. IIRC, the shallow clone option is always used unless it is fetching a working copy, but perhaps not.

**Comment by richardbporter** [comment]
Ah - it would be nice if `--shallow-clone` would leave these in place. 

> this option will significantly speed up makes which involve modules stored in very large git repos.

I can't see how deleting a bunch of .git folders would speed up a make.

**Comment by greg-1-anderson** [comment]
Make is maintenance only; closing.
