### ISSUE TITLE
drush_get_extensions($include_hidden = TRUE) is broken in Drupal 8

### ISSUE THREAD

**Issue by chx** [drush-ops/drush#1892]
Drush needs to set `$GLOBALS['settings']['extension_discovery_scan_tests''] = TRUE` to make `Settings::get('extension_discovery_scan_tests')` in `ExtensionDiscovery` evaluate to `TRUE` to make this function work as promised by the argument. I could patch this but won't because the github process is way too cumbersome.

**Comment by greg-1-anderson** [comment]
Make is maintenance only; closing.
