### ISSUE TITLE
Remove file_exists for index.php in Drupal 8 installations

### ISSUE THREAD

**Issue by lainosantos** [drush-ops/drush#1895]
I'am using the Drupal 8 core package with a Symfony Project, so a don't need the index.php file as front controller, because I use the app.php of Symfony. But drush (\Drush\Boot\DrupalBoot8) exec a file_exists at index.php to validate a D8 installation.

This file is essential to the server command, but not to others, and this file don't define a D8 installation.

I suggest remove this verification and add an option to pass alternative front controller to server command.

The drupalconsole check for autoload.php, and it's the right.

**Comment by greg-1-anderson** [comment]
Made a PR for this at #1956

**Comment by greg-1-anderson** [comment]
Fixed as suggested. Thanks.

**Comment by lainosantos** [comment]
Thanks.
