### ISSUE TITLE
Drush 6.6.0, using the --uri="<site>" flag doesn't overwrite the "uri" value in the alias file

### ISSUE THREAD

**Issue by bhasselbeck** [drush-ops/drush#1899]
It's possible this was addressed in a different version, but I have an alias file that I've downloaded and have loaded into drush.  However, when I throw a --uri flag to speak to a specific multisite site, it always reverts to the default URI because the alias explicitly declares it in it's configuration.  Drush should be intelligent enough to replace that URI properly.

**Comment by weitzman** [comment]
Please upgrade to 8.x - this is fixed. A related issue for remote-host is open at #1883. Post here if upgrading does not resolve the issue.

**Comment by ElijahLynn** [comment]
The remote host issue appears to actually be #1493, in case it matters.
