### ISSUE TITLE
drush.bashrc exits/terminates the shell if drush is not executable

### ISSUE THREAD

**Issue by krlucas** [drush-ops/drush#1900]
Line 120 of drush.bashrc checks to see if drush is executable. If not it will "exit 0", completely terminating the shell session.

It would seem preferable to fail a little more gracefully and "return" instead, like line 16 of drush.complete.sh does.

I discovered this by running "drush init" to "enrich the bash startup" but later removed (temporarily) .composer/vendor/bin from my PATH. New terminal sessions would fail. I had to edit the .bashrc through the GUI to fix.

**Comment by weitzman** [comment]
Makes sense to me. Any objections? Ping @greg-1-anderson

**Comment by greg-1-anderson** [comment]
Yeah, `exit 0` in this context is a mistake, as it terminates the parent process.  oops!

**Comment by weitzman** [comment]
Fixed. Anyone who ran this before might want to run delete ~/.drush/drush.bashrc and rerun `drush init` in order to get the changes.
