### ISSUE TITLE
Fatal error: Call to undefined function field_attach_load() by Drush used "site-install"

### ISSUE THREAD

**Issue by henrytran9x** [drush-ops/drush#1904]
hi ! i had build my Profile install . My Profile install on Browser worked fine . When i used command Drush "site-install", this my command install "drush -y site-install myprofile --db-url=mysql://root:''@localhost:''/test --account-name=admin --account-pass=xxx --account-mail=example@example.com --site-name=our.site --site-mail=example@example.com". I had error "Fatal error: Call to undefined function field_attach_load()" in D:\xampp\htdocs\hosting\includes\entity.inc on line 354". Module Field included core Drupal why underfined function field_attach_load() ? I used drush 6.0 .so how to fixed this error ? 
Thanks !

![error_drush_install](https://cloud.githubusercontent.com/assets/5550894/12193193/65a08e38-b618-11e5-8b6a-f8c25011fd15.png)

**Comment by weitzman** [comment]
In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.

**Comment by henrytran9x** [comment]
Thank you !
