### ISSUE TITLE
Drush make fails if included file is empty

### ISSUE THREAD

**Issue by pendashteh** [drush-ops/drush#1908]
This is a working `.make` file:

>   ; build.make
>     core = "7.x"
>     api = "2"
>     projects[drupal][version] = "7.x"
>     includes[] = "_modules.make"
>     includes[] = "_themes.make"
>     includes[] = "_libraries.make"

However, if there is nothing in `_libraries.make`:

>   ; _libraries.make
>     ; +++++ Libraries +++++

Then it will throw error upon running drush make:

>   $ drush make build.make _build
>     Illegal string offset 'format' make.utilities.inc:676                                         [warning]
>     array_replace_recursive(): Argument #1 is not an array make.utilities.inc:98                  [warning]
>     array_reverse() expects parameter 1 to be array, null given make.utilities.inc:103            [warning]
>     array_replace_recursive(): Argument #2 is not an array make.utilities.inc:98                  [warning]
>     array_reverse() expects parameter 1 to be array, null given make.utilities.inc:103            [warning]
>     The 'core' attribute is required                                                              [error]
>     You need to specify an API version of two in your makefile:                                   [warning]
>     api = 2
>     Beginning to build build.make.                                                              [ok]
>     No core project specified.                                                                    [error]
>     Drush Make failed to download all projects. See the log above for the specific errors.        [error]

&&

> Drush Version   :  8.1-dev

**Comment by xtfer** [comment]
The problem appears to be that, if the core= attribute is not specified, Drush attempts to detect the type by checking for valid YAML. Just about any .ini file will return as valid YAML, so it fails. The workaround is to add a core= property to the make file.

**Comment by pendashteh** [comment]
Confirmed that adding core attribute to the included file does fix the issue. Thanks Chris!
