### ISSUE TITLE
Security Update mechanism for drush itself?

### ISSUE THREAD

**Issue by mc0e** [drush-ops/drush#1911]
I want a mechanism that I can run cheaply on a regular basis that can be used to raise an alert when an update is needed.

There's been a [recent issue](https://groups.drupal.org/node/506128) which resulted in some tightening of security in the way drush does things.  This has lead to me looking at somewhat dated versions of drush on various servers and thinking about how to maintain updates.

[docs.drush.org](http://www.drush.org/en/master/install/) recommends upgrading via the same method that is used for the original installation.  That's OK when an upgrade is known to be required, but it provides now mechanism for tracking when an update is available or recommended, or failure to update has security implications.

What do people recommend here?

**Comment by weitzman** [comment]
You can use Composer to learn about new drush updates or you can follow Github's Releases atom feed.
