### ISSUE TITLE
Composer is installed and pathes but autoload.php unreachable

### ISSUE THREAD

**Issue by Benosika** [drush-ops/drush#1912]
I've installed Composer and setted Path values (c:\Userdata\Appdata && c:\ProgramData\ComposerSetup\bin) but I still get in Drush-master: "Unable to load autoload.php. Drush now requires Composer in order to install its dependencies and autoload classes". Composer.JSON is also available at at c:/drush-master and all seems in place. Can you please suggest what is missing?

**Comment by weitzman** [comment]
I dont know whats wrong, but I do know that the install docs no longer recommend using Composer, unless are building your whole site with Composer. See http://docs.drush.org/en/master/install/ or just use Acquia's Dev Desktop [per Drush's recommendation](http://docs.drush.org/en/master/install-alternative#windows).

**Comment by Benosika** [comment]
Hello Weitzman, first I use VirtualBox with Ubuntu and can run Drush easily from there but it's important for me to run on Win.

Since I don't really use Composer at all - according to your message I deleted it from Windows and also it's two path variables, and restarted server... But drush-master keeps giving me the same message... You might have any advice for me? Something to check or to change somewhere?

**Comment by weitzman** [comment]
My first advice is to use Dev Desktop. If thats not possible, delete your old drush install and then install per http://docs.drush.org/en/master/install/. I suspect you are not really using drush.phar.

**Comment by Benosika** [comment]
Ran search to find drush.phar but didn't anywhere so I downloaded it and putted in c:/drush-master. Maybe it wasn't downloaded with wget (even though I installed wget) and configured it's PV c:\Program Files (x86)\GnuWin32.

Anyway the error persists :\
