### ISSUE TITLE
syntax error, unexpected end of file in drushrc.php 

### ISSUE THREAD

**Issue by rallen-temp** [drush-ops/drush#1913]
Hi,

After installing the latest stable version of Drush via Composer, and running the `drush init` command, I get an error afterwards when trying to run Drush.

The error is in https://github.com/drush-ops/drush/commit/aec2188ccff45ba69ddcd3e264bbf28532b1a3dd#diff-ce6639aa61b243b71a998bf90cb8bdacR284

The error that I get is:
```
drush --version
Drush command terminated abnormally due to an unrecoverable error.                                                                               [error]
Error: syntax error, unexpected end of file, expecting variable (T_VARIABLE) or '$' in /home/vagrant/.drush/drushrc.php, line 292
```

This is the output of the `drush init` command:

```
foo@xyz:~/.drush$ drush init -y --add-path
Copied example Drush configuration file to /home/vagrant/.drush/drushrc.php                                                                      [ok]
Copied example Drush bash configuration file to /home/vagrant/.drush/drush.bashrc                                                                [ok]
Copied Drush completion file to /home/vagrant/.drush/drush.complete.sh                                                                           [ok]
Copied example Drush prompt file to /home/vagrant/.drush/drush.prompt.sh                                                                         [ok]
# Include Drush bash customizations.
if [ -f "/home/vagrant/.drush/drush.bashrc" ] ; then
  source /home/vagrant/.drush/drush.bashrc
fi

# Include Drush completion.
if [ -f "/home/vagrant/.drush/drush.complete.sh" ] ; then
  source /home/vagrant/.drush/drush.complete.sh
fi

# Include Drush prompt customizations.
if [ -f "/home/vagrant/.drush/drush.prompt.sh" ] ; then
  source /home/vagrant/.drush/drush.prompt.sh
fi

# Path to Drush, added by 'drush init'.
export $PATH="$PATH:/opt/smg/composer_home/vendor/bin"

Append the above code to /home/vagrant/.bashrc? (y/n): y
Updated bash configuration file /home/vagrant/.bashrc                                                                                            [ok]
Start a new shell in order to experience the improvements (e.g. `bash`).  
```

Removing the dollar sign `$` from the end of the file solves the issue.

**Comment by rallen-temp** [comment]
Dang it - https://github.com/drush-ops/drush/pull/1914 !!!

LOL!

Thanks man.

**Comment by seanhamlin** [comment]
Might want to rebuild http://files.drush.org/drush.phar as anyone that downloads this at present will encounter this issue. I'm guessing a new drush of Drush is required here @weitzman ?

**Comment by gagarine** [comment]
Yes I confirm the drush.phar as the issue a new build would be very nice.

**Comment by jeremygrajales** [comment]
Same issue here. Is there an older drush.phar hosted anywhere without this issue? Or any installation alternatives for the time being?

**Comment by click2tman** [comment]
This error is still valid. I just installed drush using the same method and got the error. removing the $ resolved it.

**Comment by HoangNam18** [comment]
removing the '$' at the end of file resolved it.

**Comment by summerg** [comment]
Agree - Remove $ at end of file

**Comment by adriend** [comment]
Same here, remove $ at the end of the file fix the problem

**Comment by skippednote** [comment]
I've tried `composer global require drush/drush:dev-master` and  `composer global require drush/drush` but I'm still getting the same error. Has anyone been able to figure this out?

**Comment by weitzman** [comment]
After upgrading to dev-master or 8.0.3, delete ~/.drush/drush.bashrc and then re-run `drush init`.
