### ISSUE TITLE
md5 equal operator hash collision

### ISSUE THREAD

**Issue by Robert-Th** [drush-ops/drush#1915]
if (drush_op('md5_file', $download_path) != $release['mdhash'] && ... != in wget pm hash compare makes all hashes with form ^0+e\d*$ pass as equal.

https://github.com/drush-ops/drush/blob/master/commands/pm/package_handler/wget.inc

**Comment by greggles** [comment]
@Robert-Th is that what you were suggesting?

**Comment by ergonlogic** [comment]
It looks like PHP is casting to floats which, with a 0 base are always just 0:

    php > print((('0000e1234' != 0) ? 'true' : 'false') . "\n");
    false
    php > print((('0000e1234' !== 0) ? 'true' : 'false') . "\n");
    true
    php > print((((int)0000e1234 !== 0) ? 'true' : 'false') . "\n");
    false
