### ISSUE TITLE
Alias wildcard name collisions

### ISSUE THREAD

**Issue by jamesrward** [drush-ops/drush#1918]
I have sites on 2 hosts (acquia and pantheon) with the same names.  By using their provided aliases.drushrc.php files I end up with mysite.test and pantheon.mysite.test respectively.  If I try to do drush @mysite.test status it notifies me that it will check the status on both the pantheon and acquia sites.  Is there a way to be explicit about the alias I want?  In this case I want the acquia site status but the wildcard for the start of the alias name is adding pantheon to the mix.

**Comment by weitzman** [comment]
Assigning to @greg-1-anderson. Meanwhile, I suggest do implement [hook_drush_sitealias_alter()](http://api.drush.org/api/drush/drush.api.php/function/hook_drush_sitealias_alter/master) to rename an alias. You can do that in a custom commandfile.

**Comment by greg-1-anderson** [comment]
I agree with @weitzman regarding the workaround, but I'm not really sure what the best behavior is here. I like being able to refer to aliases both by @group.shortname and @shortname; the utility of this is predicated on not giving different sites the same name.

We might make things better by improving site-local aliases (c.f. #1532), so you could cwd to your local 'mysite' to disambiguate between different remote test sites. This presumes that you are using a drush.wrapper with --local.

My basic advice would be to avoid giving two sites the same name, though.

**Comment by jamesrward** [comment]
While I agree there are plenty of work-arounds here I think the default behaviour is incorrect.  If there is one and only one exact match for a site alias drush should operate on that site.  If there are multiple near-matches then the current behaviour would be expected.  The current behaviour leans away from explicit and towards more implicit behaviour in this edge-case.

Also, in case anyone from Acquia wanders in here, this whole thing wouldn't have come up if they would namespace their aliases the way Pantheon does.

**Comment by weitzman** [comment]
This is really and edge case IMO. Edit your alias files or alter them as suggested.
