### ISSUE TITLE
Higher bootstrap level for a command - In Ubuntu ???

### ISSUE THREAD

**Issue by Benosika** [drush-ops/drush#1919]
drush config-set system.theme default bartik

did that to change my theme back to bartik after a WSOD with premium theme but than I got
![hbl](https://cloud.githubusercontent.com/assets/13021900/12285703/83006556-b9c5-11e5-885d-dc9f17acc487.PNG)

Any idea?

**Comment by weitzman** [comment]
In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.

**Comment by Benosika** [comment]
Okay Weitzman, no problem. I've published the question there with my own answer (link below). 

I do want to ask Wetizman - Are there any kinds of support requests I can ask here? or else I didn't understand what this "Issues" forum is about... Ben,

**Comment by weitzman** [comment]
No suppurt requests. This Github space is only used for development. The issue tracker is used only for bug reports and feature requests.

**Comment by Benosika** [comment]
Sure, I understand, thank you for clarifying that to me!
