### ISSUE TITLE
Error on missing output format (and docs)

### ISSUE THREAD

**Issue by hansfn** [drush-ops/drush#1922]
Hi!

I have just played with pm-projectinfo and discovered some features of Drush output formatting that I think can be improved. Before writing any patches, I would like to get some feedback.
1. Selecting a non-existing output format, Drush reverts to the default format. I would prefer an error.
2. Selecting fields doesn't work with several output formats:
   - Formats like json and yaml always print everything. I would actually like to get just the fields I selected. Or, get an error if fields are selected, telling me that this format doesn't support fields.
   - The list format really only handles one field. If you give multiple fields (`--fields=type,path`), Drush output the array keys instead. (The machine name for the project when using pm-projectinfo.) I would like to get an error, if multiple fields are selected.

In addition the documentation (docs/output-formats.md) should be updated to make the treatment of fields clearer for the different formats. I can do that when we have reached consensus here.

PS! The csv and table formats behaves like expected when multiple fields are selected.

**Comment by weitzman** [comment]
1. is probably a bug - I agree
2. is #333 

Docs improvements are welcome. Been wanting this for a while.

**Comment by hansfn** [comment]
Thx for the pointer to #333. I'll comment there (and submit a patch for the docs afterwards). If you don't beat me, I'll write a patch for 1.

**Comment by greg-1-anderson** [comment]
Further improvements to output formatters in Drush 8 are unlikely. Drush 9 is considerably improved in this respect.
