### ISSUE TITLE
pm-projectinfo improvements - type filter and machine name

### ISSUE THREAD

**Issue by hansfn** [drush-ops/drush#1925]
- I think it would be nice to have the type filter/option (that pm-list has) also for pm-projectinfo. This is trivial to implement, so maybe it was left out for a reason? If not, I'm happy to write a patch.
- It would be nice if the machine name was available as a field. I know it's part of the label - "human-readable name (machine name)" - and that you can get it by abusing the list format ("drush pm-projectinfo --format=list --fields=x,y" where x and y really means whatever). It would be trivial to add a machine_name field in drush_get_extensions so again I wonder if it's left out for a reason?

**Comment by greg-1-anderson** [comment]
These would be worthwhile enhancements. PRs welcome.

**Comment by greg-1-anderson** [comment]
Make is maintenance only; closing.
