### ISSUE TITLE
Cannot modify header information - headers already sent by (output started at phar:///usr/local/bin/drush/includes/output.inc:38) common.inc:698

### ISSUE THREAD

**Issue by AlexShapka** [drush-ops/drush#1927]
Suddenly started to get the error message in subject. My environment:

> drush status
> Drupal version                  :  7.41                         
> Site URI                        :  http://default                       
> Database driver                 :  mysql                                
> Database hostname               :  localhost                            
>  Database port                   :                                       
>  Database username               :  dbuser 
>  Database name                   :  cp                                   
>  Drupal bootstrap                :  Successful                           
>  Drupal user                     :                                       
>  Default theme                   :  customname                              
>  Administration theme            :  0                                    
>  PHP configuration               :  /etc/php.ini                         
>  PHP OS                          :  Linux                                
>  Drush script                    :  /usr/local/bin/drush                 
>  Drush version                   :  8.0.1                                
>  Drush temp directory            :  /tmp                                 
>  Drush configuration             :                                       
 > Drush alias files               :                                       
 > Install profile                 :  standard                             
>  Drupal root                     :  /home/username/public_html 
 > Site path                       :  sites/default                        
 > File directory path             :  sites/default/files                  
 > Private file directory path     :  ../private                           
 > Temporary file directory path   :  /tmp

**Comment by weitzman** [comment]
In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.
