### ISSUE TITLE
Getting drush error: the file name, directory name, or volume label syntax is incorrect after module update

### ISSUE THREAD

**Issue by nizzok** [drush-ops/drush#1929]
I've been adding and removing modules with drush when something went wrong. I'm using the latest version of Acquia devdesktop and now when I run any drush command I get the error "the file name, directory name, or volume label syntax is incorrect." This error seems to be specific to the site I am working on, because drush works outside of the site folder. How can I fix this? It was after installing composer_manager as a dependency for Openlayers.

**Comment by weitzman** [comment]
In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.
