### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by dgtlmoon** [drush-ops/drush#1932]
```
Unable to load autoload.php. Drush now requires Composer in order to install its dependencies and autoload classes. Please see README.md
```

There is no specific details about this in the README.md

**Comment by weitzman** [comment]
In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.

**Comment by dgtlmoon** [comment]
This is not about support, this is about a bug/task which is missing documentation referred to by that error message

**Comment by dgtlmoon** [comment]
Thanks! a bit annoying you closed this issue, then made a commit after I rebuffed your update, but thanks anyway, all these little documentation tweaks save a lot of people a lot of time!
