### ISSUE TITLE
Drush log created about 150k records in locales_source

### ISSUE THREAD

**Issue by finex** [drush-ops/drush#1936]
Hi, **_drush_search_index()** function contains the following line:

```php
drush_log(dt(number_format($percent, 2) . '% complete. Remaining items to be indexed: ' . $remaining), LogLevel::OK);
```

I'm currently working a website where the ```locales_source``` table is filled with about 150k records with garbage like:

``` 49.98% complete. Remaining items to be indexed: 123456 ```

Is really necessary to translate this log?

**Comment by weitzman** [comment]
Sorry - we misused the dt() API there. Also fixed in 7.x branch.
