### ISSUE TITLE
Cannot use Drush with XDebug and PhpStorm for debugging

### ISSUE THREAD

**Issue by jepster** [drush-ops/drush#1938]
Hi,

I was searching the web for advices about running Drush with XDebug and PhpStorm. I could not find out why my cli php.ini config does not bring the debugger to stop at my breakpoints. Including the option for "breaking at first line in php scripts". PHP is installed with XDebug on my Ubuntu server system which already works with debugging via the Apache2 webserver.

If I run e.g. 
```
drush core-cron
```
The command runs and my debugger does not stop. It follows my php.ini config for XDebug.
```
[xdebug]
xdebug.max_nesting_level=256
xdebug.remote_enable=true
xdebug.profiler_enable=0
xdebug.remote_connect_back=1
xdebug.remote_autostart=1
xdebug.idekey="PHPSTORM";
```

With

```
xdebug.remote_autostart=1
```

I "should" force XDebug to run on every script. 

Has anybody an idea what goes wrong? Any help would be appreciated. :)

**Comment by weitzman** [comment]
Not sure, but I know it helps to up the maximum number of simultaneous connections in the PHP debug preference pane in PHPStorm. Mine is set to 19.
