### ISSUE TITLE
Drush & user sync

### ISSUE THREAD

**Issue by toddmbloom** [drush-ops/drush#1941]
Now that D8 is in the wild and using UUID, is there a way to use Drush to just sync user information/roles/permissions (well, not so much roles since those are config based now but users specifically) between different versions of the site. 

I know you can do sql-sync but that usually does everything. It would be pretty amazing to have a `drush sync-users` command between different servers (staging to prod to staging, for example).

**Comment by weitzman** [comment]
You would use Migrate or default_content for slinging entities around like Users. Not in scope for core Drush.
