### ISSUE TITLE
Drush Memory Limit Detection Does Not Account For "Infinite" memory

### ISSUE THREAD

**Issue by rvtraveller** [drush-ops/drush#1947]
Drush includes a function `drush_memory_limit()` which is designed to get the memory limit of PHP.  However, the function assumes the memory limit will be a certain value (256M, 1G, etc).  While this is good in practice, many default installation of PHP (such as Ubuntu LTS versions) ship with a `memory_limit` for the CLI of -1.

For the most part, this is not a big deal.  For batch processing via `drush_backend_batch_process()`, this is a huge deal because it forces Drupal to bootstrap for every single item in the batch.  If you have 100,000 items to process then you have to bootstrap Drupal 100,000 times.  Setting the memory limit to a real value (2G, 512M, whatever) allows Drush to process multiple entries per Drupal bootstrap which significantly reduces processing time.

I'm not sure of the best approach for what to do if `memory_limit` is -1.  Maybe we just give the user some sort of warning?  My quick Google searches didn't yield an easy way for PHP to see how much free RAM is on the box so this value could be set intelligently.

**Comment by weitzman** [comment]
Not sure how to proceed, but I want to share prior work at #1405

**Comment by weitzman** [comment]
Maybe we should just act like value is 512M or something when php reports -1.

**Comment by greg-1-anderson** [comment]
I like the solution in #1405. Let's just move that over to batch_7.inc as suggested.

**Comment by greg-1-anderson** [comment]
The implication being, that Drush treats "unlimited" as "yes, I really have unlimited memory". If you want batch processing to fork a new process to account for memory limits, then set memory_limit.

**Comment by alexpott** [comment]
This causes interesting issues for very long running processes like site map generation when memory limit is set to -1. I think it'd be useful if we provided a way to trigger spawning a new process. If seems like either having the ability to define a drush memory limit on the command line like `DRUSH_MEMORY_LIMIT=512M vendor/bin/drush` or having an arbitrary time limit that once exceeded we should start a new thread. I think I prefer a time limit that is settable via an environment variable.

**Comment by weitzman** [comment]
@alexpott would this work for your use case `php -d memory_limit=2GB vendor/bin/drush ...`. That should fork new processes when you exceed 60% mof 2GB in memory usage.

**Comment by alexpott** [comment]
I tried doing `php -d memory_limit=2GB` but that didn't work. In the forked process it was the value in php.ini. I think this is because $env is passed in as null and therefore eventually in \Symfony\Component\Process\Process::start() and \Symfony\Component\Process\Process::$inheritEnv never gets set to TRUE. At least on Drupal 8 and SF3. This behaviour is probably different on SF4.

**Comment by alexpott** [comment]
Also on the project where this is an issue they had some code somewhere doing a `ini_set('MEMORY_LIMIT', -1')` :( 

So regardless of env var inheritance I still think a default time limit for drush batch processes is not the worst idea. It makes them more like a batch process in the brwoser.

**Comment by alexpott** [comment]
The reason why `php -d memory_limit=2GB` is because of the custom code doing the set to -1 ... environment inheritance is working just fine in SF3. Sorry for the noise.

**Comment by weitzman** [comment]
>  If you want batch processing to fork a new process to account for memory limits, then set memory_limit.

I'm cool with that position so closing this.
