### ISSUE TITLE
drush make --overrides gives "Unknown option: --overrides."

### ISSUE THREAD

**Issue by frankcarey** [drush-ops/drush#1948]
So I've been trying to test out some of the impressive sounding new drush make features, but I'm running into issues.

Supposedly the --overrides cli option was added along with adding it to make files, but when I go to use it, I get the error.
`Unknown option: --overrides. ` .. I tried this with versions 8.0.1, 8.0.2, and dev-master but nothing seems to work.

It's documented here: http://www.drush.org/en/master/make/#overrides
And it was added here: https://github.com/drush-ops/drush/blame/3657fa99a9c47e4684786ccac71270b2db27615e/commands/make/make.utilities.inc#L64

**Comment by ergonlogic** [comment]
Git bisect identifies 66b2eef5 as the first bad commit.

**Comment by ergonlogic** [comment]
The error there wasn't the same, however:

    $ drush make-lock production.make --overrides=testing.make
    file_get_contents(production.make): failed to open stream: No such file or directory make.utilities.inc:575                               [warning]
    Invalid or empty make file: production.make                                                                                               [error]
    Failed to parse makefile production.make.        

This appears unrelated, though odd. Changing the makefile path to `./production.make` appears to have resolved that bit.

**Comment by ergonlogic** [comment]
With further testing, I'm not able to replicate this issue. Make sure to update composer and clear the Drush cache. If anyone else is able to replicate this, I'd appreciate step-by-step instructions, as this is working fine for me at 8.0.1, 8.0.2 and master.

**Comment by ergonlogic** [comment]
It turns out I was testing against the wrong command. I usually use `make-lock` to see the results of parsing makefiles, rather than run through the actual build process with `make`. Unfortunately, `make-lock` doesn't validate options, as `make` does. We should maybe look at consolidating the option-handling for all the makefile generating commands.

**Comment by dkinzer** [comment]
I tried the `--overrides` option locally and can confirm that this error is generated.  Further, using the ` --strict=0` argument prevents error but does not result in any overrides being applied.
