### ISSUE TITLE
Using remote alias, _drush_find_commandfiles() doesn't scan ../drush when merging CLI options

### ISSUE THREAD

**Issue by simesy** [drush-ops/drush#1960]
When my custom command is being prepared to execute over ssh via an alias, (in the preflight part of command.inc), drush is losing extra CLI arguments. I have `--test` an optional argument, and when I debug drush, `--test` is not being passed in the ssh command.

But, when I specify `--include=../drush` as another CLI argument, Drush suddenly scans the command file there and the argument is passed successfully.

To recreate.
1. Create a commandfile outside the webroot in ../drush
2. Add a command and specify an option --test
3. Create a site alias, pointing to a remote server in ../drush
4. Run the command with --test, and debug to see no --test being passed

I'm not able to force drush to scan the directory using $options['include'] in a drushrc.php or as an 'include' option in the alias, only when I pass it on the command line.

I hope this is enough information.

**Comment by weitzman** [comment]
What version of drush? If it is master branch, how recent?

**Comment by simesy** [comment]
Master from 26 hours ago. 86de4b6

**Comment by simesy** [comment]
I have just now checked latest master, and also 8.0.0 tag, and the problem appears to exist in both.

**Comment by weitzman** [comment]
I can reproduce this when I call a command which does not exist anywhere on the local system. In that case the --test option is not passed along. I'm pretty sure thats the same behavior that @greg-1-anderson mentioned in https://github.com/drush-ops/drush/pull/1924#discussion-diff-49902619. 

About to commit a fix. Please test and report back.

**Comment by simesy** [comment]
b233972 works - and yes I agree it's the behaviour greg reported.

Huge thanks for the rapid turnaround!
