### ISSUE TITLE
Custom location is ignored in drush make-lock command.

### ISSUE THREAD

**Issue by ncharalampidis** [drush-ops/drush#1967]
In the function **make_generate_from_makefile** the following code causes "location" property to be ignored in generation of a new lock file:
```
$ignore = array('build_path', 'contrib_destination', 'core', 'location', 'make_directory', 'l10n_url', 'download_type');
foreach ($ignore as $key) {
  unset($projects[$name][$key]);
}
```
This works fine for d.o module but causes trouble for modules with custom location other than d.o.
Maybe an approach to solve this would be the following:
```
$ignore = array('build_path', 'contrib_destination', 'core', 'make_directory', 'l10n_url', 'download_type');
foreach ($ignore as $key) {
  unset($projects[$name][$key]);
}
if ($projects[$name]['location'] == 'https://updates.drupal.org/release-history') {
  unset($projects[$name]['location']);
}
```

**Comment by ncharalampidis** [comment]
Created a pull request using the above approach: #1968
This approach works fine for me and solves the issue.

**Comment by weitzman** [comment]
Lets focus conversation on the PR
