### ISSUE TITLE
List all patch info in one central PATCHES.txt file

### ISSUE THREAD

**Issue by damienmckenna** [drush-ops/drush#197]
Rather than littering the directory structure with multiple PATCHES.txt files, it would be better to centralize this all in one file. Furthermore, the file should automatically grab other information from d.o related to the patch, namely the project name, the issue URL and title. The end result should be something like this:

```
CTools: Block errors on admin pages
http://drupal.org/node/1925018
http://drupal.org/files/ctools-n1925018-12.patch

EntityCache: Performance improvement re terms loading
http://drupal.org/node/1670848
http://drupal.org/files/entitycache-remove-unnecessary-setcaches-1670848.patch
```

Explanation:

```
[project name]: [issue title]
[issue URL]
[patch URL]
```

The above information should be readily identifiable if the patches listed in the make file have the issue number included in the URL, e.g.:

```
projects[drupal][patch][985814] = http://drupal.org/files/drupal-actions-985814-11-D7.patch
```

**Comment by greg-1-anderson** [comment]
This is a good idea, but make is deprecated and not getting much attention. Closing old issues.
