### ISSUE TITLE
Installation of Drush leads to sftp failing

### ISSUE THREAD

**Issue by micrology** [drush-ops/drush#1981]
A standard install of Drush modifies the user's .bashrc shell initialisation script.  In doing so, it causes bash to echo text to stdout at start up.  However, if sftp is used to access the user's home directory from a remote client for an interactive transfer session, it fails because it encounters output on stdout which it is not expecting.

In short, the Drush installation modifications to .bashrc generates a hard-to-track down error in a completely unrelated program, sftp!

The work-around is to delete the added Drush script form .bashrc while using sftp.

**Comment by weitzman** [comment]
I have added the word Optional to the last step of install instructions. I hope that helps.
