### ISSUE TITLE
Provide a command to download third party scripts

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#1983]
### Problem/Motivation
Drupal standards require that contributed modules ship without third party code. Usually all external libraries are placed under _sites/all/libraries_ directory. The users owe it to themselves [to install external libraries](https://www.drupal.org/node/1440066) and keep it up to date. The process is really tedious and so that some modules provide a special drush command to facilitate installing a library the module depends on [(example)](http://cgit.drupalcode.org/colorbox/tree/drush/colorbox.drush.inc).

### Proposed solution
Implement a generic drush command that can be used to install any kind of frontend libraries. We could use _libraries.yml_ files to retrieve required meta information about libraries. Another option is adopting third party tools like [bower.php](http://bowerphp.org/).

**Comment by weitzman** [comment]
External PHP libraries should be fetched via `composer`. Javascript and CSS and such should be bower or grunt or somesuch. No need for Drush to reinvent those wheels. And no need for Drush to wrap bower.php. Just use the bower natively.

**Comment by Chi-teck** [comment]
> Just use the bower natively.

It's not possible for contributed modules. Nor Drupal core nor Libraries API support Bower. That's why contrib maintainers keep creating Drush commands to download just one concrete library. The issue is not about reinventing wheels but about replacing dozens existing wheels bundled with contributed modules with one that comes from the Drush core.
I just grepped Drupal 7 contrib codebase to check the scale of the issue. See results in attachment.
[drush-download.txt](https://github.com/drush-ops/drush/files/127726/drush-download.txt)
