### ISSUE TITLE
Can't install rest module due to always_populate_raw_post_data not set to -1

### ISSUE THREAD

**Issue by limelime** [drush-ops/drush#1984]
When I try to install `rest` module using drush, it showed the following errors:
```
drush -r "${DRUPAL_DIR}" -y pm-enable rest
Module rest doesn't meet the requirements to be enabled.                                                                                                [error]
The always_populate_raw_post_data PHP setting should be set to -1 in PHP version 5.6. Please check the PHP manual for information on how to correct     [error]
this. (Currently using always_populate_raw_post_data PHP setting version Not set to -1.)
```
Looking into phpinfo(), the parameter `always_populate_raw_post_data` is already set to -1 for local and master.

However, I'm able to install `rest` module from Drupal itself.

I'm running Drush v8.0.3 and clean install of Drupal 8.0.3 on Debian Jessie.

**Comment by weitzman** [comment]
CLI PHP often has a different php.ini than the web server. This config must differ between the two php instances. You can find out which php.ini is being used by drush by running `drush status`.
