### ISSUE TITLE
Drush 8.0.3 while calling drush qd, causes error undefined method Drush\Boot\EmptyBoot::conf_path() in phar

### ISSUE THREAD

**Issue by rw355** [drush-ops/drush#1985]
Error: Uncaught Error: Call to undefined method Drush\Boot\EmptyBoot::conf_path() in phar:///usr/local/bin/drush/commands/core/core.drush.inc:993
Stack trace:
#0 phar:///usr/local/bin/drush/includes/command.inc(366): drush_core_quick_drupal('testsite')
#1 phar:///usr/local/bin/drush/includes/command.inc(217): _drush_invoke_hooks(Array, Array)
#2 phar:///usr/local/bin/drush/includes/command.inc(185): drush_command('testsite')
#3 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#4 phar:///usr/local/bin/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#5 phar:///usr/local/bin/drush/includes/startup.inc(321): drush_main()
#6 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#7 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#8 {main}
  thrown in phar:///usr/local/bin/drush/commands/core/core.drush.inc, line 993

**Comment by weitzman** [comment]
I'm unable to reproduce this even with same .phar. Please share the command you are running along with full --debug output.

**Comment by rw355** [comment]
Ah, sorry.. I figured out I used a wrong core version string. The full input and output was:

$ drush qd testsite --core=drupal-7.0.x --yes

Could not locate drupal version 7.0.x-dev.                                                                                                         [error]
Could not download requested project(s).                                                                                                           [error]
Caching 'uri' 127.0.0.1:8888 in DRUPAL_ROOT/drush/drushrc.php                                                                                      [ok]
DRUPAL_ROOT/drush/drushrc.php already exists. Overwrite? (y/n): y
PHP Fatal error:  Uncaught Error: Call to undefined method Drush\Boot\EmptyBoot::conf_path() in phar:///usr/local/bin/drush/commands/core/core.drush.inc:993
Stack trace:
#0 phar:///usr/local/bin/drush/includes/command.inc(366): drush_core_quick_drupal('testsite')
#1 phar:///usr/local/bin/drush/includes/command.inc(217): _drush_invoke_hooks(Array, Array)
#2 phar:///usr/local/bin/drush/includes/command.inc(185): drush_command('testsite')
#3 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#4 phar:///usr/local/bin/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#5 phar:///usr/local/bin/drush/includes/startup.inc(321): drush_main()
#6 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#7 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#8 {main}
  thrown in phar:///usr/local/bin/drush/commands/core/core.drush.inc on line 993
Drush command terminated abnormally due to an unrecoverable error.
