### ISSUE TITLE
'Psr\Log\AbstractLogger' not found

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#1990]
I just updated drush (composer says c0212b2) and now just running 'drush' or anything else crashes with this error:

```
'Psr\Log\AbstractLogger' not found in /Users/joachim/.composer/vendor/drush/drush/lib/Drush/Log/Logger.php
```

**Comment by joachim-n** [comment]
Seeing this with 8.0.3 too. 8.0.0 works ok.

**Comment by weitzman** [comment]
Please post your composer.json and how you are installing and updating
drush. Share exact commands.

**Comment by joachim-n** [comment]
It currently is:

```
{
    "require": {
        "drush/drush": "8.0.0"
    }
}
```

I'm afraid I don't remember what it was before -- dev/master possibly?

The only composer command I've been using is 'composer global update'.

**Comment by weitzman** [comment]
So you changed that to 8.0.3, ran composer global update, and for the error? please redo that and post the full --debug log.

**Comment by joachim-n** [comment]
Changed composer.json to have 8.0.3.

```
composer global update
Changed current directory to /Users/joachim/.composer
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing pear/console_table (v1.2.1)
  - Installing pear/console_table (v1.3.0)
    Loading from cache

  - Installing psr/log (1.0.0)
    Loading from cache

  - Updating drush/drush (8.0.0 => 8.0.3)
    Checking out ee77dc526aa9fb26611ded18b5caef801b29aca7

Writing lock file
Generating autoload files
```

Then:

```
$ drush --debug
Using the Drush script found at /Users/joachim/.composer/vendor/drush/drush/drush.launcher using proc_open

Fatal error: Class 'Psr\Log\AbstractLogger' not found in /Users/joachim/.composer/vendor/drush/drush/lib/Drush/Log/Logger.php on line 31
```

**Comment by weitzman** [comment]
No idea. Try removing your global drush and installing the .phar as per docs.drush.org/en/master/install/

**Comment by SpiesInOrbit** [comment]
The reinstall worked for me. Thanks!

**Comment by gh640** [comment]
I met the same error.

For future visitors, The error in my environment was caused by Psr with the version incompatible with the installed Drush. In my case, it was fixed when I unregister other packages such as `drupal/coder` once and reinstalled the Drush again.

    composer g remove drush/drush
    composer g remove drupal/coder  # Uninstall other packages once
    composer g require drush/drush
    composer g require drush/coder
