### ISSUE TITLE
Terminal Notifier installation message keeps appearing 

### ISSUE THREAD

**Issue by ccharlton** [drush-ops/drush#1991]
Even though I have already installed the Terminal Notifier I keep seeing this message appear (Mac OS X):

`terminal-notifier command failed. Please install it from https://github.com/alloy/terminal-notifier. Or you may specify an alternate command to run by specifying --notify-cmd=<my_command>`

**Comment by weitzman** [comment]
Run with --debug to see the command that is being issued. Then try that in your terminal and fix any errors.

**Comment by ccharlton** [comment]
I see something about ```line 1: -title: command not found```, so maybe the newlines are messing with the call to notifier. I'll take a look into my local setup to see if it's just me.

```
Executing: terminal-notifier -message
 -title Drush
  terminal-notifier (1.6.3) is a command-line tool to send OS X User Notifications.
...
  sh: line 1: -title: command not found
```
