### ISSUE TITLE
Drush make does not delete files that go away with a module update

### ISSUE THREAD

**Issue by joshuaboltz** [drush-ops/drush#2001]
It appears that when using drush make, it does not clear out any unused files when performing module updates.
I'm using Drush 8.0-dev to run the drush make command.

As a real example, I've been trying to update l10n_update module from 7.x-1.0 to 7.x-2.0.
I start with l10n_update 7.x-1.0.
I have this included in my file.make file:
projects[l10n_update][subdir] = "contrib"
projects[l10n_update][version] = "2.x"

This file is present in the local docroot:
sites/all/modules/contrib/l10n_update/l10n_update.locale.inc

When I run drush make file.make --no-core, the module updates properly to 7.x-2.0, leaving me this when I check the diff:
-; Information added by Drupal.org packaging script on 2014-04-12
-version = "7.x-1.0"
+files[] = tests/L10nUpdateCronTest.test
+files[] = tests/L10nUpdateInterfaceTest.test
+files[] = tests/L10nUpdateTest.test
+files[] = tests/L10nUpdateTestBase.test
+; Information added by Drupal.org packaging script on 2014-11-10
+version = "7.x-2.0"
 core = "7.x"
 project = "l10n_update"
-datestamp = "1397295556"
+datestamp = "1415625781"

Looking at 7.x-2.0 on the repo for the l10n_update module, it shows no l10n_update.locale.inc:
http://cgit.drupalcode.org/l10n_update/tree/?h=7.x-2.0

So, when I run git status, I expect to see a:
deleted:   sites/all/modules/contrib/l10n_update/l10n_update.locale.inc

But, I only see this, plus some newly added untracked files:
modified:   sites/all/modules/contrib/l10n_update/README.txt
modified:   sites/all/modules/contrib/l10n_update/css/l10n_update.admin-rtl.css
modified:   sites/all/modules/contrib/l10n_update/css/l10n_update.admin.css
modified:   sites/all/modules/contrib/l10n_update/l10n_update.admin.inc
modified:   sites/all/modules/contrib/l10n_update/l10n_update.api.php
modified:   sites/all/modules/contrib/l10n_update/l10n_update.batch.inc
modified:   sites/all/modules/contrib/l10n_update/l10n_update.drush.inc
modified:   sites/all/modules/contrib/l10n_update/l10n_update.info
modified:   sites/all/modules/contrib/l10n_update/l10n_update.install
modified:   sites/all/modules/contrib/l10n_update/l10n_update.module

The current fix is to be sure to delete the existing module directory before running drush make, but I think it makes more sense to just delete the files.
https://www.drupal.org/node/2374833

The reason the file needs to disappear is because it gives some errors about redeclaring functions when database updates are run.

**Comment by ergonlogic** [comment]
Have you tried the `--overwrite` option when running Drush Make?

    --overwrite                               Overwrite existing directories. Default is to merge.

**Comment by weitzman** [comment]
no reply.
