### ISSUE TITLE
drush 8.0.3 installation failure: symfony/yaml conflict

### ISSUE THREAD

**Issue by nikolas** [drush-ops/drush#2006]
Hi, I have drush 7.1.0 installed with composer, and I'm having trouble installing drush 8:

```
$ ./bin/composer  global require drush/drush:8.*
Changed current directory to /home/nnyby/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drush/drush 8.0.3 requires pear/console_table ~1.3.0 -> satisfiable by pear/console_table[v1.3.0].
    - Conclusion: don't install pear/console_table v1.3.0
    - Conclusion: don't install drush/drush 8.0.2
    - Conclusion: don't install drush/drush 8.0.1
    - Conclusion: don't install symfony/yaml v2.7.9
    - Conclusion: remove symfony/yaml v2.8.2
    - Conclusion: don't install symfony/yaml v2.7.8|keep symfony/yaml v2.8.2
    - Conclusion: don't install symfony/yaml v2.7.7
    - Installation request for pear/console_table == 1.2.1.0 -> satisfiable by pear/console_table[1.2.1].
    - Installation request for drush/drush 8.* -> satisfiable by drush/drush[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - Conclusion: don't install symfony/yaml v2.8.2
    - drush/drush 8.0.0 requires symfony/yaml 2.7.* -> satisfiable by symfony/yaml[v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
    - Can only install one of: symfony/yaml[v2.7.0, v2.8.2].
    - Can only install one of: symfony/yaml[v2.7.1, v2.8.2].
    - Can only install one of: symfony/yaml[v2.7.2, v2.8.2].
    - Can only install one of: symfony/yaml[v2.7.3, v2.8.2].
    - Can only install one of: symfony/yaml[v2.7.4, v2.8.2].
    - Can only install one of: symfony/yaml[v2.7.5, v2.8.2].
    - Can only install one of: symfony/yaml[v2.7.6, v2.8.2].
    - Installation request for symfony/yaml == 2.8.2.0 -> satisfiable by symfony/yaml[v2.8.2].


Installation failed, reverting ./composer.json to its original content.

$ ./bin/composer --version
Composer version 1.0-dev (9e623f50e7c883a1108352dd61c3d77a65e41130) 2016-02-18 09:56:21
$ php --version
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

Let me know if you have any advice.

**Comment by webbj74** [comment]
Have you checked `/home/nnyby/.composer/composer.json` to see if there are other packages installed globally which are dependent on `symfony/yaml`?

**Comment by nikolas** [comment]
Here is my `composer.json`:
```
$ cat ~/.composer/composer.json 
{
    "require": {
        "drush/drush": "7.*"
    }
}
```

**Comment by weitzman** [comment]
No idea whats up there. Maybe remove drush and start over. Use the .phar if needed - see install instructions.

**Comment by nikolas** [comment]
Thanks for the tip. I was able to solve this by removing drush with composer, then reinstalling.

```bash
vim ~/.composer/composer.json  # Removed the line containing drush
composer global update
composer global require drush/drush:8.*
```

**Comment by subharanjanm** [comment]
Thanks @nikolas !! Works like a charm :)

**Comment by pranav-pathak** [comment]
Thanks @nikolas !!  It works for me as well.

**Comment by tarassuliatitskiy** [comment]
@nikolas you're the man!!!

**Comment by sasanikolic90** [comment]
Thanks @nikolas!

**Comment by Zaft** [comment]
Also worked for me, nice work @nikolas

**Comment by illepic** [comment]
composer global require drush/drush:8.*

That is unfortunately now met with 

    zsh: no matches found: drush/drush:8.*

for me with Ubuntu 16.04

**Comment by timclifford** [comment]
Also worked for me, Thanks @nikolas

**Comment by jfcartier** [comment]
THANKS! @nikolas

**Comment by jaenalexander** [comment]
Great, Thanks! @nikolas

**Comment by therealchiko** [comment]
Worked!

**Comment by trangunghoa** [comment]
Thanks @nikolas. It's worked for me

**Comment by cbovard** [comment]
Wicked and Thumbs up

**Comment by agudivad** [comment]
Thanks @nikolas 👍

**Comment by gzveri** [comment]
for those like me who had no idea where is the composer.json file located in windows7 , I've found it at C:/Users/G/AppData/Roaming/Composer/composer.json , where /G/ is my windows user name.

**Comment by gAusWeb** [comment]
yeah boi, thanking you! :)

**Comment by nikolas** [comment]
Okay, everyone can stop thanking me now.

**Comment by niraimani** [comment]
Thanks @nikolas, that steps helped me to upgrade drush 8.

**Comment by bjornbreck** [comment]
Thanks @nikolas, dead simple!

**Comment by greg-1-anderson** [comment]
Everyone on this thread should be using [cgr](https://github.com/consolidation/cgr) instead. :wink:

**Comment by DavidABruce** [comment]
@nikolas saves my day

**Comment by deborah-blessy** [comment]
Thank you @weitzman got my drush updated. Special thanks to @gzveri for the path...

**Comment by greg-1-anderson** [comment]
I would like to point out to everyone on this thread, and our visitors from the future, that despite the large number of "thank you's" here, the advice is none-the-less incorrect.

Un-installing the old Drush (`composer global remove drush/drush`) is a good first step; however, you should not use `composer global require` to install Drush, or any other command line tool. If you do, you will have problems again in the future. Removing and re-adding components will not always fix the problem.

Please read [Fixing the Composer Global Command](https://pantheon.io/blog/fixing-composer-global-command).
