### ISSUE TITLE
The drush command 'migrate-manifest' could not be found

### ISSUE THREAD

**Issue by alex-moreno** [drush-ops/drush#2014]
Not sure if it's a dupe issue, couldn't find it. Just trying to run an upgrade in drush8 and get:

The drush command 'migrate-manifest' could not be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new extensions.

Tried with previous 8.* version and got the same problem :-(

Thanks in advance

**Comment by weitzman** [comment]
that command was moved to https://www.drupal.org/project/migrate_plus (see project page).
