### ISSUE TITLE
@self alias not working correctly for DRUSH_BOOTSTRAP_DRUSH

### ISSUE THREAD

**Issue by AdamPS** [drush-ops/drush#2016]
Custom drush command boots to DRUSH_BOOTSTRAP_DRUSH.

In 8.0.2 call drush_sitealias_get_record('@self'); and it returns a valid alias.
In 8.0.3 it returns an empty array.

I think the problem may come from https://github.com/drush-ops/drush/commit/70752cf0c4f340322044fedb81cbbeb4b87e3d77 by @weitzman.

In the new code, drush_sitealias_create_self_alias calls drush_get_context('DRUSH_SELECTED_DRUPAL_ROOT') which is not defined at DRUSH_BOOTSTRAP_DRUSH level.

In case you are wondering about the requirement, the custom command is a "make new site" command "drush ALIAS my-make-site" that works based on my global alias file.  The command operates without any drupal root and creates the root.

Thanks

**Comment by weitzman** [comment]
It makes sense to me that @self is empty during DRUSH_BOOTSTRAP_DRUSH (aka preflight). We can't define a Drupal site until we determine a Drupal root. I think your command was relying on a happy accident. Please rewrite to not depend on @self. Sorry for the inconvenience.

**Comment by AdamPS** [comment]
OK, thanks, no problem.

In case it helps anyone else, the code I found that works is this:
` $alias = drush_sitealias_get_record(drush_get_context('DRUSH_TARGET_SITE_ALIAS'));`

@weitzman - Any chance you could comment please on whether this is something I can reasonably rely on, or another happy accident?  (And in the latter case, any better suggestion?)

**Comment by weitzman** [comment]
Thats the best way in Drush 8 and earlier. Hopefully we clean it up for Drush9.

**Comment by AdamPS** [comment]
Thanks
