### ISSUE TITLE
Docs for building drush from git

### ISSUE THREAD

**Issue by AdamPS** [drush-ops/drush#2019]
I'm trying to help fix some bugs I've found.  I'm used to drush 6, and not familiar with the new system of phar files.  I have a git checkout of master with some local changes that I'd like to test.  I can't find any docs that explain how I can run my code.  I guess I need to create a phar and it seems to be done using a tool called box.  But I can find lots of different possible websites offering box, and I get errors when I try to run it.

Please can we have some instructions?

**Comment by weitzman** [comment]
You can continue to use your git checkout with patches. Just run `composer install` after each time you pull changes from our github. that will fetch all your dependencies and write an autoload.php file. These are generic  instructions for any Composer project.

An alternative is to run the command mentioned in our [alternative install docs](http://docs.drush.org/en/master/install/) - `composer global require drush/drush:dev-master --prefer-source`. That gets you a git clone that you can hack as needed.

**Comment by AdamPS** [comment]
@weitzman Thanks for the reply.

I would still recommend creating documentation, rather than just leaving the answer here where it's hard for anyone to see.  I think you may not quite appreciate the lack of information that a potential reader has.

NB the install docs at http://docs.drush.org/en/master/install/ tell me to wget a drush.phar.  I have no idea at this point that I ought to be using composer if I want to build.  Yes I am beginning to see that you guys are big fans of it, but it's not a standard Drupal requirement, it wasn't needed in drush 6, and I didn't even have it installed.
