### ISSUE TITLE
Follow correct update procedure for drupal core

### ISSUE THREAD

**Issue by AdamPS** [drush-ops/drush#2022]
Correct procedure is [here](https://www.drupal.org/node/1223018).

Principal problem relates to step 3), "Remove all old core files and directories".
- Latest master preserves all files (_pm_update_core search for 'backup target') from old version.  Consequence is that if the new version of Drupal removes a file it doesn't get removed locally.  Although unlikely, worst case the file could have been removed to fix a security issue.
- The preserving code only works if there was a backup (depends on command line options).  Without that, it's like old drush (see #614), and any custom files in the root or profile directory are removed.

Why don't we instead do exactly what the instructions say?
- After installing core, save a list of the files installed.  
- Download the new core to a working directory.
- Delete all files on the list from the old core.  If the list is missing, take it from the new core which normally will be right.
- Copy from the working directory to the root.  (Added bonus is that files like /sites/README.txt are updated which the instructions say should be.)

Secondary problem: drush doesn't set maintenance mode.  Does anyone know if this is deliberate?  Looks like it does in D8, but only during database update.  Of course whilst we are copying files, it will be pure luck if any page works at all.  But it seems like it would be safest in case the process has a long delay at any stage.  I guess the downside is that a minor error could leave the site in maintenance mode which might be unwanted.

**Comment by weitzman** [comment]
1. Hopefully someone will chime in about file preservation.
2. We don't set maint mode because thats rarely needed for code only updates. Furthermore, pm-updatecode already has enough responsibilties. pm-update adds the complexity of updatedb on top of it. If you want maint mode, script it into your process as per the Example in vset docs.

**Comment by AdamPS** [comment]
Thanks.  In terms of point 1), I believe this proposal is the more or less the same as proposed by @greg-1-anderson in #614.  Minor differences:
- I am proposing it only for core (the use-case for adding site-local files within a module directory is much less clear)
- I am not suggesting we actual fetch the old release again at upgrade time, but instead keep a record of the top-level files in it.

If there is consensus, I will have a go at coding it, although it will be a few weeks before I have time.

I'm happy to ignore maint mode.

**Comment by greg-1-anderson** [comment]
I am wary about the `save the list of files downloaded` part. Maybe this should be an example pm-updatecode hook rather than a part of the core Drush pm code.

**Comment by AdamPS** [comment]
Thanks.  OK, so if we don't save the list, I guess the other options I can see are
- re-fetch the old core to check what files are in it (and figure out what to do if we can't)
- assume the list of top-level files never changes (similar to current code, except can improve it to work even if a backup has not been configured)

**Comment by AdamPS** [comment]
OK after some thinking and testing, here is a simple proposal.
- The list of core directories is specified explicitly in the Drupal core upgrade instructions for each major version and it seems unchanging across minor versions.  Put these lists explicitly into the code, and delete those directories before upgrade.
- Don't bother to delete individual files in the root.  They will get overridden by the new version.  If a root file is removed in a new version of Drupal core, then drush will not automatically remove it.  This is likely to be a rare event, and likely flagged in the release note if removing the file really is important.  Make no attempt to handle it automatically.
- In the pre_update phase, pass as $items_to_test the core directories, plus _all_ files (not directories/links) in the root.  It's doesn't really matter if we backup/check a few extra files.

(Continued...)

**Comment by AdamPS** [comment]
What are the benefits?  Well 90% of users will notice no difference from now.  However:
- Any scenario where there is no backup (e.g. SVN) we avoid losing files; this is my principal motivation.
- New method is safer.  If the upgrade stops part way (PHP error, control-C, pkill, SSH error, server shutdown, etc), can simply retry.  Whereas with the old code, everything was a mess!
- New method is simpler to understand.  No longer are some files moved to a drush-XX directory, others stashed in the backup then it all pulled back together later.  40-50 lines less code.  Removed some unnecessary dependence on VCS/download method which help future maintainability.  backup->pre_update now better fits the rest, paying attention to $items_to_test.

Pull request coming up later as I'm out of time for now.

**Comment by AdamPS** [comment]
Closing as drush maintainers have deprecated pm in favour of composer.
