### ISSUE TITLE
Unable to run drush with XDebug listener on in PHPStorm

### ISSUE THREAD

**Issue by wonder95** [drush-ops/drush#2029]
I recently installed drush 8 (currently on v8.0.3) using Composer, and one issue I've noticed is that I can no longer run drush when my XDebug listener is turned on in PHPStorm. I've been using both tools for years - including debugging drush commands and drush itself - and with previous drush versions, this was never an issue. However, only since installing drush 8.x with Composer has this problem started.

What troubleshooting info can I get/look at that would help?

Thanks.

**Comment by weitzman** [comment]
In your PHPStorm PHP Debug settings, turn up the max simultaneous connections number to 19 (thats what i have anyway).

**Comment by wonder95** [comment]
Yup, that was it. The irony is, I actually saw that in a [blog post](https://www.drupaleasy.com/quicktips/debugging-phpstorm-including-drush) today, and then forgot about it. I guess the big red arrow didn't catch my attention. :-(

Sigh.
