### ISSUE TITLE
Windows bug in drush finder

### ISSUE THREAD

**Issue by chriscohen** [drush-ops/drush#2032]
When running drush 8.0.3 on Windows 7 Enterprise, after a composer install, under any circumstances, will always result in "The filename, directory name, or volume label syntax is incorrect."

This happens whether the command is executed in Git Bash or a DOS prompt.

This will happen wherever the command is executed within a Drupal 8 site.

This might be related to #1839 .

More output:
```
$ drush8 -d -d status
Cache HIT cid: 8.0.3-commandfiles-0-22cc07ba50fbfcef4999a0563276ec1a     [debug]

[0.48 sec, 2.15 MB]
Begin redispatch via drush_invoke_process(). [0.9 sec, 5.29 MB]         [notice]

Backend invoke: "C:\\Webs\\mysite\\vendor\\bin\\drush.launcher"      [command]

--root="C:\\Webs\\mysite\\docroot" --debug --verbose  core-status
2>&1 [1.02 sec, 5.31 MB]
Calling proc_open("C:\\Webs\\mysite\\vendor\\bin\\drush.launcher"  --root="C:\
\Webs\\mysite\\docroot" --debug --verbose  core-status 2>&1);
The filename, directory name, or volume label syntax is incorrect.
End redispatch via drush_invoke_process(). [1.04 sec, 5.31 MB]          [notice]
```

Things I've tried:
* Aliasing drush directly to mysite/vendor/drush/drush/drush and mysite/vendor/drush/drush/drush.php.
* Setting the executable bit on drush.launcher in Git Bash (not a "real" executable bit on Windows but was worth a shot).
* Executing drush.launcher manually. If executed outside of the Drupal 8 docroot, it works absolutely fine. When executed inside it, it no longer works.
* Executing drush from outside the Drupal 8 docroot, but specifying the --root on the command line. This yields "The filename, directory name, or volume label syntax is incorrect".
* Executing drush from the exact same location as above, but pointing --root at a non-Drupal 8 site. This works perfectly.

**Comment by chriscohen** [comment]
I have found a workaround to this. I have my own copy of drush 8 installed locally, but also, there is a version installed by composer.json into the site's vendor dir (outside the webroot).

If I simply delete the one in the site, the global one sort of seems to "take over" and everything works.

I don't know why this works or what's wrong with the one in the site itself. It looks fine to me and is exactly the same version.

Leaving this open in case anyone has input on what's going on here.

**Comment by weitzman** [comment]
This suggests a problem in the code path when a global Drush hands over to local Drush (Windows only)

**Comment by justinlevi** [comment]
I'm also seeing this issue.

**Comment by weitzman** [comment]
Same as #1674?

**Comment by weitzman** [comment]
Lets close in favor #1674
