### ISSUE TITLE
drush sa not printing list of local sites

### ISSUE THREAD

**Issue by joelcollinsdc** [drush-ops/drush#204]
drush 6.x: local site aliases are not printing out.  Also, the aliases defined in alias files dont print out with an '@' like they used to in drush5... has that funcitonality changed?

<code>
Joels-Air:joel d7core.localhost$ pwd
/Users/joel/work/htdocs/d7-core/sites/d7core.localhost
Joels-Air:joel d7core.localhost$ drush sa | grep d7core
Joels-Air:joel d7core.localhost$ drush5 sa | grep d7core
d7core.localhost
Joels-Air:joel d7core.localhost$
</code>

debug output if it helps.
<code>
Joels-Air:joel d7core.localhost$ drush sa --debug
Bootstrap to phase 0. [0.01 sec, 2.35 MB]                            [bootstrap]
Drush bootstrap phase : _drush_bootstrap_drush() [0.01 sec, 2.48 MB] [bootstrap]
Loading drushrc "/Users/joel/.drushrc.php" into "user" scope. [0.02  [bootstrap]
sec, 2.48 MB]
Cache MISS cid: 6.2-dev-alias-path--bc5eca404d7ad716f0b63666f55aaf7a     [debug]
[0.02 sec, 2.48 MB]
Cache HIT cid:                                                           [debug]
6.2-dev-commandfiles-0-368d7cd1e857a15c8dcefee2e0c315fc [0.03 sec,
2.49 MB]
Bootstrap to phase 0. [0.17 sec, 6.17 MB]                            [bootstrap]
Bootstrap to phase 0. [0.26 sec, 6.17 MB]                            [bootstrap]
Found command: site-alias (commandfile=sitealias) [0.26 sec, 6.17 MB][bootstrap]
Loading outputformat engine. [0.44 sec, 6.19 MB]                        [notice]
Cache HIT cid: help_text [0.45 sec, 6.27 MB]                             [debug]
Calling hook drush_sitealias_print [0.45 sec, 6.26 MB]                   [debug]
Loading outputformat engine. [0.45 sec, 6.26 MB]                        [notice]
Returned from hook drush_sitealias_print [0.63 sec, 6.29 MB]             [debug]
aegir2dev
aegir2dev.aegir2-dev
aegir2dev.project
congress
cs
none
pantheon
pantheon.budsmith.dev
pantheon.budsmith.live
pantheon.budsmith.test
pantheon.test-openpublic.dev
pantheon.test-openpublic.live
pantheon.test-openpublic.test
self
Command dispatch complete [0.63 sec, 6.27 MB]                           [notice]
Peak memory usage was 7.55 MB [0.63 sec, 6.26 MB]                       [memory]
Joels-Air:joel d7core.localhost$
</code>

**Comment by greg-1-anderson** [comment]
Okay, here is a deep philosophical question.  As noted above, Drush 6 does not include the "@" in front of alias names in the output of the sa command, whereas Drush 5 did.  I think this was a mistake, but it was not caught prior to the 6.0 stable release.

So, the question is, should Drush 7 print "@site", like Drush 5 did, or should it continue to print "site", like Drush 6 currently does?

I think it makes sense to include the "@" in the output, but it might be a bit odd to have "@" in Drush 5 and 7, but not in 6.

@weitzman, what do you think?

**Comment by weitzman** [comment]
I agree that it should have @ in front.

**Comment by greg-1-anderson** [comment]
I added the '@' back in at the head of alias records when site-alias is producing a list of sites (e.g. with no arguments).

It seems like the local site's site directory names are being included as well, but I didn't change anything for this -- it was just working for me.  Test again on latest 'master' branch, and re-open / comment here if still having problems with this part.
