### ISSUE TITLE
Automatic Identify Version

### ISSUE THREAD

**Issue by guiajlopes** [drush-ops/drush#2050]
Hey Guys, I donwloaded Drush 8 and when I'm on Drupal 7 project it download Drupal 8 projects when I do drush dl [module]. I think it should download drupal 7 modules automatically. I know we have --default-major but I think we should select major version automatically based on Drupal installation.

Whay you guys think about it ?

**Comment by weitzman** [comment]
We do already detect the major version when you have a bootstrapped site. Perhaps you are not really bootstrapping the site. Specify --root to be more sure.
