### ISSUE TITLE
Requirements conflict installing Drush 7.1.0 on Ubuntu 12.04 with composer

### ISSUE THREAD

**Issue by benk-cogapp** [drush-ops/drush#2051]
I'm trying to install Drush 7 on Ubuntu 7.1.0 using the alternative install instructions from http://docs.drush.org/en/master/install-alternative/. When I run `composer global require drush/drush:7.1.0`, composer is unable to install a compatible set of packages;

```
$ composer global require drush/drush:7.1.0
Changed current directory to /home/vagrant/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: pear/console_table[v1.2.1, v1.3.0].
    - Can only install one of: pear/console_table[v1.3.0, v1.2.1].
    - Can only install one of: pear/console_table[v1.2.1, v1.3.0].
    - drush/drush 7.1.0 requires pear/console_table ~1.2.0 -> satisfiable by pear/console_table[v1.2.1].
    - Installation request for drush/drush 7.1.0 -> satisfiable by drush/drush[7.1.0].
    - Installation request for pear/console_table == 1.3.0.0 -> satisfiable by pear/console_table[v1.3.0].


Installation failed, reverting ./composer.json to its original content.
```

It seems this means I'm unable to install Drush 7 through either of the recommended methods, since the `.phar` installs 8 as default.

**Comment by benk-cogapp** [comment]
With further experimentation, this works fine when invoked as `composer global require drush/drush:7.*`

**Comment by benk-cogapp** [comment]
Could you give some detail as to why this is closed? Is this a documentation issue (i.e. `composer global require drush/drush:7.1.0` shouldn't work), a configuration issue (something in the local environment is causing it to fail) or something else? Thanks.

**Comment by weitzman** [comment]
is there a reason why you need Drush 7 and not Drush 8. 7 was only the recommended release for a brief period is not well maintained at this point.

**Comment by benk-cogapp** [comment]
My specific use-case is that I'd like to run it with a Drupal 7 site with Registry Rebuild. If Drush 8 was an option then I'd prefer to be able to use that, but it's not yet supported in Drush 8 (https://www.drupal.org/node/1785672) and its `drush cr` appears to be D8-specific.

In the general case, wanting to be able to install Drush 7 doesn't seem like a completely outlandish requirement given the number of Drupal 7 sites still in the wild and the potential for similar lagging support for extensions (or user customisations). If this isn't a supported configuration, it would be good if the documentation at least reflected a stable way of installing Drush 7.

**Comment by benk-cogapp** [comment]
(I've now managed to kludge this into a workable installation by tricking `drush dl` with `drush @none dl registry_rebuild --default-major=7`. I suspect part of the root of my issues in getting this to work is that drush now has 8 as the default major version, so `drush rr` refuses to install.)
