### ISSUE TITLE
Centos - cannot run drush

### ISSUE THREAD

**Issue by pakati** [drush-ops/drush#2052]
Hello All,
I installed composer and drush (was like a whole day to figure it out...), and made it run under a local user, except that I don't have enough privileges to run drush, only if I use sudo.
But with sudo no composer and no drush was working, so I installed the whole thing again with sudo, but was still not working. Then I moved the .composer and .drush files under the usr/bin folder (instead of usr/local/bin) and got some response. The issue is, that I cant run drush, as it produces this error message:
/root/.composer/vendor/drush/drush/drush.launcher: line 42: which: command not found ERROR: can't find php.
There are many tutorials out there on the net, but could not find a solution. Anyone?
Thanks,
//pakati

**Comment by weitzman** [comment]
Non-experts should use the .phar version of Drush. Do a `composer global remove drush` and then follow the install instructions at docs.drush.org/en/master/install/.

In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.
