### ISSUE TITLE
Drush update code should recommend Composer

### ISSUE THREAD

**Issue by mlncn** [drush-ops/drush#2056]
Until documentation catches up, `drush up` should have a message for Drupal 8 noting that the correct way to update should be:

`composer update`

I direct people to Greg Anderson's answer here for more information - http://drupal.stackexchange.com/questions/167922/what-is-the-correct-composer-based-core-update-workflow - and leave all the below error messages so everyone who runs into the same problem can find this answer!

> vagrant@endtb:/vagrant$ drush up
> Update information last refreshed: Fri, 03/04/2016 - 13:28
>  Name    Installed Version  Proposed version  Message          
>  Drupal  8.0.4              8.0.5             Update available 
> 
> 
> Code updates will be made to drupal core.
> WARNING:  Updating core will discard any modifications made to Drupal core files, most noteworthy among these are .htaccess and robots.txt.  If you have made any modifications to these files, please back them up before updating so that you can re-create your modifications in the updated version of the file.
> Note: Updating core can potentially break your site. It is NOT recommended to update production sites without prior testing.
> 
> Do you really want to continue? (y/n): y
> Project drupal was updated successfully. Installed version is now 8.0.5.
> Backups were saved into the directory                                        [ok]
> /home/vagrant/drush-backups/drupal/20160304184142/drupal.
> PHP Fatal error:  Cannot redeclare class Drupal in /vagrant/web/core/lib/Drupal.php on line 79
> PHP Stack trace:
> PHP   1. {main}() /vagrant/vendor/drush/drush/drush.php:0
> PHP   2. drush_main() /vagrant/vendor/drush/drush/drush.php:12
> PHP   3. Drush\Boot\BaseBoot->bootstrap_and_dispatch() /vagrant/vendor/drush/drush/includes/preflight.inc:66
> PHP   4. drush_bootstrap_to_phase() /vagrant/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php:59
> PHP   5. drush_bootstrap_validate() /vagrant/vendor/drush/drush/includes/bootstrap.inc:471
> PHP   6. Drush\Boot\DrupalBoot->bootstrap_drupal_root_validate() /vagrant/vendor/drush/drush/includes/bootstrap.inc:430
> PHP   7. drush_drupal_version() /vagrant/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php:268
> PHP   8. Drush\Boot\DrupalBoot8->get_version() /vagrant/vendor/drush/drush/includes/drupal.inc:43
> PHP   9. drush_drupal_load_autoloader() /vagrant/vendor/drush/drush/lib/Drush/Boot/DrupalBoot8.php:36
> PHP  10. require() /vagrant/vendor/drush/drush/includes/drupal.inc:17
> PHP  11. require() /vagrant/web/autoload.php:14
> PHP  12. ComposerAutoloaderInitDrupal8::getLoader() /vagrant/web/vendor/autoload.php:7
> PHP  13. composerRequireDrupal8() /vagrant/web/vendor/composer/autoload_real.php:45
> PHP  14. require() /vagrant/web/vendor/composer/autoload_real.php:55
> 
> Fatal error: Cannot redeclare class Drupal in /vagrant/web/core/lib/Drupal.php on line 79
> 
> Call Stack:
>     0.0001     221832   1. {main}() /vagrant/vendor/drush/drush/drush.php:0
>     0.0023     387656   2. drush_main() /vagrant/vendor/drush/drush/drush.php:12
>     0.3321    8679864   3. Drush\Boot\BaseBoot->bootstrap_and_dispatch() /vagrant/vendor/drush/drush/includes/preflight.inc:66
>     0.3360    8691936   4. drush_bootstrap_to_phase() /vagrant/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php:59
>     0.3375    8694264   5. drush_bootstrap_validate() /vagrant/vendor/drush/drush/includes/bootstrap.inc:471
>     0.3381    8695760   6. Drush\Boot\DrupalBoot->bootstrap_drupal_root_validate() /vagrant/vendor/drush/drush/includes/bootstrap.inc:430
>     0.3385    8695920   7. drush_drupal_version() /vagrant/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php:268
>     0.3388    8695968   8. Drush\Boot\DrupalBoot8->get_version() /vagrant/vendor/drush/drush/includes/drupal.inc:43
>     0.3388    8696000   9. drush_drupal_load_autoloader() /vagrant/vendor/drush/drush/lib/Drush/Boot/DrupalBoot8.php:36
>     0.3401    8697280  10. require('/vagrant/web/autoload.php') /vagrant/vendor/drush/drush/includes/drupal.inc:17
>     0.3406    8699080  11. require('/vagrant/web/vendor/autoload.php') /vagrant/web/autoload.php:14
>     0.3414    8712184  12. ComposerAutoloaderInitDrupal8::getLoader() /vagrant/web/vendor/autoload.php:7
>     0.3447    8878176  13. composerRequireDrupal8() /vagrant/web/vendor/composer/autoload_real.php:45
>     0.3453    8974688  14. require('/vagrant/web/core/lib/Drupal.php') /vagrant/web/vendor/composer/autoload_real.php:55
> 
> Drush command terminated abnormally due to an unrecoverable error.           [error]
> Error: Cannot redeclare class Drupal in /vagrant/web/core/lib/Drupal.php,
> line 79
> The external command could not be executed due to an application error.      [error]

**Comment by weitzman** [comment]
updatecode is not recommended by Drush maintainers for D8 sites but lots of those are not yet using Composer. Given that, what docs do you recommend we change?

**Comment by mlncn** [comment]
https://www.drupal.org/upgrade/ definitely needs an update.  But regardless of documentation, could Drush could detect if it is being used to update code on Drupal 8 or above, and just suggest that this be done with composer?  And maybe link somewhere like https://www.drupal.org/node/2404989 ?

**Comment by weitzman** [comment]
I dont think thats the right place to let folks know that there is a whole new paradigm in town. Its a much larger change in workflow than just drush.

**Comment by colans** [comment]
> updatecode is not recommended by Drush maintainers for D8 sites

Perhaps this information should be presented to the user when he/she runs this command on a D8 site?  I only discovered this after running into problems.  We could provide a link to [Update procedure in Drupal 8](https://www.drupal.org/node/2700999) instead.

**Comment by weitzman** [comment]
Alas its not that simple. The recommendation is that codebases be assembled and updated via Composer. This is needed because Contrib modules have Composer dependencies and there is no better way to fetch and resolve those dependencies that via Composer. 

Folks who choose to not follow the Composer recommendation are fine using just updatecode.

So, this subtlety in this topic doesn't lend itself to help text and log messages.

**Comment by colans** [comment]
Maybe there's a way to check if Composer is being used?
