### ISSUE TITLE
Drush not updating everything by default

### ISSUE THREAD

**Issue by MartijnBraam** [drush-ops/drush#2057]
`drush pm-update` doesn't update every module by default but only the enabled modules for the current site. This behavior can be fixed by supplying `--check-disabled` so it checks and updates the disabled modules.

The update checker in drupal checks the disabled modules by default so why doesn't drush? This can leave a site insecure if you enable a module that hasn't been update in a while because it isn't checked.

**Comment by clemens-tolboom** [comment]
Are you talking about Drupal 7 or Drupal 8?

**Comment by MartijnBraam** [comment]
This affects both as far as I'm aware.

**Comment by weitzman** [comment]
D* doesn't have disabled modules. SInce this only affects prior versions of Drupal and has an easily available workaround, I'm calling this Won't Fix.
