### ISSUE TITLE
Command for changing a user's name

### ISSUE THREAD

**Issue by torfsen** [drush-ops/drush#2063]
I can change a user's name using Drupal's admin UI, but it would be nice if I could do it via Drush, similar to the existing `user-password` command:

    drush user-name my_old_name --new-name="my_new_name"

**Comment by weitzman** [comment]
Too edge case for core Drush. Can be a contrib

**Comment by webmasterpf** [comment]
Does this feature added to drush 8 ? I don't find information on it.
