### ISSUE TITLE
mysqli only seems not supported (PHP7 issue also)

### ISSUE THREAD

**Issue by EugenMayer** [drush-ops/drush#2068]
it seems like drush7 and drush8 do only support ext/mysql not ext/mysqli? Disabling mysql and only leaving mysqli / mysqlnd active, drush will no longer be able to boostrap. My connection string

`$db_url = "mysqli://root@db:3306/drupalwiki";`

Interestingly this does work in drush6.0-rc2

Beside that ext/mysql is deprecated and has been removed in php7 completely (mysqli only), this leads to issue in php5.5 and others also, when the deprecated interface is not installed.

**Comment by weitzman** [comment]
Is this a dupe of #2002
