### ISSUE TITLE
Drush 8.x not detecting sites other than default in multi-site when installed in sites/all/vendor via composer

### ISSUE THREAD

**Issue by echernyavskiy** [drush-ops/drush#2070]
Steps to reproduce:

    drush dl drupal-7
    # Project drupal (7.43) downloaded to /var/www/drupal-7.43
    cp /var/www/drupal-7.43/sites/default/default.settings.php /var/www/drupal-7.43/sites/default/settings.php
    cp -r /var/www/drupal-7.43/sites/default /var/www/drupal-7.43/sites/site1
    cd /var/www/drupal-7.43/sites/all
    composer require drush/drush:8.0.5

With the above set up, if one was to issue

    cd /var/www/drupal-7.43/sites/site1
     /var/www/drupal-7.43/sites/all/vendor/bin/drush status

the output would be slightly unexpected:

    www-data@php:~/drupal-7.43/sites/site1$ /var/www/drupal-7.43/sites/all/vendor/bin/drush status
     Drupal version         :  7.43                                                        
     Site URI               :  http://default                                              
     PHP executable         :  /usr/local/bin/php                                          
     PHP configuration      :  /usr/local/etc/php/php.ini                                  
     PHP OS                 :  Linux                                                       
     Drush script           :  /var/www/drupal-7.43/sites/all/vendor/drush/drush/drush.php 
     Drush version          :  8.0.5                                                       
     Drush temp directory   :  /tmp                                                        
     Drush configuration    :                                                              
     Drush alias files      :                                                              
     Drupal root            :  /var/www/drupal-7.43                                        
     Drupal Settings File   :  sites/default/settings.php                                  
     Site path              :  sites/default                                               
    
Same story with the globally installed Drush as it simply hands off to the one in `/var/www/drupal-7.43/sites/all/vendor/bin/drush`:

    www-data@php:~/drupal-7.43/sites/site1$ drush status
     Drupal version         :  7.43                                                        
     Site URI               :  http://default                                              
     PHP executable         :  /usr/local/bin/php                                          
     PHP configuration      :  /usr/local/etc/php/php.ini                                  
     PHP OS                 :  Linux                                                       
     Drush script           :  /var/www/drupal-7.43/sites/all/vendor/drush/drush/drush.php 
     Drush version          :  8.0.5                                                       
     Drush temp directory   :  /tmp                                                        
     Drush configuration    :                                                              
     Drush alias files      :                                                              
     Drupal root            :  /var/www/drupal-7.43                                        
     Drupal Settings File   :  sites/default/settings.php                                  
     Site path              :  sites/default                                               
    
Removing the local Drush (installed via composer) resolves the issue:

    rm -Rf /var/www/drupal-7.43/sites/all/vendor/drush /var/www/drupal-7.43/sites/all/vendor/bin/drush*

    www-data@php:~/drupal-7.43/sites/site1$ drush status
     Drupal version         :  7.43                       
     Site URI               :  http://site1               
     PHP configuration      :  /usr/local/etc/php/php.ini 
     PHP OS                 :  Linux                      
     Drush script           :  /usr/local/bin/drush       
     Drush version          :  8.0.5                      
     Drush temp directory   :  /tmp                       
     Drush configuration    :                             
     Drush alias files      :                             
     Drupal root            :  /var/www/drupal-7.43       
     Drupal Settings File   :  sites/site1/settings.php   
     Site path              :  sites/site1                
    
I've narrowed it down to [drush_cwd()](https://github.com/drush-ops/drush/blob/8.0.5/includes/environment.inc#L123) returning incorrect value for the current working directory due to `$_SERVER['PWD']` not being correct.
The `$_SERVER['PWD']` value seems to be correct both in [drush](https://github.com/drush-ops/drush/blob/8.0.5/drush#L115) and [drush.launcher](https://github.com/drush-ops/drush/blob/8.0.5/drush.launcher#L132), but not in [drush.php](https://github.com/drush-ops/drush/blob/8.0.5/drush.php#L10).

Have spent almost two days on it already but no dice, so decided to raise an issue.

---

PHP

    PHP 5.6.19 (cli) (built: Mar  9 2016 01:46:16) 
    Copyright (c) 1997-2016 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

is running in a Docker

    Docker version 1.10.3, build 20f81dd

container atop of

    Linux php.service.company.loc 4.4.0-040400-generic #201601101930 SMP Mon Jan 11 00:32:41 UTC 2016 x86_64 GNU/Linux

**Comment by weitzman** [comment]
Who recommends putting drush in sites/all/drush? Our docs mention that location but its for config/commandfiles/aliases, but not drush itself.

**Comment by echernyavskiy** [comment]
@weitzman I was not following any particular recommendations here - it is more so that the project I was put in charge of has such layout.
Correction to your comment: `drush` is in fact NOT in `sites/all/drush` - it is in `sites/all/vendor/drush` with `composer.json` to be found in `sites/all` respectively.

**Comment by darkogav** [comment]
Out of curiosity, what version of drush are you running?

**Comment by echernyavskiy** [comment]
@darkogav yup, just tried all 8.x versions starting from 8.0.1 and it looks like this regression was introduced in 8.0.3 - compare:

	www-data@php:~/drupal-7.43/sites/site1$ /var/www/drupal-7.43/sites/all/vendor/bin/drush status
	 Drupal version         :  7.43                                                        
	 Site URI               :  http://site1                                                
	 PHP executable         :  /usr/local/bin/php                                          
	 PHP configuration      :  /usr/local/etc/php/php.ini                                  
	 PHP OS                 :  Linux                                                       
	 Drush script           :  /var/www/drupal-7.43/sites/all/vendor/drush/drush/drush.php 
	 Drush version          :  8.0.2                                                       
	 Drush temp directory   :  /tmp                                                        
	 Drush configuration    :                                                              
	 Drush alias files      :                                                              
	 Drupal root            :  /var/www/drupal-7.43                                        
	 Site path              :  sites/site1                                                 

vs.

	www-data@php:~/drupal-7.43/sites/site1$ /var/www/drupal-7.43/sites/all/vendor/bin/drush status
	 Drupal version         :  7.43                                                        
	 Site URI               :  http://default                                              
	 PHP executable         :  /usr/local/bin/php                                          
	 PHP configuration      :  /usr/local/etc/php/php.ini                                  
	 PHP OS                 :  Linux                                                       
	 Drush script           :  /var/www/drupal-7.43/sites/all/vendor/drush/drush/drush.php 
	 Drush version          :  8.0.3                                                       
	 Drush temp directory   :  /tmp                                                        
	 Drush configuration    :                                                              
	 Drush alias files      :                                                              
	 Drupal root            :  /var/www/drupal-7.43                                        
	 Drupal Settings File   :  sites/default/settings.php                                  
	 Site path              :  sites/default

**Comment by weitzman** [comment]
Please move drush out of the docroot. We dont support it there. I'm not sure if thats related to your issue, but its a prerequisite for investigating this. Thanks.

**Comment by echernyavskiy** [comment]
Investigated this some more. So whether it's a globally installed Drush or a site-local Drush, if it's > 8.0.2, however you run it (see my very first comment), it won't properly perform website detection/bootstrap.

@weitzman just to clarify: is site-local Drush not supported at all for Drupal 7 then?

**Comment by weitzman** [comment]
You can have a Drush thats local to the project. I'm assuming you dont maintain your whole project with Composer.

docroot (DRUPAL goes here)
    index.php
    etc.
vendor
    bin
        drush (PROJECT-BUNDLED DRUSH EXISTS HERE)
composer.json (Drush is listed as a requirement)

**Comment by echernyavskiy** [comment]
@weitzman appreciate the suggestion. Drupal 8 went this way and this Drupal 7 project might as well.

**Comment by weitzman** [comment]
I just fixed a big related to this. It would only have affected you if your Finder chose to use proc_open() instead of pcntl_exec() which would be unusual on Linux. If you run with --debug, you see a log message about this at the very beginning. Anyway, if you are still experiencing a problem you could run with --debug and if it says "launching via proc_open()" then you should update to latest on master or 8.x branches. Will release soon.

**Comment by carnnia** [comment]
in drupal 8.4.2 multi-site with drush installed locally via composer:
while in /var/www/public/d8/sites/carnnia.local
../../vendor/bin/drush status gives
Drupal Settings File : MISSING
i think it is trying to look in default directory for settings.php

using debug:

vagrant: /var/www/public/d8/sites/carnnia.local$ ../../vendor/bin/drush status --debug
Using the Drush script found at /var/www/public/d8/vendor/bin/drush.launcher using pcntl_exec
PHP Fatal error:  Uncaught Error: Class 'Drush\Log\Logger' not found in /var/www/public/d8/vendor/drush/drush/includes/drush.inc:1278
Stack trace:
#0 /var/www/public/d8/vendor/drush/drush/includes/preflight.inc(147): _drush_create_default_logger()
#1 /var/www/public/d8/vendor/drush/drush/includes/preflight.inc(27): drush_preflight_prepare()
#2 /var/www/public/d8/vendor/drush/drush/drush.php(12): drush_main()
#3 {main}
  thrown in /var/www/public/d8/vendor/drush/drush/includes/drush.inc on line 1278
