### ISSUE TITLE
Unable to Install Drush on Centos 7 

### ISSUE THREAD

**Issue by sernapallyanurag** [drush-ops/drush#2075]
============================================================================
====
    Error executing action `run` on resource 'execute[download_drupal]'
    ============================================================================
====

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of  /usr/local/bin/drush dl drupal --drupal-project-rename
=drupal -y ----
    STDOUT:
    STDERR: Your command line PHP installation is too old. Drush requires at
 [error]
    least PHP 5.5.0. To suppress this check, set the environment variable
    DRUSH_NO_MIN_PHP=1
    ---- End output of  /usr/local/bin/drush dl drupal --drupal-project-rename=d
rupal -y ----
    Ran  /usr/local/bin/drush dl drupal --drupal-project-rename=drupal -y return
ed 1

How do I install Latest PHP version? Where do I make changes?
Since latest available package for Centos is 5.4.16 https://www.rpmfind.net/linux/rpm2html/search.php?query=php-cli.

**Comment by weitzman** [comment]
http://lmgtfy.com/?q=upgrade%20to%20php5.6+on+centos#
