### ISSUE TITLE
Installed with Composer. command not found: drush

### ISSUE THREAD

**Issue by Ollie-w** [drush-ops/drush#2077]
I had received a successful download message after running `composer global require drush/drush`
```
Installing drush/drush (8.0.5)
    Downloading: 100%
```
Then I copy and pasted `export PATH="$HOME/.composer/vendor/bin:$PATH"` into my ~/.bash_profile using Vim.
Yet now I get the message `command not found: drush` when I try to use it.

**Comment by weitzman** [comment]
[Our install docs now recommend using the phar install method](http://docs.drush.org/en/master/install/). Try that. Otherwise, figure out if ~.bash_profile is even getting read. If not, try ~/.bashrc
