### ISSUE TITLE
Fatal Error: Class 'League\Container\Container' not found

### ISSUE THREAD

**Issue by jasonkhanlar** [drush-ops/drush#2085]
```
$ pwd
/site/public_html
$ drush

Fatal error: Class 'League\Container\Container' not found in /site/bin/drush-9.0.0-alpha1/includes/preflight.inc on line 197
```

```
$ pwd
/site/bin/drush-9.0.0-alpha1
$ grep -r "class League" *
```

What provides the League class?

I see few search results at https://duckduckgo.com/?q=%22Class+%27League\Container\Container%27+not+found%22&t=ffsb

**Comment by jasonkhanlar** [comment]
Found https://github.com/derhasi/composer-preserve-paths

and `composer update` resolves this, though I had to run this locally on my machine and upload the files to server due to memory restrictions

**Comment by joelpittet** [comment]
How did that project fix it?
