### ISSUE TITLE
Installing Drush

### ISSUE THREAD

**Issue by cmcky** [drush-ops/drush#2086]
When I do the following:
1. `wget http://files.drush.org/drush.phar`
2. `php drush.phar core-status`
3. `chmod +x drush.phar`
4. `sudo mv drush.phar /usr/local/bin/drush`
5. `drush init`

I get the following error:
`-bash: /usr/bin/drush: No such file or directory`

The drush file is present in the directory. What could be causing this?

**Comment by dustinleblanc** [comment]
@cmcky do you have /usr/local/bin in your path?

**Comment by weitzman** [comment]
Yes, thats the likely problem.

**Comment by cmcky** [comment]
@dustinleblanc, @weitzman - it's definitely a part of the path:  `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games` 

This is easily reproducible, this is just a fresh Ubuntu box on Digital Ocean.
