### ISSUE TITLE
Clearly document differences between each branch

### ISSUE THREAD

**Issue by damienmckenna** [drush-ops/drush#2087]
Now that Drush is onto v9, is there any chance of clearly documenting somewhere what the main differences are between each branch? Thanks.

**Comment by weitzman** [comment]
Do you have a model in mind? We have been lazily using the Compare links that Github provides for release notes. I guess we could maintain a Changelog. Would that meet your ideas?

**Comment by damienmckenna** [comment]
I think bringing back the Drush vs Drupal core table that used to be available would be a huge help. Then add a column to list the key changes in each branch, e.g. Drush 6 added support for alternative output formats and..., Drush 7 added support for Drupal 8 and.., Drush 8 added.., Drush 9 is a rewrite using COBOL.., etc.

**Comment by weitzman** [comment]
That table is at http://docs.drush.org/en/master/install/. I'm open to moving the table to a more obvious spot. I dont think the table has enough width for adding comments like these.

**Comment by damienmckenna** [comment]
Check out #2089.
