### ISSUE TITLE
Add more debugs, when there is an error: Drush command terminated abnormally due to an unrecoverable error.

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#209]
I've a script and its keep terminating with the following general error:

```
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                                                                                   [error]
Error: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in includes/unicode.inc, line 349 [1.62 sec, 19.26 MB]
```

I've tried to use verbose and debug options, but it didn't help.
Is there any way of adding some error handler which will catch that kind of things (e.g. on shutdown)?

Code which fails:

```
drupal_execute('uc_cart_checkout_review_form', $uc_cart_checkout_review_form_state);
```

I'm calling it via:

```
drush -vd -u "some_user" scr my_script.php
```

I believe it's because of redirect (Location header).
But still I think I should be able to execute some code after affected line, but I can't.

**Comment by weynhamz** [comment]
As it is in the registered shutdown handler, there is no way to get more info about the context info by php   itself, but xdebug could help to identify where the exit happens.

1. Enable xdebug in cli mode

```shell
phpenmod -s cli xdebug
```

2.  edit drush/includes/preflight.inc, in `drush_shutdown()` function, add below lines

```php
var_dump(xdebug_get_function_stack());
```

**Comment by weitzman** [comment]
thx
