### ISSUE TITLE
packages.drush.org - This site can’t be reached  packages.drush.org took too long to respond. ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by frederickjh** [drush-ops/drush#2091]
Hi!
There are links on the drush.org website and the drush github project page that have the text "**Drush packages available via Composer**" these link to [packages.drush.org](http://packages.drush.org). Currently visiting these links you see:
![screenshot from 2016-03-22 17 07 30](https://cloud.githubusercontent.com/assets/864159/13958621/0e00c3d2-f051-11e5-80b7-36743c4383b4.png)

I hope that this is the correct place to report this. If not please let me know where I should report it.

**Comment by weitzman** [comment]
ping @xendk

**Comment by xendk** [comment]
It's pretty down, can't log into it. I've sendt a request for it to be rebooted.

I have a plan of moving it to another hosting, just haven't had the time yet.

**Comment by xendk** [comment]
It's up again.

**Comment by weitzman** [comment]
Thanks Thomas.

**Comment by frederickjh** [comment]
Thanks!
