### ISSUE TITLE
Update drushcommands.com web site

### ISSUE THREAD

**Issue by hcpss-banderson** [drush-ops/drush#2092]
I am trying to use site-install with the --writable and --keep-config option, but I am getting the following error:

```
Unknown options: --writable, --keep-config.  See `drush help site-install` for available options. To suppress this error, add the option --strict=0.
```

And it's true `drush help site-install` does not show options for --writable or --keep-config. But those are [documented on drushcommands](http://drushcommands.com/drush-8x/core/site-install/).

I feel like I must be missing something obvious. I have tried it with 8.0.5, 8.1-dev and 9.0-dev.

Here's the command for reference:
```
drush si config_installer -y \
        --account-mail=me@gmail.com \
        --account-name=admin \
        --account-pass=admin \
        --db-url=mysql://root:root@drupal_db/drupal \
        --site-mail=me@gmail.com \
        --writable \
        --keep-config \
        config_installer_sync_configure_form.sync_directory=/src/config/sync
```

**Comment by weitzman** [comment]
Peter, =the drushcommands.com webmaster, will get that site updated soon.

**Comment by weitzman** [comment]
You should remove those options as file perms are not touched by Drush (writable) and Drupal no longer deletes your config.

**Comment by peter-brady** [comment]
Apologies for the delay here.

Drush 6 removed from Drush commands, re. @weitzman request. Also added Drush 9 at http://drushcommands.com/drush-9x/ (9.0.0-alpha1).

See http://drushcommands.com/drush-9x/core/site-install/. No longer displays the --writable and --keep-config options.

Thanks.

**Comment by hcpss-banderson** [comment]
@peter-brady, Can you remove the --writable and --keep-config options from the Drush 8 docs as well?

**Comment by peter-brady** [comment]
@hcpss-banderson Sure. I'll check out the 8.1.0 tag and rebuild. Will be later today or at the very latest tomorrow morning.

**Comment by peter-brady** [comment]
@hcpss-banderson I checked out the 8.1.0 tag, built the site anew and deployed. Config options now gone from Drush 8 http://drushcommands.com/drush-8x/core/site-install/

Thanks.
