### ISSUE TITLE
Config-Export: Skip Modules by Package

### ISSUE THREAD

**Issue by charginghawk** [drush-ops/drush#2099]
drush config-export currently has a skip-modules option that lets you identify individual modules to skip when exporting config.

This is great, but most of the modules I'd like to skip conveniently put themselves in the Development package. A skip-modules-by-package option would let me skip all Development modules at once.

If I'm configuring this in my drushrc.php, it would let me skip all Development modules past, present, and future, instead of updating the list every time I add a new module.

Thanks!

**Comment by weitzman** [comment]
I'd rather keep config commands lean. Please script this using drupal extension api. Then feel free to add as a contrib or just post the code here. Note that drushrc.php is a PHP file and thus you can do whatever you wish there.
