### ISSUE TITLE
sql-sanitize does not work on Drupal 8

### ISSUE THREAD

**Issue by steveoliver** [drush-ops/drush#2105]
Using Drush version 8.0.5 on Drupal 8.0.5, $ drush sql-sanitize does not work.

Steps to reproduce:

1. Install fresh D8.
2. Create a user (#2)
3. Run $ drush sql-sanitize
4. Notice nothing happens.

**Comment by weitzman** [comment]
I think this bug is fixed since I could reproduce the problem on 8.0.5 but not 8.x

I added error handling to the sanitize query in both the 8.x and 9.x branches. See a27d131

**Comment by steveoliver** [comment]
Thanks, Moshe.  Sorry, should have checked dev!
