### ISSUE TITLE
Help command for annotation classes

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#2106]
We need to implement our own sublcass of Application so that we can provide our own [Application::getDefaultCommands](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Console/Application.php#L919). From there, we can provide our own implementation of the Help command.

The existing Symfony help command is not very extensible.  It uses a [Descriptor](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Console/Descriptor/Descriptor.php) that formats the help sections in code. Each different output format is implemented as a subclass of Descriptor. To change the way help works using this model, we would need to make our own subclass of Descriptor in order to change the help structure, and then copy all of the existing formatters, so that they extended our subclass instead of Symfony's descriptor.

A better way to do it would be to follow the existing Drush model, and have the help command build a data structure containing the structured help contents. This could then be formatted by a formatter.

**Comment by weitzman** [comment]
Closing in favor of #2670
