### ISSUE TITLE
drush.complete.sh - drush prompt error if drush is not present

### ISSUE THREAD

**Issue by frederickjh** [drush-ops/drush#2107]
Currently **drush.complete.sh** first tests to see if drush is installed. If it is not it exits. However if the **__drush_ps1** has been included in the system prompt  on a system where drush has not been installed or been uninstalled, an error is produced.

My use case is this I copy my standard configuration files to new servers when I set them up. I like to have my prompt and such setup the same everywhere. Sometimes I work on server without Drush or Drupal. In these cases I would like the prompt to work without Drush and without producing an error.

Proposed fix is to incorporate the test for drush into **__drush_ps1** so that it returns an empty response if Drush is not present and move it before the test that exits **drush.complete.sh** so that it is still found and does not produce an error.

Before fixing this also read my comments about using **which** to test for Drush's presence (https://github.com/drush-ops/drush/issues/521#issuecomment-203454865).

**Comment by weitzman** [comment]
Seems like a good improvement to me. I wont be working on it but feel free to submit a PR.

**Comment by frederickjh** [comment]
I am going to close this. In newer versions of Drush the prompt as has been moved to examples/example.prompt.sh This combined with core-init may have made this a non-issue.
