### ISSUE TITLE
site-install results in "Failed to create database:" if empty database exists

### ISSUE THREAD

**Issue by geerlingguy** [drush-ops/drush#2110]
Ever since this commit (https://github.com/drush-ops/drush/commit/92fa9a439fc5ec26cff3fb68a9e7cfd0d4076d2d), I'm not able to install new sites anymore in Drupal VM (any PHP version, Apache, or Nginx) or on localhost (Mac OS X with Apache/MySQL/PHP 5.6).

It seems some of the logic changes cause any site-install to fail with the error message:

```
Failed to create database:                                            [error]
```

This is causing Drupal VM builds to fail on the `drush site-install` task as of yesterday; for example: https://travis-ci.org/geerlingguy/drupal-vm/builds/119706131

If I simply check out `drush` at a revision 13703da4c86864453e8dc2f1c7b29cd147d15dc4, everything works as normal.

**Comment by geerlingguy** [comment]
Also, when running `site-install` manually with `-vvvv` on master, I get:

```
$ drush site-install standard -y --site-name="Drupal VM" --account-name=admin --account-pass=admin --db-url=mysql://drupal:drupal@localhost/drupal -vvvv
Executing: mysql --defaults-extra-file=/tmp/drush_6yHoRp --database=drupal --host=localhost --silent  < /tmp/drush_PcvX0a > /dev/null
You are about to DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y
Sites directory /var/www/drupalvm/drupal/sites/default already exists - proceeding.                             [notice]
Executing: mysql --defaults-extra-file=/tmp/drush_cJhgHT --database=drupal --host=localhost --silent  < /tmp/drush_R1sjME > /dev/null
Executing: mysql --defaults-extra-file=/tmp/drush_Wkjdzn --database=drupal --host=localhost --silent  < /tmp/drush_qQC8C8
Failed to create database:                                                             [error]
Command dispatch complete                                                        [notice]
```

MySQL connection is fine, UI install is fine, and as stated above, reverting to the previous commit makes site-install work without a failure.

**Comment by geerlingguy** [comment]
Another hint: It looks like the issue is the `return` on `drop_or_create()`, and only on the first run: If I install the site, then run `site-install` again, the `DROP TABLE` command returns a bool `TRUE` because it successfully dropped some existing tables.

But on first install, no tables exist in the database that was pre-created, so the `DROP TABLE` command that Drush pipes into `mysql` triggers the failure; imo, we don't need to trigger a fail on a failed `DROP TABLE`, because those tables might or might not exist if the database already exists.

**Comment by geerlingguy** [comment]
If I completely drop the database and run the command again, too, it works fine, since it doesn't see an existing empty database.

Steps to reproduce:

  1. MySQL CLI: `CREATE DATABASE drupal;`
  2. `drush site-install standard -y --db-url=mysql://drupal:drupal@localhost/drupal` _fails_
  3. MySQL CLI: `DROP DATABASE drupal;`
  4. `drush site-install standard -y --db-url=mysql://drupal:drupal@localhost/drupal` _works_

So if you have a pre-existing empty database, `site-install` currently fails due to this line: https://github.com/drush-ops/drush/commit/92fa9a439fc5ec26cff3fb68a9e7cfd0d4076d2d#diff-5549a39041cc73cc4ddf3e35a4533357R269

**Comment by geerlingguy** [comment]
See PR #2111

**Comment by mortenson** [comment]
I still see this on the master branch, but https://github.com/drush-ops/drush/commit/92fa9a439fc5ec26cff3fb68a9e7cfd0d4076d2d~1 (commit before introduction of the bug) works just fine.

@geerlingguy can you confirm that this is (still) fixed for you if you use master's head commit?

**Comment by geerlingguy** [comment]
@mortenson - In unrelated testing, I've built/re-built about 10 instances of Drupal VM today, with no failures, always using Drush master (that was as of 10 a.m. EST or so).

**Comment by mortenson** [comment]
Ignore me! I found the issue and it was unrelated. Thanks for the quick reply Jeff.

**Comment by alexdesignworks** [comment]
@weitzman 
Somehow this commit from 31 of March did not get into v8.1.2 released on 5 of May. This is strange. `master` branch does indeed contain this commit. Any chance to make a minor release to include this change?

**Comment by weitzman** [comment]
Think I backported this properly in 32e505b542feb130d2b0262aaa5ca9de7a2ace32. Please test with 8.x branch if possible.

**Comment by hkirsman** [comment]
So this fix is in Drush 8?
