### ISSUE TITLE
Destination directory is wrong if module doesn't contain .module file.

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#2112]
In Drupal 8 .module files [are no longer required](https://www.drupal.org/node/2217931). However sometimes _pm_drush_pm_download_destination_alter()_  recognizes such modules as pure drush commands. That causes some modules are downloaded to a wrong destination. See [#2697473](https://www.drupal.org/node/2697473) as an instance.

**Comment by weitzman** [comment]
This was recently fixed and will be in the next release of 9.x and 8.x.

**Comment by Chi-teck** [comment]
I have encountered the problem using the latest code from 8.x branch.
