### ISSUE TITLE
Determine mapping from Drush procedural hooks to new HookManager

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#2116]
The [existing Drush command dispatcher](https://github.com/drush-ops/drush/blob/b69f3b769fb2e84464e2d6e39c5936a5b8d09bcd/includes/command.inc#L325) provides the following hooks:

- hook_init
- hook_pre_validate
- hook_validate
- pre_hook
- hook
- post_hook

Also, all of these have a `_rollback` hook that is called iff the command fails after the corresponding hook has executed.

[AnnotationCommand\HookManager](https://github.com/consolidation-org/annotation-command/blob/master/src/HookManager.php) provides the following hooks:

- validate (validates arguments)
- alter (changes result returned from primary command hook)
- status (look up status result code from result object)
- extract (get information to display to user from result object)

Each of these also have "pre" and "post" varieties, to give more flexibility vis-a-vis hook ordering (and for consistency). Note that many validate and alter hooks may run, but the first status or extract hook that successfully returns a result will halt processing of further hooks of the same type.

The mapping from Drush hook to AnnotationCommand hook is as follows:

- hook_init => (none - needed)
- hook_pre_validate => pre-validate
- hook_validate => validate
- pre_hook => post-validate
- hook => (none - deprecated)
- post_hook => alter
- *_rollback => (none - tbd)

Maybe we need something better than `post-validate` to replace the old "pre_" hook.

It was fairly unusual for anyone to write a hook for some other command's primary callback function. This really should never be done, because it is indeterminate whether the hook will run before or after the primary callback function. It is therefore always better to use a pre or post hook to disambiguate what order was intended for the hook function.

Rollbacks are also fairly uncommon. We should investigate whether these can be done using Robo collections, and only provide a replacement for these if they are really needed.

**Comment by weitzman** [comment]
All that makes sense to me. Hoever the names alter/status/extract are not
immediately intuitive to me. Maybe they would be if I read the source or
descriptions.

I think we can leave rollback  as tbd for a long time.

**Comment by greg-1-anderson** [comment]
I edited the description above and added a brief description of the purpose of each of the new hooks. The hooks need better documentation in the AnnotationCommands project as well.

**Comment by greg-1-anderson** [comment]
I updated the [AnnotationCommand project description](https://github.com/consolidation-org/annotation-command) to contain a description of the available hooks.

**Comment by weitzman** [comment]
This was completed by #2366.
