### ISSUE TITLE
Check drupal core version in drushrc.php?

### ISSUE THREAD

**Issue by aaronbauman** [drush-ops/drush#2117]
Is there a preferred way to determine the version of the current command's contextual drupal core (if any) in drushrc.php? 

use case: supplying different flags for d7 and d8

**Comment by weitzman** [comment]
If your drushrc lives within the site, then you can call
drush_drupal_major_version(). If it is a global config file, that function
returns NULL since we havent bootstrapped far enough to know the version of
Drupal.
