### ISSUE TITLE
The "batch" table may not exist by the time _drush_backend_batch_process() is called in 8.x-1.x

### ISSUE THREAD

**Issue by mortenson** [drush-ops/drush#2122]
Following the closing of https://www.drupal.org/node/2664324, the batch table is no longer created when the "system" module is enabled. 

As a result if https://github.com/drush-ops/drush/blob/8.x/commands/core/drupal/batch.inc#L53 is invoked before the batch table is created, an error like this may be thrown:

```
exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd8df.batch' doesn't exist' in                                      [error]
/Users/samuel.mortenson/Sites/d8df/core/lib/Drupal/Core/Database/Statement.php:64
Stack trace:
#0 /Users/samuel.mortenson/Sites/d8df/core/lib/Drupal/Core/Database/Statement.php(64): PDOStatement->execute(Array)
#1 /Users/samuel.mortenson/Sites/d8df/core/lib/Drupal/Core/Database/Connection.php(615): Drupal\Core\Database\Statement->execute(Array, Array)
#2 /Users/samuel.mortenson/Sites/d8df/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(86): Drupal\Core\Database\Connection->query('INSERT INTO {ba...',
Array, Array)
#3 /Users/samuel.mortenson/Sites/d8df/core/lib/Drupal/Core/Database/Driver/mysql/Insert.php(37): Drupal\Core\Database\Driver\mysql\Connection->query('INSERT INTO
{ba...', Array, Array)
#4 /Users/samuel.mortenson/.composer/vendor/drush/drush/commands/core/drupal/batch.inc(58): Drupal\Core\Database\Driver\mysql\Insert->execute()
#5 /Users/samuel.mortenson/.composer/vendor/drush/drush/includes/batch.inc(75): _drush_backend_batch_process('batch-process', Array, Array)
...
```

We either need to check if that table exists before running the insert, or alternatively not use an insert at all and instead use the Core BatchStorage service.

**Comment by weitzman** [comment]
Interesting. I'm fine with either implementation approach. I just upped our test suite to use Drupal 8.1.x instead or 8.0.x (8e7a40e) so hopefully this error will start showing. And others?

Here is some code if anyone wants to get started on this:

```
$sql = drush_sql_get_class();
if (!in_array('batch', $sql->listTables()) {
  // Create table manually or use \Drupal\Core\Batch\BatchStorage::ensureTableExists()    
}
```

It would be a bigger job to actually support external storage for batches.

**Comment by mortenson** [comment]
Should have a PR ready today.

**Comment by mortenson** [comment]
Thanks for the quick merge!

**Comment by weitzman** [comment]
Needs backporting to D8. Doesn't apply cleanly but is not hard.

**Comment by weitzman** [comment]
My mistake. It was backported.
