### ISSUE TITLE
sql-sync not placing file in specified dump-dir

### ISSUE THREAD

**Issue by chavab1** [drush-ops/drush#2125]
I have a dev and staging alias setup and they are both working correctly. I included a reference to where I want the dump file placed during a `drush sql-sync` using:
```
  'path-aliases' => array(
    '%dump-dir' => '/home/.drush/db_dumps'
  ) 
```

The command is run successfully but it doesn't use my dump directory. Instead it uses _/home/user/drush-backups_. I tried changing the location of my dump-dir to a location inside of the drupal site folder, but it still doesn't work.

One of the solutions that I found was to include the `--source-dump` option (which points to the same location as I have in %dump-dir) when running `drush sql-sync`. It seems like if that's the case, then why even bother adding it in my alias file.

Another solution states to also include a reference to the actual dump file using `%dump` in the path-aliases array. I tried that and it still doesn't work.

Is there a solution to this or is it not suppose to work at all?? Because the example.aliases.drushrc.php file doesn't mention dump-dir at all.

Using: Ubuntu 14.0.4, Drush 8.0.5, Drupal 8 site

Thanx

**Comment by oxyc** [comment]
This seem to have been removed https://github.com/drush-ops/drush/commit/e89c7c44d849643c5b50f0d51153495b2a46e65d

**Comment by weitzman** [comment]
Correct. sql-sync changed architecture. It gzips and transfers the full dump every time. It uses a temp file in your specified temp dir for the transfer. Files are deleted right after rsync.

**Comment by chavab1** [comment]
Thanx guys. That's what I thought since there was no mention of it in the example aliases.drushrc.php file. I just thought I'd ask because all tutorials still have reference to it. I guess they're all old.

Once again, thanx.

**Comment by kenorb** [comment]
Related: [Drush sql-sync not placing file in specified dump-dir](http://drupal.stackexchange.com/q/197425/1908) at DA

**Comment by bradallenfisher** [comment]
using drush 6 files are no longer being cleaned up from /tmp directory. not sure if this is related or not, but I had a disc fill up after a week of nightly backups.
