### ISSUE TITLE
Export database compact line .sql  

### ISSUE THREAD

**Issue by henrytran9x** [drush-ops/drush#2129]
hi ! I used Drush Version 8.0 .
 the code `drush sql-dump > ~/my_file.sql`
Allow export database .So I want export database compact break space file .sql . How to did it ? 

Thanks

**Comment by weitzman** [comment]
In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.
