### ISSUE TITLE
Issue with runserver and Drupal 8 entity reference field autocomplete

### ISSUE THREAD

**Issue by waako** [drush-ops/drush#2130]
- Drupal 8.0.5
- Drush 8.0.5 and 9.0-dev (install via Composer)
- PHP 6.5.17
- PHP memory limit = 128M
- Mac OS 10.11.4

When using drush runserver and Drupal 8 entity reference, autocomplete fields don't display any results.
The spinner goes, but no results appear.
No errors in browser devtools console.
Tested with drush core-quick-drupal and have the same issue.
Problem occurs on two different macs.

Any ideas of why this is occuring, and how to resolve it?

**Comment by jmolivas** [comment]
@waako probably related to this d.o. issue Add a startup configuration for the built-in PHP server that supports clean URLs https://www.drupal.org/node/1543858

**Comment by waako** [comment]
Thanks for responding @jmolivas I'll have a look and see if that helps

**Comment by pwolanin** [comment]
I just ran into this also - the path had been substituted for the query param somehow

**Comment by pwolanin** [comment]
Looks like this is fixed is master but still may be broken in 8.x

**Comment by pwolanin** [comment]
Even fixed in 8.x branch, just not in 8.1.9 tag
fax was in #2599

**Comment by webflo** [comment]
The fix is in 8.1.10. I think we can close this issue.
