### ISSUE TITLE
Drush 7 composer.lock compatibility with PHP 5.3

### ISSUE THREAD

**Issue by JorisVanEijden** [drush-ops/drush#2132]
The install.md document states Drush 7 requires PHP 5.3.0+
The composer.json also lists PHP >=5.3.0
But the composer.lock file requires symfony/var-dumper 2.8.0 and symfony/yaml 2.8.0 which require PHP >=5.3.9

The symphony/* 2.* requirements in composer.json also require PHP >=5.3.3 so anything less than 5.3.3 isn't going to work anyway.

**Please keep composer.lock compatible with the listed minimum requirements.**
Maybe add to the composer.json:
`    "config": {
        "platform": {
            "php": "5.3.3"
        }
    }`
Or remove the composer.lock from the repository.

See also Symphony's own discussion about this issue: https://github.com/symfony/symfony-standard/issues/858

**Comment by weitzman** [comment]
just read that issue. There isnt a great solution. I'm inclined to remove composer.lock. Any comments?

**Comment by JorisVanEijden** [comment]
Removing it looks like the best solution.

**Comment by greg-1-anderson** [comment]
Drush 7.x does not have a .phar distribution, but this issue, when it recurs for other components in the future, has implications for .phar files.

In cases where `composer require` does **not** bring in the most recent version of all of an apps dependencies when used with the lowest supported version of php, then a different .phar file for each version of php supported. We could build multiple phars (one per php version) via the Travis build, but it would be inconvenient to determine if they were necessary or not.

The composer.lock problem is similar, but Symfony has no facility for supporting multiple lock files. Pinning the php version is not good, for the reasons stated in the Symfony issue.

I think that the only robust solution for the master branch of the project is to ensure that our minimum php >= the minimum php of the latest release of all of our dependencies. This may sometimes be in conflict with our project goals vis-a-vis php support. It would be nice if all of our dependencies would recognize this, and ensure that bumping the php version can only be done with a change in major version number. Semver currently does not require a change in dependencies to be considered breaking unless it is exposed through the library's public API.  For Composer, it is easy for a dependency change to break backwards compatibility, even when the public API does not change -- but it is difficult to determine when this has happened.

**Comment by weitzman** [comment]
Ugh - good point .... We will probably abandon global Drush by the next time this becomes an issue.
