### ISSUE TITLE
Allow custom storage filters to be created/applied during config import/export

### ISSUE THREAD

**Issue by ericduran** [drush-ops/drush#2133]
This issue is coming from https://github.com/drush-ops/drush/pull/1522#issuecomment-206711685

@ericduran: 

> @greg-1-anderson @weitzman I came here looking for drush_command_invoke_all('drush_storage_filters');
> 
> I'm working on a solution to allow a multi-site set up to share a majority of configs (Entity/Bundles/Fields/etc..) but keep certain specific settings to be unique per site such as system.site.yml in its own dir.
> 
> Right now I'll need to write new drush commands to selectively import/export certain configurations into certain directories. That being said with the addition of drush_command_invoke_all('drush_storage_filters'); I can easily implement my own storage filters to figure out what goes where.
> 
> Thoughts? Concern? This is an oversimplification of the solution but yeah.
> 
> Should I open a PR? Move the discussion to a new issue?

I'm just moving this into an issue for now, I'll probably probably give this a dry run sometime soon, just starting the conversation.

**Comment by larowlan** [comment]
Thoughts on adding a ```--ignore-list=blacklist.yml``` for a simple generic approach?

Basically you'd add your blacklist (patterns) into .yml file and the import/export would ignore those.

Would that solve the 90% use case?

This could be done with a similar approach to partial.

Eg. for the import:

- export live config into a tmp dir
- copy config to be imported into second tmp dir
- copy blacklist matches from tmp dir into second tmp dir (effectively removing the variations)

Use those to dirs for the StorageComparer

**Comment by bircher** [comment]
An example for custom storage filters in action: https://www.drupal.org/project/config_split

A similar approach could also be useful for #1820 it needs PR #2313 though.

**Comment by weitzman** [comment]
We are discussing bringing back the storage filter hook in #2314
