### ISSUE TITLE
Drush Drupal multisite, single sign on and more functional Drupal environment

### ISSUE THREAD

**Issue by ItangSanjana** [drush-ops/drush#2134]
When on a non _default_ site of my Drupal 7 _single sign on multisite_, Drush 8 command `drush ups` yield:
```
Command pm-updatestatus needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command. [error]
The drush command 'ups' could not be executed.
```
So I need to temporary replace my database settings in `settings.php` from:
```
'prefix' => array(
  'default'   => 'db_01.',
  'users'     => 'db_00.',
  'sessions'  => 'db_00.',
  'role'      => 'db_00.',
  'authmap'   => 'db_00.',
),
```
to:
```
'prefix' => '',
```
Is it normal or am I missing something? Please let me know. TIA

**Comment by weitzman** [comment]
This table sharing configuration is no longer a best practice, and not tested/supported in Drush. Sorry.

**Comment by ItangSanjana** [comment]
Thanks to let me know.
