### ISSUE TITLE
drush updb fails with Call to undefined function drupal_get_installed_schema_version() 

### ISSUE THREAD

**Issue by aangelinsf** [drush-ops/drush#2138]
I'm getting the following error:

```
drush updb
PHP Fatal error:  Call to undefined function drupal_get_installed_schema_version() in /Users/andreangelantoni/Sites/vaccine-p/core/includes/install.inc on line 80
PHP Stack trace:
PHP   1. {main}() /Applications/DevDesktop/drush/vendor/drush/drush/drush.php:0
PHP   2. drush_main() /Applications/DevDesktop/drush/vendor/drush/drush/drush.php:12
PHP   3. Drush\Boot\BaseBoot->bootstrap_and_dispatch() /Applications/DevDesktop/drush/vendor/drush/drush/includes/preflight.inc:66
PHP   4. drush_dispatch() /Applications/DevDesktop/drush/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php:67
PHP   5. call_user_func_array:{/Applications/DevDesktop/drush/vendor/drush/drush/includes/command.inc:185}() /Applications/DevDesktop/drush/vendor/drush/drush/includes/command.inc:185
PHP   6. drush_command() /Applications/DevDesktop/drush/vendor/drush/drush/includes/command.inc:185
PHP   7. _drush_invoke_hooks() /Applications/DevDesktop/drush/vendor/drush/drush/includes/command.inc:217
PHP   8. call_user_func_array:{/Applications/DevDesktop/drush/vendor/drush/drush/includes/command.inc:366}() /Applications/DevDesktop/drush/vendor/drush/drush/includes/command.inc:366
PHP   9. drush_core_updatedb() /Applications/DevDesktop/drush/vendor/drush/drush/includes/command.inc:366
PHP  10. update_main() /Applications/DevDesktop/drush/vendor/drush/drush/commands/core/core.drush.inc:462
PHP  11. drupal_load_updates() /Applications/DevDesktop/drush/vendor/drush/drush/commands/core/drupal/update.inc:111

Fatal error: Call to undefined function drupal_get_installed_schema_version() in /Users/andreangelantoni/Sites/vaccine-p/core/includes/install.inc on line 80

```

I've performed an /update.php and it reports nothing there. Cleared the caches. Running Drush 8.0.5 on a D8.0.6 installation.

Any ideas why this could be occurring?

**Comment by weitzman** [comment]
Sorry, no idea. Requires googling and debugging ...

**Comment by dsdobrzynski** [comment]
I also am experiencing this with Drush 8.1.0 and Drupal 8.1.0. Unfortunately, I don't have time to debug right now.

**Comment by dsdobrzynski** [comment]
I encountered this with php version 7.0.6. but not version 5.6.21.

@aangelinsf What version of php are you using?

**Comment by aangelinsf** [comment]
That happened with 5.6

**Comment by dsdobrzynski** [comment]
I'm using Docker, so I tried again with 5.6 after removing all containers and images. I am experiencing this with 5.6 now, too.

This seems like a pretty big issue, so I'll see I can't get some time to investigate this (though it might take some time since I haven't worked on Drush before, other than looking at some of the commands' code).

**Comment by vincenzodibiaggio** [comment]
I've experienced the same error on launching drush command outside 'web' drupal 8 root dir. With the option 'root' I've no problem.

**Comment by dsdobrzynski** [comment]
With PHP versions 7 and 5.6 I also get the exception, even when specifying the 'root' option.

**Comment by weitzman** [comment]
I just saw this happen but the real problem is that `mysql` was not on my PATH. I think the error message is a bit misleading here. Run `drush status` and make sure you see `Drupal bootstrap:  Successful` before running updb.

**Comment by jlfranklin** [comment]
Why is the `mysql` command a dependency?  If the site can access the database and run the updates though the mysql PHP driver, then shouldn't drush be able to do the same?

**Comment by MaffooBristol** [comment]
I got this, then realised I was being an idiot and mysql wasn't running! Haha.

**Comment by ivanjaros** [comment]
Same issue but mysql is in my path :( drush 8.1.6

**Comment by davebeach** [comment]
same issue 8.2.2.

Similar to older issue https://www.drupal.org/node/1618346
and
https://www.drupal.org/node/1180112

drush status - bootstrap and path fine.

PHP Fatal error:  Call to undefined function drupal_get_installed_schema_version() in /opt/bitnami/apps/drupal/htdocs/core/includes/install.inc on line 80
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                                                                                         [error]
Error: Call to undefined function drupal_get_installed_schema_version() in /opt/bitnami/apps/drupal/htdocs/core/includes/install.inc, line 80
bitnami@bitnami-drupal-dm-3d36:~/apps/drupal/htdocs/modules/contrib$

**Comment by ivanjaros** [comment]
I have "fixed" this by installing drush via cgr - https://github.com/consolidation/cgr

**Comment by rodrigoaguilera** [comment]
It happened to me today and it was because the db credentials were missing. Can drush improve the message whe you do updatedb and the connection to the db is broken for some reason?

**Comment by weitzman** [comment]
Yes - thats #1371

**Comment by rodrigoaguilera** [comment]
That is great. Shouldn't we close this one in favor of the other?

**Comment by axel-rutz** [comment]
I had this as a consequence of #2183

**Comment by joachim-n** [comment]
This also happens if your mySQL server happens to have crashed.

**Comment by socialnicheguru** [comment]
I get this if
1) I have drush installed globably on my linux machine
2) drupal/drush is added to the composer.json file and added to the system.

**Comment by void--** [comment]
For posterity: I got this error with stale drush aliases on pantheon.

**Comment by brooke-heaton** [comment]
Same here - needed to run `terminus aliases` to freshen the drush aliases. Weird error tho. :/

**Comment by jimafisk** [comment]
I hit this in a pantheon/lando project trying to run drush from the project root (was trying to use drush version `8.3.5`), simply moving into the web root `cd web` and running the command again worked (used the project's drush version `11.5.1`)
