### ISSUE TITLE
Add support for core migration (currently in migrate_upgrade contrib module)

### ISSUE THREAD

**Issue by xjm** [drush-ops/drush#2140]
Drupal 8.1.0 includes a UI for Drupal 6/7 to Drupal 8 migrations in addition to the Drupal migration sources and destinations that were already provided in 8.0.0. However, the equivalent Drush commands are still in the contrib module that previously included the UI:

https://www.drupal.org/project/migrate_upgrade

It would make sense for these commands to be in Drush itself since they support key core functionality.

**Comment by xjm** [comment]
I posted https://www.drupal.org/node/2709537 to get feedback from that module's maintainers.

**Comment by mikeryan776** [comment]
Note the related issue https://www.drupal.org/node/2706693 - the command currently implements a --configure-only option dependent on contrib functionality (configuration entities provided by migrate_plus).

**Comment by weitzman** [comment]
I'm happy with this in Drush core as long as it comes with tests and comes with a person willing to maintain the commands.

**Comment by heddn** [comment]
I think enough is in flux with configuration for migrations, that waiting a couple weeks... at least until after drupalcon seems like it would make sense.

**Comment by quietone1** [comment]
I've ported the commands to drush, 9.0-dev-dev. Still needs work, migrate-upgrade works but not migrate-rollback.

What type of tests are needed?

**Comment by weitzman** [comment]
See the /tests directory in Drush. We generally use do system level tests so you would have an installed drupal at start of test. You will enable the needed modules, install test data siilar to how the drupal core tests do it, and then execute your drush commands to migrate the data.

**Comment by quietone1** [comment]
Time to dip my toes into this again. 
Starting from scratch (had a data destroying disk crash awhile back) and want to start with making sure I can run drush tests successfully but haven't got them all to pass yet. 

In an LXC container I followed the Usage instructions at tests/README.md. I didn't change any of the xml.dist files. Then ran `compose test` which failed, as below.

```
php -d sendmail_path='true' vendor/bin/phpunit --colors=always --configuration tests
PHP Fatal error:  Cannot declare class Unish\RsyncTest, because the name is already in use in /opt/sites/drush/tests/functional/RsyncTest.php on line 102
PHP Stack trace:
PHP   1. {main}() /opt/sites/drush/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() /opt/sites/drush/vendor/phpunit/phpunit/phpunit:53
PHP   3. PHPUnit\TextUI\Command->run() /opt/sites/drush/vendor/phpunit/phpunit/src/TextUI/Command.php:148
PHP   4. PHPUnit\TextUI\Command->handleArguments() /opt/sites/drush/vendor/phpunit/phpunit/src/TextUI/Command.php:159
PHP   5. PHPUnit\Util\Configuration->getTestSuiteConfiguration() /opt/sites/drush/vendor/phpunit/phpunit/src/TextUI/Command.php:837
PHP   6. PHPUnit\Util\Configuration->getTestSuite() /opt/sites/drush/vendor/phpunit/phpunit/src/Util/Configuration.php:918
PHP   7. PHPUnit\Framework\TestSuite->addTestFiles() /opt/sites/drush/vendor/phpunit/phpunit/src/Util/Configuration.php:1014
PHP   8. PHPUnit\Framework\TestSuite->addTestFile() /opt/sites/drush/vendor/phpunit/phpunit/src/Framework/TestSuite.php:403
PHP   9. PHPUnit\Util\Fileloader::checkAndLoad() /opt/sites/drush/vendor/phpunit/phpunit/src/Framework/TestSuite.php:325
PHP  10. PHPUnit\Util\Fileloader::load() /opt/sites/drush/vendor/phpunit/phpunit/src/Util/Fileloader.php:48
Script php -d sendmail_path='true' vendor/bin/phpunit --colors=always --configuration tests handling the phpunit event returned with error code 255                                 
Script @phpunit was called via test
```
So I change the class name for one of the RsyncTests and tried again. This time
```
No syntax errors detected in tests/fixtures/sitealiases/legacy/pantheon.aliases.drushrc.ph
p
> php -d sendmail_path='true' vendor/bin/phpunit --colors=always --configuration tests
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

...............................................................  63 / 144 ( 43%)
...............FFFFFFFFFFFFFFFFFFFFFF.FFFFFFFF..FFFF....FF....F 126 / 144 ( 87%)
F.FFFFFFFFFFFFFFFF                                              144 / 144 (100%)

Time: 50.39 seconds, Memory: 16.00MB

There were 54 failures:

1) Unish\CacheCommandCase::testCacheGet
/opt/sites/drush/drush site:install testing install_configure_form.enable_update_status_em
ails=NULL --root=/opt/sites/drush/sut --uri=default --db-url=mysql://root:@127.0.0.1/unish
_default --sites-subdir=default --yes --quiet

Exit Code: 1(General error)

Working directory:

Output:
================


Error Output:
================

In SiteInstallCommands.php line 384:

  Failed to drop or create the database: ERROR 1045 (28000): Access denied fo
  r user 'root'@'localhost' (using password: NO)


site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--druplicon] [--xh-link XH-LINK] [--notify [NOTIFY]] [--] <command> [<profile>]...


Failed asserting that false is true.

/opt/sites/drush/tests/unish/UnishTestCase.php:704
/opt/sites/drush/tests/unish/UnishTestCase.php:673
/opt/sites/drush/tests/unish/UnishIntegrationTestCase.php:73
/opt/sites/drush/tests/integration/CacheCommandTest.php:15

```
I am guessing I haven't done some setup that is required?

**Comment by weitzman** [comment]
Given the specialized audience for migrate commands, I'm now preferring this continue to live outside of core Drush. Note that Drush Test Traits are now available for testing Drush commands in 3rd party modules. See https://github.com/drush-ops/drush/tree/master/tests#drush-test-traits. 

As for your DB problem, see that whole URL for test setup instructions. Feel free to ping in #drush if you get stuck.
