### ISSUE TITLE
Drush in Windows gives error: filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by Zythyr** [drush-ops/drush#2152]
I am unable to properly use Drush 7 and 8 on Windows. Whenever I run command such as "drush pm-update" I get error as below:

> The command could not be executed successfully (returned: The        [error]
> filename, directory name, or volume label syntax is incorrect.
> , code: 1)
> pm-updatestatus failed.

Below is my environment: 
Windows 10x64 
XAMPP with PHP 5.6.19
Cygwinx64
Drush 8.0.5

Below is my Drush status output:

> dev@DEV-PC /cygdrive/c/xampp/htdocs/www/my_drupal_6_site
> $ drush status
>  Drupal version         :  6.16
>  Site URI               :  http://www
>  Database driver        :  mysql
>  Database hostname      :  localhost
>  Database port          :
>  Database username      :  drupal
>  Database name          :  my_drupal_6_site
>  PHP configuration      :  C:\xampp\php\php.ini
>  PHP OS                 :  WINNT
>  Drush script           :  C:\Users\dev\AppData\Roaming\Composer\vendor\drush
>                            \drush\drush
>  Drush version          :  8.0.5
>  Drush temp directory   :  C:\cygwin64\tmp
>  Drush configuration    :
>  Drush alias files      :
>  Drupal root            :  C:\xampp\htdocs\www\my_drupal_6_site
>  Drupal Settings File   :  sites/default/settings.php
>  Site path              :  sites/default

Below is part of the debug output when I run the command: `drush -d pm-update`. 

> 
> Backend invoke:                                                        [command]
> "C:\\Users\\dev\\AppData\\Roaming\\Composer\\vendor\\drush\\drush\\drush"
>  --backend=2 --verbose --debug
> --root="C:\\xampp\\htdocs\\www\\my_drupal_6_site" --uri=http://www
> pm-updatestatus 2>&1 [7.21 sec, 16.15 MB]
> "C:\\Users\\dev\\AppData\\Roaming\\Composer\\vendor\\drush\\drush\\drush"   [n     otice]
>  --backend=2 --verbose --debug
> --root="C:\\xampp\\htdocs\\www\\my_drupal_6_site" --uri=http://www
> pm-updatestatus 2>&1 [7.21 sec, 16.16 MB]
> The command could not be executed successfully (returned: The        [error]
> filename, directory name, or volume label syntax is incorrect.
> , code: 1) [7.32 sec, 16.16 MB]
> pm-updatestatus failed. [7.32 sec, 16.15 MB]                         [error]
> Returned from hook drush_pm_updatecode [7.32 sec, 16.15 MB]              [debug]
> Changes made in drush_pm_updatecode have been rolled back. [7.32 sec,    [debug]

**Comment by vnada** [comment]
In the same situation as you, what I can help with is that you can run the command with --debug and then copy pasting the backend invoke, in your situation: 

"C:\Users\dev\AppData\Roaming\Composer\vendor\drush\drush\drush"
--backend=2 --verbose --debug
--root="C:\xampp\htdocs\www\my_drupal_6_site" --uri=http://www
pm-updatestatus

**Comment by ebspeter** [comment]
Install drush 7 instead, it works. [Here](http://drupal.stackexchange.com/questions/135599/how-to-uninstall-drush-via-composer) is a link on how to change the version.

**Comment by Zythyr** [comment]
@ebspeter I changed to Drush 7.3.0, but I am still getting the same issue. And update to Drush 8.1.2 also gives me the same issue.

**Comment by ebspeter** [comment]
Sorry to hear that @Zythyr, as soon as i down-graded to drush 7.3.0 it started working for me, before that both 8.0.5 and 8.1.2 gave me the same problem as you. 

My environment is quite different though: 
Win: 8.1
Wamp: 2.5
PHP: 5.5.12
MINGW64 (git bash)

Here's my drush status output: 

`$ drush status
 Drupal version                  :  7.43
 Site URI                        :  http://default
 Database driver                 :  mysql
 Database hostname               :  localhost
 Database port                   :
 Database username               :  root
 Database name                   :  devlocal
 Drupal bootstrap                :  Successful
 Drupal user                     :
 Default theme                   :  bartik
 Administration theme            :  seven
 PHP executable                  :  php
 PHP configuration               :  C:\wamp\bin\php\php5.5.12\php.ini
 PHP OS                          :  WINNT
 Drush script                    :  C:\Users\Peter\AppData\Roaming\Composer\vendor\drush\drush\drush.php
 Drush version                   :  7.3.0
 Drush temp directory            :  C:\Users\Peter\AppData\Local\Temp
 Drush configuration             :
 Drush alias files               :
 Install profile                 :  standard
 Drupal root                     :  C:\wamp\www\dev.local
 Site path                       :  sites/default
 File directory path             :  sites/default/files
 Temporary file directory path   :  c:/wamp/tmp
`

**Comment by parkerjgit** [comment]
Same problem here. 

Win7 64
Wamp 2.5
php 5.5.12
git bash

drush status:
````
 Drupal version         :  8.2.0-dev                                            
 Site URI               :  http://www                                           
 Database driver        :  mysql                                                
 Database hostname      :  127.0.0.1                                            
 Database port          :  3306                                                 
 Database username      :  admin                                                
 Database name          :  test                                                 
 Drupal bootstrap       :  Successful                                           
 Drupal user            :                                                       
 Default theme          :  bartik                                               
 Administration theme   :  seven                                                
 PHP configuration      :  C:\wamp\bin\php\php5.5.12\php.ini                    
 PHP OS                 :  WINNT                                                
 Drush script           :  C:\Users\Josh\AppData\Roaming\Composer\vendor\drush\ 
                           drush\drush                                          
 Drush version          :  8.1.2                                                
 Drush temp directory   :  C:/Users/Josh/AppData/Local/Temp                     
 Drush configuration    :                                                       
 Drush alias files      :                                                       
 Install profile        :  standard                                             
 Drupal root            :  C:\wamp\www\test                                     
 Drupal Settings File   :  sites/default/settings.php                           
 Site path              :  sites/default                                        
 File directory path    :  sites/default/files                                  
 Temporary file         :  c:/wamp/tmp                                          
 directory path                                                                 
 Sync config path       :  sites/default/files/config_aPEAHYXnQjzJuEpsK1AbwpoF6 
                           QSAkIWJCMqIRBp8gRMSDEnGO0Cmu9Fe5qU8paWAA-4vFVkV_A/sy 
                           nc  
````

**Comment by leeorah** [comment]
I tried vnada suggestion and pasted in the backend invoke:
"C:\\Users\\leora\\AppData\\Roaming\\Composer\\vendor\\drush\\drush\\drush" --verbose --debug --root="C:\\wamp\\www\\d8" --uri=http://default pm-download video_embed_field 2>&1 

For some reason it then worked.  Nasty solution for now.
Below is my drush status:
<pre>
Drupal version         :  8.1.1
 Site URI               :  http://default
 Database driver        :  mysql
 Database hostname      :  localhost
 Database port          :  3306
 Database username      :  root
 Database name          :  d8commru
 Drupal bootstrap       :  Successful
 Drupal user            :
 Default theme          :  omega
 Administration theme   :  seven
 PHP configuration      :  C:\wamp\bin\php\php5.5.12\php.ini
 PHP OS                 :  WINNT
 Drush script           :  C:\Users\leora\AppData\Roaming\Composer\vendor\drush
                           \drush\drush
 Drush version          :  8.1.2
 Drush temp directory   :  C:\Users\leora\AppData\Local\Temp
 Drush configuration    :
 Drush alias files      :
 Install profile        :  standard
 Drupal root            :  C:\wamp\www\d8
 Drupal Settings File   :  sites/default/settings.php
 Site path              :  sites/default
 File directory path    :  sites/default/files
 Temporary file         :  c:/wamp/tmp
 directory path
 Sync config path       :  sites/default/files/config_q0awFKTlb9qLCj7iKL69JvmrA
                           hLnOA7ZYMlCZV5zX7otkhrMWpY_PZFJcQwDxhK9vmoiT3QSoQ/sy
                           nc
</pre>

**Comment by ebspeter** [comment]
Sounds like your path to drush is not in the PATH.

**Comment by leeorah** [comment]
Hm, it looks like drush is in PATH, or else I wouldn't be able to do drush commands at all (version, rebuild cache and status work fine).  I tried typing the whole path to drush, but it still wouldn't let me download a module.  Then I again did the whole backend invoke, and it worked just fine (downloaded the module).  It is only commands that involve outside server that are problems.

**Comment by vnada** [comment]
I'm personally using the drush 9.0 dev version with windows 10 and still encounter this issue when I run the command updatedb --entity-updates, so running the backend invoke is currently the only way.

The error I get is the exact same one with the filename, directory name, or volume label syntax being incorrect.

Here's my drush status: 
<pre> Drupal version                  :  8.1.1
 Site URI                        :  http://default
 Database driver                 :  mysql
 Database hostname               :  localhost
 Database port                   :  3306
 Database username               :  admin
 Database name                   :  admin_d8
 Drupal bootstrap                :  Successful
 Drupal user                     :
 Default theme                   :  admin
 Administration theme            :  admin
 PHP configuration               :  C:\Programming\XAMPP\php\php.ini
 PHP OS                          :  WINNT
 Drush script                    :  C:\Users\vnada\AppData\Roaming\Composer\vendor\drush\drush\drush
 Drush version                   :  9.0-dev
 Drush temp directory            :  C:\Users\vnada\AppData\Local\Temp
 Drush configuration             :
 Drush alias files               :
 Install profile                 :  admin
 Drupal root                     :  C:\Programming\D8
 Drupal Settings File            :  sites/default/settings.php
 Site path                       :  sites/default
 File directory path             :  sites/default/files
 Temporary file directory path   :  C:\Programming\XAMPP\tmp
 Sync config path                :  sites/default/files/config_7mc2jUyQ25Y-bYQLUT-dCK0d3s3PTRs_LE_X_cPJPjmbipC8RlIyz9Q9WL37SCeF5AeFikI-oA/sync
</pre>

**Comment by DocDJ** [comment]
I too am having this problem trying to update 8.1.1 to 8.1.2. I have tried both `drush pm-update` and ` drush pm-update projects drupal-8.1.2`.
 Here is my status data:
Drupal version         :  8.1.2
 Site URI               :  <default>
 Database driver        :  mysql
 Database hostname      :  localhost
 Database port          :  3306
 Database username      :  <hidden>
 Database name          :  <hidden>
 Drupal bootstrap       :  Successful
 Drupal user            :
 Default theme          :  bartik
 Administration theme   :  seven
 PHP configuration      :  C:\WINDOWS\php.ini
 PHP OS                 :  WINNT
 Drush script           :  C:\Users\dj\AppData\Roaming\Composer\vendor\drush\drush\drush
 Drush version          :  8.1.2
 Drush temp directory   :  C:\Users\dj\AppData\Local\Temp
 Drush configuration    :
 Drush alias files      :  C:\Users\dj/.drush/aliases.drushrc.php
 Install profile        :  standard
 Drupal root            :  E:\DJs Documents\public_html\Drupal_80
 Drupal Settings File   :  sites/default/settings.php
 Site path              :  sites/default
 File directory path    :  sites/default/files
 Temporary file         :  c:\windows\temp
 directory path
 Sync config path       :  sites/default/files/config_sv6Fa0bsJ-8-3r7jqKWAXF5b5aTa4wPF3cGiGACIUGlzZYikJx9obhTX_nlyIWR7rox9zB4q4Q/sync

**Comment by Zythyr** [comment]
Anyone know when there will be an update to drush that will resolve this issue?

**Comment by Zythyr** [comment]
I updated Drush to 8.1.3. Still having the same issue.

**Comment by peterromero** [comment]
I just created a possible fix for this... we'll see if the Drush people accept my pull request. In the meantime, try this:

Edit the file /path/to/drush/includes/exec.inc and change line 331 from this:
`return _drush_escapeshellarg_windows($arg, $raw);`
to this:
`return _drush_escapeshellarg_windows($arg, TRUE);`

**Comment by randell** [comment]
`return _drush_escapeshellarg_windows($arg, TRUE);` seems to have worked for me.

**Comment by Zythyr** [comment]
@peterromero  Thank you very much. Your solution worked!

**Comment by peterromero** [comment]
So glad to hear it! It's a stopgap... we should find out why escaping paths with quotes is breaking in Windows, but for now, this seems to work.

**Comment by francesco-quagliati** [comment]
@peterromero thanks so much! I was struggling with this issue for some time..  Thanks!

**Comment by medis** [comment]
other workaround is to cd to drush dir i.e. C:\Users\user\AppData\Roaming\Composer\vendor\drush\drush
and run
php drush.php --root="C:\www\webroot" core-cron

**Comment by vnada** [comment]
@peterromero Thanks man, this fixed the issue for me.

**Comment by parkerjgit** [comment]
that worked. Thanks @peterromero !! made my day.

**Comment by weitzman** [comment]
I think I just fixed the problem mentioned here. Not sure I got all cases though. Please post here if problems persist.

**Comment by bradklaver** [comment]
I had this issue, and saw weitzman's previous post.  After updating drush to 8.15, I'm no longer experiencing the issue.

**Comment by ivanjaros** [comment]
So I updated my drush(really stupid idea in a long time) and now I cannot run drush because I will get `Could not open input file: 'C:\Users\ijaro\.composer\global\drush\drush\vendor\drush\drush\drush.php` and the only thing that works is to run `drush.launcher` but that gives me `The filename, directory name, or volume label syntax is incorrect.`

**Comment by isabelmr** [comment]
I have still the same error in Windows 7 using Drush 8.1.10. Drush works but I get this error when I try to use drush inside a Drupal folder, in additionally I would like to add that I am using composer to create my drupal structure, that means that my drupal folder is  something like "myProyectFolder/web"

**Comment by ivanjaros** [comment]
use cgr to install drush and all will be fine.

**Comment by benedikt-d** [comment]
Experiencing the same issue with Windows 7 and Acquia Dev Desktop. Drush Version is 8.1.10.

**Comment by benedikt-d** [comment]
@weitzman can you check if this is still from the problem mentioned above?

**Comment by blakemorgan** [comment]
I'm still having this issue. I'm running the latest version of Drush 8, PHP 7.1.14, and Windows 10. I'm using XAMPP.

**Comment by Skullywag** [comment]
Having the same issue on windows 7, php 7.1.13 with drush 8.1.16, my --root path looks odd as per the above log, whats with the double slashes "C:\\Websites\\\myproject\\docroot"?

**Comment by cscawley** [comment]
I resolved this issue when I noticed drush was installed as a vendor package on the project I'm working on. I deleted drush binaries from vendor/bin and vendor/drush. After that I was finally able to run drush on the docroot of the project.

**Comment by shakilahmad46** [comment]
@peterromero their is nothing like this `return _drush_escapeshellarg_windows($arg, TRUE); ` in my exec.inc file. the file is attached. can you help me to get rid of this issue? I am using Acquia Dev Desktop
[exec.zip](https://github.com/drush-ops/drush/files/3194865/exec.zip)

**Comment by peterromero** [comment]
@shakilahmad46 you seem to be running a newer version of Drush. Which version is it? I'm not doing much with Drush these days; maybe @weitzman will see this and circle back around.

**Comment by shakilahmad46** [comment]
@peterromero I am using version 8.

**Comment by usmanublox** [comment]
@shakilahmad46 
I was also facing the same issue on windows 10 with Acquia Dev Desktop and configured existing Drupal 8 project from a client.

Following three things what I did worked for me.

I simply:

Removed directory **vendor/drush**
Removed directory **vendor/bin**
Removed line **"drush/drush": "^8.1"** from `composer.json` which is located on docroot directory.
Now, default drush is working for me as you can see the default drush version at `C:\Program Files (x86)\DevDesktop\tools\composer.json`.

Hopefully, this will help someone else.

**Comment by MayraU** [comment]
@usmanublox that worked for me, thank you! It was the conflict between Drupal composer drush inside vendor/drush/drush/ vs the Acquia Dev Desktop drush that kept causing this issue for me. I wonder if there another way other then deleting those files and somehow set a Acquia drush as default.

**Comment by greg-1-anderson** [comment]
If vendor/drush/drush exists, then you must use it. Trying to use the global Drush when there is a site local Drush will cause problems; Drush goes to lengths to avoid this.

**Comment by MayraU** [comment]
@greg-1-anderson I I took a look at it again and I was able to make it work without deleting any files and having acquia dev desktop in place as well. So instead of deleting either drush or acquia dev desktop I was able to run locally drush that's in the vendor doing the following.

1. Using acquia dev desktop opened Drush Console
2. cd into vendor
3. ran just `drush`
4. cd into bin 
5. ran `drush cr`

This worked while keeping the vendor drush files intact. I was not able to run it to vendor/drush/drush locally but noticed that there was a bin folder with drush there too and that worked. Seems like a known issue when having Acquia Dev Desktop installed: [Other users with the same issue](https://drupal.stackexchange.com/questions/271193/acquia-dev-desktop-and-drush-broken-with-syntax-is-incorrect)

**Comment by permanaj** [comment]
Hi @MayraU ,
I tried similar workaround.

1. Using acquia dev desktop open Drush Console
2. It will open directory docroot, type `drush cr`, let the error appear
3. Type `php ..\vendor\drush\drush\drush cr` (or any drush command)

However, this is not working in Windows Powershell. Wanted to try another console because Windows command prompt can't colorize some command.

**Comment by Chandra-Gowsalya** [comment]
Facing same issue "The filename, directory name, or volume label syntax is incorrect." When checking drush status ...I have tried in command prompt and also in gitbash
![Screenshot (7)](https://user-images.githubusercontent.com/90616150/133258778-8aab37f2-b5e4-4410-ad98-cd4c9670b1af.png)
