### ISSUE TITLE
field-info throws errors

### ISSUE THREAD

**Issue by avibrazil** [drush-ops/drush#2154]
Here are the outputs:

> $ drush field-info fields
> 
> Fatal error: Call to undefined function field_info_fields() in phar:///Users/aviram/bin/drush/commands/core/field.drush.inc on line 304
> Drush command terminated abnormally due to an unrecoverable error.  
> Error: Call to undefined function field_info_fields() in phar:///Users/aviram/bin/drush/commands/core/field.drush.inc, line 304

And one more

> $ drush field-info types
> 
> Fatal error: Call to undefined function field_info_field_types() in phar:///Users/aviram/bin/drush/commands/core/field.drush.inc on line 319
> Drush command terminated abnormally due to an unrecoverable error.  
> Error: Call to undefined function field_info_field_types() in phar:///Users/aviram/bin/drush/commands/core/field.drush.inc, line 319

This is Drush 8.1.0

**Comment by lifenstein** [comment]
Having the same issue in Drush 8.1.12 with Drupal 8.3.5

**Comment by lifenstein** [comment]
Also getting `undefined function` error with other field functions:

- field-clone
- field-update

`field-create` tries to call field-info internally and fails as well.

**Comment by lifenstein** [comment]
Related: #692, #1080, #230. It seems field commands haven't been ported to D8 yet.

**Comment by awm086** [comment]
having the same issue with field-create wonder if it's no longer supported .
 Drush version                   :  8.1.13     &  Drupal version                  :  8.6.3

**Comment by webmasterpf** [comment]
Get this error too with Drush8 and Drupal8.7.8:
```
$ drush @vmdevd8lr field-info
Which information do you wish to see?
 [0]  :  Cancel
 [1]  :  types
 [2]  :  fields
2
Error: Call to undefined function field_info_fields() in drush_field_info() (line 304 of /home/xxx/.config/composer/vendor/drush/drush/commands/core/field.drush.inc)
```
And get this message with Drush 9 and D8.7.8:
`Command "field-info" is not defined.`

So is this command had been ported to D8 ? If not, when could we hope it will be ?

Thanks

**Comment by weitzman** [comment]
Not ported, and likely wont be in drush core anymoore.

**Comment by webmasterpf** [comment]
Ok, do exist another way to get this kind of list ?

**Comment by Chi-teck** [comment]
@webmasterpf, depends on what you are trying to achieve. In Drush 8 field settings are stored in configuration system. So you can check it like follows:
` drush cget field.field.node.article.body`

**Comment by webmasterpf** [comment]
I just want to get a list of fields like `admin/reports/fields` do. So drush 8 command was useful. I will try your way.

**Comment by Chi-teck** [comment]
If you have exported your configuration it's quite easy to find field definition through yml.
```
ls -1 config/sync/field.storage.*
ls -1 config/sync/field.field.*
```

For reading definitions from active storage you can use plugin manger.
`drush ev 'print_r(\Drupal::service("plugin.manager.field.field_type")->getDefinitions());'`
