### ISSUE TITLE
drush fails updating drupal 8.x site

### ISSUE THREAD

**Issue by deajan** [drush-ops/drush#2155]
Hello,

Trying to update drupal 8.0.5 to 8.1.0 with drush.
I get the following error:
```
The external command could not be executed due to an application error.                                                                                                            [error]
The command could not be executed successfully (returned: PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or[error]
'{' or '$' in /home/www/siteurl.fr/ftp/www/core/includes/common.inc on line 1273
PHP Fatal error:  Call to a member function getRequestUri() on a non-object in /home/www/siteurl.fr/ftp/www/core/modules/locale/src/LocaleLookup.php on line 151
, code: 255)
pm-updatestatus failed.
```

Using drush 8.1.0.
After updating drupal 8.0.5 manually to 8.1.0, the problem remains the same.

Output of drush pm-update --debug:
https://gist.github.com/deajan/136855a8d6851327a1698f1ea9dbd1a0

Using PHP 7.0.5 (cli) (built: Apr  8 2016 16:43:12) ( NTS ).

Thanks for any advice here.

**Comment by bmx269** [comment]
I am having the same issue.

**Comment by jslowy** [comment]
I also have exactly the same issue

**Comment by weitzman** [comment]
That message suggests a parse error in Drupal core.

**Comment by bloomt** [comment]
Also having the same issue

**Comment by deajan** [comment]
Problem persists with drush 8.1.2 and drupal 8.1.1.

**Comment by origindesign** [comment]
I got the same issue and it was related to php version. Apparrently your site is on php 7 but maybe your server is on another version. In my case, the site is on php5.6 but the server is still on php5.4. Running drush with php5.4 was causing the exact same issue.

The solution was to ceate an alias to tell drush to use php5.6 instead of the default server version. Here is the alias I created in my .bash_profile:

`alias drush='DRUSH_PHP=/usr/local/php-5.6.20-cgi/bin/php /usr/local/bin/drush'`

Change it to whatever your php and drush paths are.
Hopefully it will help.

**Comment by bmx269** [comment]
if you have multiple versions of Drush installed, this works too: (whatever php you have)

```
export DRUSH_PHP=/usr/local/php5-5.6.xxxxx/bin/php
```

**Comment by mikeusry** [comment]
I have attempted the above.  My path to drush = /usr/local/bin/drush   My path to my 5.6 version of php = /opt/plesk/php/5.6/etc/php.ini

Therefore I run
`export DRUSH_PHP=/opt/plesk/php/5.6/etc/php.ini`

Any advice on why my drush status output does not change?

**Comment by RamboLau** [comment]
# ## ##

**Comment by weitzman** [comment]
DRUSH_PHP only works on non .phar installations. The best way to control your PHP version with DRUSH is to adjust your PATH so that the desired php is always called.

**Comment by deajan** [comment]
I have multiple php-fpm versions installed with SCL on CentOS.
In my case, I could force the shell to my SCL php version with
```
source /opt/remi/php70/enable
/usr/local/bin/drush
```

Instead of enabling the SCL php on all shells, I wrote a small wrapper in /usr/local/bin/drush-alt
```
#!/usr/bin/env sh

export PATH=/opt/remi/php70/root/usr/bin:/opt/remi/php70/root/usr/sbin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/opt/remi/php70/root/usr/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export MANPATH=/opt/remi/php70/root/usr/share/man:${MANPATH}

/usr/local/bin/drush "$@"
```

This way, I could run drush with the stock php version or with the scl php version depending on the site I'm working on.

Solved for me :)

**Comment by mikeusry** [comment]
@deajan Thank you so much!

**Comment by crantok** [comment]
@weitzman said

> DRUSH_PHP only works on non .phar installations. The best way to control your PHP version with DRUSH is to adjust your PATH so that the desired php is always called.

Which installation method should I use if I want to use DRUSH_PHP ? (It seems a heck of a lot more elegant than messing with my PATH when I want to use drush.)

Please could I just check that the problem I have is the same one described in this thread?

I run

`php56 ./drush.phar up drupal`

and the output I get is

`pm-updatestatus failed. [error]`

If I add the verbose flag then I see this line of output first

`env COLUMNS=207 /home/hellings/webapps/red_dev/drush.phar  --backend=2 --verbose --root=/home/hellings/webapps/red_dev --uri=http://default  pm-updatestatus drupal 2>&1                               [notice]`

If I copy and paste that line and edit it to be

`env COLUMNS=207` **php56** `/home/hellings/webapps/red_dev/drush.phar  --backend=2 --verbose --root=/home/hellings/webapps/red_dev --uri=http://default  pm-updatestatus drupal 2>&1                               [notice]`

and execute it then I see a lot of json scroll down my screen that I didn't see before. Is this an indication that my edit solved the problem? Would I be able to solve this by setting DRUSH_PHP for an installation that responds to that setting?

**Comment by weitzman** [comment]
You use a Composer install not a .phar install if you want to use DRUSH_PHP env variable.

However, futzing with path can be done just for a given request. For example (untested):

    alias drush="$PATH=/path/to/desired/php:$PATH drush"

**Comment by crantok** [comment]
Thank you!

Just a note to anyone else with a similar issue to me: My host does not provide php 5.6 anywhere as an executable called `php`, so I did this:

```
# cli
mkdir $HOME/php56
cd $HOME/php56
ln -s /usr/local/bin/php56 php

# and in .bashrc
alias drush="PATH=$HOME/php56:$PATH $HOME/scripts/drush.8.0.5.phar"
```

**Comment by pselfin** [comment]
Hi!
Drush instaled via composer.
In my .bashrc/.bash_profile added

```
export DRUSH_PHP='/opt/php56/bin/php'
export COLUMNS
alias composer='/opt/php56/bin/php -d memory_limit=500M /home/c/ct00533/composer.phar'
alias drush='/opt/php56/bin/php -d memory_limit=500M /home/c/ct00533/vendor/bin/drush.php'
```
alias work good
```
public_html$ drush --version
 Drush Version   :  8.1.12
```
Command _drush status/cc/cr/dl_ workin very good. **drush pm-updatestatus** work too...

But! 
**drush up** don't work!((

Error:

```
public_html$ drush up
The external command could not be executed due to an application error.                                                                                 [error]
The command could not be executed successfully (returned: PHP Parse error:  syntax error, unexpected '[' in                                             [error]
/home/c/ct00533/vendor/drush/drush/includes/preflight.inc on line 341
, code: 255)
pm-updatestatus failed.  
```             

Why???

Php version for drush ok:
```
public_html$ drush status
 PHP configuration               :  /etc/php56/cli/php.ini
 PHP OS                          :  Linux
 Drush script                    :  /home/c/XXXX/vendor/drush/drush/drush.php
 Drush version                   :  8.1.12
```
Help me, please!

--
Sory for my English
