### ISSUE TITLE
'drush runserver' in 8.1.0 fails with Class 'Drush' not found in commands/runserver/runserver.drush.inc on line 140

### ISSUE THREAD

**Issue by dsnopek** [drush-ops/drush#2157]
The thing is, I can't find a 'Drush' class in the 8.1.0 release, however, it does exist in the Git repo.

I suspect that some in development change that depended on the new 'Drush' class got merged into stable before the 'Drush' class got merged into stable?

Our CI is installing drush/drush:8.* which is now breaking - in the meantime, I guess we'll switch to drush/drush:8.0.*

**Comment by weitzman** [comment]
Did you run `composer install` to generate a new autoload.php?

**Comment by dsnopek** [comment]
I installed drush via 'composer require drush/drush:8.*' so composer ran! The thing is, I don't see the 'Drush' class anywhere in the source code via grepping or looking for a Drush.php file. :-/

**Comment by weitzman** [comment]
I improperly backported a patch. Will fix and issue new release soon.

**Comment by weitzman** [comment]
I pushed a fix in c3da343. I'll wait a day or two for more bugs and then push a release. thanks for the report.

**Comment by dsnopek** [comment]
Thanks for the quick fix! :-)

**Comment by heddn** [comment]
This is biting me using a composer based install. Will a new rev be provided soon?
