### ISSUE TITLE
Fatal error: Class 'League\Container\Container' not found

### ISSUE THREAD

**Issue by aaronbauman** [drush-ops/drush#2159]
After updating to Drupal 8.2.x (from 8.0.x: git checkout origin/8.2.x ; composer install ) and latest drush (via http://docs.drush.org/en/master/install/) I'm get the fatal error "Fatal error: Class 'League\Container\Container' not found" when running any drush command.

update.php works fine to run db updates, but drush issue persists

**Comment by weitzman** [comment]
You have to run composer install anytime you change drush code (assuming you dont use the .phar)

**Comment by aaronbauman** [comment]
After updating drupal and updating drush using the ".phar" method, i ran composer install in d8 root directory, in ~/.composer/, ~/.composer/vendor/drush/drush

still drush is working fine for D7 sites, but fails with this fatal on D8

What am i missing?

**Comment by weitzman** [comment]
It sounds like you are running a Drush with an outdated vendor directory. composer install should fix it up.

**Comment by messageagency** [comment]
composer install didn't work.
I had to remove vendor/drush, then ran composer install, and i'm back up and running.

thanks

**Comment by joelpittet** [comment]
I'm running into this as well.  9.x seems to have some issues today.
