### ISSUE TITLE
7.x branch "The Source and Destination cannot both be the same"

### ISSUE THREAD

**Issue by ElijahLynn** [drush-ops/drush#2160]
With 7.x checked out and a `drush --version` giving 7.3-dev on both local and remote and a sqlsync.drush.inc file with a comment at the top that says " \* - Source and Dest can both be remote. Convenient." I am getting "The Source and Destination cannot both be the same" when trying to sync a remote to a remote. 

I see in issue #1013 this should not happen on 7.x because it was only in Drush 6 and this makes sense because I get nothing when grepping for fragments of this in the Drush 7.x source code. 

Any ideas on why I would be getting this error? 

Here are my aliases:

```
$aliases['stage'] = array(
  'root' => '/var/www/html/mvpdadminstg/docroot',
  'uri' => 'http://stage.example.com',
  'remote-host' => 'ec2-52-91-108-119.compute-1.amazonaws.com',
  'remote-user' => 'anon',
  'path-aliases' => array(
    '%drush-script' => 'drush' . $drush_major_version,
  ),
);
$aliases['qa'] = array(
  'root' => '/var/www/html/mvpdadminqa/docroot',
  'uri' => 'http://qa.example.com',
  'remote-host' => 'ec2-54-165-27-205.compute-1.amazonaws.com',
  'remote-user' => 'anon',
  'path-aliases' => array(
    '%drush-script' => 'drush' . $drush_major_version,
  ),
);
```

I have the full debug output but will only post if requested as I will have to go through it and review for security reasons.

**Comment by ElijahLynn** [comment]
I just read through more issues and I suspect it is because the two remotes need SSH access to each other and I don't think that is the case currently. I also think they may have some firewall rules in effect as I can only access these aliases behind a proxy. 

This leads me to believe the error message is just inaccurate and I need to fix the above issues. I am also guessing cannot grep for that error message since it just bubbles up from rsync.

**Comment by ndf** [comment]
@ElijahLynn commented on 26 Apr 2016
This is true. I had this setup where my 2 remotes were not able to connect to each other. And I called the sql-sync command from a 3rd machine that has access to both remotes.
That resulted in the error message "The Source and Destination cannot both be the same"

**Comment by weitzman** [comment]
Drush7 is now unsupported.
