### ISSUE TITLE
Retrieve a specific field of a given site alias.

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#2163]
I wonder how do I get _uri_ option of the site alias. Per the documentation the _field_ option should fit my needs but it is not working for me.
The output of `drush sa @mysite.local --fields=uri` does not differ from `drush sa @mysite.local --fields=uri`. However `drush sa --field=uri` (for all aliases) works as expected.

**Comment by weitzman** [comment]
I think the issue is that --fields is not supported by all output formats, including the default one for this command (json). Append --format=list and you will get just value of uri
