### ISSUE TITLE
Runserver failed on 8.1.0

### ISSUE THREAD

**Issue by yaoweizhen** [drush-ops/drush#2166]
Enviroment:
Fedora 23, PHP 5.6.19, Drupal 7.43

(It works on 8.0.5)

> Call Stack:
>     0.0381     772104   1. {main}() /usr/local/bin/drush.phar:0
>     0.0383     765432   2. require('phar:///usr/local/bin/drush.phar/drush') /usr/local/bin/drush.phar:10
>     0.0392     814720   3. drush_startup() phar:///usr/local/bin/drush.phar/drush:114
>     0.0420     982840   4. drush_main() phar:///usr/local/bin/drush.phar/includes/startup.inc:325
>     0.6207    8869384   5. Drush\Boot\BaseBoot->bootstrap_and_dispatch() phar:///usr/local/bin/drush.phar/includes/preflight.inc:66
>     1.9394   45651464   6. drush_dispatch() phar:///usr/local/bin/drush.phar/lib/Drush/Boot/BaseBoot.php:67
>     2.2877   48518568   7. call_user_func_array:{phar:///usr/local/bin/drush.phar/includes/command.inc:185}() phar:///usr/local/bin/drush.phar/includes/command.inc:185
>     2.2877   48519088   8. drush_command() phar:///usr/local/bin/drush.phar/includes/command.inc:185
>     2.2885   48523912   9. _drush_invoke_hooks() phar:///usr/local/bin/drush.phar/includes/command.inc:217
>     2.2911   48575720  10. call_user_func_array:{phar:///usr/local/bin/drush.phar/includes/command.inc:366}() phar:///usr/local/bin/drush.phar/includes/command.inc:366
>     2.2911   48576360  11. drush_core_runserver() phar:///usr/local/bin/drush.phar/includes/command.inc:366
> 
> Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                      [error]
> Error: Class 'Drush' not found in phar:///usr/local/bin/drush.phar/commands/runserver/runserver.drush.inc, line 140

**Comment by weitzman** [comment]
Already fixed.  A new release is forthcoming.
