### ISSUE TITLE
Drush 8 install fails on Windows

### ISSUE THREAD

**Issue by liquidcms** [drush-ops/drush#2167]
D:\>composer global require drush/drush
Changed current directory to C:/Users/Peter/AppData/Roaming/Composer
You are running composer with xdebug enabled. This has a major impact on runtime
 performance. See https://getcomposer.org/xdebug
Using version ^8.1 for drush/drush
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: pear/console_table[v1.3.0, v1.2.1].
    - Can only install one of: pear/console_table[v1.3.0, v1.2.1].
    - Can only install one of: pear/console_table[v1.3.0, v1.2.1].
    - drush/drush 8.1.0 requires pear/console_table ~1.3.0 -> satisfiable by pea
r/console_table[v1.3.0].
    - Installation request for drush/drush ^8.1 -> satisfiable by drush/drush[8.
1.0].
    - Installation request for pear/console_table (locked at v1.2.1) -> satisfia
ble by pear/console_table[v1.2.1].

Installation failed, reverting ./composer.json to its original content.

D:\>

I ran pear install console_table which installed console table ver 1.3.0, but error is the same.

**Comment by weitzman** [comment]
I dont know why Windows would affect dependency resolution. We perform that same command in our Travis tests so it is working in general.

Try a non-global install of Drush. That way you are unaffected by other programs you have installed.

**Comment by liquidcms** [comment]
Thanks. I'll try the non-global as a test; although certainly isn't a solution (if i understand what non-global is: install per site?). 

Maybe this issue queue is handled different than say the one on d.org; but seems odd to mark as closed when the issue isn't resolved. Isn't it easier for others to comment on if they have seen same issue if it isn't closed.
