### ISSUE TITLE
Core drush hooks with annotation files

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#2172]
Today (using #2139 or #2103), you can create a hook with an annotation command like so:
```
/**
 * @hook core-status pre-validate
 */
```
That will create a pre-validate hook for the core-status command.  Any command alias can also be used in the first position as well.  Currently, only commands can be hooked, and you must hook old-style commands with the old hook mechanism, and can only hook annotated commands with the new hook mechanism.  That much may or may not ever change.

It would be nice, though, to be able to make annotated hooks for core drush hooks, such as hook_drush_sitealias_alter.  For this, I propose:
```
/**
 * @hook drush sitealias_alter
 */
```
It does not matter very much what the first word is; since the second hook name will not be the same as one of the existing command hooks (pre-validate & c.), there will not be any namespace collisions here, even if someone makes a `drush` command. I suggest that we just use `drush` for all internal Drush hooks, and come up with other namespaces as needed. For example, if we factor out a site aliases library, we could at that time standardize on `@hook alias alter`.  At that point, though, we have a potential collision, as `alias` might be a command, and `alter` is definitely one of the standard command hook names.

So, what do you think?  To unambiguously avoid collisions, we could:

1. Use something other than @hook for global hooks (not my favorite)
2. Add another keyword to global hooks, e.g. @hook global drush sitealias_alter (also not great, as both 'global' and 'drush' are kind of meaningless here; also, perturbs the HookManager code)
3. Add perl-like punctuation, e.g. @hook # sitealias_alter or @hook #drush sitealias alter
4. Drop one parameter, e.g. @hook sitealias_alter (adds special checking to the HookManager methods; plus, the namespacing is handy once we start having multiple libraries)
5. Just avoid the common command hook names like `alter`, as suggested above (which means that `@hook alias alter` would have to be something like `@hook alias alias-alter`).

**Comment by greg-1-anderson** [comment]
I should also add that we currently have:
```
/**
 * @hook * post-extract
 */
```
This adds a hook to the `extract` phase that runs for all commands. For example, Drush does this in order to get a reference to the final function result of the command to pass along to backend invoke.

**Comment by weitzman** [comment]
4. sounds good to me. maybe commandfiles should register their available hooks? 

note that silealias_alter might not need to exist? could you not use a post hook to alter it? i guess there are codepaths that would not execute that. but maybe we say that those are bypassing API?

Lets not document that you can use command aliases in hook names. i'd rather folks use the canonical name for easier grepping.

**Comment by greg-1-anderson** [comment]
Actually, I think we should stick with constant (pre-defined) hook annotations (e..g @hook), or at most, allow libraries to register new hook annotations via an API on the HookManager applied only when the DI container is built. Allowing commandfiles to register available hooks is too flexible, IMO; we'd have to register all of the commandfile commands and hooks once (since the available hook registration function would itself be a hook), and then go back and look at all of the commandfiles again to figure out if any of their methods were annotated with a registered hook.

I suppose another way to break out of the two-pass connundrum would be to have commandfiles implement an interface if they want to register available hooks.  That would still be two passes, but the first pass, at least, would not parse any annotations, so the annotation parsing would happen in just one pass.

The existing `hook_drush_sitealias_alter` allows a hook function to change an alias definition whenever it is used. When working with a Pantheon site with multiple domain names, for example, Pantheon will pick an arbitrary domain to place in the aliases `uri` field. Some folks have modules that care which domain is used; in this instance, we recommend using a policy file with a `hook_drush_sitealias_alter` to select the URI they want to use, so they don't need to worry about the contents of the alias file on disk (users may update their aliases in multiple ways, including just downloading a file via the web browser).

The current set of global hooks used by Drush includes:

- bootstrap_candidates
- drush_cache_clear
- drush_command_alter
- drush_engine_topic_additional_text
- drush_engine_type_info
- drush_flush_caches
- drush_help
- drush_help_alter
- drush_invoke_alter
- drush_pm_download_destination_alter
- drush_pm_post_download
- drush_sitealias_alter
- drush_sql_sync_sanitize
- drush_storage_filters

I don't know that we will still need all of these, but that's the current list.  Do you know of any contrib commands today that define their own global hooks?  Site audit calls comand_alter, but I don't know of any that define their own.

**Comment by greg-1-anderson** [comment]
Also, if we stick with `@hook hookname`, that would make it easier to grep for all commandfiles with hooks, without having to know in advance what the hooks were.

Maybe we should swap the order of the parameters:
```
/**
 * @hook pre-validate core-status 
 */
```
Then we just say that `alter` is taken, and make aliases use `sitealias-alter` or `alias-alter`. I think I like that the best; moving the variable component to the end disambiguates things quite a bit.

**Comment by greg-1-anderson** [comment]
I just went to look into making the parameter order swap I mention above, and I discovered that I already did that many releases ago -- I just forgot.

I think in the short term I am going to postpone things here by simply not discussing global hooks during dcnola, but post-presentation, I think I'll proceed per my previous comment.

**Comment by weitzman** [comment]
Sounds good.

I can meet up on sun or mom if you want to work on slides and such.
Otherwise I'm free on tues until our session and bof.

**Comment by weitzman** [comment]
I think this is done now. See #2366
