### ISSUE TITLE
Call to undefined function db_result() when running site-install command on D6

### ISSUE THREAD

**Issue by jamesbeake** [drush-ops/drush#218]
Here's the error in context. drush command work fine on D7.

===Commandline===

> drush si --db-url=mysql://d6:d6@localhost/d6 --site-name="d6" --account-name=admin --account-pass=password --yes

===== Output====
You are about to DROP all tables in your 'd6' database. Do you want to continue? (y/n): y
No tables to drop.                                                                                                                             [ok]
Starting Drupal installation. This takes a few seconds ...                                                                                     [ok]
Drush was not able to start (bootstrap) the Drupal database.                                                                                   [error]
Hint: This may occur when Drush is trying to: \* bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working database setup by specifying the URI to use with the --uri parameter on the command line. See `drush topic docs-aliases` for details. \* connect the database through a socket. The socket file may be wrong or the php-cli may have no access to it in a jailed shell. See http://drupal.org/node/1428638 for details.

Drush was attempting to connect to:
Drupal version         :  6.28
Site URI               :  http://default
Default theme          :  garland
Administration theme   :  garland
PHP executable         :  /usr/bin/php
PHP configuration      :  /etc/php5/cli/php.ini
PHP OS                 :  Linux
Drush version          :  6.0-dev
Drush configuration    : 
Drush alias files      : 
Drupal root            :  /var/www/d6.local
Site path              :  sites/default         

PHP Fatal error:  Call to undefined function db_result() in /opt/drush/commands/core/drupal/site_install_6.inc on line 134 
Drush command terminated abnormally due to an unrecoverable error.
[error]
Error: Call to undefined function db_result() in /opt/drush/commands/core/drupal/site_install_6.inc, line 134

=== PHP Version ====
php --version
PHP 5.4.9-4ubuntu2.3 (cli) (built: Sep  4 2013 19:37:07) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2012 Zend Technologies

cheers
James

**Comment by pfrenssen** [comment]
This error occurs if the "mysql" extension is disabled. Check your `php.ini` file and uncomment this line:

```
;extension=mysql.so
```

**Comment by nickveenhof** [comment]
Error is reproducible on php 5.5.9. Trying to get some more understanding but looks like that doesn't exist anymore

**Comment by anavarre** [comment]
Just got the issue as well by trying to spin up repeatable D6 sites for D6->D8 migrations. Running PHP 5.6 and the installer works fine via the UI, not just with Drush.

```
$ drush site-install -y --site-mail=admin@source.local --site-name=source --account-mail=admin@source.local --account-name=root --account-pass=root --clean-url --db-url=mysql://root:root@localhost/source
```

**Comment by weitzman** [comment]
Perhaps Drupal 6 has trouble with modern PHP versions. This is going to take some research by someone who cares about odd and barely supported software combinations like that.

**Comment by crevillo** [comment]
error appears also with php 5.3. (ubuntu precise docker image)

**Comment by ryanjbonnell** [comment]
This error also occurs when using the latest version of Drush 8.x installed via Homebrew on macOS 10.12 "Sierra" with PHP 5.6.24.

```
$ drush site-install -y default --db-url=mysql://username:password@127.0.0.1/database
...
PHP Fatal error: Call to undefined function db_result() in  
/usr/local/Cellar/drush/8.1.3/libexec/commands/core/drupal/site_install_6.inc on line 136
```

**Comment by geerlingguy** [comment]
Using `mysqli` instead of `mysql` in the site-install command worked for me (e.g. using the above comment as an example, it would be `drush site-install -y default --db-url=mysqli://username:password@127.0.0.1/database`).

**Comment by AaronFeledy** [comment]
I was able to work around this in PHP 5.6 by disabling mbstring functions in php.ini:

```
mbstring.http_input = pass
mbstring.http_output = pass
```

**Comment by AaronFeledy** [comment]
Lando is using v8.4.5 for Drupal 6. The above workaround doesn't work on versions newer than that. Tried today with 8.5.0 and the issue remains.
