### ISSUE TITLE
user-login (uli) shouldn't fall back to using user 1 if a non-existent user is requested

### ISSUE THREAD

**Issue by TravisCarden** [drush-ops/drush#2182]
If you pass a non-existent user to `drush uli` it returns a one-time link for user 1 without saying anything:

``` bash
drush uli some_nonexistent_user
http://example.localhost/user/reset/1/1462994999/WpJPLLXbkd_AKMA94IieNc0f6DGBPIZu4Dt8fdMhL-Y
```

This can be disorienting, but one can easily imagine how it could cause real problems. Suppose, for example, your customer asks you for a login link and you mis-type their username. You've just given your customer root access.

I think it should throw an error if you supply an invalid user argument.

**Comment by weitzman** [comment]
Agreed. Hope someone whips up a PR.

**Comment by TravisCarden** [comment]
Looking at the relevant code, @weitzman, it would be trivial to fix this if we consider the command arguments normally. The following is all it would take:

```diff
diff --git a/commands/user/user.drush.inc b/commands/user/user.drush.inc
index 7adad52..dd451b9 100644
--- a/commands/user/user.drush.inc
+++ b/commands/user/user.drush.inc
@@ -401,12 +401,15 @@ function drush_user_login($inputs = '', $path = NULL) {
     }

     // Try to load a user from provided options and arguments.
+    if (!$inputs) {
+      // No user option or argument was passed, so we default to uid 1.
+      $inputs = 1;
+    }
     try {
       $userlist = new UserList($inputs);
     }
     catch (UserListException $e) {
-      // No user option or argument was passed, so we default to uid 1.
-        $userlist = new UserList(1);
+      return drush_set_error($e->getMessage());
     }
     $links = $userlist->each('passResetUrl', array($path));
   }
```

The trouble is that the `user` command argument is "magic"--if you pass any of the `--mail`, `--name`, or `--uid` options, it "disappears" and the command acts as if it only has a `path` argument. Right now, `drush uli 1 node/add` is the same as `drush uli node/add --uid=1`. (See [\Unish\userCase::testUserLogin()](https://github.com/drush-ops/drush/blob/9.0.0-alpha1/tests/userTest.php#L115).) Well, that's just crazy talk. :) If `user` is an argument, we have to be able to identify it by position. That's the whole distinction between an argument and an option. I'm sure I could write a patch that would account for that complexity, but the result will be silly, and I wanted to get your thoughts first. How would you like to handle this? Change the signature of the command so as to stop conflating the concepts or arguments and options? Or add more special case handling code to compensate for the conflation? I generally vote for doing the "correct" thing and respecting the domain, but in this case that involves making a backwards-incompatible change. What say you?

**Comment by TravisCarden** [comment]
Thoughts, @weitzman ?

**Comment by weitzman** [comment]
The signature of the command has already changed in master per your suggestion. Can you see if anything more is needed in that branch?

**Comment by TravisCarden** [comment]
Oh, nice! I didn't see that change go through. Then this is fixed. All that remains is to correct the usage example in the command help: #2596.
