### ISSUE TITLE
composer global update fails to update drush

### ISSUE THREAD

**Issue by ckosloff** [drush-ops/drush#2185]
This is what I get upon running 'composer global update' 
 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12

	

kosloff@asr-2:/var/www/html/demoflorida.com$ composer global update
Changed current directory to /home/ckosloff/.composer
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drush/drush dev-master requires codegyre/robo ~1.0.0-beta1 -> satisfiable by codegyre/robo[1.0.0-beta1] but these conflict with your requirements or minimum-stability.
    - drush/drush dev-master requires codegyre/robo ~1.0.0-beta1 -> satisfiable by codegyre/robo[1.0.0-beta1] but these conflict with your requirements or minimum-stability.
    - Installation request for drush/drush dev-master -> satisfiable by drush/drush[dev-master].

ckosloff@asr-2:/var/www/html/demoflorida.com$

**Comment by dasrecht** [comment]
Hi there
We're having this issue too. So it looks like it comes from this commit https://github.com/drush-ops/drush/commit/5b2c92d48f511637c0cd0453790c58d8dbb20567

@greg-1-anderson is there any way we can solve the errors while installing drush[dev-master]?

**Comment by greg-1-anderson** [comment]
If you wish to install a dev version of Drush, you must [set your minimum stability to dev](https://getcomposer.org/doc/04-schema.md#minimum-stability) in your root composer.json file.  In the case of `composer global update`, that would be ~/.composer/composer.json.

If you do not wish to set your minimum stability to `dev` for all of your globally-installed Composer projects, then you should install a stable version of Drush, such as `~8`.

**Comment by ckosloff** [comment]
Thank for answer.
I already tried adding "minimum-stability":"dev" to /home/ckosloff(my user)/.composer/composer.json
but composer global update would throw errors of bad syntax.
Please post verbatim the syntax that needs to be there.
Thank you.

**Comment by zaporylie** [comment]
Try `composer global config minimum-stability dev`

**Comment by ckosloff** [comment]
hanged current directory to /home/ckosloff/.composer

                                                 
  [Seld\JsonLint\ParsingException]               
  "./composer.json" does not contain valid JSON  
  Parse error on line 3:                         
  ...rush": "dev-master""minimum -stability"     
  ---------------------^                         
  Expected one of: 'EOF', '}', ':', ',', ']'     
                                                 

global <command-name> [<args>]...

ckosloff@asr-2:~/.composer$ 
==============================================
Thanks for answer, tried it and the result is above. However, this is nonsensical because this is what happened when I has other stuff there. Now I have another file in .composer directory: composer.lock, I think that I should delete that one, am I right?
