### ISSUE TITLE
move docs into own repo with a more permissive license 

### ISSUE THREAD

**Issue by frob** [drush-ops/drush#2187]
I was thinking of including some of drush's documentation in something that I was writing when I noticed that the docs are included with the code itself and under the same license. This could cause issues for authors who want to include the docs as reference material in a distributed work. It also makes it so full patch releases have to be issued for documentation fixes/contribution. 

Currently it has the benefit of having documentation block releases.

**Comment by weitzman** [comment]
I like our current arrangement. We have docs that revise as the code revises and in the same PRs.
