### ISSUE TITLE
Is `drush site-aliases` supposed to SSH into every alias?

### ISSUE THREAD

**Issue by ElijahLynn** [drush-ops/drush#2193]
Is it expected behavior to SSH into every alias when issuing a `drush site-aliases` command? It takes a long time for this command to run sometimes because of the need to SSH into all of the servers.

If not I will post info on how to reproduce etc.

**Comment by weitzman** [comment]
No. What version of Drush?

**Comment by ElijahLynn** [comment]
Looks like I was actually on fd4216c (after 8.0.2, before 8.0.3), I thought it was on an actual tag though. It is working now in 8.1.2. And it is super fast now!
