### ISSUE TITLE
My report on installing drush in the new WSL

### ISSUE THREAD

**Issue by Benosika** [drush-ops/drush#2196]
I've installed WAMP, WSL in Win10 and also PHP & Drush on WSL ... I then navigated to a site's folder in c:/WAMP with WSL bash like this:

```
cd /
cd mnt/c/wamp64/www/yoursitesname/
```
While inside the sites' folder I did "drush up" and than got:

```
Benia@DESKTOP-D5K6365:/mnt/c/wamp64/www/benia$ drush up
PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_SSL_CA' in phar:///usr/bin/drush/lib/Drush/Sql/Sqlmysql.php on line 56
Drush command terminated abnormally due to an unrecoverable error.
```

**Comment by weitzman** [comment]
See http://stackoverflow.com/questions/13559807/receiving-php-fatal-error-when-using-pdo-mysql-attributes

Make sure your CLI is using a modern PHP and that your PHP has a pdo_mysql driver.

Please post any further notes with WSL.
