### ISSUE TITLE
drush fails when path contains space

### ISSUE THREAD

**Issue by mossy2100** [drush-ops/drush#2203]
It gives an error like
sh: /Users/shaun is a directory
(if the space comes after 'shaun')

This can be patched by changing one line in includes/setup.inc, as follows:

diff --git a/includes/startup.inc b/includes/startup.inc
index 693fede..5c8e4ed 100644
--- a/includes/startup.inc
+++ b/includes/startup.inc
@@ -367,7 +367,7 @@ function drush_startup($argv) {
   }
   else {
     $escaped_args = array_map(function($item) { return _drush_escapeshellarg_linux($item); }, $arguments);
-    $process = proc_open($found_script . ' ' . implode(' ', $escaped_args), array(0 => STDIN, 1 => STDOUT, 2 => STDERR), $pipes);
+    $process = proc_open('"' . $found_script . '" ' . implode(' ', $escaped_args), array(0 => STDIN, 1 => STDOUT, 2 => STDERR), $pipes);
     $proc_status = proc_get_status($process);
     $exit_code = proc_close($process);
     exit($proc_status["running"] ? $exit_code : $proc_status["exitcode"] );

Thanks,
Shaun

**Comment by weitzman** [comment]
Are you on Mac? Linux? Windows? Have you found a solution? Is this still a problem?

**Comment by alexej-d** [comment]
I have exactly the same problem on Mac. @mossy2100's patch fixes it.

**Comment by mossy2100** [comment]
Thank you. Sorry for not following up.

**Comment by weitzman** [comment]
Please try with latest Drush (not yet released). Should be fixed.
