### ISSUE TITLE
config-import --partial does not take into account new files from the source directory

### ISSUE THREAD

**Issue by gggeek** [drush-ops/drush#2208]
This is a problem if a file is present in the 'partial' configs but not in the 'full' configs

**Comment by weitzman** [comment]
I think this is a core limitation. We leverage \Drupal\config\StorageReplaceDataWrapper and thats only for replacing existing data. A PR which handled new files would be welcome.

**Comment by gggeek** [comment]
Actually this might already work... It was reported by a colleague of mine but I could not reproduce it in my own more recent testing. I will try to test it a few more times, and if I can not find a root cause I will close the ticket

**Comment by powysm** [comment]
I am having problems with --partial failing to create the new config from a specified directory label. Can you confirm for me if under these circumstances the create is working correctly, update is working fine.

**Comment by weitzman** [comment]
I just tested and creation works for me. Am using latest code on master branch.
