### ISSUE TITLE
Allow color output to be forced

### ISSUE THREAD

**Issue by ergonlogic** [drush-ops/drush#2214]
Some CI environments (e.g., GitLab CI) appear not to have a terminal, and so Drush output cannot be colored. Drush supports a `--nocolor` option, but there's no way (that I've found anyway) to force color output.

The relevant code is [here](https://github.com/drush-ops/drush/blob/master/includes/preflight.inc#L581). This logic doesn't allow us to force color output, as it would interpret `--nocolor=0` the same as if the option wasn't set to begin with.

So, I propose adding a `--color` option.

**Comment by ergonlogic** [comment]
@greg-1-anderson Do you have any thoughts on this?

**Comment by greg-1-anderson** [comment]
If we add --color, then it would make sense (be consistent with other Drush options) if --color=0 and --no-color turned off colored output.  Maybe doing this, and also supporting --color in the 8.x branch, would be appropriate.

**Comment by webflo** [comment]
I think this is covered ``--ansi`` and ``--no-ansi`` in Drush 9.

**Comment by weitzman** [comment]
Drush9 has no color handling anymore. We build upon symfony console. See #3259
