### ISSUE TITLE
Command user-password needs a higher bootstrap level to run in latest 8.x Drush

### ISSUE THREAD

**Issue by alexrayu** [drush-ops/drush#2221]
I have a number of Dupal 7 and 8 sites across a number of servers. I usually navigate into the drupal root folder and type drush commands. With the current drush 8.x code, that no longer works. Drush recognizes the settings.php file in `drush status` command, but it fails to do anything, like, `drush user-password` or `drush cc all` with an error:

`Command user-password needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.`

`drush cc all `results in this error:

`No Drupal site found, only drush cache was cleared.`

And these errors with drush status recognizes the settings and display correct output with `drush status`.

**Comment by alexrayu** [comment]
Reverted to Drupal 8.1.0 - higher versions are unusable.

**Comment by weitzman** [comment]
Just tried on D7. Worked for me with latest master branch.

 Looks like Drush can't recognize your Drupal site. Please pass --root and --uri options so Drush doesn't have to guess. Thats first step debugging.

**Comment by alexrayu** [comment]
Confirmed with Drush 8.1.2. Thanks for all your work!
