### ISSUE TITLE
Drush make fails for relative path to make file (8.1.2)

### ISSUE THREAD

**Issue by thamas** [drush-ops/drush#2224]
Just updated Drush to 8.1.2 (via composer) on OSX and have the same issue as in #1856. Relative path does not work but absolute path works. And I do not have any drush include files in my site directory…

(I use Drush with MAMP–it was configured earlier and works, and have Acquia DevDesktop installed on my system too.)

**Comment by gaelg** [comment]
I had the problem on Linux when I tried a drush make outside of my home directory. It works otherwise.

**Comment by greg-1-anderson** [comment]
Make is deprecated. Closing old issues.
