### ISSUE TITLE
Incompatibility with Drupal 8.1.x-dev

### ISSUE THREAD

**Issue by bradjones1** [drush-ops/drush#2228]
Similar to #2221 but with (I think) a more descriptive title... Looks like there is a general incompatibility with a recent change to Drupal core > 8.1.0 that makes Drush complain of not having a high-enough bootstrap to continue, even for `drush site-install`.

**Comment by bradjones1** [comment]
This is actually a change > `8.1.3`. Not too helpful in tracking this down but at least that's more specific...

**Comment by greg-1-anderson** [comment]
Old issue with few details; closing.
