### ISSUE TITLE
PHP Fatal error:  Allowed memory size when enabling module (drush 8.1.2)

### ISSUE THREAD

**Issue by Zmove** [drush-ops/drush#2234]
Hello,

When I try to install a drupal module using `drush en mymodule -y` I always get the following error :

> PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted......

I have 512M allocated in my memory_limit of my php.ini. It should be enought....

**Comment by gitressa** [comment]
Have you actually checked that with for example `phpinfo()`?

**Comment by Zmove** [comment]
Hello, thank you for your answer.

I just resolved the problem. In fact, drush didn't use the php.ini file I expected.

doing a "drush status" commande showed me what is the php.ini file used and the memory_limit in that file was 64M. Increased it to 256M and it works.

Thanks
