### ISSUE TITLE
Drush make will not patch .htaccess

### ISSUE THREAD

**Issue by chrisgross** [drush-ops/drush#2237]
I am creating a minimal drupal distribution which includes one core patch. I've included the patch in my drupal-org-core.make file, like so:

`projects[drupal][patch][2106057] = http://drupal.org/files/issues/drupal-7.x-symlinksifownermatch-2106057-5.patch
`

When make is finished, only includes/file.inc is patched. However, when I run `git apply drupal-7.x-symlinksifownermatch-2106057-5.patch`, .htaccess is patched as well. Does drush make intentionally ignore .htaccess patches?

**Comment by sawtell** [comment]
I know this is a couple of years late.. but I just came across the same issue.
If you delete the `.htaccess` file before running `drush make` then the file will be successfully patched.

**Comment by greg-1-anderson** [comment]
Make is deprecated. Closing old issues.
