### ISSUE TITLE
PHP error with Drush and Crontab

### ISSUE THREAD

**Issue by tdmix** [drush-ops/drush#2240]
I'm getting this PHP error when a Drush command is run from Crontab.

Warning: proc_open(): Descriptor item must be either an array or a File-Handle in phar:///usr/local/bin/drush/includes/startup.inc on line 370

Works fine from the CLI as root. Any ideas as to what this might cause? It's Drush 8.12 btw. Drupal 7.44

Thanks much.

**Comment by weitzman** [comment]
Do you have he .phar or a Composer installation? Please post full logs, and output of `drush status`

**Comment by jtphelan** [comment]
Same issue. I was running Drush 6.2 and attempted to upgrade to 8.1.3 following these instructions https://www.drupal.org/node/2603018. But when I try and run drush I get these errors. If I switch back to 6.2 it works fine.

<code>PHP Warning:  proc_open(): Descriptor item must be either an array or a File-Handle in phar:///usr/local/bin/drush/includes/startup.inc on line 370
X-Powered-By: PHP/5.5.36
Content-type: text/html

<br />
<b>Warning</b>:  proc_open(): Descriptor item must be either an array or a File-Handle in <b>phar:///usr/local/bin/drush/includes/startup.inc</b> on line <b>370</b><br />
PHP Warning:  proc_get_status() expects parameter 1 to be resource, boolean given in phar:///usr/local/bin/drush/includes/startup.inc on line 371
<br />
<b>Warning</b>:  proc_get_status() expects parameter 1 to be resource, boolean given in <b>phar:///usr/local/bin/drush/includes/startup.inc</b> on line <b>371</b><br />
PHP Warning:  proc_close() expects parameter 1 to be resource, boolean given in phar:///usr/local/bin/drush/includes/startup.inc on line 372
<br />
<b>Warning</b>:  proc_close() expects parameter 1 to be resource, boolean given in <b>phar:///usr/local/bin/drush/includes/startup.inc</b> on line <b>372</b><br /></code>

**Comment by dmsmidt** [comment]
I'm seeing something similar when running a command via cron (Cpanels).

`/usr/local/bin/drush COMMAND ARG --opt=something`

> PHP Warning:  proc_open(): Descriptor item must be either an array or a File-Handle in /usr/local/src/drush/includes/startup.inc on line 366
> X-Powered-By: PHP/5.6.24
> Content-type: text/html; charset=UTF-8
> 
> <br />
> <b>Warning</b>:  proc_open(): Descriptor item must be either an array or a File-Handle in <b>/usr/local/src/drush/includes/startup.inc</b> on line <b>366</b><br />
> PHP Warning:  proc_get_status() expects parameter 1 to be resource, boolean given in /usr/local/src/drush/includes/startup.inc on line 367
> <br />
> <b>Warning</b>:  proc_get_status() expects parameter 1 to be resource, boolean given in <b>/usr/local/src/drush/includes/startup.inc</b> on line <b>367</b><br />
> PHP Warning:  proc_close() expects parameter 1 to be resource, boolean given in /usr/local/src/drush/includes/startup.inc on line 368
> <br />
> <b>Warning</b>:  proc_close() expects parameter 1 to be resource, boolean given in <b>/usr/local/src/drush/includes/startup.inc</b> on line <b>368</b><br />
> 

If I do the following, it seems the commands do run, but with a lot of warnings.

`/usr/local/bin/php /usr/local/src/drush/drush.php COMMAND ARG --opt=something`

Warnings like:
> <b>Notice</b>:  Use of undefined constant STDERR - assumed 'STDERR' in <b>/usr/local/src/drush/includes/backend.inc</b> on line <b>224</b><br />
> <br />
> <b>Warning</b>:  fwrite() expects parameter 1 to be resource, string given in <b>/usr/local/src/drush/includes/backend.inc</b> on line <b>224</b><br />

Drush status (redacted):

```
 Drupal version                  :  7.44                                                                
 Site URI                        :  something.nl                                                  
 Database driver                 :  mysql                                                               
 Database hostname               :  localhost                                                           
 Database port                   :                                                                      
 Database username               :  cred                                                          
 Database name                   :  db                                                            
 Drupal bootstrap                :  Successful                                                          
 Drupal user                     :                                                                      
 Default theme                   :  something                                                                 
 Administration theme            :  seven                                                               
 PHP configuration               :  /usr/local/lib/php.ini                                              
 PHP OS                          :  Linux                                                               
 Drush script                    :  /usr/local/src/drush/drush.php                                      
 Drush version                   :  8.0.5                                                               
 Drush temp directory            :  /tmp                                                                
 Drush configuration             :  /home/user/site/docroot/sites/all/drush/drushrc.php             
 Drush alias files               :  /home/user/site/docroot/sites/all/drush/nvj.aliases.drushrc.php 
 Install profile                 :  minimal                                                             
 Drupal root                     :  /home/user/site/docroot                                         
 Drupal Settings File            :  sites/some/settings.php                                              
 Site path                       :  sites/some                                                           
 File directory path             :  sites/some/files                                                     
 Private file directory path     :  ../private_files                                                    
 Temporary file directory path   :  /tmp   
```

**Comment by RobinCee** [comment]
The problem with Cpanel:

Use of undefined constant STDERR / fwrite() expects parameter 1 to be resource, string given in etc etc

Whatever you do, it seems like Drush & Cpanel always use the cgi when executed via cron, or worse: the default php version (and that has cli disabled and falls back to cgi without a notice)

Also: .bashrc is not loaded when executing cron, so setting DRUSH_PHP there won't fix this.

/usr/bin/php -v
/usr/local/bin/php -v
compare the output.

What happens:
drush.launcher tests for env var DRUSH_PHP, if not set, (on *ux) it tests with  'which php-cli'
And on Cpanel that does not exist, it's named php5-cli for one.
I first tried a symlink to the actual php version i want to use (72), but that also does not seem to work.

Back to cron:
All scripts use #!/usr/bin/env php, but when called via cron, on Cpanel this leads to the cgi version !

Try it yourself:
crontab -e
Add this line:
*/1 * * * *  /usr/bin/env php -v | /usr/bin/logger
Then: tail -f /var/log/messages

And voila! The problem exposed.

What does seem to work: a simple script (or one-liner, but to be clear, export DRUSH_PHP before calling drush works)
`#!/bin/bash

# Define php version to use.
DRUSH_PHP=/usr/local/bin/php; export DRUSH_PHP;

# Call elysia.
/path/to/bin/drush @site elysia-cron run --debug 2>&1 | /usr/bin/logger -t drush_cron_for_site
`
Also: try a drush cc drush when you first attempt this, it helps.

Note: i executed all this ^^ as the site's user (except for the tail -f /var/log/messages)
(And to get the complete output, edit /etc/rsyslog.conf, set $SystemLogRateLimitBurst 500 and restart rsyslog)

Possible TODO: add some bits n pieces to the docs? this page: http://docs.drush.org/en/master/cron/#running-drupal-cron-tasks-from-drush

I believe a small paragraph about DRUSH_PHP and php-cgi could be added there. (It seems to work, but you need to dig a lil, cpanel silently falling back to cgi is an issue, put a broken drush cache on top of that and then try to debug.)

http://docs.drush.org/en/master/search.html?q=DRUSH_PHP returns nothing, so TODO?

**Comment by RobinCee** [comment]
@greg-1-anderson thanks, i know this, but it's documented only in code, issue queues, etc. Figured it might not hurt to add this to the manual (found multiple people asking the same question), but ok.

**Comment by greg-1-anderson** [comment]
Documentation PRs welcome.
