### ISSUE TITLE
Reporting drush issue on WSL

### ISSUE THREAD

**Issue by Benosika** [drush-ops/drush#2243]
[I have installed drush on WSL successfully as described here](http://drupal.stackexchange.com/questions/204842/installing-drush-on-wsl). After installing I navigated `/mnt/c/wamp64/www/yoursitesname` .

Whenever I run a drush command on a site's folder I get the following error:

    PHP Fatal error: Undefined class constant 'MYSQL_ATTR_SSL_CA' in phar:///usr/local/bin/drush/lib/Drush/Sql/Sqlmysql.php on line 56

    Drush command terminated abnormally due to an unrecoverable error.

It is interesting to note that when I do `drush status` outside the sites' folder (and even in c: in the Windows partition, all seems just fine.

This is a bit wired as I understand that the error is common only in some cases when drushing while in SSH - I don't use SSH in this case.

System details (WAMP64bit):

PHP 5.6.16, MySQL 5.7.9, Drush 8.1.2, Drupal 7.44, WSL-Ubuntu 14.04 LTR.

**Comment by weitzman** [comment]
Please show out `php -i`. Think you dont have pdo support  or pdo+mysql in your PHP.
