### ISSUE TITLE
drush cc all ends in segmentation fault

### ISSUE THREAD

**Issue by vlieder79** [drush-ops/drush#2256]
Hi List,
we have a customer, installed Drupal 7.41 on a debian jessie with PHP 5.6.22-0+deb8u1 and apache 2.4.20-1. If we use drush in command line to clear the cache "drush cc all" within the document root, all new request from our webbrowser ends in a segmentation fault from apache.
I have read about issues with .info files, but we dont find a directory such as node_modules, which is described in many other posts. 
For testing we tried the following:
make a backup from sql database
use command "drush cc all"
Website not responding with segmentation faults
If we start to restore sql database, the site is running again.
At the moment we cant see what happens within the "drush cc all" command and why the site is available directly while we starting the restore of the database.

drush -v cc all -d
Bootstrap to phase 0. [0.01 sec, 1.71 MB]                            [bootstrap]
Drush bootstrap phase : _drush_bootstrap_drush() [0.01 sec, 1.83 MB] [bootstrap]
Cache MISS cid: 5.10.0-commandfiles-0-91aaea6decf1eee0e60c3d87cbd612ef [0.03 sec, 1.84 MB]                                                                      [debug]
Cache SET cid: 5.10.0-commandfiles-0-91aaea6decf1eee0e60c3d87cbd612ef [0.04 sec, 1.86 MB]                                                                       [debug]
Bootstrap to phase 0. [0.07 sec, 4.31 MB]                                                                                                                   [bootstrap]
Drush bootstrap phase : _drush_bootstrap_drupal_root() [0.08 sec, 4.32 MB]                                                                                  [bootstrap]
Initialized Drupal 7.41 root directory at /var/www/staging.domain.de [0.1 sec, 5.16 MB]                                                          [notice]
Drush bootstrap phase : _drush_bootstrap_drupal_site() [0.1 sec, 5.16 MB]                                                                                   [bootstrap]
Initialized Drupal site default at sites/default [0.1 sec, 5.16 MB]                                                                                            [notice]
Cache MISS cid: 5.10.0-commandfiles-2-c32acd775c18a90c5b41d0fc9accf5ab [0.11 sec, 5.17 MB]                                                                      [debug]
Cache SET cid: 5.10.0-commandfiles-2-c32acd775c18a90c5b41d0fc9accf5ab [0.12 sec, 5.17 MB]                                                                       [debug]
Drush bootstrap phase : _drush_bootstrap_drupal_configuration() [0.12 sec, 5.17 MB]                                                                         [bootstrap]
Drush bootstrap phase : _drush_bootstrap_drupal_database() [0.12 sec, 5.18 MB]                                                                              [bootstrap]
Successfully connected to the Drupal database. [0.13 sec, 5.18 MB]                                                                                          [bootstrap]
Drush bootstrap phase : _drush_bootstrap_drupal_full() [0.13 sec, 5.69 MB]                                                                                  [bootstrap]
Cache MISS cid: 5.10.0-commandfiles-5-e17eb818e68d5371f0fac02ddcbc4417 [0.47 sec, 32.31 MB]                                                                     [debug]
Cache SET cid: 5.10.0-commandfiles-5-e17eb818e68d5371f0fac02ddcbc4417 [0.54 sec, 32.33 MB]                                                                      [debug]
Drush bootstrap phase : _drush_bootstrap_drupal_login() [0.55 sec, 33.18 MB]                                                                                [bootstrap]
Successfully logged into Drupal as Gast (uid=0) [0.56 sec, 33.19 MB]                                                                                        [bootstrap]
Found command: cache-clear (commandfile=cache) [0.56 sec, 33.19 MB]                                                                                         [bootstrap]
Calling drush_cache_clear_both() [0.65 sec, 33.91 MB]                                                                                                           [debug]
'all' cache was cleared in /var/www/staging.domain.de#default [5.49 sec, 62.08 MB]                                                            [success]
Command dispatch complete [5.5 sec, 62.02 MB]                                                                                                                  [notice]
 Timer  Cum (sec)  Count  Avg (msec)
 page   5.374      1      5373.76

Peak memory usage was 88.28 MB [5.5 sec, 62.02 MB]                                                                                                             [memory]

We tried drush from repository (5.10.0-2) and from git  (drush-6.4.0).
Any ideas or hints what we can check?
opcache and apc is disabled at the moment.
Regards,
Volker

**Comment by weitzman** [comment]
Not likely caused by Drush
