### ISSUE TITLE
Disable Cron during Drush request (D8)

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#2258]
I encountered this issue when was running [Drupal REPL](https://github.com/Chi-teck/docker-drupal-repl) container.

Looks like it is disabled in Drupal 7 only.
https://github.com/drush-ops/drush/blob/7f59c15d18daff5552f00c2c6ea9c57fc5a1c6b4/lib/Drush/Boot/DrupalBoot.php#L454

**Comment by damiankloip** [comment]
Yes, I have been meaning to look into this!
