### ISSUE TITLE
There is no documented way to suppress warnings about missing 4 byte UTF-8 support

### ISSUE THREAD

**Issue by stefanruijsenaars** [drush-ops/drush#2270]
See https://www.drupal.org/node/2764757

**Comment by cilefen** [comment]
REQUIREMENT_INFO Does not usually show up as drush warning. Is something else going on here?

**Comment by weitzman** [comment]
There is no "warning". Drupal is emitting an INFO statement, and Drush is faithfully reporting it as INFO. Are you seeing this on all Drush requests, or just core-requirements command?  Could you paste the troublesome Drush output?

**Comment by cilefen** [comment]
`drush updatedb
4 byte UTF-8 for mysql is disabled. See the documentation on adding 4 byte UTF-8 support for more information. (Currently using Database 4[warning]
byte UTF-8 support Disabled)
No database updates required`

**Comment by cilefen** [comment]
And that is a [warning].

**Comment by nicholas12345** [comment]
I did update to Drush version 8.1.2 and I still see this message, so it is not fixed for me.

**Comment by weitzman** [comment]
Drush has not made a new release yet. Soon.

**Comment by capfive** [comment]
Has this been updated yet? quite an annoying message, or is there a way in the meantime to fix it?
