### ISSUE TITLE
conflicting drush aliases.  how to fix/prevent?

### ISSUE THREAD

**Issue by user58258** [drush-ops/drush#2273]
In my Drupal8 + drush install, I notice that there are two '(cr)' aliases: 

    cache-rebuild (cr)

from 'cache' module, &

    cron-run (cr)

from ultimate-cron module. (https://github.com/md-systems/ultimate_cron/blob/8.x-2.x/ultimate_cron.drush.inc#L85)

Exec'ing 

    drush cr

executes only

    drush cache-rebuild

What's the correct way to get rid of this conflict?  Or, detect & prevent it in the first place?

Does this cause any actual problem? Or should we just avoid using the aliases and use the full commands?

**Comment by weitzman** [comment]
The usual way is for core Drush to take precendence with alias names. ultimate cron should rename or remove their alias.

**Comment by user58258** [comment]
@berdir

**Comment by Berdir** [comment]
Patches against ultimate_cron are welcome to remove the alias or change it. Overlooked this when committing that patch recently. Also not that the you can user drush core-cron in 8.x, works fine with UR as well.

I think this can be closed.
