### ISSUE TITLE
`drush cex -y --skip-modules=devel` still results in devel.settings.yml

### ISSUE THREAD

**Issue by rachellawson** [drush-ops/drush#2276]
When working with config export on Drupal 8, it becomes increasingly essential to ensure an exported configuration does not include modules used only in development.

The --skip-modules= switch does an excellent job of ensuring that the created core.extensions.yml file does not include the modules listed BUT any configuration yml files those module might create ARE still created.

If this is then used in a `drush cim -y` then the import will fail as there will be imports to make for modules that are not enabled.

**Comment by rachellawson** [comment]
Drush version 8.1.2

**Comment by weitzman** [comment]
Dupe. Can't search right now. Help wanted.

**Comment by rachellawson** [comment]
It’s a duplicate of #1820.

Sorry, I didn’t go back far enough when I looked!
