### ISSUE TITLE
Drush pm-download puts drush commands in wrong location.

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#2277]
I suppose this was introduced by the following commit dd7e013605dc.
> A module is a pure drush command if it has no .info.yml and contain  .drush.inc files.

This assumption is not correct. Many drush related modules contain info file. I faced this problem when installing [Site Audit](https://www.drupal.org/project/site_audit) drush command.
I just checked first 10 projects from [this list](https://www.drupal.org/node/2767439) and found 3 projects that do have info file. That means about 30% projects of that list will be downloaded to a wrong location.

**Comment by weitzman** [comment]
Site audit looks like a regular Drupal module with drush integration (via a symfony console command). I looked at its 8.3 branch.

**Comment by Chi-teck** [comment]
> That means about 30% projects of that list will be downloaded to a wrong location.

More precisely 35.6 % in the Drupal 7 codebase. I just found them all with the following snippet:

```bash
#! /bin/bash

for directory in * ; do
  if [ ! "$(find $directory -name *.module)" ] && [ "$(find $directory -name *.info)" ] && [ "$(find $directory -name *.drush.inc)" ]; then
    url=https://www.drupal.org/project/$directory
    title=$(wget --quiet -O - $url  | sed -n -e 's!.*<h1 id="page-subtitle">\(.*\)</h1>.*!\1!p')
    echo "[$title]($url)"
  fi
done
```

Output:

1. [apachesolr_reindex](https://www.drupal.org/project/apachesolr_reindex)
2. [Configuration Manager](https://www.drupal.org/project/cfgmgr)
3. [Composer Generate](https://www.drupal.org/project/composer_generate)
4. [Drush dpkg](https://www.drupal.org/project/dpkg)
5. [Drush](https://www.drupal.org/project/drush)
6. [Drush clone](https://www.drupal.org/project/drush_clone)
7. [Drush Compass](https://www.drupal.org/project/drush_compass)
8. [Drush Download File](https://www.drupal.org/project/drush_dlf)
9. [Drush extras](https://www.drupal.org/project/drush_extras)
10. [Drush grant RID](https://www.drupal.org/project/drush_grant_rid)
11. [drushify](https://www.drupal.org/project/drushify)
12. [Drush Issue Queue Commands](https://www.drupal.org/project/drush_iq)
13. [Drush IQ Extras](https://www.drupal.org/project/drush_iq_extras)
14. [Drush Mandrill Statistics](https://www.drupal.org/project/drush_mandrill_stats)
15. [Drush Migrate Inspect](https://www.drupal.org/project/drush_migrate_inspect)
16. [Drush Modulesmith](https://www.drupal.org/project/drush_modulesmith)
17. [Drush Permissions](https://www.drupal.org/project/drush_permissions)
18. [Drush Queue](https://www.drupal.org/project/drush_queue)
19. [Drush Recipes](https://www.drupal.org/project/drush_recipes)
20. [Drush SQL Sync Pipe](https://www.drupal.org/project/drush_sql_sync_pipe)
21. [Drush Symlinks](https://www.drupal.org/project/drush_symlinks)
22. [Drush Taxonomyinfo](https://www.drupal.org/project/drush_taxonomyinfo)
23. [Drush Typeinfo](https://www.drupal.org/project/drush_typeinfo)
24. [File permissions](https://www.drupal.org/project/file_permissions)
25. [Git Release Notes for Drush](https://www.drupal.org/project/grn)
26. [Instaweb](https://www.drupal.org/project/instaweb)
27. [Locale Import/Export](https://www.drupal.org/project/locale_import_export)
28. [MAMP](https://www.drupal.org/project/mamp)
29. [Hard-working Monkey](https://www.drupal.org/project/monkey)
30. [PHP Server](https://www.drupal.org/project/php_server)
31. [Privatize](https://www.drupal.org/project/privatize)
32. [Project Status](https://www.drupal.org/project/project_status)
33. [Provision](https://www.drupal.org/project/provision)
34. [Provision ACL support](https://www.drupal.org/project/provisionacl)
35. [Provision boost support](https://www.drupal.org/project/provision_boost)
36. [Provision Cloud Files](https://www.drupal.org/project/provision_cloud_files)
37. [Provision Git Features](https://www.drupal.org/project/provision_git_features)
38. [Provision hosting injections](https://www.drupal.org/project/provision_hosting_injections)
39. [Drush Refactor Project](https://www.drupal.org/project/refactor_project)
40. [Rush](https://www.drupal.org/project/rush)
41. [Drush Search &amp; Replace](https://www.drupal.org/project/sar)
42. [Sensitive Data](https://www.drupal.org/project/sensitive_data)
43. [Settings.php generator](https://www.drupal.org/project/settingsphp)
44. [Site Audit](https://www.drupal.org/project/site_audit)
45. [Surf](https://www.drupal.org/project/surf)
46. [Turnip](https://www.drupal.org/project/turnip)
47. [Valkyrie](https://www.drupal.org/project/valkyrie)

**Comment by weitzman** [comment]
I think my intent in that commit was to change behavior for D8+ only. So, we have a bug.

**Comment by weitzman** [comment]
Thanks @Chi-teck for the link to the ill commit and for the command listing. Hope I got it right this time.
