### ISSUE TITLE
drush config-import doesn't create field tables in DB

### ISSUE THREAD

**Issue by MatthieuScarset** [drush-ops/drush#2278]
Hi 

### Main site
- create a new site with the standard profile named "Main site"
- create a custom content type named "Test"
- create two custom fields named "Test" (text field) and "Test date" (date field)
- export the configuration in `sync` folder
- grab the site UUID `drush cget"system.site" uuid`

### Clone site
- create a new site with the standard profile named "Clone site"
- set the UUID to match Main site `drush cget"system.site" uuid <uuidvalue_grabbed_from_mainsite>`
- copy the `sync` folder from Main site to Clone site
- try to import the configuration `drush cim`

Everything seems to be working fine, as you see in the console output:
```
drush cim
Choose a source.
 [0]  :  Cancel
 [1]  :  staging
 [2]  :  sync
2
 Collection  Config                                      Operation              
             field.storage.node.field_test_date          create
             field.storage.node.field_test               create
             node.type.test                              create
             field.field.node.test.field_test_date       create
             field.field.node.test.field_test            create
             field.field.node.test.body                  create
             core.entity_form_display.node.test.default  create
             core.entity_view_display.node.test.teaser   create
             core.entity_view_display.node.test.default  create
             field.field.node.test.field_test            delete
             field.field.node.test.field_test_date       delete
             field.field.node.test.field_test_email      delete
Import the listed configuration changes? (y/n): y
Cache rebuild complete.                                                                                      [ok]
The configuration was imported successfully.                                                                 [success]
```

But **this simple export/import operation doesn't work.** 

Content type is imported but **Fields are not created in database**.

**Comment by MatthieuScarset** [comment]
Hi, 

I'm using 8.1.6 

Here's the full details of `drush core-status`:
` Drupal version                  :  8.1.6`
` Site URI                        :  http://default`
` Database driver                 :  mysql`
` Database hostname               :  127.0.0.1`
` Database port                   :  33067`
` Database username               :  drupaluser`
` Database name                   :  database`
` Drupal bootstrap                :  Successful`
` Drupal user                     :`
` Default theme                   :  bartik`
` Administration theme            :  seven`
` PHP executable                  :  php.exe`
` PHP configuration               :  C:\tools\devdesktop\php5_5\php.ini`
` PHP OS                          :  WINNT`
` Drush script                    :  C:\tools\devdesktop\drush\vendor\drush\drush\drush.php`
` Drush version                   :  8.0.5`
` Drush temp directory            :  D:\Users\mscarset\AppData\Local\Temp`
` Drush configuration             :  C:\tools\devdesktop\drush\vendor\drush\drush\drushrc.php`
` Drush alias files               :  D:\Users\mscarset/.acquia/DevDesktop/Drush/Aliases/aliases.drushrc.php`
` Install profile                 :  standard`
` Drupal root                     :  D:\devdesktop\cmne`
` Drupal Settings File            :  sites/default/settings.php`
` Site path                       :  sites/default`
` File directory path             :  sites/default/files`
` Temporary file directory path   :  c:\windows\temp`
` Sync config path                :  sync`

**Comment by weitzman** [comment]
Your Drush is too old.

**Comment by MatthieuScarset** [comment]
Ho... you're right. 
It's still 8.0.5, sorry.

My Drush is the one bundled with Acquia DevDesktop.

I've set the version to be 8.1.2 in its composer.json but it seems that it didn't updated correctly.

Thank you anyway.
