### ISSUE TITLE
drush core-execute does not handle options correctly

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#2281]
`drush exec` command does not work if its options overlap with global ones
Examples:
`drush exec ls -l` works fine.
`drush exec ls -lh` doesn't work because -h is registered global option (help).
`drush exec "ls -lh"` does't work by some reason.

**Comment by weitzman** [comment]
Is it just 'h; thats a problem? That one is special in that it is read and acted upon very early.

**Comment by Chi-teck** [comment]
Well `drush exec du -d 0` prints some debug information.

**Comment by Chi-teck** [comment]
> drush exec "ls -lh" does't work by some reason.

With newer "ssh" command wrapping command into quotes fixes the problem.

I think it makes sens to make the code argument accept only one value.
