### ISSUE TITLE
Provide documentation to install/update drush securely.

### ISSUE THREAD

**Issue by zoredache** [drush-ops/drush#2284]
At the moment the [install documentation](http://docs.drush.org/en/master/install/) instructs you to download the file `http://files.drush.org/drush.phar`, then run it.  This file is transferred over an un-encrypted link and there doesn't appear to be any documented method to validate that the file I downloaded was valid.

**Comment by weitzman** [comment]
Duplicate ... Download from Github release. Feel free to submit a docs PR.
