### ISSUE TITLE
Updating drush with composer doesn't seem to update

### ISSUE THREAD

**Issue by jc4141** [drush-ops/drush#2290]
I have drush 8.0.5 on my machine (I'm using DAMP on Windows 7).  I ran to following command to update:

`composer global require drush/drush:8.1.3`

Install indicated it was successful.  However, my version of drush is still at 8.0.5.  Further attempts to run the above command give result "Nothing to install or update".  I updated composer to latest version and it made no difference.  

Am I missing something?

**Comment by greg-1-anderson** [comment]
Do you have a copy of Drush in your Drupal site?  This will happen for you automatically if you use the drupal-composer/drupal-project template, for example.  In this instance, Drush will redispatch to the site-local Drush.  You will therefore need to run `composer require` or `composer update` on the Drupal site.
