### ISSUE TITLE
Return a valid error code when an error happens

### ISSUE THREAD

**Issue by Artusamak** [drush-ops/drush#2295]
Hello, thank you for your work with drush.
I ran a search query without finding a matching issue, sorry if it's a duplicate.

When drush is running with Jenkins for instance, it happens to have an error and the script keeps running. My guess is that the wrong return code is sent. Do we have an option to have errors returning the -1 return codes?
Example is below, a PHP Fatal error happens and the script keeps running, preventing jenkins to catch the error and notify the builder.

```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /.../www/sites/all/modules/contrib/rules/rules.module on line 1099
Drush command terminated abnormally due to an unrecoverable error.       [error]
Error: Allowed memory size of 134217728 bytes exhausted (tried to
allocate 20480 bytes) in
/.../www/sites/all/modules/contrib/rules/rules.module,
line 1099
//../www/../scripts/update.sh: line 41: 25872 Segmentation fault      
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: SUCCESS
```

Thank you for your help.

**Comment by greg-1-anderson** [comment]
What is the exact Drush command that is failing?

**Comment by Artusamak** [comment]
It was a drush features-revert.

Le 26 juil. 2016 10:32 PM, "Greg Anderson" <notifications@github.com> a
écrit :

**Comment by morsok** [comment]
We are having the same issue with other commands, sometimes there is an exeption (in a migration for example) and drush doesn't exit with -1 at the end so ansible doesn't know something went wrong and jenkins says all is ok.

**Comment by greg-1-anderson** [comment]
When I triggered a forced `Drush command terminated abnormally` error, my result was that $? was set to 1.  More information is needed on the code path being followed in the failure scenarios you are encountering.  Also, please make sure you are using a recent version of Drush (Drush 8 recommended).

**Comment by Artusamak** [comment]
OK problem sovled.

Here is the situation. The drush command are run from a bash script. This bash script is processed when a Jenkins job is triggered.
Now, the important part. The bash script must have the -e flag set otherwise the Jenkins job doesn't interpret the error code.
Several points to know about Jenkins error codes are resumed here: http://stackoverflow.com/a/22816074

So after returning properly the error code and catching the error code, the builds are failing properly!

Thank you Greg for the feedback and support.
