### ISSUE TITLE
Drush make: Unable to clone error

### ISSUE THREAD

**Issue by ghost** [drush-ops/drush#23]
We use drush (5.9) make to build a production site. It seems to work without issue for weeks at a time, then suddenly drush make will start throwing the error "Unable to clone [name_of_repo] from git@[repo url].git". It can download anything in the make file as http, but fails on git.

The only way we can fix this is by downgrading the drush version. Then, when it happens again, we fix it by upgrading, etc. Not an ideal fix, but a temporary solution.

In the meantime we have not changed the version of drush -- is drush updating itself in the background? And moreso, what is causing the git clone errors?

When we encounter this error, I verify that I can clone the repos independently of drush make.

**Comment by drzraf** [comment]
I can confirm this bug:
using 7.0-dev, drush make can clone a git@... repository.
using 8.0.1, it's no more possible (https works anyway, but sadly it does not relies upon ssh-agent)

worth reopening

**Comment by ergonlogic** [comment]
@drzraf Would you mind opening a new issue? Ideally, include an example makefile.
