### ISSUE TITLE
After recent update drush is now showing [notice] output in console

### ISSUE THREAD

**Issue by tanc** [drush-ops/drush#2304]
I just updated drush version 9.0-dev and I'm now seeing some [notice] messages where I didn't before.

These messages are from a custom drush command we're using to handle our aliases. The difference is that they didn't used to show so I was wondering if there is a way to suppress messages of a certain type?

**Comment by weitzman** [comment]
You can not show any stderr messages by redirecting that stream. Or try --quiet to see if it helps? Not sure if there are any other options.

**Comment by helderco** [comment]
A notice saying "Cron run completed" should go out to stderr. I don't want to suppress stderr because I still want to be notified if real errors come up. Why doesn't "-q" work anymore?
