### ISSUE TITLE
Required password should be argument in user-password command

### ISSUE THREAD

**Issue by colans** [drush-ops/drush#2306]
```
colan@snake[Fri 5 13:31]% drush upwd colan                                                                                                                  
Missing required option: --password.  [...]
```

By definition, options aren't required.  Is there a good reason why the password here is an option, and not an argument?  If not, we should switch this around, making it so.

**Comment by weitzman** [comment]
Will be fixed in drush9 by #2458. Cant change drush8 IMO.
