### ISSUE TITLE
drush pm-update to 8.1.8 replace /vendor

### ISSUE THREAD

**Issue by didiermisson** [drush-ops/drush#2307]
Hello

I first open this issue
https://www.drupal.org/node/2779713
## But seem to be a drush problem

We upgrade from D8.1.7 to 8.1.8, with drush :

```

drush pm-refresh
drush pm-update
```

Now, white page. Site is blocked.
Seem to be link with Address module.
Same error with drush :

```
# drush version
 Drush Version   :  8.1.3 


# drush status
PHP Fatal error:  Trait 'CommerceGuys\Addressing\Model\FormatStringTrait' not found in /home/mysite/public_html/modules/address/src/Entity/AddressFormat.php on line 60
Drush command terminated abnormally due to an unrecoverable error.                                     [error]
Error: Trait 'CommerceGuys\Addressing\Model\FormatStringTrait' not found in
/home/mysite/public_html/modules/address/src/Entity/AddressFormat.php, line 60
Drush was not able to start (bootstrap) Drupal.                                                        [error]
Hint: This error can only occur once the database connection has already been successfully initiated,
therefore this error generally points to a site configuration issue, and not a problem connecting to
the database.

Drush was attempting to connect to: 
 Drupal version                  :  8.1.8                                                             
 Site URI                        :  http://default                                                    
 Database driver                 :  mysql                                                             
 Database hostname               :  localhost                                                         
 Database port                   :  3306                                                              
 Database username               :  mysite                                                          
 Database name                   :  mysite                                                          
 Default theme                   :  startupgrowth                                                     
 Administration theme            :  seven                                                             
 PHP executable                  :  /usr/bin/php                                                      
 PHP configuration               :  /etc/php/7.0/cli/php.ini                                          
 PHP OS                          :  Linux                                                             
 Drush script                    :  /root/vendor/drush/drush/drush.php                                
 Drush version                   :  8.1.3                                                             
 Drush temp directory            :  /tmp                                                              
 Drush configuration             :                                                                    
 Drush alias files               :                                                                    
 Install profile                 :  standard                                                          
 Drupal root                     :  /home/mysite/public_html                                        
 Drupal Settings File            :  sites/default/settings.php                                        
 Site path                       :  sites/default                                                     
 File directory path             :  sites/default/files                                               
 Temporary file directory path   :  sites/default/files/tmp                                           
 Sync config path                :  sites/default/files/config_ytJkemDKhITNR7PdsbBU003XjBey2ZZxwKQkXX 
                                    cg6A5byRdUFDBzuF0Rwvt0Vi89DeORZzX_Yw/sync 
```

Seem that drush replace the vendor folder ?

I was thinking I can use drush without problem...
It was always ok before this 8.1.8 upgrade.

Thanks.
Didier

**Comment by weitzman** [comment]
Perhaps we can avoid this in Drush, but really you should not be using pm-updatecode or pm-update anymore. Just use Composer to build and update your whole site, including Drupal core.

**Comment by didiermisson** [comment]
Hello Weitzamn

hum... ok...
We will begin to learn more about Composer.

But Drush was so easy, when compare to Composer...
And surprise that Drush make problem : nowhere it's officially say "avoid Drush ! "
;-)

Thanks.
Didier

**Comment by weitzman** [comment]
The PHP community chose to follow most other languages and embrace dependency management. See NPM or Gem for ruby. Not much Drush can or should do about that. Make is obsolete, pm-updatecode is obsolete. Time to get your learning on!

**Comment by weitzman** [comment]
FYI, it is officially said "Dont use Drush" when you build your site on drupal-project. [See the policy file](https://github.com/drupal-composer/drupal-project/blob/8.x/drush/policy.drush.inc). We will eventually deprecate this functionality in Drush but still contemplating how.

**Comment by didiermisson** [comment]
"_Encourage folks to use `composer` instead of Drush pm commands_"

Sad that the command always run, but destroy some D8 site...

Problem is that some users simply used drush... and don't go on GitHub, or don't look inside the Drush code.... and don't see this warning msg.

Ok, thanks a lot.
We REALLY need to learn more about Composer and Drupal.
;-)

**Comment by didiermisson** [comment]
"_The PHP community chose to follow most other languages and embrace dependency management. See NPM or Gem for ruby. Not much Drush can or should do about that. Make is obsolete, dl is obsolete, pm-updatecode is obsolete. Time to get your learning on!_ "

I understand this !
NPM
Composer
...

Drush is a limited tool for Drupal only... 
Composer is a global tool for any PHP scripts, so better to follow Composer.

Ok, we will go to Composer.

**Comment by greg-1-anderson** [comment]
Nothing more to do here.
