### ISSUE TITLE
"drush cache-rebuild" issue with localization/plugin cache

### ISSUE THREAD

**Issue by ividyon** [drush-ops/drush#2316]
I have a Drupal 8 site with a German localization set up.

When I clear my site's caches using `drush cache-rebuild`, a lot of the German translations for strings will disappear.

Rebuilding the cache again via the "Flush all caches" menu item in the `admin_toolbar` module restores the translations.

The translations also reappear if I only flush the "plugin cache" via the same module.

`admin_toolbar`'s "flush all caches" callback simply executes the function `drupal_flush_all_caches()`.
The "Flush plugin cache" callback executes the following line:
`\Drupal::service('plugin.cache_clearer')->clearCachedDefinitions();`

I therefore managed to properly rebuild the caches via Drush by performing the following:

`drush cr; drush php-eval "\Drupal::service('plugin.cache_clearer')->clearCachedDefinitions();"`

Is this a Drush issue or a core issue? Shouldn't the `drush cr` command perform the same as the cache flush in the interface? DrupalConsole's rebuild faces the same problem.

**Comment by weitzman** [comment]
Drush just runs core's cache rebuild. Doubt its Drush issue.
