### ISSUE TITLE
drush fr needs the following extension(s) enabled to run: features

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#2317]
This is happening quiet often on the VM where the drush is installed.

```
$ drush -y fr foo_submission
 [error]  Command fr needs the following extension(s) enabled to run: features. 
 [error]  The drush command 'fr foo_submission' could not be executed. 
$ drush pm-list | grep features
 Features  Features (features)  Module  Enabled        7.x-2.10              
$ drush -y en features
 [notice] features is already enabled.
$ drush --version
 Drush Version   :  9.0-dev 
$ drush cc drush
 [notice] 'drush' cache was cleared.
# Then it works, but I don't know for how long.
```

After clearing the cache via 'cc drush' (as 'cc all' doesn't help), it works for some time, but it breaks again after some time (probably after reprovisioning). I'm using memcached. I don't have clear reproduction steps to demonstrate. When switching git branches, features module is always there, so it's rather something to do with drush or caching.

Related: #79

**Comment by weitzman** [comment]
Perhaps #79 is back on master branch. Maybe move to 8.x branch and see if that fixes it.

**Comment by djouuuuh** [comment]
:+1: Same issue here. Interested in future comments.

**Comment by geerlingguy** [comment]
We've been running into this on Acquia Cloud sometimes, running Drush 8.1.3... it seems to only affect `migrate`-related commands, like `drush mi [migration]`, while other drush commands work.

If we run `drush cc drush && drush mi [migration]` it works.

**Comment by wouters-frederik** [comment]
Also seeing this with other commands...
`drush csim --split=live_split -y`
or 
`drush customdrushcommand`

**Comment by longwave** [comment]
Also running into this from time to time, usually after an `updb` even if there were no updates required, and it happened again today:

```
$ drush updb -y && drush fra -y && drush cc all
No database updates required
Command fra needs the following extension(s) enabled to run: features.
The drush command 'fra' could not be executed.

$ drush cc all && drush fra -y && drush cc all
'all' cache was cleared.
The following modules will be reverted: [redacted]
Do you really want to continue? (y/n): y
Reverted [redacted].hierarchical_select.
Reverted [redacted].field_instance.
Reverted [redacted].field_instance.
Reverted [redacted].filter.
Reverted [redacted].field_instance.
Reverted [redacted].search_api_server.
'all' cache was cleared.

$ drush --version
 Drush Version   :  8.1.10 
```

Not sure what the trigger is, as it seems to come and go from different sites, there is an annoying lack of consistency with this bug!

**Comment by weitzman** [comment]
Please use latest release of drush8 or drush9 and post here if still broken.

**Comment by jfayad** [comment]
Hello,

I have a custom drush command and I noticed this random behaviour occurring with this command.

All commands are being executed on a newly created website (I use Aegir) from a script so I'm sure all the commands are always executed in the same order.

I'm also systematically executing a `drush @site_alias cc drush` to supposedly avoid such issues, yet I'm still facing this _drush needs the following extension(s) to run..._ randomly.

I can see only one factor that might interfere here: Do I have other drush commands running on the system in //.

```
drush --version
 Drush Version   :  8.1.15-dev 
```

**Comment by weitzman** [comment]
Please use Drupal Answers for support questions.

**Comment by jfayad** [comment]
Well it is not really a support question.  You said on oct 3 (though to another person) to post here if still broken with the latest release. As you can see I'm using the lattest release and it seems to be still random...

Unless you consider that because this is happening with a custom command it qualifies as a support question... I think this is related to the above mentioned error (given the command works I doubt it's an issue with the hook implementations etc...).

Thanks

**Comment by glassdimly** [comment]
I was getting this error on Drupal 7 sites running php 7.1 (drush not recognizing that features was installed). I switched to php 5.6 and this was resolved for me.

**Comment by acrolink** [comment]
This solves the issue for me: `drush cc drush`
