### ISSUE TITLE
Default database prefix (other database name) not supported on Database Bootstrap step

### ISSUE THREAD

**Issue by smalot** [drush-ops/drush#2329]
When used in multisite setup, the `drush cc all` is not able to work if prefix are used to mutualize tables.
In fact, the `database` bootstrap step is not able to detect the `blocked_ips` table because either not correctly named neither not in the current database.

``` sql
$databases = array (
  'default' =>
  array (
    'default' =>
    array (
      'database' => 'database__fr',
      'username' => 'username',
      'password' => 'password',
      'host' => 'localhost',
      'port' => '',
      'driver' => 'mysql',
      'prefix' => array(
        'default'  => 'database__fr.',
        'authmap'  => 'database__common.',
        'blocked_ips'  => 'database__common.',
        'role'     => 'database__common.',
        'sessions' => 'database__common.',
        'users'    => 'database__common.',
      ),
    ),
  ),
);

```

Instead of listing all tables of the database, it should be better to create a light select to detect the table existance.

``` sql
SELECT COUNT(1) FROM {blocked_ips}
```

Like that, the prefix will be correctly used.

**Comment by smalot** [comment]
The concerned method is this one:

````php
\Drush\Boot\DrupalBoot::bootstrap_drupal_database_has_table();
````

**Comment by da70** [comment]
We have also been hit by this.  Recently we linked 6 Drupal sites into a shared configuration using the same method, and also traced the problem to `bootstrap_drupal_database_has_table`.  We have been forced to downgrade to Drush 6.

According to [current Drupal 7.x drupal/sites/default/default.settings.php]( 
https://github.com/drupal/drupal/blob/d4d7a73eaac2ea6310b6fe3d751ef7a8fd560416/sites/default/default.settings.php#L184-L198), this is a supported use case of prefix:

```php
 * You can also use a reference to a schema/database as a prefix. This may be
 * useful if your Drupal installation exists in a schema that is not the default
 * or you want to access several databases from the same code base at the same
 * time.
 * Example:
 * @code
 *   'prefix' => array(
 *     'default'   => 'main.',
 *     'users'     => 'shared.',
 *     'sessions'  => 'shared.',
 *     'role'      => 'shared.',
 *     'authmap'   => 'shared.',
 *   );
 * @endcode
 * NOTE: MySQL and SQLite's definition of a schema is a database.
```

Without the ability to bootstrap to `DRUSH_BOOTSTRAP_DRUPAL_DATABASE`, `drush` is unable to run many of its most useful commands.  Any estimate idea as to when this issue will be attended to?  Thanks!

**Comment by da70** [comment]
To make it easier for the Drush devs to verify the error exists and to see where it's caused, here is the breakdown for release 8.1.9 (assume Drupal 7 bootstrap):

Bootstrap phase index = 4:

[drush/lib/Drush/Boot/DrupalBoot7.php](https://github.com/drush-ops/drush/blob/7c1887fbbe746ffbfba7575440a7b21cbfe21833/lib/Drush/Boot/DrupalBoot7.php#L69-#L71):

```php
  function bootstrap_drupal_database_validate() {
    return parent::bootstrap_drupal_database_validate() && $this->bootstrap_drupal_database_has_table('blocked_ips');
  }
```

...calls:

[drush/lib/Drush/Boot/DrupalBoot.php](https://github.com/drush-ops/drush/blob/7c1887fbbe746ffbfba7575440a7b21cbfe21833/lib/Drush/Boot/DrupalBoot.php#L492=L507):

```php
  function bootstrap_drupal_database_has_table($required_tables) {
    try {
      $sql = drush_sql_get_class();
      $spec = $sql->db_spec();
      $prefix = isset($spec['prefix']) ? $spec['prefix'] : NULL;
      if (!is_array($prefix)) {
        $prefix = array('default' => $prefix);
      }
      $tables = $sql->listTables();
      foreach ((array)$required_tables as $required_table) {
        $prefix_key = array_key_exists($required_table, $prefix) ? $required_table : 'default';
        if (!in_array($prefix[$prefix_key] . $required_table, $tables)) {
          return FALSE;
        }
      }
    }
```

...which gets its list of tables from:

[drush/lib/Drush/Sql/Sqlmysql.php](https://github.com/drush-ops/drush/blob/7c1887fbbe746ffbfba7575440a7b21cbfe21833/lib/Drush/Sql/Sqlmysql.php#L112-L119):

```php
  public function listTables() {
    $current = drush_get_context('DRUSH_SIMULATE');
    drush_set_context('DRUSH_SIMULATE', FALSE);
    $return = $this->query('SHOW TABLES;');
    $tables = drush_shell_exec_output();
    drush_set_context('DRUSH_SIMULATE', $current);
    return $tables;
  }
```

...which returns an array containing:

```
...
block
block_custom
block_node_type
block_role
blocked_ips
cache
...
```

Since `bootstrap_drupal_database_has_table` is trying to match `prefix + table name` pattern of `shared.blocked_ips`, which will never be in the list returned by `listTables`, it will always return `FALSE` -- thus, `bootstrap_drupal_database_validate` will always fail, and bootstrap cannot ever proceed up to phase 4.

**Comment by wturrell** [comment]
I spent some time tracing this back, and eventually found the same methods as @da70; clearly it will never work with prefixes, and based on other issues I believe db prefix support has now been officially removed (but for which combinations of Drush and Drupal versions I'm unclear?) 

I have a Drupal 7 multisite that uses shared users, sessions, role, user_roles and authmap tables.

The workaround I've come up with, so I can still run the latest Drush 8.x (albeit ensuring I switch to the correct database via `--uri=example.com/sitename` etc. when calling Drush for anything concerning users) is to do this in settings.php:

```
if (defined('DRUSH_VERSION')) {
	// Drush doesn't construct prefixes correctly, remove and use single DB
        // remember to call Drush with correct --uri= value!
	$db_prefixes = [];
} else {
	$db_prefixes = // whatever they usually are
}

$databases = [
...

unset($db_prefixes);
```

The *DRUSH_VERSION* constant is only set when Drush is running (i.e. safer than using `var_dump(PHP_SAPI)` - which will only return "cli", which could be the case in other situations).  When Drush is running there will be no prefixes and everything uses a single DB only.

**Comment by weitzman** [comment]
Wont Fix
