### ISSUE TITLE
Allow make files to live in ~/.drush/

### ISSUE THREAD

**Issue by akamustang** [drush-ops/drush#2331]
This is a feature request that when executing `drush make example.make example` if `./example.make` doesn't exist we also check if `~/.drush/example.make` (or similar) exists before saying `Invalid or empty make file: example.make`.

I believe this functionality would be added in `make.utilities.inc::make_get_data()`.

**Comment by greg-1-anderson** [comment]
Make is deprecated. Closing old issues.
