### ISSUE TITLE
Command config-import leaves settings out of sync

### ISSUE THREAD

**Issue by rodrigoaguilera** [drush-ops/drush#2332]
Steps
- Install a drupal with the standard profile.
- Change the user settings so only admins can create new users.
- Save the active configuration with drush config-export on a folder
- Change core.extension.yml form that folder rreplacing standard with minimal
- Install a minimal site
- Make the minimal site a clone of your configuration folder by setting the uuid that is on system.site.yml with "drush config set system.site uuid UUID_FROM_YML"
-Import the configuration folder into the minimal site

Expected result: all the configuration is syncronized.

Bug:
 user.settings still has differences with the active configuration

Solutions:
-Run drush migrate-import twice
-Do the config-export step using the drupal interface

**Comment by weitzman** [comment]
This workflow is not non-standard. If there is bug, its got to be expressed simpler for us to work on it.

**Comment by rodrigoaguilera** [comment]
I updated to drush 8.1.5 and drupal 8.2.0-rc2 and I can't reproduce this issue anymore
