### ISSUE TITLE
Config Export misses config translations

### ISSUE THREAD

**Issue by yobottehg** [drush-ops/drush#2335]
If you export your config after translating configuration like the site slogan drush cex will tell you that nothing changed.

The problem is in config.drush.inc line 485
`if (!$config_comparer->createChangelist()->hasChanges()) {`

This makes it impossible to deploy config translations or even make unwanted overwrites to translated config on remotes.

I don't know exactly where the problem is but drupal console behaves the same.
Core config diff sees the changes, also drupal config:diff
drupal config:export and drush cex say that nothing changed.

**Comment by yobottehg** [comment]
One more thing:

If you do not early return in line 486 of config.drush.inc the config gets exported correctly but no changes are displayed. 

It is only a problem of checking what has changed which misses for example the translations.fr Collection

**Comment by vermario** [comment]
Experiencing the same problem, also https://github.com/drush-ops/drush/issues/2504 seems to be related to the same. 

it would seem a quite common problem, so I am wondering if there is something wrong with our setups?

**Comment by weitzman** [comment]
Was fixed by #2939 I think.
