### ISSUE TITLE
Fancy options features for annotated commands (suboptions)

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2336]
We don't have to keep supporting these weird old behaviors, but if we drop them we should knowingly do so:
- [x] Sharing options across commands inside a commandfile and even across commanfiles. For example, see [drush_sql_get_table_selection_options](http://api.drush.org/api/drush/commands!sql!sql.drush.inc/function/drush_sql_get_table_selection_options/master) is used in archive commands and sql commands. Maybe we allow specifying a callable as value to a new annotation called @optionset?
- [ ]  [sub-options](https://github.com/drush-ops/drush/blob/master/commands/pm/pm.drush.inc#L331)
- [x]  hidden options - supported by annotation_adapter
- [x]  example-value. Symfony always shows the default value for the example value;
- [x] [allow-additional-options](https://github.com/drush-ops/drush/blob/master/commands/pm/pm.drush.inc#L383). Seems easy enough.
- [x] ~~[engines key](https://github.com/drush-ops/drush/blob/master/commands/pm/pm.drush.inc#L370). engines is a way for commands to declare what engines apply to them. Alas, each declaration can have config such as _add-options-to-command_~~ Engines will be removed.

**Comment by weitzman** [comment]
Think @greg-1-anderson made progress on this in AnnotatedCommand

**Comment by greg-1-anderson** [comment]
Progress is being made in AnnotatedCommand, but the above items are still all todo's -- although getting closer.

**Comment by greg-1-anderson** [comment]
The first of these, sharing options, can now be done as follows:

/**
 * @hook pre-command @sql-get-table-selection
 * @option skip-tables-key A key in the $skip_tables array. @see example.drushrc.php. Optional.
 */
public function sqlGetTableSelection(...)
{
    // Code to implement common functionality of skip-tables-key et. al. goes here
}

Then, the above pre-command hook will be applied to any command annotated with `@sql-get-table-selection`.

This same mechanism could potentially be used to implement something similar to the existing Drush engines feature; however, it seems unlikely that this implementation would be perfectly backwards-compatible with the existing implementation. Perhaps this would be acceptable, as existing external Drush commands that referenced Drush engines (if any) could continue to run the original implementation.

Sub options will require implementation of a custom `help` command. There is some question as to what these should look like.

Using `@suboption` as a mode-switch would probably work for most use-cases:
```
/**
 * @option lock Add a persistent lock
 * @suboptions lock
 *     @option lock-message A brief message 
 *     @option unlock Remove the persistent lock
 */
```
The suboptions would continue until the next @suboptions annotation. The parameter of the @suboption annotation is the immediate parent for all of the suboptions that follow. The indentation would be for cosmetic purposes only; the annotation parser ignores this whitespace.

Does that seem sufficient, or would some other mechanism be preferable?

**Comment by greg-1-anderson** [comment]
Suggestion: do not port `make` or `pm` commands in the 8.x branch.  Leave them in their original implementation, and keep engines as they are.  In the master branch, move both `make` and `pm` out of core into extensions, and remove the engines implementation completely.

**Comment by weitzman** [comment]
Agree on make and pm approach. Suboption proposal looks good.

Will give this a try.

**Comment by greg-1-anderson** [comment]
Note that Drush is still using Annotated Commands ~1, whereas my improvements are on the 2.x branch. Try the 2.x beta; I'll make a stable 2.x release of Annotated Commands soon, so that we can use it in the next Drush 8.x release.

**Comment by weitzman** [comment]
I pushed a commit which starts using ~2 from Consolidation and updates drupliconCommands as you suggested (I think). The error below prevents from me from seeing if my changes are working. Not sure how to fix it. Feel free to say here or push another commit which fixes it. Thanks Greg.

```
PHP Catchable fatal error:  Argument 2 passed to Robo\Robo::configureContainer() must be an instance of Robo\Config, instance of Symfony\Component\Console\Input\StringInput given, called in /Users/moshe.weitzman/reps/drush/includes/preflight.inc on line 252 and defined in /Users/moshe.weitzman/reps/drush/vendor/consolidation/robo/src/Robo.php on line 103
PHP Stack trace:
PHP   1. {main}() /Users/moshe.weitzman/reps/drush/drush.php:0
PHP   2. drush_main() /Users/moshe.weitzman/reps/drush/drush.php:11
PHP   3. drush_preflight_prepare() /Users/moshe.weitzman/reps/drush/includes/preflight.inc:36
PHP   4. drush_init_dependency_injection_container() /Users/moshe.weitzman/reps/drush/includes/preflight.inc:195
PHP   5. Robo\Robo::configureContainer() /Users/moshe.weitzman/reps/drush/includes/preflight.inc:252
```

**Comment by weitzman** [comment]
I added hidden and example-value to the checklist.

**Comment by greg-1-anderson** [comment]
Symfony always shows the default value for the example value; maybe that is fine for us as well?

**Comment by weitzman** [comment]
Yeah, seems sufficient.

**Comment by weitzman** [comment]
The first checkbox, 'sharing options across commands via an annotation like @sql-get-table-selection is supported in AnnotatedCommand but not yet supported in our adapter. Unchecked that box in the OP.

**Comment by weitzman** [comment]
suboptions are the only item left here. console doesn't suport these, and perhaps we shouldn't either. i found [1 related feature request](https://github.com/symfony/symfony/issues/19654)

**Comment by greg-1-anderson** [comment]
Suboptions are blocked on writing our own `help` command, something I've wanted to do for a while. Releated to #2453.

**Comment by weitzman** [comment]
We now have own help.
