### ISSUE TITLE
How to debug "sh: 1: -t: not found"

### ISSUE THREAD

**Issue by alberto56** [drush-ops/drush#2338]
I have found a few references online to drush showing a notice "sh: 1: -t: not found", I'm looking for insight on how to debug this and where this might be defined, and what it means.

To reproduce, create a Docker image based on the following Dockerfile:

    FROM drupal

    # Install Drush
    RUN curl -sS https://getcomposer.org/installer | php
    RUN mv composer.phar /usr/local/bin/composer
    RUN composer global require drush/drush:8
    RUN ln -s /root/.composer/vendor/drush/drush/drush /bin/drush

    # Install mysql client, required by drush
    RUN apt-get update && apt-get upgrade -y
    RUN apt-get install -y mysql-client

Also, create a mysql container and take note of the root password, and then run the Drupal container: 

    docker run --name mydrupal \
      --link mymysql:mysql \
      -p 80:80 \
      -d mydrupal-image

Then running drush si will cause `sh: 1: -t: not found` (note that the installation works fine, but the notice is annoying):

    $ docker exec mydrupal /bin/bash -c "cd /var/www/html && drush site-install -y --db-url=mysql://root:$PASSWORD@mysql/drupaldatabase"
    You are about to create a /var/www/html/sites/default/settings.php file and DROP all tables in your 'drupaldatabase' database. Do you want to continue? (y/n): y
    Starting Drupal installation. This takes a while. Consider using the        [ok]
    --notify global option.
    sh: 1: -t: not found
    Installation complete.  User name: admin  User password: N5oyHKuP6J         [ok]
    Unable to send email. Contact the site administrator if the problem      [error]
    persists.
    Congratulations, you installed Drupal!                                  [status]

**Comment by Chi-teck** [comment]
In my experience this error is caused by running wrong shell command using php _exec_ function. Have you tried to run drush with `-d` option?

**Comment by alberto56** [comment]
Hi, thanks for the tip. Here is the same command with the debug (-d) flag. Still not clear to me what can be causing this though...

    $ docker exec mydrupal /bin/bash -c "cd /var/www/html && drush -d site-install -y --db-url=mysql://root:$PASSWORD@mysql/drupaldatabase"
    Using the Drush script found at /root/.composer/vendor/drush/drush/drush.launcher using proc_open
    Drush preflight prepare loaded autoloader at                         [preflight]
    /root/.composer/vendor/autoload.php [0 sec, 725.16 KB]
    Starting Drush preflight. [0.01 sec, 725.7 KB]                       [preflight]
    Cache HIT cid: 8.0.0-commandfiles-0-523151f6fe5a7b8dab1dd64817f5a983     [debug]
    [0.01 sec, 740.98 KB]
    Scanning into /etc/drush for /.*aliases\.drush(8|)rc\.php$/ [0.03    [sitealias]
    sec, 1 MB]
    Scanning into /etc/drush for /self\.alias\.drush(8|)rc\.php$/ [0.03  [sitealias]
    sec, 1 MB]
    Scanning into /root/.composer/vendor/drush/drush/includes/.. for     [sitealias]
    /.*aliases\.drush(8|)rc\.php$/ [0.03 sec, 1 MB]
    Scanning into /root/.composer/vendor/drush/drush/includes/.. for     [sitealias]
    /self\.alias\.drush(8|)rc\.php$/ [0.04 sec, 1.01 MB]
    Scanning into /root/.drush for /.*aliases\.drush(8|)rc\.php$/ [0.04  [sitealias]
    sec, 1.01 MB]
    Scanning into /root/.drush for /self\.alias\.drush(8|)rc\.php$/ [0.04[sitealias]
    sec, 1.01 MB]
    Scanning into /var/www/html/../drush for                             [sitealias]
    /.*aliases\.drush(8|)rc\.php$/ [0.04 sec, 1.01 MB]
    Scanning into /var/www/html/../drush for                             [sitealias]
    /self\.alias\.drush(8|)rc\.php$/ [0.04 sec, 1.01 MB]
    Scanning into /var/www/html/drush for /.*aliases\.drush(8|)rc\.php$/ [sitealias]
    [0.04 sec, 1.01 MB]
    Scanning into /var/www/html/drush for                                [sitealias]
    /self\.alias\.drush(8|)rc\.php$/ [0.04 sec, 1.01 MB]
    Scanning into /var/www/html/sites/all/drush for                      [sitealias]
    /.*aliases\.drush(8|)rc\.php$/ [0.04 sec, 1.01 MB]
    Scanning into /var/www/html/sites/all/drush for                      [sitealias]
    /self\.alias\.drush(8|)rc\.php$/ [0.04 sec, 1.01 MB]
    Scanning into /var/www/html/sites/default for                        [sitealias]
    /.*aliases\.drush(8|)rc\.php$/ [0.04 sec, 1.01 MB]
    Scanning into /var/www/html/sites/default for                        [sitealias]
    /self\.alias\.drush(8|)rc\.php$/ [0.04 sec, 1.01 MB]
    Bootstrap to phase 0. [0.06 sec, 2.01 MB]                            [bootstrap]
    Bootstrap to phase 1. [0.06 sec, 2.01 MB]                            [bootstrap]
    Drush bootstrap phase : bootstrap_drupal_root() [0.07 sec, 2.15 MB]  [bootstrap]
    Initialized Drupal 8.1.8 root directory at /var/www/html [0.07 sec,     [notice]
    2.15 MB]
    Find command files for phase 1 (max=1) [0.07 sec, 1.16 MB]               [debug]
    Cache HIT cid: 8.0.0-commandfiles-1-3b09cf1acaa11c1d8f49e77092e21140     [debug]
    [0.07 sec, 1.16 MB]
    Found command: site-install (commandfile=site_install) [0.07 sec,    [bootstrap]
    1.16 MB]
    Calling hook drush_core_site_install_validate [0.09 sec, 2.24 MB]        [debug]
    Returned from hook drush_core_site_install_validate [0.09 sec, 2.24      [debug]
    MB]
    Calling hook drush_core_pre_site_install [0.09 sec, 2.26 MB]             [debug]
    Scanning into /etc/drush for /.*aliases\.drush(8|)rc\.php$/ [0.09    [sitealias]
    sec, 2.34 MB]
    Scanning into /etc/drush for /self\.alias\.drush(8|)rc\.php$/ [0.09  [sitealias]
    sec, 2.35 MB]
    Scanning into /root/.composer/vendor/drush/drush/includes/.. for     [sitealias]
    /.*aliases\.drush(8|)rc\.php$/ [0.09 sec, 2.35 MB]
    Scanning into /root/.composer/vendor/drush/drush/includes/.. for     [sitealias]
    /self\.alias\.drush(8|)rc\.php$/ [0.09 sec, 2.35 MB]
    Scanning into /root/.drush for /.*aliases\.drush(8|)rc\.php$/ [0.1   [sitealias]
    sec, 2.35 MB]
    Scanning into /root/.drush for /self\.alias\.drush(8|)rc\.php$/ [0.1 [sitealias]
    sec, 2.35 MB]
    Scanning into /var/www/html/../drush for                             [sitealias]
    /.*aliases\.drush(8|)rc\.php$/ [0.1 sec, 2.35 MB]
    Scanning into /var/www/html/../drush for                             [sitealias]
    /self\.alias\.drush(8|)rc\.php$/ [0.1 sec, 2.35 MB]
    Scanning into /var/www/html/drush for /.*aliases\.drush(8|)rc\.php$/ [sitealias]
    [0.1 sec, 2.35 MB]
    Scanning into /var/www/html/drush for                                [sitealias]
    /self\.alias\.drush(8|)rc\.php$/ [0.1 sec, 2.35 MB]
    Scanning into /var/www/html/sites/all/drush for                      [sitealias]
    /.*aliases\.drush(8|)rc\.php$/ [0.1 sec, 2.35 MB]
    Scanning into /var/www/html/sites/all/drush for                      [sitealias]
    /self\.alias\.drush(8|)rc\.php$/ [0.1 sec, 2.35 MB]
    Scanning into /var/www/html/sites/default for                        [sitealias]
    /.*aliases\.drush(8|)rc\.php$/ [0.1 sec, 2.35 MB]
    Scanning into /var/www/html/sites/default for                        [sitealias]
    /self\.alias\.drush(8|)rc\.php$/ [0.1 sec, 2.35 MB]
    Cache MISS cid: 8.0.0-alias-path--15a6664634e88b32b6b71df70fb4d2ce       [debug]
    [0.1 sec, 2.35 MB]
    Scanning into /etc/drush for /.*aliases\.drush(8|)rc\.php$/ [0.1 sec,[sitealias]
    2.36 MB]
    Scanning into /etc/drush for /.*\.alias\.drush(8|)rc\.php$/ [0.1 sec,[sitealias]
    2.36 MB]
    Scanning into /root/.composer/vendor/drush/drush/includes/.. for     [sitealias]
    /.*aliases\.drush(8|)rc\.php$/ [0.1 sec, 2.36 MB]
    Scanning into /root/.composer/vendor/drush/drush/includes/.. for     [sitealias]
    /.*\.alias\.drush(8|)rc\.php$/ [0.1 sec, 2.36 MB]
    Scanning into /root/.drush for /.*aliases\.drush(8|)rc\.php$/ [0.1   [sitealias]
    sec, 2.36 MB]
    Scanning into /root/.drush for /.*\.alias\.drush(8|)rc\.php$/ [0.1   [sitealias]
    sec, 2.36 MB]
    Scanning into /var/www/html/drush for /.*aliases\.drush(8|)rc\.php$/ [sitealias]
    [0.1 sec, 2.36 MB]
    Scanning into /var/www/html/drush for /.*\.alias\.drush(8|)rc\.php$/ [sitealias]
    [0.1 sec, 2.36 MB]
    Scanning into /var/www/html/sites/all/drush for                      [sitealias]
    /.*aliases\.drush(8|)rc\.php$/ [0.1 sec, 2.36 MB]
    Scanning into /var/www/html/sites/all/drush for                      [sitealias]
    /.*\.alias\.drush(8|)rc\.php$/ [0.1 sec, 2.36 MB]
    Scanning into /var/www/html/sites/default for                        [sitealias]
    /.*aliases\.drush(8|)rc\.php$/ [0.1 sec, 2.36 MB]
    Scanning into /var/www/html/sites/default for                        [sitealias]
    /.*\.alias\.drush(8|)rc\.php$/ [0.1 sec, 2.36 MB]
    Scanning into /var/www/html/../drush for                             [sitealias]
    /.*aliases\.drush(8|)rc\.php$/ [0.1 sec, 2.36 MB]
    Scanning into /var/www/html/../drush for                             [sitealias]
    /.*\.alias\.drush(8|)rc\.php$/ [0.1 sec, 2.36 MB]
    sql-query: SELECT 1; [0.1 sec, 2.36 MB]                                 [status]
    Executing: mysql --defaults-extra-file=/tmp/drush_xLtwpz --database=drupaldatabase --host=mysql --silent  < /tmp/drush_bmL8hq > /dev/null
    You are about to DROP all tables in your 'drupaldatabase' database. Do you want to continue? (y/n): y
    Sites directory /var/www/html/sites/default already exists -            [notice]
    proceeding. [0.12 sec, 2.37 MB]
    Drush bootstrap phase : bootstrap_drupal_site() [0.12 sec, 2.46 MB]  [bootstrap]
    Initialized Drupal site default at sites/default [0.12 sec, 2.46 MB]    [notice]
    Find command files for phase 2 (max=) [0.12 sec, 1.41 MB]                [debug]
    Cache HIT cid: 8.0.0-install_profile-66ecfeb9791a023150773849f1550c5d    [debug]
    [0.13 sec, 1.42 MB]
    Cache HIT cid: 8.0.0-commandfiles-2-d52f0bcffa9fd586a8b4704e0a485dbe     [debug]
    [0.13 sec, 1.42 MB]
    sql-query: SELECT 1; [0.13 sec, 1.42 MB]                                [status]
    Executing: mysql --defaults-extra-file=/tmp/drush_LbOuNR --database=drupaldatabase --host=mysql --silent  < /tmp/drush_XYiuBI > /dev/null
    sql-query: SHOW TABLES; [0.14 sec, 1.42 MB]                             [status]
    Executing: mysql --defaults-extra-file=/tmp/drush_6nMFfa --database=drupaldatabase --host=mysql --silent  < /tmp/drush_Uu0x10
      block_content
      block_content__body
      block_content_field_data
      block_content_field_revision
      block_content_revision
      block_content_revision__body
      cache_bootstrap
      cache_config
      cache_container
      cache_data
      cache_default
      cache_discovery
      cache_entity
      cachetags
      comment
      comment__comment_body
      comment_entity_statistics
      comment_field_data
      config
      file_managed
      file_usage
      history
      key_value
      key_value_expire
      menu_link_content
      menu_link_content_data
      menu_tree
      node
      node__body
      node__comment
      node__field_image
      node__field_tags
      node_access
      node_field_data
      node_field_revision
      node_revision
      node_revision__body
      node_revision__comment
      node_revision__field_image
      node_revision__field_tags
      queue
      router
      search_dataset
      search_index
      search_total
      semaphore
      sequences
      sessions
      shortcut
      shortcut_field_data
      shortcut_set_users
      taxonomy_index
      taxonomy_term_data
      taxonomy_term_field_data
      taxonomy_term_hierarchy
      url_alias
      user__roles
      user__user_picture
      users
      users_data
      users_field_data
      watchdog
    sql-query: DROP TABLE block_content, block_content__body,               [status]
    block_content_field_data, block_content_field_revision,
    block_content_revision, block_content_revision__body,
    cache_bootstrap, cache_config, cache_container, cache_data,
    cache_default, cache_discovery, cache_entity, cachetags, comment,
    comment__comment_body, comment_entity_statistics, comment_field_data,
    config, file_managed, file_usage, history, key_value,
    key_value_expire, menu_link_content, menu_link_content_data,
    menu_tree, node, node__body, node__comment, node__field_image,
    node__field_tags, node_access, node_field_data, node_field_revision,
    node_revision, node_revision__body, node_revision__comment,
    node_revision__field_image, node_revision__field_tags, queue, router,
    search_dataset, search_index, search_total, semaphore, sequences,
    sessions, shortcut, shortcut_field_data, shortcut_set_users,
    taxonomy_index, taxonomy_term_data, taxonomy_term_field_data,
    taxonomy_term_hierarchy, url_alias, user__roles, user__user_picture,
    users, users_data, users_field_data, watchdog [0.16 sec, 1.43 MB]
    Executing: mysql --defaults-extra-file=/tmp/drush_6p06Ps --database=drupaldatabase --host=mysql --silent  < /tmp/drush_RxvKxj
    Returned from hook drush_core_pre_site_install [0.8 sec, 1.42 MB]        [debug]
    Calling hook drush_core_site_install [0.8 sec, 1.43 MB]                  [debug]
    Starting Drupal installation. This takes a while. Consider using the        [ok]
    --notify global option. [1.14 sec, 6.42 MB]
    Calling install_drupal(Object, Array) [1.14 sec, 6.43 MB]                [debug]
    sh: 1: -t: not found
    Installation complete.  User name: admin  User password: enRbTyZ77a         [ok]
    [23.34 sec, 32.14 MB]
    Returned from hook drush_core_site_install [23.34 sec, 32.13 MB]         [debug]
    Unable to send email. Contact the site administrator if the problem      [error]
    persists. [23.34 sec, 32.13 MB]
    Congratulations, you installed Drupal! [23.34 sec, 32.13 MB]            [status]
    Command dispatch complete [23.34 sec, 32.08 MB]                         [notice]

**Comment by axiac** [comment]
The cause of this error is PHP not being properly configured to send emails. It is not your fault, this is how some distributions install it. I had the same issue some time ago (in a different environment), I investigated, found the solution and wrote an article about it: http://axiac.ro/blog/sh-1-t-not-found/

**Comment by alberto56** [comment]
@axiac thanks, your article explains it very well. I'll go ahead a close this issue.

**Comment by leymannx** [comment]
In the case of this happening inside some debug or testing container where you never want to send mails in the first place, you might simply disable Drupal sending mails all together using DevelMailLog: https://drupal.stackexchange.com/questions/38255/how-can-i-stop-drupal-from-sending-e-mails-of-any-kind

**Comment by Luc45** [comment]
> @alberto56 The cause of this error is PHP not being properly configured to send emails. It is not your fault, this is how some distributions install it. I had the same issue some time ago (in a different environment), I investigated, found the solution and wrote an article about it: http://axiac.ro/blog/sh-1-t-not-found/

Hi @alberto56 , it seems the blog is down. Can you briefly explain the issue here, please?
