### ISSUE TITLE
Lag between download available on drush.org and release available for drush dl / drush rl?

### ISSUE THREAD

**Issue by jsibley2** [drush-ops/drush#2342]
I see a lag of at least several hours between what is listed for a module on drupal.org:
Development releases
Version Download    Date
7.x-3.x-dev tar.gz (152.99 KB) | zip (174.89 KB)    2016-Sep-12

and

7.x-3.x Fix Rules issue, new features   Julien Duteil   7 hours

and what is listed by drush (7) rl and/or downloaded:

 Project          Release        Date         Status
limesurvey_sync  7.x-3.x-dev    **2016-Sep-08**  Development
 limesurvey_sync  7.x-3.0-beta1  2016-Sep-06  Supported
 limesurvey_sync  7.x-2.x-dev    2016-Jun-18  Development
 limesurvey_sync  7.x-1.8        2016-Feb-26  Supported, Recommended
 limesurvey_sync  7.x-1.x-dev    2016-Feb-26  Development

Is this expected behavior or does it have to do with the way the module is being committed, etc.?

If I want to use Drush, do I just have to wait until the correct release shows up?

Thanks.

**Comment by weitzman** [comment]
You can try to run `drush cc drush`. Otherwise the delay is outside of drush. This is not expected behavior.
