### ISSUE TITLE
Install a specific version of Drush

### ISSUE THREAD

**Issue by vaibhavjain-in** [drush-ops/drush#2346]
Hi team,

I recently installed Drush with the documentation in http://docs.drush.org/en/master/install/. I see that the drush version is Drush 9. I want to have drush 8, how can I install this from this command "php -r "readfile('https://s3.amazonaws.com/files.drush.org/drush.phar');" > drush" ?

**Comment by weitzman** [comment]
That is drush 8. Remove all your drush's from system and retry.
