### ISSUE TITLE
[D8] Preserve system.maintenance_mode on database update

### ISSUE THREAD

**Issue by DuaelFr** [drush-ops/drush#2358]
D8 has some mecanism to remove the maintenance mode at the end of the database update process if it was not set at the beginning. This mecanism is based on a session variable. The thing is that somehow, drush does not set this session variable so the maintenance mode is removed when doing a drush updb.

That problem can be really annoying if you want to ensure your website is not totally broken after the update and before visitors see the damages.

**Comment by Leksat** [comment]
Totally agree.

https://github.com/drush-ops/drush/blob/7f1a290709b1d49392119326606e0af56146d105/src/Commands/core/UpdateDBCommands.php#L272-L274
Here drush should save the original value of `system.maintenance_mode` state and then restore it back.

**Comment by weitzman** [comment]
Fixed in #3236
