### ISSUE TITLE
.drush_bashrc does not locate drush

### ISSUE THREAD

**Issue by grasmash** [drush-ops/drush#2363]
`.drush_bashrc` executes `d=$(which drush)` to find drush.

On OSX, running `which drush` will produce output like:

```
drush is /Users/matthew.grasmick/drush/drush
drush is /usr/local/bin/drush
drush is /Applications/DevDesktop/tools/drush
```

As you can see, this may produce multiple lines, but it will also produce each line with the prefix "drush is". Subsequent lines in .drush_bashrc do not account for this prefix. It will attempt to use a string like `drush is /Users/matthew.grasmick/drush/drush` as the executable. 

At least on my machine, the following change resolves this for this: `d=$(which drush | tail -1 | cut -d' ' -f 3)`. 

I'm not sure what the best cross-operating-system compatible approach would be, but I thought it was worth raising this case.

**Comment by weitzman** [comment]
My which doesn't have any prefix (OSX 10.11). But regardless, can you retry replacing which as per https://github.com/drush-ops/drush/pull/2108/files. If it works, lets update this PR accordingly.

**Comment by joestewart** [comment]
Would "command -v drush" be more appropriate?

**Comment by grasmash** [comment]
Yes `command -v drush` does do the trick. It actually looks like this line isn't in example.bashrc on the master branch? Perhaps this issue is inapplicable.

Is `drush.complete.sh` to be included in `.bash_profile` manually now rather than via `example.bashrc`?

**Comment by grasmash** [comment]
Actually, `example.bashrc` on master says:

    # Features:
    #
    # Finds and sources drush.complete.sh from your drush directory,
    # enabling autocompletion for Drush commands.

Perhaps that is no longer correct? I don't quite see how it accomplishes it.

**Comment by weitzman** [comment]
Yeah, thats no longer recommended. The recommended setup is to run `drush init`. When you do that, here is what is appended to your ~/.bashrc

```
# Path to Drush, added by 'drush init'.
export PATH="$HOME/reps/drush:$PATH"
alias dr=drush

# Include Drush bash customizations.
if [ -f "/Users/moshe.weitzman/.drush/drush.bashrc" ] ; then
  source /Users/moshe.weitzman/.drush/drush.bashrc
fi

# Include Drush completion.
if [ -f "/Users/moshe.weitzman/.drush/drush.complete.sh" ] ; then
  source /Users/moshe.weitzman/.drush/drush.complete.sh
fi

# Include Drush prompt customizations.
if [ -f "/Users/moshe.weitzman/.drush/drush.prompt.sh" ] ; then
  source /Users/moshe.weitzman/.drush/drush.prompt.sh
fi

PROMPT_COMMAND='__git_ps1 "\w" "$(__drush_ps1 "[%s]") \\\$ "'
```
