### ISSUE TITLE
"Source and target databases are the same" while port numbers differ

### ISSUE THREAD

**Issue by marcvangend** [drush-ops/drush#2364]
When trying a sql-sync between two remote sites, I got the message "Source and target databases are the same". 

The sites' SSH connections have the same IP address, but different port numbers. (I don't know why the server admins chose this setup, but it's beyond my control.) I assume the Drush thinks the databases are the same because the IP addresses are identical. It's probably an edge case, but could / should port numbers be taken into account as well here?

**Comment by weitzman** [comment]
Please post debug log (--debug), and the output of `drush status`. If your Drush is not up to date, please update. drush8+ rsync should handle two remote sites.

**Comment by marcvangend** [comment]
Thanks for looking into this Moshe. Here's the debug output (I obfuscated some project/server specific info):

    $ drush --debug sql-sync @prod @acc
    Using the Drush script found at /home/me/http/mysite/vendor/drush/drush/drush.launcher using pcntl_exec
    Loading drushrc "/home/me/.drush/drushrc.php" into "home.drush" scope. [0.01 sec, 3.04 MB]                         [bootstrap]
    Cache HIT cid: 8.1.5-commandfiles-0-a5111c4601b48e035eecd8e0a5dbd0c3 [0.01 sec, 3.08 MB]                                 [debug]
    Loading drushrc "/home/me/http/mysite/drush/drushrc.php" into "drupal" scope. [0.03 sec, 5.64 MB]              [bootstrap]
    Bootstrap to phase 0. [0.07 sec, 7.36 MB]                                                                            [bootstrap]
    Bootstrap to phase -1. [0.07 sec, 7.36 MB]                                                                           [bootstrap]
    Found command: sql-sync (commandfile=sqlsync) [0.07 sec, 7.37 MB]                                                    [bootstrap]
    Calling drush command init function: drush_sql_sync_init [0.07 sec, 7.37 MB]                                         [bootstrap]
    Drush bootstrap phase : bootstrap_drupal_root() [0.07 sec, 7.49 MB]                                                  [bootstrap]
    Loading drushrc "/home/me/http/mysite/drush/drushrc.php" into "drupal" scope. [0.07 sec, 7.49 MB]              [bootstrap]
    Initialized Drupal 8.1.10 root directory at /home/me/http/mysite/docroot [0.07 sec, 7.49 MB]                   [bootstrap]
    Find command files for phase 1 (max=2) [0.07 sec, 6.13 MB]                                                               [debug]
    Cache HIT cid: 8.1.5-commandfiles-1-da3809eddf7d80bbfdf1997a95c7a7f1 [0.07 sec, 6.13 MB]                                 [debug]
    Cache HIT cid: 8.1.5-annotationfiles-1-54c31edba440a89a4fe2d2bdf97a8ce5 [0.07 sec, 6.21 MB]                              [debug]
    Drush bootstrap phase : bootstrap_drupal_site() [0.08 sec, 6.7 MB]                                                   [bootstrap]
    Initialized Drupal site mysite.localhost at sites/mysite [0.08 sec, 6.71 MB]                                 [bootstrap]
    Find command files for phase 2 (max=2) [0.08 sec, 6.71 MB]                                                               [debug]
    Cache HIT cid: 8.1.5-install_profile-ff5c172531ad81a797c345d8c0437276 [0.08 sec, 6.71 MB]                                [debug]
    Cache HIT cid: 8.1.5-commandfiles-2-19eeae91f65da034139b2f5d927e1cd0 [0.08 sec, 6.71 MB]                                 [debug]
    Loaded alias @acc from file /home/me/http/mysite/docroot/../drush/mysite.aliases.drushrc.php [0.11 sec,       [notice]
    8.53 MB]
    Loaded alias @prod from file /home/me/http/mysite/docroot/../drush/mysite.aliases.drushrc.php [0.12 sec,      [notice]
    8.54 MB]
    Calling hook drush_sqlsync_sql_sync_validate [0.12 sec, 8.58 MB]                                                         [debug]
    Backend invoke: ssh -p 4001 admin@xxx.xxx.xxx.xxx '/usr/bin/php /var/www/mysite/vendor/drush/drush/drush.php     [command]
    --php=/usr/bin/php  --backend=2 --verbose --debug --root=/var/www/mysite/docroot
    --uri=https://prod.mysite.nl  sql-conf   --all 2>&1' 2>&1 [0.12 sec, 8.59 MB]
    ssh -p 4001 admin@xxx.xxx.xxx.xxx '/usr/bin/php /var/www/mysite/vendor/drush/drush/drush.php --php=/usr/bin/php   [notice]
     --backend=2 --verbose --debug --root=/var/www/mysite/docroot --uri=https://prod.mysite.nl  sql-conf
    --all 2>&1' 2>&1 [0.12 sec, 8.59 MB]
    Backend invoke: ssh -p 4002 admin@xxx.xxx.xxx.xxx '/usr/bin/php /var/www/mysite/vendor/drush/drush/drush.php     [command]
    --php=/usr/bin/php  --backend=2 --verbose --debug --root=/var/www/mysite/docroot
    --uri=http://acc.mysite.nl  sql-conf   --all 2>&1' 2>&1 [0.77 sec, 8.61 MB]
    ssh -p 4002 admin@xxx.xxx.xxx.xxx '/usr/bin/php /var/www/mysite/vendor/drush/drush/drush.php --php=/usr/bin/php   [notice]
     --backend=2 --verbose --debug --root=/var/www/mysite/docroot --uri=http://acc.mysite.nl  sql-conf
    --all 2>&1' 2>&1 [0.77 sec, 8.61 MB]
    Source and target databases are the same; please sync to a different target. [1.47 sec, 8.62 MB]                     [error]
    Returned from hook drush_sqlsync_sql_sync_validate [1.47 sec, 8.62 MB]                                                   [debug]
    Command dispatch complete [1.47 sec, 8.59 MB]                                                                           [notice]

Other relevant info:

    $ drush --version
     Drush Version   :  8.1.5


    $ drush status
     Drupal version                  :  8.1.10
     Site URI                        :  mysite.localhost
     Database driver                 :  mysql
     Database hostname               :  127.0.0.1
     Database port                   :  3306
     Database username               :  mysite
     Database name                   :  mysite
     Drupal bootstrap                :  Successful
     Drupal user                     :
     Default theme                   :  mysite
     Administration theme            :  seven
     PHP executable                  :  /usr/bin/php
     PHP configuration               :  /etc/php/php-cli.ini
     PHP OS                          :  Linux
     Drush script                    :  /home/me/http/mysite/vendor/drush/drush/drush.php
     Drush version                   :  8.1.5
     Drush temp directory            :  /tmp
     Drush configuration             :  /home/me/http/mysite/drush/drushrc.php /home/me/.drush/drushrc.php
     Drush alias files               :  /home/me/http/mysite/docroot/../drush/mysite.aliases.drushrc.php
     Install profile                 :  standard
     Drupal root                     :  /home/me/http/mysite/docroot
     Drupal Settings File            :  sites/mysite/settings.php
     Site path                       :  sites/mysite
     File directory path             :  sites/mysite/files
     Private file directory path     :  ../private_files/mysite
     Temporary file directory path   :  /tmp
     Sync config path                :  /home/me/http/mysite/docroot/../config


    $ drush sa @prod
    $aliases["mysite.prod"] = array (
      'root' => '/var/www/mysite/docroot',
      'uri' => 'https://prod.mysite.nl',
      'remote-host' => 'xxx.xxx.xxx.xxx',
      'remote-user' => 'admin',
      'ssh-options' => '-p 4001',
      'command-specific' =>
      array (
        'sql-sync' =>
        array (
          'structure-tables-list' => 'cache,cache_apachesolr,cache_block,cache_bootstrap,cache_commerce_shipping_rates,cache_entity_comment,cache_entity_file,cache_entity_node,cache_entity_registration,cache_entity_registration_state,cache_entity_registration_type,cache_entity_taxonomy_term,cache_entity_taxonomy_vocabulary,cache_entity_user,cache_field,cache_filter,cache_image,cache_form,cache_filter,cache_menu,cache_page,cache_panels,cache_path,cache_path_breadcrumbs,cache_rules,cache_token,cache_update,cache_variable,cache_views,cache_views_data,history,sessions,watchdog',
        ),
        'sql-dump' =>
        array (
          'structure-tables-list' => 'cache,cache_apachesolr,cache_block,cache_bootstrap,cache_commerce_shipping_rates,cache_entity_comment,cache_entity_file,cache_entity_node,cache_entity_registration,cache_entity_registration_state,cache_entity_registration_type,cache_entity_taxonomy_term,cache_entity_taxonomy_vocabulary,cache_entity_user,cache_field,cache_filter,cache_image,cache_form,cache_filter,cache_menu,cache_page,cache_panels,cache_path,cache_path_breadcrumbs,cache_rules,cache_token,cache_update,cache_variable,cache_views,cache_views_data,history,sessions,watchdog',
        ),
      ),
      'path-aliases' =>
      array (
        '%drush-script' => '/var/www/mysite/vendor/drush/drush/drush.php',
      ),
    );


    $ drush sa @acc
    $aliases["mysite.acc"] = array (
      'root' => '/var/www/mysite/docroot',
      'uri' => 'http://acc.mysite.nl',
      'remote-host' => 'xxx.xxx.xxx.xxx',
      'remote-user' => 'admin',
      'ssh-options' => '-p 4002',
      'command-specific' =>
      array (
        'sql-sync' =>
        array (
          'structure-tables-list' => 'cache,cache_apachesolr,cache_block,cache_bootstrap,cache_commerce_shipping_rates,cache_entity_comment,cache_entity_file,cache_entity_node,cache_entity_registration,cache_entity_registration_state,cache_entity_registration_type,cache_entity_taxonomy_term,cache_entity_taxonomy_vocabulary,cache_entity_user,cache_field,cache_filter,cache_image,cache_form,cache_filter,cache_menu,cache_page,cache_panels,cache_path,cache_path_breadcrumbs,cache_rules,cache_token,cache_update,cache_variable,cache_views,cache_views_data,history,sessions,watchdog',
        ),
        'sql-dump' =>
        array (
          'structure-tables-list' => 'cache,cache_apachesolr,cache_block,cache_bootstrap,cache_commerce_shipping_rates,cache_entity_comment,cache_entity_file,cache_entity_node,cache_entity_registration,cache_entity_registration_state,cache_entity_registration_type,cache_entity_taxonomy_term,cache_entity_taxonomy_vocabulary,cache_entity_user,cache_field,cache_filter,cache_image,cache_form,cache_filter,cache_menu,cache_page,cache_panels,cache_path,cache_path_breadcrumbs,cache_rules,cache_token,cache_update,cache_variable,cache_views,cache_views_data,history,sessions,watchdog',
        ),
      ),
      'path-aliases' =>
      array (
        '%drush-script' => '/var/www/mysite/vendor/drush/drush/drush.php',
      ),
    );

**Comment by weitzman** [comment]
My suggestion is to alter the drush aliases so that they don't define remote-host when the Drupal site is local. Then you will go down a different and simpler/faster code path which doesn't hit this validation.

If you cant edit the alias file directly, I would create a commandfile with an alter hook. [Here is a great blog post by @greg-1-anderson](https://pantheon.io/blog/fix-drush-site-aliases-policy-file).

**Comment by weitzman** [comment]
Also, I think /var/www/mysite/vendor/bin/drush would be a slightly better choice for %drush-script since that would go through the drush.launcher. Curious if that would work.

**Comment by weitzman** [comment]
Also note that alias files are PHP (for now) so you can conditionally declare remote-host.

**Comment by marcvangend** [comment]
I'm sorry, but I don't really understand the part "alter the drush aliases so that they don't define remote-host when the Drupal site is local". Both site aliases (@acc and @prod) are remote, so I must define `'remote-host' => 'xxx.xxx.xxx.xxx',`, right? If I don't define the remote host, how would Drush/SSH know which server to connect to?

By the way, to make sure the problem is 100% clear: in the  info above 'xxx.xxx.xxx.xxx' is always the same IP address, for both aliases.

**Comment by weitzman** [comment]
There are aliases stored on your local machine and then aliases stored on your the remote machine. The aliases on the remote machine could be defined without a remote-host entry. Once you do that, I think this would work: `drush @acc sql-sync @prod @self` or maybe `drush --runner=destination sql-sync @prod @acc`

**Comment by marcvangend** [comment]
Ah, I see, thanks. I will have to give that a try. 

Meanwhile I still think that the "Source and target databases are the same" message should be considered a bug in Drush, because even if the site aliases are defined as they are now, the databases are _not_ the same.

**Comment by weitzman** [comment]
Noticed that we have docs for doing a conditional declaration of remote-host at http://api.drush.ws/api/drush/drush.api.php/function/hook_drush_sitealias_alter/master

**Comment by weitzman** [comment]
Decided to fix this anyway by taking into account port number. I didn't actually test my change because it looked so simple. Please report back if it fixes things for you. Thanks.

**Comment by marcvangend** [comment]
Thanks Moshe, it works, but only if you fix the syntax error at [line 147](https://github.com/drush-ops/drush/blob/4905871facd43c9d07fc34eafdae903ea9b23dd1/commands/sql/sqlsync.drush.inc#L147) ;)

```
-  if drush_sitealias_convert_db_spec_to_db_url($source_db_spec) == drush_sitealias_convert_db_spec_to_db_url($target_db_spec) && !drush_get_context('DRUSH_SIMULATE')) {
+  if (drush_sitealias_convert_db_spec_to_db_url($source_db_spec) == drush_sitealias_convert_db_spec_to_db_url($target_db_spec) && !drush_get_context('DRUSH_SIMULATE')) {

```

**Comment by marcvangend** [comment]
By the way, a possible UI improvement would be to mention the port number in the confirmation message in case it's not the regular port 22.
Currently:

    You will destroy data in 203.0.113.0/my_database and replace with data from 203.0.113.0/my_database.

Could become:

    You will destroy data in 203.0.113.0:2222/my_database and replace with data from 203.0.113.0:3333/my_database.
