### ISSUE TITLE
Allow changing entire SSH command

### ISSUE THREAD

**Issue by djdevin** [drush-ops/drush#2367]
In some cases, `ssh-options` isn't enough.

Some examples:
1. When having to SSH through machines to get to other machines - often necessary for large corporations with layers of VPN/gateway servers/etc. Sometimes this involves executing a command on a remote machine to bring up an SSH connection to the final target, or using SSH tunneling which isn't possible with ssh-options since it tries to append remote-user to the wrong host (remote-host).
2. Having to run a script/wrapper before the SSH command
3. Connecting to services that use their own SSH command, but provide a tty. Example with openshift, `oc rsh` will open a terminal to the pod. Or `vagrant ssh`, `docker exec` etc.

I've been able to write drush wrappers for all the above manually but it would be nice to store them in Drush aliases. For example I can manually run `oc rsh php-4-hdfax drush uli` or any other remote drush command.

It would be nice to allow manually specifying the SSH (or drush) command per-alias (`oc rsh php-4-hdfax`). Jenkins does a little something like this where you can provide the entire command used to set up a Jenkins SSH slave.

**Comment by djdevin** [comment]
Maybe %drush-script is the solution here?

```
<?php
  $aliases['openshift-project'] = array(
    'root' => '/var/www/html',
    'path-aliases' => array(
      '%drush-script' => dirname(__FILE__) . '/openshift',
    ),
  );
```

openshift:
```
#!/bin/bash
oc rsh php-4-hdfax drush "$@"
```

It does work but results in "We could not find an applicable site for that command." also.
```
drush @openshift-project uli
http://openshift.project/user/reset/1/1475078874/qQRMqvcC0oV-CVFTwi5yQhG6QoKtEK_OhRcJpUL-W5U/login
We could not find an applicable site for that command.              
```

**Comment by weitzman** [comment]
FYI http://docs.drush.org/en/master/bastion/. 

Perhaps folks can chime in with more suggestions.

**Comment by weitzman** [comment]
I dont think we want to overload site aliases more than they already are. Keeping these as wrapper scripts seems fine to me. Needs some more thought.

**Comment by mc0e** [comment]
I don't think we should be adding support for every kind of transport, but I do think it should be possible to plug in support for transports as necessary. (My particular need at present is access via kubectl).  

I wonder if it would be best to remove explicit support for ssh, replacing that with a wrapper script also, which in effect means creating and documenting a well defined interface for how wrapper scripts should be used.  

I would like to retain the ability to loop over aliases and do operations on the references sites.
I think the way to do that is to have the aliases file identify the transport plugin required (aka wrapper script).

**Comment by ElijahLynn** [comment]
https://docs.drush.org/en/8.x/bastion/ (because master/bastion doesn't exist right now)

**Comment by djdevin** [comment]
>  (My particular need at present is access via kubectl).
> 
> I wonder if it would be best to remove explicit support for ssh, replacing that with a wrapper script also, which in effect means creating and documenting a well defined interface for how wrapper scripts should be used.

Seconded, this would be great. I described a workaround for OpenShift projects in #3544 but it's a bit hacky.

**Comment by greg-1-anderson** [comment]
I'm in progress on making [site-process](https://github.com/consolidation/site-process) support extensible transport mechanisms. @weitzman just merged a PR he did that added a transport for docker containers. The existing [ssh transport](https://github.com/consolidation/site-process/blob/master/src/Transport/SshTransport.php) could be extended as requested here as well. See the `configure` and `wrap` methods.

PRs in that project would be welcome.

**Comment by weitzman** [comment]
Lets discuss at https://github.com/consolidation/site-process/pull/20. I do think this make possiblethe OpenShift use case described by @djdevin
