### ISSUE TITLE
['config-export']['skip-modules'] - deletes lines from core.extension.yml for Modules that should be enabled on remote

### ISSUE THREAD

**Issue by eigentor** [drush-ops/drush#2371]
I learnt about the
$command_specific['config-export']['skip-modules'] = array('devel');
in drushrc.php to keep a module that I enable locally out of config export and import.
This works very well.

What does not seem to work, is the reversed situation:
I want to keep the shield module enabled on my remote site, so it is passwort protected and hidden from Google. I Exported its status into core.extension.yml, so it has a line
shield: 0
It needs to stay like this, so when I import configuration on the remote site (which I do not do with drush but via the interface).
But when I put the shield module into the drush-ignored ones, like so
$command_specific['config-export']['skip-modules'] = array('shield');
The line shield:0 gets deleted from core.extension.yml when exporting config.
So skipping in this case appears not to mean "leave untouched" but "have no config for".
Importing the newly written config into the remote site would uninstall the shield module.

Maybe it is the way this is meant to work.
So would be the only way for me to keep shield installed on the remote site to import config on the remote site with drush and put
$command_specific['config-import']['skip-modules'] = array('shield'); in the remote servers drushrc.php

**Comment by weitzman** [comment]
Thats not supported
