### ISSUE TITLE
drush status: Database: Connected was dropped

### ISSUE THREAD

**Issue by johnbburg** [drush-ops/drush#2372]
Prior to this commit in drush 7 (https://github.com/drush-ops/drush/commit/0f4e59a9ceb1c95fdd4dfff925cc131fec9d83c1#diff-9e2b1896af01f89d4d97823474f12ae2), the output of the drush status command included a line like the following:

```
 Database                        :  Connected 
```

This line was helpful in determining whether the site had a working database connection, but could not bootstrap Drupal (e.g. for an uninstalled site). This has caused issues with some of our continuous integration scripts (See https://github.com/forumone/web-starter/issues/250).

My guess was that this was removed in error as the comment in the commit does not refer to removing that information. Can we add it back?

**Comment by weitzman** [comment]
Fixed in 736e126
