### ISSUE TITLE
Destination database backup on sql-sync

### ISSUE THREAD

**Issue by skuark** [drush-ops/drush#2374]
When you run an sql-sync between two environments, it's easy confusing the order of parameters, typing `drush sql-sync @dev @prod` instead of `drush sql-sync @prod @dev`.

sql-sync makes a dump of the origin database, to sync from destination to origin, and saves it on `~/drush-backups` directory, but maybe would be interesting also saving a dump of the destination database automatically, before importing the source, to prevent possible data loss on user mistakes.

**Comment by weitzman** [comment]
We already warn user to do a backup. I think thats sufficient. Use sql-dump to accomplish the backup or some other tool.
