### ISSUE TITLE
Function name conflict with Devel module

### ISSUE THREAD

**Issue by joshbrown81** [drush-ops/drush#2380]
I installed Drush again today on a new machine and tried to use it at the same time that the Devel module was installed on a Drupal install. Both contributions define a function named 'dd'. 

`drush cc all
PHP Fatal error:  Cannot redeclare dd() (previously declared in /home/vagrant/.composer/vendor/illuminate/support/helpers.php:498) in /var/www/public/sites/all/modules/contrib/devel/devel.module on line 1772
Drush command terminated abnormally due to an unrecoverable error.                                                                                                      [error]
Error: Cannot redeclare dd() (previously declared in /home/vagrant/.composer/vendor/illuminate/support/helpers.php:498) in
/var/www/public/sites/all/modules/contrib/devel/devel.module, line 1772`

Not an issue as such, but worth knowing if you like using the devel module.

**Comment by weitzman** [comment]
Drush doesn't implement dd(). You error message mentions iluminate.

**Comment by joshbrown81** [comment]
You're right sorry!
