### ISSUE TITLE
Better support for the fish shell

### ISSUE THREAD

**Issue by jurgenhaas** [drush-ops/drush#2385]
Some drush commands like `ssh` or `exec [cmd]` can't be used by users with the fish shell being the default. The reason is the separator for multiple commands in a single CLI line which is ` && ` by default for bash and most other shells. However, fish needs a different syntax: `command; and command`

I'd be happy to provide a PR to fix this, if the maintainers agree to this.

**Comment by weitzman** [comment]
I think the issue is that Windows doesn't like ;. See b7c91327cf8fcb453349fbb6fda15e169c77a8b9

**Comment by jurgenhaas** [comment]
Which doesn't mater as I would suggest to implement this context-sensitive, i.e. only if the user shell is fish.

**Comment by weitzman** [comment]
There are too many such compound calls. That solution is not readable or sustainable IMO.

**Comment by jurgenhaas** [comment]
We should define the separator once in a variable or callback and use that callback everywhere it's needed. That way it would even increase readability of the code compared to today's solution.

**Comment by weitzman** [comment]
Good idea but ...

[The Fish folks don't want compat](https://github.com/fish-shell/fish-shell/issues/150). Its unfair to push the burden down to all CLI projects.

**Comment by jurgenhaas** [comment]
I'm confused. Why are you closing this issue? We do have a problem that Drush doesn't work and we know how to fix that. Why wouldn't we want to fix it then?

**Comment by jurgenhaas** [comment]
I mean we could be doing something along the lines of this:

```
function getCommandSeparator() {
  switch getOsShell() {
    case 'fish':
      return '; and ';

    default:
      return ' && '
  }
}
```

And then this would be used like this:

```
$cmd[] = $cd ? sprintf('cd %s%s', self::escapeshellarg($cd), getCommandSeparator()) : NULL;
```
