### ISSUE TITLE
locale-update or locale-check won't work

### ISSUE THREAD

**Issue by jkeruzec** [drush-ops/drush#2388]
Hello,

Drupal version : 8.1.10
Drush version installed with composer : 8.1.5
Dev Environment : Windows 7
Database used : PostgreSQL 9.4

We are trying to load .po file for our specific module using drush command but it doesn't work.
We already try this :
`drush --debug local-check`
`drush --debug local-update`
`drush --debug local-check --langcodes en`
`drush --debug local-update --langcodes en`

First, we had a problem with PGPASSFILE. We add a "set PGPASSFILE" as we are using Windows. I think this problem is solved for now....
Then we have two problems :
`The drush command 'local-check' could not be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new`

Off course, we did try to clear cache but it doesn't change anything.

With Lang option :
`Command locale-update needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this`

Can you help with this ?

Best regards,

**Comment by weitzman** [comment]
You might need to pass --uri
