### ISSUE TITLE
Make --include-overridden the default

### ISSUE THREAD

**Issue by damienmckenna** [drush-ops/drush#2390]
In Drupal 7 when you do "drush vget [varname]" it always shows the variable as it would be presented to Drupal's UI, including any variables that are overridden via the appropriate settings.php file. In D8 the equivalent command "drush cget [configname]" does not include config values overridden unless the "--include-overridden" argument is provided. This is a major change to the expected output and what one would expect when querying a specific instance of the site; there isn't a flag to enable in Drupal to "accept values overridden in the settings.php file" so there also shouldn't be a flag for Drush to present the same data structures, it should be automatic.

**Comment by weitzman** [comment]
Lets do conversation in the PR.
