### ISSUE TITLE
Class 'SebastianBergmann\Version' not found

### ISSUE THREAD

**Issue by tanc** [drush-ops/drush#2395]
I have drush installed with composer using "drush/drush": "dev-master" in my composer.json.

After a recent `composer global update` I found that `drush sql-sync` was throwing the following:

`PHP Fatal error:  Class 'SebastianBergmann\Version' not found in /Users/tanc/.composer/vendor/drush/drush/lib/Drush.php on line 71`

A temporary fix was to require this globally but it looks like there might be a dependency missing?

`composer global require sebastian/version`

**Comment by weitzman** [comment]
Yes, it is indeed missing. That package is part of phpunit so thats why it is there for most installs. I did `composer require sebastian/version` but am seeing errors. Help is welcome here.
