### ISSUE TITLE
--druplicon printing twice

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2396]
From outside a Drupal root I'm running `drush st --druplicon` and seeing it printed twice. I think the issue is that two instances of \Drush\CommandFiles\core\DrupliconCommands are being instantiated. In general I think hooks are running multiple times (also seeing that with \Drush\CommandFiles\core\ViewsCommands::validate during views-enable) during a single request.

ping @greg-1-anderson

**Comment by greg-1-anderson** [comment]
This also happens in some instances when a redispatch is involved, e.g. when help redispatches to help one command. Not sure about core-status, though; will need to look at it.

**Comment by weitzman** [comment]
I think we fixed this.
