### ISSUE TITLE
Drush make-convert stopped writing output files

### ISSUE THREAD

**Issue by fuzzy76** [drush-ops/drush#2399]
Our scripted CI setup stopped working because make-convert suddenly stopped writing output files and instead wrote the result to stdout.

The changed happened in this commit which claims to only backport support for an extra format: https://github.com/drush-ops/drush/commit/befc2ca1778352718d246b4fb1e51ee4664c079c

As you can see near the end of the diff, the file is not written to disk any more, but returned as output.

But the help text still claims it writes output files as before:

https://github.com/drush-ops/drush/blob/8.x/commands/make/make.drush.inc#L151

**Comment by weitzman** [comment]
ping @phenaproxima. if we can fix this quickly, lets do that. if not, lets just change docs and apologize profusely.

**Comment by phenaproxima** [comment]
I think I'd rather fix this, since we too need the ability for the command to output to a file. Forking now so I can whip up a fix.

**Comment by phenaproxima** [comment]
On second thought...it seems kind of pointless to fix this, since people can just pipe the output into a file quite easily. Is there any reason we shouldn't change the documentation to instruct this for file output?

```
drush make-convert foo.make --format=yml > foo.make.yml
```

**Comment by fuzzy76** [comment]
I doubt we're the only ones relying on the documented behaviour for our CI setup. So you'll probably break stuff for a lot of people for no apparent reason.

**Comment by weitzman** [comment]
Decided to just improve the docs. My apologies to all the folks who get surprised by this change. We try our best.
