### ISSUE TITLE
Is there a way to prevent Drush from bootstrapping the site?

### ISSUE THREAD

**Issue by dsnopek** [drush-ops/drush#2402]
If you run `drush core-status` on a Drupal root that hasn't been installed yet, it will get some information from the Drupal root, like the 'Drupal version' and 'Drupal root'.

If a sites/default/settings.php it will attempt to fully bootstrap the site. 

Is there a way to prevent the site from being bootstrapped, while still loading basic information about the Drupal root that you get when there's no sites/default/settings.php?

If you run `drush @none core-status` it won't bootstrap the site, but it also won't load the same basic information about the Drupal root. I tried setting `--uri` to an arbitrary value, and it still tried to bootstrap the 'default' site.

Thanks!

**Comment by weitzman** [comment]
It sounds like you would do well to write a custom command. In the command definition, set `'bootstrap' => DRUSH_BOOTSTRAP_DRUPAL_ROOT,`. That stops Drush from going farther for this command. Then in the command callback, just call `drush_core_status()`. Post again if you have more questions.

**Comment by dsnopek** [comment]
Ok, thanks! I was hoping for an option or environment variable or config thing, but we'll try doing a custom command.
