### ISSUE TITLE
make-convert does not handle version short form with patch

### ISSUE THREAD

**Issue by komlenic** [drush-ops/drush#2403]
Consider the following:
```
projects[field_inspector] = "1.0-beta2"
projects[field_inspector][patch][] = "https://www.drupal.org/files/1821316-add-groups-support-to-inspector.patch"
```
Drush make-convert will convert this to:
```
field_inspector:
  patch:
    - 'https://www.drupal.org/files/1821316-add-groups-support-to-inspector.patch'
```

As the first example above is valid in the "old" .info INI format and behaves as expected when executed with `drush make`, this may be desirable to be fixed in make-convert to be handled correctly.  However, the .info INI format documentation states:

> These projects are defined using the short form definition. You can use this form if you **only** want to declare the version of the project.

And indeed, passing this to `drush make-convert`...
```
projects[field_inspector][version] = "1.0-beta2"
projects[field_inspector][patch][] = "https://www.drupal.org/files/1821316-add-groups-support-to-inspector.patch"
```
...produces what is expected:
```
  field_inspector:
    version: 1.0-beta2
    patch:
      - 'https://www.drupal.org/files/1821316-add-groups-support-to-inspector.patch'
```
Feel free to close this issue as wont-fix if desired, as there is an easy workaround, and the condition which uses the short form with an additional property is technically not valid (though it executes as expected using `drush make`).  I'm mostly submitting this here to document this.

**Comment by weitzman** [comment]
ping @grasmash

**Comment by grasmash** [comment]
I'd be inclined to mark this as "won't fix" since the unsupported format is documented as invalid.
