### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Your environment or operation system isn't supported' in phar:///usr/bin/drush/vendor/webmozart/path-util/src/Path.php:257

### ISSUE THREAD

**Issue by MradulaPai** [drush-ops/drush#2405]
I am trying automate the Dkan installation on Elastic Beanstack. 
After every required installation,
If i run drush si dkan --verbose --account-pass='admin' --site-name='EIC' install_configure_form.update_status_module="'array(FALSE,FALSE)'" --yes 
is working throwing below error. 
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Your environment or operation system isn't supported' in phar:///usr/bin/drush/vendor/webmozart/path-util/src/Path.php:257

But manually above command working fine. Need some help here.

**Comment by weitzman** [comment]
Whats you OS and version of that OS?

```
/**
     * Returns canonical path of the user's home directory.
     *
     * Supported operating systems:
     *
     *  - UNIX
     *  - Windows8 and upper
     *
     * If your operation system or environment isn't supported, an exception is thrown.
     *
     * The result is a canonical path.
     *
     * @return string The canonical home directory
     *
     * @throws RuntimeException If your operation system or environment isn't supported
     *
     * @since 2.1 Added method.
     */
    public static function getHomeDirectory()
    {
        // For UNIX support
        if (getenv('HOME')) {
            return static::canonicalize(getenv('HOME'));
        }

        // For >= Windows8 support
        if (getenv('HOMEDRIVE') && getenv('HOMEPATH')) {
            return static::canonicalize(getenv('HOMEDRIVE').getenv('HOMEPATH'));
        }

        throw new RuntimeException("Your environment or operation system isn't supported");
    }
```

**Comment by MradulaPai** [comment]
Hi i am using AWS elastic bean stack with php 5.6.25 64 bit amazon linux v2.1.7

**Comment by MradulaPai** [comment]
can you please explain

**Comment by weitzman** [comment]
The next version of Drush will no longer error like you are seeing.

**Comment by MradulaPai** [comment]
Thank you for that. But i am using drush from https://s3.amazonaws.com/files.drush.org/drush.phar

**Comment by MradulaPai** [comment]
is update is applicable for this too?

**Comment by MradulaPai** [comment]
Commands for installing drush i am using:
php -r "readfile('https://s3.amazonaws.com/files.drush.org/drush.phar');" > /usr/bin/drush
sudo chmod +x /usr/bin/drush
su -s "/bin/bash" -g "apache" -c "/usr/bin/drush core-status" $projectuser
su -s "/bin/bash" -g "apache" -c "/usr/bin/drush init" $projectuser

**Comment by MradulaPai** [comment]
Hi, I have did the Dkan-Drupal setup once again, still getting the same error.

**Comment by MradulaPai** [comment]
We are taking Drush from 
php -r "readfile('https://s3.amazonaws.com/files.drush.org/drush.phar');" > /usr/bin/drush

**Comment by terao** [comment]
hi @weitzman !
thank you for fix it!
When  the next version is released?
We are very troubled by not move the automatic installation.

**Comment by kamalkech** [comment]
@MradulaPai : 

PHP Warning:  readfile(https://s3.amazonaws.com/files.drush.org/drush.phar): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
 in Command line code on line 1

**Comment by Rakeshsivagouni** [comment]
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Your environment or operation system isn't supported' in /home/ec2-user/.composer/vendor/webmozart/path-util/src/Path.php:257

I am also facing the error.I have downloaded drush directly  and drupal copied from S3

**Comment by Rakeshsivagouni** [comment]
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Your environment or operation system isn't supported' in /home/ec2-user/.composer/vendor/webmozart/path-util/src/Path.php:257
Stack trace:
#0 /home/ec2-user/.composer/vendor/drush/drush/drush.php(57): Webmozart\PathUtil\Path::getHomeDirectory()
#1 /home/ec2-user/.composer/vendor/drush/drush/drush(4): require('/home/ec2-user/...')
#2 {main}
  thrown in /home/ec2-user/.composer/vendor/webmozart/path-util/src/Path.php on line 257

**Comment by thirdender** [comment]
Elastic Beanstalk hooks are run as `nobody`, so you need to export a value for `HOME` before running drush.

```
files:
  "/opt/elasticbeanstalk/hooks/appdeploy/post/91_drupal_uuid.sh":
    mode: "000755"
    owner: root
    group: root
    content: |
      #!/bin/sh

      # Set $HOME to prevent https://github.com/hechoendrupal/drupal-console-core/issues/255
      export HOME=/var/www/html

      # Get configured Drupal environment variables from Elastic Beanstalk
      # before running Drush
      keys=( RDS_HOSTNAME RDS_PORT RDS_DB_NAME RDS_USERNAME RDS_PASSWORD DRUPAL_HASH_SALT DRUPAL_SYNC_DIR )
      for key in "${keys[@]}"
      do
        export $key=`/opt/elasticbeanstalk/bin/get-config environment -k $key`
      done

      # Set site UUID
      /var/www/html/vendor/bin/drush --root=/var/www/html -y config-set "system.site" uuid "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
```
