### ISSUE TITLE
Menu links loose their "active/is-active" class when running "drush cr" on the console

### ISSUE THREAD

**Issue by gceja1** [drush-ops/drush#2409]
_We are using:_
Drupal core 8.2.1
Standard Profile
_We tried different versions of Drush and got the same results:_
Drush 8.1.3, 8.1.5 and 8.1.6

**Description of the issue:**
When we run "drush cr" on the command line to clear the cache, the menu links that are linked to an alias loose the "active/is-active" class.

**Steps to Reproduce:**
1. First create a menu with a link to an alias, for example: "/contact"
2. Then add some css class to make the active link bold in the menu
3. Test that the active class is working when visiting the link
4. Run the "drush cr" command on the console
5. Refresh the page and check that the "active/is-active" class has disappeared from the active link and its no longer highlighted

**Note:** This issue only occurred when we updated to Drupal 8.2.1, before we had Drupal 8.1.10 and Drush 8.1.3 and this issue didn't occur

**Comment by weitzman** [comment]
Thanks for the excellent bug report. This was just fixed in #2393. A new Drush release will be coming soon.
