### ISSUE TITLE
Fail with Installation through Composer on Ubuntu 16.04

### ISSUE THREAD

**Issue by ArtuGit** [drush-ops/drush#2410]
I use an official instruction
http://www.drush.org/en/master/install-alternative/#install-a-global-drush-via-compose

Chapter: Install Drush for all users via Composer

I get this errors list:

root@Desktop:/opt/drush-8.x# drush
PHP Fatal error:  Uncaught ReflectionException: Class DOMDocument does not exist in /opt/drush-8.x/vendor/consolidation/output-formatters/src/Transformations/DomToArraySimplifier.php:24
Stack trace:
#0 /opt/drush-8.x/vendor/consolidation/output-formatters/src/Transformations/DomToArraySimplifier.php(24): ReflectionClass->isSubclassOf('DOMDocument')
#1 /opt/drush-8.x/vendor/consolidation/output-formatters/src/FormatterManager.php(339): Consolidation\OutputFormatters\Transformations\DomToArraySimplifier->canSimplify(Object(ReflectionClass))
#2 /opt/drush-8.x/vendor/consolidation/output-formatters/src/FormatterManager.php(177): Consolidation\OutputFormatters\FormatterManager->canSimplifyToArray(Object(ReflectionClass))
#3 /opt/drush-8.x/vendor/consolidation/output-formatters/src/FormatterManager.php(172): Consolidation\OutputFormatters\FormatterManager->isValidDataType(Object(Consolidation\OutputFormatters\Formatters\StringFormatter), Object(ReflectionClass))
#4 /opt/drush-8.x/vendor/consolidation/output-formatters/src/FormatterM in /opt/drush-8.x/vendor/consolidation/output-formatters/src/Transformations/DomToArraySimplifier.php on line 24

Drush command terminated abnormally due to an unrecoverable error.                                         [error]
Error: Uncaught ReflectionException: Class DOMDocument does not exist in
/opt/drush-8.x/vendor/consolidation/output-formatters/src/Transformations/DomToArraySimplifier.php:24
Stack trace:
#0 /opt/drush-8.x/vendor/consolidation/output-formatters/src/Transformations/DomToArraySimplifier.php(24):

ReflectionClass->isSubclassOf('DOMDocument')
#1 /opt/drush-8.x/vendor/consolidation/output-formatters/src/FormatterManager.php(339):

Consolidation\OutputFormatters\Transformations\DomToArraySimplifier->canSimplify(Object(ReflectionClass))
#2 /opt/drush-8.x/vendor/consolidation/output-formatters/src/FormatterManager.php(177):

Consolidation\OutputFormatters\FormatterManager->canSimplifyToArray(Object(ReflectionClass))
#3 /opt/drush-8.x/vendor/consolidation/output-formatters/src/FormatterManager.php(172):

Consolidation\OutputFormatters\FormatterManager->isValidDataType(Object(Consolidation\OutputFormatters\Formatters\StringFormatter),
Object(ReflectionClass))
#4 /opt/drush-8.x/vendor/consolidation/output-formatters/src/FormatterM in

/opt/drush-8.x/vendor/consolidation/output-formatters/src/Transformations/DomToArraySimplifier.php, line 24
root@Desktop:/opt/drush-8.x#

**Comment by weitzman** [comment]
Can you paste the output of `php --version`

**Comment by ArtuGit** [comment]
Initially, I installed the standard variant which was offered me from a command line.
Then I installed the version according to an Digital Ocean instruction without Apache and MySQL.

_PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies_

**Comment by axel-rutz** [comment]
Greg has answered this [on SO](https://drupal.stackexchange.com/questions/218268/drush-8-installed-with-composer-gives-uncaught-reflectionexception-class-dom): 

> sudo apt-get install php-xml

Let's make this a feature request (separate ticket?): 
_Print informative message if php-xml extension missing_

**Comment by weitzman** [comment]
Maybe add comment to #1371

**Comment by ArtuGit** [comment]
It works for me.
Thank you very much.

I agree that a separate ticket will be useful.
