### ISSUE TITLE
Root relative paths in site aliases

### ISSUE THREAD

**Issue by axel-rutz** [drush-ops/drush#2411]
When using a home-relative (important here) root path, the path is duplicated. Experienced on 8.1.6 and today's dev.

See "current/docroot/current/docroot" below.

```
$ drush rsync @project.live.default:%files @project.live-new.default:%files -v
You will delete files in user@host:current/docroot/current/docroot/sites/default/files and replace with data from user@oldhost:/foo/sites/default/files/
```

```
$ drush sa @project.live-new.default
$aliases["project.live-new.default"] = array (
  'uri' => 'http://uri',
  'root' => 'current/docroot',
  'remote-host' => 'host',
  'remote-user' => 'user',
);
```

**Comment by weitzman** [comment]
Are you using latest dev on both sides of the rsync? Please post both `sa --full` for both aliases.

**Comment by axel-rutz** [comment]
Lools like the root cause is in drush_sitealias_evaluate_path().

If i set %files explicitly to 'foo', the path is "corrent/docroot/current/docroot/foo".

**Comment by axel-rutz** [comment]
> Are you using latest dev on both sides of the rsync?

[renner@serpens docroot]$ drush @weinkauf.live-new.default version
 Drush Version   :  8.2-dev 

[renner@serpens docroot]$ drush @weinkauf.live.default version
 Drush Version   :  8.1-dev

**Comment by axel-rutz** [comment]
> Please post both sa --full for both aliases.

```
$ drush sa @weinkauf.live-new.default --full
$aliases["weinkauf.live-new.default"] = array (
  'uri' => 'http://uri',
  'root' => 'current/docroot',
  'remote-host' => 'host.freistilbox.net',
  'remote-user' => 'user',
  'php' => 'php5.6',
);
$ drush sa @weinkauf.live.default --full
$aliases["weinkauf.live.default"] = array (
  'uri' => 'https://uri',
  'root' => '/app/public',
  'remote-host' => 'ssh.eu.platform.sh',
  'remote-user' => 'foo-master',
);

```

**Comment by axel-rutz** [comment]
Debugging shows this is the code indrush_sitealias_evaluate_path() that does the duplication. Alas, i'm too far from gromking the logic there to suggest a fix.
```
  // Next make the rsync path, which includes the machine
  // and path components together.
  // First make empty paths or relative paths start from the drupal root.
  if (empty($path) || (!drush_is_absolute_path($path, "LOCAL"))) {
    $path = $drupal_root . $path;
  }

```

**Comment by weitzman** [comment]
This has come up in a few issues. Maybe @greg-1-anderson can spot the problem and know where to fix. Also see #2324

**Comment by greg-1-anderson** [comment]
Drush does not support relative paths for `root`.  Supporting relative paths here would be antithetical to the purpose of an alias, which is to provide a reference to a specific site that works regardless of your current working directory.  I am not really in favor of officially making this a supported configuration; however, the workaround would be to call `getcwd()` in your alias file, and compose your own path in your alias.  e.g. `'root' => getcwd() . '/current/docroot',`.

I also think that the workaround is a bad idea, but it would work as well as could be expected (which IMO is not very well).

**Comment by weitzman** [comment]
Should we throw an exception or error when we read such a malformed root?

**Comment by greg-1-anderson** [comment]
I think that failing fast might be appropriate here; however, the guard would have to be well-placed. --root on the command line might be relative, and that should be allowed. It might be overly diligent to stop execution for any alias merely loaded that contains a relative document root; besides, some might choose to store their alias roots as relative paths, and then use an alias alter hook to provide the base path. So, if such a check is included, it would have to be right before the alias was used, after it was altered.  I'm not convinced it's worth the effort to do it at this point. Maybe the object-oriented implementation of aliases could have a `validate` method that could do tests like this.

**Comment by axel-rutz** [comment]
> Drush does not support relative paths for root.
SSH treats them as relative to user-root, and i use them with many other drush commands.
(It's just this case that fails.)
And if we remove one of the two duplicate code blocks mentioned above, then rsync will do too.

I'd request keeping this behavior as it can strongly simplify aliases. (I have providers here that have no less than 7 path components in a user-root =:-() And the server knows its user-root so why duplicate that.)

**Comment by greg-1-anderson** [comment]
You'd be better off changing your aliases to use `'root' => getcwd() . '/current/docroot',`, in case Drush rejects relative roots in the future.

I'm not in a big hurry to break this feature, though.

**Comment by greg-1-anderson** [comment]
Old issue; closing.
