### ISSUE TITLE
Expected behavior of drush make during update process

### ISSUE THREAD

**Issue by uberhacker** [drush-ops/drush#2414]
I have noticed that using `drush make` to perform Drupal contrib module updates in Drupal 7 leaves residue behind.  The expected behavior is to clear out the previous contrib module code from the project directory, download the release as requested in the .make file and update in the same manner as `drush pm-updatecode` would execute.  However, what `drush make` does currently is create a temporary `destination` directory and then moves the code to the existing contrib module directory later in the process.  This seems to be consistent with all versions of Drush that are compatible with Drupal 7.  It is repeatable and can be reproduced by diff-ing the directories of a fresh download of the contrib module version being updated and the resulting code changes in the `sites/*/modules/contrib` project directory.

**Comment by uberhacker** [comment]
I noticed if I change `commands/make/make.project.inc` and override the temporary directory as shown below, I get the expected behavior.
<code>
 /**
  * The base project class.
  */
 class DrushMakeProject {
...
   /**
    * Determine the location to download project to.
    */
   function findDownloadLocation() {
-     $this->path = $this->generatePath();
+     $this->path = $this->generatePath(FALSE);
</code>

**Comment by uberhacker** [comment]
As an attempt to get more traction on this important issue, below is a real life example of the problem in action.
project.make before:
```
projects[addressfield][version] = 1.0-beta5
```
project.make after:
```
projects[addressfield][version] = 1.2
```
diff of fresh download of addressfield-7.x-1.2 directory vs the sites/all/modules/contrib/addressfield directory:
```
Only in /project/sites/all/modules/contrib/addressfield/example/plugins/format: addressfield-example.inc
```

**Comment by uberhacker** [comment]
Can one of the maintainers please explain the purpose of `drush make` downloading into a temporary directory prior to moving the code to the contrib project directory?  Just trying to wrap my mind around why this is even needed.

**Comment by uberhacker** [comment]
I have attached a patch which applies cleanly on drush versions 5-9.

[drush-make-2414.patch.txt](https://github.com/drush-ops/drush/files/590379/drush-make-2414.patch.txt)

**Comment by greg-1-anderson** [comment]
Make is deprecated. Closing old issues.
