### ISSUE TITLE
Declaration of Drush\Command\DrushInputAdapter::hasParameterOption() must be compatible with Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false)

### ISSUE THREAD

**Issue by djdevin** [drush-ops/drush#2415]
From the 8.1.7 phar.
```
Drush command terminated abnormally due to an unrecoverable error.                                                                                   [error]
Error: Declaration of Drush\Command\DrushInputAdapter::hasParameterOption() must be compatible with
Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false) in
phar:///usr/local/bin/drush/lib/Drush/Command/DrushInputAdapter.php, line 27
The external command could not be executed due to an application error.                                                                              [error]
PHP Fatal error:  Declaration of Drush\Command\DrushInputAdapter::hasParameterOption() must be compatible with Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false) in phar:///usr/local/bin/drush/lib/Drush/Command/DrushInputAdapter.php on line 27
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/drush:0
PHP   2. require() /usr/local/bin/drush:10
PHP   3. drush_startup() phar:///usr/local/bin/drush/drush:114
PHP   4. drush_run_main() phar:///usr/local/bin/drush/includes/startup.inc:365
PHP   5. drush_main() phar:///usr/local/bin/drush/includes/startup.inc:458
PHP   6. Drush\Boot\BaseBoot->bootstrap_and_dispatch() phar:///usr/local/bin/drush/includes/preflight.inc:66
PHP   7. drush_dispatch() phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php:67
PHP   8. call_user_func_array:{phar:///usr/local/bin/drush/includes/command.inc:199}() phar:///usr/local/bin/drush/includes/command.inc:199
PHP   9. drush_command() phar:///usr/local/bin/drush/includes/command.inc:199
PHP  10. _drush_invoke_hooks() phar:///usr/local/bin/drush/includes/command.inc:231
PHP  11. spl_autoload_call() phar:///usr/local/bin/drush/includes/command.inc:353
PHP  12. Composer\Autoload\ClassLoader->loadClass() phar:///usr/local/bin/drush/includes/command.inc:353
PHP  13. Composer\Autoload\includeFile() phar:///usr/local/bin/drush/vendor/composer/ClassLoader.php:301
PHP  14. include() phar:///usr/local/bin/drush/vendor/composer/ClassLoader.php:414
Drush command terminated abnormally due to an unrecoverable error.                                       
```

**Comment by djdevin** [comment]
Doesn't happen in 9.x-dev, so maybe a non-issue.

**Comment by stmh** [comment]
Why is this closed? Happens on 8.x after a fresh install via composer.

**Comment by weitzman** [comment]
Compare the parameters for each of these versions of Symfony Console

http://api.symfony.com/2.8/Symfony/Component/Console/Input/InputInterface.html#method_hasParameterOption
(1 param)
http://api.symfony.com/3.1/Symfony/Component/Console/Input/InputInterface.html#method_hasParameterOption
(2 params)

Drush 8 depends on Symfony Console version 2.8 and in the case of the Phar,
it ships with that inside. This is the same version that Drupal 8.2 depends
on.

I'm not sure where you are getting that Console version 3 from. Thats
really messing things up.

**Comment by stmh** [comment]
Going back to 8.1.4 fixed the problem

**Comment by itafroma** [comment]
This winds up being problematic for any use-case where you use Symfony console version 3, like if you're developing/using modules in Drupal 7 (which has no declared Symfony Console 2.8 requirement) that use it. Any reason the change in depednencies was added to a patch version insead of at least 8.2.0?

@stmh From my testing, Drush 8.1.5 is also free from this problem.

**Comment by DuaelFr** [comment]
I had the issue today with drush 8.2-dev. 
I upgraded to Drush 9 to fix the problem.

**Comment by djdevin** [comment]
I closed it because I thought my Drush was just too old to work with composer.

Seems like #2474 is the issue.

**Comment by SUN123RAY** [comment]
I upgraded to Drush 9 beta, but not improving. Showing the same error.

**Comment by greg-1-anderson** [comment]
@SUN123RAY Maybe Drush 9 is redispatching to an old version of Drush 8. If your target site is composer-managed, check your composer.lock and see what version of Drush is installed. Update to 8.1.15 or 9.

**Comment by SUN123RAY** [comment]
@greg-1-anderson Thanks for your comment.
 I have tried to find Drush in my composer.lock, but I did not get.  my
composer.lock file is attached here.

**Comment by SUN123RAY** [comment]
[composerlock.txt](https://github.com/drush-ops/drush/files/1455284/composerlock.txt)

**Comment by SUN123RAY** [comment]
@greg-1-anderson 
[composerlock.txt](https://github.com/drush-ops/drush/files/1455286/composerlock.txt)

**Comment by SUN123RAY** [comment]
sorry @greg-1-anderson I think I have checked in wrong composer.lock. OK here is the correct one attached.
I have checked 
grep "drush" composer.lock 
            "name": "drush/drush",
                "url": "https://github.com/drush-ops/drush.git",
                "url": "https://api.github.com/repos/drush-ops/drush/zipball/c9e6ac15b88d9329f560e90cc6c801b9b7859ad7",
                "drush"
            "homepage": "http://www.drush.org",
        "drush/drush": 10
[composer.lock.txt](https://github.com/drush-ops/drush/files/1455351/composer.lock.txt)
