### ISSUE TITLE
archive-dump assumes happy path

### ISSUE THREAD

**Issue by skwashd** [drush-ops/drush#2425]
When calling `drush archive-dump` it is assumed that the gzip operation always succeeds. I have been trying to track down random failures with the gzip step. While tracking this down I discovered that drush never checks the return of the [`drush_shell_exec()` call for the gzip operation](https://github.com/drush-ops/drush/blob/8.x/commands/core/archive.drush.inc#L289). 

The lack of checking the response means that when the gzip step fails drush never cleans up the tar file or reports that the command failed.

Is something like this an acceptable fix?

```php
if (!drush_shell_exec("gzip --no-name -f %s", $destination)) {
  // Clean up the tar file
  drush_register_file_for_deletion($destination);
  return drush_set_error(DRUSH_APPLICATION_ERROR, dt('Failed to gzip @destination', ['@destination' => $destination]));
}
```

**Comment by weitzman** [comment]
Thanks @skwashd. Merged to 8.x and master.
