### ISSUE TITLE
Drush commands output resize

### ISSUE THREAD

**Issue by ccharlton** [drush-ops/drush#2429]
Is there an easy way to resize (widen) the commands column when listing commands?

I've noticed some commands for important modules are verbose (eg. `migrate-fields-destination`), and while the commands wrap (and many have short aliases), I can't fight the feeling that we're entering a new phase of Drush where the commands/plugins list is so huge that the narrow width rendering of commands is dated.

**Comment by weitzman** [comment]
Agree that some usability here is needed. I propose to discuss in #1034
