### ISSUE TITLE
Weird loop running drush with a site alias in the same machine

### ISSUE THREAD

**Issue by skuark** [drush-ops/drush#2431]
I have the next scenario:

A d8 site managed with composer. 

```
- /var/www/d8site/
| - web/
| | - ...
| - vendor/
| | - bin/
| | | - drush
```

A d7 site managed also with composer.

```
- /var/www/d7site/
| - web/
| | - ...
| - vendor/
| | - bin/
| | | - drush
```

Both are drush 8.1.7.

Then, I have the next drush alias in `/root/.drush/project.dev.aliases.drushrc.php`:

```php
$aliases['d7site'] = array(
  'host' => '127.0.0.1',
  'root' => '/var/www/d7site/web',
  'uri' => 'd7site.dev',
  'path-aliases' => array(
    '%drush-script' => '/var/www/d7site/vendor/bin/drush'
  )
);
```

When I run drush from the same machine:

```
$> /var/www/d8site/vendor/bin/drush @project.dev.d7site -v
Loaded alias @project.dev.d7site from file /root/.drush/project.dev.aliases.drushrc.php                                              [notice]
Begin redispatch via drush_invoke_process().                                                                                              [notice]
Calling proc_open(env COLUMNS=146 /var/www/d7site/vendor/bin/drush  --root=/var/www/d7site/web --uri=project.dev --verbose   2>&1);
Begin redispatch via drush_invoke_process().                                                                                              [notice]
Calling proc_open(env COLUMNS=146 /var/www/d7site/vendor/bin/drush  --root=/var/www/d7site/web --uri=project.dev --verbose  help 2>&1);
Begin redispatch via drush_invoke_process().                                                                                              [notice]
Calling proc_open(env COLUMNS=146 /var/www/d7site/vendor/bin/drush  --root=/var/www/d7site/web --uri=project.dev --verbose  help 2>&1);
Begin redispatch via drush_invoke_process().                                                                                              [notice]
Calling proc_open(env COLUMNS=146 /var/www/d7site/vendor/bin/drush  --root=/var/www/d7site/web --uri=project.dev --verbose  help 2>&1);
Begin redispatch via drush_invoke_process().                                                                                              [notice]
Calling proc_open(env COLUMNS=146 /var/www/d7site/vendor/bin/drush  --root=/var/www/d7site/web --uri=project.dev --verbose  help 2>&1);
…
```

The process never ends, printing both lines repeatedly in a loop, and the machine memory usage never stops increasing.

However, if I run:

```
$> /var/www/d7site/vendor/bin/drush @project.dev.d7site -v
Loaded alias @project.dev.d7site from file /root/.drush/project.dev.aliases.drushrc.php                                        [notice]
Executing: mysql --defaults-extra-file=/tmp/drush_VC8yFD --database=d7site --host=127.0.0.1 --silent  < /tmp/drush_3rzJf0
Executing: mysql --defaults-extra-file=/tmp/drush_Ayi1yU --database=d7site --host=127.0.0.1 --silent  < /tmp/drush_dJBh7g
$> 
```

It's weird because both are the same drush version. Anyway, I understand that it's a very particular scenario.

**Comment by weitzman** [comment]
using site aliases for local sites is discouraged and will be removed one day.

**Comment by skuark** [comment]
I didn't know it was discouraged. Is it documented anywhere?

I am using drush aliases in a Drupal multisite, for local and remote sites across multiple environments. Among others tasks, in the local environment drush aliases are really useful to be able to run drupal cron across all the sites with a system cron job. For example, in production we run cron in a concurrent way (2 tasks at the same time) with a cron job like this:

```
0 7,15,23 * * * drush @project.production cron -y --concurrency=2 --strict=0
```

What's the way to go in that scenario? I could prepare a script with n `drush -l site-n.com` commands (one for each site), and keep it updated when adding new sites to multisite, but then it would not be possible to run it in a concurrent way?

Sorry for converting that issue into a support request, I could move that question into another place if you have an official channel for that kind of questions.

**Comment by weitzman** [comment]
Sorry its not documented anywhere besides a few comment threads like this one. 

To be honest, we are also considering deprecating site lists and concurrency. See #975. Thanks for using all the fancy Drush features :). Unfortunately not enough people use them to justify the (substantial) maintenance.

**Comment by skuark** [comment]
Ok, I understand. I don't know if technically possible, but It would be nice if that functionality (concurrency and site lists) could be extracted to a contrib module, instead of been removed, for those users using these fancy features ;)

Thanks.
