### ISSUE TITLE
Meta-issue for various pm related fixes

### ISSUE THREAD

**Issue by AdamPS** [drush-ops/drush#2438]
I hope this issue will help everyone get a clear shared understand of the future of drush and pm.

Pulling together what I have learnt from reading other issues:
- SVN support will be dropped in Drush 9 according to @weitzman in #2021.
- pm-updatecode is to some degree deprecated in favour of  https://github.com/drupal-composer/drupal-project.  Maintainer @weitzman states in #2275 "that's how all D8+ sites should be built and even D7 sites should consider it."

There are various pm issues still open.  I appreciate the maintainers don't want to spend time fixing them.  However I have written patches in a couple of PRs that contain fixes.  Is there any chance please that the maintainers would consider at least taking the time to review and merge pm fixes?  D7 still has quite a few years of life left in it.  Secondary question: some of my fixes include removal of redundant outdated code - is this tidy up useful, or would you prefer minimal safer patches?

At the moment, how does anyone using drush pm know that it is deprecated and composer is preferred?  Can we add to the help text of pm-updatecode - especially if running D8?  If PRs for pm are no longer accepted except for high severity, please can we try to communicate this as clearly as possible?  Another thing we can do is to comment in all the outstanding issues to inform people not to waste their time creating a PR.

Thanks!

**Comment by AdamPS** [comment]
For anyone reading this thread: drush pm is dying.  The maintainers no longer want to make fixes, and eventually will remove support entirely.  Composer is the way forward and @weitzman states in #2275:

> I'll note that sites built with https://github.com/drupal-composer/drupal-project dont suffer from this problem, mainly because the dont use pm-updatecode. Thats how all D8+ sites should be built and even D7 sites should consider it.

I have added comments on several outstanding pm issues to discourage anyone from putting forward a PR.  I have closed my own issues and PRs for pm.

In drush 8.x, drush pm is usable provided you stick to the default options:

-     --version-control=backup
-     There is a backup (i.e. not --no-backup)

**Comment by weitzman** [comment]
Only small parts of pm are being deprecated. Namely, update code and dl. Those are code assembly functions better handled by Composer. Lot of pm like enable/uninstall/updatestatus/info/list will carry on.

**Comment by davekopecek** [comment]
During the transition from pm-update to a composer based solution ([#2614](https://github.com/drush-ops/drush/issues/2614)) could a warning of potential pm-update pitfalls be added to the command?  Currently Drupal Commerce requires a composer install.  Running pm-update on a site with commerce installed kills the site. 

If there's an easy way for pm-update to check for composer installed modules it would be great if it could issue a warning:
````
This site contains modules installed with composer.
Continuing will overwrite the vendor directory and waste the next hour of your life. Continue? (y/n) 
`````
 
... or something like that.
