### ISSUE TITLE
Setting --root flag when using aliases causes alias root to be overwritten

### ISSUE THREAD

**Issue by frankcarey** [drush-ops/drush#2442]
We place the site alias files from acquia in `/repo-root/docroot/sites/all/drush/.` and we have some scripts that call drush from `/repo-root/.` which requires adding `drush --root=docroot ..` for drush to find the local site.  It's also required for drush to find the site aliases.

When using both a site alias and `--root=` flag in the same command, it appears that the root is set incorrectly during the ssh call as well. This all works fine if I just `cd docroot` before running drush instead of setting the root, but this seems like a bug.

example:

Note the line `.. COLUMNS=204 drush8  --root=docroot ..` where the docroot gets overwritten from what is actually set in the alias file.

```
$ drush -v --root=docroot @mydrupal.prod status
Executing: cd docroot && git rev-parse --show-toplevel 2> /dev/null
Loaded alias @mydrupal.prod from file /var/www/docroot/sites/all/drush/mydrupal.aliases.drushrc.php                                                                                         [notice]
Begin redispatch via drush_invoke_process().                                                                                                                                                        [notice]
Calling proc_open(ssh -o PasswordAuthentication=no mydrupal.prod@###.acquia.com 'env COLUMNS=204 drush8  --root=docroot --verbose --uri=###.acquia-sites.com  core-status 2>&1' 2>&1);
Loading outputformat engine.                                                                                                                                                                        [notice]
 PHP executable         :  /usr/local/php5.6/bin/php
 PHP configuration      :  /usr/local/php5.6/etc/cli/php.ini
 PHP OS                 :  Linux
 Drush script           :  /usr/local/drush8/vendor/drush/drush/drush.php
 Drush version          :  8.1.3
 Drush temp directory   :  /mnt/tmp/###
 Drush configuration    :  /etc/drush/drushrc.php
 Drush alias files      :  /mnt/drush/testdrupald8/####.aliases.drushrc.php

Command dispatch complete                                                                                                                                                                           [notice]
End redispatch via drush_invoke_process().

```

**Comment by greg-1-anderson** [comment]
Use `--alias-path` rather than `--root` if your only purpose is to identify the location of alias files.  Commandline options take precedence over  alias contents by design.

**Comment by frankcarey** [comment]
Thanks for the clarification. I'll have to make a separate [ahoy](http://www.ahoycli.com/en/latest/) command that talks to production via the alias. 

Closing this as you answered my question, I appreciate it.

Food for thought.. It might be a nice features to have flags BEFORE the `@alias` refer to local drush and ones that come after refer to the alias.. like how would I handle doing an drush rsync for instance? ( I guess I can use a `@self` or a '@local` alias instead of setting `--root`? )
