### ISSUE TITLE
Drush master needs php-xml

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#2453]
e.g. on Debian:

sudo apt-get install php7.0-xml

Seems this is available by default when installing php via brew on a Mac.

The outputformatters project falis non-gracefully when this is not available, even when it is not in use. I can fix this in the upstream; however, I was planning on using php-xml DomDocuments to implement Drush help. Supporting xml format in help is important because Symfony does it, and ideally we remain compatible with Symfony Console when we drop in our own help.  If we support xml, then it is most convenient to use a DomDocument for the native representation of the help text, because it is relatively easy to convert from a DOM (attributes and children) to an array (lossy), but fairly difficult to convert a normalized array representation into a DOM. (You'd need a schema to determine what goes in attributes, and what goes in children.)

Hopefully this requirement is okay, as I would prefer to depend on the DomDocument class.

**Comment by weitzman** [comment]
Would be better if it were a 'suggest' versus a requirement. But in the end be OK with it.

**Comment by weitzman** [comment]
Drush is now depending on DomDocument for help. Not sure what we need to add to composer.json and elsewhere to verify this extension.

**Comment by weitzman** [comment]
Added to composer.json in 641b2a1
