### ISSUE TITLE
Declare formatter options in annotation_adapter

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2460]
The CSV formatter has an option --include-field-labels but thats unusable right now without also sending --strict=0.

**Comment by greg-1-anderson** [comment]
There are a bunch of options in [FormatterOptions](https://github.com/consolidation/output-formatters/blob/master/src/Options/FormatterOptions.php#L39,L50) that could potentially be useful if added on the commandline as options.  We can probably just add these as global options for now.
