### ISSUE TITLE
Unable to set site-name when site-install

### ISSUE THREAD

**Issue by terao** [drush-ops/drush#2462]
When site-install using drush, I Specified following --site-name option.
Then login to Drupal, Sitename was not set.
No error message was displayed.

```# Drupal site-install
drush -y si\
  --db-url=mysql://root@localhost/drupal\
  --locale=ja\
  --account-name='terao'\
  --account-pass='u8UMzKDP'\
  --account-mail='terao@example.com'\
  --site-name='drupal8-1' || exit 1
```

**Comment by weitzman** [comment]
OK. Next someone needs t debug and see if the bug is in Drupal or Drush.

**Comment by terao** [comment]
Hi weitzman,

Thankyou for reply.
I am looking forward to bug fix.

**Comment by diogoviannaaraujo** [comment]
Im having this problem, if i dont pass site-name it comes as "site-install" if I do it comes as "drupal" dont matter what I type

**Comment by weitzman** [comment]
What version of Drush and Drupal are you using @diogoviannaaraujo and @terao?
