### ISSUE TITLE
Timeline for next Drush release?

### ISSUE THREAD

**Issue by emilyshaw-acquia** [drush-ops/drush#2469]
@weitzman @greg-1-anderson any idea when the next release of Drush may be? I am specifically asking regarding this committed patch:
- [archive-dump assumes happy path #2425](https://github.com/drush-ops/drush/issues/2425) 

Thanks for any insight.

**Comment by Chi-teck** [comment]
#2425 should be included to Drush 8.1.8 which was released a couple weeks ago.
https://github.com/drush-ops/drush/compare/8.1.7...8.1.8
