### ISSUE TITLE
make file include order not being respected?

### ISSUE THREAD

**Issue by hanoii** [drush-ops/drush#2475]
I have the following example makefile:

```
includes:
  - URL1TOMAKEFILE.yml
  - URL2TOMAKEFILE.yml
  - URL3TOMAKEFILE.yml
  - local.make.yml
```

So, we have some common makefile definitions separate on three makefiles that I pulled form a repository, and then some local ones.

On an instance, I have a older project version defined on one of the remote makefiles, and then I override it on local.make.yml to a newer one. 

However, when I run drush make, the older version is retrieved. This used to work with other combinations of inclusions.

For instance, if I do:

```
includes:
  - local.make.yml
  - URL1TOMAKEFILE.yml
  - URL2TOMAKEFILE.yml
  - URL3TOMAKEFILE.yml
```

It does work, but this shouldn't be the case as per the docs.

```
includes:
  - URL1TOMAKEFILE.yml
  - URL2TOMAKEFILE.yml
  - URL3TOMAKEFILE.yml
  - local.make.yml

projects:
  # Doing the override here also works.
```

Bug?

**Comment by greg-1-anderson** [comment]
Make is deprecated. Closing old issues.
