### ISSUE TITLE
Give site-install an interactive mode.

### ISSUE THREAD

**Issue by serundeputy** [drush-ops/drush#2484]
If no `--db-url` option is specified drop into interactive shell prompts to get the required information form the user.

**Comment by serundeputy** [comment]
@greg-1-anderson I wonder if you'd be willing to take a look at this `PR`: https://github.com/drush-ops/drush/pull/2485

In the file: `site_install.drush.inc` I've introduced the `drush_prompt`'s if `--db-url` is empty.

```php
$db_spec['database'] = drush_prompt('Database name');
    $db_spec['driver'] = drush_prompt('Database driver', 'mysql');
    $db_spec['username'] = drush_prompt('Database username');
    $db_spec['password'] = drush_prompt('Database password');
    $db_spec['host'] = drush_prompt('Database host', 'localhost');
    $db_spec['port'] = drush_prompt('Database port', '3306');
    //$db_spec->db_prefix = drush_prompt('Database prefix', NULL);
    //return drush_sql_get_class($db_spec);
    $sql = drush_sql_get_class($db_spec);
```

That seems to get the `$db_spec` and either create the DB or drop the tables as necessary, but then I seem to have to repopulate the `$db_spec` in either `commands/core/drupal/site_install.inc` for D8 or `commands/core/drupal/site_install_7.inc` for D7.

There must be a way I can pass the `$db_spec` info through to those functions, but I can't figure it out ... you think you could give me some direction?

**Comment by weitzman** [comment]
In 8.x, you could try with drush_set_option('db-url, drush_sitealias_convert_db_spec_to_db_url($db_spec));

Note that we'll need PR for master branch first, and then can merge this into 8.x. Thanks for the great improvement.

**Comment by serundeputy** [comment]
@weitzman thanks!

re-rolled against `master`

https://github.com/drush-ops/drush/pull/2485

**Comment by weitzman** [comment]
This went in
