### ISSUE TITLE
Warnings when running drush

### ISSUE THREAD

**Issue by thwsllc** [drush-ops/drush#2487]
I am getting the following when I try to run any drush command on a system using Drush 8.1.7 any clues?

array_keys() expects parameter 1 to be array, boolean given annotationcommand_adapter.inc:764                                   [warning]
array_keys() expects parameter 1 to be array, boolean given annotationcommand_adapter.inc:765                                   [warning]
implode(): Invalid arguments passed annotationcommand_adapter.inc:766                                                           [warning]
implode(): Invalid arguments passed annotationcommand_adapter.inc:767                                                           [warning]

Thanks in advance.

**Comment by mike503** [comment]
same here. how did you fix it?

**Comment by hargobind** [comment]
Same issue reported in https://github.com/drush-ops/drush/issues/3576
