### ISSUE TITLE
drush make can't update core in different directory

### ISSUE THREAD

**Issue by IslandUsurper** [drush-ops/drush#2500]
If the `build_path` argument to `drush make` isn't specified, it runs in the current directory but asks to make sure you want to overwrite anything in it. If `build_path` is specified, and it exists, Drush refuses to run unless you also specify `--no-core` (per #919 and #920).

Why does it do different things? I don't want to leave my whole site's make file in the web root, but I think Drush Make is a good way for me to keep Drupal updated when a minor version comes out. Currently, I have to make sure any semi-automated process's current directory is the Drupal root before it runs Drush Make, which seems like an unnecessary limitation.

Now, I think the confirmation question if `build_path` exists is a good idea, because users need to know it's a potentially destructive operation. A script can easily add `-y` to the invocation to get around it.

**Comment by greg-1-anderson** [comment]
Make is deprecated. Closing old issues.
