### ISSUE TITLE
Bug: Config Export not working for single translation items

### ISSUE THREAD

**Issue by lovelyhomie** [drush-ops/drush#2504]
Hi there,

I got a particular problem with "drush cex".

The site is in English (Default) and German

I have a translated View item for a view called views.view.project_list and I translated some labels for that. In the Synchronize tab inside Drupal it is showing I have one changed item but if I do a 

`drush -y cex`

 it still says "The active configuration is identical to the configuration in the export directory (../drupal-config/sync)."

...which is NOT true.

How I can still export that single translation item?

**Comment by weitzman** [comment]
Was fixed by #2939 I think.
