### ISSUE TITLE
drush override of Drupal database

### ISSUE THREAD

**Issue by drzraf** [drush-ops/drush#2509]
(see also https://www.drupal.org/node/1335626)
I would like to setup a Drush for some maintenance operation (creating a cleaned/scrubbed version of the database to use in -preprod).
This operation needs read-only access to production database and read-write access to temporary database.

For security reasons (most notably avoiding humans error) I would like Drush to use another MySQL user than the one specified in the site's settings.php.

I thus set:
```
$ drush8 @prod st --fields=db-username,db-status
 Database username   :  mysite
 Database            :  Connected
 $ drush8 @roprod st --fields=db-username,db-status
 Database username   :  readonly
 Database            :  Connected
```
After having put `` 'databases' => array('default' => array('default' => array ('...')))`` in the ``roprod`` alias.
But actually I didn't setup a "readonly" mysql account.

Conclusion:
* ``drush st`` shows the value of the ``databases`` variable in the alias
* but it does not actually override the value used by Drupal
So it appears to not be possible + the current output is misleading.

Does a practicable way to do such an override currently exist?

**Comment by weitzman** [comment]
Not supported anymore. Removed in #831
