### ISSUE TITLE
Change $_SERVER['REQUEST_METHOD'] default to 'GET'

### ISSUE THREAD

**Issue by kentr** [drush-ops/drush#2511]
### Problem / Motivation

After upgrading core from 8.1.x to 8.2.4, I'm experiencing issues with menu items when enabling / disabling modules via drush:

The `menu_tree` table becomes corrupted for menu items that were created with a path alias as the value for **Link**, and the active menu item isn't set correctly in the page output.

#### Setup

1. Assign a path alias to a node.
2. Create a menu item, using that path alias in the `Link` field.
3. Go to the node page in the browser.  The menu item should be highlighted as "active".
4. Observe the `menu_tree` table with the following query.  There should be a record with the new menu item, and the record should have `route_name = 'entity.node.canonical'`, the node id in `route_param_key` & `route_parameters`:

```sql
-- JOINS on `menu_link_content` and `menu_link_content_data` are for convenience,
-- to view human-readable identifiers for the menu entry.
SELECT
  mt.menu_name
  , mt.mlid
  , mt.id
  , mt.route_name
  , mt.route_param_key
  , mt.route_parameters
  , mt.url
  , mlcd.title
  , mlcd.link__uri
FROM menu_tree mt
JOIN menu_link_content mlc
  ON CONCAT('menu_link_content:', mlc.uuid) = mt.id
JOIN menu_link_content_data mlcd
  ON mlcd.id = mlc.id
WHERE
  mt.id LIKE 'menu_link_content:%'
  AND
    (
      route_name IS NULL
      OR route_name = 'entity.node.canonical'
    )
ORDER BY
  route_name
  , route_param_key
```

#### Triggering the issue

1. Enable devel module via drush (tested with drush versions `8.2-dev` & `master`).
2. Reload the node page in the browser.  The menu item now isn't highlighted as "active".
3. Rerun the SQL query.  The record in the `menu_tree` table now has `route_name = NULL`, empty `route_param_key`, & empty `route_parameters`.

#### Repairing the `menu_tree` table

Either of these should correctly repopulate `menu_tree` and correct the menu item's "active" state in the browser:
* Execute `drush cr`.
* Enable / disabling devel via the UI.

I believe the first option works because [`CacheCommands::rebuild()` explicitly sets the request method to 'GET'](https://github.com/drush-ops/drush/blob/master/lib/Drush/Commands/core/CacheCommands.php#L183).

#### Explanation

1. If the _request's_ method is null, [`Request::getMethod()` falls back to the server's value, and performs `strtoupper()` on the value](https://github.com/symfony/http-foundation/blob/2.8/Request.php#L1289).
2. Due to the underlying [ParameterBag::get() implementation](https://github.com/symfony/http-foundation/blob/2.8/ParameterBag.php#L102), If the _server's_ value is <em>unset</em>, `Request::getMethod()` defaults to 'GET', however if the server value is <em>set</em>, `Request::getMethod()` uses it.
3. Since drush [sets `$_SERVER['REQUEST_METHOD']` to `NULL`](https://github.com/drush-ops/drush/blob/master/lib/Drush/Boot/DrupalBoot.php#L392), `Request::getMethod()` uses that and returns `strtoupper(NULL)`, which is `""` (empty string).
4. `MethodFilter::filter()` (added in [this commit](https://github.com/drupal/drupal/commit/af80cb499a04d15b5905d19e66c8d5a8efd9b293)?) rejects `""` as an invalid method and throws `MethodNotAllowedException`.
5. `PathValidator::getUrlIfValidWithoutAccessCheck()` then returns `FALSE` [here](https://github.com/drupal/drupal/blob/8.2.4/core/lib/Drupal/Core/Url.php#L413) and the resulting `$url` is incorrect.

### Suggested fix

Change the default `$_SERVER['REQUEST_METHOD']` to `GET`.  Isolated testing confirms that this fixes the issue (for the known symptoms: `menu_tree` and menu item "active" status).

#### Rationale

* `REQUEST_METHOD` is an HTTP spec and has no official meaning in the CLI context.  So, the use of `REQUEST_METHOD` for this context is arbitrary.
* Drush's `DrupalBoot::bootstrap_drupal_site_setup_server_global()` [claims to initialize `$_SERVER` to mimic a web request](https://github.com/drush-ops/drush/blob/master/lib/Drush/Boot/DrupalBoot.php#L352).  Since `GET` is among the most basic possible web request methods, it's fitting to use it as the default.

**Comment by weitzman** [comment]
What an excellent bug report! I plan to merge the PR. ping @Berdir in case he has any input.

**Comment by Berdir** [comment]
The referenced fix for variant 1 is based on https://github.com/drush-ops/drush/pull/2393.

Defaulting to GET does make sense to me.

**Comment by weitzman** [comment]
PR went into 8.x and master. Thanks.

**Comment by webflo** [comment]
The fix is is just a workaround, we could be reverted after the underlying core issue https://www.drupal.org/node/2822190 is fixed.
