### ISSUE TITLE
MAMP drush fails to install drupal 7 core

### ISSUE THREAD

**Issue by BastouBach** [drush-ops/drush#252]
I installed MAMP 2.0 and installed drush 6.1.0 using Pear. 

I did `drush dl drupal` which seemed successful. Then I proceeded to install using the browser window. I was able to enter the database information, but proceeding from there got a WSOD and the following php error message found in the php error log file: 

PHP Fatal error:  Call to undefined function field_attach_load() in .../includes/entity.inc on line 316

I then downloaded the ZIP file from drupal.org through the browser and everything installed fine.

**Comment by greg-1-anderson** [comment]
Please use [Drupal Answers](http://drupal.stackexchange.com/questions/tagged/drush) for support requests.
