### ISSUE TITLE
Use robo tasks in drush command

### ISSUE THREAD

**Issue by axel-rutz** [drush-ops/drush#2521]
I'd like to use robo tasks inside a drush command. 
(This looks non-trivial to me as robo does some $this magic)

**Comment by axel-rutz** [comment]
It looks like @greg-1-anderson might have some experience with this.

**Comment by axel-rutz** [comment]
For the records: The opposite issue (use drush tasks in robo) is done here:
https://github.com/boedah/robo-drush

**Comment by greg-1-anderson** [comment]
This is possible in the `master` branch of Drush, but not in Drush 8 (which does not `require` Robo).  See https://github.com/drush-ops/drush/blob/master/lib/Drush/Commands/core/InitCommands.php

**Comment by axel-rutz** [comment]
THX! i'm just groking the source right now. 
Any estimate when this lands in beta (hopefully before gnu herd)?
