### ISSUE TITLE
How to use @hook interact?

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2524]
Please advise on how to use @hook interact. We now have two non-functional instances of it. See WatchdogCommands and ImageCommands.

**Comment by greg-1-anderson** [comment]
`@hook interact` is called by the Symfony Console `interact` method during the Symfony Console command dispatch process, which Drush is not using. Beyond the fact that this is not implemented, the usage in WatchdogCommands is correct.

Hook interact is [called in AnnotatedCommand::interact()](https://github.com/consolidation/annotated-command/blob/2.2.2/src/AnnotatedCommand.php#L362). We simply need to call this method, or equivalent functionality, iff interaction has not been disabled. We also need to decide if -n should behave like Drush 8 or like Symfony Console. Terminus has both --yes and -n, the later of which behaves like Symfony Console. In SC, -n defaults most yes/no prompts to `yes`. Terminus defaults destructive prompts to `no` and the rest to `yes`.

**Comment by greg-1-anderson** [comment]
+1 LGTM looks like a good start

**Comment by weitzman** [comment]
We are now using this in a couple commands. Grep for `@hook interact`
