### ISSUE TITLE
Remove make from Drush9

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2528]
Per https://medium.com/@weitzman/drush-9-roadmap-9eb5cd227c50, we are removing make from Drush 9 and recommending that folks use Composer instead. This issue forms a plan for executing this.

- **Keep** ability for folks to convert to Composer from a makefile in ini or yaml format. Keep tests/makeConvertTest.php
- **Port** make-convert to Annotated.
- **Drop** everything else - Building, writing a lock file, make-generate, ...

Make will keep getting bug fixes in Drush 8, so folks have a long time to transition.

**Comment by weitzman** [comment]
Ping @grasmash, in case he is interested in taking this on.

**Comment by grasmash** [comment]
Since we're only supporting Composer moving forward, it would make sense to modify the `make-convert` command such that it only converts from .make or .make.yml to composer format. In that case, I'll remove the "format" option from the command.

**Comment by grasmash** [comment]
@weitzman What chat channel do you hang out in?

**Comment by weitzman** [comment]
Usually in #drush on IRC Freenode - I've just joined again after a brief
absence. Also I've been joining
https://pantheon-community.slack.com/archives/power-users

**Comment by weitzman** [comment]
Make was removed
