### ISSUE TITLE
'drush rsync' creates another inserted 'files' directory

### ISSUE THREAD

**Issue by ArtuGit** [drush-ops/drush#2529]
I perform 
'drush rsync @mysite.dev:%files @mysite.local:%files'
and Drush creates a '/sites/all/default/files/files' directory.

There is the superfluous 'files' directory ('/files/files').

Is it an idea or a lack of my aliases configuration?

---

Happy New Year!
It is time to find out it. ))
There a loss of time.

**Comment by derimagia** [comment]
Take a look at how rsync handles paths: http://qdosmsq.dunbar-it.co.uk/blog/2013/02/rsync-to-slash-or-not-to-slash/

**Comment by 2pha** [comment]
I'm pretty sure your command should be:
'drush rsync @mysite.dev:%files/ @mysite.local:%files'

**Comment by ArtuGit** [comment]
Thank you. it so flexibly.
