### ISSUE TITLE
Source and target databases are the same; please sync to a different target

### ISSUE THREAD

**Issue by kenpeter** [drush-ops/drush#2541]
Could anyone have a look at this for me?

https://drupal.stackexchange.com/questions/224477/drush-source-and-target-databases-are-the-same-please-sync-to-a-different-targ

**Comment by weitzman** [comment]
Possibly related #2522. I've seen this myself but not had time to dig in.

**Comment by morbus** [comment]
They look the same to me though, in this particular case, the poster expects the remote DSN to use the "remote-host" value defined in his (local) alias file when I suspect the remote host values are coming from the remote host's settings.php (which is why both DSNs are becoming the same, as both local and remote use "localhost" as the DB host).

**Comment by back-2-95** [comment]
For example this is an issue in scenario as follows:

I am migrating production to a new server, so I have 2 drush aliases for time being:
production: the current one
production_new: the new production server

They were both provisioned with the same mysql user and password, so when syncing database, it will give the error mentioned.

To by pass this now, I will use different password for production-new.

But the check functions might add check for site alias 'host' value? As the SSH configuration here is also one differentiating aspect.

Example:

```
drush_sitealias_convert_db_spec_to_db_url($source_db_spec)  
drush_sitealias_convert_db_spec_to_db_url($target_db_spec) 
```

Now they both return: `mysql://username:password@localhost:3306/databasename`

Maybe they could return: `ssh://remote-user@remote-host+mysql://username:password@localhost:3306/databasename` ?

**Comment by weitzman** [comment]
We removed this validation in #2589
