### ISSUE TITLE
How do contrib modules use annotated commands?

### ISSUE THREAD

**Issue by TravisCarden** [drush-ops/drush#2547]
I'd like to start using annotated commands in my contrib and custom modules, but it's not clear to me how to get started. I think I could add one to Drush itself based on the examples there, but in my own module I haven't gotten as far as command discovery. Does discovery depend on a certain namespace? directory structure? etc.? Are contrib authors meant to start using annotated commands yet? And, if so, could we get some documentation? Thanks!

**Comment by weitzman** [comment]
Yeah, we need to document this. See how the woot module does it in our tests - https://github.com/drush-ops/drush/blob/master/tests/resources/modules/d8/woot/woot.services.yml

**Comment by TravisCarden** [comment]
Thanks for the quick response, @weitzman! I just realized that annotated commands require a version of Drush newer than the latest tag. I don't want my commands to depend on something that most people won't have yet, so I'll hold off a little. If I have time, I may try to help with documentation anyhow.

**Comment by greg-1-anderson** [comment]
@TravisCarden The d8 branch of Drush supports the same annotated commands for Drupal 8 modules as the Drush master branch does for this very reason. However, Drush 8 does not use annotated commands internally.

**Comment by weitzman** [comment]
See devel (and its devel_generate submodule)
