### ISSUE TITLE
Undefined index: memory Logger.php:125

### ISSUE THREAD

**Issue by messageagency** [drush-ops/drush#2550]
Getting an "undefined index" for every hook_cron implementation (lines truncated for readability):

> Found command: core-cron (commandfile=core) [2.96 se ...
> Calling hook drush_core_cron [3.25 se ...
> Undefined index: memory Logger.php:125 [3.32 se ...
> Starting execution of comment_cron().  ...
> Undefined index: memory Logger.php:125 [3.38 se ...
> Starting execution of dblog_cron(), execution of comment_cron() took 49.57ms.  ...
> Undefined index: memory Logger.php:125 [3.4 se ...
> Starting execution of field_cron(), execution of dblog_cron() took 20.45ms.  ...
> Undefined index: memory Logger.php:125 [3.42 se ...
> Starting execution of file_cron(), execution of field_cron() took 7.26ms.  ...
> Undefined index: memory Logger.php:125 [3.5 se ...
> Starting execution of history_cron(), execution of file_cron() took 78.8ms.  ...
> Undefined index: memory Logger.php:125 [3.52 se ...
> Starting execution of node_cron(), execution of history_cron() took 10.32ms.  ...
> Undefined index: memory Logger.php:125 [3.58 se ...
> Starting execution of search_cron(), execution of node_cron() took 59.4ms.  ...
> Undefined index: memory Logger.php:125 [3.63 se ...
> Starting execution of system_cron(), execution of search_cron() took 47.11ms.  ...
> Undefined index: memory Logger.php:125 [3.77 se ...
> Starting execution of update_cron(), execution of system_cron() took 129.3ms.  ...
> Undefined index: memory Logger.php:125 [4.97 se ...
> Execution of update_cron() took 1187.84ms.  ...
> Undefined index: memory Logger.php:125 [4.98 se ...
> Cron run completed.  ...

is this due to my old PHP version? something else?

drush 8.1.9
PHP 5.5.31
OSX 10.10.5

**Comment by weitzman** [comment]
What version of Drupal? Also, is there any chance you have another Drush beside 8.1.9 somewhere on your $PATH?

**Comment by ummdorian** [comment]
I'm seeing this notice if I run drush with the debug command, drupal 8.2.5, drush 8.1.9, xampp
