### ISSUE TITLE
SQL-santize does not check field length prior to replacing values

### ISSUE THREAD

**Issue by seanhamlin** [drush-ops/drush#2556]
After the PR https://github.com/drush-ops/drush/pull/2457 got merged it is forcing all string fields (regardless of size) to be set to 255 characters when you do an sql-sanitize.

Ideally, sql-sanitize would set the length to be no more than the current column size in the database to avoid errors.

**Comment by weitzman** [comment]
Think this just got fixed in master

**Comment by seanhamlin** [comment]
I think this was the PR https://github.com/drush-ops/drush/pull/2586, thanks @weitzman !
