### ISSUE TITLE
Convert one core Drush command (user-delete?) to accept injected Drupal services

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2558]
See https://github.com/hechoendrupal/drupal-console/blob/master/config/services/drupal-console/user.yml. Also note https://www.drupal.org/node/2703131

**Comment by weitzman** [comment]
For contrib commands, we already have [woot.services.yml](https://github.com/drush-ops/drush/blob/master/tests/resources/modules/d8/woot/woot.services.yml) which demonstrates this.

**Comment by greg-1-anderson** [comment]
Related: #2539
