### ISSUE TITLE
Feature request add --preview=<format> option to cex - config-export

### ISSUE THREAD

**Issue by frederickjh** [drush-ops/drush#2563]
Hi !
Currently the `drush cim` command has the following option:
`--preview=<list>                          Format for displaying proposed changes. Recognized values: list, diff. Defaults to list.`

This is useful to get a diff of what will be imported. It would be helpful to have this same functionality in the `drush cex` so that a diff of what will be export can be seen. I know that I can do this with git after the configuration as be exported. Or is this not possible without a previous export? Maybe a temporary export to a tmp directory would make this possible.

Thanks for your consideration of this new feature.
Frederick

**Comment by weitzman** [comment]
I've wanted this as well. Hope someone finds time to add it.

**Comment by frederickjh** [comment]
In the meantime if you use fish (Friendly Interactive SHell) you can add this function to your `~/.config/fish/functions/` directory.  You will need to rename the attached file to `cex-diff.fish`. I had to add the .txt ending as .fish files are not an accepted upload file type. So, it should end up like this: `~/.config/fish/functions/cex-diff.fish`

Usage is `cex-diff @<DrushSiteAlias>`  If you use the `drush use @<DrushSiteAlias>` command to set the site drush should run commands on, you can just do `cex-diff`.

Other than normal drush commands this uses [colordiff](http://www.colordiff.org/) to get a easy to read output, so you may need to install that. It will export to a folder it makes with the linux user's name in the /tmp folder. After the colordiff it cleans up after itself. This has been tested on Linux. YMMV

[cex-diff.fish.txt](https://github.com/drush-ops/drush/files/851134/cex-diff.fish.txt)

**Comment by gitressa** [comment]
I just discovered that previewing changes for `drush config:export` has been added, so now both export and import have that option:
```
drush config:export --diff
drush config:import --diff
```
