### ISSUE TITLE
drush quick-drupal --core fails in some instances

### ISSUE THREAD

**Issue by queenvictoria** [drush-ops/drush#257]
I've been trying to use drush qd to bring up D8 without success. Turns out its not isolated to D8 and its not in every situation. I've not looking too far under the hood yet.

Tested on various versions of drush on various versions of OS X.

* If I try and run the command from the `drush help qd` I get an md5 error ([filename] is corrupt (wrong md5  [error]
checksum))
`drush qd --profile=minimal --dev --cache --core=drupal-8.x --yes`

* Or D7
`drush qd --profile=minimal --dev --cache --core=drupal-7.x --yes`

* Or without caching
`drush qd --profile=minimal --dev --no-cache --core=drupal-8.x --yes`

* If I specify the version of Drupal explicitly everything works.
`drush qd --profile=minimal --dev --cache --core=drupal-8.0-alpha4 --yes`

* If I don't specify core everything works.
`drush qd --profile=minimal --cache --yes`

* If I don't specify core but do require dev I get an md5 error.
`drush qd --profile=minimal --dev --cache --yes`

* If I specify git-drupal everything works.
`drush qd --profile=minimal --dev --cache --core=drupal-8.x --yes  --package-handler=git_drupalorg`

Environment:
`whale:temp rossetti$ drush --version
 Drush Version   :  7.0-dev 
whale:temp rossetti$ wget --version
GNU Wget 1.13.4 built on darwin10.8.0.
+digest +https +ipv6 -iri +large-file -nls +ntlm +opie +ssl/openssl 
...
`

**Comment by weitzman** [comment]
In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.
