### ISSUE TITLE
Error when custom drush command calls drush_invoke_process on a group alias

### ISSUE THREAD

**Issue by AdamPS** [drush-ops/drush#2584]
Running latest drush 8.x.  Custom drush command contains:

```
function drush_xxx() {
  if ($apply = drush_get_option('apply')) {
    drush_invoke_process($apply, 'drupal-directory');
  }
}
```

It works fine when passed an alias of a single site, but fails with the following output if invoked with an alias group _mygroup = site1+site2:
drush XXX --apply=@_mygroup

(I used an underscore after @ to stop markdown turning it into a link.)

```
The command could not be executed successfully (returned: site1 >> /data/www/site1                                  [error]
site2 >> /data/www/site2
, code: 0)
```

The problem seems to be that _drush_backend_invoke call drush_backend_parse_output in sequence for site1, site2, then finally _mygroup.  However for that final time the output does not have delimiters and JSON encoded data but instead is just a plain string with the output of each site.  Any non-array output causes the above error message.

**Comment by weitzman** [comment]
group alias and drush_invoke_process() are gone. older branches are only fixed for critical problems.
