### ISSUE TITLE
remove trailing slashes in en & pmu commands

### ISSUE THREAD

**Issue by HongPong** [drush-ops/drush#2597]
Hi all,

A tiny change to request. If you want to disable a module in the modules folder, and you start to type it and hit tab in most shells you get the directory name and a trailing slash. It would be nice if instead of failing, like so it would correct:

```bash
$ drush pmu securelogin/
The following extensions will be uninstalled: securelogin (Autocorrected, without slash)
Do you really want to continue? (y/n):
```

A really minor thing but would be nice. I can't think of a case where you actually would want the trailing slash to be considered ahead of the name without the trailing slash.

**Comment by weitzman** [comment]
I'm not aware of other CLI tools doing this. Please use backspace.
