### ISSUE TITLE
Detect modules in profiles/[profile]/modules/* and such before drush dl

### ISSUE THREAD

**Issue by acao** [drush-ops/drush#260]
So theres one thing that bugs me so very much that I often will move contrib modules in profiles to sites/all/modules/contrib before running a profile install.  And that is that, while when a module lives somewhere in sites/all/modules, drush will warn that it already exists and prompts to replace it, however if the module lives in a profile, this doesn't happen. Leading to duplicate modules and even duplicate module versions, even.  It gets very messy in the long term.

Now checking the registry/registry_file tables would be an option, except sometimes I'm running drush dl against a simple git repo or sshfs mounted directory rather than working against an instance where drush can bootstrap the database. So possibly drush can look in the profiles/[profile]/modules/\* directories as well for a duplicate of that module? or maybe there can be a --check-profiles option on dl? Maybe the existance of non-standard profiles and their module directories could be stored in the drush cache to make this less expensive? Thinking out loud here, and haven't looked in great detail at the code, so let me know if i'm overlooking a technique or new development here, thanks!

**Comment by greg-1-anderson** [comment]
`pm-*` commands are maintenance-only. Closing.
