### ISSUE TITLE
Allow delete of single value in a config object

### ISSUE THREAD

**Issue by AdamPS** [drush-ops/drush#2604]
Drupal 8 [supports](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Config%21Config.php/class/Config/8.2.x):

1. Config::set:     Sets a value in this configuration object.
2. Config::clear:     Unsets a value in this configuration object
3. Config::delete:     Deletes the configuration object.

As far as I can see, drush can do 1 and 3 but not 2.  Use cases for 2:

- You accidentally cset a non-valid key and want to get rid of it again
- During module dev, you changed the name of a schema key and want to remove the value for the old key.

Could solve this with a new command config-clear.  Alternatively simply add an optional second parameter 'key' to drush config-delete?

I think this is not a duplicate of similar issue #699 as that was eventually fixed by creating the config-delete command, but the fix did not seem to allow deleting just a single value.

**Comment by drzraf** [comment]
Use-case: I would like to remove one of the migrate-generated field migration and expect to do:
`drush cdel migrate_plus.migration.upgrade_d6_node_xxx process.field_myfield`

Such a task is currently cumbersome:
* setting `process.field_myfield` to null won't do it
* `config-set` does not accept JSON so `cget | jq "del(.process.field_myfield)" | cset` won't do it either
* and current Debian does not provide a sed-like YAML editor

Finally:
`cget --format=yaml xxx | awk 'BEGIN{s=0}{if($0~/^\s+field_.+:$/)s=0;if($0~/^\s+field_date:$/)s=1;if(s)next;print($0);}' | cset --format=yaml xxx` will do it

**Comment by AdamPS** [comment]
Great thanks.  I created PR #3004 to backport to 8.x
