### ISSUE TITLE
Drush should be using the Drupal UpdateKernel when running updates

### ISSUE THREAD

**Issue by hchonov** [drush-ops/drush#2611]
Currently drush is using the normal DrupalKernel when running updates, but it should be using the designated UpdateKernel as through the UpdateServiceProvider Drupal is altering services and using the null cache backend in order not to write into the cache at some places. There is currently an issue which is going to make use of this and really needs that drush is using the UpdateKernel otherwise updates might/will fail - https://www.drupal.org/node/2851529.

**Comment by greg-1-anderson** [comment]
This has been done
