### ISSUE TITLE
Wrapper for composer

### ISSUE THREAD

**Issue by AdamPS** [drush-ops/drush#2614]
As per #2438, pm-download and pm-update are being deprecated in favour of composer.

It would be great to have a drush wrapper for composer.  Any idea if this already exists somewhere?  I imagine it would help bridge the gap of drupal and composer, especially for people who are less familiar with composer.

Here are some ideas:

- Command cm-update.  Support for  --security-only (maybe implemented via pm-updatestatus?), --check-updatedb, --entity-updates, --lock (implemented by composer require of exact version).  Add support for "recommended version" checking, with detection when a newer recommended release is available (default composer require of ^a.b would ignore a newer major version).
- Command cm-install.
- Command cm-download alias cm-require.
- Command cm-remove.  Checks modules have been uninstalled.
- Command cm-updatestatus = update --dry-run
- Automatic conversion from drupal to composer version numbers, can specify either.
- Brings power of drush aliases.  Can run composer from any directory or even remotely.  Can use alias groups.
- Brings power of drushrc, for example to turn on option --no-dev by default.

**Comment by weitzman** [comment]
Thats a great brainstorm. I mentioned my interest in a Composer wrapper in our Roadmap - https://medium.com/@weitzman/drush-9-roadmap-9eb5cd227c50#.7evicwpzr

**Comment by davekopecek** [comment]
During the transition from pm-update to a composer based solution could a warning of potential pm-update pitfalls be added to the command?  Currently Drupal Commerce requires a composer install.  Running pm-update on a site with commerce installed kills the site. 

If there's an easy way for pm-update to check for composer installed modules it would be great if it could issue a warning:
````
This site contains modules installed with composer. User composer to update this site.
Continuing will overwrite the vendor directory and waste the next hour of your life. Continue? (y/n) 
`````
 
... or something like that.

**Comment by weitzman** [comment]
pm-update on 9.x branch gives you help and wont kill your site.
