### ISSUE TITLE
drush upwd sets the password to NULL

### ISSUE THREAD

**Issue by PARULSHARM** [drush-ops/drush#2615]
With drush 9.0-dev, using the command,
drush upwd admin --password=dsmdsdsd

sets the password to NULL in Database on my Drupal 8 instance(v 8.2.6). Attaching screenshots for reference:

![screen shot 2017-02-14 at 2 32 00 pm](https://cloud.githubusercontent.com/assets/25008611/22922172/855ba0ea-f2c2-11e6-94ac-87ba4a2a35ba.png)
![screen shot 2017-02-14 at 2 32 28 pm](https://cloud.githubusercontent.com/assets/25008611/22922173/855feae2-f2c2-11e6-90a0-f09fcde1afc3.png)

**Comment by weitzman** [comment]
I changed this command so that password is second argument, not an option.
