### ISSUE TITLE
Please restore alternative install instructions

### ISSUE THREAD

**Issue by karlshea** [drush-ops/drush#2634]
I'm not sure if this is the right queue for this, but the URL was http://docs.drush.org/en/master/install-alternative/

Not everyone is running D8 yet, and they will still be useful for some time yet.

**Comment by weitzman** [comment]
They are still there but you have to look at 8.x branch - http://docs.drush.org/en/8.x/. i left a few links to 8.x on main page but i know folks will have trouble finding it.

**Comment by karlshea** [comment]
This continues to not work (see issue #1834 I opened in Dec 2015):

`COMPOSER_HOME=/opt/drush COMPOSER_BIN_DIR=/usr/local/bin COMPOSER_VENDOR_DIR=/opt/drush/7 composer require drush/drush:7`

"Unable to load autoload.php. Drush now requires Composer in order to install its dependencies and autoload classes. Please see README.md"

This is the second time I've had to use the Wayback Machine in order to get the all-users install instructions. They aren't in the latest 8.x branch, so they've effectively disappeared from your docs site again.

I'll include them here for myself or anyone else searching for them in the future:

# Install Drush for all users via Composer

If you need Drush installed for all users on a system using Composer, [install Composer globally](https://getcomposer.org/doc/00-intro.md#globally) then follow the steps below.

**Important:** Run these shell commands as a privileged user with write access to `/opt` and  `/usr/local/bin` or prefix with `sudo`.

```
# Create and/or navigate to a path for the single Composer Drush install.
mkdir --parents /opt/drush-8.x
cd /opt/drush-8.x
# Initialise a new Composer project that requires Drush.
composer init --require=drush/drush:8.* -n
# Configure the path Composer should use for the Drush vendor binaries.
composer config bin-dir /usr/local/bin
# Install Drush. 
composer install
```
## Getting Updates

Use composer to update Drush just as you would with any other composer managed project. The vendor binaries will be updated for all users.

```
# Navigate to the Drush install path.
cd /opt/drush-8.x
# Run composer update
composer update
```
## Major Version Upgrade

If upgrading to a new major version the steps are the same, with one addition:

```
# Remove the existing symlinks to Drush vendor binaries. 
find /usr/local/bin -lname '/opt/drush*' -exec unlink \{\} \;
# Follow the steps shown above, starting with creation of a new path.
mkdir --parents /opt/drush-9.x
cd /opt/drush-9.x
```
Important: At the time of writing composer will warn you if it cannot create vendor binaries due to a name conflict with an existing file.
