### ISSUE TITLE
Drush sql-query doesn't respect $databases init_commands overrides

### ISSUE THREAD

**Issue by anavarre** [drush-ops/drush#2636]
Consider this `init_commands` override.

```
$ drush @site.env sql-conf --format=json
{
    "database": "test",
    "username": "root",
    "prefix": {
        "default": ""
    },
    "host": "203.0.113.12",
    "port": "3306",
    "namespace": "Drupal\\Core\\Database\\Driver\\mysql",
    "driver": "mysql",
    "init_commands": {
        "increment": "SET session auto_increment_increment = 5"
    }
}
```

Drush `sql-conf` sees it correctly by parsing `$databases`. However, when using `sql-query` it just returns the default DB variable instead of the override.

```
$ drush @site.env sql-query "SELECT @@auto_increment_increment"
1
```

Shouldn't Drush respect the override? If you do the following, you'll see the overridden values are taken into account as expected.

```
$ drush @site.env php-eval "print json_encode(\Drupal\Core\Database\Database::getAllConnectionInfo());"
{"default":{"default":{"database":"test","username":"root","password":"root","prefix":{"default":""},"host":"203.0.113.12","port":"3306","namespace":"Drupal\\Core\\Database\\Driver\\mysql","driver":"mysql","init_commands":{"increment":"SET auto_increment_increment = 5","sql_mode":"SET sql_mode = 'ANSI,STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,ONLY_FULL_GROUP_BY'"},"pdo":{"3":2,"1000":true,"1005":true,"20":true,"1013":false}}}}
```

**Comment by ricardoamaro** [comment]
I also believe it should, since Drupal itself is using it.
By not honouring it we could see all sort of weird behaviours happening not consistent with Drupal results.

**Comment by weitzman** [comment]
Drush commands that actually bootstrap Drupal and use the Drupal API honor that init-commands obscurity. Drush commands like sql-query have always bypassed PDO and used `mysql` program directly. Thats been an excellent strategy, and not likely to change. We have never needed to do more than pull the DB creds out of Settings.

If you want a sql-query that respects init-commands, i suggest you write a drush command that performs queries using `Database::getConnection()->query()`

**Comment by anavarre** [comment]
Thanks, Moshe. This clears up our confusion.

**Comment by MikeGodin** [comment]
Here's a simple example that respects init-commands, without the overhead of writing a command, for the query `show variables WHERE Variable_name LIKE '%_isolation'`:

`query="show variables WHERE Variable_name LIKE '%_isolation'";drush eval "print_r(\Drupal::database()->query(\"$query\")->fetchAll());"`
