### ISSUE TITLE
Site-install fails, .my.cnf socket not overridden

### ISSUE THREAD

**Issue by axel-rutz** [drush-ops/drush#2645]
Wow, this was hard to debug.

How to reproduce:
* Have a .my.cnf that has a socket:3306 connection as default
* Want to do a site-install on a 127.0.0.1:3307 network connection

Actual outcome:
```
$ drush si --db-url=mysql://foo:bar@127.0.0.1:3307/db
You are about to CREATE the 'mediacp8_dev' database. Do you want to continue? (y/n): y
Failed to create database: ERROR 1045 (28000): Access denied for user 'foo'@'bar' (using password: YES)       [error]

```

Debug details:
```
sql-query: DROP DATABASE IF EXISTS mediacp8_dev; CREATE DATABASE mediacp8_dev /*!40100 DEFAULT CHARACTER SET utf8 */;       [notice]
[5.93 sec, 8.77 MB]
Executing: mysql --defaults-extra-file=/tmp/drush_llCT5s --database=information_schema --host=127.0.0.1 --port=3307 --silent  < /tmp/drush_HXI3kS
Failed to create database: ERROR 1045 (28000): Access denied for user 'foo'@'bar' (using password: YES)       [error]
```

Workaround:
* Rename the .my.cnf while installing, then rename back

Proposed solution
* Add something like _socket=""_ or _protocol=TCP_ to the [mysql client options](https://dev.mysql.com/doc/refman/5.6/en/connecting.html) IF the DB server is not _localhost_ (in this case 127.0.0.1)

Sounds insane?
This is the setup on uberspace.de hoster, which allows to have the distribution's standard legacy SQL version on _socket localhost:3306_ and D8-enabled bleeding edge MariaDB on _TCP 127.0.0.1:3307_.

**Comment by alexpott** [comment]
This is covered by https://github.com/drush-ops/drush/pull/2387

**Comment by axel-rutz** [comment]
Thanks @alexpott for pointing this out. Looks good and is in master now. So closing this.
