### ISSUE TITLE
Error when executing drush sql-sanitize

### ISSUE THREAD

**Issue by webmasterpf** [drush-ops/drush#2655]
I encounter an issue when using this command to change password on dev website.
http://drupal.stackexchange.com/questions/230568/error-when-executing-drush-sql-sanitize

the error message:
```
ERROR 1146 (42S02) at line 1: Table 'provence-formation_pfdevd6mg.users' doesn't exist
Sanitize query failed.
```

Drush 8.1 on a D6 DB.
My DB tables are prefixed but drush doesn't seem to be aware of that.
Is it a bug or an command error from myself ?

Thanks

**Comment by weitzman** [comment]
Database prefixing is no longer supported by Drush. Its a relic from a prior era.

**Comment by webmasterpf** [comment]
so I must to clear this prefix ?

**Comment by weitzman** [comment]
Yes, if you want to use Drush fully and reliably.

**Comment by webmasterpf** [comment]
got it.Thanks
