### ISSUE TITLE
Drupal 8 drush uli

### ISSUE THREAD

**Issue by csandanov** [drush-ops/drush#2674]
Hi,

Drush version: 8.1.10
When I reset password for Drupal 8 via drush uli I get an url like `http://base_url/user/reset/uid/timestamp/hash/login`. Drupal responds with 404 not found when I use this URL. However, when I remove `/login` from the URL it works fine. When I reset a password via Drupal UI, it sends me a link without `/login` at the end.

**Comment by weitzman** [comment]
What version of Drupal? I think Drupal was recently enhanced to once again support /login.

**Comment by csandanov** [comment]
8.1.7

**Comment by weitzman** [comment]
That version of Drupal is no longer supported by Drupal Security team, so Drush doesn't support it either. See https://www.drupal.org/core/release-cycle-overview
