### ISSUE TITLE
Move old global options to new Annotated commandfile

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2678]
Not sure to handle their oddball properties for backend invoke (e.g. never-propagate). I guess these will be new custom annotations for now.

**Comment by greg-1-anderson** [comment]
Once we are using the Symfony dispatcher, we can add options like this:

https://github.com/consolidation/Robo/blob/master/src/Application.php#L18

In the meantime, I don't think there is any cause to change the way it is right now -- at least I can't think of any reason. There's no need or point to making global options annotations, IMO.

**Comment by weitzman** [comment]
Yes, you are right.
