### ISSUE TITLE
Remove drush_confirm(), drush_prompt(), etc in favor of Console QuestionHelper

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2680]
See http://symfony.com/doc/current/components/console/helpers/questionhelper.html. Any objection?

**Comment by damiankloip** [comment]
Sounds like a good idea, I've used the QuestionHelper quite a bit and it works great.

**Comment by dhrjgpt2005** [comment]
Hey would this be part of drush 9 or drush 8 onwards?
