### ISSUE TITLE
Remove /composer.lock

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2688]
Now that Drush (master) only operates as a dependency in a bigger project, we can remove /composer.lock. Thats not used for dependencies - only the project's top level composer.lock is used. See https://getcomposer.org/doc/02-libraries.md#lock-file.

Any objections?

**Comment by greg-1-anderson** [comment]
Yes, I agree that the composer.lock is of little use here.

**Comment by glennpratt** [comment]
@weitzman I'm hearing via third party that for some purposes we should still install drush globally, but without a lock file, I'll have to fork to create stable build. Is that basically the sum of it?

IMO, committing a lock file is just better, even for libs, regardless of language/tool. If you want a test that blows up as your dependencies flap in the wind, make a secondary test that deletes the lock file before it starts so you can isolate the problem.
