### ISSUE TITLE
Disable installing major updates via drush pm-update command

### ISSUE THREAD

**Issue by MurzNN** [drush-ops/drush#2689]
Please provide any way to disable installing major updates (like 1.23 » 2.0 versions) via drush pm-update command, but with display info that new version is released. For example, via `--ignore-major` argument.

Also will be good to have ability for ignore updates of all manually patched versions on site (we add -patched_123456 suffix in module version) via something like `--ignore-match='patched_'` argument, but with display info that new version is released.

**Comment by weitzman** [comment]
pm-updatecode is getting bug fixes but not new features. for drush9, one would use composer for this.
