### ISSUE TITLE
.drush-use file not respected within webroot

### ISSUE THREAD

**Issue by malikkotob** [drush-ops/drush#2699]
I have the following project structure:
- .drush-use
- drush.wrapper
- drush (directory)
- webroot
- vendor
- directory-1
- directory-2
- directory-n

`.drush-use` file contains the following: `./drush.wrapper`
`drush.wrapper` file, the following:
```
vendor/drush/drush/drush.launcher --config=${DIR}/drush/drushrc.php --alias-path=${DIR}/drush/site-aliases "$@"
```

The current behavior I'm seeing is that within all directories in the repo aside from the webroot, the launcher from my drush.wrapper is being used. When I'm anywhere within the webroot, however, the `.drush-use` and `drush.wrapper` scripts are never reached, seemingly because of the logic found in `startup.inc`, whereby if a `.drush-use` file isn't in the current working directory, it skips over to the `find_wrapper_or_launcher` function, which ends up handling things a bit differently, due to the fact that we're within a webroot:
```
 * If the provided location looks like it might be a web
 * root (i.e., it contains an index.php), then we will search
 * in a number of locations in the general vicinity of the
 * web root for a Drush executable.
 *
 * For other locations, we will look only in that specific
 * directory, or in vendor/bin.
 */
function find_wrapper_or_launcher($location) {
  if (file_exists($location. DIRECTORY_SEPARATOR. 'index.php')) {
    return find_wrapper_or_launcher_in_vicinity($location);
  }
```

What is the best path forward to ensure that my drush.wrapper script is found everywhere within my project? As a test, I placed an additional `.drush-use` file at the top-level of my webroot, and it was respected only at that level, but not deeper.

```
Drush Version: 8.1.10
Drupal Version: 8.2.7
PHP Version: 5.6.29
```

**Comment by webflo** [comment]
.drush-use, drush.launcher and drush.wrapper has been removed in Drush 9 in favour of the new launcher. see  https://github.com/drush-ops/drush-launcher for details.
