### ISSUE TITLE
drush site-install uses minimal profile instead of standard

### ISSUE THREAD

**Issue by horvan** [drush-ops/drush#2704]
I tried serveral times to get 

```shell 
drush si --db-url=mysql://drupal:drupal@localhost/drupal8  --local=de 
```
work with the standrd profile 

regardless what i do minimal gets selected

To install drush I used composer require drush/drsush

**Comment by greg-1-anderson** [comment]
Did you try `drush si --db-url=mysql://drupal:drupal@localhost/drupal8  --local=de standard`?

**Comment by horvan** [comment]
yes I did. It seems there is a difference between if there is a copy of default.settings,php in sites/default or not. I hadnt got the news that this file has not to be crated anymore if you useing drush. That may be where the error is comming from.
