### ISSUE TITLE
Add a cache clear type for page cache

### ISSUE THREAD

**Issue by gh640** [drush-ops/drush#2710]
I'd like to add an option to clear page cache.

(This is my first attempt to create an issue in this repository and if I'm wrong, I'm sorry.)

**Comment by gh640** [comment]
I read the contributing guide https://github.com/drush-ops/drush/blob/master/CONTRIBUTING.md but I couldn't understand how to "simply open an issue to be added as an Outside Collaborator". 

How should I do that? Is it just to create an issue labeled like "Please add me as an outside collaborator"?

**Comment by weitzman** [comment]
Welcome! Thats not needed. I just removed that line from the docs.

**Comment by weitzman** [comment]
As for page cache, I'd like to not add new cache types. Feel free to add new ones from outside cache.drush.inc. See hows Views does it in Drush core.

**Comment by gh640** [comment]
@weitzman thanks for your response and explanation. I'll try to anticipate in other issues.
