### ISSUE TITLE
allow update command to select versions

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#2714]
The 'dl' command allows you select a version, but the 'up' command doesn't.

This would be useful in cases where you only want to update to a security release, but not subsequent releases with new features, or where there are multiple major branches, or updating core to stay on the current major branch rather than advance to the latest one.

**Comment by weitzman** [comment]
update code already has --security-only. since updatecode is now on bug-fix-only support, this is won't-fix. sorry.
