### ISSUE TITLE
drush sql-connect Unable to load class Drush\Sql\Sql 

### ISSUE THREAD

**Issue by richhorn** [drush-ops/drush#2721]
Ubuntu 16.04 localhost Drush 8.1.10 installed via composer as per the recommended route. Drupal 8.3

Drush runs and completes some tasks. eg

_drush status_

> PHP executable : /usr/bin/php
> PHP configuration : /etc/php/7.1/cli/php.ini
> PHP OS : Linux
> Drush script : /home/rich/vendor/drush/drush/drush.php
> Drush version : 8.1.10
> Drush temp directory : /tmp
> Drush configuration :
> Drush alias files :

However when I try any mysql/database-related commands I get errors

Usually like;

_drush up_

> Command pm-update needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.                              
> [error] The drush command 'up' could not be executed. 

Or this one;

_drush sql-connect_

Unable to load class Drush\Sql\Sql                                                                                                                                                  [error]    
Drush\Sql\SqlException: Unable to find a matching SQL Class. Drush cannot find your database connection details. in /home/rich/vendor/drush/drush/commands/sql/sql.drush.inc:541    [error]    
Stack trace:                                                                                                                                                                                   
#0 /home/rich/vendor/drush/drush/commands/sql/sql.drush.inc(221): drush_sql_get_class()                                                                                                        
#1 /home/rich/vendor/drush/drush/includes/command.inc(422): drush_sql_connect()                                                                                                                
#2 /home/rich/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)                                                                                                  
#3 /home/rich/vendor/drush/drush/includes/command.inc(199): drush_command()                                                                                                                    
#4 /home/rich/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)                                                                                                        
#5 /home/rich/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()                                                                                     
#6 /home/rich/vendor/drush/drush/drush.php(12): drush_main()                                                                                                                                   
#7 {main}  

My settings.php

> $databases['default']['default'] = array (
> 'database' => 'drupal8-test1',
> 'username' => '',
> 'password' => '',
> 'prefix' => '',
> 'host' => '127.0.0.1',
> 'port' => '3306',
> 'namespace' => 'Drupal\Core\Database\Driver\mysql',
> 'driver' => 'mysql', );

PATH in .bashrc

> export PATH=$HOME/.config/composer/vendor/bin:$PATH export PATH=/bin:/usr/local/bin:/usr/local/mysql/bin:$PATH

Seems correct to me ...?

I have tried Forcing 127.0.0.1 instead of localhost.
I am running drush from drupal root directory.
I would greatly appreciate any suggestions as to where to go next with this. :)
Thanks for looking.

**Comment by weitzman** [comment]
Add --debug and you will see the actual shell commands that are run. See if those fail and fix if needed.

**Comment by richhorn** [comment]
Thank you, Moshe, for your prompt reply.
:)
I have done as you suggested, but am unsure now where to go with the outputs.
Please would you advise?

So ...

 _drush up --debug_

> Using the Drush script found at /home/rich/vendor/drush/drush/drush.launcher using pcntl_exec
> Cache HIT cid: 8.1.10-commandfiles-0-fcef2bb3879f94f27262252d9ac29def [0.01 sec, 870.66 KB]                                                                                             [debug]
> Bootstrap to phase 0. [0.08 sec, 2.79 MB]                                                                                                                                           [bootstrap]
> Bootstrap to phase 6. [0.08 sec, 2.79 MB]                                                                                                                                           [bootstrap]
> Command pm-update needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command. [0.08 sec, 2.8 MB]           [error]
> The drush command 'up' could not be executed. [0.08 sec, 2.8 MB]

and 

_drush sql-cli --debug_

> Using the Drush script found at /home/rich/vendor/drush/drush/drush.launcher using pcntl_exec
> Cache HIT cid: 8.1.10-commandfiles-0-fcef2bb3879f94f27262252d9ac29def [0.01 sec, 870.66 KB]                                                                                             [debug]
> Bootstrap to phase 0. [0.08 sec, 2.79 MB]                                                                                                                                           [bootstrap]
> Bootstrap to phase -1. [0.09 sec, 2.79 MB]                                                                                                                                          [bootstrap]
> Found command: sql-cli (commandfile=sql) [0.09 sec, 2.8 MB]                                                                                                                         [bootstrap]
> Calling hook drush_sql_cli [0.09 sec, 2.92 MB]                                                                                                                                          [debug]
> Unable to load class Drush\Sql\Sql [0.09 sec, 2.93 MB]                                                                                                                              [error]
> Drush\Sql\SqlException: Unable to find a matching SQL Class. Drush cannot find your database connection details. in /home/rich/vendor/drush/drush/commands/sql/sql.drush.inc:541    [error]
> Stack trace:
> #0 /home/rich/vendor/drush/drush/commands/sql/sql.drush.inc(446): drush_sql_get_class()
> #1 /home/rich/vendor/drush/drush/includes/command.inc(422): drush_sql_cli()
> #2 /home/rich/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
> #3 /home/rich/vendor/drush/drush/includes/command.inc(199): drush_command()
> #4 /home/rich/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
> #5 /home/rich/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
> #6 /home/rich/vendor/drush/drush/drush.php(12): drush_main()
> #7 {main} [0.09 sec, 2.94 MB]
> Command dispatch complete [0.09 sec, 2.88 MB]   


and

_drush sql-connect --debug_

> Using the Drush script found at /home/rich/vendor/drush/drush/drush.launcher using pcntl_exec
> Cache HIT cid: 8.1.10-commandfiles-0-fcef2bb3879f94f27262252d9ac29def [0.01 sec, 870.66 KB]                                                                                             [debug]
> Bootstrap to phase 0. [0.08 sec, 2.79 MB]                                                                                                                                           [bootstrap]
> Bootstrap to phase -1. [0.08 sec, 2.79 MB]                                                                                                                                          [bootstrap]
> Found command: sql-connect (commandfile=sql) [0.08 sec, 2.8 MB]                                                                                                                     [bootstrap]
> Calling hook drush_sql_connect [0.09 sec, 2.92 MB]                                                                                                                                      [debug]
> Unable to load class Drush\Sql\Sql [0.09 sec, 2.93 MB]                                                                                                                              [error]
> Drush\Sql\SqlException: Unable to find a matching SQL Class. Drush cannot find your database connection details. in /home/rich/vendor/drush/drush/commands/sql/sql.drush.inc:541    [error]
> Stack trace:
> #0 /home/rich/vendor/drush/drush/commands/sql/sql.drush.inc(221): drush_sql_get_class()
> #1 /home/rich/vendor/drush/drush/includes/command.inc(422): drush_sql_connect()
> #2 /home/rich/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
> #3 /home/rich/vendor/drush/drush/includes/command.inc(199): drush_command()
> #4 /home/rich/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
> #5 /home/rich/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
> #6 /home/rich/vendor/drush/drush/drush.php(12): drush_main()
> #7 {main} [0.09 sec, 2.94 MB]
> Command dispatch complete [0.09 sec, 2.88 MB]

**Comment by richhorn** [comment]
Solved by adding 

> --root=/full/path/to/your/webroot

to the drush command. 

Thanks all :)

**Comment by n8thanael** [comment]
I encountered this error while migrating a Acquia Dev Desktop build into an AWS environment using a Bitnami AMI.  Similar to how DevDesktop pulls the settings['default']['default'] mysql configuration from: 

`	if (isset($_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR']) && file_exists($_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] . '/loc_mysite-enviornment_dd.inc')) {
		require $_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] . '/loc_mysite-enviornment_dd.inc';
	} `

I enabled a similar model by pulling the path to the settings directory (which is the home directory) directly into the settings.php file via php require().   $_SERVER['BITNAMI_DRUPAL_SETTINGS_DIR'] would dynamically point to the proper settings in my Apache2 vhosts_httpd.config files:

` elseif (isset($_SERVER['BITNAMI_DRUPAL_SETTINGS_DIR']) && file_exists($_SERVER['BITNAMI_DRUPAL_SETTINGS_DIR'])) {
		require $_SERVER['BITNAMI_DRUPAL_SETTINGS_DIR'];
	} `

Some how drush still won't recognize the settings using drush sql commands ... even though other commands such as drush archive-dump work correctly.  I couldn't discover why drush does this, but the solution was simply to remove the require() and have the database settings in the settings.php file.

**Comment by wturrell** [comment]
@n8thanael the issue (for me anyway, when trying to run Drush on local dev sites) is that Acquia's conditional only runs when serving web pages, not via the Drush CLI, because when you use the CLI, ``$_SERVER`` doesn't exist…

You can work around it by adding this line outside (above) the ``<DDSETTINGS>`` block. 

    $_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] = '/Users/[your-username-here]/.acquia/DevDesktop/DrupalSettings';

(That's an example for macOS users.)

It's enough to trick the rest of Dev Desktop's code into looking in the correct place without having to rewrite or duplicate it.
