### ISSUE TITLE
Installing drush incorrectly appends to user ~/.bashrc

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [drush-ops/drush#2723]
Commands run:
``` bash
php -r "readfile('http://files.drush.org/drush.phar');" > drush
chmod +x drush
./drush init
```

Output:

```bash
Copied example Drush configuration file to /home/username/.drush/drushrc.php                                                                                                                             [ok]
Copied example Drush bash configuration file to /home/username/.drush/drush.bashrc                                                                                                                       [ok]
Copied Drush completion file to /home/username/.drush/drush.complete.sh                                                                                                                                  [ok]
Copied example Drush prompt file to /home/username/.drush/drush.prompt.sh                                                                                                                                [ok]

# Include Drush bash customizations.if [ -f "/home/username/.drush/drush.bashrc" ] ; then
  source /home/username/.drush/drush.bashrc
fi


# Include Drush completion.
if [ -f "/home/username/.drush/drush.complete.sh" ] ; then
  source /home/username/.drush/drush.complete.sh
fi


# Include Drush prompt customizations.
if [ -f "/home/username/.drush/drush.prompt.sh" ] ; then
  source /home/username/.drush/drush.prompt.sh
fi


# Path to Drush, added by 'drush init'.
export PATH="$PATH:phar:///home/username/scripts/drush"

Append the above code to /home/username/.bashrc? (y/n): y
Updated bash configuration file /home/username/.bashrc                                                                                                                                                   [ok]
Start a new shell in order to experience the improvements (e.g. `bash`).
```

`.bashrc` Contents:

``` bash
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias mysqldump='mysqldump --defaults-file=~/.my.cnf $@'

# Include Drush bash customizations.if [ -f "/home/username/.drush/drush.bashrc" ] ; then
  source /home/username/.drush/drush.bashrc
fi


# Include Drush completion.
if [ -f "/home/username/.drush/drush.complete.sh" ] ; then
  source /home/username/.drush/drush.complete.sh
fi


# Include Drush prompt customizations.
if [ -f "/home/username/.drush/drush.prompt.sh" ] ; then
  source /home/username/.drush/drush.prompt.sh
fi


# Path to Drush, added by 'drush init'.
export PATH="$PATH:phar:///home/username/scripts/drush"
```

Resulting in errors upon restarting bash session:

``` bash
-bash: /home/username/.bashrc: line 18: syntax error near unexpected token `fi'
-bash: /home/username/.bashrc: line 18: `fi'
```

Looks like a possible line ending issue in the drush phar when appending the generated text or just a missing line ending between the commend and the starting `if`.

**Comment by Caffe1neAdd1ct** [comment]
Quick investigation after forking, cloning and running locally i can reproduce using the latest master branch.

The issue is the `bashAddition` function inside `src/Commands/core/InitCommands.php` using <<< EOD to build up the bash if statement text.

``` php
  protected function bashAddition($file) {
    return <<<EOD
if [ -f "$file" ] ; then
  source $file
fi


EOD;
  }
```

I've modified to:

``` php
  protected function bashAddition($file) {
    return PHP_EOL . 'if [ -f "' . $file . '" ] ; then' . PHP_EOL . '  source ' . $file . PHP_EOL . 'fi';
  }
```

Which fixes the issue and avoids using the heredoc method in favour of explicit line endings and correct spacing... Had this issue on both a CentOS 6 server and my local Arch Linux desktop across PHP 5.6 and PHP 7.1.2.

**Comment by Caffe1neAdd1ct** [comment]
I'm happy to raise this as a pull request, however would appreciate a quick review of this issue before i go ahead.

**Comment by greg-1-anderson** [comment]
The change looks fine; however, what what's wrong with the heredoc? It's easier to read than the composed version suggested, so I'd like to understand the limitations before we simply remove it.

**Comment by Caffe1neAdd1ct** [comment]
The current limitation is the incorrectly generated bashrc line:

``` bash
# Include Drush bash customizations.if [ -f "/home/username/.drush/drush.bashrc" ] ; then
```

The heredoc statement is correctly formatted with a newline at the start:

``` php
protected function bashAddition($file) {
    return <<<EOD
if [ -f "$file" ] ; then
```

However this isn't always applied. The proposed change is explicit with the newline characters and won't have issues if this file gets committed with incorrect line endings. If there is a better/nicer way to format this change to be clearer please feel :+1:

**Comment by greg-1-anderson** [comment]
Do you know why the heredoc generates the incorrect result on your system?

**Comment by Caffe1neAdd1ct** [comment]
Looks like the first newline in a EOD heredoc doesn't actually get applied to a prepended string:

```php
"\n# Include $description.". $this->bashAddition($destFile)

protected function bashAddition($file) {
    return <<<EOD
if [ -f "$file" ] ; then
  source $file
fi


EOD;
  }
```

Changing the heredoc to:
``` php
protected function bashAddition($file) {
    return <<<EOD

if [ -f "$file" ] ; then
  source $file
fi


EOD;
  }
```

Also works fine...

**Comment by Caffe1neAdd1ct** [comment]
Original heredoc output:

`php drush.php init -vvv`
```
string(139) "
# Include Drush bash customizations.if [ -f "/home/username/.drush/drush.bashrc" ] ; then
  source /home/username/.drush/drush.bashrc
fi

"
string(140) "
# Include Drush completion.if [ -f "/home/username/.drush/drush.complete.sh" ] ; then
  source /home/username/.drush/drush.complete.sh
fi

"
string(147) "
# Include Drush prompt customizations.if [ -f "/home/username/.drush/drush.prompt.sh" ] ; then
  source /home/username/.drush/drush.prompt.sh
fi

 Modify /home/username/.bashrc to include Drush configuration files? (yes/no) [yes]:
 > no

 [error]  Cancelled. 
 [info] Command dispatch complete
"

Newline added to heredoc:

`php drush.php init -vvv`

```
string(140) "
# Include Drush bash customizations.
if [ -f "/home/username/.drush/drush.bashrc" ] ; then
  source /home/username/.drush/drush.bashrc
fi

"
string(141) "
# Include Drush completion.
if [ -f "/home/username/.drush/drush.complete.sh" ] ; then
  source /home/username/.drush/drush.complete.sh
fi

"
string(148) "
# Include Drush prompt customizations.
if [ -f "/home/username/.drush/drush.prompt.sh" ] ; then
  source /home/username/.drush/drush.prompt.sh
fi

"

 Modify /home/username/.bashrc to include Drush configuration files? (yes/no) [yes]:
 > no
```

**Comment by chowdah** [comment]
For the DRUSH non-developers -I just installed drush globally on a new server that I migrated to on Friday. 

When I log in as root on the server, I get this error:
-bash: /root/.bashrc: line 18: syntax error near unexpected token `fi'
-bash: /root/.bashrc: line 18: `fi'


When I log in as the another user, I get no error, and there are no issues using drush from the command line. 

This is the content of the bash rc file with extra lines and line end error :  
`


# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Include Drush bash customizations.if [ -f "/root/.drush/drush.bashrc" ] ; then
  source /root/.drush/drush.bashrc
fi


# Include Drush completion.
if [ -f "/root/.drush/drush.complete.sh" ] ; then
  source /root/.drush/drush.complete.sh
fi


# Include Drush prompt customizations.
if [ -f "/root/.drush/drush.prompt.sh" ] ; then
  source /root/.drush/drush.prompt.sh
fi

`
Using Pico (or other), remove all extra blank lines starting at line 18 (using pico or other)
Also Change:
# Include Drush bash customizations.if [ -f "/root/.drush/drush.bashrc" ] ; then
  source /root/.drush/drush.bashrc
fi
To:
# Include Drush bash customizations.
if [ -f "/root/.drush/drush.bashrc" ] ; then
  source /root/.drush/drush.bashrc
fi

Now my bashrc reads: `
# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Include Drush bash customizations.
if [ -f "/root/.drush/drush.bashrc" ] ; then
  source /root/.drush/drush.bashrc
fi

# Include Drush completion.
if [ -f "/root/.drush/drush.complete.sh" ] ; then
  source /root/.drush/drush.complete.sh
fi

# Include Drush prompt customizations.
if [ -f "/root/.drush/drush.prompt.sh" ] ; then
  source /root/.drush/drush.prompt.sh
fi`

**Comment by jantoine1** [comment]
I'm getting the same error when installing Drush via a Dockerfile that extends the php:apache image which is derived from the debian:jesse image. Here is the snippet from the Dockerfile:
```
# Install Drush dependencies and Drush.
RUN apt update \
  && apt install -y \
    mysql-client \
    rsync \
  && php -r "readfile('http://files.drush.org/drush.phar');" > drush \
  && chmod +x drush \
  && mv drush /usr/local/bin \
  && drush -y init
```
This has worked fine in the past.

**Comment by weitzman** [comment]
Fixed today. Sorry all.

**Comment by Caffe1neAdd1ct** [comment]
Great stuff, thanks for implementing the fix!

**Comment by gitressa** [comment]
In the two commits I can't see that the missing line break is being addressed, or perhaps I am looking the wrong place? This is taken from drush.phar, I have inserted the missing **\n** and made it bold., it's after `Include Drush bash customizations.`:

  // If there is no ~/.drush/drush.bashrc file, then copy
  // the example bashrc file there
  if (!is_file($drush_bashrc)) {
    copy($example_bashrc, $drush_bashrc);
    $pattern = basename($drush_bashrc);
    $bashrc_additions["%$pattern%"] = "\n# Include Drush bash customizations.**\n**". drush_bash_addition($drush_bashrc);
    drush_log(dt("Copied example Drush bash configuration file to !path", array('!path' => $drush_bashrc)), LogLevel::OK);
  }

**Comment by Caffe1neAdd1ct** [comment]
This might not be in the phar yet as that would be generated from the drush source code. 

You can run drush by cloning this repo, composer install and run the drush command inside this repo folder .. that should have the fix if you go from master

**Comment by weitzman** [comment]
Correct - its not released yet. See
https://github.com/drush-ops/drush/compare/8.1.11...8.x

Hopefully soon.

**Comment by gitressa** [comment]
Thanks for the feedback guys, I just can't see the part that says `Include Drush bash customizations` ... but as long as the line break thing is fixed, all is great.

**Comment by gitressa** [comment]
I can confirm that the line break is fixed in the latest official version, thanks.
