### ISSUE TITLE
Drush 9 requires PHP 5.6

### ISSUE THREAD

**Issue by webflo** [drush-ops/drush#2737]
Drush 9 requires PHP 5.6 atm. It this by accident or because we thought D8 will require 5.6?

// cc @alexpott

**Comment by webflo** [comment]
Last drupal-project build on travis ci https://travis-ci.org/drupal-composer/drupal-project/builds/228240365

**Comment by alexpott** [comment]
As far as I know there's no plans for Drupal 8 to require PHP 5.6

**Comment by weitzman** [comment]
When we branched Drush9, we decided to require a non-EOL PHP as minimum. No other reason. I guess this decision could be reverted if anyone feels strongly. See e15e3499ac96daee6ea229f1f80cfea97c9a5ace

**Comment by geerlingguy** [comment]
Also, note that Drupal Core will likely start (justifiably) throwing a warning if you're running an unsupported release of PHP (e.g. 5.5 and below): [Warn users of PHP 5.5 and recommend PHP 7](https://www.drupal.org/node/2670966).

**Comment by alexpott** [comment]
Throwing a warning is different from not allowing installation

**Comment by greg-1-anderson** [comment]
Drush 8 is still supported, and works with Drupal 8.

That said, I'm not opposed to re-introducing php 5.5 in Drush 9. I don't think we've deliberately used any 5.6-only features.
