### ISSUE TITLE
Drush 8.1.11 incompatibilities with Drupal 8.4.x as of 02.05.2017 - Symfony components updated from 2.8 to 3.2.6

### ISSUE THREAD

**Issue by hchonov** [drush-ops/drush#2738]
All Symfony components in Drupal 8.4.x have been updated from 2.8 to 3.2.6.

@see https://www.drupal.org/node/2743809

There are some API changes that have to be made to drush as well, because drush is extending from some Symfony classes.

An example where drush is not working anymore is site install:

> hchonov:drupal hchonov$ drush --version
>  Drush Version   :  8.1.11 
> 
> hchonov:drupal hchonov$ drush si standard
> 
> Fatal error: Declaration of Drush\Command\DrushInputAdapter::hasParameterOption($values) must be compatible with Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false)

**Comment by weitzman** [comment]
Please use Drush9 for Drupal 8.4.x.

**Comment by NiklasBr** [comment]
Will Drush8 ever support Drupal 8.4?

**Comment by weitzman** [comment]
Drush8 will never support Drupal 8.4. Its not possible sine Drupal decided to upgrade its Symfony components.

Just get the most recent release of Drush9 and you should be fine. See Drush install instructions.

**Comment by NiklasBr** [comment]
Ok, I'll hope Drush 9 supports Drupal 6 because we are waiting for a handful och blocking issues which we need to be fixed for our migration from D6 to D8. Thanks!

**Comment by hchonov** [comment]
Drush 9 supports only Drupal 8 according to https://github.com/drush-ops/drush/blob/master/docs/install.md

**Comment by NiklasBr** [comment]
Can I sponsor or set a bounty for Drush 8 to support Drupal 8.4 or Drush 9 to support Drupal 6?

**Comment by weitzman** [comment]
For your migration, use Drush9. You dont have to load up Drupal 6 you just have to query its database. Should work fine AFAIK.

**Comment by generalredneck** [comment]
This is only a problem if you have drush installed via the site's composer.json along side the site correct. If you install drush outside of the dependencies of the site... (say globally) they shouldn't be sharing requirements.
