### ISSUE TITLE
Drush command works with -d but not without

### ISSUE THREAD

**Issue by jsibley2** [drush-ops/drush#2751]
I don't know if this is specific to the drupal module I am using or whether it is a more generic drush issue.

Using drush with views data export, if I don't include "-d", I get an empty file. If I add the "-d", the file has the appropriate data in it.

Any clues about what might be different when running in debug mode that could lead to this behavior?

Thanks!

**Comment by weitzman** [comment]
No idea. Not likely a core Drush issue
