### ISSUE TITLE
Infinite loop in pm-install when sites/all is read-only

### ISSUE THREAD

**Issue by lkmorlan** [drush-ops/drush#2753]
In our environment, we have sites/all read-only and do not install anything there. If pm-install cannot find a module, it attempts to download to sites/all, fails, and loops endlessly. Drush should instead exit will a failure status.

**Comment by lkmorlan** [comment]
The loop is the 'while' loop in drush_pm_enable_validate(). Suggested solution: If when looping back, the list of modules to install is the same as the last time through the loop, exit with an error. The maintainers agree with this approach, I can write a patch.

**Comment by weitzman** [comment]
Seems reasonable.

**Comment by weitzman** [comment]
Fixed in commit above.
