### ISSUE TITLE
`drush pm-update --no` triggers updatedb

### ISSUE THREAD

**Issue by marcvangend** [drush-ops/drush#2760]
I sometimes run `drush pm-update -n` to check for available updates. Today I noticed that, in spite of the `--no` option, the updatedb command is still triggered.

Normally that shouldn't be a problem (you shouldn't have pending database updates when running `drush up` anyway) but it did surprise me. Is this by design? Is there a reason for this behavior that I'm not aware of?

**Comment by weitzman** [comment]
Use `drush updatedb-status`
