### ISSUE TITLE
Feature request: Run specific update with drush

### ISSUE THREAD

**Issue by ivanjaros** [drush-ops/drush#2768]
While developing it is quite useful being able to run a specific update hook. For example:
`drush updb --module=foo --schema=8005`
or even something like
`drush updb --module=foo --schema=">=8005"`

At this time one has to reset the schema verison before running the update again or create a n executable script that will handle it or run it manually via devel's php.

**Comment by gapple** [comment]
I had made a drush plugin that worked for D7; may not be hard to update for D8.

`drush update_rerun foo 7001`
https://gist.github.com/gapple/48ab2dc5424dc3408166

**Comment by weitzman** [comment]
This is contrib territory.
