### ISSUE TITLE
Drush should add an extra confirmation step when installing experimental modules

### ISSUE THREAD

**Issue by anavarre** [drush-ops/drush#2770]
Current state:

```
$ drush @drucker.local en -y layout_discovery
 [success] Successfully enabled modules: layout_discovery
```

Sample expected state:

```
$ drush @drucker.local en -y layout_discovery
WARNING: You're trying to install an experimental module. See https://www.drupal.org/node/XXXXX
I understand the risks [Y/n] y
 [success] Successfully enabled modules: layout_discovery
```

See https://www.drupal.org/node/2880374 for background.

**Comment by weitzman** [comment]
I support that issue on drupal.org. As for Drush, I don't it needs nanny-nags. I'm willing to keep discussing, but this is -1 from me (for Drush).

**Comment by timplunkett** [comment]
If you pass `-y` you shouldn't have to confirm again. But it'd be nice to add the experimental message into the prompt (even if you bypass it)

**Comment by anavarre** [comment]
> If you pass `-y` you shouldn't have to confirm again.

That's the thing. Passing `-y` would leave you with no option but to discover after the fact that this was an experimental module. You'd probably want to know about that before installing the module, especially if it conflicts with an already installed module.

From a UX standpoint the following is probably not great, but I'd rather see an experimental module installed only when a special parameter is invoked with `pm-enabled`, e.g. `--accept-experimental`, no matter if there's a `-y` argument already passed.

E.g.

```
$ drush en -y devel, layout_discovery
(normal messages)
layout_discovery is an experimental module and wasn't automatically enabled.
If you're sure you wish to enable it, pass the --accept-experimental parameter
```

**Comment by timplunkett** [comment]
But isn't that what `-y` means? "Damn the consequences and just do the thing already!"

> discover after the fact that this was an experimental module
Also, if you can figure out the machine name of a module, you can look this up too.

**Comment by anavarre** [comment]
It sure is. I guess I'm just trying to help people make an educated choice based on the special status of experimental modules when they have to make an important decision like installing a module.

**Comment by greg-1-anderson** [comment]
An extra non-confirmed warning message is sufficient here. Folks can always un-install the module if they did not realize in advance that it was experimental.

**Comment by weitzman** [comment]
FYI confirmation is no longer needed when enabling a module unless more dependencies need to be also enabled. Same for uninstall. As of Drush9.

**Comment by weitzman** [comment]
Drupal core can add a nag if it wants to.
