### ISSUE TITLE
drush_cwd() broken in Drush 9?

### ISSUE THREAD

**Issue by Berdir** [drush-ops/drush#2774]
See https://www.drupal.org/node/2825490#comment-12100444

drush rn isn't working with drush 9 because the current working directory seems to be reported as the drupal root folder, not the current module.

The code there, at least my old version still uses getcwd(), but I also tried drush_cwd(), didn't help. And it worked in Drush 8.

**Comment by weitzman** [comment]
Thanks. Lets talk in that issue
