### ISSUE TITLE
Aliases file at $ROOT/../drush/site.aliases.drushrc.php doesn't seem to work. [v7.4.0]

### ISSUE THREAD

**Issue by calvinjuarez** [drush-ops/drush#2776]
<sup>_Super new to Drush, so forgive the lack of technical info._</sup>

At https://github.com/drush-ops/drush/blob/7.x/examples/example.aliases.drushrc.php#L51 it mentions that a _drush/_ folder in the directory above the current drupal root will be searched for aliases.  However, if I've got a _drush/_ directory there w/ _site.aliases.drushrc.php_, when I run `drush sa`, I only get `@none`, `@self` and `default`.  But, if I move that same _drush/_ folder to _drupal/_ or _drupal/sites/all/_ (as also mentioned in the example.aliases.drushrc.php), running `drush sa` shows me my `@site` alias.

Is this a known issue?

---

Drush 7.4.0
macOS Sierra (10.12.5)

**Comment by weitzman** [comment]
It should work. However, you will get better support if you upgrade to latest drush release.
