### ISSUE TITLE
sql-sync --target-dump creates a directory with the filename

### ISSUE THREAD

**Issue by surajho** [drush-ops/drush#2780]
Hi,
At work we have a few websites with fairly large databases. When we use drush sql-sync on these websites, it fails because the target /tmp folder is not large enough to containt the whole sql file after the gunzip command.

I tried to use the --target-dump parameter so sql-sync rsyncs the gz file to a different folder on the server, /path/of/folder/filename.sql.gz. But what happens is, is that sql-sync creates a folder named /path/of/folder/filename.sql.gz and in this folder it rsyncs the gz file. So the full path of the gz file ends up being /path/of/folder/filename.sql.gz/filename.sql.gz.

When sql-sync tries to gunzip the value of the --target-dump parameter, it fails, because it is trying to gunzip a directory.

Is this a known issue of sql-sync and if so, is someone already working on it? I haven't been able to find anything related to this among the open issues.

Kind regards,

Suraj

**Comment by Chi-teck** [comment]
In case you just need to sync your local database. I found that pipes work much faster than sql-sync.
`drush @local sql-drop -y && drush @dev sql-dump --gzip | gunzip | drush @local sql-cli`

**Comment by weitzman** [comment]
I would 

1. create a dump via `drush sql-dump --zip --result-file=/path/to/dump`
1. import it via `drush sql-sync --no-dump --source-dump=/path/to/dump

**Comment by surajho** [comment]
Thank you for the responses. I am aware of the workarounds, which are many, even without using drush.

But my question has not been answered, which is if others are aware of this issue or not. Because we have a nice command, sql-sync, at our disposal, it just misses a certain piece to make life easier. And instead of giving options to circumvent the problem, I was wondering if someone was already working on a solution. So I'll just assume the answer is no.

**Comment by dmsmidt** [comment]
I've encountered this problem as well. This should be handled as a bug report and we should find a way to fix this. The workarounds are no real solution, since documented behaviour doesn't work.
