### ISSUE TITLE
Unable to run Drush command in mac os sierra!

### ISSUE THREAD

**Issue by punyaruchal** [drush-ops/drush#2783]
I am a huge fan of Drush and it makes my work so easy and fast. A few days ago I have formated my PC and setup the new Drush 8.1.11 via composer. Now when I run any Drush command I got following errors. I totally unaware about this error. Does anybody have any idea?

![image](https://cloud.githubusercontent.com/assets/3156932/26617051/a7d74efc-45f2-11e7-8347-073393818aa6.png)

![image](https://cloud.githubusercontent.com/assets/3156932/26617671/23fd6fb8-45f6-11e7-8575-47c217ffc7a1.png)

Thanks for any help.

**Comment by weitzman** [comment]
Please use Drupal Answers for support questions.
