### ISSUE TITLE
drush locale-update and drush entity-updates don't work with custom drush.ini

### ISSUE THREAD

**Issue by SosyalAlkolik** [drush-ops/drush#2784]
Hi, 
I am using Drupal 8.3.2 with Drush 8.1.11 on Centos 7. I put the drush.phar file under the` /opt/drush/ `and there is a` /usr/bin/drush` file. In this file, I directed `/opt/drush/drush.phar` file with 

`/usr/bin/php -c /home/username/.drush/drush.ini /opt/drush/drush.phar "$@" `
When I use these commands, drush doesn't see my custom `drush.ini` file and reads `/etc/php.ini` file and I get an error about `disable_functions` in `php.ini`. How can I  use these commands with custom `drush.ini`? 
Thanks!

**Comment by weitzman** [comment]
Drush no longer supports using a custom .ini. Your technique will work for simple commands but not those that redispatch to a new process.

**Comment by SosyalAlkolik** [comment]
Thanks @weitzman !

**Comment by SosyalAlkolik** [comment]
Hi back, are there any alternative commands which work the same with `drush locale-update` and `drush entity-updates` We don't want to make concessions from security, so we can't change php.ini file. Are there any solutions for my problem?
