### ISSUE TITLE
No release history was found for the requested project (7.54)

### ISSUE THREAD

**Issue by rgoodie** [drush-ops/drush#2789]
I'm trying to `qd` a site to test a module on my local machine. Since upgrading to drush 8 (`8.1.10` specifically), I can no longer pull down Drupal 7. I assume it's how I'm writing out `core=`. 

I've found this invaluable in previous versions of drush. Am I doing something wrong, or is 8 no longer able to qd and run a D7 instance?

`$ drush qd --core=7.54 d7_project`

> No release history was found for the requested project (7.54).     [error]
> Could not download requested project(s).                             [error]
>

**Comment by greg-1-anderson** [comment]
Try `drush qd --core=drupal-7.54 d7_project`
