### ISSUE TITLE
Provide a twig-invalidate command to invalidate Twig compiled files

### ISSUE THREAD

**Issue by anavarre** [drush-ops/drush#2819]
There's a [twig-compile](https://github.com/drush-ops/drush/blob/a115eb726819ee97ea9bbc080f4f223113f996c8/src/Drupal/Commands/core/DrupalCommands.php#L64) command already, but its equivalent for wiping cached files doesn't exist. I think this would make for a good addition.

Currently, your only option is to do as follows:

```
$ drush @site.env ev '\Drupal::service('twig')->invalidate();'
```

**Comment by weitzman** [comment]
This belongs in cache-clear, if anywhere. However, I think that the existing twig debug options are good enough. IMO there is nothing to do here for Drush. Lets keep talking at https://www.drupal.org/node/2752961
