### ISSUE TITLE
sql-create returns no proper exit code

### ISSUE THREAD

**Issue by webflo** [drush-ops/drush#2824]
The exit code for sql-create is always 0 even when it fails because the db config is wrong.

**Comment by webflo** [comment]
I tried to fix in in Drush 9, but the interaction with StatusDeterminerHookDispatcher and runCommandCallback is not clear.

**Comment by jibran** [comment]
This commit broke `drush sql-cli < db.sql`. :disappointed:

**Comment by webflo** [comment]
Use ``cat db.sql | drush sql-cli`` instead.

**Comment by jibran** [comment]
The command is not a problem it is the exit code both commands load the DB just fine but command fails after it finishing loading the DB. It is mysql btw.
