### ISSUE TITLE
drush up doesn't check that new requirements are satisfied

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#2835]
I used drush up to update search_api from an alpha version to the current stable, on Drupal core 8.2.

In between the alpha I had installed and the stable (1.2), the requirement for core was changed -- in the git log for Search API:

```
-  - system (>=8.2)
+  - system (>=8.3)
```
However, Drush didn't check for this and went ahead and installed the update.

**Comment by weitzman** [comment]
pm commands that manage code are maint only, as drush9 no longer does any of that.

**Comment by weitzman** [comment]
Also, dupe of #1285
