### ISSUE TITLE
drush_startup can break drush make if drush is installed via project composer

### ISSUE THREAD

**Issue by swichers** [drush-ops/drush#2844]
Versions:

```
macOS 10.12.5

Drush Version   :  8.1.12

PHP 7.1.6 (cli) (built: Jun 23 2017 08:42:14) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

Project structure:

```
config/
docroot/
composer.json
```

Install drush into the project with `composer require --dev drush/drush`

```sh
cd docroot
drush make /path/to/config/makefile.yml
```

Drush will now incorrectly install the project to the top level (where the composer.json is present) instead of `docroot/`.

In the function `drush_startup` in `startup.inc` the following code changes the working directory which later causes '.' to translate to the wrong path.

```php
  if (empty($found_script)) {
    $c = getcwd();
    // Windows can give us lots of different strings to represent the root
    // directory as it often includes the drive letter. If we get the same
    // result from dirname() twice in a row, then we know we're at the root.
    $last = '';
    while (!empty($c) && ($c != $last)) {
      $found_script = find_wrapper_or_launcher($c);
      if ($found_script) {
        chdir($c);
        break;
      }
      $last = $c;
      $c = dirname($c);
    }
  }
```

The expectation is that if I cd into `docroot/` and run drush make then drush make should default to that folder, and not the folder drush found a launcher in.

Workaround: 

* Remove drush from composer.json
* -OR- Pass the destination folder with drush make if possible

**Comment by greg-1-anderson** [comment]
Make is deprecated. Closing old issues.
