### ISSUE TITLE
Drush help does not list original command name

### ISSUE THREAD

**Issue by darthsteven** [drush-ops/drush#2849]
When using the Drush help command like this:

    drush help pmi

You don't actually get told that this is the `pm-info` Drush command. Might be nice to add it to the output. Maybe before the aliases in the help output? Or possibly it should be considered an alias for the purposes of outputting the help text?

This could be done for all commands in the help command output.

**Comment by weitzman** [comment]
The Examples section of Help usually clears that up as we always use the
long form name for a command. Please contribute examples for any commands
where that might be missing.

**Comment by darthsteven** [comment]
Hmm...that seems a bit odd, pushing the responsibility onto all Drush extension writers to document their commands throughly when Drush itself could simply add a line to the help text output.

Would you welcome a contribution that added this line to the help text output or would that get rejected?

**Comment by darthsteven** [comment]
Meh. This is annoying imho, but let's face it, I'm not going to work on this.
