### ISSUE TITLE
Ignoring update module in Drush site install no longer works

### ISSUE THREAD

**Issue by ivanjaros** [drush-ops/drush#2851]
I stumbled upon this issue before. There was some change made to the Drupal installation form some time ago so the usual `install_configure_form.update_status_module='array(FALSE,FALSE)'` no longer works. I was able to find a solution buried deep in some issue somewhere but now I am not able to find it anywhere, so I am opening a new ticket in here.

What is the proper way to ignore the update module when calling the site install command?

**Comment by weitzman** [comment]
Its documented in the Examples when you run `drush help si`

**Comment by ivanjaros** [comment]
Thanks. So the new way is `install_configure_form.enable_update_status_module=NULL`.
