### ISSUE TITLE
MariaDB unix_socket causes access issues under Debian - Drush can't login

### ISSUE THREAD

**Issue by diqidoq** [drush-ops/drush#2856]
We would like to contribute to the [Drupal docs](https://www.drupal.org/documentation) regarding the usage of [Drush](https://github.com/drush-ops/drush) with [MariaDB](https://mariadb.org/) as the very common [MySQL](https://en.wikipedia.org/wiki/MySQL) replacemant under [Debian](http://www.debian.org) 9 and higher. And especially regarding the common issues with [unix_socket](https://mariadb.com/kb/en/mariadb/unix_socket-authentication-plugin/) defaults of packaged MariaDB under Debian nowadays. Which has many advantages. But it is making Drush unable to connect to the database inside a Drupal project by default, because [unix_socket plugin](https://mariadb.com/kb/en/mariadb/unix_socket-authentication-plugin/) raises root access problems of applications, which are not aware of this change. But Debian crons are. This is what makes it tricky simply changing any defaults for Drush to run without errors, because it can break other things. The user has to change his work flow (rarely findable on Google).

We think this should be documented. There are a few regular not Drush specific work-arounds around on Google, but they all have some different drawbacks here and there and are not obviously to find.

I would like to collect ideas here and all known back and forths. Finally I would like to sum it up and put it up on Drupal.org or in your Drush documentation, if prefered.

Let me start a list of interesting links on this issue (sadly most of them not Drush specific):

 + https://ubuntuforums.org/archive/index.php/t-2275033.html
 + https://bugs.launchpad.net/ubuntu/+source/mariadb-10.0/+bug/1447808
 + https://superuser.com/questions/957708/mysql-mariadb-error-1698-28000-access-denied-for-user-rootlocalhost
 + https://stackoverflow.com/questions/39281594/error-1698-28000-access-denied-for-user-rootlocalhost
 + https://kofler.info/root-login-problem-mit-mariadb/ (German)
 + https://drupal.stackexchange.com/questions/70986/what-complications-are-there-if-i-switch-mysql-to-mariadb-any-drush-issues

Like stated here as an example for some small unexpected issues with Drush/D8 under Debian 9 and MariaDB, there is a certain chance for some Drupal/Drush users to hit exactly the following situation:

Fresh Debian 9 installation with fresh Apache2, PHP7, Drush8, Composer, SQL Server. Now you realize as one of the last on the planet that Debian has changed to MariaDB as default. Oh great, Let's check that out. Now you read everywhere _"It's not a problem. We run it all the time with no problems since years because it's completely exchangeable."_ And you think: _"Well, Not for me"_.

Because:

    drush dl drupal
    cd drupal-8-version/
    drush si --db-url=mysql://root:rootpassword@localhost/yourdbname

e-violá ... Causes the following error:

    Failed to create database: ERROR 1698 (28000): Access denied for user 'root'@'localhost'.

This is something never happened before. Test installations have been ever made pretty easely this way with Drush and database root user back in the days without any problems. Searching for this issue will bring you to some "rare" threads explaining that Debian runs MariaDB with [unix_socket](https://mariadb.com/kb/en/mariadb/unix_socket-authentication-plugin/) plugin **ON** by default, meaning there is no root password set, which can cause some issues when other processes try to access the database server.

Other spots point out it is not a good idea to change that because not only a few threads under Debian expect that setting now. So the common ground of some readings I found _"MariaDB: your app(s) won't know the difference."_ is not true, because it doesn't matter if MySQL is exchangeable with MariaDB like promoted, if the default settings have changed in some Linux distros in a way _"your app(s)"_ can't handle it by default.

**Our first attempt of a small work-around:** For now we run a second database admin user and leave the database root user allone and leave anything like it is by default to not confuse Debian in other corners. This way we can get close to what we expect from before when it comes to test user installations with `drush site-install`. But this is no final fix, because other shell scripts or automations connected to Drush are more complex and would like to run like before.

**Comment by diqidoq** [comment]
Closed issue. Reason: missing interest and/or maybe missleading issue description. **For searchers coming here hoping for some enlightment:** atm I only see the option to create a second DB admin user for the use with Drush. Do not touch the MariaDB default settings. Leave the default DB root alone with Debian and do all your DB admin things with admin nr. 2. Otherwise it will cause trouble one day.

**Comment by ao2** [comment]
Creating an additional admin user is what Debian maintainers recommend in `/usr/share/doc/mariadb-server-10.1/README.Debian.gz` in the **PASSWORDS** section, also here:
https://salsa.debian.org/mariadb-team/mariadb-10.1/blob/stretch/debian/mariadb-server-10.1.README.Debian#L73

The `README.Debian` file is the first place to look for package specific quirks in Debian, unfortunately is a little under documented, and in this particular case is especially painful as people usually end up changing the default root user settings breaking the maintainer scripts on their system.
