### ISSUE TITLE
Feature Request: Some sort of Quiet Mode for error type messages.

### ISSUE THREAD

**Issue by chriscalip** [drush-ops/drush#2858]
Lets have an option to suppress the error type messages. 

Drush\Log\Logger lets users suppress most type of messages. We should have an option for error type messages too.

**Comment by weitzman** [comment]
Can you give an example? I'm not sure what error type messages are.

**Comment by chriscalip** [comment]
Right; for set $level types = {'LogLevel::WARNING', 'cancel', 'failed', 'error', 'ok', 'completed', 'success', 'status', 'notice', 'message', 'info'};
As a drush user there are ways to suppress messages of certain message level types; eg. `--quiet` parameter to suppress 'status' messages.
Lets have an option to suppress the 'error' level type messages via somesort of `--xxx` parameter.
It is useful for many situations eg. on `drush pm-updatestatus --pipe --format=list` just the list of modules available for updates and ignore the noise/false alarm messages.

**Comment by greg-1-anderson** [comment]
@chriscalip redirect stderr to /dev/null via `2> /dev/null` and all status messages will be removed.

**Comment by chriscalip** [comment]
@greg-1-anderson That only works if the originating drush call host server is the same with the intended drush executioner. For example `drush pm-updatestatus --pipe --format=list 2>/dev/null`
But on a local to remote calls for example
`terminus drush xxx.chriscalip -- pm-updatestatus --pipe --format=list 2>/dev/null` redirect stderr is not going to work.

**Comment by weitzman** [comment]
i don't think we will do this.
