### ISSUE TITLE
Syncronice back to Drupal .org  to localize drush

### ISSUE THREAD

**Issue by horvan** [drush-ops/drush#2863]
Is it possible to sync github Releases back to Drupal.org to  make sure drush could still be localized via localize.drupal.org?

**Comment by greg-1-anderson** [comment]
This is theoretically possible. Would anyone localize Drush if this was done?

Would it be sufficient to just push the commits back to the repository on drupal.org? Would we also need to push tags? Would we need to create a drupal.org release?

**Comment by horvan** [comment]
As far as I know Drush had support to 8,x-6.0-rc4 at localize,drupal.org and this is the last release available from drupal.org, too. 

So if it is not to much amount of work to synchronize resales back to drupal.org this would be enough to make it possible. 

Some drush commands are already translated with the modules on drupal.org in some languages. 

It would be great if you can push some drush resales to drupal.org, again so that the translation teams on localize.drupal.org have the ability to translate drush to their languages and the users get as less mixed output as possible between English and there own language, when using drush.

Otherwise you miss the opportunity to get drush translated in over 100 languages. 

I am part of the German localisation teem and I like to have the ability to translate this great command line tool very much.

**Comment by weitzman** [comment]
Sorry, we are not planning to use localize.drupal.org.
