### ISSUE TITLE
sql-sync: The input line is too long

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#2871]
When running:

    drush sql-sync @src @dst

to sync the db from remote (Linux) to local (Windows), the command fails with:

> The input line is too long.

![](https://image.prntscr.com/image/bZSw75AuQnuMjyeIS5lWvw.png)

This is something to fix?

**Comment by greg-1-anderson** [comment]
What shell are you using? Maybe try bash? It's provided by msysgit.

**Comment by kenorb** [comment]
Won't be able to reproduce this (as I'm on Mac when this command works) as the screenshot is from my colleague where the same command doesn't work on Windows. Closing for now, unless somebody will have more details about this issue.
