### ISSUE TITLE
uli --no-browser and similar negations are unrecognized options

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2878]
This contradicts our `uli` docs and elsewhere.

**Comment by GBirch** [comment]
See PR #2868 , which seems to fix this issue as well.

**Comment by greg-1-anderson** [comment]
Does #2868 allow the user to specify **--no-**browser? I didn't see any code in the PR to allow that. I think that only `--browser` is supported there.

**Comment by GBirch** [comment]
I was not trying to solve this problem with my PR; I just noticed that it did.  Maybe something to do with changing the process signature?  In any event, the PR seems to make drush honor --no-browser, at least on my Ubuntu box:  i.e. if you do not use --no-browser, the uli launches in the browser, if you do use --no-browser it does not.    And I did not go looking for any other "no-" options.

**Comment by greg-1-anderson** [comment]
This is fixed in #2843
