### ISSUE TITLE
Drush incorrectly reports test themes as missing modules

### ISSUE THREAD

**Issue by madmanmax** [drush-ops/drush#2886]
This is a bit of an edge case but it can create confusion since it looks like the error is coming from drupal. If a module comes with a test theme and the setting `extension_discovery_scan_tests` is set to `TRUE` certain `drush` commands will incorrectly report that a module (the test theme) is missing.

Steps to reproduce the problem:
- clean drupal 8 installation
![drush_status](https://user-images.githubusercontent.com/1675195/29514327-69a4e94e-8668-11e7-81c0-3666ffe80c95.png)
- add `$settings['extension_discovery_scan_tests'] = TRUE;` in `sites/default/settings.php`
- `drush en -y mailsystem`
- `drush pm-updatestatus`

![missing_module_warning](https://user-images.githubusercontent.com/1675195/29514268-3d4bd1b4-8668-11e7-965f-bdbf23988f18.png)

The problem seems to be how the `extensions` array for a project is being built. It will include both themes and modules. Inside `drush_get_projects` the `drush_pm_find_common_path` is being called that uses the last extension (which in this case is a theme) to find the path and will trigger the error.
![project_extensions](https://user-images.githubusercontent.com/1675195/29516909-dfc98198-8672-11e7-8a80-2f288af7eae3.png)

My digging around got me so far, unfortunately I don't have so much `drush` experience to provide a pull request. Probably the extensions array should contain either only modules or keep the modules and themes separate.

**Comment by joncatalyst** [comment]
also seeing - thanks for reporting!
and news on  fix?

**Comment by weitzman** [comment]
Drupal is reporting that missing extension, not Drush.
