### ISSUE TITLE
load custom commands from /etc/drush

### ISSUE THREAD

**Issue by drzraf** [drush-ops/drush#2893]
Drush already looks for custom commands from `~/.drush`
It'd be appreciated if it could looks for them inside `/etc/drush` too.

Our team shares a couple of custom commands (`search/replace,` `patch-file`, and sometimes custom ones intended for maintenance tasks).
Having these commands in one place would help ensuring availability, consistency (same version) and simplicity.

**Comment by weitzman** [comment]
You can add custom search locations with --include. No more built-in global
locations will be added. The trend is to check custom commands into your
codebase.

**Comment by greg-1-anderson** [comment]
Global Drush commands are loaded from `/usr/share/drush/commands`

**Comment by greg-1-anderson** [comment]
Drush commands may be committed to your codebase in __DRUPAL_ROOT__/drush

**Comment by drzraf** [comment]
Thank you for the good tips.
I ended up using `/usr/share/drush/commands` because I manage several core installations and wanted commands for all, but both path may be useful.

**Comment by greg-1-anderson** [comment]
The global location is actually `getenv('SHARE_PREFIX') . '/share/drush/commands'`, so you can
```
export SHARE_PREFIX='/usr/local'
```
and it will work the way you'd like it to.
