### ISSUE TITLE
"Unknown options" with drush dl (version 9.0-alpha1)

### ISSUE THREAD

**Issue by DicksB** [drush-ops/drush#2895]
I have a composer script running the following command:

```
/Users/wrd/Documents/Drupal/Repositories/Drupal/drupal84/vendor/bin/drush dl drupal-8 --root=/Users/wrd/Documents/Drupal/Repositories/Drupal/drupal84/tmp --destination=/Users/wrd/Documents/Drupal/Repositories/Drupal/drupal84/tmp --drupal-project-rename=drupal-8 --quiet --yes
```

This results in the following error:

```
[error]  Unknown options: --destination, --drupal-project-rename.  See `drush help pm-download` for available options. To suppress this error, add the option --strict=0. 
```

Running the help command, I get:

```
/Users/wrd/Documents/Drupal/Repositories/Drupal/8.x/vendor/bin/drush --help pm-download

Options:

Aliases: dl
```

Not sure if I've somehow managed to screw up installing drush (composer require drush/drush:9.*), or if these options are just not yet implemented in drush 9, or what. I have tried dev-master and beta1 as well as alpha1, with the same results. I guess I'm not sure if this is an issue, or if I've just done something wrong...any suggestions appreciated.

**Comment by weitzman** [comment]
`dl` has been removed from Drush9. Use Composer instead to build your site.
There is a deprecation message if you run `drush dl`. But you never saw it because you used no-longer-valid options and then you used help. Neither of those paths show you what you needed to see. I'll think about a fix.

**Comment by greg-1-anderson** [comment]
It would be nice if we had a mechanism to customize / enhance error messages for commands. e.g. for `drush dl drupal` "Drush 9 doesn't do that any more: see ...".

**Comment by DicksB** [comment]
I actually am using Composer to build the site. I'm using Drush inside a post-update-cmd script to download the Drupal distribution and copy the scaffolding files if the core version has changed. I suppose I can probably use curl for the purpose instead.

**Comment by greg-1-anderson** [comment]
See https://github.com/drupal-composer/drupal-project and https://github.com/drupal-composer/drupal-scaffold.

**Comment by DicksB** [comment]
That's actually where I copied the drush command from. Our needs don't quite match their setup, but it served as a very useful guide to getting our 8.3 stuff working.

I don't think this turns out to be a significant problem. Looks like I can just check the core version, use that to build a valid URL, and grab the download with curl. Thank you for your help!
