### ISSUE TITLE
drush up drupal -d Version 8.1.13  - Destination directory already exists

### ISSUE THREAD

**Issue by jkeruzec** [drush-ops/drush#2896]
Hello,

I'm trying to upgrade a Drupal 8 installation on Centos 6.8 with latest Drush 8.1.13.
PHP Version : PHP 5.6.27 (cli) (built: Oct 15 2016 21:31:59)
My command is:
drush up drupal -d 

After decompressing the drupal 8.3.7 archive, I have this following : 

> drupal-8.3.7/vendor/.htaccess
>  drupal-8.3.7/vendor/web.config
>  drupal-8.3.7/LICENSE.txt
> Calling chdir(/var/www/XXX/XXX/XX-portal) [29.8 sec, 49.37 MB]    [debug]
> 
> Destination directory /var/www/XXX-XXX-XX-portal/drupal-8.3.7 already exists. [29.8 sec, 49.37 MB] [error]
> 
> Updating project drupal failed. Attempting to roll back to previously installed version. [29.8 sec, 49.38 MB]     [error]
> Returned from hook drush_pm_updatecode [29.8 sec, 49.24 MB] [debug]
> Rolling back update of Drupal core code ... [29.8 sec, 49.24 MB] [notice]

I succeed to upgrade this drupal on Windows local dev server from an VM Ubuntu after few tries but not with Centos production installation.

Any clue to help me ?

Regards,

**Comment by weitzman** [comment]
Please use Drupal Answers for support questions.

**Comment by jkeruzec** [comment]
Ok I did it : 
https://drupal.stackexchange.com/questions/244708/drush-up-drupal-d-version-8-1-13-destination-directory-already-exists
