### ISSUE TITLE
Use user-specific git credentials with --working-copy

### ISSUE THREAD

**Issue by ezra-g** [drush-ops/drush#29]
As a distribution maintainer, I'd love to have Drush make --working-copy checkout repositories with my git credentials so that I can write to their repositories without having to do git set-url and providing my credentials.

Drush pm includes a --gitusername flag, however, I'm not clear on how and whether this could be used with Drush make:

"drush make commons-profile/build-commons-dev.make --working-copy --gitusername=ezrag ./commons-builds/latest-3
Unknown option: --gitusername. See `drush help make` for available options. To suppress this error, add the option --strict=0."

**Comment by greg-1-anderson** [comment]
Drush make is maintenance only; closing.
