### ISSUE TITLE
none of the methods in Commandfiles/CommandfilesInterface are documented

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#2902]

**Comment by weitzman** [comment]
I agree that doxygen is great, and welcome. However, we are not using the issue tracker for tracking such deficiencies.

**Comment by joachim-n** [comment]
Where are you tracking them then?

**Comment by weitzman** [comment]
we aren't. the only remedy is to submit a pr to make docs better.

**Comment by joachim-n** [comment]
Ok, I'm not going to submit a PR to write docs for *your* project, now or anytime soon. The reason being that *I* understand most of it, while *you* do. The knowledge is already in *your* brain, but not in mine. It's a grossly inefficient use of overall developer time for me to try to understand and figure out how your project works in order to write documentation, when it's something that you already know.

I was trying to be helpful to highlight that the docs are missing here, because it's perhaps something that's fallen off your radar. Without docs it's harder for other devs to understand your code. Without docs, another developer who is encountering a bug in your code and wants to fix it is more likely to give up, because as they make their way through the code they encounter one thing after another that they need to unpick, and the hurdles just add up.

I feel that because of that, writing docs is a valuable investment of time, but if you feel that it's not worth tracking as a task, then perhaps you don't agree.

**Comment by greg-1-anderson** [comment]
Commandfiles/CommandfilesInterface are internal classes that extension writers do not need to user or extend.

**Comment by greg-1-anderson** [comment]
Actually, these are obsolete. I'm removing them.
