### ISSUE TITLE
_drush_add_commandfiles() needs documentation

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#2903]

**Comment by greg-1-anderson** [comment]
Alas, more of the Drush 8 (and earlier) internal methods should indeed have been better documented. This method is now deprecated (or will be) - maintainer efforts are focused on the new dispatcher, so older methods are unlikely to get the documentation they deserve. We will try to answer specific questions, & could consider contributed PRs that improve docs in these areas.
