### ISSUE TITLE
command file discovery searches in lib/Drush, which doesn't exist

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#2904]
While trying to figure out why my command files don't get picked up, I spotted that Drush searches in lib/Drush -- in my case, "/Users/joachim/Sites/8-drupal/vendor/drush/drush/lib/Drush".

This seems to be the code in drush_init_annotation_commands():

```
  $commandFiles = $discovery->discover(DRUSH_BASE_PATH . '/lib/Drush', '\Drush');
```

**Comment by greg-1-anderson** [comment]
This location is for core Drush commandfiles only. Drush 9 uses a different internal path.

**Comment by joachim-n** [comment]
Commit  65c2383 is removing rather more than what this issue is about:

```

-  // Search for commandfiles in the root locations
-  $discovery = annotationcommand_adapter_get_discovery();
-  $searchpath = [dirname($root) . '/drush', "$root/drush", "$root/sites/all/drush"];
-  $drush_root_extensions = $discovery->discover($searchpath, '\Drush'); 
```
is that right?

**Comment by weitzman** [comment]
Yes, thats also stale code. Those locations are checked in \Drush\Boot\DrupalBoot::commandfileSearchpaths
