### ISSUE TITLE
@complete annotation in commands references class that doesn't exist

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#2906]
Several @complete annotations reference the class Drush\Commands\CompletionCommands, which AFAICT doesn't exist. Eg:

```
     * @complete \Drush\Commands\CompletionCommands::completeModules
```

**Comment by weitzman** [comment]
Yes, these complete annotations and methods should be removed for now.

**Comment by greg-1-anderson** [comment]
Once we are using the Symfony dispatcher, we can autocomplete with https://github.com/bamarni/symfony-console-autocomplete
