### ISSUE TITLE
drush_get_option() doesn't get default value defined in command method's parameters

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#2907]
According to the docs, the way to define options and their default value is in the method declaration:

```
  public function myCommand($options = ['foo' => 'bar']) {
```

However, when I run the command without giving the --foo option, drush_get_option() doesn't return the default value.

**Comment by weitzman** [comment]
drush_get_option() is not supported in annotated commands.

**Comment by joachim-n** [comment]
This needs documenting -- can you reopen please?

The context.inc file has a large docs section at the top of it that makes it sound like it's for all commands:

>  * This API also acts as an IPC mechanism between the different drush commands,
