### ISSUE TITLE
Relative root paths no longer seem to work

### ISSUE THREAD

**Issue by jhedstrom** [drush-ops/drush#2909]
When switching from Drush 8 to Drush 9, I noticed that relative `--root` paths don't seem to work for providing the core location.

Here's output for a build that exists in `build/html`:

**With relative `--root`**
```
$> vendor/bin/drush -r build/html status
 PHP binary    : /usr/local/Cellar/php70/7.0.12_5/bin/php
 PHP config    : /usr/local/etc/php/7.0/php.ini
 PHP OS        : Darwin
 Drush script  : /.../vendor/bin/drush
 Drush version : 9.0-dev-g65c2383
 Drush temp    : /tmp
 Drush configs :
 Drush aliases : /.../.drush/aliases.drushrc.php
                 /.../.drush/drupalEight.aliases.drushrc.php
```

**With no `--root`** (behaves the same as with absolute path for root arg)
```
$> vendor/bin/drush status

 Drupal version : 8.4.0-beta1
 Site URI       : http://default
 PHP binary     : /usr/local/Cellar/php70/7.0.12_5/bin/php
 PHP config     : /usr/local/etc/php/7.0/php.ini
 PHP OS         : Darwin
 Drush script   : /.../vendor/bin/drush
 Drush version  : 9.0-dev-g65c2383
 Drush temp     : /tmp
 Drush configs  :
 Drush aliases  : /.../.drush/aliases.drushrc.php
                  /.../.drush/drupalEight.aliases.drushrc.php
 Drupal root    : /.../build/html
 Site path      : sites/default
```

**Comment by greg-1-anderson** [comment]
We're rewriting the bootstrap / preflight at the moment. See https://github.com/drush-ops/drush/pull/2843. Let's make sure it works there.

**Comment by weitzman** [comment]
Looks fixed to me.

**Comment by pingers** [comment]
Relative paths working here too - thanks!

**Comment by pjcdawkins** [comment]
I've found a relative `--root` path does not work in Drush 9.5.2. I suppose there was a regression?

**Comment by greg-1-anderson** [comment]
How about in 9.6.0-rc3?

**Comment by greg-1-anderson** [comment]
Hm, yes, broken in HEAD of master too.

**Comment by pjcdawkins** [comment]
Hi @greg-1-anderson I did some digging and opened https://github.com/webflo/drupal-finder/pull/40

**Comment by greg-1-anderson** [comment]
Seems to be working for me now in today's HEAD of the `master` branch. Maybe some of our recent bootstrapping improvements accidentally fixed this.

@pjcdawkins / other interested parties: could you please test and confirm?

**Comment by greg-1-anderson** [comment]
We'll re-open if this crops up again

**Comment by JTubex** [comment]
@greg-1-anderson, I'm still having this issue.

Running `drush cr -vvv` gives the following output:

```
[preflight] Redispatch to site-local Drush: /var/www/..../htdocs/vendor/drush/drush/drush.
[preflight] Redispatch to site-local Drush: /var/www/..../htdocs/vendor/drush/drush/drush.
[preflight] Redispatch to site-local Drush: /var/www/..../htdocs/vendor/drush/drush/drush.
```

Probably not the best fix, but adding `$root = realpath($root);` in `Drush\Preflight\RedispatchToSiteLocal::findSiteLocalDrush()` did the trick for me:

```    /**
     * Find a site-local Drush, if there is one in the selected site's
     * vendor directory.
     *
     * @param string $root The selected site root
     */
    protected static function findSiteLocalDrush($root)
    {
      $root = realpath($root);
        $candidates = [
            "$root/vendor/drush/drush/drush",
            dirname($root) . '/vendor/drush/drush/drush',
        ];
        foreach ($candidates as $candidate) {
            if (file_exists($candidate)) {
                return $candidate;
            }
        }
    }```

**Comment by greg-1-anderson** [comment]
Maybe `Path::canonicalize` would also work here? A PR would be welcome.

**Comment by JTubex** [comment]
I Created PR: #4019
