### ISSUE TITLE
installing global commandfiles with composer?

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#2911]
Is it possible to install global commandfiles as composer dependencies?

**Comment by greg-1-anderson** [comment]
Possible future feature. See https://github.com/consolidation/Robo/pull/604

Feedback welcome if this feature looks interesting.

**Comment by joachim-n** [comment]
My use case for this would be to allow users to install https://github.com/drupal-code-builder/drupal-code-builder-drush with composer (and its dependencies) rather than having to say 'download, put in the right folder for Drush to find, and then do 'composer require foobar' manually to get its dependencies.

**Comment by weitzman** [comment]
If admins setup their Composer project via drupal-project, and you classify Codebuilder as a drupal-drush type, then Codebuilder will be installed into the right place. See installer-paths at end of composer.json - https://github.com/drupal-composer/drupal-project/blob/8.x/composer.json#L72

Note that Drush9 now has a `generate` command that wraps [DCG](https://github.com/Chi-teck/drupal-code-generator)
