### ISSUE TITLE
 failed to open stream: No such file or directory JSONCache.php:25

### ISSUE THREAD

**Issue by Jackson8Zhang** [drush-ops/drush#2912]
[warning] file_put_contents(C:/Users/Administrator/.drush/cache/factory/Drush\Commands\ValidatorsCommands.cache): faile
d to open stream: No such file or directory JSONCache.php:25

drush:9.0.0-beta4
php:7.1.8
drupal:8.3.7

**Comment by newsec** [comment]
Same errors after updating to 9.0.0-beta4. 
Seems that Drush can't create subdirectories in "factory/Drush" directory in Windows environment.

**Comment by newsec** [comment]
Think so

**Comment by weitzman** [comment]
I pushed a quick fix for this to 8.x and master. I didn't try on Windows so not 100% sure. Please post here if this fixes or does not fix the problem. I'll reopen if needed.

**Comment by weitzman** [comment]
My fix caused test fails, so reverted both branches. Someone needs to work on a better fix.

**Comment by newsec** [comment]
drush_mkdir() function ensures only ".drush\cache\factory\Drush" path and not path from $cid.

**Comment by weitzman** [comment]
Pushed a different fix to 8.x and master.
