### ISSUE TITLE
By default, remove global discovery of aliases/commandfiles

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2914]
That is, stop looking in /etc/drush and /usr/share except for config. Folks who want this capability can configure their Drush to look there via --include, --alias-path. The config for doing so can go into a top level /drush folder as proposed in [drupal-project](https://github.com/drupal-composer/drupal-project).

The goal here is to nudge users to commit their aliases and commands to the composer project.

**Comment by greg-1-anderson** [comment]
This isn't the best when putting Drush into a docker container, for example. It would be nice if there was a site-wide location for Drush config (drushrc.php / drush.yml).

I was actually advocating for cutting it the other way, and not looking for aliases or commandfiles in global locations (user home directory, /etc/drush, etc.)

**Comment by weitzman** [comment]
Acquia uses global config  to add an alias-path location which points to some bad aliases which I'd rather not get discovered. They have a  bad %drush-script in them. Maybe we could resolve that but not auto-upgrading legacy aliases. That would let us keep global config.

**Comment by greg-1-anderson** [comment]
Hm, it seems like it's always going to be possible for someone to add bad config. If we changed the path to the global config, or renamed `%drush-script`, the culprit might just "fix" the problem with a variant of the same error (e.g. alias.yml files with similar bad config). Maybe we need some sort of config "exclude" option that is built up as config is loaded, and then used to erase everything excluded at the end of config parsing. Then folks could turn off bad config on their system as needed.

As far as auto-upgrading aliases is concerned, I was thinking that perhaps we could make thyou e upgrade operation a command, as you suggested, and offer auto-upgrade as an example hook that folks could enable if they wanted the behavior.

**Comment by weitzman** [comment]
+1 to alias upgrade-as-command.

If Drush9 ignores old style config files, then I see now that Acquia problem is moot.

**Comment by weitzman** [comment]
Lets close in favor of #2995
