### ISSUE TITLE
drushrc.php in ~/.drush isn't getting picked up

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#2917]
```
$ ls ~/.drush
cache
drush8rc.php
drush9rc.php
drushrc.php
```

None of these are getting picked up with the latest clone of Drush from master. I've put statements that should crash everything in all of them, and Drush doesn't crash!

**Comment by weitzman** [comment]
Have you specified --local in CLI or config? The place where this should get loaded is pretty early in drush_preflight(). See https://github.com/drush-ops/drush/blob/9.0.0-beta4/includes/preflight.inc#L463

**Comment by joachim-n** [comment]
Nope, all I changed was did a composer update going from beta 2 (I think?) to beta 4.

But drush_get_option('local') *thinks* it's true.

One other difference is I am now going through the launcher. Is that maybe setting the --local option? Should it?

**Comment by greg-1-anderson** [comment]
It is also my opinion that it would be preferable if the launcher did not set `--local`.

**Comment by weitzman** [comment]
Yes, launcher currently sets --local. Lets remove that once we get #2914. I'm not sure we need to tie these two issues but seems prudent

**Comment by weitzman** [comment]
The latest Launcher no longer sets --local.
