### ISSUE TITLE
drush dl: "exec(): Unable to fork [wget --version 2>&1] exec.inc:150" "wget nor curl executables found"

### ISSUE THREAD

**Issue by hackish** [drush-ops/drush#292]
drush has been working fine without any problems but suddenly since yesterday whenever I attempt to download a module using drush dl, I get the following error:

exec(): Unable to fork [wget --version 2>&1] exec.inc:150
exec(): Unable to fork [curl --version 2>&1] exec.inc:150
exec(): Unable to fork [which curl 2>&1] exec.inc:150
wget nor curl executables found

I have drush 6.1.0 installed on Ubuntu 12.04.3 LTS running PHP 5.3.10-ubuntu3.8 with Suhosin-Patch

**Comment by saleo** [comment]
thx, worked for me too

**Comment by mbarcia** [comment]
<code>service apache2 restart</code> solved it for me as well.

**Comment by antoniodltm** [comment]
Thank you, it worked for me too.
