### ISSUE TITLE
Warn users that D8 will soon require drush 9

### ISSUE THREAD

**Issue by AdamPS** [drush-ops/drush#2922]
For background see this [Drupal.org issue](https://www.drupal.org/node/2874827).

Request is to have a new version of drush 8 that prints a warning when run against Drupal 8.
Warning: drush 8 will soon cease to be supported for Drupal 8, please see https://XXXPAGE for details.

There should be a way for the user to disable the warning once they have read it.

**Comment by mlncn** [comment]
This would have been nice for Drupal 8.4.  Would still be nice, for late upgraders and people trying to  figure out why Drush 8.14 and Drupal 8.4 can't even resolve their symfony dependencies.

**Comment by greg-1-anderson** [comment]
We are actually working on an 8.1.15 release to resolve that issue. See https://github.com/drush-ops/drush/pull/2800

Sorry we didn't get all of the issues resolved prior to the 8.4.0 release.

**Comment by mlncn** [comment]
Oh awesome thanks.

After upgrade to Drush 9 and Drupal 8.4 i can't get Drush to see Drupal on our server (it works locally, and everything is composer managed so i'm at a complete loss as to what the difference would be locally versus on the server).  Maybe one of the permutations of a global Drush 8 in that issue will solve it for me...

**Comment by mlncn** [comment]
Drush 8.x-dev is now working for me with Drupal 8.4.  Thanks!

**Comment by AdamPS** [comment]
Since I raised this issue, I have learnt that there are back-compatibility problems, in particular (see [link](http://docs.drush.org/en/master/install/))

> Drush 9 cannot run commandfiles from Drush 8 and below (e.g. example.drush.inc).

Hence I am closing this issue in favour of #3042

**Comment by weitzman** [comment]
Out of curiosity, whats keeping you on Drush8? Any must-have contrib
commandfiles that are not yet ported?

**Comment by grasmash** [comment]
The main reason for staying on Drush 8 are:
 
- [Issues with configuration imports](https://github.com/drush-ops/drush/issues/2953)
- Various contributed modules have not yet upgraded commands to Drush 9 (acsf, [migrate](https://www.drupal.org/node/2914005), [features](https://www.drupal.org/node/2913651), etc.)
- Incompatibility with hosting environments (Acquia), [issues with aliases](https://github.com/drush-ops/drush/issues/3017#issuecomment-334859422).
- Unreadiness [in our own tools](https://github.com/acquia/blt/issues?q=is%3Aissue+is%3Aopen+label%3Adrush)

**Comment by AdamPS** [comment]
- My understanding is that drush 9 is missing several pm-* commands
- Custom (site-local) drush commands
- Migrating sites already delivered to a customer seems like unnecessary work that no one will pay for

> Any must-have contrib commandfiles that are not yet ported?
How would I find out? :-)

Drush 9 is still beta.  Normally open-source software continues to support an old major release for a good while after the new one is released stable to allow users sufficient time to migrate.

**Comment by AdamPS** [comment]
With modules installed on a site:

- 1 result for find -name drush.services.yml (devel:-))
- 9 results for find . -name "*.drush.inc"

Does either drush version support both?  If not, any suggestions for how it will work when some contrib modules are on one system and some on the other?

**Comment by greg-1-anderson** [comment]
@adamPS See https://github.com/drush-ops/drush/issues/3041 for a discussion on issues related to compatibility between Drush 8 and Drush 9 for new-style commandfiles.

**Comment by AdamPS** [comment]
@greg-1-anderson thanks so if I understand correctly, drush 8 supports both the old and the new way.

Hopefully after drush 9 is released over a year or so most modules will gradually port over.  In the meantime drush 8 will be useful to many users.

**Comment by alisonjo2786** [comment]
We're staying with drush 8 b/c of the loss of pm-* commands :(

**Comment by gitressa** [comment]
> Out of curiosity, whats keeping you on Drush8? Any must-have contrib commandfiles that are not yet ported?

At the very bottom ("Find most used ...") are the most used Drush commands in a recent project of mine. Of these, I would say the following are essential, and would be a big loss. I am not sure if site-install has been removed in Drush 9?

- dl
- site-install
- up
- make
- generate-makefile
- archive-dump

**Find most used Drush commands**
`history | grep drush | awk '{print $3}' | sort  | uniq --count | sort --numeric-sort --reverse | head -30`

96 dl
49 config-export
48 en
47 site-install
37 up
26 pmu
25 config-import
15 pm-list
14 st
14 make
12 user-create
12 user-add-role
11 migrate-import
11 cset
10 migrate-status
8 migrate-rollback
8 archive-dump
7 generate-makefile
4 sset
4 require
4 pm-refresh
3 cr
