### ISSUE TITLE
console questions don't allow an empty response

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#2931]
```
    $question = new \Symfony\Component\Console\Question\Question(
      "Enter a value"
    );
    $value = $this->io()->askQuestion($question);
```
This doesn't allow an empty input. I've tried passing NULL and '' as the default parameter in the constructor too. The output is:

```
 [ERROR] A value is required.
```

With a plain console app, it works fine:

```
      $question = new \Symfony\Component\Console\Question\Question(
        "Enter a value"
      );
      $helper = $this->getHelper('question');
      $name = $helper->ask($input, $output, $question);
```

That allows an empty input.

**Comment by joachim-n** [comment]
I wonder whether this is a Symfony version issue, as my test code is using Symfony 3.3, or whether it's something Drush or AC is doing?

The responsible code is this in Symfony:

```
        $validator = $question->getValidator();
        $question->setValidator(function ($value) use ($validator) {
            if (null !== $validator) {
                $value = $validator($value);
            } else {
                // make required
                if (!is_array($value) && !is_bool($value) && 0 === strlen($value)) {
                    throw new LogicException('A value is required.');
                }
            }

            return $value;
        });
```

and looking at that, the workaround is to set a dummy validator like this:

```
    $question = new \Symfony\Component\Console\Question\Question(
      "Enter a value"
    );
    $question->setValidator(function ($answer) { return $answer; });
    $value = $this->io()->askQuestion($question);
```

**Comment by greg-1-anderson** [comment]
`$this->io()` is a SymfonyStyle object, whereas your other example uses a QuestionHelper. You could always just instantiate a QuestionHelper via `new QuestionHelper()` and call ask. That should work. Your no-op validator also looks like a viable workaround.

**Comment by joachim-n** [comment]
>  new QuestionHelper()

Is that the correct way to get a QuestionHelper?
The Symfony console docs all have calls to $this->getHelper('question'), but that's not available in AC command callbacks.

**Comment by greg-1-anderson** [comment]
`getHelper` does the appropriate dependency injection for the helper object. The QuestionHelper does not need any DI. I suppose we could / should expose the helper object for folks who want to use it, as there is always a chance that future versions of Symfony might add more DI to the QuestionHelper.

**Comment by joachim-n** [comment]
Confirming that this works:

```
    $question_helper = new \Symfony\Component\Console\Helper\QuestionHelper();
    $question = new \Symfony\Component\Console\Question\Question(
      "Enter a value"
    );
    $value = $question_helper->ask($input, $output, $question);
```

but the downside with this is that the question output isn't formatted the same way as other questions.

I'll stick with the dummy validator for now.

**Comment by joachim-n** [comment]
This doesn't seem to have been fixed:

```
    $question = new \Symfony\Component\Console\Question\Question(
      "Enter a value",
      ''
    );
    $value = $this->io()->askQuestion($question);
```

Result:

```
$ drush9 cbm

 Enter a value []:
 >



 [ERROR] A value is required.


 Enter a value []:
 >
```

**Comment by greg-1-anderson** [comment]
You're working with Symfony code here - we don't control the implementation. Did your dummy validator idea not work out?

**Comment by joachim-n** [comment]
Yes, it did.

But is there not a bug in the wrappers that the Drush stack puts around Symfony?
