### ISSUE TITLE
Let drush dl and drush up detect local modifications ("hacks")

### ISSUE THREAD

**Issue by donquixote** [drush-ops/drush#2937]
Currently, drush up or drush dl will silently wipe local modifications (hacks).

A trick I found myself:
- download the same version of a module that is already installed.
- look at the diff. If none, proceed as usual.
- If there is a diff, commit it (git). We now have a commit that wipes the local changes and restores the original state.
- Download the new version. Commit.
- Revert HEAD^^, restoring the local changes.
- Squash the last 3 commits.

I have also worked in teams where we had other work flows to maintain local changes. E.g. with a folder full of patches.

Either way: None of those tricks prevents a careless user from wiping local changes with drush dl or drush up.

Could we somehow implement a cheap version of the above mentioned trick into drush dl / up?
- Somehow get a hash of current module directory contents.
- Download same version into a tmp directory.
- Compare the hash.
- If there is a diff, ask feedback from the user.
- If there is no diff, proceed to download the new version.

I assume it would be too hard to let drush simulate the revert and squash without git.
The goal here is only to prevent the user from unknowingly wiping local changes.

Such a change would make it easier to delegate security updates to other developers, without introducing them to a complicated work flow.

**Comment by guaka** [comment]
Could be good to have an update script that does at least some of this.

**Comment by weitzman** [comment]
See https://www.drupal.org/project/hacked

Even better, build your site with Composer, which already has this feature.

**Comment by donquixote** [comment]
Yes I know these options.
But for an existing Drupal 7 site, if I want someone else (other developer, or the client if they are somewhat capable) to do the updates, they are likely to run the most commonly known commands: drush dl or up. I want these commands to be safer to use.

**Comment by weitzman** [comment]
Core Drush is not addressing this use case. FYI there are hooks that run before and after any command.

**Comment by greg-1-anderson** [comment]
I recall contributing a Drush hook to the hacked module, but I can't remember off the top of my head what it did. If it doesn't cover your use case, it might still be a good starting point for adding the checks you want.
