### ISSUE TITLE
Rename pm-enable

### ISSUE THREAD

**Issue by Pasqualle** [drush-ops/drush#2938]
In D8 the modules are installed/uninstalled not enabled. I guess the pm-enable command should be renamed to pm-install.

**Comment by weitzman** [comment]
"enable" is still commonly used and understood. changing name would frustrate folks for little gain.

**Comment by Pasqualle** [comment]
But it is a wrong terminology for Drupal 8.
can we add pm-intall command and make pm-enable as an alias for pm-install.

**Comment by Pasqualle** [comment]
#4588
