### ISSUE TITLE
pm-enable: allow skipping automatic module downloads

### ISSUE THREAD

**Issue by marcvangend** [drush-ops/drush#294]
When I run `drush en -y context_ui views_ui devel diff coder` to enable some of my favorite development modules, drush automatically downloads modules that have not been downloaded yet. The --skip option only skips the automatic downloading of libraries, not modules.

Is there a way (or can it be added as a new feature) to skip the automatic downloading of modules?

**Comment by jonhattan** [comment]
`drush pm-enable foo bar baz --resolve-dependencies=0` is available since some time.

**Comment by v29neil** [comment]
I am also looking  to use only enable module and skip its download , how i am using is i have docker file, i installed drupal, i specifically map /sites/all/modules folder with my local volume , so i dont need to download my custom module which dont even exist on drupal packages, any idea how may i achieve that ?

**Comment by weitzman** [comment]
see the comment above.
