### ISSUE TITLE
Modernize end of core-cli

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2949]
See https://github.com/drush-ops/drush/blob/8298a2c70280c6721f609759f3d9a600a356a3d7/src/Drupal/Commands/core/CliCommands.php#L70-L85

**Comment by greg-1-anderson** [comment]
I guess we will need some sort of Termination manager where different end-of-execution handlers can be added and manipulated.

**Comment by weitzman** [comment]
Done
