### ISSUE TITLE
Drush test-run doesn't check if simpletest is enabled

### ISSUE THREAD

**Issue by Uhkis** [drush-ops/drush#296]
Running drush test-run when simpletest isn't enabled dies to fatal error:
PHP Fatal error:  Call to undefined function simpletest_test_get_all() in ../commands/core/test.drush.inc on line 246

Using master branch.
Older versions of Drush checked if simpletest is enabled and informed the user.

**Comment by mark-posh** [comment]
What if Simpletest is enabled, and you get a similar error?  Running drush test-run I get: Command test-run needs the following module(s) enabled to run: simpletest.

Drush version is 8.0.0

**Comment by weitzman** [comment]
test-run has been removed from Drush core in favor of Drupal's run-tests.sh
