### ISSUE TITLE
Declaration of Drush\Sql\Sqlsqlsrv::creds() should be compatible with Drush\Sql\SqlBase::creds()

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#2967]
```
$ drush sql-connect
Declaration of Drush\Sql\Sqlsqlsrv::creds() should be compatible with Drush\Sql\SqlBase::creds($hide_password = true)           [warning]
Sqlsqlsrv.php:5
$ php --version
PHP 7.2.0beta1 (cli) 
```

**Comment by greg-1-anderson** [comment]
The most important question here is what version of Drush are you using, is it site-local or global Drush, are you running the launcher, etc.

Just tried HEAD of master with a site-local Drush, and it worked fine. From the symptoms, looks like you are mixing versions of Drush.

**Comment by kenorb** [comment]
It's the PHP 7.x warning about function declaration being not compatible.

So basically:

`    public function creds()
`

in [`SqlSqlsrv.php`](https://github.com/drush-ops/drush/blob/master/src/Sql/SqlSqlsrv.php#L16)

should be compatible with:

`    public function creds($hide_password = true)`

defined in [`SqlBase.php`](https://github.com/drush-ops/drush/blob/master/src/Sql/SqlBase.php#L372).

See:

```
$ grep n\ creds\( *
SqlBase.php:    public function creds($hide_password = true)
SqlMysql.php:    public function creds($hide_password = true)
SqlOracle.php:    public function creds()
SqlPgsql.php:    public function creds($hide_password = true)
SqlSqlite.php:    public function creds($hide_password = true)
SqlSqlsrv.php:    public function creds()
```

----

Reproducible steps on empty folder (use PHP 7.1, not 7.2, e.g. `DRUSH_PHP=php71`):

1. `drush -y qd --no-server`
2. Go to Drupal root: `cd quick-drupal-*/drupal`
3. Change db driver to `sqlsrv`, e.g. by: `ex +'%s/sqlite/sqlsrv/g|wq!' sites/default/settings.php`
4. Run `drush sql-connect`.

Same issue with `oracle` driver.

**Comment by greg-1-anderson** [comment]
Oh, I see. I read the error message too quickly and missed that you were using one of the uncommon database types. Those were community-submitted, and are not heavily tested by Drush maintainers. PRs to fix this are welcome.

**Comment by kenorb** [comment]
@greg-1-anderson Please check PR #2969

**Comment by weitzman** [comment]
merged. thanks.
