### ISSUE TITLE
drush_get_runner() is obsolete?

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2968]
[drush_get_runner()](https://github.com/drush-ops/drush/blob/4e2c2cd7b3774b6ec44c6ff6d56f9d06e9b9db57/includes/sitealias.inc#L2341-L2367) existed in order to decide where to run a rsync when both sites are remote. I dont think we support that anymore. If so, let's remove that function.

**Comment by greg-1-anderson** [comment]
drush_get_runner is still used in config-pull and sql-sync. It could be modernized, but I think we still need it.

**Comment by weitzman** [comment]
I moved just the few key lines into those two commands and removed drush_get_runner().
