### ISSUE TITLE
--php parameter fails to select the right PHP binary

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#2971]
Basically when specifying PHP with `--php`, it's ignored, however it works when specifying with `DRUSH_PHP` variable. Tested on macOS.

Example:

```
$ php71 --version
PHP 7.1.7 (cli)
$ which php71
/usr/local/bin/php71
$ which php # This one is default (PHP 7.2).
/usr/local/bin/php
$ drush --php=php71 ev 'echo phpversion();' # Wrong.
7.2.0beta1
$ drush --php=$(which php71) ev 'echo phpversion();' # Wrong.
7.2.0beta1
$ DRUSH_PHP=php71 drush ev 'echo phpversion();' # Right.
7.1.7
$ DRUSH_PHP=non-existing drush status
vendor/drush/drush/drush.launcher: line 132: exec: non-existing: not found
$ drush --php=non-existing status
 PHP executable         :  non-existing                                                                                      
$ drush --php=php71 ev 'phpinfo();' | grep php= # Two --php parameters?
    [1] => --php=/usr/local/bin/php
    [3] => --php=php71
$ drush --version
 Drush Version   :  8.1-dev 
```

**Comment by weitzman** [comment]
what is drush version 8.1-dev? Please use latest release or latest dev which is [8.1.14-dev](https://github.com/drush-ops/drush/blob/8.x/drush.info)

**Comment by agoradesign** [comment]
I'm having similar problems, but only with Drush 9 (9.0.0-beta4). As long as I was running on Drush 8, switching PHP version worked as expected. Now on Drush 9, none of the above methods work (--php param, nor setting DRUSH_PHP).

I'm still having other projects on the same server with a local Drush 8.1.x, that are still working. However, I need Drush 9 for the mentioned project, as it's already on Drupal 8.4, and I've no idea how to break the cycle

**Comment by weitzman** [comment]
Drush9 doesn't support --php or DRUSH_PHP. See 5. at https://github.com/drush-ops/drush/blob/master/docs/install.md

**Comment by agoradesign** [comment]
I should have mentioned that this is not the only difference. Trying --php and DRUSH_PHP was just acting from necessity. I wasn't using this before. Before it worked for me by setting the PATH like described in your docs. So, without --php and/or DRUSH_PHP, running drush eval 'phpinfo()' gives me different results for Drush 8 and Drush 9

**Comment by greg-1-anderson** [comment]
The behavior may vary depending on whether you are using the launcher.

The behavior of Drush vis-a-vis PHP selection does vary between Drush 8 and Drush 9. They should both behave the same if you have your desired version of PHP on your $PATH though.

**Comment by agoradesign** [comment]
thanks for your reply. I had the problem although the $PATH was set correctly, but now I know why:

My global Drush was an old 8.x one (also not the latest 8.x one). I've updated/switch to Drush Launcher, now the correct PHP version gets used :)
