### ISSUE TITLE
Remove drush's internal cache subsystem?

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#2985]
The only core code using our cache subsystem is the 'factory' that gets passed to AnnotatedCommand. Should we handle that differently and remove our custom cache subsystem (including the backends)? Use https://symfony.com/blog/new-in-symfony-3-1-cache-component if needed?

**Comment by greg-1-anderson** [comment]
Yeah, I am in favor of removing our cache subsystem.

Also, we should measure the time difference of simply not providing a cache handler to annotated command. I think that the original delay that motivated the use of a cache here may be reduced or gone.

We might want to be cautious about adopting Symfony 3.1 components, though. At the moment, Drush 9 is still "happens to work" with Drupal 8.3.x.  We might want to wait for Drupal 8.5.x to be released before we hard-un-support Drupal 8.3.x.

**Comment by damiankloip** [comment]
The psysh shell command uses the file cache to store the history files for the shell. Is this targeting everything, including that?

See https://github.com/drush-ops/drush/blob/master/src/Drupal/Commands/core/CliCommands.php#L155 . We only use it to get ourselves a 'cli' cache directory. We then generate a file name, and psysh actually handles the file itself from there.

**Comment by greg-1-anderson** [comment]
It's certainly useful to have a general-purpose cache mechanism available in Drush. Perhaps, rather than modernizing the one we have, we should just live with it as-is until we are comfortable adding a dependency on Symfony 3.1, and port to that at that time.

**Comment by weitzman** [comment]
We can leave drush_directory_cache() but remove the subsystem. That would be fine for psysh. If we ship with the subsystem we're going to have to fix its bugs and maintain it. Better to remove and restore when a need arises. before we do that though, we need to measure the impact per comment 2 above

**Comment by greg-1-anderson** [comment]
I don't think we need to support everything we ship. We may have some residual code in `includes` that we do not want to support. I think that we should "whitelist" the files in `includes` that Drush extensions are allowed to use (e.g. `exec` and `filesystem`, et. al.). Other files, e.g. `context` and `cache` could be labeled "unsupported". Folks who write new-style commands that use unsupported internal functions will break in future patch versions when we remove the functions.

**Comment by greg-1-anderson** [comment]
That said, I think we should remove as much of `cache` and `context` & c. as we can without breaking Drush core with different versions of Drupal.

**Comment by weitzman** [comment]
I experimented with using NullCache() from Annotated instead of our own `CommandCache($cacheBackend)`. The result was measurably slower, so we are benefitting from the command cache. Lets leave this subsystem in Drush9.
