### ISSUE TITLE
Meta - legacy contrib module command files to port

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#2987]
- [x] https://www.drupal.org/project/simple_sitemap
- [ ] https://www.drupal.org/project/security_review

**Comment by Chi-teck** [comment]
In the attached file list of Drupal 8 contributed modules that implement Drush 8 commands.
[drush-legacy.txt](https://github.com/drush-ops/drush/files/1344511/drush-legacy.txt)

**Comment by pcambra** [comment]
I've just made an initial port of the migrate tools one, would appreciate a review if someone us up for it https://www.drupal.org/node/2914005

**Comment by pcambra** [comment]
@Chi-teck note that the list you've attached includes modules that have no Drupal 8 release, it's unlikely that someone would use Drush 9 in Drupal 7, right?

**Comment by Chi-teck** [comment]
@pcambra could you please point out some D7 only modules from that list?

**Comment by pcambra** [comment]
Ah my bad, I opened this one randomly https://www.drupal.org/project/viewerjs and didn't spot the dev version at the bottom, sorry about that :)

**Comment by Chi-teck** [comment]
@pcambra I used [Drupal project loader](https://github.com/Chi-teck/drupal-project-loader) to get codebase of Drupal 8 contributed modules.

**Comment by Chi-teck** [comment]
In case you are interested on how this is progressing.
<details>
  <summary>Modules that have implemented annotated commands</summary>

1. https://www.drupal.org/project/advancedqueue
2. https://www.drupal.org/project/baguettebox
3. https://www.drupal.org/project/config_devel
4. https://www.drupal.org/project/config_split
5. https://www.drupal.org/project/config_sync
6. https://www.drupal.org/project/default_content
7. https://www.drupal.org/project/devel
8. https://www.drupal.org/project/drd_agent
9. https://www.drupal.org/project/drd
10. https://www.drupal.org/project/encrypt
11. https://www.drupal.org/project/entity_share
12. https://www.drupal.org/project/entity_staging
13. https://www.drupal.org/project/library_manager
14. https://www.drupal.org/project/ludwig
15. https://www.drupal.org/project/media_entity
16. https://www.drupal.org/project/migrate_manifest
17. https://www.drupal.org/project/migrate_tools
18. https://www.drupal.org/project/ossfs
19. https://www.drupal.org/project/redis_watchdog
20. https://www.drupal.org/project/release_tracker
21. https://www.drupal.org/project/simple_sitemap
22. https://www.drupal.org/project/snippet_manager
23. https://www.drupal.org/project/views_slideshow
</details>

**Comment by weitzman** [comment]
Thanks for sharing that list. Great work by the community.

Nice use of details/summary tags. I did not know that was possible on GH.
