### ISSUE TITLE
Protect all PHP scripts from being executed through web 

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#2999]
At this moment any user can create SUT instance in _/tmp_ directory on target host by accessing  _/vendor/drush/drush/unish.sut.php_ URL.

While this may not have security implications I propose explicitly disallow such requests to avoid possible security issues in future.

Relevant issue for Drupal console project:
https://github.com/hechoendrupal/drupal-console/issues/3238

**Comment by weitzman** [comment]
I'm not opposed to protecting that script, but there is an incredible
amount of vendor code in a drupal-project installation. I think this is
just the tip of the iceberg. Does it make sense for Composer or
drupal-project to write an .htacess in /vendor?

**Comment by Chi-teck** [comment]
> Does it make sense for Composer or drupal-project to write an .htacess in /vendor?

That's already done in core.
https://www.drupal.org/node/2508591

Unfortunately .htaccess does not make sense for Nginx.

**Comment by Chi-teck** [comment]
Additionally we could configure _.gitattributes_ file to exclude such files from release.

**Comment by greg-1-anderson** [comment]
Correctly-configured web servers will prohibit access to all scripts in the vendor directory. I am in favor of optimizing .gitignore &/or `require-dev` to keep debug components out of production, but I don't think we can / should protect the vendor directory, as that's not our job.
