### ISSUE TITLE
Drush does not complete export when there is an error in exporting a config item.

### ISSUE THREAD

**Issue by jonnyeom** [drush-ops/drush#3011]
I run into the following error sometimes while running the `drush config-export` command.
```
TypeError: Argument 2 passed to Drupal\Core\Config\FileStorage::write() must be of the type array,[error]
boolean given
```

In such a case, drush completely errors out and does not complete the config export.

**Comment by weitzman** [comment]
What version of Drush and Drupal?

**Comment by jonnyeom** [comment]
I am using drush 8.1.14 and on Drupal 8.3.7.

The error itself must originate from whatever config item drush is trying to write. However, I think adding a separate check would be usefull.

**Comment by askibinski** [comment]
FWIW: We had this error recently and its source was an empty row entry in the config table. No idea how that originated. There might be other causes of course.
