### ISSUE TITLE
@sites alias missing in drush 9?

### ISSUE THREAD

**Issue by misterkay** [drush-ops/drush#3019]
I just upgraded a site to Drupal 8.4 with the latest Drush 9 beta release. It is a multisite configuration using symlinked subdirectories.

Running `drush @sites updb` results in `[error] Site alias not found.`

This alias was enabled by default in previous versions, is this no longer the case? Does it need additional configuration?

**Comment by greg-1-anderson** [comment]
Drush 9 no longer supports executing a single command on multiple sites with alias lists (@a,@b,@c) or @sites. Neither of those syntaxes are available in any context. You may still use `drush sa @group` to see all aliases in a group; that is the only context in which Drush recognizes alias lists.

**Comment by misterkay** [comment]
So executing a single command on multiple sites now requires separate commands per site?

**Comment by weitzman** [comment]
Correct. Just write a bash or drush script and loop over the sites. You can use `parallel` to run several at once.

**Comment by misterkay** [comment]
Thanks for the clarification @weitzman @greg-1-anderson

**Comment by leymannx** [comment]
@weitzman I can't find anything about `parallel`. Do you have an example for us?

**Comment by weitzman** [comment]
Mentioned at
https://www.codeword.xyz/2015/09/02/three-ways-to-script-processes-in-parallel/

**Comment by leymannx** [comment]
Some other alternatives can be found on DSE https://drupal.stackexchange.com/q/250688/15055

**Comment by sgurlt** [comment]
Ok, but why ? We are using this several times per day in several projects ?

**Comment by yonailo** [comment]
I don't know if it was "niche", but definetely it was very useful, it is a pity that it was removed.
