### ISSUE TITLE
Split updatedb command so that entity-updates can run between update and post update hooks

### ISSUE THREAD

**Issue by jibran** [drush-ops/drush#3021]
During Drupalcon Vienna sprint while discussing https://www.drupal.org/node/2762235#comment-12280421 between @alexpott, @fago, @bircher, @jibran and @mbm80 this topic came up.

The flow of running the update should be:

- Run update_N hooks
- Run entity-update hooks (optional, only if there is not a update_N hook for this)
- Run config import (optional, if need be)
- Run post_update_NAME hooks

Right now, the `updatedb` command flow is:

- Run update_N hooks
- Run post_update_NAME hooks
- Run entity-update hooks (optional)

which is incorrect.

We can do two things here:
1. Either, split the command into two `updatedb` and `post-updatedb` to run update hooks and post update hooks respectively, `updatedb` can also run `entity-update` hooks (optional),
2. Or we can add a param to `updatedb` `--update-hook-only` and `--post-update-hook-only`.

**Comment by greg-1-anderson** [comment]
Seems to me like the default behavior of `updatedb` with no option should be to do all of the recommended options.

Maybe `updatedb` should run subcommands `updatedb:update-hooks`, `updatedb:entity-update`, (`cim`) and `updatedb:post-update`.

**Comment by fago** [comment]
@greg-1-anderson I'd agree with that. Without better knowledge I'd assume that the updatedb command matches update.php by default, and update.php runs all of that!

**Comment by weitzman** [comment]
I dont think update.php runs `cim`. Looks to me like it does the same steps as updatedb, in the same order.

It looks to me like the easiest way to match what @jibran proposes is to pull `Run post_update_NAME hooks` into its own command. That way the commands can be run as follows:

```
drush updatedb
drush entity:updates
drush config:import
drush update:post
```

I know folks want a 'just run one command and it does all the things'. Thats great until something goes wrong and you are combing through a messy debug log. I have scars.

**Comment by jibran** [comment]
`cim` is completely optional. I added it to show the purposed flow but I agree with @weitzman, let's add `drush update:post` and only run 'update_N hooks' in `drush updatedb`

**Comment by weitzman** [comment]
Took a shot at this. Please help test at https://github.com/drush-ops/drush/pull/3090. updatedb has no automated tests so i'd love to get a couple human testers.

**Comment by weitzman** [comment]
I am refactoring updatedb and it's status command. And adding tests.

**Comment by Berdir** [comment]
Very confused to see @fago arguing to do entity updates by default, update.php does *not* do that, hasn't been doing it in a very long time as explained in #3167 and the change record linked from there (https://www.drupal.org/node/2554097).

Running all entity updates is mostly a tool for developers, it is are *not* reliable, not on real sites when you likely have data in whatever fields are being changed.
