### ISSUE TITLE
Drush stable (8.1.14) conflicts with Drupal stable (8.4).

### ISSUE THREAD

**Issue by JorisVanEijden** [drush-ops/drush#3023]
Drupal 8.4 requires Symfony "~3.2.8"
Drush 8.1.14 requires Symfony "~2.7"

Composer cannot install both.

Edit: after seeing [#2800] I guess this is by design.

**Comment by greg-1-anderson** [comment]
Yes, this is by design. (Not our design, but by design all the same!) Your options are:

- Use a site-local Drush 9.0.0-beta6 or later
- Remove Drush from your Drupal 8.4 project and use a global Drush 8.1.14, which works

**Comment by xjm** [comment]
Probably we should update the core release notes with this clarification; is the following text true?

[Versions of Drush earlier than 8.1.12 will not work with Drupal
8.4.x](https://www.drupal.org/node/2874827). Update Drush to 8.1.12 or higher
**before using it to update to Drupal core 8.4.x** or you will encounter fatal
errors that prevent updates from running.
* If Drush is installed globally (i.e., generally available on the web host), Drush 8.1.12 and 8.1.13 will
successfully update Drupal 8.3.x to 8.4.0, but users may still see
[other error messages after updates have
run](https://github.com/drush-ops/drush/issues/2933).
* If the site is built with Composer and [includes Drush as a composer dependency (less common), Drush 8.1.x will not be compatible](https://github.com/drush-ops/drush/issues/3023). These sites should either require Drush 9.0.0-beta6 or later, or use a global installation of Drush 1.14 until Drush 9 has a stable release.

Thanks @greg-1-anderson and @JorisVanEijden.

**Comment by greg-1-anderson** [comment]
@xjm Yes, that is correct today.

Minor corrections:

- Typo: `Drush 1.14` should be `Drush 8.1.14`
- "Drush 8.1.12 and 8.1.13 will successfully update Drupal" could be inclusive of Drush 8.1.14 (already released and working as a global install), or simply repeat "8.1.12 or higher", as there will be a 8.1.15 and follow-on releases which should also work both globally and as site-local installs.

. We are planning an 8.1.15 release to rectify this problem. Folks can try Drush 8.x-dev right now; additional community testing would be appreciated (although I don't think the release notes should recommend a dev version).

Maybe 8.1.15 will be ready on Monday, or a couple of days after.
