### ISSUE TITLE
bash completion for drush 9

### ISSUE THREAD

**Issue by rodrigoaguilera** [drush-ops/drush#3024]
I have noticed that drush.complete.sh is gone but I didn't find the way to have completion again

The docs say is with the bashrc file 
https://github.com/drush-ops/drush/blob/master/docs/examples.md

I even tried drush init but that is not adding anything about completion

Can you explain more about why that file was deprecated?

**Comment by weitzman** [comment]
Its gone. #2514 is where folks will work on its replacement.
