### ISSUE TITLE
Drush9: Cannot use commands with arguments while using aliases

### ISSUE THREAD

**Issue by yobottehg** [drush-ops/drush#3025]
When you want to uninstall a module using `pmu` it worked like this in Drush8:

`$ drush @project.local pmu module`

if i do this in Drush9 i get the following output:

```
 [Symfony\Component\Console\Exception\RuntimeException]  
  Too many arguments, expected arguments "command".  
```

If i run it without the Alias inside the Vagrant it works.
Other commands that do not take attributes work with the Alias like `$ drush @project.local cr`

Did the notation of using Drush Aliases change ?

**Comment by greg-1-anderson** [comment]
Sounds like a bug. I take it that `@project.local` refers to a Vagrant-hosted Drupal site that is called via ssh?  Does `drush @project.local status` work?

Run pmu with `--debug` and look for the ssh command that Drush is running. Report that here. Also show your Drush 8 and Drush 9 alias files for this site.

**Comment by greg-1-anderson** [comment]
Also, what version of Drush are you using? Try 9.0.0-beta6 if you're not already using that.

**Comment by yobottehg** [comment]
You were right i was using beta5. Updated to Beta6.

```
$ drush --version
Drush Launcher Version: 0.4.2
Drush Commandline Tool 9.0.0-beta6
```

```
$ drush @project.local pmu automated_cron
      
[Symfony\Component\Console\Exception\RuntimeException]  
Too many arguments, expected arguments "command".    
```

does still not work, while :

```
$ drush @project.local pmu
[success] Successfully uninstalled: 
Connection to www.project.dev closed.
```

So i think it's basically about the second parameter

**Comment by greg-1-anderson** [comment]
Could you provide `--debug` output?

**Comment by yobottehg** [comment]
sure:

```
$ drush @project.local pmu automated_cron --debug
Drush Launcher Version: 0.4.2
ROOT: /Users/rainer/Dev/localdev/devdesktop/project
DRUSH VERSION: 9
DRUPAL ROOT: /Users/rainer/Dev/localdev/devdesktop/project/docroot
COMPOSER ROOT: /Users/rainer/Dev/localdev/devdesktop/project
VENDOR ROOT: /Users/rainer/Dev/localdev/devdesktop/project/vendor

                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  Too many arguments, expected arguments "command".       
                                                          

Exception trace:
 () at /Users/rainer/Dev/localdev/devdesktop/project/vendor/symfony/console/Input/ArgvInput.php:184
 Symfony\Component\Console\Input\ArgvInput->parseArgument() at /Users/rainer/Dev/localdev/devdesktop/project/vendor/symfony/console/Input/ArgvInput.php:88
 Symfony\Component\Console\Input\ArgvInput->parse() at /Users/rainer/Dev/localdev/devdesktop/project/vendor/symfony/console/Input/Input.php:63
 Symfony\Component\Console\Input\Input->bind() at /Users/rainer/Dev/localdev/devdesktop/project/vendor/symfony/console/Command/Command.php:222
[...]

pmu [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--] <command>

```

**Comment by greg-1-anderson** [comment]
Ah, I think I know what is going on. Try setting your cwd to a local Drupal site that has an installed database (`drush status` says "Database: Connected") and run the command again.

I should be able to fix this.

**Comment by yobottehg** [comment]
If i ssh into the container and use drush without the alias everything works:

```
$ drush pmu automated_cron
 [success] Successfully uninstalled: automated_cron
```

While from the outside with using the alias there is the error above.
Just for clarifying that this only exists using aliases.

**Comment by yobottehg** [comment]
Just another find, it's not about the `pmu` command but generally every command using arguments like `cim sync`.

Clarified this in the title

**Comment by greg-1-anderson** [comment]
Yes, I'm halfway there. If you use the HEAD of the master branch, you will find that Drush no longer complains about too many arguments in this situation. However, `--foo=bar` will still throw an error, even if `--foo` is a valid option for the command you are running.

I've got a strategy for this, and will have it fixed shortly.

**Comment by greg-1-anderson** [comment]
HEAD of master should now behave correctly for both args and options.

**Comment by weitzman** [comment]
-l is not deprecated. Maybe try `--uri=http://foo`. Its recommended to use the full uri with http.

**Comment by leymannx** [comment]
Thanks @weitzman, it's working. Though it's annoying to always have to type the whole URI.

If `-l` is not deprecated I'd consider this a bug 🐛

**Comment by weitzman** [comment]
Did you try `-l http://foo`?

**Comment by weitzman** [comment]
you dont have to always type that longer uri. You can navigate into the multisite or you can use a site alias with or without the site:set command.

**Comment by leymannx** [comment]
```
$ drush -l http://foo.localhost en admin_toolbar_tools
Too many arguments, expected arguments "command".
```

I see, there are multiple workarounds. I think I'll switch to site aliases anyways.

But one last question: I this a bug and will this issue get reopened now?

**Comment by weitzman** [comment]
I can't reproduce that error. I think there would be many bug reports if -l stopped working. Can you share output of `drush status`?

**Comment by greg-1-anderson** [comment]
Make sure that you're using an up-to-date version of Drush. Also, make sure that there's nothing holding back your version of Symfony or any consolidation component (e.g. avoid `composer global require`, avoid `composer require` of cli tools in your Drupal site if the cli tool does not need to be part of the project).

**Comment by leymannx** [comment]
`-l` didn't stop working. It's just you can't use aliases of commands with it as demonstrated above. I also use a local Drush together with Drush Launcher as stated above.

```
$ drush -l foo status
Drupal version   : 8.5.6
 Site URI         : foo
 DB driver        : mysql
 DB hostname      : localhost
 DB port          : 3306
 DB username      : foot
 DB name          : foo_db
 Database         : Connected
 Drupal bootstrap : Successful
 Default theme    : foo_theme
 Admin theme      : seven
 PHP binary       : /usr/bin/php
 PHP config       : /etc/php.ini
 PHP OS           : Darwin
 Drush script     : /usr/local/bin/drush
 Drush version    : 9.3.0
 Drush temp       : /tmp
 Drush configs    : /Users/leymannx/Sites/mymultisite/vendor/drush/dr
                    ush/drush.yml
                    /Users/leymannx/Sites/mymultisite/drush/drush.yml
 Install profile  : minimal
 Drupal root      : /Users/leymannx/Sites/mymultisite/web
 Site path        : sites/foo
 Files, Public    : sites/foo/files
 Files, Private   : sites/foo/files/private
 Files, Temp      : /Users/leymannx/Sites/temp/foo
```

**Comment by leymannx** [comment]
Only "specialty" on my setup might be: The `default` site isn't set up. Only multiple multi-site instances. And it actually is working all fine, as long as I explicitly don't use aliases of commands as demonstrated above.

**Comment by greg-1-anderson** [comment]
What about `$ drush en -l http://foo.localhost admin_toolbar_tools`?

**Comment by leymannx** [comment]
Please see https://github.com/drush-ops/drush/issues/3025#issuecomment-409932185

**Comment by greg-1-anderson** [comment]
@leymannx Note that I changed the order of where the `en` is positioned. I think this is a limitation of the parse order for certain shortcuts (e.g. `en`), which is a workaround for a Symfony Console bug.

**Comment by leymannx** [comment]
@greg-1-anderson indeed the order of commands makes a difference! Thanks a lot. Still unsure, if I should consider this a workaround or if I just did it wrong for a year or so and that's the only way how it's supposed to be used.

```
$ drush en -l foo admin_toolbar_tools
[notice] Already enabled: admin_toolbar_tools
```

**Comment by greg-1-anderson** [comment]
The issue here is that the Symfony Console commandline parser gets confused with some short commad aliases such as `en`, and thinks it is the short form for some other command (I forget which). A couple of other shortcuts such as `si` also have this problem.

To work around this problem, early in the preflight stage, Drush will replace the first argument for its full command equivalent if it is one of these aliases that has a problem in the normal parse phase. However, this happens so early that at this point Drush doesn't know whether `-l` takes a parameter or not. It therefore doesn't get far enough to see the `en`, because it looks at `http://foo.localhost` and decides that's not something it wants to replace, and this particular method only ever replaces args in the first position.

The workaround is to put the short options with arguments after the command alias, or use the long option form (`--uri=http://foo.localhost`). (Or don't use the command alias.)
