### ISSUE TITLE
Drush no longer loads drush/drushrc.php automatically

### ISSUE THREAD

**Issue by grasmash** [drush-ops/drush#3027]
Previously, executing `drush` in a given directory would automatically load configuration from the relatively located `drush/drushrc.php`. This no longer happens.

I'm not sure whether this is a bug in drush, or if perhaps this file needs to be moved to a different location to be automatically discovered.

**Comment by greg-1-anderson** [comment]
Are you using Drush 9?  The configuration files are now called `drush.yml`.

I'm not sure OTTOMH whether `$(pwd)/drush` is a search location. `__DRUPAL_ROOT__/drush` is, though.

**Comment by weitzman** [comment]
I'm not really feeling the love for this feature. Please use a drush.yml in a global location if you want it back. Pretty sure those can specify additional config dirs to check.

**Comment by greg-1-anderson** [comment]
In theory, you could add this to your `~/.drush/drush.yml` (untested):
```
drush:
  paths:
    config: '${env.cwd}'
```
