### ISSUE TITLE
The @self alias no longer works reliably

### ISSUE THREAD

**Issue by grasmash** [drush-ops/drush#3028]
As of 9.0.0-beta5,  `drush @self si` will fail but `drush si` will succeed.

It's unclear to me whether this is intended behavior or a bug, but I did not find it documented.

**Comment by greg-1-anderson** [comment]
`drush @self [command]` is always redundant. Why would you ever use `@self` in this location? It is only intended for commands where you need an alias as a parameter, e.g. rsync and sql-sync.

That said, it does appear that there are some problems with the generation of the `@self` alias at the moment; `drush sa @self` does not show a `root` element, for example. This should be fixed.

**Comment by grasmash** [comment]
> Why would you ever use @self in this location? 

This syntax is used in BLT, which makes the assumption that you're always using an alias. 

It's easier to write consistent scripts when there is always a value for the alias, rather than handling the contingency that there is sometimes an alias and sometimes not. In this case we make the default alias `@self`.

**Comment by greg-1-anderson** [comment]
OK, that makes sense.
