### ISSUE TITLE
owner/group/perms changed on pm-update -- really

### ISSUE THREAD

**Issue by paulraines68** [drush-ops/drush#303]
I ran 'drush --verbose @dev pm-update'.  Before running the owner/group/perms on
ROOT/files was

drwxrwxr-x 15 root apache 4096 Sep 25 16:59 files/

and, for example, on ROOT/files/feeds was

drwxrwx---  2 apache sysadm   4096 Dec  3 12:11 feeds

After running pm-update, after the module update owner/group/perms were fine, but after updating the drupal core step, they had changed

drwxr-xr-x 15 root root 4096 Dec  3 14:22 files/
drwxr-xr-x  2 root root   4096 Dec  3 14:22 feeds

I see nothing in the output though that explains this.  The drupal-$ver.tgz file downloaded has no 'files' directory that would overwrite the existing one.  I can only guess the '/usr/bin/php .... updatedb' command is doing it somehow.

Although I don't know what this line does:

Executing: bzr root /var/www/webdev/drupal-7.24

What is bzr?

**Comment by greg-1-anderson** [comment]
Please use [Drupal Answers](http://drupal.stackexchange.com/questions/tagged/drush) for support requests.
