### ISSUE TITLE
drush 9.0.0-beta5+ hangs (Windows)

### ISSUE THREAD

**Issue by ergophobe** [drush-ops/drush#3038]
Running 9.0.0.-beta3 on Wampserver, I ran into this issue:
Failed to open stream: No such file or directory JSONCache.php:25 #2912

Last patch works great: https://github.com/drush-ops/drush/commit/494f11a9fe20504feffcd4ddcb8393c9e022e8a9

I then updated to beta6 so I wouldn't have to patch. Drush ran fine outside of the /web directory (i.e. running without an actual Drupal install)

When I cd in to the /web directory, though, it hangs. If I run 
`drush -d -v`  or `drush -v -d status`
I get no output. It just sits there infinitely.

I changed my composer file to require 9.0.0-beta4 and updated (i.e. reverted to beta4) and it runs fine again.

Something in beta5 and beta6 is causing everything to hang and it hangs before it drush debug even has a chance to output  `[bootstrap] drush_preflight_prepare()`

So unfortunately, I have no useful debug info.

**Comment by greg-1-anderson** [comment]
beta5 was nearly a complete rewrite from beta4. More diagnosis will be necessary.

**Comment by ergophobe** [comment]
Thanks Greg. I certainly didn't expect a fix from that report, but wanted to just be sure that it could be tied to beta5 at some point down the road.

Unfortunately, I don't have XDebug setup for command line. I'll try to do that and see if I can get more insight into where it's failing.

**Comment by greg-1-anderson** [comment]
The problem with diagnosing this right now is that the Drush logger does not get set up until after the DI container is built, and that does not happen until after the Drupal autoloader is loaded. That means that preflight is not logging progress at all. At some point we might add a lightwieght logger for the preflight code. Sorry for the inconvenience.

**Comment by ergophobe** [comment]
I think this is actually a problem on my system with the bash shell actually. MySQL hangs in the same way and I think Drush is just hanging because MySQL is hanging.

So I think the difference is that one version of drush is tripping this behavior and the other isn't, but in earlier versions of drush I'm now getting insufficient bootstrap level notices.

It looks like what's happening is the MySQL connection is hanging and in earlier versions of drush, this errored out with a notice and beta5 is just getting hung up along with MySQL while waiting.

I'm going to close this because I think it's a strange confluence of conditions resulting from lots of adding and removing different versions of drush and dependencies and many other things. I doubt it could ever get reproduced.

Sorry for the issue queue noise.
