### ISSUE TITLE
Notice: A non well formed numeric value encountered in drush/drush/includes/drush.inc on line 894

### ISSUE THREAD

**Issue by zero2one** [drush-ops/drush#3039]
## Problem
The `drush_memory_limit()` code retrieves the memory limit and transforms it from human form into byte form.

The calculation uses the value as retrieves trough the `ini_get('memory_limit')` function. This value contains the human form (containing the byte size in K, M, G). The calculation triggers a notice in PHP 7.x

```php
function drush_memory_limit() {
  $value = trim(ini_get('memory_limit'));
  //  Example value : 512M.
  $last = strtolower($value[strlen($value)-1]);
  switch ($last) {
    case 'g':
      $value *= DRUSH_KILOBYTE;
    case 'm':
      // This will cause the notice as is tries to do math with 
      // a numeric value and a string. 
      $value *= DRUSH_KILOBYTE;
    case 'k':
      $value *= DRUSH_KILOBYTE;
  }

  return $value;
}
```

## Solution
Remove the order size from the value and use that value to calculate the memory limit.

```php
function drush_memory_limit() {
  $value = trim(ini_get('memory_limit'));
  $last = strtolower($value[strlen($value)-1]);
  $size = (int) substr($value, 0, -1);
  switch ($last) {
    case 'g':
      $size *= DRUSH_KILOBYTE;
    case 'm':
      $size *= DRUSH_KILOBYTE;
    case 'k':
      $size *= DRUSH_KILOBYTE;
  }

  return $size;
}
```

**Comment by killes** [comment]
Could this be backported to Drush 8?

**Comment by weitzman** [comment]
Backported.

**Comment by killes** [comment]
Thanks :)

**Comment by MacGuinness** [comment]
Perhaps I'm missing something subtle, but shouldn't the relevant switch options for 'g' & 'm' above be:

   case 'g':
      $size *= DRUSH_KILOBYTE * DRUSH_KILOBYTE * DRUSH_KILOBYTE;
    case 'm':
      $size *= DRUSH_KILOBYTE * DRUSH_KILOBYTE;

**Comment by angry-dan** [comment]
@MacGuinness you're right - it is subtle - there's no `break` statement so it (intentionally) falls through to the next case.
