### ISSUE TITLE
Support site-local drush without composer

### ISSUE THREAD

**Issue by AdamPS** [drush-ops/drush#3043]
As per this [Drupal issue](https://www.drupal.org/node/2909032) but perhaps it more logically belongs here.

The composer method is [not yet ready for everybody](https://www.drupal.org/node/2845379), so please can we keep drush working for those using the tarball install?

All the required code is already present (I tested it).  All that is needed is to provide a way for tarball users to set up their Drupal image correctly.

This could be in the form of an extra tarball that contains drush plus all dependencies not already in Drupal core.  Might it be possible to build such a tarball from github please?

**Comment by weitzman** [comment]
The point of a site local drush is 

1. dependencies are resolved on every update so your codebase is known to be compatible with all its dependencies
1. drush's classes are in the same autoloader as the site

This proposal accomplishes neither goal. Wont fix.

**Comment by greg-1-anderson** [comment]
I'm not sure what the ask is here. You want to put the drush.phar in `__ROOT__/drush`? Why is this better than putting the global Drush 8 on your $PATH?

**Comment by AdamPS** [comment]
Apologies, I'm not explaining it very well.  As I understand it, the drush 8 phar uses symfony 2 and this is a headache for Drupal 8.4+

I propose to build a drush 8 tar that is specifically targetted to match the dependencies of the relevant Drupal version.

Or maybe even simpler to build a tar with the latest version of both drush and Drupal.

**Comment by greg-1-anderson** [comment]
@AdamPS We already considered and rejected the idea of having multiple phars with different dependencies. Note that the current global Drush 8 phar with Symfony 2 happens to work with Drupal 8.4.0 (because Symfony 2 and Symfony 3 are fairly similar).

The issue for further improvements on this subject that you should follow is https://github.com/drush-ops/drush/pull/2787.

**Comment by AdamPS** [comment]
OK, thanks
