### ISSUE TITLE
Drush fails because "TRUE" gets passed into the `Drush\Config\Environment::setLoader()` call.

### ISSUE THREAD

**Issue by erikfrerejean** [drush-ops/drush#3049]
I've just installed a composer based project that includes drush, however all drush commands fail with the exception:

```shell
$ drush --help
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Drush\Config\Environment::setLoader() must be an instance of Composer\Autoload\ClassLoader, boolean given, called in /var/www/site/vendor/drush/drush/drush.php on line 57 and defined in /var/www/site/vendor/drush/drush/src/Config/Environment.php:219
Stack trace:
#0 /var/www/site/vendor/drush/drush/drush.php(57): Drush\Config\Environment->setLoader(true)
#1 /var/www/site/vendor/drush/drush/includes/preflight.inc(17): require('/var/www/site...')
#2 phar:///usr/local/bin/drush/bin/drush.php(139): drush_main()
#3 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#4 {main}
  thrown in /var/www/site/vendor/drush/drush/src/Config/Environment.php on line 219
```

To check I've dumped both `$autoloadFile` and `$loader` to see their values and ran `drush status` from the site directory.
```shell
$ drush status
string(58) "/var/www/site/vendor/drush/drush/../../autoload.php"
bool(true)
```
The path to `autoload.php` is correct and the file itself is readable, `$loader` however is the `TRUE` which normally is returned by `include_once`.

This happens on a CentOS 7 server running PHP 7.0.20, and using `Drush 9.0.0-beta7`.

**Comment by weitzman** [comment]
I see phar:// in the backtrace. Is that drush8 or the drupal-launcher? what
version? and what version of drupal is in the site?

**Comment by erikfrerejean** [comment]
[`composer show`](https://gist.github.com/erikfrerejean/07b652c5c6e08d10212c3e1b73d6e753), `drush status` doesn't work since it throws the same exception before outputting anything.

> I see phar:// in the backtrace. Is that drush8 or the drupal-launcher? what
version?
That is the drush launcher

**Comment by weitzman** [comment]
Sounds like your composer install is broken. I guess you should Delete
vendor dir and run composer install.

**Comment by greg-1-anderson** [comment]
The autoloader returns the class loader the first time it is called, and returns `true` if it is called a second time. Drush 9 needs a reference to the class loader, so you shouldn't call the autoloader prior to launching Drush.

Older versions of the launcher loaded the autoloader and then included `drush_main()`. The newest launcher still does this for Drush 8, but skips loading the autoloader for Drush 9. You probably need to upgrade your launcher.

**Comment by erikfrerejean** [comment]
Sorry for the delay, didn't have time to update the server. @greg-1-anderson, updating the launcher indeed fixed the issue.

**Comment by fede-green** [comment]
mhm sorry @erikfrerejean . looks i'm having the same problem here... how do you update the launcher?

thanks :)
