### ISSUE TITLE
Allow Drush commands to be loaded from vendor directory

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#3050]
I think there is nothing special in packages that provide Drush commands and vendor directory is standard place for third party PHP code.

**Comment by greg-1-anderson** [comment]
Searching all of vendor for Drush commandfiles is too slow. There are other proposals for how this might work, though. See https://github.com/consolidation/Robo/pull/604. Help to push this forward appreciated.

**Comment by weitzman** [comment]
Until then, tag your composer package with drupal-drush and then it will be placed into /drush if you used drupal-project's 'extra' config (see its composer.json). 

Or an alternative is to add your vendor/org/mypackage as a command search location (options.include) in a drush.yml. Caveat - I have not tried this.

**Comment by Chi-teck** [comment]
We could only allow drush.services.yml file to be in top level directory of a package. Like _composer.json_.

The following command works almost instantly for me.
```
drush ev 'print_r(glob("./vendor/*/*/composer.json"));'
```

**Comment by greg-1-anderson** [comment]
Note that using type drupal-drush does not work at the moment. See #2918.

I wouldn't mind use @Chi-teck's `glob` trick to find and register extra drush.services.yml files. If we did this, would we support both projects of type `drupal-drush` in `__DRUPAL_ROOT__/drush` and vendor-based commands of any other type, or would we want to bread `drupal-drush` for Drush 9?

**Comment by Chi-teck** [comment]
The one may still need _./drush_ directory for custom commands that do not belong to a module.

**Comment by Chi-teck** [comment]
> The one may still need ./drush directory for custom commands that do not belong to a module.
Well there is a "search location" option as stated above.

**Comment by greg-1-anderson** [comment]
Commands that belong with a module are already handled by adding a `drush.services.yml` to the respective module.

The `./drush` directory is a useful place for folks to check in policy files (hooks that limit or change the behavior of Drush commands) that do not belong to any module or Composer project. The question is, should we support both Composer projects that install to `vendor`, and `drupal-drush` projects that install to `./drush/contrib`, or should we just pick one to support?

My thought:

- Support commandfile searching for `./drush/src/Commands` for site-specific policy files.   No `drush.services.yml` support for this location.
- Support commandfiles identified via a `drush.services.yml` file iff their type is `drupal-drush` (relocated to `./drush/contrib/PROJECTNAME`). Services file requires; auto-discovery not done.
- Do not support commandfiles in the vendor directory (type is something other than `drush.services.yml`).
- The "search location" can be provided to auto-discover commandfiles that do not have service files.

We can, of course, be more flexible than this. There would be nothing wrong with supporting service files for site-specific policy files, or for doing discovery on `drupal-drush` extensions that do not have a services file, or doing discovery of service files in the `vendor` directory. The documentation will be clearer and easier to understand if we put some limits on our recommendations, though.

One thing that we should not do, though, is load service files at locations specified by a user-provided (commandline or config file) search path (the `--include` directive). Service class names are cached; if you run once with --include and bring in some service files, and then run again without the include (or without the config file), then Drupal will not be able to find the cached service classnames, and you will experience crashes until you `drush cr`.

Drush triggers these crashes in its bootstrap, though (the missing classes are not a problem when running Drupal from the web server), so we could potentially filter our service cache list in DrupalBoot8 if we wanted to be more flexible about disappearing commandfiles.

**Comment by Chi-teck** [comment]
> The question is, should we support both Composer projects that install to vendor, and drupal-drush projects that install to ./drush/contrib, or should we just pick one to support?

I would prefer `vendor` over `./drush/contrib` . It is more natural and usually not accessible through web.
Also it can work without configuring _composer/installers_. We could support _./drush/contrib_ if it is not a big deal.

**Comment by greg-1-anderson** [comment]
`../drush/contrib` is also supported to avoid having to exclude `./drush` in your web server configuration.

I'm not opposed to switching to `vendor` if that's what folks want to do. We could break or keep `./drush/contrib` support as desired; it's not a big deal.

**Comment by weitzman** [comment]
These drush.services.yml files inside /vendor would not support lines like `arguments: ['@config.manager', '@config.storage', '@config.storage.sync']`, right? That is, they could not inject dependencies from Drupal. In this sense, they are inferior to our existing drush.services.yml files. DI of Drupal services is limited to modules, and DI of Drush services requires implementing ConfigAwareInterface, SiteAliasAwareInterface, and the like.

**Comment by greg-1-anderson** [comment]
drush.services.yml files inside vendor could still support dependency injection.

**Comment by greg-1-anderson** [comment]
It is currently possible to implement drush_language as its own module, and still do dependency injection from the core language module. This is the current model -- only modules get drush.services.yml. Drush extensions that are not part of a module can be policy files (hooks) or standalone commands, but cannot do dependency injection.

Unless we change that.

**Comment by weitzman** [comment]
At this moment, we are leaning toward not changing that model.
