### ISSUE TITLE
Drush 8 PHP Fatal error

### ISSUE THREAD

**Issue by banacan** [drush-ops/drush#3051]
I'm getting the following error when I try to run Drush commands:

`PHP Fatal error:  Declaration of Drush\Command\DrushInputAdapter::hasParameterOption() must be compatible with Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false) in /Users/brett/.composer/vendor/drush/drush/lib/Drush/Command/DrushInputAdapter.php on line 27
Drush command terminated abnormally due to an unrecoverable error.                                   [error]
Error: Declaration of Drush\Command\DrushInputAdapter::hasParameterOption() must be compatible with
Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false) in
/Users/brett/.composer/vendor/drush/drush/lib/Drush/Command/DrushInputAdapter.php, line 27`

Drush 8.1.8
Composer 1.5.2
Drupal site 8.4.0

**Comment by greg-1-anderson** [comment]
Your drush is very very old. That bug was fixed a long long time ago. Latest Drush 8 is Drush 8.1.15.
