### ISSUE TITLE
File sites.php is always created during install

### ISSUE THREAD

**Issue by brummbar** [drush-ops/drush#3056]
After moving to Drush 9, I noticed that the file `sites/sites.php` was always being created after an install with `site-install`, even if the site subdir is the default one `sites/default`.
With Drush 8 this doesn't happen.
I took a look at the code of said command and there is a check done between paths, where one of the paths is a relative one while the other is absolute. This leads to the condition being always true, and thus to the creation of the file.

**Comment by brummbar** [comment]
Created a PR to fix this. I decided to not convert the variable `$confPath` to a realpath, so when it's used later in the code it stays as relative path.
This is different from Drush 8, where it was always an absolute path.
I don't have a strong opinion on this, so it can be changed to match the 8 version.

**Comment by weitzman** [comment]
Lets work on the PR #3057
