### ISSUE TITLE
Missing argument 2 for Drush\Sql\SqlBase::__construct() SqlBase.php:29

### ISSUE THREAD

**Issue by danielkorte** [drush-ops/drush#3064]
I'm having a similar issue as #3047 with Drupal 8.4.0 and Drush 8.1.13. Drush was working fine until the Drupal and drush upgrade. I'm able to load the site in a browser without a problem and the database credentials are in place, but running any drush command that needs a database connection such as `drush status` results in this error:

`Missing argument 2 for Drush\Sql\SqlBase::__construct() SqlBase.php:29                                                                                                                                         [warning]
array_key_exists() expects parameter 2 to be array, null given SqlBase.php:454                                                                                                                                 [warning]
#0  Drush\Drush::getContainer() called at [/var/www/vendor/drush/drush/src/Drush.php:196]
#1  Drush\Drush::service(config) called at [/var/www/vendor/drush/drush/src/Drush.php:241]
#2  Drush\Drush::config() called at [/var/www/vendor/drush/drush/src/Drush.php:277]
#3  Drush\Drush::simulate() called at [/var/www/vendor/drush/drush/src/Sql/SqlBase.php:247]
#4  Drush\Sql\SqlBase->query(SELECT 1;) called at [phar:///usr/local/bin/drush/includes/environment.inc:393]
#5  drush_valid_db_credentials() called at [phar:///usr/local/bin/drush/lib/Drush/Boot/DrupalBoot.php:462]
#6  Drush\Boot\DrupalBoot->bootstrap_drupal_database_validate() called at [phar:///usr/local/bin/drush/lib/Drush/Boot/DrupalBoot8.php:109]
#7  Drush\Boot\DrupalBoot8->bootstrap_drupal_database_validate() called at [phar:///usr/local/bin/drush/includes/bootstrap.inc:430]
#8  drush_bootstrap_validate(4) called at [phar:///usr/local/bin/drush/includes/bootstrap.inc:507]
#9  drush_bootstrap_max() called at [phar:///usr/local/bin/drush/includes/bootstrap.inc:456]
#10 drush_bootstrap_to_phase(-2) called at [phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php:59]
#11 Drush\Boot\BaseBoot->bootstrap_and_dispatch() called at [phar:///usr/local/bin/drush/includes/preflight.inc:66]
#12 drush_main() called at [phar:///usr/local/bin/drush/includes/startup.inc:458]
#13 drush_run_main(, /, Phar detected. Proceeding to drush_main().) called at [phar:///usr/local/bin/drush/includes/startup.inc:365]
#14 drush_startup(Array ([0] => /usr/local/bin/drush,[1] => @local,[2] => status)) called at [phar:///usr/local/bin/drush/drush:114]
#15 require(phar:///usr/local/bin/drush/drush) called at [/usr/local/bin/drush:10]
Missing argument 2 for Drush\Sql\SqlBase::__construct() SqlBase.php:29`

**Comment by greg-1-anderson** [comment]
This is a duplicate of an issue I can't seem to find at the moment.

The issue is that Drush cannot bootstrap your site. It can't find your database credentials, and therefore does not know what kind of sql driver to use. It prints this error instead of something more reasonable (e.g. "cannot find database credentials for this site").

The latest version of Drush 8 is 8.1.15; not sure that an upgrade will change the behavior here.

**Comment by danielkorte** [comment]
Thanks for the response, but I'm seeing my database credentials and the database driver in the `drush status` output below the error so it seems that Drush is reading my settings. The status output does not show a successful connection though (even though the site loads fine in a browser). A Drush upgrade did not fix the issue.

**Comment by danielkorte** [comment]
I couldn't get 8.1.15 to work so I upgraded to Drush 9.0.0-beta7 and the issue has gone away.

**Comment by aangelinsf** [comment]
I was unable to get 8.1.x to work either so I too upgraded to 9 to resolve this issue.

**Comment by killes** [comment]
I've had the same issue. Happened when I had installed drush 9 through composer but was actually using drush 8 to execute commands on the site.

**Comment by rob-duplock** [comment]
Based on what @killes said, I solved in my Drupal VM by using the project specific composer required drush 9 rather than the drush 8 version that Drupal VM installed by default:
`which drush`
`>> /usr/local/bin/drush`
`cd /usr/local/bin`
`sudo mv drush drush8`
`sudo ln -s /var/beetbox/dof/vendor/drush/drush/drush drush`
`drush --version`
`>> Drush Commandline Tool 9.3.0`

**Comment by robme** [comment]
Same issue as @killes, the VM had Drupal 8 installed at `/usr/local/bin/drush`, and I had specified Drupal 9 in `composer.json`.

Unfortunately @rob-duplock's fix did not work for me, however, removing Drush from composer made it work so that it only had the globally installed one.

**Comment by Javi-er** [comment]
> Same issue as @killes, the VM had Drupal 8 installed at `/usr/local/bin/drush`, and I had specified Drupal 9 in `composer.json`.
> 
> Unfortunately @rob-duplock's fix did not work for me, however, removing Drush from composer made it work so that it only had the globally installed one.

This was the reason for me as well, removing Drush dependency fixed the issue on a Pantheon hosted site. Thanks for the suggestion.
