### ISSUE TITLE
Add sql-fetch command

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#3071]
That would be useful for scripting to be able to retrieve data from database in different formats. As I understood this happens automatically if a command returns _RowsOfFields_. With current implementation of `drush sql-query` command this is not possible because it runs queries through shell. And besides it can be used for any kind of SQL queries not just SELECTs.

**Comment by weitzman** [comment]
I agree that this would be useful.

We have had several requests to stop using the shell for sql commands and use PDO instead. Folks with docker containers don't have the `mysql` client. So, I'd be interested in converting sql-query and friends, as opposed to creating a new sql-fetch.

**Comment by weitzman** [comment]
FWIW, `mysql` can return json https://dev.mysql.com/doc/refman/5.7/en/mysql-shell-json-output.html

**Comment by jonhattan** [comment]
FYI, I usually do this:

```
$ drush @d8 ev "return db_query('SELECT * FROM users')->fetchAll()" --format=json
[
    {
        "uid": "0",
        "uuid": "a62ba8fb-1d81-4a64-8097-73ccbe104f4d",
        "langcode": "en"
    },
    {
        "uid": "1",
        "uuid": "a62423ee-bfad-463c-bf0a-706c78a8ef0b",
        "langcode": "en"
    }
]
```

**Comment by weitzman** [comment]
I made a quick PR for this at #3258 but once again am stymied by the Output Formatter system. Lets continue discussion there.
