### ISSUE TITLE
composer autoload spec in a non-module command isn't picked up

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#3073]
So that I can add other classes to my non-module command package, I tried adding this to my composer.json:

```
  "autoload": {
    "psr-4": {
      "Drush\\": "",
      "DrupalCodeBuilderDrush\\": ""
    }
  }
```

This ought to allow me to add classes in the DrupalCodeBuilderDrush namespace to the /src folder.

However, trying to instantiate one of these classes crashes.

It looks like I've correctly declared the PSR-4, as doing 'composer dumpautoload' in the folder for my package produces this in the Composer classmap file:

```
    'DrupalCodeBuilderDrush\\Question\\ComponentPropertyQuestion' => $baseDir . '/src/Question/ComponentPropertyQuestion.php',
```

However, doing the same in the Drupal root folder doesn't help.

Is this maybe caused by the Drupal composer starter repo putting Drush commands in drush/contrib?

**Comment by greg-1-anderson** [comment]
Composer should allow this. If you install the command via `composer require` and it is placed via composer installers, then your autoloaded classes should all be available.

**Comment by weitzman** [comment]
This sounds like a composer issue, not drush.
