### ISSUE TITLE
drush status fields have changed

### ISSUE THREAD

**Issue by mf-lit** [drush-ops/drush#3076]
Drush 9 has introduced a  change to the output of `status` somewhere along the line:

Drush 8 and Drush 9-alpha1:
```
$ drush status | grep 'DB\|Database'
 Database driver        :  mysql                                                
 Database hostname      :  localhost                                            
 Database port          :                                                       
 Database username      :  xxxx                                            
 Database name          :  yyyy  
```

Drush9-beta7:
```
$ drush status | grep 'DB\|Database'
 DB driver        : mysql
 DB hostname      : localhost
 DB port          :    
 DB username      : xxxx
 DB name          : yyyy
 Database         : Connected  
```

This change from "Database" to "DB" has clobbered our build scripts as we're parsing information from this output. I'm curious if this change is necessary/intentional?

**Comment by greg-1-anderson** [comment]
Major releases may introduce changes to clean things up or make things more clear. Scripts should not be parsing table output. Instead, use `--format=yaml` or `--format=json`. The keys in the machine-parsable formats should be unchanged.

That said, we could potentially convert from "DB" back to "Database". The shorter names are a little better for table output, though, as the right column can often contain long strings, so there is a benefit to shortening the left column, as that will tend to reduce wrapping in the long term.

**Comment by greg-1-anderson** [comment]
Note also that Drush 9.0.0-beta5 abandons the old Drush command processor, and replaces it with the Symfony Console runtime. Drush 9.0.0-beta4 and earlier are strongly deprecated; there is no need to use those versions when comparing behavior change in Drush. Just compare 9.0.0-beta5 and later with versions of Drush 8.

**Comment by weitzman** [comment]
Correct - please use yaml or json formats for scripts.
