### ISSUE TITLE
Env vars lead to backend "Could not open input file: env"

### ISSUE THREAD

**Issue by axel-rutz** [drush-ops/drush#3078]
Drush version 8.1.15

Drush backend invoke with drush environment variable results in messed up drush invocation.
See bold code in command output.

Invocation code:

>     drush_invoke_process("@self", 'sql-sync', ["@$source", "@$destination"]);

Alias:

`$aliases['foo.default']['#env-vars']['DRUSH_PHP'] = 'php5.6';`

Command output:

> **Backend invoke: /usr/bin/php env DRUSH_PHP=php5.6 /opt/drush/drush.php** --php=/usr/bin/php  --backend=2 --verbose --debug                                                                           [command]
> --root=/foobar/docroot --uri=http://foobar.xxx  sql-sync '@live.default'
> '@self' 2>&1 [1.27 sec, 10.47 MB]
> /usr/bin/php env DRUSH_PHP=php5.6 /opt/drush/drush.php --php=/usr/bin/php  --backend=2 --verbose --debug                                                                                            [notice]
> --root=/foobar/docroot --uri=http://foobar.xxx  sql-sync '@live.default'
> '@self' 2>&1 [1.27 sec, 10.48 MB]
> Could not open input file: env
> The command could not be executed successfully (returned: Could not open input file: env                                                                                                             [error]
> , code: 1) [1.3 sec, 10.48 MB]
>

**Comment by greg-1-anderson** [comment]
The env variables are mysteriously out-of-order relative to the path to the php binary. Not sure when that could have happened; this code hasn't changed in a long time.

How are you calling the code that runs the `drush_invoke_process`?

**Comment by greg-1-anderson** [comment]
When I run `drush8 @localsite.dev status -d` it works fine. It targets the drush launcher, not php. You perhaps have set up your local path to php in some way other than just having it on the $PATH, I imagine?

**Comment by axel-rutz** [comment]
Hmm, further strange experiences:

* every drush foo command in the cli runs fine
* sometimes when drush commands call others, the problem arises. i have a custom command that calls sql-sync which then calls core-rsync. the problem only arises in the 2nd call (to rsync). 

Spooky...

**Comment by axel-rutz** [comment]
> You perhaps have set up your local path to php in some way other than just having it on the $PATH, I imagine?

Nothing like this. Just the above "#env-vars".

**Comment by axel-rutz** [comment]
Quite notable: sql-sync does a correct invocation of "status" to get the local temp dir, but an incorrect one to rsync:

```
...

Starting to discover temporary files directory on Destination. [10.24 sec, 4.1 MB]                                [ok]
Backend invoke: env                                                                                          [command]
PATH=/home/www-data/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
COLUMNS=118 /var/www/html/docroot/../vendor/bin//drush.launcher  --backend=2 --verbose --debug
--root=/var/www/html/docroot --uri=http://dev.foo  core-status 2>&1 [10.24 sec, 4.11 MB]
env PATH=/home/www-data/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin     [notice]
COLUMNS=118 /var/www/html/docroot/../vendor/bin//drush.launcher  --backend=2 --verbose --debug
--root=/var/www/html/docroot --uri=http://dev.foo  core-status 2>&1 [10.24 sec, 4.11 MB]

Cache HIT cid: 8.1.15-alias-path--a6077306587ad70d16927c936dea3d30 [10.68 sec, 4.12 MB]                        [debug]
Cache SET cid: 8.1.15-alias-path--a6077306587ad70d16927c936dea3d30 [10.68 sec, 4.12 MB]                        [debug]


Backend invoke: /usr/local/bin/php env                                                                       [command]
PATH=/home/www-data/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/var/www/html/vendor/drush/drush/drush.php --php=/usr/local/bin/php  --backend=2 --yes --verbose --debug
--root=/var/www/html/docroot --uri=http://default  core-rsync
'@w-live:/home/www-data/drush-backups/drupal/20171119022300/drupal_20171119_022301.sql.gz'
'@dev:/tmp/drupal_20171119_022301.sql.gz'   --remove-source-files 2>&1 [10.68 sec, 4.13 MB]
/usr/local/bin/php env                                                                                        [notice]
PATH=/home/www-data/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/var/www/html/vendor/drush/drush/drush.php --php=/usr/local/bin/php  --backend=2 --yes --verbose --debug
--root=/var/www/html/docroot --uri=http://default  core-rsync
'@w-live:/home/www-data/drush-backups/drupal/20171119022300/drupal_20171119_022301.sql.gz'
'@dev:/tmp/drupal_20171119_022301.sql.gz'   --remove-source-files 2>&1 [10.68 sec, 4.13 MB]
Could not open input file: env
The command could not be executed successfully (returned: Could not open input file: env                       [error]
, code: 1) [10.79 sec, 4.13 MB]
Copying dump file from Source to Destination. [10.79 sec, 4.07 MB]                                                [ok]
Starting to import dump file onto Destination database. [10.79 sec, 4.07 MB]                                      [ok]

...
```

**Comment by axel-rutz** [comment]
Hmm, the command builder was plain wrong. Can't believe that.
The referenced patch fixes the issue for me.

**Comment by weitzman** [comment]
Fixed in 8.x (see above commit). env-vars not yet implemented in drush9.
