### ISSUE TITLE
--yes and --no-interaction do not behave identically

### ISSUE THREAD

**Issue by danepowell** [drush-ops/drush#3082]
I'm using Drush 9.0.0-beta7.

According to [docs](https://github.com/drush-ops/drush/blob/791c6907bade5f3175d270df3f5f8a6dce1f8be7/src/Application.php#L60), [previous comments](https://github.com/drush-ops/drush/issues/3014#issuecomment-334316826), and [this issue](https://github.com/drush-ops/drush/pull/2927), the `--yes` and `--no-interaction` options should behave identically. In practice, they do not, at least for the site install command.

`drush si --yes` installs a site without any further interaction from the user, because it assumes a 'yes' response to whether to drop the database prior to install
`drush si --no-interaction` fails because it assumes a 'no' response to whether to drop the database

Ironically, for the moment this is actually a good thing, because if both of these were to behave like `--no-interaction` and assume 'no', there would be no way to force a site install! But we definitely need to figure out what the intended behavior is here.

**Comment by greg-1-anderson** [comment]
Hm, I prefer the behavior you describe. If this is repeatable, we should change the docs.

This is handled here: https://github.com/drush-ops/drush/blob/master/src/Style/DrushStyle.php#L14

Symfony defines --no-interaction as "answer all questions using the default value". The downside of replicating this behavior everywhere is that `--yes` would not necessarily cause a confirmation to pass if the default value is 'no'. However, the confirm method above is derived from SymfonyStyle, so as long as we can inject our object into our dependencies, then the behavior will be consistent.

So, lets fix the docs.

**Comment by weitzman** [comment]
I think this is a happy accident that may need to be fixed. Specfically, look at how we set the value of DRUSH_NEGATIVE at https://github.com/drush-ops/drush/blob/3a6d8d78da4885f15620df01fe0beed20e10d3ab/src/Preflight/LegacyPreflight.php#L103-L114

This overloading of --no-interaction is going to bite us later, no?

**Comment by weitzman** [comment]
See #3084 where I stop overloading -n|--no-interaction and also modernize a bit

**Comment by weitzman** [comment]
Lets discuss in #3084.
