### ISSUE TITLE
placing commands into a group

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#3088]
My custom commands show in the drush list output as being in 'global'.

Is there a way to put them together into a group? I've tried prefixing the command name with foo: like the commands in Drush itself, but that has no effect.

**Comment by greg-1-anderson** [comment]
If there is one command `foo:bar` then the command will be global. If there is `foo:bar` and `foo:baz`, then they should both be in the foo group. Is that not the case for you?

**Comment by joachim-n** [comment]
I didn't think to try it with two commands!

Works perrfectly. Thanks!
