### ISSUE TITLE
Drush 9 freaks out when using symlink

### ISSUE THREAD

**Issue by bpresles** [drush-ops/drush#3098]
Drush version used: Drush 9.0.0-beta7 (and reproduced also on beta 5 or 6)

With some structure, like the one used by Ansistrano, when we launch drush, it spawn processes indefinitely.

Example structure:

/srv/www/releases/mysite_1.0.2
/srv/www/current -> /srv/www/releases/mysite_1.0.2 (i.e: current is a symlink on mysite_1.0.2)

Inside the mysite_0.2 the Drupal is installed as follow:

- src/ (contains composer.json (and .lock) for all the project dependencies (drupal modules and others dependencies)
- src/web (Drupal root).

The core and modules are installed via Composer using composer/installers and the following installer paths, and Drupal Scaffold:

> "installer-paths":
>  {
>       "drush/contrib/{$name}": [
>         "type:drupal-drush"
>       ],
>       "web/core": [
>         "type:drupal-core"
>       ],
>       "web/libraries/{$name}": [
>         "type:drupal-library"
>       ],
>       "web/modules/contrib/{$name}": [
>         "type:drupal-module"
>       ],
>       "web/profiles/contrib/{$name}": [
>         "type:drupal-profile"
>       ],
>       "web/themes/contrib/{$name}": [
>         "type:drupal-theme"
>       ]
> },

In this configuration, when we go in /srv/www/current/src/web (drupal root) and type for example "drush status", it nevers return anything and if we do a "ps aux | grep drush" we see numerous drush processes (increasing rapidly) being spawn.

If we go to the /srv/www/releases/mysite_0.2/src/web directory instead (so not using the symlink), it works just fine.

Current workaround so: either go to the original directory (not the symlink) or specify the real path using --root drush option.

**Comment by weitzman** [comment]
Please open an issue with the webflo/drupal-finder. We depend on that package.
