### ISSUE TITLE
sql-sync should validate aliases

### ISSUE THREAD

**Issue by danepowell** [drush-ops/drush#3103]
If you run sql-sync with an invalid alias (i.e. `drush sql-sync @foo.remote @foo.local`, where `@foo.remote` isn't a valid alias), you get an obscure error:
> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Drush\Commands\sql\SqlSyncCommands::databaseName() must be an instance of Drush\SiteAlias\AliasRecord, boolean given,

This looks like a bug, but in fact is just Drush's way of telling you that you are using an invalid alias.

Ideally sql-sync would validate the provided aliases and provide a more helpful error message, such as if you provide an invalid alias to `drush si`:
> The alias @foo.remote could not be found.

**Comment by weitzman** [comment]
We do validate aliases - https://github.com/drush-ops/drush/blob/53a809e11e73c0d0385c0cde215ce6b5e824362d/src/Commands/sql/SqlSyncCommands.php#L149. not sure whats going on here.

**Comment by greg-1-anderson** [comment]
My results:
```
$ drush9 -s sql-sync @foo.bar @baz.boz
 [error]  Error: no alias record could be found for source @foo.bar 
```
Are you sure you're using the most up-to-date version of Drush 9?

**Comment by danepowell** [comment]
We're on beta7 (latest stable), it looks like that validation was only added in the last couple weeks, so it'll be in beta8

**Comment by greg-1-anderson** [comment]
beta8 has been released now 🎉

**Comment by greg-1-anderson** [comment]
Reopen if there is a problem.

**Comment by danepowell** [comment]
Thanks I will try beta8
