### ISSUE TITLE
Provide a global option 'filter' for commands that return RowsOfFields

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#3113]
This would allow to filter output by field value. The signature could be one of following.
```bash
drush config-status --filter-name=system.site
drush config-status --filter='name=system.site'
drush config-status --filter=name:system.site
```
This would be useful for generating rich reports especially when used in conjunction with existing _fields_ and _format_ options 

Optionally we may implement partial string matching.

**Comment by weitzman** [comment]
config-state isn't a core command. did you mean config-list? thats gone now. anyway, i'm not sure i follow the proposal. would this do anything that grep cannot do? 

i think you know, but for completeness sake we also automatically offer a --field option which limits results to just one value.

**Comment by Chi-teck** [comment]
> config-state isn't a core command. did you mean config-list?

I meant `config-status`, sorry for this confusion. The example has been updated.

**Comment by Chi-teck** [comment]
>  would this do anything that grep cannot do?

Yes, grep may be not convenient for formats like _json_.

**Comment by Chi-teck** [comment]
To be more explicit, existing `fields` is for selecting columns and proposed `filter` option is for rows.

**Comment by greg-1-anderson** [comment]
This would also be more convenient than `grep` in tables with word wrapping.

**Comment by weitzman** [comment]
This was done. A new option is automatically added to all RowsOfFields commands. Its documented as ` --filter[=FILTER] Filter output based on provided expression`. Expression details are at https://github.com/consolidation/filter-via-dot-access-data
