### ISSUE TITLE
--include option is undocumented and tilde expansion does not work

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#3114]
1. --include is no longer considered a global option. It does not appear at `drush topic core:global-options`, and thus is nearly undiscoverable.
1. As a result of above, tilde expansion does not run. Even if it did run, it might be too late since commandfile paths are gathered very early during preflight. If this is unfixable thats OK.

**Comment by greg-1-anderson** [comment]
We should make the preflight args visible in drush topic core:global-options.

I'm not sure how hard it would be to do tilde expansion for preflight args. Probably doable.

**Comment by weitzman** [comment]
Seems like the most straightforward way to show name and description for the following missing options is to just declare them as global option. Any reason not to do that?

```
--config
--alias-path
--include
--local
--backend
--strict
```

**Comment by greg-1-anderson** [comment]
Redundantly declaring preflight args as global options would solve the help issue, but not the tilde issue. It might be confusing to do that, but beyond that there's no reason why we couldn't.

I'd rather do it another way, but don't have a proposal yet.

**Comment by weitzman** [comment]
See https://github.com/drush-ops/drush/pull/3126 for a potential fix for the tilde problem. If thats accepted, I guess we manually add the 6 options above to `drush topic core:global-options`
