### ISSUE TITLE
Add an API method for getting cwd (and similar) from config.

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#3119]
drush_cwd() has been removed.

I can see there is a cwd() method on the Environment object, but I don't see how to get hold of that from a command.

**Comment by greg-1-anderson** [comment]
The Environment object is not available after preflight. It copies any useful information it contains to the configuration object. The cwd if available in config as `env.cwd`. The best way to get access to the config object is via `ConfigAwareInterface` / `ConfigAwareTrait`.

**Comment by weitzman** [comment]
Thanks Greg. Do you think we want/need getter methods for some of the main
config items? I think thats a bit more robust that grabbing config by key.

**Comment by joachim-n** [comment]
Thanks for the quick response.

I found an example of this in PhpCommands now I know what to look for.

Would be good to have a section in the docs on getting things from the environment.

**Comment by greg-1-anderson** [comment]
Thought I commented here last week; must not have gotten saved.

Yes, we could create a DrushConfig object with specific accessor methods for folks to use. That would be a good idea.

**Comment by weitzman** [comment]
Accesor methods added today via #3149. See #2954 for docs in interfaces that commands may implement.

**Comment by pfrenssen** [comment]
For people coming here from Google looking for a quick answer:

```
$cwd = $this->getConfig()->getContext('environment')->get('env.cwd');
```
