### ISSUE TITLE
problems updatedb command with drush 9 beta4

### ISSUE THREAD

**Issue by sede1971** [drush-ops/drush#3120]
Hi
I don't use drush globaly because I need to work with a lot of olds drupal
thus I use drush in local for each drupal 8
I have try a lot of things but I have always with drush 9 in a drupal 8.4 installation
my db is a postgresql db ( PostgreSQL 10 ) and I think the problem is there. I have seen that a commit has be done 
https://github.com/drush-ops/drush/pull/2567 but this commit is for drush 9.0.0-beta8

But If I upgrade to these version of drush, my command line freezes, no messages, nothing
I see that the process takes 25 to 30% of my ressources but nothing appears in the window.

with beta4 I have a warning for JSONcache file but I see that a patch for this issue
https://github.com/drush-ops/drush/issues/2912

but with beta4 a command like php ../vendor/drush/drush/drush updb 
generate an error like this 
Fatal error: Call to undefined function drupal_get_installed_schema_version() in ..\core\includes\install.inc on line 80
 [error]  Drush command terminated abnormally due to an unrecoverable error.

somebody has a solution or idea ?  beta8 is it ok to use ? is it ok for pgsql ?
is it the version of postgresql  (10) ?

**Comment by sede1971** [comment]
ok I have found the problem with debug I see that 
The command 'psql -q' is required for preflight but cannot be found. Please install it and retry.

because I use cli to connect to db I need this
I can use beta-8 and updb

**Comment by greg-1-anderson** [comment]
Just FYI, Drush 9.0.0-beta5 contained a rewrite of the Drush preflight and runtime engine, so 9.0.0-alpha thru 9.0.0-beta4 are no longer useful reference points for behavior comparison.

Glad ou got things working with beta8.
