### ISSUE TITLE
drush.launcher removes spaces from drush.ini settings

### ISSUE THREAD

**Issue by dmp1ce** [drush-ops/drush#3129]
`drush.launcher` will remove spaces from values set in `drush.ini`. This caught me by surprise because I didn't know there were multiple launchers. Now I'm using `drush.php` which works fine. I was using `drush` finder which was then calling `drush.launcher`. Drush is installed via composer using the drupal-composer/drupal-project project using the 7.x branch.

I did spend some time trying to debug the `drush.launcher` script and found the problem line to be https://github.com/drush-ops/drush/blob/8.x/drush.launcher#L119 although no matter what shell tricks I tried to use, I couldn't figure out how to produce a `exec` command that would work as expected.

If the code is left as is, then spaces will be removed. For example I had `sendmail_path='/usr/bin/msmtp -a myvhost -t'` set in `drush.ini` and it would be changed to `sendmail_path='/usr/bin/msmtp-amyvhost-t'`. If I left the space in, then the `exec` command will fail a few lines down in the script.

**Comment by greg-1-anderson** [comment]
Drush 7 is no longer supported.

Drush 9 no longer supports drush.ini.  It would be best to not rely on it. Try setting the PHPRC environment variable to point to the php.ini you want to use.

**Comment by dmp1ce** [comment]
OK. I did get a fix for this. I didn't now that the 8.x branch was Drush 7.

**Comment by dmp1ce** [comment]
I'll try to use the PHPRC environment variable.

**Comment by greg-1-anderson** [comment]
| I didn't know that the 8.x branch was Drush 7.

The 8.x branch is Drush 8.
