### ISSUE TITLE
Unexpected behavior with @aliases run from inside a local drupal docroot

### ISSUE THREAD

**Issue by joshkoenig** [drush-ops/drush#313]
Not sure if this is by design or not, but I get unexpected behavior when running drush at an alias if I do it from within a drush installation. It definitely connects to the remote instance, but then seems to attempt to use the local install to fulfill some of the request. 

For instance, status shows very little info, and watchdog-show fails due to inability to bootstrap. Once I move out of the drupal docroot locally, it's back to normal.

**Comment by ForestMars** [comment]
This page was suggested as background for Pantheon ticket #43242 ("looks more like a drush problem than a Pantheon problem.") 

However given that drush features is apparently/completely broken on Pantheon (per support rep) I'd say it's everybody's problem, at least anyone who is using drush to deploy Drupal. (Really, who does that anyway?)

**Comment by RobLoach** [comment]
For those of you still following along, @greg-1-anderson wrote a small article about `policy.drush.inc`:
https://pantheon.io/blog/fix-drush-site-aliases-policy-file

May help, or not. :icecream:

**Comment by greg-1-anderson** [comment]
Drush 8 is now the default on Pantheon for new sites, but old sites continue to use Drush 5. Upgrading to Drush 8 is recommended.
