### ISSUE TITLE
@validate-file-exists doesn't seem to take --root into account

### ISSUE THREAD

**Issue by gaelg** [drush-ops/drush#3131]
I tried `drush @docker sql-query --file=../private/$DUMP` and got `[error]  File(s) not found: ../private/2017-11-02_17:12.sql `
The same command work if I execute it directly inside the container, without any alias.
After some search, I found out that if I remove "@validate-file-exists file" from SQLCommands.php function query(), it works. I tried a getcwd() in validateFileExists(), before the call to file_exists() and got the wrong dir. I think it's because validateFileExists() doesn't take --root into account, which is added when the command is executed through SSH.

**Comment by weitzman** [comment]
The cwd should already be Drupal root by the time @validate-file-exists starts doing its work. See https://github.com/drush-ops/drush/blob/514419fccdefce1b98a84d4b824643b83b8117b6/src/Boot/DrupalBoot.php#L183.

**Comment by greg-1-anderson** [comment]
Relative file paths used in options (e.g. `--file`) should be evaluated relative to the cwd that was set prior to running Drush, not relative to the Drupal root, which is set as described above.

The original cwd is available via the key `env.cwd` in config. `@validate-file-exists` should probably convert relative paths to absolute from `env.cwd` before testing (and set the $option to ensure consistency).

Relative paths for remote commands are perhaps a dubious proposition. Logically, these are relative to the $HOME directory of the remote user.

**Comment by greg-1-anderson** [comment]
Drush 8 and earlier sets the cwd for remote commands to the Drupal root, so I suppose we should maintain that behavior.

**Comment by weitzman** [comment]
Its a problem in SqlCommands. Fixing now ...

**Comment by greg-1-anderson** [comment]
Maybe it would be helpful to cwd in preflight?

**Comment by weitzman** [comment]
Fixed in #3135. We decided not to move the chdir() to Preflight.

**Comment by gaelg** [comment]
Thank you, it works! :)
