### ISSUE TITLE
upgrade problem with drush 9

### ISSUE THREAD

**Issue by SUN123RAY** [drush-ops/drush#3138]
when I was trying to upgrade my drush to drush 9, using this command 
composer require drush/drush:9.*

I got the following output:
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package drush/drush could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

**Comment by webflo** [comment]
Drush 9 is not stable yet. You have to adjust the ``minimum-stability`` settings (see the link in the error msg for more info) or require drush with ``composer require drush/drush:9.*@beta``

**Comment by SUN123RAY** [comment]
Actually, I was trying to upgrade Drush to avoid some conflicting issue. It’s because of the Drupal minor release (8.4.2),  Symfony components have been updated to ~3.2 (in 8.3.x they remain at 2.8.x). 
This causes a conflict with Drush –  should upgrade to Drush 9.
But after upgrading Drush, it is showing the same error,
PHP Fatal error:  Declaration of Drush\Command\DrushInputAdapter::hasParameterOption($values) must be compatible with Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false) in phar:///usr/local/bin/drush/lib/Drush/Command/DrushInputAdapter.php on line 27
Drush command terminated abnormally due to an unrecoverable error.

**Comment by greg-1-anderson** [comment]
Drush 9 is not available via a phar. If you have a `phar://` path, you are not using Drush 9.

**Comment by SUN123RAY** [comment]
then can you please suggest what to do ?

**Comment by greg-1-anderson** [comment]
Remove the drush phar from your system if you do not intend to use it. Upgrade it to 8.1.15 if you intend to use it. Maybe remove your site-local Drush if you are going to use the global drush.

If you do want to use a site-local Drush, then use the drush launcher, or call vendor/bin/drush directly.

**Comment by SUN123RAY** [comment]
how to remove the drush phar ?
should I uninstall drush (by removing the drush line in composer.json) and
reinstall drush 8.1.15 (composer global require drush/drush:8.*)?
