### ISSUE TITLE
Drush make: Unable to clone redux

### ISSUE THREAD

**Issue by webdeli** [drush-ops/drush#314]
Hi Moshe et al, Report: I am using Drush Make local OSX pointed at a remote URL with a project.stub.make file in a public http:// request which references a profile in a private BitBucket hosted Git with SSH-Key auth.

When make attempts to grab the profile - I get the following error message using -V and --debug:

...<code>
Bootstrap to phase 0. [7.01 sec, 6.29 MB]                                                                                                    [bootstrap]
Found command: make-process (commandfile=make) [7.01 sec, 6.29 MB]                                                                           [bootstrap]
Loading release_info engine. [7.17 sec, 6.3 MB]                                                                                                 [notice]
Calling hook drush_make_process [7.17 sec, 6.43 MB]                                                                                              [debug]
<strong>Unable to clone project from git@bitbucket.org:client/project_drupal.git. [12.31 sec, 6.59 MB]                                                [error]</strong>
Returned from hook drush_make_process [12.31 sec, 6.44 MB]                                                                                       [debug]
Command dispatch complete [12.31 sec, 6.41 MB]                                                                                                  [notice]
Peak memory usage was 8 MB [12.31 sec, 6.41 MB]                                                                                                 [memory]
Returned from hook drush_make [12.32 sec, 6.55 MB]                                                                                               [debug]
Command dispatch complete [12.32 sec, 6.53 MB]                                                                                                  [notice]
Peak memory usage was 8.47 MB [12.32 sec, 6.52 MB] 
</code>...

(Full output here: https://gist.github.com/webdeli/7851286)

It seems that Git is not able to clone - but on the output alone, the reason is unclear.

Any advice on how I can determine the cause and address my local configuration?

As reference - The project.make.stub and Drupal profile and make file in the private BitBucket repository are building fully and successfully on our development server (Ubuntu VM at Racktype.com)

Additional system info:

OSX (Mavericks) 10.9
Git - git version 1.8.5.1
Drush Version   :  6.1.0

Look forward to any advice / assistance / light you can shed on this issue.

**Comment by ergonlogic** [comment]
The git url in the log is using an ssh connection (`git@...`) Try simply cloning the repo as the same user that you're running `drush make`. You might need to add a deploy key, or accept github's SSH key if this is the first time cloning from there.

**Comment by greg-1-anderson** [comment]
May be resolved. In any event, please use [Drupal Answers](http://drupal.stackexchange.com/questions/tagged/drush) for support requests.
