### ISSUE TITLE
Can't run drush after global install using composer in windows 10

### ISSUE THREAD

**Issue by jsibley2** [drush-ops/drush#3141]
Hello,

It is quite possible that I am doing something stupid, I realize. I installed drush in windows using composer.
If I type "drush @none st" I get:
![image](https://user-images.githubusercontent.com/6576953/32419337-4a8b1d70-c246-11e7-9641-a2f4dcca0d38.png)
However, if I type drush st I get:
Could not open input file: C:\\Users\\Jonathan\\drush.php

Is this a path issue? If so, is there an obvious path that needs to be added? Is there something else I need to do?

Many thanks for any ideas.

**Comment by jsibley2** [comment]
I noticed that I had a file called simply "drush" in my users\[my name] directory, so given the error message reported above, I renamed the file "drush.php"

That now works, but is that the drush that I'm supposed to be using after installing drush with composer, or is that an artifact of a prior installation?

Thanks for any help.

**Comment by Nick-Hope** [comment]
I installed Drush 8.1.15 on Windows 10 version 1511 by running `composer global require drush/drush:8.1.15` from Git Bash (I previously installed Composer and Git and opened Git Bash from my Windows Explorer context menu. If this part confuses anyone, watch [this Git tutorial](https://www.youtube.com/watch?v=SWYqp7iY_Tc) (I didn't install the optional Unix tools like he did)). The installation took a good few minutes during which it looked like nothing was happening.
I then added C:\Users\Nick\AppData\Roaming\Composer\vendor\drush\drush to my system variables path (according to [this](https://modulesunraveled.com/drush/installing-drush-windows), it could also be in the user variables path.
Drush now appears to work as expected. I do see a hidden folder, C:\Users\Nick\.drush that contains a cache folder, but I don't see any "drush" file at that level.

**Comment by greg-1-anderson** [comment]
Please do not install Drush -- or any other PHP commandline tool -- using `composer global require`. Please use [cgr](https://github.com/consolidation/cgr) instead. See [Fixing the Composer Global command](https://pantheon.io/blog/fixing-composer-global-command).
