### ISSUE TITLE
sql-sync and rsync stopped working on Drush update to 9

### ISSUE THREAD

**Issue by TipiT** [drush-ops/drush#3151]
This is probably related to https://github.com/drush-ops/drush/issues/3046 .

After Drush update from 8 to 9 `$ drush sql-sync @stage @local` does not work anymore. Error with --debug is: 

`Calling system(rsync -e 'ssh ' -akzv  --stats --progress --remove-source-files deploy@123.123.123.123:/home/deploy/drush-backups/project/20171107142207/project_20171107_142207.sql.gz /tmp/project_20171107_142207.sql.gz);
Permission denied (publickey).
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.1]
 [error]  Could not rsync from deploy@123.123.123.123:/home/deploy/drush-backups/project/20171107142207/project_20171107_142207.sql.gz to /tmp/project_20171107_142207.sql.gz [16.48 sec, 8.67 MB] 
 [info] Command dispatch complete [16.48 sec, 8.09 MB]
 [debug] Cache HIT cid: 9.0.0-beta3-alias-path--6cca5c389dfb29d7269784fbf792dceb [16.48 sec, 8.08 MB]
 [debug] Cache SET cid: 9.0.0-beta3-alias-path--6cca5c389dfb29d7269784fbf792dceb [16.48 sec, 8.08 MB]
 [notice] Copying dump file from Source to Destination. [16.5 sec, 8.6 MB]
 [error]  core-rsync failed. [16.5 sec, 8.56 MB] 
 [info] Command dispatch complete [16.5 sec, 8.54 MB]
`
So it looks like ssh-options are not taken to the command when doing rsync. See:
`rsync -e 'ssh '` above.

So the ssh-options are not taken into consideration from aliases file and it does work either when giving them from the command line. E.g. `drush rsync @from @to --ssh-options="-i/var/www/xrg/deploy_rsa" `

Which is pretty weird because `drush @stage status` and even `drush @stage sql-dump > ../private/dbdumps/stage-dump.sql` works. Actually rsync is the only command which I have found not to work. Everything else also seems to work as expected.

Drush aliases file which has been working perfectly until the update:

`$aliases['local'] = array(
  'root' => '/var/www/project/web',
  'uri' => 'project.dev',
  'path-aliases' => array(
    '%dump-dir' => 'sites/default/files/tmp',
    '%files' => 'sites/default/files',
#    '%drush-script' => '/usr/local/drush',
    '%drush-script' => '/usr/local/bin/drush',
  ),
);

$aliases['stage'] = array (
  'root' => '/srv/www/project/web',
#  'uri' => '123.123.123.123',
  'uri' => 'https://example.com',
  'remote-host' => '123.123.123.123',
  'remote-user' => 'deploy',
  'os' => 'Linux',
  'ssh-options' => '-p22 -o"AddressFamily inet" -i"/var/www/project/keys/deploy_rsa"',
  'path-aliases' => array(
    '%dump-dir' => '../tmp',
#    '%dump-dir' => 'sites/default/files/tmp',
    '%files' => 'sites/default/files',
  ),
  'rsync' => array (
    'no-cache' => TRUE,
  ),
);
`
Another notable stuff:
I'm am on: drupalvm: Box 'geerlingguy/ubuntu1604' (v1.1.6) is running the latest version.

**Comment by greg-1-anderson** [comment]
Drush 8 supports remote-to-remote rsync calls. Drush 9 does not.

**Comment by TipiT** [comment]
Ok, thanks for quick answer! Then I start looking for an alternative.

**Comment by greg-1-anderson** [comment]
See the workarounds in the issue you referenced above. We may add this feature back in at some point, probably after 9.0.0.

**Comment by TipiT** [comment]
Yeah! Would be very much needed. :+1: Thank you!
