### ISSUE TITLE
drush entup is broken after latest symfony/http-foundation update (v2.8.29)

### ISSUE THREAD

**Issue by marcusx** [drush-ops/drush#3161]
drush entup gives me

`
exception 'RuntimeException' with message 'Failed to set the session handler because headers have already been sent by "/.../vendor/drush/drush/includes/output.inc" at [error]
line 41.' in /.../vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:395
`
Since the latest `symfony/http-foundation` update to v2.8.29

`
Drush Launcher Version: 0.4.2
Drush Version   :  8.1.15
`

**Comment by greg-1-anderson** [comment]
Does the Drupal UI fail similarly?

Use [webflo/drupal-core-strict](https://github.com/webflo/drupal-core-strict) to avoid using new dependency versions before the Drupal core maintainers have had a chance to resolve problems.

**Comment by greg-1-anderson** [comment]
Continued in #3163.
