### ISSUE TITLE
Sandwich example is not inclusive and should be replaced.

### ISSUE THREAD

**Issue by leafysweets** [drush-ops/drush#3164]
It may seem like a cute easter egg, but the sandwich example relies on a sexist trope with a [good bit of history implying women are subservient and belong in the kitchen](https://en.wikipedia.org/wiki/Make_me_a_sandwich) — seeing as drush is such a standard tool that many developers use, and that Drupal's foundation and expansion has been accompanied by a [**huge** community of female developers](https://groups.drupal.org/women-drupal), the joke isn't worth it.

This isn't about safe spaces or censorship. This is about not forcing women developers to see something fostered by a "men's club" culture that is still very real and prevalent in the industry.

**Comment by SuperNami** [comment]
Jezus christ...

**Comment by kalpaitch** [comment]
Seems like a reasonable request, I'm sure it was totally innocuous but worth removing all connection to 'make me a sandwich'. Sound like a plan?

**Comment by leafysweets** [comment]
@kalpaitch Yeah, that seems like the best course of action. It's just really frustrating to be alienated (even seemingly low-key) from dev communities as a new female dev whose workplace is migrating to Drupal :( Thanks for understanding!
