### ISSUE TITLE
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file

### ISSUE THREAD

**Issue by SuperNami** [drush-ops/drush#3165]
After running `drush version` I'm faced with these errors:
```
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
sh: generate_command_executed_sequence: line 1: syntax error: unexpected end of file
sh: error importing function definition for `generate_command_executed_sequence'
 Drush Version   :  8.1.15
```

I'm running on:
- Manjaro linux (Arch linux fork)
- php 7.1.11-1 (from [aur](https://www.archlinux.org/packages/extra/x86_64/php/))
- Drush 8.1.15 (bundled in composer [drupal-project](https://github.com/drupal-composer/drupal-project))

**Comment by SuperNami** [comment]
Issue resolved when updating Drush to latest version with: `composer global require drush/drush:dev-master`

**Comment by greg-1-anderson** [comment]
Please do not install Drush -- or any other PHP commandline tool -- using `composer global require`. Please use [cgr](https://github.com/consolidation/cgr) instead. See [Fixing the Composer Global command](https://pantheon.io/blog/fixing-composer-global-command).
