### ISSUE TITLE
drush updb should *not* run entity updates by default

### ISSUE THREAD

**Issue by Berdir** [drush-ops/drush#3167]
This is the default in Drush 8 but it looks like it changed in Drush 9?

Running entity updates by default is wrong and inconsistent with update.php. It is also wrong to check for differences *before* running normal updates because update functions must apply specific entity updates so that as a result of running those, there should be *no* pending entity updates after that, so showing them upfront is scary and misleading.

While some custom sites/updates might rely on using it and that's their choice, it's not reliable (will fail hard and bad if there is data on destructive updates), some users won't use drush, so it shouldn't do that by default.

Also seems to be hiding some entity updates on the 8.4 update if I saw that correctly.

**Comment by weitzman** [comment]
OK, happy to make changes here. Can you briefly explain how drupal ui handles this? Drupal shows you the pending entity updates but doesnt run them by default?

**Comment by Berdir** [comment]
It doesn't handle that at all currently, which is also not optimal and causes its own set of problems, mostly if contrib/custom developers aren't doing what they should :)

Entity updates are a developer tool, because they do not work in all conditions, and should be triggered specifically by update functions. 

See https://www.drupal.org/node/2554097 for background. This was actually changed in drush8 when this change originally happened to be consistent with core.
