### ISSUE TITLE
Change colors for IO warning format

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#3168]
Currently it prints block in red. So that there is no visual difference with `error` format.
Black foreground on yellow background seems the most suitable color scheme for this.

![io-formats](https://user-images.githubusercontent.com/673139/32791429-d52b09ca-c982-11e7-8290-991f09d7760e.png)
.

**Comment by greg-1-anderson** [comment]
We just adopt the Robo colors at the moment, but this is customizable. PRs welcome if anyone wants to improve the appearance.

**Comment by weitzman** [comment]
I agree that yellow on black would make sense for warning. 

I our logging, I think error should have white text instead of grey.
