### ISSUE TITLE
drush cr prints password to console

### ISSUE THREAD

**Issue by crashspringfield** [drush-ops/drush#3179]
When I try to rebuilt the cache I get the following error:

`exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such[error] file or directory' in
/home/user/php/patterns/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php:149`

and further down in the stacktrace it logs my password to the console:

`/home/user/php/patterns/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149):
PDO->__construct('mysql:host=loca...', 'patterns', '*password*',
Array)`

...but with the password I used to set up the site. This seems like it could be a security issue.

**Comment by greg-1-anderson** [comment]
This is outside of Drush's control. If you are concerned about leaking credentials in stack traces, then you can [turn them off in php.ini](https://stackoverflow.com/questions/17766931/disable-php-stack-trace).

However, most folks accept this risk, as only people who can view the password through other means can run Drush and see the stack trace.
