### ISSUE TITLE
Specify that Drush-Launcher  is NOT compatible with Drupal 7 sites

### ISSUE THREAD

**Issue by TynanFox** [drush-ops/drush#3181]
In the documentation on installation, please state somewhere that Drush Launcher is  ONLY compatible with Drupal 8 sites!

I wasted a few too many hours today wrestling with Drush Launcher since I am running D7 as well as D8 sites. Since Drush 9 is incompatible with D7, I would need to install Drush 8 on D7 and Drush 9 on D8. Using local installs with Drush Launcher seemed like a perfect solution. 

However, one of the checks in the DrupalFinder dependency of Drush Launcher determines that the site is running Drupal 8. If the site is running Drupal 7, the launcher simply terminates with very little explanation as to why. The error it produces simply says "The Drush Launcher could not find a Drupal site to operate on." Which is a particularly maddening error if you have your root set to a perfectly valid D7 installation. :)

Thank you. I will also post this to the Drush Launcher issue queue.

**Comment by greg-1-anderson** [comment]
The Drush Launcher should work on Drupal 7. Please submit bug reports and support requests on the launcher issue queue.

**Comment by weitzman** [comment]
The Drush Launcher expects to hand off the request to  site local Drush. So you must build your D7 site with Composer and list Drush as a dependency.

**Comment by TynanFox** [comment]
@weitzman I built my site originally a long time ago before composer usage became more common among Drupal users. So therefore it doesn't follow the drupal-composer structure. 

I HAD added composer and Drush as a composer dependency to my pre-existing site, but that wasn't enough to get it to pass. 

But I am reporting this to the launcher issue queue as requested.

**Comment by greg-1-anderson** [comment]
Since D7 does not use Composer by default, the launcher should also work fine if you put a copy of Drush, or a symlink to Drush in a launcher-approved location inside your D7 site.

**Comment by gisleh** [comment]
Please provide more explicit instructions.  I've tried to put a copy of drush in a subdirectory named "vendor/drush/drush/" on my Drupal 7 site, since that is where it lives on a Drupal 8 site, but no luck.

 What do you means by " a launcher-approved location inside your D7 site"?
