### ISSUE TITLE
Drush 9 site-install doesn't take in account the --account-pass option

### ISSUE THREAD

**Issue by nachosalvador** [drush-ops/drush#3186]
Hello, when I try to install a site running:

> drush site-install --account-mail=admin@example.com --account-name=admin --account-pass=admin --locale=en --site-name="example" --site-mail=admin@example.com -y

The site was installed correctly and the admin account created but the password didn't work and I can't login. I solved it doing drush upwd after site install.

Here my drush status:

> Drupal version   : 8.4.0
 Site URI         : default
 DB driver        : mysql
 DB hostname      : db
 DB port          : 3306
 DB username      : db
 DB name          : db
 Database         : Connected
 Admin theme      : seven
 PHP binary       : /usr/local/bin/php
 PHP config       : /usr/local/etc/php/php.ini
 PHP OS           : Linux
 Drush script     : /var/www/html/vendor/bin/drush
 Drush version    : 9.0.0-beta7
 Drush temp       : /tmp
 Drush configs    : /var/www/html/vendor/drush/drush/drush.yml
 Drush aliases    : 
 Install profile  : minimal
 Drupal root      : /var/www/html/web
 Site path        : sites/default
 Files, Public    : sites/default/files
 Files, Temp      : /tmp

**Comment by rodrigoaguilera** [comment]
please update to the latest beta (beta9) at least before reporting

**Comment by froboy** [comment]
I'm able to recreate this using `drush site-install -y config_installer --account-name=admin --account-pass=admin` on ` Drush version    : 9.0.0-beta9  `. I can get in with `uli` but admin/admin doesn't work.

**Comment by webflo** [comment]
@froboy config_installer is a special profile. It has explicit support for Drush. http://cgit.drupalcode.org/config_installer/commit/?id=a55e096f50d6795417554b1e8b019076d177e7ef is not in the latest release yet. Please try again with the dev version of config_installer.

**Comment by nachosalvador** [comment]
Thank you @froboy, update config_installer to dev version solves it.
