### ISSUE TITLE
Drush 9 rewrites file default/settings.php on live site on rsync

### ISSUE THREAD

**Issue by vistar** [drush-ops/drush#3192]
with `drush rsync @site.dev @site.live` command.

Even if it is write-protected. At drush 7 it was good.

How to prevent this?

**Comment by weitzman** [comment]
Your deployment strategy can only be named "Solo cowboy".

Anyway, see the --exclude-paths option

**Comment by greg-1-anderson** [comment]
rsync is a perfectly valid way to deploy code. However, the answer is the same: earlier versions of Drush had a more complicated version of rsync designed to make it easier to use for deploying code, but now you need to manage your own exclusions with `--exclude-paths`.
