### ISSUE TITLE
Declaration of Drush\Sql\Sqlsqlsrv::creds() should be compatible with Drush\Sql\SqlBase::creds() version 8

### ISSUE THREAD

**Issue by websystemse** [drush-ops/drush#3194]
Same problem as https://github.com/drush-ops/drush/issues/2967 but with Drush 8.

Trying to connect to an MS SQL database. Works nice in GUI.

Affected file: /lib/Drush/Sql/Sqlsqlsrv.php

**Comment by greg-1-anderson** [comment]
I guess what is being requested here is a backport of #2969 for Drush 8.

PRs welcome.

**Comment by weitzman** [comment]
Lets talk in the PR #4760
