### ISSUE TITLE
Drush Version 9 hangs

### ISSUE THREAD

**Issue by anrizal** [drush-ops/drush#3200]
Hello,

I tried to run drush --debug with drush launcher and it hangs after printing VENDOR ROOT.
what happened ? and where should I start to debug this ?

Addition: 
btw, I am running drush inside WSL (Windows Subsystem for Linux) in windows 10.

Note: this happens after 9.0.0-beta5. If I use beta4, I have no issue

Thank you 

Regards

**Comment by anrizal** [comment]
Hello,

I got the latest launcher (0.4.3). 
btw, I am running drush inside WSL (Windows Subsystem for Linux) in windows 10.

In the past, I was able to use drush 9.0 when it was possible to be installed globally. Right now after it is not possible anymore, I switched to drush launcher. But somehow it hangs.

The interesting part is that if I use the same codebase (shared to virtual machine) in ubuntu virtual machine (Guest OS). it works.

**Comment by greg-1-anderson** [comment]
Drush 9 can still be used in a global install, as long as you do not use `composer global require`. If you want to install Drush globally, please use [cgr](https://github.com/consolidation/cgr) instead. See [Fixing the Composer Global command](https://pantheon.io/blog/fixing-composer-global-command).

**Comment by anrizal** [comment]
I tried to install it without composer by cloning drush repository directly. But now it hangs after several preflights. is there better way to see where it hangs ?
[preflight] Redispatch to site-local Drush: /home/username/vagrant/development-machine/projects/projectname/vendor/drush/drush/drush.

**Comment by weitzman** [comment]
Please use Drupal Answers for support questions.
