### ISSUE TITLE
Allow drush to use environment variables in alias files

### ISSUE THREAD

**Issue by legovaer** [drush-ops/drush#3202]
For Drush < 9 it was rather easy to inject environment variables into an alias file as it was written in PHP. Now that we're moving towards the yaml format for alias files in Drush 9.x it is more complex.

It would be nice to allow users to inject environment variables in their drush files the [same way as Symfony](https://symfony.com/doc/current/configuration/external_parameters.html) allows users it to do.

The format will be `%env(VARIABLE)%`.

**Comment by weitzman** [comment]
You can override values by env variable but thats not documented yet - #3009 

As a workaround, see https://github.com/drush-ops/drush/blob/master/examples/Commands/SiteAliasAlterCommands.php where you can use arbitary php to override alias pieces.

Neither of those approaches is better than your proposal so leaving this open, though it may move to https://github.com/consolidation/config

**Comment by greg-1-anderson** [comment]
See https://github.com/grasmash/yaml-expander/issues/9

**Comment by legovaer** [comment]
Oh cool. I'll go ahead and try testing with [yaml-expander](https://github.com/grasmash/yaml-expander). I hope I get it to work with Drush :)
