### ISSUE TITLE
command-specific not recognized?

### ISSUE THREAD

**Issue by bkosborne** [drush-ops/drush#321]
I'm using Drush 6.2.0.

Here is an alias setup:

```
$aliases['test-local'] = array(
  'root' => '/Users/bosborne/Sites/test/www',
  'uri' => 'test.dev',
  'path-aliases' => array (
    '%files' => 'sites/default/files',
    '%dump-dir' => '/Users/bosborne/Sites/drush_tmp',
    '%dump' => '/Users/bosborne/Sites/drush_tmp/dbsync.sql',
  ),
  'command-specific' => array(
    'sql-sync' => array(
      'no-cache' => TRUE,
    )
  ),
);
```

When I execute `drush sql-sync @test-local @test-stage` Drush tells me "Modification time of local dump file /Users/bosborne/Sites/drush_tmp/dbsync.sql is less than 24 hours old. Use the --no-cache [warning]
option to force a refresh."

However, if I change 'command-specific' to 'source-command-specific' then the notice goes away and it doesn't used the cached SQL file.

The target does not have anything in it for command-specific, though I tried adding it there as well.

**Comment by greg-1-anderson** [comment]
The pre-Drush-9 command handler is maintenance only. Also, looks like there is a workaround here. Closing.
