### ISSUE TITLE
Use of undefined constant UNISH_TMP - assumed 'UNISH_TMP'

### ISSUE THREAD

**Issue by richardbporter** [drush-ops/drush#3224]
When attempting to generate a coverage report with PHPUnit.

Example: `./vendor/bin/phpunit --coverage-html /path/to/report`

Results in:
```
Use of undefined constant UNISH_TMP - assumed 'UNISH_TMP' vendor/drush/drush/tests/CommandUnishTestCase.php:303
```
I'm not really sure what this should be. I changed it to `$coverage_file = tempnam($this->getTmp(), 'drush_coverage');` which resolves the error but increases the running time substantially.

**Comment by weitzman** [comment]
I think thats the right change. Any increase in time is due to enabling coderage tracking I would think.
