### ISSUE TITLE
Difference with remote hosts when single or group alias is used

### ISSUE THREAD

**Issue by jurgenhaas** [drush-ops/drush#324]
The following two commands are creating different commands when calling drush_build_drush_command() because they pass different set of variables:

drush @group.alias status
drush @group status

The first one is OK, because it comes from drush_do_command_redispatch() which determines the command options by calling drush_redispatch_get_options() where the options "php" and "php-options" get unset. That makes a lot of sense because we never know what's required on a remote host.

The second one gets it wrong, because it comes from drush_preflight_command_dispatch() which determines the command options by calling drush_get_context('cli') and that doesn't unset the options "php" and "php-options".

**Comment by FreekVR** [comment]
Ran across this issue today, though I'm surprised more people haven't. At any rate, it really only occurs when your own system has PHP installed on a different path than a remote group - in my case, using a remote alias for a multisite install on OSX didn't work until I made the change in drush.inc as suggested by jurgenhaas.

Created a new pull request for the current master branch.

**Comment by greg-1-anderson** [comment]
Now this has been committed.  Sorry for the delay.
