### ISSUE TITLE
Quick-Drupal: require_once(docroot//includes/bootstrap.inc): failed to open stream

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#3240]
Here are the reproducible steps on empty folder:

```
$ composer require drush/drush
  - Installing drush/drush (8.1.15)
$ php vendor/drush/drush/drush qd --yes --no-server --core=drupal-7 --root=docroot/
...
require_once(docroot//includes/bootstrap.inc): failed to open stream: No such file or directory DrupalBoot7.php:63                        [warning]

Fatal error: require_once(): Failed opening required 'docroot//includes/bootstrap.inc' (include_path='.:') in /Users/kenorb/temp/composer/drupal/vendor/drush/drush/lib/Drush/Boot/DrupalBoot7.php on line 63
...
```

**Comment by weitzman** [comment]
Thats not how Composer works. You have to install drupal via composer as well. See https://github.com/drupal-composer/drupal-project/. Composer and QD should not be used together. Thats one reason QD is out of Drush9.

**Comment by kenorb** [comment]
I just wanted to clarify that this command works fine, so I didn't have to download Drupal via composer:

    php vendor/drush/drush/drush qd --yes --no-server --core=drupal-7

but not when running with `--root=docroot/` parameter.
