### ISSUE TITLE
Expand list of directories to search for Drush generators

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#3242]
Currently only enabled modules can implement generators.
It would be handy if generators can be discovered from the same locations as Drush command files.

**Comment by richardbporter** [comment]
Posting link from Slack for reference.

https://github.com/drush-ops/drush/blob/master/src/Application.php#L305

**Comment by weitzman** [comment]
I started on this at #3246. Hopefully someone can finish it.
