### ISSUE TITLE
Add command to export .po files

### ISSUE THREAD

**Issue by Sutharsan** [drush-ops/drush#3251]
I want to deploy custom translations (translations that are set in the admin interface to override community translations). I want to deploy them by exporting and importing custom translations. This issue pairs with my proposal in #2164.

```
Exports to a gettext translation file.

Examples:
 locale-export nl > drupal.po
 locale-export nl --type=customized > custom-translations.po
 locale-export --template > drupal.pot

Arguments:
 langcode		The language code of the exported translations. Use 'template' to
 			export a translation template that contains only source strings.

Options:
 --types		The type of translations to be exported. Defaults to all below options.
 			Options:
 			- customized: Export only custom translations.
			- not-customized: Export only non-custom translations.
			- not-translated: Export untranslated strings too.
--template		Export a gettext template file. 
```

**Comment by TessaBakker** [comment]
1. I would change --type='' to --include=[non-custom, custom, untranslated], because this is how the export options are at admin/config/regional/translate/export.

2. Also I'm not a fan of using 'language' while you have to enter a language code, suggestion: langcode instead of language.

**Comment by Sutharsan** [comment]
I agree with changing 'language' to 'langcode'.

I like to keep the name of the 'type' option the same as with the import command. Not sure if 'include' makes things clearer.

'untranslated' does not require a language code. Either, as I propose, we use 'template' as langcode, or make the langcode an optional argument (or are arguments always required?)

**Comment by TessaBakker** [comment]
Include is a reserved option and type is better as suggested. Because you can use multiple types if needed, I changed it to types.
The type 'not_translated' is needed to get all untranslated strings of a language.

I think the command #3253 is ready to be reviewed.

**Comment by Sutharsan** [comment]
Instead of 'not_translated' I proposed a special "language" 'template', perhaps you overlooked that. The example: `locale-export template > drupal.pot` It is a special, and probably rarely used use case. Most developers will use Potx module and target specific modules or directories. Because of the special nature, I do suggest to compromise the 99% use case as little as possible.
As a bonus, the code is probably simpler when using langcode 'template' instead of type 'not_translated'.

**Comment by Sutharsan** [comment]
I propose to export *all* types by default, that is what core does, and I think it is a sensible default because it exports all strings.

**Comment by Sutharsan** [comment]
Updated the initial proposal with 'langcode' and 'types' as per your suggestions.

**Comment by Sutharsan** [comment]
In the PR it is proposed to change the type stings to 'not_customized', 'customized', 'not_translated'. I suggest 'not-customized', 'customized', 'not-translated' instead. Using dashes instead of underscores is more user friendly, and only requires a little additional code.

**Comment by TessaBakker** [comment]
Small update:
1. Changed the type strings to dashes.
2. While testing with 'en' as langcode I noticed that Drush was seeing 'en' as an alias for pm-enable. As a workaround I changed the param to an option '--langcode'.
3. Added an extra warning and changed the error to warning.
4. Some typo fixes and code style

**Comment by Sutharsan** [comment]
While testing with 'en' as langcode I noticed that Drush was seeing 'en' as an alias for pm-enable. As a workaround I changed the param to an option '--langcode'.

**Comment by Sutharsan** [comment]
Updated original proposal with 3 type options as per current code.

**Comment by Sutharsan** [comment]
The PR for this issue is now closed, the `locale:export` is currently available in master.
At last the issue can be closed.
