### ISSUE TITLE
Drush tab autocompletion not working on ZSH with Drupal 8

### ISSUE THREAD

**Issue by subhojit777** [drush-ops/drush#3256]
I have this inside my `.zshrc`:

```bash
autoload bashcompinit
bashcompinit
source /Users/subhojit/.drush/drush.complete.sh
```

The Drupal 8 site is using Drush 9-rc1. I am pressing tab, and the process stalls. When I interrupt the process it gives:

```
Killed by signal in _bash_complete after 2s
```

The Drupal 8 site is installed using https://github.com/drupal-composer/drupal-project. Weird thing is -- the process stalls only when I am doing the tab completion while inside the site docroot. The completion is working if done from anywhere else.

The tab completion is also working fine on Drupal 7, even when done from the site docroot.

I am using site aliases, and expecting to get the alias get completed on pressing tab, but it is not happening.

**Comment by weitzman** [comment]
Drush9 doesn't support autocomplete yet.

**Comment by manicmarvin** [comment]
Any plans for it to?
