### ISSUE TITLE
Add support for ENV variables in Settings.php

### ISSUE THREAD

**Issue by blueelvis** [drush-ops/drush#3257]
In order to support Blue-Green deployments, we need to use Environment variables inside Drupal `Settings.php` . Drush refuses to execute (As in throws errors) if the values are not hard coded. Is this something that can be fixed assuming that everyone stores credentials in the Environment variables these days?

**Comment by weitzman** [comment]
settings.php can certainly read env variables. Just make sure they are also available during a cli request.
