### ISSUE TITLE
drush.paths config should accept both paths and specific files.

### ISSUE THREAD

**Issue by grasmash** [drush-ops/drush#3279]
Executing `drush status -c docroot/sites/default/local.drush.yml` and `drush status --config=docroot/sites/default/local.drush.yml` does not load `docroot/sites/default/local.drush.yml`.

Similarly, setting `drush.paths.config` appears to have no effect.

**Comment by grasmash** [comment]
After more investigation, it appears that a file must be named exactly `drush.yml` in order to be loaded as config.

**Comment by greg-1-anderson** [comment]
`drush.paths.config` should ideally accept both paths and specific files.

**Comment by grasmash** [comment]
Addressed by https://github.com/drush-ops/drush/pull/3283.
