### ISSUE TITLE
Drush 9: config-import shows "Delete" option only (export says state identical)

### ISSUE THREAD

**Issue by davidwhthomas** [drush-ops/drush#3291]
Firstly, thanks for the effort on Drush, an awesome toolkit!

I'm trying Drush 9 and found an issue with the config import/export commands.
I just want to check the status in before reverting back to Drush 8.

```
drush config-export development
 [notice] The active configuration is identical to the configuration in the export directory (../config/development).
```
however, when trying to import the config, it says it will delete all config?
```
drush config-import development
...
|            | system.mail        | Delete    |
|            | system.logging     | Delete    |
|            | system.image.gd    | Delete    |
|            | system.image       | Delete    |
|            | system.file        | Delete    |
|            | system.diff        | Delete    |
|            | system.date        | Delete    |
|            | system.cron        | Delete    |
|            | system.authorize   | Delete    |
...
 Import the listed configuration changes? (yes/no) [yes]:
 > no
```
The config-export says the state is identical, but the config-import says it will delete all config?
Am I missing something? Please advise, thanks.

**Comment by weitzman** [comment]
Kinda curious why you are passing 'development'. Its very rare to define additional config labels beside gthe default(i.e. 'sync'). Also, are you using config_split module, by chance?

**Comment by davidwhthomas** [comment]
Hey thanks for the reply.

We're using a custom config sync dir in `settings.php` to keep the config outside the webroot.
Not using the `config_split` module

The odd thing is, `config-import` and `config-export` has started working normally again!

Not exactly sure what changed but the good news is it appears we can import/export the config ok in Drush 9!

Thanks again for the work on the excellent drush suite, I think ok to close this issue for now.

**Comment by albertoperezdosaula** [comment]
We have the same issue, if we export the configuration, it works fine, but if after you run "drush cim", then appears deleted all files. I dont know the reason... I never have seen this in Drupal.
