### ISSUE TITLE
drush sql-sync: “The external command could not be executed due to an application error.”

### ISSUE THREAD

**Issue by 0711master** [drush-ops/drush#3293]
When I execute drush sql-sync to get a database from the server to local, I get the following error after login with ssh:

> The external command could not be executed due to an application error.

Here is the debug after the ssh login:

> Backend invoke: php
> C:/Users/x/drupal-root/vendor/drush/drush/drush.php --backend=2 --verbose --debug --uri=localhost --root=/C/Users/x/drupal-root/web  sql-conf --all 2>&1
> php C:/Users/x/drupa-root/vendor/drush/drush/drush.php --backend=2 --verbose --debug --uri=localhost --root=/C/Users/x/drupal-root/web  sql-conf --all 2>&1
> The external command could not be executed due to an application error.
> Error: no database record could be found for target @local
> Returned from hook drush_sqlsync_sql_sync_validate
> Command dispatch complete

Does anyone have an idea? I'm at my wits' end.

**Comment by weitzman** [comment]
Please use Drupal Answers for support questions.
