### ISSUE TITLE
How to override / set php options for Drush 9?

### ISSUE THREAD

**Issue by frederickjh** [drush-ops/drush#3294]
With the move to Drupal 8.4 I switched one of my sites to a site installed Drush 9. I also installed the Drush launcher.
```
Drush Launcher Version: 0.5.0
Drush Commandline Tool 9.0.0-rc1
```
I have the following environmental variables related to Drush set:
```
DRUSH_INI="/home/username/.drush/drush.ini"
DRUSH_LAUNCHER_FALLBACK="/home/username/.composer/vendor/bin/drush"
DRUSH_PHP="/opt/cpanel/ea-php71/root/usr/bin/php"
```
This is on a server where the php.ini for the cli sets `memory_limit=32M`. With Drush 8 globally installed I could use `~/.drush/drush.ini` to set `memory_limit=512M`.

I did see in issue #2934 that the drush.ini file is ignored and that that the drush launcher does not handle drush.ini  either.

I have tried unsuccessfully to run Drush 9 and increase the memory limit. Here is what I have tried using the updb to test the memory_limit=32M:

```
$ php -d memory_limit=512M ../vendor/bin/drush --php-options=memory_limit=512M
Drush Commandline Tool 9.0.0-rc1
. . .
```
It appears that **--php-options** is not a valid option with Drush 9 as it spits out the default help text after the above console output.

```
$ php -c ~/.drush/drush.ini ../vendor/bin/drush -c ~/.drush/drush.ini updb
 [error]  Drush command terminated abnormally due to an unrecoverable error.
Error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 8192 bytes) in /home/meosch/l2m.ch/releases/20171229-022429/docroot/core/lib/Drupal/Core/Extension/InfoParserDynamic.php, line 22 
 [error]  The external command could not be executed due to an application error.
```
So setting the PHP options in a file does not seem to work either. I made a copy of the default php.ini and then increased memory_limit=512M.

----

So, is there a way to set php options for Drush 9? And is is also possible to use the Drush launcher with this too?

**Comment by frederickjh** [comment]
Interestingly running:
```
php -c ~/.drush/drush.ini ../vendor/bin/drush -c ~/.drush/drush.ini php:cli
```
Then running: `phpinfo()` I see in the php info:
```
memory_limit => 512M => 512M
```
So, the php cli is seeing the php option but `drush updb` does not.

**Comment by weitzman** [comment]
Drush 9 is now out of the business of setting up your PHP environment. It got too complex to maintain this.

Drush does create subprocesses for some commands (sql-sync, updb, config-pull, ...). Those subprocesses probably dont see the -c option so the subprocess gets memory starved. Thats my guess.

**Comment by frederickjh** [comment]
Thanks @weitzman for the reply. I tried everything I could think of my greatest hope was a bash alias for php that added the php.ini via the -c option but as you said it seems the sub processes do not see it.

I was able to get the memory_limit on the VPS PHP configuration raise to an acceptable level so I am back in business. However I do hope that a solution to this for others can be found.

**Comment by weitzman** [comment]
I think the best way to do this is to insure that the [PHPRC environment variable](http://php.net/manual/en/configuration.file.php) is set to the directory containing the desired php.ini. Subprocesses get the same environment so the change persists there. 

You can set the variable just for one request. See `PHP Config` line below: 

```
~/reps/mass (develop *=) $ PHPRC=/tmp drush st
 Drupal version : 8.4.5                                                                  
 PHP config     : /tmp/php.ini                                                 
 PHP OS         : Darwin                                                       
 Drush script   : /Users/moshe.weitzman/bin/drush                              
 Drush version  : 9.2.1                                                        
```

**Comment by weitzman** [comment]
now documented in install docs

**Comment by frederickjh** [comment]
@weitzman This works on linux in a normal bash shell but not in a Cpanel bash jailedshell.

To test on both servers I created a /tmp/php.ini file that sets the _memory_limit = 128M_.

Normal Linux User:
```bash
$ PHPRC=/tmp env | grep PHPRC
PHPRC=/tmp
$ PHPRC=/tmp drush st
 Drupal version : 8.4.4                                                      
 Site URI       : default                                                    
 DB driver      : mysql                                                      
 DB hostname    : db                                                         
 DB port        : 3306                                                       
 DB username    : user                                                       
 DB name        : default                                                    
 PHP binary     : /usr/bin/php7.1                                            
 PHP config     : /tmp/php.ini                                               
 PHP OS         : Linux                                                      
 Drush script   : /home/fhenderson/docker/l2mch/vendor/bin/drush             
 Drush version  : 9.1.0                                                      
 Drush temp     : /tmp                                                       
 Drush configs  : /home/fhenderson/docker/l2mch/vendor/drush/drush/drush.yml 
                  /home/fhenderson/docker/l2mch/drush/drush.yml              
 Drupal root    : /home/fhenderson/docker/l2mch/docroot                      
 Site path      : sites/default                                              
$ drush --version
Drush Launcher Version: 0.5.1
Drush Commandline Tool 9.1.0
$
```
Cpanel Jailed shell user
```bash
$ PHPRC=/tmp env|grep PHPRC
PHPRC=/tmp
$ PHPRC=/tmp drush st
$
```

The `drush st` command returned **no output in the shell**. I then tried the direct path to Drush 9 in the Drupal 8 project.
```bash
$ PHPRC=/tmp vendor/bin/drush st

Fatal error: Uncaught Error: Call to undefined function Drush\Preflight\ctype_alpha() in /home/meosch/l2m.ch/releases/20180205-090119-live-0.2.0/vendor/drush/drush/src/Preflight/ArgsRemapper.php:49
Stack trace:
#0 /home/meosch/l2m.ch/releases/20180205-090119-live-0.2.0/vendor/drush/drush/src/Preflight/ArgsRemapper.php(32): Drush\Preflight\ArgsRemapper->checkRemap('st', false)
#1 /home/meosch/l2m.ch/releases/20180205-090119-live-0.2.0/vendor/drush/drush/src/Preflight/ArgsPreprocessor.php(55): Drush\Preflight\ArgsRemapper->remap(Array)
#2 /home/meosch/l2m.ch/releases/20180205-090119-live-0.2.0/vendor/drush/drush/src/Preflight/Preflight.php(163): Drush\Preflight\ArgsPreprocessor->parse(Array, Object(Drush\Preflight\PreflightArgs))
#3 /home/meosch/l2m.ch/releases/20180205-090119-live-0.2.0/vendor/drush/drush/src/Preflight/Preflight.php(229): Drush\Preflight\Preflight->preflightArgs(Array)
#4 /home/meosch/l2m.ch/releases/20180205-090119-live-0.2.0/vendor/drush/drush/src/Runtime/Runtime.php(58): Drush\Preflight\Preflight->prefl in /home/meosch/l2m.ch/releases/20180205-090119-live-0.2.0/vendor/drush/drush/src/Preflight/ArgsRemapper.php on line 49
$ drush --version
Drush Launcher Version: 0.5.0
Drush Commandline Tool 9.0.0-rc1
$
```

Let me know if there is any more information that I can supply or test I can run to help fix this.

**Comment by frederickjh** [comment]
Do you think the version of the Drush command line tool has anything to do with it? Just saw that one is an RC and the other is a stable release version.

**Comment by weitzman** [comment]
Seems like the original question has now been answered.

could you edit [this line](https://github.com/drush-ops/drush/blob/fa81aff9b0c9e2cca7119f356dd8aedb9858fa11/src/Preflight/ArgsRemapper.php#L50) and add a \`\ before ctype_alpha. that may fix it. I'm not clear when that's needed since [php has a fallback policy](http://php.net/manual/en/language.namespaces.fallback.php).

**Comment by weitzman** [comment]
And yeah, 9.0.0-rc1 is quite old. Tha could be contributing to the problem. Hard to say.

**Comment by frederickjh** [comment]
@weitzman I made the modification that you suggested above adding `/` before `ctype_alpha`, so that the line looks like this:
```php
if (!$sawCommand && /ctype_alpha($arg[0])) {
```

I also updated Drush before:
```
Drush Launcher Version: 0.5.0
Drush Commandline Tool 9.1.0
```
However still got no ouput when I  run `PHPRC=/tmp drush st`.

**Comment by weitzman** [comment]
slash needs to go in other direction - `\`

**Comment by frederickjh** [comment]
Sorry, I tried it again with the line `if (!$sawCommand && \ctype_alpha($arg[0])) {` and still no output.

**Comment by weitzman** [comment]
Sounds like your PHP does not have the [ctype extension](http://php.net/manual/en/book.ctype.php). Thats quite rare.

**Comment by bioshazard** [comment]
I landed here searching for how to deal with this in Drush 9 and settled on this so I didn't have to maintain a physical file for my override:

```
php -c <(echo "sendmail_path=$(which true)")  /.../vendor/drush/drush/drush.php ev 'return ini_get("sendmail_path")'
```

**Comment by dabley** [comment]
Note that if you simply want to modify a few of the php.ini parameters, then rather than using the PHPRC environment variable to specify a completely new php.ini file, there's a simple way to specify an additional '.ini' file which contains just your customisations.

After php has loaded the php.ini file located in the directory indicated by the PHPRC
environment variable (or indicated by other means), it then scans for other .ini files located in one or more other directories. You can easily get php to search an extra directory of your choice, by setting the PHP_INI_SCAN_DIR environment variable.

For example, create a directory /home/myname/mydrush, and in this put a file named drush.ini, containing the custom initialisation commands you require. Then you can call drush with:

    $ PHP_INI_SCAN_DIR=:/home/myname/mydrush drush <drush command>

The colon at the front of the assignment causes the directory you specify to be added to the end of the list of additional directories that php searches looking for .ini files when it starts up. (In Ubuntu 18.04, for example, php 7.3 will scan for additional .ini files in the directory /etc/php/7.3/cli/conf.d)

You can get a confirmation of exactly which .ini files php is loading using a command such as:

    $ PHP_INI_SCAN_DIR=:/home/myname/mydrush php --ini

Note that with php 7.3.16, this command will show:

> Scan for additional .ini files in: :/home/myname/mydrush

This is misleading - it doesn't list the names of the other "additional" directories that are scanned prior to your custom one. But you can easily reassure yourself that they *are* in fact being scanned, because the command goes on to list "Additional .ini files parsed: ", and there you'll see the complete list of .ini files loaded.

For more on PHP_INI_SCAN_DIR, see https://www.php.net/manual/en/configuration.file.php

**Comment by weitzman** [comment]
Great tip! I added. link to it from the comment above thats linked in the install docs.

**Comment by StudioVDS** [comment]
I can't get this to work, hope you can help me with this:
First I do this: PHPRC=~/tmp drush st
Getting this: `PHPRC=/home/domain/tmp` as output

Then when I try `drush st` I get this:
`[preflight] The following restricted PHP modes have non-empty values: {disable_functions}. This configuration is incompatible with drush.  {Please check your configuration settings in /home/domain/tmp/php.ini or in your drush.ini file; see examples/example.drush.ini for details.}`

So it looks like it is looking at the right php.ini file but still I get this message even though have removed all disable_functions from this specific file. What am I doing wrong?

**Comment by dabley** [comment]
> First I do this: PHPRC=/tmp env | grep PHPRC

This only causes the value of PHPRC to be set for the single command "env". If you want the setting of PHPRC to apply when you call drush, you either need to do the setting on the same line where you invoke drush, e.g.

``` $ PHPRC=/tmp drush [drush command]```

Or, you can make the setting persist in your current shell environment by doing:

```
$ export PHPRC=/tmp
$ drush [drush command]
```

**Comment by StudioVDS** [comment]
Thanks, but unfortunately this doesn't work as expected:
`$ PHPRC=~/tmp drush --version`

Outputs:

`Drush Launcher Version: 0.6.0
 [preflight] The following restricted PHP modes have non-empty values: {disable_functions}. This configuration is incompatible with drush.  {Please check your configuration settings in /home/domain/tmp/php.ini or in your drush.ini file; see examples/example.drush.ini for details.}
`
So it does find my custom php.ini file but still doesn't work. And when removing the Disable Functions via Direct Admin (just for testing) it does work...?

**Comment by dabley** [comment]
Hi StudioVDS, 
In the file /home/domain/tmp/php.ini, what do you have for the setting of disable_functions? And can you also try:
```$ PHPRC=/tmp php --ini```
and check to see what additional ini files are being loaded. Maybe one of those is changing the setting of disable_functions?
If you are only wanting to change the value of disable_functions, you may find it easier to just load an additional ini file using the PHP_INI_SCAN_DIR variable, as I explained in an earlier comment: https://github.com/drush-ops/drush/issues/3294#issuecomment-618962852.

**Comment by StudioVDS** [comment]
Hi,

I'm using the drush.ini file I used for Drush 7. You can see it [here](https://www.dropbox.com/s/iawm2yskhvmyqbc/php.txt?dl=0).

When I use `php --ini` I get this:
```
Configuration File (php.ini) Path: /opt/alt/php73/etc
Loaded Configuration File:         /home/domain/tmp/php.ini
Scan for additional .ini files in: /opt/alt/php73/link/conf
Additional .ini files parsed:      /opt/alt/php73/link/conf/alt_php.ini
```

But still I get this message:
``` [preflight] The following restricted PHP modes have non-empty values: {disable_functions}. This configuration is incompatible with drush.  {Please check your configuration settings in /home/domain/tmp/php.ini or in your drush.ini file; see examples/example.drush.ini for details.}```

About the `PHP_INI_SCAN_DIR` option. This does work. A question about this. I added:
```export PHP_INI_SCAN_DIR=:~/tmp``` to my .bash_profile file. Now the custom php.ini file is only loaded when using the terminal, it's not overwriting the regular php.ini file the server is using?

**Comment by dabley** [comment]
Hi StudioVDS,
I'm guessing that before calling ```php --ini``` you had set the environment variable PHPRC to /tmp, and similarly before you invoked ```drush```, and that the ini file you cited is the one that's located in /home/domain/tmp/php.ini?
The output from ```php --ini``` shows that the file /opt/alt/php73/link/conf/alt_php.ini is loaded *after* your custom ini file, so there's a possibility that this might be altering the value of disable_functions, and setting it to something that drush doesn't like. You might like to check this. 
If you use PHP_INI_SCAN_DIR to add your custom file to the *end* of the list of ini files that are loaded, then you can avoid this risk.

I'm pretty confident that your .bash_profile file is not being loaded by your webserver, but if you want to be sure, just make a short php script that runs phpinfo(); put it in your docroot, and load it through a web browser. This will show you what ini files are loaded. (Delete the script when you're done - it can be a security risk otherwise.)

**Comment by AlexSkrypnyk** [comment]
1. Create an ini file in your repo (has to be in a sub-dir dedicated to ini files):
```shell
mkdir drush/ini
echo "memory_limit=2G;" >> drush/ini/cli.ini
```
2. Include it into the call, while preserving the existing values:
```shell
PHP_INI_SCAN_DIR="${PHP_INI_SCAN_DIR}:<path/to/repo>/drush/ini" drush <command>
```
3. Test it
```shell
PHP_INI_SCAN_DIR="${PHP_INI_SCAN_DIR}:drush/ini" drush php:eval "phpinfo();"
```
The `memory_limit` should have a value of `2G` in the output.
If your `PHP_INI_SCAN_DIR` had other settings - those values should appear in the output as well.
