### ISSUE TITLE
Drush 9; Argument 'en' is always replaced with 'pm:enable'

### ISSUE THREAD

**Issue by TessaBakker** [drush-ops/drush#3295]
If a Drush 9 commands allows arguments, the argument 'en' will be replaced with its full command name pm:enable. In this way it isn't possible to create an argument that accepts the language code 'en'.

Drush 8 doesn't have this issue.

Some test cases:
```Shell
$ drush @site_alias en 'en'
[error]  Unable to install modules pm:enable due to missing modules pm:enable.

$ drush @site_alias pm:enable 'en'
[error]  Unable to install modules pm:enable due to missing modules pm:enable.
```

**Comment by greg-1-anderson** [comment]
😢 Thought we fixed this. Thanks for reporting.

**Comment by weitzman** [comment]
What exact version of drush? See composer show command.

**Comment by TessaBakker** [comment]
@weitzman c905926 a.k.a. 9.0.0-rc2

**Comment by weitzman** [comment]
Our attempted fix was https://github.com/drush-ops/drush/pull/3066. That should help identify where we went wrong.

**Comment by Sutharsan** [comment]
It's caused by typo's in #3066

**Comment by weitzman** [comment]
Lets talk in the PR
