### ISSUE TITLE
Errors after PHP5.5 update (on windows)

### ISSUE THREAD

**Issue by majestixx** [drush-ops/drush#33]
On each executed drush command 3 error messages appear:

Strict Standards: Declaration of DrushMakeProject_Library::getTranslations() sho
uld be compatible with DrushMakeProject::getTranslations($project_directory) in
C:\Program Files (x86)\drush\commands\drush_make\drush_make.project.inc on line 353

Strict Standards: Declaration of DrushMakeProject_Library::recurse() should be c
ompatible with DrushMakeProject::recurse($path) in C:\Program Files (x86)\drush\
commands\drush_make\drush_make.project.inc on line 353

Strict Standards: Declaration of DrushMakeProject_Profile::buildPath() should be
 compatible with DrushMakeProject::buildPath() in C:\Program Files (x86)\drush\c
ommands\drush_make\drush_make.project.inc on line 371

The script is executed on windows and PHP 5.5.3. The neweste drush version from http://www.drush.org/drush_windows_installer is installed.

**Comment by sniperBlank** [comment]
no one can solve this problem?

**Comment by greg-1-anderson** [comment]
Drush support for Windows has always been thin, unfortunately. Closing because php 5.5 is EOL.
