### ISSUE TITLE
Prompt for a program to open drush.launcher file on windows

### ISSUE THREAD

**Issue by v-tsymbalistyi** [drush-ops/drush#3301]
This looks to be this issue: #1674
It seems to be closed but can't seem to figure out the version of drush which contains the fix.

I'm having troubles with 8.1.15 drush version and 8.4.3 drupal version.

**Comment by v-tsymbalistyi** [comment]
Guys?

**Comment by weitzman** [comment]
Please try launching with `drush.bat` instead of `drush`. That would work for simple commands. Might not work for commands that fork new processes.

**Comment by liquidcms** [comment]
2 years later.. same issue :(

**Comment by liquidcms** [comment]
nvm.. figured it out.. drush 8 doesn't work... removed with composer and installed drush 7 instead.. works fine. :)
