### ISSUE TITLE
auto clear cache after work with modules

### ISSUE THREAD

**Issue by landsman** [drush-ops/drush#3312]
Hi,

I think that automatic clearing of cache - `drush cr` could be called after command like: `drush en xy` or `drush pmu xy` by auto. Because without clearing cache we can get some exceptions to cli from old state of compiled DI container.

What you think?

**Comment by weitzman** [comment]
The design is that this is not needed. Drupal or Drush should be handling this already. Please provide a reproducible use case where thats not so.
