### ISSUE TITLE
Using ssh-options on CLI leads to fatal error

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#3313]
I have traced the problem to Symfony looking at earlier transformation of ssh-options to `Dssh.options=-R 9000:localhost:9000` in \Symfony\Component\Console\Input\ArgvInput::hasParameterOption. That token looks like the user is requesting `help` command with the -h option.

```
~/reps/mass (DP-6496-experimental_build_speed *=) $ drush --ssh-options="-R 9000:localhost:9000" -v @prod ssh
PHP Fatal error:  Uncaught Error: Call to undefined method Consolidation\AnnotatedCommand\AnnotatedCommand::setCommand() in /Users/moshe.weitzman/reps/mass/vendor/symfony/console/Application.php:407
Stack trace:
#0 /Users/moshe.weitzman/reps/mass/vendor/symfony/console/Application.php(546): Symfony\Component\Console\Application->get('ssh')
#1 /Users/moshe.weitzman/reps/mass/vendor/drush/drush/src/Application.php(206): Symfony\Component\Console\Application->find('ssh')
#2 /Users/moshe.weitzman/reps/mass/vendor/drush/drush/src/Application.php(191): Drush\Application->bootstrapAndFind('ssh')
#3 /Users/moshe.weitzman/reps/mass/vendor/symfony/console/Application.php(190): Drush\Application->find('ssh')
#4 /Users/moshe.weitzman/reps/mass/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/moshe.weitzman/reps/mass/vendor/drush/drush/src/Runtime/Runtime.php(111): Symfony\Component\C in /Users/moshe.weitzman/reps/mass/vendor/symfony/console/Application.php on line 407

Fatal error: Uncaught Error: Call to undefined method Consolidation\AnnotatedCommand\AnnotatedCommand::setCommand() in /Users/moshe.weitzman/reps/mass/vendor/symfony/console/Application.php on line 407
```

**Comment by greg-1-anderson** [comment]
What does `ssh @prod @self` mean? Should this have just been `ssh @prod`?

**Comment by weitzman** [comment]
I made a careless edit before. The correct command is now in the log.

**Comment by weitzman** [comment]
Actually, you can reproduce this with just a global Drush and no alias - `./drush st --ssh-options="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"`

**Comment by greg-1-anderson** [comment]
Note that `--ssh-options` is converted into `-Dssh.options="-R 9000:localhost:9000"`, which should assign `ssh.options="-R 9000:localhost:9000"` to the `-D` short option, but runs up against https://github.com/symfony/symfony/issues/25825, which makes Symfony think that `-h` is defined.

**Comment by weitzman** [comment]
We have worked around this in Drush. Hopefully the workaround can be removed soon. Follow the symfony/symfony issue for updates.

**Comment by ethanbb** [comment]
Should the workaround in DrushArgvInput.php be removed now that the symfony issue is closed?
