### ISSUE TITLE
updatedb fails to run updates when status checks fail

### ISSUE THREAD

**Issue by rbayliss** [drush-ops/drush#3316]
Running `drush updatedb -y` on Drush 9.x-dev fails to run update hooks when a status check fails.  The command still returns 0 overall.  For example, if the public files directory is not writable, I see:

```
 [error]  The webserver needs to be able to write to the public files directory (public://). Please check your server configuration and try again. 
```
No update hooks are run after this message.  When I comment out the failing status check, update hooks appear and run fine.  For context, this is during an 8.3 => 8.4 update.

**Comment by weitzman** [comment]
I would like to see an option which controls whether to fail on status cghecks. the option should default to false. if the option is false, false, updates should run.

**Comment by pfrenssen** [comment]
Something like `--stop-on-failed-status-check`?

**Comment by weitzman** [comment]
Fixed by a confirmation prompt asking user "Requirements error found. Do you wish to proceed"
