### ISSUE TITLE
Drush extremly slow in windows 10

### ISSUE THREAD

**Issue by arunavak111** [drush-ops/drush#3317]
I have installed drush 8 using composer in my windows machine. But it seems like extermly slow in my machine. drush cache clear is taking morethan 30min to execute. if through website performance page it only takes 1min. I couldn't identify whats wrong with this.

Is there any specific configuration need to be done for windows machine?

**Comment by weitzman** [comment]
No specific configuration. Please use Drupal Answers for support questions.
