### ISSUE TITLE
Drush\Sql\SqlException' with message 'Unable to find a matching SQL Class.

### ISSUE THREAD

**Issue by jaubinr** [drush-ops/drush#3318]
I'm trying to run  `drush sql-sync @bd.unit @bd.devd` and I keep getting this error message `Unable to load class Drush\Sql\Sql                                                                                                                                                                  [error]
exception 'Drush\Sql\SqlException' with message 'Unable to find a matching SQL Class. Drush cannot find your database connection details.' in /usr/local/src/drush/commands/sql/sql.drush.inc:597   [error]
Stack trace:
#0 /usr/local/src/drush/commands/sql/sql.drush.inc(274): drush_sql_get_class()
#1 [internal function]: drush_sql_dump()
#2 /usr/local/src/drush/includes/command.inc(359): call_user_func_array('drush_sql_dump', Array)
#3 /usr/local/src/drush/includes/command.inc(210): _drush_invoke_hooks(Array, Array)
#4 [internal function]: drush_command()
#5 /usr/local/src/drush/includes/command.inc(178): call_user_func_array('drush_command', Array)
#6 /usr/local/src/drush/lib/Drush/Boot/BaseBoot.php(62): drush_dispatch(Array)
#7 /usr/local/src/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 /usr/local/src/drush/drush.php(11): drush_main()
#9 {main}
`

Here my setting.php
`$databases = array (
  'default' => array (
    'default' =>
    array (
      'database' => 'BD',
      'username' => '',
      'password' => ''
      'host' => 'localhost',
      'port' => '97',
      'driver' => 'mysql',
      'prefix' => '',
      'charset' => 'utf8mb4',
      'collation' => 'utf8mb4_general_ci',
    ),
  ),
);
`
I've ask our organic analyst here and He's has clueless then me. I would really appreciate your help.
Thank you

**Comment by weitzman** [comment]
Please use Drupal Answers for support questions.
