### ISSUE TITLE
Use MySQL Interactive mode?

### ISSUE THREAD

**Issue by JPustkuchen** [drush-ops/drush#332]
From: https://drupal.org/node/2119513

<p>Firstofall, there is no connection to interactive commands as described in <span class="project-issue-issue-link project-issue-status-info project-issue-status-7"><a href="/node/543550" title="Status: Closed (fixed)">#543550: Drush interactive mode</a></span>
.</p>

<p>My suggestion is to use the "MYSQL_CLIENT_INTERACTIVE" client_flag of <a href="http://php.net/manual/de/function.mysql-connect.php">http://php.net/manual/de/function.mysql-connect.php</a></p>

<p>The reason is, that drush is mostly used for "bigger" jobs, sometimes with longer idle times or confirmation messages (yes / no).</p>

<p>In some (e.g. shared) hosting environments with low mysql "wait_timeout" it then happens that the action is being aborted by the server with a "MySQL Server has gone away" message. (see: <a href="https://drupal.org/node/186384">https://drupal.org/node/186384</a>)</p>

<p>So it might be an idea to use MYSQL_CLIENT_INTERACTIVE as a proper solution and better environment for drush, because it is indeed interactive.</p>

<p>What's your oppinion about that? I just wanted to mention this idea and get your feedback.</p>

<p>Thanks a lot :)</p>

**Comment by greg-1-anderson** [comment]
Sorry that no one looked at this idea. It looks like mysql_connect is obsolete in PHP 7. I'm not sure if there is an equivalent to MYSQL_CLIENT_INTERACTIVE in the mysqli driver. In any event, Drush relies on Drupal to bootstrap and establish the mysql connection.
