### ISSUE TITLE
Drush sql-dump not working with 'extra' arguments with Postgres

### ISSUE THREAD

**Issue by kalpaitch** [drush-ops/drush#3321]
To replicate: `sql-dump --skip-tables-list=cache_* --extra='-O -x'` with postgress.

The extra arguments only work with pg_dump utility command (we want to exclude dumping with ownership).

However, drush will also pass these extra arguments to psql when it does the select query to get a list of all the tables available to be dumped. Because these aren't options for psql it will return a failure and therefore just dump _all_ the tables, including the ones we want to skip.

If we're passing extra arguments to `sql-dump` it doesn't seem right to also pass them to `psql` command  that drush also runs, or at least if it does there should be some way to validate that these are actually valid arguments.

**Comment by kalpaitch** [comment]
One of the main issues is in the main query constructor which states in the comments that drush_get_options() should be avoided, but then proceeds to use it in the method - https://github.com/drush-ops/drush/blob/8.x/lib/Drush/Sql/SqlBase.php#L167

**Comment by kalpaitch** [comment]
https://github.com/drush-ops/drush/pull/3328

**Comment by kalpaitch** [comment]
Related to - https://github.com/drush-ops/drush/issues/2079

**Comment by kalpaitch** [comment]
"So we just need two more changes - line 437 of sql.drush.inc and lines 98-99 of Sqlpgsql.php" that would allow us to pass in the extras from the sql-dump command _only_ and override the query_extras just for that command.

**Comment by weitzman** [comment]
See recent pg fixes and post here if still not working.

**Comment by kalpaitch** [comment]
I can confirm this is still an issue with Drush 10.6.2.

**Comment by kalpaitch** [comment]
This is the generated query, as you can see the `-O` should not be included in this query in `SqlPgsql::listTables()`:

```
psql -q --dbname=xxx --host=xxx --port=xxx --username=xxx  -O -x -w -c 'SELECT tablename FROM pg_tables WHERE schemaname="public";'
```

**Comment by gitressa** [comment]
[Drush 10.6.2](https://github.com/drush-ops/drush/releases/tag/10.6.2) is from 15 Dec 2021, so perhaps you can try the latest version 11.1.1, and check if it works in that version?

**Comment by kalpaitch** [comment]
> [Drush 10.6.2](https://github.com/drush-ops/drush/releases/tag/10.6.2) is from 15 Dec 2021, so perhaps you can try the latest version 11.1.1, and check if it works in that version?

Still same query generated. Same result.

**Comment by kalpaitch** [comment]
The only solution I have to date is to pass the query_extras into the query function as a parameter, thus allowing `$this->getOption('extra', $this->queryExtra)` to be overridden on a query by query basis. I have an old patch against an old drush version as an example, if you're open to this approach then I can open a new branch, but essentially the query extras for `sql:dump` must be separated from the query extras for all other psql queries:

```
diff --git a/lib/Drush/Sql/SqlBase.php b/lib/Drush/Sql/SqlBase.php
index 0d8871ce..e828a8ba 100644
--- a/lib/Drush/Sql/SqlBase.php
+++ b/lib/Drush/Sql/SqlBase.php
@@ -142,7 +142,7 @@ class SqlBase {
    * @return
    *   TRUE on success, FALSE on failure
    */
-  public function query($query, $input_file = NULL, $result_file = '') {
+  public function query($query, $input_file = NULL, $result_file = '', $query_extras = '') {
     $input_file_original = $input_file;
     if ($input_file && drush_file_is_tarball($input_file)) {
       if (drush_shell_exec('gzip -d %s', $input_file)) {
@@ -152,6 +152,9 @@ class SqlBase {
         return drush_set_error(dt('Failed to decompress input file.'));
       }
     }
+    
+    // If no query_extras are passed in the use the default options from cmd or query base.
+    $query_extras = !empty($query_extras) ? $query_extras : drush_get_option('extra', $this->query_extra);
 
     // Save $query to a tmp file if needed. We will redirect it in.
     if (!$input_file) {
@@ -164,7 +167,7 @@ class SqlBase {
       $this->command(),
       $this->creds(),
       $this->silent(), // This removes column header and various helpful things in mysql.
-      drush_get_option('extra', $this->query_extra),
+      $query_extras,
       $this->query_file,
       drush_escapeshellarg($input_file),
     );
diff --git a/lib/Drush/Sql/Sqlpgsql.php b/lib/Drush/Sql/Sqlpgsql.php
index e8945c73..81ceabfe 100644
--- a/lib/Drush/Sql/Sqlpgsql.php
+++ b/lib/Drush/Sql/Sqlpgsql.php
@@ -96,7 +96,9 @@ class Sqlpgsql extends SqlBase {
   }
 
   public function listTables() {
-    $return = $this->query(PSQL_SHOW_TABLES);
+    // listTables should only ever respect the query_extras of the base sql class
+    // and not the cmd extras @see https://github.com/drush-ops/drush/issues/3321
+    $return = $this->query(PSQL_SHOW_TABLES, NULL, '', $this->query_extra);
     $tables = drush_shell_exec_output();
     if (!empty($tables)) {
       return $tables;
```

**Comment by kalpaitch** [comment]
Ok, I'm sorry for all the recent comments, I realise the `extra-dump` option now exists for this purpose, although I could not see this by looking at this ticket.... https://www.drush.org/latest/commands/sql_dump/
