### ISSUE TITLE
multisite commands

### ISSUE THREAD

**Issue by landsman** [drush-ops/drush#3323]
Hi,

I want using drush for all multisites like:
- `drush @sites sset system.maintenance_mode 0 -y`
- `drush @sites config-set system.performance css.preprocess 1 -y`
- `drush @sites config-set system.performance js.preprocess 1 -y`

but these commands not working well. Can you help me with this please?

**Comment by weitzman** [comment]
Thats no longer a feature in Drush9. Is that the version you are using?

**Comment by weitzman** [comment]
You will want to write a wrapper script (and share it back here!) that iterates over subdirs of /sites and then calls drush like `drush #subdir [command-name]`. That might work. If not, pass a --uri that you derive from subdir name."
