### ISSUE TITLE
Drush 9 support drupal7?

### ISSUE THREAD

**Issue by mfechner** [drush-ops/drush#3324]
Dear all,

I maintain the drush port for FreeBSD and I would like to ask if drush 9 does support drupal 7 or was support for it dropped?

**Comment by weitzman** [comment]
Dropped. Drupal 7 users should continue to use Drush 8, which is still
supported.

**Comment by mfechner** [comment]
Thanks a lot for this information.
Maybe that could be put into the documentation, so it will be clear which drush version is supporting which drupal version?

**Comment by weitzman** [comment]
Its there already http://docs.drush.org/en/master/install/#drupal-compatibility

**Comment by mfechner** [comment]
@weitzman thanks a lot, I will then prepare a second port for drush9 to not break drupal7 users.

**Comment by greg-1-anderson** [comment]
@mfechner The work to support Drush 9 for Drupal 7 users is tractable. However, there are hundreds and hundreds of contrib modules with Drush extensions. All of these (of those still needed by a given user) would have to be ported to Drush 9 before a Drupal 7 user could step away from Drush 8. If that work isn't going to happen in a meaningful way, then it seems unlikely that we will want to maintain Drupal 7 support in Drush 9.

**Comment by austin-brian** [comment]
It seems to me that the Drush compatibility chart has been inaccurate for months, leading people to install Drush 9.

the Drush 8 line at:
http://docs.drush.org/en/master/install/#drupal-compatibility

says it supports D6, D7, D8.3- 

But since Drush 8.1.13 or so, it has supported 
D6, D7, D8.4+

Am I wrong, and if I'm correct, why has no one updated that chart. It makes it appear that you cannot use Drush 8 with Drupal 8.4.x

**Comment by weitzman** [comment]
You are wrong. Drush8 "happens to work" with Drupal 8.4+. Its not a supported combination. See various discussions in this queue for more info.

**Comment by chx** [comment]
Care to point us to that info? I am seriously considering forking drush 8 to continue support Drupal 8 until Drupal 9 is released and Drupal 7 is EOL as the mixed setup those who work on a variety of sites are forced to use at the moment is maddenningly frustrating.
