### ISSUE TITLE
Executing drush result in PHP Fatal error

### ISSUE THREAD

**Issue by Aporie** [drush-ops/drush#3329]
Hello,

I'm trying to install drush per project as recommanded in the doc. I can't get drush working even with fresh install.

Here are the steps I did : 

**For drupal** 
`composer create-project drupal/drupal public_html`
In public_html : 
`composer require drush/drush`

**For drush launcher** 

Just following the doc and downloaded it in /usr/bin which is in my $PATH

**Result**
```
drush --version
Drush Launcher Version: 0.5.1
PHP Fatal error:  Uncaught Error: Class 'Drush\Config\Environment' not found in /home/orao/web/folder/public_html/vendor/drush/drush/drush.php:57
Stack trace:
#0 /home/orao/web/folder/public_html/vendor/drush/drush/includes/preflight.inc(17): require()
#1 phar:///usr/bin/drush/bin/drush.php(137): drush_main()
#2 /usr/bin/drush(10): require('phar:///usr/bin...')
#3 {main}
  thrown in /home/orao/web/folder/public_html/vendor/drush/drush/drush.php on line 57
```

Before I was getting the error below and just did a complete reinstall trying to solve the issue and get the one above ...

```
Drush Launcher Version: 0.5.1
PHP Fatal error:  Class 'Psr\Log\AbstractLogger' not found in /home/orao/web/folder/public_html/vendor/drush/drush/lib/Drush/Log/Logger.php on line 31
```
Drush version in drupal project result in : 

```
vendor/bin/drush --version
Drush Commandline Tool 9.0.0
```

**Comment by weitzman** [comment]
Please use the composer project thats linked from step 1 at http://docs.drush.org/en/master/install/. Thats the de facto standard.

**Comment by Aporie** [comment]
Yeah but actually that was the doc I was following and running drush init result in the error above ...

**Comment by weitzman** [comment]
```
composer create-project drupal/drupal public_html
composer require drush/drush
```

Neither of those comes from drush install docs or drupal-project docs.

I would omit the launcher to start and call `vendor/bin/drust st` to start. The launcher is just a convenience.

**Comment by Aporie** [comment]
[Drupal doc](https://www.drupal.org/docs/develop/using-composer/using-composer-to-manage-drupal-site-dependencies)

It's just the option B, as the option A comes with a lot of sub dir tree that doesn't fit my needs.

Nevermind, I'll probably use /vendor/bin/drush to run drush as I can't setup the launcher to work properly.

**Comment by weitzman** [comment]
The launcher presumes that you are using the drupal-project filesystem layout

**Comment by Aporie** [comment]
Ok thanks so it should probably be written somewhere in the doc.

**Comment by ejazulhaqcse** [comment]
Thanks, i have resolved Drush  Installation issue on windows 10 + Xampp 
========================   Drush For  Drupal ========================

What is Drush ?
Ans :  Drush is a command line shell and scripting interface for Drupal, and it is work like
          Laravel-Artisan, and Angular CLi etc.
           It is very Help-full for fast development on Drupal.
          Official Website  ->    http://www.drush.org/
          Official composer repository   ->   https://packagist.org/packages/drush/drush#dev-master
          Official Drupal Repository ->  https://www.drupal.org/project/drush
     
What is the Installation Process ?
Ans : There is following steps.

1. Step
Install new and latest version of composer 

 2. Step 
Run in vscode  Terminal

composer global require drush/drush:9.x-dev
check the installation  in terminal  via following command 
drush version

For more details visit 
https://packagist.org/packages/drush/drush#dev-master
And also helpful
http://docs.drush.org/en/master/

 3. Step
 Visite following link and see Drush All conads details and documentation
https://drushcommands.com/drush-9x/
https://www.drupal.org/docs/user_guide/en/prevent-cache-clear.html

How can see drush commands list in terminal ?
Just type in vscode terminal in project dir
Drush  and enter
So all commands will be listed with summary   

Uninstallation process for  Drush ?
Just change in command ‘require’ to ‘remove’
composer global remove drush/drush:9.x-dev
 
How can resolve Drush Errors ?
Run command in vscode terminal
Composer require drush/drush

**Comment by mlncn** [comment]
This error happened to us on a test site after an incomplete deploy, or at least it was fixed after a full deploy (which hadn't been completing because the drush-based backup step was failing with this error!)— after a full deploy of the latest Drush 10 was included with the site via Composer as usual.
