### ISSUE TITLE
Handle --fields better in output formatters that do not explicitly support fields.

### ISSUE THREAD

**Issue by bjeavons** [drush-ops/drush#333]
The drush site-alias command with fields flag does not work as expected.

According to the help for sa, --fields should allow specifying the field to print.

Example, for site alias

```
$aliases["example.env"] = array (
  '#name' => 'example.env',
  'site' => 'example',
  'env' => 'env',
  'root' => '/var/www/html/example.env/docroot',
  'remote-host' => 'host.example.com',
  'remote-user' => 'exampleuser',
);
```

calling drush @site.env --fields=remote-host should print host.example.com but it does not.

drush 6.2.0

**Comment by hansfn** [comment]
So, the consensus is that fields shouldn't be supported for formats like json, yaml and similar? In my opinion they should, and it shouldn't be that hard to remove (unset) the non-selected fields. I would like to know, since I plan to submit a documentation patch for the field support for different output formats.

**Comment by greg-1-anderson** [comment]
Maybe fields could be supported for yaml et. al.; someone would need to submit a PR, though.

**Comment by weitzman** [comment]
I also would like to see --fields support for json and yaml.

**Comment by 4garfield** [comment]
do you have any plan to support the fields output for json,yaml?
till now, the fields output is still only supported by --format=csv but there is still no document

**Comment by greg-1-anderson** [comment]
The Drush output formatters code has a very messy "middle layer" that needs some work. It's possible that this enhancement could be made without touching that part of the code, but for my part, I have decided to defer all output formatter work in favor of the rewrite at https://github.com/consolidation-org/output-formatters. I was actually considering this feature in that module a short time ago, but as of yet it is unimplemented.

PRs here or there would be welcome.

**Comment by greg-1-anderson** [comment]
This is now supported in the [output-formatters](https://github.com/consolidation-org/output-formatters) project.
