### ISSUE TITLE
How to "detect" a site’s URI based on the current working directory?

### ISSUE THREAD

**Issue by torotil** [drush-ops/drush#3345]
Hi I’d really like to make `drush` detect the correct uri based on the current working directory (without extra arguments to `drush`).

Currently I’m using #2580 with a site-specific `drushrc.php` to achieve this. The maintainers of drush seem not in favor of that solution though (see #1965 and #2055).

As I’m not willing to maintain a drush fork ;) I’m looking for another way to achieve this. Any suggestions?

**Comment by weitzman** [comment]
Are you asking about drush9 or drush8? please describe your setup a bit more.

**Comment by torotil** [comment]
This is about a Drupal7 multi-site setup. I’m happy to use whatever drush version works. Up to now I have used a patched version of drush8.

A basic test-setup would look like this:

* One Drupal7 root in `/drupal-root`
* Two sites (configured via `sites.php`):
  * `default.example.com` pointing to `sites/default`
  * `a.example.com` pointing to `sites/a`

What I want to achieve is that the correct `-l` argument is automatically set based on the current shell working directory. In an imaginary shell session this would look like:
```
$ cd /drupal-root
$ drush status | grep URI
Site URI: https://default.example.com
$ cd sites/a
$ drush status | grep URI
Site URI: https://a.example.com
```

With the patch in #2580 I can do that when each sites folder contains a `drushrc.php` with a line like `$options['l'] = 'https://default.example.com';`

**Comment by weitzman** [comment]
Thanks for elaborating ... I dont have a suggestion offhand.

**Comment by weitzman** [comment]
My understanding is that your drushrc.php approach should work with drush8. But we have certainly received reports of it not working - #2285. If that issue matches this one, please close this as a dupe.

No solution exists yet for drush9

**Comment by torotil** [comment]
@weitzman As far as I understood #2285 is something completely different. I only have one global drush installation but I want it to detect and use the correct `site/*/drushrc.php` early enough to be able to configure the site url there as described in the imaginary shell session above. [… or any other means to achieve the same goal.]

**Comment by torotil** [comment]
Ok never mind. It seems that it does indeed work with 8.1.9.

**Comment by weitzman** [comment]
Drush9 equivalent #3968
