### ISSUE TITLE
Launch browser from Vagrant Box with drush user-login?

### ISSUE THREAD

**Issue by gitressa** [drush-ops/drush#3350]
If I issue the command `drush user-login --browser=firefox --debug` inside my Ubuntu-based [Vagrant Box Scotch Box Pro](https://github.com/scotch-io/scotch-box-pro), I get this error:
```
No graphical display appears to be available, not starting browser.
```
Is it possible to launch Firefox from Vagrant Box with `drush user-login --browser=firefox`?

**Comment by gitressa** [comment]
My system: Vagrant Scotch Box Pro - Ubuntu 16.04.2 LTS - PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
```
Drupal version   : 8.3.4
Drush script     : /usr/local/bin/drush
Drush version    : 8.1.15
```
Same behavior with these versions (I use [Drush Launcher](https://github.com/drush-ops/drush-launcher))
```
Drupal version   : 8.4.4
Drush script     : /usr/local/bin/drush
Drush version    : 9.0.0
```

**Comment by weitzman** [comment]
I dont think this is possible.
