### ISSUE TITLE
Drush 8.1.15 install fails with php 7.2.2

### ISSUE THREAD

**Issue by ryanaslett** [drush-ops/drush#3351]
Howdy all. So, d7 doesnt work with php 7.2, or at least throws a lot of exceptions for deprecated each() and count() of non-countables. Except I cannot run a `drush si` using 8.1.15 for a d7 site on drupalci, thus we cant really fix these issues without a version of drush that will work. For some reason, the error messages I get are the following: 

`testbot:drupaltestbotpw@172.18.0.4/jenkins_drupal_d7_61404 --clean-url=0 --account-name=admin --account-pass=drupal --account-mail=admin@example.com`
You are about to CREATE the 'jenkins_drupal_d7_61404' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                     [ok]
PHP Fatal error:  Uncaught Error: Call to undefined function cache_get() in /var/www/html/includes/module.inc:754
Stack trace:
#0 /var/www/html/includes/module.inc(954): module_implements('system_theme_in...')
#1 /var/www/html/modules/system/system.module(2511): module_invoke_all('system_theme_in...')
#2 /var/www/html/includes/theme.inc(798): _system_rebuild_theme_data()
#3 /var/www/html/includes/theme.maintenance.inc(57): list_themes()
#4 /var/www/html/includes/bootstrap.inc(2872): _drupal_maintenance_theme()
#5 /var/www/html/includes/errors.inc(179): drupal_maintenance_theme()
#6 /var/www/html/includes/bootstrap.inc(2609): _drupal_log_error(Array, true)
#7 [internal function]: _drupal_exception_handler(Object(Error))
#8 {main}
  thrown in /var/www/html/includes/module.inc on line 754
Drush command terminated abnormally due to an unrecoverable error.

I *was* able to install the site manually, and then run the tests, but drupalci has to use drush si to create a testable site.

**Comment by Chi-teck** [comment]
This is related to https://bugs.php.net/bug.php?id=75227

> Starting Drupal installation. This takes a while. Consider using the --notify global option.

Seems like the message is sent before Drupal bootstrap process has begun, so `ini_set` fails to set some session settings. The simplest workaround is suppressing the output with `--quiet` option.

**Comment by ryanaslett** [comment]
What do headers have to do with a CLI php script? Im confused as to how that relates.

**Comment by greg-1-anderson** [comment]
`Call to undefined function cache_get()` looks more like a problem bootstrapping Drupal prior to the site-install to me, but I haven't had a chance to look at it yet.

**Comment by Chi-teck** [comment]
> What do headers have to do with a CLI php script?
That is another PHP bug.
https://bugs.php.net/bug.php?id=42197

**Comment by Chi-teck** [comment]
One more solution to consider is printing this message conditionally form PHP < 7.2
https://github.com/drush-ops/drush/blob/8.1.15/commands/core/drupal/site_install.inc#L81

**Comment by greg-1-anderson** [comment]
@chi Have you confirmed that commenting out the message allows site-install to work correctly? A while ago we switched `drush_print` to use fwrite instead of print or echo, as that method apparently did **not** interact with the php headers. Is that perhaps no longer the case in php 7.2?

I'll run some tests and see if I can figure anything out about this.

**Comment by Chi-teck** [comment]
@greg-1-anderson Turns out the error was caused by another message.
> You are about to DROP all tables in your '<table_mane>' database. Do you want to continue? (y/n):

Commenting out these three lines did the job for me.
https://github.com/drush-ops/drush/blob/8.1.15/commands/core/site_install.drush.inc#L159

**Comment by Chi-teck** [comment]
> Starting Drupal installation. This takes a while. Consider using the --notify global option.

> You are about to DROP all tables in your '<table_mane>' database. Do you want to continue? (y/n):

The important difference between these two messages is that the first one is printed to _stderror_ while the second one is printed to _stdout_.

**Comment by greg-1-anderson** [comment]
It seems that we never switched `drush_print` to use `fwrite` instead of `print`. Making this adjustment allowed me to successfully install Drupal 7 using Drush 8.x with PHP 7.2.

I'll make a PR.

**Comment by greg-1-anderson** [comment]
@ryanaslett Please try #3353 and see if it also does the trick for you.
