### ISSUE TITLE
Null AnnotatedCommandFactory

### ISSUE THREAD

**Issue by blakemorgan** [drush-ops/drush#3357]
```
 [warning] get_class() expects parameter 1 to be object, null given AnnotatedCommandFactory.php:187
```
This warning appears every time I run a drush command. I'm using Drush v. 9.0.0-beta3

**Comment by greg-1-anderson** [comment]
Please try with Drush 9.0.0-stable. Could be caused by an invalid commandfile. We could hide the symptom in the consolidation/annotated-command project.

**Comment by blakemorgan** [comment]
The issue was because I was using PHP 7.2.
