### ISSUE TITLE
broken links in docs for master & v9 because examples/example.aliases.yml is missing

### ISSUE THREAD

**Issue by ownsourcing** [drush-ops/drush#3358]
drush master & v9 documentation refers to example.aliases.yml which does not exist in those branches:
https://github.com/drush-ops/drush/blob/master/docs/usage.md
https://github.com/drush-ops/drush/blob/master/docs/site-alias-manager.md

search for references to example.aliases.yml in repo: https://github.com/drush-ops/drush/search?q=%22example.aliases%22&type=Code&utf8=✓

**Comment by weitzman** [comment]
Fixed in #3356.
