### ISSUE TITLE
Drush aliases across environments

### ISSUE THREAD

**Issue by reissr** [drush-ops/drush#3363]
I am wondering what is the best-practice to share our Drush aliases across our team members and across our environments.
(We are also working in a multi-site environment which makes it even more complicated to manage)

At the moment we have drush directory in Git (docroot\drush\sites) which contains 1 file per site, and each file has 3 aliases in it (dev, stg and prod).

We need to use those aliases on staging as well (i.e. for sql-sync from prod to stg), but what happens is that the stg aliases is connecting to its own server via SSH which is an issue.

Thanks.

**Comment by reissr** [comment]
This seems like the right direction - https://github.com/drush-ops/drush/issues/3063 isn't it? Altering the aliases is the best approach?

**Comment by weitzman** [comment]
Your arrangement of multiple alias files with 3 envs is each looks great.

Yes, I would try dynamically altering. If that doesn't work, you may be
able to override some parts of the alias from the command line when calling
from stage. Or you can fiddle with DNS to make consistent hosts work in
both environments (if its a host-related problem).

**Comment by rotemreiss** [comment]
Thanks, I will try that.
