### ISSUE TITLE
Support: Any ideas why this command would download drush 9?

### ISSUE THREAD

**Issue by hkirsman** [drush-ops/drush#3369]
COMPOSER_HOME=/usr/lib/composer /usr/bin/composer.phar global require drush/drush:8.x-dev

It was downloading Drush 9 on 2 servers. On 1 server it downloaded Drush 8. Servers should be pretty identical. I deleted old composer.json and lock before the update.

**Comment by weitzman** [comment]
I dont know. If you really want 8.x you can just get the Phar file from https://github.com/drush-ops/drush/releases
