### ISSUE TITLE
CommandNotFoundException: Command "basic-install" is not defined.

### ISSUE THREAD

**Issue by joelpittet** [drush-ops/drush#3373]
https://www.drupal.org/project/basic/issues/2942848

> "[Symfony\Component\Console\Exception\CommandNotFoundException] Command "basic-install" is not defined.

Is there something we can do to get this working again? Is there an upgrade path for contrib modules?

**Comment by weitzman** [comment]
The porting steps for contrib and custom commands are outlined at https://weitzman.github.io/blog/port-to-drush9

**Comment by joelpittet** [comment]
This doesn't seem to work for themes? Should I make a feature request?

**Comment by weitzman** [comment]
I didn't realize this was a theme. This is a dupe of #3089. For that to proceed, we probably do need the issue you linked to. I'll note that.
