### ISSUE TITLE
Drush alias files not working

### ISSUE THREAD

**Issue by horvan** [drush-ops/drush#3377]
I created a file named test.site,yaml in ~/drsuh/sites
the alias test doesent appear when i type drush sa with drush 9.x

**Comment by weitzman** [comment]
Unlike prior versions of Drush, If you want drush9 to find commandfiles and aliases outside the project you are working on, you have to configure it do do so. See alias-paths at https://github.com/drush-ops/drush/blob/master/examples/example.drush.yml
