### ISSUE TITLE
Allow using environment variables in drushrc.yml

### ISSUE THREAD

**Issue by jibran** [drush-ops/drush#3379]
It would be handy to use the environment variables in drushrc.yml.

**Comment by weitzman** [comment]
You can! Now documented in example.drush.yml

**Comment by jibran** [comment]
Thank, now I see it now. I had a look at `\Drush\Config\ConfigLocatorTest` but there was no test case. I think we should add a test for it.

**Comment by jibran** [comment]
Also created https://github.com/consolidation/config/issues/18.
