### ISSUE TITLE
'Container cannot be saved to cache' for updatedb:status with Drush 9.1.0

### ISSUE THREAD

**Issue by dhendriks** [drush-ops/drush#3380]
Using Drush 9.1.0, executing 'updatedb:status' leads to a 'Container cannot be saved to cache.' error in the Drupal log. See steps to reproduce below:

```
$ drush watchdog:show --count=1
 ------- -------------- -------------- ---------- -------------------------------------
  ID      Date           Type           Severity   Message
 ------- -------------- -------------- ---------- -------------------------------------
  53058   13/feb 15:11   DrupalKernel   Fout       Container cannot be saved to cache.
 ------- -------------- -------------- ---------- -------------------------------------
$ drush updatedb:status
 [success] No database updates required.
$ drush watchdog:show --count=1
 ------- -------------- -------------- ---------- -------------------------------------
  ID      Date           Type           Severity   Message
 ------- -------------- -------------- ---------- -------------------------------------
  53059   13/feb 15:14   DrupalKernel   Fout       Container cannot be saved to cache.
 ------- -------------- -------------- ---------- -------------------------------------
$ drush --version
Drush Commandline Tool 9.1.0
```

Note that entry 53059 has been added during the execution of the 'updatedb:status' command.

I saw a similar issue at https://www.drupal.org/node/2646410, which is about update.php, that is supposedly fixed a while back. So it seems this is a new issue.

I'm using Drupal 8.4.4.

**Comment by outlawery** [comment]
Same here using drush 9.2.1 and drupal 8.5

**Comment by hrcegeka** [comment]
drush updb itself also generates this error (9.2.1/8.5.0)

**Comment by benjy** [comment]
Does Drush have a predetermined release cycle? Looking for a date as to when this will be included so I can come back and update.

**Comment by hunterbuchanan** [comment]
@benjy I'm in the same boat, my team doesn't want to upgrade to Drush 9 until this is patched in a dot release. Have you tried installing Drush with Composer using `composer require drush/drush:9.x-dev`? I can test it out at some point, but we're not including Drush 9 in our environment until the next new version is released.
