### ISSUE TITLE
Workflow: Should `drush/sites/` be committed as part of the project

### ISSUE THREAD

**Issue by joelpittet** [drush-ops/drush#3381]
I'm curious to know if `drush/sites/` should be committed as part of the project since it's new with Drush 9 that aliases seem to need to be local with the project.

**Comment by weitzman** [comment]
Yes, thats the my recommendation. And yeah, not searching global locations
is a little push/indicator about the new way. Thanks for picking up on it.

**Comment by greg-1-anderson** [comment]
@joelpittet You can still have global site aliases if you opt in to do so. If you run `drush init`, it will add a configuration directive to search global locations.

Committing `drush/sites` is a great way to share project aliases (e.g. to the test and live sites) among a team, tho.
