### ISSUE TITLE
updatedb --post-updates requires an option argument to run

### ISSUE THREAD

**Issue by rbayliss** [drush-ops/drush#3385]
On Drush 9.1.0, `drush updatedb --post-updates` displays pending post updates, but does not actually execute them.  `drush updatedb --post-updates=1` does execute them.  I'm unclear on whether this is an upstream bug with `consolidation/annotated-command` or something with `drush`.  If I drop in a debug statement at the top of `UpdateDbCommands::updatedb()`, I can see the following options values:

```
// Debug output with drush updatedb --post-updates -y
array (
  // ...
  'post-updates' => NULL,
  'no-post-updates' => false,
  // ... 
)
// Debug output with drush updatedb --post-updates=1 -y
array(
  // ...
  'post-updates' => '1',
  'no-post-updates' => false,
  // ...
)
```

**Comment by rbayliss** [comment]
For reference, `consolidation/annotated-command` is at 2.8.2.

**Comment by weitzman** [comment]
I can confirm this. Using Drush 9.1, with symfony/console v3.2.14. The spec thats gone wrong here is "If the option exists on the commandline, but has no value (e.g. --foo), then the value will be true" from https://github.com/consolidation/annotated-command/#option-default-values.

To reproduce this, run the command (or `sut updatedb --post-updates`) above and do a print)r($options) at top of \Drush\Commands\core\UpdateDBCommands::updatedb. You don't actually need any pending updates.

/cc @greg-1-anderson

**Comment by greg-1-anderson** [comment]
The unit tests only had coverage for StringInput; I [added tests for ArgvInput](https://github.com/consolidation/annotated-command/blob/638356ea2d3925092cc5df51785d8370d8800465/tests/testAnnotatedCommandFactory.php#L179:L180), and the tests are still passing.

I'll investigate in the context of Drush and see if I can figure out what the cause is here.

**Comment by greg-1-anderson** [comment]
The problem is that `DrushArgvInput` extends `Input`, and it needs to extend ArgvInput for all of the features of AnnotatedCommand to work. I'll submit a PR.
