### ISSUE TITLE
Option without value is ignored?

### ISSUE THREAD

**Issue by kmajzlik** [drush-ops/drush#3387]
Before last update on my project (Drush 9.0.0-rc1) this command worked:
`drush migrate:import --all --force --update`
After update (Drush 9.1.0) it ignore those options (i hope _option_ is correct word in this meaning).
I have to use:
`drush migrate:import --all=1 --force=true --update=whatever`
(so i have to add there any value just to meet !empty() condition)

Is that somewhere documented or is that bug?

**Comment by weitzman** [comment]
Looks like a migrate bug. Its a little tricky to get option values right.

**Comment by kmajzlik** [comment]
migrate_plus which provides this command has last release: 8.x-4.0-beta2 released 27 November 2017 so nothing changed there during my update yesterday.

http://cgit.drupalcode.org/migrate_tools/tree/src/Commands/MigrateToolsCommands.php#n274

**Comment by weitzman** [comment]
Its possible that Drush fixed a bug that migrate_tools was relying on.

**Comment by weitzman** [comment]
Specifically, the default value of 'all' and 'force' options should be `false`, not `null`.
