### ISSUE TITLE
Unable to implement SiteAliasManagerAwareInterface 

### ISSUE THREAD

**Issue by himerus** [drush-ops/drush#3394]
### Issue Summary
The basics are this: I'm attempting to write a Drush command that uses the site aliases available to an environment in order to handle creating some custom sync/deploy commands between environments. In order to do so I need to implement the `SiteAliasManagerAwareInterface` and have access to the available aliases in `drush/sites/mysite.yml`. 

I've used the `drush @myalias generate` command to build out the sample module and Drush command file. Then I replace the contents (and edit appropriately) from any of the Drush commands I found to ` implements SiteAliasManagerAwareInterface`. 

### Replicate issue
I've created a sample module to demonstrate what I'm trying to accomplish, the issue I've noted, and to avoid having to post the contents of everything from the module/command file in this issue directly.

Sample module demonstrating issue: 
[sam_test](https://github.com/himerus/sam_test) 

From [SamTestCommands.php](https://github.com/himerus/sam_test/blob/master/src/Commands/SamTestCommands.php)
```
<?php

namespace Drupal\sam_test\Commands;

use Drush\Commands\DrushCommands;
use Drush\SiteAlias\SiteAliasManagerAwareInterface;
use Drush\SiteAlias\SiteAliasManagerAwareTrait;

class SamTestCommands extends DrushCommands implements SiteAliasManagerAwareInterface {
  use SiteAliasManagerAwareTrait;

  /**
   * Test to run $this->siteAliasManager()->getSelf();
   *
   * @command sam:test
   * @aliases sam-test
   * @usage drush sam:test
   *   Test that `implements SiteAliasManagerAwareInterface` is working correctly.
   * @handle-remote-commands true
   */
  public function example() {
    $alias = $this->siteAliasManager()->getSelf();
  }

  /**
   * Test to run $this->siteAliasManager()->searchLocations();
   *
   * @command sam:test2
   * @aliases sam-test2
   * @usage drush sam:test2
   *   Test that `implements SiteAliasManagerAwareInterface` is working correctly.
   * @handle-remote-commands true
   */
  public function example_two() {
    $alias = $this->siteAliasManager()->searchLocations();
  }
}

```

### Resulting Error:
`drush @mysite-alias sam:test`: 
> Error: Call to a member function getSelf() on null in Drupal\sam_test\Commands\SamTestCommands->example() (line 22 of modules/custom/sam_test/src/Commands/SamTestCommands.php).

### Conclusion
Either I'm doing something really wrong, and have wasted a day or two for nothing, or there's something wrong with implementing the `SiteAliasManagerAwareInterface` outside of the default Drush commands in Drush 9.

**Comment by weitzman** [comment]
Hi @himerus!

Thanks for the example module and clear bug report. I can confirm the ill behavior. The issue is that the inflectors at https://github.com/drush-ops/drush/blob/afecae950a6cbd2a857184355441afc853ae6cef/src/Runtime/DependencyInjection.php#L104-L108 only run for Drush core commands. Perhaps @greg-1-anderson has an idea on how to address this for Drupal commands which use the Drupal container, not the League container like Drush. I think this need has come up before.

**Comment by weitzman** [comment]
Until we have a dependency injection solution, your code should use `Drush::aliasManager()`. I think the docs dont make this clear at all.

**Comment by himerus** [comment]
Thanks Moshe! 

Yeah, the docs at http://docs.drush.org/en/master/site-alias-manager/ weren't super helpful, and until I wrap my head around some of the underpinnings, I was spinning my wheels a bit.

`Drush::aliasManager()` definitely gets me access to the alias data.

**Comment by greg-1-anderson** [comment]
See #3406

**Comment by Ambient-Impact** [comment]
Hi there. I'm still seeing this problem with Drush 9.7.1 despite seemingly following all the instructions in the docs and in this thread. I'm implementing the interface and using the trait, but I still end up with ```$this->siteAliasManager()``` returning ```null```. Has this not been fixed, or is it possible I'm doing something wrong?

**Comment by bob-hinrichs** [comment]
I am finding Drush::aliasManager() still works in Drupal 9.1 + Drush 10, but is deprecated; but the suggested siteAliasManager() on the same service returns null.  I have spent two days attempting to find any working guidance on the correct way to do it.  Is this a bug?  All I need to do is simply execute a drush command from a module's post-install hook.

**Comment by Ambient-Impact** [comment]
> 
> 
> I am finding Drush::aliasManager() still works in Drupal 9.1 + Drush 10, but is deprecated; but the suggested siteAliasManager() on the same service returns null. I have spent two days attempting to find any working guidance on the correct way to do it. Is this a bug? All I need to do is simply execute a drush command from a module's post-install hook.
> 
> FWIW, I eliminated the error by instantiating the SiteAliasManager and setting it into the service.
> 
> $command = \Drupal::service('my_service_implementing_siteawarenterface');
> $command->setSiteAliasManager(new SiteAliasManager());
> print "\r\nRun silly drush command devel entity updates...\r\n";
> Drush::drush($command->siteAliasManager()->getSelf(), 'devel-entity-updates')->run();

I think this has been fixed at some point since I posted my comment. On Drush 10.5, it seems to work if you try accessing ```$this->siteAliasManager()``` in a command method for me. It doesn't work in the command class' ```__construct()``` for whatever reason.

Also, I would strongly recommend using proper dependency injection when possible and not the ```\Drupal``` static class. Let me know if you want some more info on that or you're already familiar with it.
