### ISSUE TITLE
Add pm:outdated command

### ISSUE THREAD

**Issue by gitressa** [drush-ops/drush#3395]
I can check for security updates for modules and themes with `drush pm:security` which is great, because I don't have to remember to navigate from ./web to root-folder to do this.

If I forget to move to root-folder, Composer asks me this, if all I want is a list of outdated modules:
```
/var/www/public/my_web_site/web$ composer outdated 'drupal/*'
No composer.json in current directory, do you want to use the one at /var/www/public/my_web_site? [Y,n]?
```
So it would be really nice to also have `drush pm:outdated` available, to quickly get a list of modules and themes with available updates.

**Comment by seanbeaton** [comment]
There used to be `drush pm:updatecode` or `drush pmu` which would list updatable modules. That's been deprecated:

```
$ drush pm:updatecode

  [Exception]
  The pm-updatecode command was deprecated. Please see `composer outdated` and `composer update`. For security release notification, see `drush pm:security`.
```

I have this set up in my .bash_profile to allow for running the drush.sh script I have in the root directory of a given repository (a special drush script to work with docker). 

```
function drush {
  DRUSH_LOCATION="$(pwd)"; while [ "$DRUSH_LOCATION" != "/" ]; do if [ -e "${DRUSH_LOCATION}/drush.sh" ]; then break; fi; DRUSH_LOCATION="$(dirname "$DRUSH_LOCATION")"; done
  if [ "$DRUSH_LOCATION" = "/" ]; then
    DRUSH_LOCATION=`which drush`;
  else
    DRUSH_LOCATION="$DRUSH_LOCATION/drush.sh";
  fi
  $DRUSH_LOCATION $@;
}
```

This isn't fully tested in all cases, but you may be able to use something like this to automatically use the closest composer.json file it can find up the directory tree:

NOT TESTED:
```
function composer {
  # remember the original previous directory so we can use `cd -` later outside this command.
  ORIG_OLDPWD=$OLDPWD;
  COMPOSER_LOC=`which composer`
  COMPOSER_JSON_LOCATION="$(pwd)";
  while [ "$COMPOSER_JSON_LOCATION" != "/" ]; do 
  	if [ -e "${COMPOSER_JSON_LOCATION}/composer.json" ]; then 
  		echo "Using composer.json from $COMPOSER_JSON_LOCATION";
  		break; 	
  	fi;
  	COMPOSER_JSON_LOCATION="$(dirname "$COMPOSER_JSON_LOCATION")"; 
  done
  if [ "$COMPOSER_JSON_LOCATION" = "/" ]; then
    $COMPOSER_LOC $@;
  else
    cd $COMPOSER_JSON_LOCATION;
    $COMPOSER_LOC $@;
    cd - > /dev/null 2>&1;
    OLDPWD=$ORIG_OLDPWD;
  fi
}
```

You may also want to set a sleep on it if it's not using the composer.json in your current directory so you have a chance to cancel it if it ends up finding the wrong one.

```

function composer {
  # remember the original previous directory so we can use `cd -` later outside this command.
  ORIG_OLDPWD=$OLDPWD;
  COMPOSER_LOC=`which composer`
  COMPOSER_JSON_LOCATION="$(pwd)";
  while [ "$COMPOSER_JSON_LOCATION" != "/" ]; do 
  	if [ -e "${COMPOSER_JSON_LOCATION}/composer.json" ]; then 
  		echo "Using composer.json from $COMPOSER_JSON_LOCATION in 2 seconds, cancel with ^C";
  		sleep 2
  		break; 	
  	fi;
  	COMPOSER_JSON_LOCATION="$(dirname "$COMPOSER_JSON_LOCATION")"; 
  done
  if [ "$COMPOSER_JSON_LOCATION" = "/" ]; then
    $COMPOSER_LOC $@;
  else
    cd $COMPOSER_JSON_LOCATION;
    $COMPOSER_LOC $@;
    cd - > /dev/null 2>&1;
    OLDPWD=$ORIG_OLDPWD;
  fi
```

**Comment by weitzman** [comment]
I think we will pass on wrapping Composer commands for the sole purpose of setting the composer working directory. That can be done as Drush contrib commands, if anyone desires.

**Comment by gitressa** [comment]
Thanks for sharing your solution @seanbeaton. I do understand that from Drush 9 and forward updates to modules and composer.json is done with `composer require drupal/<module>`. But what I'd like to is be able to get a list of modules with available updates, via a Drush command, just to check for their availability.
