### ISSUE TITLE
Drush upwd command fails with drush/drush 9.1.0

### ISSUE THREAD

**Issue by phrane** [drush-ops/drush#3399]
Description:
Drush upwd USER --password="newpassword" to change password fails.

Expected:
Drush upwd USER --password="newpassword" should result in [success] with changed password.

Actual:
The Drush upwd command fails with notification - 
"  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--password" option does not exist.  "

Observation:
After downgrading to Drush Commandline Tool 8.1.16 (from 9.1.0) and re-running Drush upwd command, it was successful.

My environment:
Ubuntu 16.04
Composer based Drupal 8.4.4 project

**Comment by weitzman** [comment]
password is now an argument, not an option. see `drush help upwd`.

**Comment by phrane** [comment]
Understood... So in Drush 9 this is now:

drush upwd USERNAME PASSWORD

thanks!
