### ISSUE TITLE
drush sql-query should exit with failure status if query fails

### ISSUE THREAD

**Issue by rfay** [drush-ops/drush#34]
Currently, drush sql-query exits with a 0 even if there was an error in the query:

```
[rfay@dev-web11 current]$ drush sqlq 'select * from nothing;'
ERROR 1146 (42S02) at line 1: Table 'xxx_dev.nothing' doesn't exist
[rfay@dev-web11 current]$ echo $?
0
```

I think it would be useful to all of us if it returned an error status in a case like this.

Thanks!

**Comment by plach79** [comment]
I'm still experiencing this on 8.x, apparently `drush_sql_cli()` does not set an explicit error when the process fails and returning `FALSE` is not enough to set a non-zero exit status.
