### ISSUE TITLE
Drush 8 aliases don't work

### ISSUE THREAD

**Issue by OnkelTem** [drush-ops/drush#3401]
Created a file `mysite.site.yml` and placed it into placed into `$ROOT/../drush/sites/`
No reaction from Drush (8.1.16).

Created `drushrc.php` and placed into `sites/all/drush/` - the same. 

In the last case I even could trigger breakpoint so it was read. But it didn't do anything, whenever I run drush sa I just get those default aliases like: @none, @self and default.
Honestly it's triggered only from `\drush_load_config_file()` and there I don't see any uses of `$aliases` variable so it seems like it should be called from somewhere else.

**Comment by weitzman** [comment]
site.yml files are for drush9 not drush8. for 8 see
http://docs.drush.org/en/8.x/

**Comment by OnkelTem** [comment]
> site.yml files are for drush9 not drush8. for 8 see

Oh, good to know. I didn't even know that there is Drush number 9 and honestly I don't see any version numbers here http://docs.drush.org/en/master/ - no in the URL just nowhere.
Also there is no mention about Drush 9 inside this file: 
https://raw.githubusercontent.com/drush-ops/drush/master/examples/example.site.yml
The same with drushrc.php - no version specification. Just makes it all complicated.

So what is the way to get aliases really working?

**Comment by OnkelTem** [comment]
Folks, so do you have any ideas?

This is my `drushrc.php`:

```
<?php

$aliases['stage'] = [
  'uri' => 'some.doman.com',
  'root' => '/some/path',
  'remote-user' => 'my-username',
  'remote-host' => 'ip-address',
];
```

**Comment by fafnirical** [comment]
The file should be named `mysite.aliases.drushrc.php`, per the instructions in the example: https://github.com/drush-ops/drush/blob/8.x/examples/example.aliases.drushrc.php#L33-L37

**Comment by OnkelTem** [comment]
@fafnirical 
> The file should be named mysite.aliases.drushrc.php, per the instructions in the example: 
>  https://github.com/drush-ops/drush/blob/8.x/examples/example.aliases.drushrc.php#L33-L37

Oh, thank you very much.
