### ISSUE TITLE
'A non-numeric value encountered preflight.inc' warning

### ISSUE THREAD

**Issue by alexey-kuznetsov** [drush-ops/drush#3410]
When use drush 8.1.15 with php 7.1 at every drush command I see in console warning
`A non-numeric value encountered preflight.inc:468`
Everything else is seems to work properly, but this warning bothers me.

**Comment by weitzman** [comment]
Have you set `--reserve-margin` option to a non-number via the CLI or config?

**Comment by weitzman** [comment]
The relevant line is https://github.com/drush-ops/drush/blob/1230b62b363d4ce4ada59840f0474a34552e4422/includes/preflight.inc#L468.

**Comment by alexey-kuznetsov** [comment]
@weitzman , no I didn't set this option. I found this warning at four different servers with fresh php 7.1 and drush 8 installation. This warning is new feature of php 7.1, you can read details here: http://php.net/manual/en/migration71.other-changes.php
It seems like this line (441 at the same file):
`if (!($columns = getenv('COLUMNS'))) {`
could return non-numeric value, something like NULL. But I'm not sure, because I'm not familiar with drush codebase.

**Comment by weitzman** [comment]
Ah right. I think this is now fixed. See https://github.com/drush-ops/drush/commit/a13851c614f4e3172455ddf9c26f01decddf3f27.

**Comment by alexey-kuznetsov** [comment]
Good job!

**Comment by acbramley** [comment]
Still seeing this error on 8.1.17

**Comment by lukasz-zaroda** [comment]
Yep, it's still there.
