### ISSUE TITLE
virtual hosts do not "see" global update of drush

### ISSUE THREAD

**Issue by RKopacz** [drush-ops/drush#3415]
I just tried updating my installation of drush to 8.1.12 to accomodate updates to Drupal 8.4.5.  I ran the update in the root directory and when I type 'drush --version' in the root it correctly reports 8.1.12, but from within the virtual hosts it is still reporting 8.1.10.

I tried clearing the composer cache and clearing the Drush cache; still reporting 10 in the virtual hosts.

Anybody know what I need to do? If this is not the appropriate place to seek support on this issue, please let me know where I need to go.

**Comment by greg-1-anderson** [comment]
Check to see if you have a site-local version of Drush in your virtual hosts, e.g. `vendor/bin/drush` or `vendor/drush/drush/drush`. Drush will redispatch to the site-local Drush if it exists. Run `drush --debug --version` and you should see the redispatch if it is happening.

**Comment by RKopacz** [comment]
@greg-1-anderson thank you for your input. I ran that debug command in the root of the server and in the root of the virtual host, but I am not sure how to interpret the output, except to see. The virtual host seems to be pulling from a cache:

`Phar detected. Proceeding to drush_main().
Cache HIT cid: 8.1.10-commandfiles-0-3339095dd6bd76b12856d993f68f4b69 [0.02 sec, 3.58 MB] `

I see that @weitzman marked this as closed. Is this question not worthy of this issue queue? If so, I would appreciate pointing me to some documentation to debug this or another more appropriate forum. Thanks.

**Comment by greg-1-anderson** [comment]
I'm not sure what is causing the issue here. The Drush [README Support section](https://github.com/drush-ops/drush#support) recommends using Drupal Stack Exchange for support questions.

**Comment by RKopacz** [comment]
That's where I'll go! Thank you for that. Cheers.
