### ISSUE TITLE
Compatible Drupal versions for Drush 9

### ISSUE THREAD

**Issue by hansfn** [drush-ops/drush#3420]
I have read http://docs.drush.org/en/master/install/#drupal-compatibility which is very clear. However, I wonder if it is correct ...

My motivation is that I try to improve/simplify some of the [update D8 docs on drupal.org](https://www.drupal.org/docs/8/update), and it would be really nice to say "use Drush 9 and composer, never Drush 8". Currently it seems like you have to use Drush 8 to update for example Drupal 8.2, but Drush 9 to update for example Drupal 8.4.

I might have misread the table.

**Comment by greg-1-anderson** [comment]
I did try Drush9 with Drupal 8.2 sometime back. It works on later versions (8.2.7+ I think) but does not work at all on earlier versions. But I'd say that there be dragons here; later versions of Drush 9 might not work as well, and certainly no one is going to fix bugs here.

**Comment by hansfn** [comment]
Thx for the feedback. I think the easy solution when it comes to the drupal.org documentation is to only recommend composer for updating Drupal 8.
