### ISSUE TITLE
Drush command line option for download Drupal to current folder

### ISSUE THREAD

**Issue by MurzNN** [drush-ops/drush#3424]
Very often we need to download Drupal core via Drush directly to current folder via CLI, without `Drupal-X.Y` or any other subfolder.

At now there are exists only some ugly Bash command line hacks from <a href="https://www.drupal.org/project/drush/issues/495438#comment-5079384">here</a> like:
`drush dl -v -d --destination=".." --drupal-project-rename="$(basename `pwd`)"`
`drush dl drupal --drupal-project-rename="../${PWD##*/}" -y`
but this is too hard way for newbies, and will work only on Linux.

Please provide standard Drush way for download Drupal directly to current folder! 

Best will be having separate Drush command line argument like:
`drush dl drupal --to-current-folder`

Also will be good to extend arguments `--destination=<path>` and `--drupal-project-rename` for support current folder, marked as `.` (one dot).

**Comment by weitzman** [comment]
For new projects, the expectation is that you are using Composer to download Drupal and any modules you need. Drush9 doesn't even have a `dl` command. 

Drush8 does download to the current folder by default. Also, we are no longer taking feature requests for Drush8
