### ISSUE TITLE
[POSTGRESQL] - the password is always asked

### ISSUE THREAD

**Issue by dleras** [drush-ops/drush#3427]
Hi,

I have an issue with drush 9.0.0-beta4, the password is always asked for any operation in a POSTGRESQL database (drush cr, drush sql-dump, drush updb ... )

I do not have this issue with drush 8.1.16 and I had to rollback the drush version in order to be able to use drush. 

The problem seems to come from the temporary file generated to store to database credentials for the psql command

Could you have a look on this issue, it would be very annoying to not be able to upgrade drush because of this issue. 

Thanks for your help

**Comment by weitzman** [comment]
Duplicate. Also, use 9.2.1 not a beta please.
