### ISSUE TITLE
Run Drush command without install the module

### ISSUE THREAD

**Issue by drobert8584** [drush-ops/drush#3429]
Sorry, I don't know if there is the good place.

I write a Drush 9 command in a drupal 8.5 module, but I don't find a explanation how can I make my command "callable / runable" without installing my module ( my drupal instance is fully installed).

Someone can explain me how to make that ?

Thanks

DrDam

**Comment by weitzman** [comment]
http://docs.drush.org/en/master/commands/#global-drush-commands
