### ISSUE TITLE
Drush problem

### ISSUE THREAD

**Issue by christophe-natale** [drush-ops/drush#3431]
Hello,
I'm using drush since 3 years on a VPS server.
Installation has been made in root, so the same drush installation is used on several account.
Since last update of drupal I have a problem with Drush only on few account :
Drush doesn't find the drupal installation.
When I use drush cc, only few options appears :
[0]  :  Cancel
 [1]  :  drush
 [2]  :  registry
But if i use drush status :
 drush status
 Drupal version         :  7.57
 Site URI               :  http://default
 Database driver        :  mysql
 Database hostname      :  localhost
 Database port          :
 Database username      :  gretalor_admin
 Database name          :  gretalor_1
 PHP configuration      :  /opt/cpanel/ea-php70/root/etc/php.ini
 PHP OS                 :  Linux
 Drush script           :  /usr/local/bin/drush
 Drush version          :  8.1.14
 Drush temp directory   :  /tmp
 Drush configuration    :
 Drush alias files      :
 Drupal root            :  /home/gretalor/public_html
 Drupal Settings File   :  sites/default/settings.php
 Site path              :  sites/default

It seems that drush is well configure, but can not find drupal installation, I wonder if it's rights problem..
Can you help ?
Regards,

**Comment by weitzman** [comment]
Please use Drupal Answers for support questions.
