### ISSUE TITLE
Drupal core compatibility for Drush 8

### ISSUE THREAD

**Issue by danepowell** [drush-ops/drush#3440]
The documentation on core compatibility seems out of date and should be updated: http://docs.drush.org/en/master/install/#drupal-compatibility

Specifically, it states that Drush 8 only works for Drupal 8.3 and below, which is incorrect. 8.1.15 and above work for Drupal 8.4: https://github.com/drush-ops/drush/releases/tag/8.1.15

Additionally, I'm wondering if Drush 8 supports Drupal 8.5? I really hope so, given that Drush 9 includes major breaking changes and not all downstream projects (like acquia/blt) have stable releases that work with Drush 9 / Drupal 8.5.

**Comment by weitzman** [comment]
The core compatibility chart lists the versions of Drupal that are *supported*. Given that distinction, its accurate AFAICT. You are correct that Drush 8 *happens to work* for Drupal 8.4 and happily is passing tests for Drupal 8.5 as well. The standard for *happens to work* is lower than *supported*.
