### ISSUE TITLE
pm-enable does not trigger translation import

### ISSUE THREAD

**Issue by Sutharsan** [drush-ops/drush#3444]
In Drupal 8 with Locale module enabled, interface translations are imported when modules are enabled via the interface. But when enabled via Drush, this does not happen.
The same situation applies for enabling themes.

Proposed solution: Add a check for and execution of batch process as part of pm-enable.
Follow-up: option to suppress the auto-import.

**Comment by Sutharsan** [comment]
Created pull request #3445 to execute the batch process.

**Comment by weitzman** [comment]
Drush9 PR is in. Lets talk as needed in #3445
