### ISSUE TITLE
Drush 9 pm:security does not report security updates for Drupal core

### ISSUE THREAD

**Issue by shaysmith** [drush-ops/drush#3448]
Checking security updates via drush 8, I see the following output:
`$ drush pm-updatestatus --security-only`
`Checking available update data ...                                                                [ok]`
`Checking available update data for Drupal.                                                        [ok]`
` Name    Installed Version  Proposed version  Message`
 `Drupal  8.3.3              8.4.5             SECURITY UPDATE available`

When I check the same site using drush 9, I see no security updates:
`$ drush pm:security`
` [notice] There are no outstanding security updates for Drupal projects.`

Is this expected behavior?

**Comment by weitzman** [comment]
from the command, `$composer_lock_data` notes SAs for `drupal/drupal` but your project likely uses `drupal/core`. So no conflict is reported.

Not sure if we should change this in Drush or in drupal-composer/drupal-security-advisories. ping @webflo and @grasmash

**Comment by webflo** [comment]
We could publish the SA for ``drupal/drupal`` as ``drupal/core`` as well. Maybe it helps other implementations too.

**Comment by grasmash** [comment]
I think that makes the most sense.

**Comment by webflo** [comment]
https://github.com/drupal-composer/drupal-security-advisories/commit/46dc7a4790bb98e7b785a1fa1679a076b93e1851

**Comment by webflo** [comment]
https://packagist.org/packages/drupal-composer/drupal-security-advisories#8.x-dev it up to date. It lists the same constraints for drupal/drupal and drupal/core.

**Comment by weitzman** [comment]
Thanks @webflo.
