### ISSUE TITLE
How to print a message to drush 9 from a module

### ISSUE THREAD

**Issue by gaelg** [drush-ops/drush#3449]
I made a custom module that implements hook_rebuild(). There's a drupal_set_message() in it. If I clear the caches from Drupal's UI, the message is shown. But it's not shown if I execute drush cr. Is there an easy way to print my message in both cases?

**Comment by weitzman** [comment]
Watchdog shows in both.

**Comment by gaelg** [comment]
I don't get what you mean. I tried both following commands with Drupal 8.5 and Drush 9.2.1, but I only get "[success] Cache rebuild complete."

`\Drupal::messenger()->addMessage($message);
    \Drupal::logger('insite_default_content')->info($message);`

**Comment by gaelg** [comment]
Any chance I get an answer in this closed issue? If not I'll create a new one.

**Comment by luksak** [comment]
watchdog logs the messages instead of displaying them.

**Comment by chx** [comment]
You need to extend from `MessengerCommands` instead of `DrushCommands`. This was added in #3489 and is documented absolutely nowhere.

**Comment by weitzman** [comment]
Usually Drupal Messages are shown in Drush but in this particular example the request doesn't fully bootstrap so the Message never gets shown.

**Comment by weitzman** [comment]
Yes just add `@bootstrap full` as an annotation on your command.

**Comment by gaelg** [comment]
Well, "my" command is "drush cr", it's not mine. ;) I'm actually asking if it's possible to override the bootstrap level at run time, like with a UNIX option to the drush command call.

**Comment by weitzman** [comment]
The drupal cache rebuild API is designed to work before full bootstrap. Drush can't change that.

**Comment by gaelg** [comment]
You mean, even if `drush cr` had `@bootstrap full` in its annotation, the message that is printed to the browser when I rebuild the cache through Drupal admin UI would still not be printed to the console when I rebuild through drush?

**Comment by greg-1-anderson** [comment]
`drush cr` would not work correctly if you made it `@bootstrap full`. It might work sometimes (I have not tried), but even if it did, you could get into a situation where the cache needs to be rebuilt in order to bootstrap.

If watchdog messages from your hook show in the UI after a cache rebuild, though, I suspect there is a way that Drush could get the watchdog messages. Maybe our watchdog code could be working at a lower bootstrap level than full. I have not looked into this, though.

**Comment by gaelg** [comment]
@greg-1-anderson Interesting. Yes Drupal prints the messenger ones and logs the logger ones. I stay tuned, thank you anyway.

**Comment by awm086** [comment]
I know this is closed but I am having the same issue. I invoking a service method from a drush command. The method print messages but non of  `\Drupal::messenger()` are being printed. This may be a quirk of my installation but wonder if anyone can reproduce: 
```
      \Drupal::messenger()->addStatus('Starting') // no displaying anything
      \Drupal::messenger()->addMessage('Test');
```
The only way to print to the console is to use the drush IO service as far as I could see.
