### ISSUE TITLE
Drush breaks on nonstandard bin-dir

### ISSUE THREAD

**Issue by axel-rutz** [drush-ops/drush#3452]
Finally tracked this jitterbug down. How to reproduce:
* Have one drush version (here 8) on your global PATH
* Have another drush version (here 9) site-local
* Set a site-local bin dir different from `vendor/bin` via `composer config bin-dir bin`

Result:
* drush8 does NOT launch the site-local drush9
* ...but uses its driver classes

BOOM and we have all sorts of enigmatic exceptions.

#############################################################################

This is a bit confusing (and may be connected to some other issues with that exception).

How to reproduce
* Have a drush 8.1.16 on your PATH
* Have a site-local drush9

Then in drupal root
* `drush status` errors out as shown below
* `../vendorbin/drush status`

`drush status`
```
[09-Mar-2018 23:56:29 UTC] ArgumentCountError: Too few arguments to function Drush\Sql\SqlBase::__construct(), 1 passed and exactly 2 expected in /var/www/html/vendor/drush/drush/src/Sql/SqlBase.php on line 29 #0 [internal function]: Drush\Sql\SqlBase->__construct(Array)
#1 /home/wodby/.composer/vendor/drush/drush/includes/drush.inc(117): ReflectionClass->newInstanceArgs(Array)
#2 /home/wodby/.composer/vendor/drush/drush/commands/sql/sql.drush.inc(523): drush_get_class('Drush\\Sql\\Sql', Array, Array)
#3 /home/wodby/.composer/vendor/drush/drush/commands/sql/sql.drush.inc(540): drush_sql_get_class(Array)
#4 /home/wodby/.composer/vendor/drush/drush/includes/environment.inc(384): drush_sql_get_class()
#5 /home/wodby/.composer/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php(462): drush_valid_db_credentials()
#6 /home/wodby/.composer/vendor/drush/drush/lib/Drush/Boot/DrupalBoot8.php(109): Drush\Boot\DrupalBoot->bootstrap_drupal_database_validate()
#7 /home/wodby/.composer/vendor/drush/drush/includes/bootstrap.inc
23:56:29  INFO [Update database][command] only_if output: (430): Drush\Boot\DrupalBoot8->bootstrap_drupal_database_validate()
#8 /home/wodby/.composer/vendor/drush/drush/includes/bootstrap.inc(507): drush_bootstrap_validate(4)
#9 /home/wodby/.composer/vendor/drush/drush/includes/bootstrap.inc(456): drush_bootstrap_max()
#10 /home/wodby/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(59): drush_bootstrap_to_phase(-2)
#11 /home/wodby/.composer/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#12 /home/wodby/.composer/vendor/drush/drush/drush.php(12): drush_main()
#13 {main}

```

**Comment by axel-rutz** [comment]
NOPE, something different is happening here. Closing for now until i see clearly.

**Comment by axel-rutz** [comment]
After several updates of the IS i finally got it! 😜

**Comment by weitzman** [comment]
Have you tried drush-launcher as your global instead of drush8? We dont recommend drush8 as a global launcher anymore so I'm not inclined to invest time on this issue, at least as described now.

**Comment by weitzman** [comment]
Note that drush-launcher includes a FALLBACK feature if you still run sites that need global drush8.

**Comment by axel-rutz** [comment]
> so I'm not inclined to invest time on this issue, at least as described now.

I do understand.

> Note that drush-launcher includes a FALLBACK feature if you still run sites that need global drush8.

So the supported way is to install the launcher, and optionally a global (8 or 9) drush?
And the launcher will give priority to a site-local (8 or 9) drush?

If so, i'll report this back to the hoster (wodby).

**Comment by weitzman** [comment]
Yes, that is a supported configuration.

**Comment by axel-rutz** [comment]
So this might simply go into the docs.

**Comment by weitzman** [comment]
I'm not clear what docs changes would help. Maybe suggest via a PR?
