### ISSUE TITLE
Prevent loading of Drush9 commands in Drush 8.x

### ISSUE THREAD

**Issue by PhilippVerpoort** [drush-ops/drush#3456]
After installing Drupal 8 including Drush 9.x with composer

`composer create-project drupal-composer/drupal-project:8.x-dev foldername --stability dev --no-interaction`

and downgrading to Drush 8.x

`composer require drush/drush:8.x`

I get the following error message when trying to run `drush`

`PHP Fatal error:  Class 'Drush\Commands\DrushCommands' not found in /var/www/html/path-to-site/drush/Commands/PolicyCommands.php on line 11`

`Drush command terminated abnormally due to an unrecoverable error.`

`Error: Class 'Drush\Commands\DrushCommands' not found in /var/www/html/path-to-site/drush/Commands/PolicyCommands.php, line 11`

After removing the folder 'drush' from the root directory, it works fine.

It seems as if when uninstalling Drush 9.x, Composer didn't properly remove it from the Composer project. Sorry, I'm not sure where to report this bug -- is it Composer's fault?

**Comment by weitzman** [comment]
Easiest thing to do is delete PolicyCommands.php as it is made for Drush.

I'll see what can be done about the error.

**Comment by weitzman** [comment]
This was probably introduced when https://github.com/drupal-composer/drupal-project/pull/351 went in.

**Comment by weitzman** [comment]
@greg-1-anderson said he may look into preventing the loading of these commands in 8.x

**Comment by greg-1-anderson** [comment]
Drush 8.1.17 has some basic interoperability with Drush 9 command files, so the policy file from drupal-composer/drupal-project no longer crashes Drush 8.

**Comment by leymannx** [comment]
Is the following related? I can't use my global Drush 8.2.3 anymore inside a non-Composer D7 due to the following error. I think this happened after I cloned Drush master into the folder above the non-Composer D7 project. Renaming the `drush` directory to something different solved it.

```bash
$ drush8 -y sql-drop
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Class 'Drush\Commands\DrushCommands' not found in
/Users/leymannx/Sites/drush/src/Commands/pm/SecurityUpdateCommands.php,
line 15
```

**Comment by greg-1-anderson** [comment]
Drush will look for preferences in a directory named 'drush' in the folder above the document root. Perhaps this code could detect and exclude directories that were entire Drush installs.

You should try with 8.3.0 and see if that works better, too.
