### ISSUE TITLE
Can not run into drupal 8.5.0 even after run  composer require drush/drush.

### ISSUE THREAD

**Issue by dravenk** [drush-ops/drush#3457]
There are a error after run drush status.
```
[preflight] The YAML value does not appear to be valid UTF-8.
```

**Comment by greg-1-anderson** [comment]
Try temporarily removing your drush.yml file/files and any alias files. Sounds like there may be a bad value in one of them.

**Comment by paolobareze** [comment]
I fixed this same issue by editing the drush.yml file in my text editor (Geany), it was already set to UTF-8 encoding, but by making no changes and then saving again to the server it got rid of the error.

**Comment by lukewebdev** [comment]
I am getting this error even if I remove the drush.yml completely. Where should this file be put for a site-specific drush.yml?
