### ISSUE TITLE
The "--reserve-margin" option does not exist in Drush 9

### ISSUE THREAD

**Issue by hamrant** [drush-ops/drush#3458]
`
$ drush --version
Drush Commandline Tool 9.2.1
`
I have updated drupal core to 8.5.0 and it require drush 9, so I have ported my custom commands and got this error.
Mu custom command use drush_invoke_process for run another custom command multiple in background. 

Drush Command for multiple commands run:
```
  /**
   * Run stress test.
   *
   * @param int $count
   *   How many processes to run (default - 1)
   *
   * @command slp:run-stress-test
   * @aliases slp-run-stress-test
   */
  public function runStressTest($count = 1) {
    $this->logger()->log('success', dt('Run multiple @count processes.', ['@count' => $count]));
    drush_invoke_process(
      '@self',
      'slp-test',
      [],
      [],
      ['invoke-multiple' => $count, 'fork' => TRUE, 'concurrency' => $count]
    );
  }
```
Sub command that was run from `drush_invoke_process`:
```
  /**
   * Run test operation.
   *
   * @command slp:test
   * @aliases slp-test
   */
  public function test() {
    // Some custom logic.
  }
```
Looks like `drush_invoke_process` run this custom sub command with "--reserve-margin" option that does not exist in drush 9. With drush 8 all works fine

**Comment by hamrant** [comment]
`drush/drush/includes/backend.inc:1021`:
```
  if (!empty($common_backend_options['interactive']) || !empty($common_backend_options['fork'])) {
    foreach ($cmds as $cmd) {
      $exec_cmd = $cmd['cmd'];
      if (array_key_exists('fork', $common_backend_options)) {
        $exec_cmd .= ' --quiet &';
      }
```
Looks like in drush 9 `fork` option work only with `interactive`. If I set `interactive` option for `drush_invoke_process` it works without errors:
```
    drush_invoke_process(
      '@self',
      'slp-test',
      [],
      [],
      ['invoke-multiple' => $count, 'fork' => TRUE, 'concurrency' => $count, 'interactive' => FALSE]
    );
```

**Comment by weitzman** [comment]
Correct - that option has been deprecated. The whole backend.inc is slated for a rewrite one day.
