### ISSUE TITLE
Scripted use of Drush 9 behaves differently from non-scripted use.

### ISSUE THREAD

**Issue by FatherShawn** [drush-ops/drush#3459]
I'm filing this here because the change in setup was the move to Drush 9.

I trigger `drush cim` in a Robo `taskExecStack` which does not pickup `config_split` settings in the proper way, but the exact same command then pasted into my shell works as expected.

In Robo's subshell:

```
[ExecStack] Running docker-compose --tlsverify --tlscacert="/Users/shawnduncan/.docker/machine/machines/dp-docker/ca.pem" --tlscert="/Users/shawnduncan/.docker/machine/machines/dp-docker/cert.pem" --tlskey="/Users/shawnduncan/.docker/machine/machines/dp-docker/key.pem" -H=tcp://192.168.99.100:2376 exec cli drush -y cim
+------------+--------------------+-----------+
| Collection | Config             | Operation |
+------------+--------------------+-----------+
|            | block.block.footer | Update    |
+------------+--------------------+-----------+
```

In a regular shell:

```
$ docker-compose --tlsverify --tlscacert="/Users/shawnduncan/.docker/machine/machines/dp-docker/ca.pem" --tlscert="/Users/shawnduncan/.docker/machine/machines/dp-docker/cert.pem" --tlskey="/Users/shawnduncan/.docker/machine/machines/dp-docker/key.pem" -H=tcp://192.168.99.100:2376 exec cli drush -y cim
+------------+--------------------+-----------+
| Collection | Config             | Operation |
+------------+--------------------+-----------+
|            | core.extension     | Update    |
|            | block.block.footer | Update    |
|            | shield.settings    | Delete    |
+------------+--------------------+-----------+

 // Import the listed configuration changes?: yes.

 [notice] Synchronized extensions: uninstall shield.
 [notice] Synchronized configuration: update block.block.footer.
 [notice] Finalizing configuration synchronization.
 [success] The configuration was imported successfully.
```

Any suggestions on how what is different between the two contexts?

**Comment by weitzman** [comment]
Using latest drush9? I have no idea here.

**Comment by FatherShawn** [comment]
Yes: 9.2.1 - It seems pretty weird.  I'll also create an issue with config_split.  Maybe it's how they built the command - I'll post back and close this if I find an answer.

**Comment by weitzman** [comment]
Note that config split kicks in only if 2 paths are identical. See https://github.com/drush-ops/drush/blob/master/src/Drupal/Commands/config/ConfigImportCommands.php#L168. Perhaps you could debug and see if that check is not matching in your case.

**Comment by FatherShawn** [comment]
The difference between the two is that I simply omitted the config import from my script and ran it after.  My script clears cache, which allowed the proper behavior.

From the config_split [issue queue discussion](https://www.drupal.org/project/config_split/issues/2952568#comment-12524265):

> The status of the split is cached in the plugin cache, so it depends on which config overrides were active when the plugin cache is built.

So this used to work because **drush updb** comes earlier in the script.  Drush 8 also rebuilt cache as part of this command but I see no such report in in Drush 9 output.  Adding an additional **drush cr** before config import returned the prior experience.

**Comment by weitzman** [comment]
Happy you sorted it.

There should be a cache clear at end of updb. See https://github.com/drush-ops/drush/blob/44daf5422d3f1cba04bdc36df22a16890c7ba8bd/src/Commands/core/UpdateDBCommands.php#L470-L477
