### ISSUE TITLE
Document requirements for environment names in an alias file

### ISSUE THREAD

**Issue by darrenoh** [drush-ops/drush#3460]
I tried using 6, 7, and 8 as environment names in a site alias file. This was necessary to make my Drush 9 aliases match my Drush 8 aliases. The first numeric environment name was ignored and the second and third were changed from 7 and 8 to 1 and 2.

**Comment by weitzman** [comment]
Drush9 has strict rules about env names. Drush 8 did not. This is by design. Not sure that these are documented anywhere. Repurposing this issue. Ping @greg-1-anderson.

**Comment by weitzman** [comment]
Now documented at https://github.com/consolidation/site-alias. There are 2 links to there from drush docs.

**Comment by greg-1-anderson** [comment]
My documentation efforts at site-alias were kind of rushed; not all of the capabilities inherited from consolidation/config & c. are described. Documentation requests and, even better, documentation PRs at https://github.com/consolidation/site-alias would be welcome.
