### ISSUE TITLE
Updatedb command doesn't work on Windows

### ISSUE THREAD

**Issue by wongjn** [drush-ops/drush#3462]
OS: Windows 10
Drush: 9.2.1

When trying to run `updatedb` command (some parts masked with `...`):
```
dr updatedb
'C:/.../AppData/Roaming/Composer/vendor/drush/drush-launcher/bin/drush' is not
recognized as an internal or external command,
operable program or batch file.
 [error]  The command could not be executed successfully (returned: 'C:/.../Roaming/Composer/vendor/drush/drush-launcher/bin/drush' is not recognized as an internal or external command,
operable program or batch file.
, code: 1)
```
Conversely with `status`:
```
dr status
 Drupal version   : 8.5.0
 Site URI         : default
 DB driver        : mysql
 DB hostname      : localhost
 DB port          :
 DB username      : root
 DB name          : ...
 Database         : Connected
 Drupal bootstrap : Successful
 Default theme    : ...
 Admin theme      : seven
 PHP binary       : C:\wamp64\bin\php\php7.0.28\php.exe
 PHP config       : C:\Users\...\AppData\Local\Temp\5144.tmp
 PHP OS           : WINNT
 Drush script     : C:/Users/.../AppData/Roaming/Composer/vendor/drush/drush-l
                    auncher/bin/drush
 Drush version    : 9.2.1
 Drush temp       : C:\Users\...\AppData\Local\Temp
 Drush configs    : C:\Users\...\Sites\elf\vendor\drush\drush/drush.yml
 Install profile  : elf_profile
 Drupal root      : C:\Users\...\Sites\.../public_html
 Site path        : sites/default
 Files, Public    : sites/default/files
 Files, Temp      : c:/wamp64/tmp
```

**Comment by lamp5** [comment]
I had the same problem yesterday. I installed D8.5 using composer on my local xampp server and try to run drush command from web directory. After install drush global on my pc, the problem still existed, after spend a hour under this I discover that drush running correctly from directory 1 lvl up. But in my case drush pm:enable do not work.

**Comment by enzodev** [comment]
I suppose you are using Drupal and you installed drush-launcher, I suppose drush command is working and is recognized BUT "drush updatedb" is not working.
If so, all the docs on the web about this bug are outdated or wrong. This is what I did and it worked (just tested on Windows 10).

In this directory:
C:\Users\WRITE_HERE_YOUR_USER\AppData\Roaming\Composer\vendor\drush\drush-launcher\bin
create a drush.bat file
Open the file with a text editor and write these lines:

@echo off
php %~dp0\drush.php %*

That's it, now you can use "drush updatedb" on Windows.

**Comment by weitzman** [comment]
Thanks. That was recently documented at https://github.com/drush-ops/drush-launcher/pull/55/files
