### ISSUE TITLE
Drush does not always set the base path from option.uri

### ISSUE THREAD

**Issue by ao2** [drush-ops/drush#3463]
Hi,

I noticed that Drush 9.2.1 does not always set the drupal site [base path](https://api.drupal.org/api/drupal/core%21includes%21common.inc/function/base_path/8.5.x) from the `options.uri` setting, Drush 8 used to do that and in my [drupal-init-tools](https://ao2.it/en/blog/2017/08/02/drupal-init-tools-quick-and-easy-drupal-8-setup) workflow I relied on that behavior to make sure that the base path can be assumed to be the same regardless of being in a CLI context or in the web UI.

The issue can be demonstrated with drush 9 (in the drupal root, but that shouldn't matter with drush 9):

```
$ cd web/
$ ../vendor/bin/drush --uri='http://localhost/~ao2/test_site/web' php-eval 'echo base_path();'
/
```

Conversely with Drush 8 `base_path()` returned an usable value when setting options.uri (AFAIU being in the drupal root actually matters with drush 8):

```
$ cd ..
$ composer require drush/drush:8.x
$ rm drush/Commands/PolicyCommands.php 
$ cd web/
$ ../vendor/bin/drush --uri='http://localhost/~ao2/test_site/web' php-eval 'echo base_path();'
//~ao2/test_site/web/
```

BTW, the double leading slash shouldn't be there, but it's harmless.

If you are interested in some background info: having the same base path bewteeen cli and web UI is important for some modules which rely on it at install time, one example is [syntaxhighlighter](https://cgit.drupalcode.org/syntaxhighlighter/tree/syntaxhighlighter.module#n410).

The issue is not only about the Drupal function `base_path()`, it occurs also with `Url::FromUri('internal:/')` which does not use `base_path()` directly but relies on [Symfony Request](http://api.symfony.com/2.3/Symfony/Component/HttpFoundation/Request.html#method_getBasePath) instead.

Another example of a different behavior between Drush 8 and Drush 9 is in fact:

```
../vendor/bin/drush --uri='http://localhost/~ao2/test_site/web/' php-eval "use Drupal\Core\Url; echo  Url::FromUri('internal:/')->toString()"

```

It seems to occur in any case where the base path is calculated from some PHP server variables.

In particular `$_SERVER['REQUEST_URI']` seems to be of interest.

I see that Drush 8 sets this for all the commands in:

```
drush/lib/Drush/Boot/DrupalBoot.php:      $_SERVER['REQUEST_URI'] = $drupal_base_url['path'] . '/';
```

while Drush 9 seems to be doing it only in `SiteInstallCommands::serverGlobals()`.

```
drush/src/Commands/core/SiteInstallCommands.php:        $_SERVER['REQUEST_URI'] = $drupal_base_url['path'] . '/';
```

I think this issue has gone unnoticed mainly because:

1. Not a lot of modules use the base path at install time.
2. The majority of drupal installs seem to be in the web docroot (my dev sites are not, I use the userdirs module with Apache).
3. `drush site-intall` seems to be covered.

Without a consistent base path, module installation may fail when done via cli (I am thinking to `drush pm-enable` in particular).

Of course it is still responsibility of the user to set `options.uri` appropriately but I think Drush should honor it for **any command** when that is done.

Thanks,
   Antonio

**Comment by weitzman** [comment]
Your use of a subduer in the uri means you might be running into https://github.com/drush-ops/drush/pull/3166. If so, lets close this issue and work there.
