### ISSUE TITLE
Drush needs 'mysql' in the system path, but this isn't clear without --debug

### ISSUE THREAD

**Issue by runeasgar** [drush-ops/drush#3464]
drush cex just kept telling me the command wasn't defined. It wasn't until someone advised me to run with --debug that I noticed drush was choking because it couldn't find the mysql command.

I added this to my .bash_profile, which resolved the issue:
PATH=$PATH:/Applications/MAMP/Library/bin

This took almost an hour to diagnose with myself and 3 other people looking into the issue, and it was very hard to find any answers on Google about a missing "cex" command. I'm not sure if this is already in the documentation somewhere.. but if not, maybe it could be created? Or, if it exists, maybe it could be made easier to find?

**Comment by weitzman** [comment]
What version of Drush? We check for this in Drush 9.

**Comment by runeasgar** [comment]
Drush 9.2.1, launcher 0.6 (although I started on 0.5).

Here's the command I was running (in Drupal root):
$ drush cex
 Command “cex” is not defined.

And here's the line in --debug:
[bootstrap] The command ‘mysql’ is required for preflight but cannot be found. Please install it and retry.

**Comment by jannakha-copy-01** [comment]
this worked for me:
sudo ln -s /Applications/MAMP/Library/bin/mysql80/bin/mysql /usr/local/bin/mysql
