### ISSUE TITLE
Feature Enhancement: Config Export:  Add option to remove UUID and/or config-hash, only export config that has changed

### ISSUE THREAD

**Issue by lhridley** [drush-ops/drush#3468]
This would be an extremely useful (IMO) option for developers working on modules and/or installation profiles, to be able to export configuration and remove the UUIDs and/or config-hash from the exported config file instead of having to edit each exported config file.

It would also be useful to be able to export only those configuration files that have changed, with the UUID and/or config-hash removed.

**Comment by weitzman** [comment]
See various config related modules. This is too niche for core drush.

**Comment by lhridley** [comment]
Wow.

-1 for Drush
+1 for Drupal Console
