### ISSUE TITLE
The each() function is deprecated in PHP 7.2.

### ISSUE THREAD

**Issue by MPParsley** [drush-ops/drush#3469]
Deprecated: The each() function is deprecated. This message will be suppressed on further calls in drush/src/Drupal/Commands/pm/PmCommands.php on line 251

See https://www.drupal.org/forum/support/post-installation/2017-12-29/the-each-function-is-deprecated

See https://github.com/drush-ops/drush/pull/3472

**Comment by weitzman** [comment]
Fixed in #3472
