### ISSUE TITLE
Exceptions are not logged

### ISSUE THREAD

**Issue by attrib** [drush-ops/drush#3473]
Drush Version: 8.x, not tested for 9.x

Throwing an exception inside the drush command, will not log that exception in the error handler.

```
  function drush_test_test() {
    throw new Exception('test');
  }
```

This is catched by `_drush_invoke_hooks`

```
        try {
          $result = call_user_func_array($func, $args);
          drush_log(dt("Returned from hook !hook", array('!hook' => $func)), LogLevel::DEBUG);
        }
        catch (Exception $e) {
          drush_set_error('DRUSH_EXECUTION_EXCEPTION', (string) $e);
        }
```

Resulting in `_drupal_exception_handler` not being called, resulting in _drupal_log_error() not being called and therefor this message not going into the log.

I noticed this as we use syslog module and everything goes to a centralized logging system. But last week we had a bad error in a drush command resulting in a Exception and that exception wasn't logged anywhere as drush is running by cron with the output piped to /dev/null. In all other cases this works as everything else is logged normally to syslog.

**Comment by greg-1-anderson** [comment]
Drush 8 was not designed for exceptions. Please use `drush_set_error` directly in Drush 8. If you would like to use exceptions, please upgrade to Drush 9.

**Comment by greg-1-anderson** [comment]
In my answer above I focused on Exceptions, but I think the larger issue here is that the desire is for `drush cron` to ensure that any event that is generated is sent to Drupal's watchdog. This also was never part of Drush's design.

A pull request to add this enhancement could certainly be considered. In the meantime, though, I would suggest that you check for the result code from `drush cron` from the script that invokes it, and write an error directly to your syslog if the command fails.

**Comment by attrib** [comment]
Just to clarify this issue is related to any application exception or error for any drush command, not only drush cron. I didn't understand yet how drush9 works here as the code is rewritten a lot.

My custom drush command calls functions which are also called inside a normal node view. Here an exception was thrown which wasn't catch correctly. Now in drupal the `_drupal_exception_handler` is called, which takes care of the logging. In drush all Exceptions are catched in the mentioned try/catch from commands.inc. This exceptions are not logged with the Drupal logger.
So calling that function from UI, it gets logged. Calling it via drush, it doesn't get logged.
Same applies for an E_RECOVERABLE_ERROR. As drush uses own error_handler which also ignores the Drupal loggers.

In the meantime I added now a nasty try/catch over my complete drush command and added a own error handler which does the logging and then calls _drush_error_handler...

```php
function drush_MODULE_COMMAND() {
  set_error_handler(function ($errno, $message, $filename, $line, $context) {
    \Drupal::logger('xxx')->critical('Error while drush COMMAND. !exception !file:!line', [
      '!exception' => $message,
      '!file' => $filename,
      '!line' => $line,
    ]);
    return drush_error_handler($errno, $message, $filename, $line, $context);
  });

  try {
     // my real command code
  }
  catch (\Exception $e) {
      \Drupal::logger('xxx')->critical('Error while drush COMMAND. !code !exception', [
        '!code' => $e->getCode(),
        '!exception' => $e->getMessage(),
      ]);
  }
}
```

**Comment by greg-1-anderson** [comment]
Yeah, something like the above would be a useful addition for Drush. I'd say that it should probably be disabled by default, enabled via a Drush config option, and clearly labeled as a Drush issue (as you have done, but maybe put "Drush" at the beginning of the line).

**Comment by greg-1-anderson** [comment]
`class_exists('\Drupal')` would probably also be a good guard to ensure that Drupal was bootstrapped. Not necessary when added via a module as shown above, of course.

**Comment by mfb** [comment]
In https://www.drupal.org/project/raven/issues/3070478 I was playing around with how a contrib module could log exceptions in drush commands.

Maybe there is some other recommended way to do this, but so far I came up with
```
\Drush\Drush::service('eventDispatcher')->addListener(\Symfony\Component\Console\ConsoleEvents::ERROR, [$this, 'onConsoleError']);
```

My `onConsoleError` method will then get an event which contains an error/exception.
