### ISSUE TITLE
Get drush back into Debian

### ISSUE THREAD

**Issue by fredddii** [drush-ops/drush#3476]
Currently drush is no longer in Debian because the maintainer is no longer using drush. I have no experience into packaging nor do I have any package uploading rights.

Would it be possible for somebody to pick up the package?

**Comment by weitzman** [comment]
No longer applicable ... Drush is now installed as a dependency of your Composer project.

**Comment by fredddii** [comment]
I am confused. Which package do I install to get drush? I can not find drupal-composer or so.

**Comment by weitzman** [comment]
http://docs.drush.org/en/master/install/
