### ISSUE TITLE
Error: Command pm:enable is not defined.

### ISSUE THREAD

**Issue by asimlqt** [drush-ops/drush#3477]
I'm new to Drupal and having an issue installing a theme using drush version 9.2.1.

I've created a docker setup for installing Drupal which you can check out at:

https://github.com/asimlqt/docker-drupal

After completing the installation I installed a theme:

`composer require drupal/adaptivetheme`

And then tried to enable it but I get the above error:

```
docker exec -it web bash
./vendor/bin/drush en adaptivetheme
```

**Comment by weitzman** [comment]
Make sure your site can bootstrap during CLI requests. Try with -vvv for more debug info. Also, please use Drupal Answers for support questions.

**Comment by asimlqt** [comment]
Thank you for the -vvv tip. I've got it working now. Had to install mysql cli client.
