### ISSUE TITLE
Notice: Undefined index: name in InputHandler.php

### ISSUE THREAD

**Issue by MPParsley** [drush-ops/drush#3481]
When performing `drush generate test-unit` the following notice occurs:

Undefined index: name vendor/drush/drush/src/Commands/generate/Helper/InputHandler.php on line 102

```
            $default_machine_name = function ($vars) use ($modules, $root_directory) {
                $machine_name = array_search($vars['name'], $modules);
                return $machine_name ?: Utils::human2machine(isset($vars['name']) ? $vars['name'] : $root_directory);
            };
```

**Comment by weitzman** [comment]
ping @Chi-teck

**Comment by Chi-teck** [comment]
Same notice appears for theme related generators.
`drush generate breakpoints -v`

I think this callbacks were created before we decided not to ask a user for extension human name.

**Comment by Chi-teck** [comment]
So there is no point to check `$vars['name']` in default machine name callback and vise versa.
