### ISSUE TITLE
How to print a message to the console from a module when called with drush 9

### ISSUE THREAD

**Issue by gaelg** [drush-ops/drush#3486]
I made a custom module that implements hook_rebuild(). There's a drupal_set_message() in it. If I clear the caches from Drupal's UI, the message is shown. But it's not shown if I execute drush cr. Is there an easy way to print my message in both cases?
I tried both following commands with Drupal 8.5 and Drush 9.2.1, but I only get "[success] Cache rebuild complete."

`\Drupal::messenger()->addMessage($message); \Drupal::logger('my_module')->info($message);`

**Comment by weitzman** [comment]
I would expect the logger() call to be visible, when you run with `-v`. If it isn't, thats a bug.

I just added a PR to surface messenger() in the Drush log - #3489
