### ISSUE TITLE
Command "config-export" is not defined

### ISSUE THREAD

**Issue by Kwadz** [drush-ops/drush#3492]
With a fresh install of Drupal made in a Docker container with:

`composer create-project drupal-composer/drupal-project:8.x-dev /app --stability dev --no-interaction`

When I execute `drush config-export`, I get:

```
  Command "config-export" is not defined.

  Did you mean this?
      docs-config-exporting
```

Drush Commandline Tool 9.2.1

According to [the documentation](https://drushcommands.com/drush-9x/config/config:export/) this command is still supposed to exist.

**Comment by weitzman** [comment]
Did you install drupal? In any case the error message you are seeing
suggests that your site is not bootstrapping fully. Run with --vvv to see
more info.

**Comment by Kwadz** [comment]
> Did you install drupal?

Drupal is installed in the `web` directory of the project, the composer command that I mentioned does it automatically as explained [here](https://github.com/drupal-composer/drupal-project#what-does-the-template-do).

I executed the drush command with `-vvv`:

```
# drush config-export -vvv
 [preflight] Config paths: /app/vendor/drush/drush/drush.yml,/app/drush/drush.yml
 [preflight] Alias paths: /app/web/drush/sites,/app/drush/sites
 [preflight] Commandfile search paths: /app/vendor/drush/drush/src,/app/drush/Commands
 [debug] Bootstrap further to find config-export
 [debug] Trying to bootstrap as far as we can
 [bootstrap] Drush bootstrap phase: bootstrapDrupalRoot()
 [bootstrap] Change working directory to /app/web
 [bootstrap] Initialized Drupal 8.5.1 root directory at /app/web
 [bootstrap] Drush bootstrap phase: bootstrapDrupalSite()
 [bootstrap] Initialized Drupal site default at sites/default
 [bootstrap] Drush bootstrap phase: bootstrapDrupalConfiguration()
 [debug] Add service modifier
 [debug] Unable to validate DB: Unable to load Drupal settings. Check your --root, --uri, etc.
 [debug] Bootstrap phase bootstrapDrupalDatabase() failed to validate; continuing at bootstrapDrupalConfiguration()
 [debug] Done with bootstrap max in Application::find(): trying to find config-export again.

In Application.php line 618:

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "config-export" is not defined.

  Did you mean this?
      docs-config-exporting


Exception trace:
 Symfony\Component\Console\Application->find() at /app/vendor/drush/drush/src/Application.php:234
 Drush\Application->bootstrapAndFind() at /app/vendor/drush/drush/src/Application.php:191
 Drush\Application->find() at /app/vendor/symfony/console/Application.php:229
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /app/vendor/drush/drush/src/Runtime/Runtime.php:112
 Drush\Runtime\Runtime->doRun() at /app/vendor/drush/drush/src/Runtime/Runtime.php:41
 Drush\Runtime\Runtime->run() at /app/vendor/drush/drush/drush.php:64
 require() at /app/vendor/drush/drush/includes/preflight.inc:17
 drush_main() at phar:///usr/local/bin/drush/bin/drush.php:159
 require() at /usr/local/bin/drush:10
```

**Comment by weitzman** [comment]
``` [debug] Unable to validate DB: Unable to load Drupal settings. Check your --root, --uri, etc.```

Installing Drupal is a later step after you get the Drupal codebase into the web directory. You can do it over the web or with `drush site:install`. In any case, the error above indicates that Drush cannot query your DB. Thats what needs fixing. You can see what credentials Drush is trying to use with `drush sql:connect`

Drush cannot connect to to your database. You ei

**Comment by Kwadz** [comment]
OK I have found what happens. As Drupal runs into a Docker container, we use an alias for the database host name (instead of `localhost`). However I was executing drush locally (not into the container).

Running drush into the container solved the issue.
