### ISSUE TITLE
  The service "messenger.commands" has a dependency on a non-existent service "messenger".

### ISSUE THREAD

**Issue by MichaelMallett** [drush-ops/drush#3493]
Drush Launcher Version: 0.5.1
Drush Commandline Tool 9.2.2

Can't seem to run any commands except CR and site-install (that I can try so far). Only information provided, verbose gives me nothing. Clean install of entire site, running on PHP 7.1, ubuntu 16.04 (latest drupalvm). Service does exist in code, but not in container:debug. Restarted php, reinstalled, etc etc

Seems every week there's a new drush related challenge!

**Comment by weitzman** [comment]
what version of drupal?

**Comment by MichaelMallett** [comment]
Colleague downgraded through composer to 9.2.1 and had no problems.

**Comment by weitzman** [comment]
Working on a fix ...

**Comment by weitzman** [comment]
I pushed a fix. If you use dev-master in composer it should work with Drupal 8.4. Please let me know how it goes.

**Comment by chibi03** [comment]
@weitzman I just tested it with drupal 8.4.6 and it worked.

**Comment by weitzman** [comment]
I pushed a new patch release - 9.2.3. Thanks for the bug report and quick verification.
