### ISSUE TITLE
How to stop a system Drush binary from falling through to local binary?

### ISSUE THREAD

**Issue by danepowell** [drush-ops/drush#3500]
We're having some trouble with how Drush seems to automatically choose which version to run based on where it's called.

We have a project running on ACSF, which has Drush 8 installed globally and explicitly calls the `drush8` binary for all commands. ACSF is _only_ compatible with Drush 8.

Our project, however, is only compatible with Drush 9, so it includes its own copy of Drush 9 via composer and calls it explicitly for all commands.

The problem is that even though ACSF is explicitly calling the `drush8` system binary, our project-local Drush 9 ends up actually handling the commands, which breaks everything. Presumably this happens because `drush8` is being called in our docroot, Drush sees the local binary, and passes off the command.

My question is how can we stop Drush from "falling through" from the global to local version?

**Comment by weitzman** [comment]
Can you elaborate on the folder structure of your codebase, noting the location of the drush's and drupal?

**Comment by weitzman** [comment]
To answer your question, see https://drupal.slack.com/archives/C62H9CWQM/p1522683735000296 and replies

**Comment by greg-1-anderson** [comment]
Since Drupal slack does not save history, I'm copying the thread here:

> **moshe [8:58 AM]** Looks like you can bypass it by setting DRUSH_AUTOLOAD_PHP env variable. See https://github.com/drush-ops/drush/blob/7b698ef4683d9d642413658b650bf42ab8ed385d/src/Preflight/RedispatchToSiteLocal.php#L28-L69
> Look at `./sut` for an example of how that is set.
> **grasmash** [9:02 AM] @moshe thanks!
> **greg.1.anderson** [12:25 PM] @grasmash Please be aware that bypassing the redispatch is often a bad idea. This will work if the global Drush and site-local Drush have the exact same dependencies; however, redispatching from Drush to Drush in situations where the site-local Drush has newer or older dependencies is very likely to result in bad results.

If you want to use a global Drush with a Drupal site, please **remove** the site-local Drush from the site first. You are very very likely to encounter hard-to-diagnose failures if you mix dependencies like this.

**Comment by weitzman** [comment]
I second Greg's recommendation. Your composer project has the classes of drush 9 in it. You cant just go run Drush8 against that and have things work. Blame PHP or Composer or OO - just dont blame Drush!

**Comment by greg-1-anderson** [comment]
The "system-level" Drush bootstraps Drupal, which loads all project-level classes -- and by "loads" I mean "make available via the autoloader". Classes that are instantiated at least once prior to bootstrapping Drupal will use the version packaged with Drush; classes instantiated for the first time after bootstrapping Drupal will use the version packaged with Drupal. Note that it is therefore entirely possible to instate a class that is loaded from Drupal, but ends up calling the version of its superclass that is bundled with Drush.

It is possible to use Drush 9 as a global / "system-level" Drush. If you do this, then you should be able to mix Drush 8 and Drush 9 commandfiles in the same Drupal site.

If you continue doing what you are doing right now, you need to ensure that your global Drush has exactly the same dependencies as your Drupal site. Any variation in this will eventually cause failures. It's not easy to keep independent Composer projects in sync like this, so this is not recommended. Requiring `webflo/drupal-core-strict` in your global Drush 8 might help, but I wouldn't count on that necessarily being a guarentee.
