### ISSUE TITLE
Drupal 8 Messages are not surfaced if the command only bootstrap to "site"

### ISSUE THREAD

**Issue by gaelg** [drush-ops/drush#3501]
This is a follow-up to #3486: I figured out that my message appears in cli if I change the cache:rebuild annotations from "@bootstrap site" to "@bootstrap max". Otherwise, the message does not surface.

**Comment by gaelg** [comment]
Is this the expected behavior? I'd like to be able to see potential Drupal messages when I use drush cr.

**Comment by weitzman** [comment]
I think rebuild is a special case and we cant expect the Messenger integration to work in this case. So yes, expected behavior.

**Comment by gaelg** [comment]
All right, thank you for the clarification.
