### ISSUE TITLE
sql:sync errors out in Drush 9

### ISSUE THREAD

**Issue by kevinquillen** [drush-ops/drush#3502]
When I try the command

`drush @dev.dev @self sql:sync` it errors with:

```
Class constant &#039;MYSQL_ATTR_SSL_CA&#039; in Drush\Sql\SqlMysql->creds() (line 60 of /Users/kevinquillen/Servers/foo/vendor/drush/drush/src/Sql/SqlMysql.php).
 [error]  Drush command terminated abnormally due to an unrecoverable error. [5.47 sec, 7.92 MB] 
 [error]  Failed to import /tmp/foo_20180405_152230.sql.gz into target. [5.48 sec, 7.91 MB]
```

Not really sure where to go from here, I recently upgraded from Drush 8 to 9. The problem also happens on another project.

**Comment by weitzman** [comment]
alises go after the command name for sql:sync. see examples at `drush help sql:sync`

**Comment by kevinquillen** [comment]
Ah sorry, I typed it into the issue incorrectly.

`drush sql:sync @dev.dev @self ` or `drush sql:sync @dev.dev @local` produces the same error.

**Comment by weitzman** [comment]
I think your mysql client is not setup properly. Run `drush sql:status -vvv` and note the shell commands that are run. they have to be working for you at the shell in order for drush to work.

**Comment by kevinquillen** [comment]
It says `sql:status` command not found. Drush Commandline Tool 9.2.1.

When I run drush with no alias, it always errors.

However `drush @local sql:connect -vvv` works. A basic query with `sql:query` also works.

Inside the VM, I only get `Permission denied (publickey)`.

**Comment by weitzman** [comment]
Sorry, these are local issues. Please use Drupal Answers for support questions.

**Comment by kevinquillen** [comment]
But it worked prior to upgrading to 9 and running site alias convert?
