### ISSUE TITLE
Adhoc alias / sitespec broken

### ISSUE THREAD

**Issue by axel-rutz** [drush-ops/drush#3510]
```
$ drush8 user@host.com/path/to/root status
[OK]
$ drush9 user@host.com/path/to/root status
[Command not found]
```

**Comment by weitzman** [comment]
I'm pretty sure that this used to work in Drush9. Seems not anymore. Ping @greg-1-anderson

**Comment by axel-rutz** [comment]
Really sad. Repinging @greg-1-anderson ...

**Comment by greg-1-anderson** [comment]
This is definitely just a bug.

**Comment by greg-1-anderson** [comment]
Local site specs were working, but there was an error in remote site specs. Maybe this was introduced in a refactor; I didn't try to trace it down, I just fixed it.

I'll merge the PR once the tests come back green.
