### ISSUE TITLE
Drush not connecting to SQL database - after working fine for several months!

### ISSUE THREAD

**Issue by doingandlearning** [drush-ops/drush#3514]
Hi, 

I am using Drush 8.1.15 and working on a few different websites in both Drupal 7 and Drupal 8.  As of this morning, I have been getting errors whenever I try to execute *any* drush command within any of the site roots.  

Executing `drush` gets this:
`exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in                                                                                         [error]
/Users/user/Documents/workspace/website/website.com/drupal/www/includes/database/database.inc:321
Stack trace:
#0 /Users/user/Documents/workspace/website/website.com/drupal/www/includes/database/database.inc(321): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/user/Documents/workspace/website/website.com/drupal/www/includes/database/mysql/database.inc(66): DatabaseConnection->__construct('mysql:host=loca...', 'root', 'root', Array)
#2 /Users/user/Documents/workspace/website/website.com/drupal/www/includes/database/database.inc(1745): DatabaseConnection_mysql->__construct(Array)
#3 /Users/user/Documents/workspace/website/website.com/drupal/www/includes/database/database.inc(1535): Database::openConnection('default', 'default')
#4 /Users/user/Documents/workspace/website/website.com/drupal/www/includes/database/database.inc(2406): Database::getConnection('default')
#5 /Users/user/Documents/workspace/website/website.com/drupal/www/includes/bootstrap.inc(2193): db_query('SELECT 1 FROM {...', Array)
#6 /Users/user/Documents/workspace/website/website.com/drupal/www/includes/bootstrap.inc(2206): drupal_is_denied('127.0.0.1')
#7 /Users/user/Documents/workspace/website/website.com/drupal/www/includes/bootstrap.inc(2657): drupal_block_denied('127.0.0.1')
#8 /Users/user/Documents/workspace/website/website.com/drupal/www/includes/bootstrap.inc(2512): _drupal_bootstrap_page_cache()
#9 /Users/user/.composer/vendor/drush/drush/lib/Drush/Boot/DrupalBoot7.php(74): drupal_bootstrap(2)
#10 /Users/user/.composer/vendor/drush/drush/includes/bootstrap.inc(354): Drush\Boot\DrupalBoot7->bootstrap_drupal_database()
#11 /Users/user/.composer/vendor/drush/drush/includes/bootstrap.inc(509): drush_bootstrap(4, 7)
#12 /Users/user/.composer/vendor/drush/drush/commands/core/help.drush.inc(103): drush_bootstrap_max()
#13 [internal function]: drush_core_help()
#14 /Users/user/.composer/vendor/drush/drush/includes/command.inc(422): call_user_func_array('drush_core_help', Array)
#15 /Users/user/.composer/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#16 [internal function]: drush_command()
#17 /Users/user/.composer/vendor/drush/drush/includes/command.inc(199): call_user_func_array('drush_command', Array)
#18 /Users/user/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#19 /Users/user/.composer/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#20 /Users/user/.composer/vendor/drush/drush/drush.php(12): drush_main()
#21 {main}`

Running any other command e.g. `drush status` or `drush cc`:

`<h1>Additional uncaught exception thrown while handling exception.</h1><h2>Original</h2><p>PDOException: SQLSTATE[HY000] [2002] No such file or directory in drupal_is_denied() (line 2193 of /Users/user/Documents/workspace/website/website.com/drupal/www/includes/bootstrap.inc).</p><h2>Additional</h2><p>PDOException: SQLSTATE[HY000] [2002] No such file or directory in _registry_check_code() (line 3477 of /Users/user/Documents/workspace/website/website.com/drupal/www/includes/bootstrap.inc).</p><hr />Drush command terminated abnormally due to an unrecoverable error.                                                                                                                  [error]`

Things that I've tried:
- Checked that the SQL details hadn't changed in the sites/default/settings.conf files
- Rebooted the SQL server
- Uninstalling and reinstalling drush
- Changing the permissions on files within my sites, as follows from the site root:
` find . -type f | xargs chmod 644
 find . -type d | xargs chmod 755 `
- Dumping the database and re-importing database from a backup

**Comment by weitzman** [comment]
Please use Drupal Answers for support questions.
