### ISSUE TITLE
drush_backend_batch_process doesn't support class static method for "finished"

### ISSUE THREAD

**Issue by miteshmap** [drush-ops/drush#3515]
If you try to run a batch with `drush_backend_batch_process()`, using already existing static methods of a class, It does work for "operations", But it doesn't work for "finished". 

It should have work without any issue But as it's called like: 
`$batch_set['finished']($batch_set['success'], $batch_set['results'], $operations, $elapsed)`,  Instead it should have called using`call_user_func_array`

**Comment by weitzman** [comment]
Merged both PRs. Thanks.

**Comment by miteshmap** [comment]
👍 thanks @weitzman, That was real quick 💯
