### ISSUE TITLE
Add a base unit test class to make testing contrib module commands easier

### ISSUE THREAD

**Issue by jhedstrom** [drush-ops/drush#3530]
The current base unit test classes assume a quite specific test environment setup.

```php
        require_once __DIR__ . '/unish.inc';
        list($unish_tmp, $unish_sandbox, $unish_drush_dir) = \unishGetPaths();
        $unish_cache = Path::join($unish_sandbox, 'cache');

        self::$drush = $unish_drush_dir . '/drush';
        self::$tmp = $unish_tmp;
        self::$sandbox = $unish_sandbox;
```
This makes it difficult for contrib (and custom) modules to leverage the drush test framework.

Since properly written drush commands are light-weight wrappers to services that are readily unit-testable, the missing piece is a light-weigh test class that simply verifies command annotations are working as expected.

If drush shipped with such a test class, it would make testing contrib module commands easier (and potentially allow for these tests to be run on drupal CI).

The test class could extend `UnishTestCase`, but override the basic paths to drush to assume by default it is in `vendor/drush/drush/drush`, and assume it is sitting in a valid Drupal installation.

**Comment by weitzman** [comment]
We tried something like this at #3453. I found that solution a bit awkward. Maybe we can improve upon it here.

**Comment by weitzman** [comment]
That specific test framework is now gone in master. I think contrib tests that extend CommandUnishTestCase will just work.

**Comment by weitzman** [comment]
Um, I was wrong - there may be more work to do. 

> Since properly written drush commands are light-weight wrappers to services that are readily unit-testable, the missing piece is a light-weigh test class that simply verifies command annotations are working as expected.

Do you think this light weight test needs to execute the command or not? If not, an approach like https://github.com/consolidation/annotated-command/blob/master/tests/testAnnotatedCommand.php would work (but not this line https://github.com/consolidation/annotated-command/blob/master/tests/testAnnotatedCommand.php#L28). I'm not sure how much value there is in strictly testing command definition.

**Comment by weitzman** [comment]
And if we think that command execution is important, should we assume testing in a virgin site like Drupal core or testing in an installed site like [Drupal Test Traits](https://gitlab.com/weitzman/drupal-test-traits)? Or both.

**Comment by greg-1-anderson** [comment]
Regarding testing annotated commands, see the tests in [g1a/starter](https://github.com/g1a/starter).

I think a simple technique like that coupled with traits (similar to Drupal Test Traits) to make it easier to set up test fixtures is the way to go.

**Comment by weitzman** [comment]
See integration tests being made at #3809. Could be a basis for contrib testing.

**Comment by Sweetchuck** [comment]
Are there any work in progress?

**Comment by weitzman** [comment]
Done. See https://github.com/drush-ops/drush/tree/master/tests#drush-test-traits
