### ISSUE TITLE
Site install, site-name option truncated to first word

### ISSUE THREAD

**Issue by FlorentTorregrosa** [drush-ops/drush#3534]
Hello,

On Drush 9.2.3, when using site:install command, the option --site-name is truncated to the first word.

Example: "Drupal 8" will give on the installed website "Drupal".

My config and scripts are openly available at https://github.com/FlorentTorregrosa/docker-drupal-project.

I have put a var_dump in src/Commands/core/SiteInstallCommands.php install, and it is already truncated in the method parameters.

That's not something urgent.

Thanks for any help.

**Comment by weitzman** [comment]
Make sure you are quoting values like --site-name="Drupal 8". 

Feel free to post your full log output when running with --debug. I will then reopen the issue as needed.

**Comment by FlorentTorregrosa** [comment]
Thanks @weitzman for your reply.

You were right, it was missing quotes...
