### ISSUE TITLE
"Unable to copy" during pm-update on windows filesystem

### ISSUE THREAD

**Issue by jneubert** [drush-ops/drush#354]
The issue [Drush failing to download and save modules under windows](https://drupal.org/node/1801788) occurs also when a windows filesystem is shared to a linux vbox (e.g., for developing with phpstorm/vagrant or the like). The error messages are like:

```
Unable to copy /tmp/download_filezMMPkT to /vol/devcms/sites/all/modules/migrate-7.x-2.x-dev.tar.gz?date=1386717204.                                         [error]
```

This can be reproduced on the OS level in the linux box:

```
# touch  /vol/devcms/sites/all/modules/migrate-7.x-2.x-dev.tar.gz?date=1386717204
touch: cannot touch `/vol/devcms/sites/all/modules/migrate-7.x-2.x-dev.tar.gz?date=1386717204': Protocol error
```

The command without the question mark works fine - the windows filesystem cannot deal with the question mark in the file name.

The issue occured in 7.x-5.x-dev (and, due to the nature of the problem, presumably in other versions, too).

**Comment by kenorb** [comment]
Not sure if it's related, but tested with recent drush with `-vd` on OSX and I've got this:

    $ drush make -y --no-core ../base.make.yml 
    ...
	Merging existing ./sites/all directory [14.35 sec, 10.17 MB]                                                                
	Calling _drush_recursive_copy(/tmp/make_tmp_1446740507_563b821b0635d/__build__/sites/all, ./sites/all) [14.35 sec, 10.18 MB]
	Unable to copy /tmp/make_tmp_1446740507_563b821b0635d/__build__/sites/all to ./sites/all. [14.39 sec, 10.18 MB]             
	Cannot move build into place. [14.39 sec, 10.18 MB]                                                                         
	Returned from hook drush_make [14.59 sec, 10.18 MB]                                                                         

I believe my permissions are fine.

**Comment by greg-1-anderson** [comment]
The `pm-*` commands are maintenance support fixes only; closing.
