### ISSUE TITLE
Commands not loaded from ../drush/contrib

### ISSUE THREAD

**Issue by RoSk0** [drush-ops/drush#3543]
I am trying to [port](https://www.drupal.org/project/grn/issues/2930759) "Git release notes for Drush" Drush extension to Drush 9 API.

I followed https://weitzman.github.io/blog/port-to-drush9 updated command body as far as possible without actually running it but now I'm stuck because Drush don't see my new shiny command :( .

I used https://github.com/drupal-composer/drupal-project as a project template so my command located in {PROJECT_ROOT}/drush/contrib/grn/

```
$ tree drush/
drush/
├── contrib
│   └── grn
│       ├── composer.json
│       ├── drush.services.yml
│       ├── grn.api.php
│       ├── grn.drush.inc
│       ├── grn.info.yml
│       ├── README.txt
│       └── src
│           └── Commands
│               └── GrnCommands.php
├── policy.drush.inc
└── README.md

4 directories, 9 files

```

What am I doing wrong?

**Comment by RoSk0** [comment]
Figured out what the issue is. 

Because command files generated by `drush generate drush-command-file` are expected to be parts of the modules they are namespaced with `Drupal/$module/Commands`. This doesn't work for particular case because this is Drush extension and will leave outside of Drupal. Discovery methods for those two cases are different so that is why converted command was not found.

This is not exactly Drush 9 issue at the same time this should be captured somewhere, not sure where.

**Comment by weitzman** [comment]
not sure either. would be nice to `generate` to be able to make global commandfiles. we would have to ask a couple more questions.
