### ISSUE TITLE
drush failing to connect to remote mysql in docker setup

### ISSUE THREAD

**Issue by laurencefass** [drush-ops/drush#3546]
im running two docker containers - one nginx/php-frm/drupal connecting to a remote mysql server.

i used drupal site:install to install and the folder structure looks ok. i can't do anything useful with drush because it complains it can't connect to mysql

i added mysql-client after reading this was an essential (if undocumnted?) requirement but drush sql:cli hangs 

```
bash-4.3# drush sql:connect
mysql --user=root --password=admin --database=drupal --host=192.168.99.100 --port=3306
```

**Comment by laurencefass** [comment]
the actual website looks like this. no css no formatting. no blocks. the bare html url doesn't recognise the site user credentials.

```
Skip to main content
Error message
Unrecognized username or password. Forgot your password?
Log in
Username
Enter your Drupal username.
Password
Enter the password that accompanies your username.

```

**Comment by weitzman** [comment]
what happens when you run that `mysql` command on its own? if it fails then you have to fix that before drush can work.

**Comment by laurencefass** [comment]
? Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock'

I installed client with `apk add mysql-client '....

**Comment by weitzman** [comment]
A socket is not in play when you have a remote mysql. closing this, as your issues are unrelated to drush.

**Comment by laurencefass** [comment]
actually this works and allows me to connect so problem may be with drush configuration. how do i tell drush what to look at?

mysql --host=192.168.99.100 --user=root --password=admin --database=quickstart

**Comment by bartvanhoutte** [comment]
I'm having the same issue @laurencefass is having. I have a container running PHP and a container running MySQL and need to add `mysql-client` as a package to my PHP container which seems rather odd.

@weitzman Is there any reason Drush uses the local MySQL client instead of connecting through PHP?

**Comment by weitzman** [comment]
Yes - you can run queries against your DB even when Drupal bootstrap is broken.

**Comment by weitzman** [comment]
Drush master now uses PHP to connect to the DB when bootstrapping. So now a lot of commands don't require mysql-client. The sql:* commands still do, as does site:install.
