### ISSUE TITLE
Drush site alias has issues with case sensitivity in the folder name it's executed from.

### ISSUE THREAD

**Issue by anakinjay** [drush-ops/drush#3556]
Super weird bug here.

On my Mac, if I'm in the folder ~/sites/repos/drupal/sitename/docroot and try to run a drush alias like drush @alias.dev cr I get the following error:

```
PHP Fatal error:  Cannot redeclare composerRequiree5f6a9bb22591129afb0ed05cf7167b4() (previously declared in /Users/slayjay/Sites/repos/give/vendor/composer/autoload_real.php:63) in /Users/slayjay/sites/repos/give/vendor/composer/autoload_real.php on line 70
```
However, if I change to the folder ~/Sites with a capital S it works fine.  On my mac the folders are not case sensitive so that's the exact same folder, but it only works if I go into it using a capital S.

You can see in the error message drush is looking at Sites with a capital S and Sites with a lower case s as two different folders and trying to load the auto-loader twice once from each folder.

**Comment by weitzman** [comment]
Thats not drush bug. Arguably its not a bug as you are using a case sensitive file system. I agree its surprising and frustrating. Just not fixable by Drush. We dont want to get in the business of "fixing" paths for the user.
