### ISSUE TITLE
Suggestions to improve bootstrap debug messages

### ISSUE THREAD

**Issue by wturrell** [drush-ops/drush#3560]
Drupal 7.59 (multisite), Drush 8.1.17-dev

I have a Drupal 7 multisite where Drush wouldn't load, and it took some time to [narrow down the cause to db_prefixes](https://github.com/drush-ops/drush/issues/2329).

In this instance `drush_valid_db_credentials()` succeeded, but `bootstrap_drupal_database_has_table()` didn't, because it was comparing a list of tables with prefixes to ones without.   None of that you'd be able to figure out from using `--debug`, however. 

For example, the end of the output for *pm-list* is:

```
Bootstrap to phase 1. [0.84 sec, 8.77 MB]
Bootstrap to phase 6. [0.92 sec, 11.11 MB]
Bootstrap to phase 5. [0.92 sec, 11.11 MB]
Command pm-list needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command. [0.93 sec, 11.12 MB]
```

You could assume any of the following based on that:

- all three of those bootstrap attempts completed successfully (they're actually printed at the start)
- it got to phase 6 and given it "needs a higher bootstrap level to run" it must be failing on phase 7
- Drush attempted to bootstrap to phase 6 but failed, so fell back to phase 5

It's also unclear to people why bootstrapping is apparently happening multiple times.

In reality, it's failing on phase **4** (BOOTSTRAP_DRUPAL_DATABASE), but you might also be misled about that given --debug outputs a full list of DB tables and you can run `sql-*` commands without problem.

Things we could maybe do: 

(not submitting a PR at this stage due to (a) time (b) possibility this has come up before)

- Change 'Bootstrap to phase X' to 'Beginning bootstrap to phase X'
- in drush_bootstrap() and drush_bootstrap_validate(), add debug statement when `$bootstrap->{$current_phase}();` fails
- debug message in bootstrap_drupal_database_has_table() if table is missing
- warning about lack of db_prefix support if prefixes detected in settings.php (what precisely is the status of this, is it unsupported for all combinations of Drush/Drupal, or just some? have I missed a docs page somewhere?)

Thanks,
William

**Comment by weitzman** [comment]
These all seem like good ideas. db-prefix support was never really there. Its always been in a "might work" status.

**Comment by weitzman** [comment]
In Drush9 I changed to "Starting Bootstrap ..." in caeedc11. It looks to me like we are already emitting the other suggested messages.

The db prefix situation is not ideal. I guess a debug message makes sense. Not sure I would support a level higher than that. PRs welcome.
