### ISSUE TITLE
Bad/misleading/useless allocation warning

### ISSUE THREAD

**Issue by jptillman** [drush-ops/drush#3561]
Drush 9.2.3, Drupal 8.5.3

Running any drush command, I get the following warning output:
```
[warning] You have -1 allocated (minimum 32Mb, recommended 64Mb)
```
It seems to be tied to the php cli memory allocation, which on Ubuntu PHP 7.0 is always set to -1 (meaning no limit).  I'm fairly certain this is misleading since it seems to be trying to prevent memory exhaustion and "no limit" would prevent that.  Not to mention that it doesn't even tell you what setting it's really warning you about.  I'd suggest improving the warning even for values above -1.

**Comment by weitzman** [comment]
Thats not a drush message.

**Comment by jptillman** [comment]
Right you are, it appears to be CiviCRM:
```
vendor/civicrm/civicrm-core/Civi/Install/Requirements.php:      'details' => "You have $mem_string allocated (minimum 32Mb, recommended 64Mb)",
```
