### ISSUE TITLE
$_SERVER[HTTP_HOST] not set even when the --uri is provided or set via alias

### ISSUE THREAD

**Issue by jptillman** [drush-ops/drush#3562]
Drush 9.2.3, Drupal 8.5.3

Drush reports $_SERVER[HTTP_HOST] is not set even when the --uri is provided or set via alias

If I run `status` command:
```
$ drush @site status
 Drupal version   : 8.5.3
 Site URI         : http://www.site.com
 DB driver        : mysql
 DB hostname      : localhost
 DB port          :
 DB username      : prolydian
 DB name          : site
 Database         : Connected
 Drupal bootstrap : Successful
 Default theme    : bartik
 Admin theme      : seven
 PHP binary       : /usr/bin/php7.0
 PHP config       : /etc/php/7.0/cli/php.ini
 PHP OS           : Linux
 Drush script     : /var/www/html/connect/vendor/drush/drush/drush
 Drush version    : 9.2.3
 Drush temp       : /tmp
 Drush configs    : /var/www/html/connect/vendor/drush/drush/drush.yml
                    /var/www/html/connect/drush/drush.yml
 Install profile  : standard
 Drupal root      : /var/www/html/connect/web
 Site path        : sites/site
 Files, Public    : sites/site/files
 Files, Private   : /var/www/html/connect/private/site
 Files, Temp      : /tmp
```

Now, the same installation but using `updb` command:

```
$ drush @site updb
 [warning] You have -1 allocated (minimum 32Mb, recommended 64Mb)
 [error]  The following PHP variables are not set: $_SERVER[HTTP_HOST]

 Requirements check reports errors. Do you wish to continue? (yes/no) [yes]:
```

**Comment by weitzman** [comment]
What is emitting that requirement? Is that a contrib module, custom module, core? You might have to do some debugging to get the answer.

**Comment by weitzman** [comment]
In any case, there is no HTTP in a CLI request so the requirement is buggy. as you can see the Site URI is fine. Drupal is happy.

**Comment by jptillman** [comment]
It appears to be CiviCRM having the issue, butting in where it's not wanted for some reason.  Didn't realize that Drush was formatting general errors like that.
```
vendor/civicrm/civicrm-core/Civi/Install/Requirements.php:      $results['details'] = 'The following PHP variables are not set: ' . implode(', ', $missing);
```

**Comment by msilvert** [comment]
https://lab.civicrm.org/dev/core/issues/750

**Comment by rg-viza** [comment]
$_SERVER variables are "supposed" to be read only. However in php from command line the $_SERVER['HTTP_HOST'] is not set since we're not running php in the httpd context. However, setting $_SERVER['HTTP_HOST'] in a drupal settings file, will remove this error with (*apparently) no ill effects to your drupal site. running drush in a drupal install with civicrm should not look for this variable to be set since you run drush in a shell with no httpd context.

**Comment by Rar9** [comment]
Getting this error, anything i can do?
