### ISSUE TITLE
can't enable bootstrap theme

### ISSUE THREAD

**Issue by GiorgosK** [drush-ops/drush#3563]
on a clean install using composer  I have done 

> $ composer require drupal/bootstrap
> ... 
> $ drush en bootstrap -y
>  [error]  Unable to install modules bootstrap due to missing modules bootstrap. 

meanwhile 

> $ drush pm:list
> ...
>   Core                  Stark (stark)                                                           Disabled   8.5.3     
>  Bootstrap             Bootstrap (bootstrap)                                                   Disabled   8.x-3.11

with drush 9.2.3

**Comment by GiorgosK** [comment]
bootstrap is in `themes/contrib/bootstrap`
but strangely now that I have tested uninstalling and then running 
`drush en bootstrap -y` again everything seems to be working correctly

**Comment by jptillman** [comment]
I'm getting this same error right now with Drupal 8.6.1, Drush 9.5.2 and Bootstrap 8.x-3.16

```drush pm:list``` lists the theme as Disabled, but ```drush en``` gives the same error as reported:

     Unable to install modules bootstrap due to missing modules bootstrap.

**Comment by weitzman** [comment]
In Drush9, please use `theme:enable`, not `module:enable`.
