### ISSUE TITLE
Use custom implementation of SiteAliasManager service

### ISSUE THREAD

**Issue by zaporylie** [drush-ops/drush#3565]
Is there a way to replace container's default SiteAliasManager with a custom one? I am planning to populate the list of available aliases based on a request to the external API.

**Comment by greg-1-anderson** [comment]
Replacing the SiteAliasManager is a non-starter, I'm afraid to say. If we did this, it would not be possible for two different extensions to add their aliases, as they would fight for control of the alias manager. Allowing alias managers to be chained together would be complex and hard to test.

What I would be open to would be adding well-defined hooks to the site alias manager to allow its behavior to be customized as necessary. I would recommend against making API calls whenever the list of available aliases is fetched from the site alias manager for two reasons, though:

1. This would be slow.
2. The list of all aliases is only occasionally fetched; usually the site alias manager determines whether an alias exists by looking for the file path it should be stored in, and loading only the necessary alias files.

What I would suggest for your use-case is that you make a command to refresh your aliases, and write them to disk. You could potentially auto-update this list e.g. when the user runs the `drush site:aliases` command. This can already be hooked.

**Comment by greg-1-anderson** [comment]
Oh, in context of the above plus https://github.com/amazeeio/lagoon/issues/147#issuecomment-387704344, it is now more clear to me what you are trying to do.

If you do indeed make an external filesystem mount with your alias files, that should just work without needing to hook or replace the site alias manager. You'd just need to add another location for Drush to search for aliases. This is already configurable.

**Comment by weitzman** [comment]
FYI, we just moved SiteAliasManager to [its own project](https://github.com/consolidation/site-alias). Still not easily pluggable though. Not sure if this request belongs here or in that project.

**Comment by greg-1-anderson** [comment]
It's fine by me if we move all alias-related issues to consolidation/site-alias. I suspect that this issue can be closed, though, as I think Amazee can do what they want without any additional hooks.

I'm still open to adding hooks if they are needed, though.

**Comment by MPParsley** [comment]
I'm getting these errors after the latest dev update: Uncaught TypeError: Argument 7 passed to Drush\Runtime\DependencyInjection::initContainer() must be an instance of Consolidation\SiteAlias\SiteAliasManager, instance of Drush\SiteAlias\SiteAliasManager given

**Comment by greg-1-anderson** [comment]
@MPParsley That is unrelated to this issue. Please open a new report with more information, e.g how you installed Drush, whether @sitealias is local or remote, whether there is a site-local Drush in the target site, are both versions of Drush the same, etc.

**Comment by MPParsley** [comment]
I created an issue here https://github.com/drush-ops/drush/issues/3611

@greg-1-anderson sorry for the off-topic comment. I assumed it was related as @weitzman reported here that SiteAliasManager had moved to its own project which seems to be the source of the error.

**Comment by greg-1-anderson** [comment]
There's nothing Drush needs to do here; the request on the OP can be done with existing Drush features.
