### ISSUE TITLE
My global command is no longer found with 9.3.0

### ISSUE THREAD

**Issue by jurgenhaas** [drush-ops/drush#3566]
First of all, the namespace in the global command is `Drush\Commands` and it lives in `PROJECT_ROOT/drush/contrib/dev_modules/src/Commands/DevModulesCommands.php`

In the drush.yml I have defined the include path and when running with debug I can see that the path is included:

```
drush dev --debug
 [preflight] Redispatch to site-local Drush: /var/www/html/vendor/drush/drush/drush.
 [preflight] Config paths: /etc/drush/drush.yml,/var/www/html/vendor/drush/drush/drush.yml,/var/www/html/drush/drush.yml
 [preflight] Alias paths: /var/www/html/web/drush/sites,/var/www/html/drush/sites
 [preflight] Commandfile search paths: /var/www/html/vendor/drush/drush/src,./drush/contrib
 [debug] Bootstrap further to find dev
```

Still, the command isn't found. The module in question is https://www.drupal.org/project/dev_modules

Can you please help me to understand what's wrong?

**Comment by weitzman** [comment]
global drush commands no longer distribute as modules. they usually are just placed in a /drush dir. if you want to distrbute one, you would do so as a composer package thats of type=drupal-drush.  if the user has https://github.com/drupal-composer/drupal-project/blob/8.x/composer.json#L68 then it should get downloaded to /drush/contrib/[name].

our generator for drush commands currently assumes your command will ship in a module. perhaps thats what tripped you up.

**Comment by jurgenhaas** [comment]
Thanks @weitzman, the way this "module" is defined now has been working up until drush 9.2 just fine and we came up with the workaround with the infrastructure team to make it work although it's not really a product.

I'm happy to change this to a composer package. Can you explore the structure inside /drush/contrib/[name] then?

**Comment by weitzman** [comment]
Yes, we changed this in 9.3, as the existing behavior was a bug. I tried to note this in the release notes but I was still fuzzy on details.

This is working for me:

Filename: `$PROJECT_ROOT/drush/Commands/dev_modules/DevModulesCommands.php`
Namespace: `Drush\Commands\dev_modules`

ping @greg-1-anderson in case I've missed a nuance here. we do need to clarify docs at http://docs.drush.org/en/master/commands/#global-drush-commands. For example, the above namespace is longer than the one mentioned there.

**Comment by greg-1-anderson** [comment]
Yeah there was a bug in the namespace generation that we fixed. This is going to break some global commands, but it will be better / more consistent in the long run. Sorry for the inconvenience.

**Comment by eiriksm** [comment]
Had some issues as well, and just wanted to see if I understand things correctly before I make the required changes to this project.

So, correct me if I am wrong, but as far as I see it also applies to a projects composer configuration then? Not only to authors of commands? Can I no longer use `$PROJECT_ROOT/drush/contrib/` as folder for `drupal-drush` types of compoesr packages (at least a couple of variations I tried to get it to work with this change)? Seems like something we should fix in the drupal-project composer.json as well, if this is the case? :)

**Comment by zaporylie** [comment]
Correct me if I am wrong but does it mean that from now on custom hooks/commands implemented on per-project basis, such as https://github.com/drupal-composer/drupal-project/blob/8.x/drush/Commands/PolicyCommands.php will now be placed in the same directory as contrib `drupal-drush` packages? This will make it slightly inconvenient to exclude the latter one with .gitignore.

**Comment by jurgenhaas** [comment]
I've now fixed it for https://www.drupal.org/project/dev_modules and my projects now look like this:

```
PROJECT_ROOT/----drush/----Commands/----dev_modules/DevModulesCommands.php
                      |----sites/----
                      |----drush.yml
            |----composer.json
```

In `composer.json` there are entries like these:

```json
{
  "require": {
    "drupal/dev_modules": "1.x-dev",
  },
  "extras": {
    "installer-paths": {
      "drush/Commands/{$name}": [
        "type:drupal-drush"
      ]
    }
  }
}
```

This is now working OK and I hope that this API is not going to change again anytime soon ;-)

**Comment by greg-1-anderson** [comment]
See https://github.com/drush-ops/drush/issues/3566, which attempts to repair some of the damage done by the change in Drush 9.3.0. The configuration in https://github.com/drush-ops/drush/issues/3566#issuecomment-392007132 should still be supported. Please try it and provide feedback.

**Comment by jurgenhaas** [comment]
Confirmed, just tested this with Drush 9.4.0 and it is still working as before. Thanks @greg-1-anderson

**Comment by greg-1-anderson** [comment]
@jurgenhaas Please test with dev-master and see if it still meets your needs. We made more improvements here that should still be compatible with 9.3.0 and 9.4.0. If you have any issues, it would be good to know before we tag 9.5.0, which should be happening shortly.

**Comment by greg-1-anderson** [comment]
In 9.5.0, it should be possible to put `"drush/Commands/contrib/{$name}"` in your `installer-paths`, and `contrib` should NOT be part of your resulting namespace.  This allows folks to use `drush/Commands/custom/{$name}` for site-specific commands committed directly to their repository. `contrib` and `custom` are the only supported names that are ignored.

`"drush/Commands/{$name}"` should still work.

**Comment by jurgenhaas** [comment]
Wanted to give this a try but getting the following exception:

```
TypeError: Argument 1 passed to Drush\Drupal\Commands\core\LocaleCommands::__construct() must implement interface Drupal\Core\Language\LanguageManagerInterface, instance of Drupal\Core\Extension\ModuleHandler given, called in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 266 in Drush\Drupal\Commands\core\LocaleCommands->__construct() (line 59 of /var/www/html/vendor/drush/drush/src/Drupal/Commands/core/LocaleCommands.php).
```

Looks like something in the dev release is currently broken? Using Drupal 8.6.1 here.

**Comment by jurgenhaas** [comment]
I have changed the constructor of `Drush\Drupal\Commands\core\LocaleCommands` into `__construct(ModuleHandlerInterface $moduleHandler, StateInterface $state)` and now Drush's bootstrap works again.

The handling of contrib and custom directories inside of drush/Commands does work nice as well. Little improvement but much appreciated. Now we have similar logic to modules, profiles and themes which is perfect.

**Comment by weitzman** [comment]
Thats odd. The existing constructor looks OK based on the service definition

https://github.com/drush-ops/drush/blob/af64eb79ba7419606ea8d94a522124c45f1d9993/src/Drupal/Commands/core/drush.services.yml#L29-L34

Before af64eb79ba7419606ea8d94a522124c45f1d9993 on 9/13, he service was as you describe. I suspect you updated code without doing a `drush cr`. Thats required in order to update drush's services in the drupal container.

**Comment by jurgenhaas** [comment]
Shame on me :-( You're right and I can confirm that everything regarding the original topic is working with the latest dev release too.
