### ISSUE TITLE
drush 9 does not discover annotations in sites/[..]/modules

### ISSUE THREAD

**Issue by ideb** [drush-ops/drush#3568]
Assume the following site structure built by https://github.com/drupal-composer/drupal-project

htdocs/modules/contrib
htdocs/modules/custom
htdocs/sites/example.com/modules/custom (which contains a module with a custom entity type 'user_preference')
vendor/drush

When running `drush9 @example.dev cr --debug`
```
Using the Drush script found at /Users/.../git/d8/vendor/drush/drush/drush using pcntl_exec
 [preflight] Config paths: /Users/.../.drush/drush.yml,/Users/.../git/d8/vendor/drush/drush/drush.yml
 [preflight] Alias paths: /Users/.../.drush/sites,/Users/.../git/d8/htdocs/drush/sites,/Users/.../git/d8/drush/sites
 [preflight] Commandfile search paths: /Users/.../git/d8/vendor/drush/drush/src
 [bootstrap] Bootstrap to site [0.22 sec, 7.33 MB]
 [bootstrap] Drush bootstrap phase 2 [0.22 sec, 7.33 MB]
 [bootstrap] Try to validate bootstrap phase 2 [0.22 sec, 7.33 MB]
 [bootstrap] Try to validate bootstrap phase 2 [0.22 sec, 7.33 MB]
 [bootstrap] Try to bootstrap at phase 2 [0.23 sec, 7.53 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalRoot() [0.23 sec, 7.53 MB]
 [bootstrap] Change working directory to /Users/.../git/d8/htdocs [0.23 sec, 7.53 MB]
 [bootstrap] Initialized Drupal 8.5.3 root directory at /Users/.../git/d8/htdocs [0.23 sec, 7.53 MB]
 [bootstrap] Try to validate bootstrap phase 2 [0.23 sec, 7.53 MB]
 [info] Undefined index: scheme DrupalBoot8.php:121 [0.23 sec, 7.53 MB]
 [bootstrap] Try to bootstrap at phase 2 [0.24 sec, 7.99 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalSite() [0.24 sec, 7.99 MB]
 [bootstrap] Initialized Drupal site example.localhost at sites/example.com [0.24 sec, 7.99 MB]
 [error]  The "user_preference" plugin does not exist. [4.11 sec, 74.76 MB]
```

When running `drush8 @example.dev cr`
  Cache rebuild complete.

**Comment by weitzman** [comment]
i've seen reports like this that modules in a multisite dir appear as if they are disabled after a cache:rebuild. dont think we know why yet. needs a reproducible case

**Comment by KeyboardCowboy** [comment]
I was able to dig this out a little further.  The Drupal Dependency Injection container contains a list of enabled modules in the parameters[container.modules].

![container php broxy8 2018-07-10 13-29-33](https://user-images.githubusercontent.com/1002715/42532846-524d594e-8445-11e8-990c-053c794e7e0f.png)

This fully-built container is stored in the `cache_container` table, from which it is retrieved until the next cache clear.

When I delete the record from the cache table and reload my site, the newly cached record contains more modules listed than if I rebuild the cache with drush, by the exact number of modules I have enabled in sites subdirectories.  It appears that drush's cache rebuilding is not scanning the sites directories when it builds the list of enabled modules.

I'll keep digging at this and create a separate ticket if necessary.

**Comment by KeyboardCowboy** [comment]
Moving my discussion over to #3391 as it seems more applicable.

**Comment by KeyboardCowboy** [comment]
Sounds like this is related to the same Drupal core issue: https://www.drupal.org/project/drupal/issues/2985199

**Comment by ideb** [comment]
Closing as a duplicate of #3391
