### ISSUE TITLE
Drush 5.9 shows 301 permanently moved errors

### ISSUE THREAD

**Issue by wvdvegt** [drush-ops/drush#3577]
Due to a Drupal7 site and a ISP that does not support phar I'm stuck with Drush 5.9 ((which used to work pretty nicely). No phar means no composer.

However since the last time I used it I now get 301 permanently moved messages when running a batch script up update my sites.

I tried the 6.x and 7.x branch with the same results (using git). The 8.x branch just failed with other funky issues.

Any suggest what to change to correct these 301's?

**Comment by weitzman** [comment]
301 is a web response. drush is not returning that as its not a web server.

also, drush5 is not supported anymore.

**Comment by wvdvegt** [comment]
That answer I could think of myself. 
I was asking if anybody new what has changed causing this. So where to look (probably some querying service moved).
