### ISSUE TITLE
Allow comma (or space) separated list of config items as argument to `drush cex`

### ISSUE THREAD

**Issue by timwood** [drush-ops/drush#3580]
Use case:
When running a Drupal migrate you may only want to export certain Drupal config to yml. Rather than running `drush cex` and having to remove a bunch of files, or going one-by-one in the Drupal config export single-item UI, it would be nice if the `drush cex` command took an argument with a list of config object machine names, perhaps separated by commas.

Would this be possible?

**Comment by Chi-teck** [comment]
I would apply the same to `drush cim` as well.

**Comment by weitzman** [comment]
We already support this for import with --partial.

I'm not too keen on this. You could export to a tmp dir and copy out what you need. Or use run config:get a few times.

**Comment by timwood** [comment]
Does `config:get --format` option allow for a full .yml file to be generated so that I can output the command results to a file? I haven't used this command much and the [command's option documentation](https://drushcommands.com/drush-9x/config/config:get/) doesn't have a list of supported formats.

Exporting to a tmp dir and copying out what I need is as burdensome as exporting to the default location and having to delete what you don't want.

**Comment by timwood** [comment]
Thanks for the note about drushcommands.com, I was looking for details on `drush config:get`, a place to link to from my comment, plus I didn't have access to Drush.

I'll check out `drush help config:get` when I can.
