### ISSUE TITLE
Drush.luncher: php54 not found

### ISSUE THREAD

**Issue by Nisarg1792** [drush-ops/drush#3582]
I have successfully installed drush in centos. but after when I used drush command. I am getting following error.  I am not sure, is path missing? or something else? 

usr/share/drush/drush.launcher: line 132: exec: php54: not found.

![image](https://user-images.githubusercontent.com/11726988/41304525-6953e652-6e3e-11e8-9477-a0880ac2a94c.png)

**Comment by weitzman** [comment]
please follow the [install instructions of this project](http://docs.drush.org/en/master/install/), instead CentOS. nowadays you use composer to install drush as a dependency of your project.
