### ISSUE TITLE
Installation instructions aren't clear

### ISSUE THREAD

**Issue by avibrazil** [drush-ops/drush#3584]
Installation instructions on http://docs.drush.org/en/master/install/ are not clear. Please consider you are talking to beginners when writing documentation. I consider myself advanced Drupal user, but correct Drupal installation and code administration with DevOps practices is very difficult and not clear for me. Its not just download a tar file anymore.

Should I install Drush first and then use it to install and manage Drupal? How ?
Should I install Drupal already with Drush? How?

The first link in the doc (https://github.com/drupal-composer/drupal-project) is extremely difficult to comprehend and demands advanced concepts as composer, templates, projects. It doesn't help.

So maybe "composer require drush/drush" would install drush for me on a modern Fedora Linux with a complete PHP stack, but it fails with message:

> The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Connection timed out

**Comment by greg-1-anderson** [comment]
1. You are correct: the installation instructions for Drush 9 are not clear for a beginner. It would be better if these instructions could be improved. A prerequisite for using Drush 9 is knowledge of Composer and understanding of drupal-composer/drupal-project, so the docs needed extend beyond just Drush.

2. `composer require drush/drush` should be run when your cwd is inside a Composer-managed Drupal site. Most folks use drupal-composer/drupal-project for this, which already contains Drush.

3. For a beginner, it would perhaps be best to start with installing the Drush launcher. It would be good if the Drush launcher had a command to download and set up a drupal-composer/drupal-project site.

4. The specific error you are reporting at the end is a service interruption at packagist.org. This can also be caused if you are attempting to use Composer over a very slow internet connection.

I know these points do not solve your issue, but improvements in this area will take some time.

**Comment by avibrazil** [comment]
For item 4, I’m not having issues with my internet connection. It’s probably something else. For item 3, I’ll try tomorrow, but your words make me feel like it’s not yet implemented.

Overall, my feeling this is not ready yet and I’ll have to wait a few more versions. I can’t currently install Drupal with clean commands on a script. Not with drush.

So let’s go back to tar.gz for now. Or maybe try Drupal Console too.

**Comment by greg-1-anderson** [comment]
Drupal Console also requires a Composer-based install for your Drupal site. If you find the instructions over there more comprehensible, you could follow the same steps for Drush.

If you want to continue working with the Drupal .tgz and pm-* commands, try Drush 8. You can still install that via its phar.

**Comment by avibrazil** [comment]
But Drush 8 declares itself not compatible with latest versions of Drupal.
Drush 8 goes up to Drupal 8.3. Right !?

**Comment by greg-1-anderson** [comment]
The Drush 8 status with Drupal 8.4+ is "happens to work", which is admittedly confusing. The reason it is not fully supported is that Drupal core may at any time make changes that would break Drush 8 support, and, for some changes, we would not be able to to fix it. There is also a small chance that a contrib module could cause problems, depending on how Symfony APIs are used.

So far we have not had any reports of problems with Drush 8 and Drupal 8.4.x or 8.5.x.

At this point in time, everyone should be leveling up their Composer skills, as in the future it will absolutely be the only option. If you're not quite there yet, you can continue to use Drush 8 for a while.

**Comment by TMWagner** [comment]
The comment about leveling up Composer skills is probably one of the most relevant takeaways I've seen in my search for fixing my broken Drush environment. 
That said, the [Instructions here](http://docs.drush.org/en/8.x/install-alternative/) seem to be somewhat contrary to my limited knowledge of Composer. My understanding of Composer is that it is intended to manage files at the PROJECT level. If that's the case, and certainly with the [Option A](https://www.drupal.org/docs/develop/using-composer/using-composer-to-manage-drupal-site-dependencies) method of installing Drupal 8, Composer installs an instance of Drush within a specific Drupal project instance. 

So - what is the best practice?  I'm developing both in Drupal 7 and Drupal 8. My working copy of Drush that was "global" until I installed D8 worked. Now it is very broken.

**Comment by greg-1-anderson** [comment]
If you want to use a global Drush 8, you can install via cgr per the link you shared above, or you can simply download the phar and put it in your PATH.

In terms of Composer being a tool to manage dependencies at a project level is very much the case. Specifically, Composer considers a project to be a set of dependencies that were all evaluated at the same time via `composer update`. When you install Drush as part of your Drupal site, Drush becomes part of your project. Its dependencies are evaluated at the same time that Drupal's dependencies are evaluated. Drush was designed to do this. If you run a global Drush, then it includes Drupal's autoloader along with its own. Doing this puts you at risk of "dependency hell". See 
https://pantheon.io/blog/fixing-composer-global-command

When running as a global install, Drush 9 attempts to get around or at least minimize the risk of dependency hell by avoiding the use of any external dependencies until after it loads Drupal's autoload files. (It uses some external dependencies, but mostly things that are not used in Drupal.) This tends to work pretty well. Drush 8 does not do that. We'd need to re-open https://github.com/drush-ops/drush/pull/2787 for that.

**Comment by avibrazil** [comment]
So my first finding is that composer fails because packagist.org host has issues with IPv6 !!!!!!!
I had to completely disable IPv6 on my Linux dev host (_sysctl -w net.ipv6.conf.all.disable_ipv6=1_) to be able to evolve. I'll post further commands as I'll learn them.
