### ISSUE TITLE
Add support for additional db's (sql-sync, sqlc, aliases, etc..)

### ISSUE THREAD

**Issue by 5n00p4eg** [drush-ops/drush#3585]
Sometimes I need to sync non-drupal database.  (migrate source) from one environment to another.

**Comment by weitzman** [comment]
you should be able to do that already. define the DB in drupal (see example.settings.php) and then specify an alternate --database in the site alias. note that i have not tried this yet with drush9. i do see that other sql commands take --database option.

**Comment by 5n00p4eg** [comment]
I don't see any database related docs around site alias. Site alias actually target one of settings.php which may have multiple databases.
Also drush sql-sync don't have --database key or any additional source/dest syntax.
