### ISSUE TITLE
Feature Request: Allow global drush 8.x to be run by itself, without drush finder, without having to set an obscure undocumented environment variable

### ISSUE THREAD

**Issue by jonpugh** [drush-ops/drush#3599]
Hi.

## Background

I've been struggling to prevent drush8  from using drush finder when being run in a drupal directory with drush 9.

I tried setting the DRUSH_FINDER_SCRIPT environment variable with PHP to override this, but it doesn't actually work when being run from an Aegir task: `drush @hostmaster hosting-task 123` is in the context of the hostmaster site, which then invokes provision_backend_invoke(), which then invokes drush_process_invoke() and so on. For whatever reason, I could not dynamically set that environment variable. I spent at least 2-3 hours trying.

Please see this issue for more detail. https://www.drupal.org/project/provision/issues/2953349

## Feature Request
Add a check for a global drush config variable that would stop finder from finding.
Something we could drop in drushrc.php, like "drush_global_finder_enabled" or something.

Thoughts?

**Comment by jonpugh** [comment]
I'm not trying to get any specific site to work, I'm trying to ensure the Aegir hosting system can host sites with drush 9 in them.

This is more about letting drush8 live on as a self contained thing... Having it call another command when it's in a different folder produces unexpected behavior. We want to run our drush8 global commands in isolation.

 We just need our drush global commands to be available no matter what folder we call "drush" from.

**Comment by greg-1-anderson** [comment]
Using Drush 8 on a site with Drush 9 in it is not a supported operation.

**Comment by jonpugh** [comment]
I'm starting to think you are 100% right 😏

`drush provision-install` literally includes drupal core, so if drush 9 is included in vendor and autoloader, 💥.

Looks like we need to rush to @Provision4!

**Comment by jonpugh** [comment]
Sorry, I need to try this again.

I can deal with the provision-install problem later. 

It still feels like there should be a way to call global drush 8 and know it will always respond with global drush 8.

Turns out @omega8cc figured this out! 

https://github.com/omega8cc/drush/commit/b9257ea97593443b37763a1eddd0096c20167fa1#diff-8a1bcc8d3ab0006f61e1e4a7e7d65a20

The paths it searches for is hard coded! What do you think our chances are of getting a patch committed that would allow this to be configurable?

**Comment by greg-1-anderson** [comment]
So, to be clear:

- If your target Drupal site does not have a site-local Drush, go ahead and use the global Drush. It will work fine. No special action should be necessary.
- If your target Drupal site does have a site-local Drush, then you must use the Drush that's bundled with your site.

It is wrong to ever try to use a global Drush in the later scenario, because you will eventually encounter some very hard-to-to-debug problems. If this scenario happens to work by some hack, and I can figure out how to break the hack, then I will break it, because it's dangerous behavior.

**Comment by greg-1-anderson** [comment]
See [Fixing the Composer Global Command](https://pantheon.io/blog/fixing-composer-global-command). The cause is different there, but the problem is the same.

**Comment by jonpugh** [comment]
>* If your target Drupal site does have a site-local Drush, then you must use the Drush that's bundled with your site.

Yes... if you are actually working on your site.

What I'm saying is some global drush8 commands are just global, they don't really care about the site, but sometimes I might want to run them from a Drupal directory. These global commands cannot be run in a Drupal directory if it happens to include drush 9, because drush 8 just gives up no matter what you do.

I might want that and I might want to also call`bin/drush` to get site local drush to do site specific stuff.

**Comment by greg-1-anderson** [comment]
If you have a Drush command that does not care about the site, maybe it should not be a Drush command. You could bundle those in a phar instread. See [g1a/starter](https://github.com/g1a/starter).

If you want to ignore a Drupal site and not bootstrap it regardless of the cwd, try:
```
drush8 @none my-global-command
```
I think that should work even if the cwd was at the Drupal root of a site with a site-local Drush 9. The Drupal site will not be bootstrapped, so the site-local Drush should not be called, and the autoloaders should not be mixed / catch fire.  If @none does not work correctly, I would be interested in trying to fix that (or accept a PR to do so).
