### ISSUE TITLE
Uncaught TypeError: Argument 7 passed to Drush\Runtime\DependencyInjection::initContainer() must be an instance of Consolidation\SiteAlias\SiteAliasManager, instance of Drush\SiteAlias\SiteAliasManager given

### ISSUE THREAD

**Issue by MPParsley** [drush-ops/drush#3611]
I'm getting these errors when running `drush @sitealias.test status` after the latest dev update: 

```
Uncaught TypeError: Argument 7 passed to Drush\Runtime\DependencyInjection::initContainer() must be an instance of Consolidation\SiteAlias\SiteAliasManager, instance of Drush\SiteAlias\SiteAliasManager given
```

- Drush 9.4-dev-gde44f93 is installed with composer
- @sitealias.test is a remote alias
- there is a site-local Drush in the target site
- both versions of Drush are the same

I resolved it for now by rolling back to Drush 9.3@stable. In order to roll back I had to downgrade symfony/var-dumper to 3.x as I ran into the following dependency issue:

    - Installation request for symfony/http-kernel (locked at v3.4.12) -> satisfiable by symfony/http-kernel[v3.4.12].
    - Installation request for drush/drush ~9.3@stable -> satisfiable by drush/drush[9.3.0].
    - Conclusion: don't install symfony/var-dumper v4.1.1
    - Installation request for symfony/var-dumper (locked at v4.1.1) -> satisfiable by symfony/var-dumper[v4.1.1].

Note, on the remote there is still a global drush (8.1.15).

**Comment by greg-1-anderson** [comment]
Please try again with the latest dev-master. I just tried to reproduce your scenario using:

- A global install of Drush 9 1844496e on my local system
- A remote site alias
- A global Drush 8 that received the remote dispatch
- A site-local Drush 9 (also 1844496e) on the target Drupal site

This setup correctly ran the site-local Drush 9 on the remote system when I tried it.

**Comment by greg-1-anderson** [comment]
Closing as "dependency hell" issue. Should work in typical cases.

**Comment by greg-1-anderson** [comment]
As I close this I also realize this might be cause by pulling the latest dev-master without running `composer install`

**Comment by ashishdeynap** [comment]
Finally, I got it fixed by updating global drush to the same version required by the project-specific drush.

**Comment by greg-1-anderson** [comment]
@ashishdeynap What version of Drush are you using for your global Drush and the project-specific Drush? Usually this mix should work, as the global Drush should redispatch to the project-specific Drush. When you run `drush status` in this configuration, does the path to the Drush script point to your global Drush, or the project-specific Drush?

**Comment by kristofferrom** [comment]
Also seeing this error when connecting to remote projects with Drush 9.
I'm running 9.7.1 on both local and remote project. 
There's both  Drush 8 and Drush 9 global installations on my computer (set up via [this approach](https://drupal.stackexchange.com/a/267520/23755)). Drush 8 works without issues.

**Comment by Insasse** [comment]
Sorry for waken up a "dead" Issue but I am getting the same error for me it could be fixed by replacing line 14 in Drush\Runtime\DependencyInjection.php "use Drush\SiteAlias\SiteAliasManager;" with "use Consolidation\SiteAlias\SiteAliasManager;"
