### ISSUE TITLE
drush.api.php is missing in Drush 9

### ISSUE THREAD

**Issue by phil-s** [drush-ops/drush#3613]
i.e. In Drush 8 this is https://github.com/drush-ops/drush/blob/8.x/drush.api.php

As with all Drupal *.api.php files, this file is incredibly useful for text editor tagging/indexing, so that any editor can tell you all about the API functions, use it to generate hook templates, etc, etc...

Can this please be restored?

**Comment by phil-s** [comment]
Ignore the hooks comment, then :)  Based on http://www.drush.org/api/master/ Drush 9 *does* still have an API, however.  Can that not be provided in a drush.api.php file?

Web-based API documentation is a poor second place to in-editor API documentation, so this feels like a significant loss.

**Comment by greg-1-anderson** [comment]
I don't think that the `drush.api.php` file can be used to represent the Drush API. If you find anything out about how to make useful in-editor documentation for the current API, a PR would be welcome.

**Comment by phil-s** [comment]
Ah well.  Offhand I've no idea, but I'll keep it in mind.  Thank you for the quick responses.
