### ISSUE TITLE
Drush (7) doesn't seem to recognize one site in multi-site linux install

### ISSUE THREAD

**Issue by agerard** [drush-ops/drush#3618]
Similar to https://github.com/drush-ops/drush/issues/1193 and others, where clearly drush isn't able to reach the necessary Drupal bootstrap level - can download but not enable modules, but can't run registry rebuild or anything requiring database writes - but I haven't seen any solutions that apply to my situation. Running a D7 multi-site install where all sites are serving pages as expected, and all sites except one (imported from another server) are working fine with Drush, some using mysql, some postgres. Here is output from running drush status on the problematic site:

>  Drupal version         :  7.59                                                        
>  Site URI               :  http://popgrid                                              
>  Database driver        :  pgsql                                                       
>  Database hostname      :  mydb                                                    
>  Database port          :  XXXX                                                        
>  Database username      :  popgrid                                                     
>  Database name          :  popgrid                                                     
>  PHP executable         :  /usr/bin/php                                                
>  PHP configuration      :  /etc/php/7.0/cli/php.ini                                    
>  PHP OS                 :  Linux                                                       
>  Drush script           :  /home/xxxx/.config/composer/vendor/drush/drush/drush.php 
>  Drush version          :  7.4.0                                                       
>  Drush temp directory   :  /tmp                                                        
>  Drush configuration    :                                                              
>  Drush alias files      :  /var/www/drupal7x/sites/all/drush/aliases.drushrc.php 
>  Drupal root            :  /var/www/drupal7x                                     
>  Site path              :  sites/popgrid 

 vs another working postgres site on the same server

> 
>  Drupal version                  :  7.59                                                        
>  Site URI                        :  http://pern                                                 
>  Database driver                 :  pgsql                                                       
>  Database hostname               :  mydb                                                   
>  Database port                   :  XXXX                                                        
>  Database username               :  pern                                                        
>  Database name                   :  pern                                                        
>  Drupal bootstrap                :  Successful                                                  
>  Drupal user                     :                                                              
>  Default theme                   :  omega_site2                                                 
>  Administration theme            :  seven                                                       
>  PHP executable                  :  /usr/bin/php                                                
>  PHP configuration               :  /etc/php/7.0/cli/php.ini                                    
>  PHP OS                          :  Linux                                                       
>  Drush script                    :  /home/xxxx/.config/composer/vendor/drush/drush/drush.php 
>  Drush version                   :  7.4.0                                                       
>  Drush temp directory            :  /tmp                                                        
>  Drush configuration             :                                                              
>  Drush alias files               :  /var/www/drupal7y/sites/all/drush/aliases.drushrc.php  
>  Install profile                 :  standard                                                    
>  Drupal root                     :  /var/www/drupal7y                                      
>  Site path                       :  sites/pern                                                  
>  File directory path             :  pern_files                                                  
>  Private file directory path     :  /tmp                                                        
>  Temporary file directory path   :  /tmp  

I would really appreciate any tips on troubleshooting this issue, since maintaining this site will be a real pain without full use of drush. Glad to provide any other pertinent info.

**Comment by greg-1-anderson** [comment]
Drush 7 is not supported. Please try again with Drush 8.

**Comment by greg-1-anderson** [comment]
Also, this sort of support request is not handled by Drush maintainers. You will have a better response rate if you use Drush 8 and ask your question on Drupal Stack Exchange.

**Comment by agerard** [comment]
Thanks all. In my search for solutions I'd seen several comments indicating this was the place to ask; clearly they were wrong.

**Comment by greg-1-anderson** [comment]
Please see the "Support" section of the main Drush documentation page:

http://docs.drush.org/en/master/

**Comment by agerard** [comment]
I have. But suspect your terse response was faster in resolving my issue, which promptly disappeared after upgrading to 8 (even with the unfortunate detour thru 9, which Composer thought was better but apparently doesn't work with D7).

**Comment by greg-1-anderson** [comment]
Issues in the Drush queue stay open if:

1. There are more action items that the maintainers must take to resolve the issue
2. The maintainers forget to close it
