### ISSUE TITLE
`drush cron` in container cannot connect to database in another container

### ISSUE THREAD

**Issue by mattacular** [drush-ops/drush#3621]
**Describe the bug**
When running Drupal 8 in a container for local development, if the database is running in another container, `drush cron` command fails seemingly due to DB connection issues. Other commands that interact with the database (such as `drush cr` and `drush status` work fine).

**To Reproduce**
Start a database (mysql or mariadb) in a container, from host machine or another container run `drush cron` command.

**Expected behavior**
Cron command will run.

**Actual behavior**
Generic db connection error is thrown:

```
root@snip:/var/www/html# drush status
 Drupal version         :  8.5.4
 Site URI               :  http://default
 Database driver        :  mysql
 Database hostname      :  mariadb
 Database port          :  3306
 Database username      :  casautil
 Database name          :  casablanca
 PHP executable         :  /usr/local/bin/php
 PHP configuration      :  /usr/local/etc/php/php.ini
 PHP OS                 :  Linux
 Drush script           :  /tmp/local/vendor/drush/drush/drush.php
 Drush version          :  8.1.17
 Drush temp directory   :  /tmp
 Drush configuration    :  /tmp/local/docroot/sites/default/drushrc.php
 Drush alias files      :
 Drupal root            :  /tmp/local/docroot
 Drupal Settings File   :  sites/default/settings.php
 Site path              :  sites/default
 Sync config path       :  ../config_sync/default

root@snip:/var/www/html# drush cron
Command core-cron needs a higher bootstrap level to run - you will   [error]
need to invoke drush from a more functional Drupal environment to run
this command.
The drush command 'cron' could not be executed.                      [error]
Drush was not able to start (bootstrap) the Drupal database.         [error]
Hint: This may occur when Drush is trying to:
 * bootstrap a site that has not been installed or does not have a
configured database. In this case you can select another site with a
working database setup by specifying the URI to use with the --uri
parameter on the command line. See `drush topic docs-aliases` for
details.
 * connect the database through a socket. The socket file may be
wrong or the php-cli may have no access to it in a jailed shell. See
http://drupal.org/node/1428638 for details.

Drush was attempting to connect to:
 Drupal version         :  8.5.4
 Site URI               :  http://default
 Database driver        :  mysql
 Database hostname      :  mariadb
 Database port          :  3306
 Database username      :  casautil
 Database name          :  casablanca
 PHP executable         :  /usr/local/bin/php
 PHP configuration      :  /usr/local/etc/php/php.ini
 PHP OS                 :  Linux
 Drush script           :  /tmp/local/vendor/drush/drush/drush.php
 Drush version          :  8.1.17
 Drush temp directory   :  /tmp
 Drush configuration    :  /tmp/local/docroot/sites/default/drushrc
                           .php
 Drush alias files      :
 Drupal root            :  /tmp/local/docroot
 Drupal Settings File   :  sites/default/settings.php
 Site path              :  sites/default
 Sync config path       :  ../config_sync/default
```

**Workaround**
Theoretically one could share the socket file using Docker volumes to mount it in both containers but configuring this correctly is tricky.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.1.17
| Drupal version? | 8.5.4
| PHP version     | 7.1
| OS?             | Linux/Debian Stretch

**Additional information**
This is only an issue when the database is containerized (which typically would only be done for local development).

**Comment by greg-1-anderson** [comment]
Your `drush status` does not say `Database : Connected`, so you are apparently not able to access your database.

You will have better luck using [Drupal Answers](http://drupal.stackexchange.com/questions/tagged/drush) for support requests. You might try a docker support channel if you're finding the db socket configuration tricky.

**Comment by mattacular** [comment]
Thanks, realized it is actually not due to socket connection issues but rather because the container running D8 and Drush did not have the `mysql`-cli util installed. 

It might be nice to add that as a suggestion to the general DB connection error as it seems to be dependency somewhere along the line?

**Comment by greg-1-anderson** [comment]
`Database : Not Connected` sounds like a great idea. A PR for this or additional documentation would be most welcome.

**Comment by weitzman** [comment]
FYI we already give a better error message in Drush9

https://github.com/drush-ops/drush/blob/34f7b17942f0dd83e17716096a71db846cca590b/src/Boot/DrupalBoot.php#L227-L229

**Comment by greg-1-anderson** [comment]
Didn't notice this was a Drush 8 issue.
