### ISSUE TITLE
Provide targetted cache clearing commands

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#3622]
**Is your feature request related to a problem? Please describe.**

'drush cr' means everything needs to be rebuilt on the next page load. On a big site, that takes a while. Sometimes, you know that you specifically want to clear the plugin discovery, or the hook discovery, or the entity cache for a particular entity type. Doing 'drush cr' seems like too big a hammer in these cases.

**Describe the solution you'd like**

A new version of the 'drush cc' command, which has various useful options such as:

- all entities
- specific entity type's entities
- entity type definitions
- plugin definitions for a particular plugin manager service
- hook implementations

**Describe alternatives you've considered**

Finding the right cache table in the database and doing it by hand. Or just doing 'drush cr'.

**Additional context**

None.

**Comment by weitzman** [comment]
The drush cache:clear command has a few targetted options. We cant add everything here. There is an API for other commandfiles to add more of them. See https://github.com/drush-ops/drush/blob/master/docs/hooks.md#custom-hooks.

**Comment by weitzman** [comment]
any of those caches dont exist anymore? see the code if you are unclear what they do.

yes there is a drush cache for commandfile discovery.

**Comment by joachim-n** [comment]
> yes there is a drush cache for commandfile discovery.

Huh, I'll have to file a separate issue for that, as on my systems, commandfile discovery runs every time. That's on multiple installs of Drush.

> any of those caches dont exist anymore? see the code if you are unclear what they do.

No, but they look a bit dated and D7-era. Plugins and entities are useful too, views probably less so.

Also, I don't think it makes sense to add further cache options to some other command. Where would it go? These are core caches, so it makes sense for Drush to handle them.

**Comment by weitzman** [comment]
OK, feel free to submit a PR for most important caches. I am sensitive to the select list getting too big so I may not go for all of them.

Just because a feature ships in Drupal core does not mean that core Drush needs to be the one to endure its support burden. There is plenty of edge case stuff in drupal core.

**Comment by joachim-n** [comment]
I'm going to add a plugin type cache clearing command to Plugin module: https://www.drupal.org/project/plugin/issues/3029763

However, it does clash a bit with Drush core's 'plugin' cache clearer.
