### ISSUE TITLE
Support import single configuration

### ISSUE THREAD

**Issue by rotemreiss** [drush-ops/drush#3628]
**Is your feature request related to a problem? Please describe.**
Today we are using both Drush and Drupal console for configuration management, the only functionality that we are currently missing in Drush is the config import single, which is used to import the config_split configuration file before importing all the other configuration (so if it was updated with a new blacklisted config - it won't be overridden during the current import).
There are possibly more cases, and the --partial solution is good, but I like it better to know that I am importing a specific config without creating new directories for sync files.

**Describe the solution you'd like**
Adding a new config:import:split command.

**Describe alternatives you've considered**
Adding another option to the current import command may work, but I think that it will be less good in the eyes of a developer (developer experience)

**Additional context**
-

I am providing a code that seems to work + unit tests update, but I couldn't test it on my local for some reason, will try again later (and probably will also see the result on CircleCI 😄 )

The changes list condition didn't work for some reason, I assume you guys may understand why much faster than me, I have added a @todo comment for that.

Those are the lines I tried:
```php
      if (!$storage_comparer->createChangelist()->hasChanges()) {
        $this->logger()->notice('There are no changes to import.');
        return;
      }
```

Thanks

**Comment by weitzman** [comment]
Lets discuss in #3629
