### ISSUE TITLE
Database migration and seeding for drupal

### ISSUE THREAD

**Issue by liaogz82** [drush-ops/drush#3631]
**Is your feature request related to a problem? Please describe.**
There are no modules in drupal that does database migration and seeding like laravel and cakephp. Current database management is just mysqldump which is bulky and difficult to do code review of schema difference and the data needed for UI layout

**Describe the solution you'd like**
Supplement existing sql commands with migration commands based on [phinx](https://github.com/odan/phinx-migrations-generator) library

**Describe alternatives you've considered**
tried to use the phinx libraries directly but you need to manually add in db connection details to their `phinx.yml` file. Would be better if drush uses phinx library as drush is already handling drupal database connection

**Comment by weitzman** [comment]
Drupal has own mechanism for propagating schema changes called [hook_update_n](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_update_N/8.5.x). Drush updatedb is a runner for it.
