### ISSUE TITLE
Case-sensititive issues with drush dl

### ISSUE THREAD

**Issue by barraponto** [drush-ops/drush#364]
`drush dl in-field-labels` will fail, while `drush dl In-Field-Labels` works.
I never saw any other project with capitals and hyphens, though. Only https://drupal.org/project/In-Field-Labels

**Comment by HongPong** [comment]
It would still be optimal to have it retry with all-lower-case if something with caps fails. Sometimes it retains the uppercase spelling even when you request lowercase. To clear this out,
$ drush cc drush
works.
