### ISSUE TITLE
I don't understand the documentation

### ISSUE THREAD

**Issue by maniac0s** [drush-ops/drush#3641]
**Existing document**
http://docs.drush.org/en/master/install/

**What are you attempting to do**
I want to run drush as described in http://docs.drush.org/en/master/usage/
"Drush can be run in your shell by typing "drush" from within your project root directory or anywhere within Drupal."

**In what way is the existing documentation unclear or incomplete**
The documentation tells me, that my project already has drush or should be completed with 
composer require drush/drush. I did that, both. I installed my Drupal using drupal-project via composer and I also ran an additionally composer require.

$ composer require drush/drush
Using version ^9.3 for drush/drush                        
./composer.json has been updated
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information                                                                                    Updating dependencies (including require-dev)         
Nothing to install or update
Writing lock file
Generating autoload files
> DrupalProject\composer\ScriptHandler::createRequiredFiles

It tells me "nothing to install or update"

drupal-project$ drush
bash: drush: command not found

??? what now 

But I can not do what the documentation tells me to do.

**What should the documentation say instead?**
Where does composer install drush, how can I access it, what is copied where, what subdirectory do I have to look into to run drush...

The documentation tells me to run composer require and then type drush in drupal directory.

I am aware that these things are for long time Drupal/Composer users maybe totally clear but for anyone who's not an expert, the documentations are lacking or depending on too much knowledge and don't mention where to get missing knowledge. That's not just in Drush but also happened in composer and Drupal itself.

Yes, it works if I walk the whole process installing drush globally using cgr but what's told in the documentation is still not clear if I want to have drush in my project so I can just deploy it, run composer install and have everything I need on the server.

**Comment by maniac0s** [comment]
Ok it seems when I go to my home directory, not the project directory, then I can install drush using composer global require and adding the path to my env. However I still don't understand how I can install/use drush from my project so that I can check it into the repository and have it available after just running composer install in the drupal directory as the documentation suggests.

**Comment by greg-1-anderson** [comment]
If you are using https://github.com/drupal-composer/drupal-project, then you may simply use `composer require drush/drush` to create a site-local Drush.

Please do not install Drush -- or any other PHP commandline tool -- using `composer global require`. Please use [cgr](https://github.com/consolidation/cgr) instead. See [Fixing the Composer Global command](https://pantheon.io/blog/fixing-composer-global-command).

**Comment by weitzman** [comment]
from project root, run `vendor/bin/drush`. if there is no file there,
then you need to `composer require drush/drush`

**Comment by maniac0s** [comment]
But that's not menitoned in the documentation at all or do I read the wrong pages?

http://docs.drush.org/en/master/usage/

"Drush can be run in your shell by typing "drush" from within your project root directory or anywhere within Drupal."

How's that supposed to run if "drush" is not in my PATH?

Don't get me wrong, I have no issues in typing vendor/bin/drush from within the project directory but when I go into the documentation and click of "usage" to find how to use drush, I can not get that information there at all.

**Comment by weitzman** [comment]
The docs are written assuming you complete 2. at http://docs.drush.org/en/master/install/. I see your point. However, it would be awkward to mention both `drush` and `vendor/bin/drush` all over the docs.

**Comment by maniac0s** [comment]
Yeah but the issue I had was, that it's saying "Optional" when it's actually not optional, because I either need to have drush launcher, drush globally or access it via vendor/bin/drush.

It would be enough however, if the doc explained at step 1 what composer does, that composer require drush/drush will throw drush in your project's directory at vendor/bin/drush by default - and then move to step 2 and 3 which then really is optional.

**Comment by weitzman** [comment]
Sounds promising. I'd love a PR for that change. See docs/install.md. Also you can make a PR right form the web without any git knowledge.
