### ISSUE TITLE
Rsync options after -- are not respected

### ISSUE THREAD

**Issue by johnpez** [drush-ops/drush#3643]
**Describe the bug**

I'm trying to follow the documentation to get --delete to work on drush core:rsync but I believe this functionality is simply broken.

Adding a option like --delete after a -- is not working. I'm trying commands like:

`drush core:rsync @site.prod ./ --mode="rakzlthv" -- --delete`

And superfluous files are not being deleted. If I add the --simulate argument like so:

`drush core:rsync @site.prod ./ --mode="rakzlthv" --simulate -- --delete`

I get an rsync command that doesn't show --delete:

`Calling system(rsync -e 'ssh -p 22 -i /user/.ssh/id_rsa' -rakzlthv developer@ip:/var/www/html/ ./);`

Am I doing something wrong? According to the docs it really looks like this should work.

Thank you!

**To Reproduce**
try a rsync command appending rsync options, such as -- --delete

**Expected behavior**
rsync to execute with the --delete option

**Actual behavior**
rsync executed without the --delete option

**Workaround**
Using a raw RSYNC command

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | I've tested on 9.3.0 and on dev-master.
| Drupal version? | 8.5.6
| PHP version     | 7.1
| OS?             | Mac

**Comment by greg-1-anderson** [comment]
Just tried this on master:
```
$ ./drush -s rsync a b -- --delete
Calling system(rsync -e 'ssh -o PasswordAuthentication=no' -akz --delete a b);
```
Looks okay to me. Could you try to isolate further and see if it's something in your options or your alias that might be causing the problem you're seeing? Or do you get different results when you run the command above?

**Comment by johnpez** [comment]
Interesting. Thanks for the quick response. 

I tried the same command and did get different output 
`Calling system(rsync -e 'ssh ' -akz a b);`

This is in a Lando container which now appears to be the issue, my command actually looks like:
`lando drush -s rsync a b -- --delete`

I probably should have isolated this before posting, but this does appear to be an issue with the Lando passthrough of Drush commands, if I execute your sample command directly without going through lando I get the expected result.

Thanks again. Will post back here if/when I find a workaround for Lando issue.

**Comment by greg-1-anderson** [comment]
I am guessing that the `lando' command is also interpreting the `--`. Maybe you need more than one `--` on the lando commandline.
