### ISSUE TITLE
mysql credentials leak in drush sqlc

### ISSUE THREAD

**Issue by durist** [drush-ops/drush#365]
I'm copying this verbatim from https://drupal.org/node/671906:

"drush sqlc" (and other commands that invoke the mysql cli) leak the database credentials. For example, after running "drush sqlc" I can see the password showing up in the "ps" listing.

My environment allows shell access to multiple Drupal vservers via a single file server, so this security bug renders drush practically unusable for my installation.

**Comment by greg-1-anderson** [comment]
As mentioned in #1175, new versions of mysql complain when using the credential-leaking options in the mysql tool.

This issue might be easier to resolve now that sql-sync has been refactored.

**Comment by weitzman** [comment]
@greg - this is issue is already closed and fixed.

**Comment by greg-1-anderson** [comment]
Nice!  Didn't even notice.  :P
