### ISSUE TITLE
8.x: Cleanup Return Values For drush_user_get_class()

### ISSUE THREAD

**Issue by alexfinnarn** [drush-ops/drush#3652]
**Describe the bug**
In the 8.x branch, `drush_user_get_class` can return a boolean although an instance of `\Drush\User\UserVersion` is always expected. 

So in https://github.com/drush-ops/drush/blob/8.x/commands/runserver/runserver.drush.inc#L113 you can try to call `->getCurrentUserAsSingle()` on a boolean. 

The real issue happens at https://github.com/drush-ops/drush/blob/8.x/includes/drush.inc#L122 where `drush_set_error()` returns a boolean https://github.com/drush-ops/drush/blob/8.x/includes/drush.inc#L1527.

Even though there is more to this issue that checking to see if a user passed in an ID to login as, I think the login attempt should only be done if the `user` option is passed in. When I read the command, I assume it just starts up a webserver, not that it automatically logs me in as the super user. I might not want that.

**To Reproduce**
I'm trying to run testing on a Backdrop CMS site on Travis CI. The Backdrop project has an abstraction layer around hijacking some commands to run differently and let others pass through safely to how the command is run in this project. 

I think this is public https://travis-ci.com/alexfinnarn/highlightjs_wysiwyg/builds/81946097#L796 but that has a link to the code.

**Expected behavior**
Logging a user in is only attempted if the argument/option is passed into the runserver command. 

The function signatures should be changed to reflect that the 

**Actual behavior**
`Call to a member function getCurrentUserAsSingle() on boolean in drush_core_runserver() (line 113...`

**Workaround**
I will try to wrap that logic in https://github.com/drush-ops/drush/blob/8.x/commands/runserver/runserver.drush.inc#L113 around a check to see if a uid is passed in. I didn't even know the command could log you in, and I'm not sure how many other people know this.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.1.17
| Drupal version? | N/A Backdrop CMS HEAD 1.x branch
| PHP version     | 7.1
| OS?             | Linux 

Travis Log: https://travis-ci.com/alexfinnarn/highlightjs_wysiwyg/builds/81946097#L796 with more detailed information on system configuration.

**Comment by alexfinnarn** [comment]
After looking through more of `drush_core_runserver()` it seems like the user information and login attempts are more involved than what I thought. I'll leave this issue open for at least declaring better return types, bool|object, or putting in an exception where the comment mentions adding one.

**Comment by alexfinnarn** [comment]
#1750 could be related.

**Comment by greg-1-anderson** [comment]
I'd advise trying to reproduce on `master` first and see if it still is happening there.

**Comment by greg-1-anderson** [comment]
Didn't notice the system spec was backdrop -- you are correct, Drush 8.x is the only option there.
