### ISSUE TITLE
Parameter is required twice although specified once only.

### ISSUE THREAD

**Issue by asodastreamer** [drush-ops/drush#3661]
**Describe the bug**
Specifying a command in the the class with one parameter and documenting this paramter in PHPDoc using the @param annotation and no options or alias will result in drush expecting the parameter twice.
This is counter-intuitive and would require us to drop documentation or request function-arguments, without the argument being specified int he function-signature.

**To Reproduce**

Using the following class-definition in a drush command and trying to call it.

`<?php
namespace Drupal\someNamespace\Commands;

use Drush\Commands\DrushCommands;

/**
 * A Drush commandfile.
 *
 * In addition to this file, you need a drush.services.yml
 * in root of your module, and a composer.json file that provides the name
 * of the services file to use.
 *
 * See these files for an example of injecting Drupal services:
 *   - http://cgit.drupalcode.org/devel/tree/src/Commands/DevelCommands.php
 *   - http://cgit.drupalcode.org/devel/tree/drush.services.yml
 */
class ModuleDrush extends DrushCommands {

  /**
   * Command description here.
   *
   * @param string $parameter
   *
   * @command module:hello
   */
  public function hello($parameter) {
    echo $parameter;
  }
}`

**Expected behavior**
The parameter is only supposed to be expected once, just like in the method's signature.

**Actual behavior**
The parameter is required to be passed in twice.

**Workaround**
Delete documentation in PHPDoc of method.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | Drush Commandline Tool 9.2.3
| Drupal version? | 8.5.3
| PHP version     | PHP 7.1.8 (cli)
| OS?             |  Linux(Centos)

**Additional information**
No other context.

**Comment by asodastreamer** [comment]
All you need is the class-definition i provided, the module would just be a scaffold load it.

**Comment by greg-1-anderson** [comment]
Please note that the Drush `status` command already has:
```
@param $filter A field to filter on. @deprecated - use --field option instead.
```
Changing this to `@param string $filter` had no ill effect when I tried it.
