### ISSUE TITLE
Services with needs_destruction tags are not destroyed

### ISSUE THREAD

**Issue by cspitzlay** [drush-ops/drush#3672]
**Describe the bug**
Services tagged with needs_destruction that are instantiated as part of a script run ('drush scr') are not destroyed at the end. 

**To Reproduce**
Configure a search API index to "index immediately".
Change an entity in a script executed with drush scr scriptname.php

**Expected behavior**
The change should be reflected in the index even before the next cron run, i.e. immediately (read: "after the end of the script run").

**Actual behavior**
The change is only reflected in the index after the next cron run which means the search API feature "index immediately" is broken. This is because the destruct() method of the service is not called. In GUI mode this is done via HTTPKernel->terminate() in KernelDestructionSubscriber->onKernelTerminate() which receives a PostRequestEvent.

**Workaround**
Dunno. Calling this manually does not seem like the correct solution.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.3.0
| Drupal version? | 8.5.x
| PHP version     | 7.0
| OS?             | Mac

**Additional information**
I opened a core issue, too, as I am not sure if this is a drush or a drupal core bug:
https://www.drupal.org/project/drupal/issues/2997740

**Comment by weitzman** [comment]
We added that terminate call at https://github.com/drush-ops/drush/pull/1259. Hope that helps with debugging this. If the bug still appears to be in Drush, please post here and I'll reopen the issue.

**Comment by cspitzlay** [comment]
I did some more debugging.  
I tried with a vanilla D8.7.x checkout and drush 7.4.0 which means without search API  and without any custom code.
I set a breakpoint in htdocs/vendor/drush/drush/src/Boot/DrupalBoot8.php in the terminate() method. It was never hit when I ran my test script with "drush scr": 
```
<?php
use Drupal\node\Entity\Node;
$node = Node::load(1);

$stop = 1;
```

One more data point:
While switching over my test to a fresh install I accidentally tested it with drush 8.1.17 (I thought that version wasn't even compatible with newer Drupal versions?).
And there it *did* call the destruct() method.
Could it be that this feature implemented in 2015 got broken between Drush 8 and 9?

**Comment by weitzman** [comment]
I'm not sure what value there is in testing with Drush 7. Maybe you mean Drush 9?

Yes, thats possible. Thanks for debugging.

**Comment by cspitzlay** [comment]
By D8.7.x I meant Drupal Core 8.7.x; my custom project is still on on Drupal 8.5 (see my original report) and I wanted to test with the latest versions.

**Comment by cspitzlay** [comment]
Ah, now I see what you meant.  That was a typo.  Drush 9.4.0 is the version.

**Comment by weitzman** [comment]
I can confirm that we have regressed here. @greg-1-anderson  - Any thoughts on where the call to $bootstrap->terminate should go? I know that Console has a terminate event - not sure if we should subscribe to that.

**Comment by greg-1-anderson** [comment]
I'm doing an experiment with registering a shutdown handler -- if it isn't too late to call it then.

**Comment by greg-1-anderson** [comment]
@cspitzlay Would you mind doing some ad-hoc testing on #3680 and see if it is effective in making the search API work correctly again?

**Comment by cspitzlay** [comment]
Yes, I will test and report back.

**Comment by cspitzlay** [comment]
I can confirm that now the destruct methods are called.

I tested both with vanilla drupal core 8.7.x without any contrib modules and with our custom project code with drupal core 8.5.x with Search API Solr and our custom code enabled.

**Comment by cspitzlay** [comment]
Thanks.
