### ISSUE TITLE
If an 8.x bin is called from a project folder where 9.x is installed, 9.x runs instead

### ISSUE THREAD

**Issue by JacobSanford** [drush-ops/drush#3676]
**Describe the bug**
If a Drush 8.x binary is run from a project folder where Drush 9.x is installed, Drush 9.x runs instead.  FWIW, the reverse does not happen.

**To Reproduce**
```
mkdir drush8
cd drush8/
composer require drush/drush:8.x
cd ..
mkdir drush9
cd drush9
composer require drush/drush:9.x
../drush8/vendor/bin/drush --version
> Drush Commandline Tool 9.4.0
```

**Expected behavior**
Drush 8.x runs.

**Actual behavior**
Drush 9.x runs.

**Comment by JacobSanford** [comment]
It also appears that the ```--root``` argument affects the drush version executed:

```
cd ~
drush8/vendor/bin/drush --version
> Drush Version   :  8.1.17 
drush8/vendor/bin/drush --version --root=/home/jsanford/drush9/
> Drush Commandline Tool 9.4.0
drush9/vendor/bin/drush --version --root=/home/jsanford/drush8/
> Drush Commandline Tool 9.4.0
```

Is there perhaps an undocumented (or one I may have missed) such as ```--drush-root``` argument that can avoid this? As with the case above, running 9.x from an 8.x ```---root``` also DOES work as expected:

```
drush9/vendor/bin/drush --version --root=/home/jsanford/drush8/
> Drush Commandline Tool 9.4.0
```

**Comment by weitzman** [comment]
please install drush9 per the install instructions. Its meant to be a dependency of your composer built project.

**Comment by JacobSanford** [comment]
@weitzman I appreciate your efforts, and this project. It has been a pillar of our deployment system for years.

That having been said, I am confused by your response, as I am reporting what I feel is unexpected behavior in Drush 8, not Drush 9. Your answer suggests I have improperly installed 9.x.

If a drush 8.x's bin is called from a drush 9.x project root, drush 9.x will run instead of 8.x.

**Comment by greg-1-anderson** [comment]
@JacobSanford If you have a site-local Drush installed, then either a global Drush 8 install or a global Drush 9 install should redispatch to the site-local Drush. If a global Drush 9 does not do this, it is a bug.

However, it is also important to note that a global Drush 9 is not a supported configuration. If you check out the install instructions and @weitzman suggested, then you will see that the recommended way to install Drush 9 is as a site-local install, with the Drush launcher being used as your global installation. Maintainers do not have a lot of time to support all of the possible ways to install Drush, so you're likely to get a brief answer.

In the case of this report, calling one Drush from the install folder of another Drush is a real edge case. It seems that Drush 8 is confusing the Drush 9 installation as a Drupal site. Using `--root` to specify a Drush install should never be done. If you have a use-case where doing this is important, you're pretty much going to be on your own. If you need to use the global installs of Drush (e.g. to run both Drush 8 and Drush 9 extensions in a Drupal site), then I would recommend staying away from the Drush install directories. If this really really bothers you, you could try submitting a PR to fix it, but Drush 8 is in maintenance fix only mode, so a PR on an edge case does not seem to be very important.

**Comment by JacobSanford** [comment]
HI Greg, thanks for the reply.

Neither of these is a global install. See the original report for reproducible stuff.

This isn't a hill I want to die on either - we already have a work-around. And I agree that this may be an edge case - needing two drush versions, but the error seemed to illuminate how drush 8.x either uses the executed directory or the --root to determine the 'current' binary and then loads its libraries from there. That seems like something that a maintainer would want to change. 

Regards,

JS

**Comment by greg-1-anderson** [comment]
We seem to have a misunderstanding vis-a-vis terminology

- A site-local Drush is one that is installed as part of a Composer-managed Drupal site (e.g. drupal-composer/drupal-project).
- A global Drush is one installed outside of a Drupal site.

The reason the later install is called "global" is that it is typically added to the `$PATH` and used with multiple Drupal sites. However, "global" may be a misnomer, as this term is sometimes used in the context of servers to indicate binaries available to every user on the system.

**Comment by JacobSanford** [comment]
@greg-1-anderson : I appreciate the time you took to clarify and address this. Thanks.
