### ISSUE TITLE
Dispatch an event, when there are no config changes to import

### ISSUE THREAD

**Issue by jepster** [drush-ops/drush#3678]
**Is your feature request related to a problem? Please describe.**
I am developing an own module, which would profit from an event, which is dispatched, when there are no config changes to import.

**Describe the solution you'd like**
Near drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php:189 the logger is logging an notice for no changes to import (inside the import method). There should also be an event dispatched. This method is being triggered, when you execute the following Drush command:

`drush cim -y`

**Comment by weitzman** [comment]
i'm not inclined to add this. You could ask Drupal core to see if they would add such an event. Otherwise, your script is welcome to call `config:status` in order to determine if there are pending config changes.
