### ISSUE TITLE
drush cc drush bootstraps Drupal

### ISSUE THREAD

**Issue by danepowell** [drush-ops/drush#3693]
**Describe the bug**
I wouldn't expect `drush cc drush` to bootstrap Drupal, but it does. This can cause problems if your site is in any sort of inconsistent state, especially during CI operations, or when trying to recover from a corrupt db / cache.

Less severely but still a bug: if the Drupal database doesn't exist at all, I think this causes a warning:
> Missing database table: key_value

**To Reproduce**
Drop your Drupal database, then run `drush cc drush -vvv`.

**Expected behavior**
`drush cc drush` should be able to run without errors in the presence of no Drupal database or a corrupt Drupal database.

**Actual behavior**
Observe that it tries to bootstrap Drupal and throws `Missing database table: key_value`

**Workaround**
Depending on the situation there might be workarounds, but generally no.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.3.0
| Drupal version? | 8.5
| PHP version     | 7.1
| OS?             | Mac/Linux

**Comment by weitzman** [comment]
It isn't possible for the different types of caches to have different levels of bootstrap. The only solution  I can think of is to move `drush cc drush` to its own command.

**Comment by weitzman** [comment]
I looked again and `cc` is set to bootstrap to max which means "bootstrap as far as you can" then run the execute() method. So the key_value warning you see is harmless and expected when your site is in this half working state.
