### ISSUE TITLE
drush 8.1.17 fails to detect drupal 6 (incompatibility with php7.2 ??)

### ISSUE THREAD

**Issue by cptX** [drush-ops/drush#3700]
Hi guys, after spending several hours not finding a solution I ended up posting here...

I have installed drush 8.1.17 by using drush.phar in an Ubuntu 18.04 running php7.2 and nginx.
I have installed the drush.phar in /usr/local/bin and renamed it to drush
The problem is that in my drupal 6 site folder (/var/www/sitename) when I run drush cc all , drush reports "No Drupal site found, only 'drush' cache was cleared"
If I run drush cc all --debug I get these two lines:
mysql extension for PHP is not installed. Check your php.ini to see how you can enable it.
DB credentials are invalid.

DB credentials are for sure OK (credentials in settings.php) because the site is actually up and running...
I know that the php.ini is used from /etc/php/7.2/cli folder and is different than the /etc/php/7.2/fpm/php.ini 
I tried enabling the mysqli.so and mysqlnd.so modules (also with reverse order) in the cli version of php.ini to no availability...
The same copy of the website in another server running php5 with drush6 and ubuntu 12.04 runs fine!!

So I really believe this is a bug of drush 8 and probably an incompatibility with php7.2..

As far as I have decided to use only php7.2 version in this server I'm out of options if really drush8 has an incompatibility with it.

To clarify also, this Drupal 6 site is modified by me to be compatible with php7.2 and is currently up and running.

Any suggestions please?

**Comment by greg-1-anderson** [comment]
Drush 8 works with PHP 7.2.  Drupal 6 is not compatible with PHP 7.2.

**Comment by cptX** [comment]
This Drupal 6 is modified by me to be completely compatible with PHP 7.2 and is currently up and running...

**Comment by greg-1-anderson** [comment]
Specify both `--root` and `--uri` when running Drush or use a site alias with root and uri or run Drush with the cwd in the directory that contains the settings.php file for your Drupal site.  Make sure that `drush status` reports "Database: Connected". Make sure that the user you are running Drush under can read the files in the directory that contains your site, and can also connect to the database using the credentials in your settings.php file.

**Comment by cptX** [comment]
--root and --uri didn't help...
I have never seen "Database: Connected" yet...
The user running Drush has full access to /var/www, although I tried running drush as root too.
As I mentioned credentials are proven because the site is up and running.

**Comment by dsnopek** [comment]
The driver being used is set in your settings.php. It's the first part of the `$db_url` - if it starts with 'mysql://' then you'll use the 'mysql' extension, if it starts with 'mysqli://' then you'll use the 'mysqli' extension

**Comment by dsnopek** [comment]
Actually, I think drush will show 'mysql' in `drush status` even if you're using 'mysqli'. BTW, I'm also seeing this problem with PHP 7.2! I'm not sure how I didn't notice it before

**Comment by weitzman** [comment]
Drush actually intervenes for its CLI requests and changes mysqli to mysql. See https://github.com/drush-ops/drush/blob/649109eead25fe03604792c69d98f7a17e7547a3/src/Sql/SqlBase.php#L546.

Some prior discussion at #2002 and #2068. We can revisit the situation if desired. It would be helpful if someone clarified under what conditions the bad behavior is evident.

**Comment by dsnopek** [comment]
> It would be helpful if someone clarified under what conditions the bad behavior is evident.

It seems that Drush isn't bootstrapping Drupal for some reason. So, if you:

1. Get out the latest 6.x branch of the LTS version of Drupal: `git clone https://github.com/d6lts/drupal.git --branch 6.x`
2. Install using an environment with PHP 7
3. The site will work fine!
4. Running `drush status` will not show the site bootstrapped, and `drush cc all` will report "No Drupal site found, only 'drush' cache was cleared."

I'll be looking into this later too. Odds are the problem is on the Drupal side, not Drush.

**Comment by weitzman** [comment]
I'm fine with the PR in #2002, if it fixes the issue and if someone can successfully run the test suite with mysqli only.

**Comment by cptX** [comment]
#2002 (comment) worked for me!!! Thanks guys!

**Comment by greg-1-anderson** [comment]
Let's track this in #2002.
