### ISSUE TITLE
drush 8.1.16 outputs long object arrays

### ISSUE THREAD

**Issue by AlexShapka** [drush-ops/drush#3701]
**Describe the bug**

Running the `drush cc all` command outputs long list of RulesReactionRule Object arrays.

**To Reproduce**

Ona Drupal 7 website with Drupal Commerce, use the following function in custom module:

```
function my_module_entity_presave($entity, $type) {
  sdpm($entity);
  sdpm($type);
}
```

and then run

`drush cc all`

on CLI.

**Expected behavior**

To see only:

`'all' cache was cleared.                                                                                                                                               [success]`

**Actual behavior**

Instead it is outputting:

```
drush cc all
'all' cache was cleared.                                                                                                                                               [success]
The administrator role has been reset for all permissions.                                                                                                             [status]
RulesReactionRule Object                                                                                                                                               [status]
(
    [itemName:protected] =&gt; reaction rule
    [events:protected] =&gt; Array
        (
            [0] =&gt; commerce_order_insert
        )

    [eventSettings:protected] =&gt; Array
        (
        )

    [conditions:protected] =&gt; RulesAnd Object
        (
            [itemName:protected] =&gt; and
            [negate:protected] =&gt; 
            [children:protected] =&gt; Array

```

and this is just the very beginning of the actual output. It is really long.

**Workaround**

Do not use the:

```
function my_module_entity_presave($entity, $type) {
  sdpm($entity);
  sdpm($type);
}
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.1.16
| PHP version     | 70
| OS?             | RHEL

**Comment by AlexShapka** [comment]
In fact, it's not about that particular function. It keeps outputting really long arrays even with that function completely removed. Can't figure out why...

**Comment by MikeyMJCO** [comment]
Current Drush 8 version is 8.1.17

**Comment by greg-1-anderson** [comment]
This is probably being caused by the behavior of some module, not Drush. Further investigation is needed.

**Comment by AlexShapka** [comment]
Greg, you were right - further investigation showed that exactly at moments of checking some long cron jobs were running.
