### ISSUE TITLE
Change Drush home directory

### ISSUE THREAD

**Issue by mcfdez** [drush-ops/drush#3704]
Hello,

I installed Drush in one Windows 10 for Drupal development. I see that Drush created a folder inside "C:/Users/UserName/.drush".

Is possible to change this folder to, for example, "C:/Users/UserName/Config/Drush" ?

**Comment by greg-1-anderson** [comment]
Looks like Drush is not accurately determining the home directory on a Windows 10 system. The Linux path is `/home/username/.drush`. I'm not sure where to best put the configuration directory on Windows, but it should be inside the user's home directory, and not right at the root of `C:/Users`.

A PR would be welcome.

**Comment by mcfdez** [comment]
Sorry, but github has erased part of the address I had placed above. I have edited the post to be understood better.

**Comment by greg-1-anderson** [comment]
This is currently controlled by the method [userConfigPath](https://github.com/drush-ops/drush/blob/9.4.0/src/Config/Environment.php#L229), which hard-codes the `.drush` in the path.

A PR to add an environment variable to control this location and/or change the default location on Windows (e.g. using `static::isWindows()` in that same class) would be welcome.

**Comment by weitzman** [comment]
I think Drush is doing this fine. You can choose any path for $HOME and then drush appends a subdir called .drush. I dont see that as a bug.

**Comment by mcfdez** [comment]
> This is currently controlled by the method [userConfigPath](https://github.com/drush-ops/drush/blob/9.4.0/src/Config/Environment.php#L229), which hard-codes the `.drush` in the path.
> 
> A PR to add an environment variable to control this location and/or change the default location on Windows (e.g. using `static::isWindows()` in that same class) would be welcome.

I changet the line "return $this->homeDir() . '/.drush';" by this "return 'C:/Users/myuser/Configs/Drush';", but when I execute Drush command, the .drush folder appears again inside return 'C:/Users/myuser/';

**Comment by greg-1-anderson** [comment]
Do you have a site-local Drush in your Drupal site? Run `drush status` to confirm the path of the Drush that is actually running.
