### ISSUE TITLE
Why is drush by default using notify-send?

### ISSUE THREAD

**Issue by maniac0s** [drush-ops/drush#3705]
When I installed my site on the server, the drush command vendor/bin/drush site-install crashed with a PHP fatal error because the server doesn't have notify-send installed. Why is drush requiring that and how can I disable this feature that doesn't make any sense on a server?

Drush was installed via composer install with the option "drush/drush": "~8.0|^9.0.0-beta8"

**Comment by greg-1-anderson** [comment]
There is no disable switch per-se, but you may select the command you wish to run or the amount of time that should pass before notification in your `~/.drush/drush.yml` file:
```
notify:
  cmd: echo
  duration: 99999999
```
I'm not sure why `src/Commands/core/NotifyCommands.php` throws an exception when the notify command fails. It seems like it would be better to just log the instructional message as a notice and still exit with a 0 status code.

**Comment by weitzman** [comment]
This started happening in my container so I debugged it. Notify is off by default but it is getting turned on when you copy examples/example.drush.yml into a discoverable position. Thats done when you run `drush init`. I have no idea why so few people have reported this. 

I commented out a few lines in 9ea9f581314e87a2f7794c95c851f140e46f4cd0 in example.drush.yml, so its now harmless to copy and use it.

**Comment by weitzman** [comment]
My fix won't actually help the many folks who have already run `drush init`. But I'm not sure if its safe to use a logger in a shutdown function? The function is currently static so I can't access $this anyway. Presumably that could be changed.
