### ISSUE TITLE
How to make sure Drush works?

### ISSUE THREAD

**Issue by zomorod** [drush-ops/drush#3709]
Hi there, 

Do we have a command to check drush functionality? For example: If I want to check drush is working on my site I need to check several commands (like drush st, pm-updatstatus, etc) to make sure Drush is working 100% on my site. I thought it is good to have a drush command to make sure Drush is working.

I appreciate any help or any recommendations.

Thank you,

**Comment by weitzman** [comment]
Sorry there is no such command.

**Comment by Chi-teck** [comment]
To make sure that Drush is installed just type `drush --version`. Commands like `drush st` and `drush pm-updatstatus` are checking your site not Drush itself.
Also `drush rq` is quite useful for checking site health.
