### ISSUE TITLE
drush.yml not read outside of root directory

### ISSUE THREAD

**Issue by jeremdow** [drush-ops/drush#3710]
**Describe the bug**
`sites/default/local.drush.yml` not read when drush is launched outside of Drupal root directory.

**To Reproduce**
Observe where `docroot/sites/default/local.drush.yml` is present.

`cd docroot; drush status`
(Produces Expected behavior)

`cd modules; drush status`
(Produces Actual behavior)

**Expected behavior**
```
 Drush configs    : /app/vendor/drush/drush/drush.yml          
                    /app/drush/drush.yml                       
                    /app/docroot/sites/default/local.drush.yml
```

**Actual behavior**
```
Drush configs    : /app/vendor/drush/drush/drush.yml 
                    /app/drush/drush.yml  
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush Launcher Version| 0.6.0
| Drush Commandline Tool | 9.4.0
| PHP version     | 7.1.22

**Additional information**
Noted after configuring `options: uri` and running `drush uli` anywhere outside the project root, the resulting link reverts to http://default ... path (and is invalid).

**Comment by weitzman** [comment]
local.drush.yml is not a valid name. We only recognize `drush.yml`. If the docs state otherwise please let me know. Thanks.

**Comment by jeremdow** [comment]
Good to know, `blt:init:settings` generates this file, referenced here:
https://blt.readthedocs.io/en/latest/onboarding/
