### ISSUE TITLE
Fatal Error running `drush updatedb`

### ISSUE THREAD

**Issue by MikeyMJCO** [drush-ops/drush#3715]
**Describe the bug**

Running `drush updatedb` returns:

>  [error]  The external command could not be executed due to an application error.

Reviewing the error log reveals:

> [30-Sep-2018 16:58:04 UTC] PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /home/XXX/XXX/vendor/symfony/var-dumper/Dumper/CliDumper.php on line 61

**To Reproduce**

Updated codebase from 8.4.4 to 8.6.1, tried to run `dr updb` , received error.

**Expected behavior**

Expected Drush to run the updates.

**Actual behavior**

Error - as above.

**Workaround**

Running updates via Drupal UI completes successfully. Even with no pending updates `dr updb` is still returning an error.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.4.0
| Drupal version? | 8.6.1
| PHP version     | 7.2
| OS?             | Centos 6.10 (Final)

**Comment by greg-1-anderson** [comment]
What version of php? How did you install Drush? It almost seems as if your version of php is mismatched with the requirements for symfony/var-dumper. What does `composer info symfony/var-dumper` return?

**Comment by MikeyMJCO** [comment]
**PHP version is**: 7.2.10
**Drush was installed using**: `composer require drush/drush`
**composer info symphony/var-dumper**:


>name     : symfony/var-dumper
descrip. : Symfony mechanism for exploring and dumping PHP variables
keywords : debug, dump
versions : * v4.1.5
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/symfony/var-dumper.git 1509020968321c1d46408c11c142a2388b1c9b0c
dist     : [zip] https://api.github.com/repos/symfony/var-dumper/zipball/1509020968321c1d46408c11c142a2388b1c9b0c 1509020968321c1d46408c11c142a2388b1c9b0c
names    : symfony/var-dumper

>autoload
files
psr-4
Symfony\Component\VarDumper\ => .
exclude-from-classmap

>requires
php ^7.1.3
symfony/polyfill-mbstring ~1.0
symfony/polyfill-php72 ~1.5

>requires (dev)
ext-iconv *
symfony/process ~3.4|~4.0
twig/twig ~1.34|~2.4

>suggests
ext-iconv To convert non-UTF-8 strings to UTF-8 (or symfony/polyfill-iconv in case ext-iconv cannot be used).
ext-intl To show region name in time zone dump
symfony/console To use the ServerDumpCommand and/or the bin/var-dump-server script

>conflicts
phpunit/phpunit <4.8.35|<5.4.3,>=5.0
symfony/console <3.4

Thanks @greg-1-anderson - I really appreciate the assist!

**Comment by MikeyMJCO** [comment]
`com check-platform-reqs`

> ext-date       7.2.10      success  
> ext-dom        20031129    success  
> ext-filter     7.2.10      success  
> ext-gd         7.2.10      success  
> ext-hash       1.0         success  
> ext-json       1.6.0       success  
> ext-libxml     7.2.10      success  
> ext-mbstring   7.2.10      success  
> ext-pcre       7.2.10      success  
> ext-PDO        7.2.10      success  
> ext-session    7.2.10      success  
> ext-SimpleXML  7.2.10      success  
> ext-SPL        7.2.10      success  
> ext-tokenizer  7.2.10      success  
> ext-xml        7.2.10      success  
> php            7.2.10      success

**Comment by greg-1-anderson** [comment]
Not sure. It **looks** like you are perhaps running php 7.0 or earlier rather than the 7.2 that you are expecting. Does `./drush status` show php 7.2 in the `php binary` line, or something else?

**Comment by MikeyMJCO** [comment]
From the project root `drush status` shows:
> PHP binary       : /opt/cpanel/ea-php72/root/usr/bin/php
From PROJECT_ROOT/vendor/drush/drush `./drush status` shows:
> PHP binary       : /opt/cpanel/ea-php72/root/usr/bin/php

**Comment by greg-1-anderson** [comment]
Drupal usually uses Symfony 3. Maybe re-install all of your Symfony components with a `^3`?

You didn't stipulate specifically how you installed Drush. Ideally this is done inside a Drupal site. The constraints for var-dumper in Drush is:
```
"symfony/var-dumper": "^3.4",
```
So, your installation is in violation of Drush's constraints. Perhaps you are installing Drush in the same vendor as some other incompatible component. Not sure how that's possible; Composer should fail to install in this instance.

All I can say is that your installation is unsupported, even though AFAIK that configuration should still work with php 7.2, and you should not have been given that version of var-dumper in the first place. (`composer why symfony/var-dumper` will give some hints to that)

**Comment by marysmech** [comment]
I just run into same issue. After downgrade of var-dumper error disappeared but there is new one:

`PHP Fatal error:  Call to undefined function Drupal\Component\Utility\random_bytes() in web/core/lib/Drupal/Component/Utility/Crypt.php on line 33`

Problem seem to be only with `drush updb`. Commands like `cim`, `cr` works. It looks like it would run under some lower php version. Weirdest about this is fact that this problem is only on server with Centos. On debian 9 with php 7.2 everything works.
