### ISSUE TITLE
Restore deprecated pm:info command, or create a new command to quickly show information specific to a module

### ISSUE THREAD

**Issue by shortymcsmalls** [drush-ops/drush#3717]
It seems that when Drush 9 was created, the pm-info command was deprecated as part of a push to make sure the Drupal community fully adopted Composer and its built in features/functionality. While it's reasonable to not duplicate functionality provided by Composer (or other drush commands), pm:info provided some novel information that was routinely useful for troubleshooting. For reference, the following is the output from `pm-info` on a D8 application running Drush 8.1.17: 

```
$ drush pm-info webform
 Extension     :  webform
 Project       :  Unknown
 Type          :  module
 Title         :  Webform
 Description   :  Enables the creation of webforms and questionnaires.
 Package       :  Webform
 Core          :  8.x
 PHP           :  5.5.9
 Status        :  enabled
 Path          :  modules/contrib/webform
 Schema        :  8116
 version
 Requires      :  drupal:field, drupal:system (>= 8.3), drupal:user
 Required by   :  webform_bootstrap, webform_node, webform_demo_application_evaluation, webform_scheduled_email, webform_demo_event_registration, webform_devel, webform_editorial,
                  webform_example_composite, webform_example_element, webform_example_remote_post, webform_examples, webform_image_select, webform_templates, webform_ui
 Permissions   :  access webform overview, access webform submission log, administer webform element access, administer webform submission, administer webform, create webform, delete any webform,
                  delete own webform, delete own webform submission, delete any webform submission, edit webform assets, edit any webform, edit any webform submission, edit own webform, edit own
                  webform submission, edit webform twig, view any webform submission, view own webform submission
 Configure     :  entity.webform.collection
```

The equivalent information provided by `composer show` and `pm:list`, respectively: 

```
$ composer show drupal/webform
name     : drupal/webform
descrip. : Enables the creation of webforms and questionnaires.
keywords :
versions : * 5.0.0-rc22
type     : drupal-module
license  : GNU General Public License v2.0 or later (GPL-2.0+) (OSI approved) https://spdx.org/licenses/GPL-2.0+.html#licenseText
source   : [git] https://git.drupal.org/project/webform 8.x-5.0-rc22
dist     : [zip] https://ftp.drupal.org/files/projects/webform-8.x-5.0-rc22.zip 8.x-5.0-rc22
names    : drupal/webform

support
source : http://cgit.drupalcode.org/webform
issues : https://www.drupal.org/project/issues/webform?version=8.x
docs : https://www.drupal.org/docs/8/modules/webform
forum : https://drupal.stackexchange.com/questions/tagged/webform

requires
drupal/core *

requires (dev)
drupal/address ~1.4
drupal/devel *
drupal/token ~1.3
drupal/webform_access *
drupal/webform_node *
drupal/webform_scheduled_email *
drupal/webform_ui *
```
```
$ drush pm:list --package=Webform
 --------- ----------------------------------------------------------- ---------- --------------
  Package   Name                                                        Status     Version
 --------- ----------------------------------------------------------- ---------- --------------
  Webform   Webform (webform)                                           Disabled   8.x-5.0-rc22
  Webform   Webform Access (webform_access)                             Disabled   8.x-5.0-rc22
  Webform   Webform Bootstrap (webform_bootstrap)                       Disabled   8.x-5.0-rc22
  Webform   Webform Devel (webform_devel)                               Disabled   8.x-5.0-rc22
  Webform   Webform Editorial (webform_editorial)                       Disabled   8.x-5.0-rc22
  Webform   Webform Image Select (webform_image_select)                 Disabled   8.x-5.0-rc22
  Webform   Webform Node (webform_node)                                 Disabled   8.x-5.0-rc22
  Webform   Webform Scheduled Email Handler (webform_scheduled_email)   Disabled   8.x-5.0-rc22
  Webform   Webform Templates (webform_templates)                       Disabled   8.x-5.0-rc22
  Webform   Webform UI (webform_ui)                                     Disabled   8.x-5.0-rc22
 --------- ----------------------------------------------------------- ---------- --------------
```

I'll gladly agree that `composer show` is the better source of information for things like version, requirements, project name and the like, but there are still a number of additional useful data points that `pm-info` returned not included in the above, such as: 

* Schema Version (this could arguably be removed in favor of `updatedb:status`, though I'd contend that the two aren't directly equivalent, especially if all db updates have been performed)
* Permissions
* Configure
  * This parameter is especially useful for quickly highlighting the correct configuration key to subsequently pass to `config:get` to see the current configuration of said module

Status is another frequently used field from the pm:info results, and while the status of the module is returned by `pm:list` - there's no way to limit that list to a single module, requiring that you then use another utility like `grep` to limit those results further. 

All the above is to say that `pm-info` was a very useful command for determining the "state" of a Drupal module, allowing you to see a number of parameters useful for troubleshooting common issues without needing to chase down those values in the module code/drupal database.

Also - it appears that a few people have commented to this effect on drushcommands.com, linking to those comments so their feedback can be included:

* https://drushcommands.com/drush-9x/pm/pm:info/#comment-4005247217
* https://drushcommands.com/drush-9x/pm/pm:info/#comment-3932888079
* https://drushcommands.com/drush-9x/pm/pm:list/#comment-3816904170

**Comment by weitzman** [comment]
Thanks for the thorough and thoughtful writeup. I'll leave this open for a bit to see how much support there is for a return of pm:info.

As for your other asks, see `drush dd views` (for example). That gives the path to Views folder. You can append views.permissions.yml or views.info.yml to get the other things you ask for.

Drush9 assumes that grep and cat are part of the user's arsenal, or that the user is curious enough to learn. I think basic use of these tools is within the skill level of a drush user.

**Comment by greg-1-anderson** [comment]
`pm:info` + the `--fields` option can be more precise than grep + cut; if you're writing a script, then you might be vulnerable to having your 'grep' expression match data in the wrong field.

We could let folks target down to the exact row and fields they want to output if we introduced a `--filter` option to `pm:list` (and other commands that output tabular data). We could [do that pretty easily with a hook](https://github.com/consolidation/filter-via-dot-access-data/blob/0.1.0/src/Cli/OpCommands.php#L45:L61).

**Comment by seanhamlin** [comment]
Just adding in my use case (which is simple), in this situation I just want to get the current status of a module in a script, and then switch on that status. At the moment, there is no way (that I can tell) to do this just for the one module `search_api`

This code works in Drush 8:

```bash
SEARCH_API_STATUS=`${DRUSH_CMD} pm-info search_api | grep -i status`
        case "${SEARCH_API_STATUS}" in
            *enabled*)
            ...
```

**Comment by weitzman** [comment]
i'd use `drush pml --format=json` along with `jq` or similar. at least until https://github.com/drush-ops/drush/issues/3717#issuecomment-426764488 comes about.

**Comment by greg-1-anderson** [comment]
I threw together a quick prototype in #3718

**Comment by seanhamlin** [comment]
```bash
$ drush9 pml --filter='id=bartik' --field=status
Enabled
```

o_O

👍 for that. You cannot really rely on `jq` being installed on managed hosting providers.

**Comment by greg-1-anderson** [comment]
`drush pm:list --filter...` is now available. That can serve as a suitable substitute for `pm:info`.

**Comment by seismicmike** [comment]
`drush pm:list --filter` does not give the detailed info I'm looking for. I primarily used `drush pmi` to inspect module dependencies both upstream and downstream of a particular module. How do I get this information now without looking through info files or logging into the interface?

In short: What drush 9 command outputs this information?

![Screen Shot 2019-04-26 at 10 18 23 AM](https://user-images.githubusercontent.com/4080804/56814253-c2497100-680c-11e9-96dd-100b4559f226.png)

If there is none, it needs to be restored, please.

**Comment by seismicmike** [comment]
To clarify, I know I can get the "Requires" info using composer show, but I'm not sure how to get the "Required By" info. Maybe there's a flag I don't know about? Also, composer doesn't know about what's enabled on the site, so it might give me unhelpful info.

**Comment by weitzman** [comment]
Core Drush9 does not expose that info. I guess they could be added to `pml` as non-default fields

**Comment by mootari** [comment]
For posterity, here is a one-liner to fetch a module's dependents. Replace "NAME" with the module name.
```
drush ev 'return array_keys(Drupal::service("extension.list.module")->get("NAME")->required_by)'
```
