### ISSUE TITLE
drush updb fails when using services in Drush 9.5.0

### ISSUE THREAD

**Issue by asacolips** [drush-ops/drush#3730]
**Describe the bug**
As of Drush 9.5.0, I'm no longer able to revert features using the features manager service in post update hooks. This may be related to https://www.drupal.org/project/drupal/issues/2863986, which was applied in Drush 9.5.0 as the following patch: https://www.drupal.org/files/issues/2863986-2-49.patch

An example of the error returned:

```
[notice] Update started: MODULE_post_update_1
[error]  You have requested a non-existent service "features.config.installer".
[error]  Update failed: MODULE_post_update_1
[error]  Update aborted by: MODULE_post_update_1
[error]  Finished performing updates.
```

**To Reproduce**
Include the following in a `MODULE.post_update.php` or `MODULE.install` file. You must have the features module installed for this example, though other modules that include services may have similar behaviors.

```php
$feature_list = [
  'some_feature_module',
];

\Drupal::service('features.manager')->import($feature_list, TRUE);

return t('Reverted @features', [
  '@features' => implode(', ', $feature_list),
]);
```

**Expected behavior**
`drush updb` should proceed without failing.

**Actual behavior**
`drush updb` failed with previously working code.

**Workaround**
Run `drush fr some_feature_module` to manually revert the features in question, or revert drush to 9.4.x.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.5.0
| Drupal version? | 8.5.7 and 8.6.1
| PHP version     | 5.6 and 7.2
| OS?             | Linux

**Comment by weitzman** [comment]
Thanks for the report. I can see that you can no longer do something that used to work. But I'm not clear that Drush is at fault. Perhaps Drush was just being lenient before and not we are properly erroring after an update fails. I think we need to understand why the error `You have requested a non-existent service "features.config.installer".` is bring thrown. Drush is not throwing tha.

**Comment by weitzman** [comment]
Do you mean that your Drupal is patched with https://www.drupal.org/files/issues/2863986-2-49.patch? You said Drush but its a Drupal patch, not a Drush patch.

**Comment by greg-1-anderson** [comment]
Does this update work correctly when applied through Drupal?  If so, it seems to me that if Drush bootstraps Drupal the same way that update.php does, then Drush should be able to apply any update that Drupal does.  We've had a couple of reports in this area, so I'm wondering if there are any subtle differences between Drush and Drupal vis-a-vis update bootstrapping.

If the issue reported in this card also happens in Drupal, then this is definitely a core issue. I am also interested in whether this report is with or without the above-mentioned patch applied to Drupal.

**Comment by asacolips** [comment]
Testing with the mentioned patch was definitely on my to-do list for this week, but I was able to confirm that I had the issue when using Drush 9.5.0 and not when using Drush 9.4.0. I'm not currently applying https://www.drupal.org/files/issues/2863986-2-49.patch to Drupal core directly, but it is applied as part of Drush 9.5.0.

I'm in the process of testing deployments scheduled for tomorrow, so I'll see if I can apply the core patch directly and confirm whether or not it affects Drupal console or `/updated.php`. I'll post back as soon as I have more info!

**Comment by anthonyrw** [comment]
I encountered the same issue when updating to Drush 9.5.0. Reverting to 9.4.0 resolves issue. In my case:
`drupal config.storage.sync has a dependency on a non-existent service "config_filter.storage_factory"`

**Comment by asacolips** [comment]
I can confirm that I receive the same error when using Drush 9.4.0 while applying https://www.drupal.org/files/issues/2863986-2-49.patch directly via composer. I'll cross post the issues that I've encountered to the core issue thread the patch is from, but Drush 9.5.0 is still potentially breaking as long as that patch is included.

**Comment by asacolips** [comment]
Doing some more digging, it looks like the compatibility issue with Drush was identified in https://www.drupal.org/project/drupal/issues/2863986#comment-12361289 (#53) of the core issue thread. In addition, #55, #56, #61, and #62 all add more context to connections with Drush https://github.com/drush-ops/drush/issues/3193.

There are a few more recent versions of the patch other than 2863986-2-49.patch, so maybe we just need to update the patch version that Drush is requiring?

**Comment by greg-1-anderson** [comment]
The Drush references you mention above are a year old; we are using the UpdateKernel now. Maybe it's something else?

_Note: I edited your post to add backticks around the comment numbers, so that GitHub wouldn't wrap them in links to PRs._

**Comment by greg-1-anderson** [comment]
... or maybe there's a regression that is stopping Drush from using the UpdateKernel.
