### ISSUE TITLE
Drush eval command failing with "Failed opening required 'vendor/drush/drush/sut/../vendor/autoload.php'"

### ISSUE THREAD

**Issue by geerlingguy** [drush-ops/drush#3734]
**Describe the bug**

My Drupal role builds have been passing for months, and runs daily.

Today the build started failing, on a task which runs the following command (see below):

**To Reproduce**

Run the command:

```
/var/www/drupal/vendor/drush/drush/drush eval "if (function_exists('apc_clear_cache')) {
  apc_clear_cache();
}
if (function_exists('opcache_reset')) {
  opcache_reset();
}"
```

**Expected behavior**

The command should run as expected.

**Actual behavior**

I get the fatal error:

```
PHP Fatal error:  require(): Failed opening required
'/var/www/drupal/vendor/drush/drush/sut/../vendor/autoload.php'
(include_path='.:/usr/share/pear:/usr/share/php')
in /var/www/drupal/vendor/drush/drush/sut/autoload.php on line 14
```

For more detail from the now-failing build: https://travis-ci.org/geerlingguy/ansible-role-drupal/jobs/441861588#L1403

**Workaround**

Sorta, but it would be really annoying to implement.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.5.0 (was working fine on versions prior)
| Drupal version? | 8.x (8.6.1 to be precise)
| PHP version     | 7.1
| OS?             | Linux

**Additional information**

See related: https://github.com/geerlingguy/ansible-role-drupal/issues/62

**Comment by geerlingguy** [comment]
It's also breaking my Drupal VM builds as well as of a few hours ago :( https://travis-ci.org/geerlingguy/drupal-vm/jobs/441874391#L2690

**Comment by weitzman** [comment]
Kinda hard to learn a lot from that log. I do see `/var/www/drupal/vendor/drush/drush/sut/autoload.php` which you should not be loading or reading from. Please describe your drupal+drush file layout and how its assembled. Drush is a dependency of a composer project/ Or a global Drush thats not part of a composer project? How to reproduce it?

**Comment by geerlingguy** [comment]
@weitzman - Sorry, didn't have time earlier to build a quick from-scratch reproducible test scenario. I'm working on that now. Basically, it's a fresh drupal codebase built with the Drupal Composer project, with Drush as a project dependency. Drush is run out of the vendor/bin/drush directory, and the call is made to `vendor/bin/drush eval "something_php()"`. As I said, this has been working for at least months without issue with Drush < 9.5.0, so I'm guessing it could have to do with newlines or something? Or maybe a dependency / pathing issue with the autoloader?

But I'll get back to you with reproducible steps once I have them.

**Comment by geerlingguy** [comment]
Okay, some testing from a Docker environment where that command is failing:

```
root@instance:/var/www/drupal# vendor/bin/drush eval 'print "test\n";'
test
```

Works, and prints newline in output.

```
root@instance:/var/www/drupal# vendor/drush/drush/drush eval 'print "test\n";'
test
```

Works, and prints newline in output.

```
vendor/drush/drush/drush eval if (function_exists('apc_clear_cache')) {\napc_clear_cache();\n}\nif (function_exists('opcache_reset')) {\nopcache_reset();\n}"
```

... hmm ... it causes a different error when I run that verbatim in my console. I'm guessing at this point it is related to newline handling though. Trying some different YAML line folding techniques. If I make sure to add `;` after each closing brace, I can get it to work as a one-line string. If that works, I'll change this role to use that technique (basically it is a command to reset opcache and apc cache, but only if they're present on the system).

The task as it was previously:

```yaml
- name: clear opcache
  command: >
    {{ drush_path }} eval
      "if (function_exists('apc_clear_cache')) {
        apc_clear_cache();
      }
      if (function_exists('opcache_reset')) {
        opcache_reset();
      }"
  args:
    chdir: "{{ drupal_core_path }}"
```

And here's what I changed it to:

```yaml
---
- name: clear opcache
  command: >-
    {{ drush_path }} eval
      "if (function_exists('apc_clear_cache')) {
        apc_clear_cache();
      };
      if (function_exists('opcache_reset')) {
        opcache_reset();
      };"
  args:
    chdir: "{{ drupal_core_path }}"
```

(Note the folded scalar change to _not_ add an additional newline on the end, and also the additional semicolons.)

**Comment by geerlingguy** [comment]
Strange, I got a local build to pass, but I realized it didn't run the handler again :/ Still failing in Travis CI, and I'm also looking at if I can get the Drush command alias to not be `/var/www/drupal/vendor/drush/drush/drush`, but instead `vendor/bin/drush`, since that seems like it could be introducing the extra directory level leading to autoloader confusion...

**Comment by geerlingguy** [comment]
It seems like it was a pathing issue. Here's the fix: https://github.com/geerlingguy/ansible-role-drupal/commit/410302dc3b3595e6c59e0aa3f5a6e304e081d577

Basically, instead of using Ansible's built-in `chdir` functionality (which seems to set the $CWD and maybe not the $PWD? Which one does Drush use?), I use the `shell` module and do a `cd $drupal_core_path && drush eval ...`, which seems to work correctly.

I also inlined the entire code block because in local testing the newlines and spacing seemed to throw me for a loop a few times copying and pasting.

Closing this issue, but hopefully I'll help a future googler!

**Comment by geerlingguy** [comment]
Well, I'm also seeing the same issue in a different scenario now:

```
PHP Warning:  require(/var/www/drupalvm/drupal/vendor/drush/drush/sut/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/drupalvm/drupal/vendor/drush/drush/sut/autoload.php on line 14
PHP Fatal error:  require(): Failed opening required '/var/www/drupalvm/drupal/vendor/drush/drush/sut/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/drupalvm/drupal/vendor/drush/drush/sut/autoload.php on line 14
```

From failed build: https://travis-ci.org/geerlingguy/drupal-vm/jobs/442223250

And this job is running the command:

```
drush status
```

From the directory /var/www/drupal, which is a fresh Drupal 8.6.1 installation with Drush 9.5.0 as a Composer dependency, as built by the Drupal Composer project. Reproducing locally to see what's up here. Note that Ansible is not involved in any way with this particular test—it's just run in the Docker container in the project root.

**Comment by geerlingguy** [comment]
Attempt at a fix: https://github.com/geerlingguy/drupal-vm/commit/21b5518e88e7ccea62d14429674e76c84153ee5e#diff-354f30a63fb0907d4ad57269548329e3

It looks like it might also be related to calling `vendor/drush/drush/drush` instead of `vendor/bin/drush`, we'll see if the test run proves that out: https://travis-ci.org/geerlingguy/drupal-vm/builds/442489483

**Comment by geerlingguy** [comment]
(And on a related note, maybe `sut` or `drush` itself is calling a relative path from the bin, assuming the bin is always located in `vendor/bin`?

**Comment by geerlingguy** [comment]
Specifically: https://github.com/drush-ops/drush/blob/f7fd4b7f41ce868e8c476eed4b729e1d728c8886/sut/autoload.php

**Comment by geerlingguy** [comment]
AHA! Looks like this is directly related: https://github.com/drush-ops/drush/issues/3741

The SUT/testing thing shouldn't even be loaded when Drush is called from outside a working docroot... maybe that's the issue?

**Comment by weitzman** [comment]
Yes, thats a correct summary. I'm thinking about how to bring this capability back, if possible. 

I'm going to close this one in favor of #3741, since it has simple STR. Feel free to join there.

**Comment by geerlingguy** [comment]
Thanks! And sorry for the long comment thread... I figured I'd document things here instead of locally so there's more googleable info. Closing.
