### ISSUE TITLE
drush invocation of himself fails in Cygwin when using PHP for Windows.

### ISSUE THREAD

**Issue by gabrieldamour** [drush-ops/drush#375]
I noticed that among the Drush commands, the ones that **invoke another drush processes** (like updb, upc features-revert-all,...) systematically failed when the command is run from cygwin env: 

Example with the following error message when try to update a module:
`$ drush upc addressfield --verbose`
...
`"/cygdrive/c/Program Files (x86)/PHP/v5.3/php"  -d magic_quotes_gpc=Off -d magic_quotes_runtime=Off -d magic_quotes_sybase=Off "C:\\cygwin64\\usr\\local\\src\\drush\\drush.php" --php="/cygdrive/c/Program Files (x86)/PHP/v5.3/php" --php-options=" -d magic_quotes_gpc=Off -d
magic_quotes_runtime=Off -d magic_quotes_sybase=Off"  --backend=2 --verbose
--root=c:/inetpub/wwwroot/fwc/docroot --uri=http://default  pm-updatestatus addressfield 2>&1`
`The command could not be executed successfully (returned: The system cannot find the path specified., code: 1)`

It is working fine when the same drush command is launch from a mingcw bash or from the [official windows installer](http://www.drush.org/drush_windows_installer)

I tried to alter the drush bootstrap script and to provide various different path in the `--php` option (Cygwin, Windows, escaped...) but nothing works...

The interesting thing is that if I removed completely the `--php` option it then working fine! It is not a proper solution, but is help me for now AND I will propose a patch based on this idea in a drush fork.

And will see how it goes...

My environment is using the following stack: Windows 20XX + IIS + [PHP 5.3](http://www.microsoft.com/web/platform/phponwindows.aspx) + MS SQL Server. Cygwin + drush are use only for admin tasks.

**Comment by Lucas-C** [comment]
Thanks for that one, great tip !
