### ISSUE TITLE
Add uid and mail-based whitelisting from sql:sanitize command

### ISSUE THREAD

**Issue by miloskroulik** [drush-ops/drush#3756]
**Is your feature request related to a problem? Please describe.**
On my website there are some users, whose personal data shouldn't be sanitized, when pulling from production environment to the localhost. Currently, I'm maintaining my own `post-command` to achieve this, but it's troublesome, because of the need to disable default sanitization.

**Describe the solution you'd like**
I would like to add 2 options to the `sql:sanitize` command:

- `--whitelist-uids`
- `--whitelist-mails`

which will skip sanitization for user entities matched.

**Describe alternatives you've considered**
The only alternative I know is using custom `post-command` (and modification of `drush.yml` to disable default sanitization flobally).

**Solution**
I can create a PR, but would like to know your opinion first.

**Comment by weitzman** [comment]
Sounds useful. Or should have tests for new options. Thanks.

**Comment by mattbloomfield** [comment]
I'm curious if anything ever happened with this? It would be useful to me in a project I'm working on now.

**Comment by miloskroulik** [comment]
A lot of other work and lack of experience with drush development prevented me from finishing it so far. I will add a preliminary patch soon, so you can try it out.

**Comment by miloskroulik** [comment]
PR has been added in #4213.

**Comment by miloskroulik** [comment]
@weitzman Tests were added and they passed now. Is there anything else I should do so that #4213 can be merged?

**Comment by Eduardomoberti** [comment]
It is a very good idea, we need something like that on our project.

**Comment by MartijnCuppens** [comment]
Thoughts on adding role based options too?

**Comment by weitzman** [comment]
Lets discuss in #4213.

@MartijnCuppens You might be interested in #4725
