### ISSUE TITLE
Drush outputs malformed tables when run in Docker container, when allocating pseudo-tty and piping/redirecting output of docker exec.

### ISSUE THREAD

**Issue by lukasz-zaroda** [drush-ops/drush#3761]
**Describe the bug**
When run in docker container, by using `docker exec`, assuming `docker exec` has allocated pseudo-tty with `-t` flag, and output of the command is being piped or redirected away, `Drush` runs with COLUMNS=0, which breaks output of tables returned from `docker exec`.

**To Reproduce**
Create docker container with drush, and run any drush command outputting tables with `docker exec -t`, then redirect/pipe output. The output will be messed up.

**Expected behavior**
Properly formatted tables.

**Actual behavior**
Tables are malformed because drush assumes that COLUMNS=0.

**Workaround**
You can avoid `-t` flag of `docker exec`. Without allocating of pseudo-tty drush output is correct. In the case of docker-compose, there is `-T` flag disabling pseudo-tty allocation that also fixes the problem. There may be some other undesirable effects to that though.

You can also pass the "COLUMNS" environmental variable to docker, to set this value manually.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.x
| Drupal version? | 7.x
| PHP version     | 7.1
| OS?             | Linux

**Additional information**
Originally described here: https://stackoverflow.com/questions/53027036/why-piping-output-of-docker-compose-exec-to-grep-breaks-it , I'm creating this issue after diagnosing the exact cause existing in Drush.

**Comment by lukasz-zaroda** [comment]
Actually, after looking deeper into it, it might be an issue with Docker, but I'm not sure, and question remains if Drush could do anything better in this situation.

**Comment by greg-1-anderson** [comment]
For sure, explicitly defining `COLUMNS` to be zero is a degenerate case, and it is not surprising that Drush does not deal with it robustly. However, since it is never sensical to have a zero-column terminal, it would be reasonable to add special-checking in Drush, and treat "0" as "undefined".  I believe that Drush defaults to 80 columns when it cannot determine the number of columns.

**Comment by greg-1-anderson** [comment]
(In other words, "PR welcome")
