### ISSUE TITLE
Regression --pipe -switch changed output

### ISSUE THREAD

**Issue by asodastreamer** [drush-ops/drush#3762]
**Describe the bug**
When using --pipe in 
Drush Commandline Tool 9.2.
we end up also getting the current and the version to be updated to.
This will break compatibility with  scripts and approaches that were working before.

**To Reproduce**
Drupalproject with 
Drush Commandline Tool 9.2. execute `../vendor/drush/drush/drush pm:security --pipe

**Expected behavior**
The same behaviour as in prior mayor versions of drush., so only the name of the module to be updated.

**Actual behavior**
It also returns the current version and the version to update to space sepearated to the module-name

**Workaround**
None.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | Drush Commandline Tool 9.2.
| Drupal version? |  Drupal version   : 8.6.1 
| PHP version     | 7.1
| OS?             | Linux

**Additional information**
None

**Comment by weitzman** [comment]
--pipe has been deprecated and is not supported any more. use --fields and --format to get the data you need.

**Comment by asodastreamer** [comment]
k. will use fields then but still it might cause headaches, because it is deprecated, but so to be removed in future releases, but essentially it was replaced with a function that breaks everything, therefor effectively removing --pipe immediately.

**Comment by greg-1-anderson** [comment]
The `--pipe` in Drush 9 was not promised to be compatible with the `--pipe` in Drush 8. There was never a very formal definition of what `pipe` should do -- it was defined to just be "better output for scripts", and every command did something slightly differently. We therefore did not spend the effort to make pipe exactly identical in all cases.

I wouldn't be entirely adverse to a PR that would "correct" the behavior of `--pipe` in Drush 9 for specific commands to better match what Drush 8 did. Note that it might be difficult in some cases to achieve this, as pipe in Drush 9 is always translated to something expressible in the format system.

Long term, though, you are better off switching to the format / field system, as the meaning of what you are asking for is well-defined, and therefore more likely to remain supported for many major version updates in the future.
