### ISSUE TITLE
pm:security doesnt show unsafe paragraphs package?

### ISSUE THREAD

**Issue by rgpublic** [drush-ops/drush#3767]
Hmm. I just got a mail about:
https://www.drupal.org/sa-contrib-2018-073

But. to my surprise, when I ran pm:security it said "No outstanding security updates". Is that normal? Admittedly, the security warning just got in. Do I have to wait some time until it is shown in pm:security ? Is there a cache I can clear to speed up the process?

```
# composer show | grep paragraphs
Do not run Composer as root/super user! See https://getcomposer.org/root for details
drupal/paragraphs                       1.3.0              Enables the creation of Paragraphs entities.

# drush pm:security
[success] There are no outstanding security updates for Drupal projects.
```

**Comment by greg-1-anderson** [comment]
Try with https://github.com/drush-ops/drush/pull/3766

**Comment by rgpublic** [comment]
Yes, it works. Thanks a lot! I think this fix should be released soon as a drush security update because it might give people a dangerously false sense of security.
