### ISSUE TITLE
Drush 8/Drupal 8/My SQL 5.5

### ISSUE THREAD

**Issue by jdotti06** [drush-ops/drush#3769]
Hi,

I use Drupal 6 on a Centos Server since 10 year. I update with PLESK Mysql (5.5) and my PHP (v7), i install Drush 8 (with drush.phar process). 
Drush works well with my old Drupal V6 website, but i have this error message with my new drupal v8 website : 

> Drush command terminated abnormally due to an unrecoverable error.   [error]
> Error: syntax error, unexpected 'class' (T_CLASS), expecting
> identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in
> /var/www/vhosts/aldeah.org/pilulerouge.org/vendor/symfony/dependency-injection/ContainerBuilder.php,
> line 146

Maybe it's come from the new encoding format of My SQL : 

Before the error message on ContainerBuilder.php, i had this one : Character set 'utf8mb4' is not a compiled character set and is not specified in the '/usr/share/mysql/charsets/Index.xml' file
I had in my.cnf the utf8mb4 directives.

Thank you for helping, without Drush i don't think i can use drupal

JD

**Comment by greg-1-anderson** [comment]
From your symptoms, it looks like you are using an older version of PHP than you think you are. Confirm your $PATH et. al.

Drush should tell you which PHP you're using if you run `drush status` without a Drupal site.

**Comment by jdotti06** [comment]
I Greg,

Tkx for your help : 
`echo $PATH = /root/.rbenv/plugins/ruby-build/bin:/root/.rbenv/shims:/root/.rbenv/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/root/scripts:/usr/local/bin/:/root/bin`
```

drush status = 
PHP configuration      :  /etc/php.ini
 PHP OS                 :  Linux
 Drush script           :  /root/drush
 Drush version          :  8.1.17
 Drush temp directory   :  /tmp
 Drush configuration    :
 Drush alias files      :  /root/.drush/aliases.drushrc.php
```

Maybe you are right. I use 3 php distri, i manage wich distri i use for wich website with PLESK.

```
php -v = 
PHP 5.4.45 (cli) (built: Aug 23 2016 14:41:13)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v5.0.18, Copyright (c) 2002-2015, by ionCube Ltd.
```

The php v7.x is here : 

> /opt/plesk/php/7.1

So i have to indicate to drush the good path for php.ini ?
I try : 

> DRUSH_PHP=/opt/plesk/php/7.1/bin drush cr
I does'nt work

And

> export PATH=/opt/plesk/php/7.1/bin:$PATH

And now is it working ;-)
Tkx
JD
