### ISSUE TITLE
How to define drupal root for drush?

### ISSUE THREAD

**Issue by abarouch** [drush-ops/drush#3771]
I installed Drush 9.3.
when I'm running the command "drush -v" I get this:
<code> [NOTE] Drupal root not found. Pass --root or a @siteAlias in order to see
 !        Drupal-specific commands.</code>
How do i make drush know my Drupal root?
B.T.W I'm having a shared server.
Thanks for Help!

**Comment by weitzman** [comment]
Pass --root option.

Please use Drupal Answers for support questions.
