### ISSUE TITLE
pm:security succeeds if connection to security advisories times out

### ISSUE THREAD

**Issue by malcomio** [drush-ops/drush#3781]
**Describe the bug**
When running `drush pm:security`, the command does not validate that it's possible to reach the list of security advisories before proceeding .

**To Reproduce**
On a server that doesn't have access to the internet, run `drush pm:security`

**Expected behavior**
If the request times out, an error should be reported.
This will allow usage in a CI server.

**Actual behavior**
The command succeeded:

```
 [warning] file_get_contents(https://raw.githubusercontent.com/drupal-composer/drupal-security-advisories/8.x/composer.json): failed to open stream: Connection timed out SecurityUpdateCommands.php:90
 [success] There are no outstanding security updates for Drupal projects.
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.4.0
| Drupal version? | 8.6.2
| PHP version     | 7.2.6
| OS?             |Linux

**Comment by malcomio** [comment]
There's a try/catch around this line of code, but `file_get_contents` doesn't throw an exception if the request times out.

> An E_WARNING level error is generated if filename cannot be found, maxlength is less than zero, or if seeking to the specified offset in the stream fails.
https://secure.php.net/manual/en/function.file-get-contents.php

https://github.com/drush-ops/drush/blob/master/src/Commands/pm/SecurityUpdateCommands.php#L91

**Comment by malcomio** [comment]
nice - thanks

**Comment by sandykadam** [comment]
Can we use curl instead of file_get_contents() as not all of the servers have required permissions or firewall block

**Comment by weitzman** [comment]
No. Please fork or run on a more functional server. You dont need a database present.
