### ISSUE TITLE
Drush can't find all its commands in a subsite

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#3783]
**Describe the bug**

Drush can't find all its commands in a subsite if the default site isn't installed.

**To Reproduce**

I had a local install of Drupal 8, where I had subsites set up. The default site didn't have a database set in its settings.php. I had site aliases set up for the subsites.

**Expected behavior**

Any command using the subsite alias should work.

**Actual behavior**

Using 'drush @subsite st' correctly found the subsite, reported its URI and DB correctly. However, a large number of commands were not available, such as 'drush @subsite en'.

**Workaround**

Install a DB on the default site.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.3.0
| Drupal version? |  8.5.6
| PHP version     | 7.1.19
| OS?             | Mac

**Additional information**

Here's the debug output:

```
$ drush @subsite en --debug
Using the Drush script found at /Users/joachim/Sites/myproject/vendor/drush/drush/drush using proc_open
 [preflight] Config paths: /Users/joachim/Sites/myproject/vendor/drush/drush/drush.yml,/Users/joachim/Sites/myproject/drush/drush.yml
 [preflight] Alias paths: /Users/joachim/Sites/myproject/docroot/drush/sites,/Users/joachim/Sites/myproject/drush/sites
 [preflight] Commandfile search paths: /Users/joachim/Sites/myproject/vendor/drush/drush/src
 [debug] Bootstrap further to find pm:enable
 [debug] Trying to bootstrap as far as we can
 [debug] Done with bootstrap max in Application::find(): trying to find pm:enable again.

In Application.php line 229:

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command pm:enable was not found. Pass --root or a @siteAlias in order to run Drupal-specific commands.


Exception trace:
 Drush\Application->bootstrapAndFind() at /Users/joachim/Sites/myproject/vendor/drush/drush/src/Application.php:191
 Drush\Application->find() at /Users/joachim/Sites/myproject/vendor/symfony/console/Application.php:229
 Symfony\Component\Console\Application->doRun() at /Users/joachim/Sites/myproject/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /Users/joachim/Sites/myproject/vendor/drush/drush/src/Runtime/Runtime.php:112
 Drush\Runtime\Runtime->doRun() at /Users/joachim/Sites/myproject/vendor/drush/drush/src/Runtime/Runtime.php:41
 Drush\Runtime\Runtime->run() at /Users/joachim/Sites/myproject/vendor/drush/drush/drush.php:66
 require() at /Users/joachim/Sites/myproject/vendor/drush/drush/drush:4
```

**Comment by joachim-n** [comment]
> Install a DB on the default site.

Nope, wait, it's still not working.

Weirdly, 'drush @subsite help en' sees the command because it outputs the help, but 'drush @subsite en' fails.

**Comment by greg-1-anderson** [comment]
`@subsite` is an alias with --uri set to a mulitdev?

**Comment by greg-1-anderson** [comment]
Also, please note that the `en` shortcut is special due to Symfony Console oddities. This is not necessarily significant to this incident, but do other commands such as `status` and `pm:enable` behave the same way?

**Comment by greg-1-anderson** [comment]
Does `status` say `connected`?

**Comment by joachim-n** [comment]
It says `Database         : Connected` if that's what you mean. Here is the full output.

```
$ drush @local.subsite st
 Drupal version   : 8.5.6
 Site URI         : http://localhost/myproject/docroot/site-subsite
 DB driver        : mysql
 DB hostname      : localhost
 DB port          : 3306
 DB username      : drupal
 DB name          : drupal-skunk-myproject-subsite
 Database         : Connected
 Drupal bootstrap : Successful
 Default theme    : champions_tennis
 Admin theme      : seven
 PHP binary       : /Applications/MAMP/bin/php/php7.1.19/bin/php
 PHP config       : /Applications/MAMP/bin/php/php7.1.19/conf/php.ini
 PHP OS           : Darwin
 Drush script     : /Users/joachim/Sites/myproject/vendor/drush/drush/drush
 Drush version    : 9.3.0
 Drush temp       : /tmp
 Drush configs    : /Users/joachim/Sites/myproject/vendor/drush/drush/drush.yml
                    /Users/joachim/Sites/myproject/drush/drush.yml
 Install profile  : minimal
 Drupal root      : /Users/joachim/Sites/myproject/docroot
 Site path        : sites/default
 Files, Public    : sites/default/files
 Files, Temp      : /tmp
```

**Comment by weitzman** [comment]
Note that it says  `Site path        : sites/default`. Thats not what you want, right? 

Also please use latest Drush when reporting bugs.

**Comment by joachim-n** [comment]
Just reporting back to say this was actually being caused by the 'default' site's settings.php getting loaded even when specifying @local.beta. And THAT was caused by ACSF module's sites.php file having a sneaky return statement in the middle of it that I hadn't seen, which meant that my Drush site aliases were having no effect and just resolving to the default site.
