### ISSUE TITLE
Cant change PHP version for Drush

### ISSUE THREAD

**Issue by gittingitin** [drush-ops/drush#3785]
I've tried several methods and none are working to get drush to use the latest php7 I have instead of php5. using " .bashrc file or you can do that each time you launch Drush with PATH=foo:$PATH drush" https://github.com/drush-ops/drush/issues/2648 does not work. Wish there was clear concise documentation on how to change this. 

When running drush status it shows php binary but where is this being pulled from? Do I vi a file and update it manually? If so which one?

**Comment by greg-1-anderson** [comment]
Drush is no longer in the business of selecting your PHP version; you must do this in accordance with the instructions for your particular operating system. For example, here is a writeup on how to do it on Ubuntu: https://www.tecmint.com/install-different-php-versions-in-ubuntu/

Please use Stack Exchange for support if you still need help with this.

**Comment by gittingitin** [comment]
I selected my php version for my site but drush is the odd one out not following directions like the rest of the environment

**Comment by cweiske** [comment]
PHP version for drush 8 can be selected with an environment variable `DRUSH_PHP`:

```
DRUSH_PHP=/usr/bin/php7.4 ../vendor/bin/drush site-install ...
```
