### ISSUE TITLE
How to tell "drush php" (interactive shell) to take file changes into account?

### ISSUE THREAD

**Issue by alberto56** [drush-ops/drush#3790]
**Describe the bug**
When "drush php" is used, all changes to php files made while we are in the interactive shell are not reflected.

**To Reproduce**
* Run "drush php"
* Modify any file, for example add a function "hello()" into an active module file.
* While still in the interactive shell, run "hello()"
* You will get an error "call to undefined function"
* Exit the shell and re-enter the shell by running "drush php" again.
* Run "hello()" now and it will work.

**Expected behavior**
I was expecting there to be a flag "--monitor-file-changes" which would allow me to run my new "hello()" function without quitting, then restarting the interactive shell.

**Actual behavior**
"drush php" uses cached versions of the files which do not reflect changes to them.

**Workaround**
Quit and restart the shell

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.1.17 
| Drupal version? | 8.6
| PHP version     | 7.2
| OS?             | Ubuntu

**Comment by weitzman** [comment]
Alas this is not possible. PHP won't can't replace with a newer version of a file once that file has been loaded.
