### ISSUE TITLE
Evolving  Windows support with Composer

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#383]
Now that Composer is the recommended install method, let's plan how we evolve Windows support.

1. Can we write a [composer script](https://getcomposer.org/doc/articles/scripts.md) which downloads the non-composer dependencies and sets up a usable shell? Maybe a shell similar to the experimental zip that @dmitrybezer shared.
1. If we can't do all that, maybe we should at least [get rid of drush.bat](https://getcomposer.org/doc/articles/vendor-binaries.md#what-about-windows-and-bat-files-)

**Comment by ergonlogic** [comment]
@weitzman, is this issue outdated, since the move to distributing .phars?

Could @totten's recent post to php-fig about improving phar support on windows, help whatever issues remain? https://groups.google.com/forum/?fromgroups#!topic/php-fig/VgFFq6BQXA4

**Comment by weitzman** [comment]
That discussion fizzled sadly ... We just got rid of drush.bat.

Windows issues remain but lets discuss elsewhere.
