### ISSUE TITLE
Site in maintenance mode after entity updates are run.

### ISSUE THREAD

**Issue by lpeabody** [drush-ops/drush#3832]
**Describe the bug**
After executing `drush entity-updates --yes`, when loading the site, the site is in maintenance mode.

**To Reproduce**
1) `drush entity-updates --yes`
2) Go to any page on the site.
3) Site is in maintenance mode.

**Expected behavior**
I expect the entity updates to apply and the site to not be in maintenance mode after the updates are complete.

**Actual behavior**
The site is in maintenance mode after entity updates are run.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.0-beta3
| Drupal version? | 8.6.4
| PHP version     | 7.1
| OS?             | Linux

**Comment by minnoce** [comment]
This issue is still present in drush 9.6.0 stable, which became part of the latest official release of Drupal 8.6.12.

**Comment by weitzman** [comment]
entity update command will soon be removed. no further changes are expected.

**Comment by weitzman** [comment]
closing due to https://www.drupal.org/node/3034742
