### ISSUE TITLE
drush make throw an error and fail when mimetype is not found

### ISSUE THREAD

**Issue by samuelsov** [drush-ops/drush#385]
Context : i am using drush make to create drupal with civicrm in it. I need to download some translations file named civicrm.mo. Those file are not recognized by drush which thow an error. drush make seems to fail after that even with --force-complete (temp directory is not copied to its final destination)

It's seems that the only place that use drush_mime_content_type is drush_file_is_tarball. I was wondering why we have to throw an error when mimetype is not find. Can't we just show a warning and return FALSE to indicate that the mimetype was not found. If it's not find, drush_file_is_tarball will simply return FALSE as well and everything works fine.

Do i miss something ?

**Comment by greg-1-anderson** [comment]
Drush make is maintenance only;closing
