### ISSUE TITLE
Fix crash in bootstrap caused by invalid Drupal site

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#3853]
**Describe the bug**
Drush can crash if pointed at a directory that does not contain a supported Drupal site.

**To Reproduce**
`drush --root=/path/to/d7 status`

**Expected behavior**
Status report should show Drush bootstrapped, but no Drupal bootstrap. Optional: could show an "unsupported version" / "Drupal site not found" error message.

**Actual behavior**
Boom.
```
$ ./drush --root=/Users/ganderson/local/sca/website status
PHP Fatal error:  Call to a member function findUri() on null in /Users/ganderson/local/drupal/drush9/drush/src/Boot/BootstrapManager.php on line 132
```

**Workaround**
Only use --root or alias files with valid paths.

**Additional information**
Started fixing this in 80b63b857, but that also broke some bootstraps that should have worked.

**Comment by weitzman** [comment]
If you run with -vvv you usually see the bootstrap step that failed so I'd argue that we already do the _Optional_ part.

**Comment by greg-1-anderson** [comment]
This no longer blows up.
