### ISSUE TITLE
Only pass -A to mysql CLI if there's no terminal

### ISSUE THREAD

**Issue by chx** [drush-ops/drush#3868]
I was very surprised when I found `TAB` no longer working in mysql prompt which I traced back to 3f3449d8fdf712499f28d73617d919f60cd47d97. I changed my `~/.drush/drush.yml` to
```
command:
  sql:
    cli:
      options:
        extra: --auto-rehash
```

I must note `drush help sqlc` doesn't say anything about this new default nor does it tell you how to revert it.

The ideal, in my opinion, would be to use [`stream_isatty`](http://php.net/manual/en/function.stream-isatty.php) (https://github.com/symfony/polyfill/ or https://github.com/symfony/polyfill-php72 has a polyfill for < PHP 7.2) to detect whether the terminal is a TTY and if so, do not pass -A. This would allow scripts to be fast and would keep the mysql command line tool behaving the same if it was started by drush or by hand.

**Comment by weitzman** [comment]
We decided to prioritize fast connection over autocomplete, even for interactive users.

Help cant easily show this default as it is dynamic - mysql only. Sorry for the surprise and inconvenience. Glad you found some config to fix it; thanks for sharing it.
