### ISSUE TITLE
'drush cex' fails on 9.5.2

### ISSUE THREAD

**Issue by emembeka** [drush-ops/drush#3869]
**Describe the bug**
After an site update from drupal 8.5.8 and drush 8.1.16 to drupal 8.6.5 and drush 9.5.2 I was unable to export the actual configuration with 'drush cex'.

**To Reproduce**
It did not happen on any other site where I did the same update, so I'm not sure how to reproduce it on another system :-(

**Expected behavior**
Exporting the current config.

**Actual behavior**

`

michael@bkmove /srv/httpd/vb-hex $ drush cex
Differences of the active config to the export directory:

+-------------+---------------------------------+-----------+
| Collection  | Config                          | Operation |
+-------------+---------------------------------+-----------+
|             | core.extension                  | Update    |
|             | config_split.config_split.dev   | Delete    |
| language.de | block.block.bartik_account_menu | Update    |
| language.de | block.block.bartik_tools        | Update    |
| language.ru | block.block.bartik_account_menu | Update    |
| language.ru | block.block.bartik_tools        | Update    |
+-------------+---------------------------------+-----------+

 The .yml files in your export directory (../config/sync) will be deleted and replaced with the active config. (yes/no) [yes]:
 > 

In FileStorage.php line 254:
                                                                                                              
  FilesystemIterator::__construct(../config/sync/language/ar): failed to open dir: No such file or directory  
                                                                                                              

config:export [--add] [--commit] [--message MESSAGE] [--destination [DESTINATION]] [--diff] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--druplicon] [--notify [NOTIFY]] [--xh-link XH-LINK] [--] <command> [<label>]

`

After this event, the '../config/sync/language/ar' does not exist, as complained.
The other language directories (de,en,ru, zh-hans )are still in place, the ../config/sync directory is empty.

**Workaround**
I tried every  version of drush 9.0.x .. 9.4.0 - they where all running correctly, so I use 9.4.0 in the moment.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version  | 9.5.2
| Drupal version | 8.6.5
| PHP version     | PHP 7.2.14-1+ubuntu18.04.1+deb.sury.org+1
| OS             | Linux

**Additional information**
We are using config_split and config_ignore, I disabled both the elimate problems there, the effect was the same.

**Comment by weitzman** [comment]
Without Steps to Reproduce, its hard to help here.

**Comment by emembeka** [comment]
> Without Steps to Reproduce, its hard to help here.

Sorry, I'm completely clueless what is happening there, my feeling is that it is a problem of the multilanguage configuration.
I hoped you had an idea where to start looking into the problem. 

Nevertheless I'll try to setup a system from the scratch with this error.

**Comment by emembeka** [comment]
A sideeffect of this problem is that the error is not caught, so that drush crashes and the config directory is deleted completely.

**Comment by weitzman** [comment]
Please post here if Steps to Reproduce arise.
