### ISSUE TITLE
putting the site alias after the 'status' command produces unrelated error

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#3871]
**Describe the bug**

Unclear error message.

**To Reproduce**

I accidentally typed 'drush st @local.foo' instead of 'drush @local.foo st'

**Expected behavior**

Tell me I got the order of parameters wrong.

**Actual behavior**

```
In FormatterManager.php line 229:

  The format table cannot be used with the data produced by this command, which was an instance of Consolidation\Ou
  tputFormatters\StructuredData\UnstructuredData.  Valid formats are: csv,json,list,null,php,print-r,tsv,var_dump,v
  ar_export,xml,yaml
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.5.2
| Drupal version? | 8.6.5
| PHP version     | 7.1
| OS?             | Mac

**Comment by weitzman** [comment]
The command param is deprecated. From its help `* @param $filter A field to filter on. @deprecated - use --field option instead.`. So no further fixes are desired for this param.

**Comment by joachim-n** [comment]
@weitzman I'm not following how your comment is at all related to this issue, sorry! There's nothing about the filter or field in my issue report.

**Comment by greg-1-anderson** [comment]
Here's what is going on:
```
./drush status @remote --format=yaml
{  }
```
The last argument is taken as a filter (that's what Moshe was talking about). It doesn't match anything, so you get an empty array. The empty array confuses the table formatter, which tells you to use a different format. If you use a different format, then you'll see the empty table.

This is a bug, but it's a minor one, and related to a deprecated feature.

**Comment by joachim-n** [comment]
I'm still seeing this on Drush 10.3.6.

If the @remote param was deprecated in Drush 9 (when I reported this), shouldn't it be gone by now?

**Comment by weitzman** [comment]
No, noone has submitted a PR to remove it. It is low priority.
