### ISSUE TITLE
Add command to process a single item from a queue

### ISSUE THREAD

**Issue by jose-oliveira** [drush-ops/drush#3872]
**Describe the solution you'd like**
As a Drush user I would like to have a command where I can process a single item from a queue.

**Additional context**
I'm working on a script that iterates through all sites on a very large (80+) multisite codebase and clears as many items from a given queue shared across these sites as it can in a given time limit by processing one item of each site's queue per iteration.

**Example:**  
`drush custom-multisite-iterator-command --total-time-limit=60 queue-run-single my_queue`

- custom-multisite-iterator-command: A custom command that iterates through a given site list and executes a given command across these sites as many times as possible in the given time limit.
- queue-run-single: Processes a single item of a given queue.

**Comment by weitzman** [comment]
See pr
