### ISSUE TITLE
Illegal option 'pipefail' in sql:dump with gzip on Ubuntu

### ISSUE THREAD

**Issue by gchaix** [drush-ops/drush#3874]
**Describe the bug**
When running `drush sql:dump --gzip` with drush 9.6.0-beta4 on Ubuntu 16.04 LTS the task fails with a "set: illegal option -o pipefail".  It appears that the system execs on Ubuntu may be using `sh`/`dash` instead of `bash`, as `sh` does not support `pipefail`.

**To Reproduce**
Execute `/path/to/drush sql:dump --gzip > /path/to/dump.sql.gz`

**Expected behavior**
A gzipped dump file would appear at `/path/to/dump.sql.gz`

**Actual behavior**
The command encounters a fatal error:
```
# /var/www/vendor/bin/drush sql-dump --gzip --debug > /backups/db/test.sql.gz
 [preflight] Config paths: /var/www/vendor/drush/drush/drush.yml,/var/www/drush/drush.yml
 [preflight] Alias paths: /var/www/web/drush/sites,/var/www/drush/sites
 [preflight] Commandfile search paths: /var/www/vendor/drush/drush/src,/var/www/drush
 [bootstrap] Starting bootstrap to max [0.23 sec, 8.43 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalRoot() [0.23 sec, 8.43 MB]
 [bootstrap] Change working directory to /var/www/web [0.23 sec, 8.43 MB]
 [bootstrap] Initialized Drupal 8.6.7 root directory at /var/www/web [0.23 sec, 8.62 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalSite() [0.23 sec, 8.91 MB]
 [bootstrap] Initialized Drupal site xxx at sites/default [0.24 sec, 9.08 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalConfiguration() [0.24 sec, 9.08 MB]
 [debug] Add service modifier [0.24 sec, 9.3 MB]
 [info] Executing: command -v mysql [0.25 sec, 9.74 MB]
 [info] sql:query: SHOW TABLES; [0.25 sec, 9.8 MB]
 [info] Executing: mysql --defaults-file=/tmp/drush_0XiJU0 --database=xxx --host=xxx --port=3306 --silent -A < /tmp/drush_mjVvMo [0.25 sec, 9.8 MB]
 [info] Executing: set -o pipefail; mysqldump --defaults-file=/tmp/drush_MHYv8C  xxx --host=xxx --port=3306 --no-autocommit --single-transaction --opt -Q  | gzip -f [0.28 sec, 9.81 MB]
> sh: 1: set: Illegal option -o pipefail

In SqlCommands.php line 231:

  [Exception]
  Unable to dump database. Rerun with --debug to see any error message.


Exception trace:
 () at /var/www/vendor/drush/drush/src/Commands/sql/SqlCommands.php:231
 Drush\Commands\sql\SqlCommands->dump() at n/a:n/a
 call_user_func_array() at /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php:257
 Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() at /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php:212
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php:178
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /var/www/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:302
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /var/www/pds/releases/master-2019-01-17-221207/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /var/www/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /var/www/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/vendor/drush/drush/src/Runtime/Runtime.php:118
 Drush\Runtime\Runtime->doRun() at /var/www/vendor/drush/drush/src/Runtime/Runtime.php:49
 Drush\Runtime\Runtime->run() at /var/www/vendor/drush/drush/drush.php:69
 require() at /var/www/vendor/drush/drush/drush:4

sql:dump [--result-file RESULT-FILE] [--create-db] [--data-only] [--ordered-dump] [--gzip] [--extra EXTRA] [--extra-dump EXTRA-DUMP] [--format [FORMAT]] [--fields FIELDS] [--field FIELD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--database [DATABASE]] [--target [TARGET]] [--db-url DB-URL] [--skip-tables-key SKIP-TABLES-KEY] [--structure-tables-key STRUCTURE-TABLES-KEY] [--tables-key TABLES-KEY] [--skip-tables-list SKIP-TABLES-LIST] [--structure-tables-list STRUCTURE-TABLES-LIST] [--tables-list TABLES-LIST] [--notify] [--xh-link XH-LINK] [--druplicon] [--] <command>
```

**Workaround**
Removing `--gzip` resolves the problem

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.0-beta4
| Drupal version? | 8.6.7
| PHP version     | 7.2.8-1+ubuntu16.04.1+deb.sury.org+
| OS?             | Ubuntu 16.04.5 LTS "xenial"

**Additional information**
This problem is not present in 9.5.x versions of drush and was likely introduced in #3818

**Comment by LionsAd** [comment]
Suggested fix: Call `bash` instead of `sh` :)

**Comment by greg-1-anderson** [comment]
If your shell does not like pipefail, you can turn it off:

**drush.yml:**
```
ssh:
  pipefail: ''
```
Untested, but see if that works for you.

**Comment by greg-1-anderson** [comment]
Drush has always presumed Bash. Back when I was using Ubuntu as my primary system, I always changed the default `sh` to point to bash rather than dash. This helped for quite a number of situations, not just Drush / Drupal.

The `pipefail` is actually quite important to prevent errors from being silently ignored. Did you try disabling pipefail in drush.yml? This will probably be the required action for folks who prefer their distros default shell to Bash. I don't think that we want to make a remote call just to detect the shell, or worse, try to send shell-agnostic commands.

**Comment by gchaix** [comment]
The `drush.yml` bit did work, but I don't see that as a proper solution.  I agree `pipefail` is important and shouldn't be disabled.  This is a stock Ubuntu LTS install and my shell *is* `bash` (the shell output in my above comment is running from bash) yet PHP is still executing shell commands with `sh`.  Since this feature breaks gzipped database dumps from drush on a current Ubuntu LTS I'd think we'd want to ensure system calls from drush are actually calling `bash`.  What I'm seeing here is that on at least some Ubuntu versions PHP's shell commands are being executed in `sh` instead even when the executing user's shell is `bash`.  I've tested this on both 16.04 and 18.04 and have seen the same results.

**Comment by greg-1-anderson** [comment]
Here's an explanation about why Ubuntu switched the default shell from dash to bash:

https://lwn.net/Articles/343924/

Now, as I mentioned above, if you change your default shell back to bash (change the symlink at /bin/sh from dash to bash), then a lot of things work better. Slower, but better. I never really noticed the performance hit.

As for solutions for folks who want pipefail to work by default on their system, I'm not sure what is best. It would be ideal if php had an ini setting to select the default shell for exec, but it does not.

I found that the following worked on both Mac and Ubuntu 18.04:
```
php -r 'passthru("bash -c \"set -o pipefail; echo $0\"");'
```
That wouldn't work when `bash` wasn't available, but then again, neither does pipefail. The downside, though, is that currently folks can turn off pipefail if they don't want it, which is a solution for non-bash users. If we were going to wrap the whole command in a `bash -c`, then we'd want a way to disable it. More to the point, *not* wrapping in `bash -c` should be the default. Adding multiple preferences to let everyone fine-tune their shell commands might get a little complicated.

I'd like this to just work by default for everyone, but I'm not seeing a good solution that's simple and universally applicable. What we have today seems reasonable: if you want pipefail, your default shell should be bash (it's a bash feature). If you don't want pipefail, you can turn it off (same as every version of Drush prior to 9.6).

If you have a better proposal, I'd like to hear it.

**Comment by greg-1-anderson** [comment]
Actually, the above solution isn't great, as `drush sql:dump` will also output to stdout if no result file is specified. The `gzip` option currently works in this mode; using `--resultfile` in the call to mysqldump would complicate things considerably.
