### ISSUE TITLE
site-install doesn't work with Drush 9.6.0-beta4 &Drush 9.6.0-rc1 (Win10)

### ISSUE THREAD

**Issue by ms-slasher13** [drush-ops/drush#3884]
**Describe the bug**
In SiteInstallCommands.php line 361:
                                          
  Failed to drop or create the database: 
It works on Drush 9.6.0-beta3

Debugging:
cmd /V:ON /E:ON /D /C (mysql --defaults-file="C:\\Users\\*****\\AppData\\Local\\Temp\\dru1D0A.tmp" --database=information_schema --host=localhost --port=3306 --silent -A < 'C:\Users\*****\AppData\Local\Temp\dru196F.tmp') 1>"C:\tmp\sf_proc_00.out" 2>"C:\tmp\sf_proc_00.err"

sf_proc_00.out: "The syntax for filename, directory name, or volume label is incorrect."
sf_proc_00.out:""
dru196F.tmp: "DROP DATABASE IF EXISTS ****; CREATE DATABASE ***** /*!40100 DEFAULT CHARACTER SET utf8 */;"
dru1D0A.tmp: '#This file was written by Drush's Sqlmysql.php.
[client]
user="XXXXXX"
password="XXXXX"'

**To Reproduce**
Use windows 10 and drush site-install
Drupal version   : 8.6.7                                                                 
 Site URI         : http://default                                                        
 DB driver        : mysql                                                                 
 DB hostname      : localhost                                                             
 DB port          :                                                                       
 DB username      : *****                                                              
 DB name          : *****                                                                 
 Database         : Connected                                                             
 Drupal bootstrap : Successful                                                            
 Default theme    : *****                                                                  
 Admin theme      : seven                                                                 
 PHP binary       : C:\Apache24\php\php.exe                                 
 PHP config       : C:\tmp\E561.tmp                                                       
 PHP OS           : WINNT                                                                 
 Drush script     : C:\drush-launcher\drush                                 
 Drush version    : 9.6.0-rc1                                                             
 Drush temp       : C:\Users\*****\AppData\Local\Temp                                
 Drush configs    : C:\src\vendor\drush\drush/drush.yml              
 Install profile  : anwalt24_dev                                                          
 Drupal root      : C:\src                                           
 Site path        : sites/default                                                         
 Files, Public    : sites/default/files                                                   
 Files, Private   : C:\src\sites\default/../../../deployment/private 
 Files, Temp      : /tmp 

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.0-beta4 & 9.6.0-rc1
| Drupal version? | 8.6.7
| PHP version     | 7.2
| OS?             | Windows
| MySQL | Ver 14.14 Distrib 5.7.22, for Win64 (x86_64)

**Comment by weitzman** [comment]
Can you tell what file is incorrect exactly?

**Comment by greg-1-anderson** [comment]
Windows shell escaping hasn't gotten extensive testing in Drush 9.6.x, and a lot has changed there. Detailed comparison between correctly-escaped commands in Drush 9.5.x and incorrectly-escaped commands in Drush 9.6.x would be very helpful. Please use triple-back-ticks to make sure that GitHub renders your example clearly.

**Comment by ms-slasher13** [comment]
The problem are single quotes of
```'C:\Users*****\AppData\Local\Temp\dru196F.tmp'```
must be double quotes.

**Comment by weitzman** [comment]
lest continue in the PRs
