### ISSUE TITLE
Over-escaping in drush ssh when using compound statement

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#3894]
from @mishac in #drush

```
$ drush -v @dev ssh "cd .. && pwd"
[info] Executing: ssh -o PasswordAuthentication=no USER@HOST 'cd /var/www/vhosts/HOST/dev/web && cd .. '\''&&'\'' pwd' 
```

Note odd escaping of `&&`

We may need to assume already-escaped in this case.

**Comment by greg-1-anderson** [comment]
I think we need to presume that if there is only one parameter to ssh, then it is pre-escaped.

I'm not sure exactly where is the best place to insert that assumption. I think that if the Drush ssh command did the check and wrapped its only parameter in `Shell::preEscaped()`, it would work.
