### ISSUE TITLE
Add Drush support for Oracle database

### ISSUE THREAD

**Issue by jaydee18** [drush-ops/drush#3896]
**Is your feature request related to a problem? Please describe.**
I am required to use Oracle DB for my Drupal projects. As there is no drush support for Oracle db, I'm forced to use UI tools for most actions.

**Describe the solution you'd like**
I'd like to be able to use drush on Drupal sites that utilise Oracle db.

**Describe alternatives you've considered**
Drupal Console - however that too lacks support for Oracle db.

**Additional context**
none

**Comment by jaydee18** [comment]
Yeah - nah they don't. If I run a drush command, I get:

[warning] Declaration of Drush\Sql\SqlOracle::createdbSql($dbname) should be compatible with Drush\Sql\SqlBase::createdbSql($dbname, $quoted = false) SqlOracle.php:98
 [info] Undefined variable: db_spec SqlOracle.php:27
 [info] Executing: rlwrap sqlplus  myUsername/myPassword@//myHostname:1521/myDatabaseName   @ /tmp/drush_gGOeSA > /dev/null

The command then hangs until timing out

**Comment by jaydee18** [comment]
Making this change to the creds function seems to work - though I've by no means done any extensive testing.

`  public function creds($hide_password = true)
  {
    $dbSpec = $this->getDbSpec();
    $parameters['dbname'] = $dbSpec['database'];
    $parameters['username'] = $dbSpec['username'];
    $parameters['host'] = empty($dbSpec['host']) ? 'localhost' : $dbSpec['host'];
    $parameters['port'] = empty($dbSpec['port']) ? '1521' : $dbSpec['port'];
     
    return $this->paramsToOptions($parameters);

//    return ' ' . $dbSpec['username'] . '/' . $dbSpec['password'] . ($dbSpec['host'] == 'USETNS' ? '@' . $dbSpec['database'] : '@//' . $dbSpec['host'] . ':' . ($dbSpec['port'] ? $dbSpec['port'] : '1521') . '/' . $dbSpec['database']);
   }`

**Comment by weitzman** [comment]
Please open PRs with fixes. If no significant contributions come in, we will be removing Oracle and SQL Server support from Drush 10.
