### ISSUE TITLE
Invalid argument supplied for foreach() ParameterInjection.php:31

### ISSUE THREAD

**Issue by Jeka-nn** [drush-ops/drush#3898]
$drush help
 [warning] Invalid argument supplied for foreach() ParameterInjection.php:31

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.5.2 
| Drupal version? | 8.x
| PHP version     | 7.2
| OS?             | Linux

**Comment by cspitzlay** [comment]
I am seeing this, too.
It seems to be an incompatibility between drush 8.5.2 and consolidation/annotated-command 2.11.1.

drush 8.5.2 and annotated-command 2.11.0 work,
as do 
drush 9.6.0-rc2 and annotated-command 2.11.1.

**Comment by greg-1-anderson** [comment]
If using Drush 8.5.2 with Annotated Command 2.11.1, try `drush cc drush` and see if that clears up the problem.  If not, please provide more details, e.g. is this every command, or only `sql:cli` or other?

**Comment by cspitzlay** [comment]
1. I had copied the "8.5.2" from Jeka-nn's report above, I was really talking about version 9.5.2.
2. Using `drush cc drush` solved the issue.  Thanks.

Fun fact: `drush cc drush` itself displayed the warning one last time before it did its job.  ;-)

**Comment by greg-1-anderson** [comment]
Yeah there is no 8.5.2 I read that as 9.5.2 even though I typed 8.5.2. 😝 

Thanks for confirming about `drush cc drush`. I'll roll a new annotated-command so folks don't need to work around this.
