### ISSUE TITLE
supplied argument is not a valid stream resource

### ISSUE THREAD

**Issue by fatkinson** [drush-ops/drush#390]
I installed Drush on three of my Web sites.
When I try to run it, this is what I get:

xxxxxxxx@xxxxxx.net [~]# drush
Content-type: text/html

Warning: fwrite(): supplied argument is not a valid stream resource in /home/atkinson/public_html/drush/includes/output.inc on line 35
xxxxxxxx@xxxxxx.net [~]#

Does anyone have a clue as to what this problem is?

**Comment by greg-1-anderson** [comment]
Closing old support request (looks like using php-cgi instead of php-cli)
