### ISSUE TITLE
Undefined index "injected_classes" when updating consolidation/annotated-command to 2.11.1 

### ISSUE THREAD

**Issue by Jesmaster** [drush-ops/drush#3900]
consolidation/annotated-command just released version 2.11.1 a day ago, trying to run drush commands with this version results in several warning messages.

> [notice] Notice: Undefined index: injected_classes in Consolidation\AnnotatedCommand\Parser\CommandInfoDeserializer->constructFromCache() (line 48 of /var/www/localhost/vendor/consolidation/annotated-command/src/Parser/CommandInfoDeserializer.php) #0 /var/www/localhost/web/core/includes/bootstrap.inc(584): _drupal_error_handler_real(8, 'Undefined index...', '/var/www/localh...', 48, Array)

If I set a hard requirement for version 2.11.0 in my composer.json file it fixes the problem.

For reference here is the commit where they introduced the injected_classes index: https://github.com/consolidation/annotated-command/commit/d912f2603e4f1c6f4b4eed99d04d41419e8ad2e0

**Comment by greg-1-anderson** [comment]
The cache version was bumped up by one; that should have prevented this. Try `drush cc drush`

I'll make a 2.11.2 to address as well.

**Comment by greg-1-anderson** [comment]
Released annotated-command 2.11.2.

**Comment by Jesmaster** [comment]
Confirmed fixed in 2.11.2. Did not need to clear drush cache.
