### ISSUE TITLE
What is the proper usage of php:eval in Drush 9?

### ISSUE THREAD

**Issue by aangelinsf** [drush-ops/drush#3908]
I don't understand what I'm missing.

`drush php:eval "echo 'hello';"`

should produce 'hello' yet I get:
`Too many arguments, expected argument "command" "code."`

What does "command" refer to?

Earlier versions of Drush worked with just `drush ev "echo 'hello'".

### System Configuration
Drush version: 9.5.2
Drupal version: 8.6.7
php: 7.2.13
macOS: 10.13.6

**Comment by greg-1-anderson** [comment]
Works for me:
```
$ drush9 php:eval 'print "hi\n";'
hi
$ drush9 php:eval "print 'hi';"
hi
# No EOL printed after previous example; inserted space for clarity
$ echo 'print "hi\n";' | drush9 php:script -
hi
```
I'm using the current HEAD of master (Drush 9.6.x)

**Comment by greg-1-anderson** [comment]
I do wonder if maybe you have installed Drush via `composer global require`, or otherwise gotten your dependencies in a pinch. See: [Fixing the Composer Global Command](https://pantheon.io/blog/fixing-composer-global-command)

**Comment by aangelinsf** [comment]
Thx, will explore some more and report back.
