### ISSUE TITLE
--uri requires trailing slash to work as expected

### ISSUE THREAD

**Issue by grasmash** [drush-ops/drush#3911]
Testing `drush status --uri=[site-path]`, I get unexpected results for the calculated `$site_path` depending on small variations in formatting.

I'm stepping through DrupalBoot8.php via xdebug, and I see that confPath() returns the following: 

  * `--uri=www.example.com/site1`, $site_path is sites/default
  * `--uri=www.example.com/site1/` $site_path is sites/example.com.site1 
  * `--uri=www.example.com.site1` $site_path is sites/example.com.site1

I'd expect the first entry to return `sites/example.com.site1`, but looks like a trailing slash is required. 

Drush should not require a trailing slash in order for `$site_path` to be correctly calculated.

**Comment by rmuit** [comment]
Please test https://github.com/drush-ops/drush/pull/3847 and join me in arguing for its inclusion. IMHO it's a trivial fix (but unfortunately I complicated the PR comments).

**Comment by bobbygryzynger** [comment]
I'm also seeing this behavior. The same thing occurs when a site's `uri` in an alias file doesn't contain a trailing slash.

**Comment by weitzman** [comment]
Possibly fixed by #3978. Can anyone recheck?

**Comment by rmuit** [comment]
It's fixed.

**Comment by weitzman** [comment]
Thanks for checking.
