### ISSUE TITLE
 Drush was unable to query the database. As a result, many commands are unavailable

### ISSUE THREAD

**Issue by paulfm** [drush-ops/drush#3913]
**Describe the bug**
I am using fresh Drupal 8  installations using Composer. To keep it simple I start off with using vendor/bin/drush to execute commands. Some commands word such as "drush version, drush cr, and drush status"

drush status results:
**Paul@Paul-Toshiba /c/Ampps/www/d8-bridgesnj-v2 (master *=) $ drush status
 Drupal version : 8.6.8
 Site URI       : default
 DB driver      : mysql
 DB hostname    : localhost
 DB port        : 3306
 DB username    : Paul
 DB name        : d8-bridges-v2
 PHP binary     : C:\Ampps\php-7.1\php.exe
 PHP config     : C:\Ampps\php-7.1\php.ini
 PHP OS         : WINNT
 Drush script   : /Ampps/www/d8-bridgesnj-v2/vendor/drush/drush/drush
 Drush version  : 9.5.2
 Drush temp     : C:\Users\Paul\AppData\Local\Temp
 Drush configs  : C:\Users\Paul\.drush/drush.yml
                  C:\Ampps\www\d8-bridgesnj-v2\vendor\drush\drush/drush.yml
                  C:\Ampps\www\d8-bridgesnj-v2\drush/drush.yml
 Drupal root    : C:\Ampps\www\d8-bridgesnj-v2/web
 Site path      : sites/default**

When I use commands such as drush ws I get the following:
  Command ws was not found. Drush was unable to query the database. As a result, many commands are unavailable. Re-run your command with --debug to see relevant log messages.

With --debug I get:

[preflight] Config paths: C:\Users\Paul\.drush/drush.yml,C:\Ampps\www\d8-bridgesnj-v2\vendor\drush\drush/drush.yml,C:\Ampps\www\d8-bridgesnj-v2\drush/drush.yml
 [preflight] Alias paths: C:\Users\Paul/.drush/sites,/etc/drush/sites,C:\Ampps\www\d8-bridgesnj-v2\web/drush/sites,C:/Ampps/www/d8-bridgesnj-v2/drush/sites
 [preflight] Commandfile search paths: C:\Ampps\www\d8-bridgesnj-v2\vendor\drush\drush\src,C:\Ampps\www\d8-bridgesnj-v2/drush
 [debug] Bootstrap further to find ws
 [debug] Trying to bootstrap as far as we can
 [bootstrap] Drush bootstrap phase: bootstrapDrupalRoot()
 [bootstrap] Change working directory to C:\Ampps\www\d8-bridgesnj-v2/web
 [bootstrap] Initialized Drupal 8.6.8 root directory at C:\Ampps\www\d8-bridgesnj-v2/web
 [bootstrap] Drush bootstrap phase: bootstrapDrupalSite()
 [bootstrap] Initialized Drupal site default at sites/default
 [bootstrap] Drush bootstrap phase: bootstrapDrupalConfiguration()
 [debug] Add service modifier
 [info] sql-query: SELECT 1;
 [info] Executing: mysql --defaults-file="C:\\Users\\Paul\\AppData\\Local\\Temp\\dru86DB.tmp" --database=d8-bridges-v2 --host=localhost --port=3306 --silent -A < "C:\\Users\\Paul\\AppData\\Local\\Temp\\dru86DA.tmp" > nul
 [bootstrap] Drush was not able to start (bootstrap) the Drupal database.
Hint: This may occur when Drush is trying to:
 * bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working database setup by specifying the URI to use with the --uri parameter on the command line. See `drush topic docs-aliases` for details.
 * connect the database through a socket. The socket file may be wrong or the php-cli may have no access to it in a jailed shell. See http://drupal.org/node/1428638 for details.
More information may be available by running `drush status`
 [debug] Bootstrap phase bootstrapDrupalDatabase() failed to validate; continuing at bootstrapDrupalConfiguration()
 [debug] Done with bootstrap max in Application::find(): trying to find ws again.

In Application.php line 238:

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command ws was not found. Drush was unable to query the database. As a result, many commands are unavailable. Re-run your command with --debug to see relevant log messages.

Exception trace:
 () at C:\Ampps\www\d8-bridgesnj-v2\vendor\drush\drush\src\Application.php:238
 Drush\Application->bootstrapAndFind() at C:\Ampps\www\d8-bridgesnj-v2\vendor\drush\drush\src\Application.php:191
 Drush\Application->find() at C:\Ampps\www\d8-bridgesnj-v2\vendor\symfony\console\Application.php:229
 Symfony\Component\Console\Application->doRun() at C:\Ampps\www\d8-bridgesnj-v2\vendor\symfony\console\Application.php:148
 Symfony\Component\Console\Application->run() at C:\Ampps\www\d8-bridgesnj-v2\vendor\drush\drush\src\Runtime\Runtime.php:112
 Drush\Runtime\Runtime->doRun() at C:\Ampps\www\d8-bridgesnj-v2\vendor\drush\drush\src\Runtime\Runtime.php:41
 Drush\Runtime\Runtime->run() at C:\Ampps\www\d8-bridgesnj-v2\vendor\drush\drush\drush.php:66
 require() at C:\Ampps\www\d8-bridgesnj-v2\vendor\drush\drush\drush:4

**Comment by weitzman** [comment]
Try with Drush 9.6. It does not use `mysql` during bootstrap so all commands except sql:* may start working for you. 

Afterwards we can figure out whats up with `mysql --database=d8-bridges-v2 --host=localhost --port=3306 --silent -A` (you need to add -u and -p to that and then debug any errors).

**Comment by paulfm** [comment]
With drush 9.6.0-rc3 installed I can now run "drush ws" without any problem. I did also add the path to Ampps mysql in the system path as well.

If I try to run "vendor/bin/drush sql:dump --result-file=test.sql" I get:

[warning] The shell command 'mysql' is required but cannot be found. Please install it and retry.

**Comment by weitzman** [comment]
MySQL client must be installed and on your PATH for those commands to work.

**Comment by paulfm** [comment]
MySQL is installed with Ampps and the path D:\paulm\Ampps\mysql\bin is set under my System Variables.

**Comment by weitzman** [comment]
Can you please share the output with -vvv?

**Comment by greg-1-anderson** [comment]
I think that Drush searches for external binaries with `command` now. It needs to use `where.exe` on Windows. PRs welcome.

**Comment by paulfm** [comment]
paulm@Paul-Aurora-R7 /d/paulm/Ampps/www/d8-bridgesnj-v2 (staff=) $ vendor/bin/drush sql:dump --result-file=test.sql -vvv
 [preflight] Config paths: C:\Users\paulm\.drush/drush.yml,D:\paulm\Ampps\www\d8-bridgesnj-v2\vendor\drush\drush/drush.yml,D:\paulm\Ampps\www\d8-bridgesnj-v2\drush/drush.yml
 [preflight] Alias paths: C:\Users\paulm/.drush/sites,/etc/drush/sites,D:\paulm\Ampps\www\d8-bridgesnj-v2\web/drush/sites,D:/paulm/Ampps/www/d8-bridgesnj-v2/drush/sites
 [preflight] Commandfile search paths: D:\paulm\Ampps\www\d8-bridgesnj-v2\vendor\drush\drush\src,D:\paulm\Ampps\www\d8-bridgesnj-v2/drush
 [bootstrap] Starting bootstrap to max [0.3 sec, 8.55 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalRoot() [0.3 sec, 8.55 MB]
 [bootstrap] Change working directory to D:\paulm\Ampps\www\d8-bridgesnj-v2/web [0.3 sec, 8.55 MB]
 [bootstrap] Initialized Drupal 8.6.8 root directory at D:\paulm\Ampps\www\d8-bridgesnj-v2/web [0.31 sec, 8.71 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalSite() [0.31 sec, 9.08 MB]
 [bootstrap] Initialized Drupal site example.com at sites/default [0.31 sec, 9.37 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalConfiguration() [0.32 sec, 9.37 MB]
 [debug] Add service modifier [0.32 sec, 9.57 MB]
 [info] Executing: command -v mysql [0.33 sec, 10.05 MB]
 [warning] The shell command 'mysql' is required but cannot be found. Please install it and retry. [0.54 sec, 10.16 MB]

**Comment by paulfm** [comment]
[greg-1-anderson](/greg-1-anderson) - where.exe is in the windows/system32 directory which is in the system path.

**Comment by weitzman** [comment]
what shows when you run `command -v mysql` at the CLI? how about `where mysql`?

**Comment by paulfm** [comment]
command -v mysql - /d/paulm/Ampps/mysql/bin/mysql

where mysql - D:\paulm\Ampps\mysql\bin\mysql.exe

**Comment by weitzman** [comment]
thanks. it looks like those commands are working, but Symfony Process reports that they are not. Odd. The code in question: https://github.com/drush-ops/drush/blob/0d25067a5cbdf599b7a09b1b454b2543c5984163/src/Exec/ExecTrait.php#L83-L94

**Comment by paulfm** [comment]
Unfortunately, this is above my skill level. I do wonder if this problem is tied to the fact that I have never been able to get the 'drush init' to work or the  Drush Launcher as per [https://docs.drush.org/en/master/install/]? I always need to use the vendor/bin/drush path to run drush commands.

**Comment by paulfm** [comment]
Problem fixed. I don't know what caused the problem but I deleted the project and recreated it using 'git clone' and 'composer install'. No problems with the database now. Thank you weitzman and [greg-1-anderson](/greg-1-anderson) for your help.

I just wish I could get Drush to work without having to use the full path but this is consistent in all my projects on this computer.

**Comment by akash-datamatics** [comment]
I have fixed this issue by adding below command in gitbash before running **drush en module_name**:
**export PATH=/d/xamp/mysql/bin/:$PATH**
where "/d/xamp/mysql/bin/" is my mysql bin path
![drush_issue](https://user-images.githubusercontent.com/44406451/63669916-f81d5700-c7f8-11e9-90e5-753ece8c03f7.png)

**Comment by minnur** [comment]
Adding `export PATH=/Applications/MAMP/Library/bin/:$PATH` to `vim ~/.bash_profile` solved the issue on MAMP. Make sure to execute `source ~/.bash_profile`  after the change you make in the file.

**Comment by omrmankar** [comment]
Restart the MySQL server and a check will work.
is happing because some time MySQL connection lost that why happing

**Comment by shital7mahajan** [comment]
Thanks restart MYSQL server worked for me !!

**Comment by hermann77** [comment]
Only mysql restart helped. Thanks!

**Comment by jannakha-copy-01** [comment]
this worked for me:
sudo ln -s /Applications/MAMP/Library/bin/mysql80/bin/mysql /usr/local/bin/mysql
