### ISSUE TITLE
Wrongly identifies Drupal 8.5.10 needing a security update

### ISSUE THREAD

**Issue by if-kenn** [drush-ops/drush#3914]
**Describe the bug**
It looks like Drush misidentifies core security updates for Drupal 8.5.x. We have quite a few sites that have not been updated to Drupal 8.6.x and because of this bug it plays havoc with our automation systems, sending out false alerts.

**To Reproduce**
On a Drupal 8.5 site issue the following command:
```
drush ups --security-only --fields=name,existing_version,candidate_version"
```

**Expected behavior**
That core would not be identified as needing a security update

**Actual behavior**
This output is given:
```
Short Name  Installed Version  Proposed version
drupal      8.5.10             8.6.8
```

**Workaround**
None that I know.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.1.15
| Drupal version? | 8.5.10
| PHP version     | 7.2.14
| OS?             | Mac

**Additional information**
We have also seen this on previous core updates that are not the most recent Drupal 8 version, e.g. Drupal 8.4 exhibiting the same behavior with 8.5. We also are able to reproduce this on Linux.

**Comment by greg-1-anderson** [comment]
The Drush pm-* commands are in maintenance only mode, and there is no active maintainer. A PR to fix this would be appreciated.

**Comment by weitzman** [comment]
Your best bet is to upgrade to latest Drush 9.6 beta.

**Comment by if-kenn** [comment]
@weitzman since we have to support Drupal 7, that is not an option.

**Comment by if-kenn** [comment]
I was not aware that Drush 8 is no longer fully supported. Especially surprised since Drupal 7 will be supported until Nov 2021.

I guess we will have to alter our automation to use a specific version of Drush based on the version of Drupal. I was hoping to avoid that due to the complication it creates.

**Comment by greg-1-anderson** [comment]
@if-kenn Maintaining the Drush 8 codebase is much more difficult than the Drush 9 codebase. We are still making a best-effort attempt to keep Drush 8 compatible with each new minor release of Drupal 8, but at some point that will not be possible. In the meantime, we will fix bugs and consider low-impact pull requests to enhance Drush 8. We will not be making any serious effort to add new features to this branch, though. This is really not very different than what is happening with Drupal 7.

Regarding supporting different versions of Drush based on your Drupal version, the easiest way to do this is to use Composer to manage all of your Drupal 8 sites, and add Drush 9 as a site-local (`composer require`) install inside the Drupal site. This is the recommended way to install Drush 9. Then, if you call Drush 8 as your global Drush, it will automatically redispatch to the site-local Drush if it exists.

**Comment by if-kenn** [comment]
@weitzman I am trying to understand from the PRs if I would have to upgrade to 9.6 beta or if I could actually upgrade to 9.6 rc?

**Comment by weitzman** [comment]
Use the latest rc. currently rc3

**Comment by if-kenn** [comment]
Great, thanks

**Comment by if-kenn** [comment]
So I am trying to use 9.6 rc3 but it appears that somehow suggested versions have been dropped, don't know if that is intentional or not. https://github.com/drush-ops/drush/issues/3925
