### ISSUE TITLE
fix SqlPgsql.php for Windows

### ISSUE THREAD

**Issue by gdev2018** [drush-ops/drush#3921]
**Describe the bug**
SqlPgsql.php not tuned well for Windows

**To Reproduce**
try: drush sql-dump --skip-tables-list=drupal_cache_* > dump.sql --debug

**Expected behavior**
created file dump.sql

**Actual behavior**
Error: "PGPASSFILE" is not an internal or external command executed by a program or batch file.

**Workaround**
-

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.5.2
| Drupal version? | 8.6.8
| PHP version     | 7.1
| OS?             | Windows

**Comment by weitzman** [comment]
Should be fixed in drush 9.6.
