### ISSUE TITLE
Drush should warn if --root is used but composer.json is not found

### ISSUE THREAD

**Issue by Kingdutch** [drush-ops/drush#3922]
**Describe the bug**
When the composer.json file is not findable by Drush then Drush doesn't do anything and is of absolutely no help to the user in diagnosing the problem.

**To Reproduce**
It took me about an hour of searching and trying different things to figure this out. The scenario can occur when using a docker based workflow and only mapping the `html` and `vendor` directories into the container but not including the `composer.json`/`composer.lock` files because dependency management happens outside of the container.

I installed Drush as a local dependency with the Drush launcher. This was reproducible by using the Drush launcher. Trying to run Drush with a path directly from the vendor directory as well as specifying the `-root` option with an absolute path.

**Expected behavior**
When I run `drush` in this way or run `drush -vvv --root=/var/www/html` inside a container without `composer.json` file and where `/var/www/html` is a valid Drupal path with a working install then I expect Drush to use that path.

At the bare minimum I expect the debug logs to acknowledge the fact that I am passing the `--root` option. Ideally in this case it provides feedback that I have passed the `--root` option but it doesn't detect a Drupal installation because it's missing (or can't access) certain files that it uses to detect the installation. 

**Actual behavior**
When using the Drush launcher:
```
The Drush launcher could not find a Drupal site to operate on. Please do *one* of the following:
  - Navigate to any where within your Drupal project and try again.
  - Add --root=/path/to/drupal so Drush knows where your site is located.
```

Or when using the full paths everywhere and enabling maximum debug output:
```
root@ea863bbfa6d3:/var/www/html# /var/www/vendor/bin/drush -vvv --root=/var/www/html status
 [preflight] Config paths: /var/www/vendor/drush/drush/drush.yml
 [preflight] Alias paths: 
 [preflight] Commandfile search paths: /var/www/vendor/drush/drush/src
 [bootstrap] Starting bootstrap to max [7.67 sec, 3.31 MB]
 [debug] Trying to bootstrap as far as we can [7.67 sec, 3.32 MB]
 PHP binary    : /usr/local/bin/php                    
 PHP config    :                                       
 PHP OS        : Linux                                 
 Drush script  : /var/www/vendor/bin/drush             
 Drush version : 9.5.2                                 
 Drush temp    : /tmp                                  
 Drush configs : /var/www/vendor/drush/drush/drush.yml 
```

**Workaround**
No, you're basically left on your own until you try to add the `composer.json` file because "Surely, no other tool than composer should depend on that file but it doesn't hurt to try"

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.5.2 
| Drupal version? | 8.6.7
| PHP version     | 7.2.14
| OS?             | A Docker container running Linux (extending the `drupal:8` image) using Docker for Mac

**Comment by weitzman** [comment]
The tool that consults composer.json is https://github.com/webflo/drupal-finder. Drush depends on it. Perhaps suggest an enhancement to the error message.

**Comment by weitzman** [comment]
I looked into this but couldn't find a good place to add a notice. Ideas welcome.

**Comment by scripthead** [comment]
Just installed Drush 10 and still experiencing this issue.

**Comment by weitzman** [comment]
drush 13 no longer uses drupal-finder so this is no longer an issue.
