### ISSUE TITLE
pm:security missing suggested version

### ISSUE THREAD

**Issue by if-kenn** [drush-ops/drush#3925]
**Describe the bug**
Trying to use Drush to check Drupal Composer packages for security updates does not provide the suggested version, only current version.

**To Reproduce**
`drush pm:security`

**Expected behavior**
Return "Name", "Installed Version" & "Suggested Version"

**Actual behavior**
Return "Name" & "Installed Version", but no "Suggested Version"

**Workaround**
None that I know

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.0-rc3
| Drupal version? | 8.5.x & 8.6.x
| PHP version     | 7.2
| OS?             | Mac

**Additional information**
I have checked this on quite a few 8.5.x & 8.6.x sites.

**Comment by weitzman** [comment]
Alas drush can’t easily provide it. please use composer show.

**Comment by if-kenn** [comment]
@weitzman so to be clear, Drush has dropped this functionality between version 9.5 and 9.6?

**Comment by weitzman** [comment]
Correct.

**Comment by if-kenn** [comment]
Have to admit this is pretty disappointing since it was a feature we relied on from Drush for many years for automation, is broken in Drush 9.5 and won't be implemented in 9.6. It seems an odd thing to drop with how much more frequently Drupal is pushing security.

Also it should be noted, unless I am missing some arcane command, that your suggestion to use Composer is not going to help with informing that Drupal 8.5.10 is the most secure version on the 8.5 branch.

I guess we will have to ditch Drush altogether and home brew our own solution.

**Comment by greg-1-anderson** [comment]
If you home brew your own solution, and it involves a reliable method for determining the most recent secure version of a module (or theme or core) on a branch, you could consider submitting a pull request.

If you're doing some coding and `pm:security` isn't to your liking, you might also want to consider trying `drupalorg.phar project:releases drupal` from https://github.com/mglaman/drupalorg-cli. It does not have the features you are looking for at the moment, but it is querying the drupalorg api, so that might be something to look into.

**Comment by gitressa** [comment]
Drupal version: 8.7.4
Drush version: 9.7.1

In a previous comment in this issue it is stated that `pm:security` will be removed from Drush 9.6, yet under [Releases](https://github.com/drush-ops/drush/releases) -> 9.6.0 it says

> Fix significant bug where pm:security misses required security updates. (#3766)

To test `pm:security` I just tried adding the Drupal 8 module alinks version 1.0, which has a security update available, and it looks like `pm:security` works perfectly in the latest version of Drupal core, and the version of Drush which comes with it:
```
$ drush pm:security
 [warning] One or more of your dependencies has an outstanding security update.
 [notice] Try running: composer require drupal/alinks --update-with-dependencies
 [notice] If that fails due to a conflict then you must update one or more root dependencies.
+---------------+-------------------+
| Name          | Installed Version |
+---------------+-------------------+
| drupal/alinks | 1.0.0             |
+---------------+-------------------+
```
Also, I looked for refresh commands, but it looks like they have all been deprecated: https://drushcommands.com/drush-9x/pm/
Is `pm:security` supposed to not need a refresh, but do it as part of checking for security updates? Also, will `pm:security` be available in the foreseeable future?

**Comment by gitressa** [comment]
Just FYI, if anyone else finds this issue, looking for info on `pm:security` and Drush 9:
> Pm:security was rewritten for drush9 and is here forever. It does not require a refresh nor does it even require a working Drupal site. Just needs a composer.lock.

From #4139.
