### ISSUE TITLE
"Fatal error: Uncaught Error: Call to a member function findUri() on null" on Cygwin + manual PHP installation

### ISSUE THREAD

**Issue by xandeadx** [drush-ops/drush#3927]
**Describe the bug**
I use Cygwin + Manual PHP installation (not using cygwin package manager).
All drush commands give an fatal error in cygwin console **"Fatal error: Uncaught Error: Call to a member function findUri() on null"**. This is because `$_SERVER['PWD']` contains path in cygwin format `/cygdrive/...` and PHP function `is_dir()` always return `FALSE` for such directories. `$_SERVER['PWD']` gets into `Environment::originalCwd` and used in many places. Also `is_dir()` using on `DrupalFinder::isValidRoot()` and this function write wrong path in `DrupalFinder::drupalRoot`.

**To Reproduce**
1. Install Cygwin and manual install PHP. Add cygwin and php binaries in PATH variable.
2. Open Cygwin bash console and execute `vendor/bin/drush status`

**Expected behavior**
Show drush status

**Actual behavior**
Fatal error "Fatal error: Uncaught Error: Call to a member function findUri() on null in vendor\drush\drush\src\Boot\BootstrapManager.php on line 132"

**Workaround**
Use cmd.exe without cygwin bash or add param `--root=$(cygpath -aw .)` in command

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.x-dev
| Drupal version? | 8.x
| PHP version     | 7.2
| OS?             | Windows

**Comment by xandeadx** [comment]
With fatal error also appear warnings:

> Warning: include(...\vendor\drush\drush\sut/../vendor/autoload.php): failed to open stream: No such file or directory in ...\vendor\drush\drush\sut\autoload.php on line 15

> Warning: include(): Failed opening '...\vendor\drush\drush\sut/../vendor/autoload.php' for inclusion in ...\vendor\drush\drush\sut\autoload.php on line 15

**Comment by Chi-teck** [comment]
Does it work for you if force Drush to use `getcwd()` instead of `$_SERVER['PWD']`?
https://github.com/drush-ops/drush/blob/9.5.2/drush.php#L44

**Comment by xandeadx** [comment]
@Chi-teck yeah, its work. `getcwd()` return correctly path in windows format `C:\...`

**Comment by greg-1-anderson** [comment]
Maybe:
```
cwd = is_dir($_SERVER['PWD']) ? $_SERVER['PWD'] : getcwd();
```

**Comment by Chi-teck** [comment]
@xandeadx Can you test if #3929 works on Cygwin?

**Comment by xandeadx** [comment]
@Chi-teck It's work, but maybe better use `is_dir(_drush_convert_path(...))`.
