### ISSUE TITLE
Print a backtrace in php errors/exceptions

### ISSUE THREAD

**Issue by donquixote** [drush-ops/drush#393]
From https://drupal.org/node/1804600 and http://drupal.stackexchange.com/questions/45737/how-to-get-backtrace-information-for-php-errors-in-drush

Whenever there is an error or an exception in drush, I want to see a backtrace. At least for the first error/exception that occurs.

Currently none of that is happening.

**Comment by joachim-n** [comment]
What part of the code is responsible for turning an exception into the big red box? It seems to me that that's where we should start poking around.

**Comment by weitzman** [comment]
Some effort here in #4649. Prob coming with next major version of Drush.

**Comment by joachim-n** [comment]
Simple fix in #5978.

**Comment by weitzman** [comment]
This has been available for a few years with the `-vvv` option. No PR needed.

**Comment by joachim-n** [comment]
The -vvv option gives me a LOT of noisy debug stuff about Drush that isn't relevant. I just want to see backtrace when something I am working on crashes.

**Comment by rgpublic** [comment]
Totally agree to joachim-n (+1). I'm also missing an option to just get a backtrace in case of an error. I don't need or want that other stuff. I still think it's a reasonable feature request. It'd be especially useful if you have lots of different shell scripts with their own individual arguments that run drush as a subprocess which might fail ocasionally. You'd have to passthru the -vvv everywhere to diagnose any errors.

**Comment by weitzman** [comment]
The decision to couple the verbose log with the backtrce comes from Console. Feel free to submit an issue there.

I'll also note that you can get just the backtrace by enabling Xdebug develop mode.

**Comment by joachim-n** [comment]
Having thought a bit more, Drush should respect the $config['system.logging']['error_level'] value.
