### ISSUE TITLE
Module-independent Drush commands cannot use dependency injections

### ISSUE THREAD

**Issue by fago** [drush-ops/drush#3938]
**Describe the bug**
A drush.services.yml defined in a drush extension, shipped as type:drupal-drush package, is not picked up.

**To Reproduce**
Create a drush extension, define drush.services.yml, it's not picked up.

**Expected behavior**
drush.services.yml to be loaded.

**Actual behavior**
It's ignored, see https://github.com/drush-ops/drush/blob/42acb4e6030199ea481ecc4b4ea48b6e242632fa/src/Drupal/DrupalKernelTrait.php#L107

**Workaround**
Is there another way to do the desired action?
I don't see any :( - well besides creating a module. But that's not always desirable.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.x

**Additional information**
This would be quite useful for drush commands that should be available indepenent of a module to be enabled or not.

**Comment by weitzman** [comment]
This is by design, unfortunately. If you to inject drupal services you must be packaged with a module.

**Comment by fago** [comment]
Why is that? The code I linked seems to suggest adding it already.

Use-case is deployment related commands, where having to enable a module first would be unfortunate.

Example:
https://github.com/drunomics/drush-phapp-env-mode

Without that, "drupal-drush" extensions seems to be rather crippled?

**Comment by greg-1-anderson** [comment]
There are a limited number of things that you can do without being a module. I don't remember off the top of my head whether service injection is something that is possible to do without being part of a module. You can get a reference to the container, so even in the worst case you can register services and do dependency injection manually.

My suggestion is to add a `@hook init *` to your Drush commandfile, and do what you wish to do there. You may use Drupal's static classes to get a reference to the container, etc.; if you come up with some general-purpose patterns, we could consider adding capabilities to Drush.

**Comment by Sweetchuck** [comment]
I also miss this feature.

**Comment by weitzman** [comment]
This is not likely to change.
