### ISSUE TITLE
Redispatch to site-local loop

### ISSUE THREAD

**Issue by cilefen** [drush-ops/drush#3939]
**Describe the bug**
When calling Drush either globally or specifically the site-local instance, Drush enters a loop of "Redispatch to site-local Drush".

```
/var/www/html/iasedu2.test/docroot$ drush9 @sites status --debug
 [preflight] Redispatch to site-local Drush: /var/www/html/iasedu2.test/docroot/vendor/drush/drush/drush.
 [preflight] Redispatch to site-local Drush: /var/www/html/iasedu2.test/docroot/vendor/drush/drush/drush.
 [preflight] Redispatch to site-local Drush: /var/www/html/iasedu2.test/docroot/vendor/drush/drush/drush.
...
```

```
/var/www/html/iasedu2.test/docroot$ vendor/bin/drush --version
Drush Commandline Tool 9.5.2
/var/www/html/iasedu2.test/docroot$ vendor/bin/drush @sites status --debug
 [preflight] Redispatch to site-local Drush: /var/www/html/iasedu2.test/docroot/vendor/drush/drush/drush.
 [preflight] Redispatch to site-local Drush: /var/www/html/iasedu2.test/docroot/vendor/drush/drush/drush.
 [preflight] Redispatch to site-local Drush: /var/www/html/iasedu2.test/docroot/vendor/drush/drush/drush.
...
```

**To Reproduce**
As above. FWIW this is Acquia Cloud.

**Expected behavior**
To not to.

**Actual behavior**
An endless loop.

**Workaround**
If Drush is not installed into vendor, the problem does not occur.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.5.2
| Drupal version? | 8.6.9
| PHP version     | 7.2.14
| OS?             | Linux

**Additional information**
~

**Comment by greg-1-anderson** [comment]
There should be a test in there that subverts the redispatch if Drush is already the site-local Drush for the target site. In your case, that is already the case, so the existing test must be failing for some reason. Are any of the directories in the presented path a symlink?

More debugging will be necessary to determine why the test is wrong.

**Comment by cilefen** [comment]
The global Drushes are symlinks.

```
$ which drush9
/usr/local/bin/drush9
$ file /usr/local/bin/drush9
/usr/local/bin/drush9: symbolic link to /usr/local/drush9/drush
```

The working directory used by Acquia Cloud hooks is also symlinked:

$ file /var/www/html/iasedu2.test/docroot
/var/www/html/iasedu2.test/docroot: setgid, directory
$ file /var/www/html/iasedu2.test
/var/www/html/iasedu2.test: symbolic link to /var/www/html/iasedu2stg

**Comment by greg-1-anderson** [comment]
I'm guessing that the symlinks are confusing the test to detect the site-local Drush location; Drush thinks that the path to the Drupal root is different, and therefore it redispatches.

Maybe a well-placed `realpath` or two would fix this. PRs welcome.

**Comment by weitzman** [comment]
I’ve removed realpath() calls in the past, especially trying to get windows to work as well as Linux. So not sure that’s the best solution. I’m not familiar with the problem here, I’m just sharing a bit.

**Comment by greg-1-anderson** [comment]
@cilefen I just noticed that you are using `@sites`, which is not supported in Drush 9. Does Drush work correctly for you in absence of a site alias? Does a simple `drush9 status --debug` work, or does it loop in a similar manner?

**Comment by cilefen** [comment]
@greg-1-anderson Yup, that was it.
