### ISSUE TITLE
Drush cannot bootstrap Drupal when started outside of Drupal root

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#3940]
This happens on Drush ^9.6-beta4.
When I run Drush outside Drupal root the following error shows up.
> PHP Fatal error:  Uncaught Error: Call to a member function findUri() on null in /var/www/d8/docroot/vendor/drush/drush/src/Boot/BootstrapManager.php:132

I think it caused by [this change](https://github.com/drush-ops/drush/commit/f7fd4b7f41ce868e8c476eed4b729e1d728c8886#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R114).

Drupal Finder reads `installer-paths` section when searching for Drupal root.

**Comment by weitzman** [comment]
How are you calling drush? You may need to pass —root or a site alias.

**Comment by greg-1-anderson** [comment]
I have sometimes seen that error, but I do not see it every time I run Drush outside of a Drupal site.

**Comment by Chi-teck** [comment]
I am calling Drush with custom Bash function which finds absolute path to Drush binary. While it works with `--root` I think it would be helpful to allow Drush figure Drupal root without providing that option (as we do in Drush 9.5).

https://github.com/drush-ops/drush-launcher#alternatives
> Drush9 is smart enough to find the PROJECT_ROOT and DRUPAL_ROOT when it is run from the bin directory.

**Comment by greg-1-anderson** [comment]
Yeah, with that setup I get the same result, plus a warning:
```
Warning: include(): Failed opening '.../Sites/crebl-org/vendor/drush/drush/sut/../vendor/autoload.php' for inclusion (include_path='...') in .../Sites/crebl-org/vendor/drush/drush/sut/autoload.php on line 15
PHP Fatal error:  Uncaught Error: Call to a member function findUri() on null in /Users/ganderson/local/drupal/Sites/crebl-org/vendor/drush/drush/src/Boot/BootstrapManager.php:132
```
This is a regression.

**Comment by greg-1-anderson** [comment]
OK, found it.  I'll have a PR to fix this shortly.

**Comment by greg-1-anderson** [comment]
#3942

**Comment by weitzman** [comment]
Dupe of #3741. That issue meanders a bit but I do think it covered this minor regression. We can keep discussing here.

**Comment by greg-1-anderson** [comment]
Fixed and merged.
