### ISSUE TITLE
Support request: how-come our cache folder is at /tmp/drush-root/cache?

### ISSUE THREAD

**Issue by hkirsman** [drush-ops/drush#3945]
**Describe the bug**
Our system was failing to download latest version of Link module that had security update yesterday. We where deleting .drush/cache in home folders, doing "drush cc drus"h but it didn't help.

**To Reproduce**
Just ran the build and it failed all the time.

**Expected behavior**
I expected the Link module not to fail to downloaded.

**Actual behavior**
Activity execution failed, because: Beginning to build /var/app/ondeck/conf/site.make.                          [ok]
  Could not locate link version 7.x-1.6.                                   [error]
  Drush Make failed to download all projects. See the log above for the    [error]

**Workaround**
rm -rf /tmp/drush-root/cache

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.1.19-dev
| Drupal version? | 7.x/
| PHP version     | 5.6
| OS?             | Linux

**Additional information**
It's being run on AWS beanstalk. When testing under normal and root user it seemed to work but when starting from Beanstalk then it failed.

**Comment by weitzman** [comment]
I guess its there because $HOME isnt defined.

**Comment by hkirsman** [comment]
Will check.

**Comment by hkirsman** [comment]
That was the issue. tx!
