### ISSUE TITLE
 --cache-duration-releasexml also to drush make

### ISSUE THREAD

**Issue by hkirsman** [drush-ops/drush#3946]
**Is your feature request related to a problem? Please describe.**
The problem has risen due to Drupal security updates where a module is released but not yet propagated to the list where it says it exists. When you 'drush make' the project too soon, drush will cache that particular version of missing module and will save that information locally. Now deleting all the caches manually or using 'drush cc drush' works but that deletes the downloaded files also. Without clearing the caches in all instances all next deploys will fail.

**Describe the solution you'd like**
There's a option currently for 'drush dl':
--cache-duration-releasexml             Expire duration (in seconds) for release XML. Defaults to 86400 (24 hours).
That would be nice to have also for 'drush make'. I understand now that if I would do 'drush make --cache-duration-releasexml=0...' I would get always the latest release info from d.org and also keep the caches of already downloaded files.

**Describe alternatives you've considered**
Alternative would be always deleting the caches but that would make builds slower and would give extra load to d.org.

**Comment by weitzman** [comment]
make is no longer maintained.
