### ISSUE TITLE
Improve readability of command line documentation

### ISSUE THREAD

**Issue by gitressa** [drush-ops/drush#3958]
If you type `drush` to list all commands, the result is not optimal, with some of the text floating to the right. It would be great with a more scannable result. It looks like the result is optimized for a terminal width of 130 columns ...

**Comment by weitzman** [comment]
Drush tries to determine the width of your terminal. You can help by assuring that the COLUMNS env variable is defined by your shell.

**Comment by gitressa** [comment]
My challenge is that I use Lando, and it seems pretty difficult to change the default `COLUMNS=256` ...
I tried inserting this in `drush.yml`, but it doesn't seem to take effect, where the `uri` part works fine:
```
options:
  uri: 'http://mysite.lndo.site'
  env-vars:
    DRUSH_COLUMNS: 80
```
Is there another way to set the `COLUMNS` value in Drush?

**Comment by gitressa** [comment]
With the help of @pirog I managed to get this working in Lando, either with a service level override or a user space lando global config that overrides the appEnv key: https://github.com/lando/lando/issues/1847#issuecomment-602185785.
