### ISSUE TITLE
sut/drush/sites/synctest.site.yml is added to Git with environment related content

### ISSUE THREAD

**Issue by Sweetchuck** [drush-ops/drush#3960]
**Environment related file content under VCS**
File `sut/drush/sites/synctest.site.yml` contains environment related content, and its content re-generated automatically.
With a careless `git add .` it can be updated with database credentials.
I think this file should be added to _.gitignore_

**To Reproduce**
Run the tests `vendor/bin/phpunit --configure tests`

**Expected behavior**
Exclude that file from Git.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.x
| Drupal version? | 8.6.x
| PHP version     | 7.2.x
| OS?             | Linux

**Comment by greg-1-anderson** [comment]
This file is simply missing from .gitignore. It should be ignored.

**Comment by weitzman** [comment]
Seems like we should remove this exclusion https://github.com/drush-ops/drush/blame/master/.gitignore#L13

**Comment by greg-1-anderson** [comment]
There are some things that we want committed in the `sut/drush` directory. Maybe the exclusion just needs to be more targeted, or we could just re-add `sut/drush/sites/synctest.site.yml`
