### ISSUE TITLE
Cannot override URI option when using site alias

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#3964]
`drush st --field=uri --uri=http://example.com`
Prints 'http://example.com'.

`drush @local st --field=uri --uri=http://example.com`
Prints URI defined for "local" site alias.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version  | 9.x
| Drupal version | 8.x
| PHP version     | 7.2
| OS             | Linux

**Comment by greg-1-anderson** [comment]
Fixed in #3966
