### ISSUE TITLE
Drush fails with limited to no direction when composer.json is invalid

### ISSUE THREAD

**Issue by amcgowanca** [drush-ops/drush#3969]
**Describe the bug**

When a project's `composer.json` is invalid (in my case, I started to modify but left an erroneous comma), Drush fails silently with little to no indication that `composer.json` is invalid.

**To Reproduce**

1. Invalid a project's `composer.json`
2. Attempt to run a `drush` command.
3. Observe that `drush` cannot bootstrap.

**Expected behavior**

I'd expect that Drush would either a) provide an error message indicating that `composer.json` is invalid _or_ continue with the command execution.

**Actual behavior**

Received an error message, `Bootstrap failed. Run your command with -vvv for more information`.

```$ vendor/bin/drush cr -vvv
 [preflight] Config paths: /var/www/html/vendor/drush/drush/drush.yml
 [preflight] Alias paths: /var/www/html/vendor/drush/drush/drush/sites
 [preflight] Commandfile search paths: /var/www/html/vendor/drush/drush/src
 [bootstrap] Starting bootstrap to site [0.41 sec, 3.39 MB]

In BootstrapHook.php line 32:
                                                                      
  [Exception]                                                         
  Bootstrap failed. Run your command with -vvv for more information.  


Exception trace:
 () at /var/www/html/vendor/drush/drush/src/Boot/BootstrapHook.php:32
 Drush\Boot\BootstrapHook->initialize() at /var/www/html/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:34
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook() at /var/www/html/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:27
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize() at /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php:117
 Consolidation\AnnotatedCommand\CommandProcessor->initializeHook() at /var/www/html/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:391
 Consolidation\AnnotatedCommand\AnnotatedCommand->initialize() at /var/www/html/vendor/symfony/console/Command/Command.php:221
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php:112
 Drush\Runtime\Runtime->doRun() at /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php:41
 Drush\Runtime\Runtime->run() at /var/www/html/vendor/drush/drush/drush.php:66
 require() at /var/www/html/vendor/drush/drush/drush:8                                                                      
```

**Workaround**

_None that I am aware of outside of double checking for my own stupidity._

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.0-beta3
| Drupal version? | 8.x
| PHP version     | 7.2

**Comment by amcgowanca** [comment]
This could be a duplicative of:

* https://github.com/drush-ops/drush/issues/3922
* https://github.com/drush-ops/drush/issues/3955

**Comment by weitzman** [comment]
@webflo - we have gotten 3 reports ablut this same behavior recently. do think this should be more grancefully handled, and if so in drush or [Drupal Finder](https://github.com/webflo/drupal-finder)?

**Comment by weitzman** [comment]
We decided on throwing an exception from Drupal-Finder. Patches welcome.

**Comment by weitzman** [comment]
PR at https://github.com/webflo/drupal-finder/pull/42

**Comment by weitzman** [comment]
The PR has been merged and will be in next release of Drupal-Finder
