### ISSUE TITLE
Memory issues on the queue:run command.

### ISSUE THREAD

**Issue by ndobromirov** [drush-ops/drush#3972]
**Describe the bug**
As I was testing on a multi-site installation this is just selecting me the site to work with.

`./vendor.bin/drush @alias queue:run QUEUE_NAME --time-limit=10 ` with limit hangs for as long the limit is set.
@alias points to a locally installed site in a multi-site context.
Works for ~10 seconds, reports the success message with the processed count and hangs for ~10 seconds more before returning back to prompt.

**To Reproduce**
1. Have a drupal queue with MANY items in there.
2. Be sure that it can not process all of them during the time-limited run.
3. Run the command:
```
time ./vendor/bin/drush @ALIAS queue:run QUEUE_NAME --time-limit=10 -vv

Output:
... 
 [success] Processed X items from the QUEUE_NAME queue in 9.46 sec. [9.91 sec, 58.37 MB]

real	0m19.380s
user	0m13.256s
sys	0m0.620s
```

**Expected behavior**
The real time needed to finish the process is expected to be around the one that was passed as an option.
What I am seeing as time and RAM on the debugging output should be correct. 
Prompt should be returned immediately.

**Actual behavior**
The console output hangs a long time after the limit parameter. Some times even double.
The system IS doing something during that hang time, but even with -VVV option, nothing can be seen.
During that time it is abusing PHP RAM memory as well.

For big enough time limits we are getting PHP memory limit errors...
```
time ./vendor/bin/drush @ALIAS queue:run QUEUE_NAME --time-limit=120 -vv
 [success] Processed 3491 items from the QUEUE_NAME queue in 119.39 sec. [120.3 sec, 75.86 MB]
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/FOLDER/docroot/modules/contrib/memcache/src/Driver/MemcachedDriver.php on line 72

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/FOLDER/docroot/modules/contrib/memcache/src/Driver/MemcachedDriver.php on line 72

real	2m52.901s
user	1m51.696s
sys	0m5.156s
```

**Workaround**
Have the time limit really low and execute the operation multiple times to process the whole piece.

The goal however was to have a single operation without the limit and process it.
The main issue that triggered me to come here was some kind of memory that is hard to track in Drupal
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.5.2
| Drupal version? | 8.6.10
| PHP version     | PHP 7.2.12-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Nov 12 2018 09:55:12)
| OS?             | Ubuntu 16.04 (under VM - DrupalVM)

**Additional information**
Not additional information, but a questions that pop in my head looking in this...
1. What is happening after the queue operation has finished processing?
2. Why Drush is not terminating asap?
3. What part of Drupal might be running in the background to cause this?

Could this be related: https://www.drupal.org/node/3037985

**Comment by ndobromirov** [comment]
After further digging into this, it turned out to be some kind of a shutdown function that get's progressively slower the longer the Drush operation runs...

Once I've added this on the top of `drush.php`
```php

**Comment by weitzman** [comment]
I suggest using a debugger to track this.

**Comment by ndobromirov** [comment]
After debugging this :crab: properly...

**Here is what was happening:**
1. Queue is processing things as expected - correct.
2. Queue processing finishes (based on the predefined time limit) - correct.
3. Any module can add an arbitrary shut-down function to be executed at the end of the request / PHP process.
4. Search API maintains a list of tings that have changed in the request and indexes them in bulk, assuming they are a small amount. Imagine saving a node form...
5. Drush emulates Drupal 8 request :(. So all request end handlers on all contrib modules are being executed. Including the Search API one, that starts to index all of the just re-saved items at once
6. Search API triggers the indexing process and from there the out of memory error.

I think this is not a direct bug in Drush per say, but emulating the request / response model within Drupal just to trigger the terminate handlers of the Kernel should be a well documented feature.

In the exact same scenario Drush can randomly trigger cron executions on end of any command (based on chance and D8 config). Even though there is a dedicated command to run the cron...

If all of this is OK behavior then this is not a bug on Drush but a Search API one and I will post an issue there shortly either way.

**Comment by weitzman** [comment]
In general, this is by design. Folks complained when we didn't fire those request end handlers in the past. having said that, I'm open to discussion about it.

**Comment by ndobromirov** [comment]
I consider this one OK as in the end it was not Drush issue but a **Search API** one (or the lack of my understanding how it worked)...

[Here is the issue](https://www.drupal.org/project/search_api/issues/1137734) in there, running for the last 8 or so years...
