### ISSUE TITLE
Error with sql:cli after updating to 9.6.0-rc4

### ISSUE THREAD

**Issue by claudiu-cristea** [drush-ops/drush#3983]
**Describe the bug**
After updating Drush from 9.5.2 to 9.6.0-rc4, we're getting this error while running `sql:cli` on our CI environment:

```
In Process.php line 1042:
                                                   
  TTY mode requires /dev/tty to be read/writable.  
```

 See this screenshot:
<img width="956" alt="sqlcli" src="https://user-images.githubusercontent.com/473868/54126447-3d4af980-4410-11e9-9387-44b7d98bbefe.png">

I cannot reproduce the bug locally.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.0-rc4, master
| Drupal version? | 8.6.10
| PHP version     | 7.1
| OS?             | Linux

**Additional information**

N/A

**Comment by claudiu-cristea** [comment]
It could be something related to this change https://github.com/drush-ops/drush/commit/5640cf94d10add8b828ed5cc908cd37c5754e817#diff-7f763b53e070de98dac7a82fcf3b0392

**Comment by greg-1-anderson** [comment]
@claudiu-cristea Try running in `--no-interaction` mode. That should avoid the tty.

**Comment by claudiu-cristea** [comment]
@greg-1-anderson, indeed, that fixes the issue. Thank you.
