### ISSUE TITLE
--db-su no longer works in drush 9.6

### ISSUE THREAD

**Issue by singularo** [drush-ops/drush#3997]
It appears that the --db-su option no longer works with drush 9.6, downgrading back to 9.5 makes this command line work:

drush -y sql:create --db-su=root --db-su-pw=thepass --db-url="mysql://xxx:yyy@db/zzz"

But it fails with 9.6 with:

```
In SqlCommands.php line 101:
Unable to create database. Rerun with --debug to see any error message.
```

I use this command as part of a script to load an sql database as part of a migration, and with the 9.6 upgrade, the command started to fail.

Debugging showed that in the https://github.com/drush-ops/drush/blob/ee6ecc5f7f3e6743c3939e6042098b191e2c73fb/src/Sql/SqlBase.php#L539 function
```
$db_superuser = $this->getOption('db-su');
```
is returning null, and that the db-su is actually been moved from the options array into an element within the array with the value within.
```
sql.db-su=root
```

I worked around the issue by downgrading to 9.5.*

Drush 9.5 / 9.6
Drupal 8.7
PHP 7.2.8
OS Ubuntu Linux

**Comment by greg-1-anderson** [comment]
Looks like I did an incomplete conversion in 247216a100. The goal appears to have been to allow `db-su` to be overridden by a site alias.  `db-su-pw` should have been done, but was not.  The code that actually inspects `db-su` was not adjusted.

**Comment by greg-1-anderson** [comment]
Actually, although the commit I mention above did break db-su, Drush later changed to using Drupal APIs to bootstrap and do other sql options, including creating databases. This new code does not support `db-su`. We'd have to make another database record in order to do that. I think that's feasible, but I haven't tried.

**Comment by greg-1-anderson** [comment]
Please try #3998 and see if it fixes things for you.

**Comment by singularo** [comment]
That works in that it now creates the database, but the code in `createdbSql` doesn't get executed, the `$db_superuser = $this->getConfig()->get('sql.db-su');` returns NULL, so the user specified in the --db-url doesn't get access granted.

**Comment by chrisfromredfin** [comment]
Discovered the same--created but no privileges granted--on 9.7.1.
