### ISSUE TITLE
Update Drupal core without moving core files out of the way

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#4]
See original issue at https://drupal.org/node/759906

**Comment by AdamPS** [comment]
@weitzman Recommend that you close this as "won't fix".  As I understand it, PR for drush pm are no longer of interest because it is deprecated in favour of composer.

We should make it clear to readers that creating a PR here is a waste of time.

**Comment by greg-1-anderson** [comment]
The `pm-*` commands are maintenance support fixes only; closing.
