### ISSUE TITLE
Database Credentials are saved multiple times in tmp folder by default

### ISSUE THREAD

**Issue by jmonte-sph** [drush-ops/drush#4010]
**Describe the bug**
drush/src/Sql/SqlMysql.php creds() function should not save the username/password in the temp file.

**To Reproduce**
Call any drush sql function and it will create create a temp_file with the username/password of the database by default.

**Expected behavior**
It should not save the username/password of the database by default.

**Actual behavior**
It is creating a temp_file with the username/password of the database

**Workaround**
Set the call to creds(false) or change the condition in https://github.com/drush-ops/drush/blob/master/src/Sql/SqlMysql.php line 20 to 
`if(!$hide_password) `

$hide_password should not save the credentials when set to true.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version  | 9.x/8.x master
| Drupal version | 8.x
| PHP version     | 5.6/7.1
| OS             | Mac/Linux/Windows

**Additional information**
This poses a security risk as username/password of the database is save multiple times in the server by default.

**Comment by greg-1-anderson** [comment]
I think that the real solution here is to ensure that these temporary files are always deleted immediately as soon as Drush is done with them. Setting `$hide_password` to false makes the situation worse, as doing this exposes the password on the process list.

**Comment by greg-1-anderson** [comment]
Oh, the other thing is that some of the Drush sql-* commands are going to be provided in a form that uses the Drupal APIs to access the database. This also would allow us to avoid writing the temporary files. Operations involving sql dump cannot be converted in this way, though, so Drush will need to create temporary credential files for these operations still.

**Comment by weitzman** [comment]
Drush already auto-deletes the files at end of request. This approach is by design. See this issue, fixed in 2014 https://www.drupal.org/project/drush/issues/671906.
