### ISSUE TITLE
Execution problem with Drush 9.6.1

### ISSUE THREAD

**Issue by jenbhu** [drush-ops/drush#4018]
Hello,
Since i've updated to 9.6.1 on my drupal project. On my remote server executing drush commands which launches a batch process fails . Simple commands like drush status, drush cr works.

Using Drush 9.5.2 works flawlessly.

I normally execute the drush.php file as i don't have bash executions permissions for security purposes as follows:

usr/bin/php vendor/drush/drush/drush.php [DRUSH-COMMAND]

Here is a debug/verbose log
```

[info] Executing: /space/data/releases/20190326135528/vendor/bin/drush batch-process 4216553 --uri=default --root=/space/data/releases/20190326135528 [2.15 sec, 32.39 MB]
> sh: /space/data/releases/20190326135528/vendor/bin/drush: Permission denied
```

With Drush 9.5.2 , there is no problem and the batch launches correctly without any problem

Here is a verbose log of the execution with Drush 9.6.1
```

 [command] Backend invoke: php /space/data/current/vendor/drush/drush/drush.php  --backend=2 --verbose --debug --root=/space/data/releases/20190327054152 --uri=default  batch-process 4216558 2>&1 [9.03 sec, 44.69 MB]
 [info] php /space/data/current/vendor/drush/drush/drush.php  --backend=2 --verbose --debug --root=/space/data/releases/20190327054152 --uri=default  batch-process 4216558 2>&1 [9.03 sec, 44.7 MB]

```

The major differences that i can see between the execution with drush 9.5.2 and 9.6.1 is that the 9.6.1 is missing the execution with the php binary and drush.php is not executed but rather vendor/bin/drush

### System Configuration
| --------------- | ---
| Drush version?  | 9.6.1
| Drupal version? | 8.6.10
| PHP version     | 7.0.33
| OS?             | Linux

Is anyone having the same Issue ?

**Comment by weitzman** [comment]
This change is by design, and I cant think of a workaround for you.

**Comment by jenbhu** [comment]
So the solution would be to have bash execution permission ?

**Comment by weitzman** [comment]
yes. `vendor/bin/drush` should be executable - composer sets that by
default.
