### ISSUE TITLE
Provide "support" for automatic entity updates by adding new command to guess and create hook_update_N() functions

### ISSUE THREAD

**Issue by rachellawson** [drush-ops/drush#4025]
**Is your feature request related to a problem? Please describe.**
In https://www.drupal.org/node/3034742 we have decided to no longer support automatic entity updates, instead recommending the creation of hook_update_N() functions. 
**Describe the solution you'd like**
If we were previously able to determine what entity updates were required, it must also be possible to determine what hook_update_N() functions would be required in a module to support those same updates in a more managed way. We could offer to create those functions in a module chosen by the user for the user to then review and approve.

**Comment by weitzman** [comment]
Sure, but not in core Drush. Please do it i contrib first.

**Comment by weitzman** [comment]
The audience is too small. Only developers, and even then only a small subset (entity update authors).
