### ISSUE TITLE
Broken SQL dump whith --gzip option

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#4026]
This only happens on Drush 9.6+

```
$ drush sql-dump --gzip > /tmp/dump.sql.gz
$ gunzip /tmp/dump.sql.gz
gzip: /tmp/dump.sql.gz has flags 0x5c -- not supported
```

**Comment by greg-1-anderson** [comment]
Run `sql-dump` with `-d` and reproduce by running the commandline that Drush produces manually in the shell. Replace the sql dump with `echo` and see if you get the same results. Fiddle with the options until it works.

It could be that Drush is producing something on stdout that is not part of the gzip. If that is the case, then you won't be able to reproduce on the commandline. Try sql-dump with `--result-file` and see if that works. Also, try passing the output of `drush sql-dump --gzip` to `head` and `tail` and see if there is readable text in either location that should not be there.

**Comment by weitzman** [comment]
Related to #4004

**Comment by Chi-teck** [comment]
`drush sql-dump` without `--gzip` works fine for me even on remote host because I have `tty: false` in _drush.yml_ file.
