### ISSUE TITLE
Shell scripts (she-bang) feature missing or working strangely on Drush 9

### ISSUE THREAD

**Issue by rgpublic** [drush-ops/drush#4031]
On Drush 8 there is this page:
`https://docs.drush.org/en/8.x/shellscripts/`
If I replace 8 with 9 in the url I end up nowhere:
`https://docs.drush.org/en/9.x/shellscripts/`
Usually such a shell scripts started with:
`#!/usr/bin/env drush`
On Drush 9 this results in:
`Command "/usr/local/pw6/pw6-drupal-search-paragraph-new" is not defined.`
If I use this line:
`#!/usr/bin/drush php:script`
I can make this work. And opening PHP tag like `<?php ...` seems to be required, though.
This was not necessary in Drush 8 as far as I can remember (may be wrong).
The worst thing, however, is that the she-bang line seems to be printed to the screen.
I don't know yet: Is this a bug? Should this feature work? I couldnt find any info on this via Google. Weird. Is nobody else missing this?

**Comment by weitzman** [comment]
We decided not to port that feature to Drush9. Was mentioned at https://github.com/drush-ops/drush/issues/2876#issuecomment-332755098. Sorry for the inconvenience.

**Comment by greg-1-anderson** [comment]
This is the first time I've seen someone besides me using this feature in the wild. 😛 Drush commands are really easy to write using annotated commands so probably just switch to that.

If you want to write standalone scripts, see [robo](https://robo.li) and [g1a/starter](https://github.com/g1a/starter).
