### ISSUE TITLE
Queue:run has a different behavior than the processQueues() section of Drupal cron.

### ISSUE THREAD

**Issue by lems3** [drush-ops/drush#4032]
When inspecting the code, I saw a couple of differences between the command `queue:run` and the function `processQueues()` from Drupal Cron.

Here are the sources for each functions : 
https://github.com/drush-ops/drush/blob/master/src/Drupal/Commands/core/QueueCommands.php#L61

https://git.drupalcode.org/project/drupal/blob/8.6.13/core/lib/Drupal/Core/Cron.php

In Queue:run :

- When an item is claimed, there is no time limit set, so the claim will use the default time, which sits at one hour now.
- The Queue:run command doesn't handle a generic \Exception.

The second point may not be relevant. The first one though allows a cron run to release items from the queue when it finishes. Implementing the same approach in the drush queue:run command would give it a similar behavior than a cron run.

An alternative to this would be to handle requeuing items in my QueueWorker::processItem() function, and return a SuspendQueueException when I hit an item I have just processed so the queue stop running. It seems more logic though to expect the queue:run command to processeach items once, and let the devs requeue items if they want it processed again in the same function call.

So default behavior would make queue:run process each item once and free them when it finishes, and dev can implement requeuing for instant reprocess if needed.

For the exact implementation, I would use the difference between time() and $end, so the items are freed as soon as the function calls end. We also can directly use the $time-limit parameter if we really want to stick to the current cron behavior.

**Comment by weitzman** [comment]
Ping @juampynr @neclimdul for input.

**Comment by weitzman** [comment]
Also @davereid @damiankloip

**Comment by lems3** [comment]
https://github.com/drush-ops/drush/pull/4035

I have opened a PR with the "remaining time" approach.

We can also use $time_limit, but it could potentially lock late items in a queue for a while. If you set a 30 minutes timeout and the last item is the only one that had issue, it would be lock for 30 minutes and  could potentially not be processed in the next queue run. But, it's how the cron is currently executed, so we can also  aim to have similar behavior between different commands.

**Comment by juampynr** [comment]
It seems that core's queue processor has evolved a bit since the last time I looked at it. Here is what I found:

![image](https://user-images.githubusercontent.com/108130/56634475-6b079d00-6662-11e9-8ac3-aa4d75ae1523.png)

As for the behavior, I mentioned at https://github.com/drush-ops/drush/pull/4035#issuecomment-486067935 that I don't see major changes there unless I am missing something. That is why I suggested adding tests to prove the changes.

**Comment by lems3** [comment]
+1 for the test. I will dig into it.
The issue is that the "queue:run" command was not claiming an item with a time limit.

**Comment by m4olivei** [comment]
> The Queue:run command doesn't handle a generic \Exception.

I'd like to see this incorporated to parity with what Drupal core does. Handling a generic \Exception gives a queue worker a way to skip an item (until it's expiry passes). This is currently not possible with the `drush queue:run` command.

**Comment by deviantintegral** [comment]
This seems like core should really provide queue processing separate from cron, so future upstream changes don't have to be duplicated in drush. I filed https://www.drupal.org/project/drupal/issues/3068764 with an initial patch to do that.

**Comment by kevin-dutra** [comment]
FWIW, although the `QueueInterface` documentation mentions the default lease time as being one hour, the concrete implementations don't necessarily follow this convention. `DatabaseQueue`, for instance, only has a 30 second default lease time. This can lead to problematic issues where a queue worker that takes longer than 30 seconds can end up getting claimed by a second worker while the first one is still in progress.

Having the ability to alter this when running the Drush command would be a huge help to avoid this situation for queues that you know to be longer running (e.g. video transcoding or something).

**Comment by jhedstrom** [comment]
The catching of all `\Exceptions` would be great (as circled in the above image). Right now if a queue processor throws `SuspendCurrentItemException`, the entire `queue:run` process stops, instead of just ignoring that one item as cron's processing does.
