### ISSUE TITLE
Cannot set proxy settings for drush pm:security

### ISSUE THREAD

**Issue by minorOffense** [drush-ops/drush#4040]
We have a client where there servers can only access the outside world through a proxy. We've setup settings in wget, curl and composer to allow proxying to cover most cases. But the ``drush pm:security`` command uses ``file_get_contents`` and I can't find a way to pass in proxy settings to it.

Am I missing something or is that option not available. And if it's not would be it possible to add that option?

**Comment by weitzman** [comment]
I'm not inclined to go back to the old days where we tried curl and fell back to wget. The only other option is adding PHP dependencies on guzzle or ext:curl. I dont think the win justifies that so I'm disinclined to change code here - sorry.

**Comment by weitzman** [comment]
I will say that you don't need to run this command where your web site is. Maybe checkout your codebase somwhere publically accessible and run it there. You dont need a functional site, since this command does not bootstrap drupal. You just need to run composer install so that autoloading works.

**Comment by minorOffense** [comment]
Yeah the whole network is restricted. Even the local GitLab instance can't talk to the outside without the proxy.

That's ok, I was more curious if there was some hidden option somewhere I didn't know about to maybe proxy this.

I'll find another way to do the check (maybe some kind local redirect to a local copy of that file downloaded some other way).

Thanks for the feedback though. Much appreciated.

**Comment by obriat** [comment]
The **only way** to monitor your prod servers (usually in secured networks) for security alerts is to use `drush sec`. I don't want to setup a clone of each of my prod server just to check these.

drush can read settings.php (or env or command line parameters) for proxy settings and passed them easily to file_get_contents() through stream_context_set_default(), it didn't seems like a big feature ?

This command is almost useless without proxy support...

**Comment by obriat** [comment]
https://github.com/drush-ops/drush/pull/4438

**Comment by weitzman** [comment]
Lets continue in #4438
