### ISSUE TITLE
Twig compile throws routing errors on disabled submodules

### ISSUE THREAD

**Issue by kvij** [drush-ops/drush#4044]
**Describe the bug**
Twig compile generates a Route error and aborts compilation under certain circumstances.
See [https://www.drupal.org/project/devel/issues/302116](https://www.drupal.org/project/devel/issues/302116) for a real world example.

**To Reproduce**
Enable devel module, do _not_ install webprofiler. Run ```drush twig:compile```

**Expected behavior**
Compile twig templates of only installed modules regardless of install status of other modules in the project

**Actual behavior**
Twig compile, compiles templates on disabled submodules when a higher level module (in directory structure) in the same project is enabled. This is due to the inclusion of the project directory in ```$searchpaths``` and a broad search on ```*.html.twig```

**Workaround**
No good workaround

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.5.2 (code in master still displays this behaviour)
| Drupal version? | 8.6.14
| PHP version     | 7.1
| OS?             | Linux

**Comment by weitzman** [comment]
The only solution i can think of is for projects to stop organizing this way. devel.module and devel_generate should be on same level, not nested. not much twig:compile can do here.

**Comment by kvij** [comment]
It is a common pattern in D7 projects, so I imagine we will run into this problem more often. Have you seen any other reason why projects should stop organizing this way?

It can be fixed by fist searching for all ```*.info.yml``` files than add all directories that are _not_ in the `$searchpaths` array to the `exclude()` list of the ```*.html.twig``` search.

**Comment by weitzman** [comment]
There is an open issue somewhere about standards for organizing your module. I can't find it. This pattern is discouraged ... A PR with your suggested workaround would be welcome.

**Comment by greg-1-anderson** [comment]
There's a similar bug for Drush 8 (and lower) extensions on Drupal 7 modules organized this way.

**Comment by kvij** [comment]
@weitzman I agree that a standard for organizing a project is most welcome. I'm working on that PR. Unfortunately the Finder excludes work differently from what I expected so my first attempt failed (the exclude must be relative to the current active search path, making it impossible to reliably exclude everything by Finder when using multiple locations).
Hopefully I have a resource friendly solution by the end of the weekend.
