### ISSUE TITLE
Drupal 8 compatibility matrix for Drush 9

### ISSUE THREAD

**Issue by sudoman** [drush-ops/drush#4046]
**Existing document**

http://docs.drush.org/en/master/install/

**What are you attempting to do**

Hoping to figure out whether Drupal 8 is supported by Drush 9

**In what way is the existing documentation unclear or incomplete**

The top of the page describes how to install Drush 9 with Drupal 8, but the compatibility matrix at the bottom of the page shows no compatibility for Drupal 8.

**What should the documentation say instead?**

Ideally the compatibility matrix would list full or partial support.

**Comment by weitzman** [comment]
That matrix states that drush9 is compatible with Drupal 8.4+

**Comment by sudoman** [comment]
Hmm... they show up in Firefox 66, but not Abrowser 66, which is a debranded version of Firefox with some patches for privacy. I turned off all forms of asset blocking that I know of in Abrowser, but that didn't resolve the issue. I didn't see any warning messages in the JavaScript console.

Some of the check marks do show up for other versions of Drush, but they look different than the ones in Firefox.

**Comment by greg-1-anderson** [comment]
The checkmarks are in unicode; perhaps some browsers do not render unicode correctly?

**Comment by sudoman** [comment]
@greg-1-anderson That's likely the issue. I experimented with setting the fonts to be the same, and I checked the HTML inspector in both browsers. In Firefox's inspector, the Unicode character is rendered as a check box, but in Abrowser, it appears as a blank space. This is likely an issue with the browser, and not with Drush.

Thanks for helping even though the issue wasn't caused by your site. : )

**Comment by greg-1-anderson** [comment]
We could resolve by using images rather than unicode characters, but it's a little easier to maintain this way.
