### ISSUE TITLE
drush en fails on dash in package name

### ISSUE THREAD

**Issue by thwee-alchemist** [drush-ops/drush#4049]
**Describe the bug**
Drush fails when the package name includes a dash.

**To Reproduce**
I have a bunch of packages I'm downloading and installing using composer. They install just fine, but when I try to enable them, I get an error about missing pacakges, but only for those packages with a dash in them. 

**Expected behavior**
I expected drush to handle dashes in package names.

**Actual behavior**
Instead the packages with dashes in their names fail. 

**Workaround**
I don't know one.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.2
| Drupal version? | 8.6.15
| PHP version     | 7.2.17
| OS?             | CentOS 7

**Additional information**

**Comment by weitzman** [comment]
composer downloads packages. drush enables modules. what is the name of the composer package, and the module name?

**Comment by thwee-alchemist** [comment]
Yes, I'm using composer to download and install packages, and drush to enable them. The package is a private package called sds-form, but the enable step fails for everything with a dash in the name.

**Comment by weitzman** [comment]
So the module file is sds-form.module? or sdsform.module?

**Comment by weitzman** [comment]
please post debug output.

**Comment by weitzman** [comment]
dont think modules are allowed dashes in name. they are illegal in function names
