### ISSUE TITLE
drush cex --destination=/valid/destination will prompt for a destination if there is more than one item in the $config_directories array

### ISSUE THREAD

**Issue by alberto56** [drush-ops/drush#4052]
**Describe the bug**

Running drush cex --destination=/some/valid/destination worked in Drush 8, but fails on Drush 9:

    root@a9ba710517f7:/var/www/html# ls -lah /tmp/localconfig/
    total 8.0K
    drwxr-xr-x 2 root root 4.0K Apr 24 16:13 .
    drwxrwxrwt 1 root root 4.0K Apr 24 16:13 ..
    root@a9ba710517f7:/var/www/html# drush cex --destination=/tmp/localconfig

     Choose a destination:
      [0] Cancel
      [1] deploy
      [2] sync
      [3] temp 

**To Reproduce**

drush help cex says: "--destination[=DESTINATION] An arbitrary directory that should receive the exported files. A backup directory is used when no value is provided."

This leads me to believe that, as with Drush 8, I can run:

    drush cex --destination=/tmp/localconfig
         
**Expected behavior**

I expect the configuration to be exported to /tmp/localconfig.

**Actual behavior**

I get a prompt:

    Choose a destination:
     [0] Cancel
     [1] deploy
     [2] sync
     [3] temp

**Workaround**

Use drush 8.x; I cannot find a workaround with drush 9; because this is done in a non-interactive CI environment so I cannot select a destination.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.2 
| Drupal version? | 8.6.15
| PHP version     | 7.2
| OS?             | Linux

**Additional information**

**Comment by greg-1-anderson** [comment]
Didn't try to reproduce, but how about:
```
drush cex sync --destination=/some/valid/destination
```

**Comment by alberto56** [comment]
Hi, thanks for the suggestion, but that does not seem to work for me:

    root@f309e4a6b154:/var/www/html# drush cex --destination=/tmp/localconfig

     Choose a destination:
      [0] Cancel
      [1] deploy
      [2] sync
     > 
    root@f309e4a6b154:/var/www/html# drush cex sync --destination=/tmp/localconfig

     Choose a destination:
      [0] Cancel
      [1] deploy
      [2] sync
     > 
    root@f309e4a6b154:/var/www/html# drush cex --destination=/tmp/localconfig sync

     Choose a destination:
      [0] Cancel
      [1] deploy
      [2] sync

**Comment by alberto56** [comment]
Interesting.

If there is only one key in $config_directories, and that key is 'sync', this works:

    echo '$config_directories = ["sync" => "this-can-be-anything"];' >> sites/default/settings.php 
    drush cex --destination=/tmp/localconfig
     [notice] The active configuration is identical to the configuration in the export directory (/tmp/localconfig).
    /tmp/localconfig
    ls -lah /tmp/localconfig/|grep system.site
    -rw-rw-r-- 1 root root  342 Apr 24 17:13 system.site.yml
  
However if there is more than one key in $config_directories (Acquia settings files, for example, require a "deploy" $config_directories key), this no longer works:

    echo '$config_directories = ["sync" => "whatever", "something-else" => "whatever"];' >> sites/default/settings.php 
    drush cex --destination=/tmp/localconfig
    
     Choose a destination:
      [0] Cancel
      [1] sync
      [2] something-else

**Comment by greg-1-anderson** [comment]
Does it do the right thing if you select `sync` from the menu? Seems like the message is wrong, and Drush is looking for the source for the config export.

A lot of people have only `sync`, which is probably why this bug has gone unnoticed for as long as it has.

**Comment by alberto56** [comment]
> Does it do the right thing if you select sync from the menu?

Yes. Is there any way to force it to choose "1", something 

    rm -rf /tmp/localconfig/*   
    drush cex --destination=/tmp/localconfig

     Choose a destination:
      [0] Cancel
      [1] sync
      [2] something-else
     > 1
     [success] Configuration successfully exported to /tmp/localconfig.
    /tmp/localconfig
    ls -lah /tmp/localconfig/|grep system.site
    -rw-rw-r-- 1 root root  342 Apr 24 17:20 system.site.yml

However:
  
    drush cex --destination=/tmp/localconfig sync

    Choose a destination:
     [0] Cancel
     [1] sync
     [2] something-else

the above does not work; this seems to work however:

    rm -rf /tmp/localconfig/*   
    echo '$config_directories = ["sync" => "whatever", "temp" => "/tmp/localconfig"];' >> sites/default/settings.php 
    drush cex temp 
    ls -lah /tmp/localconfig/|grep system.site
    -rw-rw-r-- 1 root root  342 Apr 24 17:24 system.site.yml

**Comment by alberto56** [comment]
This only seems to affect drush cex, not drush cim, so:

    drush cim -y --source=/some/valid/path

seems to work regardless of how many $confi_directory keys there are.

**Comment by weitzman** [comment]
I think this will be fixed by https://github.com/drush-ops/drush/pull/4124 (a 1 line change). Please post here if I'm wrong

**Comment by weitzman** [comment]
My PR was wrong. Reopening this. Anyone is welcome to work on it.

**Comment by alberto56** [comment]
The concept of multiple config_directories [is now deprecated](https://www.drupal.org/node/3018145) so it might make sense to close this issue, which I'll do.
