### ISSUE TITLE
Sort commands under namespaces alphabetically

### ISSUE THREAD

**Issue by bpstr** [drush-ops/drush#4055]
Commands under namespaces are sorted in the same order as defined in files which makes hard to find the right commands. Especially in custom namespaces defined in multiple classes. Example:

```
 devel: 
   devel:reinstall (dre)  
   devel:hook (fnh, fn-hook, hook)   
   devel:event (fne, fn-event, event)  
   devel:token (token)
   devel:uuid (uuid)
   devel:services
```

I would like to see the commands in alphabetical order inside namespaces.

Another solution would be to add an optional argument to define sorting method **under namespaces**.

This is a small modification but could improve user experience and may be easy to solve.

**Comment by greg-1-anderson** [comment]
🎉
