### ISSUE TITLE
SiteAlias alter hook ignored depending on command line arguments

### ISSUE THREAD

**Issue by tspng** [drush-ops/drush#4058]
**Background**
I am trying to dynamically alter some site alias settings as described in the [example](https://raw.githubusercontent.com/drush-ops/drush/master/examples/Commands/SiteAliasAlterCommands.php) mentioned in the [docs](https://docs.drush.org/en/master/examples/).
Reason for this is that when running drush locally on a server instance, we need to use different IP's for the hosts defined in the aliases.

**Describe the bug**
The site alias alter hook as described in the example from docs is **not** executed when running:
`$ drush core:rsync @alias1:%files/ @alias2:%files`
 
But the hook works when running: 
`$ drush core:rsync @alias1 @alias2`

**To Reproduce**
Try the following SiteAliasAlter sample code and run `$ drush core:rsync @alias1:%files/ @alias2:%files`. 

```php
<?php
namespace Drush\Commands;
use Consolidation\AnnotatedCommand\AnnotationData;
use Consolidation\SiteAlias\SiteAliasManagerAwareInterface;
use Consolidation\SiteAlias\SiteAliasManagerAwareTrait;
use Symfony\Component\Console\Input\InputInterface;
/**
 * SiteAliasAlter Test
 */
class SiteAliasAlterTestCommands extends DrushCommands implements SiteAliasManagerAwareInterface
{
    use SiteAliasManagerAwareTrait;
    /**
     * This hook should make drush commands not work and exit.
     *
     * @hook pre-init *
     *
     * @param \Symfony\Component\Console\Input\InputInterface $input
     * @param \Consolidation\AnnotatedCommand\AnnotationData $annotationData
     */
    public function alter(InputInterface $input, AnnotationData $annotationData)
    {
        exit();
    }
}
```

**Expected behavior**
Drush should exit with `Drush command terminated abnormally. Check for an exit() in your Drupal site.`

**Actual behavior**
The alter() method is not executed (but should have).

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  |  Drush v9.6.2
| Drupal version? | 8.6.15
| PHP version     | 7.1.23
| OS?             | MacOS 10.14.4

**Comment by greg-1-anderson** [comment]
For avoidance of any doubt, where is SiteAliasAlterTestCommands installed?

**Comment by tspng** [comment]
In `$PROJECT_ROOT/drush/Commands/SiteAliasAlterTestCommands.php`

**Comment by weitzman** [comment]
Please share output of `drush sa` for both aliases. Might help. Also try to explicitly include your alter commandfile as per the example docs

> Load this example by using the --include option - e.g. `drush --include=/path/to/drush/examples`
