### ISSUE TITLE
Does drush cex really need a confirmation dialog?

### ISSUE THREAD

**Issue by MrPaulDriver** [drush-ops/drush#4060]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MrPaulDriver** [comment]
I see that when I `drush cex `I am always presented with a confirmation message..

> The .yml files in your export directory (../config/sync) will be deleted and replaced with the active config. (yes/no) [yes]:

Someone using this command would know what they want to do. So Is this confirmation request really necessary? 

I didn't check `drush cim`. But my thought are the same.

**Comment by greg-1-anderson** [comment]
You could use a command-specific option in your drush.yml file to auto-confirm configuration commands if you do not wish to be prompted.

**Comment by weitzman** [comment]
IMO is a valuable prompt. Pass -y or -n if you dont want to see it.

**Comment by gitressa** [comment]
+1 from me for keeping the confirmation dialog. It's great to be able to review the changes before exporting, by requiring a confirmation allows checking which files will be updated, should I accept.

**Comment by MrPaulDriver** [comment]
I've changed my mind about this. Very silly feature request of mine.
