### ISSUE TITLE
Make MessengerCommands the default w/ an option

### ISSUE THREAD

**Issue by chx** [drush-ops/drush#4063]
https://github.com/drush-ops/drush/pull/3489 is awesome. There are no articles, examples or tests so I'd wager noone knows its there. It's not easy to find. Why not move the functionality to `DrushCommands` triggered with an option? If I had any idea on how to take options in `MessengerCommands::log()` (or `pre/post`) I'd write it myself. Ie. if you like the idea and tell me how, I will code this.

**Comment by weitzman** [comment]
It's a commandfile so it loads on every request. You don't need to extend it - it logs all Drupal messages to the drush log. The disclaimer is that it only works after Drupal has fully bootstrapped. So it misses messages during cache rebuild and site install too.

**Comment by chx** [comment]
I really don't understand anything Drush does these days. Where could I read more?

**Comment by weitzman** [comment]
This is commandfile is implementing hooks provided by Annotated Command project. See https://github.com/consolidation/annotated-command/blob/master/README.md. I'm also happy to discuss via chat or voice.

**Comment by chx** [comment]
Well then let's continue in https://github.com/consolidation/annotated-command/issues/187
