### ISSUE TITLE
Drush 9 pm:security is not reporting the currently available security update

### ISSUE THREAD

**Issue by shaysmith** [drush-ops/drush#4064]
**Describe the bug**
Drupal core update has released, but drupal-security-advisories has not updated which results in pm:security not reporting the available security update.

**To Reproduce**
Reported issue at the drupal-security-advisorites project:
https://github.com/drupal-composer/drupal-security-advisories/issues/15

**Expected behavior**
Between Drush and the external project, the expected behavior is that Drush pm:security is aware of the available security update within minutes of its release.

**Actual behavior**
Drush reports that there are no available security updates which is incorrect.

**Workaround**
Is there another way to do the desired action?

https://raw.githubusercontent.com/drupal-composer/drupal-security-advisories/8.x-v2/composer.json

At time of this writing, security update has been out for 30+ minutes and Drush still does not report the availability of a security update (8.7.1):

```
drupal/core: "8.0-alpha2|8.0-alpha3|8.0-alpha4|8.0-alpha5|8.0-alpha6|8.0-alpha7|8.0-alpha8|8.0-alpha9|8.0-alpha10|8.0-alpha11|8.0-alpha12|8.0-alpha13|8.0.0|8.0.0-alpha14|8.0.0-alpha15|8.0.0-beta1|8.0.0-beta2|8.0.0-beta3|8.0.0-beta4|8.0.0-beta6|8.0.0-beta7|8.0.0-beta9|8.0.0-beta10|8.0.0-beta11|8.0.0-beta12|8.0.0-beta13|8.0.0-beta14|8.0.0-beta15|8.0.0-beta16|8.0.0-rc1|8.0.0-rc2|8.0.0-rc3|8.0.0-rc4|8.0.1|8.0.2|8.0.3|8.0.4|8.0.5|8.0.6|8.1.0|8.1.0-beta1|8.1.0-beta2|8.1.0-rc1|8.1.1|8.1.2|8.1.3|8.1.4|8.1.5|8.1.6|8.1.7|8.1.8|8.1.9|8.1.10|8.2.0|8.2.0-beta1|8.2.0-beta2|8.2.0-beta3|8.2.0-rc1|8.2.0-rc2|8.2.1|8.2.2|8.2.3|8.2.4|8.2.5|8.2.6|8.2.7|8.2.8|8.3.0|8.3.0-alpha1|8.3.0-beta1|8.3.0-rc1|8.3.0-rc2|8.3.1|8.3.2|8.3.3|8.3.4|8.3.5|8.3.6|8.3.7|8.3.8|8.3.9|8.4.0|8.4.0-alpha1|8.4.0-beta1|8.4.0-rc1|8.4.0-rc2|8.4.1|8.4.2|8.4.3|8.4.4|8.4.5|8.4.6|8.4.7|8.4.8|8.5.0|8.5.0-alpha1|8.5.0-beta1|8.5.0-rc1|8.5.1|8.5.2|8.5.3|8.5.4|8.5.5|8.5.6|8.5.7|8.5.8|8.5.9|8.5.10|8.5.11|8.5.12|8.5.13|8.5.14|8.6.0|8.6.0-alpha1|8.6.0-beta1|8.6.0-beta2|8.6.0-rc1|8.6.1|8.6.2|8.6.3|8.6.4|8.6.5|8.6.6|8.6.7|8.6.8|8.6.9|8.6.10|8.6.11|8.6.12|8.6.13|8.6.14|8.7.0-alpha1|8.7.0-alpha2|8.7.0-beta1|8.7.0-beta2|>=8.0,<8.0.0-beta2|>=8.0,<8.0.4|>=8.1,<8.1.3|>=8.1,<8.1.7|>=8.1,<8.1.10|>=8.2,<8.2.3|>=8.2,<8.2.7|>=8.2,<8.2.8|>=8.3,<8.3.1|>=8.3,<8.3.4|>=8.3,<8.3.7|>=8.3,<8.3.9|>=8.4,<8.4.6|>=8.4,<8.4.7|>=8.4,<8.4.8|>=8.5,<8.5.1|>=8.5,<8.5.2|>=8.5,<8.5.3|>=8.5,<8.5.6|>=8.5,<8.5.8|>=8.5,<8.5.9|>=8.5,<8.5.11|>=8.5,<8.5.14|>=8.5,<8.5.15|>=8.6,<8.6.2|>=8.6,<8.6.6|>=8.6,<8.6.10|>=8.6,<8.6.13|>=8.6,<8.6.15|>=8.7,<8.7.0-rc1",
```

**Comment by greg-1-anderson** [comment]
It looks like the SLA for the security advisories project is now thirty minutes.

The `pm:security` command should not be polled to detect security updates. The utility of this tool is to catch updates that may have been missed.

For update services, see [Violinist](https://violinist.io), [Dependabot](https://dependabot.com/) or [Dependencies.io](https://dependencies.io).

**Comment by shaysmith** [comment]
Is this communicated or documented somewhere? This is a significant change in expectation from how Drush pm-updatestatus was used or understood to have worked.

**Comment by greg-1-anderson** [comment]
I'm not sure that it was great that so many people were hitting drupal.org every five minutes with `pm-updatestatus`. You are right that we need to develop and socialize expectations for updates moving forward. c.f. the autoupdates initiative.

**Comment by greg-1-anderson** [comment]
There is interesting information about this in [[Policy, no patch] Improve speed of discovering an update](https://www.drupal.org/project/automatic_updates/issues/3051186). Planned improvements will be tracked in [Replace update status XML with a more modern system](https://www.drupal.org/project/infrastructure/issues/2688479).

**Comment by greg-1-anderson** [comment]
I think I overstated the limits of the `pm:security` command. Certainly it is polled to detect security updates. The thing that is out of scope is using it to provide extremely rapid response to recent releases. We are not going to be providing results within minutes.

For extremely critical (high value, high target) sites, a commercial service such as [Quo from Tag 1](https://quo.tag1consulting.com/) should be considered.

**Comment by shaysmith** [comment]
Why would most people do this as opposed to checking the UI? If I'm able to retrieve the information immediately via Drupal, I should be able to retrieve the same information via Drush. It would be faster and more convenient for some. That's how it used to work and I think folks would appreciate it working like that again.

It's clear that that is not going to happen however.

**Comment by greg-1-anderson** [comment]
The UI pulls data from drupal.org. The drupal.org data is read directly via the Drush `pm-*` commands. You can still use `pm-updatestatus` via Drush 8 if that is your preference (n.b. only if you do not have a site-local Drush 9).

This data is only exposed in the Composer workflow indirectly, and that process does not happen right away. There are initiatives in progress, cited above, to make Composer updates work better with Drupal. That will happen, but it will take time. Drush has no real facility to push this forward ahead of the core initiative, though, so on that front you are correct.
