### ISSUE TITLE
[Feature]: Config:Get command does not show if there any language overriden config

### ISSUE THREAD

**Issue by joshirohit100** [drush-ops/drush#4065]
I am using Drush 9.5.2 version. I have a config object and this config object also has language override.

When I run `drush cget my_config_object`, it shows the config object of default but not the language override.

So I suggest to have a option in command to show the language override as well if exists.

I am happy to contribute for this if already not available (I checked but couldn't find any).

**Comment by weitzman** [comment]
Please try with latest version if possible.

**Comment by KalleVuorjoki** [comment]
Still an issue on Drush 9.7.1.

**Comment by weitzman** [comment]
See --include-overridden option

**Comment by KalleVuorjoki** [comment]
Please re-open.

I have following in config table:
<img width="523" alt="DRUSH-4065" src="https://user-images.githubusercontent.com/3080364/74126363-6bb4f400-4be0-11ea-92bd-2fded031b2ab.png">

When I run `drush config-get --include-overridden block.block.tabs settings.label` I'll get only `'block.block.tabs:settings.label': 'Primary tabs'` not any of the language overriden values.

**Comment by weitzman** [comment]
I'm not sure, but I think thats by design. There is only 1 config objects for tabs. You would have to do language negotiation  in order to see other labels but Drush(and Drupal core CLI commands)  have no way to do that.
