### ISSUE TITLE
sql-sync fails at core:rsync step

### ISSUE THREAD

**Issue by socketwench** [drush-ops/drush#4071]
**Describe the bug**
In Drush 9.6.2, sql-sync now fails when attempting to run core:rsync. 

**To Reproduce**
1. Install Drush 9.6.2 in docker container `ten7/flight-deck-web`. This can either be globally via cgr or locally.
2. Set up SSH keys as expected.
3. Set up drush aliases as expected.
4. Run drush sql-sync @remote_source @self

**Expected behavior**
The sql-sync to complete.

**Actual behavior**
When running the command, the sync fails when attempting to rsync the file from the remote source. See verbose output:

https://gist.github.com/socketwench/287e8bf4e1aae90b4e5a7c8907738edc

**Workaround**
If the `core:rsync` command is run manually, it succeeds and the resultant database dump can be imported as expected.

Alternatively, revert back to drush 9.5.2, where the sql-sync completes without issue. 

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.2
| Drupal version? | 8.x
| PHP version     | 7.2
| OS?             | Alpine Linux via Docker.

**Additional information**

**Comment by socketwench** [comment]
This may be related to changes due in https://github.com/drush-ops/drush/pull/4011

**Comment by weitzman** [comment]
That looks to me like a confirm prompt was shown but not confirmed because its a non-interactive session. I'm not sure why the prompt was shown.

**Comment by johnpitcairn** [comment]
@weitzman this sounds right. I'm mentoring somebody who is having sql:sync trouble on Windows. The rsync portion of the command is getting aborted regardless of whether we run drush directly in git bash or drush.bat through winpty.

**Comment by back-2-95** [comment]
I get this currently with 9.7.1 inside Docker container (Alpine 3.10) with PHP 7.3.10.

**Comment by back-2-95** [comment]
And running the rsync command manually works...

**Comment by back-2-95** [comment]
And the change from #4011 seems to be reverted in 9.7.1.

**Comment by back-2-95** [comment]
Ok, so following command is run and it prompts (hence the aborted command):

`/app/vendor/drush/drush/drush core-rsync -y @remote-alias:/home/wodby/drush-backups/drupal/20191021062046/drupal_20191021_062046.sql.gz @self:/app/tmp/drupal_20191021_062046.sql.gz --uri=https://local.docker.sh --root=/app/public -- --remove-source-files`

It would need `-y` between `drush` and `core-rsync`.

**Comment by back-2-95** [comment]
@socketwench maybe you could test this?
