### ISSUE TITLE
Can't use Drush config for runserver --quiet option.

### ISSUE THREAD

**Issue by dpagini** [drush-ops/drush#4072]
**Describe the bug**
A recent update to Drush has caused the `$ drush runserver` command to output a lot of messages when hitting a site. I want to run the command in quiet mode. However, I cannot seem to use the drush config to do so.

In my `drush.yml` file, which I can confirm is being loaded, the following seems to be ignored:
```yml
command:
  runserver:
    options:
      quiet: true
```

**To Reproduce**
Put the above code in my `drush` config file, then run `$ drush runserver` and confirm that the output is not quiet.

**Expected behavior**
I expect no command line output, the same as if I ran `$ drush runserver --quiet`.

**Actual behavior**
I see lots of command line output.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.2
| Drupal version? | 8.6.16
| PHP version     | 7.1
| OS?             | Linux

**Comment by weitzman** [comment]
See #2956.

**Comment by dpagini** [comment]
Thanks @weitzman, sorry for the duplicate. If I could make a suggestion, it would be great to see this in either the example drush config file, or maybe on the consolidation/config readme page called out before this gets fixed. Is this a drush issue or upstream?
Thanks for all your work on drush!

**Comment by weitzman** [comment]
Its upstream, in https://github.com/symfony/symfony/issues/24314 I agree that a doc would be nice. I'm also unsure where it belongs. Any thoughts @greg-1-anderson?

**Comment by greg-1-anderson** [comment]
Yeah it is kind of unfortunate. Our workaround used to work; I'm not sure what changed. I do wonder if there might be another workaround.
