### ISSUE TITLE
 blt drupal:sync fails in drupal 8

### ISSUE THREAD

**Issue by mktomanikandan** [drush-ops/drush#4073]
**Describe the bug**
The command "ssh -p 22 xxxxxxxx.devcloud.hosting.acquia.com  
   'drush sql-dump --create-db --target-dump=/tmp/tmp.target.sql.gz --ansi --  
  no-interaction --structure-tables-key=lightweight --strict=0 --gzip --resul  
  t-file=auto --backend=json --uri=xxxxxxxx.devcloud.acquia-site  
  s.com --root=/var/www/html/xxxxxx.dev/docroot'" failed.

**To Reproduce**
What did you do?

**Expected behavior**
What did you expect would happen?

**Actual behavior**
The command "ssh -p 22 xxxx.dev@xxxxx.devcloud.hosting.acquia.com  
   'drush sql-dump --create-db --target-dump=/tmp/tmp.target.sql.gz --ansi --  
  no-interaction --structure-tables-key=lightweight --strict=0 --gzip --resul  
  t-file=auto --backend=json --uri=xxxxx.devcloud.acquia-site  
  s.com --root=/var/www/html/xxxxx.dev/docroot'" failed.                 
                                                                               
  Exit Code: 1(General error)                                                  
                                                                               
  Working directory:                                                           
                                                                               
  Output:                                                                      
  ================                                                             
  \DRUSH_BACKEND_OUTPUT_START>>>{"output":"","object":[],"error_status":1,"lo  
  g":[{"type":"preflight","message":"Drush preflight prepare loaded autoloade  
  r at \/usr\/local\/drush8\/vendor\/autoload.php","timestamp":1557981283.833  
  5969,"memory":2695592,"error":null},{"type":"preflight","message":"Starting  
   Drush preflight.","timestamp":1557981283.8361399,"memory":2696184,"error":  
  null},{"type":"bootstrap","message":"Loading drushrc \"\/etc\/drush\/drushr  
  c.php\" into \"system\" scope.","timestamp":1557981283.838119,"memory":3059  
  440,"error":null},{"type":"debug","message":"Cache HIT cid: 8.1.17-commandf  
  iles-0-8d3243674002493cf35f4de51cbda8b5","timestamp":1557981283.84196,"memo  
  ry":3098760,"error":null},{"type":"debugnotify","message":"Scanning into \/  
  etc\/drush for \/.*aliases\\.drush(8|)rc\\.php$\/","timestamp":1557981283.8  
  658619,"memory":6291080,"error":null},{"type":"debugnotify","message":"Scan  
  ning into \/etc\/drush for \/self\\.alias\\.drush(8|)rc\\.php$\/","timestam  
  p":1557981283.865952,"memory":6291712,"error":null},{"type":"debugnotify","  
  message":"Scanning into \/usr\/local\/drush8\/vendor\/drush\/drush\/include  
  s\/.. for \/.*aliases\\.drush(8|)rc\\.php$\/","timestamp":1557981283.866019  
  ,"memory":6292344,"error":null},{"type":"debugnotify","message":"Scanning i  
  nto \/usr\/local\/drush8\/vendor\/drush\/drush\/includes\/.. for \/self\\.a  
  lias\\.drush(8|)rc\\.php$\/","timestamp":1557981283.8677781,"memory":629335  
  2,"error":null},{"type":"debugnotify","message":"Scanning into \/home\/born  
  bulldog\/.drush for \/.*aliases\\.drush(8|)rc\\.php$\/","timestamp":1557981  
  283.8693709,"memory":6293984,"error":null},{"type":"debugnotify","message":  
  "Scanning into \/home\/xxxxx\/.drush for \/self\\.alias\\.drush(8|)rc  
  \\.php$\/","timestamp":1557981283.869405,"memory":6294888,"error":null},{"t  
  ype":"debugnotify","message":"Scanning into \/mnt\/drush\/xxxxx for \  
  /.*aliases\\.drush(8|)rc\\.php$\/","timestamp":1557981283.8694291,"memory":  
  6295520,"error":null},{"type":"debugnotify","message":"Scanning into \/mnt\  
  /drush\/xxxxx for \/self\\.alias\\.drush(8|)rc\\.php$\/","timestamp":  
  1557981283.8694961,"memory":6296560,"error":null},{"type":"debugnotify","me  
  ssage":"Scanning into \/mnt\/www\/html\/xxxxx\/docroot\/..\  
  /drush for \/.*aliases\\.drush(8|)rc\\.php$\/","timestamp":1557981283.86954  
  69,"memory":6297192,"error":null},{"type":"debugnotify","message":"Scanning  
   into \/mnt\/www\/html\/xxxxxx\/docroot\/..\/drush for \/sel  
  f\\.alias\\.drush(8|)rc\\.php$\/","timestamp":1557981283.8695619,"memory":6  
  297824,"error":null},{"type":"debugnotify","message":"Scanning into \/mnt\/  
  www\/html\/xxxxx\/docroot\/drush for \/.*aliases\\.drush(8|  
  )rc\\.php$\/","timestamp":1557981283.869575,"memory":6298456,"error":null},  
  {"type":"debugnotify","message":"Scanning into \/mnt\/www\/html\/bornbulldo  
  gtpa6tfwxpq\/docroot\/drush for \/self\\.alias\\.drush(8|)rc\\.php$\/","tim  
  estamp":1557981283.8695869,"memory":6299088,"error":null},{"type":"debugnot  
  ify","message":"Scanning into \/mnt\/www\/html\/xxxxx\/docr  
  oot\/sites\/all\/drush for \/.*aliases\\.drush(8|)rc\\.php$\/","timestamp":  
  1557981283.8695991,"memory":6299720,"error":null},{"type":"debugnotify","me  
  ssage":"Scanning into \/mnt\/www\/html\/xxxxx\/docroot\/sit  
  es\/all\/drush for \/self\\.alias\\.drush(8|)rc\\.php$\/","timestamp":15579  
  81283.869612,"memory":6300992,"error":null},{"type":"debugnotify","message"  
  :"Scanning into \/mnt\/www\/html\/xxxxx\/docroot\/sites\/bo  
  rnbulldogtpa6tfwxpq.devcloud.acquia-sites.com for \/.*aliases\\.drush(8|)rc  
  \\.php$\/","timestamp":1557981283.8696239,"memory":6301624,"error":null},{"  
  type":"debugnotify","message":"Scanning into \/mnt\/www\/html\/xxxxxx  
  \/docroot\/sites\/xxxxx.devcloud.acquia-sites.com   
  for \/self\\.alias\\.drush(8|)rc\\.php$\/","timestamp":1557981283.8696361,"  
  memory":6302256,"error":null},{"type":"bootstrap","message":"Bootstrap to p  
  hase 0.","timestamp":1557981283.9054539,"memory":8719024,"error":null},{"ty  
  pe":"bootstrap","message":"Bootstrap to phase -1.","timestamp":1557981283.9  
  058831,"memory":8722504,"error":null},{"type":"bootstrap","message":"Found   
  command: sql-dump (commandfile=sql)","timestamp":1557981283.9060011,"memory  
  ":8723160,"error":null},{"type":"debug","message":"Calling hook drush_sql_d  
  ump","timestamp":1557981283.9085391,"memory":8986760,"error":null},{"type":  
  "bootstrap","message":"Drush bootstrap phase : bootstrap_drupal_root()","ti  
  mestamp":1557981283.9142089,"memory":9711520,"error":null},{"type":"bootstr  
  ap","message":"Initialized Drupal 8.5.3 root directory at \/mnt\/www\/html\  
  /xxxxxx\/docroot","timestamp":1557981283.9172859,"memory":97  
  17920,"error":null},{"type":"debug","message":"Find command files for phase  
   1 (max=3)","timestamp":1557981283.9181559,"memory":8130352,"error":null},{  
  "type":"debug","message":"Cache HIT cid: 8.1.17-commandfiles-1-4631fc77d223  
  93a6f63cc807b6317f29","timestamp":1557981283.918298,"memory":8132968,"error  
  ":null},{"type":"debug","message":"Cache HIT cid: 8.1.17-annotationfiles-1-  
  0cbcb7bfe736f47e85cee43b4ff66810","timestamp":1557981283.9191761,"memory":8  
  206016,"error":null},{"type":"bootstrap","message":"Drush bootstrap phase :  
   bootstrap_drupal_site()","timestamp":1557981283.923861,"memory":8749856,"e  
  rror":null},{"type":"bootstrap","message":"Initialized Drupal site bornbull  
  dogtpa6tfwxpq.devcloud.acquia-sites.com at sites\/default","timestamp":1557  
  981283.923949,"memory":8750560,"error":null},{"type":"debug","message":"Fin  
  d command files for phase 2 (max=3)","timestamp":1557981283.9267421,"memory  
  ":8751192,"error":null},{"type":"debug","message":"Cache HIT cid: 8.1.17-in  
  stall_profile-66ecfeb9791a023150773849f1550c5d","timestamp":1557981283.9270  
  329,"memory":8752992,"error":null},{"type":"debug","message":"Cache HIT cid  
  : 8.1.17-commandfiles-2-ad38df9543aa6d43a8df20ae1660bd2c","timestamp":15579  
  81283.927243,"memory":8757144,"error":null},{"type":"bootstrap","message":"  
  Drush bootstrap phase : bootstrap_drupal_configuration()","timestamp":15579  
  81283.929755,"memory":9013784,"error":null},{"type":"debug","message":"Crea  
  te from request","timestamp":1557981283.930007,"memory":9027280,"error":nul  
  l},{"type":"debug","message":"add service modifier","timestamp":1557981283.  
  9363489,"memory":9544728,"error":null},{"type":"debug","message":"Find comm  
  and files for phase 3 (max=3)","timestamp":1557981283.93641,"memory":954602  
  4,"error":null},{"type":"debug","message":"Returned from hook drush_sql_dum  
  p","timestamp":1557981283.9640591,"memory":9702008,"error":null},{"type":"n  
  otice","message":"Command dispatch complete","timestamp":1557981283.964215,  
  "memory":9637008,"error":null}],"error_log":{"DRUSH_SQL_DUMP_FAIL":["Databa  
  se dump failed"]},"self":{"root":"\/mnt\/www\/html\/xxxx\/  
  docroot","uri":"xxxxxx.devcloud.acquia-sites.com","path-alia  
  ses":{"%drush-script":"drush8"},"ac-site":"xxxx","ac-env":"dev","ac-  
  realm":"devcloud","site":"xxxx","env":"dev","#group":"xxxx","  
  #file":"\/mnt\/drush\/xxx\/xxxx.aliases.drushrc.php"},"conte  
  xt":{"alias-path":["\/mnt\/drush\/xxxx","\/home\/xxxx\/.drush  
  "],"config-file":"\/etc\/drush\/drushrc.php","context-path":"\/etc\/drush\/  
  drushrc.php","php":"\/usr\/local\/php7.2\/bin\/php","php-options":"","creat  
  e-db":true,"target-dump":"\/tmp\/tmp.target.sql.gz","ansi":true,"no-interac  
  tion":true,"structure-tables-key":"lightweight","strict":"0","gzip":true,"r  
  esult-file":"auto","backend":"json","uri":"xxxxx.devcloud.a  
  cquia-sites.com","root":"\/var\/www\/html\/xxxx.dev\/docroot"}}<<<DR  
  USH_BACKEND_OUTPUT_END                                                       
                                                                               
  Error Output:                                                                
  ================                                                             
  \DRUSH_BACKEND:{"type":"bootstrap","message":"Bootstrap to phase 0.","times  
  tamp":1557981283.9054539,"memory":8719024,"error":null,"packet":"log"}       
  \\DRUSH_BACKEND:{"type":"bootstrap","message":"Bootstrap to phase -1.","tim  
  estamp":1557981283.9058831,"memory":8722504,"error":null,"packet":"log"}     
  \\DRUSH_BACKEND:{"type":"bootstrap","message":"Found command: sql-dump (com  
  mandfile=sql)","timestamp":1557981283.9060011,"memory":8723160,"error":null  
  ,"packet":"log"}                                                             
  \\DRUSH_BACKEND:{"type":"debug","message":"Calling hook drush_sql_dump","ti  
  mestamp":1557981283.9085391,"memory":8986760,"error":null,"packet":"log"}    
  \\DRUSH_BACKEND:{"type":"bootstrap","message":"Drush bootstrap phase : boot  
  strap_drupal_root()","timestamp":1557981283.9142089,"memory":9711520,"error  
  ":null,"packet":"log"}                                                       
  \\DRUSH_BACKEND:{"type":"bootstrap","message":"Initialized Drupal 8.5.3 roo  
  t directory at \/mnt\/www\/html\/xxxxx\/docroot","timestamp  
  ":1557981283.9172859,"memory":9717920,"error":null,"packet":"log"}           
  \\DRUSH_BACKEND:{"type":"debug","message":"Find command files for phase 1 (  
  max=3)","timestamp":1557981283.9181559,"memory":8130352,"error":null,"packe  
  t":"log"}                                                                    
  \\DRUSH_BACKEND:{"type":"debug","message":"Cache HIT cid: 8.1.17-commandfil  
  es-1-4631fc77d22393a6f63cc807b6317f29","timestamp":1557981283.918298,"memor  
  y":8132968,"error":null,"packet":"log"}                                      
  \\DRUSH_BACKEND:{"type":"debug","message":"Cache HIT cid: 8.1.17-annotation  
  files-1-0cbcb7bfe736f47e85cee43b4ff66810","timestamp":1557981283.9191761,"m  
  emory":8206016,"error":null,"packet":"log"}                                  
  \\DRUSH_BACKEND:{"type":"bootstrap","message":"Drush bootstrap phase : boot  
  strap_drupal_site()","timestamp":1557981283.923861,"memory":8749856,"error"  
  :null,"packet":"log"}                                                        
  \\DRUSH_BACKEND:{"type":"bootstrap","message":"Initialized Drupal site born  
  bulldogtpa6tfwxpq.devcloud.acquia-sites.com at sites\/default","timestamp":  
  1557981283.923949,"memory":8750560,"error":null,"packet":"log"}              
  \\DRUSH_BACKEND:{"type":"debug","message":"Find command files for phase 2 (  
  max=3)","timestamp":1557981283.9267421,"memory":8751192,"error":null,"packe  
  t":"log"}                                                                    
  \\DRUSH_BACKEND:{"type":"debug","message":"Cache HIT cid: 8.1.17-install_pr  
  ofile-66ecfeb9791a023150773849f1550c5d","timestamp":1557981283.9270329,"mem  
  ory":8752992,"error":null,"packet":"log"}                                    
  \\DRUSH_BACKEND:{"type":"debug","message":"Cache HIT cid: 8.1.17-commandfil  
  es-2-ad38df9543aa6d43a8df20ae1660bd2c","timestamp":1557981283.927243,"memor  
  y":8757144,"error":null,"packet":"log"}                                      
  \\DRUSH_BACKEND:{"type":"bootstrap","message":"Drush bootstrap phase : boot  
  strap_drupal_configuration()","timestamp":1557981283.929755,"memory":901378  
  4,"error":null,"packet":"log"}                                               
  \\DRUSH_BACKEND:{"type":"debug","message":"Create from request","timestamp"  
  :1557981283.930007,"memory":9027280,"error":null,"packet":"log"}             
  \\DRUSH_BACKEND:{"type":"debug","message":"add service modifier","timestamp  
  ":1557981283.9363489,"memory":9544728,"error":null,"packet":"log"}           
  \\DRUSH_BACKEND:{"type":"debug","message":"Find command files for phase 3 (  
  max=3)","timestamp":1557981283.93641,"memory":9546024,"error":null,"packet"  
  :"log"}                                                                      
  \sh: 1: cannot create auto.gz: Permission denied                             
  mysqldump: Got errno 32 on write                                             
  \DRUSH_BACKEND:{"error":"DRUSH_SQL_DUMP_FAIL","message":"Database dump fail  
  ed","packet":"set_error"}                                                    
  \\DRUSH_BACKEND:{"type":"debug","message":"Returned from hook drush_sql_dum  
  p","timestamp":1557981283.9640591,"memory":9702008,"error":null,"packet":"l  
  og"}                                                                         
  \\DRUSH_BACKEND:{"type":"notice","message":"Command dispatch complete","tim  
  estamp":1557981283.964215,"memory":9637008,"error":null,"packet":"log"}      
  \\DRUSH_BACKEND:{"type":"debug","message":"Cache HIT cid: 8.1.17-alias-path  
  --70c4dc6ad3f9be608b0d0448651187dc","timestamp":1557981283.966614,"memory":  
  9774024,"error":null,"packet":"log"}                                         
  \\DRUSH_BACKEND:{"type":"debug","message":"Cache SET cid: 8.1.17-alias-path  
  --70c4dc6ad3f9be608b0d0448651187dc","timestamp":1557981283.9911671,"memory"  
  :11798136,"error":null,"packet":"log"}

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.2
| Drupal version? | 8.7.1  
| PHP version     | 7.2.16
| OS?             | Centos 7

**Comment by weitzman** [comment]
please ask in blt or acquia support.
