### ISSUE TITLE
service-provider generator: incorrect inferred class/file name prevents execution when building the service container

### ISSUE THREAD

**Issue by john-herreno-ds** [drush-ops/drush#4076]
**Describe the bug**
Given a module with name "My O&M" (see second word) and machine name "my_om", the generated file/class name will be something like MyOMServiceProvider, which Drupal won't execute when building the service container.

**To Reproduce**
- Add a custom module, make sure to follow the specific conditions mentioned above about name and machine name.
- Generate a service-provider: drush generate service-provider, target the generated class to be under the custom module.
- Add 'die("Calling service provider");' to the register() method of the generated service provider class.
- Rebuild caches: drush cr
- The die() call is *not* triggered.

**Expected behavior**
- The generated class is named properly, so that Drupal will find it and execute it.

**Actual behavior**
- Drupal does not execute the generated service provider, when building the service container.

**Workaround**
- Rename the class/file, so that proper camelCase is used. For the "My O&M" example, a proper class/file name is MyOmServiceProvider.
- Rebuild caches: drush cr
- The test die() call is triggered.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.2
| Drupal version? | 8.7.1
| PHP version     | 7.3.1
| OS?             | Linux

**Comment by john-herreno-ds** [comment]
I already did some checks on both the Drush side and DCG, but could not find where the file/class name is inferred from the module name.

**Comment by Chi-teck** [comment]
>  could not find where the file/class name is inferred from the module name

https://github.com/Chi-teck/drupal-code-generator/blob/1.29.1/src/Command/Drupal_8/ServiceProvider.php

That's similar to https://github.com/Chi-teck/drupal-code-generator/issues/28. The class name should be  created from machine name not from human name. The issue has been fixed in DCG 2.x for all generators. We might need to backport it to 1.x branch.

**Comment by Chi-teck** [comment]
Fixed in DCG 1.29.2.
