### ISSUE TITLE
Units of time in `drush cron` are not correct

### ISSUE THREAD

**Issue by iBobik** [drush-ops/drush#4084]
**Describe the bug**
It seems it mixes miliseconds with seconds and prints always `ms`:

```
$ drush cron
 [notice] Starting execution of dblog_cron().
 [notice] Starting execution of field_cron(), execution of dblog_cron() took 12.97ms.
 [notice] Starting execution of file_cron(), execution of field_cron() took 8.83ms.
 [notice] Starting execution of locale_cron(), execution of file_cron() took 175.6ms.
 [notice] Starting execution of node_cron(), execution of locale_cron() took 7.65ms.
 [notice] Starting execution of search_cron(), execution of node_cron() took 108.17ms.
 [notice] Starting execution of statistics_cron(), execution of search_cron() took 28265.87ms.
 [notice] Starting execution of system_cron(), execution of statistics_cron() took 12.46ms.
 [notice] Starting execution of update_cron(), execution of system_cron() took 26.31ms.
 [notice] Execution of update_cron() took 81.29ms.
 [notice] Cron run completed.
```

At least total should be in seconds. search_cron seems real (28 s).

Here is video where you can see how long it took in reality: https://www.dropbox.com/s/5go5rldoyfcml1w/drush%20cron.mov?dl=0

**To Reproduce**
Run drush cron

**Expected behavior**
It will print `s` or `ms` units correctly.

**Actual behavior**
Prints `ms` always, even if value is in seconds.

**Workaround**
Not known.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.2 
| Drupal version? | 8.7.1 
| PHP version     | 7.2.18
| OS?             | Lando on Mac (Docker running in Linux VM)

**Comment by Chi-teck** [comment]
> Actual behavior
Prints ms always, even if value is in seconds.

28265.87ms is almost equal 28 sec. Isn't it?

Anyway I think those log messages come from Drupal core. You can find them in DB log (admin/reports/dblog).

**Comment by weitzman** [comment]
There is no total time in your output. The last log msg is for update_cron().
