### ISSUE TITLE
Drush and Entity query - D8

### ISSUE THREAD

**Issue by jnicola** [drush-ops/drush#4095]
**Describe the bug**
Our site deployment pattern uses Drush to run update hooks. Occasionally I have tasks where I need to take a newly added field on content and populate it with values. I write a hook_update_n function to accomplish this.

Twice now i've written updates that work, but fail on deploy and say there are no entities to update. It would appear to me that entity queries executed by Drush actually run as anonymous, and thus you need to add $query->accessCheck(FALSE); in order for them to work.

**To Reproduce**
-Create a node, give it a field
-Create a variety of those nodes
-Set permissions so as they cannot be accessed by anonymous.
-Create a custom hook_update_n function that performs an entity query on those nodes.
-Execute update from Drupal UI. It should report the correct amount of nodes with whatever conditon you chose.
-Execute the update again but this time from the command line via Drush (either by iterating the hook_update_n or changing system schema)
-Observe that you get zero values.

**Expected behavior**
Given drush has highly elevated levels of permission already, any time Drush executes an entity query, it should do so as superadmin.

**Actual behavior**
Drush seems to execute entity queries as Anonymous.

**Workaround**
Disable access checking on entity queries.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.x
| Drupal version? | 8.6.x
| PHP version     | 7.1
| OS?             | Reproducable on local for Mac, docker based linux, and Acquia's hosting.

**Comment by Chi-teck** [comment]
Hi Jesse.

> it should do so as superadmin

Drupal core allows to run updates through UI for any user with permission "administer software updates". However, this does not grantee that a user with such a permission has access to unpublished nodes.
From this point disabling access check for the entity query seems to be the most reliable solution.

Also special behavior of UID 1 is going to be removed some day.
https://www.drupal.org/project/drupal/issues/540008

**Comment by weitzman** [comment]
Drush should not automatically elevate the request's permissions. Agree that disabling access check is right solution. Or you can add a drush "pre" hook that call's drupal user account switcher service and switch before every updatedb request.
