### ISSUE TITLE
Allow json for the input-format of config:set

### ISSUE THREAD

**Issue by nnn-dev** [drush-ops/drush#4097]
**Is your feature request related to a problem? Please describe.**
Inside a python program (ansible library code), I want use drush command `config:set` to set an array.
I don't have yaml library to  encode data and don't want use string format (indicate each index is frustating), but I can use json format.

**Describe the solution you'd like**
Allow `json` as input-format for `config:set` command.
Perhaps using `json_decode` function in php.

**Describe alternatives you've considered**
I cannot use yaml input-format because I cannot encode in yaml (no yaml library and it is difficult to install one in my environment)
I have tested : with string input-format indicate each array element with index suffix  but it  make my code too complex.

**Additional context**
None

**Comment by weitzman** [comment]
I think this is useful in limited cases and conversion may not be reliable. Not worth it for core drush. Feel free to write pre hooks that add this option and convert the data.
