### ISSUE TITLE
Drush does not grant access to SQL user

### ISSUE THREAD

**Issue by prudloff-insite** [drush-ops/drush#4098]
**Describe the bug**
As mentionned in https://github.com/drush-ops/drush/issues/3997#issuecomment-474730629, Drush 9.6.2 does not grant privileges to the SQL user anymore when using `--db-su`.

**To Reproduce**
```bash
drush si config_installer --db-url=mysql://${DB_USERNAME}:${DB_PW}@localhost/${DB_NAME} --db-su=root --db-su-pw=$DB_ROOT_PW --yes"
```

**Expected behavior**
It should grant the user privileges on this database.

**Actual behavior**
It does not grant the privileges so the install fails later with this error:
```
In install.core.inc line 973:
                                                                               
  Resolve all issues below to continue the installation. For help configuring  
   your database server, see the <a href="https://www.drupal.org/docs/8/insta  
  ll">installation handbook</a>, or contact your hosting provider.<div class=  
  "item-list"><ul><li>Failed to connect to your database server. The server r  
  eports the following message: <em class="placeholder">SQLSTATE[HY000] [1045  
  ] Access denied for user '***'@'localhost'  
   (using password: YES)</em>.<ul><li>Is the database server running?</li><li  
  >Does the database exist or does the database user have sufficient privileg  
  es to create the database?</li><li>Have you entered the correct database na  
  me?</li><li>Have you entered the correct username and password?</li><li>Hav  
  e you entered the correct database hostname?</li></ul></li></ul></div>    
```

**Workaround**
Downgrading to 9.5.2 fixes the problem.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.2
| Drupal version? | 8.7.2
| PHP version     | 7.1.30
| OS?             | Linux

**Additional information**
I tried with the latest master (99923aa72b4c36a18affdac8b442c356a15d7287) and it does not work either

**Comment by greg-1-anderson** [comment]
Drush was improved to use the php sql APIs instead of the mysql cli tool in several instances. This is why the `--db-su` option disappeared, as Drush always uses the database credentials from (or for) the settings.php file.

We could potentially restore this feature by fixing up the database credentials on the fly during bootstrap. It would also be possible, although a little more complex to do this for `site:install`, as we'd want to be sure to keep `--db-url` around to use to rewrite settings.php after the Drupal installer is done, as the Drupal installer will always use whatever credentials were used to access the database during the install process. For `site:install`, this is also the workaround that folks can use in the latest version of Drush: put the `--db-su` credentials in the `--db-url` option, and then rewrite settings.php at the end.

**Comment by mikran** [comment]
That workaround works for database name, but not for creating database user and privileges.

It was very convenient to be able to quickly create user along with the database. Hopefully this will be possible in future versions again.

**Comment by weitzman** [comment]
The db-su option is still present in `si` command. So this is a bug report starting that we used to GRANT but now we dont? Sure thats possible - I have not investigated.

**Comment by weitzman** [comment]
The code to do the grant is still present. It inspects drush config, which you probably have not set yet. Is the --db-su option supposed to set the drush config dynamically? See https://github.com/drush-ops/drush/blob/21494be38146049e3000b68557f2dac34bd1aaa8/src/Sql/SqlMysql.php#L96-L107

**Comment by mikran** [comment]
Yes, I noticed too that the grant code is still there. Here is my exact case that is not working after the update:

I had automated non-interactive pipeline that created databases with `drush sql-create`, using `--db-url`, `--db-su` and `--db-su-pw`. This used to create database and user and privileges for that user. It used to work, now it does not create the user and privileges. Only the database gets created.

Speaking of workarounds, can Drush be used to write settings.php without actually installing the site?

**Comment by weitzman** [comment]
Unfortunately no - we delegate settings.php writing to Drupal's installer.

**Comment by weitzman** [comment]
Any chance you are using mysql 8? See #4261

**Comment by prudloff-insite** [comment]
We are using MariaDB 10.1.

**Comment by chrisfromredfin** [comment]
This ends up null in 9.7.1 if passed on command line as --db-su `$db_superuser = $this->getConfig()->get('sql.db-su');`

Where would this be set if not using --db-su on command line?
