### ISSUE TITLE
site:install error reporting

### ISSUE THREAD

**Issue by andrewanswer** [drush-ops/drush#4107]
https://www.drupal.org/project/drupal/issues/3063901

I have recently written several installation profiles/distribution and found this problem. When I try to install a profile from the command line, I don't see a list of installed modules (from dependencies/install section of profile). And, if I got some error, this error is much less than what I see when installing the profile through the browser (for example, about configuration issues).

What I suggest:

* Add an option to the drush si command or change the output to print a list of installed modules. (with current number and total count: "[3/57] Views module installed.").
* Catch errors like it was in the browser. I expect to get the same information from the CLI as from the browser.

**Comment by weitzman** [comment]
We had this logging before Drupal 8. I have not found a way to inject our logger before bootstrap is complete. See https://github.com/drush-ops/drush/blob/d129e2db7ae7f103b8b27abf329039cc4def2bd4/src/Boot/DrupalBoot8.php#L242

**Comment by andrewanswer** [comment]
So, how you can propose to implement my request?

**Comment by weitzman** [comment]
I don't have a proposal.

**Comment by weitzman** [comment]
For error reporting, please elaborate on what you see at CLI versus web. Thanks.

**Comment by weitzman** [comment]
Fixed by #4378
