### ISSUE TITLE
Use a contrib package for opening links in browser.

### ISSUE THREAD

**Issue by drupol** [drush-ops/drush#4112]
**Is your feature request related to a problem? Please describe.**
I see in [ExecTrait.php](https://github.com/drush-ops/drush/blob/master/src/Exec/ExecTrait.php) that there are some code use for opening an url in a browser.

**Describe the solution you'd like**
I had to do a custom project recently where I needed a proper launcher, so I created [drupol/launcher](https://packagist.org/packages/drupol/launcher).

Maybe it would be a nice idea to delegate that part of the job to that new package?

**Comment by weitzman** [comment]
Too small to merit a new dependecy.
