### ISSUE TITLE
Add cache tags invalidate

### ISSUE THREAD

**Issue by batkor** [drush-ops/drush#4126]
**I'm not can invalidate cache tag .**
In production server, all cache size > 8Gb. I'm want invalidate cache for individual node. I dont can :-(

**Add new drush command**
I think add new drush command for cache tag invalidate.

**In DrupalConsole used command**
In Drupal console used `cache:tag:invalidate`

I'm created command on the current project
```php
  /**
   * Command TagInvalidate.
   *
   * @param string $tags
   *   Tags for invalidate.
   *
   * @command cache-manager:tag:invalidate
   * @aliases cm:ti
   */
  public function cacheTagInvalidate($tags) {
    $array_tags = explode(',', $tags);
    $this->invalidator->invalidateTags($array_tags);
    $this->logger()->success(dt('Invalidate tags: %tags.', [
      '%tags' => $tags,
    ]));
  }
```

**Comment by andypost** [comment]
Looks like devel module is better fit for that

**Comment by weitzman** [comment]
Yeah, lets do this in contrib. FYI purge module might have something similar already.
