### ISSUE TITLE
Drush 9.x is not using http proxy.

### ISSUE THREAD

**Issue by obriat** [drush-ops/drush#4134]
**Describe the bug**
Drush 9 could not reach drupal-security-advisories if placed behind a proxy.
The `methodSecurityUpdateCommands::fetchAdvisoryComposerJson` is using raw `file_get_contents()` without any proxy settings.

**To Reproduce**
Execute `drush sec` behind a proxy

**Expected behavior**
Drush should be aware of proxy settings either from settings.php, parameters or env variables.

**Actual behavior**
Drush could not reach internet host if placed behind a proxy.

**Workaround**
Patch these method to pass proxy setting (there's also 21 other occurrences of  `file_get_contents` in drush 9 code base):
```
// TODO : get proxy settings
$context = stream_context_create([
    'http' => [
        'proxy' => 'tcp://PROXY_HOST:PROXY_PORT',
        'request_fulluri' => true,
    ],
]);
$response_body = file_get_contents('https://raw.githubusercontent.com/drupal-composer/drupal-security-advisories/8.x-v2/composer.json');
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.x
| Drupal version? | 8.x
| PHP version     | 7.1
| OS?             | Linux

**Comment by weitzman** [comment]
Note #4040. I'd consider a PR for this.

**Comment by obriat** [comment]
Hi @weitzman,
I made the PR, could you please review it and merge it if everything is OK ?
