### ISSUE TITLE
Escape rsync params

### ISSUE THREAD

**Issue by kristofferrom** [drush-ops/drush#4138]
If you place your local site in a local Google Drive-folder on Mac OSX the @self path isn't working. I guess it's due to the space in the folder name (Google Drive). I got these errors when doing an rsync. Notice how the path gets duplicated in the second error for some reason.

> rsync: link_stat "/Users/Username/Google" failed: No such file or directory (2)
> rsync: change_dir "/Users/Username/Google Drive/Path/Site//Drive/Path/Site" failed: No such file or directory (2)

I tried moving my site to my Documents-folder and rsync'ing from there works completely fine with the exact same settings.

**Comment by greg-1-anderson** [comment]
What version of Drush? That does look like a file path escaping issue.

**Comment by kristofferrom** [comment]
That's Drush 9.

**Comment by weitzman** [comment]
please share log ouput when running with `-vvv`. also please include the site aliases involved. use `drush sa` for that.

**Comment by weitzman** [comment]
@greg-1-anderson  like we should be escaping $parameters at https://github.com/drush-ops/drush/blob/a7fd48e1a6c68f3182f2c783cb223265b12f3515/src/Commands/core/RsyncCommands.php#L70-L78?

**Comment by weitzman** [comment]
Closed in #4150
