### ISSUE TITLE
Will pm:security work for Drush 9 in the future?

### ISSUE THREAD

**Issue by gitressa** [drush-ops/drush#4139]
Drupal version: 8.7.4
Drush version: 9.7.1

In #3925 it is stated that `pm:security` will be removed from Drush 9.6, yet under [Releases](https://github.com/drush-ops/drush/releases) -> 9.6.0 it says

> Fix significant bug where pm:security misses required security updates. (#3766)

To test `pm:security` I just tried adding the Drupal 8 module alinks version 1.0, which has a security update available, and it looks like `pm:security` works perfectly in the latest version of Drupal core, and the version of Drush which comes with it:
```
$ drush pm:security
 [warning] One or more of your dependencies has an outstanding security update.
 [notice] Try running: composer require drupal/alinks --update-with-dependencies
 [notice] If that fails due to a conflict then you must update one or more root dependencies.
+---------------+-------------------+
| Name          | Installed Version |
+---------------+-------------------+
| drupal/alinks | 1.0.0             |
+---------------+-------------------+
```
Will `pm:security` be available in the foreseeable future?

Also, I looked for [Drush refresh commands](https://drushcommands.com/drush-9x/pm/), but it looks like they have all been deprecated. Is `pm:security` supposed to not need a refresh, but refresh status, as part of checking for security updates?

**Comment by weitzman** [comment]
Pm:security was rewritten for drush9 and is here forever. It does not require a refresh nor does it even require a working Drupal site. Just needs a composer.lock.

**Comment by gitressa** [comment]
That is really good news @weitzman, thank you for that, and all the work you and @greg-1-anderson have put into Drush over the years.
