### ISSUE TITLE
Site alias with "." in name fails drush pre-flight check

### ISSUE THREAD

**Issue by philltran** [drush-ops/drush#4140]
**Describe the bug**
Site alias with "." in name fails drush pre-flight check. I am not sure if the site name is against naming convention. I did not see "." character disallowed at [drupal.org documentation.](https://www.drupal.org/docs/8/multisite)

**To Reproduce**
Exported site aliases from Acquia account. When I try to use drush with alias, I receive an error. 
`drush @site.name.smgdev status`
` [preflight] The alias @storm.water.smgdev could not be found.`

**Expected behavior**
Drush runs the selected command on my remote server.

**Actual behavior**
Received error message. 
` [preflight] The alias @storm.water.smgdev could not be found.`

**Workaround**
Renamed site alias to remove "." from alias. 

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.7.1
| Drupal version? | 8.7.5 
| PHP version     | 7.2
| OS?             | Linux

**Additional information**
I think the issue lies with [drush/src/Preflight/PreflightSiteLocator.php: 44](https://github.com/drush-ops/drush/blob/d83e2fd4291d759571de40215ab0dcf0aeb16b09/src/Preflight/PreflightSiteLocator.php#L44). 

I believe the function thinks the alias name is an uri and acts accordingly.

**Comment by greg-1-anderson** [comment]
Drush 8 allowed `.`s in alias names. Drush 9 does not. In Drush 9, the `.` character is reserved as the separator between the parts of the alias (e.g. site name and environment).

**Comment by philltran** [comment]
Thanks for the info. I guessed that was the case, but couldn't find documentation stating that.
