### ISSUE TITLE
@remote command not found with composer-installed drupal / drush

### ISSUE THREAD

**Issue by govb** [drush-ops/drush#4146]
Drush version: 9.7.1
System: remote linux server (no root rights whatsoever, no globally installed drush)

I used composer to install drupal on a shared host without any rights to setup drush globally. Everything works fine when I use 'php vendor/bin/drush' to call drush. 

I created an alias for this remote site:

remote:
  host: ssh.hostname
  user: user
  paths: 
    drush-script: /www/mysite/vendor/drush/drush/drush.php
  root: /www/mysite
  uri: mysite.web

When executing a command on the remote site, however, the global command 'path/to/drush' is called directly instead of '**php** path/to/drush'. 
So I get an error saying 'command not found'.

I can't find a way to force the script to add the 'php' call. 

Workarounds that I tried:
- setting 'drush-script' to 'php  /www/mysite/vendor/drush/drush/drush.php'  (or several variations hereof) doesn't work because for some reason ''\'' is added around the command. ("ssh -t -o PasswordAuthentication=no user@ssh.hostname ''\''php /www/mysite/vendor/drush/drush/drush.php'\'' cr --uri=mysite.web --root=/www/mysite')

- bashrc is not sourced when ssh'ing a command so shell alias 'drush' doesn't work. I don't have the rights to change this (is set in /etc/bash.bashrc).

Wouldn't it be a good idea to always add 'php' when a drush-script path is specified? Or is there an other way to use the site alias for remote environments without a globally installed version of drush?

**Comment by weitzman** [comment]
If your drush is inside your codebase in the usual vendor/bin/drush location then you should not need to specify %drush-script. Thats not usually used to point to drush itself, but rather to a custom script of your own creation that wraps drush. Do you get errors if you omit drush-script?

**Comment by govb** [comment]
Yes, I get the same error. For example: drush @remote cr

results in:

 The command "ssh -t -o PasswordAuthentication=no user@ssh.hostname 'drush cr --uri=mysite.web --root=/www/mysite'" failed.

  Exit Code: 127(Command not found)


When I run ssh -t -o PasswordAuthentication=no user@ssh.hostname 'php drush cr --uri=mysite.web --root=/www/mysite 
it works fine.

**Comment by weitzman** [comment]
I suppose you can make a bash script called rundrush.sh whose contents are `php drush `

**Comment by govb** [comment]
But then I need to call the script as 'bash rundrush.sh', right? Just running rundrush.sh fails too...

**Comment by govb** [comment]
Another option would be that I can pass a custom command that would be executed between the ssh call and the drush command. I could then pass 'source ~/.bashrc' for example. But I can't find a way to do that either.

**Comment by weitzman** [comment]
You have to put a shebang at top of rundrush.sh so that unix knows what
program to use. See https://bash.cyberciti.biz/guide/Shebang

**Comment by govb** [comment]
Yes, I did that, but I don't have any rights to put stuff in any of the folders in the PATH. So I either have to find a way add my home to the path with ssh, or I have to call the script with 'bash'. The joys of working with a cheap host...

**Comment by weitzman** [comment]
rundrush.sh doesn't have to be on your PATH. You can specify a full path as value of drush-script.
