### ISSUE TITLE
Drush SQL commands not working with non standard MySQL socket

### ISSUE THREAD

**Issue by r7l** [drush-ops/drush#4158]
**Describe the bug**

I have a Docker setup with a MySQL container only connected to my PHP container over a socket. So far so good, everything works and was working with older Drush versions (It works with Drupal 7 and Drush 8).

The socket is defined to be at `/var/run/mysql/mysql.sock` in Drupal settings.php and MySQL configuration. I can run any MySQL command from cli as well as any other Drush command (like `drush updb`). Drupal is running fine as well.

I can't run any Drush SQL commands. It will always end up with this error:

```Got error: 2002: "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)" when trying to connect```

**To Reproduce**
Run a command like `drush sqlc`

**Expected behavior**
Connect to MySQL

**Actual behavior**
Error Message: 

```ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)```

**Workaround**
Use any MySQL command directly.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | Drush Commandline Tool 9.7.1
| Drupal version? | 8.7.6
| PHP version     | 7.3.6
| OS?             | Linux / Docker

**Additional information**
When debugging this issue i've found that Drush seems to add some default configuration. I am not entirely sure what is in that configuration since it will delete the files after using it.

This is what the debug gives me:

 [info] Executing: mysqldump **--defaults-file=/tmp/drush_Vf8J0Z** drupal --host=localhost --no-autocommit --single-transaction --opt -Q  [0.29 sec, 3.81 MB]

What exactly is in **/tmp/drush_Vf8J0Z** and how to prevent Drush from using it? How  to set it to the correct socket?

Suggested fix would be to not introduce a default when there is one set already in MySQL config or use the one from Drupal in settings.php when it's set like this: `'unix_socket' => '/var/run/mysql/mysql.sock',`

**Comment by weitzman** [comment]
IIRC, there was some uproar about mysql client config overriding whats setup in Drupal. So now the Drupal config is used to populate tmp files like ` /tmp/drush_Vf8J0Z` and thats used unconditionally. 

You can see the minimalist contents of that file at https://github.com/drush-ops/drush/blob/21494be38146049e3000b68557f2dac34bd1aaa8/src/Sql/SqlMysql.php#L17-L28. Looks like we have no handling of socket there. Please add it if you can. Here is what $dbSpec is for my local install. [socket] would there if one were defined in Drupal's settings.php since $dbSpec contains the return value of Drupal's `Database::getConnectionInfo`
```
Array
(
    [database] => unish_default
    [username] => root
    [password] => password
    [prefix] => Array
        (
            [default] => 
        )

    [host] => localhost
    [port] => 
    [namespace] => Drupal\Core\Database\Driver\mysql
    [driver] => mysql
)
```

**Comment by r7l** [comment]
Thanks for your reply. I am somewhat uncertain how to add it into it since i've never used EOT syntax in PHP before. It's probably not a good idea to write PHP code within the EOF part. Without any code it would always default to some socket, which isn't ideal as well.

So i think it should either be duplicated and decided by some `if` when to use the version with socket and when to use the one we have now.

Currently the setting for socket is not `socket` but `unix_socket`. At least that's how it works for me in Drupal.

**Comment by weitzman** [comment]
This was fixed. See above.
