### ISSUE TITLE
Drush assumes bash/bourne shell for redirection of stderr

### ISSUE THREAD

**Issue by mrludo** [drush-ops/drush#416]
Drush assumes that remote sites are using either bash or bourne shell.

When doing  drush sql-sync @mydev @myprod  where the myprod is on a remote FreeBSD server, the command that is executed remotely has 2>&1 which is bourne/bash syntax to redirect stderr to stdout .

If the remote user has tcsh as their shell, this syntax is not understood and the command fails.

**Comment by mc0e** [comment]
I came here to report the piping of stderr to stdout as a bug (https://github.com/drush-ops/drush/issues/1270), so perhaps just not doing that is the way to deal with the issue here?

**Comment by greg-1-anderson** [comment]
Yes.  I doubt we will ever fix this unless we do #1270, so I am just going to close this as a duplicate.
