### ISSUE TITLE
Option to drop existing during non-interactive site install

### ISSUE THREAD

**Issue by danepowell** [drush-ops/drush#4184]
**Is your feature request related to a problem? Please describe.**
We are writing scripts that use Drush to install Drupal. Because they are run automatically, we use `--no-interaction`. When any tables exist in the database, Drush/Drupal throw a database already installed exception.

**Describe the solution you'd like**
An option such as `--drop-existing` that could be used as follows: `drush si my_profile --no-interaction --drop-existing` that will essentially force an install, even if tables exist in the database.

**Describe alternatives you've considered**
Manually dropping the db/tables prior to running `drush si`. This involves duplicating a lot of Drush internal logic, which just seems silly.

**Additional context**
During interactive execution, Drush already asks if you'd like to drop an existing db/tables, but the same option doesn't exist during non-interaction execution. This would just bring parity between interactive and non-interactive installs.

**Comment by greg-1-anderson** [comment]
Does `--yes` drop existing?

**Comment by weitzman** [comment]
site:install already drops existing tables. it uses the same logic that sql:drop command uses. neither of those is working for you? is there any way `mysql` is not available? what version of drush?

**Comment by danepowell** [comment]
> is there any way mysqlclient is not available

Bingo! That's a hell of a hunch, how'd you come up with that one? 😄 

You are both correct, it appears that under normal conditions, `drush si --no-interaction` automatically drops existing tables/db as necessary and as desired.

However, if `mysql` is not available in the path, `drush si --no-interaction` will happily finish as long as the DB is empty, but will throw this entirely misleading error if any tables exist:
```
 In install.core.inc line 1165:
<ul>
<li>To start over, you must empty your existing database and copy <em>default.settings.php</em> over <em>settings.php</em>.</li>
<li>To upgrade an existing installation, proceed to the <a href="/update.php">update script</a>.</li>
<li>View your <a href="http://default">existing site</a>.</li>                                                          </ul> 
```

Can we do something to provide more helpful feedback when `mysql` is missing?

**Comment by greg-1-anderson** [comment]
Better error checking during site install (e.g. that there is actually a db that it can talk to, and that the cli tool is available) would be worthwhile to have.

**Comment by weitzman** [comment]
We used to forbid install in this situation. But as of Drush9, almost all of Drush works without `mysql`. You hit a situation that doesnt. 

@danepowell - Could you try #4185 and see if messaging improves? I didnt test it myself.

**Comment by danepowell** [comment]
Thanks a lot, that approach makes sense. Will comment in the PR.
