### ISSUE TITLE
Using --extra with "--set-gtid-purged=OFF" causes sqldump parameters to be ignored

### ISSUE THREAD

**Issue by pobtastic** [drush-ops/drush#4188]
**Describe the bug**
As per title, when using `--extra="--set-gtid-purged=OFF"` with a sql dump command (at least), the "SHOW TABLES" part which parses the tables doesn't run and fails with;
```
mysql: [ERROR] unknown variable 'set-gtid-purged=OFF'
```

Understandably, as it's a parameter only for the dump part of this command.

**To Reproduce**
`drush --root=/var/www sql-dump --structure-tables-list="a*,block,b*,c*,d*,e*,f*,g*,h*,i*,j*" --extra="--set-gtid-purged=OFF" --result-file=/tmp/dump.sql`

**Expected behavior**
To receive a dump with the appropriate tables skipped or containing just the structure.

**Actual behavior**
A full database dump is generated, as there are no tables being skipped or containing just the structure.

**Workaround**
Is there another way to do the desired action? **No**

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.x (but isn't limited to 8.x)
| Drupal version? | 7.x/8.x (doesn't matter/ both)
| PHP version     | 7.2
| OS?             | Linux

**Additional information**
N/A

**Comment by pobtastic** [comment]
This is a bit of a bother when using AWS RDS as you don't have "proper" access to the root MySQL user.  This means that imports contain a varied number of;
```
ERROR 1227 (42000): Access denied; you need (at least one of) the SUPER privilege(s) for this operation
```

**Comment by weitzman** [comment]
You want the --extra-dump option:

`--extra-dump=EXTRA-DUMP                       Add custom arguments/options
to the dumping of the database (e.g. mysqldump command).`

**Comment by pobtastic** [comment]
Ah ... not an option in the 8.x branch :(  No worries, I'll patch locally.  Thank you.

**Comment by Mykola-Veryha** [comment]
drush sql-dump --result-file=/tmp/dump.sql --gzip --extra-dump="--set-gtid-purged=OFF"
