### ISSUE TITLE
drush pm:security is not listing modules with 'security update required!'

### ISSUE THREAD

**Issue by greasedonkey** [drush-ops/drush#4189]
**Describe the bug**
drush pm:security says there is no outstanding security updates when the Web UI says otherwise.
```
root@d568732a8640:/app# drush pm:security
 [success] There are no outstanding security updates for Drupal projects.
```
![image](https://user-images.githubusercontent.com/4801997/65349709-18e78b00-dbb2-11e9-909c-7b20960669f3.png)

**To Reproduce**
Add form_steps 1.1 to your project and enable it and then:
```bash
root@d568732a8640:/app# drush pm:list | grep forms_steps
  Forms                 Forms Steps (forms_steps)                                               Enabled    8.x-1.1
root@d568732a8640:/app# drush pm:security
 [success] There are no outstanding security updates for Drupal projects.
root@d568732a8640:/app# drush version
 Drush version : 9.7.1
```

**Expected behavior**
Expected to see that there was a security update available for that module.

**Actual behavior**
A message displaying there was no outstanding update was presented.

**Workaround**
Look at the Web UI
/admin/reports/updates

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.7.1
| Drupal version? | 8.7.7
| PHP version     | 7.3.9
| OS?             | Docker Desktop / Linux container

**Additional information**
N/A

**Comment by weitzman** [comment]
Is your site built with composer? Specifically this project is in composer.lock?

**Comment by greasedonkey** [comment]
I'm pretty sure it does. We based it off this project https://github.com/drupal-composer/drupal-project.

```
"name": "drush/drush",
"version": "9.7.1",
"source": {
    "type": "git",
    "url": "https://github.com/drush-ops/drush.git",
    "reference": "6f9a8d235daec06fd6f47b2d84da675750566479"
}
```

**Comment by greasedonkey** [comment]
I fired up xdebug and my conclusion is that the security update is not listed in the json file (https://github.com/drupal-composer/drupal-security-advisories/blob/8.x-v2/composer.json) the command use to compare against the lock file.

How reliable is that source?

**Comment by greasedonkey** [comment]
have opened a ticket on that project, thanks for you help.  Closing this ticket for now.

https://github.com/drupal-composer/drupal-security-advisories/issues/18
