### ISSUE TITLE
Module installation ignores `hook_requirements`.

### ISSUE THREAD

**Issue by erikfrerejean** [drush-ops/drush#4190]
**Describe the bug**
When installing a module through `drush en` the result of `hook_requirements` isn't taken into account. We've got a module that sets an requirement error if a certain environment variable is missing, when installing through the Drupal UI installation is correctly blocked, when installing through Drush the module is enabled no matter what. 

**To Reproduce**
Add a module that implements `hook_requirements` and return a requirement with the severity `REQUIREMENT_ERROR`.

**Expected behavior**
That the installation of the module would be blocked.

**Actual behavior**
The module is installed.

**Workaround**
N/A

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.7.1 
| Drupal version? | 8.7.7
| PHP version     | 7.2.20
| OS?             | Linux

**Comment by davereid** [comment]
I can confirm this behavior. hook_requirements is checked for install profiles, but not when running pm:enable.

**Comment by davereid** [comment]
Related to https://github.com/drush-ops/drush/issues/3669

**Comment by weitzman** [comment]
Will be fixed in #4337
