### ISSUE TITLE
drush config:status does not respect excluded modules 

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#4194]
**Describe the bug**
"Config exclude" functionality [has been added](https://www.drupal.org/node/3079028) to Drupal Core recently. However, `drush cst` command still checks excluded configuration.

**To Reproduce**
Put the following code to settings.php:
`$settings['config_exclude_modules'] = ['field_ui']`
Check config status: `drush config:status`

**Expected behavior**
```
 [notice] No differences between DB and sync directory.
```

**Actual behavior**
```
 ------------------- ------------ 
  Name                State       
 ------------------- ------------ 
  core.extension      Different   
  field_ui.settings   Only in DB  
```

**System Configuration**

| Q               | A
| --------------- | ---
| Drush version?  | 10.x
| Drupal version? | 8.8.x
| PHP version     | 7.3
| OS?             | Linux

**Additional information**
`drush cex` and `drush cim` commands work well.

**Comment by claudiu-cristea** [comment]
I confirm the issue even I'm still using the contrib module ([Config Exclude](https://www.drupal.org/project/config_exclude)) which was the starting point of the core new feature.

**Comment by claudiu-cristea** [comment]
And if you use the `config_update_ui` (latest from dev) and run:
```
drush config:diff core.extension
```
that shows no diff

**Comment by JTubex** [comment]
Created #4201 that edits the config:status command so it uses the `config_exclude_modules` setting.

**Comment by bircher** [comment]
:+1:

**Comment by weitzman** [comment]
Merged #4201.

**Comment by Chi-teck** [comment]
It might be useful to have an option to see the status with excluded configuration.

**Comment by theteknocat** [comment]
Why is this still an issue almost a year later? What's the point of a feature like this in core when it just doesn't work? It's even documented in the settings.local.php example file you get with Drupal, yet it never works when using Drush, which devs use ALL THE TIME. Using config split is a poor solution to the problem.
