### ISSUE TITLE
Latest Drush version not working with symfony/yaml v4.3.4

### ISSUE THREAD

**Issue by sonvir249** [drush-ops/drush#4200]
**Describe the bug**
I am trying to is install Drush using composer global require command. 
_composer global require drush/drush:dev-master_
`Problem 1
    - Conclusion: remove symfony/yaml v4.3.4
    - Conclusion: don't install symfony/yaml v3.4.31
    - Installation request for drush/drush dev-master -> satisfiable by drush/drush[dev-master].
    - Conclusion: don't install symfony/yaml v4.3.4`

**To Reproduce**
run _composer global require drush/drush:dev-master_

**Actual behavior**
`Changed current directory to /Users/sonvir249/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.`

  `Problem 1
    - Conclusion: remove symfony/yaml v4.3.4
    - Conclusion: don't install symfony/yaml v3.4.31
    - Installation request for drush/drush dev-master -> satisfiable by drush/drush[dev-master].
    - Conclusion: don't install symfony/yaml v4.3.4
    - drush/drush dev-master requires symfony/yaml ^3.4 -> satisfiable by symfony/yaml[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.27, v3.4.28, v3.4.29, v3.4.3, v3.4.30, v3.4.31, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Can only install one of: symfony/yaml[v3.4.0, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.1, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.10, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.11, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.12, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.13, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.14, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.15, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.16, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.17, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.18, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.19, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.2, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.20, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.21, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.22, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.23, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.24, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.25, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.26, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.27, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.28, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.29, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.3, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.30, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.4, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.5, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.6, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.7, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.8, v4.3.4].
    - Can only install one of: symfony/yaml[v3.4.9, v4.3.4].
    - Installation request for symfony/yaml (locked at v4.3.4) -> satisfiable by symfony/yaml[v4.3.4].
Installation failed, reverting ./composer.json to its original content.`

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.x/8.x (please be specific, and try latest dev build)
| PHP version     | 7.1.23
| OS?             | Mac

**Comment by leymannx** [comment]
You don't install Drush globally anymore.

> Drush only supports one install method. It requires that your Drupal site be built with Composer and Drush be listed as a dependency.

See https://docs.drush.org/en/master/install/

Since Drupal doesn't support Symfony 4 yet this shouldn't be a problem then.

**Comment by greg-1-anderson** [comment]
Obligatory reference to the fact that `composer global require` should only be used for global Composer plugins. If it's not a plugin, don't use `--global`.

[Fixing the Composer global command](https://pantheon.io/blog/fixing-composer-global-command)
