### ISSUE TITLE
Inconsistent quoting of the database name in CREATE DATABASE statements executed by sql:create and site:install

### ISSUE THREAD

**Issue by ericras** [drush-ops/drush#4203]
**Describe the bug**
There is inconsistent quoting of the database name in CREATE DATABASE statements executed by sql:create and site:install.  Both are hardcoded and not configurable.

- [sql:create passes TRUE to the $quoted param ](https://github.com/drush-ops/drush/blob/master/src/Commands/sql/SqlCommands.php#L103)
- [site:install calls SqlBase::dropOrCreate which does not pass a param so $quoted is FALSE by default](https://github.com/drush-ops/drush/blob/master/src/Sql/SqlBase.php#L463)

**To Reproduce**
Create databases with special characters, such as hyphens, in the names:

This succeeds: 
`drush sql:create --db-url="mysql://user:pass@127.0.0.1/name-with-hyphens"`

This fails when the database has not already been created: 
`drush site:install --db-url="mysql://user:pass@127.0.0.1/another-name-with-hyphens"`

**Expected behavior**
drush site:install should be able to complete with a supplied database name with hyphens that has not yet been created.

**Actual behavior**
drush site:install fails

**Workaround**
The workaround is to create the database first before doing a site install.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.x (master)
| Drupal version? | 8.x
| PHP version     | 7.1 & 7.3 tested
| OS?             | Mac & Linux

**Comment by weitzman** [comment]
Lets discuss in #4204
