### ISSUE TITLE
User:login command incorrect url handling

### ISSUE THREAD

**Issue by hernani** [drush-ops/drush#4208]
**Describe the bug**
The user one time login link that is generated by user:login command, directly appends '/login' to the generated url. This creates problems in situations where the language identifier is used in the end of the url as a suffix. 

For instance when using urls like:
- node/1_en
- node/_en

When generating the url using drush uli we get:
- http://locahost/user/reset/1/1570442335/VUGw8gkJPUQZ3ZhdtzfSpo2DzptejtnDfj6Z1vp38q8_en/login

Instead of the correct:
- http://localhost/user/reset/1/1570442335/VUGw8gkJPUQZ3ZhdtzfSpo2DzptejtnDfj6Z1vp38q8/login_en

**To Reproduce**
Use some sort of LanguageNegotation method that alters the path to have a required suffix.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.x/8.x
| Drupal version? | 7.x/8.x
| PHP version     | 5.6/7.1
| OS?             | Mac/Linux/Windows

**Comment by hernani** [comment]
https://github.com/drush-ops/drush/pull/4209

**Comment by weitzman** [comment]
fixed in #4209
