### ISSUE TITLE
`drush ssh` does not pipe stdin

### ISSUE THREAD

**Issue by geek-merlin** [drush-ops/drush#4210]
**Describe the bug**

When i do 
The remote process does not receive the stdin of the caller.

**To Reproduce**

`<local-file drush @foo ssh "cat >remote-file"`

**Expected behavior**

remote-file contains content of local-file, like ssh.

**Actual behavior**

remote-file is empty.

**Workaround**

None i know.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.x-dev
| Drupal version? | None
| PHP version     | 7.1
| OS?             | Linux

**Additional information**

I want to bash my ssh-copy-id with this ;-).

**Comment by greg-1-anderson** [comment]
I can't get `<local-file` to work for me in any context (e.g. `<local-file | cat >copy`).

The two variants bleow both work for me, though:

- `echo foo | drush @foo ssh "cat >remote-file"`
- `cat local-file | drush @foo ssh "cat >remote-file"`

**Comment by geek-merlin** [comment]
> I can't get <local-file to work for me in any context (e.g. <local-file | cat >copy).

OK i admit the "<" in front is unusual and maybe misleading. It would be either
`<local-file cat >copy` or `cat local-file |cat copy`. 

I'll investigate and further simplify steps to reproduce.

**Comment by geek-merlin** [comment]
Further simplified, i can reproduce this here without any files involved:
```
merlin@thinker ~/tmp $ drush @koko.live ssh "echo 'someinput'"
someinput
merlin@thinker ~/tmp $ echo 'someinput' | drush @koko.live ssh "cat"
merlin@thinker ~/tmp $ echo 'someinput' | drush -vvd @koko.live ssh "echo 'start'; cat; echo 'end'"
start
end
merlin@thinker ~/tmp $ drush version
 Drush version : 9.8.0-dev 
```

**Comment by greg-1-anderson** [comment]
The examples that are not working for you are working for me. I'm not sure what the cause is; further isolation is needed.

**Comment by ethanbb** [comment]
I'm having this same issue:

```bash
ethan@Ethan-Dell [...] $ echo foo | ssh ethanbb@$my_server cat
foo
ethan@Ethan-Dell [...] $ echo foo | vendor/bin/drush @self.test ssh cat

ethan@Ethan-Dell [...] $ vendor/bin/drush @self.test ssh "echo foo | cat"
foo
ethan@Ethan-Dell [...] $ vendor/bin/drush @self.test ssh cat << EOF
> foo
> EOF
ethan@Ethan-Dell [...] $ vendor/bin/drush version
 Drush version : 10.2.2
```

System is Ubuntu 18.04 on WSL 1,

**Comment by ethanbb** [comment]
Another bug - it does not appear to preserve newlines in a command string as regular ssh does:

```bash
ethan@Ethan-Dell [...] $ server_code=$(cat << EOF
echo blah
> echo blah
> echo blah
> EOF
> )
ethan@Ethan-Dell [...] $ ssh ethanbb@hosting.pmacs.upenn.edu "$server_code"
blah
blah
blah
ethan@Ethan-Dell [...] $ vendor/bin/drush @self.test ssh "$server_code"
blah echo blah echo blah
