### ISSUE TITLE
Root-less alias breaks `drush @foo ssh` in drush9, FIXED in drush10

### ISSUE THREAD

**Issue by geek-merlin** [drush-ops/drush#4211]
When an alias has no root, `drush @foo ssh`

* works in drush10
* throws in drush9

## Proposed solution:

* Cherry-pick 88d5b0cd2e39575fe7ac06a89143c2367c5cdd14 to 9.x

<details><summary>Backtrace</summary><pre>
merlin@thinker ~ $ drush @server.u-jenn ssh ls

In SiteAliasTrait.php line 30:
                                                      
  Site alias @server.u-jenn does not specify a root.  
                                                      

site:ssh [--cd CD] [--tty] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--ssh-options SSH-OPTIONS] [--druplicon] [--notify [NOTIFY]] [--xh-link XH-LINK] [--] <command> [<args>]...

merlin@thinker ~ $ drush -vv @server.u-jenn ssh ls
 [preflight] Config paths: /home/merlin/.drush/drush.yml,/home/merlin/.config/composer/vendor-bin/drush9/vendor/drush/drush/drush.yml
 [preflight] Alias paths: /home/merlin/.drush/sites,/etc/drush/sites,/home/merlin/PhpstormProjects/g4c-aliases/sites
 [preflight] Commandfile search paths: /home/merlin/.config/composer/vendor-bin/drush9/vendor/drush/drush/src
 [bootstrap] Starting bootstrap to none [0.28 sec, 7.36 MB]
 [bootstrap] Drush bootstrap phase 0 [0.28 sec, 7.37 MB]
 [bootstrap] Try to validate bootstrap phase 0 [0.28 sec, 7.37 MB]

In SiteAliasTrait.php line 30:
                                                      
  [Exception]                                         
  Site alias @server.u-jenn does not specify a root.  
                                                      

Exception trace:
  at /home/merlin/.config/composer/vendor-bin/drush9/vendor/consolidation/site-alias/src/SiteAliasTrait.php:30
 Consolidation\SiteAlias\SiteAlias->root() at /home/merlin/.config/composer/vendor-bin/drush9/vendor/consolidation/site-alias/src/SiteAliasTrait.php:120
 Consolidation\SiteAlias\SiteAlias->isNone() at /home/merlin/.config/composer/vendor-bin/drush9/vendor/drush/drush/src/Commands/core/SshCommands.php:32
 Drush\Commands\core\SshCommands->ssh() at n/a:n/a
 call_user_func_array() at /home/merlin/.config/composer/vendor-bin/drush9/vendor/consolidation/annotated-command/src/CommandProcessor.php:257
 Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() at /home/merlin/.config/composer/vendor-bin/drush9/vendor/consolidation/annotated-command/src/CommandProcessor.php:212
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /home/merlin/.config/composer/vendor-bin/drush9/vendor/consolidation/annotated-command/src/CommandProcessor.php:178
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /home/merlin/.config/composer/vendor-bin/drush9/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:302
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /home/merlin/.config/composer/vendor-bin/drush9/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /home/merlin/.config/composer/vendor-bin/drush9/vendor/symfony/console/Application.php:1000
 Symfony\Component\Console\Application->doRunCommand() at /home/merlin/.config/composer/vendor-bin/drush9/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /home/merlin/.config/composer/vendor-bin/drush9/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /home/merlin/.config/composer/vendor-bin/drush9/vendor/drush/drush/src/Runtime/Runtime.php:118
 Drush\Runtime\Runtime->doRun() at /home/merlin/.config/composer/vendor-bin/drush9/vendor/drush/drush/src/Runtime/Runtime.php:49
 Drush\Runtime\Runtime->run() at /home/merlin/.config/composer/vendor-bin/drush9/vendor/drush/drush/drush.php:72
 require() at /home/merlin/.config/composer/vendor-bin/drush9/vendor/drush/drush/drush:4

site:ssh [--cd CD] [--tty] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--ssh-options SSH-OPTIONS] [--druplicon] [--notify [NOTIFY]] [--xh-link XH-LINK] [--] <command> [<args>]...
</pre></details>

**Comment by geek-merlin** [comment]
Tested that adding https://github.com/drush-ops/drush/commit/88d5b0cd2e39575fe7ac06a89143c2367c5cdd14.patch to composer-patches fixes the issue for me.

**Comment by weitzman** [comment]
done in 8848863b. thanks.
