### ISSUE TITLE
sql:dump --create-db does not insert CREATE DATABASE statement

### ISSUE THREAD

**Issue by kenahoo** [drush-ops/drush#4233]
**Describe the bug**
When using the `--create-db` flag to `drush sql:dump`, no `CREATE DATABASE` command is inserted into the SQL command text.

**To Reproduce**
```
singersin@s483:~/www/www$ drush --version
Failed loading /usr/local/ioncube/ioncube_loader_lin_7.1.so:  /usr/local/ioncube/ioncube_loader_lin_7.1.so: undefined symbol: zend_interrupt_function
 Drush Version   :  8.2.3 

singersin@s483:~/www/www$ drush sql:dump --create-db |head -n25
Failed loading /usr/local/ioncube/ioncube_loader_lin_7.1.so:  /usr/local/ioncube/ioncube_loader_lin_7.1.so: undefined symbol: zend_interrupt_function
-- MySQL dump 10.13  Distrib 5.7.23-percona-sure1, for Linux (x86_64)
--
-- Host: localhost    Database: singersin_drupal
-- ------------------------------------------------------
-- Server version	5.7.23-percona-sure1-log

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `actions`
--

DROP TABLE IF EXISTS `actions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `actions` (
```

**Expected behavior**
I'm not completely sure that the `--create-db` option is supposed to do what I think it does, because I don't see docs for it, but I would assume it's supposed to insert a `CREATE DATABASE ... IF NOT EXISTS;` statement into the output before trying to create tables.

**Actual behavior**
No such statement is inserted.

**Workaround**
Tried to figure out a workaround using the `--extra` option, but couldn't figure one out.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.2.3
| Drupal version? | 7.67
| PHP version     | 5.6.40
| OS?             | Linux

**Additional information**
None.

**Comment by weitzman** [comment]
I'm not sure either. The annotation suggests that --create-db is not a public API so you are better off doing that part outside of Drush. drush sql:create may or may not be helpful for you.
