### ISSUE TITLE
Running sql-drop fails when a database view exists

### ISSUE THREAD

**Issue by edaemon** [drush-ops/drush#4236]
**Describe the bug**
Running `drush sql:drop` fails when a view exists in a MySQL database. Instead it throws a generic error:

```
  [Exception]
  Unable to drop database. Rerun with --debug to see any error message.
```

**To Reproduce**
Add a view in the database and run `drush -y sql:drop`.

**Expected behavior**
All tables and views would be dropped.

**Actual behavior**
All tables are dropped, but views remain and the command exits with an error.

**Workaround**
It's simple enough to manually drop the views with `DROP VIEW ...`. The views can be retrieved with `SHOW FULL TABLES WHERE TABLE_TYPE = 'VIEW'`.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.7.1
| Drupal version? | 8.7.8
| PHP version     | 7.2
| OS?             | Linux

**Additional information**
I think this is likely due to the use of `SHOW TABLES` to get the list of tables to drop. `SHOW TABLES` returns [both views and tables](https://dev.mysql.com/doc/refman/8.0/en/show-tables.html). Those results seem to be passed to subsequent `DROP TABLE` queries, e.g.:

```
 [info] sql:query: SHOW TABLES; [2.14 sec, 12.28 MB]
 [info] Executing: mysql --defaults-file=/tmp/drush_sPuIqg --database=example --host=localhost --port=3306 --silent -A < /tmp/drush_vTJNHC [2.14 sec, 12.28 MB]
 [info] sql:query: DROP TABLE example_view [2.18 sec, 12.28 MB]
 [info] Executing: mysql --defaults-file=/tmp/drush_i1RB3x --database=example --host=localhost --port=3306 --silent -A < /tmp/drush_DQ77eU [2.18 sec, 12.28 MB]
```

Running that in isolation throws:

```
ERROR 1965 (42S02): 'example_view' is a view
```

**Comment by weitzman** [comment]
Dropping anything other than tables is out of scope for sql:drop.
