### ISSUE TITLE
Could someone share how to determine if current context is drush invocation 

### ISSUE THREAD

**Issue by sodacrackers** [drush-ops/drush#4241]
**Existing document**
http://docs.drush.org/en/master/
https://www.drush.org/api/master/

**What are you attempting to do**
I wish to determine if the operation for a node update was called by Drush instead of front-end Drupal U/I. 

**What should the documentation say instead?**
How to identify drush commands in a module. 
We are needing the `drush` command and arguments (**and ideally a drush batch id**) to append a log field. 

These don't seem to identify if the update was invoked by drush when used in `hook_node_presave` : ```

    if (PHP_SAPI === 'cli') {
      $log_message .= ' at PHP_SAPI ' . join(',', $_SERVER['argc']);
    }
    
    if (function_exists('drush_print')) {
      drush_print(json_encode($_SERVER['argc']));
    }

```

**Comment by weitzman** [comment]
PHP_SAPI is indeed the most common way to do it.
