### ISSUE TITLE
drush pm:security backend will result no data and error_status =1

### ISSUE THREAD

**Issue by zomorod** [drush-ops/drush#4242]
The following command will return error_status":1 for backend on Drush 9.6 and above:
```
$ drush pm:security --format=json --local=1 --uri=default --backend=1 
```
**To Reproduce**
```
$ drush pm:security --format=json --local=1 --uri=default --backend=1
```

**Expected behavior**
What did you expect would happen?
Expected to see information in the following:
```
DRUSH_BACKEND_OUTPUT_START>>>{"output":"","object":{"drupal\/core":{"name":"drupal\/core","version":"8.7.2","min-version":"8.7.5"},"drupal\/metatag":{"name":"drupal\/metatag","version":"1.8.0","min-version":"1.9"}},"error_status":0,
```
But I got the following:
```
DRUSH_BACKEND_OUTPUT_START>>>{"output":"","object":[],"error_status":1,
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.6.2 and above.
| Drupal version? | 8.x
| PHP version     | 7.1
| OS?             | Linux

**Comment by weitzman** [comment]
Why are you passing --backend? Can you say more about what you are trying to do?

**Comment by zomorod** [comment]
@weitzman We have an automation that is relying on drush backend information.

**Comment by weitzman** [comment]
please run without --backend so you can see what that error message is. consider adding -v for more output.

**Comment by zomorod** [comment]
There is no error that was the reason I filed this thick as a bug when using --backend.

```
$ drush pm:security --format=json --local=1 --uri=default -v
 [warning] One or more of your dependencies has an outstanding security update. Please apply update(s) immediately.
 [notice] Try running: composer require drupal/core:^8.7.5 drupal/metatag:^1.9 --update-with-dependencies
 [notice] If that fails due to a conflict then you must update one or more root dependencies.
{
    "drupal/core": {
        "name": "drupal/core",
        "version": "8.7.2",
        "min-version": "8.7.5"
    },
    "drupal/metatag": {
        "name": "drupal/metatag",
        "version": "1.8.0",
        "min-version": "1.9"
    }
}``

**Comment by weitzman** [comment]
thanks, now i understand. --backend isn't supported in modern drush (9.7 or 10). i suggest removing it.

**Comment by zomorod** [comment]
It does not work on Drush 9.6 and above. Works fine with Drush 9.5
