### ISSUE TITLE
site-install doesn't use db connection in settings.php

### ISSUE THREAD

**Issue by danepowell** [drush-ops/drush#4243]
**Describe the bug**
I have my DB settings stored in settings.php like... well, pretty much every Drupal site on the planet :) In Drush 9, I could run `drush si` and it would install to whichever default db was configured via settings.php. In Drush 10, it seems to ignore these settings. If I pass no other parameters, it prompts for db connection info. If I pass `--no-interaction`, the install fails with `Failed to drop or create the database`

**To Reproduce**
Take an existing site with a default db defined in settings.php, upgrade to Drush 10, try running `drush si`.

**Expected behavior**
Site to be installed according to default db connection in settings.php.

**Actual behavior**
Drush seems to ignore the default db info. It prompts for db connection info, and provides inappropriate defaults (drupal/drupal/drupal) that don't match my configured db settings.

**Workaround**
Manually pass the db URL or fill in the prompts when running `drush si`

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.x
| Drupal version? | 8.7.8
| PHP version     | 7.x
| OS?             | Linux

**Comment by weitzman** [comment]
My bad. Broken in #4230. As a workaround, you can pass --db-url if you have it. I'll get a fix out soon.

**Comment by weitzman** [comment]
Fixed in https://github.com/drush-ops/drush/pull/4244/files. Please confirm if possible.

**Comment by danepowell** [comment]
Thanks a lot for the quick response. I've tested and confirmed that #4244 fixes this.
