### ISSUE TITLE
Drush generate content entity with revisions does not provide UI

### ISSUE THREAD

**Issue by lkacenja** [drush-ops/drush#4252]
**Is your feature request related to a problem? Please describe.**
When I generate a content entity with revisions (`drush generate module-content-entity`), the UI for managing revisions is not created.

**Describe the solution you'd like**
When I generate a content entity with revisions, the ui for managing revisions is created. We should handle creating the revisions UI like other revisionable core content entities (Node). We will need to create the Controller, Forms, Permissions, Route definitions and Local Tasks.

Here are some example required assets:
* [node.links.task.yml](https://git.drupalcode.org/project/drupal/blob/8.8.x/core/modules/node/node.links.task.yml#L14)
* [node.routing.yml](https://git.drupalcode.org/project/drupal/blob/8.8.x/core/modules/node/node.routing.yml#L53)
* [node.permissions.yml](https://git.drupalcode.org/project/drupal/blob/8.8.x/core/modules/node/node.permissions.yml#L17)
* [NodeController.php](https://git.drupalcode.org/project/drupal/blob/8.8.x/core/modules/node/src/Controller/NodeController.php)
* [NodeRevisionRevertForm.php](https://git.drupalcode.org/project/drupal/blob/8.8.x/core/modules/node/src/Form/NodeRevisionRevertForm.php)
* [NodeRevisionRevertTranslationForm.php](https://git.drupalcode.org/project/drupal/blob/8.8.x/core/modules/node/src/Form/NodeRevisionRevertTranslationForm.php)
* [NodeRevisionDeleteForm.php](https://git.drupalcode.org/project/drupal/blob/8.8.x/core/modules/node/src/Form/NodeRevisionDeleteForm.php)

**Describe alternatives you've considered**
It is possible to create the UI by hand, but is pretty laborious.

**Additional context**
Translation may add some additional complexity here. It seems like Node's revision controller is pretty language reliant.

**Comment by weitzman** [comment]
Please pursue this in [Drupal Code Generator repo](https://github.com/Chi-teck/drupal-code-generator), as it maintains the generate code. 

Also would be good if folks move along https://www.drupal.org/project/drupal/issues/2350939
