### ISSUE TITLE
Remove usage of entity.manager service as it has been removed in Drupal 9

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#4254]
`drush site:install` command fails with the following message.
The service "sanitize.userfields.commands" has a dependency on a non-existent service "entity.manager". 

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.x
| Drupal version? | 9.x
| PHP version     | 7.3
| OS?             | Linux

**Additional information**
I think it needs to be replaced with `entity_field.manager`.

**Comment by weitzman** [comment]
Any idea why tests are passing with Drupal 9? https://circleci.com/gh/drush-ops/drush/9789

**Comment by Chi-teck** [comment]
That services has been removed from core just three days ago.
https://www.drupal.org/node/3087546

I think that build used outdated `drupal/core` version because Composer did not pull the last commit from the branch when a package is required as `dev-branch`.
https://github.com/composer/composer/issues/563

However, the most recent build failed.
https://circleci.com/gh/drush-ops/drush/9805

**Comment by iVegas** [comment]
Looks like this requires break changes for command definition: https://github.com/drush-ops/drush/compare/master...iVegas:patch-1
