### ISSUE TITLE
Insufficient Error messages on failing SQL commands with MySQL 8

### ISSUE THREAD

**Issue by vierlex** [drush-ops/drush#4256]
**Describe the bug**
executing drush sql:create --debug --verbose results in a generic error
without any detailed explanation on why it failed.

**To Reproduce**
I use docksal environment https://docksal.io/ and their mysql 8.0 image.
The Drupal setup is based on this https://github.com/thunder/thunder-project
Setup your environment and try a site-install (what i did first)
or the sql:create above.

**Expected behavior**
For the DB to be created / A decent Error message.

**Actual behavior**
No DB created / Empty Error message.

Output from site-install 9.x or 10.x

```
fin drush si thunder --site-name="bla.com" --root="/var/www/web" -y --verbose
 [info] Executing: command -v mysql
 [info] Executing: mysql --defaults-file=/tmp/drush_XPGhzJ --database=drupal --host=db --port=3306 --silent -A < /tmp/drush_GN1hse

 // You are about to CREATE the 'drupal' database. Do you want to continue?: yes.                                       

 [info] Sites directory sites/default already exists - proceeding.
 [info] Executing: mysql --defaults-file=/tmp/drush_PyGhTJ --database=drupal --host=db --port=3306 --silent -A < /tmp/drush_841fJe
 [info] Executing: mysql --defaults-file=/tmp/drush_nXvZiK --database=information_schema --host=db --port=3306 --silent -A < /tmp/drush_EQl65e

In SiteInstallCommands.php line 367:
                                          
  [Exception]                             
  Failed to drop or create the database:  
                                          

Exception trace:
  at /var/www/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php:367
 Drush\Commands\core\SiteInstallCommands->pre() at /var/www/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php:43
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->callValidator() at /var/www/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php:27
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->validate() at /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php:195
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php:176
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /var/www/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:302
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /var/www/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/vendor/symfony/console/Application.php:1000
 Symfony\Component\Console\Application->doRunCommand() at /var/www/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /var/www/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/vendor/drush/drush/src/Runtime/Runtime.php:118
 Drush\Runtime\Runtime->doRun() at /var/www/vendor/drush/drush/src/Runtime/Runtime.php:49
 Drush\Runtime\Runtime->run() at /var/www/vendor/drush/drush/drush.php:72
 require() at /var/www/vendor/drush/drush/includes/preflight.inc:18
 drush_main() at phar:///usr/local/bin/drush/bin/drush.php:141
 require() at /usr/local/bin/drush:10

site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--xh-link XH-LINK] [--notify [NOTIFY]] [--druplicon] [--] <command> [<profile>]...
```

**Workaround**
I debugged until I got into Drush\Sql\SqlBase::alwaysQuery():350
where I output the actual error message:
>         $process = Drush::shell($exec, null, $this->getEnv());
>         $process->setSimulated(false);
>         $process->setVerbose(TRUE);
>         $process->run();
>         $success = $process->isSuccessful();
>         echo $process->getOutput() . '!';
>         echo $process->getExitCode() . '!!';
>         echo $process->getErrorOutput() . '!!!';
>         echo $process->getIncrementalErrorOutput() . '!!!!';
>         echo $process->getExitCodeText() . '!!!!!!';

which gave me this

> !
> 1!!
> ERROR 1045 (28000): Plugin caching_sha2_password could not be loaded: /usr/lib/x86_64-linux-gnu/mariadb19/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory!!!
> ERROR 1045 (28000): Plugin caching_sha2_password could not be loaded: /usr/lib/x86_64-linux-gnu/mariadb19/plugin/caching_sha2_password.so: cannot open shared object file: No such > file or directory!!!!
> General error!!!!!! 

With this info I could find a solution
Setting default_authentication_plugin = mysql_native_password in a mysqld.conf avoids this problem for now (a bit related https://www.drupal.org/project/drupal/issues/2966523)

But led to another Problem, not concerning drush (I hope)
(ERROR 1044 (42000): Access denied for user 'user'@'%' to database 'drupal')

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.7.1 & 10.0.2
| Drupal version? | 8.7.9
| PHP version     | 7.3
| OS?             | Linux

**Additional information**

**Comment by weitzman** [comment]
1. Will be fixed by #4269
2. The perms problem is being tracked at #4098

Thanks for reporting this issue.
