### ISSUE TITLE
Drush blocks ecosystem with Composer

### ISSUE THREAD

**Issue by RorschachRev** [drush-ops/drush#4258]
Composer is for new site only. If you have drupal installed, there is no way to use Migrate, Drush or a lot of other ecosystem components. Drush has decided to block existing Drupal users from having Migrate or other commands.

I don't think Drush team should have the authority to block commands from existing sites. What is the workaround for running Migrate without Drush?

**Comment by weitzman** [comment]
You can use migrate web UI. 

Also, almost none of what you claim is accurate.

**Comment by RorschachRev** [comment]
https://docs.drush.org/en/8.x/install/#drupal-compatibility Drush 8 fails build tests. Our paid license copy of a Drupal installation is not Composer based.

**Comment by RorschachRev** [comment]
I believe your claim that the documentation isn't accurate, but that doesn't tell users how to proceed. The documentation lists a catch-22 from which there is no escape or alternate path.
