### ISSUE TITLE
Windows 10 drush problem

### ISSUE THREAD

**Issue by fr00kt** [drush-ops/drush#4260]
I have Windows 10 Pro, Docker Desktop, docker4drupal (https://github.com/wodby/docker4drupal), drupal composer project (https://github.com/drupal-composer/drupal-project) installed.
How do I configure Windows to work with drush?
All my attempts to perform "drush cex" will result in an error.
Is it possible to use it through Powershell?

**Comment by weitzman** [comment]
Please use Drupal Answers for support questions.
