### ISSUE TITLE
If verbose output is enabled, log each hook_cron instance (8.x)

### ISSUE THREAD

**Issue by damienmckenna** [drush-ops/drush#4263]
In Drupal 8 when cron runs it logs a separate message for each hook_cron implementation. In Drupal 7 it only logs one message after each log item finishes. On occasions when cron goes belly up this makes it notably harder to debug the problem.

Add an option on the 'cron' command that if the -v option is passed in it logs every instance of hook_cron that is triggered.

**Comment by weitzman** [comment]
That would be a feature request for your cron service. We delegate everthing to that. See https://github.com/drush-ops/drush/blob/e2e26c18ae74a0f0ac186d8bd9179215ec47b36d/src/Drupal/Commands/core/DrupalCommands.php#L59

**Comment by damienmckenna** [comment]
Sorry I wasn't clear, this is for the 8.x branch.

I'll have a PR for this tomorrow.

**Comment by damienmckenna** [comment]
In D7 Drush defers to drupal_cron_run().

There's a core issue for something like this: https://www.drupal.org/project/drupal/issues/2560361
