### ISSUE TITLE
Drush 9 Alias and virtualhost

### ISSUE THREAD

**Issue by webmasterpf** [drush-ops/drush#4265]
**Describe the bug**
I would to set aliases to manage my local websites on a LAMP server (running in VM) and set by virtualhost

**To Reproduce**
Created a file with informations as required, like this:
```
  host: 10.100.3.XX
  user: USERNAME
  root: /var/www/drupal-8/
  uri: 'http://d8-le-rocher.vmdev/'
```
Thanks for help.Alias work for my remote hosted.

**Expected behavior**
Running drush commands

**Actual behavior**
```
ssh: Could not resolve hostname 10.100.3.XX:22: Name or service not known
In Process.php line 235:
  The command "ssh -t -o PasswordAuthentication=no webmaster@10.100.3.xx:22 'drush pml --filter=rule --uri=http://d8-le-rocher.vmdev/ --root=/var/www/drupal-8/'" failed.
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.1.7
| Drupal version? | 8.7.10
| PHP version     | 7.2
| OS?             | Linux (VM)/Windows(client)

**Comment by greg-1-anderson** [comment]
See [site-process](https://github.com/consolidation/site-process) for documentation. Please ask for support on Drupal Answers if anything there is unclear. Pull requests to make the documentation clearer would also be appreciated.
