### ISSUE TITLE
Running global drush 8 when project has drush 10 installed via composer

### ISSUE THREAD

**Issue by 2art** [drush-ops/drush#4266]
Hey,

I have been using drush 8 (currently 8.3.2), and just recently installed drush in my project with Composer. Project version is 10.0.2. I like drush 10 otherwise, but some commands seem to be removed or changed so that I cant find them. One example is config list (cli).

The problem is, I can't use drush 8 in my project anymore after installing drush via composer. Running drush 8 just launches the project version of drush instead: drush --version in any other directory gives 8.3.2, but inside the project I get 10.0.2.

How can I run commands from drush 8 inside this project? Or do I need to just uninstall the composer version?

Thanks

**Comment by weitzman** [comment]
What commands are missing?

 Note that you can't use pm commands when you have a composer built site. 

And yes you need to remove the drush 10 via composer in order to use drush 8

**Comment by 2art** [comment]
At least cli (config-list), I use it regularly to do batch operations on some configs. I think there was some other command but I can't find it now.

I was able to make drush 8 work by moving vendor/drush somewhere else temporarily, and so a small macro that moves it out, run the command, and move drush back in. It's a little weird to do, but I guess if it works, it works. I'm sure there is a reason for blocking older versions of drush.

Thanks for the answer.
