### ISSUE TITLE
As of Drupal 8.8.0 released on Dec. 4th, 2019, the recommended composer template file has changed

### ISSUE THREAD

**Issue by alberto56** [drush-ops/drush#4275]
**Existing document**
The [installation instructions for Drush](https://docs.drush.org/en/master/install/) currently state:

> It is recommended that Drupal sites be [built using Composer, with Drush listed as a dependency](https://github.com/drupal-composer/drupal-project). 

The linked template is https://github.com/drupal-composer/drupal-project.

However on the [Drupal installation documentation](https://www.drupal.org/docs/develop/using-composer/using-composer-to-install-drupal-and-manage-dependencies), it state:

> As of the release of Drupal 8.8.0 - the recommend composer template changed to from drupal-composer/drupal-project to the officially supported: drupal/recommended-project

**What are you attempting to do**
It is not clear whether Drush recommends using drupal-composer/drupal-project (which contains Drush as a dependency) or [drupal/recommended-project](https://github.com/drupal/recommended-project) (which does not).

**In what way is the existing documentation unclear or incomplete**
The existing document does not clearly indicate that there is a difference between versions of Drupal prior to 8.8.0 and Drupal 8.8.0 and above.

**What should the documentation say instead?**
Something like : "For Drupal 8.8.0 and above, install Drush using the composer file at [drupal/recommended-project](https://github.com/drupal/recommended-project) and by modifying it so that ..." (not sure how).

**Comment by alberto56** [comment]
One specific problem I've encountered is:

    Package drush/drush at version ~10 has a PHP requirement incompatible with your PHP version (7.0.8) 

Even though my system php is 7.3.12

    php -v
    PHP 7.3.12 (cli) (built: Nov 22 2019 16:56:59) ( NTS )
    Copyright (c) 1997-2018 The PHP Group
    Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies
        with Zend OPcache v7.3.12, Copyright (c) 1999-2018, by Zend Technologies

Perhaps related to [this line](https://github.com/drupal/recommended-project/blob/a4b452a3ff2d9d72902f7bbe906a3f4202c0d752/composer.json#L34).

**Comment by weitzman** [comment]
That line got removed.

I guess we'll need to expand drush install instructions for `drupal/recommended-project` users.
