### ISSUE TITLE
Using environment variables in the aliases yml

### ISSUE THREAD

**Issue by divined** [drush-ops/drush#4282]
**Describe the bug**
Added environment variable to example.site.yml doesn't work
Documentation: https://raw.githubusercontent.com/drush-ops/drush/master/examples/example.site.yml

**To Reproduce**
user: '${env.PROJECT_SSH_USER}'

.env:
PROJECT_SSH_USER=username

**Expected behavior**
${env.PROJECT_SSH_USER} will be replaced with the "username"

**Actual behavior**
I see ${env.PROJECT_SSH_USER} in the connection ssh string, and error as a result

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.4
| Drupal version? | 8.6
| PHP version     | 7.2
| OS?             | Linux, Docker

**Comment by greg-1-anderson** [comment]
Drush does not support reading environment variables from the .env file. Define your variables in the environment, and it should work.

**Comment by greg-1-anderson** [comment]
Maybe Drush Launcher supports .env files?

**Comment by weitzman** [comment]
No, launcher does not load them either.

Its possible that this feature was added after drush 9.4. Please retry with latest version.

**Comment by divined** [comment]
Ty, I've just added 
env_file: ./.env
to my docker-composer and it works.

**Comment by divined** [comment]
> Drush does not support reading environment variables from the .env file. Define your variables in the environment, and it should work.

Username it is dynamic value, each user in the company has own ))
We can't use it in the environment section )
