### ISSUE TITLE
drush status, does not show "Connected" when it can actually connect

### ISSUE THREAD

**Issue by simesy** [drush-ops/drush#4283]
`drush status db-status` does not show "Connected" when it can connect to the database, if the site is broken in a certain ways. I'm not sure if this is a bug, or needs fixing, but it was interesting and i wanted to report it. I have always read "Connected" to mean "can connect", and during Drush status db-status I would expect drush to try to connect.

**To Reproduce**
```
$ drush si minimal --yes

$ drush status db-status
  Database : Connected

$ drush sqlq "drop table key_value"

$ drush status db-status
  (no output)

$ drush sqlq "show tables"
  cache_bootstrap
  cache_config
  cache_container
  cache_default
  cache_discovery
   ...
```

**Expected behavior**
Drush status should show "Connected" when it can connect to the database.

**Actual behavior**
Drush status did not show connected when i broken the site in a certain way, but I could still use other drush database commands.

**Workaround**
n/a

### System Configuration
Drush Launcher Version: 0.6.0
Drush Commandline Tool 9.7.1
PHP 7.2.23
drupal/core   8.7.9

**more info**

```
$ drush status # (after I broke it)
 Drupal version : 8.7.9
 Site URI       : http://blah.docker
 DB driver      : mysql
 DB hostname    : mariadb
 DB port        : 3306
 DB username    : drupal
 DB name        : drupal
 PHP binary     : /usr/local/bin/php
 PHP config     : /usr/local/etc/php/php.ini
 PHP OS         : Linux
 Drush script   : /usr/local/bin/drush
 Drush version  : 9.7.1
 Drush temp     : /tmp
 Drush configs  : /home/.drush/drush.yml
                  /app/vendor/drush/drush/drush.yml
                  /app/drush/drush.yml
 Drupal root    : /app/web
 Site path      : sites/default
```

**Comment by weitzman** [comment]
You picked the table that Drush uses when it tries to connect - key_value. Did you look at the code to find that :) ... I'm not too fussed about changing this.

**Comment by simesy** [comment]
That's kinda funny. I was just dropping random important tables, trying to break my site to emulate possible broken states (and decided how to test for them) when i was testing a CI script.

**Comment by simesy** [comment]
I might close this. Everytime i think about what it should do (and edge cases), it feels like overloading the status command.
