### ISSUE TITLE
Keys exposed in travis.yml?

### ISSUE THREAD

**Issue by gondar00** [drush-ops/drush#4286]
**Describe the bug**
Not really sure if its intentional but i noticed the `S3` keys lying around in travis file.

_Ignore if its intentional_

**To Reproduce**
https://github.com/drush-ops/drush/blob/master-fulltest/.travis.yml#L76

**Comment by weitzman** [comment]
No worries. Its an excrypted value https://docs.travis-ci.com/user/encryption-keys/
