### ISSUE TITLE
Drush not detecting the field small updates

### ISSUE THREAD

**Issue by nassernak** [drush-ops/drush#4288]
There is a crazy way to detect Drupal changes with Drush rather than normal

**STEPS**

1- update an ECK field

2- run `Drush cim` (will not detect any changes)

3- manually update another config file

4- run `Drush cim` (will detect just the manual changes not field changes)

5- continue and import the manual changes

6- try again with `Drush cim` (This time it will detect the changes)

I know the usage of Drush, but recently I faced with this issue and couldn't find the solution yet.

**Here is an image that shows the process that I did, before that I just make a field required(changed to required)**

[![enter image description here][1]][1]
>Drush status result
```
Drupal version   : 8.7.1
Site URI         : http://default
DB driver        : mysql
DB hostname      : localhost
DB port          : 3306
DB username      : root
DB name          : dev_amt_dp
Database         : Connected
Drupal bootstrap : Successful
Default theme    : amt
Admin theme      : seven
PHP binary       : C:\wamp64\bin\php\php7.2.18\php.exe
PHP config       : C:\wamp64\bin\php\php7.2.18\php.ini
PHP OS           : WINNT
Drush script     : C:\xampp\htdocs\amt-drupal\docroot\vendor\drush\drush\drush
Drush version    : 9.7.1
Drush temp       : C:\Users\PC001~1\AppData\Local\Temp
Drush configs    : C:/xampp/htdocs/amt-drupal/docroot/vendor/drush/drush/drush.yml
Install profile  : standard
Drupal root      : C:\xampp\htdocs\amt-drupal\docroot
Site path        : sites/default
Files, Public    : sites/default/files
Files, Private   : sites/default/private
Files, Temp      : /tmp
```

  [1]: https://i.stack.imgur.com/kywqh.png

**Comment by weitzman** [comment]
Entity updates no longer run by default. See https://www.drupal.org/project/devel_entity_updates

**Comment by nassernak** [comment]
@weitzman how it relevant to Drush?
I try with the same environment, and as I mentioned just after another import, I can import my main (remaining) changes
