### ISSUE TITLE
How can I use a composer symlinked package which contains custom commands?

### ISSUE THREAD

**Issue by nvaken** [drush-ops/drush#4290]
**Describe the bug**
When using a Composer repository of type `path` to symlink a local package, Drush will not pick up it's custom commands. 

**To Reproduce**
Create a local Composer package, add the `path` repository to your project and require the package and make sure it is being symlinked (not mirrored).

**Expected behavior**
Drush picking up the package.

**Actual behavior**
Drush ignores symlinked package.

**Workaround**
Yes, somewhat. I've found that when removing the if statement in the dependency `consolidation/annotated-command`  in file `src/CommandFileDiscovery.php` on line `402` my package is being picked up. This makes somewhat sense, since `followLinks` is `false` by default. Is drush able to set `followLinks` to `true`? 

**Edit**: Even better workaround seems to be to add `->followLinks(TRUE)` in Drush's: `/src/Application.php` in `commandDiscovery()` where `CommandFileDiscovery` is being instantiated. Is that maybe a acceptable permanent fix?

**Comment by weitzman** [comment]
I don't think we want to follow symlinks. We used to do that and it caused as many problems as it helped. Maybe @greg-1-anderson has input on this ... The workaround is to add new paths for discovery https://github.com/drush-ops/drush/blob/master/examples/example.drush.yml#L52-L67

**Comment by nvaken** [comment]
Would it then be an idea to make following symlinks optional? I'd love to be able to just install composer packages as if it was a normal package while still developing. This way I'll be sure that the package has been installed in the correct path etc...

**Comment by greg-1-anderson** [comment]
I am ambivalent on adding configuration to follow symlinks in the general case. Configuring paths for discovery seems better. Is it really necessary to follow symlinks for module Drush commands, though? It seems that we should be able to find a module wherever it is through service discovery, and the command classes should be defined in the drush.services.yml file.

If more code is needed to make module Drush services / commandfiles discoverable for path repositories, I'd be in favor of a targeted PR that did that. (By targeted, I mean code that specifically identifies and finds modules relocated via a path repository rather than just turning on symlinks for all searching.)

The flip side of symlink following, though, is that Drush had tons of problems with this because in the old days, Drush often walked up to parent directories for the various locations it found. If we are sure that the scenarios that we are enabling symlink following for never does that, then we could consider allowing that, I guess.

**Comment by nvaken** [comment]
> Is it really necessary to follow symlinks for module Drush commands, though? It seems that we should be able to find a module wherever it is through service discovery, and the command classes should be defined in the drush.services.yml file.

I'm not sure, though I am sure that `CommandFileDiscovery` does not allow for following symlinks by default. This makes developing composer packages a bit cumbersome if you (arguably) want to make sure you're Composer package is loaded in the right composer-spot (`/drush/Commands/contrib/[package]`). Our package will sit in that spot (when released) in our 80+ Drupal projects. 

Also, I'm unable to assess the problems that Drush will have when symlinks are being followed as I'm not known with the problems that arose earlier.  Though, when it still defaults to not following and making it optional to follow... I guess that puts that responsibility into the user's hands?

**Comment by greg-1-anderson** [comment]
Sounds like you are writing a site-wide Drush command, not a module command. See https://github.com/drush-ops/example-drush-extension for this. Perhaps you can develop and test as shown in that repository, which uses Drush path configuration to discover the system under test.

**Comment by nvaken** [comment]
Yeah, I guess that's the same workaround that @weitzman suggested above, though if I'm correct, that's without testing the package in the eventual place in which it will be placed. But, as this issue progresses, I'm starting to wonder if it is just too much hassle for what it's worth. Like you guys say; you can configure alternate discovery paths, at the end of development we'll just test it as a composer package in the `/drush/Commands/contrib/` folder. 

P.s. would it be possible to make an annotation about Drush not being able to pick up symlinked packages on the [Command Authoring page](https://docs.drush.org/en/master/commands/)? That would have saved me a few hours of fiddling around.

**Comment by weitzman** [comment]
Sure. Please submit a PR for that the bottom of that page (in /docs directory). Or to https://github.com/drush-ops/example-drush-extension

**Comment by nvaken** [comment]
Was working for a while on my new package, putting it into `/projectroot/drush/Commands/mypackage/` so it would get picked up, worked like a charm. Though now I'm about to add classes to my `/mypackage/src/` folder, which made me realise that this ain't gonna work since classes will (obviously) not be autoloaded by composer this way. So I'm back to square one and for now, I'm just gonna try using my aforementioned workaround: 

> Even better workaround seems to be to add ->followLinks(TRUE) in Drush's: /src/Application.php in commandDiscovery() where CommandFileDiscovery is being instantiated. Is that maybe a acceptable permanent fix?

I'm still not charmed by this DX though...

**Comment by jonpugh** [comment]
I have created a monorepo with a drush project inside of it, and am using composer "path" repositories to setup a symlink to it so that I can develop the whole project at once.

This renders my command missing.

I guess I can set this with drush.yml anyway.

🤷🏻

**Comment by jonpugh** [comment]
Couldn't actually get that to work. Very odd. 

Still, would be nice if Drush worked with command folders being symlinks. Composer autoloader doesn't seem to care.
