### ISSUE TITLE
Drush 10 phar

### ISSUE THREAD

**Issue by awwright** [drush-ops/drush#4291]
**Is your feature request related to a problem? Please describe.**
I'm trying to perform a Drupal 7->8.8 upgrade with Drush. As noted in the documentation, Drupal 8.4+ requires Drush 10. I was using the Drush 8 phar which is very convenient, but an equivelant does not seem to exist for Drush 10. My system does not have composer, and I'm at a loss how to run Drush now.

**Describe the solution you'd like**
A phar release of Drush 10.

**Describe alternatives you've considered**
The tar.gz download seems to include an executable, but this doesn't seem to do anything, and actually gives a very unhelpful error message:

```
$ php ./drush-10.1.1/drush.php 

Fatal error: Uncaught Error: Class 'Drush\Config\Environment' not found in ./drush-10.1.1/drush.php:62
Stack trace:
#0 {main}
  thrown in ./drush-10.1.1/drush.php on line 62
```
PHP version is 7.3.9.

**Additional context**
A phar would also be very useful for distributing drush on package managers. For example:

* https://packages.debian.org/jessie/drush
* https://phar.io/
* https://packages.gentoo.org/packages/app-admin/drush

These are out of date or missing releases because there doesn't seem to be an easy way to install Drush anymore.

**Comment by weitzman** [comment]
See Drush's install instructions. You need Composer. That wont be changing.

**Comment by awwright** [comment]
@weitzman As I mentioned, Drush's install instructions do not solve this problem. Nor does saying "You need Composer".

I would like to reopen at least until the documentation can help someone with the same question.

**Comment by greg-1-anderson** [comment]
If we were to make a Drush phar, we would need to make one with Symfony 4 for Drupal 9, and one with Symfony 3 for Drupal 8. This is only one potential dependency problem that would arise. Admittedly, saying "you need Composer" is not a solution if you do not have Composer; regrettably, though, that is the solution for Drush 10.

You could try the Drush 8 phar; however, that version of Drush is not recommended, and supported on a best-effort basis only. It was working for 8.8.x and 9.0.x at DrupalCon Amsterdam, and might still be working. This, of course, will not help you if you need Drush extensions provided by modules that do not support Drush 8, but it might help you with some things. Note also that you cannot use a Drush phar if you have installed a site-local Drush using Composer.
