### ISSUE TITLE
Drupal 8.8 deprecated CONFIG_SYNC_DIRECTORY

### ISSUE THREAD

**Issue by mmoulton** [drush-ops/drush#4293]
**Describe the bug**
I'm trying to use Drush 10 with Drupal 8.8's new config transform features. While investigating some strange behavior with `drush config:import` being able to find my custom sync directory I noticed that as of Drush 10.1.1, you are still using the now defunct `config_get_config_directory(CONFIG_SYNC_DIRECTORY)`. See: https://www.drupal.org/node/3018145

**Expected behavior**
I would expect an execution of `drush config:import` to find my custom config dir configured with `$settings['config_sync_directory'] = 'some/path'` to be used as the source of the import.

I think some refactoring might need to be done to remove labels and change to the recommended `Settings::get('config_sync_directory')` as config importing no longer supports multiple locations.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.1.1
| Drupal version? | 8.8
| PHP version     | 7.3
| OS?             | Mac

**Additional information**

**Comment by jinjin123** [comment]
seems  drush version issue... I use drupal 8.9 and drupal 9.0.6, just update drush to 10.0.6 everything was fine .
