### ISSUE TITLE
Drush 9: drush_get_option / drush_get_context

### ISSUE THREAD

**Issue by njt1982** [drush-ops/drush#4296]
**Existing document**

https://github.com/drush-ops/drush/blob/36c2dd7d7921938834e47c34c5cbf3ea139c2f01/includes/drush.inc#L99-L100

**What are you attempting to do**

I dont seem to see any reference to dush_get_context (or drush_get_option for that matter) in the code? Is this still correct?

**Comment by greg-1-anderson** [comment]
`drush_get_context` and `drush_get_option` were deprecated in Drush 9 and removed in Drush 10.

For an example of how to write a Drush extension that only uses APIs that work in Drush 8, 9 and 10, see https://github.com/drush-ops/example-drush-extension

**Comment by njt1982** [comment]
Hi @greg-1-anderson  - Thank you for the response :)

So the context here is that for the command `drush migrate:import` there is an `--idlist` option and this gets handled by the MigrateExecutable... however I wanted to be able to find out the values in my MigrateSource class (so in the SQL I could easily filter for just the IDs I want to migrate, rather than skipping tens of thousands of rows ;) ).

In older Drush, I could easily have got to the context to find the options by using those global methods... but if they have been remove,  I was hoping they would have been replaced?

So I wasn't hoping to write my own command, but rather have some code on my class which could inspect the drush options being used.

Currently I've "hacked" around this by accessing `$_SERVER['argv']` and looping for `--idlist` in the array of strings, then manually parsing it.

**Comment by greg-1-anderson** [comment]
The right answer here is that the Migrate module should make the id list available to the migrate source class.

In absence of that, if you wanted to "cheat", you could use the `\Drush\Drush::input()` method to get a reference to the Symfony Console input interface. Then you could ask for the id list directly. However, this is not recommended, and it might not work in future versions of Drush. I'm not sure if this works in Drush 8 either, so in the balance, maybe looking at argv directly might not be any worse than any of your other options.

**Comment by njt1982** [comment]
Ah fab. Thank you so much for the pointers!

**Comment by maxie7** [comment]
So, how could I substitute drush_get_option() ?!
For example I have something like this in Drupal 8.9:
```
 if (drush_get_option('update')) {
 ...
}
```
 and I want to migrate to Drupal 9. I've searched over the tones of articles (including api drupal) and there's no clear answer or code example!!! And I have ~ 40 usages of drush_get_option(), how can I substitute them in order not destroy my project

**Comment by weitzman** [comment]
> use the \Drush\Drush::input() method to get a reference to the Symfony Console input interface. Then you could ask for the id list directly. 

Do that, or get it from $_SERVER['argv']

**Comment by maxie7** [comment]
```
if (Drush::input('update')) {
    $update = TRUE;
    ...
}
```
@weitzman , thanks a lot!!! The first way works perfect

**Comment by paulostarling** [comment]
Hi everyone. 
How can I replace `$this->drush_get_context('DRUSH_DRUPAL_ROOT');`?
Sorry, I did not find any example on internet.

**Comment by VeyJulien** [comment]
For people still wondering : replace it with `Drush::bootstrapManager()->getRoot();` :)
