### ISSUE TITLE
Drush is unable to determine the mime type of the .sql file during sql-query

### ISSUE THREAD

**Issue by naveenvalecha** [drush-ops/drush#4308]
**Describe the bug**
vagrant@local:/var/www/rtdcw$ /usr/local/bin/drush sql-query --strict=0 --file=/tmp/db-dump.sql --uri=default --root=/var/www/rtdcw/docroot -vvv
 [preflight] Config paths: /var/www/rtdcw/vendor/drush/drush/drush.yml,/var/www/rtdcw/drush/drush.yml
 [preflight] Alias paths: /var/www/rtdcw/docroot/drush/sites,/var/www/rtdcw/drush/sites
 [preflight] Commandfile search paths: /var/www/rtdcw/vendor/drush/drush/src,/var/www/rtdcw/drush
 [debug] Starting bootstrap to max [0.48 sec, 8.64 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalRoot() [0.48 sec, 8.64 MB]
 [debug] Change working directory to /var/www/rtdcw/docroot [0.48 sec, 8.64 MB]
 [debug] Initialized Drupal 8.8.1 root directory at /var/www/rtdcw/docroot [0.49 sec, 8.84 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalSite() [0.5 sec, 9.13 MB]
 [debug] Initialized Drupal site default at sites/default [0.51 sec, 9.37 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalConfiguration() [0.51 sec, 9.37 MB]
 [debug] Add service modifier [0.58 sec, 9.63 MB]
 [info] Executing: command -v mysql [0.6 sec, 10.71 MB]
 [debug] Mime type for /tmp/db-dump.sql is application/octet-stream. [0.64 sec, 10.75 MB]
 [debug] Examining /tmp/db-dump.sql headers. [0.65 sec, 10.75 MB]
 [debug] Unable to determine mime type from header bytes 0x2d2d of /tmp/db-dump.sql. [0.65 sec, 10.75 MB]
 [debug] Examining /tmp/db-dump.sql extension. [0.65 sec, 10.75 MB]
 [info] Executing: mysql --defaults-file=/tmp/drush_4BDmWJ --database=drupal --host=localhost --port=3306 --silent -A < /tmp/db-dump.sql [0.65 sec, 10.75 MB]

In SqlCommands.php line 201:
                 
  [Exception]    
  Query failed.  
                 

Exception trace:
  at /var/www/rtdcw/vendor/drush/drush/src/Commands/sql/SqlCommands.php:201
 Drush\Commands\sql\SqlCommands->query() at n/a:n/a
 call_user_func_array() at /var/www/rtdcw/vendor/consolidation/annotated-command/src/CommandProcessor.php:257
 Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() at /var/www/rtdcw/vendor/consolidation/annotated-command/src/CommandProcessor.php:212
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /var/www/rtdcw/vendor/consolidation/annotated-command/src/CommandProcessor.php:176
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /var/www/rtdcw/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:302
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /var/www/rtdcw/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/rtdcw/vendor/symfony/console/Application.php:1000
 Symfony\Component\Console\Application->doRunCommand() at /var/www/rtdcw/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /var/www/rtdcw/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/rtdcw/vendor/drush/drush/src/Runtime/Runtime.php:118
 Drush\Runtime\Runtime->doRun() at /var/www/rtdcw/vendor/drush/drush/src/Runtime/Runtime.php:49
 Drush\Runtime\Runtime->run() at /var/www/rtdcw/vendor/drush/drush/drush.php:72
 require() at /var/www/rtdcw/vendor/drush/drush/includes/preflight.inc:18
 drush_main() at phar:///usr/local/bin/drush/bin/drush.php:141
 require() at /usr/local/bin/drush:10

**To Reproduce**
What did you do?

**Expected behavior**
What did you expect would happen?

**Actual behavior**
It should import the db dump

**Workaround**
Not found any yet

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  |  Drush Launcher Version: 0.6.0  and Drush Commandline Tool 10.2.0
| Drupal version? | 8.8.1
| PHP version     | PHP 7.3.13-1+ubuntu16.04.1+deb.sury.org+1
| OS?             | Linux

**Additional information**

**Comment by naveenvalecha** [comment]
I tried to import the gzip file too but it didn't work too
`vagrant@local:/var/www/rtdcw$ /usr/local/bin/drush sql-query --strict=0 --file=/tmp/tawebsite_20200129_070814.sql.gz --uri=default --root=/var/www/rtdcw/docroot -vvv
 [preflight] Config paths: /var/www/rtdcw/vendor/drush/drush/drush.yml,/var/www/rtdcw/drush/drush.yml
 [preflight] Alias paths: /var/www/rtdcw/docroot/drush/sites,/var/www/rtdcw/drush/sites
 [preflight] Commandfile search paths: /var/www/rtdcw/vendor/drush/drush/src,/var/www/rtdcw/drush
 [debug] Starting bootstrap to max [0.3 sec, 8.64 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalRoot() [0.3 sec, 8.64 MB]
 [debug] Change working directory to /var/www/rtdcw/docroot [0.3 sec, 8.64 MB]
 [debug] Initialized Drupal 8.8.1 root directory at /var/www/rtdcw/docroot [0.31 sec, 8.84 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalSite() [0.32 sec, 9.13 MB]
 [debug] Initialized Drupal site default at sites/default [0.33 sec, 9.37 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalConfiguration() [0.34 sec, 9.37 MB]
 [debug] Add service modifier [0.43 sec, 9.63 MB]
 [info] Executing: command -v mysql [0.45 sec, 10.71 MB]
 [info] Executing: 'gzip' '-df' '/tmp/tawebsite_20200129_070814.sql.gz' [0.47 sec, 10.75 MB]
 [info] Executing: mysql --defaults-file=/tmp/drush_zvpMx8 --database=drupal --host=localhost --port=3306 --silent -A < /tmp/tawebsite_20200129_070814.sql [0.58 sec, 10.76 MB]

In SqlCommands.php line 201:
                 
  [Exception]    
  Query failed.  
                 

Exception trace:
  at /var/www/rtdcw/vendor/drush/drush/src/Commands/sql/SqlCommands.php:201
 Drush\Commands\sql\SqlCommands->query() at n/a:n/a
 call_user_func_array() at /var/www/rtdcw/vendor/consolidation/annotated-command/src/CommandProcessor.php:257
 Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() at /var/www/rtdcw/vendor/consolidation/annotated-command/src/CommandProcessor.php:212
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /var/www/rtdcw/vendor/consolidation/annotated-command/src/CommandProcessor.php:176
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /var/www/rtdcw/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:302
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /var/www/rtdcw/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/rtdcw/vendor/symfony/console/Application.php:1000
 Symfony\Component\Console\Application->doRunCommand() at /var/www/rtdcw/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /var/www/rtdcw/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/rtdcw/vendor/drush/drush/src/Runtime/Runtime.php:118
 Drush\Runtime\Runtime->doRun() at /var/www/rtdcw/vendor/drush/drush/src/Runtime/Runtime.php:49
 Drush\Runtime\Runtime->run() at /var/www/rtdcw/vendor/drush/drush/drush.php:72
 require() at /var/www/rtdcw/vendor/drush/drush/includes/preflight.inc:18
 drush_main() at phar:///usr/local/bin/drush/bin/drush.php:141
 require() at /usr/local/bin/drush:10

sql:query [--result-file [RESULT-FILE]] [--file FILE] [--file-delete] [--extra EXTRA] [--db-prefix] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--database [DATABASE]] [--target [TARGET]] [--db-url DB-URL] [--notify] [--druplicon] [--xh-link XH-LINK] [--] <command> [<query>]`

**Comment by thetwentyseven** [comment]
I have exactly the same issue trying to use "drush sql:sync". The strange thing is, it is working from my-local to live-environment, but not the other way around. Whereas my-local is Arch Linux, my live-environment is CentOS, but both have the same Drupal and Drush version:

```
 Drupal version   : 8.8.1                                    
 Site URI         : http://d8.local                          
 DB driver        : mysql                                    
 DB hostname      : localhost                                
 DB port          : 3306                                     
 DB username      : d8                                    
 DB name          : d8                                    
 Database         : Connected                                
 Drupal bootstrap : Successful                               
 Default theme    : bartik                                   
 Admin theme      : seven                                    
 PHP binary       : /usr/bin/php                             
 PHP config       : /etc/php/php.ini                         
 PHP OS           : Linux                                    
 Drush script     : /usr/local/bin/drush                     
 Drush version    : 10.1.1                                   
 Drush temp       : /tmp                                     
 Drush configs    : /var/www/d8/vendor/drush/drush/drush.yml 
                             /var/www/d8/web/drush/drush.yml          
 Install profile  : standard                                 
 Drupal root      : /var/www/d8/web                          
 Site path        : sites/default                            
 Files, Public    : sites/default/files                      
 Files, Temp      : /tmp   
```
Error with debug and verbose

` [preflight] Config paths: /var/www/d8/vendor/drush/drush/drush.yml,/var/www/d8/web/drush/drush.yml
 [preflight] Alias paths: /var/www/d8/web/drush/sites,/var/www/d8/drush/sites
 [preflight] Commandfile search paths: /var/www/d8/vendor/drush/drush/src,/var/www/d8/web/drush
 [debug] Starting bootstrap to none [0.04 sec, 8.09 MB]
 [debug] Drush bootstrap phase 0 [0.04 sec, 8.09 MB]
 [debug] Try to validate bootstrap phase 0 [0.04 sec, 8.09 MB]
 [info] Executing: ssh -o PasswordAuthentication=no root@********** 'drush core-status --fields=db-name --format=json --uri=http://d8.studentsunionucl.org --root=/var/www/d8/web' [0.04 sec, 8.55 MB]
 [info] Executing: /usr/local/bin/drush core-status --fields=db-name --format=json --uri=http://d8.local --root=/var/www/d8/web [0.56 sec, 8.59 MB]
You will destroy data in su_d8 and replace with data from /su_d8.

 // Do you really want to continue?: yes.                                                                               

 [notice] Starting to dump database on source. [0.75 sec, 8.6 MB]
 [info] Executing: ssh -o PasswordAuthentication=no root@********** 'drush sql-dump --strict=0 --gzip --result-file=auto --format=json --uri=http://d8.studentsunionucl.org --root=/var/www/d8/web' [0.75 sec, 8.6 MB]
 [notice] Starting to discover temporary files directory on target. [1.46 sec, 8.6 MB]
 [info] Executing: /usr/local/bin/drush core-status drush-temp --format=string --uri=http://d8.local --root=/var/www/d8/web [1.46 sec, 8.6 MB]
 [notice] Copying dump file from source to target. [1.61 sec, 8.61 MB]
 [info] Executing: /usr/local/bin/drush core-rsync @d8.test:/root/drush-backups/su_d8/20200211120500/su_d8_20200211_120500.sql.gz @d8.local:/tmp/su_d8_20200211_120500.sql.gz --yes --uri=http://d8.local --root=/var/www/d8/web -- --remove-source-files [1.61 sec, 8.68 MB]

 // Copy new and override existing files at /tmp/su_d8_20200211_120500.sql.gz.  
 // The source is                                                               
 // root@**********:/root/drush-backups/su_d8/20200211120500/su_d8_20200211_1
 // 20500.sql.gz?: yes.                                                         

 [notice] Starting to import dump file onto target database. [1.95 sec, 8.67 MB]
 [info] Executing: /usr/local/bin/drush sql-query --strict=0 --file=/tmp/su_d8_20200211_120500.sql.gz --file-delete --uri=http://d8.local --root=/var/www/d8/web [1.95 sec, 8.67 MB]

In Process.php line 235:
                                                                                                                                                                                                                                             
  [Symfony\Component\Process\Exception\ProcessFailedException]                                                                                                                                                                               
  The command "/usr/local/bin/drush sql-query --strict=0 --file=/tmp/su_d8_20200211_120500.sql.gz --file-delete --uri=http://d8.local --root=/var/www/d8/web" failed.                                                                        
                                                                                                                                                                                                                                             
  Exit Code: 1(General error)                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
  Working directory:                                                                                                                                                                                                                         
                                                                                                                                                                                                                                             
  Output:                                                                                                                                                                                                                                    
  ================                                                                                                                                                                                                                           
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
  Error Output:                                                                                                                                                                                                                              
  ================                                                                                                                                                                                                                           
                                                                                                                                                                                                                                             
  In SqlCommands.php line 201:                                                                                                                                                                                                               
                                                                                                                                                                                                                                             
    Query failed.                                                                                                                                                                                                                            
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
  sql:query [--result-file [RESULT-FILE]] [--file FILE] [--file-delete] [--extra EXTRA] [--db-prefix] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--n  
  o] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--database [DATABASE]] [--target [TARGET]] [--db-url DB-URL] [--notify [NOTIFY]] [--xh-link XH-LIN  
  K] [--druplicon] [--] <command> [<query>]                                                                                                                                                                                                  
                                                                                                                                                                                                                                             

Exception trace:
  at /var/www/d8/vendor/symfony/process/Process.php:235
 Symfony\Component\Process\Process->mustRun() at /var/www/d8/vendor/drush/drush/src/Commands/sql/SqlSyncCommands.php:241
 Drush\Commands\sql\SqlSyncCommands->import() at /var/www/d8/vendor/drush/drush/src/Commands/sql/SqlSyncCommands.php:63
 Drush\Commands\sql\SqlSyncCommands->sqlsync() at n/a:n/a
 call_user_func_array() at /var/www/d8/vendor/consolidation/annotated-command/src/CommandProcessor.php:257
 Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() at /var/www/d8/vendor/consolidation/annotated-command/src/CommandProcessor.php:212
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /var/www/d8/vendor/consolidation/annotated-command/src/CommandProcessor.php:176
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /var/www/d8/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:302
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /var/www/d8/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/d8/vendor/symfony/console/Application.php:1000
 Symfony\Component\Console\Application->doRunCommand() at /var/www/d8/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /var/www/d8/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/d8/vendor/drush/drush/src/Runtime/Runtime.php:118
 Drush\Runtime\Runtime->doRun() at /var/www/d8/vendor/drush/drush/src/Runtime/Runtime.php:49
 Drush\Runtime\Runtime->run() at /var/www/d8/vendor/drush/drush/drush.php:72
 require() at /var/www/d8/vendor/drush/drush/includes/preflight.inc:18
 drush_main() at phar:///usr/local/bin/drush/bin/drush.php:141
 require() at /usr/local/bin/drush:10
`

**Comment by weitzman** [comment]
More info at #4319
