### ISSUE TITLE
drush conf fatals with "call to undefined method Drush\Boot\EmptyBoot::confPath"

### ISSUE THREAD

**Issue by aaronbauman** [drush-ops/drush#4312]
**Describe the bug**
`drush conf` command fatals with `call to undefined method Drush\Boot\EmptyBoot::confPath`

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.x-dev
| Drupal version? | 8.8.1
| PHP version     | 7.x
| OS?             | Linux

Google turns up nothing. Any ideas here?

**Comment by weitzman** [comment]
1. Sounds like your site can't bootstrap. Pass --debug to learn more. Also pass --root and --uri if needed.
1. 9.x-dev is unfortunately not that descriptive about exact version. Consider using a released version.

**Comment by aaronbauman** [comment]
latest 9.x release has a bug in conf(), which is fixed in master 
https://github.com/drush-ops/drush/commit/5c44ab940d9b2b04f11fdfe68aed10a801b98b2b#diff-cf22ea26b3aab80da36c1f85bb4e6ca5

i installed today, fwiw.

**Comment by weitzman** [comment]
fixed in 9.x too. release is forthcoming.
