### ISSUE TITLE
In Drupal 9: undefined function system_rebuild_module_data()

### ISSUE THREAD

**Issue by alberto56** [drush-ops/drush#4315]
**Describe the bug**
drush en some_module on Drupal 9 causes:

<code>
Error: Call to undefined function Drush\Drupal\Commands\pm\system_rebuild_module_data() in Drush\Drupal\Commands\pm\PmCommands->addInstallDependencies
</code>

It seems that in the issue <a href="https://www.drupal.org/node/3097453">#3097453 Remove system.module BC layers</a> ./core/modules/system/system.module: system_rebuild_module_data() was removed.

**To Reproduce**

Install Docker, then:

    git clone --branch 8.x-1.x https://git.drupalcode.org/project/word_monitor.git
    cd word_monitor
    docker pull dcycle/drupal:9
    ./scripts/deploy.sh 9

The result can also be seen [on CircleCI](https://circleci.com/gh/dcycle/word_monitor/4).

**Expected behavior**
It is possible to install third-party modules without getting "undefined function system_rebuild_module_data()"

**Actual behavior**
Error undefined function system_rebuild_module_data()

**Workaround**
Use a version of Drupal 9 prior to commit 46bd90dc3a

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | Drush version : 10.2.0
| Drupal version? | 9.0.x commit 18d531985f from Feb. 5, 2020
| PHP version     | PHP 7.3.14 (cli) (built: Feb  1 2020 20:40:23) ( NTS )
| OS?             | Linux d321ab5bff36 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 GNU/Linux

**Comment by weitzman** [comment]
Thanks. Was fixed 7 days ago #4213 4309
