### ISSUE TITLE
"drush site-install" fails to create the user because of a syntax error

### ISSUE THREAD

**Issue by prudloff-insite** [drush-ops/drush#4318]
**Describe the bug**
When trying to install Drupal with Drush and `--db-su`, it fails with an SQL syntax error.

**To Reproduce**
```bash
drush site-install config_installer -y --db-url='mysql://drupal_drush_t:drupal_drush_test@localhost/drupal_drush_test' --db-su=*** --db-su-pw='***'
```

**Expected behavior**
It creates the user, the database and then installs the site.

**Actual behavior**
Creating the user fails with this error:
```
 [info] sql:query: DROP DATABASE IF EXISTS drupal_drush_test; CREATE DATABASE drupal_drush_test /*!40100 DEFAULT CHARACTER SET utf8 */; DROP USER IF EXISTS 'drupal_drush_t'@'localhost'; CREATE USER 'drupal_drush_t'@'localhost' IDENTIFIED WITH mysql_native_password BY 'drupal_drush_test'; GRANT ALL PRIVILEGES ON drupal_drush_test.* TO 'drupal_drush_t'@'localhost'; FLUSH PRIVILEGES; [0.29 sec, 11.93 MB]
 [info] Executing: mysql --defaults-file=/tmp/drush_ZHdBsY --database=information_schema --host=localhost --silent -A < /tmp/drush_cGzB8y [0.29 sec, 11.94 MB]
 [warning] Failed to drop or create the database. Do it yourself before installing. ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY 'drupal_drush_test'' at line 1
```

**Workaround**
Create the user manually beforehand.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.2.1
| Drupal version? | 8.8.1
| PHP version     | 7.1.33
| OS?             | Linux

**Additional information**
We are using MariaDB 10.1.44.

It seems this syntax was introduced in https://github.com/drush-ops/drush/pull/4262.

**Comment by weitzman** [comment]
Perhaps your MySQL/MariaDB doesn't support this syntax? ping @AdamPS

**Comment by prudloff-insite** [comment]
Indeed, it seems MariaDB 10.1 does not support this: https://jira.mariadb.org/browse/MDEV-11180
Note that the previous command (`GRANT ALL PRIVILEGES`) was working for us (but apparently does not work on MySQL 8, according to https://github.com/drush-ops/drush/issues/4259?).

Would it be possible to use a command that works for most versions? Or to detect what the SQL server supports?

**Comment by AdamPS** [comment]
@prudloff-insite thanks for reporting back and sorry for the disruption.  Now that I look back `WITH mysql_native_password` should have been a big clue as specific to mysql - apologies for not seeing that..

Clearly it would be much better to get a single command that works on all current servers supported by Drupal if possible.  I will be away for the next few days then I can take a look after that.  I only have access to test MySQL so we will need to work together. 

As a starting point, please can you test it without the `WITH mysql_native_password` part?

**Comment by prudloff-insite** [comment]
Yes, this seems to be valid:
```sql
CREATE USER 'drupal_drush_t'@'localhost' IDENTIFIED BY 'drupal_drush_test';
```

**Comment by AdamPS** [comment]
Background info: the "WITH mysql_native_password" was added because in MySQL 8 the default authentication plugin [has changed](https://mysqlserverteam.com/upgrading-to-mysql-8-0-default-authentication-plugin-considerations/).

Now I look again I realise that the code we are discussing is in the class Sqlmysql so it seems quite reasonable for it to be specific to MySql.

I did a search on "mariadb mysql_native_password" and found [this documentation](https://mariadb.com/kb/en/authentication-plugin-mysql_native_password/).  So I don't understand why this code is failing on MariaDB.

**Comment by prudloff-insite** [comment]
I think the issue is not `mysql_native_password` but the syntax.
This seems to work on MariaDB:
```sql
CREATE USER 'drupal_drush_t'@'localhost' IDENTIFIED WITH mysql_native_password USING 'drupal_drush_test';
```
(See the doc here: https://mariadb.com/kb/en/create-user/#identified-viawith-authentication_plugin)

**Comment by AdamPS** [comment]
OK thanks we are making progress.  In your example, is 'drupal_drush_test' the password?

It looks like [MySQL](https://dev.mysql.com/doc/refman/8.0/en/create-user.html) can accept BY or AS and MariaDB can accept USING or AS.  So hopefully it works for all with AS.  Please can you test with AS?

**Comment by prudloff-insite** [comment]
Yes, `drupal_drush_test` is the password, however:

This seems to be syntactically valid:
```sql
CREATE USER 'drupal_drush_t'@'localhost' IDENTIFIED WITH mysql_native_password AS 'drupal_drush_test';
```

But, it triggers this error:
```
 #1372 - Password hash should be a 41-digit hexadecimal number
```
So I guess we need to pass a password hash here.

**Comment by AdamPS** [comment]
From reading the docs it looks as if MariaDB perhaps expects this
`CREATE USER 'drupal_drush_t'@'localhost' IDENTIFIED WITH mysql_native_password AS PASSWORD('drupal_drush_test');`

But MySQL needs the code that's checked in.  It seems that the PASSWORD function has been removed from MySQL for security reasons.

Sorry I'm out of time to spend on this one now.  Possible next steps:

- Try more to find a command that works with both MariaDB and mysql 8 (maybe someone who is an SQL expert?)
- Allow the command to vary depending on whether MariaDB or mysql.  I can't see how the code decides to class MariaDB into the same mysql, and hence how you could make a new sub-class to support a small difference in CREATE USER.

**Comment by weitzman** [comment]
I'd be fine with either of those approaches. Drupal has been considering splitting off mariadb into own driver but not much momentum yet https://www.drupal.org/project/drupal/issues/2985788

**Comment by AdamPS** [comment]
Great thanks

**Comment by AdamPS** [comment]
In my last comment on 13th Feb I stated:

> But MySQL needs the code that's checked in. It seems that the PASSWORD function has been removed from MySQL for security reasons.

Even so it seems that the patch committed code using the PASSWORD function.  So this is broken again on mysql 8 and I imagine the patch was not tested for this case.  I have raised #4616.

**Comment by prudloff-insite** [comment]
> So this is broken again on mysql 8 and I imagine the patch was not tested for this case.

I mentioned in https://github.com/drush-ops/drush/pull/4364#issue-394879034 that I tested the patch with MySQL 8.0, but maybe I did something wrong :slightly_frowning_face:

**Comment by AdamPS** [comment]
@prudloff-insite Thanks for the report I appreciate the time you took to test.  Please don't worry about it anyway sorry I was a bit grumpy before.  It would be great if you have a chance to test my new patch for #4616 on Maria.
