### ISSUE TITLE
drush.php is not put into vendor/bin

### ISSUE THREAD

**Issue by jimrome** [drush-ops/drush#4329]
composer require drush/drush puts drush.php into vendor/drush/drush/, but not into vendor/bin.
The problem is that some scripts call on vendor/bin/drush.php, for example, gocomposer

**Expected behavior**
Scripts should not abort

**Actual behavior**
**Workaround**
I copied drush.php to vendor/bin

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.2.0
| Drupal version? | 8.8.2
| PHP version     | 7.3.14 (cli)
| OS?             | Linux OpenSUSE LEAP 15.1

**Additional information**

**Comment by weitzman** [comment]
`drush` supposed to be in bin, not `drush.php`

**Comment by jimrome** [comment]
I know, but gocomposer calls for drush.php. You ought to at least put a link to drush.php in vendor/bin.
And once drush updb seemed to call drush.php as I recall.

**Comment by greg-1-anderson** [comment]
drush.php is internal. gocomposer should use drush, which is the correct entrypoint.

I think we stopped recommending directly calling drush.php starting in Drush 4.0.0 or thereabouts.
