### ISSUE TITLE
drush is no longer updating modules

### ISSUE THREAD

**Issue by jimrome** [drush-ops/drush#4332]
**Describe the bug**

> NAME | INSTALLED VERSION | RECOMMENDED VERSION
> -- | -- | --
> Generate Password | 8.x-1.0-beta3 | 8.x-1.0-beta4 (Release notes)

so I do

> composer require 'drupal/genpass:^1.0' --update-no-dev --update-with-dependencies
>     1/1:	https://packages.drupal.org/8/drupal/provider-2020-1$5908bfb7c062088c8ab44554756dbc6498d271c490365a5c0f22596dafedc159.json
>     Finished: success: 1, skipped: 0, failure: 0, total: 1
>     1/8:	http://repo.packagist.org/p/provider-latest$94da1803ef27cc4c9d2da8125e335720c05ec94a38013bf8b939336d728e3c8f.json
>     2/8:	http://repo.packagist.org/p/provider-2020-01$7344f38250d2161a2521be0b4b62c5e4224990ad300f4554c2d81b3493032e35.json
>     3/8:	http://repo.packagist.org/p/provider-2019-07$9e0423f690e59284311df26d5df3bb61cef629c5e5f9d3f11a906d6ccbba6255.json
>     4/8:	http://repo.packagist.org/p/provider-2019-04$491f6f208ca8955c9b97472a0c335e6e3d951f9350f9ede2baec61f6c2af64ac.json
>     5/8:	http://repo.packagist.org/p/provider-2016$0a91d4930eef4288ce0ae2e145c28546336dc8bfb7753f3828c94477e5129d61.json
>     6/8:	http://repo.packagist.org/p/provider-2019-10$a8f520d2baab95959c678a47f74f0d86a52af189e77efc507882047492ccc209.json
>     7/8:	http://repo.packagist.org/p/provider-2017$530de84505ac889cc4a9424d162670e25c3ed462077804e38d8f31ec579e5a19.json
>     8/8:	http://repo.packagist.org/p/provider-2018$ea209cd1dce5e6995295030b51106750e3deb29063bb131af0c5c8bac19dc983.json
>     Finished: success: 8, skipped: 0, failure: 0, total: 8
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies
 And I still sit at version 8.x-1.0-beta3. The module is listed in composer.json, and only exists in modules/contrib

**To Reproduce**
see above

**Expected behavior**
Should have updated the module

**Actual behavior**
What happened instead?

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.2.0 (please be specific, and try latest release)
| Drupal version? | 8.8.2
| PHP version     | PHP 7.3.14 (cli)
| OS?             | Linux
**Additional information**

**Comment by weitzman** [comment]
You didn't run drush in that log. You ran composer. `drush pm:enable:` is the relevant command here. It enables your module. When you update a module via composer, your next step is `drush updatedb` to run any pending updates.

**Comment by jimrome** [comment]
Oops. sorry
