### ISSUE TITLE
Drush site install on MS SQL Server fails

### ISSUE THREAD

**Issue by Beakerboy** [drush-ops/drush#4333]
**Describe the bug**
I have been successfully installing Drupal through the drupal-project package, but decided to use the Drupal git repository instead. This necessitated using drush instead of the Drupal-project `drupal` command. However, any installation attempt leads to:

Database name field is required.                                             
Database username field is required.                                         
Resolve all issues below to continue the installation. For help configuring  your database server, see the <a href="https://www.drupal.org/docs/8/install">installation handbook</a>, or contact your hosting provider.<div class="item-list"><ul><li>Failed to connect to your database server. The server reports the following message: <em class="placeholder">SQLSTATE[HY000] [2002] No such file or directory</em>.<ul><li>Is the database server running?</li><li>Does the database exist or does the database user have sufficient privileges to create the database?</li><li>Have you entered the correct database name?</li><li>Have you entered the correct username and password?</li><li>Have you entered the correct database hostname and port number?</li></ul></li></ul></div>

**To Reproduce**
This is a failing travis script: if the Drupal install is skipped, the run-tests.sh runs fine and is able to connect to the database.
https://github.com/Beakerboy/sqlsrv/blob/Drush-no-go/.travis.yml
`drush site:install standard --db-url=sqlsrv://sa:Password12!@localhost/mydrupalsite?dbo -n`

**Expected behavior**
Successfully install

**Actual behavior**
Error message. What is the file that is missing anyways?

**Workaround**
I can successfully install with drupal-project, and I can connect to the database with PHPUnit tests.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.2.1
| Drupal version? | 8.8.x-dev
| PHP version     | 7.2
| OS?             | Linux

**Additional information**
This installation is on the Microsoft SQL Server database. This is using a contrib driver.
The command that works using drupal-project is:
`drupal site:install standard --langcode="en" --db-type="sqlsrv" --db-host="localhost" --db-name="mydrupalsite" --db-user="sa" --db-pass="Password12!" --db-port="1433" --site-name="SQL Server Drupal Site" --site-mail="admin@example.com" --account-name="admin" --account-mail="admin@example.com" --account-pass="admin" --no-interaction`

The phpunit connection URL that works is:
`sqlsrv://sa:Password12!@localhost/mydrupalsite?dbo` Note that the '?dbo' is completly optional. The same behaiour is observed with and without it.

**Comment by Beakerboy** [comment]
Attempting to install Drupal 9 gives the same error, including the same link to the Drupal **8** installation handbook.

**Comment by Beakerboy** [comment]
Anything I can do to get drush installation working for D9? I can use Drupal Console for D8, but it is incompatible with Symfony 4.

**Comment by weitzman** [comment]
drush doesnt have sqlserv integration built-in anymore. You should ship integration with the sqlsrv driver or separately. Copy the approach of oracle drush integration https://gitlab.com/weitzman/drush-oracle-driver/
