### ISSUE TITLE
`drush sa --field=foo` not formattable

### ISSUE THREAD

**Issue by geek-merlin** [drush-ops/drush#4338]
**Describe the bug**
Any attempt to extract a single field from an alias for further shell processing leads to an error.

**To Reproduce**

```
$ drush sa @freiburg
'@self.freiburg':
  host: freiburg.net
  user: s9999
  root: /home/s9999/current/docroot
  uri: 'http://db.freiburg.net'

$ drush sa @freiburg --field=host --format=yaml # ...or any other format.
In FormatterManager.php line 230:
  The format string cannot be used with the data produced by this command, which was an instance of Consolidation\OutputFormatters\StructuredData\UnstructuredListData.  Valid formats are: csv,json,list,null,php,print-r,tsv,var_dump,var_export,xml,yaml                                 

```

**Expected behavior**

Get the value.

**Actual behavior**

Above exception.

**Workaround**

Using --fields gives no exception, but has no shell parsable output.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.2.1
| Drupal version? | 8.x
| PHP version     | 7.2
| OS?             | Linux

**Additional information**
---

**Comment by greg-1-anderson** [comment]
Try `--fields=host --format=yaml`.  The singular `--field` is shorthand for `--format=string`, so this is behaving correctly.

**Comment by geek-merlin** [comment]
Thanks for responding so quickly. 

Whis gives me
```
$ drush sa @self.freiburg --fields=host --format=yaml
'@self.freiburg':
  host: c145s.freistilbox.net
```
But to have this parsed into another command i'd need something like
```
$ drush sa @self.freiburg --fields=host --format=???
host: c145s.freistilbox.net
```
So in the light of what you say it'd be a feature request.

**Comment by greg-1-anderson** [comment]
Doesn't `--fields=host --format=string` or just the `--field=host` (without --format) suit your purpose?

**Comment by greg-1-anderson** [comment]
Ah, I see.

The structure provided by the `sa` command does not work with `--string` or `--list` formats. This is an issue for (consolidation/output-formatters0[https://github.com/consolidation/output-formatters]. PRs would be welcome.

**Comment by loziju** [comment]
@greg-1-anderson any hint on which file to update in https://github.com/consolidation/output-formatters?

I need to extract the uri of `sa` information to automate deployment of multisite.

**Comment by greg-1-anderson** [comment]
Try `--format=json` and `jq`.

i.e. `drush9 sa @site.dev --format=json | jq '."@site.dev".host'`

This would be way more convenient if Drush did not include the alias name as the top-level component of the alias. Perhaps `drush sa` could have a flag `--single` to return just the body of the alias data for the first alias returned in the result (or maybe it would be better if it errored if multiple aliases match, to avoid working scripts becoming not-working-scripts if new aliases are added)

**Comment by greg-1-anderson** [comment]
There is also this:
```
drush sa @site.dev --fields=host
```
This outputs:
```
'@site.dev':
  host: example.com
```

**Comment by Chi-teck** [comment]
A workaround without `jq`.
```bash
function get_alias_field {
  "$ROOT_DIR"/bin/drush sa "$1" --fields="$2" | awk 'FNR == 2 {gsub(/\047/, "", $2); print $2}'
}

# Usage.
get_alias_field @prod uri
```

**Comment by loziju** [comment]
Thanks @greg-1-anderson @Chi-teck 
I ended up using awk for workaround.
