### ISSUE TITLE
Feature request: commands to wrap \Drupal\Core\Site\Settings, similar to Config and State wrappers

### ISSUE THREAD

**Issue by aaronbauman** [drush-ops/drush#4344]
**Is your feature request related to a problem? Please describe.**
As a developer, I'd like to be able to fetch Settings values from drush, so that I can use them in my CI workflow.

**Describe the solution you'd like**
Similar to `config:get` or `state:get` commands, I'd like a `settings:get` command that will allow me to access Settings values from drush.

**Describe alternatives you've considered**
`eval` command is an alternative, but not available in many contexts.

**Comment by weitzman** [comment]
You cant edit/delete a setting, so not as helpful as those comps.

**Comment by aaronbauman** [comment]
Would like to revisit this feature request.

Is there an alternative way, for example, to figure out the config directory from drush?
Or to find any of the other various things that are settings instead of config?

**Comment by weitzman** [comment]
Config dir:
```
$ drush st --fields=config-sync --format=string
sites/dev/files/config_yNVs8hh2V9HTi424i4gpD6AkMgsHOQk6MDDG9A9nQBerLMKiE3NLurrVe1bcfIChUxcspKk77A/sync
```

Settings in general:
```
$ drush ev --format=json "return \Drupal\Core\Site\Settings::get('container_yamls')"
[
    "/var/www/html/sut/sites/dev/services.yml"
]
```

**Comment by aaronbauman** [comment]
Thanks!
