### ISSUE TITLE
Where is command list?

### ISSUE THREAD

**Issue by liquidcms** [drush-ops/drush#4347]
I am sure I am just missing something simple; but when I google "drush" I end up here: https://docs.drush.org - which, as far as i can tell doesn't have a list of drush commands. 

I am used to using this site (although it has many mistakes): https://drushcommands.com/drush-9x/ but doesn't list for drush 10.

What am i missing here?

**Comment by weitzman** [comment]
There is no such site at this time. I'd love help making a static site for this.
