### ISSUE TITLE
ProgressBar on migrate drupal8 command

### ISSUE THREAD

**Issue by OProf77** [drush-ops/drush#4353]
**Describe the bug**
I no longer see the progress bar when I run commands for the drupal8 migrate module.

**To Reproduce**
From shell: Drush migrate:import name_plugin_migrate --limit 1000

**Expected behavior**
Before, I used to see the progressive bar that shows me the percentage.(image attach)

**Actual behavior**
There is only the cursor

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.2.2
| Drupal version? | 8.8.4
| PHP version     | 7.3
| OS?             | Linux
<img width="558" alt="Schermata 2020-03-19 alle 01 42 19" src="https://user-images.githubusercontent.com/58259159/77073909-480b7780-69f0-11ea-9080-b626973466a4.png">

**Comment by weitzman** [comment]
That would be a question for migrate tools module - its their command. Also, I dont recall them having a progress bar, so perhaps you have a different provider. They just have --feedback option.

**Comment by OProf77** [comment]
With drush 8.2 and Drush command toll 10.2.2 everything works perfectly (image attach)
<img width="651" alt="Schermata 2020-03-19 alle 15 14 28" src="https://user-images.githubusercontent.com/58259159/77076649-65424500-69f4-11ea-9bbf-2a70f2f6ade0.png">

**Comment by weitzman** [comment]
Can you paste output of `drush status` with Drush 8 and Drush 10?

**Comment by OProf77** [comment]
<img width="648" alt="Schermata 2020-03-19 alle 15 25 36" src="https://user-images.githubusercontent.com/58259159/77077816-0978bb80-69f6-11ea-9ba8-860b1b2a1c1f.png">
<img width="550" alt="Schermata 2020-03-19 alle 15 25 57" src="https://user-images.githubusercontent.com/58259159/77077841-13022380-69f6-11ea-9440-ff8de78f5c19.png">

**Comment by weitzman** [comment]
Thanks. LGTM. You will have to ask about this in the Migrate issue queue. Drush doesn't actually provide a progress bar. That would be from Symfony Console.

**Comment by OProf77** [comment]
Thanks to you for the support.

**Comment by JadhavNamisha** [comment]
Hello. Did you get the solution for this?
