### ISSUE TITLE
Use of undefined constant STDIN, fgets() issues running Drush.

### ISSUE THREAD

**Issue by liquidcms** [drush-ops/drush#4356]
I am posting just to see if anyone has seen these issues before:

Yesterday drush was running fine on our server. I suspect our hosting company modified something; most likely to do with PHP CLI. These are a few issues which i see now; which weren't there yesterday.

1. following commands all work: cron, cr, st but the output of all of them has this at the end:
X-Powered-By: PHP/7.2.28
Content-type: text/html; charset=UTF-8

2. drush updb fails:
[warning] Use of undefined constant STDIN - assumed 'STDIN' (this will throw an Error in a future version of PHP) QuestionHelper.php:158
[warning] fgets() expects parameter 1 to be resource, string given QuestionHelper.php:174

3. drush was (removed for #1, #2 above) complaining about my local php.ini having:
disable_functions = shell_exec,system

4. every drush command was failing due to a http to https chunk of code that i had in my settings.php (removed for #1, #2 above).

These all worked yesterday.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.2.2
| Drupal version? | 8.8.4
| PHP version     | 7.2.28
| OS?             | CentOS 7

**Comment by liquidcms** [comment]
Even more oddness.. when i called in to our hosting support; the guy there tried it and it worked fine. So it has something to do with ip, ssh client, session, etc. Although, I tried from a different IP with a different SSH client.. still broken.

**Comment by greg-1-anderson** [comment]
Somehow you are using php-cgi instead of php-cli. Check your $PATH, `which drush` etc.

**Comment by liquidcms** [comment]
Hi Greg... and yes.. i just figured that partially out.. like 2 min ago.. on call with hosting company now to sort it out.. but thanks a ton.

**Comment by liquidcms** [comment]
Yes, path was wrong.. /usr/bin was ahead of /usr/local/bin which was putting php-fcgi ahead of php-cli

fixing that and it now runs without tacking: 
X-Powered-By: PHP/7.2.28
Content-type: text/html; charset=UTF-8
at the end of every command.

And drush updb now runs correctly...

unfortunately cr, which did work when PATH was wrong.. now spits out:
 [warning] Drush command terminated abnormally.

een though --vvv is no help; my guess is cli php.ini is now to blame and there is a memory issue.. but just a guess..

**Comment by liquidcms** [comment]
yes, tracking down cli php.ini and setting memory_limit = -1 fixed issue with cr.. and now all is well.
