### ISSUE TITLE
The command output does not check verbosity correctly.

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#4373]
**Describe the bug**
[OutputInterface::isDebug()](https://github.com/symfony/console/blob/v4.4.7/Output/OutputInterface.php#L85) should return `true` only when `-vvv` flag was provided.

**To Reproduce**
Put the following code to some annotated command.
```
var_dump($this->io()->isDebug());
```
Run the command with `-vv` flags (very verbose).

**Expected output**
```
false
```

**Actual output**
```
true
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  |10.2.2
| Drupal version? | 9.0.0-dev
| PHP version     | 7.4.3
| OS?             | Linux

**Additional information**
Other verbosity methods (`isVerbose` and `isVeryVerbose`) work correctly.

**Comment by weitzman** [comment]
I agree, but @greg-1-anderson prefers current behavior IIRC.

**Comment by greg-1-anderson** [comment]
I actually don't recall if there was a reason that -vv turns on debug.

I was opinionated about notice vs info; we bumped up the visibility of notices, so that they were visible without -v, whereas the standard only shows warnings and errors unless verbose.
