### ISSUE TITLE
Drush 8 Release for PHP7.4 capability?

### ISSUE THREAD

**Issue by seamuslee001** [drush-ops/drush#4376]
Hi All

Just wondering if there are plans for a release for Drush 8 anytime soon I notice that there was this fix https://github.com/drush-ops/drush/pull/4330 that went in which should mean that for d7 sites they can use drush 8 on php7.4 

ping @weitzman @greg-1-anderson

**Comment by joejoseph00** [comment]
This is a blocker, we urgently need Drush 8 fixes for MySQL 8.x compatibility:
This is in preparation for Drupal 7.70 which is currently in development. 
 see: #4313 

and upstream: 

Support MySQL 8 on Drupal 7
https://www.drupal.org/project/drupal/issues/2978575

php 7.4 compatibility in Drupal 7
https://www.drupal.org/project/drupal/issues/3081386

**Comment by joejoseph00** [comment]
@weitzman please add the Drupal 7 tag.

**Comment by joejoseph00** [comment]
So if I am understanding correctly, it looks like all the fixes are now in thanks to the recent pull request and now we just hope for a tagged release?

**Comment by mustanggb** [comment]
Drush 8.3.3 has landed, much appreciated chaps, I think this issue can be closed.

**Comment by joejoseph00** [comment]
Thanks @weitzman and @greg-1-anderson !  Much appreciated!

**Comment by greg-1-anderson** [comment]
Thanks for your patience. I intended to make a release in April, but didn't get to it.

**Comment by seamuslee001** [comment]
Thanks All :)

**Comment by marcelovani** [comment]
can we update the php version here https://www.drush.org/install/
