### ISSUE TITLE
How can I resolve “Your requirements could not be resolved to an installable set of packages” error?

### ISSUE THREAD

**Issue by salavadhinl** [drush-ops/drush#4386]
When I run composer update I receive some wired output:-
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ddeboer/imap 1.9.0 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - ddeboer/imap 1.8.0 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - ddeboer/imap 1.7.2 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - ddeboer/imap 1.7.1 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - ddeboer/imap 1.7.0 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - ddeboer/imap 1.6.0 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - ddeboer/imap 1.5.5 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - ddeboer/imap 1.5.4 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - ddeboer/imap 1.5.3 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - ddeboer/imap 1.5.2 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - ddeboer/imap 1.5.1 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - ddeboer/imap 1.5.0 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - ddeboer/imap 1.10.0 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - Installation request for ddeboer/imap ^1.5 -> satisfiable by ddeboer/imap[1.10.0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.9.0].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by weitzman** [comment]
Add --ignore-platform-reqs to bypass that message.

Note that `composer why ddeboer/imap` will tell you why you are needing that package. Its not Drush thats depends on it
