### ISSUE TITLE
Major regression in SQL:SYNC command missing --database option

### ISSUE THREAD

**Issue by BramDriesen** [drush-ops/drush#4390]
So many regressions in drush recently...

There used to be a `--database` option in the SQL:SYNC command that allowed you to target specific databases to sync your data in. Quoting one of the maintainers:

> It was removed in a refactor as it would have taken too much time to port

Referencing to an previous issue I made where it was decided to just add documentation: https://github.com/drush-ops/drush/pull/3951

And the commit that removed the documentation again without any fix: https://github.com/drush-ops/drush/commit/63f284846270b5cd9d781ed94d570688c1b2c688#diff-fb2c277772bf5979ffd2cd9676de3c88

Please bring back the `--database` option as it's a very useful option we use quite a lot on some sites where we have sometimes 3 databases.

**Comment by weitzman** [comment]
The open feature request for the is #4274

**Comment by BramDriesen** [comment]
Sure 👍  😄
