### ISSUE TITLE
ThemeCommands::uninstall always throws an exception

### ISSUE THREAD

**Issue by aaronbauman** [drush-ops/drush#4392]
**Describe the bug**
\Drush\Drupal\Commands\pm\ThemeCommands::uninstall throws an exception if \Drupal\Core\Extension\ThemeInstaller::uninstall returns a value that evaluates to false, but \Drupal\Core\Extension\ThemeInstaller::uninstall never returns any value.

**To Reproduce**
drush thun <theme>

**Expected behavior**
- Theme successfully uninstalled
- Success message

**Actual behavior**
- Theme successfully uninstalled
- Exception and failure message

**Workaround**
- No, not through drush.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.2.2
| Drupal version? | 8.8.5
| PHP version     | 7.3.13
| OS?             | Mac/Linux

**Comment by weitzman** [comment]
Closed in #4393
