### ISSUE TITLE
Deprecated use of Process::inheritEnvironmentVariables

### ISSUE THREAD

**Issue by heddn** [drush-ops/drush#4402]
**Describe the bug**
CliTestTrait uses deprecated Symfony  3.3 code. See https://www.drupal.org/pift-ci-job/1667378

**To Reproduce**
Run a test that leverages CliTestTrait.

**Expected behavior**
No deprecation warnings

**Actual behavior**
Deprecation warnings.

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.x
| Drupal version? | 9.x/8.x
| PHP version     | 7.x
| OS?             | Mac/Linux/Windows

**Additional information**

**Comment by weitzman** [comment]
Lets discuss in PR #4403

**Comment by claudiu-cristea** [comment]
Closing in favour of #4726
