### ISSUE TITLE
Connected with the Database? Or.... not?

### ISSUE THREAD

**Issue by begrafx** [drush-ops/drush#4404]
**Describe the bug**

I have encountered this issue on two separate instances of Drush, which came included as part of separate Drupal 8 Distros. I am missing a number of commands. When running a command with <code>--debug</code> I am told <code>[Symfony\Component\Console\Exception\CommandNotFoundException]               
  Command rq was not found. Drush was unable to query the database. As a resu  
  lt, many commands are unavailable. Re-run your command with --debug to see   
  relevant log messages.</code> however when I enter <code>drush sql:connect</code> it comes back with all of the correct database information for the site. (in both instances). I encounter this with both local version 9.7.2 and 10.2.2 likewise <code>drush status</code> returns all the correct information regarding the database. 

**To Reproduce**
What did you do?

See above.

**Expected behavior**
What did you expect would happen?

As the error mentions, commands are missing from "drush list"

**Actual behavior**
What happened instead?

incomplete list, some commands do not appear, and do not work.

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.x/9.x/8.x (please be specific, and try latest release)

I have tried this on Drush that came with two different distros. One is using Drush 9.7.2, one is using Drush 10.2.2. Both yield the same issue. Both are Local installs, as opposed to Global install.

| Drupal version? | 9.x/8.x/7.x

Drupal 8.8.5

| PHP version     | 7.x,5.x

PHP 7.1.33
| OS?             | Mac/Linux/Windows

MacOS 10.14.6

**Additional information**

**Comment by begrafx** [comment]
To add to the above, the site itself works fine. If at the command line, I type
`
drush status`

the output shows all the correct information, so it is clearly SEEING the database.  This is a local (development) build, on my local machine, under MAMP 5.7.

**Comment by weitzman** [comment]
Please use Drupal Answers for support questions.

**Comment by begrafx** [comment]
I'll be glad to use Drupal Answers, if you'll help me to word my question "appropriately". It seems anything associated with StackExchange, if I ask a question it is promptly closed and marked as "off-topic", regardless of what I ask.
