### ISSUE TITLE
updatedb - error message from requirements check 

### ISSUE THREAD

**Issue by hansfn** [drush-ops/drush#4405]
Running `drush updatedb` when a module is missing from the file system returns:

```
 [error]   (Currently using Missing or invalid module Array) 

 Requirements check reports errors. Do you wish to continue? (yes/no) [yes]:
```

The relevant code is in `src/Commands/core/UpdateDBCommands.php` - the updateCheckRequirements function. Has the $requirements array coming from update_check_requirements() changed format? 

```
$message .= ' (Currently using '. $requirement['title'] .' '. $requirement['value'] .')';
```

makes little sense when some of the (requirement) titles are

- Database support
- PHP memory limit
- File system
- Missing or invalid module

and values are various things (that might need to be rendered - like the error message for installed modules missing from the file system).

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.2.2 (dev)
| Drupal version? | 8.9.0
| PHP version     | 7.3
| OS?             | Linux

**Comment by weitzman** [comment]
Hope someone can propose a fix.
