### ISSUE TITLE
Database is not found with Drupal 9.0.0-beta3

### ISSUE THREAD

**Issue by back-2-95** [drush-ops/drush#4412]
**Describe the bug**
Updated Drupal 9.0.0-beta2 to Drupal 9.0.0-beta3. Now drush sql-cli or any other database related command does not find database for @self.

**To Reproduce**
Updated Drupal 9.0.0-beta2 to Drupal 9.0.0-beta3.

**Expected behavior**
Drush 10.2 to work same way as it worked with Drupal 9.0.0-beta2

**Actual behavior**
drush sql-cli = Unable to load Drupal settings. Check your --root, --uri, etc.
drush sql-sync @source @self = Could not look up database name for @self

**Workaround**
Is there another way to do the desired action? No

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.2.2
| Drupal version? | 9.0.0-beta3
| PHP version     | 7.3.17
| OS?             | Linux

**Additional information**
-

**Comment by greg-1-anderson** [comment]
If you run `drush sql:conf`, do you see your correct database settings?

**Comment by back-2-95** [comment]
`drush sql:conf` gives:

```
In SqlBase.php line 106:

  Unable to load Drupal settings. Check your --root, --uri, etc.
```

**Comment by greg-1-anderson** [comment]
Looks like something went amiss with your site. Check your settings.php file etc.

I was able to successfully run `drush si` on a fresh Drupal 9.0.0-beta3 site and require + enable the token module.

**Comment by back-2-95** [comment]
Weird, if I just do `echo "foobar"; exit;` in the beginning of settings.php, it does not even do nothing....

**Comment by greg-1-anderson** [comment]
Is settings.php in `default` or some other directory? If it is not in default, have you specified `--uri` on your Drush commandline?

**Comment by back-2-95** [comment]
It's in default. And it worked normally before when I had Drupal core 9.0.0-beta2.
I just updated things with composer and boom.

**Comment by back-2-95** [comment]
Reverted changes is composer.json and composer.lock and run composer install. Everything works.

**Comment by greg-1-anderson** [comment]
Very strange. Beta3 works fine for me.

**Comment by back-2-95** [comment]
Gonna try again and keep a closer eye.

**Comment by back-2-95** [comment]
Ok, so `composer/installers` was dropped from `drupal/core-recommended` in beta 3 and all my modules and core ended up in vendor. So I had 2 version of core in 2 places and all went haywire. I required composer/installers and fixed it.

So now things work again. Sorry for the trouble.
