### ISSUE TITLE
Let database updates (`drush updb`) provide backtraces

### ISSUE THREAD

**Issue by geek-merlin** [drush-ops/drush#4417]
When doing 
```
drush updb
```
i got an output of
```
>  [notice] Update started: profile_update_8002
>  [warning] A non-numeric value encountered SettingsForm.php:687
>  [error]  Unsupported operand types 
>  [error]  Update failed: profile_update_8002 
```
and had a hard time debugging it's markdown/SettingsForm. A backtrace would have helped.

(Bear with me if i'm missing something obvious, but `-vvv`, reading help and asking aunt google did not enlighten me.)

**Comment by weitzman** [comment]
Two things to try:

1. install xdebug
1. increase reporting error level in your drupal.

**Comment by geek-merlin** [comment]
Thanks for the quick feedback! Installing xdebug is not possible on the server (and may not for others). Also i cross-checked error level config setting is highest. I also cross-checked that nothing is in the watchdog (which makes sense during update).

```
$ drush cget system.logging
error_level: verbose

```

**Comment by weitzman** [comment]
I thought it was drupal core that offers backtrace but it wont do so until https://www.drupal.org/project/drupal/issues/1158322 is merged. Until then, devel module offers it.

**Comment by geek-merlin** [comment]
That issue is for D7, we're on D8. And good you mentioned, i also checked that devel is enabled.

**Comment by weitzman** [comment]
In any case, its not drush's responsibility to enable backtraces.
