### ISSUE TITLE
Investigation: Try to run Rector on Drush

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#4419]
**Is your feature request related to a problem? Please describe.**
[Rector](https://www.palantir.net/blog/jumpstart-your-drupal-9-upgrade-drupal-rector) is a neat tool to help upgrade modules for Drupal 9.

**Describe the solution you'd like**
It would be neat if we could get Rector to help find and fix deprecations in Drush 8. Who knows, there might even be a deprecation or two lingering in Drush 10.

**Describe alternatives you've considered**
I'm not sure if Rector works on non-modules. It seems it has a non-Drupal background, so this might be easy, or it might be hard. If it won't run directly on Drush, maybe importing all of Drush into a module shell might be a suitable workaround.

**Comment by weitzman** [comment]
#4864
