### ISSUE TITLE
Drush 8.3.4 can't uninstall installed modules in d9

### ISSUE THREAD

**Issue by andypost** [drush-ops/drush#4428]
**Describe the bug**
New release allows to setup core, install modules but does not allow to uninstall

**To Reproduce**
```
$ drush pm:uninstall syslog
syslog is not disabled. Use `pm-disable` command before `pm-uninstall`.                                                                                                               [warning]
There were no modules that could be uninstalled.                                                                                                                                      [ok]
$ drush pm:disable syslog
The following extensions will be disabled: syslog
Do you really want to continue? (y/n): y
Drupal 8 does not support disabling modules. Use pm-uninstall instead.
```

**Expected behavior**
The `pm:uninstall` should uninstall module, or at least not tell to try disable it

**Actual behavior**
Module uninstalled

**Workaround**
Not yet, but `drush ev` probably by accessing module_installer

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.3.4
| Drupal version? | 9.1.x
| PHP version     | 7.3.18
| OS?             | Linux

**Additional information**
No

**Comment by greg-1-anderson** [comment]
Fixed in #4429
