### ISSUE TITLE
error after updating drupal core and commerce

### ISSUE THREAD

**Issue by parvanova** [drush-ops/drush#4439]
I just updated drupal core from 8.8.6 to 8.9.0 and Commerce from 8.x-2.18 to 8.x-2.19

After that drush cr gives
PHP Fatal error:  Cannot redeclare Zend\Diactoros\createUploadedFile() (previously declared in /usr/local/src/drush/vendor/zendframework/zend-diactoros/src/functions/create_uploaded_file.php:20) in<site root>/vendor/laminas/laminas-diactoros/src/functions/create_uploaded_file.legacy.php on line 19

**Comment by greg-1-anderson** [comment]
Are you using Drush 8.3.5?

**Comment by jansete** [comment]
I have the same problem, I'm using drush 10.2.2

We would have replace old zendFramework/* dependencies with Laminas in drush dependencies.

This is the issue in Drupal Core https://www.drupal.org/project/drupal/issues/3104015

**Comment by parvanova** [comment]
It was an update from 8.8.6 to 8.9

**Comment by jansete** [comment]
Yes, it's a change done in Drupal Core 8.9 and 9.0, I think that we will have do the same change in drush, and I think that a big amount of installations with those versions are getting this error. I guess that we have to change as soon as possible.

**Comment by greg-1-anderson** [comment]
@parvanova What version of *drush* are you using?

@jansete Are you using Drush 10 as a global install? That's not supported; add Drush as a dependency of your site.

**Comment by greg-1-anderson** [comment]
So, this is not supported, but note that Drush 10 does **not** depend on ZendFramework or Laminas, but it does require-dev drupal/core-recommended. You therefore would have better luck with the unsupported configuration if you run `composer install --no-dev` in your global Drush directory.

Installing Drush as a site-local dependency is recommended, as there may be other problems. I have not tried to make this work myself.

**Comment by greg-1-anderson** [comment]
Ah, right, after you get past the Laninas problems, your next challenge is that you'll still have Symfony 3 in Drush, and Drupal 9 has Symfony 4. Perhaps a better workaround would be to change the require-dev of drupal/core-recommended in Drush to ^9, and run `composer update`.

Again, this is not recommended, as there may be even more problems. I will reiterate that I have not tried to make this work myself.

**Comment by jansete** [comment]
You are right @greg-1-anderson ,

I've changed drush from global to drupal dependency and now it works.

Thanks!
