### ISSUE TITLE
Watchdog-show Drush 10.2.2 no longer accepts message ID

### ISSUE THREAD

**Issue by lieb77** [drush-ops/drush#4440]
In older versions of drush I could do drush ws and then see the full message with drush ws message-id - drush ws 1234

Now when I do that it says
 [notice] No log messages available.

| Drush version?  | 10.2.2
| Drupal version? | 8.90
| PHP version     | 7.3
| OS?             | Linux

Thanks

**Comment by weitzman** [comment]
that was moved to a new command `watchdog:show-one`
