### ISSUE TITLE
Drush does not display colored output in REPL

### ISSUE THREAD

**Issue by tyler36** [drush-ops/drush#4445]
**Describe the bug**
Output in Drush REPL displays in monochrome. Ie. White text on black background

**To Reproduce**
Type ```drush php```. Header text ('Psy Shell v0.10.4 (PHP 7.3.18 — cli) by Justin Hileman') displays white on black.
Entered commands also display only white text. Eg. ```$array = ['one' => 'one', 'two' => 'Two'];```

**Expected behavior**
Header text to be colored.
Array key and values to be colored; similar to screenshot on http://blog.damiankloip.net/2015/drush-php

**Actual behavior**
All text is white

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.0
| Drupal version? | 8.9.1
| PHP version     | 7.3.18
| OS?             | Win10

**Additional information**
- Psysh installed globally displays a colored header, and colored responses. Header text, "Psy Shell v0.10.4 (PHP 7.3.18 — cli) by Justin Hileman", displays blue and command responses highlighted.
- Laravel Tinker, in Laravel projects, displays header text, "Psy Shell v0.10.4 (PHP 7.3.18 — cli) by Justin Hileman", displays blue and colored responses.
- ```drush list``` display colored responses.
- ```drush list --no-ansi``` does NOT display colored responses (as expected).

**Comment by tyler36** [comment]
Colored output from drush command: ```drush list```
![drush-list](https://user-images.githubusercontent.com/7234392/85378956-22a18300-b576-11ea-90b9-6dcb0dc118f1.jpg)

Missing color: ```drush php```
![drush-php](https://user-images.githubusercontent.com/7234392/85378958-23d2b000-b576-11ea-9238-12cb3f07ed02.jpg)

Generic Psysh session: ```psysh```
![psysh](https://user-images.githubusercontent.com/7234392/85378966-259c7380-b576-11ea-99ad-6dbce4f2ba83.jpg)

**Comment by weitzman** [comment]
Its colored for me. Not sure we to debug your environment.
