### ISSUE TITLE
config:import --preview marked deprecated but no indication why

### ISSUE THREAD

**Issue by bradjones1** [drush-ops/drush#4450]
**Describe the bug**
`drush config:import --preview` was marked deprecated in https://github.com/drush-ops/drush/commit/5db1af6b1479df727fbab8794266a214c1d10563 but an examination of the issue history (most proximately, https://github.com/drush-ops/drush/issues/4371) doesn't reveal a reason for the deprecation.

Refs loosely new work on this feature at https://github.com/drush-ops/drush/issues/4395

**Comment by weitzman** [comment]
That commit adds a --diff option.
