### ISSUE TITLE
Can't import database with drush sqlc on Drupal 8 instance

### ISSUE THREAD

**Issue by golddragon007** [drush-ops/drush#4451]
**Describe the bug**
If I try to use `drush sqlc < dump.sql` or `zcat dump.sql.gz | drush sqlc` then it enters to MySQL console instead of importing the dump file to MySQL.

**To Reproduce**
Have a Drupal 8.x instance. Run LAMP.
drush sqlc < dump.sql
or
zcat dump.sql.gz | drush sqlc
As I heard with docker it works whatever reason.

**Expected behavior**
Import the database without entering to MySQL console.

**Actual behavior**
Doesn't import the database dump, instead of that it enters to MySQL console.

**Workaround**
Use direct MySQL command.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.0
| Drupal version? | 8.x
| PHP version     | 7.x
| OS?             | Linux, CentOs, Amazon Cloud 9

**Additional information**
If I'm running a Drupal 7, I can use the above-mentioned import commands, and they doing the job.

**Comment by weitzman** [comment]
duplicate.

**Comment by bgnih** [comment]
Workaround: drush sqlq 'source dump.sql;'
