### ISSUE TITLE
Add an option for choosing a different mysqldump executable

### ISSUE THREAD

**Issue by Nico-uncinc** [drush-ops/drush#4453]
I'd like to use a GDPR dump library (https://github.com/machbarmacher/gdpr-dump) for creating anonymized dumps. That library provides its own mysqldump executable for anonymizing the data. So for this to properly work with drush, we would need an option to choose their mysqldump executable instead of the default one. 

I've provided a patch file that adds a db-executable option to the sql-dump command.

[add-db-executable-as-option.patch.txt](https://github.com/drush-ops/drush/files/4857210/add-db-executable-as-option.patch.txt)

**Comment by weitzman** [comment]
Set your PATH to pick this mysqldump over the standard one.

**Comment by weitzman** [comment]
FYI you can set env vars in a site alias.
