### ISSUE TITLE
Migrating code to D9: getting Call to deprecated function drush_set_context('DRUSH_ERROR_CODE', 1);

### ISSUE THREAD

**Issue by alberto56** [drush-ops/drush#4455]
**Existing document**
I cannot find any reference to drush_set_context in the documentation: http://www.drush.org/api/master/search.html?search=drush_set_context

**What are you attempting to do**
Figure out what to put instead of drush_set_context('DRUSH_ERROR_CODE', 1); in my code so I don't get a deprecation error from the drupal-check tool.

**In what way is the existing documentation unclear or incomplete**
It makes no mention of drush_set_context().

**What should the documentation say instead?**

    drush_set_context()
    ** deprecated since version x.x.x **
    please replace with xyz().
    for example,
    * drush_set_context(xyz) should be xyz(xyz)
    * drush_set_context('DRUSH_ERROR_CODE', 1); should be ...

**Comment by weitzman** [comment]
You can remove that code and just throw an exception.
