### ISSUE TITLE
drush returning output to stderr instead of stdout

### ISSUE THREAD

**Issue by r7l** [drush-ops/drush#4460]
**Describe the bug**
When running options like `drush updb` it returns the output on stderr instead of stdout. It's kinda weird when the output itself says `[success] No pending updates.`. Is this expected behaviour?

This is also the case on serveral other options like `drush ws`.

**To Reproduce**
`drush updb 2> stderr.txt`

**Expected behavior**
`drush updb 1> stdout.txt` to have the output if there wasn't any error and have stderr only be used in case of actual errors.

**Actual behavior**
The output of several (i've tested a few options) drush options end up in stderr even if there wasn't any error.

**Workaround**
Not really, as manually reassigning to stdout would also have errors to appear in stdout.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.2.2
| Drupal version? | 8.x
| PHP version     | 7.3.18
| OS?             | Linux

**Additional information**
This is not the case if i simply run `drush`. This output is returned to stdout.

**Comment by weitzman** [comment]
The naming is a quirk of unix. stderr is the right place for log messages, regardless of whether they indicate success or failure. stdout is where the "return data" is printed. Thats things like the list of modules in `pm:list` or the list of watchdog messages in `watchdog:show`
