### ISSUE TITLE
Add option to `generate module-content-entity` for create "lite" entity (without interface, custom forms, etc)

### ISSUE THREAD

**Issue by MurzNN** [drush-ops/drush#4463]
At now `drush generate module-content-entity` works well, but creates too much files, that for most cases is unnecessary!

I suggest to add `--lite` option to `generate module-content-entity` for create "light" entity, that will not create interface for Entity class, reuse Drupal defaults EntityListBuilder, EntityViewBuilder, ContentEntityForm, not generate permission records, etc.

Ideally if it will create only single `.php` file for entity with one `Entity` class. All other features for this entity users will can add later manually, when needed.

**Comment by MurzNN** [comment]
Here https://www.drupal.org/project/drupal/issues/2476669 is issue for add entity label to core EntityListBuilder.

**Comment by weitzman** [comment]
Please file with https://github.com/Chi-teck/drupal-code-generator
