### ISSUE TITLE
Allow generating new entity into exist Drupal module via `drush generate module-content-entity`

### ISSUE THREAD

**Issue by MurzNN** [drush-ops/drush#4464]
At now `drush generate module-content-entity` command works well only when creating new module, if I try to generate entity for already created module, it can only overwrite (replace) `.yml` module files with deleting previous data, or don't touch them.

For solve this problem will be good to add mode for append info to end of yml file, instead of overwriting, and skip touching `MODULENAME.info.yml` file. And seems thats's all that we need for allow adding new generating entity type into exist Drupal module?

**Comment by MurzNN** [comment]
Woow, seems `drupal generate:entity:content` allow generating new entity into exist Drupal module, but it have less flexibility with entity features, so `drush` implementation now better and more promising.

**Comment by weitzman** [comment]
generate bugs/features should go to https://github.com/Chi-teck/drupal-code-generator
