### ISSUE TITLE
Rename Drush master branch

### ISSUE THREAD

**Issue by greg-1-anderson** [drush-ops/drush#4468]
**Is your feature request related to a problem? Please describe.**
There has been a lot of attention lately on language use that is unwelcoming for some participants. Drush uses "master" for the default branch, which is the default for Git and GitHub.

**Describe the solution you'd like**
Rename default branch to "10.x" or "main".

**Additional context**
I did this for all of the Consolidation projects; it requires some updates to the CI jobs, but isn't too difficult. Open PRs might need to be recreated, but we only have 42.

**Comment by pbull** [comment]
Github now allows project admins to edit the base branch of an open PR, so any open merges against `master` could be updated to use the new main branch after it is created.

**Comment by jcnventura** [comment]
Shouldn't the branch be deleted then?

**Comment by weitzman** [comment]
Yes, we plan to do that once Github finishes https://github.com/github/renaming/
