### ISSUE TITLE
A point release of 8.x for D9 compatibility) 

### ISSUE THREAD

**Issue by seamuslee001** [drush-ops/drush#4487]
@greg-1-anderson is it possible to get another point release of Drush 8.x, I'm one of the maintainers of the CiviCRM Project and we have a standard tool for creating demo sites and it mostly works for Drupal 9 but the role add perm causes the build process to fail. (You have merged a PR of mine in on that but just not included in a tagged release) Also i see there is a potentially useful improvement for MySQL 8 that hasn't been released yet in a tagged release either which probably will help people who install drush on Ubuntu Focal as I believe that is MySQL 8 by default

**Comment by greg-1-anderson** [comment]
Released [8.3.6](https://github.com/drush-ops/drush/releases/tag/8.3.6).

**Comment by seamuslee001** [comment]
Thanks mate
