### ISSUE TITLE
PHP Segfault error when running a migration with drush

### ISSUE THREAD

**Issue by amangrover90** [drush-ops/drush#4509]
I'm trying to run the users migration from Drupal 7 to Drupal 8 using migrate_tools module.

**To Reproduce**
drush mim upgrade_d7_user -vvv    (To import the users from D7 to D8, this migration got generated with drush migrate upgrade command)

**Expected behavior**
Migration completed/failed with a success/failure message.

**Actual behavior**
Drush command terminates and shows PHP Segfault error. (Migration status is left to importing and I have to change the status to idle to run it again.)

**Workaround**
Is there another way to do the desired action?
I can execute the migration from UI from /admin/structure/migrate/manage/migrate_drupal_7/migrations/upgrade_d7_user.
When I run this migration from UI, I don't see this error.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.1 (please be specific, and try latest release)
| Drupal version? | 8.9.1
| PHP version     | 7.3
| PHP Memory | Current 4GB | Previous 512MB| Tried setting the PHP memory to higher value to check if it resolves but no luck. 
| OS?             | Linux Centos 7

**Additional information**
https://gist.github.com/amangrover90/bef2e9185b267b5d7ed13160aa360ffc

Tried running the drush command with verbose but couldn't get any useful info.

I understand this might not be the right forum for this question but if someone could help me out with this, that will be extremely helpful. I'm stuck at this for some time now.

**Comment by weitzman** [comment]
migrate tools no longer supported
