### ISSUE TITLE
Drush::redispatchOptions() no longer includes shortcut options (-y); drush deploy fails on running config:import

### ISSUE THREAD

**Issue by davereid-pfg** [drush-ops/drush#4512]
**Describe the bug**
Running `drush deploy -y -v` should expect to pass through the "yes" and "verbose" options to each subcommand. This will fail when sub-processes expect those inputs to be present.

**To Reproduce**
Run `drush deploy -y -v` on a site that has configuration imports to process with the config:import step.

**Expected behavior**
That `drush config:import -y` would get run in the sub-process of the deploy command.

**Actual behavior**
`drush config:import` gets run without any yes confirmation option, blocking the command from proceeding.

Note the missing options added to the sub-process commands:
```
drush deploy -y -v
 [notice] Database updates start.
 [info] Executing: /app/vendor/drush/drush/drush updatedb --no-cache-clear --uri=***--root=/app/web
>  [success] No pending updates.
 [success] Cache rebuild start.
 [info] Executing: /app/vendor/drush/drush/drush cache:rebuild --uri=*** --root=/app/web
>  [success] Cache rebuild complete.
 [success] Config import start.
 [info] Executing: /app/vendor/drush/drush/drush config:import --uri=*** --root=/app/web
>  [notice] There are no changes to import.
 [success] Cache rebuild start.
 [info] Executing: /app/vendor/drush/drush/drush cache:rebuild --uri=***--root=/app/web
>  [success] Cache rebuild complete.
 [success] Deploy hook start.
 [info] Executing: /app/vendor/drush/drush/drush deploy:hook --uri=*** --root=/app/web
>  [success] No pending deploy hooks.
```

**Workaround**
Using the long form of `--yes` does work.

```
drush deploy --yes --verbose
 [notice] Database updates start.
 [info] Executing: /app/vendor/drush/drush/drush updatedb --no-cache-clear --verbose --yes --uri=***--root=/app/web
>  [info] helper should have an extra.drush.services section in its composer.json. See http://docs.drush.org/en/10.x/commands/#specifying-the-services-file.
>  [info] Executing: /app/vendor/drush/drush/drush updatedb:status --no-entity-updates --uri=***--root=/app/web
>  [success] No pending updates.
 [success] Cache rebuild start.
 [info] Executing: /app/vendor/drush/drush/drush cache:rebuild --verbose --yes --uri=*** --root=/app/web
>  [success] Cache rebuild complete.
 [success] Config import start.
 [info] Executing: /app/vendor/drush/drush/drush config:import --verbose --yes --uri=*** --root=/app/web
>  [info] helper should have an extra.drush.services section in its composer.json. See http://docs.drush.org/en/10.x/commands/#specifying-the-services-file.
>  [notice] There are no changes to import.
 [success] Cache rebuild start.
 [info] Executing: /app/vendor/drush/drush/drush cache:rebuild --verbose --yes --uri=*** --root=/app/web
>  [success] Cache rebuild complete.
 [success] Deploy hook start.
 [info] Executing: /app/vendor/drush/drush/drush deploy:hook --verbose --yes --uri=*** --root=/app/web
>  [info] helper should have an extra.drush.services section in its composer.json. See http://docs.drush.org/en/10.x/commands/#specifying-the-services-file.
>  [success] No pending deploy hooks.
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.2
| Drupal version? | 8.9
| PHP version     | 7.3
| OS?             | Mac

**Additional information**

**Comment by davereid-pfg** [comment]
The example for drush deploy says to use the short options: https://github.com/drush-ops/drush/blob/master/src/Commands/core/DeployCommands.php#L20

```
     * @usage drush deploy -v -y
     *   Run updates with verbose logging and accept all prompts.
```

**Comment by davereid** [comment]
Looks like the issue is that these are getting filtered out in `Drush::redispatchOptions()`:

`$options = $input->getOptions();`:
```
array (
  'help' => false,
  'quiet' => false,
  'verbose' => true,
  'version' => false,
  'ansi' => true,
  'no-ansi' => false,
  'no-interaction' => false,
  'debug' => false,
  'yes' => true,
  'no' => false,
  'remote-host' => NULL,
  'remote-user' => NULL,
  'root' => '/mnt/c/Projects/drupal-88/web',
  'uri' => 'https://88.drupal.test/',
  'simulate' => false,
  'pipe' => false,
  'define' =>
  array (
  ),
  'druplicon' => false,
  'notify' => NULL,
  'xh-link' => NULL,
)
```

But `$optionNamesFromCommandline = self::config()->get('runtime.options');` returns the short names used, not the long form names:
```
array (
  2 => 'y',
  3 => 'v',
  4 => 'ansi',
)
```

So when we array_intersect_key() on the two, "yes" and "verbose" get filtered out:
```
        // Remove anything in $options that was not on the cli
        $options = array_intersect_key($options, array_flip($optionNamesFromCommandline));
```

**Comment by greg-1-anderson** [comment]
I'm guessing this is Drush 10 vs. Drush 8 behavior. I seem to recall that Drush 8 normalized the option name before filtering.

**Comment by weitzman** [comment]
To expand on Greg's comment, `$input->getOptions()` are already canonicalized to long option names. Its `runtime.options` that needs canonicalizing. I'm not sure how to do that. Any ideas @greg-1-anderson? `runtime.options` gets set at https://github.com/drush-ops/drush/blob/5117a8a363101e5a6437a1901f94704b1819c574/src/Preflight/PreflightArgs.php#L169. It might have to move later, like into \Drush\Runtime\Runtime::doRun

**Comment by greg-1-anderson** [comment]
It's important that `runtime.options` remain non-canonical as stored, as they are sometimes passed as-is, e.g. as extended options to `rsync` or some other tool where the options are not necessarily Drush options.

So, `Drush::redispatchOptions()` will need to fetch `runtime.options` and then canonicalize short options. I think that given a reference to the Symfony application, we can get a reference to the input definitions (might need a reference to the command first), and from that list we could look up the short and long option name from each definition.

**Comment by weitzman** [comment]
thanks. I think I now have enough info to take this one.

**Comment by weitzman** [comment]
@davereid please try #4515 if you can.

I'm perplexed why this has not come up until now. It seems like this would be a widespread problem/frustration.

**Comment by davereid** [comment]
I'm guessing since the new deploy command is the one that makes the heaviest use of the redispatch options, but yeah I would have expected this to come up sooner. 🤷

**Comment by weitzman** [comment]
Lots of commands use it internally. sql:sync, user:login, config:pull, ...
