### ISSUE TITLE
db-prefix doesn't seem to work on Drupal9

### ISSUE THREAD

**Issue by rgpublic** [drush-ops/drush#4514]
I might be wrong but the following command just doesn't work on any of my D9 sites:

```
 drush sql:query -vvv  --db-prefix 'SELECT * FROM {users}'
```

Due to the "-vvv" the actual command that is run is shown. On D8 sites this is:

```
SELECT * FROM drupal_users
```

But on D9 sites this is:
```
SELECT * FROM "drupal_users"
```

which is wrong. The table name must no be quoted. This results in a "Query error". Don't know why it happens, though. Very mysterious...

**Comment by weitzman** [comment]
Lets just use the PR
