### ISSUE TITLE
Security check is throwing error 

### ISSUE THREAD

**Issue by jedgar1mx** [drush-ops/drush#4523]
**Describe the bug**
Drush security check is throwing an error even though the version of the module is not actually affected

```
[warning] One or more of your dependencies has an outstanding security update.
[notice] Try running: composer require drupal/group --update-with-dependencies
[notice] If that fails due to a conflict then you must update one or more root dependencies.

+--------------+-------------------+
Name Installed Version
+--------------+-------------------+
drupal/group 1.0.0-rc5
+--------------+-------------------+
```

According to the security issue `1.0-rc5` is not affected
https://www.drupal.org/sa-contrib-2020-033

**To Reproduce**
1. Install `group` version `1.0.0-rc5`
2. Run security check
3. See error

**Expected behavior**
It should only return an error based on the actual version used.

**Actual behavior**
Error is being return as a security update

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.2
| Drupal version? | 8.9.3
| PHP version     |  7.4.6
| OS?             | Linux

**Comment by weitzman** [comment]
Thats an informal note from the security team. Both Drupal and Drush are marking rc5 as insecure.
