### ISSUE TITLE
Running Drush with one specific PHP CLI setting like PHPUnit (e.g. enabling Xdebug)

### ISSUE THREAD

**Issue by jepster** [drush-ops/drush#4529]
**Describe the bug**
I am searching for a possibility to run Drush in an isolated PHP process with Xdebug enabled. Currently I must enable Xdebug in my php.ini file. That influences all my PHP processes. But I would like to run the Drush PHP process with just one specific PHP setting like I am able with PHPUnit. E.g.:

```
/bin/php -d xdebug.remote_enable=true phpunit
```
The above command enables Xdebug for just one PHP process. This is currently not possible with Drush. I am wondering so much about that, because Drush needs the PHP cli for being run.

I have also tried the DRUSH_PHP environment variable, but that is too global. I would like just to pass one PHP setting to the Drush PHP process.

Question: Is there any possibility to run Drush by the PHP CLI interpreter with one specific PHP setting? A quick way for enabling/disabling Xdebug is important for PHP developers.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.7.2
| Drupal version? | 8.8
| PHP version     | 7.3
| OS?             | Mac

**Comment by weitzman** [comment]
`/bin/php -d xdebug.remote_enable=true vendor/bin/drush` works that same way, for most commands. it wouldn't work for commands that redispatch into a new process. What would work in that case is using `PHPRC=/path/to/particular/php.ini vendor/bin/drush`. See https://github.com/drush-ops/drush/issues/3294#issuecomment-370201342. Also see the link at top of that comment to an alternative approach involving `PHP_INI_SCAN_DIR`

**Comment by jepster** [comment]
Thanks for your reply! I am able to successfully switch between Xdebug enabled/disabled by using the PHPRC variable and a separate php.ini file with enabled Xdebug:
```
PHPRC=/opt/local/etc/php73/php-xdebug.ini drush scr test-script.php
```
