### ISSUE TITLE
Support DelayedRequeueException (added in Drupal 9.1.x)

### ISSUE THREAD

**Issue by catch56** [drush-ops/drush#4543]
Drupal core just added DelayedRequeueException - it allows an item to be silently re-added to a queue, for a specified amount of time.

An example use-case is in queue_mail, which currently has to throw regular exceptions (which in turn cause jenkins jobs to show us unstable): https://www.drupal.org/project/queue_mail/issues/3151991

For drush to support this, it more or less needs to do the same as the cron queue runner in core.

More details in the issue and CR:

https://www.drupal.org/project/drupal/issues/3116478
https://www.drupal.org/node/3127239
And the commit: https://git.drupalcode.org/project/drupal/commit/0f10d21

**Comment by weitzman** [comment]
Thanks for leaving a note here. PR welcome.
