### ISSUE TITLE
Make it possible to configure commands without annotations

### ISSUE THREAD

**Issue by andrewbelcher** [drush-ops/drush#4545]
**Is your feature request related to a problem? Please describe.**
Whilst I understand the usefulness of annotation based command discovery for easy of entry and simplicity for simple commands, I (and other people I've spoken to) find the annotations very unintuitive and with a lot of hidden quirks (especially around things like the default value for options). Having worked with symfony console and drupal console, a configure method is much more explicit and intuitive and allows greater control over the arguments. It would be great it drush also supported this as a method of command registration.

**Describe the solution you'd like**
Ability to configure commands in a pattern more similar to [symfony console/drupal console](https://symfony.com/doc/current/console.html). I understand the pattern in Drush likely means it wont be identical. Perhaps something like a `configureCommands` method which returns a `\Symfony\Component\Console\Command\Command[]` might be a possible approach?

**Describe alternatives you've considered**
We could try and get this into `consolidation/annotated-command`, but it would seem odd to go there. I think a separate pass in drush app would be more appropriate.

**Comment by weitzman** [comment]
Good news - Drush already has that pass and thus supports discovery and execution of Symfony Console commands. See [this test](https://github.com/drush-ops/drush/blob/eed106ae4510d5a2df89f8e7fd54b41ffb0aa5fa/tests/integration/AnnotatedCommandCase.php#L178-L180) and [this commandfile](https://github.com/drush-ops/drush/blob/049d2a4b36338178c0c7cf89b8e7caf9769524c9/tests/functional/resources/modules/d8/woot/src/Commands/GreetCommand.php). We  should  add this to the docs.

**Comment by andrewbelcher** [comment]
Oh, great! Thanks!
