### ISSUE TITLE
Unable to require because of ezsystems/ezplatform-related exception

### ISSUE THREAD

**Issue by geerlingguy** [drush-ops/drush#4546]
**Describe the bug**

As of this afternoon, I can't add Drush to my new Drupal projects (discovered initially via CI jobs that did this automatically for Drupal VM), and it seems to be due to a version constraint parsing issue with the `ezsystems/ezplatform` project (which does not have an open issue queue).

**To Reproduce**

```
composer require drush/drush:^10
```

**Expected behavior**

Drush would be added to my project.

**Actual behavior**

Error message:

```
[RuntimeException] Could not load package ezsystems/ezplatform in http://repo.packagist.org:
[UnexpectedValueException] Could not parse version constraint dev-load-varnish-only-when-used as ^2.0@dev: Invalid version string "^2.0@dev"
```

**Workaround**

Not that I'm aware of.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.x
| Drupal version? | 9.x
| PHP version     | 7.x
| OS?             | Linux

**Additional information**

N/A

**Comment by greg-1-anderson** [comment]
ezsystems/ezplatform does not appear to be a dependency of Drush. 

`^2.0@dev` should be `2.0@dev`. This somehow needs to be fixed in the project where the error occurs.

**Comment by geerlingguy** [comment]
I found this: https://github.com/composer/composer/issues/9191

Looks like it is actually a Composer bug, and may have just been fixed.

**Comment by geerlingguy** [comment]
It looks like the latest version of Composer _did_ fix the bug: https://travis-ci.org/github/geerlingguy/drupal-vm

Sorry for the noise!
