### ISSUE TITLE
Use the same rules to discover global Generators and site-wide Commands

### ISSUE THREAD

**Issue by DuaelFr** [drush-ops/drush#4547]
**Is your feature request related to a problem? Please describe.**
We can provide Commands by creating a `drupal-drush` package which is stored in a `drush/Commands/{$name}` by default in drupal-composer/drupal-project and drupal/recommended-project. The `\Drush\Application::configureAndRegisterCommands()` method also discovers `Generators` and `Hooks` within the same directories apparently.

The thing is that the `\Drush\Commands\generate\GenerateCommands::createApplication()` method sets a different way to discover `Generators` that does not include the ones defined within a `drupal-drush` package.

**Describe the solution you'd like**
I wish we could also provide `Generators` in our packages and it would be really awesome if we could sort `Commands`, `Hooks` and `Generators` files in their own directories.

**Describe alternatives you've considered**
Drupal Console allows to define commands and thus generators in a `drupal-console-library` package and allows to declare where to find the files using the `autoload` key in the `composer.json` of the package.

**Comment by weitzman** [comment]
I suspect we should also use the `autoload` key. I havent studied it much so cant detail more.

**Comment by DuaelFr** [comment]
That'd be nice :)

**Comment by weitzman** [comment]
Use PSR4 discovery. Works for generators and commands. [Drupal Test Traits](https://gitlab.com/weitzman/drupal-test-traits/-/merge_requests/127) is an example.
