### ISSUE TITLE
sites/default/drush.yml no longer loaded?

### ISSUE THREAD

**Issue by plato1123** [drush-ops/drush#4551]
The documentation seems to suggest sites/default/drush.yml is a location where the base url can be set (for auto-generated links like login links).  Is this no longer a valid config location?  I had hoped to be able to set the base url for all of our developer's lando boxes to be the same, ergo:
options:
  uri: 'https://kstat.lndo.site/'

but the location of the other config files don't seem like they're really appropriate for version control.  Has this changed, is sites/default/drush.yml no longer valid?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.72
| Drupal version? | 8.86
| PHP version     | 7.1
| OS?             | Linux

**Comment by weitzman** [comment]
That file is loaded too late for setting uri. Use an env variable instead as per https://github.com/drush-ops/drush/blob/11710180cfeb9bc64d8331ca237ae9c4fa76afd7/examples/example.drush.yml#L38-L42

**Comment by JonMcL** [comment]
Strangely, sites/all/drush/drush.yml does work. I don't think sites/all/ is really appropriate for Drupal 8, is this possibly a bug? Same version of drush (9.7.2), Drupal version 8.9.6. I am using a /web docroot.

The file does appear to load early enough to set uri in the sites/all/drush/drush.yml location.

**Comment by weitzman** [comment]
> Simplest solution would probably be to use /drush/drush.yml for everything, but we have developers using different hostnames :)

Right, so I'd have them set `DRUSH_OPTIONS_URI` as an env variable on their local system.

**Comment by AdamPS** [comment]
I have a similar requirement.  I read through this issue and it didn't solve my situation so I raised #4638.

**Comment by weitzman** [comment]
Lets continue in #4345
