### ISSUE TITLE
Installation Documentation Missing for 10.x / master

### ISSUE THREAD

**Issue by mdrmike** [drush-ops/drush#4564]
**Describe the bug**
Drush Documentation for **9.x** or **10.x** and **master** is nonexistent. I'm unsure if this is "by design" ... but its confusing. 

**To Reproduce**
Followed link on Drupal.org docs that led to: https://docs.drush.org/en/master/install/

**Expected behavior**
Expect to see documentation

**Actual behavior**
404 page not found
![screenshot_20201001-121257](https://user-images.githubusercontent.com/259940/94853998-12087080-03e1-11eb-8a64-cd5326a5d2b1.png)

**Workaround**
look at ver 8.x docs ... but for installation, and many things, this seems really wrong.

**Comment by mdrmike** [comment]
Oh, just retried link and apparently [9.x docs exist](https://docs.drush.org/en/9.x/install/) for this link... and now makes clear (to me) why documentation is missing.   

both master and 10.x are missing this same doc as 9.x

**Comment by weitzman** [comment]
Docs have been integrated into www.drush.org site. Please update that drupal.org link. Inbound links from drupal.org and elsewhere are not managed Drush team.

**Comment by mdrmike** [comment]
Thanks for the quick reply, and makes sense. Though, this fixes my understanding plus I fixed the link on drupal.org, you're welcome, I'm afraid it won't solve all the other links on the internet that point to:

 https://docs.drush.org/en/master/FOOBAR  <-- Still should have a redirect, IMHO
