### ISSUE TITLE
Provide an example with former drush_backend_invoke_concurrent() for Drush 10

### ISSUE THREAD

**Issue by artemvd** [drush-ops/drush#4567]
**Is your feature request related to a problem? Please describe.**
Drush 9 and earlier had the ability to run the processes in parallel with drush_backend_invoke_concurrent() function, the php method documentation says that it was deprecated and Drush::drush() should be used instead, but as I understood it is only for 1 process. How is it possible to run concurrent processes in Drush 10?

**Describe the solution you'd like**
Provide an example on how to change the script that had drush_backend_invoke_concurrent() in Drush 9 to work with Drush 10.

**Describe alternatives you've considered**
I tried Drush::drush() but it runs only 1 process.

**Additional context**
The code that I try to make to work:

```
  /**
   * Spin off a specific number of concurrent workers to run queues.
   *
   * @param int $concurrency
   *   The number of worker queues to start.
   *
   * @return int
   *   The number of queue items processed by the worker queues.
   */
  public function invokeWorkers($concurrency) {
    $invocations = array_fill(0, $concurrency, [
      'site' => '@self',
      'command' => 'queue:run-concurrent',
      'args' => [$this->name],
    ]);
    // Set the timer name.
    $timer_name = 'queue_run_' . $this->name . '_' . $concurrency;

    $commandline_options = [
      'concurrency' => 1,
      'no-reclaim' => TRUE,
      // Internal flag to indicate this is a worker queue.
      'strict' => 0,
      'is-worker' => TRUE,
    ];
    foreach (['override-time-limit'] as $option) {
      $value = $this->options[$option];
      if (isset($value)) {
        $commandline_options[$option] = $value;
      }
    }
    $backend_options = [
      'concurrency' => count($invocations),
    ];

    $queue_item_count = $this->queue->numberOfItems();

    $this->logger->info(dt("Starting @concurrency queue @name workers. There are @count items in the queue.", [
      '@concurrency' => $concurrency,
      '@name' => $this->name,
      '@count' => $queue_item_count,
    ]));

    $this->getTimeLimit();

    Timer::start($timer_name);
    $results = drush_backend_invoke_concurrent($invocations, $commandline_options, $backend_options);
    $elapsed = Timer::read($timer_name);

    // Calculate the number of items actually processed using the results from
    // the drush_backend_invoke_concurrent() call.
    $count = 0;
    if (!empty($results['concurrent'])) {
      foreach ($results['concurrent'] as $result) {
        foreach ($result['log'] as $log) {
          if (preg_match('/Processed (\d+) items from queue ' . preg_quote($this->name, '/') . '/', $log['message'], $matches)) {
            $count += $matches[1];
          }
        }
      }
    }

    // Force the database connection to be reconnected since the workers may
    // have run for an extended amount of time.
    Database::closeConnection();
    $message = dt("Concurrently processed @count items from queue @queue in @elapsed sec (@rate/min). There are @remaining remaining items.",
      [
        '@count' => $count,
        '@queue' => $this->name,
        '@elapsed' => round($elapsed, 2),
        '@rate' => round(($count / $elapsed) * 60),
        '@remaining' => $queue_item_count - $count,
      ]
    );

    if (drush_get_error()) {
      $this->logger->warning($message);
    }
    else {
      $this->logger->success($message);
    }

    return $count;
  }
```

More information here https://www.drupal.org/project/concurrent_queue/issues/2701609

**Comment by greg-1-anderson** [comment]
Drush 10 recommends against managing your concurrent processes in PHP. The technique above is fine, and everyone is welcome and encouraged to do that if they wish, but we will not support it here.

Instead, we recommend making your Drush commands single-process, and then run them with [Gnu Parallel](https://www.gnu.org/software/parallel/).

**Comment by artemvd** [comment]
Thanks, @greg-1-anderson . I also think that some external process manager will handle it better. Concurrent Queue module was just intended to be an alternative to them, in case you are not allowed to install 3rd party software on the server (shared hosting or limited hosting).

I read a bit about how Symfony does it and they recommend [Supervisor](https://symfony.com/doc/current/messenger.html#supervisor-configuration) (for those who are interested).
