### ISSUE TITLE
Drush install Drupal on MYSQL SSL DB

### ISSUE THREAD

**Issue by quadrinho** [drush-ops/drush#4569]
**Describe the bug**
Hello,

we have our MYSQL DB with SSL Option forced and we need to know how install drupal using drush command.

Usually we use a command like this one:

drush -y site-install portal --db-url=mysql://xxx:XXXX@my_host_db:3306/portal--account-name=admin --account-pass=admin --account-mail=pippo@pippo.com --locale=en --site-name='Admin' --site-mail=pippo@pippo.com

Can you tell us if there is a drush option about the SSL CA of database?

Thanks a lot!

**To Reproduce**
What did you do?

**Expected behavior**
What did you expect would happen?

**Actual behavior**
What happened instead?

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.1.16
| Drupal version? | 8
| PHP version     | 7.4
| OS?             | Mac/Linux/Windows

**Additional information**

**Comment by weitzman** [comment]
You will probably have to write out a settings.php and then run `site:install`
