### ISSUE TITLE
Allow use DRUSH_OPTIONS_URI environment variable for Drush 8.x

### ISSUE THREAD

**Issue by nevergone** [drush-ops/drush#4578]
**Is your feature request related to a problem? Please describe.**

Please allow use DRUSH_OPTIONS_URI environment variable, because it would be much easier set site URI.

**Comment by nevergone** [comment]
A little interesting comment:
Drush 4.x - Drupal 5.x related patch: https://gist.github.com/nevergone/b3071593ad1c953fc09f7f19b361cbc5
Drush 7.x - Drupal 6.x related patch: https://gist.github.com/nevergone/d0df33718a5f5d508591cd433cc9623e

**Comment by weitzman** [comment]
this was merged into 8.x

**Comment by greg-1-anderson** [comment]
n.b. also Drush 8 still tests with Drupal 6, so you shouldn't need to use Drush 7. You're on your own for Drupal 5 and Drush 4, though; those are not supported. (I don't even remember where Drupal 5 support was dropped from Drush; I thought you had to go back to Drush 3 or Drush 2 for Drupal 5.)

**Comment by nevergone** [comment]
Thanks, but Drush 8.x not works with PHP 5.3.x (fully compatible with Drupal 6).

**Comment by greg-1-anderson** [comment]
"PHP 5.3; that's a name I have not heard in a long, long time."

    - Obi Wan Kenobi, Jedi and former Drush maintainer
