### ISSUE TITLE
DrupalBoot doesn't pass the app root to Drupal's kernel

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#4584]
**Describe the bug**

bootstrapDrupalConfiguration() creates the DrupalKernel, but it doesn't pass in the app root:

```
        $this->kernel = $kernel_factory($request, $classloader, 'prod', $allow_dumping);
```

This causes DrupalKernel to guess the app root all over again. In certain circumstances, this could be wrong.

In particular, if Drupal core is symlinked in by Composer (see https://github.com/joachim-n/drupal-core-composer), then DrupalKernel will deduce its app root to be inside the git clone outside of the web root, whereas Drush will have correctly deduced the app root in the Composer project.

**To Reproduce**

Set up Drupal with https://github.com/joachim-n/drupal-core-composer.

**Workaround**

Not AFAICT.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.x
| Drupal version? | 9.x
| PHP version     | 7.4
| OS?             | Mac

**Comment by weitzman** [comment]
Merged in #4585
