### ISSUE TITLE
pm:enable should be pm:install

### ISSUE THREAD

**Issue by jhodgdon-drp** [drush-ops/drush#4588]
**Describe the bug**
In Drupal 8.x and above, there is no longer a way to "enable/disable" modules. Instead we "install/uninstall" them.

However, Drush still has a pm:enable command along with pm:uninstall.

This is confusing (enable is the opposite of uninstall?) and inconsistent with the Drupal UI.

**To Reproduce**
List commands in Drush and you'll see that pm:enable turns a module on, and pm:uninstall turns it off (which also involves adding/removing configuration, database tables, and/or content).

**Expected behavior**
The pm:enable command should be named pm:install for consistency with the Drupal UI and with the pm:uninstall command.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.x
| Drupal version? | 9.x/8.x
| PHP version     | any
| OS?             | any

**Additional information**
Drupal core issue about making the Drupal UI more consistent in this area:
https://www.drupal.org/project/drupal/issues/2891294
which is part of a meta issue:
https://www.drupal.org/project/drupal/issues/2888657

**Comment by greg-1-anderson** [comment]
+1 we can keep pm:enable as an alias, so there is little cost to doing this.

**Comment by weitzman** [comment]
Yeah, this is a good proposal.

**Comment by rajeshreeputra** [comment]
I have create PR https://github.com/drush-ops/drush/pull/5061
Also kept alias **"install, pm-install, en, pm-enable, pm:enable"** for **pm:install**
@weitzman could you please review changes in PR.

**Comment by gitressa** [comment]
This is an improvement, but for consistency, shouldn't we also add an `un` alias for `pm:uninstall`, just as `pm:install` has `in`?

**`pm:install`**
```
Aliases: in, install, pm-install, en, pm-enable, pm:enable
```

**`pm:uninstall`**
```
Aliases: pmu, pm-uninstall
```

**Comment by gitressa** [comment]
I created a PR which adds a `un` alias, #5131.

```
$ drush | grep pm:uninstall
  pm:uninstall (un, pmu)      Uninstall one or more modules and their dependent modules.

$ drush un diff
 [success] Successfully uninstalled: diff
```
