### ISSUE TITLE
symlinked drush/drush can't find the autoloader.php (Backport)

### ISSUE THREAD

**Issue by Sweetchuck** [drush-ops/drush#4591]
When the "drush/drush" package referred in the "composer.json" of a main project like bellow,
then Drush throws the following exception:

> Fatal error: Uncaught Exception: Could not locate autoload.php. cwd is /foo/my_project_01; \_\_DIR\_\_ is /bar/drush/drush-10.x in /bar/drush/drush-10.x/drush.php on line 58

```json
{
    "repositories": {
        "drush/drush": {
            "type": "path",
            "url": "../../drush/drush-10.x"
        },
    },
    "require": {
        "drush/drush": "^10.3"
    }
}
```

**Comment by Sweetchuck** [comment]
maybe the `$cwd . '/vendor/autoload.php'` should be handled with higher priority than the `__DIR__ . '/vendor/autoload.php'`

**Comment by heitoralthmann** [comment]
Hi @Sweetchuck! Did this ever get merged?

I'm currently having this issue on a platform.sh Drupal site. Did you find anything new since you last worked on this?

Thank you!

**Comment by Sweetchuck** [comment]
@heitoralthmann I use this patch locally :
```patch
diff --git a/drush.php b/drush.php
index 61275fb2a..44eef4357 100755
--- a/drush.php
+++ b/drush.php
@@ -49,7 +49,16 @@ $cwd = isset($_SERVER['PWD']) && is_dir($_SERVER['PWD']) ? $_SERVER['PWD'] : get
 
 // Set up autoloader
 $loader = false;
-if (file_exists($autoloadFile = __DIR__ . '/vendor/autoload.php')
+
+$composerFileName = $cwd . '/' . (getenv('COMPOSER') ?: 'composer.json');
+$vendorDir = 'vendor';
+if (file_exists($composerFileName)) {
+  $composer = @json_decode(file_get_contents($composerFileName), TRUE);
+  $vendorDir = $composer['config']['vendor-dir'] ?? 'vendor';
+}
+
+if (file_exists($autoloadFile = "$cwd/$vendorDir/autoload.php")
+    || file_exists($autoloadFile = __DIR__ . '/vendor/autoload.php')
     || file_exists($autoloadFile = __DIR__ . '/../autoload.php')
     || file_exists($autoloadFile = __DIR__ . '/../../autoload.php')
 ) {

```

**Comment by heitoralthmann** [comment]
Thanks @Sweetchuck!

In the end I got my issue fixed by updating the project to composer 2. 🤷‍♂️ 

In my specific case (a Platform.sh Drupal install), all I had to do was to update this section on my `.platform.app.yml`.

```yaml
dependencies:
  php:
    composer/composer: '^2.0'
```

Hope it might help someone in the future.
Thanks again, Andor.

**Comment by Sweetchuck** [comment]
That is strange. I also use Composer v2, but I think this problem is not related to Composer.
Problem is that the `__DIR__` always leads to the absolute directory of drush/drush (which is outside of the main project directory in case of symlink used) instead of the root of the main project, from where the `./vendor/autoload.php` should be used.

**Comment by amirehman** [comment]
If anyone still facing the problem. here is my fixed 
So basically for some reason, you have to install composer inside the Drush directory. so in my case I went inside `cd /usr/local/src/drush/` and `composer update` and that's it. it fixed my problem.

**Comment by Marzaan** [comment]
Thank you @amirehman 
Your solution worked for me.

**Comment by philippjorek** [comment]
i got the same error. After doing this, it works:

Main folder:
composer global require drush/drush:10.2.2
export PATH="$HOME/.config/composer/vendor/bin:$PATH"
drush --version 
-> Shows Drush version 10.2.2

BUT after restart, the bug comes again:
`PHP Fatal error:  Uncaught Exception: Could not locate autoload.php. cwd is /root; __DIR__ is /usr/local/src/drush in /usr/local/src/drush/drush.php:58
Stack trace:
#0 /usr/local/src/drush/drush(4): require()
#1 {main}
  thrown in /usr/local/src/drush/drush.php on line 58`
  
  any new ideas?
  
drush: 10.2.2
composer: 2.4.4
php: 7.2.34
git version 2.17.1
ubuntu 22

**Comment by weitzman** [comment]
This is fixed in  #5455 for Drush 12. I think it could be backported to Drush 11 without adding a Composer 2.2+ requirement.

**Comment by weitzman** [comment]
Perhaps folks here can test https://github.com/drush-ops/drush/pull/5456? You can include the PR branch via composer or do the 1 line edit by hand.

**Comment by Sweetchuck** [comment]
I can confirm that branch `weitzman:better-bin-11` fixes the problem :-)
> Composer version 2.5.0 2022-12-20 10:44:08

**Comment by weitzman** [comment]
Thanks @Sweetchuck ... Merged!
