### ISSUE TITLE
Drupal 6 install issue with drush8

### ISSUE THREAD

**Issue by attilafekete** [drush-ops/drush#4594]
**Describe the bug**
The newer drush8 is handling Drupal 6 install differently and it is causing issues.

Specifically, if the database settings are already set in the settings.php and file is read-only, the site-install command will fail. 

Newer drush versions are trying to write to the 'sites/default/settings.php' and are failing to do so. There is a new function that does this (drush8/vendor/drush/drush/commands/core/site_install.drush.inc):
```
function _drush_core_site_install_add_db_url_to_settings($settingsfile, $db_spec) {
  $settingsContents = file_get_contents($settingsfile);
  if (preg_match('#^.db_url *=#', $settingsContents)) {
    return true;
  }
  // On D6, we have to write $db_url ourselves. In D7+, the installer does it.
  if (file_put_contents($settingsfile, "\n" . '$db_url = \'' . drush_convert_db_url(drush_get_option('db-url')) . "';\n", FILE_APPEND) === false) {
    return false;
```

I'd expect the preg_match() to find the existing db_url line but it apparently won't.

**To Reproduce**
Have a Drupal 6 settings.php file that sets $db_url through an include file (or have a Drupal 6 settings.php file that has $db_url setting already set).

**Expected behavior**
It seems that regexp ''#^.db_url *=#'' can be satisfied with an existing/fake line in settings.php e.g.
```
// The following line must be present to trick Drush >= 8.1.19 into thinking the db_url 
// is present in this file, otherwise drush site-install will try to write to this file:
#db_url =
```

**Actual behavior**
The `if (preg_match('#^.db_url *=#', $settingsContents)) {` condition will never return a TRUE value unless ?db_url is in the first line of settings.php.

**Workaround**
Manual intervention is needed to remove the added db_url setting (by the installer).

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.1.19+
| Drupal version? | 6.x
| PHP version     | 7.x
| OS?             | Mac/Linux/Windows

**Additional information**
n/a

**Comment by greg-1-anderson** [comment]
Since Drupal 6 is EOL, this is an edge case. You could probably work around it via the following code in settings.php:
```
include __DIR__ . '/settings.local.php'; // or whatever you are doing
$db_url = $db_url;
```
Drupal 6 is still supported by Drush 8, though, so if anyone wanted to submit a PR to make this setup work better, I would be open to it.

**Comment by attilafekete** [comment]
@greg-1-anderson thank you for your answer.

Yep I/we know that Drupal6 is EOL.

Your workaround would only work if the regexp would have the /m (multiline) modifier. In its current state, the regexp can only be satisfied if the
```
$db_url = ...
```
line is the first line of settings.php. In short, the 
```
if (preg_match('#^.db_url *=#', $settingsContents)) {
```
condition will never return TRUE unless the first line of settings.php starts with '<any character>db_url ='

But that won't work as you need at least an "<?" to indicate the beginning of php code and that's 2 characters, the regexp
```
#^.db_url *=#
```
only allows 1 char(any char) before the 'db_url' string,.. so quite impossible.

We're facing this issue with ACSF btw. We now have a workaround, but it would be nice to remove that workaround, and let  __drush_core_site_install_add_db_url_to_settings()_ - more specifically the regexp handle it.

I prepared a fix, a PR is on the way.

**Comment by attilafekete** [comment]
I slightly changed the regexp and added the /m multiline modifier: #4597

examples that will satisfy the regexp:
```
$db_url = ...
 $db_url = ...
 $db_url =
#$db_url = 
```

examples that won't satisfy the regexp:
```
db_url = ...
// $db_url = 'mysql://username:password@localhost/databasename';
 *   $db_url = 'mysql://username:password@localhost/databasename';
```
