### ISSUE TITLE
drush generate content-entity uses removed function link()

### ISSUE THREAD

**Issue by kmajzlik** [drush-ops/drush#4595]
**Describe the bug**
drush generate module-content-entity is putting $entity->link() into listBuilder class - public function buildRow(EntityInterface $entity) {}

**To Reproduce**
Generated custom entity.

**Expected behavior**
Not to use method which has been removed in Drupal 9.

**Actual behavior**
It used removed method, list of entities is having error for undefined method.

**Workaround**
Replace it as suggested in documentation: https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Entity!Entity.php/function/Entity%3A%3Alink/8.6.x

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.6
| Drupal version? | 9.0
| PHP version     | 7.4
| OS?             | Linux

**Comment by weitzman** [comment]
ping @Chi-teck

**Comment by Chi-teck** [comment]
Fixed in DCG 1.33.1

**Comment by kmajzlik** [comment]
Thank you!
