### ISSUE TITLE
The issue came back in newer Drush versions. The same conflict error persists.

### ISSUE THREAD

**Issue by l-laziz** [drush-ops/drush#4600]
@greg-1-anderson I I took a look at it again and I was able to make it work without deleting any files and having acquia dev desktop in place as well. So instead of deleting either drush or acquia dev desktop I was able to run locally drush that's in the vendor doing the following.

1. Using acquia dev desktop opened Drush Console
2. cd into vendor
3. ran just `drush`
4. cd into bin 
5. ran `drush cr`

This worked while keeping the vendor drush files intact. I was not able to run it to vendor/drush/drush locally (only locally) but noticed that there was a bin folder with drush there too and that worked. Seems like a known issue when having Acquia Dev Desktop installed: [Other users with the same issue](https://drupal.stackexchange.com/questions/271193/acquia-dev-desktop-and-drush-broken-with-syntax-is-incorrect)

_Originally posted by @MayraU in https://github.com/drush-ops/drush/issues/2152#issuecomment-690324961_

**Comment by weitzman** [comment]
Unclear problem statement - and does not follow template.
