### ISSUE TITLE
Error: [preflight] Drush::$container is not initialized yet. \Drush::setContainer() must be called with a real container.

### ISSUE THREAD

**Issue by tobiberlin** [drush-ops/drush#4604]
As I have this error only on one local Drupal / drush installation by now I am pretty sure it might be connected to this laptop - but I have no clue where to start / how to fix it. Maybe someone give me a hint.

Whenever I try to use drush I get the error message

`[preflight] Drush::$container is not initialized yet. \Drush::setContainer() must be called with a real container.`

I checked out our develop branch which is also checked out on our development server and tried the same on our development server. There drush runs as expected. I deleted the vendor folder where drush is installed and run `composer install` to get fresh files. No changes. I run `composer update drush/drush` but we have the latest version (10.3.6), Drupal is running on version 8.9.10, PHP 7.3.5 (laptop, local machine) and 7.3.23 on development server. I have PHP 7.3.5 on another local machine where it still works. 

On the same machine drush used to work - the problem just started today. Any ideas?

**Comment by greg-1-anderson** [comment]
I can't imagine why this would happen unless you changed the Drush preflight code. Would be interested to hear the cause once you figure it out.

**Comment by 2pha** [comment]
I was getting this with a site wide command calling `\Drupal::service('entity_type.manager')`.  
I had to add `@bootstrap full` to the annotations (is that what they are called?) above the function.

**Comment by greg-1-anderson** [comment]
Tricky; I would have expected a similar error from Drupal in that instance.

**Comment by greg-1-anderson** [comment]
I'm still kind of surprised; the Drush container should always be initialized before any site-wide command. 🤷
