### ISSUE TITLE
How to assign alias to group of sites in multisite mode in yml?

### ISSUE THREAD

**Issue by sjschukin** [drush-ops/drush#4605]
**Existing document**
https://www.drush.org/examples/example.site.yml/

**What are you attempting to do**
I need to execute drush command to several sites. I'd like to have multiple aliases including specific site groups with different sets for DEV and PROD.

Usage example:
`drush @mygroup.dev updatedb`

**In what way is the existing documentation unclear or incomplete**
I haven't found a solution. In previous version it was possible in php.

**What should the documentation say instead?**
An example implementation should be added to the yml if possible.

**Comment by greg-1-anderson** [comment]
The latest versions of Drush no longer support targeting multiple sites or multiple site environments with a single command. We recommend using [gnu parallel](https://www.gnu.org/software/parallel/) to do this task.
