### ISSUE TITLE
apt-get cannot find drush on Linux Mint 20

### ISSUE THREAD

**Issue by oprogramador** [drush-ops/drush#4613]
https://docs.acquia.com/blt/install/, linux tells `apt-get install git composer drush` but I get the following error (I don't want to install git or composer which are already installed and I need `sudo` for installing anything).
```
⟩ sudo apt-get install drush
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package drush
```

My OS: Linux Mint 20.

**Comment by weitzman** [comment]
We dont distibute via apt. Please file an issue against those docs.
