### ISSUE TITLE
TypeError on Drupal 9.2.x

### ISSUE THREAD

**Issue by mondrake** [drush-ops/drush#4614]
**Describe the bug**
When running `drush pml --type=module --no-core` on a dev Drupal 9.2.x install, getting

`TypeError: Argument 6 passed to Drush\Drupal\Commands\config\ConfigImportCommands::__construct() must implement interface Symfony\Component\EventDispatcher\EventDispatcherInterface, instance of Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher given, called in /home/runner/work/drudbal/drudbal/core/lib/Drupal/Component/DependencyInjection/Container.php on line 257 in Drush\Drupal\Commands\config\ConfigImportCommands->__construct() (line 200 of /home/runner/work/drudbal/drudbal/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php).`

This is not occurring on Drupal 9.1.x.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.6
| Drupal version? | 9.2.x
| PHP version     | 7.4
| OS?             | Ubuntu 20.4

**Comment by heddn** [comment]
This is likely related to https://www.drupal.org/project/drupal/issues/3161983

**Comment by weitzman** [comment]
Seems like removing the type hint fixes this issue while preserving backward compat, right?

**Comment by heddn** [comment]
That's how I would read things

**Comment by mondrake** [comment]
https://www.drupal.org/project/drupal/issues/3161983 was reverted.

**Comment by catch56** [comment]
Dropping the type hint makes sense for drush while it need to continue to support Drupal 8.9.

When Drupal 8.9 support is dropped, the type hint could be added back on the Symfony\Contracts version of the interface, which will work for both 9.x and 10.x
