### ISSUE TITLE
Cache-Rebuild fails in 10.3.6 with Drupal 8.9.11

### ISSUE THREAD

**Issue by werbfred** [drush-ops/drush#4618]
**Describe the bug**
When running drush cache-rebuild or drush cr I get the following stack trace 

>PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Symfony\Component\EventDispatcher\EventDispatcher::dispatch() must be an instance of Symfony\Component\EventDispatcher\Event or null, string given, called in C:\Users\foobar\AppData\Roaming\Composer\vendor\consolidation\annotated-command\src\Hooks\Dispatchers\CommandEventHookDispatcher.php on line 36 and defined in D:\www\\vendor\symfony\event-dispatcher\EventDispatcher.php:37
Stack trace:
#0 C:\Users\foobar\AppData\Roaming\Composer\vendor\consolidation\annotated-command\src\Hooks\Dispatchers\CommandEventHookDispatcher.php(36): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\Console\Event\ConsoleCommandEvent), 'console.command')
#1 C:\Users\foobar\AppData\Roaming\Composer\vendor\consolidation\annotated-command\src\Hooks\HookManager.php(424): Consolidation\AnnotatedCommand\Hooks\Dispatchers\CommandEventHookDispatcher->callCommandEventHooks(Object(Symfony\Component\Console\Event\ConsoleComman in D:\www\\vendor\symfony\event-dispatcher\EventDispatcher.php on line 37

>Fatal error: Uncaught TypeError: Argument 2 passed to Symfony\Component\EventDispatcher\EventDispatcher::dispatch() must be an instance of Symfony\Component\EventDispatcher\Event or null, string given, called in C:\Users\foobar\AppData\Roaming\Composer\vendor\consolidation\annotated-command\src\Hooks\Dispatchers\CommandEventHookDispatcher.php on line 36 and defined in D:\www\\vendor\symfony\event-dispatcher\EventDispatcher.php:37
Stack trace:
#0 C:\Users\foobar\AppData\Roaming\Composer\vendor\consolidation\annotated-command\src\Hooks\Dispatchers\CommandEventHookDispatcher.php(36): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\Console\Event\ConsoleCommandEvent), 'console.command')
#1 C:\Users\foobar\AppData\Roaming\Composer\vendor\consolidation\annotated-command\src\Hooks\HookManager.php(424): Consolidation\AnnotatedCommand\Hooks\Dispatchers\CommandEventHookDispatcher->callCommandEventHooks(Object(Symfony\Component\Console\Event\ConsoleComman in D:\www\\vendor\symfony\event-dispatcher\EventDispatcher.php on line 37
 [warning] Drush command terminated abnormally.

**To Reproduce**
Run drush cache-rebuild

**Expected behavior**
That cache is being rebuild and not getting an error

**Actual behavior**
Error with above stack trace

**Workaround**
Clearing cache via the Drupal GUI

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.6
| Drupal version? | 8.9.11
| PHP version     | 7.4.2
| OS?             | Windows

** Additional Notes **
Drush cache-rebuild works fine in Drupal 9.1.0 with Drush 10.3.6

**Comment by werbfred** [comment]
Note that I tries almost every Drush 10.x version.

Latest compatible Drush version with Drupal 8.9.11 is 9.7.2

**Comment by greg-1-anderson** [comment]
I am guessing you are using a global installation of Drush rather than a site-local install of Drush. Only the later is supported.

**Comment by werbfred** [comment]
What do you mean with global installation and site-local one ?

I'm using composer to keep Drupal and Drush up to date.

I've been running `composer require drush/drush:<version>` to test the different Drush versions against 8.9.11

**Comment by greg-1-anderson** [comment]
Installing Drush via `composer require` is a site-local installation.

Did you try running `composer update` to ensure that you have the latest version of Drush's dependencies? Use `composer update drush/drush --with-dependencies` if you do not want to update your Drupal site.

**Comment by werbfred** [comment]
Thank you Greg

Fixed.  I was actually running Drush with the global composer set up. Installed it with the local one and now works like a charm.
