### ISSUE TITLE
Exception in preflight does not set exit code

### ISSUE THREAD

**Issue by AdamPS** [drush-ops/drush#4627]
**Describe the bug**
Drush does not report fatal errors in preflight correctly to the shell.

**To Reproduce**
For example use a non-existent alias
`drush @zzzzz`

**Expected behavior**
The OS exit code is non-zero (visible from echo $?)

**Actual behavior**
The OS exit code is zero.  The cron script that takes my backups can fail without me being notified.

**Workaround**
None known.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | Latest dev 10.x

**Additional information**

**Comment by vStone** [comment]
I have the same issue with restricted php modes:

```
$ drush status
[preflight] The following restricted PHP modes have non-empty values: {open_basedir}. This configuration is incompatible with drush.  {Please check your configuration settings in /dev/null.}
$ echo $?
0
```

**Comment by AdamPS** [comment]
Great thanks
