### ISSUE TITLE
drush cim not found

### ISSUE THREAD

**Issue by oprogramador** [drush-ops/drush#4630]
I installed drush with `composer global require drush/drush`.

```
⟩ ~/.config/composer/vendor/bin/drush status
 PHP binary    : /usr/bin/php7.4                                          
 PHP config    : /etc/php/7.4/cli/php.ini                                 
 PHP OS        : Linux                                                    
 Drush script  : /home/pierre/.config/composer/vendor/drush/drush/drush   
 Drush version : 10.3.6                                                   
 Drush temp    : /tmp                                                     
 Drush configs : /home/pierre/.config/composer/vendor/drush/drush/drush.y 
                 ml

⟩ ~/.config/composer/vendor/bin/drush cim

                                                                               
  Command cim was not found. Pass --root or a @siteAlias in order to run Drup  
  al-specific commands.
```

And in the project directory (drush installed with `composer install`):
```
⟩ ~/.config/composer/vendor/bin/drush status
 Drupal version : 8.9.2                                                   
 Site URI       : http://default                                          
 DB driver      : mysql                                                   
 DB hostname    : localhost                                               
 DB port        : 3306                                                    
 DB username    : user                                                    
 DB name        : mydb                                               
 PHP binary     : /usr/bin/php7.4                                         
 PHP config     : /etc/php/7.4/cli/php.ini                                
 PHP OS         : Linux                                                   
 Drush script   : /var/www/html/my-project/vendor/drush/drush/drush     
 Drush version  : 9.7.2                                                   
 Drush temp     : /tmp                                                    
 Drush configs  : /var/www/html/my-project/vendor/drush/drush/drush.yml 
                  /var/www/html/my-project/drush/drush.yml              
 Drupal root    : /var/www/html/my-project/docroot                      
 Site path      : sites/default

⟩ ./vendor/bin/drush cim

                                                                               
  Command cim was not found. Drush was unable to query the database. As a res  
  ult, many commands are unavailable. Re-run your command with --debug to see  
   relevant log messages.

⟩ ./vendor/bin/drush cim --debug
 [preflight] Config paths: /var/www/html/my-project/vendor/drush/drush/drush.yml,/var/www/html/my-project/drush/drush.yml
 [preflight] Alias paths: /var/www/html/my-project/docroot/drush/sites,/var/www/html/my-project/drush/sites
 [preflight] Commandfile search paths: /var/www/html/my-project/vendor/drush/drush/src,/var/www/html/my-project/drush
 [debug] Bootstrap further to find cim [0.05 sec, 8.99 MB]
 [debug] Trying to bootstrap as far as we can [0.05 sec, 8.99 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalRoot() [0.05 sec, 9 MB]
 [bootstrap] Change working directory to /var/www/html/my-project/docroot [0.05 sec, 8.99 MB]
 [bootstrap] Initialized Drupal 8.9.2 root directory at /var/www/html/my-project/docroot [0.05 sec, 9.19 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalSite() [0.05 sec, 9.48 MB]
 [bootstrap] Initialized Drupal site default at sites/default [0.06 sec, 9.72 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalConfiguration() [0.06 sec, 9.72 MB]
 [debug] Add service modifier [0.06 sec, 9.97 MB]
 [bootstrap] key_value table not found. Database may be empty. [0.06 sec, 10.42 MB]
 [debug] Bootstrap phase bootstrapDrupalDatabase() failed to validate; continuing at bootstrapDrupalConfiguration() [0.06 sec, 10.42 MB]
 [debug] Done with bootstrap max in Application::find(): trying to find cim again. [0.06 sec, 10.42 MB]

In Application.php line 239:
                                                                               
  [Symfony\Component\Console\Exception\CommandNotFoundException]               
  Command cim was not found. Drush was unable to query the database. As a res  
  ult, many commands are unavailable. Re-run your command with --debug to see  
   relevant log messages.                                                      
                                                                               

Exception trace:
  at /var/www/html/my-project/vendor/drush/drush/src/Application.php:239
 Drush\Application->bootstrapAndFind() at /var/www/html/my-project/vendor/drush/drush/src/Application.php:192
 Drush\Application->find() at /var/www/html/my-project/vendor/symfony/console/Application.php:236
 Symfony\Component\Console\Application->doRun() at /var/www/html/my-project/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/html/my-project/vendor/drush/drush/src/Runtime/Runtime.php:118
 Drush\Runtime\Runtime->doRun() at /var/www/html/my-project/vendor/drush/drush/src/Runtime/Runtime.php:49
 Drush\Runtime\Runtime->run() at /var/www/html/my-project/vendor/drush/drush/drush.php:72
 require() at /var/www/html/my-project/vendor/drush/drush/drush:4
```

**Comment by oprogramador** [comment]
So it seems to be a problem with the `key_value` table but I don't have any idea why it's not created.

**Comment by weitzman** [comment]
Please follow https://www.drush.org/latest/install/. You cant use `global` in your composer install.

**Comment by oprogramador** [comment]
@weitzman 

After upgrading drush to 9.7.2, there's still no `cim` command (I run `composer update` in my local project directory).

**Comment by djohnsonb** [comment]
I am also facing the same issue. Below is the log 

Drush Launcher Version: 0.9.1
ROOT: / 
DRUSH VERSION: 10
DRUPAL ROOT: / /web
COMPOSER ROOT: / 
VENDOR ROOT: / /vendor
 [preflight] Config paths: /Users/ /.drush/drush.yml,/ /vendor/drush/drush/drush.yml,/ /drush
 [preflight] Alias paths: /Users/ /.drush/sites,/Users/ /.drush/sites/pantheon,/ /web/drush/sites,/ /drush/sites
 [preflight] Commandfile search paths: / /vendor/drush/drush/src,/Users/ /.drush/pantheon
 [debug] Bootstrap further to find cim [0.1 sec, 8.96 MB]
 [debug] Trying to bootstrap as far as we can [0.1 sec, 8.96 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalRoot() [0.1 sec, 8.96 MB]
 [debug] Change working directory to / /web [0.1 sec, 8.96 MB]
 [debug] Initialized Drupal 9.2.6 root directory at / /web [0.1 sec, 8.96 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalSite() [0.11 sec, 9.29 MB]
 [debug] Initialized Drupal site default at sites/default [0.11 sec, 9.52 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalConfiguration() [0.11 sec, 9.52 MB]
 [debug] Add service modifier [0.11 sec, 9.7 MB]
 [debug] Unable to connect to database with message: SQLSTATE[HY000] [2006] MySQL server has gone away. More debug information is available by running `drush status`. This may occur when Drush is trying to bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working database setup by specifying the URI to use with the --uri parameter on the command line. See `drush topic docs-aliases` for details. [0.11 sec, 9.97 MB]
 [debug] Bootstrap phase bootstrapDrupalDatabase() failed to validate; continuing at bootstrapDrupalConfiguration() [0.11 sec, 9.94 MB]
 [debug] Done with bootstrap max in Application::bootstrapAndFind(): trying to find cim again. [0.11 sec, 9.94 MB]

In Application.php line 243:
                                                                                                                                                                                 
  [Symfony\Component\Console\Exception\CommandNotFoundException]                                                                                                                 
  Command cim was not found. Drush was unable to query the database. As a result, many commands are unavailable. Re-run your command with --debug to see relevant log messages.  
                                                                                                                                                                                 

Exception trace:
  at / /vendor/drush/drush/src/Application.php:243
 Drush\Application->bootstrapAndFind() at / /vendor/drush/drush/src/Application.php:196
 Drush\Application->find() at / /vendor/symfony/console/Application.php:237
 Symfony\Component\Console\Application->doRun() at / /vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at / /vendor/drush/drush/src/Runtime/Runtime.php:118
 Drush\Runtime\Runtime->doRun() at / /vendor/drush/drush/src/Runtime/Runtime.php:48
 Drush\Runtime\Runtime->run() at / /vendor/drush/drush/drush.php:72
 require() at / /vendor/drush/drush/includes/preflight.inc:18
 drush_main() at phar:///usr/local/bin/drush/bin/drush.php:143
 require() at /usr/local/bin/drush:14

**Comment by oprogramador** [comment]
@djohnsonb 

In some way, I managed to overcome this problem. I don't remember exactly but generally, I needed to have everything installed & configured properly.

**Comment by oprogramador** [comment]
If I remember correctly, I needed to switch to composer@1 for that project.
