### ISSUE TITLE
Slashes are removed from update descriptions

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#4631]
**Describe the bug**

I ran `drush updb` and this description which contains a URL shows it broken:

```
  admin_toolbar         8001        hook_update_n   Rebuild routes to mitigate
                                                    issue 2938884.   @see
                                                    https:www.drupal.orgprojec
                                                    tadmin_toolbarissues293888
```

**To Reproduce**

I updated drupal/admin_toolbar from 2.2.0 => 2.4.0 with Composer then ran `drush updb`.

**Expected behavior**

The link outputs correctly.

**Actual behavior**

Link is broken.

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.7.0
| Drupal version? | 8.8
| PHP version     | 7.4
| OS?             | Mac

**Additional information**

This might be a problem in Drupal itself, I've not investigated.

**Comment by weitzman** [comment]
Drupal emits a render array here which is quite bad for CLI. We use Drupal's functions to try to present something same. PR  welcome. https://github.com/drush-ops/drush/blob/10.x/src/Drupal/DrupalUtil.php#L7-L25

**Comment by weitzman** [comment]
Oh woops that’s used in core:requirements. Not sure whats up here.

**Comment by weitzman** [comment]
Looks like the offender here is update_get_update_list() from drupal core
