### ISSUE TITLE
Migrate UI compatible with drush > 10.4

### ISSUE THREAD

**Issue by rodrigoaguilera** [drush-ops/drush#4637]
I am trying the 10.4 RC release and the most prominent change for me is that it conflicts with migrate_tools.
Some sites require users to run migrations but now they don't have an interface.

**Expected behavior**
A contrib module or migrate_tools 6 that only includes the interface.

**Actual behavior**
Migrate tools needs to be removed.

**Workaround**
Not that I am aware of

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.4.0-rc1
| Drupal version? | 8.x
| PHP version     | 7.x
| OS?             | Linux

**Additional information**
I am not sure why the composer conflict with migrate tools is stated as <=5, which gives me the idea that migrate_tools 6 is going to be compatible somehow. Is there a relevant issue?

**Comment by claudiu-cristea** [comment]
Yes, migrate_tools 6 will have to remove the Drush commands and will compatible.

**Comment by rodrigoaguilera** [comment]
I found your issue on migrate_tools
https://gitlab.com/drupalspoons/migrate_tools/-/issues/118

Feel free to close this one, all actions need to be done on migrate tools 6

**Comment by claudiu-cristea** [comment]
@rodrigoaguilera yes, until Migrate Tools will get a fix and a 6.x release, sites using the UI will have to pin Drush to 10.3

**Comment by heddn** [comment]
I'd be happy if someone could throw up a rough MR on https://gitlab.com/drupalspoons/migrate_tools

**Comment by heddn** [comment]
I see the alternatives right now to stay w/ drush <10.4 or migrate_tools ^5.0 until we get that all working
