### ISSUE TITLE
Error message running "help status"

### ISSUE THREAD

**Issue by AdamPS** [drush-ops/drush#4639]
**Describe the bug**
If you run `drush help status` it fails with an exception 

> Incorrectly nested style tag found

The output has printed up to part way through the list of default fields so I guess that is somehow too long/complex.

Actually it works with an insanely wide window (across 2 monitors).  So I guess the problem is related to splitting across lines.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.6
| Drupal version? | Doesn't matter as Drupal is not called in this case.
| PHP version     | 7.4.3
| OS?             | Linux

**Comment by weitzman** [comment]
This is easily reproduced. I think this is an issue in https://github.com/consolidation/output-formatters/. You agree @greg-1-anderson?

**Comment by AdamPS** [comment]
Thanks
