### ISSUE TITLE
Suddenly, readline, tab completion and the prompt do not show up when running `drush php`

### ISSUE THREAD

**Issue by dweinerATL** [drush-ops/drush#4645]
**Describe the bug**
When running `drush php`, I no longer get the `>>>` prompt, tab completion and the use of the arrow keys (readline) are no longer working.  If I run the psy shell directly (./vendor/psy/psysh/bin/psysh everything works, but the drupal environment is not initiated.

**To Reproduce**
Run `drush php`

**Expected behavior**
I expect the `>>>` prompt as well as the use of the arrow keys and tab completion

**Actual behavior**
While the psysh is working, without tab completion, the arrow keys and the `>>>` prompt, it is very difficult to use

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.0.0
| Drupal version? | 8.9.9
| PHP version     | 7.3.25
| OS?             | Mac

**Additional information**
If I run the psy shell directly (./vendor/psy/psysh/bin/psysh everything works, but the drupal environment is not initiated.

**Comment by weitzman** [comment]
Upgrade to latest drush?

**Comment by dweinerATL** [comment]
> Upgrade to latest drush?

@weitzman This is a production website with a large corporate audience.  Upgrading drush requires change control and approval at a higher level.  Plus, it only occurs in my local development environment and not on the server.

**Comment by weitzman** [comment]
We only support the latest version of each major release.
