### ISSUE TITLE
pm:security-php no more working

### ISSUE THREAD

**Issue by FlorentTorregrosa** [drush-ops/drush#4648]
**Describe the bug**
The command `pm:security-php` is using the website https://security.symfony.com/ and this service is no more available https://twitter.com/fabpot/status/1354038012892618755.

**Comment by weitzman** [comment]
Ugh. If anyone knows of a php package that checks, that would be great https://t.co/YZwsFuXdWg?amp=1. Until then, I guess folks need to use that app and not `pm:security-php`

**Comment by lpeabody** [comment]
Acquia BLT just updated their project to use a nearly drop-in replacement https://github.com/acquia/blt/pull/4329

**Comment by Rudloff** [comment]
enlightn/security-checker can be called [entirely in PHP](https://github.com/enlightn/security-checker#api) so it might be relatively easy to integrate it into Drush.

**Comment by weitzman** [comment]
Fixed in #4653
