### ISSUE TITLE
Drush Deploy should include language update

### ISSUE THREAD

**Issue by bunglegrind** [drush-ops/drush#4650]
Since the translations are not configuration, they are not automatically imported in the system using drush cim. I kindly suggest you to insert in drush deploy (at least as a parameter) the possibility to update the translations too

**Comment by weitzman** [comment]
What command would be run?

**Comment by Sutharsan** [comment]
This is the most generic to import translations:

- drush locale:check
- drush locale:update

**Comment by bunglegrind** [comment]
Why not only locale:update? Locale:check, depending on the prod environment configuration could download the updated from remote sources.

**Comment by Sutharsan** [comment]
> Locale:check, depending on the prod environment configuration could download the updated from remote sources.
Yep, that could be desired behavior. That is what can be determined in the configuration. If that is not desired, configure set the translation source to 'local'.

**Comment by weitzman** [comment]
I am inclined to let folks add the commands to their deploy scripts, and not add them to the `drush deploy` command directly. That command is already quite complex.
