### ISSUE TITLE
Batch operation on update hooks don't set the correct installed schema version if $sandbox['#finished'] is > 1

### ISSUE THREAD

**Issue by Buzu** [drush-ops/drush#4658]
**Describe the bug**
When an update hook is run in a batch operation, if the value of `$sandbox['#finished']` is set to a value greater than 1, the update operation is considered done, but the schema version is not updated. This leads to the update being performed multiple times.

**To Reproduce**
What did you do?
Write an update hook that uses the `$sandbox`.
```
function foo_update_8001 (&$sandbox) {
    $sandbox['#finished'] = 1.1;
}
```
This update will run multiple times until:
a) The function is fixed to return 1;
b) Another update is run for the foo module that properly updates the installed schema version.
c) The schema version value in the DB is updated some other way, like via an SQL statement.

**Expected behavior**
The update hook either fails with an error telling you that "1.1 is not a valid finished value, only values between 0 and 1 are valid", or the update succeeds and the proper schema version is recorded.

**Actual behavior**
The update succeeds, but the schema version is not updated leaving things in an inconsistent state.

**Workaround**
Make sure your function sets 1 for `$sandbox['finished']`. If the value depends on an operation that may return a value greater than 1, check for that case, and set the value to 1.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.6
| Drupal version? | 9.x
| PHP version     | 7.4
| OS?             | Mac & Linux

**Additional information**
I've tracked this issue to a difference in the way an operation is considered finished on https://github.com/drush-ops/drush/blob/10.x/includes/batch.inc#L261 and https://github.com/drush-ops/drush/blob/10.x/src/Commands/core/UpdateDBCommands.php#L275 One checks for finished to be exactly 1, while the other checks for it to be 1 or greater.

**Comment by weitzman** [comment]
Thanks for the excellent report  ... You mistakenly posted the same link twice at the end.

**Comment by Buzu** [comment]
Thanks for catching that @weitzman. I've added the right link.

**Comment by weitzman** [comment]
So would it suffice to make both checks be `>= 1`. Seems fine to me.

**Comment by Buzu** [comment]
I think so. I'm not familiar enough with Drush to know if that change would introduce some other unexpected behavior, but I don't think that would happen.
