### ISSUE TITLE
No results on hooks page

### ISSUE THREAD

**Issue by petk** [drush-ops/drush#4665]
**Existing document**
https://www.drush.org/latest/hooks/#core-hooks

**What are you attempting to do**
When clicking the "search the Drush source code" there are no results on GitHub.

**In what way is the existing documentation unclear or incomplete**
The documentation looks outdated.

**Comment by weitzman** [comment]
Fixed by adding quotes around the search term. Thanks for the report.

**Comment by petk** [comment]
Thank you so much @weitzman :heart: I could sent PR my self but wasn't sure where to add this. :+1:
