### ISSUE TITLE
DrupalKernel (invoked by drush) with multisite modules

### ISSUE THREAD

**Issue by dpagini** [drush-ops/drush#4666]
**Describe the bug**
To put it simply, my production Drupal site has gone down (some 503 error pages) twice over the last 6 months. My site uses Drupal 8.9 multisite setup with 3 websites, and I have site-specific modules (_modules that live at `root/sites/____/modules/*`_), and ultimately what happens is, Drupal seems to lose track of all my "site-specific code", such as plugins that live in those sites-modules.

Before thinking this was a drush/cron issue, I created this issue on d.o/core...
https://www.drupal.org/project/drupal/issues/3199185

**To Reproduce**
While investigating this outage, I have come across a very unique scenario where I am able to replicate this error in my non-production environments by deploying a branch (on Acquia) without any cache clears. My site is built on top of BLT, which sets a unique `deployment_identifier` per branch/tag. Then, and this is the important part, after my deployment I need to wait for a scheduled job run (Acquia) which basically invokes `$ drush cron --uri=example.com`, and then when I visit my Drupal site, I see my errors. The cron run, I have determined (_or highly suspect at this point_) is what triggers this error....

So some additional information here.... what I believe is happening is that, the DrupalKernel file is building the container under a certain set of circumstances, and saving that container to cache, that _does not have_ any references to the site specific modules, **only** the shared (`root/modules/*`) modules. I added some debug statements to the deployed `DrupalKernel` file I have, specifically around line [1392](https://github.com/drupal/drupal/blob/16d35ec6af1cc196b0c2b577db6315dbffd2c38e/core/lib/Drupal/Core/DrupalKernel.php#L1380-L1392), to check if, when the container is getting cached, if the definition contains any references to my site specific modules.... and if not, I print out a stack trace. 

Over and over, in my logs, here is my stack trace...
```
#0 /mnt/www/html/clientdev2/docroot/core/lib/Drupal/Core/DrupalKernel.php(974): Drupal\Core\Drupa
lKernel->cacheDrupalContainer(Array)
#1 /mnt/www/html/clientdev2/vendor/drush/drush/src/Drupal/DrupalKernelTrait.php(69): Drupal\Core\DrupalKernel->initiali
zeContainer()
#2 /mnt/www/html/clientdev2/docroot/core/lib/Drupal/Core/DrupalKernel.php(477): Drush\Drupal\DrupalKernel->initializeCo
ntainer()
#3 /mnt/www/html/clientdev2/vendor/drush/drush/src/Boot/DrupalBoot8.php(240): Drupal\Core\DrupalKernel->boot()
#4 /mnt/www/html/clientdev2/vendor/drush/drush/src/Boot/BootstrapManager.php(293): Drush\Boot\DrupalBoot8->bootstrapDru
palFull(Object(Drush\Boot\BootstrapManager), NULL)
#5 /mnt/www/html/clientdev2/vendor/drush/drush/src/Boot/BootstrapManager.php(493): Drush\Boot\BootstrapManager->doBoots
trap(5, 6, NULL)
#6 /mnt/www/html/clientdev2/vendor/drush/drush/src/Application.php(225): Drush\Boot\BootstrapManager->bootstrapMax()
#7 /mnt/www/html/clientdev2/vendor/drush/drush/src/Application.php(192): Drush\Application->bootstrapAndFind('cron')
#8 /mnt/www/html/clientdev2/vendor/symfony/console/Application.php(236): Drush\Application->find('cron')
#9 /mnt/www/html/clientdev2/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(O
bject(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /mnt/www/html/clientdev2/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->ru
n(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /mnt/www/html/clientdev2/vendor/drush/drush/src/Runtime/Runtime.php(49): Drush\Runtime\Runtime->doRun(Array, Object
(Symfony\Component\Console\Output\ConsoleOutput))
#12 /mnt/www/html/clientdev2/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#13 /mnt/www/html/clientdev2/vendor/drush/drush/drush(4): require('/mnt/www/html/v...')
#14 {main}
```

⚠️ **When DRUSH CRON is invoked, I believe with either an empty, or invalid container cache, the way that Drush is calling the Drupal Kernel appears to be ignoring my multisite specific modules, and saving a container definition that does not include those modules, which can't repaired until after a "cache rebuild" is performed, at which time everything runs great.**

Now, with that stated, I would sort of expect that when I run `$ drush cr --uri=site1` followed by `$ drush cron --uri=site1` that I could reproduce this everytime, but that's not the case, and I don't have the answer to that just yet. I am thinking it has something to do with the `deployment_identifier` maybe, but need to investigate that further. Any thoughts on what could be going on here would be **much appreciated**. I'm happy to keep looking at things, but I have been troubleshooting this for about 2 months, and this is the closest I have to a lead right now, so I figured I would throw it up and get some thoughts on all of this....

**Expected behavior**
I expect my Drupal site to always "be aware of" the site specific modules and code that runs the site.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.6 (_I think, not entirely sure if Acquia cron wrapper is running a different version_)
| Drupal version? | 8.9.13
| PHP version     | 7.3.26
| OS?             | Linux

**Comment by weitzman** [comment]
Sounds like #3391, which ultimately blames a drupal core issue.

**Comment by dpagini** [comment]
Thanks for weighing in @weitzman. I'm not fully convinced this is Drupal core, but I'll take some of that discussion over to #3391.

One note here, I realized that on my Acquia server, the Drush that's calling CRON is actually `8.4.2` - I'm not sure if maybe that version of Drush handled Drupal core bootstrap any differently? Do you happen to know?

**Comment by greg-1-anderson** [comment]
The bootstrap code for Drush 8 is quite different from Drush 10, at least in structure; in theory, they are operationally the same. It's possible that there are bug fixes in Drush 10 that were not backported. If you find anything that Drush 8 is not doing correctly, a PR would be welcome.

**Comment by weitzman** [comment]
The Drush preflight is very different but as Greg says, the Drupal bootstrap is virtually identical. I'd be surprised if it made a material difference to this issue.

**Comment by dpagini** [comment]
I'm actually seeing that the Acquia cron/drush script, although the global drush is `8.4.2` - it does seem to be handing off control to drush 10 for the actual cron command being executed. I am seeing this in my logs....

```
Using the Drush script found at /mnt/www/html/clientname/vendor/drush/drush/drush using pcntl_exec
```
(which is drush 10.3.6)

---

Anyways... I'm not very versed in the Drupal kernel, but this production issue has me getting my hands dirty in this. Maybe you both are a bit more familiar having an app that integrates tightly with it....?

So based on my original problem, it seems to me that when a drush command runs, and my site does not have the container cached already, my site is crashing.

When I look at the Drupal core index.php file, it creates a new `DrupalKernel` object, and calls `::handle()` and passes the request in.
https://github.com/drupal/drupal/blob/485d2a305f78605de55eef8e870d80f51d3fb155/index.php#L16-L19

The `::handle()` method calls `::initializeSettings()` and the SITE PATH gets set on the Kernel.
https://github.com/drupal/drupal/blob/485d2a305f78605de55eef8e870d80f51d3fb155/core/lib/Drupal/Core/DrupalKernel.php#L693-L698

Ultimately, the container gets built and saved to cache with my multisite settings intact.

---

Now, from the drush side of things...

It appears to me like Drush creates a new Kernel, and then ultimately calls `::boot()` and `::preHandle()`. when it bootstraps Drupal. However, neither of those paths _ever_ leads to Kernel's `::setSitePath()` being called, as with the Drupal example above.

Ultimately, I think a "drush drupal kernel" is running without the site path set, and then in the `ExtensionDiscovery` service, this line executes _and is really not site aware_, and compiles a Drupal container that has no knowledge of multisite specific code.

https://github.com/drupal/drupal/blob/485d2a305f78605de55eef8e870d80f51d3fb155/core/lib/Drupal/Core/Extension/ExtensionDiscovery.php#L190

Does that seem feasible at all?
So again, being totally unaware of integrating with the Drupal kernel... could this just be a scenario that was not thought about... bootstrap the kernel from _____ application with no container in cache? Thoughts?

Thank you both again for your time!

**Comment by dpagini** [comment]
Just a small follow-up... the d.o issue I posted on, @alexpott is [wondering outloud](https://www.drupal.org/project/drupal/issues/2985199#comment-14009547) the same thing if this _could be_ the way Drush is building the container.

**Comment by greg-1-anderson** [comment]
I don't think that the Drush bootstrap has changed too many times since 8.0.0.  It's possible that the `::setSitePath()` requirement is new, and Drush is no longer doing the right thing. I have not specifically investigated and don't know one way or another, but it seems like the next thing to do would be to make a PR with an adjusted bootstrap process, and see if it clears up the problems you're having.

**Comment by dpagini** [comment]
Thanks Greg. I am definitely trying to help within my power... I am working around some unfortunate company policies. The thing I am so unclear on... it seems like in Drupal core, there is really **no guidance** on how to instantiate the DrupalKernel. I'm just not familiar enough with this system to figure out _how it should be called_ without any kind of documentation or best practice there... honestly, "Drush code" would have been my go-to if I were looking for that answer.

I don't think this really works, but I almost feel like this needs a "meeting of the minds" of Drush maintainers and core to figure out where the problem is....? Is that crazy?

**Comment by weitzman** [comment]
Lets consolidate at #3391
