### ISSUE TITLE
drush browse --no-browser is not working

### ISSUE THREAD

**Issue by pivica** [drush-ops/drush#4667]
**Describe the bug**
drush browse command help file and documentation on https://www.drush.org/latest/commands/browse/ claims that there is a `--no-browser` flag. However, it seems that the implementation of that flag is missing for the browse command.

**To Reproduce**
Run
`drush browse --no-browser`

**Expected behavior**
Expect to see a Drupal website URL in the console.

**Actual behavior**
Instead of a URL, next error is outputted:

`The "--no-browser" option does not exist.`

**Workaround**
No.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.6
| Drupal version? | 8.9.13
| PHP version     | 7.4
| OS?             | Linux

**Additional information**
In the same time executing `drush uli --no-browser` works as expected.

**Comment by weitzman** [comment]
Fixed. Thanks for the report.
