### ISSUE TITLE
Add param and return type hints, OO interfaces, etc.

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#4675]
Major moderning and leveraging of recent PHP improvements. Some may break backward compat for commands.

**Comment by greg-1-anderson** [comment]
If we break bc for module commands, maybe we should also change the way commandfile discovery works. I regret putting Drush commands into the Symfony DI container. We should switch to using a static factory method that takes the DI container as a parameter.

**Comment by beejeebus** [comment]
this looks like fun.

can I get some suggestions for chunking this up?

**Comment by weitzman** [comment]
I'm undecided about breaking backward compat for commands that ship with modules. Some approaches are discussed at https://www.drupal.org/project/drupal/issues/3050720

**Comment by beejeebus** [comment]
ack, thanks, that's good context.

to get a feel for the tools around, I'll try some experiments with [Rector](https://github.com/rectorphp/rector).

**Comment by weitzman** [comment]
I think internal classes like `src/Boot`, `src/Preflight`, `src/Runtime`, `src/SiteAlias`, `src/Symfony` are good places to start.

**Comment by beejeebus** [comment]
Ok, #4775 is worth another look, might be good enough now.

What next?

**Comment by weitzman** [comment]
Done.
