### ISSUE TITLE
Module Installation - hook_requirements not being called.

### ISSUE THREAD

**Issue by abradburn** [drush-ops/drush#4677]
**Describe the bug**
Drupal's hook_requirements isn't being called when a module is installed via "drush pm:enable [module_name]"

**To Reproduce**
What did you do?

Starting with a basic "hello_world" module. I have added a hello_world.install file, and extended hook_requirements with hello_world_requirements, but it isn't being called. The same function is called and behaves as expected when enabling the module via the Drupal GUI.

function hello_world_requirements($phase){
  echo print_r(['Requirements ran.']);

  $requirements = [];
  if($phase == 'install'){
    $requirements['test'] = [
      'title' => 'Test',
      'value' => '0.1',
      'description' => 'This is to test the installation of a module.',
      'severity' => REQUIREMENT_ERROR
    ];
  }

  return $requirements;
}

**Expected behavior**
What did you expect would happen?

I expected that hook_requirements would be run so that I could check for module requirements, and abort if they weren't met.
Playing around, hook_install is called as expected.

I have looked at documentation, but haven't found anything to indicate that hook_requirements shouldn't be called by drush.

**Actual behavior**
What happened instead?

hook_requirements isn't being called at all.

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.4.0
| Drupal version? | 9.1.4
| PHP version     | 7.4
| OS?             | Linux

**Additional information**

**Comment by weitzman** [comment]
#4337
