### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by SAANDATI** [drush-ops/drush#4680]
![laravelErr](https://user-images.githubusercontent.com/53649074/109845148-b7e83180-7c44-11eb-8bcf-574002e7d67c.PNG)
Bonjour j'avais installer laravel 7.0 et ressèment je veux travail avec laravel 8.* j'ai installer composer v2.0.11 et PHP 7.4.14 mais je n'arrive toujours pas à installer un nouveau projet laravel je sollicite votre aide 
Merci beaucoup aux intervenants

**Comment by greg-1-anderson** [comment]
This report appears to be related to Laravel, and unrelated to Drush.
