### ISSUE TITLE
Message in ErrorHandler mentions option --no-halt-on-error that does not exist

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#4681]
**Describe the bug**

```
                $this->logger->error(dt('E_RECOVERABLE_ERROR encountered; aborting. To ignore recoverable errors, run again with --no-halt-on-error'));
```

I tried `drush st --debug --no-halt-on-error` and was told that the --no-halt-on-error option does not exist.

I can't see the string 'no-halt-on-error' anywhere else in the code.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.6
| Drupal version? | 8.9
| PHP version     | 7.3
| OS?             | Linux

**Comment by weitzman** [comment]
For now please pass --halt-on-error=0. I guess global options dont get automatic negations anymore /cc @greg-1-anderson.

@joachim-n Can you say more about why you want to pass this? I have not needed this option in a long time. I'm thinking it could go away.

**Comment by joachim-n** [comment]
> @joachim-n Can you say more about why you want to pass this? I have not needed this option in a long time. I'm thinking it could go away.

Drush was crashing on the server with:

```
 [warning] Drush command terminated abnormally. [0.17 sec, 3.82 MB]
```

I was trying to debug, by adding this to ShutdownHandler, to see if the message there could have more detail added to it:

```
      $error = error_get_last();
      dump($error);
```

That didn't work, but while I was there I too a look in the adjacent ErrorHandler, and spotted this option. I tried it on the offchance I'd get more detail out of Drush.

Drush is now working again, mysteriously, so I can't try the `--halt-on-error=0`.

**Comment by weitzman** [comment]
Thanks for the detail. You may find more detail in your PHP error log. See `php -i` for details on where that might be.

**Comment by joachim-n** [comment]
I looked in what I thought were the PHP logs, and there wasn't anything that looked related to the problem.
