### ISSUE TITLE
Use drush to update composer? A way to migrate older drush sites to that?

### ISSUE THREAD

**Issue by romulasry** [drush-ops/drush#4683]
**Is your feature request related to a problem? Please describe.**
I would like to use drush to update my composer file and take an existing drush site over to composer.

**Describe the solution you'd like**
Drush to update my composer file and take an existing drush install over to that.

**Describe alternatives you've considered**
I am not sure.

**Additional context**

**Comment by romulasry** [comment]
https://www.drupal.org/project/composer
 This should do that no?

**Comment by romulasry** [comment]
It doesn't seem to be able to integrate drush with composer, that would be nice. Migrating and existing drush file over to composer also would be ideal for existing sites.

**Comment by greg-1-anderson** [comment]
See the [composerize-drupal](https://github.com/grasmash/composerize-drupal) project. There is also some work in progress on a [conversion tool in the drupal.org issue queue](https://www.drupal.org/project/drupal/issues/3047468).

**Comment by romulasry** [comment]
Yes, that is good but will drush update my composer file? That would be useful too!

**Comment by weitzman** [comment]
No, drush never updates composer.json. That’s out of scope in Drush 9+
