### ISSUE TITLE
Drush is invoking command with default PHP version, not specified PHP version

### ISSUE THREAD

**Issue by Holo96** [drush-ops/drush#4686]
**Describe the bug**
For instance in case server default is php7.2, and **drush updb** is executed like this: `path_to_php7.4 drush updb -y`
this command is invoking updbst with default php7.2, it will not return any update hooks, and none will be executed.

**Expected behavior**
It is expected that invoked commands are executed in same PHP binary

**Workaround**
I haven't found workaround but I've created patch that I am using for quite some time with no issues.
```
diff --git a/drush/src/SiteAlias/ProcessManager.php b/drush/src/SiteAlias/ProcessManager.php
index cc26d8aa2..7a1ce4b8a 100644
--- a/drush/src/SiteAlias/ProcessManager.php
+++ b/drush/src/SiteAlias/ProcessManager.php
@@ -60,6 +60,12 @@ public function drushSiteProcess(SiteAliasInterface $siteAlias, $args = [], $opt
         // The executable is always 'drush' (at some path or another)
         array_unshift($args, $this->drushScript($siteAlias));

+        // Execute drush with specific PHP version
+        if (!$siteAlias->isRemote()) {
+            array_unshift($args, PHP_BINARY);
+        } elseif ($siteAlias->has('paths.php-bin')) {
+            array_unshift($args, $siteAlias->get('paths.php-bin'));
+        }
         return $this->siteProcess($siteAlias, $args, $options, $options_double_dash);
     }

```
Also in this patch you can specify php-bin path for aliases, so it is executed in given php version.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.4
| Drupal version? | 9.1.5
| PHP version     | Any
| OS?             | Any

**Comment by weitzman** [comment]
Instead of the patch, you can use env-vars in the site alias definition to set the PATH variable. Search for `env-vars` at https://www.drush.org/latest/examples/example.site.yml/.

**Comment by Holo96** [comment]
Well I don't understand how this helps me?
Can you give me example how can I set php-binary path with `env-vars` in drush.yml? I don't have problems with aliases at all

**Comment by Holo96** [comment]
So problem is that when I execute `/usr/bin/php7.4 drush updb` invoked command is invoked like this `drush updbst`, so it is executed with different php binary

**Comment by Holo96** [comment]
@weitzman I would be very thankful if you can help me with this...
I know it is not ordinary to have multiple PHP versions installed, but some of our older projects require old PHP versions

**Comment by weitzman** [comment]
See `Note` at https://www.drush.org/latest/install/. That’s all the help i can provide here. Use Drupal Answers for more.

**Comment by prudloff-insite** [comment]
We also got bitten by this. When calling Drush with a specific PHP binary, we expected subcommands to be called with the same binary.

Adding something like this to the alias does indeed work around the problem:
```yaml
alias:
  env-vars:
    PATH: /path/to/other/php/folder/:/usr/bin:/bin
```
