### ISSUE TITLE
Config file ignored

### ISSUE THREAD

**Issue by tyler36** [drush-ops/drush#4689]
**Describe the bug**
Documentation says config file `~/.drush/drush.yml` can be used. Does not work on Win10. This is a follow-up to  #4687 which was prematurely closed.

**To Reproduce**
- Create file: ``~/.drush/drush.yml` with following contents:
```yml
command:
  site:
    install:
      options:
        account-name: 'admin'
        account-pass: 'drupal-admin'
```
- Run `drush si`

**Expected behavior**
Perform a site install with user and password set. Equivalent to running
```
drush si --account-name=admin --account-pass=drupal-admin
```

**Actual behavior**
Site install performed but with incorrect admin password.
```
 [success] Installation complete.  User name: admin  User password: YRF6eUroNi
```
- If I change the `account-name` to something different (Eg. `account-name: 'stars'`), it still generates an `admin` account with a random password. This seems to suggest it is not using the config file.
- As stated in #4687, it ignores the config file even when placed in the paths suggested by the example `drush.yml` and when using the `-c` command.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.4.0
| Drupal version? | 9.1.5
| PHP version     | 7.3.24
| OS?             | Win10

**Additional information**
See #4687

Edit: This YML file listed above was copied from #4687 which was originally typed with incorrectly spacing. It has been updated here to make it easier to debug. Additionally, I have re-run the commands and found the problem still exists.

**Comment by greg-1-anderson** [comment]
Home path calculation is probably incorrect for Windows. PRs welcome.

**Comment by tyler36** [comment]
That sounds fine for the "home path" location but your [example drush.yml](https://raw.githubusercontent.com/drush-ops/drush/10.x/examples/example.drush.yml) file states theres a config switch
```
# 3.  In any location, as specified by the --config (-c) option.
```

If I copy the `drush.yml` file above to my project root, neither of the following work.
- `drush si -c drush.yml`
- `drush si -c .\drush.yml`

**Comment by weitzman** [comment]
Run `drush st --fields=drush-conf --format=yaml` to see what config files are recognized

**Comment by tyler36** [comment]
Closing ticket. I changed PCs over the weekend and everything is working on the new PC. Not really sure of the issue, but thanks for the debugging information. I will be invaluable for others, or myself, if the issue comes up again.


Thank you again for your time.
