### ISSUE TITLE
Displayed migration ID is too short

### ISSUE THREAD

**Issue by quietone1** [drush-ops/drush#4690]
**Describe the bug**
The output of `drush ms` has too few characters for the migration id making it very difficult to know to interpret the output of the command. The length of the displayed ID is now shorter than it was with migrate_run. In the example you can't use the ID to   distinguish between taxonomy term and vocabulary migrations. This will affect other migrations as well. Note that migrate_run also truncated the ID, which is very annoying, so ideally this could change to show the full ID.

**To Reproduce**
```
$ drush en -y migrate_drupal
$ ddev drush ms | grep taxon
```
**Expected behavior**
To see the full migration ID in the output or, at least, the same output as migrate_run.
```
$ ddev drush ms | grep taxon
 [error]  Could not retrieve source count from d6_taxonomy_term: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd7_dump.term_data' doesn't exist: SELECT COUNT(*) AS "expression"
 [error]  Could not retrieve source count from d6_taxonomy_vocabulary: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd7_dump.vocabulary' doesn't exist: SELECT COUNT(*) AS "expression"
  d6_taxonomy_term          Idle     N/A     0            N/A
  d6_taxonomy_vocabulary    Idle     N/A     0            N/A
  d7_taxonomy_term:sujet_   Idle     5       5 (100%)     0
  d7_taxonomy_term:tags     Idle     10      10 (100%)    0
  d7_taxonomy_term:test_v   Idle     3       3 (100%)     0
  d7_taxonomy_term:vocabf   Idle     1       1 (100%)     0
  d7_taxonomy_term:vocabl   Idle     2       2 (100%)     0
  d7_taxonomy_term:vocabl   Idle     1       1 (100%)     0
  d7_taxonomy_term:vocabt   Idle     3       3 (100%)     0
  d7_taxonomy_term:vocabu   Idle     0       0            0
  d7_taxonomy_vocabulary    Idle     8       8 (100%)     0
  taxonomy_settings         Idle     1       1 (100%)     0
```
**Actual behavior**
The migration IDs are truncated so that the ID can't be used to determine if the migration is for a d7 vocabulary or a d7 term.
```
$ ddev drush ms | grep taxon
 [error]  Could not retrieve source count from d6_taxonomy_term: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd7_dump.term_data' doesn't exist: SELECT COUNT(*) AS "expression"
 [error]  Could not retrieve source count from d6_taxonomy_vocabulary: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd7_dump.vocabulary' doesn't exist: SELECT COUNT(*) AS "expression"
  d6_taxonomy_   Idle     N/A     0            N/A              N/A
  d6_taxonomy_   Idle     N/A     0            N/A              N/A
  d7_taxonomy_   Idle     5       5 (100%)     0                0
  d7_taxonomy_   Idle     10      10 (100%)    0                0
  d7_taxonomy_   Idle     3       3 (100%)     0                0
  d7_taxonomy_   Idle     1       1 (100%)     0                0
  d7_taxonomy_   Idle     2       2 (100%)     0                0
  d7_taxonomy_   Idle     1       1 (100%)     0                0
  d7_taxonomy_   Idle     3       3 (100%)     0                0
  d7_taxonomy_   Idle     0       0            0                0
  d7_taxonomy_   Idle     8       8 (100%)     0                0
```

**Workaround**
Don't use Drush 10.4. Use migrate_run with earlier version of Drush.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.4
| Drupal version? | 9.2.x
| PHP version     | PHP 7.3.25
| OS?             | Linux

**Additional information**

**Comment by claudiu-cristea** [comment]
I don't think the code trims explicitly the IDs. It might be something with the output format. As I remember we have a new column compared to migrate_run. That may be the source of narrowing the ID column.

**Comment by weitzman** [comment]
The [tableformatter](https://github.com/consolidation/output-formatters/blob/main/src/Formatters/TableFormatter.php) allows a column to specify a minimum width. I'm not sure how to set that directly. A poor mans way to set it is to choose a longer  table header label for the ID column (and ideally briefre headers for narrow columns).

**Comment by weitzman** [comment]
A workaround until we solve this is to pass --format=yaml

**Comment by claudiu-cristea** [comment]
@quietone1  I've tried a new feature in #4779 and also restored the default number of columns. Could you try to see if the new --columns option is helpful?

**Comment by claudiu-cristea** [comment]
@quietone1 In fact as @weitzman pointed out, we have --fields. Changed the PR.
