### ISSUE TITLE
Drush updb needs an argument to list updates pending without holding the prompt

### ISSUE THREAD

**Issue by kitsushadow** [drush-ops/drush#4703]
Drush updb needs an argument to list updates pending without holding the prompt so Ops automation can decide whether to take a backup of the database or to continue with running updb -y

Drush -n still runs updates.

**Comment by jrglasgow** [comment]
In case anybody wonders why this was closed so rapidly I was having a chat with @kitsushadow through another channel and pointed out that running. "drush updb --no" will list the pending updates and a return code of 1 if there are updates, if there are no updates it will have a return code of 0 which makes the automation possible.
