### ISSUE TITLE
Sanitize telephone numbers on sql:sanitize

### ISSUE THREAD

**Issue by elissaheller** [drush-ops/drush#4708]
**Is your feature request related to a problem? Please describe.**
When removing PII from the database, telephone numbers are currently being ignored.

**Describe the solution you'd like**
Sanitize all telephone numbers in the database when running sql:sanitize.

**Describe alternatives you've considered**
The [drush-gdpr-dump](https://github.com/robiningelbrecht/drush-gdpr-dumper) package is another option, but it requires configuration specifying which tables and fields to consider. An implementation that can automatically handle new fields added to the database that need sanitization would be ideal.

This started as a [patch](https://www.drupal.org/project/drupal/issues/3205630) for Drupal Core, but a suggestion was made to put this in drush instead.

**Additional context**

**Comment by weitzman** [comment]
This can start as a contrib plugin for drush. If anyone writes that, please link here and we will consider bringing it into core drush,

**Comment by weitzman** [comment]
We actually do sanitize phone fields when attached to the User entity.
