### ISSUE TITLE
drush php breaks `Psy\Info()`

### ISSUE THREAD

**Issue by chx** [drush-ops/drush#4709]
**Describe the bug**

While trying to figure out https://github.com/drush-ops/drush-launcher/issues/90 I tried to run `Psy\Info()` which is the recommended start for debugging Psy problems. You will get a most curious `ReflectionException with message 'Property loopListeners does not exist'`

**To Reproduce**

What did you do? Oh g*d, what did I do again. Ah yes. I typed `./vendor/bin/drush php` and typed `Psy\info()` 

**Expected behavior**

What did you expect would happen? I certainly didn't expect a pandemic... wait where I was? ah yes. Well, if you do `wget https://psysh.org/psysh; chmod +x psysh; ./psysh` then `Psy\info()`  works.

**Actual behavior**

What happened instead? The world ended. Well, not quite. That was last month. Now I got an error message `ReflectionException with message 'Property loopListeners does not exist'`

**Workaround**

Nope.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.6
| Drupal version? | irrelevant
| PHP version     | 7.4.3
| OS?             | Linux (no, really, it's Linux this time, even if it is in a lightweight VM, I just moved from WSL1 to WSL2 , it _is_ Linux this time.)

**Additional information**

**Comment by leymannx** [comment]
Cross-posted https://github.com/drush-ops/drush-launcher/issues/90

**Comment by weitzman** [comment]
Its coming from Psy. Ask them what LoopListeners is. See https://github.com/bobthecow/psysh/blob/main/src/functions.php#L286-L288

**Comment by chx** [comment]
![2021-04-03 11_15_56-Window](https://user-images.githubusercontent.com/193045/113487642-1b48c780-946e-11eb-8946-576a2d3d4f45.png)
![2021-04-03 02_36_30-Window](https://user-images.githubusercontent.com/193045/113487643-1be15e00-946e-11eb-8816-276c0b3bd305.png)

**Comment by weitzman** [comment]
Fixes in Psysh and Drush Launcher.
