### ISSUE TITLE
CacheCommands::rebuild() can omit include of includes/bootstrap.inc in Drupal 9.1+

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#4711]
**Describe the bug**

In the course of poking around for a different bug, I noticed that by the time we get to CacheCommands::rebuild(), includes/bootstrap.inc has already been loaded, by the Composer autoloader.

So at least in Drupal 9, including it here is pointless.

**To Reproduce**
What did you do?

**Expected behavior**
What did you expect would happen?

**Actual behavior**
What happened instead?

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.x
| Drupal version? | 9.2
| PHP version     | 7.4
| OS?             | Mac

**Additional information**

**Comment by weitzman** [comment]
Yeah, we can't make that change until we drop support for Drupal 8. [Its 9.1+](https://www.drupal.org/node/3151229).
