### ISSUE TITLE
drush sqlc ignores all mysql client config files

### ISSUE THREAD

**Issue by chx** [drush-ops/drush#4714]
**Describe the bug**

Since I've upgraded to Ubuntu 20.04 LTS, `drush sqlc` displays BLOBs as hex which is unusable. I've added `binary-as-hex=false` to various cnf files (`/etc/mysql/mysql.conf.d/mysql.cnf `, `~/.my.cnf` even `~/.mylogin.cnf`) and they were ignored

**To Reproduce**

Ran `drush sqlc` and then `SELECT * FROM router LIMIT 1\G` 

**Expected behavior**

I expected to see a serialized PHP object.

**Actual behavior**

I saw a lot of hex bytes.

**Workaround**

I can just run `mysql -A d8www`.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.6
| Drupal version? | 9.x but irrelevant
| PHP version     | 7.4
| OS?             | Ubuntu 20.04

**Comment by weitzman** [comment]
There has been a lot of back and forth on this over the the years. See https://github.com/drush-ops/drush/issues/2183 and prob others. You can see what shell command drush uses by adding `-vvv` to your sqlc command.

**Comment by chx** [comment]
Add

```
command:
  sql:
    cli:
      options:
        extra: '--binary-as-hex=false -A'
```

to `~/.drush/drush.yml` to fix this.
