### ISSUE TITLE
Long running batch via `drush_backend_batch_process()` failure due to timeout

### ISSUE THREAD

**Issue by adam-vessey** [drush-ops/drush#4716]
**Describe the bug**

We've rolled some custom drush commands which in turn execute Drupal batches (which are also executed from Drupal's web interface); however, running longer batches fail when executed via Drush.

**To Reproduce**

Execute a batch which takes longer than [`\Drush\Drush::TIMEOUT`](https://github.com/drush-ops/drush/blob/1af5fe0881809bd8baa37386748a0276747554d2/src/Drush.php#L63-L68) to execute in aggregate, but has well-behaved operations (re-entrant operation(s) or multiple individual operations; which completes via Drupal's web GUI).

**Expected behavior**

The batch completes successfully, given `drush_backend_batch_process()` [is intended to be a drop-in replacement](https://github.com/drush-ops/drush/blob/1af5fe0881809bd8baa37386748a0276747554d2/includes/batch.inc#L64-L65).

**Actual behavior**

The batch fails after `\Drush\Drush::TIMEOUT` seconds:

```
In Process.php line 1330:
  [Symfony\Component\Process\Exception\ProcessTimedOutException]                                                                                        
  The process "/opt/www/drupal/vendor/bin/drush batch-process 36 --uri=http://localhost --root=/opt/www/drupal" exceeded the timeout of 14400 seconds.  

Exception trace:
  at /opt/www/drupal/vendor/symfony/process/Process.php:1330
 Symfony\Component\Process\Process->checkTimeout() at /opt/www/drupal/vendor/symfony/process/Process.php:418
 Symfony\Component\Process\Process->wait() at /opt/www/drupal/vendor/consolidation/site-process/src/SiteProcess.php:205
 Consolidation\SiteProcess\SiteProcess->wait() at /opt/www/drupal/vendor/symfony/process/Process.php:211
 Symfony\Component\Process\Process->run() at /opt/www/drupal/vendor/drush/drush/includes/batch.inc:153
 _drush_backend_batch_process() at /opt/www/drupal/vendor/drush/drush/includes/batch.inc:79
 drush_backend_batch_process() at /opt/www/drupal/vendor/drush/drush/includes/drush.inc:227
[...]
```

**Workaround**

Don't use drush to run the given batches; run batches via Drupal's web interface in a browser.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.7.2
| Drupal version? | 8.9.13
| PHP version     | 7.2.24
| OS?             | Ubuntu 18.04

**Additional information**

It seems the approach in #4684 would address this.

**Comment by weitzman** [comment]
Not sure how to address this. We are already increasing Symfony's default timeout by orders of magntude. I guess we could increase more. I'm not eager to complicate Drush as per #4684

**Comment by adam-vessey** [comment]
There can always be a bigger batch, by which I mean to say: I'm not sure that increasing the timeout is a solution.

This is one of the issues that the batch API is made to solve, no?: Splitting up processing across multiple processes/requests to sidestep system constraints (such as PHP's `max_execution_time`), instead of attempting to process in one shot?

... otherwise, if [the batch storage procedure](https://github.com/drush-ops/drush/blob/1af5fe0881809bd8baa37386748a0276747554d2/includes/batch.inc#L117-L148) was separately invokable (could copypasta it out on my own, I suppose), I could then handle either outputting the ID to separately invoke `batch:process` so it's not executing as a _subprocess_, with this timeout constraint, or call directly to `drush_batch_command()`... though... would that work? There doesn't appear to be another loop in (or under) the `drush_batch_command()` batch command itself, so after [`break`ing out](https://github.com/drush-ops/drush/blob/1af5fe0881809bd8baa37386748a0276747554d2/includes/batch.inc#L295) when exceeding the [presently-implemented memory constraints](https://github.com/drush-ops/drush/blob/1af5fe0881809bd8baa37386748a0276747554d2/includes/batch.inc#L291-L296), it would just stop, with the batch partially processed?... would be stuck similarly looking at the output result, to determine if it has to be kicked off again?

... would probably just fork and apply #4684, before going that route.

**Comment by weitzman** [comment]
Would be nice if we got https://www.drupal.org/project/drupal/issues/1797526 done. Until then, batch isnt really a system you can robustly build upon.

**Comment by adam-vessey** [comment]
I'm... not sure that referenced issue makes sense, or at least, the intent of it is rather unclear: Batches already make use of the queue system for batch sets; and furthermore, it's possible to handle the population and processing of a queue inside of batch operations... really, seems like the proposed rework would make more sense as an entirely separate framework, more similar to the cron queues and the `drush queue:run` business.

I'm not sure the robustness of the batch framework can be fairly called into question here, when the described failure is happening in drush's implementation due to its failure to appropriately limit the run-time for which it allows itself to process. Again: The function `drush_backend_batch_process()` calls itself a drop-in replacement for `batch_process()`; however, [`batch_process()` limits the amount of time for which it will continue trying to process](https://git.drupalcode.org/project/drupal/-/blob/8.9.x/core/includes/batch.inc#L325) (of course, more than 1 second makes sense in the CLI context, especially with the `DrushBatchContext` override business allowing messages to be emitted... some large percentage of `Drush\Drush::TIMEOUT`? 75%? 90%?)... #4684 effectively allows reintroduction of the expected time-limiting, allowing one to bring the implementation somewhat more back into line with Drupal's `batch_process()`... Admittedly, the time suffix business on that PR seems like unnecessary complexity... just having whatever variable be defined as some number of seconds seems more straight-forward.

I'm willing to help roll a solution here, but am not sure of what would be acceptable. Are there any particular issues you have with the PR (#4684)? Would it be preferable to introduce as an option on the `batch-process` drush command, instead of an environment variable?

**Comment by weitzman** [comment]
You make some excellent points. My d.o. issue doesn’t really pertain.

You think https://github.com/drush-ops/drush/pull/4727 suffices? I think #4684 is a low memory issue and is better solved by setting a memory limit.

**Comment by adam-vessey** [comment]
Yeah, #4727 should do the trick: Can't timeout if there's no timeout. :P 

I... do find myself wondering if there might be _other_ resource constraints which might rear their head with one(/fewer) long-lived process(es) versus multiple shorter-lived processes... number of open files kind of thing?... though not really sure what might be done about that: the moment you extend time beyond what Drupal itself allows can get into that territory ("this batch worked in Drupal but not in Drush"); though, encouraging cleaner file handling isn't really a bad thing.

**Comment by weitzman** [comment]
FYI A new release is available, 10.4.3

**Comment by adam-vessey** [comment]
Thanks!

**Comment by 2dareis2do** [comment]
I have experienced a similar problem with long running jobs that just seem to hang. e.g. when using with migrate module with say 128MB php memory_limit

What is interesting is that when using migrate tools  UI ,which does use the batch api, the job tends to offer a much more reliable experience. Sometimes even that may timeout but if you refresh the page it tends to continue from where you left off.

I don't think migrate tools uses batch api for drush command but it certainly does when using via the UI..

Here is an example where it just seems to hang. I would expect it to show the progress bar but in this case it does not even get to that point. Other times it might use a progress bar and just hang. This example has been left for around half an hour. 

A total import should take around 40 minutes.

In this example I believe some nodes have been imported but there is nothing shown in drush to show that to be the case.

` /opt/plesk/php/8.3/bin/php -f '/var/www/vhosts/mydomain/httpdocs/vendor/bin/drush' -- '--root=/var/www/vhosts/mydomain/httpdocs/web' '--uri=https://www. mydomain' migrate:import twodareis2do_rss_google_node --update -vvv
 [preflight] Config paths: /var/www/vhosts/mydomain/httpdocs/vendor/drush/drush/drush.yml
 [preflight] Alias paths: /var/www/vhosts/mydomain/httpdocs/web/drush/sites,/var/www/vhosts/mydomain/httpdocs/drush/sites
 [preflight] Commandfile search paths: /var/www/vhosts/mydomain/httpdocs/vendor/drush/drush/src
 [debug] Bootstrap further to find migrate:import [0.65 sec, 9.43 MB]
 [debug] Trying to bootstrap as far as we can [0.65 sec, 9.44 MB]
 [info] Drush bootstrap phase: bootstrapDrupalRoot() [0.65 sec, 9.44 MB]
 [info] Change working directory to /var/www/vhosts/mydomain/httpdocs/web [0.65 sec, 9.44 MB]
 [info] Initialized Drupal 10.2.7 root directory at /var/www/vhosts/mydomain/httpdocs/web [0.65 sec, 9.48 MB]
 [info] Drush bootstrap phase: bootstrapDrupalSite() [0.65 sec, 9.93 MB]
 [debug] Loaded Drush config file at sites/default/drush.yml. [0.66 sec, 10.1 MB]
 [info] Initialized Drupal site www.mydomain at sites/default [0.66 sec, 10.1 MB]
 [info] Drush bootstrap phase: bootstrapDrupalConfiguration() [0.66 sec, 10.1 MB]
 [info] Drush bootstrap phase: bootstrapDrupalDatabase() [0.66 sec, 10.9 MB]
 [info] Successfully connected to the Drupal database. [0.66 sec, 10.9 MB]
 [info] Drush bootstrap phase: bootstrapDrupalFull() [0.66 sec, 10.9 MB]
 [debug] Start bootstrap of the Drupal Kernel. [0.66 sec, 10.9 MB]
 [debug] Finished bootstrap of the Drupal Kernel. [0.72 sec, 16.67 MB]
 [debug] Loading drupal module drush commands & etc. [0.72 sec, 16.67 MB]
 [debug] Found drush.services.yml for migrate_tools Drush commands [0.72 sec, 16.85 MB]
 [debug] Found drush.services.yml for search_api_solr Drush commands [0.72 sec, 16.85 MB]
 [debug] Found drush.services.yml for search_api_solr_admin Drush commands [0.72 sec, 16.85 MB]
 [debug] Found drush.services.yml for token Drush commands [0.72 sec, 16.85 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\sql\SanitizeCommands [0.76 sec, 21.47 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\sql\SanitizeCommentsCommands [0.76 sec, 21.47 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\sql\SanitizeSessionsCommands [0.76 sec, 21.47 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\sql\SanitizeUserFieldsCommands [0.76 sec, 21.48 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\sql\SanitizeUserTableCommands [0.77 sec, 21.48 MB]
 [debug] Add a commandfile class: Drupal\migrate_tools\Drush\Commands\MigrateToolsCommands [0.77 sec, 21.48 MB]
 [debug] Add a commandfile class: Drupal\search_api\Commands\SearchApiCommands [0.77 sec, 21.53 MB]
 [debug] Add a commandfile class: Drupal\search_api_solr\Commands\SearchApiSolrCommands [0.77 sec, 21.61 MB]
 [debug] Add a commandfile class: Drupal\search_api_solr_admin\Commands\SearchApiSolrAdminCommands [0.77 sec, 21.64 MB]
 [debug] Add a commandfile class: Drupal\token\Drush\Commands\TokenCommands [0.77 sec, 21.66 MB]
 [debug] Add a commandfile class: Drupal\pathauto\Commands\PathautoCommands [0.77 sec, 21.67 MB]
 [debug] Done with bootstrap max in Application::bootstrapAndFind(): trying to find migrate:import again. [0.85 sec, 26.67 MB]
 [info] Starting bootstrap to none [0.86 sec, 26.74 MB]
 [info] Drush bootstrap phase 0 [0.86 sec, 26.74 MB]
 [info] Try to validate bootstrap phase 0 [0.86 sec, 26.74 MB]
 [debug] Calling Drupal\migrate_tools\MigrateExecutable::import() [1.25 sec, 30.42 MB]
 
 Z
[2]+  Stopped                 /opt/plesk/php/8.3/bin/php -f '/var/www/vhosts/mydomain/httpdocs/vendor/bin/drush' -- '--root=/var/www/vhosts/mydomain/httpdocs/web' '--uri=https://www. mydomain' migrate:import two`
 
TBH I am not sure if this is an issue with Drush or Migrate Tools.

Sometimes when exiting it will output something like:

ctrl c  (kill) will also spit out the following
^C [warning] Drush command terminated abnormally. [437.95 sec, 36.2 MB]

[warning] Drush command terminated abnormally. [437.95 sec, 36.2 MB]
