### ISSUE TITLE
Allow disabling of "Redispatch to local"

### ISSUE THREAD

**Issue by AdamPS** [drush-ops/drush#4723]
**Is your feature request related to a problem? Please describe.**
Drush supports redispatch to the specific drush executable file associated with the active site.  That's useful in many cases, but it isn't perfect: sometimes drush decides that it needs to redispatch even when it's already running the correct executable.  This make drush fail with a fatal error or cause an infinite loop of launching identical new processes until all system resources are used.  Examples of how to cause this:

- #4643 
- If the site file specifies a host that actually represents the local host.  (Easy to occur with the simple strategy to use identical host files on all servers, including developer PCs and live servers.)

**Describe the solution you'd like**
Redispatch is anyway unnecessary if a decent drush launcher is used that can read the host files and always launch the correct drush.  (I wrote a simple script that also support alias groups, approx 100 lines.)

Create a way to completely disable redispatch.  This could be a command line option or config file setting.

**Describe alternatives you've considered**
I submitted a patch for #4643 to try and improve detection of the local site, but it was rejected.  I support the rejection in favour of this issue.  The redispatch detection is likely never to be perfect for all sites even with multiple patches, so this issue is much more flexible.

**Comment by greg-1-anderson** [comment]
We can definitely do this in Drush 11, where we will reject execution if Drush is not in `vendor` of the selected site (or, to put it another way, where we will only allow the local site to be targeted).

I am reluctant to allow redispatch to local to be disabled, as this could cause a lot of problems for folks who use it incorrectly to mix global and local versions of Drush. I'd rather see redispatch local fixed, which regrettably leaves you stuck between here and a lack of symlink support.

Ultimately this is @weitzman 's call though.

**Comment by weitzman** [comment]
I'm reluctant too. We'd need a compelling use case and the symlink example wasn’t it. I dont think _identical host files on all servers, including developer PCs and live servers._ is it either. See https://www.drush.org/latest/site-aliases/#environment-variables for a one way to distribute identical alias files and have them altered by local environment variables.

**Comment by AdamPS** [comment]
Thanks for the replies. There is evidence that the symlink case [is supported](https://www.drupal.org/project/drupal/issues/1792310) by Drupal core maintainers.  It sounds as if you'd rather have it fixed but won't accept the patch to fix it :-) It's not a big problem I can run with a local patch.

@weitzman  Please can you explain how I could use environment variables to meet my second use case?  I can't see how it could work.

**Comment by greg-1-anderson** [comment]
Drush does not support every configuration that core supports; for example, Drush 10 only formally supports Composer-managed sites, whereas core still supports non-Composer-managed sites. Similarly, the support for symlinks in Drush has been limited, as the support cost is high, and there are a lot of edge cases with potential for niche bugs.

**Comment by weitzman** [comment]
In an alias file, you have
```
prod:
  host: ${env.PROJECT_PROD_HOST}
```
Then your various instances can define an environment variable `PROJECT_PROD_HOST=prod.example.com` with the exception of prod itself which defines `PROJECT_PROD_HOST=localhost`.

This may or may not be a feasible way forward for your use case. I just mention that its possible to distribute the same file everywhere but have it evaluate to different things in different places. In my experience, I have rarely needed this as the code/person running the drush command is usually smart enough to know to omit the `@prod` alias when already on prod.

**Comment by AdamPS** [comment]
OK thanks again to both of you.  Feel free to close this - I will use my own local patch.
