### ISSUE TITLE
drush sql:sync does not accept --extra-dump

### ISSUE THREAD

**Issue by ceesgeene** [drush-ops/drush#4724]
**Describe the bug**
Drush (tested with version 10.4.2 sql:sync fails when passing the --extra-dump option

**To Reproduce**
Run `drush sql:sync @source @target --extra-dump=--column-statistics=0`

**Expected behavior**
The --extra-dump option to be accepted.

**Actual behavior**
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--extra-dump" option does not accept a value.

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.4.2
| Drupal version? | 8.x
| PHP version     | 7.4
| OS?             | Linux

**Additional information**

**Comment by weitzman** [comment]
Fixed in #4722. Release coming today.
