### ISSUE TITLE
[Windows] Shell table output displays content from updb slipped

### ISSUE THREAD

**Issue by sunlix** [drush-ops/drush#4741]
Hey,

I am developing on windows.
If I run the `updb` command the content read from the `update_hook` doc-blocks is displayed slipped.

Based on some research I have done, it seems to come from the line endings.
I have set the `autocrlf ` setting in git to `true`. So the git checkouts are converting the line endings to `crlf`.
If I change the line endings manually to `lf` the content is displayed correctly.

I have not found the right files where the doc-blocks are read from the files.
So I was not able to do more research on the code base.

- Drush 10.3.6
- Drupal 8.9.14
- Git Bash / Cygwin

![image](https://user-images.githubusercontent.com/301885/116551528-51a42600-a8f8-11eb-98e6-dee5f4994a6f.png)

**Comment by weitzman** [comment]
That’s done in Drupal core. See https://github.com/drupal/drupal/blob/9.2.x/core/includes/update.inc#L404-L414 (change to your version of Drupal). Please search the issue queue there and open a new issue if needed. Thanks for researching this.

**Comment by sunlix** [comment]
Just for your information @weitzman: I opened a core issue with a tiny change to handle that.

https://www.drupal.org/project/drupal/issues/3211637
