### ISSUE TITLE
Failing to use `drush-script` path on remote

### ISSUE THREAD

**Issue by macmladen** [drush-ops/drush#4742]
**Describe the bug**
Using `example.site.yml` as the base for environment deployments, we should be able to define the path where `drush` is to be able to invoke it remotely.

For a reason unknown to me, it does not work as outlined here.

```
# File: self.site.yml
#live:
#  host: server.domain.com
#  user: www-admin
#  root: /other/path/to/live/drupal
#  uri: http://example.com
stage:
  host: there.edu
  user: me
  root: /var/www/html/there.edu/web
  uri: https://there.edu
  os: Linux
  paths:
    - files: sites/default/files
    - custom: /my/custom/path
    - drush-script: /var/www/html/there.edu/vendor/drush/drush/drush
  command:
    core:
      rsync:
        options:
          mode: Pazuh
          exclude-paths: '.DS_Store:.git:.idea:node_modules:/.ddev:/assets:/web/sites/default/settings.local.php:/web/sites/default/settings.ddev.php:%files/css:%files/js:%files/php'
```

**To Reproduce**
Use `self.site.yml` from example and adjust `drush-script` path per project

`    - drush-script: /var/www/html/there.edu/vendor/drush/drush/drush`

**Expected behavior**
To use the project `drush`

**Actual behavior**
It is using just `drush` without path
 
```
mladen@lms-web:/var/www/html$ drush @stage -d cr       
 [preflight] Config paths: /var/www/html/vendor/drush/drush/drush.yml,/var/www/html/drush/drush.yml
 [preflight] Alias paths: /var/www/html/web/drush/sites,/var/www/html/drush/sites
 [preflight] Commandfile search paths: /var/www/html/vendor/drush/drush/src,/var/www/html/web/themes/contrib/radix,/var/www/html/drush
 [debug] Redispatch hook cr [0.95 sec, 3.61 MB]
 [info] Executing: ssh -t -o PasswordAuthentication=no me@there.edu 'drush -vvv cr --uri=https://there.edu --root=/var/www/html/there.edu/web' [1.06 sec, 3.79 MB]
PHP Warning:  require(/var/www/html/there.edu/vendor/composer/../../web/core/includes/bootstrap.inc): failed to open stream: No such file or directory in /var/www/html/there.edu/vendor/composer/autoload_real.php on line 75
```

**Workaround**
Drush could be symlinked to some of the active paths (like `/usr/local/bin`) but that is hardly a solution.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.4.3
| Drupal version? | 9.1.7
| PHP version     | 7.3
| OS?             | Linux (Mac Intel, ddev, Docker 3.1.0. build 51484 Engine 20.10.2)

**Additional information**
How about `drush` launcher? But still it needs to be installed system wide while with path we can access the right one directly.

**Comment by weitzman** [comment]
I'm not sure whats going on here. You might be able to that a PATH env variable on the ssh call thus having the right `drush` get executed on the remote side. See "complex example" at https://www.drush.org/latest/site-aliases/#additional-site-alias-options
