### ISSUE TITLE
Allow webprofiler to fire when Drush commands are executed

### ISSUE THREAD

**Issue by lpeabody** [drush-ops/drush#4745]
**Is your feature request related to a problem? Please describe.**
I specifically want to be able to see all events fired during a script that is executed via `drush php:script`. Ideally the entire execution of the Drush command would get tracked, it need no be specific to `php:script`.

**Describe the solution you'd like**
A profile gets created for the execution of the Drush command and I can review it afterwards at /admin/reports/profiler/list.

If there are any thoughts on how or where to get started with this, I'll happily tinker with it.

**Comment by weitzman** [comment]
I guess coax profiler to listen on https://symfony.com/doc/current/components/console/events.html events. Develop with a full bootstrap command like pm:list, because I dont know if webprofiler will be loaded enough otherwise.
