### ISSUE TITLE
Config export/import problem

### ISSUE THREAD

**Issue by makgab** [drush-ops/drush#4746]
**Describe the bug**
Config import problem

**To Reproduce**
1. I created a docker/podman container with latest drupal. I saved the config: `drush cex`
2. I created another container with same latest drupal
3. container1# `drush config-get "system.site" uuid`
3. container2# `drush config-set "system.site" uuid "xxxxxxxxxxxxxxxxxxxxxx"`
4. container2# I tried to import config: drish cim
5. container2# `drush cim --source=/opt/drupal/web/sites/default/files/config_jUGyAAiTeixxxxxxxxxxxxxxxxxxxxxxxxxxxx/sync/`

**Expected behavior**
Config imports.

**Actual behavior**
Import does not work. "drush cim" error:
In ConfigImportCommands.php line 360:
The import failed due to the following reasons:
"_There are still Quick Link type entities and Default field groups labeled Quick Link Group that must be deleted before importing."_

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.4.3
| Drupal version? | 9.1.7
| PHP version     | 7.x
| OS?             | Linux

**Additional information**
Containers from here: docker.io/library/drupal

**Comment by weitzman** [comment]
That message comes from drupal not drush.
