### ISSUE TITLE
Support for watchdog:show --tail

### ISSUE THREAD

**Issue by dajjen** [drush-ops/drush#4756]
In drush 8 you could do  `drush ws --tail` this is not possible in drush 10.
This would be nice to have.

using the `while sleep 2; do drush watchdog:show; done` is not that great cause you will get the same 10 lines every 2 seconds if the log hasn't printed anything new.

**Comment by weitzman** [comment]
Feel free to work on #3523.

**Comment by beejeebus** [comment]
a simple alternative to `while sleep 2; do drush watchdog:show; done` is:

`watch drush watchdog:show`

**Comment by beejeebus** [comment]
started on this [#4767].

**Comment by beejeebus** [comment]
#4767 was merged, so I think we can close this.
