### ISSUE TITLE
drush site:install doesn't check for missing file permissions in sites/default/files

### ISSUE THREAD

**Issue by holybiber** [drush-ops/drush#4768]
I'm a fairly new drupal user and this made my start quite a lot harder when trying to get a local version running. I'll try my best to write a meaningful issue here.

**Describe the bug**
drush site:install runs fine. But opening the website on my local computer gives me the website without any stylesheets: very hard to read. Firefox console says cryptic things like
> The resource from “http://localhost/sites/default/files/js/js_PhspFyJbTFLkogCyyAHUvNzOQeMpr01fYllk37PWf9M.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
> The resource from “http://localhost/sites/default/files/color/bartik-1693e579/colors.css?q0weem” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

**To Reproduce**
Install brand new drupal site with composer
Set up database
drush site:install
Open the resulting website in browser

**Expected behavior**
A nice-looking drupal page
A warning by drush that parts of the installation actually failed

**Actual behavior**
drush said: [success] Installation complete.
But resulting website is rendered without stylesheets

**Workaround**
It took me quite a while to figure out the problem (navigating the page without any stylesheets is tedious...)
Then I learned about http://localhost/admin/reports/status and there I found the problem: "The directory sites/default/files is not writable."
-> I fixed permissions so that this folder becomes writeable by the apache user
-> again drush site:install
-> now it worked

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.5.0
| Drupal version? | 9.1.10
| PHP version     | 7.4.3
| OS?             | Linux

**Additional information**
I think I had in between the situation that the folder sites/default/files was already writable by the apache user but in there was at least one sub-folder that was not writable. This resulted again in a broken website but admin/reports/status not giving me a warning. It would be great to do more detailed checks (not just "is sites/default/files writable: yes/no") to see if all attempts to write files were actually successful.

**Comment by weitzman** [comment]
This is out of scope for Drush. We trust that you have setup requirements before running the command. After install, you can run `drush rq` to see any requirements errors from Drupal.
