### ISSUE TITLE
Should `drush cst` return the string into STDOUT instead of STDERR?

### ISSUE THREAD

**Issue by isholgueras** [drush-ops/drush#4769]
**Describe the bug**
We have a job and one of the commands is `drush cst | "No differences"` to check there are no differences. This should return 0 to STDERR and continue the job, as we have with some other commands.

The job always stops at this step because of a different code than 0 in STDERR.

**To Reproduce**
Executing the following in the command line (both /bin/sh or /bin/bash). I've added `(##` comments to explain it better
```
root@php:/var/www/html# drush cst > /tmp/config-diff
 [notice] No differences between DB and sync directory. (##sending the stdout to a file, shouldn't print anything)
root@php:/var/www/html# cat /tmp/config-diff (##The file is empty)
root@php:/var/www/html# drush cst 2>/tmp/config-diff (##sending the stderr to a file, should return anything)
root@php:/var/www/html# cat /tmp/config-diff (## and the output is now in that file.)
 [notice] No differences between DB and sync directory.
root@php:/var/www/html# drush status > /tmp/status (## To discard it's a drush logger issue, I've done the same with status)
root@php:/var/www/html# cat /tmp/status 
 Drupal version   : 8.9.16                                                      
 Site URI         : https://default/ 
 DB driver        : mysql    
...
```
**Expected behavior**
The same status, in term of stdout and stderr, than `drush status`

**Actual behavior**
The output is sent to STDERR(2) instead of STDOUT(1)

**Workaround**
The current workaround is to send STDERR to STDOUT as the following:
`drush -r cst 2>&1 | grep "No differences"`

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.6
| Drupal version? | 8.9.16
| PHP version     | 7.3.28
| OS?             | Linux

**Additional information**
NA

**Comment by weitzman** [comment]
The 'No diffs' text is a log message and is sent to stderr. In drush status, the values are considered data and are sent to stdout. These are opinions as opposed to facts, so its OK if you disagree ... Your test can just check for emptiness on stdout. I'd be happy to add that as a Usage example if you want to help the docs with a PR.

**Comment by isholgueras** [comment]
I thought all status for drush were sent to stdout. We've spent some time until we realize `cst` specifically, and maybe other, could be sent to stderr. It's ok.

Sure! I've created this PR. I hope is the right place: https://github.com/drush-ops/drush/pull/4772

Thanks!
