### ISSUE TITLE
Drush config:import exit code varies between Drush versions with --no flag.

### ISSUE THREAD

**Issue by adamzimmermann** [drush-ops/drush#4770]
**Describe the bug**

In Drush 8, `drush cim --no` returned a 0 exit code.

In Drush 10, `drush cim --no` returned a non-0 exit code.

We were previously using `drush cim --no --preview` to show a list of changes during a CI process that someone before me setup. I'm not convinced we need that so I just removed it. I realize we could also force the command to exit with success with `drush cim --no || true`.

The main goal of this issue is really just to understand if that change was intentional. If it was, then I don't think there is anything to do here. If it wasn't, that still might be the case, but perhaps it is worth documenting? 🤷🏼‍♂️ 

**To Reproduce**
Run `drush cim --no` with two different Drush versions and saw different exit codes. FWIW this only happens if there are changes to import. See screenshot below:

<img width="1440" alt="Screen Shot 2021-06-10 at 9 22 03 AM" src="https://user-images.githubusercontent.com/1349906/121542262-a04fe000-c9cd-11eb-951c-849053b28ebd.png">

**Expected behavior**
Exit code would be 0.

**Actual behavior**
Exit code is non-zero.

**Workaround**
Noted above.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.x/9.x/8.x (please be specific, and try latest release)
| Drupal version? | 8.x
| PHP version     | 7.4
| OS?             | Mac/CircleCi

**Additional information**

**Comment by weitzman** [comment]
Sounds like you should be using [config:status](https://www.drush.org/latest/commands/config_status).

**Comment by weitzman** [comment]
To answer your question, the --no flag did change meaning and that was deliberate. It now cancels at any interactive prompt, and signals an error. You could try  `--no-interaction` to see if it does what you want.

**Comment by adamzimmermann** [comment]
Sounds good, thank you!
