### ISSUE TITLE
warnings from migrate-rollback

### ISSUE THREAD

**Issue by quietone1** [drush-ops/drush#4771]
**Describe the bug**
Undefined array errors from migrate-rollback.

**To Reproduce**
```
$ ddev drush mr d7_system_mail
 [warning] Undefined array key "idlist" MigrateExecutable.php:158
 [warning] Undefined array key "limit" MigrateExecutable.php:163
 [warning] Undefined array key "timestamp" MigrateExecutable.php:165
 [warning] Undefined array key "total" MigrateExecutable.php:166
 [warning] Undefined array key "delete" MigrateExecutable.php:167
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 [notice] Rolled back 1 item - done with 'd7_system_mail'

```

**Expected behavior**
That there would be no warnings

**Actual behavior**
There are 5 warnings everytime I do a rollback.

**Workaround**
Use Migrate Tools and drush 10.3.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | Drush Commandline Tool 10.5.0
| Drupal version? | 9.3.x
| PHP version     | 8.0
| OS?             | Linux

**Additional information**

**Comment by claudiu-cristea** [comment]
@quietone1, thank you for this report. I've opened #4774 as PR, could you review it?

**Comment by quietone1** [comment]
All fixed. :-)

Tested with Drupal 9.3.x and drush 10.6.0-dev
```
$ ddev drush mim system_site
/var/www/html/vendor/bin/drush mim system_site
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 [notice] Processed 1 item (1 created, 0 updated, 0 failed, 0 ignored) in 0.2 seconds (343.2/min) - done with 'system_site'
$ ddev drush mr system_site
/var/www/html/vendor/bin/drush mr system_site
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 [notice] Rolled back 1 item - done with 'system_site'
$ ddev drush --version
/var/www/html/vendor/bin/drush --version
Drush Commandline Tool 10.6.0-dev
```

Thank you!
