### ISSUE TITLE
When reading documentation it is unclear what version of Drush is recommended, Drush 10 docs missing

### ISSUE THREAD

**Issue by frob** [drush-ops/drush#4776]
**Describe the bug**
There appear to be stable releases for Drush 10 and drush 10 is shown in some of the latest drush/drupal version support matrix. However, the docs on most sites (including docs.drush.org) do not list docs for Drush version 10. Instead there are warnings such as these. 

![Latest Version of Drush is 9.x warning](https://user-images.githubusercontent.com/316176/122616431-2e1b7300-d03f-11eb-9511-d9082e0d505c.png)

And clicking the version selector shows only 9.x, 8.x, and 7.x available.

![image](https://user-images.githubusercontent.com/316176/122616511-5a36f400-d03f-11eb-8da8-c54d79706725.png)

Where are the docs for Drush 10?

**To Reproduce**
Visit https://docs.drush.org/en/8.x/install/ and get a warning that the latest version is Drush 9.x

**Expected behavior**
I would expect to get a warning that Drush 10 is the latest.

**Actual behavior**
Got a warning that Drush 9.x was the latest.

**Workaround**
Sometimes when searching I will end up on https://www.drush.org which I *think* is the latest version of the docs but it isn't labeled as the docs for drush 10 and there isn't a link to there from https://docs.drush.org which is really confusing.

**Comment by weitzman** [comment]
Changed the 8.x docs. Hope that’s more clear.
