### ISSUE TITLE
core:cron terminated abnormally

### ISSUE THREAD

**Issue by Al-Rozhkov** [drush-ops/drush#4784]
**Describe the bug**
Command failed with `Error: __clone method called on non-object in Drupal\Core\Routing\UrlGenerator->getRoute() (line 426 of .../web/core/lib/Drupal/Core/Routing/UrlGenerator.php ... Drupal\Core\Routing\UrlGenerator->getRoute('update.status')`.

Cron started via web UI works without any errors/warnings in logs.

**To Reproduce**
- Run `drush -l mysite cron` failed abnormally.
- Run `drush -l mysite cc` clear cache for router.
- Run `drush -l mysite cron` and it works fine.
- Wait for 2 hours, `cron` fails again.

**Expected behavior**
Cron executed successfully.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.5.0
| Drupal version? | 9.2.0
| PHP version     | 7.4.10
| OS?             | Linux

**Additional information**
Multisite Drupal installation.

**Comment by weitzman** [comment]
Not a drush issue

**Comment by penyaskito** [comment]
Shouldn't be a Drush issue, but I'm experiencing the same. Will update when I find out what's going on.

**Comment by penyaskito** [comment]
Still figuring out what's going on,  but my scenario is:

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.6.1
| Drupal version? | 9.3.2
| PHP version     | 7.4.29 (yeah, I know)
| OS?             | Linux (can only reproduce on prod)

**Additional information**
No multisite. Just a single site.

**Comment by penyaskito** [comment]
btw I'm using postgre: @Al-Rozhkov was that your case too?
