### ISSUE TITLE
user signup not working drupal 9.2

### ISSUE THREAD

**Issue by karthik-code** [drush-ops/drush#4788]
**Describe the bug**
User signup not working on drush installation, the same is working when we do using web interface. 

**To Reproduce**
composer create-project drupal/recommended-project drupal9
cd drupal9
composer require drush/drush
drush site-install

Access drupal in browser
go to user/register
Fill up the signup form and submit

**Expected behavior**
The following success status message to be displayed 
"Thank you for applying for an account. Your account is currently pending approval by the site administrator.
In the meantime, a welcome message with further instructions has been sent to your email address."

**Actual behavior**
But, the following error status message showing
"The value you selected is not a valid choice."

**Workaround**
Unable to find a solution. 

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.5.0
| Drupal version? | 9.2
| PHP version     | 7.4.3
| Database     | MySQL 8.0
| OS?             | Linux - Ubuntu 20.04 LTS

**Additional information**
I have tried changing the mysql version to 5.7, but that too didn't work. But, the same perfectly works on web interface installation.

**Comment by weitzman** [comment]
new user approval is a drupal setting that you can disable. Unrelated to drush.

**Comment by karthik-code** [comment]
I am not telling about the settings, user signup page shows error only on the site installed using the command drush site-install.
That's the reason I am raising the issue here. 
`The value you selected is not a valid choice.`

**Comment by gloomcheng** [comment]
I faced the same issue, and found the problem is drush site:install command not set "Default country" option.
The problem solved after set "Default country" at `/admin/config/regional/settings`

**Comment by dj-pasha** [comment]
> Я зіткнувся з такою ж проблемою, і виявив, що проблема полягає в тому, що команда drush site:install не встановила параметр «Країна за замовчуванням». Проблему вирішено після встановлення «Країни за замовчуванням» у`/admin/config/regional/settings`

Мені також це допомогло для drupal 10.0.2. Дякую!)
