### ISSUE TITLE
Using 2 differents versions of drush

### ISSUE THREAD

**Issue by webmasterpf** [drush-ops/drush#4789]
Hi,

I actually use Drush 8 to manage Drupal 6 website on my shared hosting.
I actually add a Drupal 8 website for dev and migration, managed by Drush 9.

So this is the actual location for drush files:
```
Drush script : /home/xxx/bin/composer/composer.phar/vendor/drush/drush/drush.php
Drush version : 8.1.15
```

```
Drush script : /home/xxx/www/pfdev/multid8/vendor/drush/drush/drush
Drush version : 9.7.3
```

Only Drush 8 site alias works, for Drush 9 I need to go into the site folder to get it work.
Alias are well listed by drush sa .
PATH contain both paths to Drush 8 and Drush 9.
So I think I need to create a command alias like "`drush9`" to run drush 9 commands every where in the folder tree.
Where can I find this kind of documentation ?

Thanks

**Comment by weitzman** [comment]
Please use Drupal Answers for support questions.

**Comment by webmasterpf** [comment]
where ?
