### ISSUE TITLE
Encoding problems in drush 7 running on Windows

### ISSUE THREAD

**Issue by TealAlex** [drush-ops/drush#4796]
Hi,

I am not very familiar with PHP, Drupal and drush but I inherited a site running on Windows Server 2019 (in the process of being migrated from Ubuntu). When I want to download some webforms using drush wfx, special characters like German "Umlaute" ä, ö and ü in the webform contents are not correctly displayed.

I am running Drupal 7.81 und using drush 7.0.0. I also tried to specifially set the encoding to UTF-8 in the config file drushrc.php (even though the description in the file says, it should not be necessary because drush will use UTF-8 anyway). In the browser, the characters in the webform show up correctly.

The database character set is utf8.

Any idea what to try and how to troubleshoot?

PS > Get-CimInstance -ClassName Win32_OperatingSystem | fl Caption,Version

Caption : Microsoft Windows Server 2019 Standard
Version : 10.0.17763
PS C:\xampp\mysql\bin> .\mysql.exe -uroot
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 7405
Server version: 10.1.38-MariaDB mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SELECT @@character_set_database,@@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| latin1                   | latin1_swedish_ci    |
+--------------------------+----------------------+
1 row in set (0.00 sec)

MariaDB [(none)]> USE drupal;
Database changed
MariaDB [drupal]> SELECT @@character_set_database,@@collation_database;
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| utf8                     | utf8_general_ci      |
+--------------------------+----------------------+
1 row in set (0.00 sec)
PS C:\xampp\htdocs\onboarding> drush version
 Drush Version   :  7.0.0

PS C:\xampp\htdocs\onboarding> drush status
 Drupal version                  :  7.81
 Site URI                        :  http://default
 Database driver                 :  mysql
 Database hostname               :  localhost
 Database port                   :
 Database username               :  drupal
 Database name                   :  drupal
 Drupal bootstrap                :  Successful
 Drupal user                     :
 Default theme                   :  garland
 Administration theme            :  seven
 PHP executable                  :  php.exe
 PHP configuration               :  C:\drush\php\php.ini
 PHP OS                          :  WINNT
 Drush script                    :  C:\drush\vendor\drush\drush\drush.php
 Drush version                   :  7.0.0
 Drush temp directory            :  C:\Users\%USERNAME%\AppData\Local\Temp\13
 Drush configuration             :  C:\ProgramData\drush\etc\drush\drushrc.php
 Drush alias files               :
 Install profile                 :  standard
 Drupal root                     :  C:\xampp\htdocs\onboarding
 Site path                       :  sites/default
 File directory path             :  sites/default/files
 Temporary file directory path   :  /tmp

**Comment by greg-1-anderson** [comment]
Drush 7 is no longer maintained, and will receive no further updates. You should try upgrading to Drush 8. This probably will not fix your problem.

Drush 8 is under maintenance fixes only, and Windows is minimally maintained. If you find a solution to your encoding problem on Drush 8, a PR would be welcome.
