### ISSUE TITLE
Can't detect the config diff to import or export configurations

### ISSUE THREAD

**Issue by nakarimi** [drush-ops/drush#4804]
I have Drupal 8.9 and Drush 10. 
Created update the view and duplicate the default page, so I have a view with 2 page, also I change some configurations. But when I try to export my view changes, Drush can't detect changes and export them, even I try to import to override new changes. And again Drush can't detect the changes to be applied.
![image](https://user-images.githubusercontent.com/28529970/129147459-538f51f7-410f-491e-942f-09dfb4223fc3.png)

**Comment by nakarimi** [comment]
**The temporary solution to just continue development,**
is that for small changes it can't be tracked, so we can do some big fake change, like creating a fake view or removing a view, and then do export the config, then check with git diff.

Also may in export message you don't see your changes in the list but continue and then change the changes applied on files.

Note: the important thing is keep that fake change in mind and don't add it to git, once you exported config, stash the fake one.

**Comment by weitzman** [comment]
This would be a drupal bug if there is one. Drupal does the actual same and export of config
