### ISSUE TITLE
Internal fork of YAML parser does not handle multi-line strings

### ISSUE THREAD

**Issue by Sweetchuck** [drush-ops/drush#4808]
**Describe the bug**
Internal fork of YAML parser does not handle multi-line strings.

**To Reproduce**
PHP version >= 8.0.0
Add the following line to a `drush.yml` file:
```yaml
foo:
  description: >
    My long description.
    Sentence 2.
    Sentence 3.
  bar: 42
```

**Expected behavior**
Parse the YAML file correctly.

**Actual behavior**
Fatal error: Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in /.../src/internal-forks/Config/Yaml/Parser.php on line 682
\Drush\Internal\Config\Yaml\Parser::parseValue() thinks that there is no $modifier, and the $value became `>`.
An empty string is assigned to $modifier, which will be passed to the `abs()` function. 

**Workaround**
Do not use `>` or `|` or any other modifiers in `drush.yml` files for long texts.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.5.0
| Drupal version? | 9.2.2
| PHP version?    | 8.0.9
| OS?             | Linux

**Comment by weitzman** [comment]
Instead of updating the fork, maybe we could get rid of it? What do you think @greg-1-anderson? See https://github.com/drush-ops/drush/blob/e484ee61a95e9fa085a785ab19ada9183cf26a45/src/internal-forks/Config/Yaml/README.md?plain=1#L6-L11.

**Comment by greg-1-anderson** [comment]
I think we can remove the forked yaml library in Drush 11.
