### ISSUE TITLE
Can't update robo

### ISSUE THREAD

**Issue by smustgrave** [drush-ops/drush#4812]
**Describe the bug**
We are currently on drush/drush 10.6.0 per the recommendation of Drupal 9 we are on PHP 8
But drush is requiring consolidation/robo: ^1.4.11 || ^2 which IS NOT compatible with PHP 8
Robo has a version 3 that is but we can't update because Drush is blocking that.

**Comment by greg-1-anderson** [comment]
So I looked at it again, and it would be tedious / difficult to make a league/container 2.x wrapper that matched the league/container 3.x API. The Container::add() method returns a DefinitionInterface, and these are quite different between 3.x and 2.x.

Compare [addArgument in 3.x](https://github.com/thephpleague/container/blob/3.x/src/Definition/DefinitionInterface.php#L82) with [withArgument in 2.x](https://github.com/thephpleague/container/blob/2.x/src/Definition/DefinitionInterface.php#L21).

To make a wrapper, you'd need a container wrapper that returned a definition wrapper that provided addArgument and called through to withArgument. The problem, though, is that the 3.x API is more expressive, so the wrapper would be fragile.

Another option would be to have completely different mirror implementation of Drush's DI container initialization code. This isn't great, though, as this code is kind of intricate, and we'd be signing up to making changes in duplicate any time there was an adjustment to the preflight. That's probably not going to happen often, but it's still not great.

So the other thing is, what if we made a Robo 2 release compatible with PHP 8? The main problem there is testing. Robo 2.x does not have the php-8-compatible phpunit test suite from the 3.x branch. If someone wanted to backport that, then I'd make a Robo 2 release that worked with php 8.

The latest version of league/container 2.x is now php 8 compatible, so we could probably remove the pin of that component. The only php 8 incompatibility in Robo 2.x that I'm aware of is the test suite.

So, I think the conclusion is that someone has to sign up to do a lot of work, or just accept that Robo 2 "happens to work" with PHP 8.

**Comment by greg-1-anderson** [comment]
Of the options above, the lowest-effort way to get Robo 3 into Drush 10 would be to duplicate the DI container init code in Drush, and have both league/container 2.x and 3.x implementations. The league/container 2.x version (existing code) could be immediately deprecated, and the league/container 3.x version could carry forward to Drush 11, where it will be needed in any event.

**Comment by greg-1-anderson** [comment]
Specifically, most of [DependencyInjection.php](https://github.com/drush-ops/drush/blob/10.x/src/Runtime/DependencyInjection.php) would need to have two versions.

**Comment by weitzman** [comment]
That lowest-effort plan sounds good to me.

**Comment by greg-1-anderson** [comment]
Should be working in the Drush 10 dev branch now.
