### ISSUE TITLE
drush sset not working in drush 10.6.0

### ISSUE THREAD

**Issue by holybiber** [drush-ops/drush#4813]
**Describe the bug**
As of drush 10.6.0, the following commands don't work as expected for me:
`drush sset system.maintenance_mode 1 --input-format=integer`
`drush state:set system.cron_last 1406682882 --input-format=integer`
Both fail with
> Too many arguments, expected arguments "command" "key"

Also replacing `sset` with `state:set` and/or removing `--input-format=integer` doesn't make a difference.

I tried it on two systems. When I revert back to drush 10.5.0, everything works as expected.

**To Reproduce**
Run the commands above with drush 10.6.0

**Expected behavior**
Put site to maintenance mode / update timestamp for last cron run

**Actual behavior**
drush fails with the error mentioned above

**Workaround**
Using drush 10.5.0

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.6.0 (installed via composer)
| Drupal version? | 9.2.4
| PHP version     | 7.4.3 / 7.3.29
| OS?             | Linux

**Comment by shean42** [comment]
The cset command is affected by this too.

**Comment by ThomWilhelm** [comment]
I'm hitting this same issue. I too assumed it was the recent upgrade to drush 10.6.0 that broke this. But reverting to 10.5.0 I still receive the same error. Any workarounds would be greatly appreciated!

**Comment by ThomWilhelm** [comment]
Workaround, pin the **consolidation/annotated-command** package to a version earlier than 4.3.0, eg. so in your composer.json:

**"consolidation/annotated-command": "4.2.4",**

**Comment by greg-1-anderson** [comment]
Seems to be related to the release of consolidation/annotated-command:4.3.0. Pin to ~4.2.0 as a workaround. Investigating.

**Comment by greg-1-anderson** [comment]
I've identified the issue, and think I can probably resolve it with a new annotated-command release without requiring any changes to Drush.

**Comment by greg-1-anderson** [comment]
https://github.com/consolidation/annotated-command/pull/231 seems to clear this up. Will release as 4.3.1.

**Comment by shean42** [comment]
Looks good, thanks much!!

**Comment by greg-1-anderson** [comment]
Fixed in consolidation/annotated-command 4.3.1; run `composer update` to resolve.

**Comment by ThomWilhelm** [comment]
Thanks for the quick fix!

**Comment by holybiber** [comment]
For some reason on the one system I first had to do a `drush cr`.
But now it's working fine again, thank you very much!
