### ISSUE TITLE
version 10.6: "Too many arguments, expected arguments [...]" for config:set / cset command

### ISSUE THREAD

**Issue by mxhCodes** [drush-ops/drush#4816]
**Describe the bug**
Since version 10.6 using Drupal 9.2.4, the cset command does not work anymore.

**To Reproduce**
Running for example

`drush cset system.site uuid sgsdgsghesthesh-dfgesdgh-ageshe-w345345-sdfwf3f -y`

**Expected behavior**
The command should work without errors.

**Actual behavior**
Returns error:
`Too many arguments, expected arguments "command" "config_name" "key".`

**Workaround**
Until version 10.5, above mentioned command worked without errors.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.6
| Drupal version? | 9.2.4
| PHP version     | 7.4
| OS?             | Linux

**Comment by mxhCodes** [comment]
Sorry, tried to reproduce it again and failed. Will try to reproduce and report back once succeeded.

**Comment by holybiber** [comment]
See https://github.com/drush-ops/drush/issues/4813
