### ISSUE TITLE
Add continue-on-failure option to migrate:status

### ISSUE THREAD

**Issue by benjifisher** [drush-ops/drush#4819]
**Is your feature request related to a problem? Please describe.**

Calling `migrate:status` with a list of migration names generates a failure if any of the names is invalid:

```
$ drush migrate:status callback_test,invalid_name

In MigrateRunnerCommands.php line 765:
                                       
  Invalid migration IDs: invalid_name
```

**Describe the solution you'd like**

Provide an option to alter the default behavior. Show the status of all valid migration names. Perhaps provide a warning (not an error) for invalid names.

```
$ drush migrate:status callback_test,invalid_name
 --------------- -------- ------- ---------- ------------- --------------------- ------------------- 
  Migration ID    Status   Total   Imported   Unprocessed   Last Imported         Group              
 --------------- -------- ------- ---------- ------------- --------------------- ------------------- 
  callback_test   Idle     2       2 (100%)   0             2021-09-01 13:09:44   Default (default)  
 --------------- -------- ------- ---------- ------------- --------------------- ------------------- 
```

**Describe alternatives you've considered**

If this option can be implemented outside of Drush core, then we may do that in the `migrate_tools` module. Any advice is welcome!

**Additional context**

In `Migrate_tools`, we plan to implement the same option for `migrate:import` and `migrate:rollback`. The current implementation overrides these commands entirely.

**Comment by weitzman** [comment]
Why is this needed? User can just fix or omit wrong name, no?
