### ISSUE TITLE
drush_print() replacement produces no output in an update hook

### ISSUE THREAD

**Issue by phil-s** [drush-ops/drush#4829]
**Describe the bug**

In the past we could output to the terminal when running `drush updb` using `drush_print()`.

The 'log' commands produce additional output which is not always suitable, so it was important to have the option of plain printing without enforced newlines for better control.

Seemingly `drush_print()` has been replaced by `\Drush\Drush::output->write()` and `writeln()` but they produce no output within an update hook.

They *do* work in at least some other contexts, however.  E.g.:
```
drush php-eval '\Drush\Drush::output()->writeln("Hello, world.");
```

**To Reproduce**

Add an update hook containing:
```
  \Drush\Drush::output()->writeln("Hello, world.");
```

And run `drush updb -y`

**Expected behavior**

`Hello, world.` would be printed in the terminal as part of the output.

**Actual behavior**

    >  [notice] Update started: foo_update_9001
    >  [notice] Update completed: foo_update_9001
     [success] Finished performing updates.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.6
| Drupal version? | 9.1.12
| PHP version     | 7.4.21
| OS?             | GNU/Linux

**Comment by weitzman** [comment]
Update hooks have a way to return messages for printing. I suggest using that.

**Comment by phil-s** [comment]
What is that way?

**Comment by phil-s** [comment]
If you mean the <a href="https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Extension!module.api.php/function/hook_update_N">return value</a> of the update function ("Optionally, update hooks may return a translated string that will be displayed to the user after the update has completed"), then that's not a replacement at all.  If that *is* what you mean, could you please re-open this?

<code>drush_print()</code> allows progressive output with full control over formatting (e.g. without newlines or any automated prefix/suffix text) which (used to) enable an update hook to provide status updates <em>while</em> the update hook progresses (e.g. during a loop over arbitrary items).

**Comment by tostinni** [comment]
This is also the case when running `hook_post_update_name()` and yes `drush_print()` was more powerfull.

Can this been added as a feature request ?

**Comment by abelass** [comment]
+1

**Comment by ksenzee** [comment]
If you want output to the screen during a drush updb, your best bet right now is `\Drupal::logger('your_module')->notice('your message');`. If you use `\Drupal::messenger()->addMessage('your message');` you'll get the output, but not until the update function has finished. I agree it was very nice to be able to print, say, one dot to the screen for each item you're looping over, and I'd love to see a replacement for that.

**Comment by apotek** [comment]
> your best bet right now is `\Drupal::logger('your_module')->notice('your message');`

In Drupal 10 with Drush 12, this seems to no longer output anything when running drush. `\Drupal::logger()` doesn't print anything to your shell from a drush command context.  `\Drupal::messenger()->addMessage('your message');` also will not output anything to screen.

**Comment by gauravmanerkar** [comment]
@apotek 
Did you find any solution for Drush 12?

**Comment by duartegarin** [comment]
I'm encountering this as well. Is there any workable solution?

**Comment by apotek** [comment]
@gauravmanerkar @duartegarin Those who know best have made their decrees and we are out of luck. The only path I see is to duplicate your output in your drush commands, once for watchdog/logging and once for user feedback. And then hope the user isn't on Drush 11 where they will see duplicate output. One way to mitigate that is to wrap your user feedback in a check for Drush version >= 12. (I'm using `$this->io()` to provide real-time feedback to the drush user while commands are running but you may prefer another way).

You can decrease the code duplication/pain of this by creating a wrapper function or service for your drush commands, and then, when you want to log and output, use that service or function instead. You'll have to translate log levels to io levels (or whatever else you are using) etc, but once you are done with that engineering, duplicating your output to both the user and log should be pretty painless.
