### ISSUE TITLE
Drupal 9 Drush 10 infinite loop '[preflight] Redispatch to site-local Drush'

### ISSUE THREAD

**Issue by tommym9** [drush-ops/drush#4831]
Hi,

I'm seeing an odd issue when I'm upgrading Drush from 8.4.0 to 10.3.1 as part of a Drupal 8 => 9.0.0 upgrade.

When running `drush status --debug` I'm seeing the following output (truncated to just two iterations):

```
MacBook-Pro:drupal user$ drush status --debug
Drush Launcher Version: 0.9.1
ROOT: /Users/user/code/drupal
DRUSH VERSION: 10
DRUPAL ROOT: /Users/user/code/drupal/web
COMPOSER ROOT: /Users/user/code/drupal
VENDOR ROOT: /Users/user/code/drupal/vendor
 [preflight] Redispatch to site-local Drush: '/Users/user/code/drupal/web/vendor/drush/drush/drush'.
Using the Drush script found at /Users/user/code/drupal/vendor/drush/drush/drush
 [preflight] Redispatch to site-local Drush: '/Users/user/code/drupal/web/vendor/drush/drush/drush'.
Using the Drush script found at /Users/user/code/drupal/vendor/drush/drush/drush
```

The same issue crops up when running `vendor/bin/drush status --debug` so its not the launcher having a problem, but Drush itself.

I've seen some other issues around this and I've updated launcher to the latest version locally and checked there are no symlinks in my project.

Any help is hugely appreciated. I'm not sure what the next steps for debugging are.

Cheers

Tom

**Comment by tommym9** [comment]
OK so a bit more information. Running `vendor/bin/drush status -vvv --root=vendor/bin/drush` gave me this:

```
MacBook-Pro:drupal user$ vendor/bin/drush status -vvv --root=vendor/bin/drush
 [preflight] Config paths: /Users/user/.drush/drush.yml,/Users/user/code/drupal/vendor/drush/drush/drush.yml
 [preflight] Alias paths: /Users/user/.drush/sites,/Users/user/code/drupal/vendor/drush/drush/drush/sites
 [preflight] Commandfile search paths: /Users/user/code/drupal/vendor/drush/drush/src
 [debug] Starting bootstrap to max [0.13 sec, 9.2 MB]
 [debug] Trying to bootstrap as far as we can [0.13 sec, 9.2 MB]
 PHP binary    : /usr/local/Cellar/php/7.4.9/bin/php
 PHP config    : /usr/local/etc/php/7.4/php.ini
 PHP OS        : Darwin
 Drush script  : /Users/user/code/drupal/vendor/drush/drush/drush
 Drush version : 10.3.1
 Drush temp    : /tmp
 Drush configs : /Users/user/.drush/drush.yml
                 /Users/user/code/drupal/vendor/drush/drush/drush.yml
 Drupal root   : /Users/user/code/drupal/vendor/drush/drush/sut
```

This one can complete, but doesn't pick up any of the site information.

Cheers

Tom

**Comment by weitzman** [comment]
Get rid of the drush launcher and the drush8 that's in your environment. Then add drush as a composer dependency in your project and call in with vendor/bin/drush.

**Comment by weitzman** [comment]
Just seeing your last comment. Yes --root should point to drupal root

**Comment by tommym9** [comment]
Ah I didn't make it clear in my issue, but I have drush as a composer
dependency.

Calling drush directly at vendor/bin/drush has the same redirect loop.

Will give binning off the launcher a go and see what happens.

Cheers

Tom

**Comment by tommym9** [comment]
Hi,

I removed global drush from my machine. I also removed it from global composer just to be sure. When I run `drush status --debug` I now see:

```
user@drupal-web:/var/www/html$ drush status --debug
 [preflight] Redispatch to site-local Drush: '/var/www/html/web/vendor/drush/drush/drush'.
Using the Drush script found at /var/www/html/vendor/drush/drush/drush using pcntl_exec
 [preflight] Redispatch to site-local Drush: '/var/www/html/web/vendor/drush/drush/drush'.
Using the Drush script found at /var/www/html/vendor/drush/drush/drush using pcntl_exec
```

The paths look a bit off because this is inside a DDEV container.

Running `which drush` give me `/var/www/html/vendor/bin/drush`

My composer.json has 

```
"drush/drush": "^10.0",
```

And the installed version is 10.3.1. 

Cheers

Tom

**Comment by weitzman** [comment]
`using pcntl_exec`. You are using drush 8 somehow. Try using `vendor/bin/drush` and not `drush`. Also try upgrading to latest ddev.
