### ISSUE TITLE
How can I update a field on a user profile with Drush

### ISSUE THREAD

**Issue by Nuhuruine** [drush-ops/drush#4832]
Hello,

Sorry but in Drush 9, how can I update a field on a user profile with Drush?

**What are you attempting to do**
I've some custom fields on user profile (field_lastname or field_position) I want update just after `drush user:create`.

**In what way is the existing documentation unclear or incomplete**
I don't find which command I need to use :/

**What should the documentation say instead?**
Could you give the example please ?

**Results of my research**
On the web, I found some responses for this but none from officials. By example, I found to use "Drush entity module" but this project is not covered by Drupal’s security advisory policy.

Thanks for your help

**Comment by weitzman** [comment]
There is no core drush command for this.
