### ISSUE TITLE
site-install should fail on error

### ISSUE THREAD

**Issue by danepowell** [drush-ops/drush#4836]
**Describe the bug**
`drush site-install` frequently prints errors to the CLI and watchdog due to bugs in contrib modules or configuration files. Drush still returns a `0` exit code when these errors occur, allowing them to go unnoticed or unaddressed by developers. Although they may not be critical errors, I think Drush should at least return a non-zero exit code when they occur, otherwise they start to pile up and have a negative effect on the entire DX/UX, and indeed reflect badly on the entire Drupal/Drush ecosystem.

**To Reproduce**
On a project with Lightning installed via Composer:
```
$ drush site-install lightning

 You are about to:
 * DROP all tables in your 'drupal9' database.

 Do you want to continue? (yes/no) [yes]:
 >

 [notice] Starting Drupal installation. This takes a while.
 [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile
 [notice] Performed install task: install_verify_requirements
 [notice] Performed install task: install_verify_database_ready
 [notice] Performed install task: install_base_system
 [notice] Performed install task: install_bootstrap_full
 [error]  An error occurred while notifying the creation of the id field storage definition: "!message" in Drupal\Core\Entity\Sql\SqlContentEntityStorage->wrapSchemaException() (line 1576 of /app/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
 [error]  An error occurred while notifying the creation of the created field storage definition: "!message" in Drupal\Core\Entity\Sql\SqlContentEntityStorage->wrapSchemaException() (line 1576 of /app/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
 [error]  An error occurred while notifying the creation of the uid field storage definition: "!message" in Drupal\Core\Entity\Sql\SqlContentEntityStorage->wrapSchemaException() (line 1576 of /app/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
 [error]  An error occurred while notifying the creation of the ip_address field storage definition: "!message" in Drupal\Core\Entity\Sql\SqlContentEntityStorage->wrapSchemaException() (line 1576 of /app/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
 [notice] Performed install task: install_profile_modules
 [notice] Performed install task: install_profile_themes
 [error]  File 'modules/contrib/lightning_core/images/default-avatar.png' could not be copied because a file by that name already exists in the destination directory ('').
 [notice] Performed install task: install_install_profile
 [notice] Performed install task: install_configure_form
 [notice] Performed install task: lightning_set_front_page
 [notice] Performed install task: lightning_grant_shortcut_access
 [notice] Performed install task: lightning_set_default_theme
 [notice] Performed install task: lightning_set_logo
 [notice] Performed install task: lightning_alter_frontpage_view
 [notice] Performed install task: install_finished
 [success] Installation complete.  User name: admin  User password: 6gU23Yf8Kv
$ echo $?
0
```

**Expected behavior**
site-install returns a non-zero exit code

**Actual behavior**
site-install returned a zero exit code

**Workaround**
Consumers could wrap drush site-install in a script to watch for watchdog errors and fail the process, but this doesn't solve the bigger issue, which is that these errors seem to be accumulating and we as an ecosystem should strive to prevent that.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.5.0
| Drupal version? | 9
| PHP version     | 7.4
| OS?             | Linux

**Comment by weitzman** [comment]
I think your beef is with ModuleInstaller, which is catching the exception and just writing to watchdog http://github.com/drush-ops/drush/blob/641298c5988301e5fe12acac4ec3220d19411889/sut/core/lib/Drupal/Core/Extension/ModuleInstaller.php#L287-L292. 

A web request that hits this code would give a 200 response, analogous to Drush's 0 exit code. I dont think it is Drush's place to guess the intentions of the code author, and exit with 1.

**Comment by lpeabody** [comment]
Could have something like a post-command hook for site:install (a little more Drush-native) which checks if there were any watchdog errors logged with the site that was just installed by querying the table directly. You could filter it on severity or severity + module combination, dump the pertinent log messages and then exit 1. This approach is at least doing it the annotated command way and respecting Drupal's current core implementation, as pointed out by Moshe above.

Could definitely see something like this being useful.

**Comment by danepowell** [comment]
> A web request that hits this code would give a 200 response, analogous to Drush's 0 exit code

If the desire is to be more like the web installer, then Drush should not print the errors to the CLI, as they are not shown in the web installer UI.

I'm fine either way: hide the errors and exit zero, or show the errors and exit non-zero. But the current mix of showing errors and exiting cleanly doesn't seem right.

**Comment by weitzman** [comment]
I see your point. But I don't think swallowing those log messages would be a net benefit.

**Comment by weitzman** [comment]
I dont think there is a solution here that satisfies all concerns.
