### ISSUE TITLE
What is alternate of archive-dump in Drupal 10.x

### ISSUE THREAD

**Issue by hiddenpearls** [drush-ops/drush#4838]
I am trying to archive-drump of my dev environment in Acquia for Drupal site but since I have Drush 10.5.0 I can't make the use of 

drush archive-dump --destination=../mysite.tar.gz

or 

drush ard--destination=../mysite.tar.gz

**Comment by weitzman** [comment]
There isn't one.

**Comment by greg-1-anderson** [comment]
Pantheon is considering sponsoring archive dump for Drush 10, but remains undecided. There have been surprisingly few requests since it was removed in Drush 9.
