### ISSUE TITLE
drush is removing arguments from the command line

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#484]
I've the following alias configuration in my aliases.drushrc.php:

This one doesn't work:

    $aliases['dev'] = array(
        'shell-aliases' => array('deploy-test' => '!echo sudo -u www-data whoami'),
    );

it generates:

    sudo -u whoami

This one works:

    $aliases['opsdev'] = array(
        'shell-aliases' => array('deploy-test' => '!echo sudo -uwww-data whoami'),
    );

generates:

    sudo -uwww-data whoami

So somehow drush removes the username www-data when there is space after -u argument.
I think it shouldn't do that.

---
The same with drush 7.x-dev

	$ cat test1.aliases.drushrc.php 
	<?php

	$aliases['dev'] = array(
	  'remote-host' => 'example.com',
	  'shell-aliases' => array('deploy-test' => '!echo sudo -u www-data whoami'),
	);
    $ drush -yv --alias-path=. @test1.dev deploy-test
    Calling proc_open(ssh -o PasswordAuthentication=no example.com 'echo sudo -u whoami');

---
Could be related:

 - [Shell aliases starting with a ! don't pass along options and arguments](https://www.drupal.org/node/1332818)

**Comment by kenorb** [comment]
I've some example (simplified for testing purposes) using exec:

    $ drush -vd exec diff -r /etc/hosts /etc/hosts
    Calling proc_open(diff -r /etc/hosts);
    diff: missing operand after `/etc/hosts'

This indicates that `drush` is removing any argument after `-r` parameter and without `-r` it works.

The workaround is to run:

    $ drush -vd exec diff -r FOO /etc/hosts /etc/hosts

So `FOO` is eaten by `drush`. Then it works.

The same happens with any argument such as `-i`, `-u`, etc.

**Comment by kenorb** [comment]
Another example:

    $ drush -vy @remote exec sh -c 'drush -r /var/www dd'
    Calling proc_open(ssh -o PasswordAuthentication=no drush@remote 'cd /var/www-test && sh -c');

So everything after `-c` has been removed.

When used double-quotes, the command is converted into: `'cd /var/www-qa && '\''sh -c '\''\'\'''\''drush -r /var/www dd'\''\'\'''\'''\'''` which gives the error `bash: sh -c 'drush -r /var/www dd': No such file or directory`.

**Comment by weitzman** [comment]
Just tested this and it is working fine. Assume we fixed a bug somewhere along the line.
