### ISSUE TITLE
TBD Extend Drush 10 support

### ISSUE THREAD

**Issue by mxr576** [drush-ops/drush#4868]
**Is your feature request related to a problem? Please describe.**
In #4844 Drush 10 was marked as not supported from November 2021. The date is aligned with Drupal 8.9, although that version also supports Drupal 9. Drush 11's minimum required PHP version is PHP 7.4 which is aligned with PHP 7.3's EOL in this December. Generally speaking, this is an understandable move, although:
* The announcement could have come sooner so downstream devs would have more time to adjust their Drush/PHP version requirements. (We already added `drush/drush: ^10.6` as a requirement to all our Drupal 9 packages and our distribution and starting to roll them out to every project, Drush 11 was nowhere back then.)
* Even though PHP 7.3 gets EOL-ed, there is an unfortunate tendency that some PPL are still using unsupported PHP versions or moving to the new version slowly. Besides that, Zend provides LTS support for older PHP versions for years after the official EOL and some enterprise customers prefer to run Zend version on their on-prem server: https://www.zend.com/services/php-long-term-support. This is one of the reasons why we planned to keep 7.3 language level (by setting config.platform.php to 7.3.0 in composer.json) but use PHP 7.4 as runtime.

**Describe the solution you'd like**
Even if supporting a PHP 7.3 compatible library as long as Zend supports PHP 7.3 should not be a goal here, consider extending Drush 10's support at least 6 months, giving a chance to downstream to catch up with everything they should.

Traspiling a PHP 7.4 compatible Drush 11 to PHP 7.3 compatible Drush 10 could be also a viable and maintainable option:
* https://blog.logrocket.com/coding-in-php-7-4-and-deploying-to-7-1-via-rector-and-github-actions/
* https://kinsta.com/blog/transpiling-php/

This could be a feature-proof move because soon you could switch to PHP 8.0 but keep supporting older PHP versions.

Another option is keeping PHP 7.3 support in Drush 11, which is possibly a worse idea.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by mxr576** [comment]
Thanks for the quick answers and sorry for the delayed follow-up on this. We were busy with the D 8.9 => D9 updates and settling the PHP 7.4 update requirement with our customers. 

I agree that Drush _probably_ does/will not have security issues and running an unsupported version _should not be_ a problem, although we would definitely get questions from security teams of enterprise customers who like to scan codebases we deliver for vulnerable and unsupported packages and report them as issues (and they rightfully doing this).

So it is better if we stick with Drush 11 and push for PHP 7.4 upgrade. (Personally, I would go for 8.0, but there are packages without PHP 8.0 compatible releases :S)

(Transpiling code would have been a cool enhancement thought, but I understand your current limitations and the size of the challenge.)

Thanks for developing and maintaining Drush for the Drupal community!

**Comment by gitressa** [comment]
Thanks @weitzman and @greg-1-anderson for maintaining Drush, wrangling with Drupal without Drush would simply be impossible. Maintaining and expanding Drush _is_ a big task, so I am very grateful for that.

About Drush 10/11, shouldn't we get Drush 11 via `composer require drush/drush` and not `10.6.2` if Drush 10 is EOL and Drush 11 is "Supported and recommended", as can be seen at https://www.drush.org/latest/install/?

I need to loosen requirements in composer.json to `"minimum-stability": "rc",` to be able to install Drush 11 with `composer require drush/drush:~11`.

Drush 11 works perfectly, by the way :-)

**Comment by weitzman** [comment]
We will push the Drush 11 final any day now.
