### ISSUE TITLE
Use `PDO*` instead of `*sql` commands (running in docker environment)

### ISSUE THREAD

**Issue by kaznovac** [drush-ops/drush#4884]
**Is your feature request related to a problem? Please describe.**
It's uncommon (and a bit tricky to install) `*sql-client` in the php docker container.
For bootstrap `drush` has 2 queries `SELECT 1` and `SHOW TABLES` (both can be issued thru PDO)

**Describe the solution you'd like**
Use `php` extensions where possible

**Describe alternatives you've considered**
- Basing docker image on the `mysql` image and installing `php-cli` dependencies on it to run `drush`
- installing `mysql-client` in the official `php` image

**Additional context**
Some tasks would still require `*sql` cli-s (and `drush` should clearly present this to the user), but for 'lightweight' tasks using `PDO` would be preferred

**Comment by weitzman** [comment]
This is already the case in modern drush. What version are you using.

**Comment by kaznovac** [comment]
I'm using drush 8.4.8 (the last one compatible with drupal 6)

**Comment by kaznovac** [comment]
@weitzman
i believe this issue should be reopened

here's the code from from the 11.x branch:

lisitng of the tables (in mysql flow):
https://github.com/drush-ops/drush/blob/208b960285fa0892edc80ebf6249f953a9823d42/src/Sql/SqlMysql.php#L129-L137

calls `alwaysQuery`
https://github.com/drush-ops/drush/blob/208b960285fa0892edc80ebf6249f953a9823d42/src/Sql/SqlBase.php#L309-L356

which creates external process here
https://github.com/drush-ops/drush/blob/208b960285fa0892edc80ebf6249f953a9823d42/src/Sql/SqlBase.php#L344-L348
