### ISSUE TITLE
An option to timestamp output messages

### ISSUE THREAD

**Issue by kaznovac** [drush-ops/drush#4885]
**Is your feature request related to a problem? Please describe.**
Parsing logs of the `drush cron` command

**Describe the solution you'd like**
an option to timestamp the log lines, preferably taking an optional timestamp format
- `--timestamp` - use 'default' time format
- `--timestamp='\[Y-m-d H:i:s\]\ '` - some custom pretty print

**Describe alternatives you've considered**
command line piping magic, like these https://serverfault.com/questions/310098/how-to-add-a-timestamp-to-bash-script-log

**Comment by weitzman** [comment]
are there other CLI tools that offer this?

**Comment by weitzman** [comment]
FYI you get duration timings with commands that run with `-vvv` option.

Lets move discussion to #4422 which would make this possible.
