### ISSUE TITLE
migrate:import loops over each migration, hits EOM before it finishes

### ISSUE THREAD

**Issue by damienmckenna** [drush-ops/drush#4890]
**Describe the bug**
With Drush 10.6.x running "migrate:import" on an upgrade from a D7 site results in the migrations being looped over.

From migrate:upgrade:

    --------------------------------------------------------------------------------- 
     Generated migrations                                                             
    --------------------------------------------------------------------------------- 
     upgrade_book_settings                                                            
     upgrade_commerce1_cart_settings                                                  
     upgrade_commerce1_shipping_flat_rate                                             
     upgrade_commerce1_tax_type                                                       

When migrate:import runs it shows the following:

    [notice] Processed 1 item (1 created, 0 updated, 0 failed, 0 ignored) - done with 'upgrade_book_settings'
    [notice] Processed 1 item (1 created, 0 updated, 0 failed, 0 ignored) - done with 'upgrade_book_settings'
    [notice] Processed 1 item (1 created, 0 updated, 0 failed, 0 ignored) - done with 'upgrade_commerce1_cart_settings'
    [notice] Processed 1 item (1 created, 0 updated, 0 failed, 0 ignored) - done with 'upgrade_book_settings'
    [notice] Processed 1 item (1 created, 0 updated, 0 failed, 0 ignored) - done with 'upgrade_commerce1_cart_settings'
    [notice] Processed 31 items (31 created, 0 updated, 0 failed, 0 ignored) - done with 'upgrade_commerce1_shipping_flat_rate'
    [notice] Processed 1 item (1 created, 0 updated, 0 failed, 0 ignored) - done with 'upgrade_book_settings'
    [notice] Processed 1 item (1 created, 0 updated, 0 failed, 0 ignored) - done with 'upgrade_commerce1_cart_settings'
    [notice] Processed 31 items (31 created, 0 updated, 0 failed, 0 ignored) - done with 'upgrade_commerce1_shipping_flat_rate'
    [notice] Processed 0 items (0 created, 0 updated, 0 failed, 0 ignored) - done with 'upgrade_commerce1_tax_type'

As you can see, it starts with the first item, upgrade_book_settings. When it goes to process the second item, upgrade_commerce1_cart_settings, it first outputs upgrade_book_settings a second time. When it goes to run the third item, upgrade_commerce1_shipping_flat_rate, it loops over the first two items again. This repeats until it finally hits an out-of-memory error on the 129th item of a migration with 202 tasks.

**To Reproduce**
ddev drush migrate:upgrade
ddev drush migrate:import --group='migrate_drupal_7'

**Expected behavior**
The migration to run once.

**Actual behavior**
The migration loops incrementally as it processes each new task.

**Workaround**
Revert to Drush 10.3.x.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | Latest 10.6.x stable release.
| Drupal version? | 9.2.7
| PHP version     | 7.4
| OS?             | Mac, though the Drush command is running inside ddev.

**Additional information**
TBD.

**Comment by claudiu-cristea** [comment]
What command do you run?

**Comment by damienmckenna** [comment]
`ddev drush migrate:import --group='migrate_drupal_7'`, like the "to reproduce" details indicate.

**Comment by weitzman** [comment]
Any chance this command adds more batches as it goes? If yes it could be hitting a bug we just fixed #4886

**Comment by damienmckenna** [comment]
That sounds like it might have been the problem.

Does this mean it won't be fixed in 10.x?

**Comment by damienmckenna** [comment]
I created a PR with the fix against 10.x - #4893.

**Comment by weitzman** [comment]
fixed in #4983
