### ISSUE TITLE
Run deploy with config:import --diff

### ISSUE THREAD

**Issue by gitressa** [drush-ops/drush#4894]
**Is your feature request related to a problem? Please describe.**
I normally run `drush config:import` with `--diff` to see the details of a configuration import. I just started using the `deploy` command which is great, but it doesn't allow showing the diff.

**Describe the solution you'd like**
Use `config:import --diff` in `deploy` command by default.

**Now**
```
drush updatedb --no-cache-clear
drush cache:rebuild
drush config:import
drush cache:rebuild
drush deploy:hook
```

**With `--diff` parameter**
```
drush updatedb --no-cache-clear
drush cache:rebuild
drush config:import --diff
drush cache:rebuild
drush deploy:hook
```

**Describe alternatives you've considered**
Alternatively, add it as a parameter:

`drush deploy -v --diff -y`

**Comment by weitzman** [comment]
I think the changes that drupal reports today are compact and sufficient. Please run a diff before deploy if you want this info. The deploy command isnt meant to be run interactively, where you review the diff and cancel if you dislike.

**Comment by gitressa** [comment]
> The deploy command isnt meant to be run interactively, where you review the diff and cancel if you dislike.

I agree that normally, just listing config items about to be updated is enough. But sometimes being able to search in the actual changes and seeing the `diff` right there in the terminal is nice, for example when you use `deploy` to create a local instance.

Another place where it would be useful is for post-mortems for CI builds, where something "odd" is happening. Usually in CI, the build process is logged, so it is possible to search and check for abnormalities. Also, it could be a log of configuration changes over time.

My original reason for suggesting adding `--diff` is that I have previously tried and failed at viewing but also stopping an import probably because I was using `-n`. But I just did some digging:

**Works, the import is rejected**
`drush config:import --diff --no`

**Doesn't work, the import goes through**
`drush config:import --diff -n`

... and in the documentation it does outline that `-n` is `--no-interaction`, so to stop an import, `--no` is required:

`drush topic` > select 1:

```
+----------------------+----------------------------------------------------------------------------------------------+
| Name                 | Description                                                                                  |
+----------------------+----------------------------------------------------------------------------------------------+
| --alias-path         | Specifies the list of paths where drush will search for alias files.                         |
| --ansi               | Force ANSI output                                                                            |
| --config             | Specify an additional config file to load. See example.drush.yml                             |
| --include            | A list of additional directory paths to search for Drush commands. Commandfiles should be    |
|                      | placed in a subfolder called 'Commands'.                                                     |
| --local              | Don't look in global locations for commandfiles, config, and site aliases                    |
| --no                 | Cancels at any confirmation prompt.                                                          |
| --no-ansi            | Disable ANSI output                                                                          |
[...]
|                      | debug                                                                                        |
| -y, --yes            | Equivalent to --no-interaction.                                                              |
+----------------------+----------------------------------------------------------------------------------------------+
```

So to conclude, users who want a detailed `diff` of the configuration about to be imported (but not import it) should run this before `drush deploy`:

`drush config:import --diff --no`

**Comment by weitzman** [comment]
Yeah the meaning of -n had to change in drush 9 in order to start using symfony console. 

Glad you found an approach.

**Comment by weitzman** [comment]
Also if you always want --diff you can set that in drush configuration.

**Comment by gitressa** [comment]
Thanks for clarifying the reason behind the behavior of `-n` :-)

Using Drush configuration sounds really interesting. I tried with this in `vendor/drush/drush/drush.yml`, and the `uri` is getting picked up, but not the `diff`-bit ... Do I need to use another syntax?
```
# Global options.
options:
  # Specify the base_url that should be used when generating links.
  uri: 'https://DRUSH-test.com/'

# Command-specific options.
command:
  config:
    import:
      options:
        diff: true
```

**Comment by gitressa** [comment]
I also see this:

> An alternative way to populate Drush configuration is to define environment variables that correspond to config keys. For example, to populate the options.uri config item, create an environment variable DRUSH_OPTIONS_URI=http://example.com. As you can see, variable names should be uppercased, prefixed with DRUSH_, and periods replaced with dashes.

https://www.drush.org/latest/using-drush-configuration/#environment-variables

In theory, could something like this work?

`DRUSH_COMMAND_CONFIG_IMPORT_OPTIONS_DIFF: "true"`

**Comment by gitressa** [comment]
I have created #4901.
