### ISSUE TITLE
Provide an API for other storage handlers to truncate contents before site:install

### ISSUE THREAD

**Issue by Sweetchuck** [drush-ops/drush#4900]
## The problem

Currently, only the main database (`--db-url=` or `$databases['default']`) gets deleted in the early phase of the
`drush site:install`.
There can be other user contents as well. And there are. For example public files, private files, fulltext indexes
(Solr, Elasticsearch), cache backends (Redis, Memcache) and so on.

In development process when there are contents in these storages, and you ran `drush site:install --yes` then these are 
just leftover contents. When you start using the freshly installed sites, it very likely create the same cache IDs, which still 
exists in Redis, but with totally irrelevant content, but it will be used anyway, which leads to very weird problems.
Same with SearchAPI+Solr combo. Previously there was a lot of node in the index, on the new site there is no node at all,
but when you visit the search page – which has facets – facets are displayed, but they should not.

The "DROP all tables in your '@db' database." confirmation question happens in the `\Drush\Commands\core\SiteInstallCommands::pre`,
and the actual `$sql->dropOrCreate()` also happens there.

Not easy to subscribe to an event which happens after the `SiteInstallCommands::pre` and before the `SiteInstallCommands::install`.
I think nothing ensures that my `@hook pre-command site-install` subscriber method will be called after the `SiteInstallCommands::pre`.

## The proposed solution

I think the `\Consolidation\AnnotatedCommand\Events\CustomEventAwareInterface` should be used to trigger a custom event 
and let the subscribers (storage handlers) know that this is the time to delete you contents.

These subscribers can use the [Option Event Hook](https://github.com/consolidation/annotated-command#option-event-hook)
to add extra options to the site:install command if they need extra configuration. The `drush.yml` is still there if 
they need extra configuration or if the `--exsisting-config` is present they might be use that one as well.

**Comment by weitzman** [comment]
Thanks for the detailed writeup.

- One challenge is that we dont have a drupal site yet so no modules can hook into events here. Its gonna be global packages or commandfiles in global directories. If you are OK with this limitation, ...
- During PRE, you could implement the Redis clearing prompt, and then clear if YES
- Or you can implement the clearing during `@command` hook and just know that user must have agreed to the DB clear already. Maybe you worried that install might have happenned already and thats bad for some reason?
- If you still want the custom event after considering above, please submit a PR and it can go in.

**Comment by Sweetchuck** [comment]
> One challenge is that we dont have a drupal site yet so no modules can hook into events here

I was thinking the same. I am fine with that limitation. I frequently use site-wide commands.
Only inconvenience is that I always have to use the `--config=drush` option, otherwise site-wide commands won't be recognised, even though they are under the ./drush/Commands/ directory.  But this can be solved with a shell `alias`.

I think the problem is that, these kind of drush commands should be provided by the module which implements the data storage. May be some extra line in the project's main `drush.yml` under the `drush.paths.include` will solve the problem.

----

I have already achieved this goal on a few project with a custom site-wide commands with the SearchAPI+Solr combo.

After a several try-error I noticed that every \@command related hook will be called with all the command aliases.
I don't remember the exact order – and the order is crucial in this case – but all the following is available.

* @hook pre-command site:install
* @hook pre-command site-install
* @hook pre-command si

It was a little bit surprising, because I wanted to use the official `site:install` version, but it was too early (before the confirmation question). I think this kind of behaviour comes from the consolidation/annotatedcommand.


What is the preferred way to ask a confirmation question?
Collect all the information and show **one** message to the user about what is going to happen:
> if you continue
> - DROP all tables in your MySQL
> - Delete all the files in sites/FOO/files
> - Delete private files
> - Delete all entries in Redis cache
> - Delete all documents in Solr FOO index

and delete them without any further user interaction.

Or every storage handler should manage its own question and confirmation one-by-one?

**Comment by weitzman** [comment]
> May be some extra line in the project's main drush.yml under the drush.paths.include will solve the problem.

That would work. I'm not going to encourage that, but I won't strongly object either. I philosophically dislike module code running when a module is not (yet) enabled.n

> What is the preferred way to ask a confirmation question?

You probably saw sql:sanitize [It has an event for collecting the questions and then an event for taking the action](https://github.com/drush-ops/drush/blob/11.x/src/Drupal/Commands/sql/SanitizeCommands.php#L20-L21). That’s a pattern we could reuse here, if the module limitation is acceptable.

**Comment by weitzman** [comment]
The way I've handled this on projects is to have a dmall install script that clears the storages before calling `drush site:install`. I think that approach works fine, and so am not jumping at the change to complicate site:install as discussed.

**Comment by Sweetchuck** [comment]
OK I understand.
However, this way every project member (or the whole Drupal community) have to learn a new workflow or tooling.
And the current situation is not consistent. Only the main DB is handled by Drush, why not all or nothing?

**Comment by weitzman** [comment]
Yes. Any site of moderate complexity needs a scripting system whether it is ahoy, make, composer scripts, plain bash scripts, phing, etc. drush's scope does not obviate that need ... It is easy for a developer to learn "on this project we run install.sh which wraps drush site:install among other setup tasks". 

We choose to handle DB emptying because it is needed by 100% of sites that have re-install as part of their workflow.
