### ISSUE TITLE
Granular config exports

### ISSUE THREAD

**Issue by ErroneousBosch** [drush-ops/drush#4902]
**Is your feature request related to a problem? Please describe.**
A very handy feature my team uses in Drupal Console is the config:export:XXX commands, which allow for more granular configuration export into modules of items like content types, entities, views, etc. while also stripping out UUID and site hash. These commands export either single configs, or a set of configs of an item and its related fields, referenced items, etc. 

This is extremely useful for developing and deploying across a set of sites sharing a common codebase, but where complete config synchronization isn't feasible or desirable, and many features are granularized into custom modules. 

**Describe the solution you'd like**
Having this capability built into Drush would improve development usability.  

**Describe alternatives you've considered**
My understanding is that this kind of thing is accomplishable using the "Configuration Split" module, but would require running two extra modules in addition to whatever extra configuration they require. 

**Additional context**
Drupal Console documentation: https://drupalconsole.com/docs/en/commands/ - the "config:export" commands are the prototypes here. https://github.com/hechoendrupal/drupal-console/tree/master/src/Command/Config is the repository folder where the codebase for these features is housed.

**Comment by weitzman** [comment]
My understanding is that Features module still serves this use case. 

And yes, perhaps config split or config distro can serve your needs. In any case this feature is useful but it's audience is too small for core drush IMO.
