### ISSUE TITLE
Error installing on Mac

### ISSUE THREAD

**Issue by zkent** [drush-ops/drush#4904]
I am attempting to follow the installation procedures in the Readme but I am getting the following error: 

 [ErrorException]                                                                                                                         
  Use of undefined constant CONFIG_SYNC_DIRECTORY - assumed 'CONFIG_SYNC_DIRECTORY' (this will throw an Error in a future version of PHP)

I am on Mac OS (Big Sur)

**Comment by tobiasbaehr** [comment]
Your settings.php is outdated. Something like `$config_directories[CONFIG_SYNC_DIRECTORY]` should be changed to `$settings['config_sync_directory']`
