### ISSUE TITLE
config:import removed non-listed changes.

### ISSUE THREAD

**Issue by elistone** [drush-ops/drush#4913]
**Describe the bug**
Recently in the past few weeks I have had 3 different websites list one thing when it comes to import status and do something completely different when you agree to continue.

I assume something strange might have gone on while it tried to import, but when I tried recreating this kinda issue locally I found that it was not possible.
I would make a small config change, run `drush cim` and before saying yes to continue delete a random config file expecting it to show up in the notices, but this was not the case even when I cleared the cache before continuing as well.

![delete-config-inbetween](https://user-images.githubusercontent.com/2546188/144598409-b53e45d9-1e28-4eff-8283-b6f47d317731.png)

I was hoping someone might have an idea as to what could possible cause this issue and where to start looking to resolve it? or even better a way to prevent / abort if this kinda thing happens again.

**To Reproduce**
_Not yet achieved..._

**Expected behavior**
Only the config listed is removed.

**Actual behavior**
Import runs and removes non-listed changes.

This is a screenshot from an import where something went wrong:
<img width="771" alt="config-import-error" src="https://user-images.githubusercontent.com/2546188/144581768-c220ee06-a4d4-4c97-a5bb-e7a48171f6a7.png">

**Workaround**
Nope.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.6
| Drupal version? | 9.2.x (various versions)
| PHP version     | 7.4
| OS?             | Linux

**Comment by weitzman** [comment]
Please post again if it becomes reproducible. I will reopen. Also please not if you are running conflig split module, or other config transform code.
