### ISSUE TITLE
Incompatible declaration of Psysh\Shell::hasCommand

### ISSUE THREAD

**Issue by felmab** [drush-ops/drush#4916]
I had to upgrade Drush from version 9 to version 10 (10.6.1) in order to upgrade a site from Drupal 8 to Drupal 9. I noticed this error when trying to launch the `core:cli` command:
> PHP Fatal error:  Declaration of Drush\Psysh\Shell::hasCommand($input) must be compatible with Psy\Shell::hasCommand(string $input): bool in /var/www/html/vendor/drush/drush/src/Psysh/Shell.php on line 37

On another site using the same version of Drush, there is no such issue. The difference appears to be that the former uses psy/psysh:0.11.0 while the latter uses psy/psysh:0.10.9 (with different method signatures indeed). Provided I did nothing wrong while updating, there might be a constraint missing somewhere in order to avoid newer versions of psy/psysh.

**Comment by weitzman** [comment]
Looks like it. We can just require the newer psysh in Drush 11. PRs welcome.

**Comment by felmab** [comment]
Tests fail in #4918 but errors look unrelated.

**Comment by MatthieuScarset** [comment]
Same issue since today for me. 

This is a blocker because it prevents developer from using `drush php` comand.

**Comment by felmab** [comment]
@MatthieuScarset while waiting for a new release you can manually adapt the signature of `Shell::hasCommand` like [this](https://github.com/drush-ops/drush/pull/4918/files) (or maybe force a dev version).

**Comment by alexpott** [comment]
It might be handy to add a =< 0.10 constraint to Drush 10 so people can run composer update and composer can do the correct thing.

**Comment by weitzman** [comment]
Sure I'd merge that PR if anyone gets inspired.

**Comment by felmab** [comment]
> It might be handy to add a =< 0.10 constraint to Drush 10 so people can run composer update and composer can do the correct thing.

I think that's essentially what was done in #4917, only that it hasn't been released yet.

**Comment by weitzman** [comment]
Thanks for clarifying. Released at https://github.com/drush-ops/drush/releases/tag/10.6.2
