### ISSUE TITLE
Drush en module | not working | Drupal 7 on WAMP with PostgreSQL

### ISSUE THREAD

**Issue by ceeweb** [drush-ops/drush#492]
My drupal installation is installed at: C:\SiteData\WebDev\gitproject (this is my DrupalRoot)
I successfully ran "drush status" in "[DrupalRoot]\sites\site1.example.com..

This is a follow-up to the issue posted at: https://drupal.org/node/1428638

<b>But when I try to enable a module using "drush en ccl" and I get ...</b>

<b>$ drush en ccl</b>

```
Command pm-enable needs a higher bootstrap level to run - you will [error]
need to invoke drush from a more functional Drupal environment to run
this command

The drush command 'en ccl' could not be executed. [error]

Drush was not able to start (bootstrap) the Drupal database. [error] 

Hint: This may occur when Drush is trying to:

* bootstrap a site that has not been installed or does not have a
configured database. In this case you can select another site with a
working database setup by specifying the URI to use with the --uri
parameter on the command line. See `drush topic docs-aliases` for
details.
* connect the database through a socket. The socket file may be
wrong or the php-cli may have no access to it in a jailed shell. See
http://drupal.org/node/1428638 for details.

Drush was attempting to connect to:
Drupal version : 7.26
Site URI : http://site1.example.com
Database driver : pgsql
Database username : user
Database name : site1dev
Default theme : garland
Administration theme : garland
PHP executable : php
PHP configuration : "C:\Program Files
(x86)\Drush\Php\php.ini"
PHP OS : WINNT
Drush version : 6.0
Drush configuration :
Drush alias files :
Drupal root : c:/SiteData/WebDev/gitproject
Site path : sites/site1.example.com
File directory path : sites/site1.example.com/files
```

<b>My settings.php file looks like this:  </b>

<code>
$databases = array (
  'default' =>
  array (
    'default' =>
    array (
      'database' => 'site1dev',
      'username' => 'user',
      'password' => 'secretpw',
      'host' => '127.0.0.1',
      'port' => '',
      'driver' => 'pgsql',
      'prefix' => 'dev_',
    ),
  ),
);
if (php_sapi_name() == 'cli') {
  $db_url = 'pgsql://user:secretpw@127.0.0.1/site1dev';
 }
 else {
   $db_url = 'pgsql://user:secretpw@localhost/site1dev';
 }

</code>

I have used both the "Drush Command Prompt" and "MINGW32" git command line tool and both work for "drush status" or "drush dl " but not for "drush en "

One last comment. looking at the settings.php file permissions in MINGW32 they show the unix permissions of -rw-r--r--.. Tried changing this in using chmod but doesn't work on a windows file (not even sure that makes a difference).

Any help is much appreciated!

**Comment by mikeshiyan** [comment]
I guess the problem is that Drush does not work with PostgreSQL on Windows.
`drush --debug cc all`:
```
...
Executing: PGPASSFILE=C:\Users\Mike\AppData\Local\Temp\dru18B9.tmp psql -q --dbname=dhsem_private --host=127.0.0.1 --port=5432 --username=postgres  --no-align --field-separator='   ' --pset tuples_only=on --file "C:\\Users\\Mike\\AppData\\Local\\Temp\\dru18B8.tmp"
  "PGPASSFILE" is not an internal or external command, operable program or batch file.
```
*Output is roughly translated.*

**Comment by mikeshiyan** [comment]
There should be `$environment = "set PGPASSFILE={$pw_file} ";` (note the "set" word) for Windows in Sqlpgsql->command().

**Comment by MrKuja** [comment]
Still have the problem on the master branch.
I previously submited a pull about it (#880) but no news from drush team.

Add "SET " to the command fix that, indeed.

**Comment by zhilevan** [comment]
I have the same problem on MAC

**Comment by Renrhaf** [comment]
I'm also having the same error with a "drush en XXX" on :
- Drupal 7.53 with PostgreSQL 9.6.2
- Drupal 8.3.3 with PostgreSQL 9.5.6 (using a different schema than "public" - I see a "SELECT tablename FROM pg_tables WHERE schemaname='public';" being executed with debug option, which seems wrong - see https://www.drupal.org/node/1060476#comment-12119926)

**Comment by soelinn** [comment]
@Renrhaf there are two modifications you need to make in the Drush source code.

https://www.drupal.org/node/881676#comment-10754120

`//line 9
//public $query_extra = "--no-align --field-separator='\t' --pset tuples_only=on";
public $query_extra = "--no-align --pset tuples_only=on";`

and

`//line 49
//$environment = "PGPASSFILE={$pw_file} ";
$environment = "SET PGPASSFILE={$pw_file} & ";`

Drush source code wasn't setting the PGPASSFILE environment variable correctly on the Windows platform AND it was separating the SET command from the psql execution with the "&".

**Comment by samhaldia** [comment]
> For those who were trying to fix the issue and ended up here, **THIS IS THE SOLUTION**.
> 
> @Renrhaf there are two modifications you need to make in the Drush source code for **Sqlpgsql.php** file.
> 
> https://www.drupal.org/node/881676#comment-10754120
> 
> ```
> //line 9
> //public $query_extra = "--no-align --field-separator='\t' --pset tuples_only=on";
> public $query_extra = "--no-align --pset tuples_only=on";
> ```
> 
> and
> 
> ```
> //line 45
> //$environment = "PGPASSFILE={$pw_file} ";
> $environment = "SET PGPASSFILE={$pw_file} & ";
> ```
> 
> Drush source code wasn't setting the PGPASSFILE environment variable correctly on the Windows platform AND it was missing the "&" character to separate the SET command from the psql execution.

After following the suggested edits above, I am able to run Drush status, though but it still complaints 'PGPASSFILE' is not recognized as an internal or external command, I have also added PGPASSFILE in system path PGPASSFILE : C:\Users\suser\AppData\Local\Temp\

C:\xampp\htdocs\my_project>drush status
'PGPASSFILE' is not recognized as an internal or external command,
operable program or batch file.
Password for user postgres:
'PGPASSFILE' is not recognized as an internal or external command,
operable program or batch file.
Password for user postgres:

On running Drush status i see :
 Drupal version                  :  7.56
 Site URI                        :  http://default
 Database driver                 :  pgsql
 Database hostname               :  127.0.0.1
 Database port                   :  5432
 Database username               :  root
 Database name                   :  portal
 Drupal bootstrap                :  Successful
 Drupal user                     :
 Default theme                   :  my_custom
 Administration theme            :  adminimal
 PHP executable                  :  php.exe
 PHP configuration               :  C:\xampp\php\php.ini
 PHP OS                          :  WINNT
 Drush script                    :  C:\Users\suser\AppData\Roaming\Composer\vendor\drush\drush\drush.php
 Drush version                   :  7.4.0
 Drush temp directory            :  C:\Users\SUSER~1\AppData\Local\Temp
 Drush configuration             :
 Drush alias files               :
 Install profile                 :  suser
 Drupal root                     :  C:\xampp\htdocs\my_project
 Site path                       :  sites/default
 File directory path             :  sites/default/files
 Private file directory path     :  sites/default/private
 Temporary file directory path   :  sites/default/tmp

**Comment by weitzman** [comment]
This is long fixed. Using the latest release IS THE SOLUTION.
