### ISSUE TITLE
Fatal error on drush php:cli

### ISSUE THREAD

**Issue by quietone1** [drush-ops/drush#4923]
**Describe the bug**
Fatal error on `drush php:cli`

**To Reproduce**
What did you do?
```
dev0-web:/var/www/html$ drush php:cli
```

**Expected behavior**
What did you expect would happen?
To have an interactive shell on a Drupal site.

**Actual behavior**
What happened instead?
```
PHP Fatal error:  Declaration of Drush\Psysh\Shell::hasCommand($input) must be compatible with Psy\Shell::hasCommand(string $input): bool in /var/www/html/vendor/drush/drush/src/Psysh/Shell.php on line 37

Fatal error: Declaration of Drush\Psysh\Shell::hasCommand($input) must be compatible with Psy\Shell::hasCommand(string $input): bool in /var/www/html/vendor/drush/drush/src/Psysh/Shell.php on line 37
 [warning] Drush command terminated abnormally.
dev0-web:/var/www/html$ 
```
**Workaround**
Is there another way to do the desired action?
No

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.6.1, 10.4.0
| Drupal version? | 9.3.x, 9.4.x
| PHP version     | 8.0 or 7.4
| OS           | Linux

Same failure with Drush 9.7.3, Drupal 8.9.x, PHP 7.0. 

It does work with Drush 8.4.8 ,Drupal 7.80-dev, PHP 7.3

**Additional information**
These are all ddev environments. I first noticed this on 2021-12-07 but as I don't use the command often I don't know what I may have done that is related to the failure.

I tried a completely fresh ddev environment (deleted the whole lot and started from scratch) and got the same failure.

**Comment by weitzman** [comment]
Improved constraints in 11.x and 10.x See #4916. New releases will come out soon.

**Comment by camerongreen** [comment]
Workaround is to patch line 37 of vendor/drush/drush/src/Psysh/Shell.php look like this:

    protected function hasCommand(string $input): bool

**Comment by gitressa** [comment]
This seems to work now:

```
$ drush core:cli
Psy Shell v0.11.2 (PHP 8.0.18 — cli) by Justin Hileman
Drush Site-Install (Drupal 9.3.12)
>>> 
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version  | 11.0.9
| Drupal version | 9.3.12
| PHP version     | 8.0.18
| OS             | Ubuntu 20.04 
| dev env             |  Lando

**Comment by alberto56** [comment]
In case anyone needs to reference a patch to ./vendor/drush/drush/src/Psysh/Shell.php (for example if you're on a project which is not yet on PHP 8.2 so you can't install the latest version of Drush), here it is:

[drush-4923-psysh.patch](https://github.com/user-attachments/files/27128271/drush-4923-psysh.patch)
