### ISSUE TITLE
wget nor curl executables found

### ISSUE THREAD

**Issue by kartagis** [drush-ops/drush#493]
Hi,

When I use drush to download modules, I get this weird error:

drush dl registry_rebuild
exec(): Unable to fork [wget --version 2>&1] exec.inc:150                                                                                           [warning]
exec(): Unable to fork [curl --version 2>&1] exec.inc:150                                                                                           [warning]
exec(): Unable to fork [which curl 2>&1] exec.inc:150                                                                                               [warning]
wget nor curl executables found.                                                                                                                    [error]

which wget gives me /usr/bin/wget and which curl gives me /usr/bin/curl. /usr/bin/ is in my PATH. This seldom works if I do drush cc drush. How do I solve this permanently?

**Comment by powBetoSoft** [comment]
Restart your server. It worked for me.
And as a general rule, restart your server once a week :)
