### ISSUE TITLE
drush en some_module_name --quiet -y is broken

### ISSUE THREAD

**Issue by QuoData** [drush-ops/drush#4933]
**Describe the bug**

`drush en some_module_name --quiet -y` is broken because of the --quiet option

**To Reproduce**
Run this for a not installed module:

drush en some_module_name --quiet -y

**Expected behavior**
enable the module without error

**Actual behavior**
the module gets enabled but you get an error

```
In ProcessBase.php line 155:

  Output is empty.

```

**Workaround**
don't use quiet
### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.6.1
| Drupal version? | 9.3
| PHP version     | 7.4
| OS?             | /Linux/

**Additional information**

**Comment by QuoData** [comment]
seems to be because of drupal 9.3 not a new drush version

**Comment by weitzman** [comment]
Drush 9 no longer supported. See https://www.drush.org/latest/install/#drupal-compatibility

**Comment by hannsen** [comment]
DRUPAL 9, DRUSH 10

**Comment by hannsen** [comment]
@weitzman What do you mean? The used drush version is 10.

Do you mean drush 11 needs to be used for drupal 9?

**Comment by weitzman** [comment]
Sorry I misread. Drush 11 will be the sole supported version for Drupal 9 but not for a couple more weeks.

I cant reproduce the bug reported here, unfortunately.

**Comment by weitzman** [comment]
Thats helpful. It looks like someone should dig into drupal core's locale.bulk.inc

**Comment by weitzman** [comment]
Actually the bug seems to be in one of drush's dependencies but I cant find it. Drush's batch runner runs fine but the calling process sees empty output instead of a json doc.
