### ISSUE TITLE
There are no online docs for Drush 10

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#4981]
https://docs.drush.org/en/10.x is a 404, and https://docs.drush.org/en/9.x/ does not show 10.x in the versions popup.

**Comment by weitzman** [comment]
Yes, we only publish docs for the tip of the development branch. We have started noting in those docs when information has changed and only applies to new versions. See 10.3 marker at https://www.drush.org/latest/deploycommand/, for example.

Drush 11 will be released in a few days.

**Comment by joachim-n** [comment]
So https://www.drush.org/latest/ is docs. What is https://docs.drush.org? That's what comes up when I google 'drush docs'.

**Comment by weitzman** [comment]
That is the old docs site. Drush 8 is not recommended but it is still in use so it stays up for now.
