### ISSUE TITLE
Command language:add not in drush list

### ISSUE THREAD

**Issue by Nuhuruine** [drush-ops/drush#4986]
**Describe the bug**
In the result of the command `drush list`, the command `language:add` doesn't appear.

**To Reproduce**
drush list

**Expected behavior**
See all the commands available

**Actual behavior**
Some commands doesn't appear, by example language:add

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.6.2
| Drupal version? | 9.3.2
| PHP version     | 8.0.8
| Composer version     | 2.0.14
| OS?             | Linux

**Comment by weitzman** [comment]
As its code says, we use that command for testing, and dont support it otherwise. language commands should keep living in Contrib for now. I'm interested in bringing mature ones into Drush core, as long as we have a maintainer /cc @eiriksm

**Comment by eiriksm** [comment]
Hi there. I don't understand from this context why you cc'ed me 🤓 I don't recall contributing something along the lines of the language commands mentioned?

**Comment by Nuhuruine** [comment]
Hi, 
Thanks for your reply and sorry.
