### ISSUE TITLE
return type of logger() is inaccurate

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#4998]
**Describe the bug**

```
    /**
     * Returns a logger object.
     */
    protected function logger(): ?LoggerInterface
    {
        return $this->logger;
    }
```

$logger appears to be more than a \Psr\Log\LoggerInterface, since commands call things like success() on it, which is not in Psr\Log\LoggerInterface.

Dumping it shows it's a Drush\Log\Logger.

**To Reproduce**
What did you do?

**Expected behavior**
What did you expect would happen?

**Actual behavior**
What happened instead?

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.x/10.x/8.x (please be specific, and try latest release)
| Drupal version? | 9.x/8.x/7.x
| PHP version     | 8.x/7.x
| OS?             | Mac/Linux/Windows

**Additional information**

**Comment by weitzman** [comment]
We have an intention to make it easier to use alternative loggers like Monolog. Thus, a less specific return type is appropriate.

**Comment by joachim-n** [comment]
It's not being treated as a LoggerInterface though -- there are calls to $logger->success(), for instance, which is not in LoggerInterface.

**Comment by weitzman** [comment]
OK, lets keep working on this at https://github.com/consolidation/log/issues/20
