### ISSUE TITLE
'drush si' should catch InstallerException

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#4999]
**Describe the bug**

If installation fails because Drupal throws a InstallerException, this shows as Drush crashing.

It would be better UX to catch this and show an error.

**To Reproduce**
What did you do?

**Expected behavior**
What did you expect would happen?

**Actual behavior**
What happened instead?

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.x/10.x/8.x (please be specific, and try latest release)
| Drupal version? | 9.x/8.x/7.x
| PHP version     | 8.x/7.x
| OS?             | Mac/Linux/Windows

**Additional information**

**Comment by weitzman** [comment]
Lets continue in the PR
