### ISSUE TITLE
Infinite loop when trying to enable not available extensions in Drupal 8

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#5]
Original issue at https://drupal.org/node/1989202

**Comment by FreekyMage** [comment]
Just to confirm that this is still broken for Drupal 8, it works for Drupal 7 though.

**Comment by davereid** [comment]
Still broken on Drupal 8. Anyone have links to where this was fixed for Drupal 7?

**Comment by jonhattan** [comment]
It was never broken for Drupal 7.

Problem is that `system_rebuild_module_data()` in D8 doesn't get us with fresh data after downloading the missing deps, even if we enforce a `system_list_reset()`.

**Comment by jonhattan** [comment]
Problem is exactly here: http://cgit.drupalcode.org/drupal/tree/core/lib/Drupal/Core/Extension/ExtensionDiscovery.php#n188

It won't scan again the filesystem after we downloaded the modules, and there's no method to reset this cache.

**Comment by kostajh** [comment]
> It was never broken for Drupal 7.

@jonhattan did you see my report above? try `drush en logging_alerts -y` in a D7 site.

**Comment by jonhattan** [comment]
@kostajh, you're right. It is broken this way for any Drupal version, because of the assimetry between project names and extension names (a funny example is `google_analytics`). This is a won't fix until D.O. changes or someone invents something clever. 

The case for Drupal 8 is different. It is broken where Drupal 7,6,5 works, as explained above.

**Comment by jonhattan** [comment]
Related issue in drupal.org: https://www.drupal.org/node/2503927

**Comment by LionsAd** [comment]
I think it would be better to open an actual major bug report instead of hoping on the conversion, which might not solve the bug after all.

**Comment by webflo** [comment]
I "fixed" the bug for DrupalConsole in https://github.com/hechoendrupal/DrupalConsole/commit/2311c47cb456c95eb69ce2c7320e356aaabd3a44 (last two files)

**Comment by jonhattan** [comment]
I arrived to the same solution yesterday. It is pending a proper implementation within drush. http://www.pasteall.org/59559/diff

**Comment by kenorb** [comment]
I'm using drush 8.0-dev with D7.

Here is my scenario:

	$ drush -l http://foo -y en features_extra
	features_extra was not found.                                                                                    
	The following projects provide some or all of the extensions not found:                                          
	features_extra
	Would you like to download them? (y/n): y
	Unknown path for spartan module.                                                                                 
	Install location sites/all/modules/contrib/features_extra already exists. Do you want to overwrite it? (y/n): y
	Project features_extra (7.x-1.0) downloaded to sites/all/modules/contrib/features_extra.                         
	Project features_extra contains 4 modules: fe_block, fe_date, fe_nodequeue, fe_profile.
	features_extra was not found.                                                                                    
	The following projects provide some or all of the extensions not found:                                          
	features_extra
	Would you like to download them? (y/n): y
	Unknown path for spartan module.                                                                                 
	Install location sites/all/modules/contrib/features_extra already exists. Do you want to overwrite it? (y/n): y
	Project features_extra (7.x-1.0) downloaded to sites/all/modules/contrib/features_extra.                         
	Project features_extra contains 4 modules: fe_block, fe_date, fe_nodequeue, fe_profile.
	features_extra was not found.                                                                                    
	The following projects provide some or all of the extensions not found:                                           
	features_extra
	Would you like to download them? (y/n): y
	Unknown path for spartan module.                                                                                  
	Install location sites/all/modules/contrib/features_extra already exists. Do you want to overwrite it? (y/n): ^C

Few issues which I've found:
- `features_extra` can't be found in contrib, despite it was downloaded by drush it-self
- `features_extra` is depending on `features_extra` (it-self), probably because the sub-modules have different machines names
- `spartan` can't be found, but it's actually in: `./profiles/openpublic/themes/spartan`

**Comment by raj45** [comment]
If I try to install a D8 module using drush 7 with <code>drush en admin_toolbar -y</code>, it ends in a loop. I am using vlad, which might be a factor. If I just do <code>drush dl admin_toolbar -y</code> and then <code>drush en admin_toolbar -y</code> it works fine.

<pre>✝ d8 ✝ /var/www/site/docroot/d8.dev $ drush en admin_toolbar -y
admin_toolbar was not found.                                                                                                           [warning]
The following projects provide some or all of the extensions not found:                                                                [ok]
admin_toolbar
Would you like to download them? (y/n): y
Project admin_toolbar (8.x-1.9) downloaded to /var/www/site/docroot/d8.dev//modules/admin_toolbar.                              [success]
Project admin_toolbar contains 2 modules: admin_toolbar_tools, admin_toolbar.
admin_toolbar was not found.                                                                                                           [warning]
The following projects provide some or all of the extensions not found:                                                                [ok]
admin_toolbar
Would you like to download them? (y/n): y
Install location /var/www/site/docroot/d8.dev//modules/admin_toolbar already exists. Do you want to overwrite it? (y/n): y
Project admin_toolbar (8.x-1.9) downloaded to /var/www/site/docroot/d8.dev//modules/admin_toolbar.                              [success]
Project admin_toolbar contains 2 modules: admin_toolbar_tools, admin_toolbar.
admin_toolbar was not found.                                                                                                           [warning]
The following projects provide some or all of the extensions not found:                                                                [ok]
admin_toolbar
Would you like to download them? (y/n): y
Install location /var/www/site/docroot/d8.dev//modules/admin_toolbar already exists. Do you want to overwrite it? (y/n): y</pre>

and on and on...

**Comment by bevinhex** [comment]
Same here, using the latest version
