### ISSUE TITLE
proc_open() has been disabled for security reasons backend.inc:376

### ISSUE THREAD

**Issue by pcsystemd** [drush-ops/drush#500]
Hello,
I use Drush for several years but on a new PC I came over to use Drupal to update because I get the following error: 
proc_open() has been disabled for security reasons backend.inc:376

I tested some tips found on the web but no work.

I'm on Debian 7 and my PHP version is 5.4.4-14 + deb7u7

In my php.ini :
disable_functions = escapeshellarg, escapeshellcmd,passthru, proc_close, proc_get_status, proc_nice, proc_open,proc_terminate, ..

You have an idea to help me
Thank you

**Comment by bisonbleu** [comment]
I don't mean to reopen this issue, so apologies. I cannot tell if my comment is in any way related to this issue. So simply getting a sense of what it is I'm seeing in my New Relic Dashboard would be helpful. Is there a link between proc_open() and the _drush_backend_proc_open that I see? A 38 sec. response time is unusual. Should I worry or not ?

<img width="1105" alt="new relic dashboard 2017-10-24 at 5 55 34 pm" src="https://user-images.githubusercontent.com/5081903/31970348-abe44930-b8e5-11e7-98be-2b1a68562640.png">
