### ISSUE TITLE
The "--editor" option doesn't work

### ISSUE THREAD

**Issue by Deyter** [drush-ops/drush#5004]
**Describe the bug**
A documented option, --editor, for config:edit does not work as expected.  
It should use editor from parameter but drush use vi in any case.

**To Reproduce**
1. Run the following command:
    drush config:edit --editor=nano system.site
2. Get an error if vi is not installed on system/docker.

**Error output:**
```
www-data@48ddfea3e18d:/app/drupal$ vendor/bin/drush config-edit --editor=nano system.site
sh: 1: vi: not found

In Process.php line 269:

  The command "${VISUAL-${EDITOR-vi}} /tmp/drush_tmp_1641803520_61dbef00e4fab/system.site.yml" failed.  

  Exit Code: 127(Command not found)                                                                     

  Working directory: /app/drupal/web                                                                    

  Output:                                                                                               
  ================                                                                                      


  Error Output:                                                                                         
  ================                                                                                      

```

**Expected behavior**
    Drush use editor from parameter but not default.

**Actual behavior**
Failed to edit config because vi is not installed.

**Workaround**
Is there another way to do the desired action?

Install vi editor.

<h3 dir="auto">System Configuration</h3>

**Q** | **A**
-- | --
Drush version? | 10.x#4be7782
Drupal version? | 9.x
PHP version | PHP 7.4.23
OS? | Linux eb40682e07bf 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 GNU/Linux

**Additional information**
I'm using Lando for development.

**Comment by weitzman** [comment]
PR in progress ... You can work around the issue for now by defining the EDITOR env variables.:
```
EDITOR=nano
```
