### ISSUE TITLE
RunServerCommand TypeError on fresh installation

### ISSUE THREAD

**Issue by K3nzie** [drush-ops/drush#5020]
`TypeError: Argument 1 passed to Drush\Commands\core\RunserverCommands::parseUri() must be of the type string, null given, called in /mydir/drupal/vendor/drush/drush/src/Commands/core/RunserverCommands.php on line 96 in Drush\Commands\core\RunserverCommands->parseUri() (line 127 of /mydir/drupal/vendor/drush/drush/src/Commands/core/RunserverCommands.php).  [warning] Drush command terminated abnormally.`

I saw another issue in a previous version that was supposedly fixed, am I doing something wrong?

Drupal v 9.3
Drush  v 11

**Comment by weitzman** [comment]
It's fixed but not yet released.
