### ISSUE TITLE
Drush 11 & Drupal 10 incompatibilities

### ISSUE THREAD

**Issue by andy-blum** [drush-ops/drush#5024]
**Describe the bug**
Drupal 10 now relies on Symfony 5.4, Drush needs to update its dependencies to be compatible

https://www.drupal.org/project/drupal/issues/3197482

Is there a reason Drush is re-declaring symfony components as dependencies? Couldn't it just depend on drupal/core?

**Comment by weitzman** [comment]
Lets bump dependencies in a PR, and fix any breakage. [Lets bump this job to Drupal 10](https://github.com/drush-ops/drush/blob/11.x/.circleci/config.yml#L110-L135).
