### ISSUE TITLE
Add YAML edit commands

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#5026]
Bring the commands and tests from https://github.com/grasmash/yaml-cli into Drush core. Feedback welcome.

**Comment by weitzman** [comment]
@grasmash - any opinion on this? 

- As a first step, it would be great if we could get yaml-cli to support symfony 6. Thats needed for Drupal 10.
- If desired, it would be possible to integrate as we do with DCG. Thus the same version of yaml-cli could in Drush or independantly.

**Comment by grasmash** [comment]
Yeah I’m fine with this. Would be nice to integrate rather than duplicate.

Supporting Symfony 6 should be trivial. I can do that.

**Comment by grasmash** [comment]
You should be all set with https://github.com/grasmash/yaml-cli/releases/tag/3.0.0

It requires Symfony 6 and PHP 8.

**Comment by weitzman** [comment]
Thanks ... Did you mean to make a new release? That one is from 12 days ago.

**Comment by grasmash** [comment]
I made a release 12 days ago that supported PHP 8 and Symfony 6.

**Comment by weitzman** [comment]
Looks to me like Symfony 6 is not supported in that release https://github.com/grasmash/yaml-cli/blob/3.0.0/composer.json

**Comment by grasmash** [comment]
Well, that was a mistake. I'll release 3.0.1 to fix it.

**Comment by grasmash** [comment]
https://github.com/grasmash/yaml-cli/releases/tag/3.0.1
