### ISSUE TITLE
Drush gen for rest resource is not compatible with Drupal 9+

### ISSUE THREAD

**Issue by lamp5** [drush-ops/drush#5027]
**Describe the bug**
Right now every rest resource return 404 for post method on Drupal 9.3. The problem is that uri_paths for create method was changed from:
`https://www.drupal.org/link-relations/create`
to
`create`

https://www.drupal.org/forum/support/module-development-and-code-questions/2016-10-05/why-httpswwwdrupalorglink#comment-14164333

**To Reproduce**
Run:
`drush gen rest-resource`

**Expected behavior**
``` * @RestResource (
 *   id = "invite_client",
 *   label = @Translation("Invite client"),
 *   uri_paths = {
 *     "create" = "/api/invite-client"
 *   }
 * )```

**Actual behavior**
` ``* @RestResource (
 *   id = "invite_client",
 *   label = @Translation("Invite client"),
 *   uri_paths = {
 *     "https://www.drupal.org/link-relations/create" = "/api/invite-client"
 *   }
 * )```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.x
| Drupal version? | 9.3
| PHP version     | 7.x
| OS?             | Windows

**Comment by Chi-teck** [comment]
Fixed in DCG 2.5.3. Thank you.
