### ISSUE TITLE
Drush is just GONE and will not re-install

### ISSUE THREAD

**Issue by Wilburunion** [drush-ops/drush#5037]
I had 10.6.2 working - on Centos 7 and today it is just GONE.   I had to remove phpunit and apparently it took the drush pathing setup for drush with it.  Now it says it is installed but the command is not found if I run composer require drush/drush:10.6.2

If I go to /public_html/vendor/drush/drush and run ./drush it is there but gives the error  " ! [NOTE] Drupal root not found. Pass --root or a @siteAlias in order to see Drupal-specific commands. "

How do I get this pathed back to the drupal root  ??

**Comment by weitzman** [comment]
Please use http://drupal.stackexchange.com/questions/tagged/drush for support.
