### ISSUE TITLE
Any Drush command fails with undefined Twig\Extension\CoreExtension::getName() 

### ISSUE THREAD

**Issue by moritzz** [drush-ops/drush#5040]
**Describe the bug**
After upgrading mt Drupal installation to 9.3.2 any Rush command fails with the following error message:

```
 [warning] Declaration of Drupal\Core\Template\TwigEnvironment::compileSource(Twig\Source $source) should be compatible with Twig\Environment::compileSource($source, $name = NULL) TwigEnvironment.php:108

Fatal error: Uncaught Error: Call to undefined method Twig\Extension\CoreExtension::getName() in /home/moritzzc/bin/drush/vendor/twig/twig/src/Environment.php:974
Stack trace:
#0 /home/moritzzc/bin/drush/vendor/twig/twig/src/Environment.php(149): Twig\Environment->addExtension(Object(Twig\Extension\CoreExtension))
#1 /home/moritzzc/public_html/mattenstrasse.org/core/lib/Drupal/Core/Template/TwigEnvironment.php(99): Twig\Environment->__construct(Object(Twig\Loader\ChainLoader), Array)
#2 /home/moritzzc/public_html/mattenstrasse.org/core/lib/Drupal/Component/DependencyInjection/Container.php(262): Drupal\Core\Template\TwigEnvironment->__construct('/home/moritzzc/...', Object(Drupal\Core\Cache\DatabaseBackend), 'yJLGKsPAn345GM3...', Object(Drupal\Core\State\State), Object(Twig\Loader\ChainLoader), Array)
#3 /home/moritzzc/public_html/mattenstrasse.org/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\Container->createService(Array, 'twig')
#4 /home/moritzzc/public_html/mat in /home/moritzzc/bin/drush/vendor/twig/twig/src/Environment.php on line 974
 [warning] Drush command terminated abnormally.
```

**To Reproduce**
Run any rush command. The above shows the result of `drush cr`.

**Expected behavior**
Drush commands run flawlessly.

**Actual behavior**
Drush commands end abnormally.

**Workaround**
No.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.0.3
| Drupal version? | 9.3.2
| PHP version     | 7.4.26
| OS?             | Linux

**Additional information**
The following contributed modules are active:

- flag
- matomo
- message
- message_subscribe
- message_notify
- token

**Comment by weitzman** [comment]
it looks like you are using a global drush (/home/moritzzc/bin/drush). please use a drush thats a local dependency of your project and call it via `/home/moritzzc/public_html/mattenstrasse.org/vendor/bin/drush`

**Comment by weitzman** [comment]
I suggest removing that global drush

**Comment by moritzz** [comment]
Thanks a lot @weitzman for trying to help me out with these issues. I removed my global druse installation and tried re-installing it as a local dependency. Unfortunately this fails too with ...

```
# composer require drush/drush
Using version ^11.0 for drush/drush
./composer.json has been updated
Running composer update drush/drush
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drush/drush[11.0.0-rc1, ..., 11.x-dev] require consolidation/config ^1.2 -> satisfiable by consolidation/config[1.2.0, 1.2.1, 1.x-dev].
    - consolidation/config[1.2.1, ..., 1.x-dev] require dflydev/dot-access-data ^1.1.0 -> found dflydev/dot-access-data[v1.1.0] but the package is fixed to v3.0.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires drush/drush ^11.0 -> satisfiable by drush/drush[11.0.0-rc1, ..., 11.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require drush/drush:*" to figure out if any version is installable, or "composer require drush/drush:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

I tried to circumvent this by forcing several version changes in these other dependencies. Because I'm not a super pro in composer, I failed. Could you probably hint me on how to get along form here on one more time?

**Comment by weitzman** [comment]
Thanks. Drush doesn't directly depend on that package, so leaving this issue Closed. My install shows 4 dependencies that need upgrading and new releases. These should be simple PRs if anyone has time. `consolidation/filter-via-dot-access-data ` is already upgraded, and just needs a release. Its PR is instructive https://github.com/consolidation/filter-via-dot-access-data/pull/46.

```
$ composer why dflydev/dot-access-data
consolidation/config                      1.2.1  requires  dflydev/dot-access-data (^1.1.0)
consolidation/filter-via-dot-access-data  1.0.0  requires  dflydev/dot-access-data (^1.1.0)
consolidation/output-formatters           4.2.1  requires  dflydev/dot-access-data (^1.1.0)
grasmash/expander                         1.0.0  requires  dflydev/dot-access-data (^1.1.0)
```

**Comment by greg-1-anderson** [comment]
We need to bump up to consolidation/filter-via-dot-access-data ^2. The latest release on the 2.x branch already allows newer versions of dot-access-data. ^2 should be b/c with ^1, except that it drops some older php versions that we don't need.

I made new releases for consolidation/config (2.0.3, will need a bumb to ^2 here as well) and consolidation/output-formatters (4.2.2), so now we're just down to grasmash/expander.
