### ISSUE TITLE
Add error details when a 'drush updb' update fails

### ISSUE THREAD

**Issue by JPustkuchen** [drush-ops/drush#5065]
**Is your feature request related to a problem? Please describe.**
When an update fails (for example when developing complex update hooks) and I'm using `drush updb` inly the error message is shown with no further details.

Even worse, using -v to -vvv there are no further details on the error / exception given.

For example:
drush updb -vvv:
[...]
> >  [notice] Update started: drowl_paragraphs_types_update_8402
> >  [error]  The configuration property settings.allowed_values.0.label.0 doesn't exist. 
> >  [error]  Update failed: drowl_paragraphs_types_update_8402
>  [error]  Update aborted by: drowl_paragraphs_types_update_8402 [23.61 sec, 51.16 MB] 
>  [error]  Finished performing updates. [23.61 sec, 51.12 MB] 

The only information is
`[error]  The configuration property settings.allowed_values.0.label.0 doesn't exist. ` 
but nothing is logged to watchdog and you can't trace back where the error happened.

**Describe the solution you'd like**
I'd at least need to see the file and line, where the error happened. Using -v to -vvv I'd expect to have the full backtrace.

**Describe alternatives you've considered**
Instead or additionally the error could be logged to watchdog?

Perhaps it would even make sense to output the full error / exception information when -v to -vvv is used in all kind of commands, not only drush updb?

**Comment by weitzman** [comment]
This is a difference between logging and exceptions. Logging provides no developer info beyond the message. It is not Drush that made the decision to log versus exception.

I suggest looking at the function drowl_paragraphs_types_update_8402.

**Comment by JPustkuchen** [comment]
Thank you for the super fast reply @weitzman ! :)
So you say there's no way to output further information about the error in `drush updb` in such cases?

Yes, the problem is, that the function (and called helper functions) are quite complex, so without the backtrace it's no fun :P And lead me to this point...

I'll find a way in this concrete case, just thought it would be nice for drush users.

**Comment by weitzman** [comment]
I see that Laravel didnt implement this when requested https://github.com/laravel/framework/pull/19745. You can always use Monolog as they suggest. See Monolog module for Drupal and configure this processor https://github.com/Seldaek/monolog/blob/main/src/Monolog/Processor/IntrospectionProcessor.php
