### ISSUE TITLE
Installing modules is failing on Drupal 10 due to calls to deprecated function "module_load_install"

### ISSUE THREAD

**Issue by lhridley** [drush-ops/drush#5072]
**Describe the bug**
In Drupal 9.4, `module_load_include` has been deprecated, and will be removed in Drupal 10.  This function call still exists in Drush 11.
**To Reproduce**

1. Install Drupal 10 with Drush 11
2. Add any module and attempt to enable that module

**Expected behavior**
Module is enabled without issue
**Actual behavior**
Module installation fails with a fatal error due to calls to a now removed function `module_load_include`.  See https://github.com/Drupal-10-Compatibility/advancedqueue/runs/5174788737?check_suite_focus=true#step:12:45 for full stack dump.
**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.0.5
| Drupal version? | 10.x
| PHP version     | 8.1
| OS?             | Mac/Linux

**Comment by lhridley** [comment]
PR submitted:  https://github.com/drush-ops/drush/pull/5073

**Comment by weitzman** [comment]
Fixed in #5078
