### ISSUE TITLE
"Bootstrap failed. Run your command with -vvv for more information" on site:install <anything>

### ISSUE THREAD

**Issue by John-doe-lee** [drush-ops/drush#5083]
**Describe the bug**
i create project with 'composer create-project drupal-composer/drupal-project drupal  --no-interaction'

when i run 

vendor/bin/drush site:install -y --uri=http://drupal.server.host --site-name="云ERP" --locale=zh-hans --account-pass=admin --db-url=mysql://root:root@localhost/ezerp 

In BootstrapHook.php line 36:
                                                                      
  Bootstrap failed. Run your command with -vvv for more information.

drush status

` PHP binary    : /usr/local/Cellar/php@7.4/7.4.28/bin/php               
 PHP config    : /usr/local/etc/php/7.4/php.ini                         
 PHP OS        : Darwin                                                 
 Drush script  : /Users/nie/Project/drupal/vendor/drush/drush/drush     
 Drush version : 11.0.5                                                 
 Drush temp    : /tmp                                                   
 Drush configs : /Users/nie/Project/drupal/vendor/drush/drush/drush.yml 
                 /Users/nie/Project/drupal/drush/drush.yml              
 Drupal root   : /Users/nie/Project/drupal`

**To Reproduce**
What did you do?

**Expected behavior**
What did you expect would happen?

**Actual behavior**
What happened instead?

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.x
| Drupal version? | 9.x
| PHP version     | 7.4
| OS?             | Mac

**Additional information**

**Comment by weitzman** [comment]
Support questions belong in Drupal Answers. Use drush tag there,
