### ISSUE TITLE
Placeholder token not replaced in error message

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#5086]
**Describe the bug**

I was doing `drush updb` and got this error:

```
 [notice] Module admin_toolbar_search has an entry in the system.schema key/value storage, but is not installed. <a href=":url">More information about this error</a>.
```

Where's the `:url` gone?

**To Reproduce**
What did you do?

**Expected behavior**
What did you expect would happen?

**Actual behavior**
What happened instead?

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.6.2
| Drupal version? | 8.9.9
| PHP version     | 7.4.2
| OS?             | Mac

**Additional information**

**Comment by weitzman** [comment]
Thanks. Please upgrade when possible. Drush 10 is EOL https://www.drush.org/latest/install/#drupal-compatibility
