### ISSUE TITLE
How to pass alias to remote for remote drush to use?

### ISSUE THREAD

**Issue by fskreuz** [drush-ops/drush#5087]
**Describe the bug**

How do I pass a remote alias to use on the remote environment when running a remote command?

**To Reproduce**

Run the following command:

```sh
drush @project.dev sql:dump
```

**Expected behavior**

I was expecting something along the lines of:

```sh
ssh -t -o PasswordAuthentication=no admin@gatekeeper.project.net 'drush @project.dev sql:dump --uri=default'
```

Note the remote command has `@project.dev`, was somewhat expecting that drush would forward the alias name.

**Actual behavior**

Drush doesn't pass the alias, which makes sense.

```sh
ssh -t -o PasswordAuthentication=no admin@gatekeeper.project.net 'drush sql:dump --uri=default'
```

**Workaround**

None that I know of.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.x
| Drupal version? | 9.x
| PHP version     | 7.x
| OS?             | Mac/Linux

**Additional information**

Our remote environments are currently fronted by a Linux instance acting as the gatekeeper between the developers and the actual environments (apache and mysql instances running Drupal). This was done to limit the exposure of the actual environments and limit the details that need to be shared to developers (e.g. ssh keys, URLs, IP addresses). On this gatekeeper instance, Drush is installed and has an alias file pointing to the various environments.

The expectation was that developers should be able to do something like `drush @project.dev sql:dump` and Drush would just forward this to the gatekeeper server to run it against the `@project.dev` alias defined on the remote. This used to work in Drush 8, but I can't find a way to get it to work with Drush 9+. 

I've tried writing the command like these, but to no avail:

- `drush @project.dev sql:dump` - The case described above, only `drush sql:dump --uri=default` is passed.
- `drush @project.dev @remote.dev sql:dump` - Takes `@remote.dev` as the command. Error.
- `drush @project.dev sql:dump @remote.dev` - Takes `@remote.dev` as an argument. `sql:dump` doesn't take any. Error.
- `drush @project.dev sql:dump -- @remote.dev` - Same as previous. Error.

I'm aware that Drush 9+ was rewritten and simplified. Just wondering if this is still supported, and if not, is there a workaround or a different syntax to do this.

**Comment by weitzman** [comment]
we dont pass aliases along like that. i'm surprised that used to work. i think the ssh config in this section is still the best w ay. this removes drush from the initial ssh connection https://github.com/drush-ops/drush/blob/8.x/docs/bastion.md#setting-up-a-bastion-server-in-sshconfig. the rest of that doc is no longer relevant to modern drush. 

drush @project.dev
