### ISSUE TITLE
TypeError for drush generated plugin

### ISSUE THREAD

**Issue by simblycode** [drush-ops/drush#5099]
**Describe the bug**

Error while accessing 'admin/config/services/rest' after enabling plugin generated via drush

Below is the error seen in the logs

```
TypeError: get_class_methods(): Argument #1 ($object_or_class) must be an object or a valid class name, string given in get_class_methods() (line 158 of
drupal9/web/modules/contrib/restui/src/Controller/RestUIController.php)
#0 drupal9/web/modules/contrib/restui/src/Controller/RestUIController.php(158): get_class_methods('Drupal\\store_re...')
#1 [internal function]: Drupal\restui\Controller\RestUIController->listResources()
```

**To Reproduce**

- Generated plugin using `drush generate plugin:example`
- Enable plugin using `drush en example`
- Visit 'admin/config/services/rest', error can be seen
- Disable plugin using 'drush pmu example'
- Visit 'admin/config/services/rest', no error can be seen

**Expected behavior**
No error and lists all enabled and disabled resources

**Actual behavior**
Error message

**Workaround**
Couldn't find any

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.0.7
| Drupal version? | 9.3.9
| PHP version     | 8.1.1
| OS?             | Mac

**Comment by Chi-teck** [comment]
> Generated plugin using `drush generate plugin:example`

Where does `plugin:example` come from? Drush does not provide such generator.

**Comment by weitzman** [comment]
No reply
