### ISSUE TITLE
Documentation on upgrade Drush extensions from Drush 5.x -> 6.x?

### ISSUE THREAD

**Issue by dsnopek** [drush-ops/drush#51]
Is there anywhere that explains the API changes from Drush 5.x -> 6.x from the perspective of someone who maintains a Drush extension? I'd love something along the lines of Drupal change notices for Drupal core. I'm not really sure how to begin porting something (other than just trying it and seeing what breaks ;-)).

**Comment by greg-1-anderson** [comment]
Drush 6 EOL; closing.
