### ISSUE TITLE
Deprecated warning when running php 8.0.8 and drush 11

### ISSUE THREAD

**Issue by carolpettirossi** [drush-ops/drush#5101]
**Describe the bug**
When I try to run any drush command with aliases I get Deprecated errors.

```
The command "/usr/local/bin/drush core-rsync @self:/home/docker/drush-backups/default/20220328222532/default_20220328_222532.sql.gz '@onsetd9.dev:Deprecated: Required parameter $args follows optional   
  parameter $command in /usr/local/drush9/vendor/drush/drush/includes/batch.inc on line 115  Deprecated: Required parameter $options follows optional parameter $command in /usr/local/drush9/vendor/drush  
  /drush/includes/batch.inc on line 115 /mnt/tmp/onsetd9dev/default_20220328_222532.sql.gz' --yes --uri=onset.docksal --root=/var/www/docroot -- --remove-source-files" failed.       
```                      
                       

**To Reproduce**
Run `drush sql-sync @self @onsetd9.dev `

**Expected behavior**
I expected the database on @onsetd9.dev to be restored with database from @self

**Actual behavior**
Command failed.

**Workaround**
Couldn't find one

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.6.2 or 11.0.5 _(I couldn't upgrade to 11.0.7 due to [acquia/blt](https://github.com/acquia/blt/issues/4490))_
| Drupal version? | 9.3.9
| PHP version     | 8.0.8
| OS?             | Linux (using Docksal)

**Comment by weitzman** [comment]
please share the errors.

**Comment by weitzman** [comment]
also please use latest drush

**Comment by carolpettirossi** [comment]
Hi @weitzman, 

I just updated the code description. I also noticed that I cannot upgrade to 11.0.7 as I have acquia/blt dependency. 

I'm wondering if you could release a new v10 for PHP 8? 

Also noticed that you mentioned that the issue has been fixed on latest version here: https://github.com/drush-ops/drush/issues/4914 
However, it doesn't seem that line 115 of batch.inc has changed from 10.6.2 to 11.0.7. Is that right?

**Comment by weitzman** [comment]
PRs for Drush 10 will be reviewed and considered. The maintainers are not actively working on it.
