### ISSUE TITLE
"drush cr" will not update module cache / registry, related to resolving modules directory

### ISSUE THREAD

**Issue by joshsedl** [drush-ops/drush#5102]
**Describe the bug**
When I am uninstalling a module, run "drush cr", move the directory the module resides in and reinstall the module, Drupal is still looking for the module's files in the old directory and throws the following error:
`Error: Class 'Drupal\photoswipe\PhotoswipeAssetsManager' not found in Drupal\Component\DependencyInjection\Container->createService() (line 262 of core/lib/Drupal/Component/DependencyInjection/Container.php).`

**To Reproduce**
The module resides in "web/modules/custom". Uninstall the module, run "drush cr", rename the modules folder or move the module folder to "web/modules/contrib", reinstall the module.

**Expected behavior**
The drush cr command will delete the appropriate module cache/registry connected to resolving the path to its source code

**Actual behavior**
The old directory is still set for the module.

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.0.7
| Drupal version? | 9.3.9
| PHP version     | 7.4.28
| OS?             | Windows Subsystem for Linux (Ubuntu)

**Comment by JPustkuchen** [comment]
@joshsedl do I get you right, you mean for example if you move a module from custom to contrib (as it was for example released) and calling `drush cr`, Drupal still expects it in `custom` and you'd expect `drush cr` to fix that or add a command like `drush registry-rebuild` to fix this?

**Comment by joshsedl** [comment]
@JPustkuchen Yes exactly!

**Comment by weitzman** [comment]
Drush delegates all path caches and module discovery to Drupal so this isn't likely a Drush bug.

**Comment by JPustkuchen** [comment]
Here's a longer discussion about that topic when moving a module:
https://drupal.stackexchange.com/questions/185958/moving-module-location

@joshsedl you should try these steps:
```
    Move the module in filesystem
    invoke drush ev "drupal_flush_all_caches();"
    invoke drush cr
```
Does that solve the problem?

Also, you could grep the drush source code and check if any command calls drupal_flush_all_caches() or not. If not, that might be a reason for further discussion about such cases. Anyway, I would have thought `drush cr` also handles that. Anyway I wouldn't call it a drush bug, but might be a feature to have a command to solve that problem in the future (if possible and not yet existing - still to be evaluated).

Thanks!
