### ISSUE TITLE
Drush si should not continue if it can't connect to the database; outputs misleading error

### ISSUE THREAD

**Issue by webchick** [drush-ops/drush#511]
In yet another fabulous display of PEBCAK, today I attempted to use drush si whilst Acquia Dev Desktop was turned off, so there was no MySQL database / Apache process to serve drush's request. drush si of course failed. However, rather than Drush bailing out when it couldn't find the database, it proceeded along anyway, so I ended up getting a  Drupal\Core\Installer\Exception\AlreadyInstalledException which sent me down a few rabbit holes before I finally gave up and resigned myself to a manual install through the UI and thereby instantly realized my mistake. :P

Suggestion would be:

```
$ drush si --account-pass=admin -y
You are about to empty any Config directories and CREATE the '8x' database. Do you want to continue? (y/n): y
Warning: Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (61)
# STOP. FAIL HERE. DO NOT CONTINUE. IT IS POINTLESS. LIFE IS MEANINGLESS. AND SO ON.
Starting Drupal installation. This takes a few seconds ...           [ok]
WD php: Drupal\Core\Installer\Exception\AlreadyInstalledException:   [error]
[5K of HTML barf]
```

**Comment by mikeryan776** [comment]
+1 - same thing happened to me today, but without the "Can't connect to MySQL server" error to clue me in, so I blamed my fresh pull of core and spun my wheels trying to find which recent commit to blame.

An underlying issue here is that AlreadyInstalledException is thrown from various places, it would be helpful if core provided a specific hint at each place as to why it thinks Drupal is already installed...

**Comment by mikeryan776** [comment]
Core issue: https://www.drupal.org/node/2459671

**Comment by weitzman** [comment]
The first time Drush tries to connect to Db we are checking if the target DB exists. The way we do that currently makes it hard to distinguish between DB needing to be created and mysql being unavailable. Needs a little refactor.

**Comment by tbfisher** [comment]
I'm confused...

```
$ drush si
You are about to DROP all tables in your 'example2' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the [ok]
--notify global option.
exception 'Drupal\Core\Installer\Exception\AlreadyInstalledException'[error]
with message '<ul>
<li>To start over, you must empty your existing database and copy
<em>default.settings.php</em> over <em>settings.php</em>.</li>
```

**Comment by frankcarey** [comment]
Yes, I get the same error after trying to re-install with "drush si --writable"

**Comment by weitzman** [comment]
Whats --writable? Thats not in core Drush.

**Comment by RoSk0** [comment]
The same issue still happens when drush fails to delete all tables(sql-drop) before si. In my case this happen because there was  way too many tables left after simpletest(~7.2k) and PostgreSQL was running out of memory to wrap transaction

**Comment by joachim-n** [comment]
Seeing this with Drush 10:

```

 You are about to:
 * Create a sites/default/settings.php file
 * CREATE the 'drupal-foobar' database.

 Do you want to continue? (yes/no) [yes]:
 >

 [warning] Failed to drop or create the database. Do it yourself before installing. ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (61)

 [notice] Starting Drupal installation. This takes a while.
 [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile
 [notice] Performed install task: install_verify_requirements

In install.core.inc line 967:

  Resolve all issues below to continue the installation. For help configuring your database server, see the <a hre
  f="https://www.drupal.org/docs/8/install">installation handbook</a>, or contact your hosting provider.<div class
  ="item-list"><ul><li>Failed to connect to your database server. The server reports the following message: <em cl
  ass="placeholder">SQLSTATE[HY000] [2002] Connection refused</em>.<ul><li>Is the database server running?</li><li
  >Does the database exist or does the database user have sufficient privileges to create the database?</li><li>Ha
  ve you entered the correct database name?</li><li>Have you entered the correct username and password?</li><li>Ha
  ve you entered the correct database hostname and port number?</li></ul></li></ul></div>


site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command> [<profile>]...
```

**Comment by weitzman** [comment]
Yeah, that’s much better, IMO we ca  close this.

**Comment by joachim-n** [comment]
It's better, but it's still needlessly doing all this:

```
 [notice] Starting Drupal installation. This takes a while.
 [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile
 [notice] Performed install task: install_verify_requirements
```

**Comment by weitzman** [comment]
That’s new logging in Drush 10 that I've found helpful. Installer errors are often hard to debug. This helps a bunch. It also helps identify why Drupal's installer is so slow. Otherwise we hwave a prompt that says nothing for 30 seconds.

I suppose they could be info level instead of notice level if these messages bothered  more people.

**Comment by joachim-n** [comment]
What I mean is (to quote webchick from years ago) this:

```
 [warning] Failed to drop or create the database. Do it yourself before installing. ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (61)

# STOP. FAIL HERE. DO NOT CONTINUE. IT IS POINTLESS. LIFE IS MEANINGLESS. AND SO ON.

 [notice] Starting Drupal installation. This takes a while.
 [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile
 [notice] Performed install task: install_verify_requirements
```

**Comment by weitzman** [comment]
Ah, I see. Basically, we don't know if install will succeed at that point. All we know is that we failed to drop existing tables. Often that happens because there is no `mysql` on user's PATH (common with Docker). So now Drush considers this not a fatal error, and proceeds with a 'Drop them yourself' message. I know the error text says 'Connection refused' but we generally don't parse and rely on CLI error text (unlike PHP Exception type which is more explicit).

**Comment by weitzman** [comment]
I forgot to say that you can run all but sql:* commands without a `mysql` client nowadays, including site:install. The bootstrap uses PDO instead of `mysql`

**Comment by weitzman** [comment]
If someone wants to work on quitting earlier, `$sql->getProcess()->getErrorOutput()` gives `ERROR 2002 (HY000): Can't connect to MySQL server on '192.168.3.99' (36)` for me. Add a check for that [here](https://github.com/drush-ops/drush/blob/f590ce2233db71408ed2e17e527417efc58bd007/src/Commands/core/SiteInstallCommands.php#L360).
