### ISSUE TITLE
Add revert functionality to Config entities

### ISSUE THREAD

**Issue by thenchev** [drush-ops/drush#5119]
**Is your feature request related to a problem? Please describe.**
The feature request is not related to a problem. We are in the process of adding a new API to revert config entities in Drupal core and it would be great if we can add that functionality in Drush itself. The more usages we have of the API the better

**Describe the solution you'd like**
After the core patch is committed It would be great to add the revert functionality calling the core API

**Describe alternatives you've considered**
Nothing here yet.

**Additional context**
[Add revert functionality to Config entities](https://www.drupal.org/project/drupal/issues/1497268)

**Comment by weitzman** [comment]
Sure. A PR will be considered once the Drupal core issue lands.
