### ISSUE TITLE
Drush cannot connect to database in MAMP

### ISSUE THREAD

**Issue by C13L0** [drush-ops/drush#512]
os: mavericks
Drush Version   :  6.2.0
MAMP:  Version 3.0.2 (3.0.2)
PHP Version 5.5.10
mysql  Ver 14.14 Distrib 5.5.34, for osx10.6 (i386) using  EditLine wrapper

Steps I have taken to troubleshoot
1. Uninstalled older version and re-installed most current version of mamp. 
2. Removed older version of drush and re-installed via composer. 
3. Installed a fresh drupal site and downloaded a few modules with drush (just to verify drush works and no issues with clean drupal install)
4. Verified that /.drush php.ini was the same as mamp php.ini 
   https://github.com/drush-ops/drush/issues/420
5. Created a symlink to the socket 
   http://stackoverflow.com/questions/19300996/drush-cannot-connect-to-mysql-on-mamp
6. Edited settings.php from 'host' => 'localhost',   To:  'host' => '127.0.0.1',  
   https://drupal.org/node/1428638
7. Have tried: drush --uri=drupal7.dev en pathauto

[Cielo@Keiths-MacBook-Pro:~/localhost/drupal7.dev ] $ drush en pathauto
Command pm-enable needs a higher bootstrap level to[error]
run - you will need to invoke drush from a more
functional Drupal environment to run this command.
The drush command 'en pathauto' could not be       [error]
executed.
Drush was not able to start (bootstrap) the Drupal [error]
database.
Hint: This may occur when Drush is trying to:
- bootstrap a site that has not been installed or
  does not have a configured database. In this case
  you can select another site with a working database
  setup by specifying the URI to use with the --uri
  parameter on the command line. See `drush topic
  docs-aliases` for details.
- connect the database through a socket. The
  socket file may be wrong or the php-cli may have no
  access to it in a jailed shell. See
  http://drupal.org/node/1428638 for details.

Any help would truly be appreciated!

**Comment by creutz** [comment]
Thanks C13L0, I had the exact same problem when trying to use drush after upgrading to OSX Yosemite, your exports worked for me.

**Comment by dupls** [comment]
This worked perfectly. The key was a complete shut down. thanks,
