### ISSUE TITLE
Drush 10 || 11 throws error when running core-cli, due to incompatibility with psy/psysh:~11

### ISSUE THREAD

**Issue by marklabrecque** [drush-ops/drush#5141]
I get an error thrown by drush when running core-cli subcommand.

**To Reproduce**
When I run drush core-cli, I get the following error.
PHP Fatal error:  Declaration of Drush\Psysh\Shell::hasCommand($input) must be compatible with Psy\Shell::hasCommand(string $input): bool in /var/www/html/vendor/drush/drush/src/Psysh/Shell.php on line 37

Fatal error: Declaration of Drush\Psysh\Shell::hasCommand($input) must be compatible with Psy\Shell::hasCommand(string $input): bool in /var/www/html/vendor/drush/drush/src/Psysh/Shell.php on line 37
 [warning] Drush command terminated abnormally.

**Expected behavior**
I would expect the core-cli command to succeed and drop me into a functioning shell

**Actual behavior**
See above error.

**Workaround**
No known workaround.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.x/10.x (I tried a number of minor version revisions on both 10 and 11, to same result)
| Drupal version? | 9.3.12
| PHP version     | 7.4
| OS?             | Linux - arm64

**Additional information**
Please note, there is already another similar issue for drush 8 that might be related, but enough changed between 8 and 10/11 that it may be a different problem that manifests the same.

See #5134

**Comment by greg-1-anderson** [comment]
We have https://github.com/drush-ops/drush/pull/4919 and https://github.com/drush-ops/drush/pull/5136 for Drush 8. Seems like an update of the signatures for the Psysh method overrides and an update to composer.json should make it work again. Might be trickier if both new and old versions of psysh need to be supported (e.g. for older versions of Drupal).

PRs welcome. Please ping a maintainer if you think test failures are not related to the PR. Usually, rebasing should fix those sorts of problems.

**Comment by damienmckenna** [comment]
This problem was fixed in commit c1b3a1 and was released in 11.0.0-rc3. I ran into this problem on a site that was still tied to Drush 10.3, once I updated to Drush 11 it worked fine.
