### ISSUE TITLE
Add Version Selector to drush.org

### ISSUE THREAD

**Issue by tekNorah** [drush-ops/drush#5151]
**Existing document**
https://www.drush.org/latest/commands/all/

**What are you attempting to do**
Get a list of Drush 10 commands

**In what way is the existing documentation unclear or incomplete**
No version switcher option in header or footer

**What should the documentation say instead?**
Version Selector should be available in the header.  See: https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/

**Comment by tekNorah** [comment]
Would this change be done here?
https://github.com/drush-ops/drush/blob/11.x/mkdocs_base.yml

**Comment by tekNorah** [comment]
The comment on this issue appears to be related: https://github.com/drush-ops/drush/pull/4623

**Comment by weitzman** [comment]
Yes, that would be the file. See https://www.drush.org/latest/commands/mk_docs/ for the command that makes an mkdocs.yml out of that.

I think we should do this soon, before we release 12.0
