### ISSUE TITLE
Drush site:install should check for existing site install

### ISSUE THREAD

**Issue by rajeshreeputra** [drush-ops/drush#5159]
**Is your feature request related to a problem? Please describe.**
drush site:install should check for existing drupal installation and ask user for confirmation to start over.

**Describe the solution you'd like**
- run `drush site:install`
- this should check if drupal already installed
- if yes, 
  - ask question "Seems like Drupal is already installed, would you like to re-install? [no]", basically yes/no question
  - if yes, start with site install
  - if no, do not proceed with site install
- if no, start with normal site install

**Comment by weitzman** [comment]
It pretty much does do this. You are prompted when drush wants to drop all tables of an existing database.
