### ISSUE TITLE
Error on remote pm:list command with "--no-core" option

### ISSUE THREAD

**Issue by DicksB** [drush-ops/drush#5161]
**Describe the bug**
I'm not 100% certain whether this is a Drush problem or an Acquia Cloud problem. When I attempt to issue a remote `drush pm:list` command to a site running in Acquia Cloud, I get an error if I use the --no-core option. The error does not occur when I run the command locally, and it doesn't occur with any other option that I've been able to find (for example, "--core" works as expected).

**To Reproduce**
Working as expected, locally: `drush --uri=https://bar.baz pm:list --type=module --status=disabled --no-core --format=json`
Produces error, remotely: `drush @foo.prod --uri=https://bar.baz pm:list --type=module --status=disabled --no-core --format=json`

**Expected behavior**
A JSON-formatted list of disabled, non-core modules.

**Actual behavior**
I get the following error: `The "--core" option does not accept a value.`

**Workaround**
I can leave out the option and drop the core modules from the results in my code.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.0.9
| Drupal version? | 9.3.16
| PHP version     | 8.0.18 locally, 8.0.16 in Acquia Cloud
| OS?             | Mac locally, Linux in Acquia Cloud

**Additional information**
I'm afraid I don't have another remote environment to test, which could help determine whether the problem is exclusive to Acquia Cloud or not.

**Comment by DicksB** [comment]
Looks like it's 11.0.9 on the server as well.

**Comment by DicksB** [comment]
OK, problem solved. I'm not sure why, but switching from using a global alias (drush @foo.prod) to a self.site.yml alias (drush @prod) resolves the issue.

**Comment by greg-1-anderson** [comment]
Can you run it both ways with `--debug`, and report the difference in options that Drush is passing? Could be a stray setting in your global alias, or could be a Drush bug.

**Comment by DicksB** [comment]
Oh, well, this could have something to do with it...--debug shows me that when I use the global alias, Drush is trying to use the old foo.aliases.drushrc.php file generated by Acquia Dev Desktop years ago, rather than the much newer .yml file I converted it to quite a while back. It looks like, although the remote status command was reporting the remote drush version as 11.0.9, the local version that was being found by Drush Launcher is an old 8.x phar somewhere on my system.

My apologies for the false alarm!

**Comment by greg-1-anderson** [comment]
np, glad you got it worked out.
