### ISSUE TITLE
Drush 11 doesn't work with PHP 8.0

### ISSUE THREAD

**Issue by colearseneau** [drush-ops/drush#5164]
**Describe the bug**
Tried using Drush 11 with php 8.0 since Docker doesn't have support for php 8.1 yet and when trying to use them together on my Drupal 9 site, and command I run with drush or any page I try to view said I needed php => 8.1 or newer. I check the compatibility of each module I was using and everything was supported for my PHP version and if I remembered right, it broke when moving to Drupal Core 9. 

**To Reproduce**
Use Lando to serve and manage dev environment of Drupal Core 9.4 site with php 8.0, and Drush 11. 

**Expected behavior**

Everything to work as expected since PHP 8.0 and Drush 11 are compatible, so running lando drush updatedb or drush updatedb I should get the expected prompt to update the database and continue on.

**Actual behavior**

Receive error when using Drush and viewing site pages (need to updatedb and it prevents me from version when upgrading core from 9.3 to 9.4)

<img width="1311" alt="Screen Shot 2022-06-20 at 11 48 18" src="https://user-images.githubusercontent.com/15149715/174648115-e0a41e52-0190-40dc-8380-bbc6cf34f3e0.png">

![Screen Shot 2022-06-20 at 11 49 04](https://user-images.githubusercontent.com/15149715/174648129-439b54c8-fefa-4f65-b467-af66308b79f1.png)

PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.18. in /app/vendor/composer/platform_check.php on line 24

Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.18. in /app/vendor/composer/platform_check.php on line 24

**Workaround**

Downgrade to Drush 10

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | ^11
| Drupal version? | 9.4
| PHP version     | 8.0
| OS?             | Mac

**Additional information**

**Comment by kevinquillen** [comment]
I also have the same issue. When I require drush ^11 in Composer, I am met with this message:

```
  Problem 1
    - symfony/filesystem is locked to version v6.1.0 and an update of this package was not requested.
    - symfony/filesystem v6.1.0 requires php >=8.1 -> your php version (8.0.11) does not satisfy that requirement.
  Problem 2
    - symfony/finder is locked to version v6.1.0 and an update of this package was not requested.
    - symfony/finder v6.1.0 requires php >=8.1 -> your php version (8.0.11) does not satisfy that requirement.
  Problem 3
    - symfony/string is locked to version v6.1.0 and an update of this package was not requested.
    - symfony/string v6.1.0 requires php >=8.1 -> your php version (8.0.11) does not satisfy that requirement.
  Problem 4
    - symfony/filesystem v6.1.0 requires php >=8.1 -> your php version (8.0.11) does not satisfy that requirement.
    - consolidation/self-update 2.0.5 requires symfony/filesystem ^2.5 || ^3 || ^4 || ^5 || ^6 -> satisfiable by symfony/filesystem[v6.1.0].
    - consolidation/self-update is locked to version 2.0.5 and an update of this package was not requested.

```

**Comment by weitzman** [comment]
Same advice: "What you are seeing here is that you used PHP 8.1 to do a composer update on your Drupal site, and then tried to run it on PHP 8.0.".
