### ISSUE TITLE
Drush make doesn't clean/remove temporary files when build fails

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#517]
I've the build which is takes around 250MB in size and when drush make fails, it doesn't remove the temporary files. So if I run drush make twice in OS with 0,5GB of /tmp, I'll run out of space.
So each time I've to remove the dirs such as /tmp/make_tmp_\* or /tmp/drush_tmp_\* manually.
Is there any argument which removes the temporary files when build fails?
It's a bug or feature?

**Comment by ergonlogic** [comment]
Can you provide a log of the type of failure you're seeing that's leaving behind the tmp/ dir.

Iirc, the function that creates a temporary directory registers a shutdown function to clean it up. Perhaps that isn't triggered on a rollback?

**Comment by greg-1-anderson** [comment]
Drush make is in maintenance only; closing.
