### ISSUE TITLE
drush rq throws "Unexpected file extension" after installing contrib modules

### ISSUE THREAD

**Issue by csandanov** [drush-ops/drush#5173]
**Describe the bug**
After installing purge module (including purge drush) on Drupal 9.4 and PHP 7.4 I get the following error.
```
$ drush rq

PHP Fatal error:  Uncaught TYPO3\PharStreamWrapper\Exception: Unexpected file extension in "phar:///usr/local/bin/drush/.box/bin/core/modules/mysql/src/Driver/Database/mysql//Update.php" in /var/www/html/web/core/lib/Drupal/Core/Security/PharExtensionInterceptor.php:44
Stack trace:
#0 /var/www/html/vendor/typo3/phar-stream-wrapper/src/Behavior.php(72): Drupal\Core\Security\PharExtensionInterceptor->assert()
#1 /var/www/html/vendor/typo3/phar-stream-wrapper/src/Manager.php(110): TYPO3\PharStreamWrapper\Behavior->assert()
#2 /var/www/html/vendor/typo3/phar-stream-wrapper/src/PharStreamWrapper.php(421): TYPO3\PharStreamWrapper\Manager->assert()
#3 /var/www/html/vendor/typo3/phar-stream-wrapper/src/PharStreamWrapper.php(410): TYPO3\PharStreamWrapper\PharStreamWrapper->assert()
#4 phar:///usr/local/bin/drush/.box/vendor/composer/ClassLoader.php(571): TYPO3\PharStreamWrapper\PharStreamWrapper->url_stat()
#5 phar:///usr/local/bin/drush/.box/vendor/composer/ClassLoader.php(571): include()
#6 phar:///usr/local/bin/drush/.box/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#8 [internal function]: spl_autoload_call()
#9 /var/www/html/web/core/lib/Drupal/Core/Database/Connection.php(1129): class_exists()
#10 /var/www/html/web/core/lib/Drupal/Core/Database/Connection.php(1332): Drupal\Core\Database\Connection->getDriverClass()
#11 /var/www/html/web/core/lib/Drupal/Core/Database/Query/Merge.php(400): Drupal\Core\Database\Connection->update()
#12 /var/www/html/web/core/lib/Drupal/Core/Config/DatabaseStorage.php(152): Drupal\Core\Database\Query\Merge->execute()
#13 /var/www/html/web/core/lib/Drupal/Core/Config/DatabaseStorage.php(128): Drupal\Core\Config\DatabaseStorage->doWrite()
#14 /var/www/html/web/core/lib/Drupal/Core/Config/CachedStorage.php(124): Drupal\Core\Config\DatabaseStorage->write()
#15 /var/www/html/web/core/lib/Drupal/Core/Config/Config.php(224): Drupal\Core\Config\CachedStorage->write()
#16 /var/www/html/web/modules/contrib/purge/src/Logger/LoggerService.php(106): Drupal\Core\Config\Config->save()
#17 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/KernelDestructionSubscriber.php(51): Drupal\purge\Logger\LoggerService->destruct()
#18 [internal function]: Drupal\Core\EventSubscriber\KernelDestructionSubscriber->onKernelTerminate()
#19 /var/www/html/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func()
#20 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(100): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#21 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(32): Symfony\Component\HttpKernel\HttpKernel->terminate()
#22 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(687): Stack\StackedHttpKernel->terminate()
#23 /var/www/html/vendor/drush/drush/src/Boot/DrupalBoot8.php(306): Drupal\Core\DrupalKernel->terminate()
#24 [internal function]: Drush\Boot\DrupalBoot8->terminate()
#25 {main}
  thrown in /var/www/html/web/core/lib/Drupal/Core/Security/PharExtensionInterceptor.php on line 44
```

**To Reproduce**
- Set up vanilla Drupal, e.g. via https://github.com/wodby/docker4drupal
- Download purge module `composer require -n drupal/purge`
- Install site via `drush si`
- Enable modules: `drush en -y purge purge_queuer_coretags purge_drush`
- Run `drush rq` to see the error

**Expected behavior**
No exception should be thrown

**Actual behavior**
An "Unexpected file extension" thrown

**Workaround**
Use PHP 8

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.0.9
| Drupal version? | 9.4
| PHP version     | 7.4
| OS?             | Alpine Linux

**Additional information**
Worked fine before 9.4 update

Can be seen failing in docker4drupal tests: [https://github.com/wodby/docker4drupal/runs/7016062158?check_suite_focus...](https://github.com/wodby/docker4drupal/runs/7016062158?check_suite_focus=true)

You can actually clone https://github.com/wodby/docker4drupal and run `PHP_VER=7.4 make test`  from the repository root to reproduce it.

**Comment by weitzman** [comment]
@csandanov It looks like you using a global drush, and not the one that composer installs into vendor/bin/drush. IMO projects should not be bundling drush. They should instruct users to install and use the drush thats in their own codebase, and vendor/bin/drush. if you must ship with a global program, use drush launcher instead of drush. See https://github.com/drush-ops/drush-launcher. If you are already using drush launcher, perhaps this bug belongs to that project.

**Comment by csandanov** [comment]
Yes, I'm using drush launcher. Global drush and the project drush have the same version 11.0.9

**Comment by nmenon8684** [comment]
hello, 

i too got this error, but i was able to apply this patch here and it seemed to work for me
https://www.drupal.org/project/drupal/issues/3291830

**Comment by weitzman** [comment]
If that doesnt fix the issue, please post here and i will reopen.
