### ISSUE TITLE
sqlite query/dump doesn't work correctly as its just using the command, none of the connection options from Drupal are set.

### ISSUE THREAD

**Issue by singularo** [drush-ops/drush#5191]
**Is your feature request related to a problem? Please describe.**
If you try `drush sql:dump --result-file=test.sql` with an sqlite database, what you get appears valid, however trying to load it back into Drupal with `drush sql:query --file=test.sql` gives a lot of errors.

The problem is that there are quite a few custom things setup in the `open()` function in `core/modules/sqlite/src/Driver/Database/sqlite/connection.php`

**Describe the solution you'd like**
People used to mysql would expect that `sql:dump` and `sql:query` would work correctly, or would provide a useful error message.

**Describe alternatives you've considered**
For my own purposes, I'll be switching to using the `.backup` and `.restore` commands within sqlite, but others would expect things to work like they do with the mysql database.

**Additional context**
Mostly recording this as I couldn't see it noted anywhere else. sqlite is now close to if not faster than mysql up to a certain size of site, and making it easier to try both would be great.

**Comment by weitzman** [comment]
Unfortunately we need query/dump to work even when Drupal is not installed yet so I don't think we can use Drupal API in them.

Related #2636
