### ISSUE TITLE
Contradictory drush upgrade instructions

### ISSUE THREAD

**Issue by sheldonrampton** [drush-ops/drush#520]
The Drupal.org instruction page on "How to Upgrade Drush" offer instructions for updating Drush using the following options:
- sudo drush dl drush
- drush self-update
- pear upgrade drush/drush

https://drupal.org/node/901828

I believe that these instructions are obsolete. None of them works on my Mac, which is currently running Drush version 6.0-dev (branch 8.x-6.x, using http://git.drupal.org/project/drush.git as its remote). They also do not work on the version of Drush on a local Vagrant box running Drush version 7.0-dev (branch master, using https://github.com/drush-ops/drush.git as the remote). When I try "sudo drush dl drush" on either my Mac or the Vagrant box, I get the following options:
- [1]  :  7.x-5.x-dev           -  2013-Sep-30  -  Development 
- [2]  :  All-versions-4.x-dev  -  2013-Sep-30  -  Development 
- [3]  :  7.x-1.x-dev           -  2013-Sep-30  -  Development

It is unclear what these options represent, since they do not appear to correspond to the version numbers or branches of Drush which appear on http://drush.ws or in any documentation that I have been able to find. Is 7.x-5.x-dev the same as Drush version 7, or is it the same as Drush version 5? My best guess is that it is Drush version 5 and that "All-versions-4.x-dev" is Drush version 4 and that 7.x-1.x-dev is some really ancient version. In any case, it appears that running "sudo drush dl drush" only offers options for downgrading to older versions of Drush, not for upgrading.

The drush.ws website is not much help, since it only displays tabs for Drush version 5, version 4 and version 3. This in turn is inconsistent with the branching and numbering information that I find if I inspect the Drush repository on Drupal.org, which shows a number of branches that seem to be tied to Drupal core release versions -- 4.7, 5.x, 6.x, 7.x, 8.x. And of course none of this is consistent with the branching information in the Github repo, which includes branches for 3.x, 4.x, 5.x, 6.x and master.

My best guess based on all of this contradictory information would be that my best bet for upgrading Drush would be to reinstall the master branch of Drush from Github following the instructions in the Github README file, and that this will set me up with Drush version 7. If this is indeed the case, then the documentation on the "How to Upgrade Drush" page on Drupal.org should be updated accordingly, as should the documentation on the drush.ws website.

I'm sure that the Drush maintainers have a lot of responsibilities, but properly maintaining your documentation is important too.

**Comment by kopeboy** [comment]
Instructions incomplete: using git pull && composer update in my .drush folder (on Mac):
**fatal: Not a git repository (or any of the parent directories): .git**

**Comment by ashishietecs** [comment]
Hi,
As per you post, i am using drush dl drush command, facing below error's

A newer version of drush, 7.x-5.9, is available.  You are currently running drush version 5.4. The update process depends on how you installed drush. Some common update commands are: `pear upgrade drush`,  `git pull`, `drush dl drush --destination=[/path/to/drush]`.  To disable this check, put "$options['self-update'] = FALSE;" in your drushrc.php configuration file.
