### ISSUE TITLE
drush make fails with array_key_exists() error with PHP 8.0

### ISSUE THREAD

**Issue by damienmckenna** [drush-ops/drush#5201]
**Describe the bug**
Updated a Drupal 7 site's ddev to use PHP 8.0 instead of 7.4. Ran `ddev drush make [makefile.yml] .` and it hits this error.

    ddev drush make --no-patch-txt ../makefile.yml .
    Beginning to build ../makefile.yml.                                                                                                                 [ok]
    PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, SimpleXMLElement given in phar:///usr/local/bin/drush8/lib/Drush/UpdateService/Project.php:205
    Stack trace:
    #0 phar:///usr/local/bin/drush8/lib/Drush/UpdateService/Project.php(205): array_key_exists('name', Object(SimpleXMLElement))
    #1 phar:///usr/local/bin/drush8/lib/Drush/UpdateService/Project.php(42):     Drush\UpdateService\Project::parseXml(Object(SimpleXMLElement))
    #2 phar:///usr/local/bin/drush8/lib/Drush/UpdateService/Project.php(102): Drush\UpdateService\Project->__construct(Object(SimpleXMLElement))
    #3 phar:///usr/local/bin/drush8/lib/Drush/UpdateService/ReleaseInfo.php(64): Drush\UpdateService\Project::getInstance(Array, 86400)
    #4 phar:///usr/local/bin/drush8/lib/Drush/UpdateService/ReleaseInfo.php(226): Drush\UpdateService\ReleaseInfo->get(Array)
    #5 phar:///usr/local/bin/drush8/commands/make/make.drush.inc(892): Drush\UpdateService\ReleaseInfo->checkProject(Array, 'core')
    #6 phar:///usr/local/bin/drush8/commands/make/make.drush.inc(957): make_prepare_projects(false, Array, 'sites/all', '.', '/var/www/html')
    #7 phar:///usr/local/bin/drush8/commands/make/make.drush.inc(320): make_projects(false, 'sites/all', Array, '.', '/var/www/html')
    #8 phar:///usr/local/bin/drush8/includes/command.inc(422): drush_make('../makefile.ym...', '.')
    #9 phar:///usr/local/bin/drush8/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
    #10 phar:///usr/local/bin/drush8/includes/command.inc(199): drush_command('../makefile.ym...', '.')
    #11 phar:///usr/local/bin/drush8/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
    #12 phar:///usr/local/bin/drush8/includes/preflight.inc(67): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
    #13 phar:///usr/local/bin/drush8/includes/startup.inc(465): drush_main()
    #14 phar:///usr/local/bin/drush8/includes/startup.inc(369): drush_run_main(false, '/', 'Phar detected. ...')
    #15 phar:///usr/local/bin/drush8/drush(114): drush_startup(Array)
    #16 /usr/local/bin/drush8(10): require('phar:///usr/loc...')
    #17 {main}
      thrown in phar:///usr/local/bin/drush8/lib/Drush/UpdateService/Project.php on line 205

**To Reproduce**
Run `drush make [makefile.yml]` on a Drupal 7 codebase while using PHP 8.0.

**Expected behavior**
It should complete the process and not fail.

**Actual behavior**
It fails.

**Workaround**
None known

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.4.8 (via ddev)
| Drupal version? | 7.91
| PHP version     | 8.0.
| OS?             | Linux inside ddev on macOS.

**Additional information**

**Comment by knezmilos** [comment]
This message is also present when running status checks on Pantheon:
TypeError: array_key_exists(): Argument #2 ($array) must be of type array, SimpleXMLElement given in array_key_exists() (line 205 of /opt/pantheon/drush/lib/Drush/UpdateService/Project.php).

**Comment by greg-1-anderson** [comment]
I recently made some fixes to Project.php, so maybe check again with HEAD of the 8.x branch.

My support of Drush Make is minimal, and limited to reviewing and merging contributions from the community.

**Comment by edvanleeuwen** [comment]
I had the same issue with 8.4.8. Updating to latest version solved this.
