### ISSUE TITLE
Add --extended option to watchdog:show-one command

### ISSUE THREAD

**Issue by gitressa** [drush-ops/drush#5202]
**Is your feature request related to a problem? Please describe.**
`drush watchdog:show --extended` works well if you want to see the entire log message, but it can become quite a wall of text.

**Describe the solution you'd like**
It would be great to be able to get the full message of a single entry by also adding the `--extended` option to `watchdog:show-one` like this:

```
$ drush watchdog:show-one 310 --extended
```

**Comment by weitzman** [comment]
Now show-one is always extended. No option needed.
