### ISSUE TITLE
Add counter for the output of chained commands

### ISSUE THREAD

**Issue by bakulahluwalia** [drush-ops/drush#5205]
Example: Current if you have multisite setup and wants to clear the cache of all the sites, you can do it by chaining them using &&. Like: `drush --uri=test1.com cr && drush --uri=test2.com cr && drush --uri=test3.com cr && drush --uri=test4.com cr && drush --uri=test5.com cr && drush --uri=test6.com cr`

Output:
Current the output looks like:
[success] Cache rebuild complete.
[success] Cache rebuild complete.
[success] Cache rebuild complete.
[success] Cache rebuild complete.
[success] Cache rebuild complete.
[success] Cache rebuild complete.

It would be nice to have counter added to the output like or however it is esier:
[success] Cache rebuild complete.(1)
[success] Cache rebuild complete.(2)
[success] Cache rebuild complete.(3)
[success] Cache rebuild complete.(4)
[success] Cache rebuild complete.(5)
[success] Cache rebuild complete.(6)

It would be awesome to have uri instead of counter like:
[success] Cache rebuild complete.(test1.com)
[success] Cache rebuild complete.(test2.com)
[success] Cache rebuild complete.(test3.com)
[success] Cache rebuild complete.(test4.com)
[success] Cache rebuild complete.(test5.com)
[success] Cache rebuild complete.(test6.com)

Some commands have really big response to it would be good to have the URI or counter to know where is it. Like:
`drush updb -y` or `drush cohesion:import` running on more than 100 sites makes the monitoring really hard.

**Comment by weitzman** [comment]
Drush isnt aware the count or the alias. Sugggest you do a `echo "start @foo" && drush @foo cr`
