### ISSUE TITLE
Watchdog: "Unknown severity level" for --severity=0

### ISSUE THREAD

**Issue by hugovk** [drush-ops/drush#5206]
**Describe the bug**

**To Reproduce**
What did you do?

```sh
drush watchdog:show --format=string --severity=2
drush watchdog:show --format=string --severity=1
drush watchdog:show --format=string --severity=0
```

**Expected behavior**
What did you expect would happen?

Output of all commands, filtered by severity.

**Actual behavior**
What happened instead?

The first two gave output but the last gave an error:

```console
wodby@php.container:/var/www/html $ drush watchdog:show --format=string --severity=2
 [notice] No log messages available.
 [notice] No log messages available.
wodby@php.container:/var/www/html $ drush watchdog:show --format=string --severity=1
 [notice] No log messages available.
 [notice] No log messages available.
wodby@php.container:/var/www/html $ drush watchdog:show --format=string --severity=0

In WatchdogCommands.php line 321:

  Unknown severity level: .
  Valid severity levels are: Emergency(0), Alert(1), Critical(2), Error(3), Warning(4), Notice(5), Info(6), Debug(7).


wodby@php.container:/var/www/html $
```

The error message says `0` is a valid level, but it causes an error.

**Workaround**
Is there another way to do the desired action?

I guess we could run with no severity flag, then repeat with levels 1-7 and try and filter those out?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.0.5
| Drupal version? | 9.4.4
| PHP version     | 8.0.16
| OS?             | Linux

**Additional information**

This is happening here, the zero value isn't being passed properly:

https://github.com/drush-ops/drush/blob/91ee2b5526f6d08b5e91056dc27eb5f542847378/src/Drupal/Commands/core/WatchdogCommands.php#L305-L311

**Comment by tyler36** [comment]
Confirmed.  I can reproduce the error with `drush watchdog:show --format=string --severity=0`

Originally, I encountered this error by using `drush wd-list`, then selecting a number (I tried 1,2,3,4,5).
A search led me to this open issue.

| Q | A|
|---|---|
|Drush version? | 11.1.1|
|Drupal version? | 9.4.5|
|PHP version | 8.0.21|
|OS? | Ubuntu 20.40 via DDEV on WSL2|

**Comment by weitzman** [comment]
The documented example for this is `--severity=Emergency` not `--severity=0`. 0 would work but I dont see a different default value for this option than our current `self::REQ`.
