### ISSUE TITLE
Fix installation instructions / process for bash completion to work

### ISSUE THREAD

**Issue by tanius** [drush-ops/drush#521]
When following the standard installation instructions in [`README.md`](https://github.com/drush-ops/drush/blob/master/README.md), bash command completion does not work for drush. (At least not on modern Ubuntu / Debian systems – Ubuntu 13.10 here.)

The problem is that the installation instructions (those for composer) propose to modify the PATH in `~/.bashrc`. However the drush autocompletion script `drush.complete.sh` already requires drush to be found on the PATH. But because it is sourced via `/etc/bash.bashrc` on Ubuntu 13.10 (at least when wanting to enable it system-wide), the PATH modification done in `~/.bashrc` is not yet in effect, so drush auto completion never gets enabled.

A (rather dirty) workaround is to include commands to source the auto-completion scripts _again_ in `~/.bashrc`, after the PATH modification is done:

    export PATH="$HOME/.composer/vendor/bin:$PATH"
    if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
      . /etc/bash_completion
    fi

(You can enable these (Ubuntu provided) three lines for auto-completion in `~/.bashrc`. But it won't work out for you if you further follow along the drush installation instructions and use the `sed` command to modify PATH, because that commands adds the PATH modification again _after_ the lines for sourcing autocompletion.)

Since the required addition to PATH is inside a user's home directory, adding it via `/etc/environment` is no clean solution either. So maybe the cleanest solution is to _not_ instruct users in [`bash.complete.sh`](https://github.com/drush-ops/drush/blob/master/drush.complete.sh) to put that file into `/etc/bash_completion.d/`. Rather, sourcing it directly from `~/.bashrc` will do the job.

That said, an option to install `drush` into a non-user-specific directory would even be a cleaner solution, and would be desirable anyway :-)

**Comment by frederickjh** [comment]
You do not want to use **which** to test with. It a very bad choice for testing if a command is present. As @mgorny stated it is not guaranteed to exist on all systems. Your test may result in true with **which** even if a command is not present. 

Please see [Check if a program exists from a bash script](
http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script) for reasons why and better ways to do it.

Here is an example from ~/.bashrc that only loads ~/.drush.bashrc if drush has been installed and the configuration file exists.

# Add some neat bash completion to drush commands
  if command -v drush >/dev/null ; then

**Comment by weitzman** [comment]
This issue is obsolete. We now have `drush init` command which sets up completion and the install docs reflect that.

1. It looks like drush.complete.sh still uses `which`. Feel free to submit a new PR which uses `command -v`.
1. In PHP, we have a wrapper for command -v: [drush_program_exists()](http://api.drush.org/api/drush/includes!filesystem.inc/function/drush_program_exists/master)

**Comment by frederickjh** [comment]
@weitzman So is the `_drush_completion()` in drush.complete.sh no longer used but `drush init` instead?

**Comment by weitzman** [comment]
Not sure. core-init command appends to user's .bashrc. That code sources
examples/example.prompt.sh which in turn calls __drush_ps1() if available.
So this may be the "safe" codepath you are looking for.

**Comment by frederickjh** [comment]
OK, Thanks for the info. It appears that in newer versions of Drush the prompt has been moved to the example.prompt.sh and is no longer in drush.complete.sh. I need to try the new prompt and see how that all works.
