### ISSUE TITLE
xdebug is gone when using drush launcher

### ISSUE THREAD

**Issue by chx** [drush-ops/drush#5210]
![2022-08-18 23_27_37-Window](https://user-images.githubusercontent.com/193045/185556957-b7db1619-c003-46f1-b35b-af968a89f232.png)

```
drush --version
Drush Launcher Version: 0.10.1
Drush Launcher Version: 0.10.1
Drush Commandline Tool 10.6.2
```

I have no idea what happened here. This used to work. Luckily running `./vendor/bin/drush` works.

**Comment by weitzman** [comment]
Sorry, this is a bit of a gotcha. See https://github.com/drush-ops/drush-launcher#xdebug-compatibility

**Comment by chx** [comment]
Please see the screenshot. I tried the environment variable.
