### ISSUE TITLE
Class "Consolidation\Log\ConsoleLogLevel" not found

### ISSUE THREAD

**Issue by mglaman** [drush-ops/drush#5213]
**Describe the bug**
Drupal 10 + Drush 11 crashes due to 

```
Error: Class "Consolidation\Log\ConsoleLogLevel" not found in Drush\Log\DrushLoggerManager->success()
```

See https://drupal.stackexchange.com/questions/311778/uncaught-error-class-consolidation-log-loglevel-not-found-in-app-vendor-con

Caused by https://github.com/consolidation/log/commit/12d16fd85830489eaf1c1cd25ae83c384e3503bb

**To Reproduce**

```
composer create-project drupal/recommended-project:^10@alpha foobar
cd foobar
composer require drush/drush
php vendor/bin/drush si
```

```
omposer why consolidation/log
consolidation/robo  4.0.0-alpha1  requires  consolidation/log (^2.0.2 || ^3)
```

**Expected behavior**
It work.

**Actual behavior**
It go boom.

**Workaround**
Manually fix consolidation/log

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.1.1
| Drupal version? | 10.0.0-alpha7
| PHP version     | 8.1.8
| OS?             | macOS
| consolidation/log | 3.0.0
| psr/log | 3.0.0

**Additional information**

**Comment by mglaman** [comment]
I've updated the config table to have consolidation/log and psr/log values.

**Comment by mglaman** [comment]
🤔 I added `"consolidation/log": ">=3"` to my `conflict`, but then Drupal 10 was downgraded to alpha5.

**Comment by greg-1-anderson** [comment]
I forgot about this. `consolidation/log` removed `Consolidation\Log\ConsoleLogLevel` in 3.x. Drush needs to stop using it that constant, and define its own `success` constant instead. I was going to make a PR, but I've been busy.

**Comment by mglaman** [comment]
I see https://www.drupal.org/project/drupal/releases/10.0.0-alpha6, this bumped to `psr/log` 3. Only `consolidation/log` allows 3 of `psr/log`

**Comment by greg-1-anderson** [comment]
Yeah, Drush adopted `consolidation/log` ^3 some time ago, but erroneously kept using the removed constant `Consolidation\Log\ConsoleLogLevel`. Drupal was holing Drush back to `consolidation/log` ^2, so no one noticed the mistake.

**Comment by greg-1-anderson** [comment]
The tests seem to pass despite the error. 🤷

**Comment by gitressa** [comment]
See also https://github.com/consolidation/log/issues/31.

**Comment by greg-1-anderson** [comment]
[278e0dc](https://github.com/drush-ops/drush/commit/278e0dc965b92b9134882f8794483d600195ed7a) does not apper to have fully resolved. See also #5247

**Comment by gitressa** [comment]
Perfect @greg-1-anderson and @weitzman, Drupal 10 now installs nicely with the new Drush `11.2.0`.
