### ISSUE TITLE
Add config:validate command

### ISSUE THREAD

**Issue by DieterHolvoet** [drush-ops/drush#5233]
**Is your feature request related to a problem? Please describe.**
Validating a Drupal config against its schema.

**Describe the solution you'd like**
The pretty much abandoned Drupal Console project has a config:validate command we could copy.

**Describe alternatives you've considered**
/

**Additional context**
The code for the Drupal Console command can be found [here](https://github.com/hechoendrupal/drupal-console/blob/master/src/Command/Config/ValidateCommand.php).

**Comment by DieterHolvoet** [comment]
@weitzman what's your opinion on this one? Seems useful to me, and the implementation very simple because we can leverage a lot of Drupal core code.

**Comment by weitzman** [comment]
I don't recall anyone ever asking for this. I'd like for a couple people to say "I have needed this" before we consider adding a new command.

**Comment by DieterHolvoet** [comment]
I just found this command already exists in the config_inspector module: https://git.drupalcode.org/project/config_inspector/-/blob/2.0.x/src/Commands/InspectorCommands.php

**Comment by weitzman** [comment]
Do you see this being used by module authors or site owners or both?

**Comment by DieterHolvoet** [comment]
I'd say module authors, site owners should rarely edit config immediately without some kind of UI. If there are issues with config schema, most of the time it will be the job of the module author to fix it.

**Comment by weitzman** [comment]
OK, lets leave this to config_inspector.
