### ISSUE TITLE
Add chain commands

### ISSUE THREAD

**Issue by DieterHolvoet** [drush-ops/drush#5235]
**Is your feature request related to a problem? Please describe.**
Drupal Console has a very interesting chain command feature:

> A chain command is a custom command that help you automate multiple command execution, allowing you to define and read an external YAML file containing the definition name, options and arguments of multiple commands and execute that list based on the sequence defined in the file.

https://drupalconsole.com/docs/en/chains/what-is-a-chain-command/

Since the Drupal Console project is basically abandoned, we could leverage their code for this feature.

**Describe the solution you'd like**
Add the same/similar functionality to Drush.

**Describe alternatives you've considered**
Until now I have declared chained commands in code using a custom trait ([example](https://github.com/consolidation/annotated-command/issues/64#issuecomment-997268439)). An approach like this, instead of declaring the command chains in YAML, would also be okay for me. The maintainers of `consolidation/annotated-command` have also shown an interest in a feature like this ([source](https://drupalconsole.com/docs/en/chains/what-is-a-chain-command/)).

**Additional context**
/

**Comment by greg-1-anderson** [comment]
I think this feature would be best added at the Robo or Annotated Command library level. Regarding syntax, I think I would favor the mixed yaml / shell syntax popular with tools like Circle CI et. al. rather than the longer form that Drupal Console used, where yaml lists are used for each option.

**Comment by weitzman** [comment]
I reopened #2943. Lets discuss there.
