### ISSUE TITLE
Drush user-cancel command blocks the user account instead of deletion

### ISSUE THREAD

**Issue by xopoc14** [drush-ops/drush#5253]
**Describe the bug**
Drush user-cancel command blocks an user account instead of deletion. For blocking users there is user-block command.

**To Reproduce**
Run `drush user-cancel username -y`

**Expected behavior**
The account is deleted, content is reassigned to the Anonymous user.

**Actual behavior**
The account is blocked.

**Workaround**
The only way to do it manually from Drupal UI.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.x/1
| Drupal version? | 9.x
| PHP version     | N/A
| OS?             | N/A

**Comment by weitzman** [comment]
Lets discuss in PR #5254
