### ISSUE TITLE
Example rsyncValidate policy command not running

### ISSUE THREAD

**Issue by jcandan** [drush-ops/drush#5257]
**Describe the bug**

The `rsyncValidate()` method is not being called with the `@hook validate core:status` annotation.

**To Reproduce**

I am able to see `sqlSyncValidate()` fire with the `@hook validate sql:sync` annotation, so I know my Drush policy file is being picked up.

When I use a debugger, I noticed that the `command` in the `$commandData` from `Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher::validate()` was for `core:status`, even though the command run was for `core:rsync`.

**Expected behavior**

I expected that the `drush core:rsync` command validation method would be run. 

**Actual behavior**
What happened instead?

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  |  10.6.2
| Drupal version? | 9.4.5
| PHP version     | 8.0.23
| OS?             | via Lando on macOS

**Additional information**

**Comment by weitzman** [comment]
rsync validate will run first, and then all the subcommands that rsync uses will run their validation as well (e.g. status). It gets tricky to follow the flow because some commands run locally and some run on the remote depending on arguments.

**Comment by jcandan** [comment]
But that’s just it: the validate hook for rsync is not being fired. I can see the the validate hook for other commands are run, but not rsync.

**Comment by weitzman** [comment]
please share the exact command you are running and the contents of each alias in that command. and the output of your run with -vvv option. thanks.

**Comment by weitzman** [comment]
Note that you may need the policy commandfile remotely depending on where the rsync runs.
