### ISSUE TITLE
Drush deploy hook counted as successful when running out of memory

### ISSUE THREAD

**Issue by benvoynick** [drush-ops/drush#5259]
**Describe the bug**
I am seeing deploy hooks marked as finished if they fatal due to lack of memory. For instance:

```
W: > >  [notice] Deploy hook started: a_deploy_hook
W: > >  [notice] Performed: a_deploy_hook
W: > >  [notice] Deploy hook started: a_big_deploy_hook
W: > >  [notice] Performed: a_big_deploy_hook
W: > > PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /app/dist/core/lib/Drupal/Core/Entity/TypedData/EntityDataDefinition.php on line 107
W: >  [success] Finished performing deploy hooks.
```

_Both_ a_deploy_hook and a_big_deploy_hook are marked are successful here. I would have expected only a_deploy_hook to be written to the database.

**To Reproduce**
Write a deploy hook that intentionally consumes vasts amounts of memory. Not sure about the most efficient way to do that, but I suppose loop while loading and/or saving nodes ad infinitum without ever breaking out of said loop.

(In my case I did use $sandbox in my a_big_deploy_hook, but I apparently have optimization problems, and hit that out of memory about halfway through a ~600 node set of updates.)

**Expected behavior**
If a deploy hook hits a fatal error for any reason, including running out of memory, I would expect it would not be marked as finished; and therefore would be run again the next time deploy:hook is called. This is how Drupal DB updates and post_updates work in my experience.

**Actual behavior**
The deploy hook was added to the list of successfully run deploy hooks, and so will not run again short of me editing the database.

**Workaround**
One can edit the key_value entry for deploy hooks, or avoid using deploy hooks. Avoiding running out of memory is always good too...

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.1.1
| Drupal version? | 9.4.3
| PHP version     | 8.0.22
| OS?             | Linux

**Additional information**
Hoping to update Core and Drush soon so I can test with the very latest, but I'm not sure relevant code has changed much in recent releases.

**Comment by weitzman** [comment]
odd. The code looks like it shouldn't do that. And I can't reproduce the problem. Perhaps someone else can. I ran the update hook below on PHP 8.1 and drush 11.x which gives a fatal TypeError. The deploy hook was not marked complete. 

```
/**
 * Failing deploy hook.
 */
function woot_deploy_failing()
{
    $a = str_contains(['dd'], ['ss']);
}
```

**Comment by benvoynick** [comment]
Apologies, I should have tested my reproduction locally and did not. That was sloppy and unhelpful of me.

Search API is in use on this site, and looking at things again this morning I see immediate indexing is turned on for the index the content type being altered. I think what may have happened to produce the output in the bug description is that the deploy hooks did both finish okay (and so were marked complete correctly), and the out of memory error came from Search API's on-kernel-destruction indexing service.

Sorry again for the wild goose chase.
