### ISSUE TITLE
Remove pm:security-php command in favor of composer audit

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#5269]
I think composer audit uses the same data set. AFAIK, Drupal contrib SAs are not in that data set so pm:security is still needed.

**Comment by weitzman** [comment]
and maybe pm:security too once https://www.drupal.org/project/project_composer/issues/3301876 is done

**Comment by prudloff-insite** [comment]
The core issue is done so `drush sec` could theoretically be removed?
