### ISSUE TITLE
Is /var/www/drush used when searching for commands?

### ISSUE THREAD

**Issue by danshumaker** [drush-ops/drush#5274]
**Existing document**
https://www.drush.org/latest/examples/ArtCommands.php/

**What are you attempting to do**
When downloading and installing different commands drush does not seem to find them.  I want to create my own drush command and have put "ArtCommands.php" in the /var/www/drush directory.  After I `drush cache-clear drush` and then `drush -vvv art`  , it says there is no such art command.

**In what way is the existing documentation unclear or incomplete**
In the ArtCommands.php example it says that in order to use the command you have to use the --include
"Run these commands using the --include option - e.g. `drush --include=/path/to/drush/examples art sandwich`" but that does not work for me `drush --include=/var/www/drush art`  still gets "Command "art" is not defined".

**What should the documentation say instead?**
I do not know what it should say because I have not been able to get it to work.    In the output below you can see that /var/www/drush is in the command search path but it does not seem to actually search it.

`
docker@cli:/var/www$ ll drush
total 24
4 -rw-r--r--  1 docker dialout 1162 Oct 13 11:53 policy.drush.inc
4 drwxr-xr-x  4 docker dialout 4096 Oct 13 13:15 contrib/
4 drwxr-xr-x 12 docker dialout 4096 Oct 13 13:15 ../
8 -rw-r--r--  1 docker dialout 5366 Oct 13 13:31 ArtCommands.php
4 drwxr-xr-x  3 docker dialout 4096 Oct 13 13:31 ./
docker@cli:/var/www$ drush --include=/var/www/drush/ art -vvv

Box Requirements Checker
========================

> Using PHP 8.1.8
> PHP is using the following php.ini file:
  /usr/local/etc/php/php.ini

> Checking Box requirements:
  ✔ The package "composer/xdebug-handler" requires the version "^5.3.2 || ^7.0 || ^8.0" or greater.
  ✔ The package "laravel-zero/phar-updater" requires the version "^7.3|^8.0" or greater.
  ✔ The package "psr/log" requires the version ">=5.3.0" or greater.
  ✔ The package "symfony/polyfill-ctype" requires the version ">=7.1" or greater.
  ✔ The package "webmozart/assert" requires the version "^7.2 || ^8.0" or greater.
  ✔ The package "webmozart/path-util" requires the version ">=5.3.3" or greater.
  ✔ The package "webflo/drupal-finder" requires the extension "json".

 [OK] Your system is ready to run the application.

 [preflight] Config paths: /var/www/vendor/drush/drush/drush.yml
 [preflight] Alias paths: /var/www/web/drush/sites,/var/www/drush/sites
 [preflight] Commandfile search paths: /var/www/vendor/drush/drush/src,/var/www/drush/,/var/www/drush
 [debug] Bootstrap further to find art [0.03 sec, 9.63 MB]
 [debug] Trying to bootstrap as far as we can [0.03 sec, 9.63 MB]
 [info] Drush bootstrap phase: bootstrapDrupalRoot() [0.03 sec, 9.63 MB]
 [info] Change working directory to /var/www/web [0.03 sec, 9.63 MB]
 [info] Initialized Drupal 9.4.8 root directory at /var/www/web [0.03 sec, 9.63 MB]
 [info] Drush bootstrap phase: bootstrapDrupalSite() [0.03 sec, 9.65 MB]
 [debug] Could not find a Drush config file at sites/default/drush.yml. [0.04 sec, 9.81 MB]
 [info] Initialized Drupal site ngaus.fin at sites/default [0.04 sec, 9.81 MB]
 [info] Drush bootstrap phase: bootstrapDrupalConfiguration() [0.04 sec, 9.81 MB]
 [debug] Add service modifier [0.04 sec, 10.02 MB]
 [info] Drush bootstrap phase: bootstrapDrupalDatabase() [0.04 sec, 10.65 MB]
 [info] Successfully connected to the Drupal database. [0.04 sec, 10.65 MB]
 [info] Drush bootstrap phase: bootstrapDrupalFull() [0.04 sec, 10.65 MB]
 [debug] Start bootstrap of the Drupal Kernel. [0.04 sec, 10.65 MB]
 [debug] Finished bootstrap of the Drupal Kernel. [0.08 sec, 18.43 MB]
 [debug] The "Sentry\Integration\FatalErrorListenerIntegration" integration has been installed. [0.11 sec, 27.74 MB]
 [debug] The "Sentry\Integration\RequestIntegration" integration has been installed. [0.11 sec, 27.75 MB]
 [debug] The "Sentry\Integration\TransactionIntegration" integration has been installed. [0.11 sec, 27.75 MB]
 [debug] The "Sentry\Integration\FrameContextifierIntegration" integration has been installed. [0.11 sec, 27.75 MB]
 [debug] The "Sentry\Integration\EnvironmentIntegration" integration has been installed. [0.11 sec, 27.75 MB]
 [debug] The "Drupal\raven\Integration\SanitizeIntegration" integration has been installed. [0.11 sec, 27.75 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\config\ConfigCommands [0.12 sec, 31.5 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\config\ConfigExportCommands [0.12 sec, 31.53 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\config\ConfigImportCommands [0.12 sec, 31.54 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\BatchCommands [0.12 sec, 31.54 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\CliCommands [0.12 sec, 31.55 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\DrupalCommands [0.12 sec, 31.55 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\DeployHookCommands [0.12 sec, 31.57 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\EntityCommands [0.12 sec, 31.58 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\LinkHooks [0.12 sec, 31.6 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\ImageCommands [0.13 sec, 31.6 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\JsonapiCommands [0.13 sec, 31.61 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\LanguageCommands [0.13 sec, 31.62 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\LocaleCommands [0.13 sec, 31.63 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\MessengerCommands [0.13 sec, 31.65 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\MigrateRunnerCommands [0.13 sec, 31.65 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\QueueCommands [0.13 sec, 31.72 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\RoleCommands [0.13 sec, 31.73 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\StateCommands [0.13 sec, 31.76 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\TwigCommands [0.13 sec, 31.77 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\UserCommands [0.13 sec, 31.78 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\ViewsCommands [0.13 sec, 31.82 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\core\WatchdogCommands [0.13 sec, 31.85 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\field\FieldCreateCommands [0.13 sec, 31.89 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\field\FieldInfoCommands [0.13 sec, 31.9 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\field\FieldDeleteCommands [0.13 sec, 31.91 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\field\FieldBaseOverrideCreateCommands [0.13 sec, 31.91 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\field\FieldBaseInfoCommands [0.13 sec, 31.92 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\pm\PmCommands [0.13 sec, 31.93 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\pm\ThemeCommands [0.13 sec, 31.94 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\sql\SanitizeCommands [0.13 sec, 31.95 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\sql\SanitizeCommentsCommands [0.13 sec, 31.95 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\sql\SanitizeSessionsCommands [0.13 sec, 31.96 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\sql\SanitizeUserFieldsCommands [0.13 sec, 31.96 MB]
 [debug] Add a commandfile class: Drush\Drupal\Commands\sql\SanitizeUserTableCommands [0.13 sec, 31.97 MB]
 [debug] Add a commandfile class: Drupal\chosen_lib\Commands\ChosenLibCommands [0.13 sec, 31.97 MB]
 [debug] Add a commandfile class: Drupal\entity_reference_revisions\Commands\EntityReferenceRevisionsCommands [0.13 sec, 31.97 MB]
 [debug] Add a commandfile class: Drupal\path_redirect_import\Commands\PathRedirectImport [0.13 sec, 31.98 MB]
 [debug] Add a commandfile class: Drupal\raven\Commands\RavenCommands [0.14 sec, 31.98 MB]
 [debug] Add a commandfile class: Drupal\search_api\Commands\SearchApiCommands [0.14 sec, 31.99 MB]
 [debug] Add a commandfile class: Drupal\search_api_solr\Commands\SearchApiSolrCommands [0.14 sec, 32.07 MB]
 [debug] Add a commandfile class: Drupal\simple_sitemap\Commands\SimplesitemapCommands [0.14 sec, 32.1 MB]
 [debug] Add a commandfile class: Drupal\token\Commands\TokenCommands [0.14 sec, 32.1 MB]
 [debug] Add a commandfile class: Drupal\webform\Commands\WebformCommands [0.14 sec, 32.11 MB]
 [debug] Add a commandfile class: Drupal\webform\Commands\WebformSanitizeSubmissionsCommands [0.14 sec, 32.19 MB]
 [debug] Add a commandfile class: Drupal\pathauto\Commands\PathautoCommands [0.14 sec, 32.19 MB]
 [debug] Done with bootstrap max in Application::bootstrapAndFind(): trying to find art again. [0.14 sec, 32.24 MB]

In Application.php line 676:

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "art" is not defined.

  Did you mean one of these?
      ard
      arr

Exception trace:
  at /var/www/vendor/symfony/console/Application.php:676
 Symfony\Component\Console\Application->find() at /var/www/vendor/drush/drush/src/Application.php:230
 Drush\Application->bootstrapAndFind() at /var/www/vendor/drush/drush/src/Application.php:186
 Drush\Application->find() at /var/www/vendor/symfony/console/Application.php:237
 Symfony\Component\Console\Application->doRun() at /var/www/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /var/www/vendor/drush/drush/src/Runtime/Runtime.php:124
 Drush\Runtime\Runtime->doRun() at /var/www/vendor/drush/drush/src/Runtime/Runtime.php:51
 Drush\Runtime\Runtime->run() at /var/www/vendor/drush/drush/drush.php:72
 require() at /var/www/vendor/drush/drush/includes/preflight.inc:18
 drush_main() at phar:///usr/local/bin/drush/bin/drush.php:143
 require() at /usr/local/bin/drush:14

`

**Comment by weitzman** [comment]
Hmm. Drush reports that it is searching there in your log `[preflight] Commandfile search paths: /var/www/vendor/drush/drush/src,/var/www/drush/,/var/www/drush`.

**Comment by danshumaker** [comment]
Right I know, so "it reports" that it is , but it clearly isn't... right? That is what we are agreeing to?  That is the conundrum.  Or are you saying that something else is wrong? Like file permissions or something.  I tried putting the ArtCommands.php in a src dir or a src/contrib dir but that didn't seem to help.
This feels like I'm missing something super basic.

**Comment by weitzman** [comment]
Try a subdir like /var/www/drush/Commands/ArtCommands.php
