### ISSUE TITLE
Upgrade to site-alias 4+ in order to remove abandoned dependency webmozart/path-util

### ISSUE THREAD

**Issue by Defcon0** [drush-ops/drush#5279]
Hello,

at the moment, consolidation/site-alias is a dependency of drush:

https://github.com/drush-ops/drush/blob/11.x/composer.json#L41

For this reason, webmozart/path-util is a "sub dependency" of drush:

https://github.com/consolidation/site-alias/blob/3.1.7/src/HostPath.php#L6

In the latest site-alias the abandoned dependency has been replaced by symfony/filesystem:

https://github.com/consolidation/site-alias/blob/4.0.0/src/HostPath.php#L6

If we could upgrade to site-alias 4.0+, we could get rid of path-util which has been started here already:

https://github.com/drush-ops/drush/issues/4935#issuecomment-1275478887

Thanks in advance!

Bye Defcon0

**Comment by weitzman** [comment]
Yes, I think we forgot to allow site-alias:^4 in PR #5278

**Comment by mikemadison13** [comment]
FYI @weitzman / @greg-1-anderson it looks like another conflict between drush and drupal/core-dev just cropped up. drupal/core-dev requires symfony/filesystem ^4.4 (and nothing in the 5.x range). i'm running into some issues with this on the 4.4.x, trying to test further (disregard previous comment, apologies missed that you still allow 4.4).

**Comment by mikemadison13** [comment]
so, it looks like this fix is only accessible if you are running the consolidation/site-alias ^4 version, which itself requires symfony/filesystem ^5 or ^6 (not ^4). so, while drush is still compatible (my bad, misspoke in previous post) you cannot use this fix without updating to a newer version of these libraries (which will make your project incompatible with drupal/core-dev). if you aren't using core-dev, no problem. if you are, you'll get stuck on the lower version of symfony/filesystem and consolidation/site-alias (so you'll still have webmozart in place).

**Comment by weitzman** [comment]
Right. The private copy of the library is how we decided to support symfony 4 users.

**Comment by mikemadison13** [comment]
@weitzman i've been traversing the issues here trying to find the private copy of the library you've mentioned. could you please point me to where / how you did that? i'd love to adopt a similar approach on blt so we don't have to re-add webmozart/path-util.

**Comment by weitzman** [comment]
The issue I'm thinking of is https://github.com/consolidation/site-alias/pull/59.

**Comment by weitzman** [comment]
I guess we didn't go with the private copy of library in the end. I misremembered that.

**Comment by mikemadison13** [comment]
hm, ok. so how does it work for people still running symfony/filesystem 4.4? it seems to me it doesn't using only drush dependencies (based on my experience with blt). obviously if i re-add webmozart/path-util then i'm good, or if i can update to symfony/file-system 5.x then i'm fine. otherwise, i'm guessing there's no path to upgrade to drush 11.3.x using the drupal/core-dev plugin?

**Comment by weitzman** [comment]
Yes, we did go with a private library for Symfony 4 users. My recall is diminishing. See https://github.com/drush-ops/drush/pull/5278/files

**Comment by greg-1-anderson** [comment]
Yeah we have a copy of Symfony Filesystem's Path class, still residing in Symfony's namespace. We load it early if `class_exists` says it doesn't already exist. `class_exist` uses the autoloader, so it will find the Symfony version if it's in your vendor.

**Comment by mikemadison13** [comment]
thanks guys
