### ISSUE TITLE
Make Drush core command classes 'final'

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#5283]
Indicate that command classes should not be extended by marking them with the final keyword. Followup to #5260

**Comment by greg-1-anderson** [comment]
Was also considering making this a requirement in the next major version of the annotated command library.

**Comment by DieterHolvoet** [comment]
I can understand why we whould make all built-in Drush commands final but I don't really see why this should be a requirement for absolutely all commands, including custom/contrib. Especially if this PR is merged: https://github.com/consolidation/annotated-command/pull/272

**Comment by greg-1-anderson** [comment]
Yeah, I agree that making command classes break if they were not final would be too inconvenient for contrib modules with Drupal commands. Maybe in the next major release of annotated commands I will be a bit more strict, but I won't require `final`.

**Comment by weitzman** [comment]
Done
