### ISSUE TITLE
Composer not installing drush on 10.1.x due to conflicts with your root composer.json require

### ISSUE THREAD

**Issue by mherchel** [drush-ops/drush#5291]
**Describe the bug**
Unable to install Drush with Drupal `10.1.x` branch

**To Reproduce**

1. Install the latest Drupal 10.1.x branch
2. `git clone --branch '10.1.x' https://git.drupalcode.org/project/drupal.git`
3. Run`composer install`
4. Attempt to install drush `composer require drush/drush` 

**Expected behavior**
Drush gets installed 🤷 

**Actual behavior**
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires drush/drush ^11.3 -> satisfiable by drush/drush[11.3.0, 11.3.1, 11.x-dev].
    - drush/drush[11.3.0, ..., 11.x-dev] require symfony/filesystem ^4.4 || ^5.4 -> found symfony/filesystem[v4.4.0-BETA1, ..., 4.4.x-dev, v5.4.0-BETA1, ..., 5.4.x-dev] but it conflicts with your root composer.json require (^6.1).
```

**Workaround**
None that I can found

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.x
| Drupal version? | 10.1.x
| PHP version     | 8.1
| OS?             | mac

**Additional information**

**Comment by gitressa** [comment]
I can confirm this, it also happens in Ubuntu 20.04 with PHP 8.1.

**Comment by weitzman** [comment]
PR in progress at #5292.

**Comment by weitzman** [comment]
Fixed and released

**Comment by mherchel** [comment]
💥 Boom!

**Comment by gitressa** [comment]
Thanks @weitzman :+1:
