### ISSUE TITLE
Fatal error: Cannot redeclare qp() 

### ISSUE THREAD

**Issue by webmasterpf** [drush-ops/drush#5294]
**Describe the bug**
When I use a drush command I get this error :
`Fatal error: Cannot redeclare qp() (previously declared in /home/XX/www/XX/sited9/vendor/querypath/querypath/src/qp_functions.php:152) in /home/XX/www/XX/sited9/vendor/arthurkushman/query-path/src/qp_functions.php on line 155`

**To Reproduce**
I deleted the original folder from Drush was executed ( Drupal 8 site) , and change it for a Drupal 9 site, using Drush 11. For that I modified the bashrc file like this:
```
# Path to Drush, added by 'drush init'.- DRUSH LAUNCHER
export PATH="$PATH:$HOME/bin/drush"
#Ajout manuel D9PF Drush
export PATH="$PATH:$HOME/www/XX/sited9/vendor/bin"
```
and put Drush launcher into  ~/bin

**Expected behavior**
Alias worked whithout error like  the one for the website mentionned into the bashrc.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.x
| Drupal version? | 9.x
| PHP version     | 8.x
| OS?             | Linux

**Comment by webmasterpf** [comment]
When I modify the bashrc like this: only one line, one that lead to drush launcher.
`export PATH="$PATH:$HOME/vendor/drush"`

I get drush working into the website directory, but outside I get:
```
The Drush launcher could not find a Drupal site to operate on. Please do *one* of the following:
  - Navigate to any where within your Drupal project and try again.
  - Add --root=/path/to/drupal so Drush knows where your site is located.
```
So how can I get drush to work from anywhere on the tree folder ? Because root is provided in the alias file.

Thanks

**Comment by weitzman** [comment]
Please use Drupal Answers for support

**Comment by webmasterpf** [comment]
If they let me post on I'll do. Just FYI, it works better on multisite installation, no need to change folder to execute commands.
