### ISSUE TITLE
How to declare multiple drush.services.yml files in one composer.json

### ISSUE THREAD

**Issue by mstenta** [drush-ops/drush#5297]
**Existing document**

https://www.drush.org/latest/commands/#specifying-the-services-file

**What are you attempting to do**

In some cases, a single project with a single `composer.json` file may have multiple sub-modules, each providing their own Drush commands and `drush.services.yml` files. How should this be handled in the project's root `composer.json` file?

Two scenarios where this happens:

1. Modules that have sub-modules.
2. Distributions that include modules.

Specifically, I am curious how to solve this for (2) in the farmOS distribution, where we have two different modules that provide Drush commands:

- https://github.com/farmOS/farmOS/blob/2.x/modules/core/migrate/drush.services.yml
- https://github.com/farmOS/farmOS/blob/2.x/modules/core/update/drush.services.yml

And here is the distro's `composer.json`: https://github.com/farmOS/farmOS/blob/2.x/composer.json

**In what way is the existing documentation unclear or incomplete**

It is unclear how to handle the above situation.

**What should the documentation say instead?**

TBD (and happy to open a PR once I understand!)

**Comment by weitzman** [comment]
The expectation is that you have a composer.json in each directory (migrate and update). Its OK if the composer.json has nothing in it except for the drush line.

**Comment by mstenta** [comment]
Ah thanks @weitzman! I'll give that a try and contribute some language back to the docs if it seems like it would be helpful to others.

**Comment by mstenta** [comment]
Confirmed that adding minimal `composer.json` files to the sub-module directories works!

Here is a PR that adds a bit of language to the docs to describe this: https://github.com/drush-ops/drush/pull/5312
