### ISSUE TITLE
Cannot clear `cache.container` to invalidate container definition

### ISSUE THREAD

**Issue by mglaman** [drush-ops/drush#5300]
**Describe the bug**
I wanted to invalidate the container cache quickly and tried `cc bin` but it failed, possible because it's only defined in the bootstrap container

**To Reproduce**
Run `drush cc bin cache.container`

**Expected behavior**
Container cache destroyed and gets rebuilt

**Actual behavior**
```
You have requested a non-existent service "cache.container". Did you mean this: "cache.config"? 
```

**Workaround**
```
drush sql:query "TRUNCATE cache_container;"
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.6.2
| Drupal version? | 9.4.8
| PHP version     | 7.4
| OS?             | Mac/Linux

**Additional information**

**Comment by weitzman** [comment]
You can see the list of supported bins by omitting the last argument - `drush cc bin`. That list comes from Drupal's `Cache::getBins()`. 

I think we need to create another cache type for this. I've done that in #5304

**Comment by mglaman** [comment]
You're amazing, thank you! I figured it'd need to be a pseudo bin since it only exists in the bootstrap container definition.
