### ISSUE TITLE
Drush updatedb error code 0

### ISSUE THREAD

**Issue by dpagini** [drush-ops/drush#5306]
**Describe the bug**
The `$ drush updatedb` command will output an error, but return exit code 0.

**To Reproduce**
1. Install a site from scratch. Include a "random contrib module" and install that module.
1. Remove the "random contrib module" from the codebase.
1. Run `$ drush updb; echo $?` command.

**Expected behavior**
Observe the error printed to the screen with the return code of 1.

**Actual behavior**
Observe a printed error to the screen, and the echo command tells you the return code was 0.

**Workaround**
N/a

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.2.1
| Drupal version? | 9.4.8
| PHP version     | 7.4
| OS?             | Linux

**Additional information**
![image](https://user-images.githubusercontent.com/1724163/200909948-536361a7-e81f-40fd-8ff8-d32b358f25e3.png)

**Comment by weitzman** [comment]
Requirements errors don't stop updatedb as per https://github.com/drush-ops/drush/issues/3316. Non interactive installs like this one could default to stopping in next major version (PR welcome).
