### ISSUE TITLE
STDERR constant not available in Logger.php

### ISSUE THREAD

**Issue by damienmckenna** [drush-ops/drush#5313]
**Describe the bug**
Clearing the caches on a D7 site has started logging the following:

    Error: Undefined constant "Drush\Log\STDERR" in Drush\Log\Logger->log() (line 148 of /home/myaccount/drush/lib/Drush/Log/Logger.php).

The command also returns a 500 response.

**To Reproduce**
Run the following command:

    PATH=/bin:/usr/local/bin:/usr/bin /home/myaccount/drush/drush --root=/home/myaccount/public_html cc all

**Expected behavior**
The caches are cleared as expected.

**Actual behavior**
The command returns a 500 error.

**Workaround**
n/a

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.x branch
| Drupal version? | 7.92
| PHP version     | 8.0.25
| OS?             | Linux

**Additional information**
The problem doesn't happen when I "cd" to the website directory and directly run "drush cc all", it only happens when I use the verbose command above.

**Comment by damienmckenna** [comment]
The Drush codebase was a few months old, I updated it and the problem does not happen.

**Comment by damienmckenna** [comment]
Actually the problem persists.

**Comment by damienmckenna** [comment]
The problem doesn't happen when I "cd" to the website directory and directly run "drush cc all", it only happens when I use the verbose command above.

**Comment by damienmckenna** [comment]
I narrowed down the problem to the PATH definition used with the command. This command comes from a crontab, hence needing to define the PATH. I compared the normal path when logged in via ssh and was able to make it work, so I think there's an old version of a command available from one of the system paths that's conflicting with a command it wants from another path.

**Comment by damienmckenna** [comment]
I was able to fix this by setting the path in crontab as follows:

    PATH=/home/myaccount/drush:/usr/local/bin:/usr/bin

(fyi /home/myaccount/drush is where I've installed Drush 8 for this account)

Then the Drush commands work correctly. *shrug*

**Comment by greg-1-anderson** [comment]
Perhaps Drush was being run from the php-cgi or php-fpm, rather than php-cli.

**Comment by damienmckenna** [comment]
It might have been picking up a different "php" binary from a different path, I can't rule that out.
