### ISSUE TITLE
Which version is recommended for Drupal 10 / PHP 8.1

### ISSUE THREAD

**Issue by SirClickALot** [drush-ops/drush#5319]
I am developing a Drupal 10 site based on PHP 8.1 and I am currently using DRUSH 10. I get quite a lot of 'deprecation' related errors and warnings which don't stopnit working but I would like to try to remove them if I can.

Should I update to DRUSH 11?

Can I also use DRUSH 11 for a Drupal 9 site too?

Thanks

**Comment by gitressa** [comment]
You should use Drush 11, since Drush 10 reached End Of Life January 2022.

You can see the recommended versions here: https://www.drush.org/latest/install/#drupal-compatibility

**Comment by gitressa** [comment]
I created an MR which adds Drupal 10 to the list: https://github.com/drush-ops/drush/pull/5320.
