### ISSUE TITLE
user:create and user:password don't recognize password starting with ! character

### ISSUE THREAD

**Issue by marciuz** [drush-ops/drush#5324]
**Describe the bug**
The bug appears when creating a user with user:create, but also replacing the password with user:password does not work if the password starts with a characteristic dollar ('$'). For example, the password '$foobar12345', a normally acceptable password, does not work. Conversely, "£foobar12345" or ".foobar12345" or apparently any other first character, seems to work. 
Perhaps Drush tries to interpret the parameter as a variable? 

**To Reproduce**
drush user:create your.user --mail="your.user@email.com" --password="$foobar12345" 

**Expected behavior**
The password should be correctly registered.

**Actual behavior**
The password is not assigned or changed.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.2.1
| Drupal version? | 9.x
| PHP version     | 8.x
| OS?             | Linux

**Comment by gitressa** [comment]
This looks more like a command line issue ... I can't create a folder with a dollar sign in it, unless I escape it:

```
$ mkdir "testing$test"
$ ls | grep testing
4,0K Nov 28 15:47 testing

$ mkdir "testing\$test"
$ ls | grep testing
4,0K Nov 28 15:47 testing
4,0K Nov 28 15:47 testing$test
```

**Comment by marciuz** [comment]
Yes, I agree.
Probably we can close the issue.

Thank you

Il lun 28 nov 2022, 15:50 gitressa ***@***.***> ha scritto:

**Comment by gitressa** [comment]
Thanks. Just out of curiosity, I tried updating the password with this, after which I could log in with `$foobar12345`:

`drush user:password your.user "\$foobar12345"`

These characters also work, if I set the password with this:
```
\$\`\"\\foobar12345
```
... I can log in with:
```
$`"\foobar12345
```

Setting pw with `\!foobar12345` and logging in with `!foobar12345` doesn't work , though so it looks like defining a password containing an exclamation mark is not possible ...

EDIT: It's because the password is set to `\!foobar12345`, which is a bit inconsistent, since these characters usually require to be escaped, to be used as normal characters on the command line:

```
$
`
"
\
!
```

So it's not possible to set exclamation as part of a password: 
```
$ drush user:password your.user "!foobar12345"
bash: !foobar12345: event not found
```

**Comment by marciuz** [comment]
Curious. Any idea about the reason?

Il lun 28 nov 2022, 19:38 gitressa ***@***.***> ha scritto:

**Comment by gitressa** [comment]
Sorry,  but I don't ... 

Trying to set pw to `f!oobar12345` gives the same "event not found" error, so maybe we can reopen this issue, but change title to "user:create and user:password don't recognize password containing ! character"?

**Comment by marciuz** [comment]
Yes, of course.
But are you sure it isn't another shell-related issue?

Il giorno mar 29 nov 2022 alle ore 09:20 gitressa ***@***.***>
ha scritto:

**Comment by gitressa** [comment]
Ah yes, you are right:

> Strings in single quotes are not expanded by bash.

From https://superuser.com/questions/133780/in-bash-how-do-i-escape-an-exclamation-mark

And indeed, `drush user:password your.user '!foobar12345'` is accepted.

Perhaps you can create a merge request and update the example? From:
```
Examples: 
drush user:password someuser "correct horse battery staple"
```

To:
```
Examples: 
drush user:password someuser 'correct horse battery staple'
```

Full help message:
```
$ drush user:password -h
Set the password for the user account with the specified name.

Examples:
 drush user:password someuser "correct horse battery Set the password for the username someuser. See 
staple"                                              https://xkcd.com/936                            

Arguments:
 name     The name of the account to modify. 
 password The new password for the account.  

Global options:
-v|vv|vvv, --verbose Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for 
                     debug                                                                                        
-y, --yes            Auto-accept the default for all user prompts. Equivalent to --no-interaction.                
-l, --uri=URI        A base URL for building links and selecting a multi-site. Defaults to                        
                     https://default.                                                                             
                     To see all global options, run `drush topic` and pick the first choice.                      

Aliases: upwd, user-password

```

**Comment by gitressa** [comment]
I created an MR: #5326.
