### ISSUE TITLE
Using specific php version for updatedb command

### ISSUE THREAD

**Issue by uniquename** [drush-ops/drush#5331]
**Describe the bug**
When using a specific php version for drush to call the updatedb command it fails with 

```
The command "..... vendor/bin/drush updatedb:status --no-entity-updates --strict=0 --uri=de
    fault --root=/path/to/drupal/root
    22/web" failed.

    Exit Code: 255(Unknown error)

    Working directory:

    Output:
    ================


    Error Output:
    ================
    Composer detected issues in your platform:

    Your Composer dependencies require a PHP version ">= 8.0.0". You are runnin
    g 7.4.28.
```

**To Reproduce**

Call `/usr/bin/php8.1 vendor/bin/drush updatedb` on the command line

**Expected behavior**

That it works, like all the other commands that could be called this way

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.6.2
| Drupal version? | 9.4
| PHP version     | 8.x/7.x
| OS?             | Linux

**Comment by weitzman** [comment]
Adjust your PATH for all requests or just one. See the _Note_ about non-default PHP at https://www.drush.org/latest/install/
