### ISSUE TITLE
Inform the user when database updates have warnings

### ISSUE THREAD

**Issue by pfrenssen** [drush-ops/drush#5335]
**Is your feature request related to a problem? Please describe.**
It is possible that a database update from a module cannot be executed. For example if the module's schema version is from a previous version of Drupal, or when a module uses the update hook number `_8000` which is reserved for the major D7 > D8 update.

In this case `update_get_update_list()` will return a warning for the offending module, rather than the usual `start` key that indicates the first update that can be executed.

In the Drupal core `update.php` page these warnings are shown to the end user before they start the update procedure:

![image](https://user-images.githubusercontent.com/442924/207344679-399339d5-c640-4631-9195-082290eb8774.png)

We should probably do the same.

On a side note, when a module update has a warning, the missing "start" array key throws a warning:

> [warning] Undefined array key "start" UpdateDBCommands.php:456

**Describe the solution you'd like**
Show the warnings to the user. The best solution would be to show them as part of the `drush update:status` command. The output of this command is shown before the user is asked for confirmation to execute the updates.

**Comment by gitressa** [comment]
Thanks for fixing and committing this so fast @pfrenssen and @weitzman, impressive.
