### ISSUE TITLE
Changed `pm:uninstall` in v. 11.4.0 breaks BLT pipeline

### ISSUE THREAD

**Issue by imonroe** [drush-ops/drush#5340]
**Describe the bug**
The change in https://github.com/drush-ops/drush/pull/5293 means that an exception gets thrown if there is a request to uninstall a module which isn't currently installed.

That exception breaks pipelines that include the `blt toggle:modules` command, which we use in our CI/CD pipeline to uninstall modules which are not needed for our tests.  That command is being provided by: https://github.com/shelane/toggle-modules 

Prior to this change, no exception was thrown if the module wasn't there.  With the exception, our application won't complete building in our tests, so our tests always fail.

**To Reproduce**
Using drush 11.3.2, try to uninstall a module that isn't installed: `drush pm:uninstall`.  You get a success message, which makes sense.  Either the module was never installed, or it's uninstalled now.

Using drush 11.4.0, try the same thing.  You now get an Exception, which, if used in a build pipeline, will result in the build failing.

**Expected behavior**
I expected our build system to continue building, even if the module was not installed.

**Actual behavior**
Builds all failed.

**Workaround**
Is there another way to do the desired action?

Not in our case.  We have a complicated pipeline that requires a number of different modules in different environments.  Our short term solution is to lock drush at v 11.3.2.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.4.0
| Drupal version? | 9.4.x
| PHP version     | 8.1
| OS?             | Linux

**Comment by weitzman** [comment]
We never declared that it was OK to pass modules that are already uninstalled. So thats why this bug fix is eligible for a minor release. You'll want to adjust your build/dependancy to be more precise.
