### ISSUE TITLE
How to create a Drush command inside a theme?

### ISSUE THREAD

**Issue by gitressa** [drush-ops/drush#5343]
**What are you attempting to do**
I tried to add a Drush command inside a theme, adapting [Creating Custom Drush 9 Commands in Drupal 8](https://www.droptica.com/blog/creating-custom-drush-9-commands-drupal-8/) to get a starting point, without success.

I searched a bit, and found [Creating Drush commands inside a theme](https://kporras07.com/blog/creating-drush-commands-inside-theme), which seems complicated to me, so I hope the process has been made simpler since the blog post from June 2020. Is it documented somewhere how create a Drush commands inside a theme?

**Comment by weitzman** [comment]
If you just need it to work on your site it may work amid you follow https://www.drush.org/latest/commands/#auto-discovered-commands. You would also need a class declaration in your sites composer.json. 

Or try the configuration approach in the section above that link.

**Comment by gitressa** [comment]
Thanks, but sadly, this Drush command has to be implemented directly in the theme, to be self-contained ... I found an example of a custom Drush command in the [CivicTheme Drupal theme](https://github.com/salsadigitalauorg/civictheme):

https://github.com/salsadigitalauorg/civictheme/blob/master/src/Drush/Commands/CivicthemeCommands.php

It seems like all that is needed is that file, and then use it by specifying the path, like this:

`drush --include=docroot/themes/contrib/civictheme/src/Drush civictheme:clear-cache`

**Comment by weitzman** [comment]
--include should work. good call.
