### ISSUE TITLE
Drush command terminated abnormally

### ISSUE THREAD

**Issue by adminko71** [drush-ops/drush#5346]
**To Reproduce**
Run drush status

**Describe the bug**
When run whatever drush command i get the error message below:

`PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\Console\shell_exec() in /home/username/public_html/PDT/vendor/symfony/console/Application.php:989`

`Stack trace:`

`#0 /home/username/public_html/PDT/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()`

`#1 /home/username/public_html/PDT/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()`

`#2 /home/username/public_html/PDT/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run()`

`#3 /home/username/public_html/PDT/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun()`

`#4 /home/username/public_html/PDT/vendor/drush/drush/drush.php(77): Drush\Runtime\Runtime->run()`

`#5 /home/username/public_html/PDT/vendor/drush/drush/drush(4): require('/home/username/...')`

`#6 /home/username/public_html/PDT/vendor/bin/drush(120): include('/home/username/...')`

`#7 {main}
  thrown in /home/username/public_html/PDT/vendor/symfony/console/Application.php on line 989`

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.4
| Drupal version? | 10.0.0
| PHP version     | 8.1.13
| OS?             | Linux

**Comment by weitzman** [comment]
Your php is insufficient as per the error message. This is a requirement of symfony console not drush.

**Comment by weitzman** [comment]
Please use Drupal Answers for support
