### ISSUE TITLE
Add command to unban IP address (from Core ban module)

### ISSUE THREAD

**Issue by JPustkuchen** [drush-ops/drush#5348]
**Is your feature request related to a problem? Please describe.**
The Drupal core "ban" module ([admin/config/people/ban](https://ddev-vscode-devcontainer-drupal-template.ddev.site/admin/config/people/ban)) allows to ban IP's. Cobtrib Modules like login_security or autoban utilitize this to automatically ban users based on certain attack detection rules.

Sadly there's no drush command to unban an IP or clear the ban table from drush.

Especially if you're banned as administrator and can't access the admin UI anymore, that would be super helpful

**Describe the solution you'd like**
Add `unban-ip` and `unban-all` (flush) commands.

**Comment by gitressa** [comment]
A workaround until this is implemented could be running sql commands:

```
$ drush sql:query "TRUNCATE ban_ip;"
$ drush sql:query "DELETE FROM ban_ip WHERE ip='100.100.0.0';"
```

**Comment by weitzman** [comment]
Due to niche usage of ban, I'd prefer these commands not live in core drush.

**Comment by gitressa** [comment]
The commands to unblock a user or IP-address were also added to https://www.drupal.org/docs/extending-drupal/contributed-modules/contributed-module-documentation/ban/ban-module-overview.

**Comment by JPustkuchen** [comment]
Yes, we've solved this in ban! Thanks

**Comment by gitressa** [comment]
Very cool! I wasn't aware that the Ban module had progressed so much as a contrib module, with new features both in the GUI and Drush. `cr` is progressing very nicely (thank you @weitzman!) and I created an issue:

- [Add dr support in Ban](https://www.drupal.org/project/ban/issues/3606943)

**Comment by gitressa** [comment]
@weitzman: @JPustkuchen asked this question in [Add dr support in Ban](https://www.drupal.org/project/ban/issues/3606943):

> IMHO dr and drush should simply be able to use the same commands instead of implementing that twice. Does such a plan exist?

Perhaps you know if there is documentation or an issue about adding `dr` integration in a contrib modules?
