### ISSUE TITLE
Lock option for aliases for sql-sync/rsync

### ISSUE THREAD

**Issue by pixiekat** [drush-ops/drush#5349]
**Is your feature request related to a problem? Please describe.**
When using sql-sync, it's possible to accidentally sync from dev to production instead of the other way around, which would, obviously, be bad.  I know there are confirmations but sometimes you look quickly and get mixed up. A failsafe would be great, especially in environments with multiple devs.

**Describe the solution you'd like**
Adding a simple key to the alias file to lock an alias from being the destination from rsync or sql-sync. So when you do drush sql-sync @dev @prod, it would fail with an error message. Something like:

```yml
prod:
  extra:
    production: true
    locked: true
```

**Describe alternatives you've considered**
Using sql-sync without "-y" does present a confirmation but with so much text, it's sometimes easy to misread things.

**Comment by weitzman** [comment]
Recommendation is to use a policy file. It can look for locked or whatever you'd like. See policy link in the atopic section of https://www.drush.org/latest/commands/sql_sync/. There an example policy file there.

**Comment by pixiekat** [comment]
Thank you! I did some searching but didn't come across anything. Will look today!
