### ISSUE TITLE
deprecated function drush_mkdir()

### ISSUE THREAD

**Issue by j-dobr** [drush-ops/drush#5350]
Here https://github.com/drush-ops/drush/blob/11.x/includes/filesystem.inc#L102 is function `drush_mkdir()` marked as deprecated. It seems to me that it was deprecated before its implementations was changed to use `\Symfony\Component\Filesystem`, and thus the deprecation should be removed now. 

Or does that deprecation mean that other modules using drush are supposed to use \Symfony\Component\Filesystem directly instead of Drush implementation?

**Comment by greg-1-anderson** [comment]
Yes; the ultimate goal for Drush is to remove most-to-all of the procedural utility functions in favor of class-based APIs. In cases where a class-based API is available from another provider, e.g. Symfony Filesystem, that is preferred over a Drush-specific API.
