### ISSUE TITLE
Upload build asset in the Github release - Nix integration

### ISSUE THREAD

**Issue by drupol** [drush-ops/drush#5366]
Hello,

I'm Pol, a PHP maintainer in the NixOS community... long time no see Drupal!

I notice that the `drush` [package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/misc/drush/default.nix) in Nix is quite old(8.4.11).
Since software are automatically updated by a robot scanning outdated version in the `nixpkgs` tree, I was wondering why it stopped being updated automatically.
I think I just discovered the issue. The release 8.4.11 is the latest release where the phar file was provided as a release asset. Since then, nothing... and this is why it doesn't get updated in Nix.

So, I'm re-opening this issue to know if it would be possible to attach the drush phar at each release again so it could be automatically updated in Nix.

Let me know what you think about this.

Thanks.

**Comment by greg-1-anderson** [comment]
I can look into that, but please note that Drush 8 itself is quite old; the latest version of Drush is version 11, which does not include a phar because it is installed via Composer.

**Comment by drupol** [comment]
Oh, then if I understand correctly, installing drush using a phar is no more recommended ?

**Comment by weitzman** [comment]
Correct.
