### ISSUE TITLE
Allow to prevent drush from registering itself as a log subscriber

### ISSUE THREAD

**Issue by Berdir** [drush-ops/drush#5367]
Follow-up of https://github.com/drush-ops/drush/issues/4074.

What we need IMHO is an ability to tell drush to not subscribe to log messages, then the problem described in that issue shouldn't appear. Something like --no-log-output? I don't want to hide _all_ error output, just logged drupal errors.

Looking at \Drush\Drupal\DrushLoggerServiceProvider, I think that can't be done at runtime as it's part of the container, so it would need to be an explicit check in \Drush\Log\DrushLog itself.

My specific context is a custom command of the monitoring project, where running our sensors can sametimes trigger error logs, but that shouldn't break the parsing JSON output. I'll see if I can work around there by reinitializing the logger factory but that's pretty ugly. Looking at \Consolidation\Log\Logger::log, we might also be able to set the output verbosity all the way down while executing our sensors and then restoring it for the regular output.

**Comment by weitzman** [comment]
Not sure if it will help, but I did some work to let sites add or replace our logger. See https://github.com/drush-ops/drush/pull/5022/files#diff-99d5f4f635c30767edca2077f00a804bec2c283565da05f4a864e9d45295d690R37-R56. That example adds a logger but there is a remove() method as well.

**Comment by weitzman** [comment]
I can reopen if needed.
