### ISSUE TITLE
Set SQL transaction level for new sites

### ISSUE THREAD

**Issue by AdamPS** [drush-ops/drush#5369]
**Is your feature request related to a problem? Please describe.**
Drupal [recommends a change](https://www.drupal.org/docs/system-requirements/setting-the-mysql-transaction-isolation-level) to the SQL transaction level. 

**Describe the solution you'd like**
Drush should apply this change when creating new sites. Probably it lives at the end of `SqlMysql::createdbSql()`.

**Describe alternatives you've considered**

**Additional context**

**Comment by weitzman** [comment]
I don't think we want Drush to change the global state of the mysql server with `SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED`. So we are down to the settings.php changes recommended in that link, which are best done by a human or the Drupal installer. So I don't think there is anything to do here for Drush.

**Comment by AdamPS** [comment]
Thanks for the reply.

>  I don't think we want Drush to change the global state of the mysql server

Not even from site:install?? It would be useful if site install could match the Drupal recommended installation.

**Comment by weitzman** [comment]
1. There could other DBs on the mysql server
2. Not sure the current user will have enough mysql perms to set it.

**Comment by AdamPS** [comment]
> 1. There could other DBs on the mysql server

This command affects only the newly created database.
 
>     2. Not sure the current user will have enough mysql perms to set it.

That's why I suggested adding to `SqlMysql::createdbSql()` which runs as the root user.

**Comment by AdamPS** [comment]
> This command affects only the newly created database.

Or maybe I'm wrong sorry. I just ran the command for one site and the next one didn't need fixing.

**Comment by AdamPS** [comment]
Sorry I read the docs more closely and you are right.
