### ISSUE TITLE
installing drush before drupal/core-dev breaks the project

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#5372]
**Describe the bug**

Installing Drush with composer on a fresh site causes a subsequent attempt to install drupal/core-dev to fail.

**To Reproduce**

I installed Drupal 9, then drush:

```
composer create-project drupal/recommended-project:^9  drupal-contrib
composer require drush/drush
composer require drupal/core-dev // fails because of https://www.drupal.org/project/drupal/issues/3163114
composer require drupal/core-dev ^9 // fails
composer require -W drupal/core-dev ^9 // also fails
```

The last command fails with:

```
  Problem 1
    - drupal/core-dev[9.0.0, ..., 9.5.2] require symfony/filesystem ^4.4 -> found symfony/filesystem[v4.4.0, ..., v4.4.42] but the package is fixed to v5.4.19 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires drupal/core-dev ^9 -> satisfiable by drupal/core-dev[9.0.0, ..., 9.5.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

I don't understand why Composer won't downgrade filesystem, as everything that requires it is ok with ^4:

```
symfony/filesystem v5.4.19 Provides basic utilities for the filesystem
├──chi-teck/drupal-code-generator 2.6.2 (requires symfony/filesystem ^4.4 || ^5.1 || ^6)
│  └──drush/drush 11.4.0 (requires chi-teck/drupal-code-generator ^2.4)
│     ├──drupal/recommended-project (requires drush/drush ^11.4)
│     └──drupal/core 9.5.2 (conflicts drush/drush <8.1.10) (circular dependency aborted here)
├──consolidation/robo 4.0.2 (requires symfony/filesystem ^4.4.9 || ^5 || ^6)
│  └──drush/drush 11.4.0 (requires consolidation/robo ^3.0.9 || ^4.0.1)
│     ├──drupal/recommended-project (requires drush/drush ^11.4)
│     └──drupal/core 9.5.2 (conflicts drush/drush <8.1.10) (circular dependency aborted here)
├──consolidation/self-update 2.0.5 (requires symfony/filesystem ^2.5 || ^3 || ^4 || ^5 || ^6)
│  └──consolidation/robo 4.0.2 (requires consolidation/self-update ^2.0)
│     └──drush/drush 11.4.0 (requires consolidation/robo ^3.0.9 || ^4.0.1)
│        ├──drupal/recommended-project (requires drush/drush ^11.4)
│        └──drupal/core 9.5.2 (conflicts drush/drush <8.1.10) (circular dependency aborted here)
├──consolidation/site-alias 4.0.0 (requires symfony/filesystem ^5.4 || ^6)
│  ├──consolidation/site-process 4.2.1 (requires consolidation/site-alias ^3 || ^4)
│  │  └──drush/drush 11.4.0 (requires consolidation/site-process ^4.1.3 || ^5)
│  │     ├──drupal/recommended-project (requires drush/drush ^11.4)
│  │     └──drupal/core 9.5.2 (conflicts drush/drush <8.1.10) (circular dependency aborted here)
│  └──drush/drush 11.4.0 (requires consolidation/site-alias ^3.1.6 || ^4)
│     ├──drupal/recommended-project (requires drush/drush ^11.4)
│     └──drupal/core 9.5.2 (conflicts drush/drush <8.1.10) (circular dependency aborted here)
└──drush/drush 11.4.0 (requires symfony/filesystem ^4.4 || ^5.4 || ^6.1)
   ├──drupal/recommended-project (requires drush/drush ^11.4)
   └──drupal/core 9.5.2 (conflicts drush/drush <8.1.10) (circular dependency aborted here)
```

**Expected behavior**
What did you expect would happen?

**Actual behavior**
What happened instead?

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.x/10.x/8.x (please be specific, and try latest release)
| Drupal version? | 10.x/9.x/8.x/7.x
| PHP version     | 8.x/7.x
| OS?             | Mac/Linux/Windows

**Additional information**

**Comment by weitzman** [comment]
I see `consolidation/site-alias 4.0.0 (requires symfony/filesystem ^5.4 || ^6)` in your output. I think site-alas:3 is the one that works with filesystem:4. Maybe delete all of vendor and retry.

**Comment by joachim-n** [comment]
I did `composer remove drush/drush` and then installed drupal/core-dev, followed by drush, and it worked.

I don't know if this is something to fix in drush or in composer, but it's pretty confusing to manage to break a fresh project in only 3 commands!

**Comment by greg-1-anderson** [comment]
The problem is that Drush allows `consolidation/site-alias` at `^3.1.6 || ^4`, so you get 4.0.0 when you install Drush first. `consolidation/site-alias` needs symfony/filesystem `^5.4 || ^6`, but, since `consolidation/site-alias` isn't a dependency of `drupal/core-dev`, `-W` isn't enough to persuade Composer that it should try to downgrade it in order to enable the downgrade of symfony/filesystem.

**Conclusion:** Composer is freakin hard to use.

**Potential Solution:** Loosen the constraints on `consolidation/site-alias` to allow symfony/filesystem ^4. There might be PHP version issues with doing this; API changes should be minimal-to-none. PR's welcome if it works. Adding Drush first is likely to break another way for a similar reason again in the future, though, so is it worth chasing our tail on this one?

**Recommended Strategy:** Composer works best if you install projects with highly specific dependencies, like `drupal/core-dev` *before* projects like `drush/drush` that have loose dependencies that allow it to work in a lot of different environments.

**Comment by gitressa** [comment]
See also #4385 and [drupal/core-dev install fails if drush/drush already installed](https://www.drupal.org/project/drupal/issues/3123013).
