### ISSUE TITLE
Drush configuration files should have the *.yml extension in all places

### ISSUE THREAD

**Issue by pompetardo** [drush-ops/drush#5373]
I'm not sure why drush configuration files are expected to not have the *.yml extension in some places. According to https://www.drush.org/latest/using-drush-configuration/ in "2. sites/all/drush, WEBROOT/drush, or PROJECTROOT/drush".

If I put a symlink named "drush" in the root of the project to avoid writing "vendor/bin/drush", drush goes bananas and tries to parse the PHP file as if it were a YAML one. This happened to me with drush 11.4  and Drupal 10. The error doesn't happen in Drupal 9 because in Symfony 4, the YAML parser apparently, just makes a deprecation warning instead of throwing a ParseException. The warning is never shown but written in the code, which is just a happy coincidence. (vendor/symfony/yaml/Parser.php, Drupal10: line 451, Drupal9: line 458)

I'm a newbie so it took me a while to get what was happening. I modified the vendor/symfony/yaml/Parser.php file to traceback the calls and the problem is in vendor/drush/drush/src/Config/ConfigLocator.php line 275:
`$this->addConfigPaths(self::DRUPAL_CONTEXT, [ dirname($siteRoot) . '/drush', "$siteRoot/drush", "$siteRoot/sites/all/drush" ]);`
I think this should be:
`$this->addConfigPaths(self::DRUPAL_CONTEXT, [ dirname($siteRoot) . '/drush.yml', "$siteRoot/drush.yml", "$siteRoot/sites/all/drush.yml" ]);`

**Comment by weitzman** [comment]
The are expected to have .yml always. 

> sites/all/drush, WEBROOT/drush, or PROJECTROOT/drush

Those are dir names, not filenames.
