### ISSUE TITLE
sql:query auto runs --file-delete

### ISSUE THREAD

**Issue by ebricca** [drush-ops/drush#5377]
**Describe the bug**
when I issue a "drush sql:query --file=dump.sql.gz" it runs the subroutine --file-delete even tough it is not set.

**To Reproduce**
run "drush sql:query --file=dump.sql.gz"
dump.sql.gz gets deleted

**Expected behavior**
not to run --file-delete when it is unset

**Actual behavior**
deletes the sql.gz input file

**Workaround**
not to use sql:query but sql:cli
'gunzip < dump.sql.gz | vendor/bin/drush sql:cli'

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.4.0
| Drupal version? | 10.1
| PHP version     | 8.1
| OS?             | Linux

( was on docker php:8.1-apache-bullseye / drush installed via composer )

**Comment by weitzman** [comment]
I can't reproduce this. What DB are you using?
