### ISSUE TITLE
Error getting a state that contains an Array - Array to string conversion TsvFormatter.php:35 Drush11/PHP 8.1

### ISSUE THREAD

**Issue by reece-oliver** [drush-ops/drush#5378]
**Describe the bug**
Using Drush 11 on PHP 8.1 and try running a state:get command that stores an array I get this error

```
drush state:get site.sync_errors
[warning] Array to string conversion TsvFormatter.php:35
Array
````

Works fine as json, something just needs updating in the TsvFormatter

```
drush state:get site.sync_errors --format=json
{
    "site.sync_errors": []
}
```

**To Reproduce**
What did you do?
Add a state that stores an array

**Expected behavior**
What did you expect would happen?
Should print the array or nothing if its empty

**Actual behavior**
What happened instead?
Errors and only prints the word 'Array`
**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.4.0
| Drupal version? | 10.0.3
| PHP version     | 8.1.15
| OS?             | Linux

**Additional information**

**Comment by weitzman** [comment]
The tab separated values formatter, like a couple others, only handles scalar values properly. Thats by design, and is a natural limitation of those formats. The value here is an (empty) array.
