### ISSUE TITLE
Running drush sql-drop on one site a multisite install with shared tables drops all the tables

### ISSUE THREAD

**Issue by davereid** [drush-ops/drush#543]
When using a database settings in Drupal 7 with something like the following that corresponds with an alias of `@mysite.dev`:

```php
$databases['default']['default'] = array(
  'database' => 'mydb',
  'username' => 'test',
  'password' => 'test',
  'host' => 'localhost',
  'port' => '',
  'driver' => 'mysql',
  'prefix' => array(
    'default' => 'mysite_',
    'users' => 'shared_',
    'session' => 'shared_',
  ),
);
```

If I were to run `drush @mysite sql-drop -y` this will result in all the tables in the `mydb` database being dropped, even if there were shared tables, or other sites from the same multisite install in that db.

Ideally we could use something like db_find_tables($default_prefix . '%') in Drupal 7 and above to only find the right tables. And would be nice if there was some kind of `--all` option to drop all tables regardless of prefix.

I'm not sure what the best way to solve this is right now. I thought about adding some kind of alter hook to the 'get me the list of all tables' functionality in master/6.x, but that wouldn't be good. For now this is what I'm using in multisite_sql.drush.inc: https://gist.github.com/davereid/9680778

**Comment by weitzman** [comment]
More recent discussion (but no progress) at #1135
