### ISSUE TITLE
Drush features with composer?

### ISSUE THREAD

**Issue by romulasry** [drush-ops/drush#5457]
**Is your feature request related to a problem? Please describe.**
It would be nice to use (some?) of Drush's features in composer

**Describe the solution you'd like**
Such as uninstalling from composer uninstalls from drupal, etc

**Describe alternatives you've considered**
None.

**Additional context**
Someone said they were looking into it: https://github.com/drush-ops/drush/issues/3719#issuecomment-602057005

https://getcomposer.org/doc/articles/scripts.md

**Comment by greg-1-anderson** [comment]
The other issue you reference is about adding hooks to Drush deploy, not Composer.

If you want to do this, you can add a Composer script per the docs you reference above. I don't think this should be the responsibility of Drush core.
