### ISSUE TITLE
Can't update from Drupal 9 to Drupal 10 with Drush installed

### ISSUE THREAD

**Issue by gitressa** [drush-ops/drush#5461]
**Describe the bug**
If I create a fresh Drupal 9.5 install, add Drush and then try to update with Composer, I get an error message about a `psr/log ~3.0.0` conflict.

If I uninstall Drush, the update goes through. See also [Unable to upgrade Drupal 9 to Drupal 10](https://www.drupal.org/project/drupal/issues/3335486).

**To Reproduce**
```
$ composer create-project drupal/recommended-project:9.5.0 "d95"
$ cd d95/
$ composer require drush/drush

# update ^9.5 to ^10 in composer.json

$ composer update "drupal/core-*" --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drupal/core-recommended[10.0.0, ..., 10.0.4] require psr/log ~3.0.0 -> found psr/log[3.0.0] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires drupal/core-recommended ^10 -> satisfiable by drupal/core-recommended[10.0.0, ..., 10.0.4].
```

**Expected behavior**
That Drupal code was updated to Drupal 10.

**Actual behavior**
I got an error.

**Workaround**
Uninstall Drush.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version  | 11.x
| Drupal version | 9.x
| PHP version     | 8.x
| OS             | Linux

**Additional information**

**Comment by weitzman** [comment]
Pretty sure this is not a Drush issue. I would try `composer update` instead of `composer update "drupal/core-*" --with-all-dependencies`. Your allow-list there is likely preventing things from updating. If you must keep an allow-list then add on stuff on like `drupal/core-recommended` and `drush/drush`

**Comment by gitressa** [comment]
Ah yes, you're right @weitzman. The command I tried is for updates between minor releases, i.e. from 9.4 to 9.5, or 10.0 to 10.1.

The official documentation recommends your method as well ([Upgrading a Composer-based site](https://www.drupal.org/docs/upgrading-drupal/upgrading-from-drupal-8-or-later/upgrading-a-composer-based-site)) and the update goes through using that. Have a nice day.

**Comment by joachim-n** [comment]
What is the cause of the problem if it isn't a Drush problem?

The instructions at https://www.drupal.org/docs/upgrading-drupal/upgrading-from-drupal-8-or-later/upgrading-a-composer-based-site -- which are the only thing I found to work to go from 9 to 10 -- are insane.

> We use --no-update to avoid a chicken-and-egg problem with mutual dependencies

What's the cause of the mutual dependency?

**Comment by greg-1-anderson** [comment]
The mutual dependencies are caused by the fact that both Drush and Drupal use Symfony. Composer is often pretty bad at this sort of complicated update.

**Comment by joachim-n** [comment]
Do you know if there's a Composer issue for this already?

**Comment by joachim-n** [comment]
> both Drush and Drupal use Symfony

Can't Drush rely on assuming that Symfony is there because of Drupal? Or is it packages required by drupal/core-dev only?

**Comment by greg-1-anderson** [comment]
Drush has certain expectations of Symfony and its other various requirements, so it needs to have its own constraints in order for Composer to provide a working set of libraries.
