### ISSUE TITLE
Cache-rebuild no longer reliable.

### ISSUE THREAD

**Issue by liquidcms** [drush-ops/drush#5474]
**Describe the bug**
I use drush a lot including for automated site deployment. Also a fair bit of module development. For years cache:rebuild has always seemed reliable. But lately there are times when it doesn't seem to rebuild class "repository" (is that a thing?).

One example from today was i was trying out the draggableviews module with various patches. As always, after enabling a module with drush, i run cr as i know classes are not "installed" when using drush to enable a module (as they are when going through the UI). I have had this module installed, enabled and working in the past on this site but was now uninstalled.

After installing it (composer) and enabling it (followed by cr), the Views plugin it provides was not available. After redoing this a few times and then trying it on a vanilla D9.4 site (where it worked correctly); i tried what i have done a few times "lately" - i manually emptied all the cache_ tables. This fixed the issue.

I have seen issues like this a few times in the past few months and they have always been fixed by emptying all the cache tables. I do not recall ever seeing this issue before (since starting D8 dev work years ago).

I refer to lately as i am not sure if this would be due to a newer version of Drush (currently running 11.4.0) or could it be to some recent addition in my site code (is this possible to break drush commands when they still report operation successful?).

I am not an expert on class discovery but if i were to guess; i would think something has changed in how drush empties some of the tables; possibly the cache_discovery table. One of the times where i saw something odd like this i emptied only the cache_discovery table and that resolved the issue. Another time it was not sufficient; but emptying all the cache tables worked.

**To Reproduce**
Very difficult to reproduce.

**Expected behavior**
Class files known to Drupal should be updated as per the installed code.

**Actual behavior**
Not al class files were available.

**Workaround**
Manually empty all the cache_ tables.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.4.0
| Drupal version? | 9.4.10
| PHP version     | 7.4.32
| OS?             | Windows

**Comment by gitressa** [comment]
Could this be a related issue, since it is also about cache not getting cleared? [Reinstalling a moved module throws “ InvalidArgumentException: Class "\Drupal\example\Form\ExampleForm" does not exist. in Drupal\Core\DependencyInjection\ClassResolver->getInstanceFromDefinition()”](https://www.drupal.org/project/drupal/issues/3342669). Like I write in that issue, its not clear if this is Drupal, Drush or Lando-related.

**Comment by liquidcms** [comment]
Sounds much different. There are no errors thrown. No module is moved.

**Comment by weitzman** [comment]
cache:rebuild is actually a tiny command that just calls drupal_rebuild() from drupal core. that then calls drupal core code and contrib code to clear as it wishes. See https://github.com/drush-ops/drush/blob/12.x/src/Commands/core/CacheCommands.php#L220. So, its likely that your problem is with Drupal code and not Drush.

**Comment by gitressa** [comment]
Thanks for clearing that up @weitzman, I'll try to pursue a solution in Drupal or Lando.

**Comment by liquidcms** [comment]
Still not convinced. Not an expert at writing custom drush commands but had to add one today. I see that 1 already exists for my custom module (don't recall adding it; but must have). Added a new command class, did a cr (and a cc drush) and my new command wasn't showing up. Because not a drush custom command expert i assumed i was doing something wrong. Wasted a couple hours trying various changes. Changed the command name of my existing command and that did show up (because the class has already been discovered).

Finally decided to empty all the cache tables. This fixed it. My new command was correct 2 hours ago but cr wouldn't reload drush.services.yml

This is completely different site than the one i originally saw this issue on.

Of course, now that i am an expert.. lol.. i guess i could write a cache rebuild command that does empty the cache tables. :)

**Comment by gitressa** [comment]
Have you tried verifying if "Clear all caches" on `/admin/config/development/performance` works? If not, it could mean that it's a Drupal issue, and not a Drush issue.
