### ISSUE TITLE
Document and publish a security bug reporting policy

### ISSUE THREAD

**Issue by junowilderness** [drush-ops/drush#5486]
**Existing document**
There is none as far as I can see.

**What are you attempting to do**
This is to provide clear steps for properly reporting security bugs.

**In what way is the existing documentation unclear or incomplete**
It does not exist.

**What should the documentation say instead?**
See https://github.com/drush-ops/drush/security/policy for suggestions.

**Comment by weitzman** [comment]
I just turned on vuln reporting in Github - https://github.com/drush-ops/drush/security/advisories.

As for the recent security.drupal.org report, it is not valid. I replied to security@drupal.org.

**Comment by massgov-outsider** [comment]
Also added to composer.json as per https://getcomposer.org/doc/04-schema.md#support

**Comment by weitzman** [comment]
Also added to composer.json as per https://getcomposer.org/doc/04-schema.md#support
