### ISSUE TITLE
Make usually skips large sections of the .make file with no errors or explanation

### ISSUE THREAD

**Issue by kpaxman** [drush-ops/drush#549]
Running Drush 6.2 on OSX Mavericks, drush make usually skips most of our .make file for some unknown reason. If we keep running the command, eventually it works. The only difference in the output is the missing section.

Linux users running the same command are not seeing the same issue.

The command we are issuing is:
drush make --working-copy --no-core --no-cache -y -v --contrib-destination=. profilename.make

**Comment by pmackay** [comment]
Hi, I've just updated on OSX from 5.9 to 6.6 (installed via composer) and found exactly this problem. Running a drush make file that worked fine before, simply downloads core and then 3 libraries, skipping everything else. Have dropped back to 5.9 and can run make command again.

**Comment by kpaxman** [comment]
I don't know if this is helpful in diagnosing the issue, but today my make file absolutely refused to do anything other than skip straight to the libraries. I split my make file into multiple files, and each built successfully. So maybe it's something to do with the size of the make file?

**Comment by kpaxman** [comment]
I've also been told by a colleague that this has happened to him occasionally in Linux, but it's a rare event for him instead of a constant occurrence like it is for me.

**Comment by pjcdawkins** [comment]
This is happening for me too, occasionally, with Drush 6.4.0.

I suspect that force-deleting the whole Drush cache first will help: `rm -Rf ~/.drush/cache` (but I'm not certain).

It is a large make file, but it's unlikely to be to do with the size of the file. Because it works sometimes but not others, I suspect it's do with caching and/or the connection to updates.drupal.org.

Do check your make file for little errors, perhaps with `drush verify-makefile` (I've done this for mine).

**Comment by pjcdawkins** [comment]
After a bit of debugging, I suspect it's to do with the length of the `--projects` option that Drush passes to its sub-process. The debugging is pretty hard...

**Comment by pjcdawkins** [comment]
About 80% of the attempts I make to run `drush make`, `drush_make_process()` is getting called with an empty `projects` option.

The other 20% of the attempts, the projects option is filled with the 121 modules that I have.

**Comment by pjcdawkins** [comment]
@weitzman this isn't a support request, it's a bug report - my logic is that anything this inconsistent must be a bug...

**Comment by pjcdawkins** [comment]
FWIW - when it works, multiple PHP processes appear to be running. When it doesn't work (when it skips projects and only downloads libraries), it seems to be just one PHP process.

**Comment by weitzman** [comment]
Sounds like #1049. @jhedstrom do we need to backport that to 6.x?. Folks with this bug should upgrade to latest drush7 release.

**Comment by kpaxman** [comment]
> Do check your make file for little errors, perhaps with drush verify-makefile (I've done this for mine).

Had to figure out how to verify-makefile, since it's not a default part of Drush (it turns out its at https://www.drupal.org/project/drupalorg_drush). The only issue I get is that my repos aren't on drupal.org (which should be fine since this is just for us).

> Sounds like #1049. @jhedstrom do we need to backport that to 6.x?

If this is the issue, I'd love to see it backported to 6.x as I'd rather run the "stable" version over the "unstable".

**Comment by pjcdawkins** [comment]
Aha, #1049 sounds like it (although why would it work some of the time?)

**Comment by kpaxman** [comment]
Installed Drush 7 using the instructions I found here - http://whaaat.com/installing-drush-7-using-composer - then re-merged my .make files. First attempt skipped straight to libraries, but after running composer global update I got this message...
  - Updating drush/drush dev-master (459140b => 1893cb6)
    Checking out 1893cb6545d49719dd8b718a3187ed9500cf98d2
...and then rebuilding worked fine, at least the three times I tried it. (I see that #1049 was committed somewhere in the middle of those 2 commits.)

**Comment by fuzzy76** [comment]
The Drush 6.x backport never happened on this? :-/
