### ISSUE TITLE
Fix batch for Drupal 10.1

### ISSUE THREAD

**Issue by andypost** [drush-ops/drush#5494]
**Is your feature request related to a problem? Please describe.**
Core getting rid of using `sequences` table and batch now using auto-increment https://www.drupal.org/node/3220378

Needs to fix [this pace at least](https://github.com/drush-ops/drush/blob/2b890ab5c2b5d70cae7b17ebda63ad57a3b318ab/includes/batch.inc#L129) the same way like https://git.drupalcode.org/project/drupal/-/commit/779785e220253c1d9fee8c43f7c7ed343a64244e

**Describe the solution you'd like**
Use to check if method exists and fallback to database method for BC

**Describe alternatives you've considered**
no

**Additional context**
running updates is broken https://www.drupal.org/project/drupal/issues/3337513#comment-14978772

**Comment by mondrake** [comment]
If I understand correctly batches in drush are run via it's own `batch.inc` code, i.e. code in Drupal's `form.inc` is not executed when the update runs via drush. That would explain why the table doesn't exist - in the new code that is ensured in `BatchStorage::getid()` which drush doesn't execute.
