### ISSUE TITLE
Can no longer run drush

### ISSUE THREAD

**Issue by jimrome** [drush-ops/drush#5495]
**Describe the bug**
if I run drush on Drupal 9.5.5 (or 10.0.5) on one site, I get:
[preflight] Mapping values are not allowed in multi-line blocks at line 2 (near "<?php").

**To Reproduce**
ran drush (even with no argument)

**Expected behavior**
should run

**Actual behavior**
get above error

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.2
| PHP version     | 8.1.17
| OS?             | OpenSuse LEAP 15.4
**Additional information**
This seems to be a YAML or php error, but I did not write any code myself, so it must be an error in an installed module. But how do I tell which one??

**Comment by greg-1-anderson** [comment]
Sounds like you're using a version of PHP that's newer than supported by the EOL Drush versions you are using. Try upgrading to a supported version of Drush, e.g. 11.5.1, at the time of this writing.

**Comment by jimrome** [comment]
No. That's the version in composer.json since I can't run drush to get the version. But it sahould be the latest one if composer update works.

**Comment by greg-1-anderson** [comment]
Transposed your Drupals and Drush's the first time, but 11.2 isn't newest either. What does `composer info drush/drush` say? You could try putting `^11.5` for your Drush version in your composer.json; if `composer update` doesn't work after that, try removing composer.lock and vendor and try again.

**Comment by jimrome** [comment]
requires
chi-teck/drupal-code-generator ^2.4
composer/semver ^1.4 || ^3
consolidation/annotated-command ^4.7.0
consolidation/config ^2
consolidation/filter-via-dot-access-data ^2
consolidation/robo ^3.0.9 || ^4.0.1
consolidation/site-alias ^3.1.6 || ^4
consolidation/site-process ^4.1.3 || ^5
enlightn/security-checker ^1
ext-dom *
guzzlehttp/guzzle ^6.5 || ^7.0
league/container ^3.4 || ^4
php >=7.4
psy/psysh ~0.11
symfony/event-dispatcher ^4.0 || ^5.0 || ^6.0
symfony/filesystem ^4.4 || ^5.4 || ^6.1
symfony/finder ^4.0 || ^5 || ^6
symfony/polyfill-php80 ^1.23
symfony/var-dumper ^4.0 || ^5.0 || ^6.0
symfony/yaml ^4.0 || ^5.0 || ^6.0
webflo/drupal-finder ^1.2

requires (dev)
composer/installers ^1.7
cweagans/composer-patches ~1.0
david-garcia/phpwhois 4.3.0
drupal/core-recommended ^9 || ^10
drupal/semver_example 2.3.0
phpunit/phpunit >=7.5.20
rector/rector ^0.12
squizlabs/php_codesniffer ^3.6
vlucas/phpdotenv ^2.4
yoast/phpunit-polyfills ^0.2.0

conflicts
drupal/core < 9.2
drupal/migrate_run *
drupal/migrate_tools <= 5

I reequired > 11.5 in composer.json, and nothing update4d

**Comment by jimrome** [comment]
I uninstalled and reinstalled
No security vulnerability advisories found
Using version ^11.5 for drush/drush
jarfx:/srv/www/htdocs/ssl2/xisam # dr
 [preflight] Mapping values are not allowed in multi-line blocks at line 2 (near "<?php").
 dr -> vendor/bin/drush

**Comment by jimrome** [comment]
I fixed it. I was pulling drush from somewhere else.
Sorry for the bother.

**Comment by jimrome** [comment]
oops. I spoke too soon. It is definitely an issue with an imported module.
**`jarfx:/srv/www/htdocs/ssl2/xisam # dr updb
 [success] No pending updates.**

jarfx:/srv/www/htdocs/ssl2/xisam # composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]?
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 6 installs, 29 updates, 11 removals
  - Removing doctrine/reflection (1.2.3)
  - Removing laminas/laminas-diactoros (2.24.0)
  - Removing laminas/laminas-escaper (2.12.0)
  - Removing laminas/laminas-feed (2.20.0)
  - Removing stack/builder (v1.0.6)
  - Removing symfony-cmf/routing (2.3.4)
  - Removing symfony/debug (v4.4.44)
  - Removing symfony/http-client-contracts (v2.5.2)
  - Removing symfony/polyfill-php73 (v1.27.0)
  - Removing symfony/translation (v4.4.47)
  - Removing typo3/phar-stream-wrapper (v3.1.7)
  - Upgrading asm89/stack-cors (1.3.0 => v2.1.1)
  - Upgrading consolidation/log (2.1.1 => 3.0.0)
  - Upgrading consolidation/robo (4.0.2 => 4.0.3)
  - Upgrading consolidation/site-process (4.2.1 => 5.2.0)
  - Upgrading drupal/core (9.5.5 => 10.0.5)
  - Upgrading drupal/sophron (1.3.0 => 2.0.1)
  - Upgrading grasmash/expander (2.0.3 => 3.0.0)
  - Downgrading laminas/laminas-servicemanager (3.20.0 => 3.15.0)
  - Downgrading laminas/laminas-text (2.10.0 => 2.9.0)
  - Upgrading mglaman/composer-drupal-lenient (1.0.2 => 1.0.3)
  - Locking phootwork/collection (v3.2.1)
  - Locking phootwork/lang (v3.2.1)
  - Locking phpowermove/docblock (v4.0)
  - Upgrading psr/container (1.1.2 => 2.0.2)
  - Locking psr/event-dispatcher (1.0.0)
  - Upgrading psr/log (1.1.4 => 3.0.0)
  - Upgrading symfony/console (v4.4.49 => v6.2.7)
  - Upgrading symfony/dependency-injection (v4.4.49 => v6.2.7)
  - Upgrading symfony/error-handler (v4.4.44 => v6.2.7)
  - Upgrading symfony/event-dispatcher (v4.4.44 => v6.2.7)
  - Upgrading symfony/event-dispatcher-contracts (v1.1.13 => v3.2.1)
  - Upgrading symfony/http-foundation (v4.4.49 => v6.2.7)
  - Upgrading symfony/http-kernel (v4.4.50 => v6.2.7)
  - Upgrading symfony/mime (v5.4.13 => v6.2.7)
  - Locking symfony/polyfill-php81 (v1.27.0)
  - Upgrading symfony/process (v4.4.44 => v6.2.7)
  - Upgrading symfony/routing (v4.4.44 => v6.2.7)
  - Upgrading symfony/serializer (v4.4.47 => v6.2.7)
  - Upgrading symfony/service-contracts (v2.5.2 => v3.2.1)
  - Upgrading symfony/translation-contracts (v2.5.2 => v3.2.1)
  - Upgrading symfony/validator (v4.4.48 => v6.2.7)
  - Upgrading symfony/var-dumper (v5.4.21 => v6.2.7)
  - Locking symfony/var-exporter (v6.2.7)
  - Upgrading symfony/yaml (v4.4.45 => v6.2.7)
  - Upgrading twig/twig (v2.15.4 => v3.5.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 6 installs, 29 updates, 11 removals
  - Removing typo3/phar-stream-wrapper (v3.1.7)
  - Removing symfony/translation (v4.4.47)
  - Removing symfony/polyfill-php73 (v1.27.0)
  - Removing symfony/http-client-contracts (v2.5.2)
  - Removing symfony/debug (v4.4.44)
  - Removing symfony-cmf/routing (2.3.4)
  - Removing stack/builder (v1.0.6)
  - Removing laminas/laminas-feed (2.20.0)
  - Removing laminas/laminas-escaper (2.12.0)
  - Removing laminas/laminas-diactoros (2.24.0)
  - Removing doctrine/reflection (1.2.3)
  - Upgrading mglaman/composer-drupal-lenient (1.0.2 => 1.0.3): Extracting archive
  - Upgrading symfony/http-foundation (v4.4.49 => v6.2.7): Extracting archive
  - Installing psr/event-dispatcher (1.0.0): Extracting archive
  - Upgrading symfony/event-dispatcher-contracts (v1.1.13 => v3.2.1): Extracting archive
  - Upgrading symfony/event-dispatcher (v4.4.44 => v6.2.7): Extracting archive
  - Upgrading symfony/var-dumper (v5.4.21 => v6.2.7): Extracting archive
  - Upgrading psr/log (1.1.4 => 3.0.0): Extracting archive
  - Upgrading symfony/error-handler (v4.4.44 => v6.2.7): Extracting archive
  - Upgrading symfony/http-kernel (v4.4.50 => v6.2.7): Extracting archive
  - Upgrading asm89/stack-cors (1.3.0 => v2.1.1): Extracting archive
  - Upgrading psr/container (1.1.2 => 2.0.2): Extracting archive
  - Upgrading symfony/service-contracts (v2.5.2 => v3.2.1): Extracting archive
  - Upgrading symfony/console (v4.4.49 => v6.2.7): Extracting archive
  - Upgrading consolidation/log (2.1.1 => 3.0.0): Extracting archive
  - Upgrading twig/twig (v2.15.4 => v3.5.1): Extracting archive
  - Upgrading symfony/yaml (v4.4.45 => v6.2.7): Extracting archive
  - Upgrading symfony/translation-contracts (v2.5.2 => v3.2.1): Extracting archive
  - Upgrading symfony/validator (v4.4.48 => v6.2.7): Extracting archive
  - Upgrading symfony/serializer (v4.4.47 => v6.2.7): Extracting archive
  - Upgrading symfony/routing (v4.4.44 => v6.2.7): Extracting archive
  - Upgrading symfony/process (v4.4.44 => v6.2.7): Extracting archive
  - Upgrading symfony/mime (v5.4.13 => v6.2.7): Extracting archive
  - Installing symfony/var-exporter (v6.2.7): Extracting archive
  - Upgrading symfony/dependency-injection (v4.4.49 => v6.2.7): Extracting archive
  - Upgrading drupal/core (9.5.5 => 10.0.5): Extracting archive
  - Upgrading drupal/sophron (1.3.0 => 2.0.1): Extracting archive
  - Downgrading laminas/laminas-servicemanager (3.20.0 => 3.15.0): Extracting archive
  - Downgrading laminas/laminas-text (2.10.0 => 2.9.0): Extracting archive
  - Upgrading grasmash/expander (2.0.3 => 3.0.0): Extracting archive
  - Upgrading consolidation/site-process (4.2.1 => 5.2.0): Extracting archive
  - Installing symfony/polyfill-php81 (v1.27.0): Extracting archive
  - Installing phootwork/lang (v3.2.1): Extracting archive
  - Installing phootwork/collection (v3.2.1): Extracting archive
  - Installing phpowermove/docblock (v4.0): Extracting archive
  - Upgrading consolidation/robo (4.0.2 => 4.0.3): Extracting archive
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
Generating autoload files
51 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> DrupalProject\composer\ScriptHandler::createRequiredFiles
No security vulnerability advisories found
**jarfx:/srv/www/htdocs/ssl2/xisam # dr updb
 [preflight] Mapping values are not allowed in multi-line blocks at line 2 (near "<?php").`**

**Comment by weitzman** [comment]
You are upgrading to a new major version of Drupal there. So too many changes to be effective at debugging this.

I have seen this error before when Drush parsed a php file when it was looking for yml files. It doesnt happen under normal circumstances so its hard to say which file is causing this, and why.

**Comment by jimrome** [comment]
Just a suggestion: get drush to print out the name of the offending file.

**Comment by jimrome** [comment]
This was solved. It probably should be fixed.
[Do you have a shortcut to drush at the root ?](https://www.drupal.org/forum/support/post-installation/2023-03-22/can-no-longer-run-drush#comment-15001754)
[Manuel.loth](https://www.drupal.org/u/manuelloth) commented about 7 hours ago

Hello,

We encountered the same issue. After some debugging, we realized that drush looks for config files in various locations, and may mistake a shortcut to drush for a config file, which raises an exception in the yaml parser :

$this->addConfigPaths(self::DRUPAL_CONTEXT, [ dirname($siteRoot) . '/drush', "$siteRoot/drush", "$siteRoot/sites/all/drush" ]);

So if like us, you have a symlink to drush in $siteRoot, this should explain the failures.

    [reply](https://www.drupal.org/comment/reply/3349654/15001754) [report as spam](https://www.drupal.org/flag/flag/drupalorg_comment_spam/15001754?destination=node/3349654&token=U3cpZprpKlzyTFO-69mneCaYtiKrwNpq4o9tPADjz60)  


new
[Thanks!](https://www.drupal.org/forum/support/post-installation/2023-03-22/can-no-longer-run-drush#comment-15002016)
[tjtj](https://www.drupal.org/u/tjtj) commented about 3 hours ago

Yes! Thank you so much. I had an old drush link, and when I removed it it worked.
