### ISSUE TITLE
Drush has been segfaulting

### ISSUE THREAD

**Issue by dereliahmet1** [drush-ops/drush#5498]
**Describe the bug**
We have started to experience segfault issues. We have cronjobs for queuing jobs on CiviCRM, which mainly involves sending emails. It’s a basic process, but we’ve started to see a couple of segfault errors. These errors are happening across different versions of PHP (7.4 and 8.0), Drush (8 and 10), and Drupal (7 and 8). We haven’t been able to find any relation between these issues.
 
**To Reproduce**
drush --root=/var/www/example.org --uri=https://example.org--user=1 civicrm-api job.process_mailing auth=0 --yes
drush --root=/var/www/example.com --uri=https://example.com --uid=1 civicrm:api job.execute auth=0 --yes
drush --root=/var/www/example.com --uri=https://example.org cron --yes

**Expected behavior**
Return Success

**Actual behavior**
Segfault 
Coredump info
                Stack trace of thread 1795936:
                #0  0x00007f66543f6a7c __pthread_kill_implementation (libc.so.6 + 0x96a7c)
                #1  0x00007f66543a2476 __GI_raise (libc.so.6 + 0x42476)
                #2  0x00007f66543887f3 __GI_abort (libc.so.6 + 0x287f3)
                #3  0x00007f66543e96f6 __libc_message (libc.so.6 + 0x896f6)
                #4  0x00007f6654400d7c malloc_printerr (libc.so.6 + 0xa0d7c)
                #5  0x00007f6654402ef0 _int_free (libc.so.6 + 0xa2ef0)
                #6  0x00007f66544054d3 __GI___libc_free (libc.so.6 + 0xa54d3)
                #7  0x00005584277e7892 n/a (dash + 0x17892)
                #8  0x00005584277e2f37 n/a (dash + 0x12f37)
                #9  0x00005584277dcc00 n/a (dash + 0xcc00)
                #10 0x00005584277dcd4e n/a (dash + 0xcd4e)
                #11 0x00005584277dcc00 n/a (dash + 0xcc00)
                #12 0x00005584277dcc3a n/a (dash + 0xcc3a)
                #13 0x00005584277dcc00 n/a (dash + 0xcc00)
                #14 0x00005584277dcc00 n/a (dash + 0xcc00)
                #15 0x00005584277e1b28 n/a (dash + 0x11b28)
                #16 0x00005584277d4d53 n/a (dash + 0x4d53)
                #17 0x00007f6654389d90 __libc_start_call_main (libc.so.6 + 0x29d90)
                #18 0x00007f6654389e40 __libc_start_main_impl (libc.so.6 + 0x29e40)
                #19 0x00005584277d4f15 n/a (dash + 0x4f15)
  
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/bin/sh -e /usr/lib/php/sessionclean'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Section `.reg-xstate/1114047' in core file too small.
#0  __strcspn_sse42 (s=0x55e750e96bb8 "\001", a=0xd <error: Cannot access memory at address 0xd>) at ../sysdeps/x86_64/multiarch/strcspn-c.c:83
83	../sysdeps/x86_64/multiarch/strcspn-c.c: No such file or directory.
(gdb) bt
#0  __strcspn_sse42 (s=0x55e750e96bb8 "\001", a=0xd <error: Cannot access memory at address 0xd>) at ../sysdeps/x86_64/multiarch/strcspn-c.c:83
#1  0x000055e75023b3db in ?? ()
#2  0x000055e750245773 in ?? ()
#3  0x000055e7502412d8 in ?? ()
#4  0x000055e75023ac00 in ?? ()
#5  0x000055e75023ac00 in ?? ()
#6  0x000055e75023ac3a in ?? ()
#7  0x000055e75023ac3a in ?? ()
#8  0x000055e75023ac3a in ?? ()
#9  0x000055e75023ac00 in ?? ()
#10 0x000055e75023ac00 in ?? ()
#11 0x000055e75023af88 in ?? ()
#12 0x000055e75023ac00 in ?? ()
#13 0x000055e75023af88 in ?? ()
#14 0x000055e75023ac00 in ?? ()
#15 0x000055e75023ac00 in ?? ()
#16 0x000055e75023ac3a in ?? ()
#17 0x000055e75023f8ad in ?? ()
#18 0x000055e75023ac00 in ?? ()
#19 0x000055e750240556 in ?? ()
#20 0x000055e75023ac00 in ?? ()
#21 0x000055e75023fb28 in ?? ()
#22 0x000055e750232d53 in ?? ()
#23 0x00007f86a1dc0d90 in __libc_start_call_main (main=main@entry=0x55e750232ae0, argc=argc@entry=3, argv=argv@entry=0x7ffe10b895b8) at ../sysdeps/nptl/libc_start_call_main.h:58
#24 0x00007f86a1dc0e40 in __libc_start_main_impl (main=0x55e750232ae0, argc=3, argv=0x7ffe10b895b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7ffe10b895a8) at ../csu/libc-start.c:392
#25 0x000055e750232f15 in ?? ()

**Workaround**
It's not happening on every run but we are getting this segfaults mininum twice a day. 

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.x/10.6.2/8.4.11  
| Drupal version? | 9/8/7 
| PHP version     | 8.0/7.4
| OS?             | Linux

**Additional information**

**Comment by weitzman** [comment]
I suggest asking at Drupal Answers. Not likely a Drush issue.
