### ISSUE TITLE
Drush does not list all annotated commands

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#5505]
**To Reproduce**
1. Install [field_definition_dumper](https://github.com/Chi-teck/field_definition_dumper) module.
2. Check that `drush field:dump:types` command works.
3. Runs `drush list` command. 

**Expected behavior**
`field:dump:*` commands to be listed

**Actual behavior**
`field:dump:*` are not listed

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.x
| Drupal version? | 10.x
| PHP version     | 8.x
| OS?             | Linux

**Additional information**
Seems like Drush sets the commands "hidden" by some reason.

**Comment by weitzman** [comment]
Fixed by https://github.com/consolidation/annotated-command/pull/299

**Comment by weitzman** [comment]
These commands look pretty sweet. If @Chi-teck and @DieterHolvoet think these should move to core Drush, I support that. They are pretty small. They do need some basic tests.

**Comment by Chi-teck** [comment]
I don't mind moving these commands to Drush.

**Comment by DieterHolvoet** [comment]
Sure, we could move these to Drush! I'd rename them though, to be in line with other commands like `pm:list`, `role:list`, `queue:list`, etc. How about `field:type:list`, `field:widget:list` and `field:formatter:list`?

**Comment by weitzman** [comment]
What about naming them field:types, field:widgets, field:formatters?

**Comment by DieterHolvoet** [comment]
Sure, that works as well. @Chi-teck would you be up for creating the PR?
