### ISSUE TITLE
drush si fails with DB name with hyphens in

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#5525]
**Describe the bug**

I ran `drush si` on a site whose settings.php defined the DB as:

```
  'database' => 'drupal-circle-dot',
```

I got this error:

```
 [warning] Failed to drop or create the database. Do it yourself before installing. ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-circle-dot' at line 1
```

Changing the DB name to one without hyphens fixed the problem.

I suspect the bug only happens if the DB doesn't exist already. I always prefix my DB names with `drupal-` (unless running migrations -- there's a Drupal core bug with JOINs to migration maps!) and doing drush si to reinstall a site works fine for me.

**To Reproduce**

**Expected behavior**
What did you expect would happen?

**Actual behavior**
What happened instead?

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.5.1
| Drupal version? | 9.5.5
| PHP version     | 8.1
| OS?             | Mac

**Additional information**

**Comment by weitzman** [comment]
Just fixed in #5167
