### ISSUE TITLE
Misleading error msg when composer.json extra.installer_types is not present

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#5539]
drush 12 now says "Globally installed Drush is no longer supported; Drush must be installed inside a Drupal site."

**Comment by greg-1-anderson** [comment]
I guess we should fall back and use some of our own logic to find the root if Drupal Finder doesn't return a location. We could also check to see if drupal/core exists in composer.lock, and print a better message. We could use Composer metadata to find the install location of drupal/core, but I don't want Drush to depend on composer/composer, and I don't want to read the internal structures manually either.

**Comment by weitzman** [comment]
> We could use Composer metadata to find the install location of drupal/core

Composer has an API for this now https://getcomposer.org/doc/07-runtime.md#knowing-the-path-in-which-a-package-is-installed

**Comment by greg-1-anderson** [comment]
Oh, that sounds like a fantastic enhancement for Drupal Finder.

**Comment by weitzman** [comment]
Fixed
