### ISSUE TITLE
Add "drush generate readme" command

### ISSUE THREAD

**Issue by joshsedl** [drush-ops/drush#5554]
**Is your feature request related to a problem? Please describe.**
I really enjoy using the `drush generate` command for all sorts of things, as it saves a lot of time, when creating a module. And I recently wondered why there is no `drush generate readme` command, which would generate a README.md template, using Drupal's [README.md template](https://www.drupal.org/docs/develop/managing-a-drupalorg-theme-module-or-distribution-project/documenting-your-project/readmemd-template).

**Describe the solution you'd like**
Implement a `drush generate readme` command to easily generate a module's README.md.

**Comment by JPustkuchen** [comment]
Really nice idea :) Especially now that Drupal.org allows to copy the contents from the README.md to the project page!

**Comment by gitressa** [comment]
This would be a nice feature. Anything that can be automated with tools, should be :)

**Comment by weitzman** [comment]
This belongs in DCG - https://github.com/Chi-teck/drupal-code-generator. Then it will go into Drush automatically.

**Comment by JPustkuchen** [comment]
Thanks @weitzman! I did that now: https://github.com/Chi-teck/drupal-code-generator/issues/99
