### ISSUE TITLE
Provide a drush.api.php file to document available custom hooks provided by Drush e.g. HOOK_deploy_NAME()

### ISSUE THREAD

**Issue by codebymikey** [drush-ops/drush#5559]
**Is your feature request related to a problem? Please describe.**
Following on from #3613, it'd be nice if we had a `drush.api.php` file which could be used to document custom Drupal hooks like `HOOK_deploy_NAME()` which is called by the `drush deploy:hook` [command](https://www.drush.org/11.x/deploycommand/)

This is useful because certain IDE plugins e.g. PHPStorm's Drupal integration pick these API hook declarations up and provides you with contextual autocomplete options when writing new hook implementations.

**Describe the solution you'd like**
Provide a simple [`drush.api.php`](https://api.drupal.org/api/drupal/core%21core.api.php/group/hooks/10) file documenting `HOOK_deploy_NAME()` as well as other custom Drupal hooks declared by Drush (example file available [here](https://git.drupalcode.org/project/examples/-/blob/4.0.x/modules/hooks_example/hooks_example.api.php))

**Comment by weitzman** [comment]
Every site is going to have different commands so will have different hooks available. You could write a command or a generator that scans the site and builds a drush.api.php file. I'm not too interested in this for core Drush but its nice as a contrib.

**Comment by codebymikey** [comment]
I think there might be a misunderstanding with what I'm saying here and what the `api.php` file does.

The `drush.api.php` just needs to be a static file containing only custom Drupal API hooks that are provided by the actual Drush project itself (not all the available Drush commands picked up by the site), and as far as I can tell, `hook_deploy_NAME()` is the only Drupal hook that's currently directly declared and executed by the Drush project.

If a contrib project declares its own Drupal hooks, then it'd need to document it inside its own `project_name.api.php` e.g. [drush_pre_deploy](https://www.drupal.org/project/drush_pre_deploy/issues/3359642)

There's no need for it to be generated dynamically. It'll be a simple php file [like this](https://git.drupalcode.org/project/webform/-/blob/6.1.x/webform.api.php) documenting that the `hook_deploy_NAME()` hook is available for implementation [kinda like this](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_post_update_NAME/8.2.x) (since Drush is currently installed).

**Comment by weitzman** [comment]
Thanks for clarifying your suggestion. That omits the [Annotated Command hooks](https://github.com/consolidation/annotated-command#hooks) that run for each command.

**Comment by weitzman** [comment]
See #5615
