### ISSUE TITLE
Generators should no longer need a drush.services.yml entry (like commands)

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#5575]
**Is your feature request related to a problem? Please describe.**
The[ tagged service check that we do now](https://github.com/drush-ops/drush/blob/5ed4fc7710c41293b36183165ec1b66588690a9b/src/Boot/DrupalBoot8.php#L286
https://github.com/weitzman/drush/blob/5ed4fc7710c41293b36183165ec1b66588690a9b/src/Boot/DrupalBoot8.php#L286) could potentially be removed and we ideally don't load generators which were made for DCG v2.

**Comment by greg-1-anderson** [comment]
The legacyServiceInstantiator is there for bc, to avoid forcing folks to port their modules right away. There are fewer generators out there, though; if you and @Chi-teck prefer it, we could certainly remove the bc layer for generators and force folks to port those.

**Comment by Chi-teck** [comment]
DCG 2 generators are not compatible with DCG 3. So there is no point to load them in Drush 12.

**Comment by greg-1-anderson** [comment]
Oh, okay; if all of the generators need to be rewritten for Drush 12 anyway, then we might as well remove the drush.services.yml adaptor for them as well.

**Comment by weitzman** [comment]
Closed by #5581
