### ISSUE TITLE
Provide `NULL` value support for config-set without having to use `--input-format=yaml`

### ISSUE THREAD

**Issue by wimleers** [drush-ops/drush#5587]
**Is your feature request related to a problem? Please describe.**
Just like #4081/#4781 added support for the empty string and empty array, we also need to provide support for `~` (NULL).

Example: a Text Editor config entity (`editor.editor.*`)'s `image_upload.max_dimensions.width` accepts integers for imposing a width restriction, but also `NULL` (`null` or `~` in YAML) for indicating there is _no_ width restriction. See https://www.drupal.org/node/2644838.

There's a handful of other config schemas in Drupal core that have `nullable: true` set that allow this, and many more in contrib.

**Describe the solution you'd like**
Allow `drush cset media.settings iframe_domain NULL -y` to set `null` to not only have
```
        // Special handling for empty array.
        if ($data == '[]') {
            $data = [];
        }
```
but also
```
        // Special handling for NULL.
        if ($data == 'NULL') {
            $data = NULL;
        }
```
(PR: #5588 — handles any upper- or lowercasing of this special value.)

With those 3 added lines, it'd work as expected, instead of generating:
```
iframe_domain: 'NULL'
```
it would generate:
```
iframe_domain: null
```

**Describe alternatives you've considered**
Work-arounds that work today:
- `drush cset media.settings iframe_domain null --input-format=yaml -y`
- `drush cset media.settings iframe_domain '~' --input-format=yaml -y`

**Additional context**
N/A

**Comment by weitzman** [comment]
Done
