### ISSUE TITLE
Drush sql:query should return non-zero exit code when fails (postgres)

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#5591]
**Describe the bug**
This applies to other sql:* commands as well.

**To Reproduce**
```
drush sql:query 'wrong query'
```

**Expected behavior**
```
echo $?;
1
```

**Actual behavior**
```
echo $?;
0
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.x
| Drupal version? | 10.x
| PHP version     | 8.x
| OS?             | Linux

**Comment by weitzman** [comment]
I get exit code 1 in this same experiment 

```
eitzman@drush-web:/var/www/html$ drush sql:query 'wrong query'

In SqlCommands.php line 183:

  Query failed. Rerun with --debug to see any error message. ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corr
  esponds to your MariaDB server version for the right syntax to use near 'wrong query' at line 1


weitzman@drush-web:/var/www/html$ echo $?;
1

weitzman@drush-web:/var/www/html$ drush status
Drupal version   : 10.0.8
Site URI         : https://drush.ddev.site:444
DB driver        : mysql
DB hostname      : db
DB port          :
DB username      : root
DB name          : unish_default
Database         : Connected
Drupal bootstrap : Successful
Default theme    : stark
Admin theme      : seven
PHP binary       : /usr/bin/php8.1
PHP config       : /etc/php/8.1/cli/php.ini
PHP OS           : Linux
PHP version      : 8.1.16
Drush script     : /var/www/html/drush
Drush version    : 12.x-dev
Drush temp       : /tmp
Drush configs    : /var/www/html/drush.yml
                   /var/www/html/drush
Install profile  : testing
Drupal root      : /var/www/html/sut
Site path        : sites/default
Files, Public    : sites/default/files
Files, Temp      : /tmp
```

**Comment by Chi-teck** [comment]
Forgot to mention. In my case the site is using PostgreSQL.

**Comment by weitzman** [comment]
I tested and the issue is that psql is reporting code 0 in this case. We are running `psql -q --dbname=unish_dev --host=db --port=5432 --username=db  --no-align --field-separator="	" --pset tuples_only=on --file /tmp/drush_ZEGuAA`

See https://stackoverflow.com/questions/37072245/check-return-status-of-psql-command-in-unix-shell-scripting for solutions. Perhaps we should set ON_ERROR_STOP on all our psql statements? Needs postgres expert advice.

**Comment by Chi-teck** [comment]
I am not an expert but enabling `ON_ERROR_STOP` seems the correct approach to me.

**Comment by Chi-teck** [comment]
Well setting `ON_ERROR_STOP` may break restoring database using dump created with `drush sql:dump` command.

**Comment by weitzman** [comment]
Can you think of a reason why would there be statements in the dump that fail to query successfully?

**Comment by Chi-teck** [comment]
Any `CREATE TABLE` will fail if a table already exists.
Even if you drop all tables though `drush sql:drop` restoring dump will fail anyway because of existing functions and views.

For instance, Drupal PG driver adds [rand](https://github.com/drupal/drupal/blob/10.0.0/core/modules/pgsql/src/Driver/Database/pgsql/Install/Tasks.php#L283) function which appears in the dump file like follows.

```
CREATE FUNCTION public.rand()
```

**Comment by Chi-teck** [comment]
Possible workaround could be creating `drush sql:restore` command for restoring database.
The command would use `psql` with non-strict mode or `pg_restore`  utility.

Though I am not sure if this would be a reliable solution.

**Comment by Chi-teck** [comment]
> restoring dump will fail anyway because of existing functions and views

That's BTW another issue I faced recently. I have a few SQL views in Postgres and thouse cause `drush sql:drop` to fail silently because tables cannot be removed as long as they are referenced by other DB objects. We probably need to append `CASCADE` keyword to the `DROP table` statement for PG driver.

**Comment by weitzman** [comment]
Now that we added CASCADE in #5649, maybe its safe to do #5650. What do you think @Chi-teck?

**Comment by Chi-teck** [comment]
Tested `drush sql:dump` and `drush sql:cli`. It worked as expected,.
