### ISSUE TITLE
SQL Server : Bootstrap phase bootstrapDrupalDatabase() failed to validate

### ISSUE THREAD

**Issue by NCAC** [drush-ops/drush#5603]
**Describe the bug**

It applies seemingly to all drush commands.
My website works well otherwise, the database is well connected and I have no errors in the back-end

1. When I launch `drush list -vvv` or `drush status -vvv` I have the folowing message in the console :
**[info] key_value table not found. Database may be empty. [0.19 sec, 9.62 MB]
[debug] Bootstrap phase bootstrapDrupalDatabase() failed to validate; continuing at bootstrapDrupalConfiguration() [0.19 sec, 9.62 MB]**
 
 2. Furthermore, a lot of drush commands with `drush list` are not available, only *_global*, *archive*, *cache*, *core*, *php*, *pm* (but not `pm:install` or `pm:uninstall`), *site*, *sql* and *updatedb*.

 
3. As expected, the `drush config:import` does not work :
Command config:import was not found. Drush was unable to query the database. As a result, many commands are unavailable. Re-run your command with --debug to see relevant log messages.
 
**To Reproduce**
`drush list -vvv`
`drush config:import`

**Expected behavior**
with `drush list -vvv`, having the full list of drush commands, without the **Bootstrap phase bootstrapDrupalDatabase() failed to validate** error.

**Workaround**
- The error comes from Drush\Boot\DrupalBoot8::bootstrapDrupalDatabaseValidate in \vendor\drush\drush\src\Boot\DrupalBoot8.php with this lines :
```
if (!$connection->schema()->tableExists('key_value')) {
  $this->logger->info('key_value table not found. Database may be empty.');
  return false;
}
```
- I use the [stabloom/drush-sqlserver-driver package](https://github.com/starbloom/drush-sqlserver-driver/tree/master) which I had to modify a bit to be compatible with PHP 7.4.3  and of course the [Drupal driver for SQL Server and SQL Azure](https://www.drupal.org/project/sqlsrv) contrib module.

By accident, I fixed the bug by adding this line in Drush\Boot\DrupalBoot8::bootstrapDrupalDatabaseValidate, just before the line `if (!$connection->schema()->tableExists('key_value')) {`. (I wanted only to print the result and I was surprised to find that the error was gone)

```
$this->logger->info('test: ' . print_r($connection->schema()->findTables('key_value'), true));
```

I still don't quite understand with this line addition it works again, maybe the database connection is somehow initialized??
Anyway, it's fixed on my side, also with this line:
```
$unused_variable = $connection->schema()->findTables('test'); // It works with any string in fact
```
From the moment the solution is kind of hacky and I don't *clearly* understand why it works, I did not make a pull request

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.5.1
| Drupal version? | 9.x
| PHP version?     | 7.4.3
| OS?             | Windows
| Database?    | SQLServer version 15.00.2000

**Comment by greg-1-anderson** [comment]
Seems sql-server specific. Did you try to reproduce on Drush 11, to see if it behaved any differently?

**Comment by NCAC** [comment]
Sorry, typing error, I was actually on version 11.5.1

**Comment by weitzman** [comment]
please work starbloom on the driver. we do not support connections to ms sql server in this project.

**Comment by NCAC** [comment]
Ok, I will take a look at the [SQL Server Driver](https://www.drupal.org/project/sqlsrv), there must be something wrong with their implementation of Schema::tableExists.
Thank you !
