### ISSUE TITLE
Site Install $additional_form_options only supports strings.

### ISSUE THREAD

**Issue by Decipher** [drush-ops/drush#561]
It appears that $additional_form_options can only be provided with string values, which is an issue for checkboxes as any string value will result in the default value being returned, and if the default value is on then there is no way to set the checkbox as off.

Integers (via is_numberic) and NULL (== 'NULL') should be translated into the correct data types, which should resolve this issue.

I have a relatively simply version of such that I will push as a PR shortly, but I suspect that there are other types of data that should be able to be passed in that I'm not accounting for.

**Comment by leo72** [comment]
Same problem here for multilingual site profile. I have 

    $form['polyglot_languages'] = array(
    '#title' => t('Choose a language'),
    '#type' => 'checkboxes',
    '#required' => TRUE,
    '#options' => $languages_processed,
  );

$languages_processed is array of languages. How to set languages via drush si?
