### ISSUE TITLE
Port Drupal Console `config:import:single` command so we can import single configuration entities from an existing file. 

### ISSUE THREAD

**Issue by trackleft** [drush-ops/drush#5619]
**Is your feature request related to a problem? Please describe.**
As a manager of a custom Drupal distribution, which manages configuration in code, sometimes individual sites run into issues with pulling in upstream changes via mechanisms like config_distro, config_sync.

**Describe the solution you'd like**
A more precise way to import a single config file to override any existing configuration, or missing configuration.  

**Describe alternatives you've considered**
1. Manually import config via the UI in config_sync for each affected site.
2. There is a drupal module for this. https://www.drupal.org/project/config_import_single, however it does currently require a patch to be used with Drupal 9.5 and above.

**Additional context**
https://github.com/hechoendrupal/drupal-console/blob/7027117c82cd8b9d9f3fb89558a088e0575434d3/src/Command/Config/ImportSingleCommand.php#L55

**Comment by joeparsons** [comment]
FWIW, there is a related Drupal contrib project that provides a drush command that replicates command from the Drupal console project: https://www.drupal.org/project/config_import_single

Would love it if this existed in drush (core) so the module wasn't necessary.

**Comment by joeparsons** [comment]
Would love it if this were added to Drush (core) and adding the contrib module weren't necessary.

**Comment by weitzman** [comment]
Done in #5146 and #5543
