### ISSUE TITLE
"You have requested a non-existent service" on "drush cset" (in drush v12)

### ISSUE THREAD

**Issue by sboden** [drush-ops/drush#5623]
I'm getting a "You have requested a non-existent service "cache.classic". Did you mean this: "cache.static"?" when doing a "drush cset" in drush v12, it works in drush v11.

I just installed "drupal/recommended-project:^10" (ending up with v10.0.9), when I install drush/drush composer opts for v12.0.0
I set up some basic modules including gin theme and gin toolbar

I'm trying to set some gin config in a shell script. So I use:

`drush cset gin.settings classic_toolbar classic -y`

and that gets me:

`You have requested a non-existent service "cache.classic". Did you mean this: "cache.static"?`

When I change `classic` in the command line  to `vertical` (the gin default) I get the error `You have requested a non-existent service "cache.vertical"`
I tried `drush cr`, that also doesn't help. Then I downgraded to drush 11 as in:

`composer require drush/drush:^11 -W`

and then the command line works as expected.

Both in v11 and v12 `drush cget` works properly, both giving the same output:

Command line: `drush cget gin.settings classic_toolbar`
Output: `'gin.settings:classic_toolbar': vertical`

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.0.0
| Drupal version? | 10.0.9
| PHP version     | 8.1
| OS?             | Linux

**Comment by weitzman** [comment]
Fixed by #5632
