### ISSUE TITLE
make doesn't download Drupal core for a distribution

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#563]
The docs at https://drupal.org/developing/distributions/drupalorg state that a drupal-org.make file is required, but that a drupal-org-core.make is optional:

> If your distribution requires patches to Drupal core, a -dev release, a checkout of a specific Git revision, or anything more complicated than an official release of core, you need to define how core should be built in a separate file called drupal-org-core.make.

However, without this file, drupal core is not downloaded when doing:

$ drush make --drupal-org drupal-org.make temp-directory

**Comment by greg-1-anderson** [comment]
Drush make is in maintenance only; closing.
