### ISSUE TITLE
hook_test_group_started() never called

### ISSUE THREAD

**Issue by alberto56** [drush-ops/drush#565]
Hi,

When running tests, the hooks invoked differ whether one is using Drupal's GUI, the script included with Drupal, or `drush test-run`. In all cases the way it is invoked is questionable, but perhaps Drush should work as the Drupal GUI:
- Drupal GUI: hook_test_group_started() is called before each test _class_.
- Drupal scripts/run-tests.sh: hook_test_group_started() is never called.
- `drush test-run Node` (for example): hook_test_group_started() is never called.

Some related issues:
- https://drupal.org/node/2234483
- https://drupal.org/node/2234479

**Comment by greg-1-anderson** [comment]
The Drush 8 command handler is in maintenance only; closing.
