### ISSUE TITLE
Enable drush archive-dump --extra (drush 8.x)

### ISSUE THREAD

**Issue by AndrewGearhart** [drush-ops/drush#5663]
**Is your feature request related to a problem? Please describe.**
Drush archive-dump does not allow for sql flags such as --no-tablespaces which makes it fail without separate configuration of the database server. 

**Describe the solution you'd like**
It would be great if the same --extra flag that is available to the sql-dump command would work with drush archive-dump (drush ard). This allows for that flag to be used when necessary.

**Describe alternatives you've considered**
This can be solved with a user .my.cnf, however, you are then setting that setting for all mysqldump commands. You can also solve this by setting the process permission which is considered by the mysql maintainers to be a security issue.

**Additional context**
By adding this flag as a command option, it can use the same underlying functionality as drush sql-dump to create the mysqldump command and allow people to successfully use drush ard as they continue to maintain their Drupal 7 sites on the way to Drupal 10!

**Comment by weitzman** [comment]
Drush 8 is getting security/significant fixes only. I suggest using drush configuration for sql-dump command.
