### ISSUE TITLE
drush autocomplete does not run

### ISSUE THREAD

**Issue by joelcollinsdc** [drush-ops/drush#567]
This line kills the autoomplete for me on ubuntu:

which drush > /dev/null || alias drush &> /dev/null || return

which drush has a return value of 0 for success, so this seems like it would never work:

EXIT STATUS
       0      if all specified commands are found and executable

```
   1      if one or more specified commands is nonexistent or not executable

   2      if an invalid option is specified
```

Also, i just typed 'man which' into a computer.  giggle.

**Comment by greg-1-anderson** [comment]
The Drush 8 command engine is in maintenance only. Closing.
