### ISSUE TITLE
How to share a patch for drush 11.6 to adapt variables strings to php8.2

### ISSUE THREAD

**Issue by FabRondeau** [drush-ops/drush#5691]
**Describe the bug**
After upgrading php from 8.1 to 8.2 (8.2.7), an error message is showing about ${var} format that should be written as {$var}.
See [This deprecation page](https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated)

**To Reproduce**
Upgrade Drupal 9.5.9 to 9.5.10.
In docker, upgrade you PHP version from 8.1 to 8.2.
run docker-compose up -d --build
Open bash with the command `docker exec -it <your container> bash`
run drush updb

**Expected behavior**
No warning should be displayed and the command should run.

**Actual behavior**
This returns a warning.

**Workaround**
Is there another way to do the desired action?
Instead of Docker, you can upgrade your PHP version in Apache2 or nginx.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.6 (please be specific, and try latest release)
| Drupal version? | 9.5.10
| PHP version     | 8.2.7
| OS?             | Linux

**Additional information**
I'm proposing a patch to fix the dependency consolidation/config.

**Comment by FabRondeau** [comment]
github.com/FabRondeau/consolidation_config/blob/2-0-6-patch/fix-var-format-for-php82.patch

**Comment by weitzman** [comment]
Please open a PR in https://github.com/consolidation/config if its not fixed already.

**Comment by weitzman** [comment]
Also the latest Drush is 12.
