### ISSUE TITLE
field:create: Add support for allowed text formats

### ISSUE THREAD

**Issue by DieterHolvoet** [drush-ops/drush#5692]
**Is your feature request related to a problem? Please describe.**
It doesn't look like https://www.drupal.org/project/allowed_formats/issues/3254013 is ever going to be committed. Which is fine, because allowed text formats were added to Drupal core: https://www.drupal.org/project/drupal/issues/784672

**Describe the solution you'd like**
Add a `FieldTextHooks` class with hooks adding an `allowed-formats` option to the `field:create` command. We'll be able to reuse the majority of the code from this MR: https://git.drupalcode.org/project/allowed_formats/-/merge_requests/2/diffs.

Since it was only added in Drupal 10.1, we should add a check to make sure the functionality is already present. Maybe somehow check the `field.field_settings.text` config schema for an `allowed_formats` key.

**Comment by DieterHolvoet** [comment]
Started a WIP PR, hooks are working but the Drupal 10.1 check still has to be added.

**Comment by weitzman** [comment]
Lets discuss in PR

**Comment by mayeulk** [comment]
@weitzman  & @DieterHolvoet 
Thank you very much for this commit!
Still, I ran into issues with this, for non-interactive use (IMHO, maybe the documentation is not ready yet?).

Seen in Drush Commandline Tool 13.6.0.0, Drupal 10.5.1, running:

    drush field:create node my_content_type  --field-name=tmp_test_1 \
        --field-label="Tmp Test 1" --field-type=text \
        --field-description="" --field-widget="text_textfield" --is-required=0\
        --cardinality=1 --allowed-formats=plain_text

- `drush field:create --help` does not advertise the` --allowed-formats` options (before finding it here in https://github.com/drush-ops/drush/issues/5692, I had to use xdotool to automate the interactive selection...)

The option is not described in :  https://www.drush.org/13.x/commands/field_create/#options
By the way: no html help either for:

    --link-type=LINK-TYPE                       Allowed link type.                                              
    --allow-link-text=ALLOW-LINK-TEXT           Allow link text.      
 
- The default allowed format is "- None -"; which means the following command creates a field which cannot be filled-in at all and blocks the data entry (maybe using "plain_text" as a default is a more sensible option?)
 
  drush field:create node my_content_type  --field-name=tmp_test_1 \
        --field-label="Tmp Test 1" --field-type=text \
        --field-description="" --field-widget="text_textfield" --is-required=0\
        --cardinality=1  --yes

- How to specify various allowed formats? Maybe adding an example would help.

I was thinking adding, in     drush/src/Commands/field/FieldCreateCommands.php, this code

    #[CLI\Option(name: 'allowed-formats', description: 'Allowed format(s)')]

But I realised that this option was not mentioned at all in this file (I probably missed something; sorry)

**Comment by DieterHolvoet** [comment]
I'll have a look when I find the time, but in the meantime PR's are always welcome.

**Comment by DieterHolvoet** [comment]
> drush field:create --help does not advertise the --allowed-formats options

Changing this in #6461.

> The default allowed format is "- None -"; which means the following command creates a field which cannot be filled-in at all and blocks the data entry (maybe using "plain_text" as a default is a more sensible option?)

That unnecessary _none option has been removed in #6420.

> How to specify various allowed formats? Maybe adding an example would help.

 By passing the `allowed-formats` option multiple times with different values.
