### ISSUE TITLE
The "field-type" option does not exist.

### ISSUE THREAD

**Issue by DieterHolvoet** [drush-ops/drush#5698]
**Describe the bug**
`composer mk:docs` fails after merging https://github.com/drush-ops/drush/pull/5693, but I'm not sure why. `FieldTextHooks:::hookOption` has `field-create` as target and that command definitely has a `field-type` option. The failing GitHub Action: https://github.com/drush-ops/drush/actions/runs/5506007220/jobs/10034112172

**Comment by DieterHolvoet** [comment]
@weitzman any idea?

**Comment by weitzman** [comment]
Fixed in #5700
