### ISSUE TITLE
drush cache:clear [ERROR] Value 'all' is invalid

### ISSUE THREAD

**Issue by NathanHealea** [drush-ops/drush#5703]
**Describe the bug**
when trying to clear all the cache for Drupal 10 using `drush cache:clear` the `all` option throws an error. 

**To Reproduce**
1. In a command line run `drush cache:clear`
2. when prompted for a selection, press enter. Indicating `all`

**Expected behavior**
All cache for the site should be cleared.

**Actual behavior**
Error message is presented, `[ERROR] Value "all" is invalid`

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.x
| Drupal version? | 10.x
| PHP version     | 8.x
| OS?             | Linux

**Additional information**
Drupal and Drush are running in the same docker container.

**Comment by weitzman** [comment]
Closed by #5704

**Comment by weitzman** [comment]
FYI there is no 'all' anymore. Use `drush cache:rebuild` instead
