### ISSUE TITLE
Ignore the maintenance_mode during the update process

### ISSUE THREAD

**Issue by eugene-brit** [drush-ops/drush#5707]
There is no ability to run `drush deploy` or `drush updb` commands without maintenance_mode enabling. I agree with that in 99% of cases, but sometimes I want to ignore the maintenance_mode.

I decided to add a new option `--no-maintenance` to these commands:
`drush deploy`
`drush updb`

I've added this option only for 11.5.1 for now as I use this version on the project.

**Comment by weitzman** [comment]
suggest making your own deploy command for customizations like this.
