### ISSUE TITLE
Fail Drush Deploy if Database Updates Produce a Diff Against Tracked Configuration

### ISSUE THREAD

**Issue by adamzimmermann** [drush-ops/drush#5712]
> If an update hook modifies configuration, then old configuration is imported, the changes made by the update hook are forever lost.
- https://www.drupal.org/project/drupal/issues/3110362

```
if (update hook changes config values to values different from config files) {
  abort deploy process
}
```

**Describe the solution you'd like**
```
$existing_diff = drush config:status
drush updatedb
$new_diff = drush config:status
if (diff_exists($existing_diff, $new_diff)) {
  fail the command?
}
```

**Describe alternatives you've considered**
We have talked about several, but nothing panned out as a serious viable alternative.

**Additional context**

Slack Discussion:

> It's not OK for updatedb to change config to values that differ from the deployment's saved config". Alas this complicates things badly.
- https://drupal.slack.com/archives/C45342CDD/p1689778091247189

**Comment by weitzman** [comment]
Lets talk in PR

**Comment by adamzimmermann** [comment]
Works for me. I'm unsure what the next steps there are though. I'll look to you for guidance.
