### ISSUE TITLE
A person who uses --dry-run with generate gets, included in the output, a drush command filled with --answer options so as to be able to easily re-do the precise dry run

### ISSUE THREAD

**Issue by mlncn** [drush-ops/drush#5721]
**Is your feature request related to a problem? Please describe.**

After doing something with dry run and identifying precisely the options needed for the right result, such as with `drush generate entity:bundle-class --dry-run` or any other [generator](https://www.drush.org/12.x/generators/all/), the task of doing it all again remains with the annoyance of human tedium and the frustration of human error.

**Describe the solution you'd like**

Drush knows what options were selected, and can summarize these in a way that can be copy-pasted to do the same without the dry run.

**Describe alternatives you've considered**

Remember the number options selected and text to retype.  Clearly this is not an essential feature but it would be nice, after the output, to have a message that says: "To produce the same output and save it to the file system, run:" with the requisite drush command.

**Additional context**

Just hoping this is an easy win that has not occurred to do, is all!

**Comment by weitzman** [comment]
It took me a while to understand the request, but now I do. You are using the interactive questions and want to later switch to non-interactive. @Chi-teck - would it be possible for drush generate to get the user's values after generation is complete?

**Comment by Chi-teck** [comment]
Generators are stateless. Though it might be technically possible to collect all user input and print a command with `--answer` options to terminal.
The use case seems too specific to me. The simplest workaround (besides using Git) is to dump the code to some stage directory for review.
```
drush generate entity:bundle-class --destination=/tmp/example
```
Once you the code reviewed it can be copied manually to the final destination.
