### ISSUE TITLE
Upgrade to Drush 11 breaks Drush with TypeError 

### ISSUE THREAD

**Issue by yotkadata** [drush-ops/drush#5722]
**Describe the bug**
I upgraded Drush from 10.6.2 to 11.6.0 using `composer require drush/drush:^11.0 --with-all-dependencies`. The upgrade ran smoothly, but when it's done, on any drush command, I get the following error:

> [error]  TypeError: Drush\Drupal\Commands\config\ConfigImportCommands::__construct(): Argument #3 ($configCache) must be of type Drupal\Core\Cache\CacheBackendInterface, Drupal\Core\Config\FileStorage given, called in /var/www/html/drupal/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 259 in Drush\Drupal\Commands\config\ConfigImportCommands->__construct() (line 172 of /var/www/html/drupal/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php) #0 /var/www/html/drupal/web/core/lib/Drupal/Component/DependencyInjection/Container.php(259): Drush\Drupal\Commands\config\ConfigImportCommands->__construct()
> #1 /var/www/html/drupal/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\Container->createService()
> #2 /var/www/html/drupal/web/core/lib/Drupal/Component/DependencyInjection/Container.php(434): Drupal\Component\DependencyInjection\Container->get()
> #3 /var/www/html/drupal/web/core/lib/Drupal/Component/DependencyInjection/Container.php(273): Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters()
> #4 /var/www/html/drupal/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\Container->createService()
> #5 /var/www/html/drupal/vendor/drush/drush/src/Boot/DrupalBoot8.php(306): Drupal\Component\DependencyInjection\Container->get()
> #6 /var/www/html/drupal/vendor/drush/drush/src/Boot/DrupalBoot8.php(253): Drush\Boot\DrupalBoot8->addDrupalModuleDrushCommands()
> #7 /var/www/html/drupal/vendor/drush/drush/src/Boot/BootstrapManager.php(291): Drush\Boot\DrupalBoot8->bootstrapDrupalFull()
> #8 /var/www/html/drupal/vendor/drush/drush/src/Boot/BootstrapManager.php(477): Drush\Boot\BootstrapManager->doBootstrap()
> #9 /var/www/html/drupal/vendor/drush/drush/src/Boot/BootstrapManager.php(412): Drush\Boot\BootstrapManager->bootstrapMax()
> #10 /var/www/html/drupal/vendor/drush/drush/src/Boot/BootstrapManager.php(384): Drush\Boot\BootstrapManager->bootstrapToPhaseIndex()
> #11 /var/www/html/drupal/vendor/drush/drush/src/Boot/BootstrapHook.php(32): Drush\Boot\BootstrapManager->bootstrapToPhase()
> #12 /var/www/html/drupal/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(44): Drush\Boot\BootstrapHook->initialize()
> #13 /var/www/html/drupal/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(36): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->doInitializeHook()
> #14 /var/www/html/drupal/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(29): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook()
> #15 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(145): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize()
> #16 /var/www/html/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(376): Consolidation\AnnotatedCommand\CommandProcessor->initializeHook()
> #17 /var/www/html/drupal/vendor/symfony/console/Command/Command.php(221): Consolidation\AnnotatedCommand\AnnotatedCommand->initialize()
> #18 /var/www/html/drupal/vendor/symfony/console/Application.php(1039): Symfony\Component\Console\Command\Command->run()
> #19 /var/www/html/drupal/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand()
> #20 /var/www/html/drupal/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
> #21 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run()
> #22 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun()
> #23 /var/www/html/drupal/vendor/drush/drush/drush.php(79): Drush\Runtime\Runtime->run()
> #24 /var/www/html/drupal/vendor/drush/drush/drush(4): require('...')
> #25 /var/www/html/drupal/vendor/bin/drush(120): include('...')
> #26 {main}. 
> [warning] Drush command terminated abnormally.

**To Reproduce**
Run `composer require drush/drush:^11.0 --with-all-dependencies` and the `drush status`

**Expected behavior**
Receive a Drush status report.

**Actual behavior**
The above mentioned error message is displayed.

**Workaround**
Not that I am aware of.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.6.0
| Drupal version? | 9.5.10
| PHP version     | 8.1
| OS?             | Linux (Debian)

**Additional information**
No.

**Comment by weitzman** [comment]
did you run `drush cr`. required after any code change

**Comment by yotkadata** [comment]
I wasn't aware of that.. Thanks for the hint Moshe, it seems to do the trick.
