### ISSUE TITLE
Uncaught TypeError in Drush\Config\Environment

### ISSUE THREAD

**Issue by MarttiR** [drush-ops/drush#5725]
**Describe the bug**
The `$docPrefix` property is of type `?string`, but it can get a `bool` assigned to it, which causes a TypeError.

**To Reproduce**
Make docs path resolution fail somehow, for example by adding `**/README*` in `.dockerignore`.

If the docs path cannot be resolved from any of the candidates, a TypeError occurs due to `false` return value propagating to the `$docPrefix` assignment.

**Expected behavior**
No fatal error occurs

**Actual behavior**
App crashes due to fatal error:
```console
Fatal error: Uncaught TypeError: Cannot assign bool to property Drush\Config\Environment::$docPrefix of type ?string in /var/www/html/vendor/drush/drush/src/Config/Environment.php:290
Stack trace:
#0 /var/www/html/vendor/drush/drush/src/Config/Environment.php(141): Drush\Config\Environment->docsPath()
#1 /var/www/html/vendor/drush/drush/src/Config/ConfigLocator.php(200): Drush\Config\Environment->exportConfigData()
#2 /var/www/html/vendor/drush/drush/src/Preflight/Preflight.php(184): Drush\Config\ConfigLocator->addEnvironment(Object(Drush\Config\Environment))
#3 /var/www/html/vendor/drush/drush/src/Preflight/Preflight.php(256): Drush\Preflight\Preflight->prepareConfig(Object(Drush\Config\Environment))
#4 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(58): Drush\Preflight\Preflight->preflight(Array)
```

**Workaround**
Fix whatever config is needed so that docs path resolution succeeds, e.g. remove/change `**/README*` or similar in `.dockerignore`.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.x
| Drupal version? | 10.x
| PHP version     | 8.x
| OS?             | Linux

**Additional information**
You can see how the error happens by following the call path:
https://github.com/drush-ops/drush/blob/12.x/src/Config/Environment.php#L281-L293
https://github.com/drush-ops/drush/blob/12.x/src/Config/Environment.php#L295-L306
https://github.com/drush-ops/drush/blob/12.x/src/Config/Environment.php#L318

**Comment by raileanunalexandru** [comment]
Facing exactly the same issue with Drush 12.1.2, on PHP 8.1 and Drupal 10.1.2

**Comment by weitzman** [comment]
PR welcome
