### ISSUE TITLE
generate action doesn't create the system.action.[action_id].yml file

### ISSUE THREAD

**Issue by socketwench** [drush-ops/drush#5727]
**Describe the bug**
When running `drush generate action`, Drush will generate the required plugin class, but will not create (or prompt you if you want to create) a system.action.[action_id].yml file necessary for Node Bulk Actions provided by Drupal core to appear.

**To Reproduce**
Run `drush generate action`, complete all on-screen prompts, the action YAML will not be generated.

**Expected behavior**
For node actions, a prompt should appear to ask if you want to create the system.action.[action_id].yml file.

**Actual behavior**
No system.action.[action_id].yml file is generated.

**Workaround**
Create the system.action.[action_id].yml file manually.

**Comment by Chi-teck** [comment]
> For node actions, a prompt should appear to ask if you want to create the system.action.[action_id].yml file.

Where would we place this config? Module config/install directory? Site-wide config directory?  Or just active config storage? 

I think creating action plugin and configuring it are too separate tasks.  A single plugin can be used in multiple configuration entities.  Also if the plugin was generated with "configurable" option it will have "example" option which is just a placeholder.  In this case a user is supposed to edit plugin code and define desired options for the plugin. Till the plugin code is updated there is no point to enable it.
This behavior is consistent with other plugin generators. Consider blocks. We generate a block plugin but do not put it to layout. That should be done manually through admin UI.

As of actions UI there were a couple really annoying issues. Fortunately those have been resolved recently. So actions can not be easily configured through UI as well.

https://www.drupal.org/project/drupal/issues/2815301
https://www.drupal.org/project/drupal/issues/2815297

Closing this as "won't fix".
