### ISSUE TITLE
Drush cache:rebuild does not apply css and js changes

### ISSUE THREAD

**Issue by BadWebCoder** [drush-ops/drush#5728]
**Describe the bug**
I have some sites on Drupal 10.1 with Drush 12
When I run `drush cache:rebuild` command, aggregation is not performed and CSS and JS changes are not applied. Changes are only applied when I rebuild cache via the admin toolbar. But after downgrade to Drush 11, `drush cache:rebuild` works, and CSS and JS changes are applied.

**To Reproduce**
- Update Drupal core to 10.1.1
- Update Drush to 12.1
- Run `drush cache:rebuild` in console

**Expected behavior**
CSS and JS changes applied to site

**Actual behavior**
CSS and JS change don't apply to the site

**Workaround**
I don't know

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.1
| Drupal version? | 10.1
| PHP version     | 8.1
| OS?             | Linux

**Additional information**
This issue is reproduced on Drupal 10.1.1 with Drush 12.1. 
Drupal 10.1 with Drush 11 or Drupal 10.0 with Drush 12.1 working as expected

**Comment by weitzman** [comment]
Drupal had a major change in https://www.drupal.org/node/3301716. CSS+JS clears during cache:rebuild and should be rebuilt in next request. If thats not happening, there is a bug somewhere.

**Comment by BadWebCoder** [comment]
I'm sorry, I forgot to attach these messages when I run `drush cache:rebuild`
```
[notice] The file assets://css was not deleted because it does not exist.
[notice] The file assets://js was not deleted because it does not exist.
```
But the files exist in the specified directories

> Drupal претерпел серьезные изменения в https://www.drupal.org/node/3301716 . CSS+JS очищается во время cache:rebuild и должен быть перестроен в следующем запросе. Если этого не происходит, значит где-то ошибка.

But I don't quite understand how to find the source of the problem. This problem occurs on three different sites on Drupal 10.1 that I support, and temporarily solved downgrading Drush to 11 is temporarily solved.
CSS and JS clears if I do it in other ways, but not through drush

**Comment by gitressa** [comment]
It looks like the owner for `css` and `js` folders is updated at some point, maybe by Drupal? See also https://www.drupal.org/project/google_tag/issues/3159778#comment-15187589.

**Comment by BadWebCoder** [comment]
I set up Xdebug to find out at what step everything goes wrong. As it turned out, everything goes on the step when the CSS and JS should be cleared. It does not see "assets://css" and "assets://js" as directories, and therefore cannot remove them.
If you start clearing the cache through the admin toolbar or through Drush 11, then he sees and clears these directories

**How I reproduced**: I set breakpoints in `FileSystem::deleteRecursive`. I entered `is_dir($path)` into the debug console and got `FALSE` through Drush 12 and `TRUE` through Drush 11. CSS and JS are not cleared because of this, as I understand it.
_______
> It looks like the owner for css and js folders is updated at some point, maybe by Drupal? See also https://www.drupal.org/project/google_tag/issues/3159778#comment-15187589.

No, my CSS and JS folders haven't changed in anyway. Owner and roles remain the same

**Comment by weitzman** [comment]
Thanks for digging in. I have no immediate thought on why those stream wrappers are not working with Drush 12. Summoning @Chi-teck @DieterHolvoet who worked on https://www.drupal.org/project/drupal/issues/3374395 and might have an idea.

**Comment by Chi-teck** [comment]
@BadWebCoder Try to update Drupal to version 10.1.2

**Comment by gitressa** [comment]
I am seeing this in 10.1.2:

```
$ drush cache:rebuild
PHP Warning:  unlink(/var/www/html/website.com/public_html/web/sites/default/files/css/css_Dd8YCdHfaQEgt3dWdSVw94rP7EmTUdfBCOWw7Z_fzr8.css): Permission denied in /var/www/html/website.com/public_html/web/core/lib/Drupal/Core/File/FileSystem.php on line 124
 [error]  Failed to unlink file 'assets://css/css_Dd8YCdHfaQEgt3dWdSVw94rP7EmTUdfBCOWw7Z_fzr8.css'. 

In FileSystem.php line 326:
                                                                                             
  Failed to unlink file 'assets://css/css_Dd8YCdHfaQEgt3dWdSVw94rP7EmTUdfBCOWw7Z_fzr8.css'.  
```
Versions:                                                
```
$ drush st
Drupal version   : 10.1.2                                                                
Site URI         : http://default                                                        
PHP binary       : /usr/bin/php8.2                                                       
PHP config       : /etc/php/8.2/cli/php.ini                                              
PHP OS           : Linux                                                                 
PHP version      : 8.2.8                                                                 
Drush version    : 12.1.0.0
```

I have previously chowned all folders to `webuser:www-data`, but it looks like Drupal reverts `js` and `css` to `www-data:www-data`. Did this a while ago:

```
$ cd /var/www/html/website.com/public_html/web/
$ chown -R webuser:www-data .
```
Owner has been changed at some point:
```
$ ls /var/www/html/gestamondo.com/public_html/web/sites/default/files/
total 24K
drwxrwx--- 3 webuser      www-data 4,0K Jun 18 19:31 config_gocPFbHI7[...]
drwxrwxr-x 2 www-data www-data 4,0K Aug 11 12:01 css
drwxrwxr-x 2 www-data www-data 4,0K Aug 11 12:02 js
drwxrwx--- 3 webuser      www-data 4,0K Aug 10 14:33 php
drwxrwx--- 2 webuser      www-data 4,0K Jun 18 19:31 styles
```

**Comment by gitressa** [comment]
I am seeing this in 10.1.2:

```
$ drush cache:rebuild
PHP Warning:  unlink(/var/www/html/website.com/public_html/web/sites/default/files/css/css_Dd8YCdHfaQEgt3dWdSVw94rP7EmTUdfBCOWw7Z_fzr8.css): Permission denied in /var/www/html/website.com/public_html/web/core/lib/Drupal/Core/File/FileSystem.php on line 124
 [error]  Failed to unlink file 'assets://css/css_Dd8YCdHfaQEgt3dWdSVw94rP7EmTUdfBCOWw7Z_fzr8.css'. 

In FileSystem.php line 326:
                                                                                             
  Failed to unlink file 'assets://css/css_Dd8YCdHfaQEgt3dWdSVw94rP7EmTUdfBCOWw7Z_fzr8.css'.  
```
Versions:                                                
```
$ drush st
Drupal version   : 10.1.2                                                                
Site URI         : http://default                                                        
PHP binary       : /usr/bin/php8.2                                                       
PHP config       : /etc/php/8.2/cli/php.ini                                              
PHP OS           : Linux                                                                 
PHP version      : 8.2.8                                                                 
Drush version    : 12.1.0.0
```

I have previously chowned all folders to `webuser:www-data`, but it looks like Drupal reverts `js` and `css` to `www-data:www-data`. Did this a while ago:

```
$ cd /var/www/html/website.com/public_html/web/
$ chown -R webuser:www-data .
```
Owner has been changed at some point:
```
$ ls /var/www/html/website.com/public_html/web/sites/default/files/
total 24K
drwxrwx--- 3 webuser      www-data 4,0K Jun 18 19:31 config_gocPFbHI7[...]
drwxrwxr-x 2 www-data www-data 4,0K Aug 11 12:01 css
drwxrwxr-x 2 www-data www-data 4,0K Aug 11 12:02 js
drwxrwx--- 3 webuser      www-data 4,0K Aug 10 14:33 php
drwxrwx--- 2 webuser      www-data 4,0K Jun 18 19:31 styles
```

**Comment by Chi-teck** [comment]
@gitressa 10.1.2 has another issue )
https://www.drupal.org/project/drupal/issues/3381293

**Comment by gitressa** [comment]
Ok, thanks for clarifying! I'll follow along in that issue then.

**Comment by Chi-teck** [comment]
I don't think Drush can help on this. All these issues need to be addressed in Drupal core.
So I propose we close this ticket.

**Comment by BadWebCoder** [comment]
> I don't think Drush can help on this. All these issues need to be addressed in Drupal core. So I propose we close this ticket.

Ok, I'll open issue in www.drupal.org core later.

**Comment by catch56** [comment]
Coming here from https://www.drupal.org/project/drupal/issues/3381610 there are a lot of commits to CacheCommands in drush 12 which aren't in drush 11, so I wonder if this has somehow broken stream wrapper registration in drush cr. I think this should be re-opened or a new issue opened to replace it.

**Comment by weitzman** [comment]
I just tried to reproduce this with Drush 12.x and Drupal  10.1.3-dev but am unable to do so.

FYI, you can more directly trigger asset deletion via `drush cc css-js`. 

Sounds like putting a breakpoint in \Drupal\Core\StreamWrapper\StreamWrapperManager::addStreamWrapper would be helpful. Thats what starts registration of the _assets_ stream wrapper. Thats called during Kernel::preload, during service instantation. The `stream_wrapper.assets` service is defined in core/core.services.yml

Also, please see if it is `assets://` that doesnt exist, or `assets://css`. One implicates stream_wrapper registration and rhe other implicates file permissions (usually)

**Comment by BadWebCoder** [comment]
The problem turned out to be different. I answered in detail here https://www.drupal.org/project/drupal/issues/3381610#comment-15199728.

I will open another issue later
