### ISSUE TITLE
Drush 7.x.5.9 Error: Bad CPU type in executable

### ISSUE THREAD

**Issue by stuzog** [drush-ops/drush#573]
Since installing 7.x.5.9 on OS X 10.9.2 I'm getting:

/Users/[user]/drush/drush: line 49: /sw/bin/tput: Bad CPU type in executable

at the start of every execution of a command. They complete,and everything seems to be working apart from that. Is this to do with having a 64-bit capable processor and 32-bit code? 

(See comment from Gulfie on Wednesday, April 16, 2008 at 10:40 pm at http://jwopitz.wordpress.com/2007/12/09/getting-mysql-mac-os-x-105-leopard-togetherfinally/)

**Comment by greg-1-anderson** [comment]
Drush 7 is EOL. Please use [Drupal Answers](http://drupal.stackexchange.com/questions/tagged/drush) for support requests.
