### ISSUE TITLE
Composer: Package webmozart/path-util is abandoned

### ISSUE THREAD

**Issue by jcvignoli** [drush-ops/drush#5731]
**Describe the bug**
Drush is using an obsolete composer library. When running a composer update, I get the following message from composer:
`Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.`

**To Reproduce**
do a "composer update"

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.4.12
| Drupal version? | 7.98
| PHP version     | 8.2
| OS?             | Linux

**Comment by weitzman** [comment]
Only urgent updates are going into Drush 8. This library is not used in modern versions.
