### ISSUE TITLE
DrushStyle choice function does not account for multi-select when returning answer

### ISSUE THREAD

**Issue by theteknocat** [drush-ops/drush#5732]
**Describe the bug**
When using the choice question type to prompt the user for MULTIPLE values, the choice method in DrushStyle returns a boolean false.

**To Reproduce**
Write something like this in a drush command:

`$answer = $this->io()->choice('your text here', $your_choices_array, $your_default_value, TRUE);`

Write some code to check the value of the $answer variable and display it in the console.

**Expected behavior**
The $answer value should match one or more of the selected values in the $your_choices_array variable.

**Actual behavior**
The $answer contains a boolean false value.

**Workaround**
In your drush command, add your own io() method to override the parent io() method. In there, when setting $this->io for the first time, you can have it instantiate an alternative style class to use. You can either use SymfonyStyle directly, or create your own class if you like the functions DrushStyle offers and just want to implement a fix to the choice method. In case of the latter, your class should extend SymfonyStyle (not DrushStyle) so you can copy the methods you like from DrushStyle into your class and update them as you desire.

To fix the choice method for multiselect, it just needs this before the existing return statement:

```
    if ($multiSelect) {
      return array_map(function ($value) use ($choices) {
        return array_search($value, $choices);
      }, $return);
    }
```

**Comment by weitzman** [comment]
Thanks. PRs welcome.
