### ISSUE TITLE
Broken Link on REPL Page

### ISSUE THREAD

**Issue by JCL324** [drush-ops/drush#5736]
**Existing document**
https://www.drush.org/11.x/repl/

**What are you attempting to do**
Trying to read the blog post on how to use.

**What should the documentation say instead?**
Looks like the site is gone. Maybe some other post is available to explain how to use this feature?

**Comment by weitzman** [comment]
Link "fixed" in 11.x and 12.x. Now uses google cached page.

**Comment by JCL324** [comment]
Awesome Moshe, thx!
