### ISSUE TITLE
Drush 12 don't see some settings that are added via `require_once` in settings.php

### ISSUE THREAD

**Issue by BadWebCoder** [drush-ops/drush#5739]
**Describe the bug**
My site settings consist of two parts: in `site/settings.php`, where the main site settings are located, and in `site/default/settings.php`, where individual settings are located, depending on the working environment (database, mail configs, etc. ). In `site/default/settings.php` I include the main settings via `require_once DRUPAL_ROOT . '/sites/settings.php';`
If I run `drush cache:rebuild` , I get an error: 
```
Missing $settings['hash_salt'] in settings.php
```
And if I transfer `$settings['hash_salt']` from `site/settings.php` to` site/default/settings.php` directly, then the error disappears. 
Also, drush does not see the directory settings for the public directory, for example. And instead of the `sites/default/files/public` I specified, it sees `sites/default/files`

But if, for example, transfer the database settings to `sites/settings.php` and run `drush sql-dump --result-file=sites/default/files/public/dump.sql`, then the dump will be successfully done. Or if you run `drush config-export`, it will export to the directory specified in `site/settings.php`

**To Reproduce**
The problem can be reproduced on pure Drupal

1. Install Drupal 10.1.2
2. Install Drush 12.1
3. `cp sites/default/settings.php sites/settings.php`
4. Clear `sites/default/settings.php` and paste:
    ```
    <?php

    require_once DRUPAL_ROOT . '/sites/settings.php';
    ```
5. Run `drush cache:rebuild `

**Expected behavior**
```
[success] Cache rebuild complete.
```

**Actual behavior**
```
Missing $settings['hash_salt'] in settings.php
```

**Workaround**
1. Add required settings to `sites/default/settings.php`.
    ```
    <?php

    require_once DRUPAL_ROOT . '/sites/settings.php';

    $settings['hash_salt'] = 'HASH_SALT';
    $settings['file_public_path'] = 'sites/default/files/public';
    ```
2. Run `drush cache:rebuild`

This will successfully clear the cache and clear the CSS and JS that are located in `sites/default/files/public`

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.1
| Drupal version? | 10.1.2
| PHP version     | 8.1
| OS?             | Linux/Windows

**Additional information**
This issue also occurs in Drupal 10.0 with Drush 12, but it defines the public directory correctly as specified in `site/settings.php`

**Comment by weitzman** [comment]
This isnt actually a Drush issue. Its PHP and possibly Drupal. Some things to investigate.

1. Is PHP actually getting to the require_once?
2. If so, is PHP loading the file you think it is? If not, what is the value of DRUPAL_ROOT
3. If site/settings.php is loading correctly, is something changing the value after the require_once?

**Comment by BadWebCoder** [comment]
Yes, `site/settings.php` is loading correctly because Drush sees some settings from `sites/settings.php`. Also, if comment `require_once DRUPAL_ROOT . '/sites/settings.php';` in `sites/default/settings.php` then errors like these will appear:
```
 Command config-export was not found. Drush was unable to query the database. As a result, many commands are unavailable. Re-run your command with --debug to see relevant log messages.
```

Even if leave only `require_once` in `sites/default/settings.php`, without changing any values, Drush it will ignore some settings in sites/settings.php, replacing them with the default settings (as `$settings['file_public_path']`) or not seeing them at all (as `$settings['hash_salt']`)

**Comment by weitzman** [comment]
I have no further ideas about your issue.
