### ISSUE TITLE
Drush 12 doesn't work with Drupal being in a symlink'd directory

### ISSUE THREAD

**Issue by MikeAnchor** [drush-ops/drush#5754]
**Describe the bug**
Drush fails to work when Drupal core's install path is a symlink. There's a check for an altered root being different to the root found another way in the preflight code, the first case uses `realpath()` and so resolves symlinks but the altered root does not causing the 2 methods to get different directories, even they're the same once symlinks are resolved.

**To Reproduce**

- We have `"www/core": ["type:drupal-core"],` in the `installer-paths` section
- Make the `www` a symlink to the folder Drupal's `core` folder is inside
- Run drush 12.x

**Expected behavior**
Drush to work.

**Actual behavior**
Drush fails to run with `[preflight] The alias references a Drupal site that does not contain its own copy of Drush. Please add Drush to this site to use it.`

**Workaround**
None

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.1.3.0
| Drupal version? | 10.1.2
| PHP version     | 8.1.22
| OS?             | Linux

**Comment by weitzman** [comment]
Lets discuss in PR
