### ISSUE TITLE
Drush updb with -r or --root fails

### ISSUE THREAD

**Issue by b3nkai** [drush-ops/drush#5756]
Drush updb fails if we pass a -r or --root option. The subprocess for updatedb:status adds a '=' to the --root option

`# vendor/bin/drush -r=docroot --uri=https://my-domain.com/ updb

In SiteProcess.php line 214:

  The command "/var/www/html/vendor/bin/drush updatedb:status --root==docroot --strict=0 --uri=https://my-domain.com/" failed.`

However, with the --root option AND an absolute path, it's working :

KO: vendor/bin/drush -r=docroot --uri=https://my-domain.com/ updb
KO: vendor/bin/drush -r=/var/www/html/docroot --uri=https://my-domain.com/ updb
KO: vendor/bin/drush --root=docroot --uri=https://my-domain.com/ updb
OK: vendor/bin/drush --root=/var/www/html/docroot --uri=https://my-domain.com/ updb

### System Configuration

| Q               | A
| --------------- | ---
| Drush version  | 11.x
| Drupal version | 10.x
| PHP version     | 8.x
| OS             | Linux

**Comment by greg-1-anderson** [comment]
I'd suggest using the workaround; Drush 11 won't be getting much attention.

Note that Drush 12 does not pay attention to the `--root` parameter; you should be able to simply remove it from your call once you upgrade to Drush 12.

**Comment by b3nkai** [comment]
This is what we'll do :)

You can close the issue it won't be fixed, at least we'll keep track of this problem here if anyone encounters it.

Thanks !

**Comment by greg-1-anderson** [comment]
Folks can re-open if interested; "PRs welcome" is best case, will-not-fix-please-upgrade is preferred.
