### ISSUE TITLE
sql:dump outputs deprecation warning with MariaDB 11

### ISSUE THREAD

**Issue by LordAro** [drush-ops/drush#5777]
**Describe the bug**

`sql:dump` uses a hardcoded `mysqldump` command. Since mariadb v11 `mysqldump` now outputs a deprecation warning

https://github.com/drush-ops/drush/blob/cb2610d5aa007b80bae4126b4cfb5454cd14dfe3/src/Sql/SqlMysql.php#L163

**To Reproduce**
What did you do?

Run `drush sql:dump`

**Expected behavior**
What did you expect would happen?

`drush sql:dump` to work cleanly

**Actual behavior**
What happened instead?

```
mysqldump: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb-dump' instead
```
output to stderr

**Workaround**
Is there another way to do the desired action?

Not that I'm aware of. Maybe dump command should be configurable?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.6 (but also git HEAD)
| Drupal version? | 9.5.11
| PHP version     | 8.1.23
| OS?             | Linux (but all)

**Additional information**

```
$ mariadb --version
mariadb from 11.1.2-MariaDB, client 15.2 for debian-linux-gnu (x86_64) using  EditLine wrapper
```

**Comment by weitzman** [comment]
We could add a driver for mariadb. We just have to be able to tell when thats in use over mysql.

**Comment by terryzwt** [comment]
`drush sqlc --extra=--skip-ssl` as a trick
