### ISSUE TITLE
Config import error messages have HTML entities

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#5778]
**Describe the bug**

Errors raised by the config system during a `drush cim` command show quote characters as HTML entities which makes them really hard to read.

**To Reproduce**

Do `drush cim` when the config has import problems.

**Expected behavior**

Readable error message shown

**Actual behavior**

```
In ConfigImportCommands.php line 318:

  The import failed due to the following reasons:
  Unexpected error during import with operation create for user.role.qa_reviewer_global: Attempt to save a confi
  guration entity &#039;qa_reviewer_global&#039; with UUID &#039;f70bcda0-5d4a-4173-a075-f64b02737e98&#039; when
   this UUID is already used for &#039;content_reviewer_global&#039;
```

The HTML entities make it really hard to read the key elements of the error message -- the UUID and the config names.

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | /11.0.9
| Drupal version? | 9.5
| PHP version     | 8.2
| OS?             | Mac

**Additional information**

**Comment by weitzman** [comment]
This comes from Drupal, not Drush. Drupal should not assume a web request context for its errors
