### ISSUE TITLE
Fatal error on php:cli command 

### ISSUE THREAD

**Issue by holo96** [drush-ops/drush#5779]
**Describe the bug**
When I try drush php:cli i get fatal error:
`[error]  ParseError: syntax error, unexpected token "\" in Drush\Commands\core\CliCommands->makeEntitiesAvailableWithShortClassNames() (line 1 of /var/www/html/vendor/drush/drush/src/Commands/core/CliCommands.php(319) : eval()'d code) #0 /var/www/html/vendor/drush/drush/src/Commands/core/CliCommands.php(97): Drush\Commands\core\CliCommands->makeEntitiesAvailableWithShortClassNames()`

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.2.0.0 
| Drupal version? | 10.1.5
| PHP version     | 8.2.10
| OS?             | Linux

### Solution
There is unnecessary escape character:
```patch
diff --git a/src/Commands/core/CliCommands.php b/src/Commands/core/CliCommands.php
index 934010264..e647ababd 100644
--- a/src/Commands/core/CliCommands.php
+++ b/src/Commands/core/CliCommands.php
@@ -316,7 +316,7 @@ final class CliCommands extends DrushCommands
                 continue;
             }
             // Make it possible to easily load revisions.
-            eval(sprintf('class %s extends \%s {
+            eval(sprintf('class %s extends %s {
                 public static function loadRevision($id) {
                     $entity_type_repository = \Drupal::service("entity_type.repository");
                     $entity_type_manager = \Drupal::entityTypeManager();
```

**Comment by weitzman** [comment]
@chx pls review

**Comment by chx** [comment]
I thought we rolled this back because of classname clashes? But yeah looks good to me.

**Comment by weitzman** [comment]
We ended up avoiding the conflicting class #5733

**Comment by chx** [comment]
Sorry! That was a root namespace , nothing to do with sprintf. I recommend the commit to be reverted (sorry again :( ) and OP to provide more details on what happens. 

The eval'd code intends to looks like this:

`class Node extends \Drupal\node\Entity\Node`

This is valid PHP. I can't imagine how would we produce invalid code here, the class name must exist or otherwise reflectionclass would fatal.

**Comment by chx** [comment]
Oh! Nevermind! https://3v4l.org/sXNUv

https://stackoverflow.com/a/36945446/308851

>  your namespace declarations in the setup code don't transfer to the code coming in from include/eval, and the functions which are defined there are defined in the global namespace.

**Comment by holo96** [comment]
@chx hmm, It seems in most cases there is no error but only on one type it is parsed like this:
```injectablephp
class ApplicationFile extends \\Drupal\application\Entity\ApplicationFile {}
```

I actually override file class in core system like this:
```injectablephp
/**
 * Implements hook_entity_type_alter().
 */
function application_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\ContentEntityType $file */
  $file = $entity_types['file'];
  $file->setClass('\Drupal\application\Entity\ApplicationFile');
}
```

When I remove leading backslash (\) it is working again

**Is additional leading backslash necessary?**

**Comment by chx** [comment]
> Is additional leading backslash necessary?

You could run `foreach (\Drupal::entityTypeManager()->getDefinitions() as $definition) { print $definition->getClass()."\n";}` to see it is not used by another entity class.

However, this change to drush _is_ good at the end of the day.
