### ISSUE TITLE
Drush entity:delete command (EntityCommands.php) should use batch processing since it runs out of memory if deleting thousands of entities

### ISSUE THREAD

**Issue by codebymikey** [drush-ops/drush#5784]
**Describe the bug**
When attempting to purge out certain entity types with lots of entities (think 500,000+). Which can be necessary when attempting to uninstall the module which created all those entities.

The Drush command attempts to load all the entities into memory first before processing them in chunks, this isn't feasible, and we should process the entities using batch similar to #4800

We can also introduce options to limit how many entities are affected by the `entity:save` and `entity:delete` commands, e.g. if only interested in saving/deleting the first N entities.

**To Reproduce**
Generate 500,000 entities and attempt to delete all the entities using `drush entity:delete {entity_type_id}`.

**Expected behavior**
It should be capable of efficiently deleting thousands of entities without issue.

**Actual behavior**
It throws the following exception:

```
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 16777224 bytes) in /app/web/core/lib/Drupal/Core/Database/StatementWrapper.php on line 294
 [warning] Drush command terminated abnormally.
```

**Workaround**
Not through the CLI currently as far as I'm aware.

**Comment by weitzman** [comment]
This has been possible for 3 years #4583. See --chunks option.

**Comment by codebymikey** [comment]
Hi @weitzman,

The `--chunk` option doesn't actually mitigate this specific issue.

In that issue, the results of the [`$result = $query->execute();`](https://github.com/drush-ops/drush/blob/ae5ad78/src/Drupal/Commands/core/EntityCommands.php#L68) call [returns an array](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21Query%21Sql%21Query.php/function/Query%3A%3Aexecute/10) of the 1,000+ IDs, it just doesn't load or process them into full entities yet. However, if there are more IDs in the database than can be feasibly loaded in memory (e.g. millions), then the command simply doesn't work - which is why handling it within a batch context is the more robust way of handling it.

And in terms of implementation, I was thinking something along the lines of [this](https://api.drupal.org/api/examples/batch_example%21batch_example.install/function/batch_example_update_8001/8.x-1.x) (but we can't use `n.nid > :nid` type logic since the entity might not be numeric), [this](https://www.thirdandgrove.com/insights/using-batch-api-and-hookupdaten-drupal-8/) or [this](https://gorannikolovski.com/blog/batch-processing-and-update-hooks-drupal-8).

**Comment by weitzman** [comment]
Thanks for clarifying. Can you really run out of memory just from a few million integers? That doesnt seem like a lot of memory consumption. What is your CLI memory_limit? Can it be bumped?

**Comment by codebymikey** [comment]
Hmm, thought about it a bit more after reviewing how many entities I had to delete (720,000), and you were right, and that seems like a feasible amount of entities IDs to be loaded in PHP. I had a memory limit of 256M on the CLI.
```bash
$ php -i | grep mem
memory_limit => 256M => 256M
```

And was able to resolve the issue by temporarily [increasing the memory limit](https://acquia.my.site.com/s/article/360005311613-Increasing-the-memory-limit-for-Drush) in my `settings.php` with the following:

```php
if (PHP_SAPI === 'cli') {
  # 512M still wasn't enough.
  ini_set('memory_limit', '-1');
}
```

But I guess it'd just be nice to have the code optimized to not require as much memory if possible.
