### ISSUE TITLE
`user.mail.yml` missing newline at end of file when exporting config

### ISSUE THREAD

**Issue by tyler36** [drush-ops/drush#5786]
**Describe the bug**
After exporting config, PHPCS reports `user.mail.yml` as missing new line at end of file.

**To Reproduce**

1. Export data via command

```shell
drush cex
```

2. Scan exported directory with PHPCS; below targets `./web/sites/default/files/sync`

```shell
$ phpcs --standard="Drupal,DrupalPractice" --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md,md,yml 
```

**Expected behavior**
No errors detected.

**Actual behavior**

```shell
$ phpcs
FILE:  XXXXXX/web/sites/default/files/sync/user.mail.yml
--------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------
 116 | ERROR | [x] Expected 1 newline at end of file; 0 found
```

It flags `user.mail.yml`. 
All other files are exported with end-of-file new line, so it seems strange that `user.mail.yml` isn't. 
The behavior should be consistent though, all files have it (... or none).

**Workaround**
I _could_ update my config to ignore all config files.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.6.0
| Drupal version? | 10.x/9.x/8.x/7.x
| PHP version     | 8.1.23
| OS?             |  Debian GNU/Linux 11 (DDEV container)

**Additional information**

**Comment by weitzman** [comment]
The export is performed by drupal api, not drush.

**Comment by tyler36** [comment]
Ah ... thank you.
