### ISSUE TITLE
DevelopmentProjectCommands broken on Drush 12

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#5789]
**Describe the bug**
This command class was working fine on Drush 11 and on Drush 12 the command is not getting picked up: https://github.com/joachim-n/drupal-core-development-project/blob/main/drush/Commands/core_development/DevelopmentProjectCommands.php

The problem is this code in ServiceManager::discover():

```
        // If a command class has a static `create` method, then we will
        // postpone instantiating it until after we bootstrap Drupal.
        $this->bootstrapCommandClasses = array_filter($commandClasses, [$this, 'hasStaticCreateFactory']);
```

That is assuming that hasStaticCreateFactory is doing so because it needs Drupal services, but in my case, I just need the class loader.

Presumably Drush's own CacheCommands isn't getting filtered out because it has a different discovery method? It looks like the filtering of command files with hasStaticCreateFactory() is only done in ServiceManager::discover()?

**To Reproduce**
What did you do?

**Expected behavior**

**Actual behavior**
What happened instead?

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.3
| Drupal version? | 11.x
| PHP version     | 8.2
| OS?             | Mac

**Additional information**

**Comment by weitzman** [comment]
You can use createEarly() instead of create() as per https://www.drush.org/12.x/dependency-injection/#createearly-method

**Comment by joachim-n** [comment]
Thank you for the super-fast response!

Did this have a deprecation warning? It's the second time the overridden cr command has broken in a new major version of Drush :(

**Comment by weitzman** [comment]
This project uses release notes for communicating changes like this.
