### ISSUE TITLE
final class on drush commands breaks modules that extend them

### ISSUE THREAD

**Issue by Bladedu** [drush-ops/drush#5792]
**Describe the bug**
I'm the maintainer of the drush_pre_deploy drupal module. https://www.drupal.org/project/drush_pre_deploy

Since this Pull request was merged https://github.com/drush-ops/drush/pull/5410 I can no longer extend the `DeployHookCommands` because it became final.

I know it's none of your business this, but before full refactoring (copy the entire class methods instead of extending it)  I'd like to know if there was a specific reason on using the `final` statement on these classes.

Thank you for any feedback.

**To Reproduce**
Use drush 12 and pull the module into the codebase and try to use it.

**Comment by weitzman** [comment]
Yes, there is a reason. It communicates that the right way to extend Drush commands is to use hooks - https://www.drush.org/12.x/hooks/#core-hooks. In your case, any method that wishes to run before deploy hooks should use the PHP Attribute `#[CLI\Hook(type: HookManager::PRE_COMMAND_HOOK, target: 'deploy:hook')]`. This makes [drush_pre_deploy](https://www.drupal.org/project/drush_pre_deploy) unneeded, as far as I can tell.

**Comment by Bladedu** [comment]
This is actually what the module does: https://git.drupalcode.org/project/drush_pre_deploy/-/blob/1.x/src/global/DrushPreDeployHookCommands.php?ref_type=heads#L18
 but we're using annotations instead of php attributes.

Thing is that the DeployHookCommands has many methods that are good to use as is,but making it final means I cannot reuse any of them.

So I don't think the module is unneeded. I still have case scenarios where I can use it (most of the time is major drupal upgrades of existing sites)

**Comment by Bladedu** [comment]
Thank you for your kind reply again.

You just confirmed what many people hints about you.

Much appreciated to cooperate with you
