### ISSUE TITLE
Unclosed quotes with CSV format

### ISSUE THREAD

**Issue by jigarius** [drush-ops/drush#5795]
**Describe the bug**
Say I run a Drush command that generates a table,

    drush generate:table --format=csv > report.txt

The result of this command seems to contain invalid CSV.

```csv
Path,"Size (Kb)","Test time (seconds)","Failed requests","Requests per second (mean)","Time per request"
/en,126.59,8.076,0,0.62,"1615.119 [ms] (mean)
```

Notice that the quotes are not closed after `(mean)`, so some CSV interpreters, say Numbers on MacOS, treat it as an unfinished cell value which makes them include the first cell of the next row into it, and so on. If the `"` were closed, then everything would be fine.

**To Reproduce**
Mentioned above.

**Expected behavior**

    /en,126.59,8.076,0,0.62,"1615.119 [ms] (mean)"

**Actual behavior**

        /en,126.59,8.076,0,0.62,"1615.119 [ms] (mean)

**Workaround**
None.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.4
| Drupal version? | 9.4.10
| PHP version     | 8.1
| OS?             | Linux

**Additional information**
None.

**Comment by weitzman** [comment]
Can you reproduce this with a core drush command? I cant

```
weitzman@mass-web:/var/www/html$ drush queue:list --format=csv
Queue,Items,Class
entity_reference_revisions_orphan_purger,4402,"Drupal\Core\Queue\DatabaseQueue"
entity_usage_regenerate_queue,0,"Drupal\Core\Queue\DatabaseQueue"
entity_usage_tracker,1050,"Drupal\queue_unique\UniqueDatabaseQueue"
mailchimp_transactional_queue,0,"Drupal\Core\Queue\DatabaseQueue"
mass_auto_parents_queue,0,"Drupal\Core\Queue\DatabaseQueue"
mass_bigquery_node_queue,0,"Drupal\Core\Queue\DatabaseQueue"
mass_content_api_descendant_queue,29,"Drupal\Core\Queue\DatabaseQueue"
mass_entityreference_org_field,0,"Drupal\Core\Queue\DatabaseQueue"
mass_entityreference_link_titles,0,"Drupal\Core\Queue\DatabaseQueue"
mass_flagging_email_queue,13,"Drupal\Core\Queue\DatabaseQueue"
mass_superset_data_queue,0,"Drupal\Core\Queue\DatabaseQueue"
mass_unpublish_reminders_queue,0,"Drupal\Core\Queue\DatabaseQueue"
media_entity_thumbnail,0,"Drupal\Core\Queue\DatabaseQueue"
scheduled_transition_job,0,"Drupal\Core\Queue\DatabaseQueue"
mass_utility_populate_media_states,0,"Drupal\Core\Queue\DatabaseQueue"
mass_utility_document_save,0,"Drupal\Core\Queue\DatabaseQueue"
mass_utility_doc_organization_transfer,0,"Drupal\Core\Queue\DatabaseQueue"
mass_utility_organization_sync,0,"Drupal\Core\Queue\DatabaseQueue"
mass_utility_revisions_cleanup,0,"Drupal\Core\Queue\DatabaseQueue"
```

**Comment by greg-1-anderson** [comment]
What does the data look like with `--format=yaml`? Just wondering if there are any embedded quotes, or anything odd like that.

**Comment by jigarius** [comment]
Here's how `--format=yaml` looks like:

```yaml
/en:
  document_path: /en
  document_length: '295.75'
  time_taken_for_tests: '0.673'
  failed_requests: '0'
  requests_per_second: '1.49'
  time_per_request: "672.744 [ms] (mean)\n672.744 [ms] (mean, across all concurrent requests)"
```

**Comment by weitzman** [comment]
If you can reproduce this with a core drush command please share. I will then reopen the issue.
