### ISSUE TITLE
'mode' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by ghost** [drush-ops/drush#58]
hi. i get error "'mode' is not recognized as an internal or external command, operable program or batch file" everytime i run drush status.

running on win8x64 via git bash + wamp and everything works fine, just installed drupal 7 via it but each time performing any cmd i get that nasty error.

**Comment by Lovor01** [comment]
C:\Windows\System32 is enough on 64 bit windows
