### ISSUE TITLE
Install with composer failed.  Windows 7, Drush 6, WAMP 

### ISSUE THREAD

**Issue by andrit** [drush-ops/drush#580]
When I call drush in cmd the error message states:  <blockquote>Unable to load autoload.php.  Drush now requires Composer in order to install its dependencies and autoload classes. Please see README.md.</blockquote>

I installed composer successfully using https://getcomposer.org/Composer-Setup.exe.  Then tried to install Drush <code> composer global require drush/drush:6.*</code>.  No error messages but I didn't copy so I can't say what the full response was.  It did mention dependencies...When I call <code>composer -v</code> it shows that it is installed.

Used two sites to guide me through (being I'm still learning) <a href="http://www.newmediacampaigns.com/blog/install-drush-for-drupal-7" target="_blank">http://www.newmediacampaigns.com/blog/install-drush-for-drupal-7</a> and <a href="https://gist.github.com/coreyp1/861733" target="_blank">https://gist.github.com/coreyp1/861733</a>. 

I changed the the PATH in Computer-->Properties-->Advanced System Settings-->Environment Variables.  with entries for Drush, bin, PHP, MySQL, and Composer.  
I am using PHP 5.4.3 and MySQL 5.5.24.

**Comment by mdeletter** [comment]
Probably I fixed the include error, see https://github.com/drush-ops/drush/pull/1082
I hope this will help you.

**Comment by alexkb** [comment]
I was seeing errors relating to preflight.inc not being found. I solved the problem by making sure I didn't have other versions of PHP in both the user and system paths, and then added both the drush php folder and the drush vendor folders to the path. So if drush was installed in c:\windrush, the following should be added to the path: `C:\windrush\php;C:\windrush\vendor\drush\drush`

I'm using Windows 7 and [Drush 7.0.0](https://github.com/drush-ops/drush/releases/download/7.0.0/windows-7.0.0.zip).

Hope that helps someone.

**Comment by greg-1-anderson** [comment]
Please use [Drupal Answers](http://drupal.stackexchange.com/questions/tagged/drush) for support requests.
