### ISSUE TITLE
role:perm:remove does not remove the permission

### ISSUE THREAD

**Issue by DrupalBubb** [drush-ops/drush#5802]
**Describe the bug**
While preparing the drupal 10 upgrade, the upgrade status module shows orphaned permissions from modules not deleting their permissions proper on deactivation. Drush seems to offer a cleanup, but it fails.

**To Reproduce**
`vendor/bin/drush role:list` shows the appropriate permissions:
anonymous:
  label: Gast
  perms:
    - 'access comments'
    - 'access content'
    - 'access site-wide contact form'
    - 'search content'
    - 'use text format restricted_html'
authenticated:
  label: 'Angemeldeter Benutzer'
  perms:
    - 'access comments'
    - 'access content'
    - 'access shortcuts'
    - 'access site-wide contact form'
    - 'create abstimmungen content'
    - 'edit own vote on comment:comment:field_comment_rating'
    - 'edit own vote on node:abstimmungen:field_voting'
    - 'post comments'
    - 'search content'
    - 'skip comment approval'
    - 'use text format basic_html'
    - 'vote on comment:comment:field_comment_rating'
    - 'vote on node:abstimmungen:field_voting'
content_editor:
  label: Redakteur
  perms:
    - 'access administration pages'
    - 'access content overview'
    - 'access contextual links'
    - 'access files overview'
    - 'access toolbar'
    - 'administer url aliases'
    - 'create article content'
    - 'create page content'
    - 'create terms in tags'
    - 'create url aliases'
    - 'delete article revisions'
    - 'delete own article content'
    - 'delete own page content'
    - 'delete page revisions'
    - 'edit own article content'
    - 'edit own comments'
    - 'edit own page content'
    - 'edit terms in tags'
    - 'revert all revisions'
    - 'view all revisions'
    - 'view own unpublished content'
    - 'view the administration theme'
administrator:
  label: Administrator
  perms: {  }

**Expected behavior**
Deleting a listed permission should work.

**Actual behavior**
`./vendor/bin/drush role:perm:remove authenticated 'edit own vote on node:abstimmungen:field_voting'` fails with this output:
 [error]  Permission(s) not found: edit own vote on node:abstimmungen:field_voting

**Workaround**
[https://www.drupal.org/node/3193348](https://www.drupal.org/node/3193348)

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.6.0
| Drupal version? | 9.5.11
| PHP version     | 8.1.25
| OS?             | Linux

**Additional information**

**Comment by weitzman** [comment]
Drush is not going to fix or otherwise babysit an orphaned permission. The behavior is not defined nor supported when trying to remove such permission.
