### ISSUE TITLE
If vendor folder is a symlink, drush crashes in infinite loop

### ISSUE THREAD

**Issue by bgnih** [drush-ops/drush#5807]
**Describe the bug**
I tried making the `vendor` folder a symlink that I could point to either `vendor.D9` or `vendor.D10` folders when testing our Drupal 9 to Drupal 10 migration process, thinking that this would save me from long `composer install` processes when switching between our D9 and D10 branches.   This resulted in drush no longer running properly and eventually crashing the docker container it was run in.

**To Reproduce**
Similar results in Lando and DDEV:
```
mv vendor vendor.D9
ln -s vendor.D9 vendor
drush --debug
```

**Expected behavior**
Expected the Drupal 9 version of the vendor file to be properly used and run drush out of that folder.

**Actual behavior**
Drush entered an infinite loop of exec'ing itself until (I assume) docker's resources were consumed and the container crashed.
The --debug output shows:
```
 [preflight] Redispatch to site-local Drush: '/var/www/html/vendor/drush/drush/drush'.
 [preflight] Redispatch to site-local Drush: '/var/www/html/vendor/drush/drush/drush'.
 [preflight] Redispatch to site-local Drush: '/var/www/html/vendor/drush/drush/drush'.
... forever until crashing
```

**Workaround**
Don't use symlinks to point to the vendor folder.   If needed, create separate `vendor.D9` and `vendor.D10` folders and copy or rename the one you want to be `vendor`.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.6.0
| Drupal version? | 10.x, 9.x
| PHP version     | 8.1
| OS?             | Mac + Lando and/or DDEV

**Additional information**
The problem is in the vendor/drush/drush/src/Preflight/RedispatchToSiteLocal.php script where it does not detect a vendor folder is a symlink and tries to repeatedly redirect itself to the "official" site-local version of drush (which is actually already running)

**Comment by weitzman** [comment]
Unfortunately, D9 and Drush 11 are now EOL so I dont think this is going to get much attention.

**Comment by bgnih** [comment]
I didn't think it would, I just wanted to document it in case anyone ran into the same issue so they could solve it easier, since there's still lots of D9 to D10 upgrades going on despite the EOL.   I'll check to see if it is still an issue in D10 + Drush 12.
