### ISSUE TITLE
Wrong path for drush-script option on docs website but correct in the source.

### ISSUE THREAD

**Issue by vladdancer** [drush-ops/drush#5810]
**Existing document**
https://www.drush.org/12.x/site-aliases/#additional-site-alias-options

**What are you attempting to do**
I'm trying to figure out correct config file structure to set `drush-script` setting.
 
**In what way is the existing documentation unclear or incomplete**
It seems that nested lists are rendered in one level. Examples: `ssh.options`, `paths.drush-script`.
Compare screenshots:
<img width="762" alt="Screenshot 2023-11-13 at 14 01 40" src="https://github.com/drush-ops/drush/assets/791060/e89ac679-e04a-4d4b-ad82-ab61b38161c4">
<img width="1081" alt="Screenshot 2023-11-13 at 14 01 03" src="https://github.com/drush-ops/drush/assets/791060/8d2affd7-b14f-4d05-aab4-0d67f1bd5641">

The structure in the source document is good (https://raw.githubusercontent.com/drush-ops/drush/12.x/docs/site-aliases.md)

**What should the documentation say instead?**
I wonder if this is a problem with MkDocs  or with theme?

**Comment by weitzman** [comment]
Thanks, fixed after a couple tries. Had to add 4 spaces

**Comment by vladdancer** [comment]
Thank you!

**Comment by vladdancer** [comment]
@weitzman seems like ssh.options and ssh.tty needs adjustemnts too.
<img width="1042" alt="image" src="https://github.com/drush-ops/drush/assets/791060/f99cdb9e-9364-44db-9398-6badd7492dbe">
