### ISSUE TITLE
Provide a replacement for Drupal Console generate:ajax:command

### ISSUE THREAD

**Issue by JPustkuchen** [drush-ops/drush#5834]
**Is your feature request related to a problem? Please describe.**
I just read through
https://weknowinc.com/blog/creating-custom-ajax-command-drupal-8
as I need a custom AJAX Command (AjaxResponse).

I first looked into `drush gen` but couldn't find a command for that.
`drupal generate:ajax:command` shows:

> drupal.sh is deprecated in drupal:10.1.0 and is removed from drupal:11.0.0. There is no replacement. See https://www.drupal.org/node/3241346

The command can be found here:
https://github.com/hechoendrupal/drupal-console-en/blob/master/translations/generate.ajax.command.yml

**Describe the solution you'd like**
Provide a drush gen replacement for that command to generate custom AjaxResponse Commands.

**Comment by weitzman** [comment]
This request belongs in https://github.com/Chi-teck/drupal-code-generator which drush uses.

**Comment by JPustkuchen** [comment]
Thanks @weitzman I didn't know that. I created that one here: https://github.com/Chi-teck/drupal-code-generator/issues/120
