### ISSUE TITLE
12.x drush cr "Failed to unlink file" on nfs filesystem

### ISSUE THREAD

**Issue by jacobsaw** [drush-ops/drush#5843]
**Describe the bug**

Since upgrading to 12.x from 10.x, we have had a sporadic issue during deployments where we encounter "Failed to unlink file..." after running `drush cr`.

We have an nfs filesystem running for our sites and what appears to happen is that on sites with a large amount of files in the css directory, drush now clears that directory out.

The problem is that nfs adds `.nfs` files that are being used by an active process since so many file changes are happening, and that causes an error since they cannot be deleted. The files are mounted to both an nginx and php container.

**To Reproduce**
What did you do?

Ran `watch ls -al PUBLIC_FILES_PATH/css` and observed files being removed and the `.nfs` files being added, and then observed that drush failed to unlink file error.

**Expected behavior**
What did you expect would happen?

No errors on drush cr.

**Actual behavior**
What happened instead?

Failed to unlink file.

**Workaround**
Is there another way to do the desired action?

Remove those directories and wait prior to drush running.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.x
| Drupal version? | 10.x
| PHP version     | 8.x
| OS?             | Linux

**Additional information**

**Comment by weitzman** [comment]
To clarify, it is Drupal core that is deleting all assets and throwing the error. https://api.drupal.org/api/drupal/core%21includes%21common.inc/function/drupal_flush_all_caches/10.1.x. I think this issue should be discussed in Drupal issue queue but I'll leave this open for a few days to see what others have to offer.

**Comment by jacobsaw** [comment]
> To clarify, it is Drupal core that is deleting all assets and throwing the error. https://api.drupal.org/api/drupal/core%21includes%21common.inc/function/drupal_flush_all_caches/10.1.x. I think this issue should be discussed in Drupal issue queue but I'll leave this open for a few days to see what others have to offer.

Thanks for pointing me in the right direction and appreciate it, I will open an issue there as well.

**Comment by jacobsaw** [comment]
For anyone else encountering this, it appears to be linked to this specific change: https://www.drupal.org/project/drupal/issues/3301573.
