### ISSUE TITLE
The alias  references a Drupal site that does not contain its own copy of Drush. Please add Drush to this site to use it

### ISSUE THREAD

**Issue by novia713** [drush-ops/drush#5844]
Every invocation of drush results in this error:
"_The alias  references a Drupal site that does not contain its own copy of Drush. Please add Drush to this site to use it_."

Just upgraded my site from 9 to 10 version. just did `composer require drush/drush`

drush should answer without errors

I always get the same error
`"The alias  references a Drupal site that does not contain its own copy of Drush. Please add Drush to this site to use it."`

Doesn't matter if i do `drush`, `ddev drush`, or `vendor/bin/drush`
i always get the same error 😢

my installed version of Drush is: *12.4.3*

**Comment by greg-1-anderson** [comment]
Did Composer create the symlink `vendor/bin/drush` on the target machine?

**Comment by greg-1-anderson** [comment]
What is the exact command you are running? Is this a simple `vendor/bin/drush status` or are you using an alias, e.g. `vendor/bin/drush @remote.dev status`?

**Comment by novia713** [comment]
i dont have any alias. yes, the symlink is there ... i can do `drush st` and also `vendor/bin/drush st` .... but the error message is always the same, as i stated before

**Comment by greg-1-anderson** [comment]
Does it provide any additional useful clues if you run with `--debug`?

**Comment by novia713** [comment]
i already can't know it because i started again the upgrade 9 to 10 again and i had success on that 2nd try ....

**Comment by greg-1-anderson** [comment]
Glad it worked itself out.
