### ISSUE TITLE
The database driver module's services are not available during installation

### ISSUE THREAD

**Issue by mondrake** [drush-ops/drush#5846]
**Describe the bug**
Installing Drupal via Drush, you cannot use a service defined in the database driver module's `.services.yml` file, as it seems the module's services do not get registered in the container.

**To Reproduce**
See [[META] Use events in Database Schema operations](https://www.drupal.org/project/drupal/issues/3410480#comment-15378807), comment #4.

**Expected behavior**
The service to be available.

**Actual behavior**
Service is not available.

**Workaround**
No

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.4.3
| Drupal version? | 11.x
| PHP version     | n/a
| OS?             | n/a

**Additional information**
Will add in due time.

**Comment by weitzman** [comment]
drush calls install_drupal() and then watches. not sure more drush should do here.

**Comment by mondrake** [comment]
For Drupal in its current stage, this is not a problem. It will become evident in the future if we will need event subscribers defined by modules to perform database schema operations. Most probably, yes, this would need changes to Drupal core rather than Drush. Anyway, let's close this for now and come back when (if) we will face this issue. Thanks
