### ISSUE TITLE
Command to clear and rebuild aggregiated CSS/JS

### ISSUE THREAD

**Issue by Greg-Boggs** [drush-ops/drush#5851]
**Is your feature request related to a problem? Please describe.**
Cache Rebuild no longer rebuilds JS and CSS aggregation when using custom libraries unless you manually increment version numbers on your libraries every time you edit CSS. 

**Describe the solution you'd like**
Since cache rebuild no longer rebuilds CSS/JS aggregation, it would be awesome to have a new command that does this, or an option for drush CR that includes forced JS/CSS agg rebuild.

**Additional context**
[Chromatic blog post explaining](https://chromatichq.com/insights/drupal-libraries-version/)

**Comment by catch56** [comment]
This doesn't quite match what actually happens:

1. drush cr deletes the aggregates on disk (check the css and js directories to confirm).

2. If a library definition has no version, then the aggregate hash includes a file_get_contents() of the files, this ensures that CDNs and browser caches are busted when the file changes.

So the only situation where CDN and browser caches don't get updated for a file change, is when it's changed without incrementing the version - but then why supply a version at all?

The only way to implement the feature requested here would be to add an additional bit of information into the aggregate hash, which is not really drush's job. But also if we did that, then caches for aggregates where all the assets are correctly versioned (or not versioned and not changed) would get busted for no reason.

**Comment by Greg-Boggs** [comment]
Since Drupal 8 was released, most documentation has included the version tag in the documentation for the library.yml file. Many of these documentation posts include version: VERSION even though that is clearly wrong, and no one has worked to correct it. So, if you Google a library.yml question, you're likely to get documentation from the Drupal community recommending a version: VERSION key.

Examples, but there are many many to choose from:

https://www.oreilly.com/library/view/drupal-8-development/9781788290401/7854d815-5fcf-455d-9d5a-0545fe94a05c.xhtml
https://www.drupal.org/docs/develop/theming-drupal/adding-assets-css-js-to-a-drupal-theme-via-librariesyml

So that means many thousands of Drupal sites that have a libraries file will now have a  CSS agg that won't clear, and they will not be finding the answer in Google. So, they will probably disable CSS aggregation to edit CSS.

**Comment by Greg-Boggs** [comment]
Here are examples of what folks are going to find when they look for help with this problem in Google:

https://www.drupal.org/forum/support/theme-development/2014-12-21/unable-to-turn-off-and-save-aggregate-and-compress-css
https://www.drupal.org/project/drupal/issues/3370828
https://drupal.stackexchange.com/questions/74878/cannot-change-css-after-css-js-aggregation

If you restrict your search to Drupal 10, the results don't get any better.
