### ISSUE TITLE
Sub-theme regions created with `drush generate theme` don't match

### ISSUE THREAD

**Issue by gitressa** [drush-ops/drush#5859]
**Describe the bug**

Drush supports creating a sub-theme, which is great (see [Generating a new sub-theme using Drush](https://www.drupal.org/docs/develop/theming-drupal/creating-sub-themes#s-generating-a-new-sub-theme-using-drush)).

But the regions are not copied over from the base theme into the sub-theme `*.info.yml` file, so they are different, and block placements are not inherited.

To make it work as expected, you need to manually copy the regions from base- to sub-theme, _before_ installing the sub-theme.

**To Reproduce**
Create a sub-theme with `drush generate theme`, set `olivero` as base theme.

**Expected behavior**
That the regions from the base theme Olivero would be present in the new sub-theme.

**Actual behavior**
The standard regions were present in the `*.info.yml` file, as when creating a stand alone theme.

**Workaround**
Manually copy the regions from the base theme to the sub-theme, before installing the sub-theme.

**Suggested solution**
Either update the code to make it copy over the regions, or add a note during step "#3 Base theme", that you need to copy over the regions manually.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.x
| Drupal version? | 10.x
| PHP version     | 8.x
| OS?             | Linux

**Additional information**

**Comment by weitzman** [comment]
The theme generator (and most other generators) comes from https://github.com/Chi-teck/drupal-code-generator/. Please post issues/PRs there.
