### ISSUE TITLE
Drush removes last path segment from alias root definition

### ISSUE THREAD

**Issue by GeMiSky** [drush-ops/drush#5866]
**Describe the bug**

After the upgrade to Drush 12 / Drupal 10.2, our (remote) Aliases stoped working.
The following error is displayed:
```
In SiteProcess.php line 214:

The command "ssh -t -o PasswordAuthentication=no sshshortcut '/var/www/vhosts/site.ch/httpdocs/vendor/bin/drush cex --uri=https://site.ch'" failed.

Exit Code: 127(Command not found)

Working directory:
```
To me it looks like drush removes the last path segment from the root path defined in self.site.yml.
The Path definde in self.site.yml is: /var/www/vhosts/site.ch/httpdocs/site.ch.
If i add an additional (arbitrary) segment to the root path such as /123, the commands are executed without errors.

**To Reproduce**
Install drupal 10.2 and drush 12
define alias in self.site.yml
execute any drush command.

**Expected behavior**
Drush should use the root path of Aliases without cuting segments.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version | 12.4.3
| Drupal version | 10.2.3
| PHP version     | 8.2-fpm
| OS            | Linux

**Comment by greg-1-anderson** [comment]
The path in the `root` element is intended to point to the Drupal root directory for your site. In Drush 12, only Composer-managed sites are supported. Drush assumes that your project root (the directory that contains composer.json and vendor) is one directory above your Drupal root. Other site layouts are not recommended, but if this assumption does not match your configuration, the recommended alternative is to omit the `root` directory and instead point `drush-script` at the full path to `vendor/bin/drush`.
