### ISSUE TITLE
Site aliases are not bootstrapped in Drush scripts

### ISSUE THREAD

**Issue by jnous** [drush-ops/drush#588]
Giving a site alias as the first parameter to a Drush script ("shebang" style) does not bootstrap the site specified by the alias. The same script works fine when executed via `drush @sitealias php-script`.

This does not help, either, although it returns TRUE:

``` php
drush_bootstrap_max_to_sitealias(drush_sitealias_get_record($sitealias));
```

Example script in https://gist.github.com/jnous/10869895. I'm using Drush 6.2.

**Comment by greg-1-anderson** [comment]
Drush 8 is in maintenance only. Closing.
