### ISSUE TITLE
Global option -d (--debug) has been deleted unintentionally

### ISSUE THREAD

**Issue by nsfisis** [drush-ops/drush#5888]
**Describe the bug**

The global option, `-d` (`--debug`), has been deleted unintentionally.

**To Reproduce**

Execute `drush topic core:global-options` or execute any `drush` command with `-d`.

**Expected behavior**

`-d` option works like `-vv`.

**Actual behavior**

`-d` option cannot be passed to any commands.

**Workaround**

Replace all `-d` with `-vv`.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.2.0
| Drupal version? | 10.1.4
| PHP version     | 8.1
| OS?             | Linux

**Additional information**

The option was removed by #5097. The commit message says [Conditionally keep --debug option](https://github.com/drush-ops/drush/pull/5097/commits/8f2199b6ff498c77fe5ff03292fd3ac865c7777c), but actually the option is not available now.

[This change in the above pull request](https://github.com/drush-ops/drush/pull/5097/files#diff-00ce90757b1e2f4249d3e36b770c52ad59fbc9d6f7148a08d1f2a896fcedb08fR56) might try to check whether the `-d` option was defined or not, but it does not work as intended.

```php
        if ($this->getDefinition()->hasOption('--debug')) {
            $this->getDefinition()
                ->addOption(
                    new InputOption('--debug', 'd', InputOption::VALUE_NONE, 'Equivalent to -vv')
                );
        }
```

`$this->getDefinition()->hasOption('--debug')` *always* returns false because `hasOption()` takes option names without `--` like `hasOption('debug')`. As a result, `-d` option is never defined.

**Comment by weitzman** [comment]
Hmm. Gone for a year and nobody said anything. Maybe it should just stay gone. Its a bit odd to be conditionally defined. Also, its still working for me (i.e with -d I see debug log messages).

**Comment by nsfisis** [comment]
> Also, its still working for me (i.e with -d I see debug log messages).

The `drush completion` command still accepts the `--debug` option. The issue concerns `--debug` no longer being available for any other drush commands, despite previously being available.

**Comment by weitzman** [comment]
--debug works for me on all commands.
