### ISSUE TITLE
makeEntitiesAvailableWithShortClassNames doesn't handle abstract entity classes

### ISSUE THREAD

**Issue by MakerTim** [drush-ops/drush#5899]
**Describe the bug**
Drupal\quiz has an entity defined at an abstract Class.
I don't know Drupal's standing in this if this is allowed or should be a bug-report on their side...
But the makeEntitiesAvailableWithShortClassNames that makes it possible to easily load revisions is currently bugged since it cannot instanciate an abstract class this way.

**To Reproduce**
Have an entity with an abstract class.
Or easier / more concrete:
Install the Quiz module, try to run a drush command (like `drush php`) and get the following error.
> Fatal error: Class QuizResultAnswer contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Drupal\quiz\QuizAnswerInterface::score, Drupal\quiz\QuizAnswerInterface::getResponse) in /var/www/html/vendor/drush/drush/src/Commands/core/CliCommands.php(320) : eval()'d code on line 1

**Expected behavior**
Or: It should try to use the correct hook for class-implementation (because now it ignores bundle-split class structures)
or as quick-win, don't instantiate classes that are abstract.

**Actual behavior**
What happened instead?
PHP fatal error.

**Workaround**
Is there another way to do the desired action?
Only by patching it / merge my incomming PR :) 

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | All
| Drupal version? | All
| PHP version     | All
| OS?             | All

**Additional information**
:) PR incomming

**Comment by MakerTim** [comment]
Relates to #5730 and #5729

**Comment by weitzman** [comment]
fixed
