### ISSUE TITLE
drush deploy -vvv doesn't give enough details

### ISSUE THREAD

**Issue by andrechun** [drush-ops/drush#5909]
**Describe the bug**
When running drush deploy -vvv it doesn't output as much details as intended. It would only use --verbose argument to drush updatedb, drush config:import, drush cache:rebuild and drush deploy:hook. It should instead also use -vvv for those commands.

**To Reproduce**
Run: drush deploy -vvv

**Expected behavior**
In the debug output, it should show in each step that it is also using -vvv i.e. drush cache:rebuild -vvv and not --verbose

**Actual behavior**
It shows that it is executing each step with just --verbose
```
>  [info] Executing: /var/www/html/vendor/bin/drush updatedb:status --verbose --strict=0 --uri=https://xxx
>  [success] No pending updates.
 [success] Config import start. [18.83 sec, 45.87 MB]
 [info] Executing: /var/www/html/vendor/bin/drush config:import --verbose --uri=https://xxx [18.83 sec, 45.87 MB]
```

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.4.3
| Drupal version? | 10.1.8
| PHP version     | 8.1
| OS?             | Linux

**Additional information**

**Comment by weitzman** [comment]
Sounds like a bug. The function responsible for gathering those options from the original request is \Drush\Drush::redispatchOptions
