### ISSUE TITLE
Config export for Search API index with an aggregated field separator keeps adding additional blank lines

### ISSUE THREAD

**Issue by RichardDavies** [drush-ops/drush#5911]
**Describe the bug**
I'm experiencing an issue where `drush cex` often wants to insert additional blank lines in the middle of a search API index config file. The empty lines are unnecessary and despite how many empty lines already exist in the file, it keeps adding more each time I run `drush cex`. Interestingly, when it lists the config that will be exported, search_api.index.my_index isn't listed as having changed, but the yml file is still modified with an additional blank line when the export is executed.

![Extra blank lines](https://github.com/drush-ops/drush/assets/13959/5de4ac47-862c-424f-9ddc-21cde701436a)

This issue seems to be related to having an aggregated field defined in the Search API index.

**To Reproduce**

1. Configure your site with Search API with a Solr server and create an index.
2. Go to the Search API index field definitions page at /admin/config/search/search-api/index/your_index_name/fields
3. Add an aggregated field. Select "union" as the aggregation type and select any two other fields as the contained fields and save your changes.
4. Run `drush cex` to export the config. The aggregated field will cause a `separator: |+` line to be included in the search_api.index.your_index_name.yml.
5. Make another configuration change to something on your site and then run `drush cex` again.
6. It will report that there are changes to another config that need to be exported (but no changes to the Search API index).
7. Proceed with the export and note that it silently updated your search_api.index.your_index_name.yml and added a blank line under the separator line.
8. Repeat steps 5-7 and note additional blank lines being added to the search API index config file with each export.

**Expected behavior**
Search API config file would only be updated when there are changes to that configuration. No blank lines would be added under the separator line.

**Actual behavior**
Search API config file is updated even when there are no changes to that configuration. Extra blank lines are added under the separator line with each export.

**Workaround**
I have to manually revert the changes to my search API config file every time I do a config export.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.4.3.0
| Drupal version? | 10.2.3
| PHP version     | 8.1.27
| OS?             | Linux

**Comment by RichardDavies** [comment]
See also https://www.drupal.org/project/search_api/issues/3425506

**Comment by weitzman** [comment]
Fixed there
