### ISSUE TITLE
Drush commands throw TypeError: ucfirst() when $databases array is empty

### ISSUE THREAD

**Issue by Supreetam09** [drush-ops/drush#5917]
**Describe the bug**
We recently upgraded from Drupal Core 10.1.8 to 10.2.3 and Drush from 11.6.0 to 12.4.3

After update `DocrootUpdate` task during ACSF deployment started failing:
```
>>> \drush8 -r '/mnt/tmp/drupal.01dev/acsf_temporary_repo/1709655175/docroot' status --fields drupal-version

TypeError: ucfirst(): Argument #1 ($string) must be of type string, null given in ucfirst() (line 122 of /mnt/tmp/drupal01dev/acsf_temporary_repo/1709655175/vendor/drush/drush/src/Sql/SqlBase.php).
```

Its not an issue with ACSF but with drush only. **ALL** basic drush commands failing with the same error.

**To Reproduce**
The same command was running fine in local but failing in ACSF. We figured out its only happening when `$databases` is set to empty array in `settings.php` and no overrides gets applied. If we make `$databases` empty - issue is reproducible in local too.
And yes - drush commands like `drush status` etc runs ok with empty databases.

In local, `$databases` is defined in `local.settings.php` - which does not get deployed - so at first the issue wasn't reproducible in local and we thought its some issue with ACSF only.
Also since its not yet deployed to cloud, and cloud database overrides settings isn't available during deployment/docrootUpdate task, hence `$databases` is empty `[]` - and thats how error in ACSF was thrown and identified.

**Note:** Setting `$databases` to empty array in Drupal Core 10.1.8 and Drush 11.6.0 - doesn't throw the error

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.4.3
| Drupal version? | 10.2.3
| PHP version     | 8.1.27
| OS?             | Mac

**Comment by Supreetam09** [comment]
Created PR https://github.com/drush-ops/drush/pull/5918

**Comment by weitzman** [comment]
Fixed via that PR
