### ISSUE TITLE
How drush database update works?

### ISSUE THREAD

**Issue by mohammadzo** [drush-ops/drush#5929]
I would like to know how `drush updb` command is working?
does it put the site on the maintenance mode first and the run the database update automatically ? or I should put the site on the maintenance mode then run database update?

**Comment by weitzman** [comment]
you put site in maint mode. updatedb doesnt do it.

**Comment by mohammadzo** [comment]
@weitzman Thank you very much

**Comment by mglaman** [comment]
For anyone finding this, it does set maintenance mode:

https://github.com/drush-ops/drush/blob/86f9205f7a8706847aaf8731d5967acb736f1bf9/src/Commands/core/UpdateDBCommands.php#L405C1-L409C10

```
        $original_maint_mode = \Drupal::service('state')->get('system.maintenance_mode');
        if (!$original_maint_mode) {
            \Drupal::service('state')->set('system.maintenance_mode', true);
            $operations[] = ['\Drush\Commands\core\UpdateDBCommands::restoreMaintMode', [false]];
        }
```
