### ISSUE TITLE
Drush commands for workspaces

### ISSUE THREAD

**Issue by malcomio** [drush-ops/drush#5933]
**Is your feature request related to a problem? Please describe.**
t would be useful to provide Drush commands for workspaces actions.

For example, to automatically publish a workspace in a test environment.

**Describe the solution you'd like**
A drush command to publish a workspace

**Additional context**
I'd created https://www.drupal.org/project/drupal/issues/3435823, but realised that it belongs in drush, rather than drupal core.

**Comment by weitzman** [comment]
Lets revisit when workspaces is out of beta for drupal core. Should be soon.

**Comment by thejimbirch** [comment]
Workspaces is now a stable module in core!
https://www.drupal.org/project/drupal/issues/3088643

**Comment by weitzman** [comment]
Lets work in the PR
