### ISSUE TITLE
Queue items don't have "item_id" if the queue is stored in Redis

### ISSUE THREAD

**Issue by jurgenhaas** [drush-ops/drush#5939]
**Describe the bug**

Claiming queue items in `\Drush\Commands\core\QueueCommands::run` throws a warning in line 103 as the item doesn't have the `item_id` property. Items from Redis queue do have a `qid` property instead.

**Comment by weitzman** [comment]
Sounds like we need a patch to Drush or Redis

**Comment by jurgenhaas** [comment]
@weitzman I've already provided a PR for drush, it's linked above.
