### ISSUE TITLE
PHP Fatal error:  Trait "Drush\Commands\AutowireTrait" not found in DevelCommands.php

### ISSUE THREAD

**Issue by MatthieuScarset** [drush-ops/drush#5941]
Upgrading to Drupal 10 with `drupal/devel: "^5.2"` 

Drush commands are broken with this error:
```
PHP Fatal error:  Trait "Drush\Commands\AutowireTrait" not found in /var/www/html/web/modules/contrib/devel/src/Drush/Commands/DevelCommands.php on line 25
```

**Workaround**

Fix the dependency in `Drush\Commands\DevelCommands`

### System Configuration
| Q               | A
| --------------- | ---
| Drush version  | 12.5.1
| Drupal version | 10.1.8
| PHP version     | 8.2
| OS?             | Linux

**Comment by charlieartist** [comment]
Can confirm this error as well when upgrading to Devel 5.2.x in Drupal 10.2.4, PHP 8.2, Drush 12.4.3.0.

**Comment by weitzman** [comment]
You need Drush 12.5+, and it must be a dependency of your composer built drupal site, as per Drush installation instructions. If someone has Drush 12.5 and still gets this error, please report if this file is present in your Drupal site vendor/drush/drush/src/Commands/AutowireTrait.php

**Comment by charlieartist** [comment]
Thanks—do you think it would be a good idea to list the minimum Drush version as a dependency, so that if an update to Devel is run via `composer update drupal/devel --with-dependencies`, issues like this could be avoided?

**Comment by weitzman** [comment]
That was recently done in https://gitlab.com/drupalspoons/devel/-/commit/097e359154c87de27f1a33df49b10074bf4fc9a4. Lets talk further in Devel project if needed.

**Comment by david-tissot** [comment]
Editing composer.json to
`"drush/drush": "^12.5"`
Did the trick, upgrading both Devel and D10 core. Thanks to @weitzman

**Comment by jamesgeldart** [comment]
Thanks, this sorted it for me.
`composer require --with-all-dependencies drush/drush:^12.5`
