### ISSUE TITLE
Add a command to generate batch service 

### ISSUE THREAD

**Issue by bhanu951** [drush-ops/drush#5945]
**Is your feature request related to a problem? Please describe.**

Please add a command to generate batch service. Currently there is no command to generate batch class. Hence we need to code same boilerplate code again and again.

**Describe the solution you'd like**
Create a generator class to generate batch service.

**Comment by weitzman** [comment]
Please make generator requests to https://github.com/Chi-teck/drupal-code-generator/. Thats what Drush depends on.
