### ISSUE TITLE
`test-run` doesn't find PHPUnit tests

### ISSUE THREAD

**Issue by TravisCarden** [drush-ops/drush#599]
I haven't taken the time to validate this outside my use case, but it seems like `drush test-run` doesn't find PHPUnit tests. I'm working in the 8.x-1.x branch of [Checklist API](https://drupal.org/project/checklistapi) module right now, for example. `drush test-run "Checklist API"` runs all my simpletests, but none of my PHPUnit tests, though they're in the same category in `getInfo()`. [PIFR runs them on d.o](https://qa.drupal.org/pifr/test/720088), and the Testing module finds them in the web UI. But I can't run them via Drush. I tried `drush test-run Drupal\checklistapi\Tests\ChecklistapiControllerTest` and `drush test-run ChecklistapiControllerTest`, but the command just terminates silently (c.f. https://github.com/drush-ops/drush/issues/477). Is Drush not finding the PHPUnit classes because they're not in the main PSR-0 directory structure? Is it user error? Is it a bug?

**Comment by joachim-n** [comment]
> I would like test-run to be reimplemented to be a wrapper around run-tests.sh. Thats the most maintainable solution, IMO.

Is there an issue for that? I've not managed to find one.

> We only need that wrapper so we get same arg/option parsing and can run tests against remote site aliases.

Also so you don't need to be in the site's root folder to run tests.

**Comment by cafuego** [comment]
... and so that tesing doesn't all start failing horribly when you upgrade drush versions when pear.php.net is dead and console-table download fails :-P

**Comment by weitzman** [comment]
Open a new issue for new test-run if desired.
