### ISSUE TITLE
Allow Drush site-install to install from recipes

### ISSUE THREAD

**Issue by thejimbirch** [drush-ops/drush#5999]
**Is your feature request related to a problem? Please describe.**
Drupal can now be installed using recipes, which bypasses the need for install profiles.

Users are currently using the `drupal quick-start` and `drupal install` scripts to install from recipes, but that only allows for an sql-lite database.  A must more real-world example will be to allow this from Drush, like most folks do to install Drupal now.

**Describe the solution you'd like**
Add an option like `drush site-install --recipe /path/to/recipe` which would follow the steps in the Drupal installer and install Drupal with no install profile, and apply the recipel

**Describe alternatives you've considered**
Allow for selecting no install profile.  We could then use the proposed `drush recipe` to apply recipes.

**Additional context**
N/A

**Comment by gitressa** [comment]
This would be a great feature, and [improve Starshot and DDEV integration](https://github.com/phenaproxima/starshot-prototype/issues/94#issuecomment-2132224833).

**Comment by greg-1-anderson** [comment]
See https://github.com/drush-ops/drush/pull/6026

**Comment by weitzman** [comment]
Lets use PR for discussion
