### ISSUE TITLE
(Un)Intentional usage of self::REQ in QueueCommands class

### ISSUE THREAD

**Issue by vensires** [drush-ops/drush#6003]
Hello,
I was trying to debug why a queue execution is not working as intended. I have it executed not in cron but by using the `drush queue:cron X` command without any parameters.

I stepped on top of the following code:
https://github.com/drush-ops/drush/blob/0a32bbb3869afd181457a1838d7c1740acc53df4/src/Commands/core/QueueCommands.php#L60

My question is if this is intentional. The `self::REQ` constant equals `Symfony\Component\Console\Input\InputOption::VALUE_REQUIRED` which equals `2`.

From what I have seen, the arguments are not really required; no error is generated if we call the command without `--time-limit` or other parameters. In that case though, it seems to me that _unintentionally_ the default value equals the 2 seconds.

Might be something I haven't clearly understood or be aware of; I would like a further clarification though.
Thank you very much!

**Comment by weitzman** [comment]
Yes its intentional. REQ means that if you do pass the option, it must have a value. When you dont pass the option, $options['limit] is null. At no point does it default to the integer 2.
