### ISSUE TITLE
Cannot set watchdog:show --severity-min level in English ("Warning"), when default language is something else

### ISSUE THREAD

**Issue by gitressa** [drush-ops/drush#6004]
**Describe the bug**

If you have a Drupal installation in another language than English, you cannot define the severity level in English but have to use the installation language, or numbers.

**To Reproduce**

Run this command with default language Danish, and get an error:

```
$ drush watchdog:show --severity-min=Warning
In WatchdogCommands.php line 337: Unknown severity level: Warning
Valid severity levels are: Nødsituation(0), Advarsel(1), Kritisk(2), Fejl(3), Advarsel(4), Notifikation(5), Info(6), Debug(7).
Failed to run drush watchdog:show --severity-min=Warning: exit status 1
```

On the other hand, using a number, like this, works well:

`$ drush watchdog:show --severity-min=4`

**Expected behavior**

That I could use `drush watchdog:show --severity-min=Warning` even if the default language is not English.

**Actual behavior**

I got an error.

**Workaround**

Use a number for severity level.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.5.1.0
| Drupal version? | 10.2.5 
| PHP version     | 8.1.27
| OS?             | DDEV in Linux 

**Additional information**

**Comment by weitzman** [comment]
I think you have to use the default language levels just like that error message is telling you. We could add an Example which illustrates this.

**Comment by gitressa** [comment]
That's a great idea.

Perhaps the error message could offer a workaround tip, something like this?

```
$ drush watchdog:show --severity-min=Warning
In WatchdogCommands.php line 337: Unknown severity level: Warning
Valid severity levels are: Nødsituation(0), Advarsel(1), Kritisk(2), Fejl(3), Advarsel(4), Notifikation(5), Info(6), Debug(7).
Either use the default language levels, or use a number. <<<< ADD THIS LINE?
Failed to run drush watchdog:show --severity-min=Warning: exit status 1
```
