### ISSUE TITLE
pm:enable installs a module even if hook_requirements returns 'severity' => REQUIREMENT_ERROR

### ISSUE THREAD

**Issue by wombatbuddy** [drush-ops/drush#6006]
If we run the following command: drush en -y my_module and the [hook_requirements returns](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_requirements/10
) 'severity' => REQUIREMENT_ERROR then Drush display the error message but still enables the module.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.5.2.0
| Drupal version? | 10.2.4
| PHP version     | 8.2.11
| OS?             | Linux

**Additional information**
The similar [4874](4874) issue is marked as closed here: https://github.com/drush-ops/drush/pull/4874

**Comment by simesy** [comment]
Just as a workaround, if this is a custom module you can add an exception for Drush. In the example below it prevents installing a module anywhere except locally on DDEV.

```
/**
 * Implements hook_requirements().
 */
function MY_MODULE_requirements(string $phase): array {
  $requirements = [];
  if ($phase == 'install') {
    $error = t('EXPLAIN WHY THE MODULE SHOULD NOT BE INSTALLED');

    if (getenv('IS_DDEV_PROJECT') != 'true' && php_sapi_name() == 'cli') {
        // Prevent user from bypassing with Drush.
        throw new \Exception($error);
      }

      // Normal Drupal install in the UI.
      $requirements['cc_test_no_production'] = [
        'severity' => REQUIREMENT_ERROR,
        'description' => $error,
      ];
    }
  }

  return $requirements;
}
```

**Comment by wombatbuddy** [comment]
Thanks Simon! 
Another workaround is in addition to implementing of the hook_requirements(), also uninstall a module in the hook_install().

**Comment by weitzman** [comment]
The requirement check only stops for interactive requests. Passing -y makes it non-interactive. This could be changed now that we have a new major version (13).

**Comment by weitzman** [comment]
I'm going to call this 'By Design'. The behavior you seek happens when you pass --no-interaction instead of of --yes. --yes is like passing --no-interaction with the addition of auto-replying 'yes'. to each confirmation prompt. Thats usually the equivalent to --no-interaction but some prompts, like this one, default to no and thus passing --yes overrides the default.

**Comment by simesy** [comment]
> with the addition of auto-replying 'yes'. 

I don't really understand this. Via the UI it's not possible to install it under any circumstance when hook_requirements returns REQUIREMENT_ERROR. It's got nothing to do with the arguments passed in.

**Comment by weitzman** [comment]
Drush is currently more permissive than the core UI. I think there is an argument for and against that.
