### ISSUE TITLE
Support installing directly from a recipe

### ISSUE THREAD

**Issue by gitressa** [drush-ops/drush#6011]
To facilitate better Starshot and DDEV integration, installing directly from a recipe would be a big help. For example:

`drush site:install recipes/starshot --db-url=mysql://user:pass@dbhost/db`

Originally discussed in https://github.com/phenaproxima/starshot-prototype/issues/94#issuecomment-2132224833.

**Comment by weitzman** [comment]
Thanks. Lets work in #5999

**Comment by gitressa** [comment]
Perfect, thanks.
