### ISSUE TITLE
drush migrate:fields-source vs. strict_types

### ISSUE THREAD

**Issue by nevergone** [drush-ops/drush#6012]
**Describe the bug**
Drupal migration source plugins return translated text (TranslatableMarkup)  in field descriptions. See: https://api.drupal.org/api/drupal/core%21modules%21user%21src%21Plugin%21migrate%21source%21d7%21User.php/function/User%3A%3Afields/10
The [strip_tags()](https://www.php.net/manual/en/function.strip-tags) PHP function given string in \Drush\Commands\core\MigrateRunnerCommands::fieldsSource() method.

Automatic type conversion cannot be used because of `declare(strict_types=1);`

**To Reproduce**
Load old Drupal-dump (for ex. Drupal7) and probe `drush mfs d7_user` command.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.x/13.x
| Drupal version? | 10.x/
| PHP version     | 8.x/
| OS?             | Linux

**Additional information**
Please cherry-pick for 12.x branch.

**Comment by claudiu-cristea** [comment]
@nevergone we need a PR

**Comment by nevergone** [comment]
https://github.com/drush-ops/drush/pull/6015

**Comment by nevergone** [comment]
Thanks.
