### ISSUE TITLE
drush pmu throws array to string conversion warning

### ISSUE THREAD

**Issue by acbramley** [drush-ops/drush#6025]
**Describe the bug**
When uninstalling a module that cannot be uninstalled, a warning is thrown.

```
$ drush pmu linkit
 [warning] Array to string conversion PmCommands.php:194

In PmCommands.php line 196:
                 
  linkit: Array  
```

This is because $reason in this case is an array of TranslatableMarkup.

**To Reproduce**
```
drush si standard
drush en linkit
drush uli
```
Visit `/admin/config/content/formats/manage/basic_html` and enabled the linkit filter

Try to run `drush pmu linkit`

**Expected behavior**
The validation warning is printed

**Actual behavior**
A PHP error is printed.

**Workaround**
Is there another way to do the desired action? Uninstall via the UI?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 13.x
| Drupal version? | 11.x
| PHP version     | 8.3
| OS?             | Linux

**Comment by acbramley** [comment]
![image](https://github.com/drush-ops/drush/assets/569927/d5183f86-3fa3-48a0-9c42-9ec2c9df07ed)

Debugging info

**Comment by weitzman** [comment]
TranslatableMarkup implements __toString so I dont know why the cast to string in the highlighted line would generate an warning.

**Comment by acbramley** [comment]
@weitzman `$reason` is an array of TranslatableMarkup as seen in the screenshot (although PHPStorm is showing object for whatever reason).

`ModuleInstaller::validateUninstall` returns an array of arrays.
