### ISSUE TITLE
Add PR template, with Fixes ISSUE link

### ISSUE THREAD

**Issue by gitressa** [drush-ops/drush#6038]
**Proposal**

You can connect an issue and its PR in Github by including `Fixes #<ISSUE>` in the issue summary, [Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

DDEV has a [PR template](https://github.com/ddev/ddev/blob/master/.github/PULL_REQUEST_TEMPLATE.md) which includes the related issue at the top. Eventually the format will be `- Fixes <#ISSUE>` so that the issue and PR are connected, like for example #6004 and #6037.

**Describe the solution you'd like**

Add a PR template for Drush, to make sure that issue and PR are connected, so instead of this in the right hand side of PRs:

> ## Development
> Successfully merging this pull request may close these issues.

... it will say:

> ## Development
> Successfully merging this pull request may close these issues.
> - #6037

**Remaining task**

Create a PR template file, and integrate it.

**Comment by weitzman** [comment]
OK, but I have no need or expectation or desire to have 2 places to discuss a thing. This might give the impression that there should be. I often close an issue if a related PR is opened.

**Comment by gitressa** [comment]
I have updated the template.

**Comment by gitressa** [comment]
With that workflow, this doesn't make much sense. On the other hand, here's a discussion about the pros and cons, in [Questioning necessity of having both a GitHub issue and PR](https://discuss.python.org/t/questioning-necessity-of-having-both-a-github-issue-and-pr/26776).

For Drush, PR's can be created as standalone solutions without an issue, which is fine. But if there is a corresponding issue, maybe to multiple PR's solving a single issue, it could be useful.

The template could add `(if relevant)` to highlight that an issue for a PR is not required ... what do you think?
