### ISSUE TITLE
Add backtrace to `watchdog:show-one`

### ISSUE THREAD

**Issue by andriokha** [drush-ops/drush#6065]
**Is your feature request related to a problem? Please describe.**
When an exception is logged to the dblog by `\Drupal\Core\EventSubscriber\ExceptionLoggingSubscriber::onError()` or `\Drupal\Core\Utility\Error::logException()`, there is no backtrace shown when using `watchdog:show-one` and it is very difficult to find the problem in code.

**Describe the solution you'd like**
Display the backtrace as a separate field.

**Additional context**
The reason the issue exists is because the log message doesn't by default contain the `@backtrace_string` placeholder (`\Drupal\Core\Utility\Error::DEFAULT_ERROR_MESSAGE` is `%type: @message in %function (line %line of %file).`). The issue was fixed in Drupal 10.2 and 11.x [here](https://www.drupal.org/project/drupal/issues/3175449) where they opted to add a new backtrace row.

**Comment by weitzman** [comment]
Lets close this and keep working in the PR  #6066
