### ISSUE TITLE
PHP 8.4 compatibility

### ISSUE THREAD

**Issue by andypost** [drush-ops/drush#6069]
PHP 8.4 alpha2 is out and `php -l` passes on 13.x branch but some vendor dependencies need fixes

General function deprecation  is coming https://wiki.php.net/rfc/deprecations_php_8_4
But for now nullable-declarations can be fixed https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated

- https://github.com/consolidation/config/pull/64
- https://github.com/consolidation/site-process/pull/80
- https://github.com/consolidation/annotated-command/pull/311
- https://github.com/consolidation/site-alias/pull/71
- https://github.com/consolidation/robo/pull/1165

external dependencies

- https://github.com/JetBrains/phpstorm-attributes/pull/29
- https://github.com/thephpleague/container/pull/261
- https://github.com/grasmash/expander/pull/20

- needs version [3.2.3](https://github.com/phootwork/lang/releases/tag/v3.2.3) https://github.com/phootwork/phootwork/pull/97#issuecomment-2391755952
- needs version [1.16.3](https://github.com/mck89/peast/releases/tag/v1.16.3) https://github.com/mck89/peast/pull/70
- version 1.30.0 https://github.com/symfony/polyfill-mbstring/commit/e5e7ddb00b859dbdf5ad8f3bbe4cd29a3a37aa34
- version 1.30.0 https://github.com/symfony/polyfill-php83/commit/4101e9edae47b36671a91857ab6cd359024faabd

**Comment by andypost** [comment]
Using oneliner `find . -name '*.php' -exec php -l {} \;`

And search in vendor `find vendor -name "*.php" -exec sh -c 'php -l "$1" 2>&1 | grep -v "No syntax errors detected in" || true' _ {} \; > php84-vendor.log`

[php84-vendor.log](https://github.com/user-attachments/files/16341196/php84-vendor.log)

**Comment by andypost** [comment]
Using official docker image
`docker run --rm -v $(pwd):/mnt -w /mnt php:8.4.0alpha2-cli-alpine find src -type f -name '*.php' -exec php -l {} \;`

**Comment by andypost** [comment]
Needs update `symfony/polyfill-mbstring` to 1.30.0 for 
https://github.com/symfony/polyfill-mbstring/commit/e5e7ddb00b859dbdf5ad8f3bbe4cd29a3a37aa34
and 1.30.0 for https://github.com/symfony/polyfill-php83/commit/4101e9edae47b36671a91857ab6cd359024faabd

**Comment by andypost** [comment]
also needs upgrade PhpStan but few of its dependencies not yet ready too

**Comment by andypost** [comment]
Example use of 8.4 in CI https://github.com/mck89/peast/commit/97dd57fb5bf58408361f906898646ac90fa278d0

**Comment by weitzman** [comment]
Thanks for this work, @andypost and @greg-1-anderson. Looks like the dependencies are making progress.

**Comment by andypost** [comment]
Please create new release for https://github.com/consolidation/annotated-command/pull/311

**Comment by andypost** [comment]
new release [3.2.3](https://github.com/phootwork/lang/releases/tag/v3.2.3) is out! for https://github.com/phootwork/phootwork/pull/97#issuecomment-2391755952

**Comment by andypost** [comment]
https://github.com/thephpleague/container/releases/tag/4.2.3 is out so only 1 dependency left

**Comment by andypost** [comment]
All dependencies are ready

**Comment by andypost** [comment]
moreover https://github.com/wodby/php/releases/tag/4.54.0 release is out with PHP 8.4 (no pcov/newrelic)

**Comment by weitzman** [comment]
Can this be closed? AFAIK we did this.

**Comment by andypost** [comment]
More remains found https://github.com/consolidation/site-alias/issues/72

**Comment by weitzman** [comment]
This is now complete?

**Comment by andypost** [comment]
I bet it is!

**Comment by andypost** [comment]
Next PHP version coming https://github.com/drush-ops/drush/issues/6349
