### ISSUE TITLE
Replace `pm` with `project`?

### ISSUE THREAD

**Issue by gitressa** [drush-ops/drush#6074]
## Problem

The command to install a module is `pm:install`. The `pm` part is a cryptic prefix, and noone knows what it means ...

[What does "pm" stand for?](https://groups.drupal.org/node/91784) (groups.drupal.org, September 2010)

## Solution

We could replace `pm` with the more meaningful `project`.

**Now**
```
pm:
  pm:install (in, install, en, pm-enable, pm:enable)     Enable one or more modules.
  pm:list (pml)                                          Show a list of available extensions (modules and themes)
  pm:uninstall (un, pmu)                                 Uninstall one or more modules and their dependent modules.
```

**Proposal**
```
project:
  project:install (in, install, en, pm-enable, pm:enable, pm:install)  Install one or more modules.
  project:list (pl, pml, pm:list)                                      Show a list of available extensions (modules and themes)
  project:uninstall (un, pmu, pm:uninstall)                            Uninstall one or more modules and their dependent modules.
```

`module` might work better, but on occasion themes need to be included, for example for the `list` command.

**Comment by weitzman** [comment]
I agree that project is a slight improvement but not enough to justify the effort and re-learning, even with command aliases.

**Comment by gitressa** [comment]
Yes, that was also my thought -- this might be too big a change.

I just thought of another approach: Add the more semantically correct `project` as an alias now, to allow switching to it in Drush 14:

```
pm:
  pm:install (in, install, en, pm-enable, pm:enable, project:install)   Enable one or more modules.
  pm:list (pml, pl)                                                     Show a list of available extensions (modules and themes)
  pm:uninstall (un, pmu, pu)                                            Uninstall one or more modules and their dependent modules.
```

**Comment by weitzman** [comment]
I don't think my cost/benefit calculation will be better at that time, even with the alias. Let's stick with pm.
