### ISSUE TITLE
Cannot extend from Drush\Commands\sql\SqlCommands

### ISSUE THREAD

**Issue by back-2-95** [drush-ops/drush#6086]
**Describe the bug**

We have a dump command which extends from Drush\Commands\sql\SqlCommands but now with Drush 13 it cannot be done as the class is final.

**To Reproduce**

Try 

```php
use Drush\Commands\sql\SqlCommands;

class MySqlCommands extends SqlCommands
```

**Workaround**

Copy the whole class I tried to extend from as my class.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 13.0.0
| Drupal version? | 10.3
| PHP version     | 8.3
| OS?             | Mac/Linux

**Question**

Could there be a change to do my thing somehow with hooks?

**Comment by weitzman** [comment]
Replace hook https://github.com/consolidation/annotated-command?tab=readme-ov-file#replace-command-hookThats by By design. See https://www.drush.org/13.x/commands/#altering-command-info and the
