### ISSUE TITLE
Allow  sql:sanitize on any database

### ISSUE THREAD

**Issue by Boegie** [drush-ops/drush#6091]
Currently, there seems to be no possibility to sanitize a database that isn't defined as the default database.

**Describe the solution you'd like**
Add the `--database` option to make it possible to select any database that is defined in `settings.php`.

**Comment by weitzman** [comment]
I don't know that I want to support non-primary databases here. We could run these queries via the Drupal DB API and not SqlBase. Some plugins in custom or contrib might be doing that already. Lets leave this as a patch that interested folks can use.
