### ISSUE TITLE
Assertion error when running `drush site:install`

### ISSUE THREAD

**Issue by ericmorand** [drush-ops/drush#6093]
We are using drush to install a Drupal 11 instance from a profile. When running `drush site:install` following the documentation, we get the following error:

```
Fatal error: Uncaught Assertion error: assert($this->bootstrap instance of DrupalBoot8)
```

After some investigation, it seems like drush expect that an `autoloader.php` file exists in `vendor/drupal` in order for `vendor/drupal/core` to be recognized as a proper core location.

Moving `vendor/drupal/core` to the root of the application during our deployment process doesn't solve the issue: drush seems to search for the location of `drupal/core` using the composer provided `installed.php` file, which of course mention `vendor/drupal/core`.

It is not clear why drush is making such assumptions as:

* The core is located alongside an autoload file
* The installation location of the core is provided by composer

Can you point us to the specification of Drupal core that establishes such a requirement? 

Can you point us to the documentation of drush that explains where Drupal core must be installed?

And can you please explain how we can make drush works without having to put an autoload file in `vendor/drupal`?

**Comment by weitzman** [comment]
I think you are focusing in on the call at https://github.com/drush-ops/drush/blob/68e5d4b4ced0846b2f74064e5399ad31b7a27225/src/DrupalFinder/DrushDrupalFinder.php#L26. That is a call to the Composer Runtime API, not a Drush API. That API is responsible for telling us where drupal/core has been installed. Drush just honors whatever composer says, so you can put drupal/core anywhere AFAIK. Drush has no requirement for a vendor/drupal/autoload.php file.

> The installation location of the Drupal core is provided by composer ... Can you point us to the specification of Drupal core that establishes such a requirement?

Its is *Drush's* assumption that you build your project with Composer. When you do that, Composer knows where everything has been installed and the line I linked to above works.

Apologies if I am focusing on the wrong part of the code. If I did, please show what you code you mean.

**Comment by Gogowitsch** [comment]
My gut feeling is that the issue comes from your `composer.json` file. Maybe you are missing "composer/installers" in your require section?

A good starting point is https://github.com/drupal/recommended-project.

**Comment by ericmorand** [comment]
Thanks to both of you. My point was that drush assumes that we are installing using composer - and more specifically that the location of composer.json drives the location of Drupal core.

Is it documented somewhere? And why is it working this way, instead of just taking the core path as argument?

**Comment by weitzman** [comment]
Its not documented anywhere outside the code. Drush has to be composer installed and thus the location of core is known to composer so an argument is uneeded - we can sk composer where core is. This saves the caller some work.
