### ISSUE TITLE
Contrib Drush Commands

### ISSUE THREAD

**Issue by holo96** [drush-ops/drush#6094]
I hope I haven't missed anything, and issue is appropriate.

**Existing document**
[Auto-discovered commands (PSR4)](https://www.drush.org/12.x/commands/#auto-discovered-commands-psr4)

**What are you attempting to do**
I've created command for drush inspired by drupal console's [config:export:entity](https://drupalconsole.com/docs/vn/commands/config-export-entity) but I am not sure where to contribute it. I don't think it should be module as it provides only drush commands so drupal.org is probably not an option, though I've seen some drush commands in form of module like drush language commands and/or devel entity updates.

So should contrib drush commands be on packagist or drupal.org or neither of those?

**In what way is the existing documentation unclear or incomplete**
Though docs say how to autoload commands, there is no documentation on where to put these packages. Also I haven't found anywhere in new docs what should be composer.json type property (drupal-drush).
If this is clearer, maybe you can see more contributions for drush.

**Comment by weitzman** [comment]
Its up to you. Packagist or drupal.org works fine. If you follow the rules outlined in that PSR4 doc, the commands get recognized. The homepage of www.drush.org has a link to https://packagist.org/search/?type=drupal-drush so use type=drupal-drush if you want to appear in this list. This is for marketing your extension - your commands work regardless of type.
