### ISSUE TITLE
Logger returned as wrong type - "Return value must be of type ?Drush\Drush\Log\DrushLoggerManager, Drupal\Core\Logger\LoggerChannel returned"

### ISSUE THREAD

**Issue by reece-oliver** [drush-ops/drush#6095]
**Describe the bug**
After upgrading to Drupal 10.3 (from 10.2) and Drush 13 (from 12) no drush commands are able to be ran afterwards. Running any error results in

```
TypeError: Drush\Commands\DrushCommands::logger(): Return value must be of type ?Drush\Drush\Log\DrushLoggerManager, Drupal\Core\Logger\LoggerChannel returned in Drush\Commands\DrushCommands-&gt;logger()
```

Removing the return type from the function
```
public function logger(): ?Drush\Log\DrushLoggerManager
    {
        assert(is_null($this->logger) || $this->logger instanceof DrushLoggerManager, 'Instead of using replacing Drush\'s logger, use $this->add() on DrushLoggerManager to add a custom logger. See https://github.com/drush-ops/drush/pull/5022');
        return $this->logger;
    }
```

Allows commands to run find and log correctly. I know obviously this isn't the correct fix. But would be good to know whats going wrong here

**To Reproduce**
What did you do?
Upgrade see above

**Expected behavior**
What did you expect would happen?
Commands to work fine

**Actual behavior**
What happened instead?
No commands run

**Workaround**
Is there another way to do the desired action?
Remove the return type on the function

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 13.0.1
| Drupal version? | 10.3.2
| PHP version     | 8.3
| OS?             | Linux

**Additional information**

**Comment by weitzman** [comment]
I seem to recall a contrib module injecting its own logger and causing this error. A backtrace might tell you who the offender is. Also search Drupal Slack for "DrushLoggerManager". I see a few relevant threads

**Comment by reece-oliver** [comment]
After updating all my contrib modules to latest versions, the issue is longer a problem. So I can only assume you were correct and the updated versions are now doing their logging correctly.
