### ISSUE TITLE
Allow sites to nominate which user is provided when a ULI is requested, without arguments

### ISSUE THREAD

**Issue by dpi** [drush-ops/drush#6098]
**Is your feature request related to a problem? Please describe.**

Recent developments in core with access policies resulting in https://www.drupal.org/node/2910500 allow the super user behaviour of uid1 to be nullified with a container parameter: `security.enable_super_user`

For many users and agencies, a standard approach to user1 has been utilized: a password is not known, requiring each person to request a one time login link (via `drush uli`) in order to be able to login to a site as an administrator/developer/root.

With the super user policy off, executing `drush uli` becomes less effective since the user returned is always user 1. This user may or may not have any super user rights, via a Role config `is_admin` flag.

**Describe the solution you'd like**

Drush can no longer can guarantee user 1 is useful.

`drush uli` should remain a default command for people, so they don't need to memorize and use `--name` or `--uid` for the user which has all the permissions. Which can differ between sites. Particularly as IDs, UUIDs, and usernames (randomisation https://drupal.org/project/user_password_randomizer) can be different per site.

Allow some kind of configuration, to allow a site to nominate a particular user as the default.

The configuration could be in a YAML, like drush.yml.

The configuration should accept either a UID or a UUID or a USERNAME. I can imagine the preference for this would be different depending on who put the site together, so all should be supported.

**Describe alternatives you've considered**

Painful memorization of what each site is doing.

**Comment by weitzman** [comment]
This seems covered by a command-specific option in Drush config (untested) 

```
#drush.yml
command:
  user:
    login:
      options:
        name: foo
```

Another good option for teams are composer scripts which wrap drush commands and specific options/arguments - `composer uli`

**Comment by dpi** [comment]
This seems viable.

Though I might suggest a UUID option for the ULI command. As UID/name can still vary per env in my case.

And are there any other commands that assume UID=1, that could take advantage of some kind of unified _default user_ concept? If not, then above seems just fine.

**Comment by weitzman** [comment]
I cant think of other commands that assume uid1.

**Comment by gitressa** [comment]
Thanks for the example, it works perfectly.

I would nominate it to be included in the [example drush.yml](https://www.drush.org/13.x/examples/example.drush.yml/) since [disabling uid 1 account is recommended](https://www.drupal.org/docs/administering-a-drupal-site/security-in-drupal/securing-the-admin-super-user-1) and have created an MR.
