### ISSUE TITLE
UTF-8 error on command "pear info pear.drush.org/drush"

### ISSUE THREAD

**Issue by leopoiroux** [drush-ops/drush#61]
Hi,
When I do a "pear info pear.drush.org/drush" I have an UTF-8 error and it causes problems when using Vagrant/Puppet.
Can you fix this ?
Thanks.

--------------

pear info pear.drush.org/drush
About pear.drush.org/drush-6.0.0
================================
Release Type          PEAR-style PHP-based Package
Name                  drush
Channel               pear.drush.org
Summary               command line shell and Unix scripting interface
                      for Drupal
Description           Drush is a command line shell and Unix scripting
                      interface for Drupal.
                       If you are unfamiliar with shell scripting,
                      reviewing the documentation
                       for your shell (e.g. man bash) or reading an
                      online tutorial (e.g. search
                       for &quot;bash tutorial&quot;) will help you
                      get the most out of Drush.
Maintainers           Moshe Weitzman <weitzman@tejasa.com> (lead)
                      Owen Barton <drupal@owenbarton.com> (developer)
                      Mark Sonnabaum <marksonnabaum@gmail.com>
                      (developer)
                      Antoine Beaupr� <anarcat@koumbit.org>
                      (developer)
                      Greg Anderson <greg.1.anderson@greenknowe.org>
                      (developer)
                      Jonathan Ara�a Cruz <jonhattan@faita.net>
                      (developer)
                      Jonathan Hedstrom <jhedstrom@gmail.com>
                      (developer)
Release Date          2013-08-16 18:09:14
Release Version       6.0.0 (stable)
API Version           6 (stable)
License               GPL
                      (http://www.opensource.org/licenses/gpl-license.php)
Release Notes         Initial release.
Required Dependencies PHP version 5.0.0
                      PEAR installer version 1.4.0 or newer
package.xml version   2.0
Last Modified         2013-09-03 19:52
Previous Installed    - None -
Version

**Comment by jonhattan** [comment]
Pear is no longer supported. For installing drush with puppet I suggest this module https://forge.puppetlabs.com/jonhattan/drush (yep I'm the maintainer).

**Comment by openHirn** [comment]
It seems like a bunch of things is "no longer supported" with Drush. For the first time in about five years, we will now re-consider Drush support. Sorry to say that, thanks for the good work in the past and honestly good luck with whatever.
