### ISSUE TITLE
Default SDC's thumbnail file should be PNG (not JPG)

### ISSUE THREAD

**Issue by MatthieuScarset** [drush-ops/drush#6100]
**Describe the bug**
When generating a SDC the thumbnail image file should be a PNG not a JPG as [per this code in core 11.x](https://git.drupalcode.org/project/drupal/-/blob/11.x/core/lib/Drupal/Core/Theme/Component/ComponentMetadata.php#L178).

**Expected behavior**
`thumbnail.png`

**Actual behavior**
`thumbnail.jpg`

**Workaround**
Delete the file manually.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.5.3.0
| Drupal version? | 10.3.2
| PHP version     | 8.1.28
| OS?             | Linux

**Comment by MatthieuScarset** [comment]
https://github.com/Chi-teck/drupal-code-generator/pull/181

**Comment by weitzman** [comment]
Thanks. Lets work in the DCG PR

**Comment by MatthieuScarset** [comment]
I'm sorry I don't understand what you mean. Should I open another PR somewhere else? 

TY
