### ISSUE TITLE
Drush 12.2 docs -- drush locale:import-all example command (complex) uses --types instead of --type

### ISSUE THREAD

**Issue by Martin-B** [drush-ops/drush#6105]
**Existing document**

https://www.drush.org/12.x/commands/locale_import-all/

**In what way is the existing documentation unclear or incomplete**

The example command in the documentation

`drush locale:import-all /var/www/translations/custom --types=customized --override=all`

uses argument `--types` instead of `--type`, drush responds with error

**What should the documentation say instead?**

`drush locale:import-all /var/www/translations/custom --type=customized --override=all`

**Comment by weitzman** [comment]
Fixed in #6106
