### ISSUE TITLE
DrushStyle class not found because src-symfony-compatibility/ not defined in psr-4 autoload

### ISSUE THREAD

**Issue by pbonnefoi** [drush-ops/drush#6110]
Updating to Drush 13, I had to work around some previous unit test from our project on custom drush commands. We were mocking SymfonyStyle which now is DrushStyle. Though DrushStyle is in the 'src-symfony-compatibility/' directory which is not defined in psr-4 autoload and therefore I have a Class not found error when runnning my tests.

As a workaround, I was able to declare the right autoload in my root composer.json like this :

```
    "autoload": {
        "psr-4": {
            "Drush\\Style\\": "vendor/drush/drush/src-symfony-compatibility/v6/Style",
            "Drush\\Symfony\\": "vendor/drush/drush/src-symfony-compatibility/v6/Symfony"
        }
    }
```

### System Configuration
Drush version => 13.x
Drupal version => 10.x
PHP version => 8.x
OS => Mac

**Comment by weitzman** [comment]
That works. Drush cant do that because we need to support multiple symfony versions. 

Here is alternative code which may work for folks https://github.com/drush-ops/drush/blob/13.x/phpstan-bootstrap.php
