### ISSUE TITLE
Add support for `watchdog:show --exclude-type`

### ISSUE THREAD

**Issue by gitressa** [drush-ops/drush#6148]
**Is your feature request related to a problem? Please describe.**

If you have installed a Drupal site in another language than English, you may get a lot of "English translation file not found" errors for all contrib modules (for example https://ftp.drupal.org/files/translations/all/metatag/metatag-2.0.2.en.po.) at every Cron run.

See [Drupal install throwing "Translation file not found" notice for "en" langcode when "translate_english" is set to false](https://www.drupal.org/project/drupal/issues/3218674).

These false positive entries can fill up the database log, and thereby `drush watchdog:show` output.

**Describe the solution you'd like**

As a workaround, it would be nice to be able to exclude a type. For example:

```
drush watchdog:show --exclude-type=locale    Exclude messages of type locale
```

This could also be a nice feature for example for Cron, which has a lot of entries.

**Describe alternatives you've considered**

You could enter all the other types, but that is clunky.

**Comment by weitzman** [comment]
You want Drush's [output filtering feature](https://www.drush.org/13.x/output-formats-filters/#output-filters). It is criminally underused. This use case is solved by `drush watchdog:show --filter="type!=locale"`. A lot of options in watchdog:show could alternatively be done with output filters.

**Comment by weitzman** [comment]
Anyone is welcome to add another Example in Help with this info.

**Comment by gitressa** [comment]
Thanks for making me aware of the output filter in Drush, that is indeed very cool!

I created an MR, which adds your example to the list of Watchdog help items, since that command is one where the `filter` feature can often be useful.

**Comment by gitressa** [comment]
Thanks, very fast! I just re-read the sentence, and realized that the filter feature, which is the main character here, is not mentioned ... Perhaps this would be better?

Now:
> Exclude rows via the negation operator !

Better?
> Exclude rows with the filter feature, via the negation operator !

**Comment by weitzman** [comment]
Yes, its better. I have some sad news to report tho. Drush is moving  even further toward a native Symfony Console setup and these example descriptions may be a casualty. See https://github.com/symfony/symfony/issues/45050

**Comment by gitressa** [comment]
Losing the examples under each Drush command would definitely be a setback ... it's so great to have them available right there when you need them.

I hope, since Drupal and Drush are big players (I assume) in the Symfony world, that they may help steer Symfony in a direction where some kind of help feature can stay available in Drush.

**Comment by gitressa** [comment]
Oh, and about the little improvement, should I make a new PR, or can you do it directly?

**Comment by gitressa** [comment]
By the way, wouldn't it be cool if you as a user could get a list of types present in the log?

Perhaps a new parameter like `--list-types`could list them?

```
$ drush watchdog:show --list-types 
  Recognized types are: access denied, block, content, cron, facets, geofield, language, locale, menu, node, page not found, pathauto, path_alias, php, search_api, simple_sitemap, structure_sync, system, user, xmlsitemap.
```

This could also help clear up if it's `access_denied` or `access denied`, `simple sitemap` or `simple_sitemap`, etc. 

You can trigger this by running a "faulty" command like `drush watchdog:show --type=dont_exist`, but having to error to get info doesn't seem right.
