### ISSUE TITLE
Drush generate phpstorm-meta command inserts unwanted line break in generated metadata comments

### ISSUE THREAD

**Issue by Gonzalo2683** [drush-ops/drush#6178]
**Describe the bug**
The `drush generate phpstorm-meta` command is generating a syntax error in PHP Storm metadata files. Specifically, it's inserting an unwanted line break in the view comments and other generated files (config_entity_ids.php, entity_bundles.php, entity_links.php), resulting in an incorrect structure that affects autocompletion. In my case, the comments are generated in Spanish because my site's default language is Spanish.

**To Reproduce**
1. Install Drupal 10.3.9 with PHP 8.3.14
2. Install Drush 13.3.0
3. Run the command: `drush generate phpstorm-meta`
4. Check the generated files in the `.phpstorm.meta.php` folder

**Expected behavior**
The comment should be generated in a single continuous line (regardless of the site's language), like:
```php
// -- View in context: View Entity Type.
  registerArgumentsSet('view__ids',
```

Or in Spanish (if that's the site's language):
```php
// -- Vista en contexto: Tipo de entidad Vista.
  registerArgumentsSet('view__ids',
```

**Actual behavior**
The comment is generated with an unwanted line break (shown here in Spanish due to site language):
```php
// -- Vista
en contexto: Tipo de entidad Vista.
  registerArgumentsSet('view__ids',
```

**Workaround**
A temporary solution could be to manually edit the generated files to fix the line breaks, or use a search and replace script to correct the format after generation.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 13.3.0.0
| Drupal version? | 10.3.9
| PHP version     | 8.3.14
| OS?             | Linux

**Additional information**
This issue affects multiple generated files:
- config_entity_ids.php
- entity_bundles.php
- entity_links.php

The problem appears to be consistent across all installations with this specific configuration and affects PHPStorm's autocompletion functionality. The comments are generated in the site's default language (Spanish in my case), which is expected behavior, but the line break issue seems to be a separate bug that needs to be addressed.

**Comment by weitzman** [comment]
Please file issue at https://github.com/Chi-teck/drupal-code-generator, where this functionality lives.
