### ISSUE TITLE
Removal of global option "no" is gone? Currently parsing it like --yes !

### ISSUE THREAD

**Issue by MakerTim** [drush-ops/drush#6179]
**Describe the bug**
I cannot find the docs, but we used to do commands as dry-run / sanity check;
Things like `drush cim -n` (kinda like what config:status does)
but now the no-shorthand is interpreted as a `YES` -- that cannot be right!

Also help-section `Global options` has no mention about the "no" argument. 

**To Reproduce**
Use a command that uses a yes/no promt (eg. `drush cim` or `drush sqlsan`)
See that it requires a promt
now add `-n` and see that it is interpreted like `yes` 
now change the `-n` into `--no` and see that it is interpreted like `no` 

**Expected behavior**
-n should be the shorthand for --no (or at leased not yes)

**Actual behavior**
-n is now the shorthand for --yes
Or more likely the `--no-interaction` ?
_didnt look at the code yet_

**Workaround**
write fullout `--no` arg

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | detected at 13.3.3.0
| Drupal version? | at leased found in 10.x and 9.x
| PHP version     | all
| OS?             | all

**Additional information**

**Comment by weitzman** [comment]
Yes this changed several years ago when we adopted symfony console. -n in all console apps is short for --no-interaction which does behave similar to --yes. Use --no to get old behavior.

**Comment by gitressa** [comment]
Thanks for raising this and a fast answer.

`--no` works well, but ends in an error, though it's not ... I seem to recall other Drush issues, where the final part of the Drush feedback message is an error, where it shouldn't. So the last three last lines should ideally not be included ...

```
In ConfigExportCommands.php line 146:            
  Cancelled.               
Failed to run drush config:export --no: exit status 1
```

## ... but `--no` does work well :)
```
$ drush config:export --no
 [notice] Differences of the active config to the export directory:
+------------+-----------------------------------------------+-----------+
| Collection | Config                                        | Operation |
+------------+-----------------------------------------------+-----------+
|            | field.storage.node.field_plaion               | Create    |
|            | field.field.node.article.field_plaion         | Create    |
|            | admin_toolbar.settings                        | Create    |
|            | admin_toolbar_search.settings                 | Create    |
|            | admin_toolbar_tools.settings                  | Create    |
|            | core.extension                                | Update    |
|            | core.entity_form_display.node.article.default | Update    |
|            | core.entity_view_display.node.article.teaser  | Update    |
|            | core.entity_view_display.node.article.rss     | Update    |
|            | core.entity_view_display.node.article.default | Update    |
+------------+-----------------------------------------------+-----------+


 !                                                                                                                     
 ! [WARNING] The .yml files in your export directory (sites/default/files/sync) will be deleted and replaced with the  
 !           active config.: no.                                                                                       
 !                                                                                                                     

In ConfigExportCommands.php line 146:            
  Cancelled.               
Failed to run drush config:export --no: exit status 1
```

**Comment by weitzman** [comment]
Now you are changing the intent of this issue. Feel free to discuss in #6162

**Comment by MakerTim** [comment]
Can it be that it's more recent?
My guess is that the newer yes/no promt has changed the behaviour

That "no interact" used to say no and now it does a yes?

**Comment by gitressa** [comment]
Thanks @weitzman, I'll follow that other issue about legitimate Drush commands ending in error.

**Comment by weitzman** [comment]
I thunk this behavior changed in drush 9. drush 13 is the current version. having said that, some people use drush8 to this day so this change might be recent for you.
