### ISSUE TITLE
Unable to create

### ISSUE THREAD

**Issue by ghost** [drush-ops/drush#62]
"Unable to create /Users/USERNAME/.drush." I keep getting this error every time i use the drush command. Any reason why?

**Comment by jorgeorpinel** [comment]
Same issue. My permissions seem OK but `~/.drush` is a symlink.
```sh
ls -la ~/.drush 
lrwxrwxrwx 1 USERNAME USERNAME 54 Jul 12 03:46 /home/USERNAME/.drush -> /home/USERNAME/.oh-my-zsh/plugins/drush/drush_zsh.drush.inc
```
The target is also owned by USERNAME.

**Comment by apelegri** [comment]
@jorgeorpinel  I had the same issue as you but I didn't arrive to delete  oh-my-drush, how did you manage it? 
`ls -la ~/.drush                                                                                                          
lrwxr-xr-x  1  USERNAME staff  65 Jul  4 17:20 /Users/USERNAME/.drush -> /Users/USERNAMEi/.oh-my-zsh/plugins/drush/drush_zsh.drush.inc`

thanks in advance

**Comment by jorgeorpinel** [comment]
Sorry, I don't remember. But what do you mean? I'm guessing I simply stopped using oh-my-drush (which hasn't been updated in 5 years) in favor or [regular drush](http://docs.drush.org/en/master/install/).

**Comment by apelegri** [comment]
Can you use the drush command through zsh? because I can't have access to drush through zsh and drush is only accessible through bash.

**Comment by grantkemp** [comment]
For me I assume I had Drush installed previously - when I updated to the new desktop - I found I couldn't install anything.  

My solution was to remove the .drush via command line - then the drush commands started working again. 
```rm .drush 
drush status ```

and I was working again.
