### ISSUE TITLE
sed instructions lopping first character from home directory on Mac?

### ISSUE THREAD

**Issue by webchick** [drush-ops/drush#621]
This might well be PEBCAK like most of my Drush bug reports but just in case not. :P

Following the instructions on https://github.com/drush-ops/drush I went to copy/paste the command:

```
sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
source $HOME/.bashrc
```

The error coming out of Console is:

```
sed: ebchick/.bashrc: No such file or directory
```

if I echo $HOME I get:

```
$ echo $HOME
/Users/webchick
```

Not really sure what's going on. This text change was introduced in #444.

**Comment by greg-1-anderson** [comment]
Those instructions are obsolete. Sorry no one helped with this. The problem was that that command is Linux-specific; Mac / FreeBSD has a different sed.
