### ISSUE TITLE
support for private browsing/incognito/other browser launches

### ISSUE THREAD

**Issue by djdevin** [drush-ops/drush#622]
It would be nice if certain commands could launch regular browser windows (like `drush uli` does already) but then other commands could launch a private window (like `drush uli 12345 --private`).

We can get around this with `drush uli 12354 --browser="firefox --private-window"` but the browser must be specified, scripts won't work across different environments.

It might not be feasible to check something like xdg-open, then append the correct private browsing argument based on the browser to be launched, as we'd have to maintain a browser list with their respective launch arguments. But what might be doable is adding a public/private browser config or multiple browser profiles as .drushrc configuration overrides that `drush_start_browser()` will obey. Otherwise it would fall back to browser discovery.

This would enhance `drush uli` and any other commands that use drush_start_browser() - so far though, it seems like only `uli` and `runserver`.

**Comment by weitzman** [comment]
Agreed. Please use shell aliases or option configuration.
