### ISSUE TITLE
drush up PROJECT --gitinfofile does not update the .info file

### ISSUE THREAD

**Issue by grossmann** [drush-ops/drush#623]
I tried using the `--package_handler=git_drupalorg` with `--gitinfofile` options. Using this with the dl command worked great and the needed version info for the update status is correctly injected into the .info file.
Trying to use this with the up or upc the version info is not updated. This way I end up with code of a newer version as the .info file says. Using the `--gitcheckoutparams` with -f (force) and `--gitinfofile` removes the version information in the .info completely and therefor is no longer recognized by update status.
Any help welcome to solve this. This has to be a commen problem. Maybe i just don't do it right.
I am using drush v. 6.2.0

**Comment by drzraf** [comment]
Same problem here, why drush dl can do it seemlessly and drush up couldn't update the info file without various hacks?
up could easily do find -name '*.info' -exec git checkout {} to cleanup the info before running the version numbering update.

**Comment by drzraf** [comment]
Adding that the --gitcheckoutparams=-f does not work, at least in some case.
Just tested with drush --debug -vv @d6 upc --gitinfofile --gitcheckoutparams=-f drupal and no info file substitution happens...

**Comment by drzraf** [comment]
Well,
substitution happens in package_handler_post_download() from the git-package-handler (git_drupalorg.inc)

This post-download function is capackage_handler_post_download(à

**Comment by drzraf** [comment]
just a ping @weitzman 
wanted to know if there are any plan to resolve this annoying issue or at least if any "clean" hook-based solution should be preferred.

**Comment by greg-1-anderson** [comment]
Haven't investigate this.  Are you all using the [git_deploy](https://www.drupal.org/project/git_deploy) module?

**Comment by grossmann** [comment]
Yes, I am using the git_deploy module to see update information on the "Available Updates" report page.

**Comment by greg-1-anderson** [comment]
If folks are happy with the solution posted above, then perhaps someone could make a PR, along with a test that fails without the change, and works with it.

If anyone has a chance to do this, please remove the `drush_command_invoke_all('pm_post_update')` call.  There is already a post-command hook that can be used; the project info is available in a context.  If this is a PR for Drush core, though, then a hook probably isn't necessary; just place the code above in the same files as the other git-related options are processed.

**Comment by drzraf** [comment]
I'm really interested in having this one fixed,
but I tried to analyze how the current code works but see above for the
things I failed to figure out.

(and I can't to see how exactly the modification should be done to be
done "properly")

**Comment by drzraf** [comment]
got it working using incaic's workaround. A one-line patch (and an API change).
But still, why no interest in such a useful patch. Same as OP: isn't an intended workflow?

**Comment by grossmann** [comment]
I ended up using git_deploy module which doesn't need the version info. But there are problems as ctools and panels have some hardcoded version info for some dependency reasons. This modules don't show as git_deploy doesn't like this. So still no good solution for this.

**Comment by drzraf** [comment]
@upstream how do you drush up git'ed project without having this issue fixed?
I'm curious about what the alternatives are. Does everyone use  git_deploy on every site they use drush with? Does drush up for gi'ed modules *mandates* git_deploy?

**Comment by greg-1-anderson** [comment]
Yes, git_deploy is mandated for using pm-updatecode with git-fetched modules.

I manage git-fetched modules with git, so I don't really know the status of pm-updatecode + git_deploy in Drush core right now.  If someone makes a PR to fix this, it would be helpful to also include unit tests, so that we will know if it is working or not.

**Comment by greg-1-anderson** [comment]
`pm-*` commands are maintenance only. Closing.
