### ISSUE TITLE
Problem with executing drush as different user over SSH

### ISSUE THREAD

**Issue by jurgenhaas** [drush-ops/drush#637]
We make sure that drush is always being executed as the webserver user on our Ubuntu 12.04 hosts by defining /usr/local/bin/drush like this:
```
#!/bin/bash
sudo -u www-data /usr/bin/drush $@
```

While this approach works perfectly well while being executed from a terminal console of a remote host, it does however throw some warnings when executed from my local terminal over SSH.

The command being executed is ```drush @remote.alias status``` and the warnings are:
```
tput: unknown terminal "unknown"
No entry for terminal type "unknown";
using dumb terminal settings.
```

I was looking around the web but couldn't find a solution yet. There is no harm other than cluttering the console output which is irritating when performing tasks on a group of aliases at once.

Any idea what could be causing this and how to resolve it?

**Comment by drzraf** [comment]
happens running drush from an Ansible playbook with pipelining = True (which does not allocate a tty).
```
tput: unknown terminal "unknown"
No entry for terminal type "unknown";
using dumb terminal settings

**Comment by drzraf** [comment]
The simple fact of executing under ssh (without -t), show strange results, eg:
drush @x vget --format=json
This will output invalid json (underquoted, newlines, ...) when executed using non-interactive ssh.

**Comment by greg-1-anderson** [comment]
@drzraf: what version of Drush are you using?  Drush 7.0-rc1 already supports "unknown":
```
$ TERM=foo drush version
tput: unknown terminal "foo"
 Drush Version   :  7.0-dev 

$ TERM=unknown drush version
 Drush Version   :  7.0-dev 
```
Is there anything left to do here?  I think this issue is actually fixed in the master branch.

**Comment by drzraf** [comment]
On Mon, Mar 30, 2015 at 01:26:02PM -0700, Greg Anderson wrote:
> @drzraf: what version of Drush are you using?  Drush 7.0-rc1 already
> supports "unknown":

short version: drush 6.5.0

long version:
Ubuntu 10.04.4
=> 5.3.2
=> no usable symphony version [composer]
=> drush 6.5.0


> Is there anything left to do here?  I think this issue is actually
> fixed in the master branch.

then I trust you, I can't test Drush 7.0

**Comment by greg-1-anderson** [comment]
Maybe your remote Drush version is older?  Drush 6.5.0 also supports "unknown".

Presuming fixed; closing.
