### ISSUE TITLE
Server (global) installation

### ISSUE THREAD

**Issue by markhalliwell** [drush-ops/drush#644]
Similar to #605 I guess...

I know that PEAR is depreciated and we're going the way of composer, but installing it on a server has proved... difficult (for me anyway).

Maybe I just don't understand how composer works, but after doing some research I finally realized that `composer global` really isn't a "global" install, it just means that it installs it in the user's global `~/.composer` folder.

So I installed it as "root", but then that means it installs it as `/root/.composer/vendor/bin/drush`, which also means that no one else has access to `/root`.

I know that there's the "manual" install, but I'd rather not attempt that if it's not entirely necessary. So, this may be a dup of another issue already (didn't really search too deeply):

Is there a way to get your "composer" install method, but globally as a server level cmd so that any [new] user has access to it.

**Comment by jonhattan** [comment]
You can leverage COMPOSER_HOME to perform a server-wide installation, but it's a bit convoluted.

```bash
mkdir /opt/drush/7
cd /opt/drush/7
COMPOSER_HOME=/opt/drush/.composer composer require drush/drush:7
ln -s /opt/drush/7/vendir/bin/drush /usr/local/bin/drush
```

Follow this instructions, or keep calm and enjoy [Puppetry for Drupaleros](https://github.com/jonhattan/puppet-drush/wiki/Puppetry-for-Drupaleros) :smiley:

**Comment by kenorb** [comment]
It's actually possible to change `vendor-dir` and `bin-dir` in composer JSON config it-self which could be useful.

Related: [Why vendor dir is misplaced after composer update?](http://superuser.com/q/977692/87805)

**Comment by sint** [comment]
Is this is is the future of software development? You're using a software packaging system to install it into a folder to copy it to somewhere else by hand? WTF!! Please tell me there is another option!!

Since i am used to Linux (especially Gentoo) to run my servers, i am used to using a professional software management system. Why can't composer install software at global level? How to update this software inside composer?

Gentoo dropped support of Drush for this. THANKS ALLOT!! :-1:

**Comment by kenorb** [comment]
@sint Check the recent install instructions at http://docs.drush.org/en/master/install/

    COMPOSER_HOME=/opt/drush COMPOSER_BIN_DIR=/usr/local/bin COMPOSER_VENDOR_DIR=/opt/drush/7 composer require drush/drush:7

Using this one-liner, you don't have to copy anything. Add sudo before `composer` if required.

**Comment by sint** [comment]
Its sad you don't get the point. While composer might be nice on systems who can't get it to implement package management, it is alien to those who have. How should i keep up with future Drush updates? Learning composer and running additional commands each time i want to know if there is an update of drush? This what is great about linux, you have (ya, those days are gone!) one place to look for software / updates. Softwas was well organized on your system and you could do clean updates / uninstalls it any time. The way we used Drush, was like a simple (and great) extension to the shell and not as software you deploy for each project. 

If you go to the Composer website, its clearly written:

**Composer is not a package manager in the same sense as Yum or Apt are. Yes, it deals with "packages" or libraries, but it manages them on a per-project basis, installing them in a directory (e.g. vendor) inside your project. By default it will never install anything globally. Thus, it is a dependency manager.**

So, why are you guys pretending Drush is just some random Drupal module, when in fact it is not?
