### ISSUE TITLE
Tilde character (~) does not expand in path arguments

### ISSUE THREAD

**Issue by ksenzee** [drush-ops/drush#649]
Copied from https://drupal.org/node/1918530.

I don't know what the right fix is here, but I do think a fix is needed. Here's what just happened to me:

    $ drush archive-dump --destination=~/filename.tar.gz
    $ ls ~/filename.tar.gz

... hm, nothing there...

    $ ls
    ~
    authorize.php
    CHANGELOG.txt
    ...

Oh, it created a directory in my current location, called '~'. Annoying. I'll just get rid of that.

    $ rm -rf ~

Luckily I caught myself _just_ before I hit Enter on that command.

I understand the semantics of tilde expansion in POSIX are complicated, and as I say, I don't know what the right fix is, but I'm pretty sure creating a directory named ~ is a Bad Idea™.

**Comment by greg-1-anderson** [comment]
Fixed by #1593
