### ISSUE TITLE
D8 and test module enable

### ISSUE THREAD

**Issue by chx** [drush-ops/drush#667]
Since sun broke it test modules can't be enabled any more. There's some obscure setting that fixes it, please add it to drush. https://drupal.org/node/2198713

**Comment by weitzman** [comment]
I just came across a need for this but I still don't see how to temporarily override a Setting via code in D8.

**Comment by chx** [comment]
$settings = Settings::getAll();
    $settings['extension_discovery_scan_tests')] = TRUE;
    new Settings($settings);

**Comment by weitzman** [comment]
Again this just bit me, so here is #3681. Will merge once green. Thanks to @chx for the code (and the patience).

**Comment by weitzman** [comment]
Unfortunately, Drush cant fix this. See #3681
