### ISSUE TITLE
Long running drush batch processes fail

### ISSUE THREAD

**Issue by datr** [drush-ops/drush#676]
Long running batch processes fail if the time the workers spend executing the jobs exceeds MySQL's wait timeout. When the parent drush job resumes working it will fail with a "MySQL server has gone away" error.

The bug was previously discussed on drupal.org here:
https://drupal.org/node/587250

The correct solution is probably for the parent process to detect if the MySQL connection has gone stale after a batch has finished executing and refresh it if necessary.

**Comment by rivimey** [comment]
I've seen this problem on multiple occasions. A fix, even something as simple as that done by darthsteven above, would be greatly appreciated (i.e. have drush close and auto-reopen the db connection).

**Comment by axel-rutz** [comment]
Untested but something like this in settings.php might help:
```
if (drupal_is_cli()) {
  $databases['init_commands'][] = 'SET wait_timeout = 1200';
}
```

**Comment by weitzman** [comment]
Not a drush-specific issue.

**Comment by yuseferi** [comment]
just for record if somebody has issue in drupal 8,9 

```
if (PHP_SAPI === 'cli') {
  $databases['default']['default']['init_commands']['wait_timeout'] = 'SET SESSION wait_timeout = 1800';
}
```
