### ISSUE TITLE
Better presentation of log entries from backend calls

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#685]
I am frustrated with the presentation of log messages that come from a drush_invoke_process(). Drush (optionally) merges these logs into the originating request and it becomes hard for many folks to tell if a given log message came from the originating  request or the backend request.

Should we evolve drush_log() to add a RequestID to each entry so that we can distinguish between subrequest entries? That doesn't solve the presentation part of this.

Any ideas, @greg-1-anderson? Anyone else?

**Comment by greg-1-anderson** [comment]
Controlling this via an option, and putting the label into the log entry is a good idea.
