### ISSUE TITLE
Error: Cannot redeclare views_drush_cache_clear() 

### ISSUE THREAD

**Issue by wah22** [drush-ops/drush#686]
The error continues to say: (previously declared ../all/modules/views-DRUPAL-7--3/views.drush.inc:12) ../all/modules/views/drush/views.drush.inc line 496

Do you know what I am doing wrong?  

Thanks!

**Comment by greg-1-anderson** [comment]
Please use [Drupal Answers](http://drupal.stackexchange.com/questions/tagged/drush) for support requests.
