### ISSUE TITLE
Problem with spaces in arguments when executing drush remotely

### ISSUE THREAD

**Issue by jurgenhaas** [drush-ops/drush#690]
Example:
```
drush @alias vset name_of_var "This is the value"
```

If @alias is local, then the variable gets set properly. However, if @alias is remote then the value of the variable will be set to "This". The quotes to delimit the scope of the argument to "This is the value" get lost when forwarding the command to the remote host.

**Comment by kenorb** [comment]
Works for me on remote for 7.0-dev.

**Comment by tbfisher** [comment]
I'm seeing this with both 7 and 8:

https://gist.github.com/tbfisher/188112cb37f32087e314

**Comment by weitzman** [comment]
I was unable to repro this with `drush @foo vset site_name 'my uncle'`

**Comment by hkirsman** [comment]
Getting this with Drush 8.1.15. Havent yet tried with newer versions.

**Comment by hkirsman** [comment]
Same with 8.1.17.

**Comment by skounis** [comment]
Same situation here
```
drush config-set system.site name 'hello world'
```
Gives just "hello" as the site name.
