### ISSUE TITLE
Why is there no config-clear command?

### ISSUE THREAD

**Issue by marcvangend** [drush-ops/drush#699]
I was surprised to find there is no `drush config-clear` command for Drupal 8, as equivalent to `drush vdel` on D7. Is there a reason for this, or can you consider this issue a feature request?

**Comment by weitzman** [comment]
Just added a config-delete command. It deletes a whole config object, so its useful for deleting orphan config entities during development. 

Reverting to default config is still a wish list item

**Comment by weitzman** [comment]
Reverting config can live in Configuration Update module and Features module for now. If someone submits a PR for Drush, I'd consider it.
