### ISSUE TITLE
Unable to find a matching SQL Class. Drush cannot find your database connection details. 

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#700]
The following command gives me the error:

```
drush  -y sql-sync @prod @self
```

drush version 7.0-dev which doesn't work.
drush status indicates that Drupal bootstrap is connected Successful.
Tested with drush 6.1.0 and it works fine.

```
 $ drush status
 Drupal version                  :  7.28                                                                           
 Site URI                        :  http://default                                                                 
 Database driver                 :  mysql                                                                          
 Database hostname               :  localhost                                                                      
 Database username               :  root                                                                           
 Database name                   :  foo                                                                       
 Database                        :  Connected                                                                      
 Drupal bootstrap                :  Successful                                                                     
 Drupal user                     :                                                                                 
 Default theme                   :  foo                                                                        
 Administration theme            :  seven                                                                          
 PHP executable                  :  /Applications/MAMP/bin/php/php5.5.3/bin/php                                    
 PHP configuration               :  /Applications/MAMP/bin/php/php5.5.3/conf/php.ini                               
 PHP OS                          :  Darwin                                                                         
 Drush version                   :  7.0-dev                                                                        
 Drush temp directory            :  /tmp                                                                           
 Drush configuration             :  sites/default/drushrc.php         
 Drush alias files               :  sites/default/aliases.drushrc.php 
 Drupal root                     :  foo                                   
 Site path                       :  sites/default                                                                  
 File directory path             :  sites/default/files                                                            
 Private file directory path     :  sites/default/private                                                          
 Temporary file directory path   :  /tmp                         
```

**Comment by musubimedia** [comment]
Getting this error also. Found this thread and wondering what I'm doing wrong. Here's what I'm getting from Drush 8.0-Dev:

dmacbp:~ Dan$ drush sql-sync @www.pmm @local.pmm -y
You will destroy data in local.pmm and replace with data from 50.116.40.202/www.pmm.
Do you really want to continue? (y/n): y
Starting to dump database on Source.                                                                                                                [ok]
Database dump saved to /home/Dan/drush-backups/dev.pmm/20150717161739/dev.pmm_20150717_161739.sql.gz                                                [success]
Starting to discover temporary files directory on Destination.                                                                                      [ok]
You will destroy data from /tmp/dev.pmm_20150717_161739.sql.gz and replace with data from Dan@50.116.40.202:/home/Dan/drush-backups/dev.pmm/20150717161739/dev.pmm_20150717_161739.sql.gz
Do you really want to continue? (y/n): y
Copying dump file from Source to Destination.                                                                                                       [ok]
Starting to import dump file onto Destination database.                                                                                             [ok]
Unable to load class Drush\Sql\Sql                                                                                                                  [error]
exception 'Drush\Sql\SqlException' with message 'Unable to find a matching SQL Class. Drush cannot find your database connection details.' in       [error]
/Users/Dan/.composer/vendor/drush/drush/commands/sql/sql.drush.inc:595
Stack trace:
#0 /Users/Dan/.composer/vendor/drush/drush/commands/sql/sql.drush.inc(428): drush_sql_get_class(NULL)
#1 [internal function]: drush_sql_query()
#2 /Users/Dan/.composer/vendor/drush/drush/includes/command.inc(359): call_user_func_array('drush_sql_query', Array)
#3 /Users/Dan/.composer/vendor/drush/drush/includes/command.inc(210): _drush_invoke_hooks(Array, Array)
#4 [internal function]: drush_command()
#5 /Users/Dan/.composer/vendor/drush/drush/includes/command.inc(178): call_user_func_array('drush_command', Array)
#6 /Users/Dan/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(62): drush_dispatch(Array)
#7 /Users/Dan/.composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 /Users/Dan/.composer/vendor/drush/drush/drush.php(11): drush_main()
#9 {main}

**Comment by jenlampton** [comment]
I'm also seeing the error `Unable to load class Drush\Sql\Sql`. I checked drush 7-dev and confirmed that the fix from da0ad8a has been included. Not sure where to look next. Where is this class (I don't see it in the codebase)?

**Comment by jonhattan** [comment]
@jenlampton this starts in `drush_sql_get_version()`, but please keep in mind that if you're hacking the code to make backdrop work, you may encounter illegitimate errors.

**Comment by jiv-e** [comment]
I got this error because I had a wrong site root path in my Drush alias definition. So be sure to double check that if you get this!

**Comment by eckersley** [comment]
I laboured over this error too; the root path seemed perfectly fine in the alias file - until I realized that my home directory was not the same as the one being used by sql-dump. I had to spell out ~/Sites/ from the root, as in /Users/[My_Username]/[Drupal_Installation]. I could finally get a read on the databases in drush @[sitename].local status and perform drush @[alias].remote @[sitename].local

**Comment by briantully** [comment]
@eckersley thank you!!! Indeed it seems the home directory cannot be specified with the "~" prefix and instead must be specified as the full path, otherwise drush will frown upon the site alias. I too wasted so much time on this, and could have wasted even more time -- but thankfully I saw your comment 👍

**Comment by phanos** [comment]
I ran into this same problem after a drush rsync when I failed to notice my sites/default/settings.php was not copied
