### ISSUE TITLE
STDERR instead of STDOUT for default drush output

### ISSUE THREAD

**Issue by lukey78** [drush-ops/drush#707]
Hi there,

is there any reason why Drush by default outputs all messages to STDERR even if no errors happen, like when I do a simple cache-clear?

We usually use Drush in our deploy scripts with Capistrano, and all the drush output is displayed in red color because of that. Of course we could change the deploy recipes to always redirect STDERR to STDOUT, but... why?

Thanks for clearing this up.

**Comment by helderco** [comment]
I don't get it. How do I get notified of errors during cron? It seems my option is to suppress all output, including the useful errors. I can't suppress "[notice] WD cron: Cron run completed." with --quiet anymore, and it's going to stderr so I can't just trash stdout.

**Comment by greggles** [comment]
I used to think STDERR was for all errors - it's right there in the name, even!

I later noticed many commands that log most information to STDERR while sending the program output to STDOUT. Reading about [STDERR on wikipedia](https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)):

> Standard error is another output stream typically used by programs to output error messages or diagnostics. It is a stream independent of standard output and can be redirected separately. This solves the semipredicate problem, allowing output and errors to be distinguished, and is analogous to a function returning a pair of values – see Semipredicate problem: Multivalued return. 

In modern drush, if you want to send something to STDOUT you can do it a few ways, but a solid method is:

```
$this->output()->writeln('foo');
```

**Comment by ElijahLynn** [comment]
Thanks for this thread! Just spent an hour trying to figure out why my pipe to grep test command wasn't working and finally realized all drush output is sent to STDERR, this thread was really useful in confirming this after we realized the issue!
