### ISSUE TITLE
Parameter 1 to drush_policy_cache_clear() expected to be a reference, value given command.inc:362

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#735]
I've defined the following hook in my policy.drush.inc (sites/all/drush):

```
/**
 * Add/edit options to cache-clear command
 */
function drush_policy_cache_clear(&$types) {
  $types['views'] = 'views_invalidate_cache';
}
```

But it seems every time when I'm trying to clear my cache, it's giving me the following error:

```
$ drush cc drush // or: drush cc all
'all' cache was cleared.
Parameter 1 to drush_policy_cache_clear() expected to be a reference, value given command.inc:359
```

When used with interactive options, I've got this:

```
$ drush cc
 [1]   :  drush          
'drush' cache was cleared.                                           
Missing argument 1 for drush_policy_cache_clear() policy.drush.inc:72
```

The hook is based on example in docs/drush.api.php
Have I missed something?

I've tried this in drush 6.1.0 as well as with recent 7.0-dev.

**Comment by greg-1-anderson** [comment]
Please use [Drupal Answers](http://drupal.stackexchange.com/questions/tagged/drush) for support requests.
