### ISSUE TITLE
make_download_pm does not invoke pm-download hooks

### ISSUE THREAD

**Issue by minorOffense** [drush-ops/drush#736]
Drush make has a download method where it uses the pm-download command to download projects. But, it doesn't invoke any of the drush_HOOK_pre_COMMAND or drush_HOOK_post_COMMAND hooks for pm-download.

This is an issue since we have code we want to have run every time drush downloads a project. And in our case, running it on the "make" pre/post commands won't work.

I would suggest adding the invoke for those hooks into the make_download_pm() function or somewhere in the chain to ensure when drush pm-download is triggered by the make, the hooks are run.

drush_invoke:
https://github.com/drush-ops/drush/blob/master/includes/command.inc#L35

make_download_pm()
https://github.com/drush-ops/drush/blob/master/commands/make/make.download.inc#L26

**Comment by greg-1-anderson** [comment]
Drush make is in maintenance only; closing.
