### ISSUE TITLE
Drush make has problems with wget 1.12 and the HTTPS certificate of drupal.org.

### ISSUE THREAD

**Issue by matglas** [drush-ops/drush#74]
**Problem**
When drush make uses patches from drupal.org on a server running 1.12 it returns an because of the https certificate that drupal.org uses. This can happen with other sources too. Ubuntu 10.04 uses 1.12 as its latest package for wget. This problem is fixed with wget 1.13. In Ubuntu 12.04 they use wget 1.13 so there its no problem.

**Fix**
When you add the flag --no-check-certificate to wget on 1.12 it continues but does not check the certificate.

**Proposed solution**
It would be great to be able to add --no-check-certificate as a parameter to the wget call when the version is 1.12.

This call to check if wget is available is [here](https://github.com/drush-ops/drush/blob/98b4a2209a212a9454c4cd4e07f8a9a3b235e53d/includes/drush.inc#L800). The version could be checked there too. If the version is 1.12 the flag could be added to the [exec call](https://github.com/drush-ops/drush/blob/98b4a2209a212a9454c4cd4e07f8a9a3b235e53d/includes/drush.inc#L800). That line would look something like this

``` php
  drush_shell_exec("wget -q --timeout=30 --no-check-certificate -O %s %s", $destination_tmp, $url);
```

**References**
- https://drupal.org/node/1931940 - about certificate problem.
- http://packages.ubuntu.com/lucid/wget - reference to lucid wget version.

**Comment by drupol** [comment]
Here's a one line solution: echo "check_certificate = off" >> ~/.wgetrc
