### ISSUE TITLE
runserver: 404 when dot character in clean URL path

### ISSUE THREAD

**Issue by GarrettAlbright** [drush-ops/drush#752]
When using runserver, I noticed I was getting a PHP error from the server (not from Drupal) when attempting to go to a Memcache server report page with a path that looks like `http://127.0.0.1:8888/admin/reports/memcache/default/127.0.0.1%3A11211` (`%3A` is an encoded colon character).

However, if I manually adjust the path to make it "dirty," like `http://127.0.0.1:8888/index.php?q=admin/reports/memcache/default/127.0.0.1%3A11211`, it works just fine.

I thought this might be an issue in runserver-prepend.php, but after some consternation, as far as I can tell, that file doesn't even execute whenever there's a period in the clean path. I can only assume that PHP is assuming that there's a file involved whenever it sees a dot in the path, looking for that file, then failing when it can't find it without giving the prepend file a chance to have a say in the matter.

I notice that we don't seem to be using a router file. Would it be possible to avoid this problem if we had one? I'm not sure.

**Comment by mdeltito** [comment]
I'm seeing the same, and it looks like this is the expected default behavior with PHP's built-in server:
https://bugs.php.net/bug.php?id=61286

Using a router file *does* mitigate the issue however, and the included D8 one seems to work just fine. I don't know enough about the history of the runserver-prepend file to determine if it's still necessary for D7, but the router file seems like the right approach moving forward.

**Comment by kenorb** [comment]
It also fails for Advanced Help module which scans for the help files and generates the appropriate callbacks.

So going into: `/help/commerce_paypoint_advanced/README.md`
generates `Not Found` page as well.

**Comment by weitzman** [comment]
Got fixed by #2033 AFAIK

**Comment by weitzman** [comment]
For D7, see #1658
