### ISSUE TITLE
Don't clear cache when no database updates

### ISSUE THREAD

**Issue by iBobik** [drush-ops/drush#755]
Hello,
when `drush updb` is run but not database updates are there it will print "No database updates required". Ok, but why it clears caches in this case? I think caches should be run only if some database updates were run.

**Comment by weitzman** [comment]
in addition, updb now has --cache-clear=0 if you want to manually control the cache step.

**Comment by helmo** [comment]
Thanks, merged in drush-ops/drush/pull/1802
