### ISSUE TITLE
Wrong version number added to info file: should base on last tag

### ISSUE THREAD

**Issue by lkmorlan** [drush-ops/drush#759]
In the field_collection module, commit 3a2c562 has two tags pointing to it: 7.x-1.0-beta7 and 7.x-1.0-beta6 (I don't know why, but that is the way it is). We are running 9b507ac, which is 12 commits ahead. Problem: Drush adds to the info file the version string 7.x-1.0-beta6+12-dev. It should use 7.x-1.0-beta7+12-dev. In other words, versions should be based on the latest tag that points to the given commit. This bug could also be observed in situations where a commit is tagged as an -rc and a full release, for example.

**Comment by lkmorlan** [comment]
This would require changes to drush_pm_git_drupalorg_compute_rebuild_version(). Something besides "git describe --tags" would have to be used to get the tag name. "git reflog --decorate -1" gives all the tags for the specified commit, but unlike "git describe --tags", it does not create a label based on the most recent and the number of commits since. I don't see any simple solution to this problem.

**Comment by greg-1-anderson** [comment]
Drush `pm-*` commands are maintenance only; closing.
