### ISSUE TITLE
command cache clears itself and doesn't rebuild

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#79]
It seems that various operations cause drush to forget its commands.

See https://drupal.org/node/1653222 for various user experiences with this.

**Comment by rwam** [comment]
Puh, we ran into the same problem with Drupal 8.5.4, Features 8.x-3.7 and Drush 8.1.14. Annoying.

Doesn't work:
<code>
drush updb -y
drush fim team -y
>> Command fim needs the following extension(s) enabled to run: .    [error]
</code>

Work:
<code>
drush updb --cache-clear=0 -y
drush cr -y
drush fim team -y
>> Current state already matches active config, aborting.            [ok]
</code>
