### ISSUE TITLE
drush si --locale not working with d8

### ISSUE THREAD

**Issue by YesCT** [drush-ops/drush#796]
Tried the already existing --locale option and it didn't work with d8 (seems like the install only partially finished).

https://twitter.com/YesCT/status/507517798449311746

**Comment by dunebaud** [comment]
I am using drush 8 with drupal 8.4 and I do not succeed to install it in french. Here is my command line:

`/home/baud/alldrush/drush8/vendor/bin/drush @drupal8-sites site-install standard --db-url=mysql://useradm:password@localhost/movietowncloudsql --db-su="root" --db-su-pw="agoodpassword" --site-name="mySite" --account-name="admin" --account-pass="password" --account-mail="mymail@mydom.be" --site-mail=amail@mydom.be --sites-subdir="mysite.be" --locale=fr -y`

**Comment by dunebaud** [comment]
Forget my previous comment... the language was installed... sorry for the confusion
