### ISSUE TITLE
URI can't change during SITE bootstrap phase - Drush7

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#800]
The fix is to re-set the $SERVER vars during SITE phase, as we do during Drush6. Probably should factor out the server vars stuff.

**Comment by greg-1-anderson** [comment]
In Drush 7, drush_load_config('drupal') and drush_load_config('site') are called from drush_preflight_site(), prior to the SITE bootstrap phase.  Seems this was broken in alpha-4, but I am depending on it for [#1177], for example, so I think it's working fine now.

**Comment by morvans** [comment]
AFAICT, it does not currently work in master/HEAD. I'll try to have a look but I'm not used to the drush codebase.

**Comment by greg-1-anderson** [comment]
Post your exact use-case that is not working.  If you set uri in a site-alias, this might behave differently than if uri is unset, for example.

**Comment by weitzman** [comment]
I think the case that used to work is to set uri option from a drushrc.php that is located in a drupal site folder.

**Comment by morvans** [comment]
More precisely : located in the sites/default folder. But it doesn't work either when located in drupal root folder.

@greg-1-anderson, see #1231 for the details of my use case.

**Comment by greg-1-anderson** [comment]
Ah, I see, I was actually depending on drush_load_config('drupal').  The issue we have at drush_preflight_site() time is, if --uri is not specified, then Drush does not know where the sites folder is.  We could easily fix this particular use case by providing a default value of 'sites/defaut' if --uri is not set.

If --uri is set, then we have sort of a problem.  The priority of the contexts are:

- cli
- alias
- site
- drupal

So, if you specify --uri on the commandline, or in an alias file, then the value you set there will have priority over any 'uri' set in the 'site' or 'drupal' context.  How should Drupal decide that the 'uri' in the site context is better than the 'uri' in the cli or alias context?

Does Drush 6 really handle this?  How does it decide which 'uri' is best?  I don't remember any code that worked around the config priority during bootstrap. _drush_bootstrap_selected_uri() just uses drush_get_option('uri') in Drush 6.

838a741 looks the same as Drush 6.  838a741 crashes on my site, so I can't test right now. I suppose I could spin up D7 with qd, but need to go afk right now.

**Comment by greg-1-anderson** [comment]
If 'sites/default' is the only thing that ever was supported, and the only thing desired, then that's easy to support again, and I can make a PR.

**Comment by greg-1-anderson** [comment]
I think I've convinced myself that 'sites/default' was all that was historically supported, but I think that other sites dirs can also be supported fairly easily.  I have a meeting, but I'll whip up a PR once I'm done.

**Comment by greg-1-anderson** [comment]
Fixed and merged.

**Comment by morvans** [comment]
I can confirm it now works like before. Thanks!
