### ISSUE TITLE
D8 improvement request: make the message "There were errors validating the config synchronization." more helpful

### ISSUE THREAD

**Issue by alberto56** [drush-ops/drush#807]
Let's say you have two sites with different UUID values in the system.site.uuid configuration.

If you `drush config-export` from one of the sites and try to `drush config-import` to another, it runs into an error because only sites with the same system.site.uuid can be synced.

If you use Drupal's GUI, you see the error "The staged configuration cannot be imported, because it originates from a different site than this site. You can only synchronize configuration between cloned instances of this site.", which is helpful.

However, if you run `drush config-import` on the command line, you get the error "There were errors validating the config synchronization.".

It would be ideal to have the same error message on the command line as in the GUI.

**Comment by geerlingguy** [comment]
Link to corresponding core issue on Drupal.org: https://www.drupal.org/node/2332623
