### ISSUE TITLE
Installing Composer on bluehost solved

### ISSUE THREAD

**Issue by HongPong** [drush-ops/drush#811]
This is parochial to one web host but it drove me nuts until I got it solved. This string works for installation & I want it to be locatable here for others.

```
curl -sS https://getcomposer.org/installer | /usr/php/54/usr/bin/php -c ~/public_html/php.ini
```

Assuming you have a php.ini file configured to PHP 5.4 (single mode, others may work) . Thanks for the fine work, but ye gods Composer can be a blocker in the install process.

edit - later found this guide includes .bashrc alias:
 http://avantidevelopment.com/install-composer-on-bluehost/

**Comment by mhamed** [comment]
following the code it gives me the error  that it does not detect my php version

-bash: /usr/php/54/bin/php54-cli: No such file or directory
afeter installation :
running: composer --version

**Comment by HongPong** [comment]
I suggest looking at the contents of /usr/php/54/bin/ , perhaps the name of the binary is not right?

**Comment by mhamed** [comment]
hello 
thanks for the answer :
the real folder is this :<code>/usr/php/54/usr/bin/php-cli</<code>
but 
moving the downloaded composer.phar to  the :
<code>mv composer.phar /usr/local/bin/composer</code> gives me the error:
<code>mv: inter-device move failed: `composer.phar' to `/usr/local/bin/composer'; unable to remove target: Read-only file system.</code>
tried to chmod  but in vain.
<code>sudo </code> a politics that has no effect.
I m trying everything.
thanks

**Comment by HongPong** [comment]
You can't put anything in /usr/local/bin . you just need to call the correct interpreter and give it the phar file as an argument - they don't have to be in the same directory for it to work.

**Comment by mhamed** [comment]
ok thanks :+1: 
At the end managed to do it :+1: 
the problem was the  <code>.bashrc</code>
it takes the php path as  <code>/usr/php/54/bin/ </code>
but in reality: <code>/usr/php/54/usr/bin/php-cli</code>
i opened the .bashrc  locally changed the the alias:
from <code>alias composer=’ /usr/php/54/bin/php-cli  ~/common/composer.phar'</code>
to <code>alias composer=’/usr/php/54/usr/bin/php-cli  ~/common/composer.phar'</code>
Thanks a lot
