### ISSUE TITLE
pass information about the current command parameters to the command complete hook

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#82]
It would be useful if a command completion callback had information about the parameters given so far.

For example, for the module builder 'mb' command"

$ drush mb modulename hookname hookname hookname

I can autocomplete hook names. But if I knew which position the user was at, I could also offer to autocomplete the names of existing modules.

**Comment by greg-1-anderson** [comment]
Drush 8 is in maintenance fixes only; closing.
