### ISSUE TITLE
Arguments are not passed to module_invoke_all() from drush_module_invoke_all() in d6 and d7

### ISSUE THREAD

**Issue by komlenic** [drush-ops/drush#825]
There are warnings generated (and missing information) when running 'drush core-requirements' on an installed d6 or d7 site due to the fact that arguments are not passed to module_invoke_all() from drush_module_invoke_all().

Specifically, module_invoke_all() is used to invoke hook_requirements, which expects a $phase argument to be passed to it.  In previous versions of drush, this argument was passed correctly.

**Comment by kenorb** [comment]
This happens to me when running `rq` using Drush 7.0-dev, however it doesn't happen on my local. The site is D7.

The patch fixes the problem.
