### ISSUE TITLE
Drush 7 fails UP command on D7 site- ?PEAR or D7 core problem

### ISSUE THREAD

**Issue by AFowle** [drush-ops/drush#827]
I originally installed drush 6 via PEAR. Just upgraded to drush 7 via composer, without deleting drush 6 first. Upgrading a local dev version of a D7 site failed, as below. Reinstalling drush 6 via composer (after restoring site) then allowed upgrade to complete without error. 

adrian@valerian:~> dr version
 Drush Version   :  7.0-dev 

adrian@valerian:~> dr @bpnsdev up
 Name                 Installed Version  Proposed version  Message  
 Views Data Export    7.x-3.0-beta7      7.x-3.0-beta8     Update available 
 (views_data_export)                                                        

Code updates will be made to the following projects: Views data export [views_data_export-7.x-3.0-beta8]

Note: A backup of your project will be stored to backups directory if it is not managed by a supported version control system.
Note: If you have made any modifications to any file that belongs to one of these projects, you will have to migrate those modifications after updating.
Do you really want to continue with the update process? (y/n): y
Project views_data_export was updated successfully. Installed version is now 7.x-3.0-beta8.
Backups were saved into the directory                                         [ok]
/home/adrian/drush-backups/bpnsdev/20140919075600/modules/views_data_export.
 Views_data_export  7301  Change the object cache table to support postgres 
                          installations
Do you wish to run all pending updates? (y/n): y
require_once(/home/adrian/Drupaldev/bpnsdev/htdocs//core/includes/install.inc):[warning]
failed to open stream: No such file or directory core.drush.inc:1122
Drush command terminated abnormally due to an unrecoverable error.            [error]
Error: require_once(): Failed opening required
'/home/adrian/Drupaldev/bpnsdev/htdocs//core/includes/install.inc'
(include_path='.:/usr/share/php5:/usr/share/php5/PEAR') in
/home/adrian/.composer/vendor/drush/drush/commands/core/core.drush.inc, line
1122
PHP Fatal error:  require_once(): Failed opening required '/home/adrian/Drupaldev/bpnsdev/htdocs//core/includes/install.inc' (include_path='.:/usr/share/php5:/usr/share/php5/PEAR') in /home/adrian/.composer/vendor/drush/drush/commands/core/core.drush.inc on line 1122
The external command could not be executed due to an application error.       [error]
'all' cache was cleared.                                                      [success]
Finished performing updates.                                                  [ok]

**Comment by brylie** [comment]
I am getting this error frequently as well. How can I make sure I am running the correct version of Drush?

```
Failed opening required ...core/includes/install.inc
```
