### ISSUE TITLE
Git version control engine for --gitsync and more

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#83]
It would be nice to be able to automate drush dl and update with committing the new code to a local git repository for.

From https://drupal.org/node/797190:

> If you want this sort of functionality, it would probably be pretty easy to pull code from post_update and post_download (and the functions they call -- sync and commit), and repackage them as a post-update hook in your own commandfile stored at $HOME/.drush.

I am not sure this is doable any more.

I took at look at the kitten-o-matic example, and I have a hook_post_pm_download() implemented, but its only incoming parameter when I do, say 'drush dl PROJECT', is the string of the project name. So it seems that figure out which folder to issue a 'git add' system command on will mean redoing most of the work that's already been done by drush_pm_download().

**Comment by helmo** [comment]
@joachim-n could you give #1261 a spin?

It's as easy as:
```drush dl --gitcommit ctools```

**Comment by jonhattan** [comment]
We've agreed in #1056 to move vcs engines out of drush. I haven't had the chance to work on this though.

**Comment by helmo** [comment]
@jonhattan Thanks for the heads up, I hope you can use some of the code from #1261

**Comment by helmo** [comment]
a year went by ... :(

Code still applies to the current drush 8.0.5 stable. Re committed in https://github.com/helmo/drush/tree/dev-8-pm-gitcommit

**Comment by greg-1-anderson** [comment]
`pm-*` commands are in maintenance fixes only (and follow-on issues already closed for lack of activity). Closing.
