### ISSUE TITLE
Convert pm-updatecode lock/unlock functionality into proper commands

### ISSUE THREAD

**Issue by jonhattan** [drush-ops/drush#832]
I never liked that `--lock`/`--unlock` is coupled to `pm-updatecode` command. With the introduction of `pm-updatestatus` it is even more coupled between both commands.

OTOH `pm-dowload` doesn't prevent the overwrite of a locked project.

My proposal is to move the (un)locking operations to `pm-lock`/`pm-unlock` commands and populate the $projects array in `drush_get_projects()` with any lock information, and so make it available to `pm-download`, `pm-updatecode` and `pm-updatestatus`.

**Comment by greg-1-anderson** [comment]
Drush `pm-*` commands are maintenance only; closing.
