### ISSUE TITLE
Allow contrib_destination to be managed per project (backport 7.x patch to 6.x).

### ISSUE THREAD

**Issue by bryanhirsch** [drush-ops/drush#834]
Please backport this great patch, 087e51eabba013e28dde4be11aaf01e6ace0d8d3 from https://github.com/drush-ops/drush/pull/582, to 6.x for mainstream Drush users. From my tests, the patch applies cleanly and works as expected.

Here's a pull request: https://github.com/drush-ops/drush/pull/835.

**Comment by greg-1-anderson** [comment]
This was fixed.
