### ISSUE TITLE
Drush make destroys symlink to install profile

### ISSUE THREAD

**Issue by MacWeber** [drush-ops/drush#84]
* Coming from https://drupal.org/node/2033581 
* Related issue in Kraftwagen: https://github.com/kraftwagen/kraftwagen/issues/22 
* PR on Kraftwagen: https://github.com/kraftwagen/kraftwagen/pull/23

I want drush make to install an install profile and after install the folder structure should be like this:

drupal_root
drupal_root/profiles/
drupal_root/profiles/my_profile -> /foo/bar
(etc)

I used make_download_DOWNLOAD_TYPE() in order to create the symlink, and it worked fine (code is here). However it is created only while drush is working at /tmp. When drush moves the project to the installation folder it destroys the symlink, turning it into a regular folder.

I see there are many issues regarding the fact of copying the files instead of keeping symlinks.
It seems to be related to #1626972: Recreate symlinks in drush_copy_dir() instead of copying

Maybe I can solve it myself if someone could help with initial directions. Thanks in advance.

**Comment by ergonlogic** [comment]
The referenced d.o issue (#1626972) was closed 3 years ago. I'm going to close this issue for lack of activity. Feel free to comment, if you can confirm this is still an issue, and I'll re-open.
