### ISSUE TITLE
Allow profiles to use local versions of make files

### ISSUE THREAD

**Issue by acouch** [drush-ops/drush#846]
It seems like the convention for profiles/distros is to have a build-MYDISTRO.make file which either includes a drupal.org project name or a link to a git repo.

See: http://cgit.drupalcode.org/panopoly/tree/build-panopoly.make

```
api = 2
core = 7.x

; Drupal
includes[] = drupal-org-core.make

; Panopoly
projects[panopoly][type] = profile
projects[panopoly][version] = 1.11
```

For testing and developer experience purposes it would be great to have an option to link to a local version of the distribution. Otherwise it is always being downloaded twice.

This is especially confusing for people who want to "make" a distribution as they have to clone the distribution repository since there is a link to the local file but are not actually using any of the local code except for the Drupal core version.

Is there a way to do this? If not would it be a heavy lift? Happy to submit a pr.

**Comment by zohar** [comment]
Not sure it's the same thing - please raise a flag if it's not - 

I'm running `drush make build-mydistro.make' and the `drupal-org.make` file that is used is not the local file, but the one fetched from git, so I have to commit and push changes to git in order to test locally, which feels wrong.

Am I doing something wrong or is this the way it works?

**Comment by acouch** [comment]
@zohar That appears to be the way it works. I would like to have a flag that allows you to use a local file. @weitzman I am willing to do the work if you would accept a PR.

**Comment by weitzman** [comment]
@jhedstrom is the one who manages make.

**Comment by jhedstrom** [comment]
For building distros, it should be possible to only use local files via the `includes[]` option. The steps one need go through for developing a distro that is packaged on d.o. unfortunately do require the sort of round-about approach, but if you look at panopoly, the profile *can* be built entirely using local .make files if you are only building the profile (eg, `no-core` option).

**Comment by acouch** [comment]
``For building distros, it should be possible to only use local files via the includes[] option``

I think this is what we are trying to do. Can you explain how that would work? If you have a profile named "local_profile" a make file with a declaration like 

```
projects[local_profile][type] = profile
```

how do you get that to include a local ``drupal-org.make`` file and use the local ``.profile``, ``.install`` files?

**Comment by ergonlogic** [comment]
Do you want to build a new codebase from a makefile, and have it fetch the profile from the local filesystem?

**Comment by discipolo** [comment]
https://www.drupal.org/project/make_local

**Comment by greg-1-anderson** [comment]
Make is in maintenance only; closing.
