### ISSUE TITLE
$GLOBAL['base_url'] set to http://default

### ISSUE THREAD

**Issue by JPustkuchen** [drush-ops/drush#87]
From: https://drupal.org/node/743368

The site URI ($GLOBAL['base_url']) is set to http://default if not further specified with the -l option. Functionality that relies on a properly set base URL fails.

Is this expected?

**Comment by MarcLevy** [comment]
I didn't find any documentation on the -l flag for Drush, and I'm on a multiple-server environment that doesn't lend itself to just altering settings.php or drushrc.php anyway. So my workaround was to make the site URL a required argument of the Drush command. In my case, the command is mostly going to be run by the server's cron anyway, so it doesn't really matter if it's a little long. Even if it did matter, I could probably have coded for a shortcut in the drush_hook_commandname function. But it didn't, and making the site URL a required argument worked exactly right! 

I do think it would behoove the drush maintainers to figure out some cleaner solution that auto-populates the base_url, but I also understand the issues greg-1-anderson mentioned. Thanks.

**Comment by Chi-teck** [comment]
Below is example of _drushrc.php_ file I have used to set _uri_ option for multiple sites.

```php
<?php

$sites = [
  '/var/www/example/' => 'http://example.local',
  '/var/www/foo/' => 'http://localhost/foo',
  '/var/www/bar/' => 'http://localhost/bar',
];

$cwd = drush_cwd();
foreach ($sites as $path => $uri) {
  if (strpos($cwd, $path) === 0) {
    $options['uri'] = $uri;
   // Set drupal context outside docroot.
    if (file_exists($path . '/docroot')) {
      $options['root'] = $path . '/docroot';
    }
  }
}
```
Settings base url in _settings.php_ also works for me. It's also possible to set base url for Drush only.
```php
if (drupal_is_cli()) {
  $base_url = 'http://example.my';  // NO trailing slash!
}
```

**Comment by dineshmanne** [comment]
how you changed base_url from settings.php file. Can you share code. When i tried below code its not replaced with any canonical , og , meta tags. When base_url is set every where it needs to be updated.

$base_url='dev.mywebsite.com';

**Comment by Chi-teck** [comment]
That above code was for Drush 8.

**Comment by dineshmanne** [comment]
any idea on how to set $base_url in drupal 8?
