### ISSUE TITLE
Drush 7 on Drupal 8 *FAILS* site-install if there is a 'hyphen' in the database name

### ISSUE THREAD

**Issue by RogerPf** [drush-ops/drush#888]
'site-install'  using  Drush 7 on Drupal 7   (with hyphen in DB name) generates warning / error and refuses to proceed.   FINE

'site-install'  using  Drush 7 on >>> Drupal 8  <<<  removes hyphen and proceeds to successful completion (creating a DB with the hyphen removed from the name).

EXCEPT that the OLD database name with HYPEN is still stored in the newly created sites/default/ settings.php

THIS IS NOT GOOD :)   FIX - edit that file to remove the hyphen from the DB name and it works.

**Comment by greg-1-anderson** [comment]
Drush 7 eol; use Drush 8 or 9 for Drupal 8.
