### ISSUE TITLE
Are pipes allowed in shell aliases?

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#897]
I know that some shell logical operators are allowed such as `&&`, `||` or `;` in drush shell aliases.
But what about pipes?

I've tried the following examples such as:

```
'test-1' => '!ls | grep foo-',
'test-2' => '!sh -c "ls | grep foo-"',
'test-3' => '!ls|grep foo-',
```

But they all fail:

```
$ drush -v @remote.dev test-1
ls: cannot access |: No such file or directory
Command ls '|' grep foo- failed.
$ drush -v @remote.dev test-2
sh: 0: -c requires an argument
Command sh -c failed.
$ drush -v @remote.dev test-3
bash: ls|grep: command not found
Command 'ls|grep' foo- failed.  
```

Is there any support or workaround to use multiple commands separated by pipe for shell aliases?

**Comment by drzraf** [comment]
I don't think it was really fixed. Pipe are nowhere described in this commit. It just clearly show that alias containing || && and ; and not escaped.
I got this strange result:
`$options['shell-aliases']['xx'] = 'st | grep v';`
then `drush xx` is like apply `grep` on the name containing 'v' but not the value containing 'v'.

But in the end it should be documented that bash-aliases are better fit the need.
