### ISSUE TITLE
Favor a 'parent' from same site alias file.

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#914]
I've the following 3 sample group alias files:

	$ cat test1.aliases.drushrc.php 
	<?php
	$aliases['ssh']['ssh-options'] = '-o PasswordAuthentication=no'; // Define ssh options.
	$aliases['dev'] = array(
	  'remote-host' => 'example.com',
	  'parent' => '@ssh',
	);
	$ cat test2.aliases.drushrc.php 
	<?php
	$aliases['ssh']['ssh-options'] = '-o PasswordAuthentication=no'; // Define ssh options.
	$aliases['dev'] = array(
	  'remote-host' => 'example.com',
	  'parent' => '@ssh',
	);
	$ cat test3.aliases.drushrc.php 
	<?php
	$aliases['dev'] = array(
	  'remote-host' => 'example.com',
	);

I'm using sample `ssh` helper alias to provide common settings for multiple remote hosts defined in group alias file.

The following 2 commands fail, because the command is run locally (twice!) instead on the remote host once:

	$ drush -yv --alias-path=. @test1.dev exec hostname
	Loaded alias @test1.dev from file ./test1.aliases.drushrc.php
	Loaded alias @test1.ssh from file ./test1.aliases.drushrc.php
	Loaded alias @test2.ssh from file ./test2.aliases.drushrc.php // Wrong alias file.
	Calling proc_open(hostname);
	local
	Calling proc_open(hostname);
	local

	$ drush -yv --alias-path=. @test2.dev exec hostname
	Loaded alias @test2.dev from file ./test2.aliases.drushrc.php
	Loaded alias @test1.ssh from file ./test1.aliases.drushrc.php // Wrong alias file.
	Loaded alias @test2.ssh from file ./test2.aliases.drushrc.php
	Calling proc_open(hostname);
	local
	Calling proc_open(hostname);
	local
	Command dispatch complete

Here is sample which works as expected as it's trying to run the command on the remote host (it doesn't load other group alias files which is correct):

	$ drush -yv --alias-path=. @test3.dev exec hostname
	Loaded alias @test3.dev from file ./test3.aliases.drushrc.php
	Calling proc_open(ssh -o PasswordAuthentication=no example.com hostname);

Based on above I think it's a bug, because it seems that drush is loading the wrong group alias file (based on what it's called) generating the conflict for `ssh` alias (e.g. `dev` is defined also in all files and it doesn't create conflicts) and then it's running the commands locally twice, instead of once on the remote host.

You may test the above examples placing them locally in any folder.

**Comment by greg-1-anderson** [comment]
Just closing this per @weitzman
