### ISSUE TITLE
Requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#938]
I've getting the following error when I'm trying to update drush:

```
$ composer global require drush/drush:dev-master
Changed current directory to /Users/user/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for pear/console_table == 1.1.5.0 -> satisfiable by pear/console_table[1.1.5].
    - drush/drush dev-master requires pear/console_table ~1.2.0 -> satisfiable by pear/console_table[1.2.0].
    - drush/drush dev-master requires pear/console_table ~1.2.0 -> satisfiable by pear/console_table[1.2.0].
    - Conclusion: don't install pear/console_table 1.2.0
    - Installation request for drush/drush dev-master -> satisfiable by drush/drush[dev-master].


Installation failed, reverting ./composer.json to its original content.
```

Using `-vvv` doesn't help much, as it's printing the same thing.

Drush Version   :  7.0-dev (OSX)

Any suggestion how to solve that?
It was working some time ago, so not much changed since then.

**Comment by ikvasnica** [comment]
I couldn't remove the global keyword as I need **drush to be installed globally**.

**What worked for me** with updating from Drush 7 to 8:

1. Remove Drush 7 first:
`drush global remove drush/drush`

2. Then, install a new version:
`drush global require drush/drush:8.*`

**Comment by kingAnys** [comment]
worked for me when I:
1) got inside global composer folder (C:\Users\your_name\AppData\Roaming\Composer)
2) edited the composer.json (added to require : "drush/drush" : "8.*" )
3) in cmd: composer global update.

**Comment by falalal** [comment]
![image](https://user-images.githubusercontent.com/43725731/48173341-53e82380-e33e-11e8-9c59-5289b23c523e.png)
how to solve this problem?ask for help.

**Comment by greg-1-anderson** [comment]
Please do not install Drush -- or any other PHP commandline tool -- using `composer global require`. Please use [cgr](https://github.com/consolidation/cgr) instead. See [Fixing the Composer Global command](https://pantheon.io/blog/fixing-composer-global-command).

**Comment by afsara-ben** [comment]
I had the same warning but the problems  were different. I installed the whole **`phpunit`** package and it was solved

**Comment by siemenstutorials** [comment]
php composer.phar install
无法安装如何解决？没有高手知道吗

**Comment by Dilichukwuchukwu** [comment]
![image](https://user-images.githubusercontent.com/57221346/130362675-57ded2e4-fa6d-4de0-812a-6eba9c24785a.png)

Please how do I fix this?
