### ISSUE TITLE
Error on sql-sync: Unable to load class Drush\Sql\Sql

### ISSUE THREAD

**Issue by kenorb** [drush-ops/drush#956]
The following command works fine:

```
$ drush -y @remote sql-dump | drush -v -r dist/src -vy sql-cli
```

But that one generates the error:

```
$ drush -r dist/src -vy sql-sync @remote @self
Array to string conversion environment.inc:643
Starting to create database on Destination.
Unable to load class Drush\Sql\Sql
exception 'Drush\Sql\SqlException' with message 'Unable to find a matching SQL Class. Drush cannot find your database connection details.'
```

This is probably, because I'm using `-r` and relative path?

It works when executing inside the Drupal root, like:

```
drush --alias-path=../../drush -vy sql-sync @remote @self
```
## 

Drush Version   :  7.0-dev

**Comment by musubimedia** [comment]
So I had this error for the second time and brought in my in-house guru to see what I was doing wrong. After investigating for about an hour, he determined that the issue (at least in my case) was that:

1. Drush was getting my db info from the settings.ini file on the remote server, NOT from my www.aliases.drushrc.php file.

2. In my order of operations to set up a new Drupal site on the server, I was running 'drush sql-sync @local.<alias> @www.<alias>' before I ran rsync. What I need to do is:
       a. first run rsync to get the files in the remote directory, then
       b. set up the settings.ini file (which rsync excludes, hence, why drush couldn't find it or the db info) and then
       c. run the sql-sync command.

Now its working....

FYI, here's my www.aliases.drushrc.php setup:

# <alias>.<domain-name>

$aliases['<alias>'] = array (
  'uri' => '<alias>.ws1.<domain-name>',
  'root' => '/var/www/vhosts/ws1/<domain-name>',
  'remote-host' => '<remote-ip-address>',
  'remote-user' => '<login-name>',
  'path-aliases' => 
  array (
    '%drush' => '/usr/bin/drush',
    '%drush-script' => '/usr/bin/drush',
    '%dump-dir' => '/home/<user>/sql-dumps',
    '%files' => '/var/www/vhosts/ws1/<domain-name>/sites/default/files',
  ),
  'databases' => 
  array (
    'default' => 
    array (
      'default' => 
      array (
        'driver' => 'mysql',
        'username' => '<db-user>',
        'password' => '<db-password>',
        'port' => '3306',
        'host' => 'localhost',
        'database' => '<db-name>',
      ),
    ),
  ),
);

**Comment by greg-1-anderson** [comment]
In Drush 6 and earlier, if you included the 'databases' record in your alias file, then sql-sync would not ask the remote server to look up the databases record in settings.php -- it would just use the credentials it already had.

In Drush 7, the implementation of sql-sync was simplified; it now makes a remote call to dump the database using drush sql-sync running on the remote system. (In contrast, Drush 6 used the local sql-dump command to generate the shell commands to execute remotely via ssh.)  This means that there is really no way for Drush to make use of the database info in a site alias, even if it is available; you therefore must set up your code and configure your settings.php file on the remote side before you will be able to run sql-sync.

The documentation on site aliases still shows how to put the databases record into the alias file; however, it does not claim that there is any advantage to doing this, and I can't think of any commands that will use this information.  I think that the site-install command requires a db-url, and cannot think of a way to make use of the 'databases' record in this context either.

Perhaps we should remove this example from the site aliases documentation?

**Comment by weitzman** [comment]
Yes, we now don't ever connect directly to a remote db server like we used to. However, passing databases and db-url on the CLI to sql-sync will work fine (ignore for the moment that its hard to pass an array as an option value). Those options now get handed down to the subcommands. I'm not sure about how options coming from site aliases are handled. I think thats under discussion in #842 - lets talk there.

Depending on the outcome there, we might indeed want to update the example.aliases file.
