### ISSUE TITLE
drush user-create add --notify option

### ISSUE THREAD

**Issue by rtackett** [drush-ops/drush#959]
[This was discussed 3 years ago](https://www.drupal.org/node/1116414#comment-5736360), but I do not see any other tickets related to it.  In the d.o. thread, there is a patch available.  It would really help when users are created via drush and you don't want an email going out.

**Comment by gboudrias** [comment]
I don't get it, is this already in? This is a feature request, not a bug.

**Comment by kenahoo** [comment]
If this isn't already implemented, I request to reopen this ticket. It was discussed here several years ago: https://www.drupal.org/node/1116414 and it seems to have gotten lost in the transition to Github, unless I've missed it somewhere.
