### ISSUE TITLE
Mysql SSL / Certificate Support

### ISSUE THREAD

**Issue by drupalmodule** [drush-ops/drush#965]
What is the proper way to configure drush to use mysql SSL and certificates.  I am able to connect to my database from drupal but not with drush. Drush seems to be omitting the certs.

I have the following database entry in settings.php:
```
$databases = array (
  'default' =>
  array (
    'default' =>
    array (
      'driver' => 'mysql',
      'database' => $database,
      'username' => $dbuser,
      'password' => $dbpasswd,
      'host' => $mysql_server,
      'prefix' => '',
      'pdo' => array(
          PDO::MYSQL_ATTR_SSL_KEY => '/etc/mysql/client-key.pem',
          PDO::MYSQL_ATTR_SSL_CERT => '/etc/mysql/client-cert.pem',
          PDO::MYSQL_ATTR_SSL_CA => '/etc/mysql/server-ca.pem',
          PDO::MYSQL_ATTR_COMPRESS => true,
          ),
      'port' => '3306',
    ),
  ),
);
```
I am using drush 6.4 and drupal 7.31

**Comment by chriscroome** [comment]
I just ran into this issue:

    drush sqlc
    ERROR 1045 (28000): Access denied for user 'user'@'server' (using password: YES)

And one thing just occurred to me -- if Drush is trying to connect over the network without SSL then it is transmitting the MySQL account details unencrypted -- this is a security issue.

**Comment by weitzman** [comment]
I see at http://api.drush.org/api/drush/lib%21Drush%21Sql%21SqlBase.php/function/SqlBase%3A%3Aconnect/master that Drush accepts a global option --extra where you can pass `--ssl-ca=ca-cert.pem --ssl-cert=client-cert.pem --ssl-key=client-key.pem` on any request. When you get tired of doing that, you can save this into a drushrc.pho file and it will be provided automatically. Thats a decent workaround until someone provides a PR for this (by overriding that method with more mysql specific stuff).

**Comment by chriscroome** [comment]
It also seems that `drush` reads users `~/.my.cnf` files, so create one like this:

  [client]
  host=mysql.example.org
  ssl-cipher=DHE-RSA-AES256-SHA
  ssl-ca=/etc/ssl/example/root.pem
  ssl-cert=/etc/ssl/example/certificate.pem
  ssl-key=/etc/ssl/example/yassl_privatekey.pem

And then you can use `drush` via TLS MySQL.

**Comment by colans** [comment]
There's a patch in the original issue over at https://www.drupal.org/node/2009292.  Needs to be reviewed & brought over here.

**Comment by acrollet** [comment]
Adding a note - drush does not recognize --extra as a valid option, but it does work, so you need to add --strict=0

example:

`drush --extra --ssl_ca=/some/path/some_cert.pem --strict=0 uli`

**Comment by acrollet** [comment]
Added a PR that does things properly.

**Comment by acrollet** [comment]
@drupalmodule @chriscroome @colans would appreciate it if any of you are able to test.

**Comment by colans** [comment]
So this should work without the _--strict_ now, correct?

**Comment by weitzman** [comment]
You should not need --extra or --strict

**Comment by acrollet** [comment]
correct, drush now simply parses the PDO ssl options in the site settings.php

**Comment by worthwhileindustries** [comment]
> It also seems that `drush` reads users `~/.my.cnf` files, so create one like this:
> 
> ```
> [client]
> host=mysql.example.org
> ssl-cipher=DHE-RSA-AES256-SHA
> ssl-ca=/etc/ssl/example/root.pem
> ssl-cert=/etc/ssl/example/certificate.pem
> ssl-key=/etc/ssl/example/yassl_privatekey.pem
> ```
> 
> And then you can use `drush` via TLS MySQL.

This doesn't work if you are using multiple databases with separate certs for each

This is the best method I've seen so far tested with drupal 9.x drush 11

`drush '--extra=--ssl-cert=/some/path/some_cert.pem --ssl-key=/some/path/some_key.pem --ssl-ca=/some/path/some_ca.pem --ssl-verify-server-cert=false' --strict=0 some_drush_command --other-options=yadaydada`
