### ISSUE TITLE
--structure-tables with --gzip makes total mess

### ISSUE THREAD

**Issue by OnkelTem** [drush-ops/drush#987]
Sorry for the dumb title, but this is what really happens.
When you start cooking `$exec` variable in `sql.drush.inc` and meet non-empty `$structure-tables`, you run one more mysqldump via `&&`:

```
$exec .= " && mysqldump ..." 
```

and finally pipe the output to a file or stdout, optionally pre-piping through gzip.
Consider this command:

```
$ echo "a" && echo "b" > file
```

What do you expect to see in the `file`? The answer is "b", not "a" _and_ "b", because you pipe only the last command, not both.

The same happens with two subsequent mysqldumps:

```
$ mysqldump1 && mysqldump2 | gzip
```

and on the final output we get:
1. unzipped output from mysqldump1 -- database with data and missed structured tables
2. gzipped output from mysqldump2 -- structure of structured-tables

and all this concatenated. Evil!

Here is a patch: https://gist.github.com/OnkelTem/611c0fd5f08ed4f89e52

Haven't tested it for pgsql, just made modifications by analogy.

**Comment by fuzzy76** [comment]
Ahem, was this carried on to D8? It looks like --gzip and --structure-tables in conjunction returns uncompressed dumps. Removing --structure-tables compresses the dump again.
