### ISSUE TITLE
runserver does not respect mutli-site 

### ISSUE THREAD

**Issue by dustinleblanc** [drush-ops/drush#988]
I generally develop with drush server by starting my server like so:

`$ drush rs --dns site.dev:8888`

but with the latest dev releases of drush 7 I am getting a constant redirect to 127.0.0.1:8888/install.php

I am running mysql and php55 and dnsmasq via homebrew and if I run drush runserver via drush 6 it works (though drush6 at times gives me issues with logging in / access denied).

I have set $base_url in my settings.local.php file (where all other local dev setup is stored) which has fixed similar problems in the past but it is not having an effect here.

**Comment by dustinleblanc** [comment]
FYI, circling back to this, I have solved this by settings $base_url and $cookie_domain on multi-site installs.

**Comment by dustinleblanc** [comment]
Nevermind my report that settings variables fixes it, I forgot this is drush 7 specific. Those solutions solved this for the drush 6 version. I just revisited this today, trying to upgrade to drush 7 on this same site setup.  the -l flag has no effect, since I have setup a site serving out of sites/default I no longer get routed to /install.php but rather the default site. Ill reword the issue to try to be more correct in light of this.

**Comment by dustinleblanc** [comment]
Output from my attempt today:
```
$ drush -v rs                                                                                                                  
Initialized Drupal 7.35 root directory at /Users/dustin/code/php/drupal/site/docroot                                          [notice]
Initialized Drupal site site at sites/site.domain.com                                                               [notice]
Executing: mysql --defaults-extra-file=/private/tmp/drush_tSZUmH --database=correct_db --host=localhost --silent  < /private/tmp/drush_jjbcvk
HTTP server listening on 127.0.0.1, port 8888 (see http://127.0.0.1:8888/), serving site site.domain.com, logged in as admin...
Executing: /usr/local/opt/php56/bin/php -S 127.0.0.1:8888 --define auto_prepend_file="/Users/dustin/.composer/vendor/drush/drush/commands/runserver/runserver-prepend.php"
Calling proc_open(/usr/local/opt/php56/bin/php -S 127.0.0.1:8888 --define auto_prepend_file="/Users/dustin/.composer/vendor/drush/drush/commands/runserver/runserver-prepend.php");
PHP 5.6.8 Development Server started at Thu May  7 13:43:36 2015
Listening on http://127.0.0.1:8888
Document root is /Users/dustin/code/php/drupal/site/docroot
Press Ctrl-C to quit.
```

In other words, it says its serving my multi-site (names changed for privacy) but what actually loads in the browser is `sites/default`. If I revert to Drush 6 this setup works fine but I wanted to try 7 to see if my issues with the server dying would be resolved.

I'd love to start contributing straight to drush itself so if anyone has ideas on where to point me, I'd gladly submit a PR to improve drush.

Thanks!

**Comment by richardbporter** [comment]
Everything works fine for me when setting the `-l` option. Do you have a sites.php entry for your site such that the port prefixes the domain name? Ex. `$sites['8888.localhost'] = 'mysitefolder';`

See https://api.drupal.org/api/drupal/sites%21example.sites.php/7

**Comment by weitzman** [comment]
sites.php mapping is broken for me as well. Lets continue in #339 

Sorry for long delay. I have not needed this feature until today.
