### ISSUE TITLE
Support for completion in the FISH shell

### ISSUE THREAD

**Issue by jurgenhaas** [drush-ops/drush#991]
As I'm happily working with drush in my fish shell (a bash replacement) I was always missing the completion functionality and started to work on it. The result is this simple file:

```
# Drush autocompletion
#
# Place this in your ~/.config/fish/completions/ directory, or in the
# /etc/fish/completions directory to make it available for all users.

function __complete_drush
  drush --early=includes/complete.inc (commandline -cpo) (commandline -t)|cut -d " " -f 1
end

complete -x -c drush -d "Drush" -a "(__complete_drush)"
```

Works like a charm, please feel free to integrate this into the distro.

**Comment by dmsmidt** [comment]
@jurgenhaas love it, thanks!

Any tips on making this work for different Drush versions?
I have: drush6 as aliased binary to an older Drush.

**Comment by jurgenhaas** [comment]
@dmsmidt glad you like it. As for multiple Drush versions, I guess you should use your alias also in this line:

```
complete -x -c drush -d "Drush" -a "(__complete_drush)"
```

and make it something like

```
complete -x -c drush6 -d "Drush" -a "(__complete_drush)"
```

Not sure if you also need to replace the actual function (__complete_drush) with a special one for other drush versions, you may want to give that a try.

**Comment by dmsmidt** [comment]
@jurgenhaas tried that before to no avail, also tried to replace the "drush" in the function.
With which Drush version did you test your script? 7+ ?

**Comment by jurgenhaas** [comment]
@dmsmidt now looking into this it is certainly necessary to change the callback which delivers the autocomplete list. How to get this to work with D6, I had never tested. It works for me on drush 7 and drush 8.

**Comment by dmsmidt** [comment]
@jurgenhaas thanks for reporting back, I tried the callback with D6 and it works.
I guess there is something about symlinks and the "complete" command. I'll report back if I find a solution.

**Comment by frederickjh** [comment]
I am guessing shell completion has not yet been added to Drush 9.
