### ISSUE TITLE
Drush 7 codebase using symlinks can't find Drupal multi-site without using "-l mysite"

### ISSUE THREAD

**Issue by MrHaroldA** [drush-ops/drush#993]
I've installed a Drupal 8 (beta3) site in sites/mysite, but Drush doesn't seem to pick up this installation.

drush sqlc throws an 'Unable to find a matching SQL Class. Drush cannot find your database connection
details.' exeption, and drush st just lists the drush config.

The site itself is running fine.

User error, or something amiss with Drush?

Edit: this also affects Drupal 7 sites.

**Comment by axel-rutz** [comment]
in my setup (drush 7/8, drupal 7) drush seems not to pick up the sites.php:

in sites.php:

    $sites['example.com'] = 'subsite';

then in drupal root

    $ drush sql-connect
    - db credentials of default site -
    $ drush sql-connect -l "subsite"
    - db credentials of subsite -
    $ drush sql-connect -l "http://example.com"
    - db credentials of default site - <= Unexpected!

Downgrading to drush 6 worked around this.

**Comment by weitzman** [comment]
Please reopen if this can be reproduced with current Drupal and master branch of Drush.
