### ISSUE TITLE
Prevent Drush scanning the root directory (follow-up)

### ISSUE THREAD

**Issue by bforchhammer** [drush-ops/drush#996]
The issue described in #885 and #874 is not fixed for me. We still had a deleted module in the cached module list, so `\Drupal::moduleHandler()->getModuleList()` returned an extension with a file path of `/message_ui.info.yml`.

`dirname('/message_ui.info.yml')` produces `/`, which is not empty and therefore still added to the `$searchpath` array in `command.inc#72`.

**Comment by tstoeckler** [comment]
Hit this as well...

I think https://github.com/webflo/drush/commit/eebfcaf6ee31360c84297430d18d06903750776b should be merged into Drush proper. Since we already check for `if ($filename)` anyway, it's not much maintenance overhead.
