### ISSUE TITLE
Drush duplicates the .patch file when applying locally-sourced patches with .make.

### ISSUE THREAD

**Issue by bryanbraun** [drush-ops/drush#999]
I'd like to apply a patch to a library in a .make file. It works great, if I download the patch from a remote location, but if the patch is kept in a local `patches` folder, then the .patch file itself is duplicated. For example:

This applies the patch without side effects:

```
libraries[image2][download][type] = get
libraries[image2][download][url] = http://download.ckeditor.com/image2/releases/image2_4.4.5.zip
libraries[image2][subdir] = "ckeditor/plugins"
libraries[image2][patch][] = https://www.drupal.org/files/issues/make-ckeditor-image2-alt-text-required.patch
```

But this leaves a copy the patchfile in `sites/default/libraries/ckeditor/plugins/image2/my-patch-name.patch`:

```
libraries[image2][download][type] = get
libraries[image2][download][url] = http://download.ckeditor.com/image2/releases/image2_4.4.5.zip
libraries[image2][subdir] = "ckeditor/plugins"
libraries[image2][patch][] = patches/make-ckeditor-image2-alt-text-required.patch
```

This was encountered when using Drush 7.0-dev, while running drush make with the `--concurrency=5` flag.

**Comment by greg-1-anderson** [comment]
Make is maintenance-only; closing.
